### PR TITLE
Add missing commas in pod files

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by kroeckx** [comment]
I'm not sure this are all that are wrong, maybe find-doc-nits can be updated?

**Comment by kroeckx** [comment]
It doesn't apply as is on master, because the files have moved, I'll create an other pull request

**Comment by kroeckx** [comment]
Oh, but cherry-picking does work for it.

**Comment by richsalz** [comment]
cherry-picking works if the files have previously been cherry-picked.  else you have to do it by hand during the cherry-pick.

This diff seems to fine only other missing cases, if you want to include it:
```
; g diff
diff --git a/util/find-doc-nits b/util/find-doc-nits
index 6369880..11acee1 100755
--- a/util/find-doc-nits
+++ b/util/find-doc-nits
@@ -60,7 +60,9 @@ sub name_synopsis()
     my $tmp = $1;
     $tmp =~ tr/\n/ /;
     print "$id trailing comma before - in NAME\n" if $tmp =~ /, *-/;
-    $tmp =~ s/-.*//g;
+    $tmp =~ s/ -.*//g;
+    $tmp =~ s/  */ /g;
+    print "$id missing comma in NAME\n" if $tmp =~ /[^,] /;
     $tmp =~ s/,//g;

     my $dirname = dirname($filename);
```

**Comment by kroeckx** [comment]
It seems 1.0.2 was fine.

**Comment by kroeckx** [comment]
I already merged it. Care to make an other pull request?

**Comment by richsalz** [comment]
Will do

**Pull request closed without merging**
