### PR TITLE
Added OpenSSL GitHub URL to release and pre-release anouncement template

### LINKED ISSUE #13328: Suggestion: include GitHub repo URL in release notification templates.
While I think those of us here know the repo URL by heart and can type it into a `git clone` without even thinking about it, it might be helpful to include the full URL in the release notifications. AFAIK, this includes:

https://github.com/openssl/openssl/blob/ecabd006444d1134d2e4c8475f9abf40c4a38708/dev/release-aux/openssl-announce-pre-release.tmpl#L46
https://github.com/openssl/openssl/blob/ecabd006444d1134d2e4c8475f9abf40c4a38708/dev/release-aux/openssl-announce-release.tmpl#L19

Happy to do the edits here and elsewhere.

### PR DESCRIPTION
**Pull request by rsbeckerca**
Fixes #13328

CLA: Trivial

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

### CODE REVIEW

**Comment by rsbeckerca** [comment]
Added in case this is desired. Not married to the PR but think it might help some parts of the community (See comments in suggestion #13328).

**Comment by mspncp** [comment]
IMHO a general link to the GitHub repository in a (pre-)release announcement is more distracting than helpful. (The same holds by the way for the original note "Of course, the source is also available on GitHub." which it replaces). If any, I would expect a specific link to the signed tag of the release or to zip-file which GitHub can provide automatically, e.g.

- https://github.com/openssl/openssl/tree/openssl-3.0.0-alpha8
- https://github.com/openssl/openssl/archive/openssl-3.0.0-alpha8.zip

However, the tarball is our *official* way of releasing OpenSSL versions and advertising competing ways for downloading the source code does not make sense to me. It is important that people test the official tarballs, because sometimes it can also happen that the tarball contains errors.

**Comment by rsbeckerca** [comment]
@mspncp I appreciate your comments on the official approach. Please allow me to express what some of my community members have expressed.

In a strict regulatory environment (e.g., PCI and SWIFT), the concept of evidence of origin (a.k.a. whodunnit, or the committer) of each change is a crucial requirement to passing an audit of production environments. A tarball simply does not provide a mechanism, short of comparing each file manually, of validating what has been put into production. The overall tarball signature is insufficient. When a git-sourced commit is used in a CI/CD system to build a release, and that release build contents becomes a child commit (the branch where the build products live does not matter), a strict dependency relationship can be established between each object and the commit that built it. git can be then used as a validator to pass an audit of what is currently in production. If a tarball is used, establishing such a dependency is much more difficult and has, in one institution I cannot mention publicly but money was pilfered, resulted in a malicious code injection (don't worry, not OpenSSL). I am working hard to close off this vulnerability for my community. The primary justification for publishing the git URL is to allow the object to source dependency relationship to become immutable and verifiable. This is, perhaps, a philosophical discussion that need not occur here, but is my primary justification for this PR.

**Comment by paulidale** [comment]
Wouldn't a git commit ID provide all the traceability required?  It should be universally unique.

I'm not a fan of including the links either.  https://github.com/openssl/openssl would be more palatable.

**Comment by rsbeckerca** [comment]
> Wouldn't a git commit ID provide all the traceability required?  It should be universally unique.
> 
> I'm not a fan of including the links either.  https://github.com/openssl/openssl would be more palatable.

Strictly, the commit id might be sufficient, if it was GPG signed. But for this use case, the platform is "exotic" so customers might need to build their own. That implies a source (parent commit) object (child commit) relationship in the git Merkel tree.

**Comment by mspncp** [comment]
> Strictly, the commit id might be sufficient, if it was GPG signed.

Uuhm... we do create signed tags for the commit, see e.g. https://github.com/openssl/openssl/releases/tag/openssl-3.0.0-alpha8.

```
msp@msppc:~/src/openssl$ git cat-file -p openssl-3.0.0-alpha8
object 20d7295cb0529882306c370f5dd895f412bbf59b
type commit
tag openssl-3.0.0-alpha8
tagger Matt Caswell <matt@openssl.org> 1604585041 +0000

OpenSSL 3.0.0-alpha8 release tag
-----BEGIN PGP SIGNATURE-----

iQFFBAABCAAvFiEEhlersmDwVrHlGQg52cTSbQ5gRJEFAl+kBlERHG1hdHRAb3Bl
bnNzbC5vcmcACgkQ2cTSbQ5gRJGtywf+MqHkYZ6kOsp+iLyZj24aFr+JY9UbuhRP
aThz2C09MLWhRgvA7Aw7v+b9ptG/YkLNo2yGsh7uz2Lxo/V+Sk33TkzPfvV/Qavn
g09a16t3cUyOVwoNGaRTbZsWRPplK79dCa+Z3mOwrMP8f2j9qn6CQUmiOKcvlFKm
EPTkJG2FZXHAzJP2+B9DtwHQ6CYO87XD6wzUg8dOFUPNR/S2m/QAaO4r3NL4wDMK
P+E9jyMysSblPQm3Ue+EJzqGvHr4GDUqG5RvNKNS9MSbIxXeeiMoLuwoXbPzKW/d
0JNfu2QsJhq2Twm/PtVNJzHIigpvPV7fBjTiRZemin1VfvkahRgbZw==
=pVvG
-----END PGP SIGNATURE-----
```

**Comment by rsbeckerca** [comment]
> > Strictly, the commit id might be sufficient, if it was GPG signed.
> 
> Uuhm... we do create signed tags for the commit, see e.g. https://github.com/openssl/openssl/releases/tag/openssl-3.0.0-alpha8.

Which is good, but the requirement for visibility of EoA is still crucial as is the dependency rrlationship, which is outside any of our control.

**Comment by paulidale** [comment]
How would a link to download the git repository help with the validation checks?
I'm not connecting the dots here.

**Comment by rsbeckerca** [comment]
Assume the reader does not know the git URL.

A `git clone` gives the reader the HEAD commit, or the alpha8 commit. This is used as the basis of a platform build, without modification by the CI/CD system - for NonStop, likely Jenkins. All sources can be verified by git. The build occurs and objects added/committed. The commit~0 is the release commit (could include post `make install content`) PGP signed locally. The commit~1 is the source commit. The release objects are now auditable. The commit is pushed to a private internal upstream repo which can be used as the basis of deployment. A `git status` can verify that all contents of the deployment are legitimate and not modified.

**Comment by paulidale** [comment]
This very much sounds like the _internal_ repo should include the git repo link.  A self reference in the OpenSSL repo seems kind of pointless.  It might satisfy a (crazy?) requirement imposed by a standard but seems kind of pointless otherwise.

**Comment by levitte** [comment]
> The overall tarball signature is insufficient.

I'm not sure I understand this.

-   The announcement itself is signed, and the announcement contains a checksum to verify the tarball contents against.
-   The annotated tag is signed *using the same pgp/gpg key as the announcement email*, and its commit ID is the checksum of that commit, which can be viewed as a checksum for the snapshot of that particular commit, as well as a checksum for the history leading up to it (because of commit ID chain).

The HEAD of any repo doesn't mean anything in this regard, considering added commits after the release has been done.

This has me wonder if we're debating a perception that is different from the technical aspect of this, from an audit point of view.  I'm trying to see this debate from the aspect of *verifiable* source, but it seems that something escapes me.

**Comment by richsalz** [comment]
To express a different view, In my user community and our CI/CD system, we want signed tarballs. They are much more traceable than git commits for us.

**Comment by rsbeckerca** [comment]
Given all that, I'm happy to withdraw the PR.

**Comment by rsbeckerca** [comment]
Just to point out something about this use case. The signature itself is not sufficient for EoA (Evidence of Origin) auditing. The commit history is crucial. Each change made between a prior version installed and the current version installed must be in an auditable position, including who made the change and when. tarball signatures do not provide that richness. For this use case, however, organizations would have to know the upstream git repo anyway, so providing an additional publication of it is not really necessary. They could always ask me ;)

**Comment by mspncp** [comment]
Side note: @mattcaswell @levitte while looking into this ticket, I was surprised to find two different release scripts:

- In the [openssl/tools] repository, there is a [mkrelease.pl] perl script together with a detailed [MKRELEASE.md] documentation.
- Here in the [openssl/openssl] repository, there is a [dev/release.sh] shell script.

By comparing the (slightly different) wordings of the templates

- https://github.com/openssl/tools/blob/e4755452b7bd/release-tools/mkrelease.pl#L299-L312
- https://github.com/openssl/openssl/blob/8016faf15628/dev/release-aux/openssl-announce-pre-release.tmpl#L2-L13

with the official announcement on openssl-announce, and by looking at the Git logs, it is clear that the [dev/release.sh] shell script seems to be the correct release script, even though the other one is much better documented. Is the perl script a leftover or new work-in-progress?


[openssl/tools]: https://github.com/openssl/tools
[openssl/openssl]: https://github.com/openssl/openssl
[mkrelease.pl]: https://github.com/openssl/tools/blob/master/release-tools/mkrelease.pl
[MKRELEASE.md]: https://github.com/openssl/tools/blob/master/release-tools/MKRELEASE.md
[dev/release.sh]: https://github.com/openssl/openssl/blob/master/dev/release.sh

**Comment by mattcaswell** [comment]
> it is clear that the dev/release.sh shell script seems to be the correct release script, even though the other one is much better documented. Is the perl script a leftover or new work-in-progress?

Both scripts are used. Historically the release script has never been part of our main repo and has been maintained separately. The mkrelease.pl script was used for this purpose and is the script that we use for performing 1.1.1 and 1.0.2 releases.

This was slightly problematic because that script performs various updates to the source as part of the release process, e.g. changing version numbers, updating dates in the CHANGES files etc. Since there are changes to how these things work between one release and another the script has to cope with all of them. With 3.0 we made the decision to change things and have a release script specific to an individual release and manage it in the main repo. This is what the dev/release.sh is for.

So the short answer is: mkrelease.pl is for 1.1.1 and 1.0.2, dev/release.sh is for 3.0

**Comment by richsalz** [comment]
I suggest someone add a one-line comment to the two files explaining this.

**Comment by rsbeckerca** [comment]
> 
> 
> I suggest someone add a one-line comment to the two files explaining this.

I can try to come up with something over the weekend.

**Comment by richsalz** [comment]
In mkrelease.pl
```This script is used for 1.1.1; for 3.0 and later see release.sh```
(Deliberately no mention of out-of-support releases)

In release.sh:
```This script is used for 3.0 and later; for previous releases, see mkrelease.pl in the release-tools repo```

**Comment by levitte** [comment]
> In release.sh:
> ```This script is used for 3.0 and later; for previous releases, see mkrelease.pl in the release-tools repo```

... except release.sh is made in such a way that it could be backported to 1.1.1 if that's desirable (no one has expressed such a desire yet, though).  All the version specific functionality is in `dev/release-aux/release-version-fn.sh`; that file has this comment, which points that out:

``` bash
# They are meant to be minimalistic for easy refactoring depending on OpenSSL
# version.
```

**Comment by mspncp** [comment]
The biggest problem IMHO is the fact that the "wrong" script (i.e., the one which is not used anymore on master) is prominently advertised in [MKRELEASE.md](https://github.com/openssl/tools/blob/master/release-tools/MKRELEASE.md).

**Comment by levitte** [comment]
Me, I'm more concerned about the [release-tools README.md](https://github.com/openssl/tools/blob/master/release-tools/README.md), and considering that we're essentially dropping the whole release-tools directory for OpenSSL 3.0, that README.md should be moved elsewhere.  Would adding a suitably edited `dev/RELEASE.md` in the main source's master be good enough?

**Comment by levitte** [comment]
I've a proposed added note in MKRELEASE.md, see openssl/tools#73

**Comment by richsalz** [comment]
> ... except release.sh is made in such a way that it could be backported to 1.1.1 if that's desirable

The suggested comment describes reality, not what could be.  Shrug.  Free advice, you're free to ignore.

**Comment by t8m** [comment]
These files are no longer used when releasing. Closing the PR.

**Pull request closed without merging**
