### PR TITLE
adding a '-crlstart' and a '-crlend' to 'openssl ca'

### PR DESCRIPTION
**Pull request by felixdoerre**
I would like to specify the validity times for the CRLs generated by `openssl ca` exactly, as it is possible for the certificates. I prepared a patch that could be used to implement this feature.

### CODE REVIEW

**Comment by richsalz** [comment]
I'd be inclined to re-use startdate and enddate flags if -gencrl is specified.

**Comment by felixdoerre** [comment]
That was also, what I was thinking in the beginning, but can't ```openssl ca``` be used to create a certificate and the new CRL at the same time? (With e.g. ```ca -in csr -days 100 -gencrl -config conf ...``` ?) That would then cause confusion.

**Comment by richsalz** [comment]
also need to consider timezones (RT2990)

**Comment by t8m** [comment]
Are you still interested in having this feature included in OpenSSL? If so please rebase the PR to resolve conflicts.

Marking as inactive to be closed at the end of 3.4 dev barring further input.

**Comment by richsalz** [comment]
Not comments from anyone on the project for years and now the action is "rebase or we will close."  That's not fair.

**Comment by felixdoerre** [comment]
It looks like this feature was already implemented and merged in #21716. I've just compiled an OpenSSL-binary and tested those commands and they work as expected for me.

**Comment by nhorman** [comment]
ok, thank you

**Pull request closed without merging**
