### PR TITLE
sm2: Allow SM2 dist id to be an optional param

### PR DESCRIPTION
**Pull request by uudiin**
Actually, there is no standard doc which illustrate how to set sm2-id
correctly, only GM/T 0009-2012 gives a fuzzy definition that sm2-id
would be "1234567812345678", and there is no way to get sm2-id from
certificate. In tls handshake, client/server would get a long
certificate chain from peer, we can't find any effective way to
recognize or set sm2-id for each cert.

In practical applications, we can only use the agreed fixed sm2-id
value in signature sign and verify. The 'z' value is inconvenient
in many scenarios because it couples the hash and signature process
together. Therefore, this patch puts the sm2-id as an optional param,
in the case of not specifying the sm2-id, SM2 signature is similar
to other algorithms, just to sign a hash result, and does not involve
how to calculate the hash.

Signed-off-by: Tianjia Zhang <tianjia.zhang@linux.alibaba.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
There should be some test cases in evp_test form for this I think.

**Comment by InfoHunter** [comment]
This is not inconsistent with older versions, so I think this should not go into branch-3.1. Should be master only.

**Comment by InfoHunter** [comment]
That is to say, when someone creates/verifies an SM2 signature and dist-id is not set:
* 3.1 and older versions will stay in consistency(Z is computed);
* 3.2 and later will not be compatible with older versions (Z is not computed anymore).

**Comment by t8m** [comment]
> That is to say, when someone creates/verifies an SM2 signature and dist-id is not set:
> 
>     * 3.1 and older versions will stay in consistency(Z is computed);
> 
>     * 3.2 and later will not be compatible with older versions (Z is not computed anymore).

Hmm, that makes this patch unsuitable for master branch even...

**Comment by t8m** [comment]
The default behavior has to be compatible with 3.0 release. I suggest adding a new param to disable computing the Z value.

**Comment by InfoHunter** [comment]
> I suggest adding a new param to disable computing the Z value.

Right, make it tweak-able.

**Pull request closed without merging**
