### PR TITLE
enc(1): document that AEAD is not and will not be supported

### LINKED ISSUE #471: AEAD support in enc app
Is there any particiular reason, why AEAD ciphers are not supported in the enc app? https://github.com/openssl/openssl/blob/master/apps/enc.c#L298

I have implemented as a small part of my thesis, maybe I could polish it and submit a PR.

### PR DESCRIPTION
**Pull request by kaduk**
Recommend the use of cms(1) instead.

Fixes #471.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by dot-asm** [comment]
As already hinted, the problem arguably stretches beyond just AEAD. I mean there are other modes that are as foot-shooting-prone for handling data at rest (or even piping) with enc. A possible way to handle it is to stop offering support for encryption, but keep for decryption.

**Comment by richsalz** [comment]
Also, this does not fix the issue, since CMS adds a wrapper datastructure unlike the enc apps.  So make sure that when this is merged, that you do not close #471

**Comment by kaduk** [comment]
Isn't the whole point of this change so that #471 will get closed WONTFIX?

**Comment by richsalz** [comment]
No.  A version that only supported AEAD to/from files would be useful.

**Comment by kroeckx** [comment]
I would like to bring up our new policy that's under discussion. CMS is a standard, what enc does not. You could argue we should deprecate enc in favor of CMS.

**Comment by kaduk** [comment]
Perhaps this discussion should move back to #471.
In light of Rich's comment, I'm tempted to make an issue for "revisit file-encryption capabilities in apps/", since we seem to not fully agree on what functionality is desired in an ideal future (and how to get there).  IIRC there had been previous discussion about how the enc(1) format/header leaves much to be desired, and a "version 2" that had a better header with version field/etc. could also provide authenticated encryption in some form, could potentially provide a chunked "not-quite-streaming" usage of AEAD that limits the amount of unverified data that could be exposed to a consuming pipeline (but still at risk of truncation attacks), etc.

**Comment by kroeckx** [comment]
What functionality do you think is missing in the cms app?

**Comment by dot-asm** [comment]
> A version that only supported AEAD to/from files would be useful.

Once again, the problem actually runs deeper than AEAD and "streaming", and having a separate utility that supports enc-style AEAD does not solve it. In other words such utility would be as inappropriate as enc even if it takes "streaming" out of picture. For reference, "enc-style" means that user specifies per-file [symmetric] key and iv. cms solves it, and I see no point providing alternative in enc. Of course cms relies on PKI, which can be considered excessive by some. enc has to stick around for backward compatibility, but one can wonder if it would be appropriate to ban some modes available for encryption. This doesn't mean that enc can't be improved with updated header (or even support for xts?)...

**Comment by kaduk** [comment]
It feels like we are not even at the point of disagreeing about the implementation details of a utility, but rather we are disagreeing about what functionality is desired from a file-encryption utility (whether named enc(1), cms(1), aead(1), or something else).
Maybe @dot-asm and @richsalz could write up a description of what they think is useful/what they want to say, so we could compare and try to reach a consensus?  (And maybe there is a better venue than this pull request, but I don't have one particularly handy.)

**Comment by richsalz** [comment]
I think enc should support AEAD with limitations on input/output.

**Comment by dot-asm** [comment]
I feel that I expressed myself clear enough, but all right. Adding AEAD support to command line, be it `enc` or new utility. -1. Rationale is that since most [at least most popular, if not all] AEAD ciphers fail catastrophically in case key and iv are reused, user should not be trusted with their, key and iv, management. This has actually lesser to do with "streaming" to EVP. And for this reason rationale applies even to some of the non-AEAD modes currently supported by `enc`, most notably counter modes and RC4. This inevitably asks for following questions.

1. Should we add some kind of key-iv management to `enc`? I argue no, `cms` already does it, it's more than appropriate to use that instead. [This aligns perfectly with this merge request.]
2. Should `enc` be removed? No, we can't do that for backward compatibility reasons.
3. Should we do *anything* about `enc`? One can argue that it wouldn't be inappropriate [now or at some later point] to ban some modes from specifically `enc -e` [but leave `enc -d` alone as people are entitled to decipher old data].

And on strongly relate note, since AEAD questions customarily are about AES-GCM, one can argue that `cms` should be extended to adopt RFC5084.

**Comment by kaduk** [comment]
Sorry, @richsalz , that still leaves me with questions.  You want a utility that can do bulk-encryption with arbitrary-sized in/output when using CBC mode but limitations when using GCM?  Users are still responsible for key/password/iv management?

**Comment by richsalz** [comment]
@kaduk: yes.  But I don't feel strongly about it.  IF we want to not support this at all, I am also okay with that.  Just need to document it, as you've suggested.

**Comment by richsalz** [comment]
Re-reading @dot-asm's post https://github.com/openssl/openssl/pull/5048#issuecomment-357317862  I agree with him.

**Comment by zakjan** [comment]
I found enc utility very useful for testing correctness of new ciphers / validating existing ones. Then user-controlled key/IV is necessary. PR #5026 is updated to fail when authentication fails.

Not sure about real usage of enc to encrypt/decrypt files, is it recommended at all?

**Comment by dot-asm** [comment]
Enough time passed for anybody to chime in, no new opinions... I'm approving...

**Comment by dot-asm** [comment]
> Approving...

Though on second reading I wonder if one should even emphasize key/iv thing, i.e. lack of their management. As already said "streaming" is not the only reason for why it's inadequate idea...

**Comment by kaduk** [comment]
Added some text about key/iv/nonce management.  I plan to squash it for the final commit, as there does not seem to be reason to have separate commits.

**Comment by kaduk** [comment]
Maybe I have not been following OMC membership changes closely enough, but I think this only has 3 committers and 0 OMC approvals.

**Comment by richsalz** [comment]
You're right.  Since I said I agree with Andy, +1

**Comment by kaduk** [comment]
Pushed; thanks for all the review!
(closing)

**Comment by osresearch** [comment]
This change seems to fall short of actually helping the users: how are you supposed to use `cms` for GCM operations? Pointing people to it without a suggestion of how to actually use it for this task only leads to frustration -- `cms` does not appear to have any options that make sense for AES-GCM decryption given an ciphertext message, tag, nonce and key, while `enc` *does* take these sorts of things as arguments.

**Pull request closed without merging**
