### PR TITLE
verify fails on AKID with authorityCertIssuer #13223

### LINKED ISSUE #13223: verify fails on AKID with authorityCertIssuer
X509_check_akid checks the correctness of keyIdentifier, authorityCertSerialNumber and authorityCertIssuer
When checking authorityCertIssuer the issuer-name of the client-certificate is checked against the _issuer-name_ of the issuer-certificate:

crypto/x509/v3_purp.c
        if (nm != NULL && X509_NAME_cmp(nm, X509_get_issuer_name(issuer)) != 0)

This check will only work for Root-CA signed certificates and for intermediate CA w/o authorityCertIssuer element in AKID.

correct check must use subject name:
        if (nm != NULL && X509_NAME_cmp(nm, X509_get_**subject**_name(issuer)) != 0)

verify invocation  with intermediate CA and authorityCertIssuer failing:
```
openssl verify -verbose -show_chain -no-CAfile -no-CApath -CAfile /tmp/chain.cer /tmp/client.cer 
serialNumber = 71928, CN = TEST-ELGA-u0x27vo, O = TEST-ELGA, OU = TEST-ELGA-EB12, C = AT
error 20 at 0 depth lookup: unable to get local issuer certificate
error /tmp/client.cer: verification failed
```
verify invocation with corrected check using same certificates:
```
./apps/openssl verify -verbose -show_chain -no-CAfile -no-CApath -no-CAstore -CAfile /tmp/chain.cer /tmp/client.cer 
/tmp/client.cer: OK
Chain:
depth=0: serialNumber = 71928, CN = TEST-ELGA-u0x27vo, O = TEST-ELGA, OU = TEST-ELGA-EB12, C = AT (untrusted)
depth=1: serialNumber = 71560, CN = TEST-ELGA-EB12-GDACA-04, OU = TEST-ELGA-EB12, O = TEST-ELGA, C = AT
depth=2: serialNumber = 6, CN = TEST-ELGA-EB12-StammCA-04, OU = TEST-ELGA-EB12, O = TEST-ELGA, C = AT
```

[chain_and_client_certs.zip](https://github.com/openssl/openssl/files/5425747/chain_and_client_certs.zip)

### PR DESCRIPTION
**Pull request by shadogray**
Fixes #13223
Check the identity of client certificate's AKID authorityCertIssuer with issuer certificate's _subject_ name
sorry for not providing a test :-/

##### Checklist

- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
This is incorrect change, the code we have is correct.

**Comment by t8m** [comment]
Please see the reasoning in the issue #13223

**Comment by shadogray** [comment]
Thank you for the information, I now understand the naming in the RFC.
I apollogize for the misunderstanding and the bad fix.
Regards,
Thomas


Tomáš Mráz <notifications@github.com> schrieb am Fr., 23. Okt. 2020, 13:05:

**Comment by t8m** [comment]
No need to apologize for such inadvertent mistake.

**Pull request closed without merging**
