### PR TITLE
Type casting (remove warning)

### PR DESCRIPTION
**Pull request by Kochise**
CLA:trivial
Trivial modification, one liner, type casting
Related to pull-request #10231 that have no CLA

### CODE REVIEW

**Comment by Kochise** [comment]
Your "Contributor License Agreement" stills not show how to properly perform a "trivial" commit. With the expected syntax.

**Comment by mattcaswell** [comment]
> Your "Contributor License Agreement" stills not show how to properly perform a "trivial" commit. With the expected syntax.

Please amend the commit so that "CLA: trivial" has a space after ":" and has a blank line before it.

**Comment by Kochise** [comment]
Thanks for the help.
Please update https://www.openssl.org/policies/cla.html as well.

**Comment by t8m** [comment]
PR for that done in https://github.com/openssl/web/pull/171

**Comment by Kochise** [comment]
Closing #10231

**Comment by t8m** [comment]
Merged to master and 1.1.1. Thank you.

**Pull request closed without merging**
