### PR TITLE
Remove duplicate see also reference to BIO_s_mem.

### PR DESCRIPTION
**Pull request by paulidale**
- [x] documentation is added or updated

Documentation fix only.

Please don't merge this, I'd like it to be a benign test of my merge capabilities after approval.

### CODE REVIEW

**Comment by paulidale** [comment]
alpha

**Comment by levitte** [comment]
(errrr...  "alpha"?)

**Comment by paulidale** [comment]
Alpha is a beginning.
Omega is the end.

**Comment by levitte** [comment]
That was kind Revealing ;-)

**Pull request closed without merging**
