### PR TITLE
Update alert to common protocol

### LINKED ISSUE #7953: Confuse description in SSL_str_reasons
The common error description in SSL and  TLS  was defined begin with sslv3, and SSL3.0 was disable default from the security consider, and the string reason that begin with sslv3 will confuse that sslv3 was still used.

Example:
sslv3 alert bad certificate

Will it better that update to begin with SSL/TLS or remove the sslv3?

### PR DESCRIPTION
**Pull request by KanPlus**
Fixes #7953

### CODE REVIEW

**Comment by KanPlus** [comment]
Please help review,thanks @paulidale

**Comment by KanPlus** [comment]
@paulidale This MR matched #15864 with the base updated ,Hope could be reviewed,thanks.

**Review by paulidale — APPROVED** [review]

**Review by DDvO — APPROVED** [review]
Nice changes.
Sorry that final approval took rather long.

**Comment by DDvO** [comment]
Merged - thanks @KanPlus for this contribution, @paulidale for the other approval,
and also @richsalz and @levitte for the discussion on #7953.

**Comment by KanPlus** [comment]
> Merged - thanks @KanPlus for this contribution, @paulidale for the other approval, and also @richsalz and @levitte for the discussion on #7953.

This confused me for long time, thanks for the discussion and the review.

**Comment by KanPlus** [comment]
> Nice changes. Sorry that final approval took rather long.

Thank you.

**Pull request closed without merging**
