### PR TITLE
p5_scrypt.c: fix error check of RAND_bytes() call

### PR DESCRIPTION
**Pull request by mspncp**

### CODE REVIEW

**Comment by mspncp** [comment]
Can anyone explain this test failure to me? (see https://travis-ci.org/openssl/openssl/jobs/367508858)

```
Test Summary Report

-------------------

../../_srcdist/test/recipes/70-test_key_share.t              (Wstat: 15360 Tests: 21 Failed: 0)

  Non-zero exit status: 60

  Parse errors: Bad plan.  You planned 22 tests but ran 21.

Files=146, Tests=1336, 201 wallclock secs ( 5.35 usr  1.48 sys + 76.70 cusr 23.44 csys = 106.97 CPU)

Result: FAIL

make[1]: *** [_tests] Error 1
```

**Comment by levitte** [comment]
Yup

```
ok 21 - Ignore key_share for TLS<=1.2 server

Server command: ../../util/shlib_wrap.sh ../../apps/openssl s_server -max_protocol TLSv1.3 -no_comp -rev -engine ossltest -accept [::1]:0 -cert ../../../_srcdist/apps/server.pem -cert2 ../../../_srcdist/apps/server.pem -naccept 1 -cipher AES128-SHA -ciphersuites TLS_AES_128_GCM_SHA256 -curves X25519

engine "ossltest" set.

Using default temp DH parameters

ACCEPT [::1]:52821

Server responds on [::1]:52821

unable to connect: Operation timed out

# Looks like you planned 22 tests but ran 21.

# Looks like your test exited with 60 just after 21.

Dubious, test returned 60 (wstat 15360, 0x3c00)

Failed 1/22 subtests 

```

**Comment by levitte** [comment]
We do have that issue going on a little now and then.  @dot-asm  and @bernd-edlinger seem to be working on it

**Comment by mspncp** [comment]
The patch applies cleanly to 1.1.0. Branch 1.0.2 does not seem to be affected.

**Comment by mspncp** [comment]
Merged!

e62fb0d31bdf25854aa2c7cda8e1d03768984ab4 master
69712507e73437553790ccac6f19a9ded996c0cd 1.1.0

**Pull request closed without merging**
