### PR TITLE
Update fuzz corpora

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by ekasper** [comment]
In the commit message, could you describe what the update does? Is it a new min-corpus? With better coverage? Does the corpus size grow? (The latter is relevant because we run the corpus as a unit test.)

**Comment by kroeckx** [comment]
I'll update the commit message, but it's always a min corpus with more coverage.  coveralls even shows that we have 0.5% more coverage in the test suite with it.  The asn1 corpus has the biggest change with 474 more files, but it also didn't get updated since the tests it does changed.

I'll try to come up with more details later this evening.

**Comment by ekasper** [comment]
+1, just add that info to the commit message. We need to keep an eye on Travis so we don't choke it but for now seems fine.

**Comment by ekasper** [comment]
Also, +0.5% is pretty sweet!

**Comment by kroeckx** [comment]
I thought I already added an x509 corpus, but it seems I didn't for some reason ...

**Comment by kroeckx** [comment]
So I pushed a new commit with some stats.  Note that all of the ways afl instruments the binary involves random numbers per .o file which results in the tuple count being non-deterministic.

**Comment by kroeckx** [comment]
@ekasper: So you're still happy with this?

**Comment by kroeckx** [comment]
@ekasper: ping

**Comment by levitte** [comment]
+1

**Comment by ekasper** [comment]
Yes, still +1

**Comment by mattcaswell** [comment]
Merged.

**Pull request closed without merging**
