### PR TITLE
Treat C++ flags more like C flags, and only if C++ compiler specified

### PR DESCRIPTION
**Pull request by levitte**
C++ flags got the same config target value as C flags, but then
nothing else happened while C flags get all kinds of stuff added to
them (especially when --strict-warnings is used).

Now, C++ flags get the exact same treatment as C flags.  However, this
only happens when a C++ compiler is specified, to avoid confusing
messages about added C++ flags.

### CODE REVIEW

**Comment by levitte** [comment]
Incidently, this uncovered a case of unchecked returned status in our C++ code.  The correction is also part of this PR.

**Review by richsalz — APPROVED** [review]
The mips2/3 stuff seems unrelated, but okay.

**Comment by levitte** [comment]
The mips2/3 stuff is just recoding to get it into cxxflags as well as cflags without computing twice, that makes it related.  The mips2/3 stuff itself is otherwise functionally unchanged

**Comment by levitte** [comment]
Merged.  fa153b57a30154b828cabdfb079f832a96eeb2e1 and 0f5a77521961117df53256651ae7bca6dd8b54a2

**Pull request closed without merging**
