### PR TITLE
Use templated doc stuff

### PR DESCRIPTION
**Pull request by richsalz**
Use template stuff for common (refactored) options.

The build stuff is getting kinda heavyweight, ping @levitte for thoughts.

(that ```-i.in doc/man/*.in``` option looks kinda nice now :)

### CODE REVIEW

**Comment by richsalz** [comment]
This depends on #10159 , so only the top commit is worth looking at now.

**Comment by richsalz** [comment]
No longer in WIP, ready for review.  Requires #10159

**Comment by levitte** [comment]
Did you mean to say "ping" here?

**Comment by richsalz** [comment]
no, this get merged into #10159.  I didn't really intend to do that, call it 'distracted rebasing' but there ya go.  I can give a rationale for that saying "it's not just infrastructure, it also shows it being used" but that's really covering up my good.  So this is closed and #10159 is the one to review.

**Pull request closed without merging**
