### PR TITLE
Fix solaris build in CRYPTO_atomic_store api

### PR DESCRIPTION
**Pull request by nhorman**
Misnamed variable, just correct it to dst

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by shahsb — APPROVED** [review]

**Review by andrewkdinh — APPROVED** [review]

**Review by Sashan — APPROVED** [review]
looks good to me.

**Review by mattcaswell — APPROVED** [review]
How has this not been spotted until now!!?

**Comment by nhorman** [comment]
> How has this not been spotted until now!!?

guessing Not many people use solaris 5.10 or 5.11 with the latest openssl

**Comment by t8m** [comment]
Merged to the master and 3.4 branches. Thank you.

**Pull request closed without merging**
