### PR TITLE
[master] Fix regression in evptests.txt

### PR DESCRIPTION
**Pull request by romen**
(a port to master of #3222 )

When compiling without EC support the test fails abruptly parsing some keys.

Some keys pulled in #3187  start with
------BEGIN EC PRIVATE KEY-----

this format is not supported without EC support.

This commit reformat those keys with the generic format. After this change the
test simply skips the unsupported EC keys when EC is disabled, without parsing
errors.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by romen** [comment]
@levitte the port of #3222

**Comment by dot-asm** [comment]
Is it actually so that it's impossible to cherry-pick it to 1.1.0?

**Comment by romen** [comment]
@dot-asm that's what #3222 is for: cherry-pick wasn't able to automatically merge the changes because of different edits to evptests.txt in the two branches!

**Comment by romen** [comment]
Check this comment: https://github.com/openssl/openssl/pull/3222#issuecomment-294134456

**Comment by richsalz** [comment]
thanks!

**Comment by romen** [comment]
As a follow up to latest comment, #3226 is the pull request fixing the issue mentioned in https://github.com/openssl/openssl/pull/3222#issuecomment-294134456

**Pull request closed without merging**
