### PR TITLE
Dtls listen refactor

### PR DESCRIPTION
**Pull request by mcr**
- [x ] documentation is added or updated
- [x] tests are added or updated

This is repeated in an email to the -dev list

This patch refactors the DTLSv1_listen() to create an alternative API that is called DTLSv1_accept().
DTLSv1_accept() is useable by programs that need to treat DTLS interfaces in a way similar to TCP: new connections must be accepted, and new sockets created.
There are a number of changes included here:

1. dgram_write() and dgram_read() now use sendmsg(2) and recvmsg(2) in order to set and collect the local address used in the datagram.  This allows a socket to bound to ::, while still sending traffic correctly from the address that the other peer used. The IPv6 version of this code is according to rfc3542 API, but the IPv4 of the code is Linux specific and needs to be either abstracted and translated for *BSD and Windows, or IPv6 mapped IPv4 sockets could be used.
2. a new BIO control SET_ADDR and GET_ADDR are added, and if the address is not set then it pulls it out of the socket using getsockname(2).
3. DTLSv1_accept() accepts a second SSL* on which new connections are setup. A new socket is set up using the addresses from the received message and it is inserted into the BIO. There is a race condition during setup which turned out to be unavoidable: between the bind(2) and the connect(2), the new socket could have the same address as the "listen" socket, and additional hello packets could arrive on the wrong socket.  Such packets will hopefully be dropped as garbage. It was thought that connect(2) could be called before bind(2), but that seems to cause the kernel to allocate a local address for the new socket (a random port), which the subsequent bind(2) can not seem to change.
4. the use of POSIX socket APIs inside this code is likely inappropriate and this routine should be split up in some better way so that socket activities can be done by the application, using the correct abstractions for the OS.
5. a new test case dtlsaccepttest was created.  It uses fork() and also calls system() on "openssl s_client". Probably it should just call code internally, but apps/* is not in a library form that can be used. Perhaps this use is acceptable.  Other test functions just use canned packets in/out, but since this is testing the creation/adaption of socket code, real sockets would seem to be necessary.  Probably this test case should be disabled on non-Unix platforms.
6. routines BIO_ADDR_sockaddr and BIO_ADDR_sockaddr_size exposed from libcrypto to libssl.  There might be a better way to do this, perhaps a BIO_CTRL would be better?

### CODE REVIEW

**Comment by mattcaswell** [comment]
I am unclear about the underlying premise of this PR:

> This patch refactors the DTLSv1_listen() to create an alternative API that is called DTLSv1_accept().
DTLSv1_accept() is useable by programs that need to treat DTLS interfaces in a way similar to TCP: new connections must be accepted, and new sockets created.

Your going to give more justification than this. Why is it that DTLSv1_listen() is not appropriate for your use case?

In any case the PR as it currently stands is a very long way off being acceptable:

- As you point out the use of the POSIX socket APIs is unacceptable and is at the wrong level of abstraction. I might perhaps expect to see this sort of thing in the BIO layer.
- The code does not seem to be portable - it needs to work on all our platforms
- There is no documentation

I noticed a number of other things at a more specific level, just scanning through the code, but at this point I have not reviewed it in detail. I am not yet convinced there is a need for this.

**Comment by mcr** [comment]
DTLSv1_listen() has a number of race conditions if traffic arrives from multiple clients at the same time. Could we discuss this on the openssl-dev list rather than github?

**Comment by mattcaswell** [comment]
Sure

**Comment by mcr** [comment]
discussion moved to: https://mta.openssl.org/pipermail/openssl-dev/2018-January/009942.html

**Comment by richardweinberger** [comment]
Michael,

instead of adding a new "look like TCP" API for handling new connections. Wouldn't it be better to just fix the regression in DTLSv1_listen()? That way existing applications that work fine on 1.0.x can continue working on 1.1.x without much hassle.

Thanks,
//richard

**Comment by t8m** [comment]
I believe this should be eventually replaced with the work on SSL listener objects. Closing.

**Pull request closed without merging**
