### PR TITLE
Fix undocumented option, cleanup about magic values in app/ca

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
While looking at my changes in #1422 , I start dig about undocumented OPT_VALID ...
The result is these changes ;)

### CODE REVIEW

**Comment by richsalz** [comment]
This is a lot more than just adding a help string.  I think @mattcaswell would say post-1.1.0 to all those other things.

**Comment by FdaSilvaYY** [comment]
As you wish... I can split this to a simple string addition, if needed.
I should add an an entry to docs/ca.pod too.

**Comment by richsalz** [comment]
Up to @mattcaswell to decide.  Looks fine for 1.1.0 to me.

**Comment by mattcaswell** [comment]
The option string and doc updates would be fine for 1.1.0. Everything else is too big a change for 1.1.0.

**Comment by FdaSilvaYY** [comment]
Please see PR #1442 .

**Pull request closed without merging**
