### PR TITLE
changes opensssl typos to openssl (extra "s") in documentation

### PR DESCRIPTION
**Pull request by samueleaton**
##### Checklist
- [x] documentation is added or updated

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
nice, while you are already there, how about fixing those as well?
crypto/evp/pmeth_gn.c:     * Asssigning gentmp to ctx->keygen_info is something our legacy
doc/internal/man3/ossl_method_construct.pod:for ensuring the necesssary data is made available.
doc/man3/OSSL_HTTP_REQ_CTX.pod:OSSL_HTTP_REQ_CTX_nbio_d2i() is like OSSL_HTTP_REQ_CTX_nbio() but on successs

**Comment by bernd-edlinger** [comment]
and of course also:
providers/implementations/kdfs/x942kdf.c:     * start of the alllocated buffer at this point.
apps/include/http_server.h: * keep_alive: grant persistent connnection

**Comment by samueleaton** [comment]
@bernd-edlinger happy to make more doc fixes, but I'm not understanding the issues you are describing at those files.

**Comment by bernd-edlinger** [comment]
It just appeared logical to me to look for similar typos,
and grepped for things like triple-sss and triple-nnn or triple-lll since those don't normally appear in english words.
so I'd change alllocated to allocated and connnection to connection, Asssigning to Assigning,
necesssary to necessary and successs to success.

**Comment by samueleaton** [comment]
oh wow those were so subtle that i didn't even see them in your comment, thus my confusion. yes will fix.

**Review by paulidale — APPROVED** [review]
Nice finds.  This would be considered trivial changes I think.  If you agree, could you add a line containing only `CLA:trivial` to the initial commit message (use git amend) or submit a CLA.

**Review by slontis — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to both branches.  Thanks for the fixes.

**Pull request closed without merging**
