### PR TITLE
Fix serialization selection flags

### PR DESCRIPTION
**Pull request by slontis**
Extra tests that cover these cases should be done by #12694

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
ping - this one is fairly important - since you cannot serialize keys in the fips provider without these changes.

**Comment by slontis** [comment]
ping

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
I'm working on merging all the different encoders into one code path.  The varying parameter selectors will make life...  interesting.

**Comment by levitte** [comment]
Hmmm, I'm curious as to why `test_evp_pkey_provided` doesn't fail, 'cause this:

https://github.com/openssl/openssl/blob/bddfea0271d0596961a43283b36ff49923329a92/test/recipes/30-test_evp_pkey_provided/DSA.pub.txt#L1

**Comment by slontis** [comment]
> Hmmm, I'm curious as to why test_evp_pkey_provided doesn't fail, 'cause this:

I assume because it is not doing the export/import in this case.. i.e- they are in the same libctx so it doesnt do the bad stuff.

**Comment by slontis** [comment]
Thanks. Merged to master

**Pull request closed without merging**
