### PR TITLE
Bring FIPS dev branch up to date with 2.0.15

### PR DESCRIPTION
**Pull request by snhenson**
This PR includes all the changes between the FIPS module versions 2.0.14 and 2.0.15. They are not currently in the OpenSSL-fips_2_0-dev branch. This is all written by @dot-asm.

The first two commits are two internal PRs that were never merged.

The second two commits are the differences between the PRs and the actual tarball. I've done it that way so the differences are clear: I've set the author to @dot-asm because I didn't write that I just worked out the diffs and added them to a separate commit.

When this is approved I'll squash the difference commits (so only two remain) and delete the log message line saying "replace c6x/env...".

Note: this is already in a validated tarball so while the log messages can change the actual diffs can not.

Once this is sorted out I'll cherry pick these into the stable branch and tag it as 2.0.15 (after double checking it precisely matches the tarball).

### CODE REVIEW

**Comment by snhenson** [comment]
Taken out of WIP as the contents of this PR cannot change: just the commit log messages.

**Comment by snhenson** [comment]
Q: sometimes c6x is used and sometimes c64x. Is there a difference or should they all be the same and if so which one?

**Comment by dot-asm** [comment]
> c6x is used and sometimes c64x

And you can also spot c64xplus. Relation between c6x, c64x and c64xplus is similar to say armv4, armv5, armv6, etc. In other words c6x is a reference to a "base" instruction set for a range of specific processors, c64x is instruction set extension on top of c6x, and c64xplus is instruction set extension on top of c64x. This means that c64xplus-capable processor can execute c64x, as well as c6x binary code, but not vice versa.

**Comment by snhenson** [comment]
Update: force pushed with the original internal PRs (and corresponding log messages) and the differences between them and the official tarball.

**Comment by snhenson** [comment]
Ping anyone? BTW this will partly address #4027. If it will help I can squash and force push the two "difference" commits.

**Comment by snhenson** [comment]
Pushed and tagged, thanks everyone.

**Pull request closed without merging**
