### PR TITLE
WIP extended tests diagnostics

### PR DESCRIPTION
**Pull request by kaduk**
Nothing to see here, just getting a clean baseline on what the extended tests look like on master without any code changes.

### CODE REVIEW

**Comment by kaduk** [comment]
Of course, the S390x build, which is the one I was most interested in, is the one that got cancelled.

**Comment by mspncp** [comment]
> Of course, the S390x build, which is the one I was most interested in, is the one that got cancelled.

There seems to be some persistent problem with the S390x build, see also https://github.com/openssl/openssl/issues/12616#issuecomment-671162051 and ff.

**Comment by kaduk** [comment]
> > Of course, the S390x build, which is the one I was most interested in, is the one that got cancelled.
> 
> There seems to be some persistent problem with the S390x build, see also [#12616 (comment)](https://github.com/openssl/openssl/issues/12616#issuecomment-671162051) and ff.

Thanks for the reminder.  I specifically want a current baseline for S390x since my changes at #12233 touch some S390x-specific code and it's hard to be sure whether the Travis-reported failures are due to my changes or not.

**Comment by t8m** [comment]
Extended tests were Travis CI thing which is obsolete. Closing.

**Pull request closed without merging**
