### PR TITLE
speed.c: Check block size before running EVP_Cipher_loop()

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Comment by t8m** [comment]
The test commit to be applied only to the master and 3.4 branches.

**Comment by paulidale** [comment]
Is there a good reason for not wanting to test this on earlier versions?

I can't think of one.  More so since they are stable releases.  Even more so since 3.0 is LTS.

**Review by tom-cosgrove-arm — APPROVED** [review]

**Comment by t8m** [comment]
> Is there a good reason for not wanting to test this on earlier versions?
> 
> I can't think of one. More so since they are stable releases. Even more so since 3.0 is LTS.

There is no speed test there and it requires adding the testmode option. So this is a very good reason IMO.

**Review by Sashan — APPROVED** [review]
makes sense.

**Review by shahsb — APPROVED** [review]

**Comment by tmshort** [comment]
@t8m, merged to `master` and `openssl-3.4`. I was unable to merge to `openssl-3.3` due to a non-trivial conflict (i.e. `test/recipes/20-test_speed.t` doesn't exist).

**Comment by t8m** [comment]
Only the fix without the test was supposed to be merged to older branches. I've cherry picked the fix to 3.3 and 3.2 branches. The fix does not cherry-pick cleanly to older branches.

**Pull request closed without merging**
