### PR TITLE
doc: Fix typo in EVP_EncryptInit.pod

### PR DESCRIPTION
**Pull request by samuel-lee-msft**
CLA: trivial

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
agreed trivial

**Review by slontis — APPROVED** [review]
Agree that it is trivial

**Comment by tmshort** [comment]
CI tests are now passing.

**Comment by tmshort** [comment]
Pushed to master, openssl-3.1 and openssl-3.0. Thank you for your contribution!

**Pull request closed without merging**
