### PR TITLE
Fix mem leak in threadpool_test.c

### LINKED ISSUE #24104: There is a memory leak defect on line 134 of /openssl/test/threadpool_test.c.
1.On line 103 of the file /openssl/test/threadpool_test.c, a pointer variable named 'cust_ctx' is defined and dynamic memory is allocated for it through the function OSSL_LIB_CTX_new. When the if statement on line 133 returns true, the program will return on line 134, thereby bypassing the release operation on the dynamic memory area pointed to by the 'cust_ctx' pointer on line 239. This constitutes a memory leak defect, as shown in the diagram below:
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_10.png

### PR DESCRIPTION
**Pull request by coolshrid**
Fixes #24104

### CODE REVIEW

**Comment by t8m** [comment]
Please drop the merge commits. `git reset --hard HEAD~~~; git push --force` should help.

**Comment by coolshrid** [comment]
Done

**Comment by coolshrid** [comment]
Done

From: Tomáš Mráz ***@***.***>
Date: Thursday, May 16, 2024 at 01:50
To: openssl/openssl ***@***.***>
Cc: shridhar ***@***.***>, Author ***@***.***>
Subject: Re: [openssl/openssl] Fixes #24104 (PR #24412)


Please drop the merge commits. git reset --hard HEAD~~~; git push --force should help.

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Review by shahsb — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master, 3.3 and 3.2 branches with reworded commit message. Thank you for your contribution.

**Pull request closed without merging**
