### PR TITLE
Add a descriptive header to diff output from failed tests.

### PR DESCRIPTION
**Pull request by pauli-oracle**
- [x] tests are added or updated

Based on suggestion from #3341:

> Should we add a couple of diff-like lines saying what's what? You know:
> ```
> # --- expected
> # +++ value
> ```

### CODE REVIEW

**Comment by dot-asm** [comment]
This is not directly related to this request, but it is somewhat related. In other words this is a side note. There is certain ambiguity in context of comparison to known answers. Intuitively one expects known answer to be marked with -. I don't know how does majority do, but myself I'd tend to put known answer to the right side of comparison. I mean `if (value is right)` kind of thing, rather than `if (right is value)`. If majority turns to be `value is right` it would probably be sad if test programming styling would have to go against it to suit printing aid.

**Comment by pauli-oracle** [comment]
I've seen both versions in the tests I converted.  The `if (value is right)` form is the more common.
Swapping the `+` and `-` diff labels in the test output is certainly possible and seems like it would be worthwhile.

**Comment by levitte** [comment]
Doesn't that just mean swapping the two arguments to `TEST_bn_eq` in `equalBN` and so on?

**Comment by levitte** [comment]
Merged. bb616fabd4a82d5daa3ca701abbe30e6d1415341

**Comment by t-j-h** [comment]
The "value is right" form is considered more readable, but some folks have "right is value" in their coding standards left over from compilers that didn't warn when == is inadvertently written as = and "right" is a constant. At least I think that is what leads to a mixed usage at times of placing things in the less readable format.

**Comment by pauli-oracle** [comment]
> Doesn't that just mean swapping the two arguments to TEST_bn_eq in equalBN and so on?

The names need to be swapped somewhere.  It could be the display functions `test_fail_string_message` or the test functions `test_BN_eq` or the macro wrappers `TEST_BN_eq`  I'd lean towards modifying the display function, either swapping the arguments or changing the output strings.

**Comment by levitte** [comment]
@pauli-oracle, I'm not sure what you're saying, but if what your saying is that `TEST_bn_eq(A, B)` would be presented like below, I'm going to protest loudly:

```
# ERROR: (BIGNUM) 'B == A' failed @ whatever line something
# --- B
# --- A
...
```

**Comment by pauli-oracle** [comment]
I wasn't thinking of changing the expression print out in the first line.  More like:

```
# ERROR: (BIGNUM) 'A == B' failed @ whatever line something
# +++ A
# --- B
...
```

The order of the `+++ A` and `--- B` lines could be reversed, although neither way around is ideal:

```
# ERROR: (BIGNUM) 'A == B' failed @ whatever line something
# --- B
# +++ A
...
`

**Comment by levitte** [comment]
If we're taking inspiration from diff, I would think it would be unwise to deviate from it's form too much, and would therefore assume this rough form:

```
left == right
--- left
+++ right
... 
```

Regarding the *meaning* of left and right, I would put that in the calls of the comparison macros, i.e. `TEST_mem_eq(expected, value)` vs `TEST_mem_eq(value, expected)`.

**Comment by pauli-oracle** [comment]
@levitte the current format is already in the rough form you gave.

**Comment by levitte** [comment]
Yes. I'd rather keep it that way.

**Pull request closed without merging**
