### PR TITLE
CMP app: fix server info to be just the host (not port/URL)

### LINKED ISSUE #20031: openssl cmp -server argument used as SNI even if URL or host:port
While debugging the issue https://serverfault.com/questions/1119743/ I realized that SNI handling in `openssl cmp` seems to be broken. It simply sets the SNI to the argument given by `-server` (or by `server` in the config), even though this argument is documented as being a URL or hostname:port in addition to a simple hostname.

From openssl-3.0.7 (but still presented in openssl-3.1.0-beta1) in apps/cmp.c

<pre>
1926         info->server = opt_server;
...
1935         (void)OSSL_CMP_CTX_set_http_cb(ctx, app_http_tls_cb);
</pre>

In line 1926 it sets `info->server` to the unchanged option from command line or config, i.e. the option which might be the full URL or hostname:port. It then uses `info->server` in `app_http_tls_cb` as it is to set the SNI as seen in apps/lib/apps.c:

<pre>
2466 BIO *app_http_tls_cb(BIO *bio, void *arg, int connect, int detail)
...
2491         SSL_set_tlsext_host_name(ssl, info->server); /* not critical to do */
</pre>

It looks to me like the proper setting for `info->server` in apps/cmp.c should be `host` instead of `opt_server`, but I did not test it.

### PR DESCRIPTION
**Pull request by DDvO**
Fixes #20031, in the way correctly suggested here.

### CODE REVIEW

**Comment by t8m** [comment]
How hard it would be to add a test?

**Comment by DDvO** [comment]
> How hard it would be to add a test?

I fear this would be rather difficult, because we'd need to detect where the underlying HTTP client actually tries to connect to.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
Reminder for 2nd approval - a very low-hanging fruit ;-)

**Comment by dbuettiker** [comment]
The fix is not working.
I could do some testing cloning the branch CMP_info_server_fix but SNI is still broken! The fix sets _Server Name length to 1. 

1922 info->server = opt_tls_host;

leads to the SNI Server Name properly set.

Please also consider to add a info message before or after 1922 like
CMP_info2("opt_server: %s,  opt_tls_host: %s, port: %s", opt_server, opt_tls_host);

**Comment by dbuettiker** [comment]
The fix is not working.
I could do some testing cloning the branch CMP_info_server_fix but SNI is still broken! The fix sets _Server Name length to 1.

1922 info->server = opt_tls_host;

leads to the SNI Server Name properly set.

Please also consider to add a info message before or after 1922 like
CMP_info2("opt_server: %s, opt_tls_host: %s, port: %s", opt_server, opt_tls_host);

**Comment by DDvO** [comment]
Oh, you are right, it was sill broken - even in two ways!
1. In case `-tls_host` was used, the given value should be used instead of the server hostname.
2. It turns out that the host and port strings were potentially garbled because they are no more in scope when `app_http_tls_cb()` runs.

I've just added fixed for both issues.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
A compiler warning make many test cases fail, which is fixed now.
Strange that I did not get this warning locally though I also configure with `--strict-warnings`.

**Comment by DDvO** [comment]
The remaining CI failure is unrelated: some Windows build issue that I've been seeing for quite a while now.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
Ping for 2nd approval

**Comment by DDvO** [comment]
Pinging @openssl/committers again for 2nd approval.

**Comment by DDvO** [comment]
Asking aging @openssl/committers for 2nd approval.
It's not not much work ;-)

**Review by mattcaswell — APPROVED** [review]

**Comment by hlandau** [comment]
Merged to master, 3.0 and 3.1. Thank you.

**Pull request closed without merging**
