### PR TITLE
Remove an unused file

### PR DESCRIPTION
**Pull request by mattcaswell**

### CODE REVIEW

**Comment by paulidale** [comment]
Does this assume that this branch of the #ifdef maze in `crypto/dso/dso_win32.c` is never used?  If so, there is a big chunk of code that can be removed from that file too.

**Comment by levitte** [comment]
No, it seems to mean that tlhelp32.h is a system file, we just have a copy from longago, when it wasn't.

That's at least how I understand this.  @mattcaswell can confirm, perhaps?

**Comment by mattcaswell** [comment]
> No, it seems to mean that tlhelp32.h is a system file, we just have a copy from longago, when it wasn't.

> That's at least how I understand this. @mattcaswell can confirm, perhaps?

Yes, it's a system file that we have a copy of. I believe it was included as a workaround at one point when it was omitted in some ancient mingw release. However that workaround worked it does not apply any more because this version of the file is never referred to anywhere. The code in `dso_win32.c` that @paulidale refers to is still used, but it includes the system copy of the file not this one.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
