### PR TITLE
test: Improve coverage for the PBKDF2 unit tests

### LINKED ISSUE #25136: Unit tests for PBKDF2 need improvement
Refer comment: https://github.com/openssl/openssl/pull/25135#discussion_r1708555654

We should have tests for:
- minimum key length
- minimum salt length (present)
- minimum number of iterations

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #25136

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by Sashan — APPROVED** [review]
Looks good. I found just nit in comment. 
I'm fine with it regardless if nit gets fixed or no.

**Review by nhorman — APPROVED** [review]

**Comment by paulidale** [comment]
Ping @openssl/otc for second review

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by paulidale** [comment]
Kicking tests just in case.

**Comment by paulidale** [comment]
Merged, thanks for the reviews.

**Pull request closed without merging**
