### PR TITLE
tag ossl_assert not failing as being 'likely' to improve optimisation

### PR DESCRIPTION
**Pull request by paulidale**
Add a likely tag to ossl_assert to help compilers produce better code.

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by hlandau — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]

**Comment by mspncp** [comment]
nit: optimistaion -> optimisation
_(I'm a menace, I know. Change it or leave at your discretion)_

**Comment by paulidale** [comment]
I fixed the menace's issue.
Don't see a need for re-reviews.

**Review by mspncp — APPROVED** [review]

**Review by t8m — APPROVED** [review]
IMO this should go in 3.2 too, ~~at least~~.

**Comment by t8m** [comment]
**OTC: Which branches we should apply this to?**

**Comment by t8m** [comment]
**OTC: not a bug fix not for 3.2**

**Comment by t-j-h** [comment]
Note - these two macros should be renamed to ossl_likely and ossl_unlikely.

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed to master.

**Pull request closed without merging**
