### PR TITLE
Fix speed, use OPENSSL_free instead of free

### PR DESCRIPTION
**Pull request by dongbeiouba**

### CODE REVIEW

**Comment by beldmit** [comment]
Not sure it's a relevant fix. `fds` is allocated via app_malloc, not OPENSSL_malloc.

**Comment by dongbeiouba** [comment]
> Not sure it's a relevant fix. `fds` is allocated via app_malloc, not OPENSSL_malloc.

app_malloc invokes  OPENSSL_malloc().

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
OK for 1.1.1

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the fix.

**Pull request closed without merging**
