### PR TITLE
util/mknum.pl: Allow unset ordinals in beta1-dev

### PR DESCRIPTION
**Pull request by levitte**
beta1-dev is still pre-beta, so the ordinals don't need to be finalized yet.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
The last fixup is about the position of the ?.  I remembered it wrong...

**Comment by levitte** [comment]
So, a question I have is why added functions in *any* development "state" shouldn't get a `?` until a release is happening.  I.e., even though we really shouldn't, if we do find that we need to add another function between beta1 and final release, is there a reason it should get a number directly instead of getting assigned a number as part of the release?

In other words, the regexp could be simplified further like this:

`^\d+\.\d+\.\d+(?:[a-z]+)?(?:-alpha|(?:-.*?)?-dev$)`

That matches any version that includes `-alpha` and any version that ends with `-dev`.

**Comment by levitte** [comment]
Said and done.  *Now* I'm happy with this.

**Comment by paulidale** [comment]
Might a better approach be to add numbering to the release process for beta and beyond and have this script ignore versioning completely?  Development between releases would be unconstrained.

**Comment by levitte** [comment]
> Might a better approach be to add numbering to the release process for beta and beyond and have this script ignore versioning completely? Development between releases would be unconstrained.

Look at the latest squash.  It does exactly what you ask while still keeping the functionality in this script

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Merged

cbba082fc071de82ffb53844586cdcc26251e32b util/mknum.pl: Really allow unset ordinals in development
17213b2ad03fe577c03a3e77142242adde41fa9f Restore all the ? in util/libcrypto.num

**Comment by h-vetinari** [comment]
It seems resetting the ordinals fell under the table for beta1... @mattcaswell @levitte

**Comment by mattcaswell** [comment]
> It seems resetting the ordinals fell under the table for beta1

Yeah...we spotted they were missing during the release. The release script should have inserted them during the make update, but it didn't. We decided to proceed anyway.

**Comment by h-vetinari** [comment]
Cool, as long as you were aware already. :)

Congratulations for reaching this huge milestone BTW! 🎉

**Comment by mattcaswell** [comment]
> Congratulations for reaching this huge milestone BTW! 

Thanks!

I raised this as issue #15806

**Pull request closed without merging**
