### PR TITLE
New GOST identificators

### PR DESCRIPTION
**Pull request by beldmit**
This pull request provides OIDs and NIDs necessary for new GOST-related standards.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Oh...actually, it looks like a "make update" is required for this PR

**Comment by richsalz** [comment]
yes. fuzz/oids  okay to do 'make update' as part  of the commit?

**Comment by mattcaswell** [comment]
Sure

**Comment by richsalz** [comment]
thanks.  done and merged.

**Pull request closed without merging**
