### PR TITLE
RSA padding checks hardening, backport to 1.1.0.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by dot-asm** [comment]
On second thought one can probably argue that one should stay away from uintptr_t even in 1.1.x. I mean in 1.0.2 backport I avoided uniptr_t with rationale that "we can't assume that all compilers supported by 1.0.2 have it." But the argument is likely to apply even to 1.1.x... Just in case, if you `grep` for uintptr_t in say master, you'll spot several occurrences. But[!] those are actually system-specific sections, while crypto/err/err.c is system-neutral and as such has harder portability constrains.

**Comment by dot-asm** [comment]
> one should stay away from uintptr_t even in 1.1.x.

Relevant snippet is https://github.com/openssl/openssl/blob/master/include/openssl/e_os2.h#L231. Well, it rather means that one has to choose between staying away from uintptr_t and arranging uintptr_t typedef on some of the platforms. One should note that there is ambiguity in _MSC_VER<=1500 case. There actually is uintptr_t definition on _MSC_VER, in <stddef.h>. This means that there might be conflict between definitions in case <stddef.h> is brought in, directly or indirectly, even in application code, since this is a public header...

**Comment by mattcaswell** [comment]
@dot-asm Do the above comments imply that you are planning an update to this PR? Or should I merge this and await a later fixup PR?

**Comment by dot-asm** [comment]
> @dot-asm Do the above comments imply that you are planning an update to this PR?

No. This request target 1.1.0, while the problem arguably applies to 1.1.x. And since the snippet from e_os2.h comes from master, it's only appropriate to follow the usual pattern, i.e. master first and cherry-pick where appropriate.

**Comment by levitte** [comment]
Merged.

6d405b64b77f29241b680f7edadd14d5dc0a8522 rsa/rsa_ssl.c: make RSA_padding_check_SSLv23 constant-time.
437b7f059304f59a0fa96d329ca62cd8d748cbc8 rsa/rsa_oaep.c: remove memcpy calls from RSA_padding_check_PKCS1_OAEP.
43d53fa19da6809e458ebdadba6016d5fbc780a2 rsa/rsa_pk1.c: remove memcpy calls from RSA_padding_check_PKCS1_type_2.
b58c44a8c1b6c7354c9c8ce4631e27f9eb977b60 rsa/rsa_ossl.c: make RSAerr call in rsa_ossl_private_decrypt unconditional.
0ba39c87aa386db3a97be9e11c77aac94176a2fa err/err.c: add err_clear_last_constant_time.

**Pull request closed without merging**
