### PR TITLE
`OSSL_CMP_validate_msg()`: make sure to reject protection type mismatch

### PR DESCRIPTION
**Pull request by DDvO**
Do not accept password-based protection if signature-based is expected and no secret is available and 
do not accept signature-based protection if password-based is expected and no trust anchors available.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by t8m — DISMISSED** [review]

**Comment by t8m** [comment]
@DDvO the use of FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION in CMP code seems fairly weird to me. Is it mostly code that should use ossl_assert() instead?

**Comment by DDvO** [comment]
> @DDvO the use of FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION in CMP code seems fairly weird to me. Is it mostly code that should use ossl_assert() instead?

The point of using `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` in `crypto/cmp/cmp_vfy.c` is to disable various checks on CMP messages received in order to enable more aggressive fuzzing.
This demonstrates that even with those checks not present, which emulates bad messages being received and not rejected, the remaining code does not crash.
See also #11386.

Consequently, most of the 'negative' tests in `cmp_vfy_test.c` must be disabled with `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` because they would fail due to the disabled message validation checks.

**Comment by DDvO** [comment]
Asking @openssl/committers for 2nd review.

**Comment by DDvO** [comment]
Argh, I just noticed that cherry-picking the fix to 3.0 causes a build error because meanwhile the function `OSSL_CMP_CTX_set0_trustedStore`  had been renamed to `OSSL_CMP_CTX_set0_trusted` on the master.

How to cure this? The change needed is
```
diff --git a/test/cmp_vfy_test.c b/test/cmp_vfy_test.c
index 23117760d1..ed8e1b3143 100644
--- a/test/cmp_vfy_test.c
+++ b/test/cmp_vfy_test.c
@@ -153,7 +153,7 @@ static int test_validate_msg_mac_alg_protection(int miss, int wrong)
     SETUP_TEST_FIXTURE(CMP_VFY_TEST_FIXTURE, set_up);
 
     fixture->expected = !miss && !wrong;
-    if (!TEST_true(miss ? OSSL_CMP_CTX_set0_trusted(fixture->cmp_ctx, NULL)
+    if (!TEST_true(miss ? OSSL_CMP_CTX_set0_trustedStore(fixture->cmp_ctx, NULL)
                    : OSSL_CMP_CTX_set1_secretValue(fixture->cmp_ctx, sec_1,
                                                    wrong ? 4 : sizeof(sec_1)))
             || !TEST_ptr(fixture->msg = load_pkimsg(ip_waiting_f, libctx))) {
```
Shall I push a fixup commit on `openssl-3.0` or can I even amend and force-push it there
or is the only option to have an urgent fixup PR for 3.0? I tentatively opened it in #19859.

**Pull request closed without merging**
