### PR TITLE
Fix commit a672a02a s390x build breakage

### PR DESCRIPTION
**Pull request by p-steuer**
Commit a672a02a broke s390 build due to changes being done to the s390 code after my approval of the corresponding PR.

### CODE REVIEW

**Comment by levitte** [comment]
Please don't have commit ids in commit messages. If we change VCS some time in the future, that's going to be a confusing history

**Comment by p-steuer** [comment]
@levitte wrote:
> Please don't have commit ids in commit messages. If we change VCS some time in the future, that's going to be a confusing history

Somethings wrong with GH today.. just got an email notification of quoted comment but it doesnt appear here.

Would it be okay to have commit id in the message body ?

**Comment by levitte** [comment]
I actually deleted that comment, because I realised that any time we cherry pick to other branches, we do so with the `-x` flag, i.e. we're including commit IDs in the commit message anyway, so my protest was pretty moot.  In other words, never mind...

**Comment by p-steuer** [comment]
merged to master: 2b2eb210a1365f80a125cebdd05ed567cb3ca7cf

**Comment by slontis** [comment]
Thanks - you beat me to it ..

**Pull request closed without merging**
