### PR TITLE
Fix declaration inconsistency (Camellia)

### LINKED ISSUE #17911: declaration different from definition
cmll_local.h line 41

void Camellia_DecryptBlock(int keyBitLength, const u8 ciphertext[],
                           const KEY_TABLE_TYPE keyTable, u8 plaintext[]);

vs 

/crypto/camellia/camellia.c line 502

void Camellia_DecryptBlock(int keyBitLength, const u8 plaintext[],
                           const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
{

### PR DESCRIPTION
**Pull request by hlandau**
Fixes #17911.

### CODE REVIEW

**Comment by t8m** [comment]
I would not even call this a bug. It is a confusing code and should be fixed in master branch and perhaps 3.0. Not worth doing it in 1.1.1 though IMO.

**Review by t8m — APPROVED** [review]
OK for master and with some grain of salt for 3.0 too.

**Comment by levitte** [comment]
> I would not even call this a bug. It is a confusing code and should be fixed in master branch and perhaps 3.0. Not worth doing it in 1.1.1 though IMO.

I agree

**Comment by levitte** [comment]
I removed the 'branch: 1.1.1' label

**Review by paulidale — APPROVED** [review]

**Review by paulidale — APPROVED** [review]
FWIW

**Comment by paulidale** [comment]
Merged to 3.0 and master.   Thanks for the update.

**Pull request closed without merging**
