### PR TITLE
Add some missing env var documentation

### PR DESCRIPTION
**Pull request by richsalz**
Probably backports easily.

### CODE REVIEW

**Comment by richsalz** [comment]
pushed an updated commit that documented OPENSSL_CONF_INCLUDE.

**Comment by levitte** [comment]
Some of the env vars are master only, so a backport should be made separately

**Comment by richsalz** [comment]
> Some of the env vars are master only,

good point!

**Comment by t8m** [comment]
Merged to master as a8055c70fa.

**Pull request closed without merging**
