### PR TITLE
Fix AppVeyor/VC build failure

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Ping @dot-asm ; After -WX addition, it do not build anymore ;)

##### Checklist
- [ ] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Comment by dot-asm** [comment]
Ah! This is module that is not built in shared... Fair enough...

**Comment by dot-asm** [comment]
Merged. Thanks!

**Comment by dot-asm** [comment]
Well, more errors surfaced... I'll have a look later today...

**Comment by FdaSilvaYY** [comment]
Give me 30' and I will push a complete and tested PR ;)

**Comment by dot-asm** [comment]
Too late :-( See #4751...

**Pull request closed without merging**
