### PR TITLE
Backport probable_prime logic from master

### LINKED ISSUE #4656: the generated primes for bit-lengths 2 .. 15 are all identical
(in bash) try:
=========================== begin bash code ==============================
i=2
while [[ "35879" == $(openssl prime -generate -bits $i) ]] ; do echo $i; ((++i)); done
===========================end bash code ==============================

Is this intended? 
It tastes like a bug.
I notice that for bit-lengths >= 16, multiple calls get different primes

### PR DESCRIPTION
**Pull request by mattcaswell**
The old probable_prime logic in 1.0.2 did not handle small primes very
well (in fact it gets it completely wrong). This was fixed in later versions
by commit 96a4c31b but this was apparently never backported to 1.0.2. This
commit does that backport.

Fixes #4656

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
FYI: this improvement likely caused the infinite loop in the rsa keygen with less than 16 bits.

**Comment by bernd-edlinger** [comment]
confirmed, with this patch the following command goes into endless loop:
`openssl genrsa -3 8`

**Comment by mattcaswell** [comment]
@bernd-edlinger I added the requested additional commit.

**Comment by bernd-edlinger** [comment]
Thanks, but I think you should drop the test case.

**Comment by mattcaswell** [comment]
Oops. I meant to, and thought I had. But apparently not. Updated commit pushed.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
