### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Urgent as needed for the release.

**Comment by levitte** [comment]
Merged

54d987b92ce57c1cc38c6d9b6bf879b003f4cbd4 Update copyright year

**Comment by t8m** [comment]
Probably should be cherry picked to master as well to avoid conflicts.

**Comment by levitte** [comment]
Okie

**Comment by levitte** [comment]
Merged to master as well

a8d9bd8114510d3a1708da3922f07e7f707674bc Update copyright year

**Pull request closed without merging**
