### PR TITLE
DSA parameter check using pkeyparam

### PR DESCRIPTION
**Pull request by beldmit**
Unfortunately all the parameter files generated by `genpkey` for DSA algorithm seem to fail the parameters validation by `pkeyparam`.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
Could anybody please look at the DSA provider?

**Comment by slontis** [comment]
The doc EVP_PKEY-DSA.pod does mention why this is problematic..
For FIPS186-4 - the same parameters used for generation are required for validation.

When you do
./apps/openssl genpkey -genparam -algorithm DSA -pkeyopt dsa_paramgen_bits:2048 -pkeyopt qbits:224 -pkeyopt type:fips186_4 -text

It outputs
````
P:   ....
Q:   ....
G:   .... 
SEED:
    34:f5:4a:4b:de:55:f1:db:7f:d4:9d:4f:67:1c:15:
    4b:91:ec:d9:99:6b:24:2a:87:77:89:1c:b8
pcounter: 2212
h: 2
````
When you actually save out your DSA parameters the ASN1 format only has P, Q, G - Not the other fields..
So unless you save out the SEED, pcounter, and h seperately yourself and put them back into the DSA object - the validation will fail..
-----------------------------------------
DH has the same issue, but there is a move towards 'named' groups (which dont have this problem).

**Comment by beldmit** [comment]
@slontis, do I correctly understand that, without these parameters, the `pkeyparam` will not validate the parameters at all, and as there is no options allowing them to be passed, the `pkeyparam` is unsuitable for this purpose?

I'm not familiar with DSA, so please apologize me for a stupid question.

**Comment by t8m** [comment]
@slontis I think we should adjust the validation routine to not fail hard when all of the SEED, pcounter, and h are not present. In that case the validation should just do primality test for p and q, and do the unverifiable g validation. Any problem with that? This could be default provider only.

**Comment by t8m** [comment]
> @slontis I think we should adjust the validation routine to not fail hard when all of the SEED, pcounter, and h are not present. In that case the validation should just do primality test for p and q, and do the unverifiable g validation. Any problem with that? This could be default provider only.

I've implemented this, but there is one remaining question - should the validity of L,N according to FIPS 186-4 be checked? In that case the invalid L,N combinations will still fail. But IMO that is correct.

**Comment by slontis** [comment]
I dont even know if you should do that check either for the default provider..
@t8m you probably noticed there was a function to do a partial check already (which I needed for some other case)?

**Comment by t8m** [comment]
Yes, I am just extending the partial check. I'll probably just drop the L,N validity check in default provider completely or make it much more lenient.

**Comment by t8m** [comment]
This PR is superseded by #14148 as I incorporated your commit there. Can I close it @beldmit?

**Comment by beldmit** [comment]
Sure. Thanks!

**Pull request closed without merging**
