### PR TITLE
[URGENT] make update

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
What has happened is that a PR that was made before 7b9f8995f44482610d4f3452118e53c2f259511d was merged without updating.  This is to be expected until all PRs have caught up with that change.

**Review by paulidale — APPROVED** [review]
I was just stumbling onto this.

**Comment by levitte** [comment]
The lacking update makes builds fail in Github CI, so this is urgent

**Comment by levitte** [comment]
Merged

0647162f6af7c2e0edb4c770bf501ad7e0302970 make update

**Pull request closed without merging**
