### PR TITLE
QUIC CHANNEL: Make ping deadline and idle deadline calculation consistent

### LINKED ISSUE #22530: QUIC client fuzzer hang
OSSfuzz have found a new hang in the QUIC client fuzzer. Fuzzer file attached.
[clusterfuzz-testcase-minimized-quic-client-6245605980372992.gz](https://github.com/openssl/openssl/files/13186096/clusterfuzz-testcase-minimized-quic-client-6245605980372992.gz)

### PR DESCRIPTION
**Pull request by hlandau**
Fixes #22530.

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
LGTM.

Can you add "Fixes #22530" to the commit message?

**Comment by mattcaswell** [comment]
I can confirm that this fixes the hang.

**Review by paulidale — APPROVED** [review]

**Comment by hlandau** [comment]
This should go into 3.2.

**Comment by hlandau** [comment]
Merged to master and 3.2. Thanks for the reviews.

**Pull request closed without merging**
