### PR TITLE
Windows-based GOST implementations compatibility

### PR DESCRIPTION
**Pull request by beldmit**
Many Windows-based GOST TLS implementations are unable to extend the
list of supported SignatureAlgorithms because of lack of the necessary
callback in Windows. So for TLS 1.2 it makes sense to imply the support
of GOST algorithms in case when the GOST ciphersuites are present.

This is a backport of #10377 to 1.1.1 branch

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
@paulidale, many thanks!
What about #10377?

**Comment by beldmit** [comment]
@mspncp, could you please take a look? I think this PR along with #10377 should be labeled as "Ready to merge" because 24 hours have passed. Does the label "ready to merge" apply automatically?

Thanks!

**Comment by paulidale** [comment]
The tag isn't automatic yet.  It also isn't mandatory yet.
I've added it.

**Comment by paulidale** [comment]
I think an automatic email after the 24 hours is a good idea too.

**Comment by beldmit** [comment]
> The tag isn't automatic yet. It also isn't mandatory yet.
> I've added it.

My fault. I thought it is.

**Comment by mspncp** [comment]
> My fault. I thought it is.

For the moment, you can set it yourself until it is done automatically (any progress @levitte?).

But the [approval: *] tags are meant to be used like a state, so there shouldn't be multiple of them set at the same time. That's why I removed the [approval: done] tag.

**Comment by beldmit** [comment]
Merged. Thanks!

**Pull request closed without merging**
