### PR TITLE
Updating License - typo

### PR DESCRIPTION
**Pull request by StackKorora**
Missing a 't'. Fixing because it bothered me. :-)

### CODE REVIEW

**Comment by t-j-h** [comment]
The license text is what it is ... closing this.

**Comment by richsalz** [comment]
Yeah, it bothers many people. Myself included. :)  But we are not touching a single byte of the license, sorry.  Closing this.

**Comment by StackKorora** [comment]
No worries. It was worth a try.

**Comment by mspncp** [comment]
Fortunately, the typo makes it read only "rouines from the library" and not "ruins from the library" ;-).

**Comment by richsalz** [comment]
In my head, I see "rouines" as some kind of French dish, or maybe a cousine of poutine.

**Comment by levitte** [comment]
I'd be interested see that French dish...  as for Poutine, I'd never heard of it before, and had of course to look it up.  Suffice to say that the French in me wanted to run away screaming :smirk:

**Pull request closed without merging**
