### PR TITLE
Constify some input buffers

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Is this 1.1.0 release compatible ?

### CODE REVIEW

**Comment by mattcaswell** [comment]
Yes - I would say so.

**Comment by richsalz** [comment]
This is nice.  Did you do the (tedious) work of checking if any of these are documented?

**Comment by FdaSilvaYY** [comment]
@richsalz:  the docs of this PR are OK.
I'm obliged to keep every definition and declaration in sync: clang is very touchy about this point....
So I grep on every source file (*.c;*.h;*.num;*.def;*.pod) , and update any pod file at  the same time...

**Comment by richsalz** [comment]
Just double-checking, thanks.
+1

**Comment by kroeckx** [comment]
+1

**Comment by richsalz** [comment]
pushed, thanks.

**Pull request closed without merging**
