### PR TITLE
Allow custom extensions to be negotiated on resume.  Needed for token…

### PR DESCRIPTION
**Pull request by waywardgeek**
… binding, and most custom extensions since it there is no method for saving state between connections

### CODE REVIEW

**Comment by waywardgeek** [comment]
Hi, again.  I am about to release our token binding library as open source, and it uses the custom extension API.  It would be great if we could resolve this issue soon.  Thanks.

**Comment by richsalz** [comment]
ping @mattcaswell

**Comment by PiotrSikora** [comment]
We've just released: [Token Binding library](https://github.com/google/token_bind) & [NGINX module](https://github.com/google/ngx_token_binding) that's using it, which require this patch to work, please take a look.

Ping @mattcaswell

**Comment by richsalz** [comment]
Hey, @mattcaswell and @snhenson any thoughts?  token binding is useful to have ...

**Comment by mattcaswell** [comment]
This is a behaviour change that could break some custom extensions if they do not expect to be called on resumed sessions. I'd also note that the current custom extensions API does not work with TLSv1.3 (because there are many more messages in TLSv1.3 that can take extensions and the existing API has no way of controlling this). A new custom extensions API that is TLSv1.3 compatible is on my TODO list so I suggest we handle this request as part of that.

**Comment by richsalz** [comment]
@openssl/team I'd like to bump this up.  Being able to support token binding would be very very useful.  How long to to do the API, do you think?

**Comment by waywardgeek** [comment]
Let me know if I could be helpful with this upgrade.  I agree with mattcaswell that a new API with improved functionality would be a good thing.

**Comment by mattcaswell** [comment]
#3139 provides a new custom extensions API. It allows custom extensions to be negotiated on resume. Closing in favour of that PR.

**Pull request closed without merging**
