### PR TITLE
Backport some fuzzing data files from master

### PR DESCRIPTION
**Pull request by bernd-edlinger**
##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Oops, CI tests are failing?

**Comment by bernd-edlinger** [comment]
Looks like #13452 was forgotten to merge to 1.1.1, ...

**Comment by bernd-edlinger** [comment]
Ok, works now.

**Comment by mattcaswell** [comment]
Rather than adding the #13452 commit here - why not just push #13452 to 1.1.1? It has all the necessary approvals. If you'd rather do it here then please can you do it in a separate commit?

**Comment by bernd-edlinger** [comment]
It did not cherry pick, because the files were renamed.

**Comment by bernd-edlinger** [comment]
I did not expect to find an error, I was kind of certain that just some test files were forgotten.

**Comment by bernd-edlinger** [comment]
But if you prefer I can make that two commits.

**Comment by mattcaswell** [comment]
> It did not cherry pick, because the files were renamed.

Ah ok - fair enough.

> But if you prefer I can make that two commits.

Please do.

**Comment by bernd-edlinger** [comment]
Ok, done.

**Review by mattcaswell — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
Merged to 1.1.1.  Thanks!

**Pull request closed without merging**
