### PR TITLE
CHANGES: add note about slower prime number generation.

### PR DESCRIPTION
**Pull request by paulidale**
This will impact RSA key generation and DH and DSA parameter generation.

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
LGTM

**Comment by kroeckx** [comment]
You're changing a 1.1.1 changes entry.

**Comment by paulidale** [comment]
Oops.  You are correct and this fix is in 1.1.1f so it can't be the cause of the slow down.

It seems that whatever slowed things down hasn't got an associated CHANGES entry.
Should there be a new changes entry for 3.0 noting that RSA key generation is significantly slower without saying why?

**Comment by paulidale** [comment]
Adding a hold to avoid this being merged by accident.

**Comment by paulidale** [comment]
Should there be a new changes entry for 3.0 noting that RSA key generation is significantly slower without saying why?

**Comment by richsalz** [comment]
You can't just read this diff without context.  The previous item explains what was changed.  If it's still an issue, merge this PR text into the previous paragraph.  I think it's fine as-is tho.

**Comment by t8m** [comment]
This PR should be closed as this is not the reason for the slower RSA key generation.

The real reason is the switch to the RSA key generation method according to FIPS 186-4 B.3.6  for 4096 bit keys.

**Comment by t8m** [comment]
Created issue #14068 for that and closing this PR.

**Comment by kroeckx** [comment]
> This PR should be closed as this is not the reason for the slower RSA key generation.

I think you misunderstand. The reason for the slowdown is probably
commit 42619397eb5db1a77d077250b0841b9c9f2b8984 that now always
does at least 64 rounds of Miller-Rabin for the prime test. Before
that commit, when generating a prime, it used less rounds. When
you're generating a prime, you don't have to worry about being
attacked and the number of rounds is 5 or less for primes >= 476
bits. To prevent people from using the wrong amount of rounds,
we now always do at least 64, making things slower.

There is also a speedup caused by the commit just before that:
6c4ae41f1ca857254fc9e27edead81ff2fd3f3fe.

**Comment by t8m** [comment]
With high probability the additional MR rounds come into play only after a prime is found. So yeah, you're right that it contributes to the slowdown as well but the major difference is from the change of the rsa keygen implementation. Although the 128 MR rounds for larger primes is significant as well so. So what I see with my tests  is that up to 4096 bit keys the major part of the slowdown is the changed keygen and for larger keys it is half on the changed keygen and half for the 128 MR rounds for each prime found.

**Comment by t8m** [comment]
@kroeckx The 128 MR rounds is actually  a truly crazy number given the reasoning here: https://stackoverflow.com/questions/4159333/rsa-and-prime-generator-algorithms/4160517#4160517 which I agree with.
I'm going to submit a PR to drop that keeping just 64 rounds.

**Comment by kroeckx** [comment]
On Fri, Feb 05, 2021 at 04:44:02AM -0800, Tomáš Mráz wrote:
> @kroeckx The 128 MR rounds is actually  a truly crazy number given the reasoning here: https://stackoverflow.com/questions/4159333/rsa-and-prime-generator-algorithms/4160517#4160517 which I agree with.
> I'm going to submit a PR to drop that keeping just 64 rounds.

Note that that is about *generating* a prime, not checking it's prime.

**Comment by kroeckx** [comment]
I guess I should have read it first

**Comment by kroeckx** [comment]
So he's saying that if we returned that it was a non-prime, there
is a 1.8*10^-24 (2^-78.8) chance that the calling functions will
will see it as a prime.

With the new algorithm we follow that by a pair-wise
consistency test. That that also is going to say everything
is okay seems very low.

**Comment by t8m** [comment]
Basically doing any testing with error probability lower than 2^-128 does not provide any meaningful improvement because the testing can equally well fail to indicate the error due to physical properties of hardware. It is not right to equate security level with reciprocal error probability as both values have a completely different meaning and they are only loosely related.

**Pull request closed without merging**
