### PR TITLE
Few cleanups in s_client, s_server apps.

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Discard useless static engine_id
Add a const qualifier
Fix a spelling

### CODE REVIEW

**Comment by levitte** [comment]
:+1:

**Comment by FdaSilvaYY** [comment]
I've add two more minors changes, as separated commits.

**Comment by mattcaswell** [comment]
+1

@levitte, you probably need to re-review

**Comment by mattcaswell** [comment]
@levitte can you reconfirm your +1?

**Comment by levitte** [comment]
:+1: reconfirmed

**Comment by mattcaswell** [comment]
Merged. Thanks.

**Pull request closed without merging**
