### PR TITLE
Add an Apple privacy info file for OpenSSL

### PR DESCRIPTION
**Pull request by takeh1k0**
for https://github.com/openssl/openssl/pull/24032#issuecomment-2071405158

I have created `PrivacyInfo.xcprivacy` file using Xcode 15.1 GUI.

image

CLA: trivial

### CODE REVIEW

**Comment by t8m** [comment]
Although this is probably not copyrightable, it is outside of what we usually accept with CLA: trivial. Would you be willing to submit a regular CLA? https://www.openssl.org/policies/cla.html

**Review by mattcaswell — APPROVED** [review]
Approved subject to CLA resolution

**Comment by hlandau** [comment]
Does this really need to go in the root directory?

**Comment by takeh1k0** [comment]
@t8m I have submitted my CLA via email.

**Comment by t8m** [comment]
> Does this really need to go in the root directory?

I think we could add `Apple` subdir and move it there. We already have `ms` and `VMS` subdirs.

**Comment by t8m** [comment]
> > Does this really need to go in the root directory?
> 
> I think we could add `Apple` subdir and move it there. We already have `ms` and `VMS` subdirs.

Or even better create `Apple` subdir under `os-dep` and move it there. At some point we should move `ms` and `VMS` under `os-dep` too.

**Comment by takeh1k0** [comment]
My CLA has been received. I was told to close and reopen any open pull requests to remove the "needs CLA" tag, so I will close this pull request and will reopen.

**Comment by mattcaswell** [comment]
> My CLA has been received. I was told to close and reopen any open pull requests to remove the "needs CLA" tag, so I will close this pull request and will reopen.

It was sufficient to close and reopen this PR...but never mind.

**Comment by takeh1k0** [comment]
@mattcaswell I misunderstood the meaning of reopen... Thanks for pointing that out!

**Pull request closed without merging**
