### PR TITLE
Make d2i_PUBKEY_ex generate new style EVP_PKEYs

### PR DESCRIPTION
**Pull request by jon-oracle**
Use new decoder for d2i_PUBKEY_ex so that the output is a non-legacy EVP_PKEY.

This change is similar to work done by @slontis in https://github.com/openssl/openssl/pull/13591

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
Could you add a test case please?

**Comment by slontis** [comment]
Were you using CTLOG_new_from_base64_ex() or is this just something you noticed?

**Comment by slontis** [comment]
CI failure is not related to this PR.

**Comment by jon-oracle** [comment]
> Were you using CTLOG_new_from_base64_ex() or is this just something you noticed?

Just something that came up as a test failure after the changes to d2i_PUBKEY_ex. I noticed that it wasn't using the _ex version of d2i_PUBKEY and therefore not passing down the libctx/propq as it probably should. Failure went away after that.

**Review by slontis — COMMENTED** [review]
Keep in mind that I broke engines
See #14266

**Pull request closed without merging**
