### PR TITLE
Fix compilation of AF_ALG engine

### PR DESCRIPTION
**Pull request by zorun**
Two small commits for AF_ALG engine, one fixing a kernel version comparison, and the other one fixing compilation on aarch64 (#1685)

### CODE REVIEW

**Comment by zorun** [comment]
By the way, this should be backported to the 1.1 stable branch, but can't be cherry-picked because the files have been moved around.  Should I send another pull request against OpenSSL_1_1_0-stable?

**Comment by levitte** [comment]
A parallell PR for 1.1.0 would be nice, thanks.

**Comment by levitte** [comment]
Another thing...  if you think this PR is legally trivial, please edit your commit messages by adding this on a separate line:

```
CLA: trivial
```

If not, we need you to sign a CLA and send it to us, see https://www.openssl.org/policies/cla.html

**Comment by zorun** [comment]
@levitte thanks for the feedback, I have added the CLA tag, and opened #4618 for the 1.1 stable branch.

**Comment by levitte** [comment]
For formality: I agree this seems legally trivial

**Comment by levitte** [comment]
Merged.  bee9c8a4ffd3ec65bb56aaa04423c4f6f9c4012c and 3ba70235be29cc39df7d859df2894c9de2961019

**Pull request closed without merging**
