### PR TITLE
perlasm/x86_64-xlate.pl: fix typos.

### PR DESCRIPTION
**Pull request by dot-asm**
Fix spelling typo in commentary and pair of typo-bugs in the new
cfi_directive package.

### CODE REVIEW

**Comment by dot-asm** [comment]
I took liberty of snatching #2584 with rationale that it was trivial. Though one can argue that it should have been two commits, because commentary typo was introduced in separate commit what was independent of cfi_directive... [I could/should have added [skip ci] because it's not something that can be tested by ci anyway...]

**Comment by dot-asm** [comment]
Split to two commits to facilitate cherry-picking...

**Comment by levitte** [comment]
Approval for all applicable branches.

**Comment by dot-asm** [comment]
Applied.

**Pull request closed without merging**
