### PR TITLE
SM2: add ec_algo_set param to choose which EC algos to use

### PR DESCRIPTION
**Pull request by randombit**
This is based on the commits in #6386 new change is 2bc8ea9 

I investigated adding an SM2 PKEY (and have most of the change saved in a branch if this is useful) but I got hung up the fact that (AIUI) the PKEY is chosen based on the OID in the key, but with SM2 the standard ECC OID is used so an SM2 key is basically indistinguishable from an ECDSA or ECDH key (modulo probably using the sm2p256v1 curve instead of secpxxxr1, which is how we currently decide when to use SM2). So it doesn't seem there is any way to make a distinct SM2 PKEY work. So I looked at what GmSSL does here, which is have a  EVP_PKEY_CTX_ctrl hook to let application switch between algorithms. So I did that. (None of the code is copied from GmSSL, I just reimplemented the same idea.)

@mattcaswell does this seem ok? If not I can try the PKEY approach but I'll need some hints on how to approach it.

### CODE REVIEW

**Comment by mattcaswell** [comment]
There is a distinction between an `EVP_PKEY_ASN1_METHOD`, and an `EVP_PKEY_METHOD`. The former is where we worry about the OIDs etc, but it is the latter that we are concerned about with regards to SM2.

In theory I think we can create an SM2 specific `EVP_PKEY_METHOD` and retain the existing (common) `EVP_PKEY_ASN1_METHOD`. I can think of a couple of ways to do this.

# Option 1: Handle it when creating the EVP_PKEY_CTX

So, if you want "standard" EDSA/ECDH etc then just do:

    ctx = EVP_PKEY_CTX_new(mykey, NULL);

But if you want SM2 algos then you do:

    ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_SM2, NULL);
    EVP_PKEY_CTX_set_pkey(ctx, mykey);

Note, I just made up the `EVP_PKEY_CTX_set_pkey()` function - it doesn't exist yet. But it would just have to: confirm that the `EVP_PKEY` is consistent with the id for the `EVP_PKEY_CTX`; up-ref the EVP_PKEY; and call the pmeth->init() function. Or (possibly) better would be to have:

    ctx = EVP_PKEY_CTX_new_with_pkey(mykey, EVP_PKEY_SM2, NULL);

# Option 2: Create an EVP_PKEY alias

We already have the concept of "aliases" for variants of an `EVP_PKEY`. For SM2 this might look like:

```
const EVP_PKEY_ASN1_METHOD sm2_asn1_meth = {
     EVP_PKEY_SM2,
     EVP_PKEY_EC,
     ASN1_PKEY_ALIAS}
};
```
Normally this idea is used where we have multiple OIDs for the same thing - which is *almost* the situation we have here. We (effectively) have one OID for "standard" EC and an "undefined" OID for SM2. This means that when you first create the EVP_PKEY it will initially have the type of EVP_PKEY_EC (because there is no SM2 specific OID). Then you would have to call some function to "convert" it into one of its alias types, e.g.

    EVP_PKEY_set_alias_type(mykey, EVP_PKEY_SM2);

Again, I made up the function `EVP_PKEY_set_alias_type()`. It would have to verify that the specified nid really was an alias of the base type (e.g. its not valid to convert an RSA key into a DSA key).

Finally we just need to associate the `EVP_PKEY_SM2` nid with a new EVP_PKEY_METHOD for SM2 and everything should "just work". At least in theory :-)


The more I think about it, the more I prefer option 2.

**Comment by mattcaswell** [comment]
One other thing I just thought about with Option 2. We might need to do something clever with the encoding. Otherwise if you have an EVP_PKEY of type EVP_PKEY_SM2 and try and encode it, it might fall over because there is no OID associated with it...

**Comment by randombit** [comment]
@mattcaswell Thanks for your guidance here, I will try implementing Option 2 this week.

**Comment by randombit** [comment]
Closing in favor of #6443 which splits SM2 into its own PMETH and uses API suggested here to toggle using SM2 algos vs NIST algos.

**Pull request closed without merging**
