### PR TITLE
Clean up Windows RNG

### PR DESCRIPTION
**Pull request by xoloki**
This PR removes all of the dangerous Windows entropy gathering routines in favor of standard CryptGenRandom calls, as was discussed in the "Improving OpenSSL default RNG" thread on openssl-dev.  This fixes common, repeatable crashes that happen when running openssl under the VS debugger.  

We will likely lose support for some ancient versions of WINCE with this change, so it should only go in master for now.  I would strongly argue in favor of putting this in 1.1.0, but it should probably not go into 1.0.2 (as much as I'd like to see it there).

### CODE REVIEW

**Comment by vszakats** [comment]
Suggesting `CRYPT_VERIFYCONTEXT | CRYPT_SILENT` in place of `CRYPT_VERIFYCONTEXT` for each occurrence &mdash; to make sure no UI is popping up here.

Ref.: https://msdn.microsoft.com/en-us/library/windows/desktop/aa379886.aspx

**Comment by xoloki** [comment]
Seems like a good idea @vszakats, PR updated.

**Comment by vszakats** [comment]
Thank you @xoloki!

**Comment by ghedo** [comment]
RAND_screen() should go too IMO.

**Comment by richsalz** [comment]
See also https://rt.openssl.org/Ticket/Display.html?id=2485  Probably are some other ones related.

**Comment by xoloki** [comment]
Done @ghedo.  I wasn't sure what to do with libeay.num, so I marked RAND_screen as NOEXIST.  Hopefully I don't need to renumerate the entire file.

**Comment by xoloki** [comment]
I don't have rt access @richsalz, how do I get it?

**Comment by richsalz** [comment]
User guest password guest

**Comment by xoloki** [comment]
Thanks @richsalz.  That RT is exactly what I saw, though in my case it had the decency to crash and not deadlock.  The crash appeared frequently (~66% of the time) when running my application under the VS debugger.

**Comment by ghedo** [comment]
@xoloki RAND_event() too probably. Also, `MAXDELAY` and the code inside the `CURSOR_SHOWING` ifndef (including the comment above it) can be removed too since they seem unused. Might want to check if we actually need all the `#include`s as well.

**Comment by OscarLinden** [comment]
Done @ghedo.  I built on windows and verified that we could get rid of one #include.  

The VC-WIN64A build seems a little broken in general, but I was able to build libeay32.lib so rand_win seems good.

**Comment by ghedo** [comment]
Oh, wow, I didn't know we had a `winrand` app. It was added almost 16 years ago, and since then it received 4 commits in total (all of them being general code improvements, not specific to that file). Should be safe to drop as well IMO.

**Comment by OscarLinden** [comment]
Done @ghedo.  Nothing was even referencing winrand.c.

**Comment by OscarLinden** [comment]
Also, I noticed that the debug-VC configure targets are missing in master.  How do I do a debug windows build now @ghedo?

**Comment by levitte** [comment]
@OscarLinden, thanks for noticing. You need the following patch (to be committed soon):

    diff --git a/util/mk1mf.pl b/util/mk1mf.pl
    index bac5a6f..64ad29a 100755
    --- a/util/mk1mf.pl
    +++ b/util/mk1mf.pl
    @@ -83,8 +83,6 @@ while(<IN>) {
     }
     close(IN);
     
    -$debug = 1 if $mf_platform =~ /^debug-/;
    -
     if ($mf_fipscanisterinternal eq "y") {
            $fips = 1;
            $fipscanisterbuild = 1;
    @@ -1401,6 +1399,7 @@ sub read_options
                    "rsaref" => 0,
                    "gcc" => \$gcc,
                    "debug" => \$debug,
    +               "--debug" => \$debug,
                    "profile" => \$profile,
                    "shlib" => \$shlib,
                    "dll" => \$shlib,

**Comment by xoloki** [comment]
Thanks @levitte!  I don't have a pressing need to build debug now, so I'll wait for that change to hit master.

**Comment by mlt** [comment]
> The VC-WIN64A build seems a little broken in general

Could you elaborate? I'm trying to build 64 bit version of some software using OpenSSL and it gets stuck on `heap_first` within RAND_poll. I'm not sure how slow it could be, but it doesn't seems to get past that no matter how long I wait. I'm on OpenSSL_1_0_2g.

**Comment by xoloki** [comment]
@mlt: I was talking about the master branch, not 1.0.2.  I was able to build the 1.0.2g tarball on windows/x64.  I haven't tried the branch directly.

What are your configuration options?

**Comment by mlt** [comment]
@xoloki The tagged commit builds alright. I used `perl Configure VC-WIN64A no-rc2 no-rc4 no-rc5 no-idea no-bf no-cast no-whirlpool no-md2 no-md4 no-ripemd no-mdc2 no-camellia no-seed no-comp no-krb5 no-gmp no-rfc3779 no-ec2m no-ssl2 no-jpake no-srp no-sctp no-srtp --prefix=c:\OpenSSL-Win64` and I used `ms\ntdll.mak`. I want bare bones with all extras off. The problem was that the execution never got past heap_first call within RAND_poll. Nevertheless, I managed to somewhat apply your 1st commit from here. It gets by, but now Boost ASIO is causing a pain using non-initialized variable in `::SSL_connect`. But it is another story... I just wiggled too many factors at once, I should give a try to 32 bit version again. I didn't plan to hijack this thread...

P.S. I don't want to be a smarty :jeans: about it, but it would be nice to rebase these commits on top of upstream (instead of merging master back) to make things more readable and straightforward. Since this PR was created from *master*, perhaps, you could create an *upstream* branch to follow upstream master and rebase this *master* on top of it instead of merging stuff back.

**Comment by mlt** [comment]
@xoloki Indeed upstream *master* fails to build iif ml64 is used. I have at least 2 more patches, but it is still incomplete. It is easier to use nasm. [I was able to rebase your commits on top of upstream master](https://github.com/mlt/openssl/commits/xoloki/master). It builds fine with nasm. Unfortunately Boost 1.60 can't use that OpenSSL :(

**Comment by levitte** [comment]
I'm noticing that WinCE support appears to disappear...  not that I know enough to say much about it, I do get worried...  @dot-asm, this is your field of knowledge, is it not?  Can you say a few words on the matter?

**Comment by xoloki** [comment]
According to the comments in the removing cruft, it was only particularly
old versions of WinCE that lack CryptGenRandom.  Current MS docs say
WinXP/2k3 is required:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa379942(v=vs.85).aspx

**Comment by richsalz** [comment]
We removed wince support.

**Comment by levitte** [comment]
> We removed wince support

Thanks for the reminder, I totally forgot.  Okay then, no more worries about that!

**Comment by mattcaswell** [comment]
This looks genarlly ok to me, but I'd feel happier if someone with more Windows knowledge than me took a look.
There are a number of merge commits in this PR which aren't allowed, so they need to be removed, and this PR rebased instead. Also "make update" probably needs to be run.

**Comment by xoloki** [comment]
I did the rebase, but I couldn't push to my fork without a single merge at the end.  Is this okay?

**Comment by mattcaswell** [comment]
No - there can't be any merge commits. Also looks like you messed up somehow. This PR is now showing a whole load of changes which aren't yours.

**Comment by xoloki** [comment]
I'll make a new branch and cherry pick all my actual commits. 

The commits from other people showed up days ago, no idea how that happened...

**Comment by ghedo** [comment]
@xoloki why not just do "git rebase master" from inside your branch? You might want to squash into a single commit as well.

**Comment by xoloki** [comment]
I'm on a fork, so I did

git rebase upstream/master

From my fork's master branch.

But then I couldn't push back to my fork without an extra

git pull

Which added another merge.

Will

git rebase master

On my fork's master actually work?

**Comment by OscarLinden** [comment]
Ok, new PR-1079:

https://github.com/openssl/openssl/pull/1079

**Comment by mattcaswell** [comment]
Replaced by #1079

**Comment by ghedo** [comment]
@xoloki then I think you needed to just do `git push --force`.

**Pull request closed without merging**
