### PR TITLE
Adds cross compiling with mingw-w64 to travis

### PR DESCRIPTION
**Pull request by frankmorgner**
This modification to the CI script shows that the master branch does not work with Ubuntu's default installation of 32/64 bit Mingw-w64. I cherry-picked the [CI-commit onto the branch OpenSSL_1_0_2-stable](https://github.com/frankmorgner/openssl/commit/54bd559a6c538456b301e9a6688f438676b0960d), where each configuration works as expected, see https://travis-ci.org/frankmorgner/openssl/builds/80625980.

I suspect that df2ee0e27d2db02660c1d15fe6a3e38be9df0a60 is causing this trouble, but I don't see how to fix this.

### CODE REVIEW

**Comment by frankmorgner** [comment]
I can confirm that this error does not exist before df2ee0e.

**Comment by ghedo** [comment]
1. The `sudo: false` is not needed I think. It should already be the default.
2. The `cache: ccache`  doesn't seem to have much of an effect on build times so it can probably be removed (it's also unrelated to mingw support).
3. Installing `mingw-w64` alone should already bring in all the needed dependencies.

Also, why did you reindent the whole file? It kinda makes reviewing your changes more difficult.

**Comment by frankmorgner** [comment]
ccache is documented here: http://docs.travis-ci.com/user/caching/#ccache-cache but it's true that it does not seem to have any effect.

**Comment by frankmorgner** [comment]
I can revert indenting and the sudo entry, if needed

**Comment by richsalz** [comment]
Please do the minimal set of changes, it will be easier to review.

**Comment by frankmorgner** [comment]
included only the minimal changes, as requested.

Please note, that the problem initially described still persists: This script works against OpenSSL_1_0_2-stable but not against the current master.

**Comment by frankmorgner** [comment]
actually the indenting is required in some cases of the travis-ci parser...

**Comment by frankmorgner** [comment]
The error in master starts here https://travis-ci.org/openssl/openssl/jobs/80677484#L478

**Comment by frankmorgner** [comment]
Also the VC compiler complains about the new defines in asn1t.h, see for example https://ci.appveyor.com/project/frankmorgner/openssl/build/1.0.11/job/auou76e6k0040ax9#L616

**Comment by ghedo** [comment]
@frankmorgner the indentation is not needed. The problem with you change is that the elements inside the exclude block are misaligned. It should be:

```yaml
matrix:
 exclude:
 - os: osx
   compiler: i686-w64-mingw32-gcc
 - os: osx
   compiler: x86_64-w64-mingw32-gcc
```

instead of:

```yaml
matrix:
 exclude:
  - os: osx
   compiler: i686-w64-mingw32-gcc
  - os: osx
   compiler: x86_64-w64-mingw32-gcc
```

That is, the `- os: osx` line should be indented by one space, not two.

**Comment by ghedo** [comment]
Or in alternative the `compiler` lines should be indented by one more space (which is probably the better solution, since it's more consistent with the rest of the file).

**Comment by frankmorgner** [comment]
For me it looks inconsistent if everything was indented with one space and only the indenting in front of `compiler` gets an additional space. By separating the two commits, I tried to make the changes as "reviewable" as possible. But maybe we should even change the indenting to four spaces to match OpenSSL's C style... Anyway, I don't want to fight holy wars, you may change the indenting to match your taste.

What I am more interested in is the actual compile-problem that df2ee0e27d2db02660c1d15fe6a3e38be9df0a60 seems to cause...

**Comment by ghedo** [comment]
> For me it looks inconsistent if everything was indented with one space and only the indenting in front of compiler gets an additional space

Well, that's very different from saying that "the indenting is required". In any case, as @richsalz said, I think it's best to keep the changes to a minimum.

But really, my opinion doesn't really hold that much weight since I'm not part of the OpenSSL team.

> What I am more interested in is the actual compile-problem that df2ee0e seems to cause...

I was able to reproduce the failure locally, and the following change seems to have fixed it:

```diff
diff --git a/include/openssl/asn1t.h b/include/openssl/asn1t.h
index 6467e4a..3d27d2b 100644
--- a/include/openssl/asn1t.h
+++ b/include/openssl/asn1t.h
@@ -107,6 +107,9 @@ extern "C" {
         return &local_it; \
         }
 
+#  define static_ASN1_ITEM_start(itname) \
+        ASN1_ITEM_start(itname)
+
 # endif
 
 /* Macros to aid ASN1 template writing */
```
I don't know if the change makes sense and I can't really run the test suite since it's cross-compiled, but I'll open a pull request in a bit and see what happens.

**Comment by frankmorgner** [comment]
@ghedo in Visual Studio you will get a similar error, see https://ci.appveyor.com/project/frankmorgner/openssl/build/1.0.11/job/auou76e6k0040ax9#L616. You could check if your patch fixes this...

**Comment by richsalz** [comment]
@frankmorgner email me at rsalz at openssl.org ; I would like you to look at my version.

**Comment by richsalz** [comment]
we just pushed something equivalent on all branches. thanks!  build output will show up on openssl-commits mailing list.

**Pull request closed without merging**
