### PR TITLE
Fixed legacy SM2 issue

### LINKED ISSUE #20899: SM2 failed during initialization phase.
## Issue Description
When calling the engine API of OpenSSL 3.0.x for SM2 signature/verification, it will fail in the ctx initialization phase:

https://github.com/openssl/openssl/blob/6aeb42eca97227c8235af0986d1525ee4a916504/apps/speed.c#L3244-L3245

**output:**
```bash
> /usr/local/ssl3/bin/openssl speed -engine qatengine -elapsed -async_jobs 8 -seconds 3 sm2
Engine "qatengine" set.
You have chosen to measure elapsed time instead of user CPU time.
SM2 init failure.
version: 3.0.8
built on: Mon May  8 05:42:28 2023 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL
CPUINFO: OPENSSL_ia32cap=0x7ffef3f7ffebffff:0x40417f5ef3bfb7ef
                              sign    verify    sign/s verify/s
 256 bits SM2 (CurveSM2)      infs      infs      0.0      0.0
```

## Root Cause
The function call stack when the initialization fails is as follows：
```bash
(gdb) bt
#0  evp_pkey_ctx_ctrl_int (ctx=0x748dd0, keytype=408, optype=6, cmd=4097, p1=1172, p2=0x0) at crypto/evp/pmeth_lib.c:1315
#1  0x00007ffff765aa63 in EVP_PKEY_CTX_ctrl (ctx=0x748dd0, keytype=408, optype=6, cmd=4097, p1=1172, p2=0x0) at crypto/evp/pmeth_lib.c:1352
#2  0x00007ffff7636e7e in EVP_PKEY_CTX_set_ec_paramgen_curve_nid (ctx=0x748dd0, nid=1172) at crypto/evp/ec_ctrl.c:286
#3  0x000000000047a546 in speed_main (argc=1, argv=0x7fffffffdbd8) at apps/speed.c:2819
#4  0x000000000044d3f3 in do_cmd (prog=0x705510, argc=9, argv=0x7fffffffdb90) at apps/openssl.c:418
#5  0x000000000044d00e in main (argc=9, argv=0x7fffffffdb90) at apps/openssl.c:298
```

It fails in the _evp_pkey_ctx_ctrl_int_ function because **ctx->pmeth->pkey_id != keytype** 
https://github.com/openssl/openssl/blob/6aeb42eca97227c8235af0986d1525ee4a916504/crypto/evp/pmeth_lib.c#L1321-L1322
The _ctx->pmeth->pkey_id_ is **1172(SM2)**, and the _keytype_ is **408(EC)**

```bash
(gdb) p ctx->pmeth->pkey_id
$1 = 1172
(gdb) p keytype
$2 = 408
```
Under normal circumstances, _keytype_ should also be 1172(SM2). 
But in fact _keytype_ has been fixed in its caller function _EVP_PKEY_CTX_set_ec_paramgen_curve_nid_, which will call _EVP_PKEY_CTX_ctrl_ and set the keytype to **EVP_PKEY_EC**
https://github.com/openssl/openssl/blob/6aeb42eca97227c8235af0986d1525ee4a916504/crypto/evp/ec_ctrl.c#L284-L289

## Proposed Solution
The simplest way to solve this issue is to remove the following condition code in function _evp_pkey_ctx_ctrl_int_
https://github.com/openssl/openssl/blob/6aeb42eca97227c8235af0986d1525ee4a916504/crypto/evp/pmeth_lib.c#L1321-L1322

### PR DESCRIPTION
**Pull request by ShuaiYuan21**
Fixes #20899

### CODE REVIEW

**Comment by slontis** [comment]
This does not seem like the right fix to me.

**Comment by ShuaiYuan21** [comment]
> This does not seem like the right fix to me.

OK, I can come up with some other solutions, like add an new API for setting SM2 curve nid like below:
_This method will introduce more code changes, and the initialization process of sm2 will also be affected_
```C
int EVP_PKEY_CTX_set_sm2_paramgen_curve_nid(EVP_PKEY_CTX *ctx, int nid)
{
    return EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_SM2, EVP_PKEY_OP_TYPE_GEN,
                             EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID,
                             nid, NULL);
}
```
or just change the nid for sm2 case:
```C
int EVP_PKEY_CTX_set_ec_paramgen_curve_nid(EVP_PKEY_CTX *ctx, int nid)
{
    int _nid = nid == EVP_PKEY_SM2 ? EVP_PKEY_SM2 : EVP_PKEY_EC;
    
    return EVP_PKEY_CTX_ctrl(ctx, _nid, EVP_PKEY_OP_TYPE_GEN,
                             EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID,
                             nid, NULL);
}
```
Do you think this make sense? Or do you have any other suggestions?

**Comment by t8m** [comment]
> or just change the nid for sm2 case:
>...

I think this is the right fix.

**Comment by ShuaiYuan21** [comment]
> > or just change the nid for sm2 case:
> > ...
> 
> I think this is the right fix.

Great, I will do it and update the PR, thanks!

**Comment by ShuaiYuan21** [comment]
Code updated, please review it again, thanks!

**Comment by ShuaiYuan21** [comment]
Hi @slontis, could you help to review this again?

**Comment by slontis** [comment]
Would it be possible to add a test?

**Comment by ShuaiYuan21** [comment]
> Would it be possible to add a test?

There are already test cases for SM2 and EC, so I don't think it is necessary to add new test cases.

**Comment by slontis** [comment]
legacy path might be hard to test, but if there was a test already it would not have passed :)

**Comment by slontis** [comment]
Have you tested that this  new code fixed your problem?

**Comment by ShuaiYuan21** [comment]
> Have you tested that this new code fixed your problem?

Yes, this patch can fix my issue. qatengine now can work well with this patch. 
And I agree with you that it is hard to add legacy test case, but for provider API, all test cases can pass.

**Review by slontis — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches after improving the commit message. Thank you for your contribution.

**Comment by Yogaraj-Alamenda** [comment]
@openssl-machine Can you please share us the trend about when is OpenSSL 3.0.9 release which will help us to plan for  the corresponding engine release ?

**Pull request closed without merging**
