### PR TITLE
Add aes-gcm support in afalg engine

### PR DESCRIPTION
**Pull request by ayushsawl**
Hi,

The following patch series adds aes-gcm support in openssl's afalg engine and a afalg gcm test code.

The support is added for key lengths 128, 192 and 256 bits.

Added nids of aes gcm, so that it is initialized during engine_init.

For encrytion and decrytion, the input is copied into iovec structure. The key, operation
type(encryption/decryption) and associated length is set via setsockopt options.
This inputs are send using sendmsg via afalg socket.
The output is collected asynchronously using aio apis, io_getevents() and io_read().

This patch is tested for openssl speed and openssl s_server and openssl s_client tests.

Please review the series and provide your comments.

Thanks,
Ayush
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by ayushsawl** [comment]
reopening PR again for to update cla flag

**Comment by xkqian** [comment]
I am not sure the background, but I have a question, what's the difference betweeen this afalg and the scoket's AF_ALG type in kernel?

**Comment by ayushsawl** [comment]
> I am not sure the background, but I have a question, what's the difference betweeen this afalg and the scoket's AF_ALG type in kernel?

The afalg code in this commit will utilize kernel's Socket type AF_ALG so that user space apps can use kernel crypto api.
cbc support is present in the existing afalg engine. This commits adds the support for aes(gcm).

**Comment by xkqian** [comment]
> > I am not sure the background, but I have a question, what's the difference betweeen this afalg and the scoket's AF_ALG type in kernel?
> 
> The afalg code in this commit will utilize kernel's Socket type AF_ALG so that user space apps can use kernel crypto api.
> cbc support is present in the existing afalg engine. This commits adds the support for aes(gcm).

Thanks for the explanation.  As far as I understand, there is another socket type named IF_KTLS in kernel, it also utilized aes-gcm and implement the record layer in kernel. So, with AF_ALG, what's the peroformance gain compared with IF_KTLS?

**Comment by ayushsawl** [comment]
> > > I am not sure the background, but I have a question, what's the difference betweeen this afalg and the scoket's AF_ALG type in kernel?
> > 
> > 
> > The afalg code in this commit will utilize kernel's Socket type AF_ALG so that user space apps can use kernel crypto api.
> > cbc support is present in the existing afalg engine. This commits adds the support for aes(gcm).
> 
> Thanks for the explanation. As far as I understand, there is another socket type named AF_KTLS in kernel, it also utilized aes-gcm and implement the record layer in kernel. So, with AF_ALG, what's the peroformance gain compared with AF_KTLS?

The AF_KTLS is not a valid type in mainline kernel, so i have not tried testing with that.

**Comment by mattcaswell** [comment]
I'm taking this out of the 3.0 beta1 milestone. Its too close IMO for such a significant feature to be added.

**Comment by t8m** [comment]
As engines are deprecated in 3.0 I do not think we want to add new features to the existing engines shipped in 3.0. I am closing this.

**Pull request closed without merging**
