### PR TITLE
Tweak option error messages

### LINKED ISSUE #10773: apps/openssl: error messages for unknown command line options are inconsistent
The error messages for unknown command line options are very inconsistent. Here is an incomplete list of examples, taken from https://github.com/openssl/openssl/pull/10132#issuecomment-571358064:

```
msp@msppc:~/src/openssl$ for cmd in cms ocsp s_client smime ts; do openssl $cmd -verbose ; done

cms: Unrecognized flag verbose
ocsp: Unrecognized flag verbose
ocsp: Use -help for summary.
s_client: Option unknown option -verbose
s_client: Use -help for summary.
smime: Unrecognized flag verbose
smime: Use -help for summary.
ts: Unrecognized flag verbose
ts: Use -help for summary.
```

### PR DESCRIPTION
**Pull request by richsalz**
Better messages for unknown option, unknown cipher, unknown digest.

Fixes #10773

Should be easy to cherry-pick.

### CODE REVIEW

**Comment by mspncp** [comment]
A great impovement, indeed!

```
     11 cmd: Unknown cipher foobar
      7 cmd: Unknown message digest foobar
     35 cmd: Unknown option -foobar
```
But don't you think it would make the output even more readable if you would add colons?

```
     11 cmd: Unknown cipher: foobar
      7 cmd: Unknown message digest: foobar
     35 cmd: Unknown option: -foobar
```

**Comment by mspncp** [comment]
> Should be easy to cherry-pick.

A cherry-pick to 1.1.1. would be o.k for me. After all, it's an improvement of the error diagnostics.

**Comment by richsalz** [comment]
fixup commit pushed.

**Comment by levitte** [comment]
It's at least arguable of this should go back to 1.1.1. Changed error messages in a stable release is generally not seen as stable. I would rather avoid that.

**Comment by t-j-h** [comment]
I have removed the branch: 1.1.1 label - consider it a "hold" for any back fit.

**Comment by mspncp** [comment]
> It's at least arguable of this should go back to 1.1.1. Changed error messages in a stable release is generally not seen as stable. I would rather avoid that.

That's ok for me. I was already tempted to ask whether error messages are considered part of the 'API contract', but then I refrained from doing it. Anyway, if there is a non-negligible chance to break existing scripts because they parse the error messages, it's better not to do it.

**Comment by mspncp** [comment]
Merged to master as e0e68f9e34585084038fba768fb2eecb5dd1ddf3, thanks!

**Pull request closed without merging**
