### PR TITLE
remove setup-perl action from windows jobs

### PR DESCRIPTION
**Pull request by quarckster**
Windows runners have Perl preinstalled.
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by h-vetinari** [comment]
Sidenote: the default perl in the runner images [drags](https://github.com/actions/runner-images/issues/5459) in much of GCC onto the PATH, which is obviously a source of great fun on windows (and something that both upstream strawberry perl as well as GHA have refused to fix). It might ultimately be cleaner to depend on a less troublesome perl, even if it's part of the image.

**Comment by quarckster** [comment]
> Sidenote: the default perl in the runner images [drags](https://github.com/actions/runner-images/issues/5459) in much of GCC onto the PATH, which is obviously a source of great fun on windows (and something that both upstream strawberry perl as well as GHA have refused to fix). It might ultimately be cleaner to depend on a less troublesome perl, even if it's part of the image.

I'm not sure how the action `shogo82148/actions-setup-perl` solves this problem. Does it delete preinstalled Perl or change PATH?

**Comment by quarckster** [comment]
> > Sidenote: the default perl in the runner images [drags](https://github.com/actions/runner-images/issues/5459) in much of GCC onto the PATH, which is obviously a source of great fun on windows (and something that both upstream strawberry perl as well as GHA have refused to fix). It might ultimately be cleaner to depend on a less troublesome perl, even if it's part of the image.
> 
> I'm not sure how the action `shogo82148/actions-setup-perl` solves this problem. Does it delete preinstalled Perl or change PATH?

Answering to myself. Actually, yes https://github.com/shogo82148/actions-setup-perl/blob/main/src/strawberry.ts#L78

**Comment by h-vetinari** [comment]
> I'm not sure how the action `shogo82148/actions-setup-perl` solves this problem.

If things work as in this PR, that's alright I guess. It was more of a heads-up about the idiosyncrasies of the built-in perl.

**Comment by t8m** [comment]
Merged to the master branch. Thank you.

**Pull request closed without merging**
