### PR TITLE
sha/keccak1600.c: add couple of soft asserts.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by levitte** [comment]
Are those function intended to remain internal or are they going to be accessible publically?

**Comment by t-j-h** [comment]
If the caller has restrictions on the input parameter ranges they should not be implemented as an assert ever ...

**Comment by dot-asm** [comment]
> Are those function intended to remain internal or are they going to be accessible publically?

Define "publicly". They won't be exported from shared library, no. But they will be visible in libcrypto.a.

**Comment by dot-asm** [comment]
> If the caller has restrictions on the input parameter ranges they should not be implemented as an assert ever ...

I want to remind that this is *soft* assert, i.e. one that is compiled as no-op in production build. Such asserts serve dual purpose: a) kind of documentation; b) when code is integrated into EVP it serves as development-time safety net to catch malformed EVP_MD.

**Comment by levitte** [comment]
> > Are those function intended to remain internal or are they going to be accessible publically?
> 
> Define "publicly". They won't be exported from shared library, no. But they will be visible in libcrypto.a.

I'm thinking "publically" as an interface that we publically declare, i.e. that are (or will be) declared in a header file in `include/openssl/`.

The point is that if `r` is a value we control, i.e. that *we* have a layer above the functions in this file (I imagine in EVP or in an engine) where the value of `r` has been checked, then I'm fine with this change.  If it's a value that we just pass uncontrolled from the calling application, then I'm with @t-j-h.
So in essence, are those asserts checking *our* screwups, or the calling application's?

**Comment by dot-asm** [comment]
> The point is that if r is a value we control

Yes, `r` is the value that we will have full control over. asserts are meant to catch internals screw-up during building real SHA-3/SHAKE upon this primitive.

**Comment by levitte** [comment]
Cool.  I've no issues with this then.

**Comment by dot-asm** [comment]
> a) kind of documentation;

If you need to know the reason for why I decided to add asserts is that for a fresh eye it's actually not obvious that inner loops are valid. Yes, commentary discusses possible values for `r`, but I felt that explicit reminder (in form of *soft* assert) is appropriate. One can view it as "all the values discussed in commentary are actually divisible by 8, didn't you notice?"

**Pull request closed without merging**
