### PR TITLE
Add support for BSD-ppc, BSD-ppc64 and BSD-ppc64le configs

### PR DESCRIPTION
**Pull request by pkubaj**
While OpenSSL currently works on FreeBSD/powerpc platforms, it uses a generic configuration without AltiVec / VSX.
CLA: trivial

### CODE REVIEW

**Comment by mattcaswell** [comment]
I don't have access to these platforms to test them. But from code inspection alone these changes seem reasonable.

I would point out our (recently updated) platform policy here:
https://www.openssl.org/policies/platformpolicy.html

Which says:
> Support for a new platform should only be added if it is being adopted as a primary, secondary or community platform.

Since this PR effectively adds new platforms, we would at least need to find someone willing to be the community platform maintainer. @pkubaj is this something you are willing to take on as a result of this PR? Or do you know someone who would be willing to take on that role? From the platform policy I linked to above - the responsibility of the maintainer is:

> If defects are raised that are specific to a community platform then the community maintainer may be contacted to help find a resolution. If a community maintainer is unresponsive, or unable to provide fixes then the platform may be moved to "unadopted".

**Comment by pkubaj** [comment]
I'm fine with being a maintainer.

**Review by mattcaswell — APPROVED** [review]
Approved, subject to https://github.com/openssl/web/blob/master/policies/platformpolicy.html being updated to reflect @pkubaj as being the community maintainer for these platforms

**Comment by mattcaswell** [comment]
> I'm fine with being a maintainer.

Cool!

**Comment by pkubaj** [comment]
Am I supposed to make a PR to update platformpolicy.html?

**Comment by mattcaswell** [comment]
> Am I supposed to make a PR to update platformpolicy.html?

If you are willing to do that, then that would be great!

**Review by paulidale — APPROVED** [review]

**Comment by pkubaj** [comment]
Would it be possible to also merge to 1.1.1?

**Review by paulidale — APPROVED** [review]
I don't think this is suitable for back porting to 1.1.1 or 3.0.  It doesn't seem like a bug fix and the changes go beyond only being configuration additions.

**Comment by mattcaswell** [comment]
> 24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set.

Not sure why the bot thinks this since there haven't been any updates. Setting the label manually.

**Comment by mattcaswell** [comment]
Ah.I just came to merge this and noticed the "CLA: trivial" line in the commit message. Unfortunately I think this goes beyond our definition of trivial and so I think a CLA is required. Could you provide one?

https://www.openssl.org/policies/cla.html

**Comment by paulidale** [comment]
Agreed, well beyond trivial.

**Comment by mattcaswell** [comment]
@pkubaj - looks like this is still holding waiting for a CLA. Will you be able to submit one?

**Comment by pkubaj** [comment]
Yes, I have it printed out, but I don't have a scanner at home, so will need to scan it at work next week.

**Comment by mattcaswell** [comment]
@pkubaj - CLA has now been received - thanks! It looks like this PR now needs a rebase - could you do that?

**Comment by mattcaswell** [comment]
Ah...unfortunately you added a merge commit. You need to do a rebase instead (we don't allow merge commits).

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the contribution.

**Pull request closed without merging**
