### PR TITLE
Doc: fix reference to deprecated methods.

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Small and quick doc fixup.

##### Checklist

- [X] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
For what branches is this intended?

**Comment by FdaSilvaYY** [comment]
@levitte : master for sure, this is not eligible to 1.1.1 and its security-fix-mode.
It will not cherry-pick to 1.1.0 and olders,  as doc folder layout is different.

**Comment by mspncp** [comment]
> @levitte : master for sure, this is not eligible to 1.1.1 and its security-fix-mode.

I don't see any reason why this fix shouldn't be backported to 1.1.1. It is not in security-fix-only-mode.

**Comment by FdaSilvaYY** [comment]
@mspncp : Yes, you're right, i confused 1.1.0 with 1.1.1.
so, it can be cherry pick to 1.1.1 too.

**Comment by paulidale** [comment]
@levitte has veto of course.

**Comment by levitte** [comment]
I have no comment.

**Comment by FdaSilvaYY** [comment]
ping ! good to merge ?

**Comment by mspncp** [comment]
Merged to master (56bc3ea0a4) and 1.1.1. (deab38a4638b). Thank you!

**Pull request closed without merging**
