### PR TITLE
Fix memory leak in ASN.1

### PR DESCRIPTION
**Pull request by ekasper**
Affects 1.1.0 dev branch only; introduced around commit
f93ad22f6adb00e722c130e792799467f3927b56

### CODE REVIEW

**Comment by benlaurie** [comment]
+1

**Comment by ekasper** [comment]
Updated - needs re-review.

**Comment by benlaurie** [comment]
+1

**Comment by ekasper** [comment]
Pushed with minor tweaks - had to correct a few mistakes in d2i_test now that --strict-warnings is working again.

**Pull request closed without merging**
