### PR TITLE
Remove void* type cast

### PR DESCRIPTION
**Pull request by likunyur**
I think void* type pointers don't need to be cast.

CLA: trivial

### CODE REVIEW

**Comment by kaduk** [comment]
While it's true that in C, a pointer of type `void *` may be freely converted to any other pointer type without cast, the same cannot be said of C++.  My recollection (which could be wrong) is that we do make some effort to support compiling our sources with a C++ compiler, in which case we would want to keep the casts.

Separately, if we do want to take this cleanup, the bot has flagged this as "cla required".  I would say it is legally "trivial" and thus you could avoid the need to submit a CLA by modifying the commit messages to include, on a separate line in the body of the commit message, "CLA: trivial".  Otherwise a CLA would need to be submitted, as per https://github.com/openssl/openssl/blob/master/CONTRIBUTING.md

**Comment by mattcaswell** [comment]
> My recollection (which could be wrong) is that we do make some effort to support compiling our sources with a C++ compiler, in which case we would want to keep the casts.

Our public headers need to be consumable by a C++ compiler - but internally we use C and expect a C compiler.

**Comment by mattcaswell** [comment]
Separately though, I think some of these casts may have documentary value - so I'm not entirely convinced that removing them is necessary.

**Comment by levitte** [comment]
> Separately though, I think some of these casts may have documentary value - so I'm not entirely convinced that removing them is necessary.

In all cases but one, the casts add no information at all, as they just replicate the plainly visible type that the `void *` is coerced into.  In the one remaining case, there's a comment that explains what's being done than the cast.

So in my judgment, the removed casts add zero value.

**Comment by paulidale** [comment]
I prefer having the casts in place as a matter of style.

**Comment by levitte** [comment]
> I prefer having the casts in place as a matter of style.

My preference is the opposite, at least when it's so clearly redundant.

**Pull request closed without merging**
