### PR TITLE
Add CHANGES for 1.0.2s

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by mattcaswell** [comment]
Not sure what NEWS will look like after the release scripts do there thing, if there are no entries in the list of updates. Will it look a bit strange?

**Comment by levitte** [comment]
I removed the NEWS title line for the empty sectino, that should be better.

**Comment by mattcaswell** [comment]
> I removed the NEWS title line for the empty sectino, that should be better.

I suspect that will make the release scripts barf.

**Comment by levitte** [comment]
The release scripts can be fixed

**Review by mattcaswell — APPROVED** [review]
Ok then.

**Comment by levitte** [comment]
Merged.

bb36ec5f5bc6a34370e821260ad4f620dd16ecec Add CHANGES for 1.0.2s

**Pull request closed without merging**
