### PR TITLE
Update BN_add.pod documentation so they are consistent with their header declarations. Fixes issue #19521

### PR DESCRIPTION
**Pull request by JulieDzeze1**
Update BN_add.pod documentation so they are consistent with their header declarations. Fixes issue #19521 on OpenSSL's master branch.

### CODE REVIEW

**Comment by JulieDzeze1** [comment]
I created a PR to meet the requirements for the SWE assignment for CSEC 659. @bbbrumley please review when you get the chance. Thank you!

**Comment by bbbrumley** [comment]
Looks good to me :) Thank you, @JulieDzeze1

**Review by romen — APPROVED** [review]
LGTM: it looks like these `const`s predate even 1.1.1 in the headers!

Thanks for your contribution @JulieDzeze1

**Review by romen — CHANGES_REQUESTED** [review]
Sorry @JulieDzeze1 I was too hasty in my review: we would need you to rebase your commit on top of latest `master`, as we do not allow Merge commits.

Can you handle this or do you need furhter guidance?

**Comment by romen** [comment]
I agree with CLA: trivial

**Comment by romen** [comment]
This would fix #19521 but for some reason the GitHub UI does not let me link the issue with this PR or viceversa.

**Comment by JulieDzeze1** [comment]
> Sorry @JulieDzeze1 I was too hasty in my review: we would need you to rebase your commit on top of latest `master`, as we do not allow Merge commits.
> 
> Can you handle this or do you need furhter guidance?

H

**Comment by JulieDzeze1** [comment]
> Sorry @JulieDzeze1 I was too hasty in my review: we would need you to rebase your commit on top of latest `master`, as we do not allow Merge commits.
> 
> Can you handle this or do you need furhter guidance?

Hi, I've attempted to rebase my commit but this is a little complicated since this is a forked repository from the main project. How should I approach it?

**Comment by t8m** [comment]
> Hi, I've attempted to rebase my commit but this is a little complicated since this is a forked repository from the main project. How should I approach it?

You do not even need to rebase against fresh master branch. Just remove the merge commit with `git reset --hard HEAD~ ; git push --force`.

**Comment by romen** [comment]
> > Hi, I've attempted to rebase my commit but this is a little complicated since this is a forked repository from the main project. How should I approach it?
> 
> You do not even need to rebase against fresh master branch. Just remove the merge commit with `git reset --hard HEAD~ ; git push --force`.

@JulieDzeze1 this should fix the issue. Do you need more help?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM - thanks

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to all the active branches. Thank you for your contribution.

**Pull request closed without merging**
