### PR TITLE
test/evp_test.c: If no algorithm was specified, don't try to check for DES

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
I forgot to say that this is meant for master *and* 1.1.0.  Fine with you @richsalz?

**Comment by levitte** [comment]
Merged in master 31b69e9a26c5b127ce273bc5834b9e13e5e25556

**Comment by richsalz** [comment]
yes for both.

**Comment by levitte** [comment]
Goody good.  Merged in 1.1.0 branch, 1968ea9850f7e50609284756ca78e465e5ee4fb9

**Pull request closed without merging**
