### PR TITLE
STORE: Fix OSSL_STORE_attach() to check |ui_method| before use

### LINKED ISSUE #12830: OSSL_STORE_attach() fails when ui_method is NULL
MacOS 10.15.6, Xcode-11.7, current OpenSSL master.

It looks like `OSSL_STORE_attach()` in `crypto/store/store_lib.c` forces a call to `ossl_pw_set_ui_method()` here https://github.com/openssl/openssl/blob/b434b2c08d2025936fb8b7ece3a5908613333f6b/crypto/store/store_lib.c#L971, even if `ui_method` and/or `ui_data` are NULL. Which in turn fails assertion here: https://github.com/openssl/openssl/blob/b434b2c08d2025936fb8b7ece3a5908613333f6b/crypto/passphrase.c#L84

Here's the call to `OSSL_STORE_attach()`:
```c
. . . . .
     pkey = NULL;
     OSSL_STORE_CTX *cts;
     T(cts = OSSL_STORE_attach(bp, "file", NULL, NULL, NULL, NULL, NULL, NULL));
. . . . .
```

The error message is
```
	OSSL_STORE_attach:	crypto/passphrase.c:84: OpenSSL internal error: Assertion failed: data != NULL && ui_method != NULL
```

I stumbled upon this problem running GOST engine test: https://github.com/gost-engine/engine/blob/master/test_sign.c (see issue https://github.com/gost-engine/engine/issues/276)

@levitte 
I'm working on a small reproducer (which, hopefully, won't be a big deal), but in the meanwhile, perhaps, you could see what the problem is, and maybe even how to fix it.

### PR DESCRIPTION
**Pull request by levitte**
ossl_pw_set_ui_method() demands that the passed |ui_method| be
non-NULL, and OSSL_STORE_attach() didn't check it beforehand.
We might as well enable passphrase caching while we're at it, just
like OSSL_STORE_open() does.

Fixes #12830

### CODE REVIEW

**Comment by levitte** [comment]
@mouse07410, if you wouldn't mind trying this?

**Comment by mouse07410** [comment]
> @mouse07410, if you wouldn't mind trying this?

@levitte certainly! Will report in a few minutes, when the build finishes.

**Comment by mouse07410** [comment]
```
. . . . .
100% tests passed, 0 tests failed out of 10
```

I'm happy, and it works!  Thank you!

**Comment by t-j-h** [comment]
And where in the documentation would it indicate passphrase caching is enabled or the behaviour of the API has changed?
Mixing in that sort of change in with a clear bugfix seems inappropriate to me - but even if it is appropriate this sort of change needs to be reflected in the docs I think.

**Comment by levitte** [comment]
@t-j-h, that's how the pre-provider (what we have in 1.1.1) OSSL_STORE does, so that is a regression fix.
Although... that's how the old 'file:' loader works rather than the entirety of the API, so it's true that the caching may be misplaced.

**Comment by levitte** [comment]
I've added a squash commit that removes all passphrase caching calls in the library code.  @mouse07410, would you mind verifying that this still works as expected in your scenario?

**Comment by t-j-h** [comment]
I don't see any mention of caching or anything along those lines in the 1.1.1 docs ... hence I suspect this would be a surprise to users.

**Comment by levitte** [comment]
> I don't see any mention of caching or anything along those lines in the 1.1.1 docs ... hence I suspect this would be a surprise to users.

Because the 'file:' loader makes several guesses of what it just loaded is, it may try to decrypt it more than once.  So no, the real surprise, when I developed the original 'fils:' loader, was when it prompted for more than one password on the same object.  This is a short term cache, maybe you misunderstood it to be a long term one.

**Comment by levitte** [comment]
doc/man7/ossl-store-file.pod needs a bit of a rewrite, and a rename to conform to how we document provider-side implementations.  Passphrase caching should be mentioned there.  I'll do that in a separate PR.

**Comment by t-j-h** [comment]
If this is simply to be able to not prompt twice when you are handling a chain of logic for the same authentication context then it isn't a cache and it shouldn't be optional - it is just an implementation strategy. API naming it as a cache isn't the right approach IMHO for that context. And this naming was not present in the 1.1.1 code (I did go and read that code when you pointed that you thought this was fixing a bug in bringing the code forward). 

I'm not against the logic you've mentioned and the need for it - but it should be renamed I think - but that can be for another PR. What's here is a simply fix now - although you've reverted a "cache" call - I assume you basically want consistency in the behaviour of the two API paths.

**Review by t-j-h — APPROVED** [review]

**Comment by mouse07410** [comment]
@levitte I've tested the current (at the time of this post ;) version of this PR, and it works fine - aka fixes #12830 .

It can be merged, as far as I'm concerned. ;-)

Thanks!

**Comment by levitte** [comment]
> although you've reverted a "cache" call - I assume you basically want consistency in the behaviour of the two API paths.

Most of all, it's not necessary, because it should really be done in `providers/implementations/storemgmt/file_store.c`...  and it does, although indirectly, as the cache is enabled in the `OSSL_DECODER_from_bio()` call, i.e. exactly where it should be.  So the cache enabling calls in the API functions were redundant, and practically useless.

As for naming, I have no problem renaming "cache" to a better name, but that'll have to be someone else suggesting it, 'cause I can't think of one.

**Comment by levitte** [comment]
Merged

9f604ca13ddc99e17ba37fed9281fbd1b71149a9 STORE: Fix OSSL_STORE_attach() to check |ui_method| before use

**Pull request closed without merging**
