### PR TITLE
Work around Travis "virtual memory exhausted" error

### PR DESCRIPTION
**Pull request by mattcaswell**
This is a trial build to see if this fixes the "virtual memory exhausted" error

### CODE REVIEW

**Comment by mattcaswell** [comment]
Rebased and taken out of WIP now that #3600 has gone in. This works by adding "--debug" to the build that runs out of virtual memory compiling curve25519.c. This has the effect of forcing -O0 which is much less memory intensive than -O3.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by richsalz** [comment]
should we update the FAQ or something?  Or are people not going to run into this?

**Comment by mattcaswell** [comment]
> should we update the FAQ or something? Or are people not going to run into this?

Let's wait until people do. I'm not sure how much of this is just because of the environment that travis is running in. In any case the solution here (reduce the optimisation level), is likely not suitable for others.

**Pull request closed without merging**
