### PR TITLE
Disable MDC2 by default.

### PR DESCRIPTION
**Pull request by richsalz**
##### Checklist

- [X] documentation is added or updated
- [ ] tests are added or updated
- [X] CLA is signed

##### Description of change

Disable MDC2 by default.

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
Can I suggest to enable it back in Travis, along with rc5 and md2 ? ;)

**Comment by richsalz** [comment]
excellent idea; updated commit pushed.

**Comment by mattcaswell** [comment]
Can you move "no-mdc2" from the "no-<alg>" section in INSTALL into the "enable-<alg>" section?

**Comment by richsalz** [comment]
good catch, @mattcaswell; done.

**Comment by dot-asm** [comment]
Is it really appropriate to do that kind of thing within minor release? Of course one can argue that those who see binary compatibility as not loosing symbols in shared library have the option to enable-mdc2, but do we have to make life harder than it needs to be? It's a lot of things to keep track of...

**Comment by levitte** [comment]
@dot-asm is right, we can't do this before 1.2.0

**Comment by richsalz** [comment]
okay, will someone plus-one my reverting this?

**Comment by levitte** [comment]
+1 for reverting it

**Comment by richsalz** [comment]
reverted.

**Comment by t-j-h** [comment]
The change in master should stay. It is only a change on a release branch that is target for reverting.
@richsalz had this as a pull request against master - and for that it was approved.

**Comment by kroeckx** [comment]
I think we're currently trying to keep master and 1.1.1 the same?

**Comment by t-j-h** [comment]
Master the the development version and should be open for all development - that is its purpose. When it comes time to determine the appropriate point to start subsequent releases we sort that out. But freezing master for API-and-ABI-compatible-only changes is simply not something we have done. 
The revert comment would make sense if the change was being applied to 1.1.0 - but it wasn't - it was on master. Although we note that we preserve ABI compatibility between X.Y.Z where Z is the varying item in our policy that hasn't always been the case and it absolutely has not been tested.

So if someone wants to declare that master is frozen for all work that isn't going into 1.1.1 then that needs to be done (with corresponding team vote) - however that isn't something I was aware of at all - and I don't think we have been applying that as a test across all the checkins since 1.1.0 was released.

**Comment by kroeckx** [comment]
I think we have at least agree that we need to branch if there is
such a change in master, and it hasn't been needed yet. And I
guess we don't find this change important enough to create the
extra effort of creating that branch.

**Comment by richsalz** [comment]
right, like kurt says, not worth branching just for this.

**Comment by t-j-h** [comment]
So do you all believe that **every** change in master since 1.1.0 was released is ABI compatible?

**Comment by mattcaswell** [comment]
@t-j-h, yes. I am not aware of any ABI incompatible changes in master and would have minus oned it had I seen one.

**Comment by tmshort** [comment]
Disabling mdc2 causes issues with unit tests. See: https://github.com/openssl/openssl/pull/1946

**Comment by richsalz** [comment]
MDC2 is used by OpenPGP.  Closing this.

**Pull request closed without merging**
