### PR TITLE
CI: add builds covering a number of different compiler versions

### PR DESCRIPTION
**Pull request by paulidale**
- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
I like this idea but not sure if we really need `make test` here. What shall we do to deal with tests failed because of buggy minor version of the compiler?

**Comment by paulidale** [comment]
Worry about that when it happens?
I don't see how testing can hurt otherwise.

**Review by beldmit — DISMISSED** [review]
LGTM

**Comment by t8m** [comment]
> I don't see how testing can hurt otherwise.

I am now being concerned about the number of builds we do on pull requests. IMO they are too many with this change. Should this be run only on push? Or maybe we should move some run checker builds to push only?

**Comment by paulidale** [comment]
These are intended to run on push.

**Comment by paulidale** [comment]
I've pushed the "push" change.

We ought to review which builds run when at some point.

**Comment by t8m** [comment]
You've also added the --strict-warnings with the fixup, is that tested to work with all the compiler versions?

**Comment by paulidale** [comment]
Push a temporary commit to verify the builds.

**Review by t8m — APPROVED** [review]
OK, now I believe you the --strict-warnings work. OK to merge without the not for merge commit of course.

**Comment by levitte** [comment]
Of course, the Windows CIs deliver...

**Review by levitte — APPROVED** [review]
I like!

**Comment by paulidale** [comment]
Removed the extra commit and squashed things ready for merge.
No re-approval required.

**Comment by paulidale** [comment]
To be merged before the 3.0 branch.

**Comment by paulidale** [comment]
Merged.  Thanks for the feedback.

**Comment by romen** [comment]
@paulidale what are your thoughts about backporting this to 1.1.1?

**Pull request closed without merging**
