### PR TITLE
Fix coverity issues

### PR DESCRIPTION
**Pull request by slontis**
CID : 1458169 RESOURCE LEAK ffc_params_generate.c - False positive, but addressed another Leak in adjacent code
CID : 1458171 UNCHECKED RET apps/pkeyutl.c
CID : 1458173 DEAD CODE ffc_params_generate.c
CID : 1458174 RESOURCE LEAK ssl_lib.c

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
I have to admit that I was funnier when @iamamoose was posting these reminders ;-)

**Comment by slontis** [comment]
Thanks for reviewing. Merged to master.

**Comment by bernd-edlinger** [comment]
It would be even more funny if the machine would post reminders once a month or so
for stalled PRs ;-)

**Comment by iamamoose** [comment]
> It would be even more funny if the machine would post reminders once a month or so
> for stalled PRs ;-)

sure, define "stalled" and I can make it happen :)

**Comment by richsalz** [comment]
> define "stalled"

No comments or pushes in n weeks, where n >= 3.  I would make a weekly email summary of "stalled PR's" because you don't want the reminder in the PR to reset the stalled timer.

**Comment by iamamoose** [comment]
> > define "stalled"
> 
> No comments or pushes in n weeks, where n >= 3. I would make a weekly email summary of "stalled PR's" because you don't want the reminder in the PR to reset the stalled timer.

thanks. https://github.com/openssl/tools/issues/61

**Pull request closed without merging**
