### PR TITLE
Allow logging session secret values

### PR DESCRIPTION
**Pull request by zakjan**
See https://rt.openssl.org/Ticket/Display.html?id=4201

### CODE REVIEW

**Comment by richsalz** [comment]
As written, this patch is not acceptable for a couple of reasons:
-  It has all sorts of magic numbers to look inside the handshake stuff, and should instead be integrated into the statem and/or record layer stuff.
- It relies on a magic environment variable that can be inherited from anywhere, sort of.
- There is no ```#ifdef``` control to remove it from the build.
- There is no explicit SSL_OP option to turn it on

**Comment by zakjan** [comment]
> It relies on a magic environment variable that can be inherited from anywhere, sort of.
> There is no explicit SSL_OP option to turn it on

I guess that is the reason why NSS chosen just an env var, nothing more. It allows debugging network communication of any application that uses the library. Otherwise it is not possible for ephemeral cipher suites.

**Comment by richsalz** [comment]
It's not safe.  The risk that someone using this in production will get "tricked" into exposing session keys is too great.

**Comment by zakjan** [comment]
I see. Would having it off by default and enabling by `#ifdef` suffice?

**Comment by richsalz** [comment]
I want both an OPENSSL_NO_KEYLOG, which is set by default so you need to config -enable-keylog.  And an SSL_OP_LOG_KEYS to turn it on for a particular SSL object.

But others on the team might think differently, suggest you post a link and bring this up on openssl-dev.

**Comment by richsalz** [comment]
No progress on this, closing.  Please open a new PR when it's done "safely" as described above.

**Pull request closed without merging**
