### PR TITLE
config: enable ACVP test case if FIPS is enabled.

### PR DESCRIPTION
**Pull request by paulidale**

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
In strict sense this is not a bug fix so should it be merged in 3.0?

**Comment by paulidale** [comment]
If we'd not missed the relevant part of the standard, this would definitely have been included.
It also simplifies things :)

**Comment by paulidale** [comment]
It's additional testing....

**Comment by paulidale** [comment]
Merged, thanks for the review.

**Pull request closed without merging**
