### PR TITLE
Rework how providers/fipsmodule.cnf is produced, and have a separate test/fipsmodule.cnf

### LINKED ISSUE #15166: The fipsmodule.cnf to be installed cannot be created by openssl fipsinstall in cross-compiled builds
#13684 broke cross-compiled builds by making `install_fips` automatic.

Our project cross-compiles OpenSSL for ARM on x86_64 as part of a larger distribution. Other open-source components of this distribution have dependencies on OpenSSL. As such, we depend on the `install` target working properly so we can build OpenSSL and install the artifacts into a staging directory which we then specify on the "configure" command lines when we subsequently build those other components. Prior to #13684 the install target completed successfully (and `providers/fips.so` was getting installed into the correct location). Now the install target in our cross-compile builds fails with:

`make[2]: *** No rule to make target 'providers/fipsmodule.cnf', needed by 'install_fips'.  Stop.`

This aborts installation and prevents the copying of `fips.so` into our staging directory.

We use this command line to configure OpenSSL:

`./Configure linux-generic32 -DL_ENDIAN -DOPENSSL_NO_COMP shared --prefix=/usr --openssldir=/conf/openssl enable-fips no-zlib no-comp no-tests`

It appears that `no-tests` prevents the creation of the `providers/fipsmodule.cnf` Makefile target (which we can't actually build anyway when cross-compiling). Since `providers/fipsmodule.cnf` is now a prerequisite for installing `fips.so` into our staging directory, that module is missing from our final product.

### PR DESCRIPTION
**Pull request by levitte**
`providers/fipsmodule.cnf` has the integrity checksum but not the installation checksum, and is installed alongside the FIPS module itself.  It's up to the security officer to run `openssl fipsinstall` to add the installation checksum.

`test/fipsmodule.cnf`, on the other hand, is produced with both an integrity checksum and installation checksum, so is installed locally for testing purposes.

Fixes #15166

### CODE REVIEW

**Comment by levitte** [comment]
This replaces #15174.
It's currently in draft because it's incomplete...  only the Unix build file template has been modified so far.

**Comment by levitte** [comment]
Even though this is in draft, the principal changes are in place and are worth reviewing as such.  The rest of the work is essentially only to modify the other build file templates.

**Comment by levitte** [comment]
Note that with these changes, `openssl fipsinstall` could be modified to *only* add the install checksum / indicator.  I haven't done that in this PR, and am thinking that it's for another one.

**Comment by levitte** [comment]
Not draft any more.

**Review by t8m — APPROVED** [review]
Nice work. A bigger change than I expected.

**Comment by levitte** [comment]
Merged

a2405c5f2019707d1a4306f152faa9ccda5f4cd5 Rework how providers/fipsmodule.cnf is produced
6dd07a9328950ff8bf3f95ad35caf3a4e1e33a15 Build file templates: rework how general dependencies are computed
f5657ce8e664cbb1e3314f54385b9a4d653e6bae Build file templates: rework FIPS module installation
7c499c7da93561fd620338cc4f8691c1dbc9ee36 TEST: Add test specific fipsmodule.cnf, and use it

**Pull request closed without merging**
