### PR TITLE
DH_check: Emphasize the importance of return value check

### PR DESCRIPTION
**Pull request by t8m**
##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]

**Comment by kroeckx** [comment]
I think it's still not very clear. I think a 0 return means some error happened that prevented us from checking things. A 1 return value means we did the checks and you should look at codes to see if they're good parameters.

**Comment by t8m** [comment]
> I think it's still not very clear. I think a 0 return means some error happened that prevented us from checking things. A 1 return value means we did the checks and you should look at codes to see if they're good parameters.

I'll merge this as it is better than nothing. You can submit an improvement PR if you want.

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches. Thank you for the reviews.

**Pull request closed without merging**
