### PR TITLE
Open ssl 1 1 0 stable

### PR DESCRIPTION
**Pull request by rrip**
Corrected Visual Studio compile warning C4090 in lhash.h

### CODE REVIEW

**Comment by rrip** [comment]
How do I get permission to check a file in with Git. Username is rrip. Currently I get error 403.On Wednesday, November 16, 2016 5:35 PM, Richard Levitte wrote:

Date: Wed, 16 Nov 2016 15:35:38 -0800
From: Richard Levitte
To: openssl/openssl <openssl@noreply.github.com>
cc: Robert Ripberger <rip@lan-aces.com>, Author <author@noreply.github.com>
Subject: Re: [openssl/openssl] Open ssl 1 1 0 stable (#1937)

Closed #1937.



**Comment by richsalz** [comment]
You cannot contribute directly, you have to make a pull request and then it gets reviewed and merged by one of the openssl team members.  If you need it, here's a reasonable tutorial: https://yangsu.github.io/pull-request-tutorial/

**Comment by rrip** [comment]
still getting error 403 when creating a branch

**Comment by richsalz** [comment]
You're doing it wrong.  You fork the repo into *your* space, create a branch there for your work, push the branch to github, and then on your branch click on "make pull request."  Sorry, can't offer any more advice than search the online docs.

**Pull request closed without merging**
