### PR TITLE
Solution proposal for issue #1647.

### PR DESCRIPTION
**Pull request by makr**
Avoid the memory alignment issue described in #1647 . Successfully compiled and executed on AIX, HP-UX, Linux, Solaris and Windows.

Signed-off-by: Matthias Kraft Matthias.Kraft@softwareag.com

### CODE REVIEW

**Comment by richsalz** [comment]
@makr, would you think this is a trivial fix?  If not, can you sign our CLA?

**Comment by makr** [comment]
Yes, this is a trivial fix and it only touches test code. For this fix just go ahead. For future contributions I will look into the ICLA and the CCLA.

**Comment by richsalz** [comment]
Agree.  And it's what I suggested :)
+1

**Comment by dot-asm** [comment]
+1

**Comment by richsalz** [comment]
commit 3201a1d on 1.0.2; 
af5883f on master;
e2cefab on 1.1.0  thanks!

**Comment by dot-asm** [comment]
Side note in the context. I wonder if it would be appropriate for us to reserve the right to re-word commit messages? Why in the context? Because "Solution proposal for issue #1647" isn't really appropriate subject in long run. "Avoid a memory alignment issue" is much better, but it doesn't show in `git log` output, you have to work to dig it out. Related question if we can reserve the right to squash [somebody else's] commits? This isn't about this case, it's rather general query.

**Comment by kaduk** [comment]
@dot-asm I would be shocked if you (plural) decided that you did not have the right to do any of those things.  And I also appreciate the concern about useful commit messages; thank you for that.

**Pull request closed without merging**
