### PR TITLE
Fix typo in OPENSSL_malloc.pod

### PR DESCRIPTION
**Pull request by NanXiao**
##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Assuming you agree that this is trivial from a copyright perspective please add "CLA: trivial" on a line on its own into the commit description.

For the record I consider this trivial.

**Comment by NanXiao** [comment]
@mattcaswell Updated commit message, thanks!

**Review by t8m — APPROVED** [review]
I agree with CLA: trivial.

**Comment by levitte** [comment]
Merged

74c8dd1c516c7017477a205fd1f5f975cfa86722 Fix typo in OPENSSL_malloc.pod

**Comment by levitte** [comment]
... and to 1.1.1 as well:

5daa28ad7041a0def79e14a0e845f407e6f04f7e Fix typo in OPENSSL_malloc.pod

**Pull request closed without merging**
