### PR TITLE
demos: Add clean target for bio/Makefile

### PR DESCRIPTION
**Pull request by NanXiao**
CLA: trivial

### CODE REVIEW

**Comment by NanXiao** [comment]
Anyone is willing to check this trivial change? Thanks!

**Comment by NanXiao** [comment]
@t8m Could you help to review this PR when you are free? Thanks very much in advance!

**Review by t8m — APPROVED** [review]
I agree with CLA: trivial

**Review by paulidale — APPROVED** [review]

**Comment by t-j-h** [comment]
Note - I just corrected the label - it had the required approvals 10 days ago ...

**Comment by t8m** [comment]
Merged to master. Thank you for the contribution.

**Pull request closed without merging**
