### PR TITLE
Check # of arguments for remaining commands.

### LINKED ISSUE #2421: [rt.openssl.org #4677] Options after parameters are ignored in OpenSSL 1.1.0
Migrated from [rt.openssl.org#4677](https://rt.openssl.org/Ticket/Display.html?id=4677) (status was 'open')

Requestors:
* peter@lekensteyn.nl

From peter@lekensteyn.nl on 2016-09-17 17:54:11:
```
Hi,

Commands which execute normally with OpenSSL 1.0.2h fail in OpenSSL
1.1.0. Presumably after the "Big apps cleanup (option-parsing, etc)",

Options after parameters are no longer interpreted. For example,
'openssl dhparam 128 -out /dev/null' used to discard the DH params
output, but since 1.0.2 it no longer happens.

I also noticed that 'openssl genrsa -help' no longer displays the
'numbits' option.
-- 
Kind regards,
Peter Wu
https://lekensteyn.nl

```

From levitte@openssl.org on 2016-09-17 20:18:31:
```
On Sat Sep 17 17:54:11 2016, peter@lekensteyn.nl wrote:
> Hi,
>
> Commands which execute normally with OpenSSL 1.0.2h fail in OpenSSL
> 1.1.0. Presumably after the "Big apps cleanup (option-parsing, etc)",
>
> Options after parameters are no longer interpreted. For example,
> 'openssl dhparam 128 -out /dev/null' used to discard the DH params
> output, but since 1.0.2 it no longer happens.

You're right.  There should at least be a warning

> I also noticed that 'openssl genrsa -help' no longer displays the
> 'numbits' option.

Good point.

I'll have a closer look at this and the other commands in the next few days.

Cheers,
Richard

-- 
Richard Levitte
levitte@openssl.org
```

### PR DESCRIPTION
**Pull request by richsalz**
Backport of https://github.com/openssl/openssl/pull/4201

Fixes #2421 for 1.1.0

### CODE REVIEW

**Comment by vdukhovni** [comment]
Would "unexpected excess command-line argument: '%s' ...", with the first excess argument in the error message, perhaps be more clear than "extra arguments given"?

**Comment by richsalz** [comment]
Yes, it might be.  But this was just a simple patch based on the same commit for master.

**Comment by vdukhovni** [comment]
> @richsalz Yes, it might be. But this was just a simple patch based on the same commit for master.

Would it make sense to enhance the patch in 1.1.0 and master to make the error more clear along the lines suggested?

Anyone willing to do that?

**Comment by richsalz** [comment]
A new PR that improves the messages would be useful.  Want to open an issue capturing that?

**Comment by levitte** [comment]
I'm a bit surprised how few commands are touched...  but a quick look seems to confirm that other command (I looked at `s_client`) have a check in place, even though they give the "Extra" message at all...

**Comment by richsalz** [comment]
yeah, surprising that i didn't fix them all the first time :)  merged, thanks.

**Pull request closed without merging**
