### PR TITLE
Write SSL_R alerts to error state to keep updated strings

### PR DESCRIPTION
**Pull request by t8m**
Otherwise mkerr.pl always resets the strings to the original names based on the reason identifiers.

This is alternative to #19940.

### CODE REVIEW

**Review by tmshort — APPROVED** [review]
LGTM
Either this or #19940 is fine by me

**Comment by t8m** [comment]
Ping for second review

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
I prefer this to #19940

**Comment by t8m** [comment]
Merged to master branch. Thank you for the reviews.

**Pull request closed without merging**
