### PR TITLE
Update EVP_PKEY_fromdata.pod

### PR DESCRIPTION
**Pull request by opensignature**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by opensignature** [comment]
also
- || !EVP_PKEY_key_fromdata_init(ctx)
+ || EVP_PKEY_key_fromdata_init(ctx) <= 0

**Comment by levitte** [comment]
> also

Would you mind including that in this change?

**Comment by opensignature** [comment]
I would remove this example, because it cannot work,
ctx->keymgmt is NULL and fromdata_init function returns -2

**Comment by levitte** [comment]
I'd rather correct the example if it's faulty.

**Comment by opensignature** [comment]
ok I'm sorry not to suggest the solution, but I'm still studying this part of the code

**Comment by levitte** [comment]
I'm going to merge this now.  Further enhancements are welcome, in new PRs

**Comment by levitte** [comment]
Merged

5e427a435b3b1db0fb0626b26e031f71bde65f7a Update EVP_PKEY_fromdata.pod

**Pull request closed without merging**
