### PR TITLE
#20280 Add missing preprocessor conditional to reenable Visual Studio…

### PR DESCRIPTION
**Pull request by Dani-Hub**
… 32-bit builds

Signed-off-by: Daniel Krügler <daniel.kruegler@gmail.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by Dani-Hub** [comment]
What was again the right procedure to submit a license agreement (CLA required?)

**Comment by mattcaswell** [comment]
> What was again the right procedure to submit a license agreement (CLA required?)

See this page:

https://www.openssl.org/policies/cla.html

Although potentially this is a copyright "trivial" contribution (if the reviewers agree that its trivial then you can simply add "CLA: trivial" as a line on its own in the commit message).

**Comment by t8m** [comment]
This seems wrong. The 32 bit builds should not take this part of the preprocessed code due to BN_BYTES being 4 and not 8.
Could you please investigate what is BN_BYTES set to in your build?

**Comment by Dani-Hub** [comment]
I will do that but it will need a day or two.

**Comment by Dani-Hub** [comment]
OK, I have understood the root of the issue. This is actual a problem of the cmake variant of this project, which leads to an incorrect outcome for the `SIXTY_FOUR_BIT` define on 32-bit. I'm opening an issue in that project instead.

**Pull request closed without merging**
