### PR TITLE
Move the public SIV mode functions from public headers to internal ones

### PR DESCRIPTION
**Pull request by mattcaswell**
SIV mode is accessible via EVP. There should be no reason to make the low
level SIV functions from the modes directory part of the public API. Since
these functions do not exist in 1.1.1 we are still able to make this change.

This also reduces the list of newly added undocumented symbols from
issue #9095.

### CODE REVIEW

**Comment by tmshort** [comment]
> .num files needs updating?

Hmm... given that these were never officially released? Are the numbers still used, and become NOEXIST, or can they be reclaimed?

**Comment by levitte** [comment]
Last time we made a major release, we threw away libcrypto.num and libssl.num and regenerated them. That's probably the sanest way to reclaim all the holes.

**Comment by mattcaswell** [comment]
Fixup commit pushed. As @levitte said I think we'll just regenerate the num files as some point so no need to worry about the "NOEXIST".

**Comment by mattcaswell** [comment]
> They could always be exposed when required so it isn't a big deal (and likely not any deal at all).

Right...lets cross that bridge if we come to it.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
