### PR TITLE
Fix typos found by codespell in openssl-3.1

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Only modify `doc/man*` in the [openssl-3.1](https://github.com/openssl/openssl/tree/openssl-3.1) branch.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
@t8m PR #23546 targets the 3.0 branch

**Review by shahsb — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
Merged to the 3.1 branch. Thank you for your contribution.

**Pull request closed without merging**
