### PR TITLE
Correct traces for certificates in dtls13

### PR DESCRIPTION
**Pull request by fwh-dc**

### CODE REVIEW

**Comment by fwh-dc** [comment]
@t8m This is ready for review. Would you please add labels to reflect that? Thanks!

**Review by t8m — CHANGES_REQUESTED** [review]
Needs rebase to apply the new macro.

**Comment by fwh-dc** [comment]
> Needs rebase to apply the new macro.

Done.

**Review by t8m — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the feature branch. Thank you for your contribution.

**Pull request closed without merging**
