### PR TITLE
Add RSA SHA512 truncated digest support.

### PR DESCRIPTION
**Pull request by slontis**
Partial Fix for #11648.

Some additional work still needs to be done to support RSA-PSS mode.

RSA legacy digests will be addressed in another PR.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
ping

**Comment by levitte** [comment]
Travis failure not relevant here

**Comment by slontis** [comment]
Thanks. Merged to master.

**Comment by bbolli** [comment]
It seems to me that the `evppkey.txt` change adds the same test for SHA512-224 twice, and none for SHA512-256.

**Comment by slontis** [comment]
> It seems to me that the `evppkey.txt` change adds the same test for SHA512-224 twice, and none for SHA512-256.

Not quite - one is a sign test the other is a verify of the same data. An extended test that interops with another toolkit would be more useful.

**Comment by bbolli** [comment]
You're right. Sorry for not looking hard enough.

**Pull request closed without merging**
