### PR TITLE
Fix ASN1_TIME_compare return value documentation

### PR DESCRIPTION
**Pull request by sander242**
Return values were reversed.

### CODE REVIEW

**Comment by richsalz** [comment]
Can you either sign our CLA or add "CLA: trivial" in the *commit text* ?  Thanks.  I agree this is trivial

**Comment by tmshort** [comment]
This shouldn't be a documentation issue; if it's wrong, then the code should be updated.
The behavior should match that of strcmp():

-1 if a<b 
0 if a == b
1 if a > b

**Comment by tmshort** [comment]
ASN1_TIME_compare() was introduced in master, there's time to fix the code.

**Comment by richsalz** [comment]
go for it! :)

**Comment by tmshort** [comment]
Done. :)

**Comment by thsnr** [comment]
> The behavior should match that of strcmp():

`ASN1_TIME_compare` currently only normalizes the output of `ASN1_TIME_diff`. Reversing the return values of `ASN1_TIME_compare` creates a weird disconnect, because it now returns negative values where `ASN1_TIME_diff` would return positive and vice versa. And I do not think that also changing `ASN1_TIME_diff` comes into consideration due to compatibility with existing code.

So although I agree, that behaving as `strcmp` is desireable, this disconnect should still be taken into consideration before changing `ASN1_TIME_compare`. Or at least it should be explicitly noted in the documentation.

**Comment by tmshort** [comment]
> Or at least it should be explicitly noted in the documentation.

The return value is explicitly noted in the documentation

**Comment by richsalz** [comment]
#4264 does the more correct fix.  Thanks for finding this!

**Pull request closed without merging**
