### PR TITLE
Div rounding up

### PR DESCRIPTION
**Pull request by paulidale**
This is an alternative to #17872 for non-1.1.1 versions.  I don't think safe_math should be included in 1.1.1, but it ought to be suitable for 3.0 and master.

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
Seems like overkill.. What real problem are we trying to solve here?
The normal case is (var + (CONST-1)) / CONST.
Not sure why it needs to check CONST..
Checking var I can understand..

**Comment by hlandau** [comment]
This is a good idea.

**Comment by paulidale** [comment]
@slontis, I'm trying to make it generic.  A decent compiler will completely optimise away the CONST bits.

**Comment by slontis** [comment]
> @slontis, I'm trying to make it generic. A decent compiler will completely optimise away the CONST bits.

Yeah I know - but it seems like overkill..

**Comment by paulidale** [comment]
but it's _safe_ :)

**Comment by t8m** [comment]
The problem is we do not have safe_math in 3.0. This would certainly require an exception for 3.0.

**Comment by paulidale** [comment]
safe_math.h is header only, no build infrastructure changes, no new .c files.  It would be safe to back port.

The places using it, however, wouldn't be.

Happy to leave this master only.

**Comment by paulidale** [comment]
Ping @openssl/otc & @openssl/committers for reviews

**Review by mattcaswell — APPROVED** [review]
I'm ok with this for master. I don't think it needs to be backported to 3.0.

**Review by t8m — APPROVED** [review]
Agreed. Just for master.

**Comment by paulidale** [comment]
Merged to master only.  Thanks for the feedback.

**Pull request closed without merging**
