### PR TITLE
Only release thread-local key if we created it.

### LINKED ISSUE #3584: err_cleanup deletes err_thread_local even if not initialized
I've been debugging a crash in colord-sane which led me to libcrypto (https://bugs.archlinux.org/task/54205).

`OPENSSL_cleanup`, which is called `atexit`, runs `err_cleanup` which cleans up `err_thread_local` even if the latter has never been initialized and is still `0`.

Pthread key `0` is valid and belongs to glib (specifically GSlice's `private_thread_memory`). Glib is still running in other threads while the main thread is exiting.

Glib's worker thread races with the main thread and, if unlucky, attempts to use the thread-local after libcrypto has destroyed, resulting in a noisy SIGABRT.

libcrypto should not delete a `pthread_key_t` it never created.

Probably fallout from https://github.com/openssl/openssl/pull/3035.

OpenSSL 1.1.0f
glib 2.52.2
glibc 2.25

### PR DESCRIPTION
**Pull request by richsalz**
Thanks to Jan Alexander Steffens for finding the bug and confirming the
fix.

Fixes #3584

### CODE REVIEW

**Comment by levitte** [comment]
Make sure the builds pass

**Comment by richsalz** [comment]
I waited.  The tension was kiling me :)

**Comment by mattcaswell** [comment]
Ping @richsalz - doesn't seem to have been cherry-picked to 1.1.0?

**Comment by richsalz** [comment]
yo'ure right, slipped through the cracks.  Commit c8ec341 on 1.1.0

**Pull request closed without merging**
