### PR TITLE
Build tls13secretstest correctly

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
The comment was contradictory, and the condition did the opposite of what the comment said.
(I can't quite understand why the CIs didn't complain, though...  have conditions changed?)

**Review by mattcaswell — APPROVED** [review]
Hmmm...strange. Why have we not found this before?

**Comment by levitte** [comment]
> Why have we not found this before?

I have *no* idea...  also, the CIs don't seem to agree, I'll check that.

**Comment by levitte** [comment]
Ah, that was because the test recipe had the test condition for running when built shared.

**Comment by levitte** [comment]
There's a fixup, so this needs reconfirming

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
I'm backing out of this, it looks like I'm wrong.  I don't quite understand what happened in #7581, then.  Anyway, I'm giving this up and will keep an eye on the master builds for a bit.

**Comment by mattcaswell** [comment]
> I'm backing out of this, it looks like I'm wrong.

Huh? Really? At least the comment looks wrong here?

**Comment by mattcaswell** [comment]
Hmmm. I'm now running into this issue myself on Windows. The build is failing in tls13secretstest

**Comment by levitte** [comment]
I finally found the issue.  Fix in #8063

**Pull request closed without merging**
