### PR TITLE
fixed typos and repeated words, standardized spelling to US style

### PR DESCRIPTION
**Pull request by gustafn**
CLA: trivial

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by gustafn** [comment]
CLA: trivial was added by  commit https://github.com/openssl/openssl/commit/970175504ff15a2340ab3a2b06822ae8c1096678

**Comment by levitte** [comment]
We have, albeit maybe not loud enough, informally decided on British spelling.

**Comment by richsalz** [comment]
See, for example, https://github.com/openssl/openssl/pull/10079 and the discussion.

**Comment by gustafn** [comment]
there are currently US and UK spelling mixed. If there is interest, i can rework the pull request and target it to typos, word repetitions and US->UK spellings

**Comment by richsalz** [comment]
If you do this (not commenting on whether or not it is worthwhile), you should look at #10079 and update util/find-doc-nits

**Comment by gustafn** [comment]
Interestingly, the way from the current documentation to the US spelling seems shorter then the way to the UK spelling (raw data):
```
        # to US
        # 134 files changed, 335 insertions(+), 337 deletions(-)

        # to UK
        # 181 files changed, 391 insertions(+), 393 deletions(-)
```
There are currently several API calls in US spelling (just looking at the current documentation)
```
            CRYPTO_secure_malloc_initialized()
            EVP_RAND_verify_zeroization()
            OSSL_FUNC_rand_verify_zeroization()
            OSSL_FUNC_serializer_*()
            OSSL_OP_SERIALIZER
            OSSL_SERIALIZER_*()
            OSSL_SERIALIZER_PARAM_*
            RAND_DRBG_verify_zeroization()
```
Not sure, whether anyone wants to change the spelling of these API calls.... but having API calls in US and its docs in UK is also weird.

In case, UK vs. US is a controversial discussion, i could offer as a third option a pull request containing only spelling changes neutral to the UK vs. US issue.

**Comment by richsalz** [comment]
> I could offer as a third option a pull request containing only spelling changes neutral to the UK vs. US issue.

yes please. (I'm not a member of the project these days but I have done a lot of work improving the docs.)

**Pull request closed without merging**
