### PR TITLE
Document default client -psk_identity

### PR DESCRIPTION
**Pull request by richsalz**
Fixes https://github.com/openssl/openssl/pull/3605#issuecomment-305854425

### CODE REVIEW

**Comment by Valodim** [comment]
Punctuation inside quotes is usually the right thing to do, but it feels unnecessarily ambiguous here. As written, the default value might be "Client_identity." including the period

**Comment by richsalz** [comment]
yeah.  sigh.  tweaked and pushed an updated commit.

**Comment by Valodim** [comment]
:+1:

**Comment by kaduk** [comment]
If I understand things correctly, in order to use PSK, you need to both set -psk_key and include a(t least one) PSK ciphersuite in the cipher list, but it is optional to pass -psk_identity.  Including a PSK ciphersuite with no key will see it silently ignored by the client (in ssl_set_client_disabled()) and not sent on the wire; including a key with no PSK ciphersuite will just not do anything.

This seems like a fine time at which to add some text to s_client.pod about how "both a key and a PSK cipher suite must be set in order to use PSK".

**Comment by richsalz** [comment]
Both the -psk and the -psk_identity flag say "when a PSK cipher is used."  What additional text and where should it go?

**Comment by kaduk** [comment]
> Both the -psk and the -psk_identity flag say "when a PSK cipher is used." What additional text and where should it go?

Another sentence in -psk_key (at the end).  "Both a key and cipher suite must be specified in order for PSK to be [offered to the server|used]." Or skip it, if you don't think it adds value.

**Comment by richsalz** [comment]
Since it already says "when using PSK cipher" I don't think it's necessary :)

**Comment by kaduk** [comment]
The main thing I see as missing is that -psk_key is required (i.e., there is no default).  But I can +1 just this change and do the other thing separately.

**Comment by richsalz** [comment]
okay, added and pushed an updated commit.  please take a look.

**Comment by richsalz** [comment]
Merged to the three branches as listed above.  Thanks for the review!

**Pull request closed without merging**
