### PR TITLE
util/copy.pl: work around glob quirk in some of earlier 5.1x Perl versions.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by dot-asm** [comment]
1.0.2 is also affected, but there is an extra file there, so there will be separate request....

**Comment by dot-asm** [comment]
For reference, fixes #4683 and #4680...

**Comment by levitte** [comment]
Hmmm, we do have our internal OpenSSL::Glob that we use everywhere else (I think, but haven't checked).  Would it be useful here as well?

**Comment by dot-asm** [comment]
> Would it [our internal OpenSSL::Glob] be useful here as well?

Yes, it would. The reason for why I didn't attempt it is because I'm one who appreciates simplicity and least-required approach. As it stands now the script has no specific requirement on Perl version and can be copied elsewhere without having to trace dependencies. I consider it as advantage...

**Pull request closed without merging**
