### PR TITLE
Fix RC4 based ciphersuites

### LINKED ISSUE #13363: SSL3 alert write:fatal:bad record mac by RC4-SHA
`server:
OPENSSL_MODULES=../providers gdb --args   ./openssl s_server -tls1 -state  -cert eecert.pem -key eekey.pem   -cipher RC4-SHA -msg`

`client :
OPENSSL_MODULES=../providers gdb --args  ./openssl s_client -tls1 -state -cipher RC4-SHA -CAfile rootcert.pem -CAfile cacert.pem -msg`

I loaded the legacy provider into the default library context as shown below
`       legacy = OSSL_PROVIDER_load(NULL, "legacy");
       if (legacy == NULL) {
           printf("Failed to load Legacy provider\n");
       }
       deflt = OSSL_PROVIDER_load(NULL, "default");
       if (deflt == NULL) {
           printf("Failed to load Default provider\n");
           OSSL_PROVIDER_unload(legacy);
       }
   `

And set security level 0 SSL_CTX_set_security_level(ctx, 0)

But there  appeared the following error
`client:
SSL3 alert read:fatal:bad record mac
SSL_connect:error in error
0017FDF7FF7F0000:error::SSL routines::sslv3 alert bad record mac:ssl/record/rec_layer_s3.c:1615:SSL alert number 20`

`server:
SSL3 alert write:fatal:bad record mac
SSL_accept:error in error
ERROR
0017FDF7FF7F0000:error::SSL routines::decryption failed or bad record mac:ssl/record/ssl3_record.c:664:`

Can you give me a help,thanks!

### PR DESCRIPTION
**Pull request by mattcaswell**
Commit be9d82b inadvertently disabled ciphersuite testing. This masked two separate issues in the RC4 ciphersuites.

In 1 issue RC4 based ciphersuites fail the properly extract the MAC from decrypted TLS data.

In the 2nd issue the RC4-MD5 stitched ciphersuites fails to adjust the length of the decrypted data appropriately to account for the MAC.

This PR fixes both of those issues, as well as fixing the ciphersuite testing. Note that in fixing the testing I had to make some adjustments to take account of the FIPS module. This required some changes to the DH handling in the test. Currently that test uses the old "low-level" DH object instead of an EVP_PKEY - therefore this PR does the same in order to play nicely with the existing code. That issue is fixed by another PR (#13368). Whichever PR goes in second (this one or #13368) will have to be adjusted to use EVP_PKEY instead of DH.

Fixes #13363

### CODE REVIEW

**Review by t8m — APPROVED** [review]
LGTM. Approved if CI passes.

**Comment by paulidale** [comment]
Travis is relevant.

**Comment by mattcaswell** [comment]
Fixup pushed to address Travis failure

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Unfortunately #13368 was merged which touched the same ssltest_old.c code as this PR. Therefore I had to rewrite some of that code.

@paulidale - please can you reconfirm your approval?

**Comment by mattcaswell** [comment]
Travis failures are not relevant.

Ping @paulidale.

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
