### PR TITLE
Revert "Use .s extension for ia64 assembler"

### PR DESCRIPTION
**Pull request by t8m**
This reverts commit 6009997abd2594d5a7c0606176f404190922b74d.

The .s extension is really incorrect as the files contain preprocessor directives.

### CODE REVIEW

**Comment by t8m** [comment]
This fixes #18259

**Comment by levitte** [comment]
I'll happily review

**Comment by t8m** [comment]
> I'll happily review

Done

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
@RobinGeffroy, @jon-oracle, @tomhughes, you've all been instrumental with figuring out this issue.  Please help us test this PR

**Comment by jon-oracle** [comment]
My env still has trouble with this:

$ perl ./Configure enable-fips hpux64-ia64-cc 
...

$make
...

Make: Don't know how to make crypto/chacha/chacha-ia64.S.  Stop.
*** Error exit code 1

There are rules in the Makefile for the .o and .s files but no rule to generate the .S from the perl .pl script.

`
crypto/chacha/libcrypto-shlib-chacha-ia64.o: crypto/chacha/chacha-ia64.s
        $(CC) $(LIB_CFLAGS) $(LIB_CPPFLAGS) -c -o $@ crypto/chacha/chacha-ia64.s

crypto/chacha/chacha-ia64.s: crypto/chacha/chacha-ia64.S
        $(CC)  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include $(LIB_CFLAGS) $(LIB_CPPFLAGS)  -DAES_ASM -DGHASH_ASM -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -E crypto/chacha/chacha-ia64.S | \
        $(PERL) -ne '/^#(line)?\s*[0-9]+/ or print' > $@
`

**Comment by levitte** [comment]
I'll have a look.  It may be that something is missing that's been overlooked

**Comment by levitte** [comment]
I believe that bb65a3d1a729553a901717a27296509284016a0e, which I just pushed here, solves the issue.  Mind trying again, @jon-oracle?

**Comment by levitte** [comment]
(the commit I added requires another round of approvals)

**Comment by levitte** [comment]
@t8m, if you prefer, I can make my commit into a separate PR...  that'll require this one to depend on that one

**Comment by jon-oracle** [comment]
> I believe that [bb65a3d](https://github.com/openssl/openssl/commit/bb65a3d1a729553a901717a27296509284016a0e), which I just pushed here, solves the issue. Mind trying again, @jon-oracle?

Sure. I've run it again and it's getting past that spot so it looks like the issue is fixed. I have a possibly unrelated build failure though in fipsprov.c so I cannot complete the build and run any tests:

```
        cc  -I. -Icrypto -Iinclude -Iproviders/implementations/include -Iproviders/common/include  -DAES_ASM -DFIPS_MODULE -DGHASH_ASM -DOPENSSL_CPUID_OBJ -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM +Z -Ae +DD64 +Olit=all -z +O3 -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/hpux64/engines-3\"" -DMODULESDIR="\"/usr/local/lib/hpux64/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -D_HPUX_ALT_XOPEN_SOCKET_API -DNDEBUG   -c -o providers/fips/libfips-lib-fipsprov.o providers/fips/fipsprov.c
"providers/fips/fipsprov.c", line 51: error #2020: identifier "locale_t" is
          undefined
  static locale_t loc;
         ^

"providers/fips/fipsprov.c", line 506: error #2020: identifier
          "LC_COLLATE_MASK" is undefined
      loc = newlocale(LC_COLLATE_MASK, "C", (locale_t) 0);
                      ^

"providers/fips/fipsprov.c", line 506: error #2020: identifier "locale_t" is
          undefined
      loc = newlocale(LC_COLLATE_MASK, "C", (locale_t) 0);
                                             ^

"providers/fips/fipsprov.c", line 506: error #2018: expected a ")"
      loc = newlocale(LC_COLLATE_MASK, "C", (locale_t) 0);
                                                       ^

"providers/fips/fipsprov.c", line 508: error #2018: expected a ")"
      return (loc == (locale_t) 0) ? 0 : 1;
                                ^

5 errors detected in the compilation of "providers/fips/fipsprov.c".
*** Error exit code 2

Stop.
*** Error exit code 1

Stop.
```

**Comment by t8m** [comment]
@jon-oracle You'll need fresh master or 3.0 checkout to fix that one.

**Comment by t8m** [comment]
Approving @levitte's patch

**Comment by t8m** [comment]
@mattcaswell Are you ok with the added patch?

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Ok, so all in all, it now looks like we have enough approvals to cover all the commits appropriately.

**Comment by tomhughes** [comment]
I can confirm that the patch here worked on our ia64 machine using gcc.

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for your reviews and cooperation.

**Pull request closed without merging**
