### PR TITLE
Code health: Remove another VAX C-ism, globaldef and globalref

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by dot-asm** [comment]
I'd say that it would be more appropriate to remove the comment altogether and put modified comment to commit message instead.

**Comment by levitte** [comment]
Not so sure about that...  In a year or so, how far will we dig in commit logs to find *documentation* on how to use those macros?

**Comment by richsalz** [comment]
Yeah, I like the comment.  approved.

**Review by richsalz — APPROVED** [review]
Unless @dot-asm strongly disagrees.

**Comment by dot-asm** [comment]
Right. Sorry. What I rather meant was that it would be appropriate to remove mention of VAX C from commentary. I mean modified commentary opens with "OPENSSL_GLOBAL had some meaning for VAX C, which isn't supported any more", and if you were looking at it for "first time" you would wonder "what does it have to do with anything?"

**Comment by levitte** [comment]
Ah, that...  well, `OPENSSL_GLOBAL` is still defined, to nothing.  Someone is bound to wonder why...

**Comment by levitte** [comment]
But sure, I can remove that line.

**Comment by levitte** [comment]
Actually, `OPENSSL_GLOBAL` can be removed entirely.  I was afraid the change would be massive, but found that this wasn't true.

**Comment by richsalz** [comment]
and then get rid of ```OPENSSL_IMPLEMENT_GLOBAL``` as well.

**Comment by levitte** [comment]
Errr, no.  That's a totally different deal.

**Comment by levitte** [comment]
Or, well, not *totally*, but still...

**Comment by levitte** [comment]
Ok, added a commit that removes `OPENSSL_GLOBAL` entirely.

**Comment by dot-asm** [comment]
Cool! I'd like to see what CI says and possibly run some tests myself. A bit later today though...

**Comment by levitte** [comment]
Yup.  I'm running tests on VMS as well, right now.

**Comment by levitte** [comment]
This seems to build and test fine on VMS

**Review by dot-asm — APPROVED** [review]
Everything seems to be in order

**Comment by levitte** [comment]
Cool, thanks!  Merged.

**Pull request closed without merging**
