### PR TITLE
Add OIDs for DSTU4145

### PR DESCRIPTION
**Pull request by gmile**
This is a work in progress. Once the work is done, the commits will be squashed.

Fixes https://github.com/openssl/openssl/issues/5194

### CODE REVIEW

**Comment by gmile** [comment]
> So the only change is really to objects.txt

@richsalz right now yes, only objects.txt. But this PR is WIP, I still need to figure out the smallest amount of glue code to port from the original [DSTU4145 engine](https://github.com/dstucrypt/openssl-dstu/tree/dstu-1_0_1h) implementation code.

OIDs are defined on a respective government law's web page http://zakon2.rada.gov.ua/laws/show/z1398-12/print.

**Comment by gmile** [comment]
> The question is how much more is to be added?

@paulidale that I'm trying to figure out. I'm going to port only the relevant bits from the [original implementation](https://github.com/dstucrypt/openssl-dstu/commit/5ffb6d0018eb230acb38656a8ad1cee5da63b28f#diff-3c7e3baac57971e2177e9cf0ee6b578a). I need to understand what else besides OIDs is required for external engine to work. This is what I'm doing now but it will take me some time. The biggest part was OIDs.

As soon as I'm done, I'll ping you.

**Comment by dot-asm** [comment]
As matter of protocol sanity I'd like to suggest to *not* approve WIP requests. I mean WIP means "more changes are coming", so approving it is kind of counter-productive, as you would have to re-approve it...

I note that there is "dismiss review" button, would it be appropriate to use it? I also wonder if originator can do that. [Not necessarily here, but as a matter of figuring things out.]

**Comment by kroeckx** [comment]
So is this ready for review now?

**Comment by gmile** [comment]
@kroeckx yes, I think it is ready to review.

I was not able to find any glue code that needs to be ported over from the DSTU engine to the OpenSSL core. Anyway, if such code will be found later on as I go about making DSTU engine compilation work, it would be best to review such glue code separately from OID.

I have removed the WIP a few days ago but forgot to mention this in comments.

**Comment by gmile** [comment]
@richsalz I've edited the PR title to match commit message, e.g. `Add OIDs for DSTU4145`

**Comment by outspace** [comment]
There are is much more OID's for DSTU4145 ( [http://zakon2.rada.gov.ua/laws/show/z0423-17](url) ). Maybe it will be a good idia to add all of them?

**Comment by gmile** [comment]
@outspace great point. Initially I only took the OIDs that were found in original OpenSSL DSTU work. I've extracted the OIDs from your link into a [gist](https://gist.github.com/gmile/6d06c5913153dbef51ec8c213c26eed9). I don't immediately have the time to extract them, but it makes sense to do so.

**Comment by richsalz** [comment]
@gmile, can you rebase this against a current master?  Do a "make update" and add all those files and force-push your commit?  Would like to get this done by the beta deadline.

**Comment by gmile** [comment]
Hi @richsalz, I'm not familiar with openssl beta release schedule. What would be a reasonable timeline for me to finish this PR? Should it be done today/tomorrow, or it can be postponed until this weekend?

**Comment by richsalz** [comment]
See https://www.openssl.org/policies/releasestrat.html for details.
Thank you!

**Comment by gmile** [comment]
Hi @richmoore, I've rebased & added the missing OID, based on the list found in government site – https://github.com/openssl/openssl/pull/5216#issuecomment-368803688. I've force-pushed a bigger bunch of OIDs, but original patch is still available in a [gist](https://gist.github.com/gmile/3d41295fc2b0ce5805c05422b19228e2).

Do you think it's fine to keep the new bunch of OIDs, or would you prefer to go back to the original smaller patch?

**Comment by richsalz** [comment]
That is a lot of OID's.  Yes, they're pretty cheap to add, but do you need them all?

**Comment by gmile** [comment]
@richmoore no, I certainly don't need all of them. Having just the initial portion would be enough for us. I'll rebase this once again, bringing back just the original set of OIDs.

**Comment by gmile** [comment]
Pushed. This should be enough to get dstu-4151 engine going.

**Comment by richsalz** [comment]
Thanks.  And while @richmoore has an excellent first name, it's our last names that differ :)

**Comment by richsalz** [comment]
@paulidale please reconfirm?

**Comment by gmile** [comment]
> Thanks. And while @richmoore has an excellent first name, it's our last names that differ :)

@richsalz that was embarrassing... I'm sorry!

**Comment by richsalz** [comment]
Thank you.  Merged to master.

**Comment by gmile** [comment]
Awesome, thank you @richsalz!

**Pull request closed without merging**
