### PR TITLE
Replace some of the ERR_clear_error() calls in libcrypto with mark calls

### LINKED ISSUE #15219: asn1_d2i_read_bio() has brittle design depending on the error queue
After (as part of #15147) making `ASN1_{,item_}d2i_bio()` conservative on the error queue 
by replacing `ERR_clear_error()` by `ERR_set_mark()` and friends, I got very weird regressions on private key file loading etc.

It took me a hell lot of work to find out that this is due to a nasty design of `asn1_d2i_read_bio()` and its sub-functions: unless the error queue is emptied initially, they go wrong causing all sorts of test failures related to `OSSL_STORE`.

The design should be changed to avoid such brittle behavior.

If not possible in the near future, 
* this unexpected behavior should be clearly documented at the code line containing `ERR_clear_error()` 
* documentation of functions calling `asn1_d2i_read_bio()` should mention that unfortunately they clear the error queue.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #15219

This does not replace all of them as removal of some of the ERR_clear_error() would require more substantial changes or might be potentially a security problem.

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Review by slontis — APPROVED** [review]
I realize we have run out of time - but test coverage for these would probably be a good idea at some point.

**Comment by t8m** [comment]
Merged to master. Thank you for the reviews.

**Comment by DDvO** [comment]
I'm astonished to see how simple it was to solve #15219 :+1:

**Comment by DDvO** [comment]
It turns out that this change incurred some spurious error queue entries, e.g.,
```
ossl_store_handle_load_result:crypto/store/store_result.c:151:error: unsupported:
asn1_check_tlen:crypto/asn1/tasn_dec.c:1156:error: wrong tag:
asn1_item_embed_d2i:crypto/asn1/tasn_dec.c:322:error: nested asn1 error:Type=EC_PRIVATEKEY
```
I'll try to come up with a fix.

**Pull request closed without merging**
