### PR TITLE
[1.1.0] Add a 'max_send_frag' option to configure maximum size of send fragments

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Backport of #3141:  add missing options  

##### Checklist

- [X] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
This looks like you want to add a new feature to a stable branch. What is the justification?

**Comment by FdaSilvaYY** [comment]
Hi, 
It's more an 'apps' support-code addition ... 
to be able to call/use an already existing feature in the library ...
This PR don't change core code or features.

**Comment by richsalz** [comment]
What's the relationship between this and #1008 ?

**Comment by FdaSilvaYY** [comment]
No relation...

#1008 internally relies on the 'max send frag' implementation, but this PR has nothing to see with it.
This PR is for 1.1.0.

**Comment by mattcaswell** [comment]
This looks like a new feature going into 1.1.0, so I think not appropriate.

**Pull request closed without merging**
