### PR TITLE
In cases where we ask PEM_def_callback for minimum 0 length, accept 0 length

### LINKED ISSUE #4716: 0 length passwords not accepted when importing PKCS8 encrypted key
One of my colleagues reports that 0 length passwords are not accepted when importing a PKCS8 encrypted key. To see why, go to pem_pkey.c:116 (in branch 1.0.2 stable). Notice that the comparison for password length is <= 0 rather than < 0, which disallows 0 length passwords.

Note that the PKCS 8 and PKCS 5 specifications do not disallow 0 length passwords, so this is a bug.

### PR DESCRIPTION
**Pull request by levitte**
Fixes #4716

### CODE REVIEW

**Comment by levitte** [comment]
There should probably be an entry in `CHANGES`, but someone will have to indicate how that should be written in master, considering I want to backport this all the way back to 1.0.2

**Review by richsalz — APPROVED** [review]
Wonder if this should be noted in CHANGES?  Your call either way.

**Comment by mspncp** [comment]
> There should probably be an entry in CHANGES, but someone will have to indicate how that should be written in master, considering I want to backport this all the way back to 1.0.2

Just make a normal CHANGES entry and move it around when backporting. That's what I did when I backported Emilias commit:

master: https://github.com/openssl/openssl/commit/80770da39ebba0101079477611b7ce2f426653c5#diff-e4eb329834da3d36278b1b7d943b3bc9R5

1.1.0: https://github.com/openssl/openssl/commit/414d19d0341407b211c64729df37889e2c572e12#diff-e4eb329834da3d36278b1b7d943b3bc9R10

1.0.2: https://github.com/openssl/openssl/commit/7b6cfcd6dd99a86ecc3a1c51eef539494e191754#diff-e4eb329834da3d36278b1b7d943b3bc9R10

**Comment by levitte** [comment]
Okie, that works for me

**Comment by levitte** [comment]
CHANGES entry added.  It will be reproduced at the top of CHANGES for each branch

**Comment by levitte** [comment]
(requires reconfirm)

**Comment by richsalz** [comment]
reconfirm

**Comment by levitte** [comment]
Merged.

master / 1.1.1:
c82c3462267afdbbaa53e11da0508ce4e03c02b3 In cases where we ask PEM_def_callback for minimum 0 length, accept 0 length

1.1.0:
36d2517a97f6020049116492b4d5491d177e629c In cases where we ask PEM_def_callback for minimum 0 length, accept 0 length

1.0.2:
18026c0215e942f0ad33a6012cb8cad2f51f841b In cases where we ask PEM_def_callback for minimum 0 length, accept 0 length

**Comment by davidben** [comment]
Someone pointed out an OpenSSL/BoringSSL behavior difference that I eventually narrowed down to this change. In aligning, I noticed that you all actually missed a few spots:

https://github.com/openssl/openssl/blob/master/crypto/pem/pem_lib.c#L366
https://github.com/openssl/openssl/blob/master/crypto/pem/pvkfmt.c#L1073

Based on "In cases where we ask PEM_def_callback for minimum 0 length, accept 0 length", I'm guessing this is because the third callback parameter was interpreted as a minimum length, but it's actually just a boolean for whether you're encrypting or decrypting.

(We've decided to fix the issue across the board on our end.)

**Pull request closed without merging**
