### PR TITLE
Implement PREREQUISITE

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [x] documentation is added or updated
- [x] CLA is signed

##### Description of change

There are times when you find yourself in a catch 22 when building.  Consider this in a pristine checkout:

```
$ ./config
$ make fuzz/server-test
```

This becomes trouble because some generated header files (for example `include/openssl/opensslconf.h`) haven't been generated yet, and neither has the Makefile dependency information which would otherwise ensure `opensslconf.h` gets built.  So we need a way to say that for a select (or all) bunch of object files, the generated header files that they *may* use must be generated first.  Simply put, that's a prerequisite to building the object file.

In this change, such prerequisites are specified like this in `build.info` files:

```
PREREQUISITE[**.o]=include/openssl/opensslconf.h
```

and translate to this type of sub-make call:

``` make
whatever.o: whatever.c
	$(MAKE) include/openssl/opensslconf.h
	$(CC) -o $@ -c $<
```

### CODE REVIEW

**Comment by richsalz** [comment]
double-star?
Also I thought one whole point of this was to avoid recursive make invocations.
And also, won't this break -j invocations?

**Comment by levitte** [comment]
Double-star is inspired from Ant, it's a traversal of directories.  So in regexp terms, if star becomes `[^/]*`, double-star becomes `.*`

**Comment by levitte** [comment]
The whole point was to generate a single top Makefile and not go up and down the directory tree.  And yes, we should avoid excessive recursive make invocations, but we have never said *never*.

**Comment by levitte** [comment]
As for `-j`, not sure.  Does it actually?

**Comment by richsalz** [comment]
Yes you created a race condition if the file needs to be updated, foo.o and bar.o will both end up trying to recursively sub-make the header file.  And someone could end up reading a partially-created file.

This PR adds a new syntax and adds recursive make to almost every object file -- an invocation that will *almost always* be pointless, and perhaps polluting with "... up to date" messages.

**Comment by levitte** [comment]
Hmm, yeah, good point.  Darnit...

**Pull request closed without merging**
