### PR TITLE
Do IV reset also for DES and 3DES implementations

### LINKED ISSUE #14704: EVP_CipherInit_ex(ctx, NULL, NULL, NULL, NULL, -1) no longer resets IV in CBC mode
I haven't verified with a minimal repro, but while testing with OpenSSL 3 alpha 13, it looks like `EVP_CipherInit_ex` with a `NULL` IV no longer restores `oiv` as the IV:

OpenSSL 1.1.1:

If IV is provided, copy over oiv.  After that, either way, copy oiv over IV.

https://github.com/openssl/openssl/blob/122e5f7c010859f0b2984d553fa45cd1f18a6fc4/crypto/evp/evp_enc.c#L179-L188

OpenSSL 3(a13):

Generic init only calls initiv when an IV was given.

https://github.com/openssl/openssl/blob/88df2c0b3d6162971304c06a240deb9320c9ae67/providers/implementations/ciphers/ciphercommon.c#L187-L190

Since nothing ever copied oiv over iv, the iv continues as it was when reset was called, a change from previous versions (except when an engine is used, which hits the compatibility fallback).

A quick test using the deprecated `EVP_CIPHER_CTX_original_iv` function fixed the issue for AES, 3DES, DES, and RC2 for both CBC and CFB (all applicable sizes).

### PR DESCRIPTION
**Pull request by t8m**
This is necessary to complete the fix for #14704 

Fixes #14704

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
Maybe needs a test?

**Comment by t8m** [comment]
> Maybe needs a test?

Added

**Review by slontis — APPROVED** [review]
Thanks for adding a test..

**Comment by paulidale** [comment]
I think we might need an OTC decision as to always doing this or only doing it for legacy reasons....
A debate for after 3.0.

**Comment by t8m** [comment]
> I think we might need an OTC decision as to always doing this or only doing it for legacy reasons....
> A debate for after 3.0.

Reported #14924

**Comment by t8m** [comment]
Merged to master. Thank you for the review!

**Pull request closed without merging**
