### PR TITLE
Implement the TRACE category ERR, to trace all added error records

### PR DESCRIPTION
**Pull request by levitte**
Suggested fix for #17987

### CODE REVIEW

**Comment by levitte** [comment]
@beldmit, you may want to play with this.  It is quite verbose, but
does show what's going on, even the stuff that's ignored (through
ERR popping).

**Comment by t8m** [comment]
It does not solve the problem with trace subsystem being usually not built-in. However it is useful IMO anyway and should be merged (to master branch).

**Review by paulidale — COMMENTED** [review]
Suggestion only but would it be possible to also trace the set mark, pop to mark and clear mark calls?  It would then be possible to match up what was lost.  Ideally, with indention based on depth of mark but that's not very important.

**Comment by levitte** [comment]
> Suggestion only but would it be possible to also trace the set mark, pop to mark and clear mark calls? It would then be possible to match up what was lost. Ideally, with indention based on depth of mark but that's not very important.

This thought occurred to me over the weekend.  I don't think I'll go for the depth thing, as that requires storing more state, but printing tracelines for those calls is definitely an option

**Comment by levitte** [comment]
BTW, I made the mistake of making this PR from the openssl-3.0 branch, i.e our release branch.  That ends up being quite confusing.  I'll make a new PR cnad close this.

**Pull request closed without merging**
