### PR TITLE
conf: add diagnostic option.

### PR DESCRIPTION
**Pull request by paulidale**
This is intended to assist with debugging configurations.

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
Should be ready for review.  All the nasty alternate solutions are gone.  This ended up reasonably clean.

**Comment by paulidale** [comment]
ping?  @mattcaswell

**Review by t8m — APPROVED** [review]
LGTM

**Review by mattcaswell — APPROVED** [review]
LGTM

**Comment by paulidale** [comment]
Merged to master.  Thanks for the quick reviews.

**Pull request closed without merging**
