### PR TITLE
Modify Sun copyright to follow Oracle style

### PR DESCRIPTION
**Pull request by richsalz**
Master only.

### CODE REVIEW

**Comment by richsalz** [comment]
This is on hold until Oracle confirms it to me.

**Comment by kroeckx** [comment]
I thought I added a comment about this earlier, but it seems to be lost. I think it should probably keep saying Sun Microsystems, even if Oracle now owns it.

**Comment by richsalz** [comment]
I am waiting to see what Oracle says.

**Comment by richsalz** [comment]
Oracle has approved this, and that approval is recorded in our license folder.
Oracle purchased Sun and all its assets, including all intellectual property and copyrights.
I'm merging this now.

**Comment by richsalz** [comment]
Argh, typo in the addrev call, but this is merged.

**Pull request closed without merging**
