### PR TITLE
WIP: add some travis timeouts

### PR DESCRIPTION
**Pull request by richsalz**
Trying https://github.com/richsalz/openssl/pull/new/travis-work-arounds

### CODE REVIEW

**Comment by slontis** [comment]
The heading is a bit controversial.
Maybe change to something that indicates you are fixing timeout issues :)

**Comment by richsalz** [comment]
Doesn't matter; you can't do "travis_wait" on an shell "if" construct.  So I'm closing/cancelling this.  Using the capabilities will require some serious rewrite of the project's travis.yml file.

**Comment by levitte** [comment]
This might have worked, though:

```
          if ! HARNESS_VERBOSE_FAILURE=yes BORING_RUNNER_DIR=$top/boringssl/ssl/test/runner travis_wait make test; then
```

**Comment by levitte** [comment]
Basically, `travis_wait` is a shell function, and is to be used like any other prefixing command, like `env`

**Comment by richsalz** [comment]
okay, let's try your suggestion.

**Comment by richsalz** [comment]
Moved to #11319

**Pull request closed without merging**
