### PR TITLE
Allow 3.1 FIPS provider to pass 3.0 test suite

### LINKED ISSUE #19601: Across version provider testing is failing
The test that checks that the 3.0 and master FIPS providers interoperate is [broken](https://github.com/paulidale/openssl/actions/runs/3388207103/jobs/5629908581).

In master and 3.1, triple DES has been removed from the FIPS provider because of an end of 2023 sunset.  Refer [SP 800-131Ar2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf).  The unit tests in 3.0 haven't the slightest clue that this is happening and fail because the triple DES algorithms cannot be fetched and tested.

Worse is that PKCS **⌗**1 version 1.5 padding is also being sunsetted at the end of 2023 and it's upcoming removal from the FIPS provider in master and 3.1 will cause a lot more errors to happen in the 3.0 cross version testing.

The underlying problem of algorithms going missing and been modified needs to be addressed somehow.

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #19601

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Review by t8m — APPROVED** [review]
Should be merged also to master and 3.1 branches.

**Comment by paulidale** [comment]
No need to merge to master and 3.1.  They already deal with this.

**Comment by t8m** [comment]
Ah, I did not realize there is #19666 for 3.1 and master.

**Comment by paulidale** [comment]
and the tests in 3.1 and master already cope with this case :)

**Pull request closed without merging**
