### PR TITLE
Move libapps.a source to apps/lib

### PR DESCRIPTION
**Pull request by levitte**
This makes it clearer what's what.  The 'openssl' application and its
sub-commands remain in apps/

### CODE REVIEW

**Comment by levitte** [comment]
On demand from discussion in #9331 

Note that more work is needed.  `apps/openssl.c` contains library functions, and `apps/lib/apps.c` refers to some of those functions, making it impossible to re-use libapps.a with the test programs.
*That*, however, is work for another PR.

**Comment by levitte** [comment]
Being an OMC member doesn't necessarily mean that everything gets automatic high priority.  Have a look at the number of open PRs I have hanging around....

**Comment by levitte** [comment]
More or less all -I values go "up and over", because the top include demands it and all file or directory references in build.info files are relative to the location of that build.info file.

**Comment by levitte** [comment]
As for your idea of making `libapps` a top level thing, I'm not too keen, because I fear that would make it look like something that we release alongside libcrypto and libssl, and I'd rather that library stay internal.

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

2ad75c6c1341db8a3122bbeaf863440057d71307 Move libapps.a source to apps/lib

**Pull request closed without merging**
