### PR TITLE
Use '-rpath' to set run time lib path for binaries like apps/openssl

### PR DESCRIPTION
**Pull request by InfoHunter**
##### Checklist

If I configure OpenSSL with a simple '--prefix' option and then make install the binaries and libs into the destination directory, I find <prefix>/bin/openssl cannot be executed directly since it's something like this:

```
$ ldd bin/openssl
        ...
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
       ...
```

Add a 'rpath' while linking the binaries would solve this problem.

### CODE REVIEW

**Comment by levitte** [comment]
Bad idea. For starters, -rpath isn't universal, and with the GNU toolchain, it sets DT_RPATH when it would be better to set DT_RUNPATH. 

For this reason, we leave it up to the user to configure with -rpath, like this:

```
./config --prefix=whatever -Wl,-rpath='$(LIBRPATH)'
```

**Comment by InfoHunter** [comment]
If so, it should be clarified in the INSTALL file, to let the users (especially normal users such as an administrator of a server who is not familiar with the `rpath` stuff)  know how to make `bin/openssl` run correctly. Currently, in INSTALL file there is an example:

```
 If you want to install it anywhere else, run config like this:

  On Unix:

    $ ./config --prefix=/opt/openssl --openssldir=/usr/local/ssl
```

which will not prepare a usable bin/openssl binary for end-users. So this is some kind of misleading.

Although, there is a statement in that INSTALL file: 

```
  -Dxxx, -lxxx, -Lxxx, -fxxx, -mXXX, -Kxxx
                   These system specific options will be passed through to the
                   compiler to allow you to define preprocessor symbols, specify
                   additional libraries, library directories or other compiler
                   options. ...
```

but still, it can't guide the users who have no idea about `rpath` to get a usable `bin/openssl`.

**Comment by levitte** [comment]
We have added a bit more information lately.  I'm not sure what checkout or version you have, but in the current master and 1.1.0 branches, there's [this early on in `INSTALL`](https://github.com/openssl/openssl/blob/master/INSTALL#L18-L24):

```
 For additional platform specific requirements, solutions to specific
 issues and other details, please read one of these:

  * NOTES.UNIX (any supported Unix like system)
  * NOTES.VMS (OpenVMS)
  * NOTES.WIN (any supported Windows)
  * NOTES.DJGPP (DOS platform with DJGPP)
```

and the new [`NOTES.UNIX`}(https://github.com/openssl/openssl/blob/master/NOTES.UNIX) contains exactly the information you're asking about.

Regarding citation from INSTALL on how Configure treats comman line arguments, you're quite right, there's no information at all what it will do with "unrecognised" options.  I could have sworn we added something...  so that will need to be fixed.

**Comment by InfoHunter** [comment]
Well, I am on 'master' branch and I have ignored those NOTES.xxx files, and jumped to the `Quick Start` section that normally people will refer to. I am pretty sure if we can 'promote' the statements in NOTES.UNIX into the `Quick Start` section of INSTALL file, that would be a very good idea, since `rpath` is really important for a 'non-standard' installation.

Besides, what confused me is that the very beginning 1.1.0 version (https://www.openssl.org/source/old/1.1.0/openssl-1.1.0.tar.gz) still has automatic rpath being supported. But the successors of it (the letter releases of 1.1.0) removed the automatic rpath feature, did this follow the release strategy of OpenSSL? From my understanding, the letter releases should only contain bug & security fixes and no new features. But the 'rpath' thing looks like a 'feature change' more than a bug fix. At the time I upgraded the no-letter-1.1.0 to lettered-1.1.0, oops, the bin/openssl did not work any more, that's really confusing...

**Comment by levitte** [comment]
Ok, I hear ya.  #3468 got pushed through moments ago, and I just added #3469 (not yet approved).

**Comment by InfoHunter** [comment]
Get it, that would be more clear...

**Comment by InfoHunter** [comment]
Thanks, man!

**Pull request closed without merging**
