### PR TITLE
Fix SYNOPSIS for ASN1_ENUMERATED_get_int64 and ASN1_ENUMERATED_set_int64

### PR DESCRIPTION
**Pull request by newsuk-jzelenka**
Looks like synopsis ASN1_ENUMERATED_get_int64 and ASN1_ENUMERATED_set_int64 doesn't match the implementation type for `a`.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
@newsuk-jzelenka  this commit seems to have been authored by @bukka. I'm wondering why you have submitted it? It makes a difference for CLAs...although this probably classes as trivial anyway.

**Comment by bukka** [comment]
Ah no. That's another account that I use for work. Forgot to log in into this one. Will create a new PR. Will also sort the second PR out. Sorry for that...

**Comment by newsuk-jzelenka** [comment]
Closing as it's from wrong account.

**Comment by bukka** [comment]
New PR #9823 from the right account created.

**Pull request closed without merging**
