### PR TITLE
Fix array bounds violation in ssl_session_dup

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This should fix the travis failures.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
I wonder if we should always run at least one asan configuration.
That can't be too expensive?

**Comment by dot-asm** [comment]
Trouble is that there is no right answer to this kind of questions. For example why just asan? Even judging from this case, it addresses msan problem, right? Idea behind division to "base" and "extended" tests was to ensure reasonable turnaround in case of requests' and adjustments' bursts, yet with some configuration diversity to catch most obvious errors...

**Comment by bernd-edlinger** [comment]
Actually using ASAN is sufficient to check this kind of error.
Maybe the used compiler versions are still too old?
At least in this case it was a latent bug that was triggered by the following commit:

```
commit 36ff232cf2bf5dfcaf9e60a8c492439428a243bb
Author: Matt Caswell <matt@openssl.org>
Date:   Wed Mar 14 19:22:48 2018 +0000

    Change the default number of NewSessionTickets we send to 2
    
    Reviewed-by: Viktor Dukhovni <viktor@openssl.org>
    Reviewed-by: Rich Salz <rsalz@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/5227)
```

And using a recent gcc, the following
command was sufficient to pin-point the commit:
`git bisect run sh -c "make distclean ; ./config enable-asan && make -j4 && make test TESTS=70"`

**Comment by bernd-edlinger** [comment]
The problem is that successful completion of travis in the PRs encourages the
committer to apply the patch.

**Comment by dot-asm** [comment]
> Actually using ASAN is sufficient to check this kind of error ... using a recent gcc,

But on travis is was msan...

**Comment by bernd-edlinger** [comment]
> But on travis is was msan...

Yes, but that just proves that we should use more recent gcc versions and asan.

**Comment by richsalz** [comment]
maybe open an issue to catch the build/asan issue?

**Comment by bernd-edlinger** [comment]
Merged.  Thanks!

**Pull request closed without merging**
