### PR TITLE
Fix GOST curve sec bits

### PR DESCRIPTION
**Pull request by NMorozxov**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by NMorozxov** [comment]
@beldmit a fix-up PR

**Comment by NMorozxov** [comment]
one of travis jobs fails (timeout)

**Comment by beldmit** [comment]
@t8m, could you please approve?

**Comment by NMorozxov** [comment]
@beldmit cold you please restart the failded job ?

**Comment by beldmit** [comment]
Job restarted

**Comment by NMorozxov** [comment]
ping otc

**Comment by beldmit** [comment]
Merged. Thanks!

**Pull request closed without merging**
