### PR TITLE
Fix tls_cbc_digest_record is slow using SHA-384 and short messages

### PR DESCRIPTION
**Pull request by armfazh**
The right value for this variable is
````
kVarianceBlocks = 384 / md_block_size;
````

Notice that `md_block_size=64` for SHA256, which results on the
magic constant `kVarianceBlocks = 384/64 = 6`.
However, `md_block_size=128` for SHA384 leading to
`kVarianceBlocks = 384/128 = 3`.

CLA:trivial

### CODE REVIEW

**Comment by mattcaswell** [comment]
Placing a hold on this while I look at it in more detail.

**Comment by mattcaswell** [comment]
I don't really understand how the formula you propose is derived.

Given any particular encrypted record an external observer will not know exactly how much data is in it. If there is a long padding then we will need to hash less data than if there is a short padding. We do not want to leak any timing information which might indicate the length of the data. As I understand it the `kVarianceBlocks` variable holds the difference between the maximum and minimum number of hash blocks that will be required to process any particular record.

The minimum number of hash blocks will occur in the case where padding is maximal (because with more padding stripped off there is less data left to hash). We're specifically talking about the TLS case here (not SSLv3), so the maximum padding is 255 bytes, plus 1 byte of padding length.

There is a comment in the code here which says "We conservatively assume that the MAC size varies from 0..20 bytes". This is clearly referring to a SHA1 hash. It's not clear to me why we would need to assume this since the MAC size is constant and is public information. However, in order to be able to make a comparison with the current code, I'll make the same assumption. So this means that the difference in the amount of data that might need to be hashed  (in the SHA1 case) is:

````
255 /* padding bytes */ + 1 /* padding length */ + 20 /* hash length */
````

For a maximally padded record we will need to "pretend" to hash that amount of data in order to be doing the operation in constant time. That means that the number of hash blocks required for that is:

````
(255 + 1 + 20) / md_block_size
````

But actually that's not entirely correct, because in C integer arithmetic that will round down. However in practice if we have a partial block we need to round up, so that makes it:

````
(255 + 1 + 20 + md_block_size - 1) / md_block_size
````
However there is a further complication. The "real" data that needs to be hashed has to be padded for the hashing algorithm. For SHA1 the smallest amount of padding that can be added is the "0x80" byte plus 8 bytes containing the message length, i.e. 9 bytes. If the data length is within 9 bytes of the end of the hash block boundary then the padding will push it into an extra block to be hashed. The same argument applies for all the other hashes (except for SHA384 the minimal padding is 17 bytes). Therefore for SHA1 the whole formula is:

````
((255 + 1 + 20 + md_block_size - 1) / md_block_size) + 1
````

Or more generally:

````
((255 + 1 + md_size + md_block_size - 1) / md_block_size) + 1
````

Working this out for all the various hash algorithms gives us: MD5 == 6, SHA1 == 6, SHA224 == 6, SHA256 ==6, SHA384 == 4

We could actually simplify the formula even more because the hash size is a public value. Also the padding length value will always be present. So, with slightly less conservative assumptions we could ignore these and simplify the formula to:

````
((255 + md_block_size -1) / md_block_size) + 1
````

This would give us: MD5 == 5, SHA1 == 5, SHA224 == 5, SHA256 == 5, SHA384 == 3

I'm not sure if I have the courage to make that change though in case there is something I haven't thought of :-)

**Comment by paulidale** [comment]
@mattcaswell I'm following and in agreement up until:

```
((255 + 1 + md_size + md_block_size - 1) / md_block_size) + 1
```

I'm uncomfortable with the simplification at the end.  Even though these two sizes are known, wouldn't the presence / absence of an extra block indicate something nonetheless?

**Comment by mattcaswell** [comment]
> I'm uncomfortable with the simplification at the end. Even though these two sizes are known, wouldn't the presence / absence of an extra block indicate something nonetheless?

I can't think how it would. But I'm also a little uncomfortable, so I think we can stick with the un-simplified form.

**Comment by armfazh** [comment]
The key point is that the `kVarianceBlocks` value depends on the hash algorithm, and more specifically, in the `md_block_size` since larger SHA functions consume more data per block. Thus, there are required a less number of extra "dummy" blocks.

I considered `kVarianceBlocks = 384/md_block_size` guided by the comments in the code. However, it is more accurate the derivation proposed, which considers also the `255+1` bytes from the padding (in the worst case).
````
kVarianceBlocks = ((255 + 1 + md_size + md_block_size - 1) / md_block_size) + 1
````

**Comment by mattcaswell** [comment]
Ping @paulidale.

**Comment by paulidale** [comment]
I've merged to 1.1.1 and master.  I edited the commit message to reflect the formula actually used.

**Pull request closed without merging**
