### PR TITLE
Some small cleanups.

### PR DESCRIPTION
**Pull request by UniQP**

### CODE REVIEW

**Comment by richsalz** [comment]
Since the secmem size is not growable, we need to be able to monitor its use.  Instead of removing the variable, I'll add an API to get the value.  Touching assembler scares me, I'll leave that to Andy.  The static thing makes sense.

**Comment by UniQP** [comment]
I removed the secmem size commit.

**Comment by ghedo** [comment]
The first patch can be dropped now, since that's fixed in master (the patch was also not correct, since those variables are supposed to be `extern` not `static`).

Don't know about the other one though.

**Comment by UniQP** [comment]
I removed the first patch according to ghedo's suggestion.
Thus, only the assembly patch is left.

The assembly computes the following:
eax |= 0xf;
eax &= 0xfff;
bl = eax == 0x06ff ? 1 : 0;
// followed by eax = 0xC0000001, which means the value of eax is not important afterwards

After the first two statements eax looks like this:
0...0 xxxx xxxx 1111 and we check whether it is equal to
0...0 0110 1111 1111.

The patch changes the code to
eax &= 0xff0;
bl = eax == 0x06f0 ? 1 : 0;

Thus, eax looks like
0...0 xxxx xxxx 0000 and check whether it is equal to
0...0 0110 1111 0000.

**Comment by kroeckx** [comment]
@dot-asm: Want to take a look at this?  Looks good to me.

**Comment by dot-asm** [comment]
As I recall it, question at that point was what it takes to identify Nano. Does one look at family/model/stepping or family/model is sufficient. 0xfff mask so to say reserves for worst case scenario, i.e. family/model/stepping, in which case one would check for a range of values. And or-ing with 0x0f, which effectively takes stepping out of equation is a *hypothesis* that needs to be proved. This is why it looks the way it does. Initially trouble was that while pre-Nano processors are documented down to stepping, there is no explicit documentation about Nano-family. One can argue that the fact that no problem were reported means that hypothesis is effectively proved, and one can implement check for family/model alone. Yes, one can. At the same time we have to recognize that current code is correct and its outcome is indistinguishable from suggested modification. Don't fix ain't broken, so it's a zero vote, i.e. neither in favour or against.

**Comment by richsalz** [comment]
Based on @dot-asm's comment, closing this.

**Pull request closed without merging**
