### PR TITLE
WIP: Investigating AppVeyor failure - do not review

### PR DESCRIPTION
**Pull request by mattcaswell**
[extended tests]

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
I reproduce it easy on my side 
assert
:
Called from atime.c :

`          if (!isdigit(a[o]))`
`+		a	0x0024a378 "0€"	char *`
`		o	1	int`

**Comment by dot-asm** [comment]
#4102 should fix isdigit problem...

**Comment by mattcaswell** [comment]
The problem I am investigating here only affects server-test.exe. I cannot reproduce it locally, but it consistently fails in AppVeyor ever since commit 12fb8c3d2d.

**Comment by mattcaswell** [comment]
So, things I have discovered so far about the AppVeyor failure:

1) It only affects the master branch
2) It only affects x86 shared builds
3) PRs targeting master always pass unless you use "extended tests". Real commits to master always fail (because we always run all tests in that case). The difference is that the failure is in the fuzzing tests which don't normally get run for PRs.
4) It's only one fuzzing test that fails "server-test.exe". All others are fine. *All* the server-test corpora files fail in exactly the same way
5) We apparently need to link applink.c into our fuzz test apps on Windows, although this doesn't seem to be the cause of this failure (although possibly this means we are not testing as much of the code as we think we are on Windows???).
6) The failure is related to the existence of the symbol SSL_read_early_data in the application. If you comment out that call, everything works.
7) It is the mere *existence* of that symbol in the application that causes it to fail - even if it is never called, i.e. *all* server-test corpora files fail, even though some of them never cause SSL_read_early_data to be invoked. If the symbol exists then server-test.exe does not even load successfully!

It is the last point above which makes me think that this is some kind of dynamic linking issue. Perhaps we are picking up some other version of the OpenSSL dlls? That would make sense because SSL_read_early_data() does not exist in any released version.

But I'm starting to get to the edge of my knowledge of how windows/appveyor works. Suggestions anyone??????

**Comment by dot-asm** [comment]
Could you test another VS version? Though I'm not sure how. I mean we have VSVER: 14 in appveyour.yml, but I fail to find it in documentation. They talk about images with multiple versions, and I don't know what image do we use... See if 15 works and if does, how does it affect outcome...

**Comment by dot-asm** [comment]
As for applink.c. It's meant to engage only if application and dll are linked with different RTLs. Which means that in build-n-test scenario it shouldn't matter.... Let me see if I have "14"...

**Comment by mattcaswell** [comment]
> As for applink.c. It's meant to engage only if application and dll are linked with different RTLs

Which is interesting because at one point during my testing I had "if 0'd" out a lot of the code to persuade server-test.exe to actually load and I got a message "no OPENSSL_Applink" displayed.

**Comment by dot-asm** [comment]
Well, I forgot what does "14" means... If it corresponds to "version number" at https://en.wikipedia.org/wiki/Visual_studio#History, then I don't have 14...

**Comment by dot-asm** [comment]
15 didn't work, presumably because we use wrong image? Try 12 then. They seem to skip 13...

**Comment by mattcaswell** [comment]
VSVER:15 fails to build at all so I think 14 is the highest available. Looking at the 1.0.2 appveyor setup we have builds for 9, 10, 11, 12 and 14.

**Comment by mattcaswell** [comment]
> Try 12 then. They seem to skip 13...

Yes, 13 doesn't appear in the wiki link you sent. Will try 12.

**Comment by mattcaswell** [comment]
So MSVER 12 still fails in the same way as for MSVER 14

**Comment by FdaSilvaYY** [comment]
Some suggestions :
- dump from code or script, at the lattest possible moment, the active PATH environment variable.
- dump of a call to [openssl api version](https://www.openssl.org/docs/manmaster/man3/OpenSSL_version_num.html)

My 2'cents

**Comment by mattcaswell** [comment]
> dump of a call to openssl api version from server-test.exe

Good idea! Dumping that out I get:

    OpenSSL Version num: 1010006f

Which translates to 1.1.0f!!!!!!!!!!!!!!!!!!!!!!!!

So that confirms the theory that we are picking up some old version of OpenSSL instead of the version we just built. Now why would that be????? Hmmmmm...

**Comment by FdaSilvaYY** [comment]
So dump the runtime content of PATH .
See also [Dynamic-Link Library Search Order](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx)...

I bet there is a 3rd-party tool in this environment who is embedding the DLL you hit.
Probably in %WINDIR%\SYSWOW64, as it apply to 32bits application only,  not x64.

Run a PowerShell version `find -name libcrypto.dll ` from the appveyor.yml ? 

Welcome to DLL hell ;)

**Comment by dot-asm** [comment]
Right! One has to copy dlls to every directory with .exe files. makefile does copy them to apps/ and test/, but not to fuzz/. In other words Configurations/windows-makefile.tmpl needs an adjustment...

**Comment by dot-asm** [comment]
> Configurations/windows-makefile.tmpl needs an adjustment

Add following line after line 522
```
        COPY $shlib$shlibext fuzz
```

**Comment by dot-asm** [comment]
Well, though final version should also have `IF EXIST test\\$shlib$shlibext DEL /Q /F fuzz\\$shlib$shlibext`. I mean one-line change would show if ci problem is resolved...

**Comment by dot-asm** [comment]
This actually explains even applink thing. I mean it shouldn't be a problem now.

**Comment by mattcaswell** [comment]
> This actually explains even applink thing. I mean it shouldn't be a problem now.

Yes, I was just thinking the same thing. Latest appveyor build is green so it seems this works. I'm going to close this PR now and create a new one with just the fix.

**Pull request closed without merging**
