### PR TITLE
Fix VMS installation - update vmsconfig.pm for consistency

### LINKED ISSUE #22899: On VMS with 64-bit pointers: No "64" in OSSL$INSTROOT:[SYS$STARTUP] DCL scripts
OpenSSL version 3.0.7, 3.0.12, and, I assume, many others. 
(Inspection suggests that 3.2.0 is similarly afflicted, so I'd guess
that 3.1.x is, too, as well as older ones.)

   On VMS, in a build with 64-bit pointers, various file specs and
logical names in the OSSL$INSTROOT:[SYS$STARTUP] DCL scripts are not
getting the desired/expected "64" modifier.  Many things fail when the
wrong ("64"-less) names are used.

   Cause: Error in templates for OSSL$INSTROOT:[SYS$STARTUP] DCL
scripts:

      [.VMS]openssl_ivp^.com.in
      [.VMS]openssl_shutdown^.com.in
      [.VMS]openssl_startup^.com.in:

   In each of these "*^.com.in" templates:

$       pz   := {- $target{pointer_size} -}

should be:

$       pz   := {- $config{pointer_size} -}

(Compare "pz" with, for example, "OPENSSLDIR" in
"[.VMS]openssl_startup^.com.in".  Refer to "[]vmsconfig.pm" to see where
"pointer_size" really is.)

   Note: The actual _files_ (.OLB, .EXE) are created with the "64" in
their names; only the OSSL$INSTROOT:[SYS$STARTUP] DCL scripts which
(should) point to them are wrong.

--------

   While we're looking at VMS stuff, here's an unrelated complaint:

   Some VMS-specific code uses obsolete conditions like:

      # ifdef __alpha
      #if defined __alpha

which, I'd venture, should be replaced by things like, say:

      # ifndef __VAX
      $if !defined __VAX

   For many purposes, the VMS world is divided into (1) VAX and
(2) everything after VAX (Alpha, IA64, x86_64, ...).  In almost all
cases, testing for VAX makes more sense than testing for any particular
post-VAX architecture (such as "__alpha").

      [.apps.lib]vms_term_sock.c
      [.providers.implementations.rands.seeding]rand_vms.c

--------

   Around here:

   ITS $ @ config -64 --prefix=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.3_0_12-64z] - 
   _ITS $  --openssldir=UTILITY_DEV:[UTILITY.SOURCE.OPENSSL.3_0_12-64z]

   ITS $ mms
   ITS $ mms test
   ITS $ mms install

   ITS $ tcpip show version ! (Not that it matters much)

     HP TCP/IP Services for OpenVMS Industry Standard 64 Version V5.7 - ECO 5
     on an HP rx2600  (1.50GHz/6.0MB) running OpenVMS V8.4-2L3

   ITS $ cc /version

   VSI C V7.4-001 on OpenVMS IA64 V8.4-2L3

### PR DESCRIPTION
**Pull request by levitte**
An effort was made to update the VMS installation data to align with
configuration data.  This touched the script templates in VMS/, but
didn't update the generation of vmsconfig.pm to match...  and also
missed a spot.

This change adds the missing updates

Ref:
https://github.com/openssl/openssl/pull/16842

Fixes #22899

### CODE REVIEW

**Comment by levitte** [comment]
I've verified that these two commits cherry-pick cleanly to 3.1, 3.2
and master

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Ping, @openssl/committers ?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by levitte** [comment]
Merged

3.0:
4058e121cbc6818235b0dcb618e636ce3c4d1f2f Fix VMS installation - update vmsconfig.pm for consistency
a43f253d586279b5d96fffcaf1b26c7a2b0dd938 VMS: Add the missing -p32 and -p64 variants for x86_64

3.1:
d2c20500032722d05f36a6664f4a813fe6320ef6 Fix VMS installation - update vmsconfig.pm for consistency
143a0915e34553912ee37331b189e78096861bfb VMS: Add the missing -p32 and -p64 variants for x86_64

3.2:
ce81e43707d1c855004979a35c3b8c74954d5ddb Fix VMS installation - update vmsconfig.pm for consistency
bef1ef36a13a4174d5907f5ecce11b7e17b06129 VMS: Add the missing -p32 and -p64 variants for x86_64

master:
3077bfb78e6fcca006359dc9e3f2b37ad104222d Fix VMS installation - update vmsconfig.pm for consistency
8d8c1600aed80b30e6dc00cbf1a9559feabec8ca VMS: Add the missing -p32 and -p64 variants for x86_64

**Pull request closed without merging**
