### PR TITLE
MacOS prior to 10.12 does not support random API correctly [branch OpenSSL_1_1_1-stable]

### LINKED ISSUE #16517: Regression: 1.1.1l test failure on MacOS El Capitan ( 10.11.6 ) using Homebrew
I just tried to upgrade OpenSSL on homebrew on my older mac.
1.1.1k and earlier work fine

Here is the system info:

```
   System Version: OS X 10.11.6 (15G22010)
   Kernel Version: Darwin 15.6.0
```

Checkout tag: `OpenSSL_1_1_1l`

Configure step:
`perl ./Configure no-ssl3 no-ssl3-method no-zlib -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include darwin64-x86_64-cc`

`make test V=1 TESTS=test_rand` output (relevant bits, ignore successful tests):

```
/Library/Developer/CommandLineTools/usr/bin/make depend && /Library/Developer/CommandLineTools/usr/bin/make _tests
( cd test; \
	  mkdir -p test-runs; \
	  SRCTOP=../. \
	  BLDTOP=../. \
	  RESULT_D=test-runs \
	  PERL="perl" \
	  EXE_EXT= \
	  OPENSSL_ENGINES=`cd .././engines 2>/dev/null && pwd` \
	  OPENSSL_DEBUG_MEMORY=on \
	    perl .././test/run_tests.pl test_rand )
../test/recipes/05-test_rand.t .. 
1..2
    # Subtest: ../drbgtest
    1..6
        # Subtest: test_kats
        1..6
        ok 1 - iteration 1
        ok 2 - iteration 2
        ok 3 - iteration 3
        ok 4 - iteration 4
        ok 5 - iteration 5
        ok 6 - iteration 6
    ok 1 - test_kats
        # Subtest: test_error_checks
        1..6
        ok 1 - iteration 1
        ok 2 - iteration 2
        ok 3 - iteration 3
        ok 4 - iteration 4
        ok 5 - iteration 5
        ok 6 - iteration 6
    ok 2 - test_error_checks
    # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:697
    # [11] compared to [0]
    # ERROR: (bool) 'test_drbg_reseed_after_fork(master, public, private) == true' failed @ test/drbgtest.c:799
    # false
    not ok 3 - test_rand_drbg_reseed
    ok 4 - test_rand_seed
    ok 5 - test_rand_add
    ok 6 - test_multi_thread
../../util/shlib_wrap.sh ../drbgtest => 1
not ok 1

#   Failed test at ../test/recipes/05-test_rand.t line 16.
    # Subtest: ../drbg_cavs_test
    1..1
        # Subtest: test_cavs_kats
        1..4320
        ok 1 - iteration 1
        ok 2 - iteration 2
....
```
```
    ok 1 - test_cavs_kats
../../util/shlib_wrap.sh ../drbg_cavs_test => 0
ok 2
# Looks like you failed 1 test of 2.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 

Test Summary Report
-------------------
../test/recipes/05-test_rand.t (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=2,  5 wallclock secs ( 0.38 usr  0.06 sys +  5.71 cusr  2.48 csys =  8.63 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make: *** [tests] Error 2
```

### PR DESCRIPTION
**Pull request by lprimak**
Fixes #16517

### CODE REVIEW

**Comment by lprimak** [comment]
ICLA sent

**Review by paulidale — APPROVED** [review]

**Comment by slontis** [comment]
Isnt this a problem in master/3.0 also?

**Comment by lprimak** [comment]
Maybe... I can get a patch for 3 as well.. lemme look

**Comment by lprimak** [comment]
patches created for all 3 branches (linked above)

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to 1.1.1 branch. Thank you for the contribution.

**Pull request closed without merging**
