### PR TITLE
Add linux-mips32be target for new platform

### PR DESCRIPTION
**Pull request by SteveMarquess**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by dot-asm** [comment]
Is it already carved in stone? Thing is that it's not a coincidence that there is not "flavour" at the end of mips32_asm line. MIPS assembler pack works with multiple ABIs and "flavour" is meant to be provided by platform line. o32, n32, 64, nubi32, nubu64 are recognized. See for example vxworks-mips, that o32 is "flavour" and suggested modification will break it (as would all irix lines, but those were never actually validated).

**Comment by SteveMarquess** [comment]
On 04/25/2017 05:47 PM, Andy Polyakov wrote:
> Is it already carved in stone? Thing is that it's not a coincidence that
> there is not "flavour" at the end of mips32_asm line. MIPS assembler
> pack works with multiple ABIs and "flavour" is meant to be provided by
> platform line. o32, n32, 64, nubi32, nubu64 are recognized. See for
> example vxworks-mips, that o32 is "flavour" and suggested modification
> will break it (as would all irix lines, but those were never actually
> validated).
> 

Unfortunately yes, for better or worse.

-Steve M.

-- 
Steve Marquess
OpenSSL Validation Services, Inc.
1829 Mount Ephraim Road
Adamstown, MD  21710
USA
+1 301 874 2571
marquess@openssl.com
gpg/pgp key: http://openssl.com/docs/0x6D1892F5.asc

**Comment by SteveMarquess** [comment]
On 04/26/2017 09:26 AM, Andy Polyakov wrote:
> *@dot-asm* approved this pull request.
> 
> No choice is left.
> 
> —

Andy, if there's a more appropriate fix that won't affect an previously
tested platforms (including this one) then I can try to slip it in the
next revision (2.0.17). If so point me to a patch and I'll file it away
for 2,0.17, which will probably be coming along soon enough.

Depending on the nature of 2.0.17 including extraneous mods may or may
not be feasible, but I'll have it filed away.

-Steve M.

-- 
Steve Marquess
OpenSSL Validation Services, Inc.
1829 Mount Ephraim Road
Adamstown, MD  21710
USA
+1 301 874 2571
marquess@openssl.com
gpg/pgp key: http://openssl.com/docs/0x6D1892F5.asc

**Comment by dot-asm** [comment]
> if there's a more appropriate fix that won't affect an previously tested platforms (including this one)

Unfortunately I have trouble wrapping my mind around this. This request affects previously tested platform and kind of relies on not specified behaviour. I mean mips scripts accept o32, n32, 64, etc. They do *something* if you pass void, and apparently it worked out, but this is not the kind of thing that should be left to chance. So with this in mind what would be appropriate to do? Just fix it up so that vxworks-mips works again and linux-mip32be keeps passing void? Would it be appropriate to remove "EXTREME" commentary?

**Comment by SteveMarquess** [comment]
On 04/26/2017 10:30 AM, Andy Polyakov wrote:
>     if there's a more appropriate fix that won't affect an previously
>     tested platforms (including this one)
> 
> Unfortunately I have trouble wrapping my mind around this. This request
> affects previously tested platform and kind of relies on not specified
> behaviour. I mean mips scripts accept o32, n32, 64, etc. They do
> /something/ if you pass void, and apparently it worked out, but this is
> not the kind of thing that should be left to chance. So with this in
> mind what would be appropriate to do? Just fix it up so that
> vxworks-mips works again and linux-mip32be keeps passing void? Would it
> be appropriate to remove "EXTREME" commentary?

Comments we can remove (with a change letter update).

Non-comment changes are going to be difficult unless we can affirm that
no previously affected platform will be affected. In the past we have
been able to make some changes like that, where you had an argument that
even though the compiler flags for previously tested platform(s) were
changed that still didn't effect the object code that was generated by
the compiler.

-Steve M.

-- 
Steve Marquess
OpenSSL Validation Services, Inc.
1829 Mount Ephraim Road
Adamstown, MD  21710
USA
+1 301 874 2571
marquess@openssl.com
gpg/pgp key: http://openssl.com/docs/0x6D1892F5.asc

**Comment by snhenson** [comment]
Reopening this because it couldn't be included in the fips2 stable branch at the time. Please reconfirm it is OK to cherry-pick.

**Comment by richsalz** [comment]
reconfirm.

**Pull request closed without merging**
