### PR TITLE
Offer PBE key streching via command line app

### PR DESCRIPTION
**Pull request by johndoe31415**
The key streching functions PBKDF2 and scrypt currently do not have any
way of performing key derivation via the command line interface. This
patch adds an app called "pbe" which offers this functionality.

### CODE REVIEW

**Comment by richsalz** [comment]
This is a nice patch, well done.  I'll work on getting it into master soon.

**Comment by johndoe31415** [comment]
Hey Rich,

thank you very much :-) I think it'd be really cool if this were merged, it's one of the very very few features I'm missing from OpenSSL at the moment.

And I also wanted to try out the new development process with GitHub. Absolutely love the direction OpenSSL is going. Keep up the great work.

Best regards,
Johannes

**Comment by richsalz** [comment]
Someone on the team is thinking about being able to treat PBE's as KDF, and being able to generalize.  So this is on hold for now.

**Comment by johndoe31415** [comment]
Hi Rich,

hm, I'd argue against putting it into the KDF routines (i.e. "openssl dgst"). I thought about it when implementing the PBE and my reasoning was that "dgst" already is horribly bloated: It handles digests, signatures and MAC. While they all rely on cryptographic hash functions in their bellies, each are very different beasts. As is PBE, in my opinion.

However, if the "dgst" facility would see a major overhaul, that would even have the great benefit of making it easier to use (and then it would also maybe be possible to cleanly integrate PBE). If you refer me to the discussion thread, I'd like to participate in the talks, I'm subscribed to openssl-user :-)

Best regards,
Johannes

**Comment by levitte** [comment]
Hmmm... @richsalz, your remark back in January, how did that all play out?  Is this PR still relevant?

**Comment by richsalz** [comment]
Nothing ever happened; Henson didn't review.

**Comment by johndoe31415** [comment]
Hi there, I'd still like to contribute since it's a feature I find important and one that I'd like to push forward. Is there anything that I can contribute that would make sense? Any discussion or modification of the PR to work against latest master? Please let me know. Thanks, Joe

**Comment by richsalz** [comment]
Perhaps start some discussion on openssl-dev as a post-1.1 feature.

**Comment by richsalz** [comment]
+1

**Comment by richsalz** [comment]
can you rebase against 1.1.0 and push an update?

**Comment by johndoe31415** [comment]
Hi Rich,

just rebased against openssl/master and also did some refactoring (i.e., used OpenSSL-specific option parsing instead of doing custom stuff). However I think I messed up something in the rebase, the whole PR now looks awful. Should I start fresh and put in a new PR or is this something you can work with? Sorry for the trouble, I'm not sure where I took a wrong turn :-(

Cheers,
Johannes

**Comment by richsalz** [comment]
Sure, close and start from scratch.  No problem!

**Comment by johndoe31415** [comment]
Closing so I can reopen this PR.

**Pull request closed without merging**
