### PR TITLE
Add echo for end of each build phase

### PR DESCRIPTION
**Pull request by richsalz**
Replaces #3834

### CODE REVIEW

**Comment by levitte** [comment]
You could have them make more sense like this:

```
if {cmd}; then
    echo "/// MAKE whatever"
else
    echo "/// MAKE whatever FAILED"
    false
fi
```

right?

So for example, instead of this:

```
          HARNESS_VERBOSE=yes BORING_RUNNER_DIR=$top/boringssl/ssl/test/runner make test;
          case $? in
          0) echo '/// MAKE TEST END' ;;
          *) echo '/// MAKE TEST FAILED' ; false ;;
          esac;
```

You could have this:

```
          if HARNESS_VERBOSE=yes BORING_RUNNER_DIR=$top/boringssl/ssl/test/runner make test; then
              echo '/// MAKE TEST END' ;
          else
              echo '/// MAKE TEST FAILED' ; false ;
          fi;
```

**Comment by richsalz** [comment]
Shrug, style.  But okay.

**Comment by dot-asm** [comment]
/// turns to be suboptimal choice. I mean idea is to have unique pattern that allows you navigate easily in travis log. And /// is not unique, it hits even file:///home/... And once again, wouldn't it be nicer if it didn't hit "starting this; echo ///..."? I.e. would bring you specifically to the line of interest?

**Comment by richsalz** [comment]
Echo, let’s try ```echo -e \100\100\100``` to get ```@@@```

**Comment by levitte** [comment]
... because, for some reason, `echo "@@@"` doesn't work?

**Comment by richsalz** [comment]
Because, as Andy pointed out, that will match the echo command, not just the output

**Comment by levitte** [comment]
Doh...

I think it's bed time for me ;-)

**Comment by dot-asm** [comment]
It has to be "\0100", note quotes and zero after backslash. BTW, /// was handy, because it doesn't take shift to enter ;-), and I was hinting on more than three slashes, but sure, tripple-@ would do just as fine...

**Comment by richsalz** [comment]
Let’s try this again. ☺

**Comment by dot-asm** [comment]
Sneaky travis... It manages to unescape \057 when reporting command exited with exit code... So that there still are undesired hits...  But if you used *increasing* amount of slashes for each echo, i.e. first 4, then 5, it would be really easy to advance to next mark... As mentioned earlier, open log in browser, ctrl-f, then enter first four slashes, then add one more...

**Comment by richsalz** [comment]
Trying again.

**Comment by dot-asm** [comment]
Do you find it handy yourself? I do...

**Comment by richsalz** [comment]
okay to cherry-pick to 1.1.0 and 1.0.2?

**Comment by dot-asm** [comment]
I don't believe it will cherry-pick... But sure, try...

**Comment by richsalz** [comment]
Thanks guys!

**Comment by paulidale** [comment]
I'm late to the party, but might it make sense to have the string being echoed built up and kept in a variable?  If an extra stage is added, it would save editing (& errors).  It would also avoid skipping a slash when a stage is optional.

**Comment by richsalz** [comment]
neat idea.  oh well :)

**Comment by richsalz** [comment]
It didn’t.  See #3844 and #3845 ☺

**Pull request closed without merging**
