### PR TITLE
Add parentheses on public macros where appropriate

### LINKED ISSUE #3063: Macro arguments should be in parentheses
I think this is a more general problem,
it starts with the following example in  https://www.openssl.org/policies/codingstyle.html:
```
    #define macrofun(a, b, c)   \
        do {                    \
            if (a == 5)         \
                do_this(b, c);  \
        } while (0)
```

which is more or less the way how not to do it, because at least if (a == 5)
should always be written as if ((a) == 5).

And a grep reveals many macros with un-parenthesed macro arguments:
```
crypto/bio/b_print.c:#define char_to_int(p) (p - '0')
crypto/bio/b_print.c:#define OSSL_MAX(p,q) ((p >= q) ? p : q)
include/openssl/ssl.h:# define SSL_set_app_data(s,arg)         (SSL_set_ex_data(s,0,(char *)arg))
include/openssl/ssl.h:# define SSL_SESSION_set_app_data(s,a)   (SSL_SESSION_set_ex_data(s,0,(char *)a))
include/openssl/ssl.h:# define SSL_CTX_set_app_data(ctx,arg)   (SSL_CTX_set_ex_data(ctx,0,(char *)arg))
```

(this is only an incomplete list)

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Code-health, although today is not Tuesday :)
Fixes #3063.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
I don't know how much of this PR can be cherry-picked for 1.1.0 and 1.0.2
but I can create extra PRs if that is considered useful for back-porting.

**Comment by richsalz** [comment]
please do that.

**Comment by dot-asm** [comment]
Hmm... I for one would vote *against* taking it to *released* branches.

**Comment by richsalz** [comment]
okay, why?

**Comment by dot-asm** [comment]
Because these are not *bugs*.

**Comment by kroeckx** [comment]
I have to agree that this should go to the stable branches.

**Comment by levitte** [comment]
What would the motivation be to take this to the stable branches?  @dot-asm is right, these changes aren't bug fixes per se, and they don't make future backports easier (unless we're touching these specific macros, but that happens *very* seldom), so yeah, I also have a hard time motivating a backport...

**Comment by richsalz** [comment]
They seem to me to fix latent bugs, such as if you do p + 1 to the BIO set-host macro.
Yes, not all of them are.

**Comment by dot-asm** [comment]
> They seem to me to fix latent bugs,

Not quite, they rather *prevent* bugs. While definition of branch in maintenance mode is [actual] bug *fixing*. Well, we all know that we are quite liberal about this in 1.1.0 context, and this might be viewed as kind of a grey area, but public headers are are not as grey as rest of the code. Yes, there is contradiction here, public headers need it most, but their modification is not to be taken lightly.

**Comment by bernd-edlinger** [comment]
Ping?

**Comment by mattcaswell** [comment]
Approved for master only

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
