### PR TITLE
Fix gcc-7 strict-warnings build

### PR DESCRIPTION
**Pull request by bernd-edlinger**
- Mostly missing fall thru comments
- And uninitialized value used in sslapitest.c

### CODE REVIEW

**Comment by levitte** [comment]
Oh my, the /* fall thru */ comment is still a current thing?  Almost feels nostagic ;-)

**Comment by levitte** [comment]
Is this for master only, or do you expect this to be cherry-picked to 1.1.0 as well?

**Comment by bernd-edlinger** [comment]
this is for master only, other branches are fine.
(just a few weeks ago master had no warnings)

**Comment by richsalz** [comment]
Really nostalgic would spell it FALLTHROUGH :)

**Comment by bernd-edlinger** [comment]
Yes, that would work as well.

**Comment by levitte** [comment]
Merged.  018fcbec38509cd03fb0709904a382c3bfcf5ed4

**Pull request closed without merging**
