### PR TITLE
Update the alert description to common protocol

### LINKED ISSUE #7953: Confuse description in SSL_str_reasons
The common error description in SSL and  TLS  was defined begin with sslv3, and SSL3.0 was disable default from the security consider, and the string reason that begin with sslv3 will confuse that sslv3 was still used.

Example:
sslv3 alert bad certificate

Will it better that update to begin with SSL/TLS or remove the sslv3?

### PR DESCRIPTION
**Pull request by KanPlus**
Update the alert description to common protocol
Fixes #7953
##### Checklist

- [X] tests are added or updated

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
Merge commits are not allowed by the project.
Please just rebase your branch over the `openssl/master` branch.

**Comment by KanPlus** [comment]
> Merge commits are not allowed by the project.
> Please just rebase your branch over the `openssl/master` branch.

rebased done,please help check,thanks

**Comment by t8m** [comment]
No, you still have merge commits in the PR. `git rebase -i --autosquash master` might help you to drop the merge commits.

**Comment by paulidale** [comment]
Kicking CLA bot.

**Comment by KanPlus** [comment]
> No, you still have merge commits in the PR. `git rebase -i --autosquash master` might help you to drop the merge commits.

Thanks for your suggestion, Redundant submission have keeped in the forked response, tied rebase with the upstream and success currently.

**Comment by KanPlus** [comment]
> Kicking CLA bot.

Thanks for your effort

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
I am not really sure this is a correct change. Also if we decide to merge this, I suppose the other version numbered alert descriptions should lose the version number - for consistency.

**Comment by t8m** [comment]
@mattcaswell What is your opinion about this one?

Also if we decide to change this, as this is imo not a pure bug fix it should go to Post 3.0.

**Comment by richsalz** [comment]
Do you know that nobody is relying on the current texts?  I agree they should be updated -- seeing 'SSL/TLS' is annoying -- but it does seem risky.

**Comment by KanPlus** [comment]
> I am not really sure this is a correct change. Also if we decide to merge this, I suppose the other version numbered tlsv1 alert descriptions should lose the version number - for consistency.

these string explain the alert, these alert define both tls1.x and ssl3.0, so tls/ssl can be response the actual meaning. macro still keeped as string already explained.

**Comment by KanPlus** [comment]
> @mattcaswell What is your opinion about this one?
> 
> Also if we decide to change this, as this is imo not a pure bug fix it should go to Post 3.0.
this PR not response bug in source logic， only impact the readability.

**Comment by KanPlus** [comment]
> Do you know that nobody is relying on the current texts? I agree they should be updated -- seeing 'SSL/TLS' is annoying -- but it does seem risky.

this should  not impact the implement logic, but may impact the log/document information etc. the sslv3 text may confuse the user in case that tls1.x have used but sslv3 still present in the log, and sslv3 regards not security  any more.

**Comment by KanPlus** [comment]
Fialed  to drop the merge commits with "git rebase -i --autosquash master", will try drop further.

**Comment by KanPlus** [comment]
> Fialed to drop the merge commits with "git rebase -i --autosquash master", will try drop further.
--It is hard to handle the the confusion, close this PR and raise new PR.

**Comment by KanPlus** [comment]
#17159 have raised,Thanks for your attention. @paulidale @t8m @richsalz @FdaSilvaYY

**Pull request closed without merging**
