### PR TITLE
Fix a possible crash in rand_drbg_get_entropy

### PR DESCRIPTION
**Pull request by bernd-edlinger**

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Ah, I forgot to set the 1.1.1 label, is your approval also valid for 1.1.1 ?

**Comment by mspncp** [comment]
Shure, reapproved. All bugfixes should go into 1.1.1 by default IMO.

**Comment by mspncp** [comment]
Self-promotion for my new [cherry-checker](https://github.com/openssl/tools/blob/master/review-tools/cherry-checker) tool: Your pull request fixes 3064b55134, which was backported to dbf0a49625.


 prnum | fixes | br |   commit   |   subject
 ----- | ----- | -- | ---------- | -------------------------------------------
 #7382 | #7381 | -> | dbf0a49625 | DRBG: fix reseeding via RAND_add()/RAND_seed() with large input 
 #7382 | #7381 | <- | 3064b55134 | DRBG: fix reseeding via RAND_add()/RAND_seed() with large input

**Comment by paulidale** [comment]
Approved to 1.1.1 too.

**Comment by bernd-edlinger** [comment]
Merged to master: 21311777ad8b8c2f2fb8eb7a4f9618ceae1e043d / 1.1.1: f3f7f1a826617af80a92f58d494ec2c8348251a5
Thanks!

**Pull request closed without merging**
