### PR TITLE
Add Clang 3.6 and additional GCC 5 builds to travis

### PR DESCRIPTION
**Pull request by ghedo**
Follow-up to f386742.

(I already squashed the changes into a single commit to make merging easier).

### CODE REVIEW

**Comment by dot-asm** [comment]
+1

On related note, I get no errors with -fsanitize=undefined with clang-3.7...

**Comment by ghedo** [comment]
@dot-asm you also need to pass `-fno-sanitize-recover` otherwise the errors are not fatal.

**Comment by richsalz** [comment]
commit'd thanks!

**Comment by richsalz** [comment]
@dot-asm want me to do a PR with adds that flag?

**Comment by richsalz** [comment]
oh, never mind:  that's ghedo talking to andy :)

**Pull request closed without merging**
