### PR TITLE
apps: fix Coverity 1451531 Unchecked return value

### PR DESCRIPTION
**Pull request by paulidale**
This is the only outstanding Coverity issue.  It was raised two years ago and has been marked ignore for ages.

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by kaduk** [comment]
IIRC, the `(void)` cast is no longer enough to appease gcc.  Are we sure that they are enough for Coverity?

**Comment by paulidale** [comment]
I don't know.  It's not complaining about the others that are void cast but that could be for other reasons.

**Comment by t8m** [comment]
> `(void)` cast is no longer enough to appease gcc.

Which is, frankly, quite bad behavior of gcc. I should be able to silence a warning with a simple thing like the cast, if I know what I am doing.

**Comment by paulidale** [comment]
Ping for a review or an alternative suggestion to remove this warning?

**Review by kaduk — APPROVED** [review]
I suppose this is tolerable, but what would the caller do if we just returned the current count or continued to the next loop iteration instead of ignoring errors?

**Comment by paulidale** [comment]
My first thought is: _get bad performance measurements_.

I guess something could be done to handle errors in performance loops.  Sadly, doing so will adversely impact performance -- probably not an issue for most but things but some might.

Doing it badly could marked improve apparent performance (go to next iteration without accounting for the problem e.g.).

**Comment by kaduk** [comment]
I mean, we get bogus performance numbers if the crypto calls just return early with an error, too.  It's not *a priori* clear that one type of error is better or worse than the other.

**Comment by paulidale** [comment]
Agreed.

I think it very unlikely that the calls will fail, so added checks would seem like it would slow things down (very slightly) without reason.

Still, something I'll raise for OTC discussion.

**Review by t8m — APPROVED** [review]

**Comment by beldmit** [comment]
My real-life test cases:
If I measure performance of the correctly set environment (e.g. license file is up-to-date for the commercial implementation), I'm interested in immediate failure.
If I measure performance of "something similar to new implementation" (e.g. I want to comment out some function to see if it has an impact to the performance), I'd like to test it all the time it should be tested. So for post-3.0 I'd prefer smth like an option `-immediate-failure`, but for now it's OK to me.

**Comment by paulidale** [comment]
Merged to master.  Figuring out a better way to do speed is something for the future I feel.

**Pull request closed without merging**
