### PR TITLE
OCSP Updates: error codes and multiple certificates

### PR DESCRIPTION
**Pull request by tmshort**
RT3877: Add X509 OCSP error codes and messages
Add additional OCSP error codes for X509 verify usage

RT3867: Support Multiple CA certs in ocsp app
Add the ability to read multiple CA certs from a single file in the
ocsp app.

### CODE REVIEW

**Comment by jrchamp** [comment]
Looks like this might fix #889 Thank you!

**Comment by tmshort** [comment]
Updated comment, and fixed where EVP_sha1() was always being used.

**Comment by mattcaswell** [comment]
This looks like a post-1.1.0 thing...i.e. its a new feature.

**Comment by levitte** [comment]
I agree with @mattcaswell and have marked it as such

**Comment by tmshort** [comment]
Ok, this has been rebased onto master... time to look at it again?

**Comment by richsalz** [comment]
Finally :)  3bb0f98 in master.  Thanks!

**Pull request closed without merging**
