### PR TITLE
CMP: add `-no_cache_extracerts` option, fix saving and loading empty cert lists

### PR DESCRIPTION
**Pull request by DDvO**
This fixes some corner cases on saving and loading empty cert lists and prematurely deleting cert files in the CMP app.
Doing so, I strengthened several test cases as needed.
This way I found that an option is needed for not caching certificates received in the `extraCerts` CMP message field.
So added this option (both at API and CLI level) and adapted the test cases accordingly.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by DDvO** [comment]
I've just rebased this PR and added a commit that 
improves the error reporting of `ossl_cmp_msg_check_update()` when checking the expected sender name.

**Comment by DDvO** [comment]
Carved out one fix to #20035, for separation of concerns and simplifying review of this PR.

**Comment by DDvO** [comment]
Rebased again to fix merge conflicts.

**Comment by DDvO** [comment]
Rebased to fix merge conflicts

**Comment by DDvO** [comment]
Added (in a separate commit) a minor improvement on cert verification diagnostics in `cmp_vfy.c/check_msg_all_certs()`: 
remove needless trace output in case 3GPP mode is not enabled.

**Comment by DDvO** [comment]
Hmm, the **check-ansi** CI run [keeps failing](https://github.com/openssl/openssl/actions/runs/5231886979/jobs/9446304259?pr=19948) although I've meanwhile removed some unrelated recent commits to master that include in commit fd54fadba6bc138fb35a82c033c540f7e97322c8 an extension to `test/cmactest.c` that causes trouble.

**Comment by DDvO** [comment]
Rebased to get rid of the **check-ansi** CI failure.

**Comment by DDvO** [comment]
Rebased to fix merge conflicts

**Comment by DDvO** [comment]
Can we please bring this PR forward.
It is waiting for reviews meanwhile for over a year.

**Review by slontis — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
Merged - thank you @slontis and @t8m for your reviews&approvals.

**Pull request closed without merging**
