### PR TITLE
Use void in all function definitions that do not take any arguments

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by richsalz** [comment]
This changes the function definitions.  Shouldn't you also change the declarations?

**Comment by kroeckx** [comment]
If there is a declaration without void, it already produce an error when building with --strict-warnings that there is no prototype.

**Comment by kroeckx** [comment]
I was able to find 1 where it did have () in the header, but that seems to be because it's an assembler function.

**Comment by richsalz** [comment]
I wonder if there's a -W flag we can use to catch f() which should be f(void) ?

**Comment by levitte** [comment]
`man gcc`:

```
       -Wstrict-prototypes (C and Objective-C only)
           Warn if a function is declared or defined without specifying the
           argument types.  (An old-style function definition is permitted
           without a warning if preceded by a declaration that specifies the
           argument types.)
```

**Comment by kroeckx** [comment]
That's what we already have.

**Comment by richsalz** [comment]
Yes, and that flag does not catch this situation that Kurt fixed.

**Pull request closed without merging**
