### PR TITLE
Increase test coverage by enabling more build options

### PR DESCRIPTION
**Pull request by t8m**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Just a draft for now

**Comment by t8m** [comment]
So yeah, apparently this works to increase the coverage at least a little: https://coveralls.io/builds/50169775

**Comment by beldmit** [comment]
I like the idea but do the tests you added pass?

**Comment by t8m** [comment]
> I like the idea but do the tests you added pass?

Yes. The build succeeded otherwise the coverage result would not be visible at the link above.

I've run it first on pull request and the fixup commit reverts that change.

**Review by hlandau — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master branch. Thank you for your reviews.

**Pull request closed without merging**
