### PR TITLE
enhancement(md6.c): Added a new hash type called MD6

### PR DESCRIPTION
**Pull request by pneb**
## Changes

- This commit adds a new hash type called MD6 to the md6.c file. This new hash type enhances the capabilities of the file and improves its overall functionality.

### CODE REVIEW

**Comment by slontis** [comment]
Before suggesting what needs to be done to integrate this into a provider and test it. 
In what scenario do you see this (2008) algorithm being useful for users, compared to other algorithms?

**Comment by pneb** [comment]
> Before suggesting what needs to be done to integrate this into a provider and test it. In what scenario do you see this (2008) algorithm being useful for users, compared to other algorithms?

Yes, MD6 is already out there but no code has been implemented. So, implementing it nowadays is reasonable!

**Comment by slontis** [comment]
A quick google search indicates that there are better alternatives.

**Comment by paulidale** [comment]
Is there a formal national or international standard for MD6?
That's a requirement for inclusion in OpenSSL.

**Comment by slontis** [comment]
Pauli it was a SHA-3 finalist, which was slower than other submissions. (And at the time lacking some proofs)

**Comment by pneb** [comment]
> Is there a formal national or international standard for MD6? That's a requirement for inclusion in OpenSSL.

https://en.m.wikipedia.org/wiki/MD6

**Comment by t8m** [comment]
For the CLA hold to be removed, the commit has to be done with the e-mail address that was on the CLA submission. (There can be multiple e-mails listed.)

**Comment by pneb** [comment]
> For the CLA hold to be removed, the commit has to be done with the e-mail address that was on the CLA submission. (There can be multiple e-mails listed.)

I am using the provided e-mail address, this account was created using that e-mail

**Comment by paulidale** [comment]
The author's email for the git commits is: 109844019+pneb@users.noreply.github.com
The CLA check prints this out when it isn't in the database.

**Comment by pneb** [comment]
> The author's email for the git commits is: [109844019+pneb@users.noreply.github.com](mailto:109844019+pneb@users.noreply.github.com) The CLA check prints this out when it isn't in the database.

shocks, what the freak is that e-mail lol?! Well thanks, is it okay for you to close this pull request and I'll try to open a new one?

**Comment by paulidale** [comment]
You should be able to change the author's email via a `git commit --amend` command.

That address is a GitHub created thingy.  Not sure what the reasons behind it coming up or not are.

It's fine to close this and open a new PR if you want.

**Pull request closed without merging**
