### PR TITLE
Cleanup legacy digest methods.

### PR DESCRIPTION
**Pull request by slontis**
Macros have been added to generate the simple legacy methods.
Engines and EVP_MD_METH_get methods still require access to the old legacy methods,
so they needed to be added back in.
They may only be removed after engines are deprecated and removed.
Removed some unnecessary #includes and #ifndef guards (which are done in build.info instead).

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by romen** [comment]
Should the legacy methods be deprecated as well in favor of EVP?
(Maybe as a separate PR if it requires some discussion and votes)

**Comment by paulidale** [comment]
Yes, they should be.  There will have to be a big deprecation pass before 3.0 is released.

**Comment by mattcaswell** [comment]
> There will have to be a big deprecation pass before 3.0 is released.

I already started this with some of the low level APIs (see #10580). Unfortunately I've run into some problems with that PR.

**Comment by slontis** [comment]
Merged to master.. Thanks.

**Pull request closed without merging**
