### PR TITLE
Recreate OS390-Unix

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
@t-j-h, if you have the possibility to test this branch, that would be great.

**Comment by dot-asm** [comment]
Extending on argument in #5032, I'd like to suggest that *everything* in Configuration that we touch, but can't actually test, should go to separate .conf file. At some earlier point I said that most targets we inherited from 1.0 are kind of in "quantum uncertainty" state, in sense that we don't know if they work because nobody actually measured. It's more than appropriate to start cleaning it up by at least classifying targets to those we know work [or at least have some capacity and willing to devote an effort actually looking into potential problem], and those we don't know if they were even tested. If some external vendor/contributor feels that classifying a target as broadly "community-supported" is inappropriate, one can as well arrange separate file for vendor/contributor. For example if Stratus considers that having VOS configs in say 50-community.conf is inappropriate, 25-stratus.conf can as well be arranged...

**Comment by richsalz** [comment]
I strongly agree with @dot-asm put this in a separate conf file.  -1 until that's done.

**Comment by levitte** [comment]
I agree, it should be in a separate config.  I followed the pattern we already have.

**Comment by dot-asm** [comment]
There is really no point pretending that it works...

**Comment by t-j-h** [comment]
We have a platform policy. I suggest you re-read it.
If you want to change the platform policy then discuss that on openssl-project.

**Comment by dot-asm** [comment]
Which word at https://www.openssl.org/policies/platformpolicy.html contradicts the suggestion to remove omit this platform? Even in 1.1.0...

**Comment by t-j-h** [comment]
Read in combination with the https://www.openssl.org/policies/roadmap.html

Platform Strategy
Classify **all** the platforms known by Configure according to the  **platform policy** (Timescale: Next feature release)
Publish the build and test status for **each platform** (Timescale: Next feature release)

**Comment by t-j-h** [comment]
You need to add a cc.sh wrapper that places the -L before the -o option - all the compiler variants have that feature. There is a minor Makefile issue which can be solved by updating the makefile or using bash as the shell.

**Comment by dot-asm** [comment]
> Classify all the platforms known by Configure according to the platform policy (Timescale: Next feature release)

It wasn't working for *years* across multiple releases. And still doesn't.

> Publish the build and test status for each platform (Timescale: Next feature release)

It's impossible to fulfill. One can do that only for primary and secondary platforms.

Once again. assertion is that we would be better off considering this as *new* problem, preferably re-branding the target. Suggesting that it was "working" all along, modulo some trivial tweaking, is gross misrepresentation.

**Comment by levitte** [comment]
@t-j-h spoke thusly:
> You need to add a cc.sh wrapper that places the -L before the -o option - all the compiler variants have that feature.

See #5033, I made that change specifically to avoid having to add that kind of script.  Did I miss a spot?  In that case, I'd like to know the details (it's possible that it warrants a separate issue)

> There is a minor Makefile issue which can be solved by updating the makefile or using bash as the shell.

That's unrelated to the -L issue, right?  Would you mind giving me details?

**Comment by t-j-h** [comment]
Andy @dot-asm with respect, the OpenSSL 1.0.2 series has been built and maintained up to date on a regular basis for many many years by more than one company. It works. There are public patches. The patches are pretty trivial. I don't see any reason so far that 1.1 also won't work - but I've been busy.

You don't know that it doesn't "work" and you don't seem to accept when others including myself tell you that it does - with minor tweaking (to use your wording) - despite the face I have been communicating this multiple times. 

The companies that have done this haven't bothered with trying to upstreaming their patches after they were rejected when they tried long ago (multiple times). The compilation passes (and pretty much always has) with very minor changes. 

make test doesn't work for a few of the test cases because of ASCII EBCDIC reasons (simply tests which haven't been updated for this)

Can you please stop spreading incorrect information about this context. It (openssl) compiles and operates (with very minor changes) - and I am working on the patches to fix the issues with test cases - and those are just test case issues - not actual functionality issues - as the libraries operate. There are many companies using the compiled code in production for a wide range of products.

IBM internally have multiple patches for OpenSSL which they haven't shared - and I believe that they stopped providing cut-down OpenSSL builds once the vendor community was doing a better job of providing a build - but that is just a guess at what happened - not a statement of fact.

**Comment by dot-asm** [comment]
> You don't know that it doesn't "work" and you don't seem to accept when others including myself tell you that it does - with minor tweaking (to use your wording) - despite the face I have been communicating this multiple times.

You are mixing up two things, what *we* *support* and what somebody else chooses to do for themselves. If somebody maintains *private* patch set, it's their right, but it puts no obligation on *us* to claim that platform is *supported*. Note that private patch can as well add a config line to 1.0.2 or extra file to Configurations in 1.1.x, it doesn't make it less of a patch set. While on the other hand we *support* is only what can be *actually* measured (by us or community) with currently available source **as it is**. And what you *yourself* tell is that it doesn't work with currently available source **as it is**, not 1.0.2, 1.1.0 or master. *You* are telling this, not me. [Just in case "work" means passes `make test`.]

Now, one can argue that one should aim toward squeezing IBM for patch and applying it. First question is which branches? Or rather does it have to be applied to released branches? Concern is that vendor patches tend to be too "ad-hoc" which can cause maintenance problems in long run. *This* is why I suggest that we would be better off viewing it as *new* problem, by taking more broad and weighed view, see if there are more sensible and sustainable approaches to solve it... While IBM could maintain its own private patch set for released branches, as they allegedly do now.

**Comment by levitte** [comment]
> This is why I suggest that we would be better off viewing it as new problem, by taking more broad and weighed view, see if there are more sensible and sustainable approaches to solve it...

@dot-asm, I'll have you note that *this* PR is titled "Recreate OS390-Unix", and does precisely that.  Most of all, it avoids the need for an argument hacking script (because #5033).  I believe that @t-j-h is testing this as we speak (with whatever his schedule allows).

**Comment by dot-asm** [comment]
> @dot-asm, I'll have you note that this PR is titled "Recreate OS390-Unix", , and does precisely that.

It merely facilitates compilation itself, test suite would still fail.

**Comment by richsalz** [comment]
I agree with Andy.  We partially removed a platform months ago and nobody has yet to complain. We finally removed the other part.  We SHOULD NOT put something back that doesn't work just because it might have been a mistake to remove it in the first two instances.

If/when someone gets OS390 working, they can open a new PR.  As for this one, -1 until someone makes the tests pass.

**Comment by dot-asm** [comment]
Besides, what I'm saying here is kind of applies even to #5032.

**Comment by dot-asm** [comment]
Additional note about "somebody else chooses to do for themselves" in context of suggestion that IBM has given up to have their patches incorporated to mainstream. In the course of many years I did ask IBM to facilitate access to platform more than once, with no outcome, So as far as I'm concerned it can be classified as their *choice*. I mean they were given a choice and made one.

**Comment by dot-asm** [comment]
> Besides, what I'm saying here is kind of applies even to #5032.

Maybe actually more so, Once again, assertion is that we would be better off considering z/OS support as *new* problem. This does imply that we don't restore anything in 1.1.0.

**Comment by levitte** [comment]
@richsalz:
> If/when someone gets OS390 working, they can open a new PR. As for this one, -1 until someone makes the tests pass.

Like I said already, @t-j-h is doing this...

> We partially removed a platform months ago and nobody has yet to complain.

"months ago" is soon to be two years.  Done in [this commit](1fbab1dc6fcb14f512a40c5755708a8bcbf84f40).  That was before 1.1.0 was released.  So yeah, at that time, noone did complain, not even on principle, for obvious reasons.  There was no "keep it compatible" to consider.

**Comment by richsalz** [comment]
So do you agree that this should wait until Tim, or someone, gets a config and build working that passes "make test" ?  And we could do that, even if, as Andy says, IBM is not interested in helping us or taking it on.

**Comment by levitte** [comment]
Yes, I totally agree with that.  As a matter of fact, I expect nothing else.

**Comment by levitte** [comment]
(No pressure, Tim ;-) )

**Comment by richsalz** [comment]
So this PR should be closed, pending Tim's work, IMO.

**Comment by levitte** [comment]
I... don't really see why.  If he runs with the config from this PR, why should he re-create it?

**Comment by t-j-h** [comment]
This PR should stay open. And I will -1 anyone attempting to remove the supporting code - which is what has happened before. We have a definition in the tree and it compiles and runs. We have never had a "make test" must work to keep a definition as a requirement so trying to add that now to justify a position isn't appropriate.
The definition should not have been removed.

**Comment by richsalz** [comment]
You say it works, Andy says it doesn't.  Toss a coin, pistols at dawn, whatever.

Even if it was a mistake to remove the script two years ago, we *cannot* add back code without a CLA or clearance.

**Comment by levitte** [comment]
Can we please stop the unnecessary bickering? @t-j-h has indicated quite a few times that he's looking at the platform and testing. I take that as "PR coming up!"

**Comment by levitte** [comment]
Hey @t-j-h, how's it going with this?

**Comment by t-j-h** [comment]
Haven't forgotten - just been busy - have worked through some of the issues - but not ready to put in a PR just yet.

**Comment by richsalz** [comment]
So we have patches from @p-steuer from *IBM* helping to maintain OpenSSL.  I think this is a non-issue now and should be closed.

**Comment by p-steuer** [comment]
hey @richsalz , im helping to maintain openssl on the s390 platform and we already made progress in publishing/integrating parts of my previously internal patch set. Ive not been active much the last weeks due to feature-freeze but i still do regular testing on the platform.

However, note that my work at this time is linux-only ie, i dont do z/os developing/testing.

**Comment by mattcaswell** [comment]
I note that #5032 has never been merged to 1.1.0, so strictly speaking this issue is a problem in both 1.1.0 and 1.1.1. Therefore, perhaps the 1.1.1 milestone on this is not justified and we can fix this problem at any time (including after release of 1.1.1)?

**Comment by levitte** [comment]
Add a config target in a stable branch? Isn't that counter policy?

**Comment by t-j-h** [comment]
Push it out past 1.1.1 as I haven't had time to sort it out. I had hoped to get to it over the last two weeks but alas other priorities consumed my time.

**Comment by mattcaswell** [comment]
> Add a config target in a stable branch? Isn't that counter policy?

It depends whether you think it is a bug that it was missing in the first place.

**Comment by levitte** [comment]
Never mind what I just wrote...

Quite frankly, I dunno what to do with this. This isn't a finished PR, or it's at least utterly untested. I would rather have it on hold for the moment.

**Comment by mattcaswell** [comment]
> Quite frankly, I dunno what to do with this. This isn't a finished PR, or it's at least utterly untested. I would rather have it on hold for the moment.

In that case I think we should remove the 1.1.1 milestone and fix it after release. Since this also impacts 1.1.0 I think that is justifiable.

**Comment by romen** [comment]
What should be done about this PR?

**Comment by levitte** [comment]
I put it on hold

**Comment by t-j-h** [comment]
All that is needed to compile and run (but not pass make test) is a cc.sh wrapper of exactly that same form last time I did a build. We have various patches available. Restoring what was there I think isn't a problem to just add it back. I already did a +1 on that ages ago and Rich's -1 has been overridden by subsequent events. So you can check this in if you want or leave it on hold.

**Comment by levitte** [comment]
Formally speaking, I can do exactly nothing, as there's been no approval.

Also, no argument rearranging script should be needed, as we already place all the `-L` options before `-o`, and that includes everything a user might give us with `-L` arguments in the configuration or anything given to configuration with any of the "make variable" configuration arguments or environment variables.

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Sorry @t-j-h, I'll have to ask you to re-approve.  I added a different change to CHANGES.

**Review by t-j-h — APPROVED** [review]

**Pull request closed without merging**
