### PR TITLE
document OPENSSL_ENGINES environment variable

### PR DESCRIPTION
**Pull request by p-steuer**
- [x] documentation is added or updated

### CODE REVIEW

**Comment by levitte** [comment]
This should really also be described somehow in doc/man3/...  this environment variable isn't specific to the openssl app, see?

**Comment by p-steuer** [comment]
How about engine(3) ?

**Comment by levitte** [comment]
There is no such thing, except in 1.0.2.  doc/man3/ENGINE_add.pod is where all the engine API stuff is currently written.

**Comment by p-steuer** [comment]
Okay , added a similar note to ENGINE_add(3). Reference to config(5) was already present.

**Comment by petrovr** [comment]
Patrick Steuer wrote:
> - [x] documentation is added or updated
>
> You can view, comment on, or merge this pull request online at:
>
>    https://github.com/openssl/openssl/pull/4956

...."a configuration file's engine section can be used to specify a 
non-default engines directory. " ..
But engine configuration does not specify directory like OPENSSL_ENGINES.

Roumen

**Comment by p-steuer** [comment]
I refer to an engine section's dynamic_path variable. So should it be 'path' instead of 'directory' or what would be the precise wording here ?

**Comment by petrovr** [comment]
Patrick Steuer wrote:
> I refer to an engine section's dynamic_path variable. So should it be 'path' instead of 'directory' or what would be the precise wording here ?
>

OPENSSL_ENGINES specify directory to look for and name of file match 
pattern {lib}<ENGINE_NAME><SHARED_SUFFIX>, where prefix "lib" is used on 
versions before 1.1.

dynamic_path sets shared library to load . It consists from both 
components: path and name. It is loaded as is, at least on linux.

Roumen

**Comment by p-steuer** [comment]
dynamic_path details are already described in config(5) (which is referenced), i just did not want to conceal that option when explaining the environment variable option.

Would something like "The environment variable B<OPENSSL_ENGINES> can be used to specify a non-default engines directory. The B<dynamic_path> variable in a configuration file's engine section can be used to point to an engine in any path."

Or drop the reference to config file option completely ?

**Comment by petrovr** [comment]
Patrick Steuer wrote:
> dynamic_path details are already described in config(5) (which is referenced), i just did not want to conceal that option when explaining the environment variable option.
>
> Would something like "The environment variable B<OPENSSL_ENGINES> can be used to specify a non-default engines directory.

Usually  manual pages has specific layout section for environment 
variables. It is placed after description+options [+results section if 
applicable].

Sentence like above should be placed in such section.


> The B<dynamic_path> variable in a configuration file's engine section can be used to point to an engine in any path."

-0

> Or drop the reference to config file option completely ?
>

I think that reference fro engine(1) page to openssl configuration is 
quite helpful, i.e. to list config(1) in section "see also".

Roumen

**Comment by p-steuer** [comment]
> Usually manual pages has specific layout section for environment variables. It is placed after description+options [+results section if applicable].

Currently there are no openssl man pages currently that provide an ENVIRONMENT section. Instead env vars are documented in DESCRIPTION sections. See e.g rehash(1) or SSL_CTX_load_verify_locations(3).

If there is no decision towards introducing ENVIRONMENT sections, id like to handle it consistently.

**Comment by richsalz** [comment]
My view is don't add an ENVIRONMENT section for now.  Other places include the ia32cap thing.  Look at that for an example of the "env" syntax to put into the synopsis.
Thank you for taking this on.
Feel free to add as many cross-ref links as you think useful.

**Comment by petrovr** [comment]
Patrick Steuer wrote:
>> Usually manual pages has specific layout section for environment variables. It is placed after description+options [+results section if applicable].
>
> Currently there are no openssl man pages currently that provide an ENVIRONMENT section. Instead env vars are documented in DESCRIPTION sections. See e.g rehash(1) ....

hmmm ...

https://www.openssl.org/docs/manmaster/man1/rehash.html  ?

**Comment by p-steuer** [comment]
okay bad example, grep-ing through master doc/, rehash(1) seems to be the only man page that provides an ENVIRONMENT section (tsget(1) has a section called ENVIRONMENT VARIABLES).
However, i see env variables are not handeled consistently, so i wouldnt mind adding the section.

**Comment by p-steuer** [comment]
Reworked this one to include an ENVIRONMENT section like rehash man page, following perlpodstyle(1). Removed the sentence about config file, cross-ref to config(5) should be enough.

**Comment by petrovr** [comment]
Simple and clear - fine with me.

**Comment by dot-asm** [comment]
I've added "pending 2nd review" because formally it need re-approval. Ping @levitte...

**Comment by richsalz** [comment]
merged to master and cherry-picked (after changing pathnames) to 1.1.0.
Thank you!

**Pull request closed without merging**
