### PR TITLE
d2i_X509.pod: clarify usage of the 'pp' function parameter

### PR DESCRIPTION
**Pull request by mspncp**
The `pp` function parameters of `d2i_TYPE()` and `i2d_TYPE()` are referenced in the DESCRIPTION section as `in` resp. `out`. This commit renames the references to `ppin` resp. `ppout` and adds an explaining sentence.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
Marked 'master' because this patch does not apply to '1.1.0'.

**Comment by mspncp** [comment]
An alternative fix would be to leave the DESCRIPTION untouched and change only the names in SYNOPSIS to `in` and `out`. A search yields that both variants `**in/**out` and `**pp` are used equally.

```
msp@msppc:~/src/openssl$ find -name '*.h' -exec grep 'd2i_.*in\>' {} +
./crypto/include/internal/asn1_int.h:int asn1_d2i_read_bio(BIO *in, BUF_MEM **pb);
./include/openssl/asn1t.h:        stname *d2i_##fname(stname **a, const unsigned char **in, long len) \
./include/openssl/asn1t.h:        stname *d2i_##fname(stname **a, const unsigned char **in, long len) \
./include/openssl/asn1.h:        type *d2i_##name(type **a, const unsigned char **in, long len); \
./include/openssl/asn1.h:        type *d2i_##name(type **a, const unsigned char **in, long len); \
...

msp@msppc:~/src/openssl$ find -name '*.h' -exec grep 'd2i_.*pp\>' {} +
./include/openssl/ts.h:TS_REQ *d2i_TS_REQ(TS_REQ **a, const unsigned char **pp, long length);
./include/openssl/ts.h:TS_RESP *d2i_TS_RESP(TS_RESP **a, const unsigned char **pp, long length);
./include/openssl/ts.h:TS_TST_INFO *d2i_TS_TST_INFO(TS_TST_INFO **a, const unsigned char **pp,
./include/openssl/ts.h:TS_ACCURACY *d2i_TS_ACCURACY(TS_ACCURACY **a, const unsigned char **pp,
...

**Comment by richsalz** [comment]
Yeah, we moved the files.  I would not worry about backport.

**Comment by mspncp** [comment]
Thanks. BTW: It was not only the move, the 1.1.0 version does not contain the generic description using `TYPE` yet.

**Comment by mspncp** [comment]
In view of https://github.com/openssl/openssl/pull/5365#issuecomment-365583574 I slightly reworded the description, see 47bb3e2a1739. If I don't here any objections within the next two hours, I will merge with the fixup.

**Comment by mspncp** [comment]
Merged, thanks!

**Comment by mspncp** [comment]
@richsalz, this issue has been reported again for 1.1.0 in #5527. This patch 7c60a968ce1a applies cleanly (after renaming `doc/man3/d2i_X509.pod` to `doc/crypto/d2i_X509.pod`) to 1.1.0.

Does your approval hold for 1.1.0, too?

**Comment by mspncp** [comment]
Oh, sorry. I forgot about my https://github.com/openssl/openssl/pull/5365#issuecomment-365613571. I will have to look into this once more...

I will let you know whether I intend to cherry-pick or come up with a new pr.

**Comment by mspncp** [comment]
> Thanks. BTW: It was not only the move, the 1.1.0 version does not contain the generic description using `TYPE` yet.

My https://github.com/openssl/openssl/pull/5365#issuecomment-365613571 was fake news: the statement holds for 1.0.2 only, not for 1.1.0. In other words: 7c60a968ce1a can be cherry-picked to 1.1.0.

**Comment by richsalz** [comment]
approved for any/all branches.

**Comment by mspncp** [comment]
Merged to OpenSSL_1_1_0-stable (9d927ddf1c74).

**Pull request closed without merging**
