### PR TITLE
Remove support for HMAC_TEST_PRIVATE_KEY_FORMAT

### PR DESCRIPTION
**Pull request by ekasper**
This is a bogus, undocumented format that was intended for testing; I
don't think anyone is using it.

### CODE REVIEW

**Comment by ekasper** [comment]
@snhenson, @dot-asm, I have a question: symmetric algorithms such as hmac or even the newly added siphash have a pkey keygen method... https://github.com/openssl/openssl/blob/master/crypto/hmac/hm_pmeth.c#L84

How does this work?

```
$ openssl genpkey -algorithm hmac
```

reports

"Error generating key."

**Comment by snhenson** [comment]
You have to include a ctrl containing the key:
```
openssl genpkey -algorithm hmac -pkeyopt key:hello
```

And (to my surprise) that actually does something on the master branch so maybe we should be cautious in removing it.

**Comment by snhenson** [comment]
The normal mechanism is via the API and EVP_PKEY_new_mac_key().

I was just checking what happens if you generate an HMAC key without the test option and checking it didn't crash. It gives out an error message thought a clearer one or documenting this possibility would be better.

I'm fine with this if we're OK that removing an undocumented and probably unused feature from what will be 1.1.1 is acceptable.

**Comment by ekasper** [comment]
Thanks @snhenson! In general I think we should stop pretending that symmetric ciphers have genpkey functionality, remove the code, and throw "unsupported algorithm" in the cmd-line tool. E.g. if you try to do the same with siphash, you get a cryptic ASN.1 error.  But that's more work. For now I'll commit this; I'll be damned if it was ever used.

**Pull request closed without merging**
