### PR TITLE
Add blowfish ciphers to default provider

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
> I expect such a guide to appear in another PR.

@paulidale Has also requested the same thing - I will wait until all the ciphers are in before trying to figure that out.. (In case something needs to be refactored). The issue is that the underlying encrypt/decrypt calls all use different way of doing things - which can make it really hard to figure out what to do. I am hoping this isnt as hard as it was in e_XXX - But that remains to be seen :)
I will keep in mind that it needs doing.

**Comment by paulidale** [comment]
Would blowfish be better in the legacy provider?

The [add a cipher wiki page](https://wiki.openssl.org/index.php/How_to_Integrate_a_Symmetric_Cipher) is the place for the new world instructions when they are done.

**Comment by slontis** [comment]
> Would blowfish be better in the legacy provider?

I have the same question for cast5, idea, seed, des

**Comment by levitte** [comment]
> > Would blowfish be better in the legacy provider?
> 
> I have the same question for cast5, idea, seed, des.

I don't clearly recall the discussions, but I think that we've kinda sorta said that if they are used in *any* SSL/TLS cipher suite we still support, then they should be in the default provider...  If not, I'd be very happy to see them relegated to the legacy provider.

However, I'm sure there will be voices that will complain about their favorite algorithms "disappearing" (i.e. not being present because the legacy provider isn't a fallback provider).  We need to think of ways to mitigate that kind of situation, which might be as simple as telling everyone to add the following in their default configuration if they care about this:

```
openssl_conf = openssl_init

[openssl_init]
providers = provider_section

[provider_section]
default = default_section
legacy = legacy_section

[default_section]
activate = 1

[legacy_section]
activate = 1
```

**Comment by slontis** [comment]
Blowfish I assume is pretty dead considering it uses 64bit blocks... 
(There is a TwoFish and ThreeFish)

**Comment by paulidale** [comment]
More an idle though than anything else: could TLS cipher suites be supplied by providers?

There has already been talk of cipher suite selection being property based.

**Comment by levitte** [comment]
> We could load the legacy provider in addition to the default provider if none have been explicitly loaded.

We still don't all agree on this, see how @mattcaswell has reacted to that idea all along.  However, there is a PR that does exactly this, #9378

**Comment by slontis** [comment]
Had to rebase because aes-xts was merged to master.

**Comment by paulidale** [comment]
@slontis, that was an approval from me but you've already got an @openssl/omc member supporting this.

**Comment by slontis** [comment]
Thanks. Merged to master

**Pull request closed without merging**
