### PR TITLE
Typo BIO_SOCK_REUSADDR => BIO_SOCK_REUSEADDR

### PR DESCRIPTION
**Pull request by riuri**
CLA: trivial

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by InfoHunter** [comment]
Typo is worth a fix to stable branch, right?

**Comment by mspncp** [comment]
> Typo is worth a fix to stable branch, right?

I would say so.

@paulidale @InfoHunter please add your consent for the records that this is a trivial change.

**Comment by InfoHunter** [comment]
> please add your consent for the records that this is a trivial change.

Sure. I agree that this is trivial.

**Comment by paulidale** [comment]
Yes, it trivial.

**Comment by paulidale** [comment]
Merged to master and 1.1.1.  Thanks for the fix.

**Pull request closed without merging**
