### PR TITLE
Avoid undefined behavior in pvkfmt.c

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Alternate more lean fix for #11853

this time with [extended tests]
in the commit message, so we can actually see the effect.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
This is identical to the first commit of my PR.

**Comment by bernd-edlinger** [comment]
> This is identical to the first commit of my PR.

nice, but did you also add the [extended tests] ?

**Comment by bernd-edlinger** [comment]
As you see all travis tests are green with this simple PR.
So the commit message Fixes #11853 is misleading when
you fix more than 11853 ?

**Comment by levitte** [comment]
> So the commit message Fixes #11853 is misleading when you fix more than 11853 ?

That's only attached to one of the commits in #11857, so it's fine.  It's true that the PR description is a little bit confusing, but that can be changed to say that one of the commits fixes #11853.  In the end, for auto-closing purposes, github pays attention to commit messages, not to PR descriptions.

**Comment by bernd-edlinger** [comment]
Since @t8m did the same commit now, with a slightly better commit message,
I took his commit directly in this PR.

**Pull request closed without merging**
