### PR TITLE
Fix Configure

### PR DESCRIPTION
**Pull request by levitte**
Configure: let INCLUDEs set on binaries "trickle down" to the objects
----------

This ensures that only one set of includes is associated with each
object file, reagardless of where it's used.

For example, if apps/build.info has this:

    SOURCE[openssl]=foo.c
    INCLUDE[openssl]=.. ../include

and test/build.info has this:

    SOURCE[footest]=../apps/foo.c
    INCLUDE[footest]=../include

The inclusion directories used for apps/foo.o would differ depending
on which program's dependencies get generated first in the build file.

With this change, all those INCLUDEs get combined into one set of
inclusion directories tied to the object file.

Configure: ensure that a DEPEND generates the correct inclusion directory
----------

We incorrectly assumed that explicit dependencies meant that the
source directory would be added for inclusion.  However, if the
dependent file is generated, it's stored in the build directory, and
that should be used for inclusion rather than the source directory.

### CODE REVIEW

**Comment by levitte** [comment]
Note that without this, VMS builds may fail.  Here's what happens:

In `apps/build.info`, we have this:

```
  INCLUDE[openssl]=.. ../include
```

Among the source for `apps/openssl`, we have `apps/vms_decc_init.c`, so when the rules for its object files are generated from `apps/openssl`'s dependence of it, the inclusion paths when building it become (expressed in Unix syntax for the sake of simplicity) `-I. -Iinclude`.

Now, in `test/build.info`, there's this:

```
  SOURCE[libtestutil.a]=testutil/basic_output.c testutil/output_helpers.c \
          testutil/driver.c testutil/tests.c testutil/cb.c testutil/stanza.c \
          testutil/format_output.c testutil/tap_bio.c \
          {- rebase_files("../apps", $target{apps_aux_src}) -} \
          testutil/test_cleanup.c testutil/main.c testutil/init.c
  INCLUDE[libtestutil.a]=../include
```

Through `$target{apps_aux_src}`, `apps/vms_decc_init.c` is *also* the source for `test/libtestutil.a`, but note the INCLUDE statement.  When the rules for building its object files comes from `test/libtestutil.a`, the inclusion paths become `-Iinclude`, and because `apps/vms_decc_init.c` ends up including `e_os.h`, that rule fails.

Now, question is which rule gets generated.  That's actually a matter of pure luck (or rather, perl hashing).

For these reasons, it's generally better to regard INCLUDE statements applied on final products as a hint that needs to trickle down to and accumulated with the object files where these statements actually matter.  If we're "lucky", this problem could happen on any platform...

**Review by richsalz — APPROVED** [review]
builds pass, you say it's needed on VMS, so approved.

**Comment by levitte** [comment]
Yup, I've just now verified that this seems to work correctly on VMS as well.

**Comment by levitte** [comment]
Thanks.

Merged.

master: 1b5ad51fc9b29d8893d5224f00bb3360f8aca465 to 14262ca950b8a75014e5495a2b93e1baa62d33a9
1.1.0: 6a8dfb90b54ad1d3d87510b37e409bf568a4338f and 8054342b78d3ffbd3625689a9692ff1e5f709913

**Pull request closed without merging**
