### PR TITLE
WIP: Remove some assembler code

### PR DESCRIPTION
**Pull request by richsalz**
This is a WIP.  Being discussed on the openssl-project mailing list.

### CODE REVIEW

**Comment by t-j-h** [comment]
-1 so a vote is required when we finish the discussion

**Comment by dot-asm** [comment]
Cryptographic algorithms customarily have short dependency chains. This means that optimal implementation can tell you things about processor. For example on x86_64 processor with sufficient instruction issue rate MD5 performance would be 5.0 cycles per processed byte. If you observe better result, then you know something phishy is going on with clock frequency. Or you can simply use MD5 to measure clock frequency. If you observe worse result, then it's either insufficient issue rate or sign of some anomaly. And specifically last part is one of the things assembly programming in general is about, i.e. identifying anomalies [so that they can be worked around]. In other words at least *some* of legacy implementations actually serve a meaningful purpose...

**Comment by richsalz** [comment]
How long has it been since you used MD5 (or others, and which ones) to detect these anomalies?

**Comment by dot-asm** [comment]
> How long has it been since you used MD5

It's first thing I use (or ask somebody who performs tests for me on) new processor. Last time? git log crypto/chacha/asm/chacha-x86_64.pl says December.

> to detect these anomalies?

Basically every time I get unexpected performance result (or any kind) I run MD5 and RC4 (among legacy algorithms that is) to see if there are bottlenecks in those. They are more likely to allow to eliminate options than to actually require work.

Just in case. None of what I say means that everything *has to* be kept, but as already said, some of them serve meaningful purpose...

**Comment by richsalz** [comment]
I am concerned, perhaps too much, about bit-rot and maintainability.  So maybe can can shrink the to-be-removed list, and put that code somewhere else?

**Comment by dot-asm** [comment]
> bit-rot

Well, one can as well argue that it's as problematic for legacy C code. Because, as was shown on several occasions, it just so happens that it's not unlike that it relies on undefined or implementation-specific behaviour. And one can probably even wonder if it's not larger problem, because in assembly there are no such problems, as programmer has no other option but to be acutely aware of what's going on. Do note that I'm *not* saying that bit-rot is not a concern, only that it's not really assembly-specific.

**Comment by richsalz** [comment]
@dot-asm and @t-j-h is there a subset of these commits that you could live with?  Suppose it was Blowfish CAST Whirlpool RC4 RMD160 DES?

**Comment by t-j-h** [comment]
No. I see no benefit in removing the hard work of optimisation code which has been in the tree.
It would be different if there was a significant measureable impact for keeping the code (but there is not). 
We have both C and ASM code here and the testing is automated. Incremental ASM code does not meaningfully increase the load.

I'm not stating the cost is zero - just not meaningful enough to remove the work that was done in my view.

Now I could be entirely out on a limb here and others might view this differently - which is why I marked it for an OMC vote to be able to proceed. As always the view of the majority of the team is what counts.

**Comment by richsalz** [comment]
@openssl please close those if you're never going to move on it in any way.

**Comment by t-j-h** [comment]
Closing.

**Pull request closed without merging**
