### PR TITLE
Backport: X509 time: tighten validation per RFC 5280 (1.0.2)

### PR DESCRIPTION
**Pull request by mspncp**
- Reject fractional seconds
- Reject offsets
- Check that the date/time digits are in valid range.
- Add documentation for X509_cmp_time

GH issue 2620

cherry-picked from 80770da39ebba0101079477611b7ce2f426653c5
                      ~~(omitting CHANGES and tests)~~

### CODE REVIEW

**Comment by mspncp** [comment]
Requested by @LarsVoelker in #4915.

**Comment by mspncp** [comment]
I'm still struggling with the 1.0.2 test framework and would appreciate some help:
					   
```
Doing certs/demo
testing...
make[1]: Entering directory '/home/msp/src/committer/openssl/test'
gcc   x509_time_test.o   -o x509_time_test
x509_time_test.o: In function `test_x509_cmp_time':
/home/msp/src/committer/openssl/test/x509_time_test.c:157: undefined reference to `X509_cmp_time'
x509_time_test.o: In function `test_x509_cmp_time_current':
/home/msp/src/committer/openssl/test/x509_time_test.c:173: undefined reference to `ASN1_TIME_adj'
/home/msp/src/committer/openssl/test/x509_time_test.c:174: undefined reference to `ASN1_TIME_adj'
/home/msp/src/committer/openssl/test/x509_time_test.c:176: undefined reference to `X509_cmp_time'
/home/msp/src/committer/openssl/test/x509_time_test.c:183: undefined reference to `X509_cmp_time'
/home/msp/src/committer/openssl/test/x509_time_test.c:190: undefined reference to `ASN1_TIME_free'
/home/msp/src/committer/openssl/test/x509_time_test.c:191: undefined reference to `ASN1_TIME_free'
collect2: error: ld returned 1 exit status
make[1]: *** [<builtin>: x509_time_test] Error 1
make[1]: Leaving directory '/home/msp/src/committer/openssl/test'
make: *** [Makefile:472: tests] Error 2
```

If I understand it correctly, `test/Makefile` is not auto-generated and needs to be edited manually, right? What did I miss, why do I get the undefined references?

**Comment by richsalz** [comment]
You need to have a rule to  build X509TIMETEST.

**Comment by mspncp** [comment]
Thanks, I pushed a fixup!

**Comment by mspncp** [comment]
It's out of WIP now.

**Comment by mspncp** [comment]
Merged.

**Pull request closed without merging**
