### PR TITLE
Skip GOST TLS 1.2 ciphers is Extender Master Secter is not recieved

### PR DESCRIPTION
**Pull request by NMorozxov**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
Not sure this patch makes sense

The ClientHello.extensions field is RECOMMENDED to contain the
extended_master_secret (see [RFC7627]) and the renegotiation_info
(see [RFC5746]) extensions.

(https://tools.ietf.org/html/draft-smyshlyaev-tls12-gost-suites-08#section-4.2.1)

**Comment by NMorozxov** [comment]
Ok what i must do ? Close this PR ?

**Comment by NMorozxov** [comment]
"криптонаборы, описанные в настоящем документе, предполагают наличие двух обязательных расширений со стороны сервера: extended_master_secret и renegotiation_info."
_- Использование российских криптографических алгоритмов в протоколе безопасности транспортного уровня (TLS 1.2)_
This text is taken from TK26_TLS document about kuzheckik and magma cipher suites. This tells than they are mandatory

**Comment by NMorozxov** [comment]
Р 1323565.1.020-2018

**Comment by beldmit** [comment]
There is neither "MUST use with EMS" nor "MUST NOT use without" neither in the Russian standard nor in the IETF draft. And even more, not all the certified Russian implementations support EMS (though some of them do).

**Comment by NMorozxov** [comment]
Ok.... what i must do close this PR?

**Comment by beldmit** [comment]
I'm afraid yes. Sorry.

**Pull request closed without merging**
