### PR TITLE
fix Coverity 1506709: error handling

### PR DESCRIPTION
**Pull request by paulidale**
- [x] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]
Heh, this is really stupid coveritism :grin: But yeah, OK.

**Comment by paulidale** [comment]
Yeah, but the INFO message isn't necessary if the test fails so it's pretty harmless.

**Comment by paulidale** [comment]
Ping @openssl/committers for second review

**Review by slontis — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
