### PR TITLE
Fix a typo found by codespell in a variable name

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
The change is limited to a single C file.

CLA: trivial

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by t8m** [comment]
@levitte @hlandau please confirm, you're ok with CLA: trivial.

**Comment by hlandau** [comment]
Agree trivial.

**Review by paulidale — APPROVED** [review]
agreed trivial

**Comment by paulidale** [comment]
Merged to master.  Not present in 3.1.

**Pull request closed without merging**
