### PR TITLE
Possibility to bind connection to local interface: ticket #2578

### PR DESCRIPTION
**Pull request by flowher**
This patch implements possibility to specify source IP in s_client from which connection should be made. Feature is useful in case when machines has many network interfaces and user wants to make connection from interface that is not used by default.

### CODE REVIEW

**Comment by levitte** [comment]
Putting this on hold.  It's a nice extra feature, but we're not in a stage to add it right now.  Sorry it took so long to even react.

**Comment by flowher** [comment]
Ok, Thanks for info.

**Comment by bdrewery** [comment]
Please get this in already

**Comment by pprindeville** [comment]
I'd definitely like to see it.

**Comment by richsalz** [comment]
It won't happen for 1.1, sorry. :(  It also needs to be ported and rebase onto that codebase.

**Comment by bdrewery** [comment]
https://github.com/yongboy/bindp let me workaround the lack of -bind.

**Comment by atzezitman** [comment]
I have been working around this missing feature for several years (at least 5) now, with xinetd/netcat or other trics. And this time I wanna use openssl s_client with bind from a bash script, so i guess I'll have to use bindp as suggested by bdrewery. :(

**Comment by flowher** [comment]
Let me know if you need help with merge

**Comment by richsalz** [comment]
@flowher if you can open a new rebased PR, that would help.

**Comment by flowher** [comment]
@pprindeville thanks, I agree
@richsalz OK, I'll rebase and open new PR

**Comment by kroeckx** [comment]
There is no need to open a new one, just rebase and force a push to this branch.

**Comment by levitte** [comment]
So, errr, what's happening with this?  @flowher, did you end up making a different PR or did you just not get around to rebasing and pushing here?

This is suitable to get into master at the very least.

**Comment by levitte** [comment]
(note that a rebase will be a bit of work, since the source code format has changed)

**Comment by richsalz** [comment]
Wasn't @kroeckx also looking at this?  Over in the RT pile?

**Comment by flowher** [comment]
This can be closed. Rebase was pretty much impossible. It needs new implementation. I've something but I need to test it still (sorry for delay but no time at a moment)

**Comment by snhenson** [comment]
Wouldn't it be better if we could do this in a portable way at the BIO level instead of having to do low level stuff in apps?

**Comment by flowher** [comment]
Is such feature needed at BIO level?

**Comment by levitte** [comment]
> This can be closed. Rebase was pretty much impossible. It needs new implementation. I've something but I need to test it still (sorry for delay but no time at a moment)

Okie.  Thank you for your effort

**Comment by amatai** [comment]
It has taken very long to get this small functionality in. Would really like to see this get in.

**Comment by richsalz** [comment]
@amatai, can you contribute a patch?

**Pull request closed without merging**
