### PR TITLE
Only call OPENSSL_init_crypto on fetch if using the default libctx

### LINKED ISSUE #20315: Is it possible to initialize a custom libctx w/o causing the default context to be initialized?
In this comment https://github.com/OpenSC/OpenSC/pull/2712#issuecomment-1432221284 we have a trace that shows how openssl seem to end up initializing the default context even though a custom OSSL_LIB_CTX was created.

The custom OSSL_LIB_CTX was created explicitly to avoid interfering with the main application context, and explicitly using only the default (and sometimes legacy) providers and nothing else.

However due to the ordering of how the application is initializing this code ends up being called before any other crypto calls have been made.

This happens inside a loadable module, so we can't control how the calling application initialized or didn't.

The issue arise because in this case the code being called is within a module that is also loaded by one of the providers (pkcs11-provider) during initialization of the provider itself.

Does OpenSSL need to forcibly initialize the default context when a custom OSSL_LIB_CTX is being used?

It sounds to me like we should be able to initialize a custom context, and potentially with a custom configuration file, w/o interfering at all with the default context, but there may be internal reasons why this is not working.

In that case I traced it down to ossl_method_store_fetch() always and unconditionally initializing the default context with configuration loading:
```
 #ifndef FIPS_MODULE
    if (!OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CONFIG, NULL))
        return 0;
#endif
```

There does not seem to be a way to pass a OSSL_LIB_CTX to OPENSSL_init_crypto() anyway ...

### PR DESCRIPTION
**Pull request by mattcaswell**
There is no point in calling OPENSSL_init_crypto() unless we are actually going to be using the default libctx.

Fixes #20315

### CODE REVIEW

**Comment by mattcaswell** [comment]
I've marked this as "tests:exempted" because coming up with a test for this would be disproportionately hard.

**Comment by simo5** [comment]
@mattcaswell isn't a test as simple as creating a custom context, running the fetch, then checking the default context is still uninitialized? What am I missing?

**Comment by simo5** [comment]
One hacky way is to define a new OPENSSL_INIT_XX flag that is just a sentinel, and make OPENSSL_init_crypto() fail if it is requested and the default context was already initialized.

So then you can call OPENSSL_init_crypto() with that flag and fail the test if the call fails.

opts is a unit64_t so there is still plenty of flag space available...

**Comment by simo5** [comment]
Of course it is also possible to add a new call that checks if the default context is initialized, that may actually be more useful, as I can see how some modules might have config options to use the default context if available vs creating a custom context. In that case they would need a way to ask openssl if the default context is initialized to make that choice, so adding an API for that is not an unreasonable thing.

**Comment by mattcaswell** [comment]
I figured out a way of testing whether the config file was loaded or not for the default libctx without having to dive into libcrypto internals or adding any new APIs. Test added.

**Comment by simo5** [comment]
Nice trick!

**Review by paulidale — APPROVED** [review]
Neat test.

**Review by beldmit — APPROVED** [review]
LGTM, nice test

**Comment by paulidale** [comment]
Merged with a manual fix for test/build.info

**Pull request closed without merging**
