### PR TITLE
fixup typo

### PR DESCRIPTION
**Pull request by baloo**
Just a simple fix for a typo in the code example.

##### Checklist
- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
Definitely trivial.

**Review by t8m — APPROVED** [review]
Trivial, it is.

**Comment by paulidale** [comment]
@baloo if you agree that this is a trivial change, could you amend the git commit so it includes `CLA: trivial` on a line by itself.  `git commit --amend` followed by `git push -f`.

Otherwise, we'll need a CLA filled in.

**Comment by t8m** [comment]
> @baloo if you agree that this is a trivial change, could you amend the git commit so it includes `CLA: trivial` on a line by itself. `git commit --amend` followed by `git push -f`.
> 
> Otherwise, we'll need a CLA filled in.

@paulidale He already did that. Although the commit message subject (the first line) could be amended as well to make it more clear. Something like `EVP_KDF-KB man page: Fix typo in the example code` would make it better.

**Comment by paulidale** [comment]
@t8m, I confused.  I thought the need CLA was present.

**Comment by baloo** [comment]
https://github.com/openssl/openssl/commit/88b7a6b1212c6ce8ed0922b68f412550b659f309.patch
```
From 88b7a6b1212c6ce8ed0922b68f412550b659f309 Mon Sep 17 00:00:00 2001
From: Arthur Gautier <baloo@superbaloo.net>
Date: Sat, 6 Mar 2021 23:08:08 +0000
Subject: [PATCH] fixup typo

CLA: trivial
Signed-off-by: Arthur Gautier <baloo@superbaloo.net>
```

Am I missing something?

**Comment by baloo** [comment]
I changed the commit title as suggested.

**Comment by baloo** [comment]
> @t8m, I confused. I thought the need CLA was present.

The need for CLA was present but I pushed a new amended commit a couple minutes later once I learned about the CLA. First commit I pushed on openssl :)

**Comment by t8m** [comment]
Still approved

**Comment by paulidale** [comment]
The CLA thing was my mistake, sorry.
Still approved.

**Comment by paulidale** [comment]
Merged to master, thanks for the fix.

**Pull request closed without merging**
