### PR TITLE
Remove the cast from the definition of OPENSSL_VERSION_NUMBER

### PR DESCRIPTION
**Pull request by mattcaswell**
If a cast is included in the definition it cannot be used in preprocessor
expressions, e.g. "#if OPENSSL_VERSION_NUMBER > 0x10000000L"

[extended tests]

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
I'm not sure why you're doing an extended test...  *We* aren't using it.

**Comment by mattcaswell** [comment]
Because the krb5 external test *is* using it - and its failing.

**Comment by levitte** [comment]
Oh!

**Comment by mattcaswell** [comment]
Travis was still not happy due to a different issue in the pyca external tests. @levitte - please can you take another look.

**Comment by richsalz** [comment]
The reason for not having the "# define" space is that this header file is not wrapped in the regular ifndef guard.  Should I do that?  Note that the API stuff at the end of the file would then also need indenting.  Let me know.

**Comment by levitte** [comment]
Uhmmmmmm, @richsalz, I think your confusing different PRs

**Comment by richsalz** [comment]
oh geez, time for a nap.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
