### PR TITLE
Left shift of a negative number is undefined behaviour

### PR DESCRIPTION
**Pull request by mattcaswell**
Fix undefined behaviour in curve25519.c. Prior to this running with
ubsan produces errors like this:

crypto/ec/curve25519.c:3871:18: runtime error: left shift of negative
value -22867

[extended tests]

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
I *think* this is the right solution. At least the tests pass and ubsan doesn't complain. I'd really like someone more familiar with this code to review this. Ping @davidben.

**Comment by mattcaswell** [comment]
Hmmm...travis failure. Looks relevant because it is in curve25519.c ... but I really have no idea...
````
ccache gcc-5  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DPEDANTIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer -g  -fPIC -DOPENSSL_USE_NODELETE -MMD -MF crypto/ec/curve25519.d.tmp -MT crypto/ec/curve25519.o -c -o crypto/ec/curve25519.o crypto/ec/curve25519.c
virtual memory exhausted: Cannot allocate memory
make[1]: *** [crypto/ec/curve25519.o] Error 1
make[1]: Leaving directory `/home/travis/build/openssl/openssl'
make: *** [tests] Error 2
````

**Comment by dot-asm** [comment]
[Looking at error message alone] one can wonder if it's ubsan bug. At least language doesn't say that left shift of negative value is undefined. It effectively says that it's the change of sign bit as result of left shift of signed type that is undefined. To be more specific it says "If E1 [as in E1 << E2] has a signed type and nonnegative value, and E1 × 2^E2 is representable in the result type, then that is the resulting value; otherwise, the behavior is undefined."

As far as suggested modification goes, *purely formally* it effectively evokes unspecified behaviour. Standard fully specifies conversion from signed to unsigned, but not other way around. Effectively it says that if most significant bit of unsigned value is set, then conversion to signed type is undefined. And this is exactly what is suggested here, i.e. perform unsigned to signed conversion with most significant bit set.

**Comment by mattcaswell** [comment]
> Hmmm...travis failure. Looks relevant because it is in curve25519.c ... but I really have no idea...

Looks like the travis failure in this PR is not relevant because it also exists in master.

**Comment by mattcaswell** [comment]
> As far as suggested modification goes, purely formally it effectively evokes unspecified behaviour. Standard fully specifies conversion from signed to unsigned, but not other way around. Effectively it says that if most significant bit of unsigned value is set, then conversion to signed type is undefined. And this is exactly what is suggested here, i.e. perform unsigned to signed conversion with most significant bit set.

So what you are saying is that this suggested modification doesn't really help because it is also undefined? Is there a *defined* way of doing a left shift on a (potentially) negative number?

**Comment by noloader** [comment]
@dot-asm,

> Looking at error message alone] one can wonder if it's ubsan bug. ...

I believe 2<sup>E2</sup> has to be representable in the result type. For a base case of `E2 = -1`, I don't believe 2<sup>-1</sup> is representable, so  it follows `E1 x 2^E2` is not representable.

You might be able to swing it away from undefined behavior with a cast and a logical and or even a mod. I think that's how most barrel-shifters work anyway. (Andy?)

If implementation defined is the issue, then its probably better to steer away from it. There's no sense in tracking down an incorrect results on one or two platforms that behave differently.

**Comment by mattcaswell** [comment]
> Is there a defined way of doing a left shift on a (potentially) negative number?

Alternative approach in #3600. Does that work instead?

**Comment by dot-asm** [comment]
> Is there a defined way of doing a left shift on a (potentially) negative number?

"The result of E1 << E2 is E1 left-shifted E2 bit positions; vacated bits are filled with zeros." Then it goes on discussing unsigned shift being mod radix, and then already quoted sentence discussing "signed *and* nonnegative value". My understanding is that shifting negative value is defined.

**Comment by dot-asm** [comment]
> For a base case of E2 = -1

Prior paragraph says "If the value of the right operand is negative or is
greater than or equal to the width of the promoted left operand, the behavior is undefined." In other words E2 = -1 is undefined. Original question was about negative E1, not E2.

**Comment by dot-asm** [comment]
> My understanding is that shifting negative value is defined.

Well, arguably one can interpret last sentence as "left shift is defined only on non-negative signed values [provided that result doesn't overflow]... After second thought it's probably correct interpretation. I mean my understanding is probably wrong...

**Comment by dot-asm** [comment]
> You might be able to swing it away from undefined behavior with a cast and a logical and or even a mod.

Formal correctness is about correct coding, not masking.

> I think that's how most barrel-shifters work anyway. (Andy?)

That's exactly the kind of thing sanitizer is supposed to make to avoid. To make such assumptions. Even though we know what all supported processors would do, we may not assume it that they do so.

**Comment by mattcaswell** [comment]
Closed in favour of #3600

**Pull request closed without merging**
