### PR TITLE
Upgrade action/{upload,download}-artifact to v4 [3.2]

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by t8m** [comment]
This needs a second approval ASAP @openssl/committers

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by levitte** [comment]
Merged

6e2fb01eaa585474094ce65b2836e82f8bae6d3b Upgrade action/{upload,download}-artifact to v4

**Comment by quarckster** [comment]
`openssl-3.2` still has `actions/upload-artifact@v3` https://github.com/openssl/openssl/blob/openssl-3.2/.github/workflows/main.yml#L29

cc @bernd-edlinger

**Comment by bernd-edlinger** [comment]
Since the approvals are still valid, I should be able merge this PR if nobody objects.
OK?

**Comment by bernd-edlinger** [comment]
reopening as the PR was not merged, but the CI started to fail now.

**Comment by bernd-edlinger** [comment]
finally merged as 9cdaa3def442e8fd89ec898616760b21016e65fc to openssl-3.2

**Comment by quarckster** [comment]
@bernd-edlinger thank you!

**Pull request closed without merging**
