### PR TITLE
Fix 36 boring tests

### PR DESCRIPTION
**Pull request by mattcaswell**
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

##### Description of change

OpenSSL requires that we set the session id context. BoringSSL apparently does not. This wasn't being done in ossl_shim.

OpenSSL documents that SSL_get_peer_cert_chain() does not work after resumption, but ossl_shim was trying to do that to check whether we have a peer certificate. It should use SSL_get_peer_certificate() instead (which does work after resumption).

The above 2 fixes enables 36 more boring tests to be enabled.

I've not done [extended tests] with this because we need #2938 to be merged.

### CODE REVIEW

**Comment by davidben** [comment]
> OpenSSL documents that SSL_get_peer_cert_chain() does not work after resumption

FYI, that documentation isn't quite true. It works after resumption as long as the `SSL_SESSION` did not happen to round-trip through serialization (so no session tickets as a server and no on-disk or otherwise serialized session caches as client or server), which is kind of bizarre. That's why you only needed to disable the server tests and not the client ones.

We were seeing consumers either relying on the `SSL_SESSION` not going through serialization (contradicting the documentation), or serializing and going through a lot of trouble to work around it when serializing sessions (often getting it wrong). So we fixed it and made `SSL_SESSION` serialization preserve all fields, which is a lot easier to reason about.

**Comment by levitte** [comment]
> I've not done [extended tests] with this because we need #2938 to be merged.

Time for a rebase?  ;-)

**Comment by mattcaswell** [comment]
Rebased and force pushed. There are no changes other than I added [extended tests] just to see what travis does.

**Comment by mattcaswell** [comment]
Pushed.

**Pull request closed without merging**
