### PR TITLE
Backport of PRs to 3.1 branch [batch 2]

### PR DESCRIPTION
**Pull request by t8m**
Second batch of backport commits to 3.1.

Made on top of first batch #19587 so draft until that one is merged.

### CODE REVIEW

**Comment by t8m** [comment]
First batch is merged. This is now rebased on top of the first batch. Please approve.

**Review by hlandau — APPROVED** [review]
Given this a quick once over. Looks OK.

Worth noting this backports some of my performance fixes.

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merging this now.

**Comment by t8m** [comment]
Merged to 3.1 branch. Thank you.

**Pull request closed without merging**
