### PR TITLE
Fix BoringSSL test failures

### PR DESCRIPTION
**Pull request by mattcaswell**
Commit fe55c4a2 attempts to prevent ECHDE from being selected in SSLv3. ECHDE is not well defined for SSLv3. However some servers (including previous versions of OpenSSL) may select ECDHE anyway in SSLv3. Therefore that commit can cause interoperability failures for clients talking to an SSLv3 server. This was causing the BoringSSL tests to fail.

This PR reverts the previous commit and prevents ECDHE selection in SSLv3 in a different way which doesn't break those clients.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
See #3181

**Comment by tmshort** [comment]
One of the beneficial side effects of commit fe55c4a was to not list ECDHE ciphers as valid ciphers for SSLv3; that benefit is lost.

**Comment by richsalz** [comment]
-1.  Wait.
Do openssl clients now try to do ECDHE with SSLv3?  That is *wrong*  We should not enshrine that behavior, even at the altar of interop.  *nobody else does it.*

**Comment by richsalz** [comment]
@tmshort has an excellent point.  Listing those ciphers in SSLv3 is a *bug* that this does not fix.

**Comment by tmshort** [comment]
@richsalz, yes appears to be the case, s_client -ssl3 can attempt to use ECDHE ciphers.

**Comment by mattcaswell** [comment]
> Do openssl clients now try to do ECDHE with SSLv3

A client will accept an ECDHE ciphersuite selected by the server in an SSLv3 connection. The same as it always did.

The change will mean that servers will never select ECDHE in SSLv3.

> That is wrong We should not enshrine that behavior, 

Too late. That behaviour is already enshrined for many many years.

**Comment by richsalz** [comment]
So are small key sizes and default hash mechanisms. :)  And that lattter switch has cause more interop questions/issues than this bug-fix ever will.
I keep my -1, discuss and team vote if you want.
And also fix the bug that @tmshort pointed out in the ciphers command.

**Comment by tmshort** [comment]
>A client will accept an ECDHE ciphersuite selected by the server in an SSLv3 connection. The same as it always did.

But _only_ if the SSLv3 client was broken in the first place and offered ECDHE ciphers. No one else does this.

This change does not fix the fundamental issue: SSLv3 clients should _never_ propose ECDHE ciphers. This change does not prevent s_client -ssl3 from proposing an ECDHE cipher.

**Comment by mattcaswell** [comment]
Closing in favour of #3204

**Pull request closed without merging**
