### PR TITLE
To use BN_BITS2, we'd better include openssl/bn.h

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
I don't quite understand how we missed this in the sparse_array PR...

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

54b5fb2dab8b216c11adfbe6320c27e18a44ffb3 To use BN_BITS2, we'd better include openssl/bn.h

**Comment by paulidale** [comment]
Weird, I was building fine last night.

**Comment by levitte** [comment]
It did, right?  I know I've seen something like this before, that we rely on openssl/crypto.h to include a whole bunch of other essential headers, but some are included conditionally...  I think openssl/bn.h is one of those, somewhere...

**Comment by paulidale** [comment]
That might explain it.  Best to include needed header unconditionally I think.
It was getting late so I might have been dreaming.

**Pull request closed without merging**
