### PR TITLE
Re-implement ANSI C building with a Github workflow

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by t8m** [comment]
Something wrong with the YAML syntax as the jobs do not seem to be run at all. Also why is it doing the whole build/make/make test/make install when we have `out-of-source-and-install` build that already does this? This could be just a compile test to save on resources.

**Comment by levitte** [comment]
You are correct on both jobs.  I did a sloppy job.  Hopefully fixed now

**Comment by levitte** [comment]
@rsbeckerca made a fix in #14731 that I cherry-picked to see what else causes errors in the ANSI C build.

**Comment by levitte** [comment]
On my laptop, only *one stray comma* caused failure to build in ANSI C mode.  I'm actually impressed, I imagined it would be worse...

**Comment by rsbeckerca** [comment]
There are a few sign issues, if you are interested, assigning -1 to unsigned values. I did not want to break anything, though. I can send a complete list. Here is a smattering.
```
      -1,                 /* mindtls */
      ^
"openssl-3.0/test/tls-provider.c", line 113: warning(161): integer conversion resulted in a change of sign
      -1,                 /* maxdtls */
      ^
"openssl-3.0/test/tls-provider.c", line 114: warning(161): integer conversion resulted in a change of sign
      -1,                 /* mindtls */
      ^
"openssl-3.0/test/tls-provider.c", line 125: warning(161): integer conversion resulted in a change of sign
      -1,                 /* maxdtls */
      ^
"openssl-3.0/test/tls-provider.c", line 126: warning(161): integer conversion resulted in a change of sign
  DEFINE_SPECIAL_STACK_OF(sint, int)
  ^
"openssl-3.0/test/stack_test.c", line 39: warning(262): function "sk_sint_new" was declared but never referenced
  DEFINE_SPECIAL_STACK_OF(sint, int)
  ^
"openssl-3.0/test/stack_test.c", line 39: warning(262): function "sk_sint_new_reserve" was declared but never referenced
// Repeat for all instances of DEFINE_SPECIAL_STACK_OF.. and same for below, and pretty much the whole set of these.
  DEFINE_STACK_OF(SS)
  ^
"openssl-3.0/test/stack_test.c", line 41: warning(262): function "sk_SS_new" was declared but never referenced
```

**Comment by rsbeckerca** [comment]
> 
> 
> On my laptop, only _one stray comma_ caused failure to build in ANSI C mode, after having applied @rsbeckerca's patch. I'm actually impressed, I imagined it would be worse...

It could be COBOL, where one missing `.` can cause millions of compile errors. Or really old PASCAL compilers where a missing `;` can cause a near infinite set based on inserting tokens then reporting that the token inserted is wrong recursively, until out of memory. Oh, I how I miss 1983. ;)

**Comment by levitte** [comment]
CIs are happy!

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.

**Pull request closed without merging**
