### PR TITLE
Fixed typo in CRYPTO_THREAD_run_once.pod

### PR DESCRIPTION
**Pull request by sapph2c**
CLA: trivial

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
agreed trivial

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
@t8m, trivial?

**Review by t8m — APPROVED** [review]
Yes, trivial

**Review by shahsb — APPROVED** [review]
Okay with trivial.

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
