### PR TITLE
Fix manpage problems

### PR DESCRIPTION
**Pull request by kroeckx**
Patches @eric-s-raymond mailed to me, but then applied to the .pod files instead of the man pages.

### CODE REVIEW

**Comment by kroeckx** [comment]
@eric-s-raymond: We will either need a CLA from you, or you need to agree that those changes are trivial and that you don't claim copyright.

**Comment by eric-s-raymond** [comment]
I agree that these changes are trivial and do not claim copyright.

These aren't the last fixes I'm going to ship you.  What is the procedure by which I can give you a CLA so we can avoid this rigamarole in the future?

**Comment by richsalz** [comment]
Awesome.  It's the Apache CLA with Apache crossed out and OpenSSL written in. :)  https://www.openssl.org/policies/cla.html

**Comment by eric-s-raymond** [comment]
I have sent a GPG-signed CLA (legally binding under the Federal E-SIGN Act of 2000) to your 'legal' address.

**Comment by mattcaswell** [comment]
CLA received. Close/reopen to kick the CLA bot.

**Comment by richsalz** [comment]
@kroeckx you going to merge?

**Comment by kroeckx** [comment]
merged

**Pull request closed without merging**
