### PR TITLE
Constify more API

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Most of these changes are related to methods that use OBJ_cmp() or OBJ_dup().

### CODE REVIEW

**Comment by levitte** [comment]
+1

**Comment by mattcaswell** [comment]
Can this be merged? @richsalz @levitte

**Comment by richsalz** [comment]
i approve but it's your decision :)
If you do, I would close internal MR's 1129 and 986.

**Comment by levitte** [comment]
Merged

**Comment by richsalz** [comment]
Done’t forget: If you do, I would close internal MR's 1129 and 986.

--
Senior Architect, Akamai Technologies
IM: richsalz@jabber.at Twitter: RichSalz

**Pull request closed without merging**
