### PR TITLE
Enhance util/openssl-update-copyright shell script

### PR DESCRIPTION
**Pull request by mspncp**
- Avoid creating repeated year ranges <current_year>-<current_year> for
  documents which were added in the current year.
- Use extended regular expressions for better readability (less quoting)
- Use a shebang line which is more portable

### CODE REVIEW

**Comment by mspncp** [comment]
@kaduk if you see a way how to make `sed -i` portable _without_ creating backup files, please let me know. Then I will integrate it. Otherwise, I will ignore the BSD portability issue.

**Comment by mspncp** [comment]
@levitte this change is for you, as discussed.

**Comment by mspncp** [comment]
Just in case somebody asks: That's the difference between [Basic (BRE) and extended (ERE) regular expressions](https://www.gnu.org/software/sed/manual/sed.html#BRE-vs-ERE).

**Comment by mspncp** [comment]
Travis failure is unrelated:

https://travis-ci.org/openssl/openssl/jobs/326875244
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-5 g++-5
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package gcc-5
E: Unable to locate package g++-5
E: Couldn't find any package by regex 'g++-5'
apt-get.diagnostics
apt-get install failed
```

**Comment by mspncp** [comment]
And I envy you for taming the perl beast ;-)

**Comment by mspncp** [comment]
The magic trick is to break down the regular expressions into little understandable parts and give them human readable names.

**Comment by kaduk** [comment]
@mspncp I don't know of a portable way -- ```sed -i'' -e 's/a/b/' filename``` uses ```-e``` as the backup extension for BSD sed, and ```sed -i '' -e 's/a/b/' filename``` treats ```''``` as a filename (after the shell condenses the quotes, so it's quite silly behavior IMO).

**Comment by mspncp** [comment]
@kaduk that's annoying. So I'll suggest to just ignore BSD.

**Comment by levitte** [comment]
I agree with ignoring BSD for now.

**Comment by mspncp** [comment]
@levitte note that your commit hook will create a `2018-2018` copyright entry for this file, unless you update it before comitting this PR.

**Comment by levitte** [comment]
Fortunately, I have made it a commit hook yet.  I used it manually and did notice the duplicate year thingy...  and I was about to report it, but you had already discovered it on your own, so ;-)

**Comment by mspncp** [comment]
@richsalz you're right. It's better to have it done semi automated by the committer when merging.

**Comment by levitte** [comment]
Our server hooks only check...  and scream loudly when something's wrong (or in the copyright stuff case, it emails @richsalz and me)

**Comment by mspncp** [comment]
Rebased commit and reworded (simplified) the subject line. No code changes.

**Comment by levitte** [comment]
Merged. 433a2e038423f111f5f9e66fe6d8ad67dd241422

**Pull request closed without merging**
