### PR TITLE
Test more curves - 3.0

### PR DESCRIPTION
**Pull request by bernd-edlinger**
- Add tests with various curves in TLS1.3
- Resolves incompatibility between 3.0/master and 1.1.1

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
This is an unexpected CI failure
at basic_gcc test, https://github.com/openssl/openssl/runs/6710674716?check_suite_focus=true
```
        # ERROR: (ptr) 'pkey = EVP_PKEY_Q_keygen(libctx, NULL, "RSA", 2048) != NULL' failed @ test/acvp_test.c:1254
2022-06-02T15:03:15.9688441Z         # 0x0
2022-06-02T15:03:15.9688861Z         # OPENSSL_TEST_RAND_ORDER=1654182192
2022-06-02T15:03:15.9689622Z         not ok 17 - iteration 1
2022-06-02T15:03:15.9701287Z # ------------------------------------------------------------------------------
2022-06-02T15:03:15.9702103Z     # OPENSSL_TEST_RAND_ORDER=1654182192
2022-06-02T15:03:15.9702659Z     not ok 8 - rsa_decryption_primitive_test
2022-06-02T15:03:16.1443612Z # ------------------------------------------------------------------------------30-test_defltfips.t ................ ok
2022-06-02T15:03:16.3971848Z 30-test_engine.t ................... ok
2022-06-02T15:03:19.8420349Z 25-test_verify.t ................... ok
2022-06-02T15:03:23.0160664Z 30-test_evp_extra.t ................ ok
2022-06-02T15:03:25.8614838Z 
2022-06-02T15:03:25.8615848Z ../../util/wrap.pl ../../test/acvp_test -config ../../test/fips.cnf => 1
2022-06-02T15:03:25.8616518Z not ok 1 - running acvp_test
2022-06-02T15:03:25.9022730Z # ------------------------------------------------------------------------------
2022-06-02T15:03:25.9023451Z #   Failed test 'running acvp_test'
2022-06-02T15:03:25.9024404Z #   at test/recipes/30-test_acvp.t line 29.
2022-06-02T15:03:25.9024850Z # Looks like you failed 1 test of 1.30-test_acvp.t ..................... 
2022-06-02T15:03:25.9025157Z Dubious, test returned 1 (wstat 256, 0x100)
2022-06-02T15:03:25.9025386Z Failed 1/1 subtests
[...]
2022-06-02T15:04:25.8641781Z Test Summary Report
2022-06-02T15:04:25.8642129Z -------------------
2022-06-02T15:04:25.8650856Z 30-test_acvp.t                   (Wstat: 256 Tests: 1 Failed: 1)
2022-06-02T15:04:25.8651218Z   Failed test:  1
2022-06-02T15:04:25.8651558Z   Non-zero exit status: 1
2022-06-02T15:04:25.8657567Z Files=243, Tests=3429, 189 wallclock secs ( 7.21 usr  0.64 sys + 327.74 cusr 37.79 csys = 373.38 CPU)
2022-06-02T15:04:25.8657922Z Result: FAIL
```

**Comment by bernd-edlinger** [comment]
When I repeated the failed CI build the error was not repeatable: See #18466

**Comment by t8m** [comment]
Did you try running the test with OPENSSL_TEST_RAND_ORDER=1654182192 ?

**Comment by t8m** [comment]
Also it could be an instance of the things fixed by https://github.com/openssl/openssl/pull/18429

**Comment by bernd-edlinger** [comment]
in the failed CI log I saw this:
```
2022-06-02T14:57:56.9912738Z ##[group]Run sudo locale-gen tr_TR.UTF-8
2022-06-02T14:57:56.9913169Z [36;1msudo locale-gen tr_TR.UTF-8[0m
2022-06-02T14:57:56.9971721Z shell: /usr/bin/bash -e {0}
2022-06-02T14:57:56.9972077Z ##[endgroup]
2022-06-02T14:57:57.0790869Z Generating locales (this might take a while)...
2022-06-02T14:57:59.1578145Z   tr_TR.UTF-8... done
2022-06-02T14:57:59.1578866Z Generation complete.
```

**Comment by bernd-edlinger** [comment]
Also it could be an instance of the things fixed by https://github.com/openssl/openssl/pull/18429
Hmm, a 1 in 2 million chance... Yeah why not...
But the test case fails here:
https://github.com/openssl/openssl/blob/6fd014f32257b63a0b17e5793faab3e70c979851/test/acvp_test.c#L1254
Sounds more like failure to recognize "RSA" in turkish...

**Comment by t8m** [comment]
> Sounds more like failure to recognize "RSA" in turkish...

That should be already fixed and the localetest passes. So IMO no.

**Comment by t8m** [comment]
> Hmm, a 1 in 2 million chance... Yeah why not...

If I understand it right this is chance of not finding the prime, however with small public exponents, there is perhaps also a chance that none of the candidate numbers tried (that would be prime) will have the GCD(Y–1, e) = 1.

**Comment by bernd-edlinger** [comment]
> If I understand it right this is chance of not finding the prime, however with small public exponents, there is perhaps also a chance that none of the candidate numbers tried (that would be prime) will have the GCD(Y–1, e) = 1.

Okay, I see what you mean, this is called 2 times both with e = 0x10001 (F4),
so that is 1 in a million multiplied with number of fips builds in each CI run.

Question is just, how did I deserve so much luck that such unlikely events always happen to me ?

**Review by paulidale — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
I removed the WIP, as the test failure seems unrelated.

**Comment by t8m** [comment]
I think the chance is not 1 in million but actually 1 in 1300 with the original 5*bits tries. Where with 20*bits tries it is something like 1 in 3 trillion which is sufficiently low.

**Comment by bernd-edlinger** [comment]
> I think the chance is not 1 in million but actually 1 in 1300 with the original 5bits tries. Where with 20bits tries it is something like 1 in 3 trillion which is sufficiently low.

How do you arrive at this number?
I read the proof in https://csrc.nist.gov/CSRC/media/Publications/fips/186/4/final/documents/comments-received-fips186-4-december-2015.pdf
at page 68, which seems to be correct math.


Bernd.

**Comment by bernd-edlinger** [comment]
Ah, you mean with e=3 only half of the 5bits prime candidates are usable.
Then we have probability = 1/exp(5/log(2)) = 1/1357.6
instead of 1/exp(10/log(2)) = 0.00000054256

But the acvp_test does generate two RSA keys with e=F4 (65537)
so only 1 of 65536 prime candidates == 1 modulo e.

Each RSA key needs two primes, so that makes 2/million test failures.
I'm not sure how many fips builds are in the CI flow, but probably
around 20, right?  Likely each time this test case runs exactly once.

So this makes this a 1/20000 probability per CI flow.

**Comment by kroeckx** [comment]
Does this enable a whole bunch of curves for TLS 1.3 that are not allowed by the standard? In that case the OTC should probably look at this.

I think that the behaviour we want is that TLS 1.3 is supported on both sides and no curves supported by TLS 1.3 are supported by either side, ECDHE is not used. If only ECDHE is supported by both sides, it should fail. It should not fall back to TLS 1.2.

**Comment by bernd-edlinger** [comment]
Anyway I don't care.

**Comment by kaduk** [comment]
> Does this enable a whole bunch of curves for TLS 1.3 that are not allowed by the standard? In that case the OTC should probably look at this.

Per https://datatracker.ietf.org/doc/html/rfc8446#appendix-B.3.1.4 , """Values within "obsolete_RESERVED" ranges are used in previous versions of TLS and MUST NOT be offered or negotiated by TLS 1.3 implementations."""

**Pull request closed without merging**
