### PR TITLE
Add new OpenSSL image files

### PR DESCRIPTION
**Pull request by jamuir**
Add the two files

-  doc/images/openssl-square.svg
-  doc/images/openssl-square-nontransparent.png

The png file (nontransparent, white background) can be used to update the profile picture for the OpenSSL organization on GitHub.

Fixes https://github.com/openssl/project/issues/262

### CODE REVIEW

**Comment by hlandau** [comment]
There is also a version of the new logo with "SSL" below "Open", which might be more suited to a logo that needs to fit in a square

**Comment by jamuir** [comment]
@hlandau :  Can you point me to an image file for the other version of the logo?

**Comment by jamuir** [comment]
I just pushed an update with a two-line version of the logo (Hugo, you can disregard my previous request).

I agree this version looks better when framed in a square.

**Review by hlandau — APPROVED** [review]

**Review by arapov — APPROVED** [review]

**Comment by quarckster** [comment]
I'm wondering why fonts in these images are different?

**Comment by sapkkaj** [comment]
Here is the canva version of the square logo. Let me know if this fixes the font and color issue. https://www.canva.com/design/DAFzltUGu5c/I8oPB_VQ3Y5zTjsX75etuQ/edit?utm_content=DAFzltUGu5c&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by arapov** [comment]
> Here is the canva version of the square logo. Let me know if this fixes the font and color issue. https://www.canva.com/design/DAFzltUGu5c/I8oPB_VQ3Y5zTjsX75etuQ/edit?utm_content=DAFzltUGu5c&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

@sapkkaj it does fix the issue. @jamuir could you update this PR with this logo please.

**Comment by jamuir** [comment]
Kajal sent me her files and I have used them in the latest commit.

For reference, the maroon colour that we use for the text "Open" has html colour code `6e2421`.

**Comment by jamuir** [comment]
the maroon colour used on www.openssl.org is slightly different (it uses `#721412`).

**Review by t8m — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Comment by hlandau** [comment]
The SVG file has been converted to paths, which is good.

FWIW I prefer the newer lighter red colour to our traditional maroon but we shouldn't change that without explicitly deciding to.

**Comment by quarckster** [comment]
I'm not satisfied with how the letters were converted. It's too imperfect and catches my eye.

Screenshot_20231114_084354

**Comment by arapov** [comment]
@sapkkaj, can you help with this to ensure the logo looks appropriate?

**Comment by jamuir** [comment]
@arapov : what is the name of the font that is being used?

**Comment by arapov** [comment]
set of logos to use: [openssl-logos-4gh.zip](https://github.com/openssl/openssl/files/13379442/openssl-logos-4gh.zip)

**Comment by arapov** [comment]
@james, there is the openssl.svg file that must replace the old, existing one in the repository, too.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
I thought we are keeping both square and one-line logos?

**Comment by jamuir** [comment]
> ~I thought we are keeping both square and one-line logos?~ Ah I misunderstood. You're asking to replace the one-line logo in sources with the one from the zip file.

I just replaced all three image files with the ones Anton provided.

**Comment by t8m** [comment]
I'd say this should go to all 3.x branches. @hlandau please confirm?

**Comment by hlandau** [comment]
This seems a little different from the square logo we're using on Matrix. That version has the two lines a bit closer together. Personally I think that version looks a little better.

**Review by arapov — APPROVED** [review]

**Comment by hlandau** [comment]
> Hugo, do you agree the changes should go to all 3.x branches?

OK

**Comment by levitte** [comment]
Merged

master:
339e5cb0be8e57372548401a998d2e5145cfc7eb Update OpenSSL logos

3.2:
bcb488d3a5f7e24667c739c5fe5fa4ac6d10ca87 (HEAD -> openssl-3.2) Update OpenSSL logos

3.1:
f558298d398729da1536da3898dc40abe92fba3a (HEAD -> openssl-3.1) Update OpenSSL logos

3.0:
a980c99b6a0b97754034204814fb66553f47b4cb (HEAD -> openssl-3.0) Update OpenSSL logos

**Comment by jamuir** [comment]
Thanks, Richard.

**Pull request closed without merging**
