### PR TITLE
Fix a windows build break

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Fix a windows build break introduced recently.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by FdaSilvaYY** [comment]
Build error is :
```
        "cl"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -I "." -I "include" -I "providers\common\include" -I "providers\implementations\in
clude" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"\\dev\\openssl\\ssl\"" -D"ENGINESDIR=\"\\dev\\openssl\\lib\\engines-3\"" -D"MODULESDIR=\"\\dev\\openssl\\lib
\\ossl-modules\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_D
EPRECATED_NO_WARNINGS" -D"NDEBUG"   -DAES_ASM -DCMLL_ASM -DDES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSS
L_BN_ASM_PART_WORDS -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPOLY1305_ASM -DRMD160_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -
DWHIRLPOOL_ASM -c /Focrypto\asn1\libcrypto-shlib-a_mbstr.obj "crypto\asn1\a_mbstr.c"
a_mbstr.c
F:\include\internal/unicode.h(21) : error C2054: expected '(' to follow 'inline'
F:\include\internal/unicode.h(22) : error C2085: 'is_unicode_surrogate' : not in formal parameter list
F:\include\internal/unicode.h(22) : error C2143: syntax error : missing ';' before '{'
F:\include\internal/unicode.h(26) : error C2054: expected '(' to follow 'inline'
F:\include\internal/unicode.h(27) : error C2085: 'is_unicode_valid' : not in formal parameter list
F:\include\internal/unicode.h(27) : error C2143: syntax error : missing ';' before '{'
crypto\asn1\a_mbstr.c(247) : warning C4013: 'is_unicode_valid' undefined; assuming extern returning int
NMAKE : fatal error U1077: 'C:\VStudio12\VC\BIN\cl.EXE' : return code '0x2'
```

**Comment by beldmit** [comment]
Shouldn't it be marked as urgent?

**Comment by FdaSilvaYY** [comment]
May be this PR should be tag as urgent ?

**Review by beldmit — APPROVED** [review]
LGTM

**Review by slontis — APPROVED** [review]
Changed tag to urgent.. Does someone else concur that this is urgent.

**Comment by DDvO** [comment]
Which AppVeyor run(s) does this affect?
I cannot find it; @slontis, can you point to one?

**Comment by slontis** [comment]
I tagged you just recently on one of these..

**Review by paulidale — APPROVED** [review]

**Comment by slontis** [comment]
Looks like I might look into adding a windows build to the workflow tomorrow..

**Comment by FdaSilvaYY** [comment]
Ready to merge ?

**Comment by FdaSilvaYY** [comment]
> 
> 
> Which AppVeyor run(s) does this affect?
> I cannot find it; @slontis, can you point to one?

My build command was : 
`perl Configure VC-WIN32 shared ... `

**Comment by slontis** [comment]
Thanks for fixing. Merged to master.

**Pull request closed without merging**
