### PR TITLE
x86_64 assembly pack: add AVX512 ChaCha20 and Poly1305 code paths.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by kaduk** [comment]
Should there be more test cases to catch edge cases in the logic of the underlying implementation, and comments in the implementation to indicate where the relevant edge cases may be?

**Comment by elalfer** [comment]
Looks good to me.
- Compiled successfully with gcc 5.2.0 & BinUtils 2.25
- Both poly1305 and chacha use AVX512 codepath (verified with SDE)
- EVP validation test passed successfully without errors

**Comment by dot-asm** [comment]
> Should there be more test cases to catch edge cases in the logic of the underlying implementation,

New tests do exercise corner cases for newly introduced code paths.

> and comments in the implementation to indicate where the relevant edge cases may be?

Added commentary. In the nutshell it's sufficient to test 128+64, n*128 and n*128+64 for Poly1305, and 512 and 512+something for ChaCha20. Hence new test vectors are 192, 512 and 576. Well, to be frank I also have some internal ChaCha20 tests... I can publish it at some later point...

**Comment by dot-asm** [comment]
> it's sufficient to test `128+64`, `n*128` and `n*128+64` for Poly1305

This turned to be a little bit incorrect. It *was* meaningful to test `128+64` when I started to put the new code together. Initially I was treating lengths >=128 in AVX512 specifically to maximize exposure to internal tests. Final version on the other hand passes lengths >=512 to AVX512, so that `128+64` was actually rendered redundant.

**Pull request closed without merging**
