### PR TITLE
Avoid buffer overruns in req.

### PR DESCRIPTION
**Pull request by paulidale**
Avoid buffer overruns in the _req_ utility.

Clean up some of the formatting "return x" instead of "return (x)" mostly.

### CODE REVIEW

**Comment by levitte** [comment]
Master only, or do you intend to cherry-pick this to 1.1.0 as well?

**Comment by paulidale** [comment]
I was planning on merging these changes to master only.  If folks think 1.1.0 as well, I'm happy to do it too.  At least if it is possible.

I'll note that the old code didn't actually have an overflow issue except perhaps in `add_attribute_object`.  The earlier code checks the lengths against the longest suffix (`_default`) first and fails if this is out of range.  The later checks I've added are therefore redundant.  They are worth keeping in case the code is ever changed or rearranged in the future -- it is a fairly low cost to pay for unintrusive checks that provide reasonable error messages.

**Comment by levitte** [comment]
If the same issue exists in 1.1.0, then I don't see why we wouldn't cherry-pick down to it.
I'm unsure if "the old code" refers to 1.1.0 or something older...

Either way, it was just a question

**Comment by paulidale** [comment]
The _old code_ being the code after the recent reversion but before this PR.

Lines 987 and 1047 guard against overflows subsequent to them.  The longest string is tested first and the later ones are left untested so no error is actually possible.  This isn't ideal, but it isn't broken and cannot cause problems as written -- maybe there will be problems later when another suffix is introduced.  This fix attempts to avoid any such.  The risk is that later backports of features which break the assumptions.

The later code from line 1170 has a risk of an overflow.  These could be guarded better and perhaps these are good to back merge to older branches.

Of course, I'll merge anything deemed useful back.

**Comment by paulidale** [comment]
The 1.1.0 code still has the reverted changes from #3701 .  Is there any reason to want to use these changes instead of those? @levitte ?  I.e. both code paths have the same protections and paranoia in place.

**Comment by paulidale** [comment]
I assume that there isn't any point to a 1.1.0 back port since these are guarded already.

**Pull request closed without merging**
