### PR TITLE
Implement Aria GCM/CCM Modes and TLS cipher suites

### PR DESCRIPTION
**Pull request by jon-oracle**
AEAD cipher mode implementation is based on that used for AES:

  https://tools.ietf.org/html/rfc5116

TLS GCM cipher suites as specified in:

  https://tools.ietf.org/html/rfc6209

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
@levitte do you want to merge these?  Otherwise, I'll do them tomorrow assuming there are no conflicts.

**Comment by levitte** [comment]
Doing it now.

**Comment by paulidale** [comment]
Great, thanks.

**Comment by levitte** [comment]
Merged. bc32673869842c7f00ae7016040a612f516ead7e

**Comment by dot-asm** [comment]
It doesn't show in apps/openssl ciphers list. [Am I missing some flag?] In either case it's probably appropriate to mention these in docs somewhere. BTW, man1/ciphers.pod lists modes that we have decided to *not* expose through TLS. As far as I recall, argument went like "CBC is effectively deprecated, if we expose any modes, it should be GCM". Is recollection correct, @paulidale?

**Comment by paulidale** [comment]
Yes, that recollection is correct ARIA CBC modes were rejected for that reason.

I get:
```
$ util/opensslwrap.sh ciphers ARIA128
ECDHE-ECDSA-ARIA128-GCM-SHA256:ECDHE-ARIA128-GCM-SHA256:DHE-DSS-ARIA128-GCM-SHA256:DHE-RSA-ARIA128-GCM-SHA256:RSA-PSK-ARIA128-GCM-SHA256:DHE-PSK-ARIA128-GCM-SHA256:ARIA128-GCM-SHA256:PSK-ARIA128-GCM-SHA256
```

Similar for `ARIA256` and `ALL`.  There is no `ARIA` though.

**Comment by dot-asm** [comment]
By not seeing it in cipher list I meant `apps/openssl ciphers -v | grep -i aria`. But second part is the one that is actually important, i.e. new ciphers should be listed in man1/ciphers.pod. Obviously in separate request. And while you are at it, maybe it would be appropriate to add a note that CBC modes are not actually "wired" to TLS. Or removed from ciphers.pod. I mean they are currently listed in man1/ciphers.pod, and it might give wrong impression...

**Comment by paulidale** [comment]
I've added the ARIA flavour in #4300

**Comment by paulidale** [comment]
Could the lack of ARIA in the `ciphers -v` listing be because it isn't in the default set?
`apps/openssl ciphers -v ALL | grep -i aria` works.

I agree a documentation update in a separate PR.  Some CBC ciphers are included and I thought they could be used for TLS.

**Comment by paulidale** [comment]
Don't worry,  I misunderstood.  Now I understand.  The ARIA CBC ones are included and shouldn't be.  The ARIA GCM ones need to be added.

**Pull request closed without merging**
