### PR TITLE
Enable the ability to seed the test RNG without randomising test ordering

### PR DESCRIPTION
**Pull request by mattcaswell**
Numerous tests use the test_random() function to get a random number. If a
test fails then the seed that was used for the test RNG is displayed.
Setting the seed to the same value in a future run is supposed to cause the
same random numbers to be generated again.

The way to set the RNG seed again is to use the `OPENSSL_TEST_RAND_ORDER`
environment variable. However setting this environment variable *also*
randomises the test ordering as well as seeding the RNG. This in itself
calls test_random() so, in fact, when the test finally runs it gets
different random numbers to when it originally run (defeating the
repeatability objective).

This means that only way repeatability can be obtained is if the test was
originally run with `OPENSSL_TEST_RAND_ORDER` set to 0. If that wasn't done
then the seed printed when the test failed is not useful.

We introduce a new environment variable `OPENSSL_TEST_RAND_SEED` which can
be used to independently seed the test RNG without randomising the test
ordering. This can be used to get repeatability in cases where test ordering
randomisation was not done in the first place.

### CODE REVIEW

**Comment by paulidale** [comment]
Is there any reason to keep to seeding via the old method?

I.e. set the seed using `OPENSSL_TEST_RAND_SEED` and randomise the ordering by setting `OPENSSL_TEST_RAND_ORDER`

This isn't a backward compatibility issue IMO.

**Comment by mattcaswell** [comment]
I wasn't intending to backport this, so I was reluctant to change the meaning of the environment variables between branches. That seemed unnecessarily confusing.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Agreed.  Another bit of legacy just added to the code :cry:

**Comment by rsbeckerca** [comment]
> Agreed. Another bit of legacy just added to the code 😢

Could this little bit help users with their FIPS certification? Not asking for myself, but for my community.

**Comment by paulidale** [comment]
No.  It's testing only and isn't a substitute for the DRBGs and seeding.  I guess it could be wrapped by a provider and exposed as a DRBG/seed but that would be a fair bit of work for no benefit -- the TEST RNG will have similar capabilities once #21964 is merged.

**Comment by mattcaswell** [comment]
Ping for second review

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by paulidale** [comment]
Merged.  We might want to consider backporting this to 3.0 and 3.1.

**Pull request closed without merging**
