### PR TITLE
EVP: use evp_pkey_copy_downgraded() in EVP_PKEY_copy_parameters()

### PR DESCRIPTION
**Pull request by levitte**
We used evp_pkey_downgrade() on 'from', which permanently converts 'from'
to have a legacy internal key.  Now that we have evp_pkey_copy_downgraded(),
it's better to use that (and thereby restore the constness contract).

### CODE REVIEW

**Comment by levitte** [comment]
This is currently WIP, because of mysterious failures in 80-test_ssl_new.t, which I *think*, but haven't confirmed yet, may be a bad interation involving differences in the RSA structure in the FIPS module vs in libcrypto.  It's weird, though, because the `evp_pkey_downgrade()` does the same thing, and that goes through with no issues...

**Review by paulidale — APPROVED** [review]
LGTM.  Not adding approval done due to the WIP problem mentioned.

**Comment by t-j-h** [comment]
@paulidale if you don't want to have something seen as approved then you need to **not** actually approve it.
The labels have no meaning other than a hint when people are looking through things - your approval at the moment means anyone can commit this. Note that @levitte still has this marked as WIP so he wasn't seeking approval yet.

As you both note, this isn't quite ready.

**Comment by levitte** [comment]
I rebased this on top of a fresh master.  Maybe the issue I experienced before has gone away by now, here's hoping...

**Comment by mattcaswell** [comment]
Looks ok to me, and all checks pass - so is this still WIP?

**Comment by levitte** [comment]
WIP removed, since the CIs agree with this

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged

93d6132a79d85127dffa1ce4e62b264cf38c296d EVP: use evp_pkey_copy_downgraded() in EVP_PKEY_copy_parameters()

**Pull request closed without merging**
