### PR TITLE
Deprecate SXNET, some old NETSCAPE data types (PR 15464)

### PR DESCRIPTION
**Pull request by richsalz**
See original comments, discussion, etc., in #15464.

### CODE REVIEW

**Comment by h-vetinari** [comment]
From previous OP: "Fixes #1177, #10668"

Out of curiosity, why move this into a new PR (instead of rebasing the old PR on master)?

**Comment by davidben** [comment]
Yay deprecating old bits. I can report that I've never seen anything use `NETSCAPE_CERT_SEQUENCE` or `SXNET`. We've deleted both on our end without any trouble.

I have, sadly, seen code that uses `NETSCAPE_SPKI` and `NETSCAPE_SPKAC`, including PyOpenSSL and Ruby. It's the output of the old `<keygen>` tag, so it's probably made it's way into various CA things.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen

**Comment by richsalz** [comment]
> Out of curiosity, why move this into a new PR (instead of rebasing the old PR on master)?

Because I removed my fork and all the PR's would have been closed anyway and I didn't want to lose all the work and comments that had been done. So I rebased on master, pushed them to Akamai's openssl/openssl fork, and then recreated the PR's that point to the old ones.

**Comment by t8m** [comment]
We should definitely revive this.

**Comment by t8m** [comment]
Could you please rebase this?

**Comment by richsalz** [comment]
No I will not rebase this. Why, so it can sit for another three years and be ignored until the next so-called "clean up"?

The contempt the project shows for its community with the recent spate of "please rebase" is palpable.

Apologize to everyone whose improvements you let languish, promise to try really hard to merge, and maybe.

**Comment by nhorman** [comment]
@richsalz 
yes, we have a lot of issues.  Many of them have gotten lost, I apologize.  There's nothing else to say there, except that we're trying to do better.

Part of doing better involves identifying those issues/prs which have fallen by the wayside and either reviving them so we can get them merged, or identifying them as stale/unresponsive/no longer applicable/etc and moving them out of the way so that our visibility into spaces where we can make progress is improved, so as to avoid this situation in the future.

I'm not sure what your intention is by saying "No I will not rebase this", but I assume the implication is that you want someone to copy your code, fix it up, rebase it, and open a separate PR to merge it?  We might do that (or, more accurately, we may if time allows recreate this work independently in a separate PR). What we're not going to do however is take your hard work and claim it as our own.  Doing so strips your agency from this work, and, generally speaking, thats a disservice to the community as a whole. Until its merged, this PR is your work, not ours.  That also places the onus on you to make corrections as needed (be it code changes/rebases/etc), and to make some noise if you think we're letting something slip.   Thats how our community moves forward.

What doesn't move anyone forward is complaining about not getting something done sooner when we're trying to get it done now.  Again, I apologize for us not getting to this.  Frustrating as that may be, it happened, and here we are.

So, where does that leave us?

1) You can rebase the PR, and let us review and merge it.  Make sure to keep us honest if it seem like its slipping.

2) You can close the PR, and someone else will hopefully get to re-creating this work in the future.  I'd hate to see that happen, as you've gone to the trouble to write it, which we all appreciate.

Its your code, you get to decide.  

The only thing I won't let you do is use a currently non-actionable PR as a forum to complain about things that you're generally upset about.   That only serves to perpetuate our pattern of a having a pile of non-actionable work items that hides things we can actually make progress on.

 If you want to point out failures in our process (which may in fact be helpful), open a discussion about it, and propose process improvements so that things get lost less.  Thats what we're trying to do with our current efforts (see our blog post [here](https://www.openssl.org/blog/blog/2024/06/25/issue-cleanup/) . There may be other things we could be doing, I have no idea, but thoughts are always appreciated.

**Comment by richsalz** [comment]
You didn't first discuss the process in a place that alllows comments, so I could only respond to actions the project is doing on GitHub.

I am not sure which of my three sentences [above](https://github.com/openssl/openssl/pull/16549#issuecomment-2206491376) you found insulting. You *are* treating your contributors with contempt by saying, after years of neglect, "please rebase." 

I am not interested in doing any work for OpenSSL. The license under which this was submitted allows anyone to take and modify the code. I am surprised you don't realize that.  It is not my code, I get to decide. It is code I contributed to OpenSSL. I do not know why *this one PR* is being treated by the project as sacrosanct, but that's wrong. Act as if it were merged, and fix things.  Or don't.

**Comment by nhorman** [comment]
the process has a blog post announcing it.  We have discussion space to contribute feedback if someone doesn't like something.

I don't find anything you've said insulting.  I'm trying to pay some deference to the code you wrote by not just taking and updating it without your input. I disagree with you on the notion that that is somehow contemptuous. 

If you don't want to do any work for openssl, ok, that's absolutely your prerogative, and I'm sorry to see you go.

**Comment by richsalz** [comment]
I said "in a place that allows comments."  Where does one comment and discuss blog posts?

The contempt is not for taking the PR which OpenSSL can do what it wants with, but for ignoring so many issues for years and then saying "please rebase or we'll close it." Does the project not feel it incurs any burden for ignoring people's work for so long?  Or is it just "too bad, update or we'll ignore it."

**Comment by levitte** [comment]
@richsalz, I did a rebase last night, it's currently sitting [in a branch in my fork](https://github.com/levitte/openssl/tree/rsalz-openssl-pr-15464).
I could either force push it into this PR (if I can, that depends on how this PR was set up), or create another PR with that (it would be wasteful, and I would prefer not to have to do that, but...).  Which do you prefer?

**Comment by richsalz** [comment]
Do you have any plans to do anything with this?  As mentioned in https://github.com/openssl/openssl/pull/16549#issuecomment-914595588, at least SXNET and NETSCAPE_CERT_SEQUENCE can be removed.  I'm going to close this PR amd you can re-open if you want and use @levitte 's code.

**Pull request closed without merging**
