### PR TITLE
CI: move final two run-checker CIs to GitHub Actions

### PR DESCRIPTION
**Pull request by paulidale**
The final pair are fuzzing builds which were left behind.

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
I suppose this will be push-only CI.

**Comment by levitte** [comment]
> The follow on question is should we drop run-checker entirely.
> That's a separate PR however.

Not to mention sysadmin action

**Comment by paulidale** [comment]
I've no problem with this being push only.  The builds aren't onerous, so I didn't think it was important.

**Comment by paulidale** [comment]
Switched to _push_ only.

**Review by t8m — APPROVED** [review]
Approved. As you said elsewhere, we should review the list of CI builds we do at some point.

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
