### PR TITLE
Don't distribute team internal config targets

### PR DESCRIPTION
**Pull request by levitte**
Configurations/90-team.conf isn't for public consumption, so we rename
it to 90-team.norelease.conf and make sure 'make dist' and 'make tar'
don't include it in the tarball.

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
Okay, but why not release it?

**Comment by levitte** [comment]
The name alone should be enough of a hint. It's a bunch of random *team* configs which are hardly relevant for public distribution. If you want to use them, t them with git.

**Comment by richsalz** [comment]
Shrug.  Seems like demo's, kinda worthwhile to have as examples, but NBD.

**Comment by FdaSilvaYY** [comment]
This PR is ready, no ?

**Comment by levitte** [comment]
Not quite, the "dist" target needs to be moved, or it must be used differently...

**Comment by levitte** [comment]
(closed and re-opened to see that the CIs agree)

I made the small change of moving the "dist" config target to its own file.  This should be good to go now, but needs re-approval.

**Comment by richsalz** [comment]
Reconfimr.

**Pull request closed without merging**
