### PR TITLE
Add Tomas Mraz key to release key fingerprints

### PR DESCRIPTION
**Pull request by t8m**
To be able to do a release in future.

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
We should also update the text on the download page about this:

https://www.openssl.org/source/

> PGP keys for the signatures are available from the [OMC page](https://www.openssl.org/community/omc.html). Current members that sign releases include Richard Levitte and Matt Caswell.

**Comment by t8m** [comment]
> We should also update the text on the download page about this:
> 
> https://www.openssl.org/source/
> 
> > PGP keys for the signatures are available from the [OMC page](https://www.openssl.org/community/omc.html). Current members that sign releases include Richard Levitte and Matt Caswell.

Now the question is how to update that page as I am not an OMC member so my key is not listed on that page. (And we do not list PGP keys for OTC members.)

**Comment by mattcaswell** [comment]
> Now the question is how to update that page as I am not an OMC member so my key is not listed on that page. (And we do not list PGP keys for OTC members.)

I'd suggest referring to the fingerprints file rather than to the OMC page.

**Review by levitte — APPROVED** [review]
Confirming that this corresponds to the key I have in my public keyring

**Comment by t8m** [comment]
> I'd suggest referring to the fingerprints file rather than to the OMC page.

But that file is not directly available to be linked to. But yeah, it could be added or we can create a new webpage with the fingerprints.

**Comment by levitte** [comment]
Haven't we already concluded that anyone on the OTC can be a release master?  It seems to be like the simple solution is to refer to the OTC member page than the OMC member page, and make sure to display the registered PGP keys for those where we have that.

**Comment by t8m** [comment]
That would work. How is the OTC member list generated?

**Comment by levitte** [comment]
It's generated much like the OMC list, with the script bin/mk-omc in the web repo.  Look for `otc.inc` and you'll find the spot in the Makefile where it's done.  All that's really needed is to add the `-p` option to the call of that script, and PGP keys will start to show for those where we have registered one.

Do note, though, that we have PGP keys registered for people that don't have machine access...  that's fine I guess, we're after all not saying that all OMC members are release masters either, so...

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you.

The PR for 1.1.1 branch is https://github.com/openssl/openssl/pull/18156

**Pull request closed without merging**
