### PR TITLE
Fix OSSL_TRACE9 missing arg9

### PR DESCRIPTION
**Pull request by wongsyrone**
fix OSSL_TRACE9 macro

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I agree that this would be trivial.  Could you either "git commit --amend" and add the line "CLA: trivial" to the bottom of the commit message or submit a signed ICLA?

**Comment by wongsyrone** [comment]
Force pushed

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
Agree trivial.

**Comment by wongsyrone** [comment]
> First-time contributors need a maintainer to approve running workflows.

What should I do now?

**Comment by t-j-h** [comment]
There is nothing for you to do now. A 24-hour grace period happens where other committers can object to the change.
And then after that one of the committers will actually commit the code to the repository.

Thanks for your contribution.

It would be good to get a CLA in place for future contributions that are non-trivial in nature.

**Comment by wongsyrone** [comment]
> It would be good to get a CLA in place for future contributions that are non-trivial in nature.

Can I comment in this PR to sign the CLA?

**Comment by paulidale** [comment]
We need a paper / scanned copy emailed to us.  Download the ICLA from [here](https://www.openssl.org/policies/openssl_icla.pdf), fill it in and sign it and email back to legal@opensslfoundation.org.  If your work is part of your employment, we also require a CCLA from your employer.

**Review by mspncp — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the fix.

**Pull request closed without merging**
