### PR TITLE
Update Cloudflare Quiche to post 0.18.0

### PR DESCRIPTION
**Pull request by t8m**
This is necessary to fix the failing CI.

### CODE REVIEW

**Comment by t8m** [comment]
This is urgent as the CI is failing currently.

**Comment by hlandau** [comment]
Agree urgent

**Review by beldmit — APPROVED** [review]
LGTM if test passed, agree urgent

**Comment by t8m** [comment]
The relevant CI is passing. Merged to the master branch. Thank you for the reviews.

**Pull request closed without merging**
