### PR TITLE
ppccap.c: Split out algorithm-specific functions

### LINKED ISSUE #13336: aix64-cc or aix64-gcc with asm target: make test fails (provider loading from shared modules fails)
```
$ make teste
....
20-test_app.t ...................... ok

Verified OK
../../util/wrap.pl ../../apps/openssl dgst -sha256 -verify DSA.nonfips.priv.pem -signature DSA.nonfips.sig ../../providers/fips.so => 0
    not ok 13 - DSA: Verify something with a non-FIPS key (should fail) # TODO see issues #12626, #12627
# ------------------------------------------------------------------------------20-test_cli_fips.t ................. ok
20-test_dgst.t ..................... ok

aes-128-cbc: unable to load provider legacy
00000001:error::DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(../../providers/legacy.so): rtld: 0712-001 Symbol sha256_block_p8 was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol sha256_block_ppc../../providers/legacy.so was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol sha512_block_p8 was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol sha512_block_ppc../../providers/legacy.so was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol ChaCha20_ctr32_vmx was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol ChaCha20_ctr32_vsx was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
rtld: 0712-001 Symbol ChaCha20_ctr32_int was referenced
      from module ../../providers/legacy.so(), but a runtime definition
	    of the symbol was not found.
Additional errors occurred but are not reported.
00000001:error::DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
00000001:error::common libcrypto routines:provider_activate:init fail:crypto/provider_core.c:537:
../../util/wrap.pl ../../apps/openssl aes-128-cbc -bufsize 113 -e -k test -provider-path ../../providers -provider default -provider legacy -in ./p -out ./p.aes-128-cbc.cipher => 1
not ok 3 - aes-128-cbc
..
<more errors here>
...
30-test_engine.t ................... ok

    # ERROR:  @ test/evp_test.c:3601
    # Failed to load config ../../test/default-and-legacy.cnf
    # 
    # 
    # Usage: evp_test [options] [file...]
    # Valid options are:
    #  -help           Display this summary
    #  -list           Display the list of tests available
    #  -test val       Run a single test by id or name
    #  -iter int       Run a single iteration of a test
    #  -indent +int    Number of tabs added to output
    #  -seed int       Seed value to randomize tests with
    #  -config infile  The configuration file to use for the libctx
    # file	File to run tests on.
../../util/wrap.pl ../../test/evp_test -config ../../test/default-and-legacy.cnf ../../test/recipes/30-test_evp_data/evpciph_aes_ccm_cavs.txt => 1
not ok 2 - running evp_test -config ../../test/default-and-legacy.cnf evpciph_aes_ccm_cavs.txt
# ------------------------------------------------------------------------------
..
<more errors here>
...

$ dump -Tv -X64 legacy.so
...
[111]   0x00000000    undef      IMP     DS EXTref libpthreads.a(shr_xpg5_64.o) pthread_rwlock_destroy
[112]   0x200058d0    .data      EXP     DS   Ldef        [noIMid] OSSL_provider_init
[113]   0x00000000    undef      IMP     DS EXTref              .. sha256_block_p8
[114]   0x00000000    undef      IMP     DS EXTref              .. sha256_block_ppc
[115]   0x00000000    undef      IMP     DS EXTref              .. sha512_block_p8
[116]   0x00000000    undef      IMP     DS EXTref              .. sha512_block_ppc
[117]   0x00000000    undef      IMP     DS EXTref              .. ChaCha20_ctr32_vmx
[118]   0x00000000    undef      IMP     DS EXTref              .. ChaCha20_ctr32_vsx
[119]   0x00000000    undef      IMP     DS EXTref              .. ChaCha20_ctr32_int
[120]   0x00000000    undef      IMP     DS EXTref              .. poly1305_init_int
[121]   0x00000000    undef      IMP     DS EXTref              .. poly1305_blocks_vsx
[122]   0x00000000    undef      IMP     DS EXTref              .. poly1305_emit
[123]   0x00000000    undef      IMP     DS EXTref              .. poly1305_blocks
```

### PR DESCRIPTION
**Pull request by t8m**
Fixes #13336

This includes one part of the #15798 PR. It will be dropped after that PR is merged and this is rebased.

### CODE REVIEW

**Comment by t8m** [comment]
@gv74 can you please try this with #15798

**Comment by gv74** [comment]
```
$ git clone https://github.com/t8m/openssl.git
...
$ git checkout aix-asm-fix
$ cd openssl
./Configure --prefix=/usr/pd --openssldir=/var/pd/ssl aix64-gcc
$ make 2>&1 | tee ../openssl-t8m-build.log
...
Assembler:
crypto/bn/ppc64-mont-fixed.s: line 4: Error In Syntax
make[1]: *** [Makefile:13936: crypto/bn/libcrypto-lib-ppc64-mont-fixed.o] Error 1
make[1]: Leaving directory '/home/gabriel/openssl'
make: *** [Makefile:3200: build_sw] Error 2
$
```
 [Fix #15748]
```
$ make 2>&1 | tee -a ../openssl-t8m-build.log
make test  2>&1 | tee ../openssl-t8m-test.log
```
[openssl-t8m-build.log.gz](https://github.com/openssl/openssl/files/6682010/openssl-t8m-build.log.gz)
[openssl-t8m-test.log.gz](https://github.com/openssl/openssl/files/6682013/openssl-t8m-test.log.gz)

It seems like #13336 is fixed.
Thank you.

**Comment by t8m** [comment]
Thank you for checking it.

Ping for review(s).

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
CIs not relevant.

**Comment by mattcaswell** [comment]
Pushed.

**Pull request closed without merging**
