### PR TITLE
Replace `unsigned int *` by `size_t *` in `EVP_Q_{digest,mac}()` outlen parameter

### LINKED ISSUE #15839: `unsigned int` instead of `size_t` in `EVP_Q_mac()`
PR #14664 added `EVP_Q_mac()` as a wrapper around the `EVP_MAC` functionality to improve usability.

Unfortunately we did not notice that the parameter type of the last argument of the new function is inconsistent with the underlying function, as it swapped `size_t*` for `unsigned int*`.

This is evident when comparing `(unsigned int*) outlen` in

https://github.com/openssl/openssl/blob/openssl-3.0.0-beta1/include/openssl/evp.h#L1215-L1219

against `(size_t*) outl` in

https://github.com/openssl/openssl/blob/openssl-3.0.0-beta1/include/openssl/evp.h#L1223-L1224

### PR DESCRIPTION
**Pull request by DDvO**
As discussed in OTC meeting on Tuesday.

Fixes #15839.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Hmmm, #15861

**Comment by DDvO** [comment]
> Hmmm, #15861

Argh, I had been assigned to fix that, and now I realize that you already did it.

**Comment by levitte** [comment]
> Argh, I had been assigned to fix that, and now I realize that you already did it.

Ah, sorry, I hadn't seen that 😖

**Comment by DDvO** [comment]
Closing this PR in favor of the - slightly better - #15861.

**Pull request closed without merging**
