### PR TITLE
APPS/cmp.c: Move warning on overlong section name to make it effective again

### LINKED ISSUE #16585: Dead code in apps/cmp.c
In apps/cmp.c line 2009, the condition can never be true
Line 2004 :
    if (len > SECTION_NAME_MAX)
        len = SECTION_NAME_MAX;
Line 2009 : 
    if (len > SECTION_NAME_MAX)
        CMP_warn2("using only first %d characters of section name starting with \"%s\"",
                  SECTION_NAME_MAX, opt_item);

### PR DESCRIPTION
**Pull request by DDvO**
Fixes #16585

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I don't object to this in 3.0 but don't see it as critical.

**Review by t8m — APPROVED** [review]
IMO this should be merged to 3.0 as it is clearly a bug fix.

**Comment by DDvO** [comment]
> IMO this should be merged to 3.0 as it is clearly a bug fix.

Fine - shall I merge this now, to both master and 3.0?

**Comment by t8m** [comment]
> Fine - shall I merge this now, to both master and 3.0?

Yes, sure.

**Comment by DDvO** [comment]
Done - thanks @paulidale and @t8m for your approvals and comments.

**Comment by t8m** [comment]
I've cherry-picked this to 3.0 branch as well.

**Pull request closed without merging**
