### PR TITLE
Regenerate bn_prime.h

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This generated file has white-space differences, if it is re-built.
That happens occasionally and is reported by git diff.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
The PR is for 1.0.2

**Comment by richsalz** [comment]
Do "we" need to change the generation script also?

**Comment by bernd-edlinger** [comment]
Looks like some white-space cleanup was done on the generated header file.
It is unclear why generated stuff has to be checked in at all.

**Comment by levitte** [comment]
This change looks way wrong. My guess is that the generation script needs fixing.

**Comment by bernd-edlinger** [comment]
Could it be that the same happens also on master?

**Comment by bernd-edlinger** [comment]
> This change looks way wrong. My guess is that the generation script needs fixing.

Hmm, do you mean the prime numbers are wrong when they are generated????

**Comment by levitte** [comment]
Sorry, haven't looked at the numbers. The source layout of the change is eay style, which we abandoned quite a while ago now...

**Comment by bernd-edlinger** [comment]
Funny, I just wanted to switch to the master branch, and now I have a bunch of changes
in apps/progs.h:

--- a/apps/progs.h
+++ b/apps/progs.h
@@ -1,366 +1,366 @@
 /* apps/progs.h */
 /* automatically generated by progs.pl for openssl.c */
 
-extern int verify_main(int argc, char *argv[]);
-extern int asn1parse_main(int argc, char *argv[]);
-extern int req_main(int argc, char *argv[]);
-extern int dgst_main(int argc, char *argv[]);

**Comment by bernd-edlinger** [comment]
So apparently there are more generated files out of sync, but it is just eay-style-nits.

On trunk the generation scripts are not even invoked if I remove the generated files,
how do you generate the generated files?

**Comment by levitte** [comment]
`make update`

**Comment by levitte** [comment]
Regarding jumping between master and release branches, I can recommend keeping each of those branches in a separate directory each.  That makes it much easier to handle.

**Comment by bernd-edlinger** [comment]
Bye.

**Pull request closed without merging**
