### PR TITLE
TEST: Add missing initialization

### PR DESCRIPTION
**Pull request by levitte**
Compiler complained.

### CODE REVIEW

**Comment by levitte** [comment]
Marked urgent because builds are currently failing

**Comment by mattcaswell** [comment]
I suspect this needs to go back to 1.1.1 too

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
> I suspect this needs to go back to 1.1.1 too

Ah, yes.  Do you appreove a cherry pick?

**Comment by levitte** [comment]
Merged

master:
55e9d8cfffc1a40b0ab72e014ff62d5ef2a0ed63 TEST: Add missing initialization

1.1.1:
01cf4f868e08f82daa16d049fa7d241d8089c8d8 TEST: Add missing initialization

**Pull request closed without merging**
