### PR TITLE
evp_test: Add the missing check after calling OPENSSL_malloc

### PR DESCRIPTION
**Pull request by JiangJias**
The OPENSSL_zalloc() could return NULL pointer if fails.
Add the check for it does make sense, like how digest_test_init() deals
with.

CLA: trivial

Signed-off-by: Jiasheng Jiang <jiasheng@iscas.ac.cn>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Please drop the last commit. We do not allow merging with merge commits.

**Comment by t8m** [comment]
(Just `git reset --hard HEAD~` and force push should suffice.)

**Comment by JiangJias** [comment]
> (Just `git reset --hard HEAD~` and force push should suffice.)

Fine, I have done it.

**Review by t8m — APPROVED** [review]
OK with CLA: trivial.

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
