### PR TITLE
Check for NULL before calling BN_CTX_end

### PR DESCRIPTION
**Pull request by richsalz**
Fixes a coverity issue reported on April 29.

### CODE REVIEW

**Comment by dot-asm** [comment]
It might make coverity happy, but if you have closer look, you'll notice bigger problem. Namely that BN_CTX_end can be called without BN_CTX_start, thus potentially messing up things for caller. There are multiple ways to solve the problem, none of which requires check for ctx being non-NULL. One can either a) return 0 from first `if` *and* move BN_CTX_start next to it; b) arrange second err label for dropouts past BN_CTX_start and move BN_CTX_end between original and second label; c) arrange boolean variable that would be set after BN_CTX_start is called and call BN_CTX_end if it's set...

**Comment by richsalz** [comment]
I approved your better fix.

**Comment by dot-asm** [comment]
I don't follow last remarks. What is checked in? What is merged? Nothing is...

**Comment by richsalz** [comment]
Oops.  It was approved, i merged but did not push to the repo!  Ha.  Lucky.

**Pull request closed without merging**
