### PR TITLE
Move more socket stuff

### PR DESCRIPTION
**Pull request by levitte**
The socket stuff for DJGPP and VMS was only partially moved to
include/internal/sockets.h...

Remains vxWorks.

----

This continues the work started in #4209

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
Oops, I made a mistake...  corrective commit coming up

**Comment by levitte** [comment]
Ok, *now* things seem to build everywhere.  I'll do a couple of VMS builds too, to be safe...

**Comment by levitte** [comment]
Ok, builds and tests fine on VMS too now.  A reconfirm would sit well at this point ;-)

**Comment by richsalz** [comment]
reconfirm

**Comment by levitte** [comment]
Merged. 9a5d80cb5e and 384cdd46a1

Thank you!

**Pull request closed without merging**
