### PR TITLE
Don't try to parse empty ClientHello extension field

### PR DESCRIPTION
**Pull request by ghedo**
RT#4069

### CODE REVIEW

**Comment by ghedo** [comment]
Indeed, I was just looking at how the ServerHello extensions are parsed and that seems the best way, patch updated.

**Comment by ghedo** [comment]
(I was replying to https://github.com/ghedo/openssl/commit/57cade8b73d4ab24e093fc6d46997ee49c0e7f82#commitcomment-13560588 btw... now it looks like I'm talking to myself).

**Comment by mattcaswell** [comment]
Ha ha. That's funny :-)

Will you be preparing a 1.0.2/1.0.1 patch too?

**Comment by ghedo** [comment]
Yeah, I'll look into it. I'll open new PRs when I have something.

**Comment by mattcaswell** [comment]
Most likely a 1.0.2 patch will work for 1.0.1 too - its just master that is quite different.

**Comment by ghedo** [comment]
I slightly changed the patch to use `goto err` instead of return. Also, I opened #422 for 1.0.2 and 1.0.1.

**Comment by mattcaswell** [comment]
Patch applied. Many thanks.

**Pull request closed without merging**
