### PR TITLE
Changed some typedefs to use the fixed-width integer types from opens…

### PR DESCRIPTION
**Pull request by heavycrystal**
…sl/e_os2.h, which uses stdint.h when possible.

Considering the project already uses fixed-width integer types extensively, this PR switches several files to using fixed-width integer types, as defined in e_os2.h.

### CODE REVIEW

**Comment by t8m** [comment]
I am unsure whether the public header changes are an API break or not.

**Comment by paulidale** [comment]
Losing `SEED_LONG` is an API break.  I think the rest are okay but am not completely sure.

**Comment by mattcaswell** [comment]
> I am unsure whether the public header changes are an API break or not.

Yes they are. They are changing the definition of public structures. If people are accessing those structure fields then they are suddenly dealing with a different to type to what they were before. That could result in problems and is an API break IMO.

**Comment by heavycrystal** [comment]
My understanding was that since uint32_t is just a typedef to unsigned int/ unsigned long anyway, any preexisting code should still work:

typedef declaration does not introduce a distinct type, it only establishes a synonym for an existing type, thus typedef names are compatible with the types they alias. [source](https://en.cppreference.com/w/c/language/typedef)

The structure layouts should be unchanged as well. 

I'm not sure if SEED_LONG or AES_LONG are documented configuration options, but any code ~could still use them, just that the compiler should autoguess the correct type anyway.

**Comment by levitte** [comment]
> Losing `SEED_LONG` is an API break. I think the rest are okay but am not completely sure.

That one specifically, or was it just an example?  This change loses `AES_LONG` as well.  And either way, I'm not sure how loosing them as an API break, as their only function was to make sure that some types become a correctly sized integer type.

**Comment by levitte** [comment]
As far as I can tell, this is not an API break, insofar that the integer types that are being replaced with `intxx_t` or `uintxx_t` are compatible with those.  That is, unless you know of a compiler that compares integer types for compatibility by the type symbol names, but then I think you've found a fundamentally broken compiler.

This PR is really a cleanup of age old definitions that were made before `intxx_t` and `uintxx_t` became defined types...  what age old definitions do is really a duplication of the `intxx_t` and `uintxx_t` definitions, but much more ad-hoc, and in some cases, obsolete (the diffferent BN_ULONG definitions for SIXTY_FOUR_BIT and SIXTY_FOUR_BIT_LONG is really not necessary in this day and age, for example).  In the end, the question is, who do we think does a better job, our definitions or the compiler's?

**Comment by levitte** [comment]
(I guess we've encountered a gray area of what we mean with "API break" :wink:)

**Comment by paulidale** [comment]
Are we going to do anything with this one?
As far as I can see, the typedef changes aren't an API break.

**Comment by rsbeckerca** [comment]
You might have to provide platform options on using each time. uint32_t and uint64_t are not always enabled by default or generated by the compiler but at least from my POV can be made to work - I just went through this conversion on a different project.

**Comment by heavycrystal** [comment]
@rsbeckerca could you elaborate on what I need to do?

**Comment by rsbeckerca** [comment]
> @rsbeckerca could you elaborate on what I need to do?

For our platform, we would need to include something like the following:
```
#if defined OPENSSL_SYS_TANDEM
# include <tnsint.h> /* __uint32_t */
#endif
#include <sys/types.h> /* uint32_t, uint64_t on some platforms. */
#include <stdint.h>      /* uint32_t, uint64_t on some platforms. */
```
This would bring in `__uint32_t`, `uint32_t`, and `uint64_t`, regardless of the build/platform, as far as I know. I can try this if you have it in place.

**Comment by heavycrystal** [comment]
I think we can add this to openssl/e_os2.h, which should propagate to the other files. This would allow further refactoring in the future as well.

**Comment by rsbeckerca** [comment]
> I think we can add this to openssl/e_os2.h, which should propagate to the other files. This would allow further refactoring in the future as well.

Do you want a PR for this?

**Comment by heavycrystal** [comment]
That would be nice yes, @paulidale could confirm if that is the way to go.

The file in question is include/openssl/e_os2.h.

**Comment by rsbeckerca** [comment]
> That would be nice yes, @paulidale could confirm if that is the way to go.
> 
> The file in question is include/openssl/e_os2.h.

I'm not sure the code will just plug into include/openssl/e_os2.h. There are a lot spots where there are already definitions. I'm just going to fix this for TANDEM at this stage. Is that ok?

**Comment by rsbeckerca** [comment]
Pull request created to deal with NonStop ia64 and x86 type requirements. Generally, the other platforms seem to cover the integer type loads.

**Comment by heavycrystal** [comment]
@rsbeckerca That would be fine yes [I can't think of any other platform that does not have these definitions anyway]

Thanks for the PR!

**Pull request closed without merging**
