### PR TITLE
DANE TA priority (vs. cross certs) (master)

### PR DESCRIPTION
**Pull request by vdukhovni**
This is a bug fix for a DANE corner case where TLSA records publish a "DANE-TA(2) 0 0" full trust anchor certificate, but the remote peer's untrusted chain has instead a cross-cert.

This is the case with Let's Encrypt and the ISRG X1 root, which is also available as a cross cert signed by DST.

- [x] tests are added or updated

[ This is the "master" version of #16471 ]

### CODE REVIEW

**Review by t8m — APPROVED** [review]
Looks good. Also looks fairly straighforward so this should not un-stabilize 3.0.0 release in any way.

**Comment by t8m** [comment]
OTC: not a blocker for 3.0.0 release

**Comment by vdukhovni** [comment]
> Looks good. Also looks fairly straighforward so this should not un-stabilize 3.0.0 release in any way.

Thanks Tomáš. If you could spare a few minutes to look over the corresponding changes for 1.1.1 in #16471, that'd be great!

**Comment by vdukhovni** [comment]
Fixed dane-cross.in copyright year.  Please reconfirm approvals.

**Review by t8m — APPROVED** [review]

**Comment by vdukhovni** [comment]
@t8m Thanks for the reconfirmation. Not sure whether the 3.0 PR made it in time: #16485 to be included in the release.  It is identical to the master version (but squashed to two commits).

**Comment by vdukhovni** [comment]
Merged.  Thanks!

**Pull request closed without merging**
