### PR TITLE
Fix intermittent sslapitest early data related failures

### PR DESCRIPTION
**Pull request by mattcaswell**
Early data is time sensitive. We have an approx 8 second allowance between writing the early data and reading it. If we exceed that time tests will fail. This can sometimes (rarely) occur in normal CI operation. We can try and detect this and just ignore the result of such test failures if the test has taken too long. We assume anything over 7 seconds is too long.

This is a partial fix for https://github.com/openssl/openssl/issues/22605

### CODE REVIEW

**Comment by mattcaswell** [comment]
CI failures are unrelated - although the cross-compilation one looks strange. I don't recall seeing that one before.

**Review by t8m — APPROVED** [review]
LGTM, hopefully it fixes these failures.

**Comment by bernd-edlinger** [comment]
FYI: I have repeatedly seen test failures due to clock jumps recently.
The clock jumped a few seconds in the past making some recently created CRLs
failing the checks.  So I suppose the clock can easily jump forward as well.
To be safe you could use monotonic clock, i.e. `clock_gettime(CLOCK_MONOTONIC, ...)`?

**Comment by mattcaswell** [comment]
Ping @openssl/committers - still looking for a second reviewer for this

**Review by nhorman — APPROVED** [review]

**Comment by mattcaswell** [comment]
Backport PRs in #24319 and #24320. Closing this one.

**Pull request closed without merging**
