### PR TITLE
Changes made to avoid symbol conflict for gf_mul

### PR DESCRIPTION
**Pull request by Pankul94**
This PR is a result of https://github.com/openssl/openssl/issues/21302.

Renaming methods:
1. gf_mul -> ossl_gf_mul
2. gf_mulw_unsigned -> ossl_gf_mulw_unsigned

to resolve the symbol conflict on `gf_mul` when using intel/ISA-L and Openssl.

Ran `make` and `make test` and verified the build is successful.

Verified the symbols are renamed in libcrypto.so:
> openssl% nm -an libcrypto.so | grep gf_mul
00000000001081f0 t ossl_gf_mul
00000000001086a0 t ossl_gf_mulw_unsigned

### CODE REVIEW

**Comment by t8m** [comment]
There needs to be a PR against the master branch instead of 1.1.1. Does the commit cherry-pick cleanly?

As this is a simple internal symbol rename I assume this would be acceptable with CLA: trivial. However if you would be able to submit a regular CLA it would be even better.

**Comment by Pankul94** [comment]
The commit should cherry-pick cleanly however, this change is only applicable for Openssl-1.1.1. I will need to make additional changes to change the symbol name in Openssl-3.

**Comment by Pankul94** [comment]
I think I am confused here, I need to do additional changes to make sure these changes work on master branch. The problem is that those changes are not applicable to Openssl-1.1.1. So how should I handle this scenario?

**Comment by Pankul94** [comment]
I will create a new PR cutting directly to master branch

**Comment by mattcaswell** [comment]
Note that these changes will not be acceptable for 1.1.1. That branch is nearing end-of-life and is currently only accepting security fixes.

**Pull request closed without merging**
