### PR TITLE
improve comment: use "optimization" for clarity

### PR DESCRIPTION
**Pull request by jsoref**
The previous word was a misspelling of nicety
Split from #3459

### CODE REVIEW

**Comment by jsoref** [comment]
See @kroeckx https://github.com/openssl/openssl/pull/3459#discussion_r116379599

**Comment by kroeckx** [comment]
@levitte: This seems to be a comment written by you in 2000, care to comment?

**Comment by levitte** [comment]
I hope that's comment enough ;-)

**Comment by richsalz** [comment]
Thanks, merged but forgot to close.

**Pull request closed without merging**
