### PR TITLE
Fix test_cmp_vfy failures with FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION

### PR DESCRIPTION
**Pull request by DDvO**
Should fix issue reported today in #11386

- [x] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
> [extended tests]

That line needs to be in the actual commit message. Can you force push an update? Otherwise this looks good (and I agree this is urgent).

**Comment by DDvO** [comment]
Oops, done.

**Comment by DDvO** [comment]
So I'll merge this as soon as the CI tests passed...

**Comment by DDvO** [comment]
All four CI failures that have been reported: https://travis-ci.org/github/openssl/openssl/builds/677315133
are not CMP related but due to some (the same?) EVP issue. So I've just merged this.

**Pull request closed without merging**
