### PR TITLE
apps/s_socket.c: Fix do_accept [1.0.2 only]

### LINKED ISSUE #3407: s_server crashes with "gethostbyname failure" on iOS connect
Using Ubuntu 14.04 with latest packages
OpenSSL 1.0.1f 6 Jan 2014

When connecting with iPhone and iOS 10, I'm getting this crash on the server side: 
```bash
openssl s_server -accept 443 -chain -cert cert/example/example.cert -key cert/example/example.key -www -debug -msg -state
Enter pass phrase for cert/example/example.key:
Using default temp DH parameters
ACCEPT
gethostbyname failure
   0 items in the session cache
   0 client connects (SSL_connect())
   0 client renegotiates (SSL_connect())
   0 client connects that finished
   0 server accepts (SSL_accept())
   0 server renegotiates (SSL_accept())
   0 server accepts that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
   0 callback cache hits
   0 cache full overflows (128 allowed)
```

Tried to upgrade to the libssl and openssl used in Ubuntu 16.04: 
`OpenSSL 1.0.2g  1 Mar 2016` 
and got the same error.

*Note* all other clients, browsers, etc.. works without a problem on the same server.

### PR DESCRIPTION
**Pull request by levitte**
do_accept() checked that the peer IP address had a PTR record, and would
fail if not.  The retrieved named was then never used, even though passed
around.  All this is unnecessary, so we remove it.

Fixes #3407

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
"never used"... HA!

**Comment by levitte** [comment]
There was a fixup, reapproval needed.

**Comment by richsalz** [comment]
Reconfirmed.

**Comment by levitte** [comment]
Aargh, I'm sorry, another small fixup was needed.

**Comment by richsalz** [comment]
re-reconfirm. :)

**Comment by levitte** [comment]
Merged.

b38999240954f7ca80abbf8064cc4c87e306a3b2 apps/s_socket.c: Fix do_accept

**Pull request closed without merging**
