### PR TITLE
Check for failures in init functions.

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by kroeckx** [comment]
This is an incomplete attempt to see what needs to happen.  #1332 might be a better solution.

**Comment by levitte** [comment]
This PR is solving a different set of init checks than #1332.  I'd say they are both applicable.

**Comment by kroeckx** [comment]
It seems the ossl_init_load_crypto_strings() in #1332 still always returns 1 while the one here can be changed changed to return 0 instead after #1332 is merged.

The only real change here is that ERR_load_ERR_strings() checks that do_err_strings_init() was successful or not, and then do what is needed to make that error propagate.

#1332 should probably get merged first.

**Comment by levitte** [comment]
That works with me.

**Comment by levitte** [comment]
Now that #1332 has been merged, I propose a rebase of this and see where that gets you.  Going off for today, will return tomorrow

**Comment by kroeckx** [comment]
New version pushed

**Comment by levitte** [comment]
The Travis build breaks because of other reasons...  the fix has just been merged to master, so if you could rebase again, that would be great.

**Comment by kroeckx** [comment]
rebased

**Comment by levitte** [comment]
+1 as long as Travis and Appveyor builds are clean.

**Comment by levitte** [comment]
(it looks promising already)

**Comment by levitte** [comment]
Builds are clean.  Please ship.

**Pull request closed without merging**
