### PR TITLE
Added Perl installation instructions to NOTES-PERL.md for HPE NonStop.

### LINKED ISSUE #14931: Add installation instructions for Perl on NonStop
The `NOTES-PERL.md` file should contain instructions for installing Perl on NonStop platforms. Applies to 3.0.0.

### PR DESCRIPTION
**Pull request by rsbeckerca**
CLA: Permission is granted by the author to the OpenSSL team to use these modifications.

Fixes #14931.

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Review by mspncp — CHANGES_REQUESTED** [review]
@rsbeckerca the content looks good, but please remove the CLA declaration from your commit message.

```
CLA: Permission is granted by the author to the OpenSSL team to use these modifications.
```

Our policy states that every non-trivial contribution requires a signed CLA referring to the author's email address. Since the cla-bot did not complain, I assume this the case for the email address you are using here. 

Only trivial contributions require a CLA declaration (`CLA: trivial`), in your case it isn't necessary and just clutters the commit message. (Just imagine if every commit message would contain such a declaration).

**Comment by rsbeckerca** [comment]
My confusion. I'll amend the commit tomorrow.

**Comment by rsbeckerca** [comment]
> @rsbeckerca the content looks good, but please remove the CLA declaration from your commit message.

Done

**Review by t8m — APPROVED** [review]

**Review by mspncp — APPROVED** [review]

**Comment by mspncp** [comment]
Merged to master in 2de02e7dca0a875b1ae5b6a4a4f946705eb71edc, thank you!

**Pull request closed without merging**
