### PR TITLE
Avoid compiler complaining

### PR DESCRIPTION
**Pull request by InfoHunter**
initialize some local variables

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
gcc-4.8.4 and gcc-trunk does not warn here.
which compiler version does emit this wrong warning?

**Comment by richsalz** [comment]
merging now.

**Comment by richsalz** [comment]
clang complains.

**Comment by richsalz** [comment]
fixed, thank you!

**Comment by levitte** [comment]
Rebase?

**Pull request closed without merging**
