### PR TITLE
Fix a memory leak in RSA_padding_add_PKCS1_OAEP_mgf1

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Hope this isn't getting boring :)

### CODE REVIEW

**Comment by triska** [comment]
I find this extremely impressive. How did you find all these issues?

**Comment by bernd-edlinger** [comment]
Hi @triska 

I used error injection as follows, built everything with gcc address sanitizer,
i.e. ./config -g -fsanitize=address -fno-omit-frame-pointer
and used the Softing OPC UA C++ Server and Client Development Toolkit
as a Stress-Test application:

```
void *my_malloc(size_t s)
{
  static short x;
  if (++x)
    return malloc(s);
  return 0;
}
void *my_realloc(void*p, size_t s)
{
  static short x;
  if (++x)
    return realloc(p,s);
  return 0;
}
void my_free(void*p)
{
  free(p);
}

CRYPTO_set_mem_functions(my_malloc, my_realloc, my_free);
```

**Comment by kroeckx** [comment]
We've been talking about doing this ourself for some time, but
nobody got around to doing this. Have you tried running the test
suite with this?

**Comment by bernd-edlinger** [comment]
Test openssl test suite alone has no issues with the address sanitizer.
To produce interesting results it completes much too quickly.
The test app I used runs usually for 3-6 weeks with 100% CPU
load.  But with this kind of error injection other parts of the
software are usually also at their limits after a few hours of run time.

**Comment by kroeckx** [comment]
I'm just wondering about what kind of coverage of openssl you're
getting, or which program you're running.

**Comment by bernd-edlinger** [comment]
The OPC UA AnsiC Stack uses TLS based client/server and RSA based opc.tcp protocols.
I have tested with EC and DH crypto.
Some things like creating certificates are not covered, though.

**Comment by mattcaswell** [comment]
Ping @kroeckx. Will you merge?

**Pull request closed without merging**
