### PR TITLE
Convert uses of snprintf to BIO_snprintf

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
Reference to issue #2360 [RT3866]

**Comment by tmshort** [comment]
It backports to 1.1.0 cleanly.

**Comment by mattcaswell** [comment]
@richsalz ok for 1.1.0 backport?

**Comment by richsalz** [comment]
i will merge to master and 1.1.0 and update the commit message.

**Comment by richsalz** [comment]
6e7e171 in 1.1.0 and c41048f in master.  Thanks!

**Pull request closed without merging**
