### PR TITLE
test/prov_config_test.c: Cleanup and fix potential leaks

### LINKED ISSUE #24106: There is a memory leak defect on line 28 of the file /openssl/test/prov_config_test.c.
On line 23 of the file /openssl/test/prov_config_test.c, a pointer variable named 'ctx' is defined and dynamic memory is allocated for it through the function OSSL_LIB_CTX_new. When the if statement on line 27 returns true, the program will return on line 28. The if statement on line 27 primarily tests whether the pointer 'configfile' is available. When 'configfile' is unavailable, it is still possible for the dynamic memory area pointed to by the variable 'ctx' to be successfully allocated. However, since the program returns on line 28, the release operation on the dynamic memory area pointed to by the 'ctx' pointer on line 45 is not executed, resulting in a memory leak, as shown in the diagram below:
https://github.com/LuMingYinDetect/openssl_defects/blob/main/openssl_11.png

### PR DESCRIPTION
**Pull request by t8m**
Fixes #24106

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by nhorman** [comment]
Patch looks fine, but why are there two cancelled ci checks?

**Comment by t8m** [comment]
> Patch looks fine, but why are there two cancelled ci checks?

This was an unrelated issue with self-hosted runners.

**Review by tom-cosgrove-arm — APPROVED** [review]

**Review by nhorman — APPROVED** [review]

**Comment by t8m** [comment]
ping for @openssl/otc review

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to all the active branches. Thank you for the reviews.

**Pull request closed without merging**
