### PR TITLE
ffc: FIPS zeroization compliance

### PR DESCRIPTION
**Pull request by xnox**
Zero out params upon cleanup.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by paulidale — CHANGES_REQUESTED** [review]
These should be conditional on FIPS_MODULE.

**Comment by xnox** [comment]
> These should be conditional on FIPS_MODULE.

I see this as a privacy leak though; without fips too.

**Comment by t8m** [comment]
> > These should be conditional on FIPS_MODULE.
> 
> I see this as a privacy leak though; without fips too.

The parameters are clearly a public thing. So I cannot really see the privacy leak here. Please add the FIPS_MODULE ifdef condition.

**Review by shahsb — APPROVED** [review]

**Comment by xnox** [comment]
> > > These should be conditional on FIPS_MODULE.
> > 
> > 
> > I see this as a privacy leak though; without fips too.
> 
> The parameters are clearly a public thing. So I cannot really see the privacy leak here. Please add the FIPS_MODULE ifdef condition.

OK!

**Comment by paulidale** [comment]
Last I heard, OpenSSL's FIPS lab had not insisted that this zeroization even be done.

**Comment by xnox** [comment]
> Last I heard, OpenSSL's FIPS lab had not insisted that this zeroization even be done.

some of them are no longer active labs.....

Anyway, superseeded by https://github.com/openssl/openssl/pull/24355

**Pull request closed without merging**
