### PR TITLE
Reorder algorithm parameter to be first in *_FETCH() operations.

### PR DESCRIPTION
**Pull request by slontis**
This is part of the OPENSSL_LIBCTX API cleanup.

The order of the libctx, propq differs across many API's and should be made to be consistent..
The libctx, propq should be together after any normal parameters, but before callback parameters.
This PR just reorders the algorithm to be the first parameter.

In a few cases where the propq was missing from a fetch it has been added OR
a TODO(3.0) has been added to investigate how to add it.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t-j-h** [comment]
This really is a backwards step IMHO in terms of API consistency and makes this stuff rather inconsistent with respect to the rest of the API. We did discuss API patterns back at the OTC f2f and I know we have differing views. But a wholesale change like this requires us in my view to actually agree to API patterns and follow them. Changing this in my view makes things worse.

Hence the otc-decision hold so we can make an actual formal decision on what API pattern we want to have.

**Comment by mattcaswell** [comment]
> This really is a backwards step IMHO in terms of API consistency and makes this stuff rather inconsistent with respect to the rest of the API.

This seems to me like a big improvement. I don't understand why you think this is inconsistent with the rest of the API?

**Comment by slontis** [comment]
In isolation this change looks bad, but it is just one part of the change.

The libctx, propq are really a pair and should be together..
Some libctx related functions have the libctx at the end, some at the start, and some in the middle.
Another question that was raised, was when we need to add a 'ex2' in the future where should the libctx param be then?

**Comment by levitte** [comment]
> This really is a backwards step IMHO in terms of API consistency and makes this stuff rather inconsistent with respect to the rest of the API.

Actually not.  There are plenty of places where the library context and property query string are together, so the diverse `_fetch` functions really stuck out as inconsistent in that regard.

Also, it makes intuitive sense to have the thing you're trying to fetch as first argument, and the "where" and "how" arguments following that.

**Comment by mspncp** [comment]
See also:

- Reordering new API's that have a libctx, propq on [openssl-project](https://mta.openssl.org/pipermail/openssl-project/2020-September/002144.html)
- Inconsistent libctx awareness function parameters (#12454)

**Comment by romen** [comment]
@mspncp did you intentionally avoid to include this in the beta1 milestone?

**Comment by mspncp** [comment]
> @mspncp did you intentionally avoid to include this in the beta1 milestone?

No, I didn't. Thanks for pointing it out.

**Comment by mspncp** [comment]
> > @mspncp did you intentionally avoid to include this in the beta1 milestone?
> 
> No, I didn't. Thanks for pointing it out.

Currently, the milestone only contains the pull requests I collect from the discussion on openssl-project. I'm sure the other project members will add their pull requests as needed.

**Comment by levitte** [comment]
After some discussions last week, we found that, even though the way we've added arguments all over the place would make us think, the library context and the property query string are as tightly coupled as we imagined.  That makes the intent of this PR questionable, unfortunately :-/

See the write-up I did: https://mta.openssl.org/pipermail/openssl-project/2020-September/002160.html

**Comment by mattcaswell** [comment]
> That makes the intent of this PR questionable, unfortunately

Not at all. This is entirely consistent with the proposed policy.

**Comment by levitte** [comment]
https://github.com/openssl/web/pull/194/files#r488857352

**Comment by mattcaswell** [comment]
The policy vote on argument ordering that would have justified this change has failed, and @levitte at least now considers the intent of this to be questionable. Therefore should we close this PR?

**Pull request closed without merging**
