### PR TITLE
Add arm64 in test matrix on TravisCI.

### PR DESCRIPTION
**Pull request by zorrorffm**
Add arm64 in test matrix on TravisCI.

### CODE REVIEW

**Comment by levitte** [comment]
What's the `Change-Id:` thing?

**Comment by zorrorffm** [comment]
> 
> 
> What's the `Change-Id:` thing?

Sorry for making you confused.   Change-Id identifies commits that belong to the same review in Gerrit.  Is Change-Id not necessary for OpenSSL commit message?

**Comment by levitte** [comment]
Change-Id is utterly meaningless to us...

**Comment by zorrorffm** [comment]
> 
> 
> Change-Id is utterly meaningless to us...

Yes, it just makes me convenient to track this PR. I removed it from PR description. 

Git log shows there are some commits with Change-Id.  So what I would like to know is whether Change-Id in commit message is acceptable. If not, I would also remove it  from commit message. Thanks.

**Comment by levitte** [comment]
I don't really care, and if others have accepted it, I don't see why I should hard-headed about it.  I was just curious, sorry if it came out differently.

**Comment by levitte** [comment]
I just looked at the Travis build for this PR, and it's very much not apparent which jobs are arm64.  If there's a quick way to add something that has Travis display the architecture, I'd like to see that added in this PR.  If we determine that it's not that easy, I'd relegate that to another PR.  @zorrorffm, do you happen to know how to?

**Comment by zorrorffm** [comment]
@levitte I have no idea how to make Travis display the architecture.  For this case, I believe https://travis-ci.org/openssl/openssl/jobs/591020146 is that job ran on arm64 because only that job's CONFIG_OPTS exactly matches what I set in this PR. Also I recognize it comparing to Travis jobs for other PR.

**Comment by levitte** [comment]
Okie

**Comment by levitte** [comment]
Merged.

master:
0399aba7e05ea9bb1a58bd2e1b164f353f6ef1c9 Add arm64 in test matrix on TravisCI.

1.1.1:
5a604dfd86d0fee4f9abc257b2a81017ecc558d1 Add arm64 in test matrix on TravisCI.

**Comment by zorrorffm** [comment]
@levitte , Just let you know, TravisCi can display architecture now.  See https://travis-ci.org/openssl/openssl/builds/591020139

**Comment by levitte** [comment]
Yeah, I noticed that when looking at a build yesterday! "Ask, and you shall be answered", apparently.

**Pull request closed without merging**
