### PR TITLE
Revert "Add padding spaces before printing algo."

### PR DESCRIPTION
**Pull request by richsalz**
Some test files need to be updated.
This reverts commit 26a374a271dabd49f3fa7f43a74e05d34aca010e.
@beldmit can you give me updated test files for the cyrillic test?

### CODE REVIEW

**Comment by richsalz** [comment]
Thanks, pushed.  Leaving open since maybe we can get help on the test_x509 failure (output of the cyrillic cert)

**Comment by levitte** [comment]
I think this is the wrong fix.  The right fix would have been this:

``` diff
diff --git a/test/certs/cyrillic.msb b/test/certs/cyrillic.msb
index 87f76cb0b0..ec58ac9b2f 100644
--- a/test/certs/cyrillic.msb
+++ b/test/certs/cyrillic.msb
@@ -3,7 +3,7 @@ Certificate:
         Version: 3 (0x2)
         Serial Number:
             be:47:3c:53:a6:2a:c0:3a
-    Signature Algorithm: sha256WithRSAEncryption
+        Signature Algorithm: sha256WithRSAEncryption
         Issuer: C=RU, ST=\U041C\U043E\U0441\U043A\U0432\U0430, L=\U041C\U043E\U0441\U043A\U0432\U0430, O=\U0414\U043C\U0438\U0442\U0440\U0438\U0439 \U0411\U0435\U043B\U044F\U0432\U0441\U043A\U0438\U0439, OU=\U042F, CN=Dmitry Belyavskiy, emailAddress=beldmit@example.com
         Validity
             Not Before: Feb 21 19:35:22 2017 GMT
diff --git a/test/certs/cyrillic.utf8 b/test/certs/cyrillic.utf8
index 6eda733fa7..2096e4fb35 100644
--- a/test/certs/cyrillic.utf8
+++ b/test/certs/cyrillic.utf8
@@ -3,7 +3,7 @@ Certificate:
         Version: 3 (0x2)
         Serial Number:
             be:47:3c:53:a6:2a:c0:3a
-    Signature Algorithm: sha256WithRSAEncryption
+        Signature Algorithm: sha256WithRSAEncryption
         Issuer: C=RU, ST=Москва, L=Москва, O=Дмитрий Белявский, OU=Я, CN=Dmitry Belyavskiy, emailAddress=beldmit@example.com
         Validity
             Not Before: Feb 21 19:35:22 2017 GMT
```

**Comment by richsalz** [comment]
I tried that and had utf8/output errors.  Maybe it was pilot error.  I'll try that later and push to this PR if it works.  Thank you!

**Comment by levitte** [comment]
I just tried it.  Worked like a charm.

I just noticed, btw, that a similar change is needed for the CRL output.  I'm lining up a PR as we speak.

**Comment by richsalz** [comment]
Great, thanks for picking this up.  I'll close this PR now.

**Pull request closed without merging**
