### PR TITLE
apps: fix AES CBC performance loop

### PR DESCRIPTION
**Pull request by paulidale**
Looks like an oops in the recent refactoring of the speed app.

### CODE REVIEW

**Comment by paulidale** [comment]
Alternative to #14777

**Review by t8m — APPROVED** [review]

**Review by xffbai — COMMENTED** [review]
seems same oops on line 2117?

**Comment by paulidale** [comment]
Thanks good catch.  I'd not checked for other instances.  The fix for Camellia is in #14786

**Comment by paulidale** [comment]
Merged to master.

**Comment by xffbai** [comment]
hi @paulidale , looks like this pr was not merged to master. It was 14777 merged in  (https://github.com/openssl/openssl/commit/bec9289143c955b330a8f9ad32f26f3da76e2685)

**Comment by paulidale** [comment]
@xffbai thanks for the heads up, I made a mistake merging somewhere.  I'll revert this and merge the proper fix.

**Comment by paulidale** [comment]
Revert in #14796

**Pull request closed without merging**
