### PR TITLE
Fix Configure death handler

### PR DESCRIPTION
**Pull request by levitte**
A couple of details weren't quite right.

### CODE REVIEW

**Comment by richsalz** [comment]
I applied the patch and it still doesn't work.

**Comment by levitte** [comment]
Well, uhmmm, I didn't really expect it to.  However, this change makes Configure play nicer with Carp::Always, which can then help writing stack traces any time die is called, and thereby maybe help us figure out what your issue is.

For everyone else listening, this is related to [this discussion on openssl-project](https://mta.openssl.org/pipermail/openssl-project/2018-July/000914.html)

**Review by richsalz — APPROVED** [review]
Fixes my breakage. :)

**Comment by levitte** [comment]
... which, incidently, wasn't a breakage at all, just [ahem] rogue output ;-)

**Comment by levitte** [comment]
Merged.

master / 1.1.1:
eb807d5383fd228a5c4cf9afc2fec487e0d22cee Configure death handler: instead of printing directly, amend the message
88accfe6dccf904fec5a17db4a59cd2c4c480382 Configure death handler: remember to call original death handler
1a6c30029802179ebe0ec1eedfdc9d78bb6dc4dd Configure death handler: bail out early when run in eval block

1.1.0:
36e732b00c8a22d50f88ee59d8790d5667ff72e2 Configure death handler: instead of printing directly, amend the message
f65389acaad600e816dcd9c231ea70d505d027a4 Configure death handler: remember to call original death handler
64eae7475e6caa669cd6369770ba4853ecaff8d1 Configure death handler: bail out early when run in eval block

**Pull request closed without merging**
