### PR TITLE
Fix memory leak in d2i_ASN1_OBJECT.

### LINKED ISSUE #14667: d2i_ASN1_OBJECT leaks the 'sn' and 'ln' fields of ASN1_OBJECT
If a program creates an `ASN1_OBJECT` using `ASN1_OBJECT_create`, the resulting object will have dynamically allocated `sn` and `ln` fields.  If the program then calls `d2i_ASN1_OBJECT` to repopulate that same object with a new object identifier, the dynamically allocated fields will be leaked:

```
// Exercise the bug 'leak_sn_and_ln' in 'c2i_ASN1_OBJECT'.
void leak_sn_and_ln()
{
  // Make my own object representing the 'countryName' OID.
  //
  // This creates an object that owns dynamically allocated 'sn' and
  // 'ln' fields.
  ASN1_OBJECT *o =
    ASN1_OBJECT_create(NID_undef, derC+2, sizeof(derC)-2, "C", "countryName");
  print_ASN1_OBJECT(o);

  // Now parse something, reusing 'o'.
  //
  // This does not free the dynamically allocated 'sn' and 'ln' fields,
  // instead simply overwriting them with NULL.
  unsigned char const *p = der1234567;
  CHECK_NZ(d2i_ASN1_OBJECT(&o, &p, sizeof(der1234567)));
  print_ASN1_OBJECT(o);

  // This frees the new object, but the old 'sn' and 'ln' are already
  // lost.
  ASN1_OBJECT_free(o);
}
```

I have attached a complete program [leak_sn_and_ln.c.txt](https://github.com/openssl/openssl/files/6192646/leak_sn_and_ln.c.txt) demonstrating the leak (attached as text because GitHub insisted; remove ".txt" extension).  When run, it prints:

```
$ leak_sn_and_ln.exe
countryName
1.2.3.4.5.6.7
[21:34:28]     6 file=crypto/objects/obj_lib.c, line=44, thread=15280, number=12, address=0x1441930
[21:34:28]     7 file=crypto/objects/obj_lib.c, line=47, thread=15280, number=2, address=0x14419b0
14 bytes leaked in 2 chunks
no_leaks: 0
```

The leak printouts require that OpenSSL be configured with the `enable-crypto-mdebug` flag before building.

Relatedly, the source code of `c2i_ASN1_OBJECT` contains this incorrect comment:

```
    /*
     * only the ASN1_OBJECTs from the 'table' will have values for ->sn or
     * ->ln
     */
```

This isn't true since, as demonstrated, `ASN1_OBJECT_create` creates an object that is not part of the predefined OID table (`nid_objs`) but has non-NULL `sn` and `ln` fields.

I have observed this behavior with OpenSSL 1.1.1b and 1.1.1j running on Windows 10, built from source.

### PR DESCRIPTION
**Pull request by slontis**
Fixes #14667

Added fix supplied by @levitte in PR #14938
Reworked test supplied by @smcpeak into a unit test.

Tested via valgrind before and after the fix was added.

@levitte I just created a separate PR that was based against master branch (not 111).

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Are you saying we should not have the test in 1.1.1?

**Comment by slontis** [comment]
> Are you saying we should not have the test in 1.1.1?

I don't mind either way... Kill this PR and add the test to your PR if you want.

**Comment by levitte** [comment]
> Kill this PR and add the test to your PR if you want.

Okie.

**Comment by levitte** [comment]
Now cherry-picked.  Thanks for coding that test!

**Comment by slontis** [comment]
Thanks @smcpeak for supplying a testcase - it makes it much easier to add a test when someone goes to the trouble of doing that..

**Comment by smcpeak** [comment]
You're welcome!

**Pull request closed without merging**
