### PR TITLE
test: add a default greeting to avoid printing a null pointer.

### PR DESCRIPTION
**Pull request by paulidale**
urgent: unit test breaking fix

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Was this a new test? Or is it a side effect from another change?

**Comment by paulidale** [comment]
It smells like an optimising compiler got a bit cleverer.  Early failure in that chain of if or if or if will leave the pointer null.  I didn't see any recent changes to the file in question when I looked.

**Review by slontis — APPROVED** [review]

**Comment by slontis** [comment]
Agree to urgent

**Comment by InfoHunter** [comment]
It seems `-Werror=format-overflow` becomes more aggressive than before. Printing a NULL sounds no real harm to format-overflow?

**Review by InfoHunter — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the quick reviews.

**Comment by t8m** [comment]
I've merged this to all the active branches as the CI error is there as well.

**Comment by paulidale** [comment]
Thanks @t8m.  I didn't check older branches.

**Pull request closed without merging**
