### PR TITLE
`check-format-commit.sh`: make `awk` patterns more robust; further improvements

### PR DESCRIPTION
**Pull request by DDvO**
for use with MacOS and certain flavours of Linux.

As briefly discussed at https://github.com/openssl/openssl/pull/24806#issuecomment-2403300718,
the nice new tool had trouble on certain systems where `awk` is unhappy with unescaped '`+`' symbols appearing in patterns.

On MacOS, I got
```
awk: illegal primary in regular expression +{3} at {3}
 source line number 3
 context is
	    >>>  /+{3}/ <<< 
This commit has no files that require checking
```
This can be fixed by escaping the two occurrences of '`+`' in patterns within the script with a backslash: '`\+`' .

Interestingly, even on my Ubuntu and Debian Linux systems, I got
```
awk: line 3: regular expression compile failed (missing operand)
+{3}
awk: line 8: regular expression compile failed (missing operand)
+
```
There, for whatever reason, after escaping the  '`+`' in patterns in the same way, 
I just got
```
This commit has no files that require checking
```
for whatever (commit range) parameters I tried, including ones that do have formatting nits that normally are shown.
So the tool did not exit with error but did not call `check-format.pl` at all and thus not show any findings.

Both issues are fixed by the first commit this PR,
which also prevents failure in case the source files happen to contain `+++` or `@@`.

### CODE REVIEW

**Review by nhorman — DISMISSED** [review]

**Comment by DDvO** [comment]
I meanwhile had a full look at the new script and suggest further minor improvements, 
including simplifications, example invocations, and fixes in comment texts.

Moreover, allow for empty commit range (no parameter), 
which is taken as the list of currently unstaged changes (like `git diff`),
which can be very handy during development (before committing).

Hope you don't mind that I piggy-back this on the existing PR?

**Review by nhorman — APPROVED** [review]

**Comment by nhorman** [comment]
I'm fine with the piggy-back

CI errors look unrelated

**Comment by DDvO** [comment]
Ping for 2nd review/approval

**Comment by DDvO** [comment]
Thanks for the approvals - merged to all active branches.

**Pull request closed without merging**
