### PR TITLE
X509_CRL_digest() - ensure precomputed sha1 hash before returning it

### LINKED ISSUE #2313: Perl Net-SSLeay testsuite failure in X509_CRL_digest
I've just been pointed to:
https://rt.cpan.org/Public/Bug/Display.html?id=120006 and https://bugs.debian.org/852920

Can someone take a look at this? @levitte?

### PR DESCRIPTION
**Pull request by levitte**
X509_CRL_digest() didn't check if the precomputed sha1 hash was actually
present.  This also makes sure there's an appropriate flag to check.

##### Checklist

- [x] tests are added or updated

Fixes #2313

### CODE REVIEW

**Comment by kroeckx** [comment]
Could you also document that EXFLAG_SET means it cached things?

**Comment by levitte** [comment]
Are you satisfied by the comment I just committed?

**Comment by kroeckx** [comment]
Yes

**Comment by levitte** [comment]
Cool.

I just added a test as well

**Comment by levitte** [comment]
@richsalz, I think I do have a CLA registered already ;-)

**Comment by richsalz** [comment]
I am playing with the CLA webhook to see if I can automatically set/remove the label.  Not working yet :(

**Review by kroeckx — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

master: 6195848b2eea627c47f74b63eb2ba3dc3d5b6436..929860d0e6112f5c7766d9ea036c3f8bd8d3d719
1.1.0: b431b094330da3e54805c49fb262192e34bc3864..b649ffcaea38864270ad6c2362ed0ef639749707

**Pull request closed without merging**
