### PR TITLE
replace 'unsigned const char' with 'const unsigned char'

### PR DESCRIPTION
**Pull request by patrickdepinguin**
The openssl code base has only a few occurrences of 'unsigned const char'
(15 occurrences), compared to the more common 'const unsigned char' (4420
occurrences).

While the former is not illegal C, mixing the 'const' keyword (a 'type
qualifier') in between 'unsigned' and 'char' (both 'type specifiers') is a
bit odd.

The background for writing this patch is not to be pedantic, but because
the 'opmock' program (used to mock headers for unit tests) does not accept
the 'unsigned const char' construct. While this definitely is a bug in
opmock or one of its dependencies, openssl is the only piece of software we
are using in combination with opmock that has this construct.

CLA: trivial

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Approved. I agree this is trivial

**Review by mspncp — APPROVED** [review]
I agree that it's a trivial change (in the legal sense).

And compliments to your excellent commit message, including the rationale :-)

**Comment by patrickdepinguin** [comment]
> And compliments to your excellent commit message, including the rationale :-)

Thanks :-)

**Comment by romen** [comment]
> And compliments to your excellent commit message, including the rationale :-)

Ditto!

**Review by romen — APPROVED** [review]
LGTM

**Comment by romen** [comment]
Merged to `master` with:

- 6d4313f03e *replace 'unsigned const char' with 'const unsigned char'*

Thanks and congratulations @patrickdepinguin  for your first merged contribution to the project!

**Pull request closed without merging**
