### PR TITLE
Do not eat trailing '\n' in BIO_gets for fd BIO.

### LINKED ISSUE #1921: fd_gets() in crypto/bio/bio_fd.c eats \n
Originally the issue comes from https://github.com/fedora-infra/fedmsg/pull/389. When trying to read
[easy_rsa.pem](https://github.com/openssl/openssl/files/590127/easy_rsa.pem.txt) with this program:
```c
/* build with
 * gcc -Wall -o test-load_cert -lssl -lcrypto $<
 */
#include <fcntl.h>
#include <openssl/bio.h>
#include <openssl/err.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>

int main(void)
{
    X509 *cptr = NULL;

    // BIO *bio = BIO_new_fd(open("/tmp/easy_rsa.pem", O_RDONLY), BIO_NOCLOSE);
    BIO *bio = BIO_new_fp(fdopen(open("/tmp/easy_rsa.pem", O_RDONLY), "rb"), BIO_NOCLOSE);
    cptr = PEM_read_bio_X509(bio, NULL, 0, NULL);
    if (cptr == NULL) {
        printf("Troubles!\n");
        ERR_print_errors_fp(stderr);
    }
    
    printf("I got %s\n", cptr);
    BIO_free(bio);
    return 0;
}
```
everything works perfectly fine. However, when switching two lines creating ``bio`` (from ``BIO_new_fp`` to ``BIO_new_fd``) I get ``NULL`` in ``cptr``.

According to @t8m , the problem lies in ``fd_gets()`` which eats ``\n``, so the read breaks on the empty line below ``serial:....`` line.

### PR DESCRIPTION
**Pull request by t8m**
##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated
- [x] CLA is signed

##### Description of change
Fixes #1921

### CODE REVIEW

**Comment by kaduk** [comment]
It seems that the behavior of BIO_gets() with respect to retaining the trailing newline should be documented in BIO_read.pod.

**Comment by levitte** [comment]
> It seems that the behavior of BIO_gets() with respect to retaining the trailing newline should be documented in BIO_read.pod.

True.  Are you saying it should be part of this PR?

**Comment by richsalz** [comment]
Yes.  Fixing code should update the docs and ideally include tests.

**Comment by kaduk** [comment]
> > It seems that the behavior of BIO_gets() with respect to retaining the trailing newline should be documented in BIO_read.pod.

> True. Are you saying it should be part of this PR?

That was my intention, yes.

**Comment by t8m** [comment]
I've included the docfix already.

**Comment by mattcaswell** [comment]
What branches are you targetting for this? It strikes me that this could be a breaking change for applications that expect the old behaviour.

**Comment by t8m** [comment]
It is your decision, although I'd prefer to see it at least in 1.1.0. However I see it as a pure bugfix - for example you cannot load a PEM certificate from a file containing empty lines over a fd BIO without this bugfix. And all the other BIOs work this way if they implement BIO_gets at all.

**Comment by richsalz** [comment]
The fact that all other BIO's do this, makes it seem like a bugfix to me too.

**Comment by richsalz** [comment]
But perhaps it's worth a note in the CHANGES file.

**Comment by mattcaswell** [comment]
I think I'd like a broader opinion on the advisability of this. We have been burnt before by "fixing" broken behaviour (e.g. commit 4880672), only to find people were relying on the old behaviour and the fix broke more stuff than it solved.

**Comment by levitte** [comment]
@mattcaswell, I'm trying to understand your reasoning...  unless I'm off track, this is about `BIO_gets()` behaving inconsistently, you sorta *have* to know what the back end is.  Yes, the code that knows exactly what backend is used will know what to expect.  But what should code that doesn't know exactly which backend is used expect?  So what makes more sense, keeping a `BIO_gets()` that's inconsistent (unless you know exactly what backend is used) or not?

**Comment by t8m** [comment]
If you're concerned about existing releases, ok, but please merge it at least into master.

**Comment by mattcaswell** [comment]
> @mattcaswell, I'm trying to understand your reasoning... unless I'm off track, this is about BIO_gets() behaving inconsistently, you sorta have to know what the back end is. Yes, the code that knows exactly what backend is used will know what to expect. But what should code that doesn't know exactly which backend is used expect? So what makes more sense, keeping a BIO_gets() that's inconsistent (unless you know exactly what backend is used) or not?

I'm thinking of all the applications that know they are using an fd BIO and call BIO_gets() on it. They will have been coded to work according to the way that specific implementation of BIO_gets() works. We are now talking about changing that, which could break those applications.

I am not saying that it makes sense to have this inconsistent behaviour - only that the fix for the inconsistency could break things. If we break more stuff than we fix with this change you have to consider whether it is advisable.

I'm also not saying that I am against this change. Only that I am worried about the impact.

**Comment by vdukhovni** [comment]
A change of behaviour in this space would require a new function.  BIO_fgets() comes to mind.  I don't thik we're at liberty to change the semantics of BIO_gets() after all these years.

**Comment by richsalz** [comment]
The semantics are "BIO_gets deletes the newline except for descriptor-based BIO's." I suppose discussion on the mailing lists is needed.

**Comment by vdukhovni** [comment]
I don't think the mailing lists get to trump compatibility requirements.  We need to minimize/avoid incompatible changes that delay or prevent upgrades of OpenSSL in O/S distributions.  If we change an interface we rename the function, and retain the old one alongside for compatibility.

**Comment by t8m** [comment]
No, the semantics are BIO_gets does not delete the newline except for fd BIO.

**Comment by t8m** [comment]
@vdukhovni This is a misunderstanding. There is no consistent semantics but apparently the existing users of BIOs in openssl except BIO_gets to not delete the newline. The fd BIO based BIO_gets() is never used in openssl code itself though.

**Comment by vdukhovni** [comment]
I made no mention of "consistency" (across backends). The "semantics" is the current behaviour. BIO_gets() does what it has always done, and changing that incompatibly requirs a new function, e.g. BIO_fgets(), which can be documented to behave consistently.

**Comment by levitte** [comment]
So, I guess it comes down to one question: is the current (mis)behavour a bug or is it not?

**Comment by vdukhovni** [comment]
The current behaviour is perhaps a design error, but that's moot. By now, there are surely applications that depend on that current behaviour, so we can't change it. Some design bugs become features.

**Comment by mattcaswell** [comment]
> So, I guess it comes down to one question: is the current (mis)behavour a bug or is it not?

Either behaviour (i.e. eating the `\n` or not) could be reasonable. It was probably originally an accident that fd BIO was implemented differently. You could argue that had that been caught shortly after it was written, then it was a bug. However, due to the passage of time, the behaviour as implemented is the de-facto semantics of the function....so its now no longer a bug! However horrible that is!

**Comment by t8m** [comment]
No, it is rather an indication that nobody really uses fd based BIO in combination with BIO_gets() call or particularly with PEM_read_bio.... Unless all the calls to BIO_gets() within openssl are replaced with the new proposed BIO_fgets() then you're basically saying that PEM_read_bio... should stay broken with fd based BIO.

**Comment by mattcaswell** [comment]
> No, it is rather an indication that nobody really uses fd based BIO in combination with BIO_gets() call or particularly with PEM_read_bio.... Unless all the calls to BIO_gets() within openssl are replaced with the new proposed BIO_fgets() then you're basically saying that PEM_read_bio... should stay broken with fd based BIO.

Or PEM_read_bio() is "fixed" to strip trailing `\n` if they exist.

**Comment by t8m** [comment]
I am not interested in further arguments (and implementing any new "consistent" call, that is.) You can close this request.

**Comment by t8m** [comment]
BTW, PEM_read_bio already strips. That's not the fix.

**Comment by levitte** [comment]
I'd like to see this fix at least in master.  Can this be done?

**Comment by mattcaswell** [comment]
> I'd like to see this fix at least in master. Can this be done?

Well master is 1.1.1 which is supposed to be ABI compatible with 1.1.0. This is a non-compatible change. It could (potentially) go in a future 1.2.0 if we agreed that the subsequent break to applications was worth it.

**Comment by t8m** [comment]
There is probably 0 applications that would be broken by the fix. But I hope you'll be as careful with all other subtle behavior changes in future as with this one. :)

**Comment by vdukhovni** [comment]
Neither we, nor O/S distributions can test every possible application to determine how close to `0` that number is. We need to allow distributions to upgrade without breaking applications. This means retaining compatible behaviour to the maximal extent possible.  Where a current interface is deficient, it means introducing a new, better interface.

**Comment by levitte** [comment]
@vdukhovni, I agree with you to some extent.  Taking that line of thinking down to bug compatibility is taking it a bit far, though...  out of proportion, even...  in my opinion.

**Comment by vdukhovni** [comment]
> @levitte , I agree with you to some extent. Taking that line of thinking down to bug compatibility is taking it a bit far, though... out of proportion, even... in my opinion.

Nobody gets to benefit from our bug fixes when it becomes very difficult or impossible for O/S distributions to ship our updated software. We need to take compatibility requirements very seriously.  Compatibility is more important than fixing minor imperfections, if we get compatibility right, then the major improvements that don't break compatibility get used.

Note that it is better to break source compatibility by removing/renaming functions than to break run-time compatibility by changing how functions behave internally, while presenting the appearance of a stable interface.

If we introduce BIO_fgets() and document BIO_gets() as deprecated, we could remove the latter a few releases down the road.

**Comment by levitte** [comment]
@t8m:
> The fd BIO based BIO_gets() is never used in openssl code itself though.

Actually, this isn't entirely true.  It's used in `apps/apps.c`'s `app_get_pass()` when the password source is `fd:n` (for any arbitrary `n`).  However, the resulting BIO is wrapped with a `BIO_f_buffer`, because back in the days when `app_get_pass()` was implemented, the `BIO_s_fd()` method didn't define a `gets` function, the wrapping it with the buffering filter BIO was the recommended way to get around that.

**Comment by kaduk** [comment]
So, the moral of the story is that historic OpenSSL didn't have enough unit tests?

**Comment by levitte** [comment]
You could argue that, although in this case, it wouldn't have made a difference...

**Comment by levitte** [comment]
...  or, well, yeah, you're entirely correct.

**Comment by levitte** [comment]
@mattcaswell, @vdukhovni, @richsalz ...  have you noticed the following in `doc/man3/BIO_s_fd.pod`?

```
BIO_puts() is supported but BIO_gets() is not.
```

and further, in `doc/man3/BIO_read.pod`:

```
If the BIO_gets() function is not supported by a BIO then it possible to
work around this by adding a buffering BIO L<BIO_f_buffer(3)>
to the chain.
```

**Comment by richsalz** [comment]
so @team, what are we goign to do with this?

**Comment by levitte** [comment]
I've made my approval.  I'll leave it to someone else to make the final decision.

**Comment by t-j-h** [comment]
My view is that the fd BIO eating the \n is a bug and it should be fixed. Having an API where the different implementations of the API in the code base behave differently for this sort of thing is simply a bug. It isn't documented clearly - but the concept in the original code was to be modeled off fgets - that is where it came from. It should go in master and the behaviour change should be noted - i.e. the doc should read as clearly as fgets does - and it should note that prior versions of the FD bio did not have these semantics.

**Comment by levitte** [comment]
So, err, your reason to close this, @t-j-h?

**Comment by t8m** [comment]
Github closed it automatically because I moved the commits to a different branch in my forked repository. I can open a new pull request if you want.

**Comment by levitte** [comment]
Ah.  Yeah, if you want the new branch to go in, a pull request will be needed.  To avoid rehashing the same discussion, I suggest you refer to this pull request in the new one.

**Comment by t-j-h** [comment]
I didn't close it - @t8m did ... I'm arguing for unclosing it and sorting it out.

**Comment by levitte** [comment]
Yeah, sorry, I misread who had closed it.  It got re-opened as #3442

**Pull request closed without merging**
