### PR TITLE
Move bn and evp test programs input data to their respective data dir

### PR DESCRIPTION
**Pull request by levitte**
Cosmetic that makes it clearer what files belong with what tests.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
are you planning to do this for all tests?  that have data files?  i find this more inconvenient -- if a test gets moved (from 30 to 5, e.g.) what about the datafiles?

**Comment by levitte** [comment]
```
git mv test/recipes/30-test_foo.t test/recipes/05-test_foo.t
git mv test/recipes/30-test_foo_data test/recipes/05-test_foo_data
git commit
```

Doesn't look too hard, does it?
In the long run, yes, I'd like test specific data files to end up in these data directories, for grouping purposes.  For now, I've concentrated on new files that are appearing and that are fairly easy to move around.

**Comment by richsalz** [comment]
I know what *has* to be done to move files.  I just don't think this is useful.  Could we get the number out of the subdir name?

**Comment by richsalz** [comment]
For example, I do this a lot:
```
./test/evp_test test/evp*.txt
```
Now I have to remember full name of the EVP test.  At least this seems more defensible to me:
```
./test/evp_test ./test/data/evp_test/*
./test/evp_test ./data/evp_test/*
```
(Second one is better as testdata is truly a portable directory, not a mix of data and exe files :)

**Comment by levitte** [comment]
So essentially, you're not compelled by the idea of grouping stuff around the test recipes.  Sorry to hear that, that's the whole idea with this data dir (it came about in 6c6a2ae6fc964795304bbe7687e42b2b0cdf81b3)

**Comment by richsalz** [comment]
I'm not not compelled. :)  I think requiring the test# is wrong and makes it hard to run individual tests.

**Comment by levitte** [comment]
The "test#"?

**Comment by levitte** [comment]
To take it from the other end, are you telling me that the *existing* data dirs is wrong?

```
: ; ls -d test/recipes/*_data
test/recipes/04-test_pem_data      test/recipes/95-test_external_krb5_data
test/recipes/15-test_ecparam_data  test/recipes/95-test_external_pyca_data
```

If not, what's the difference between those and this, in your mind?

**Comment by richsalz** [comment]
I don't like it but didn't notice those.  These are tests I am using daily. :)  Why not just a single PR that moves everything?

**Comment by richsalz** [comment]
And note, this is just commentary:  I'm not plus or minus one on this

**Comment by levitte** [comment]
> Why not just a single PR that moves everything?

Some are more complex, and I think (but haven't verified) that some are shared among several recipes.  So it's a little like the conversion of test programs to use the C test framework; one at a time, gradually.

**Comment by dot-asm** [comment]
> For example, I do this a lot: `./test/evp_test test/evp*.txt`

And I occasionally have to do some jumping through hoops to run tests on systems that don't even have shell you can pass wild char to, let alone perl... Moving evp input files (actually even splitting) is a setback. Why evp_test is different? [Well, it's obvious how it's different from things like external tests, which are simply not interesting on non-Linux systems]. Because it tests more or less everything, ciphers, hashes and indirectly bignums. It's first thing you test on cross-compile target that doesn't have the usual things most people take for granted. And if it fails, even more hoops [in comparison to which other input files tucked some strange places is smaller obstacle] ...

**Comment by dot-asm** [comment]
Oops, wrong button! Sorry!

**Comment by richsalz** [comment]
i'll approve once you resolve the conflicts :)

**Comment by levitte** [comment]
Okie.  Wait for the builds

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
Merged.  c537e74ba32e28d747d8e747abfa6cfff75c44c1

**Pull request closed without merging**
