### PR TITLE
Fix openssl mac and documentation

### LINKED ISSUE #19227: Strange behavior in openssl mac (or bad documentation)
The man page for openssl-mac says the following about input:

```
       -in filename
           Input filename to calculate a MAC for, or standard input by default.  Standard input is used if the filename is '-'.  Files are expected to be in binary format, standard input uses hexadecimal text format.
```

However, when trying to pass in hexadecimal text through standard input, I don't get the same result as when I give it a file with binary format.

With binary file:
```
$ echo "00112233445566778899aabbccddeeff" | xxd -r -p > tmp.bin
$ openssl mac -cipher AES-128-CBC -macopt hexkey:00000000000000000000000000000000 -in tmp.bin CMAC
BD71DBE9D210A18355D7468BE38E5A3C
```

With binary input:
```
$ echo "00112233445566778899aabbccddeeff" | xxd -r -p | openssl mac -cipher AES-128-CBC -macopt hexkey:00000000000000000000000000000000 -in - CMAC
BD71DBE9D210A18355D7468BE38E5A3C
```

With hexadecimal text input:
```
$ echo "00112233445566778899aabbccddeeff" | openssl mac -cipher AES-128-CBC -macopt hexkey:00000000000000000000000000000000 -in - CMAC
57A65C246ED1AEA5278BD9022D17BAE7
```

Have I misunderstood the documentation, is the documentation wrong, or is this a bug?

Version used: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

### PR DESCRIPTION
**Pull request by patriksevallius**
Fixes #19227

The documentation incorrectly said stdin should be hexadecimal. Code incorrectly switched to FORMAT_TEXT when using stdin.
Documentation and code updated to reflect reality.

##### Checklist
- [x] documentation is added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
Okay with CLA: trivial

There's a typo in one of the commit messages:

 > Update documentation, standard input is expected to be in binary formwqat too

I think CLA: trivial needs to be in both commit messages.

**Comment by patriksevallius** [comment]
Typo fixed, CLA added.

**Review by levitte — APPROVED** [review]
Agree trivial

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

**Comment by hlandau** [comment]
Merged to master and 3.0. Thank you.

**Pull request closed without merging**
