### PR TITLE
ERR: Add a missing common reason string

### PR DESCRIPTION
**Pull request by levitte**
There was no string present for ERR_R_PASSED_INVALID_ARGUMENT

### CODE REVIEW

**Comment by DDvO** [comment]
This addition is incomplete and meanwhile superseded by the improved #17056.

**Comment by levitte** [comment]
> This addition is incomplete and meanwhile superseded by the improved #17056.

Before closing, I want to double check the state of 1.1.1, which this PR targets as well

**Review by DDvO — APPROVED** [review]
Good to backport #17056 to 1.1.1 in this (reduced) form.

**Comment by DDvO** [comment]
Pushed to 1.1.1 - thanks @levitte

**Pull request closed without merging**
