### PR TITLE
CI: Replace windows-2016 with windows-2022

### LINKED ISSUE #17177: windows-2016 Github Actions environment is being removed
According to [this](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/) blog post the windows-2016 Github Actions environment is being removed on 2022--03-15. We have a few references to that environment in our current Github setup. In particular in .github/workflows/windows.yml and .github/workflows/os-zoo.yml.

We should update our setup to remove references to that environment before that date.

### PR DESCRIPTION
**Pull request by t8m**
Windows 2016 environment is going to be discontinued.

Fixes #17177

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by h-vetinari** [comment]
I would consider moving only to windows-2019, as windows-2022 (the image) is still in [beta](https://github.com/actions/virtual-environments#available-environments) & very recent. It's not that I worry that thing wouldn't work, but they might work _too well_ in the sense that using windows-2022 in CI might obscure errors that would occur on windows-2019, effectively being an even larger increase of the required minimal compiler version.

**Comment by h-vetinari** [comment]
> windows-latest is windows-2019 AFAIK.

Yes, _currently_. It will change at some point in the future, and by using `-latest` you'll have no influence or visibility on that.

Beyond that, this PR doesn't use `windows-latest`, but `windows-2022` directly.

For both of those reasons, I'd say the only reasonable option is `windows-2019`, which doesn't change unexpectedly, and is a much more reasonable (effective) lower bound than a cutting edge, beta-version compiler.

PS. The same argument could obviously be made for 3.0 & master as well, but I just stumbled over this PR and thought I'd comment.

**Comment by t8m** [comment]
If anything, we should explicitly do windows-2019 and windows-2022.

**Comment by t8m** [comment]
Needs to be merged only after #17234

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to 1.1.1. Thank you for the reviews.

**Pull request closed without merging**
