### PR TITLE
Fix potential null pointer dereference in ARIA implementation

### PR DESCRIPTION
**Pull request by jon-oracle**
Fixed null pointer deference.

### CODE REVIEW

**Comment by paulidale** [comment]
Merged, thanks.

**Comment by dot-asm** [comment]
Subject is actually misleading, because key->rd_key is not dereference. It could as well be an `(ARIA_u128 *)key`. But that's not what I'd like to discuss. Question is why check for key being NULL at all? I dare to assert that this check is nothing but a copy-paste artefact from elsewhere, e.g. aes_core.c (which in turn can also be a copy-paste artefact). In other words question is not really "why in aria.c", but it's more general. One might still argue that check might be meaningful in set_key, but it definitely makes no sense in aria_encrypt. One can wonder if *any* of NULL checks are sensible in aria_encrypt. Well, one might argue that check for `in == NULL && out == NULL` (`&&` is not typo!) can be meaningful. But other than that it's either programmer's mistake (i.e. caller should be held responsible), or sign of memory corruption (in which case application can as well just crash already).

**Comment by t-j-h** [comment]
It is a style issue. You either like checking for simple NULLs or you don't. The coding style is silent on the topic. And team member views differ. I for one check for that simple normal context always. Rich never checks. It is a choice. And the code should be consistent - which it wasn't. And the author was happy with the update (as am I).

**Comment by dot-asm** [comment]
> It is a style issue. You either like checking for simple NULLs or you don't.

And my question is if this is right/appropriate/adequate. To leave it to matter of like-ness that is. As a practical example. aria_encrypt doesn't return value. And caller has no way of telling if it actually did something. And in such case passing buf, buf, NULL would make caller conclude that buf is encrypted. But this conclusion has *catastrophic* consequences, specifically *more* catastrophic than crashing application.

> The coding style is silent on the topic.

Is it carved in stone of something? It being silent about something doesn't mean that it can't be discussed and/or all bets are off. Because you can't always formulate rule that covers all cases. Besides, I'm not even sure that this matter belongs in *style* guide.

**Comment by dot-asm** [comment]
> It being silent about something doesn't mean that it can't be discussed

This is too weak statement. Mere *presence* of style guide doesn't mean that its content can't be discussed. I rather meant that can one really dismiss somebody else's argument with "style guide is silent about it"? You rather do it with *own* arguments as "style guide is silent, so I'm going to be". And once again, I'd argue that this can't be matter of style, because it's not about formatting or readability, but about things actually happening or not. Wouldn't it be appropriate to say that *style* is about something that doesn't affect actual *functionality*. Style is really about readability, and when we speak of readability we actually speak about *humans*. While what we discussing here is actually what *computer* does.

**Comment by levitte** [comment]
I'm confused...  `key->rd_key` is a dereference of the pointer `key`, surely?

Anyway, *since we have* a check that `key` is a valid pointer, it certainly looks like a programming error to try to use it before the check, no?  Kinda counter intuitive...

**Comment by dot-asm** [comment]
> key->rd_key is a dereference of the pointer key

Well, "dereference" is kind of slippery term. But in the context, more specifically with suggestion key->rd_key would cause SEGV (or equivalent of) if key is NULL, "dereference" is viewed as "reaching out for data pointer points to". And key->rd_key doesn't reach for any data, it simply adjust pointer with offset of rd_key[] within the structure. Offset is zero here, that why I wrote that it could as well be simple cast.

> Anyway, since we have a check that key is a valid pointer, it certainly looks like a programming error to try to use it before the check, no?

And my remark was about *subject* of commit message being misleading. In other words I'm not saying that modification itself was unjustified. It's fine, it improves readability. What I said is that *subject* creates wrong impression, because there was no risk of SEGV. And *then* I questioned legitimacy of NULL checks in this and other similar cases.

**Comment by t-j-h** [comment]
I argued for NULL checks on all pointers on all user accessible functions. Views varied. So it didn't go in one way or the other. That's how we have a style that is a consensus approach - where there were strong views in either direction it got left out. Happy to revisit but the views won't have changed and it will come down to voting on a pile of style things if we want to select a single approach. The style has been out long enough another round up updates is probably prudent.

**Comment by dot-asm** [comment]
> all user accessible functions

BTW, ARIA is not user accessible. aes_core.c is, but I'd still argue that pointer sanity should caller's responsibility.

> we have a style that is a consensus approach

... on STYLE. I.e. how do we lay down code to make it more readable, not what to do. And by "what to do" I mean code that actually affects binary [in a meaningful way].

**Comment by dot-asm** [comment]
>> we have a style that is a consensus approach

> ... on STYLE.

Quiting: "Coding style is *all* about readability and maintainability" [emphasis is mine].

**Comment by paulidale** [comment]
I'm with @levitte here, this PR fixes a bug in the code.  The sequence:
```
x->blah
if (x == NULL) ...
```

[can and will be optimised](http://blog.llvm.org/2011/05/what-every-c-programmer-should-know_14.html) to:
```
x->blah
```

The NULL check is there at the moment and it should work.

**Comment by dot-asm** [comment]
Once again, *here* key->rd_key does not reach out for memory, there is no instruction generated that would trigger SEGV. If you don't find reference to cast compelling, consider that it's equivalent of `&key->rd_key[0]`. You argue that it might confuse optimizer to the level when it optimizes the check away. It might, I don't know, and don't have to know, because, once again, I do *not* question legitimacy of *this* modification, only the subject line. Well, you might argue that this possible optimization justifies the subject. But note that I'm not suggesting to change it. I'm only using this opportunity to question the *premise* for this check *and* similar to this one. Yes, you can blame me for "thread stealing"... :-)

**Comment by dot-asm** [comment]
BTW, two questions in context.

1. If it's argued that it risks confusing optimizer, was it actually OP's original reasoning? @jon-oracle?

2. How come another similar occurrence is not addressed?

3. Questions might appear mean. Are they? My social skill radar is somewhat weak, sorry for that...

**Comment by richsalz** [comment]
Perhaps we should have a discussion about checking for null pointers as a general style issue?
As you know, my view is that crashes are more likely to get fixed than run-time errors and the C library does not check for NULL on things like fprintf.

And also the 128/192/256 check. :)

**Comment by dot-asm** [comment]
> richsalz added the ready label 3 hours ago

Well, it's actually past "ready", because it's actually committed already :-) From this viewpoint it can as well be closed...

**Comment by jon-oracle** [comment]
@dot-asm In answer to your questions 1) yes that was my reasoning, 2) I was poking around in this particular code and saw the bug - I'm happy to fix other occurrences but was concentrating on the ARIA work I was doing. 3) Not really!

**Comment by dot-asm** [comment]
> 2) I was poking around in this particular code and saw the bug - I'm happy to fix other occurrences but was concentrating on the ARIA work I was doing.

But "another similar occurrence" [note *singular* form] is reference to aria_encrypt function in same file.

**Comment by dot-asm** [comment]
> 1) yes that was my reasoning,

I fail to see that [referred article](http://blog.llvm.org/2011/05/what-every-c-programmer-should-know_14.html) actually applies in this case. Article discusses different order of optimization passes causing different outcomes, but specifically in context of actual dereference. Unfortunately it doesn't seem that there is a way to control order from command line. But it's possible to prevent compiler from removing dead assignment. Like this:
```
void contains_null_check(int *P) {
  volatile int *V = P;
  int dead = *V;
  if (P == 0)
    return;
  *P = 4;
}
```
If you examine generate code, you'll actually observe if-condition being eliminated. But if you remove dead assignment, you'll observe if-condition kept. But let's consider example that resembles this case more closely:
```
typedef struct { int rd_key[1]; } ARIA_KEY;

void contains_null_check(ARIA_KEY *P) {
    volatile int *V = P->rd_key;
    int dead = *V;
    if (P == 0)
        return;
    P->rd_key[0] = 4;
}
```
It behaves exactly as previous snippet. I.e. with dead assignment in place if-statement is removed, and without it - kept. [Actually you don't have to modify snippet to remove dead assignment, you can as well compile without or with `-Dvolatile=` option.] In other words P->rd_key does not substitute dereference and consequently should have no effect on optimizer. At least not the kind discussed in referred article. One can still wonder if P->rd_key constitutes defined behaviour even in cases when P is NULL. Well, if it wasn't [defined], then you wouldn't be able to define offsetof(type,member) as `(type *)0->member`...

But once again, I do *not* question legitimacy of this modification, it's fine, it does improve readability.

**Pull request closed without merging**
