### PR TITLE
QUIC: Optimised FIN API

### PR DESCRIPTION
**Pull request by hlandau**
Fixes https://github.com/openssl/project/issues/410

- QUIC: Add optimised FIN API
- QUIC APL: Implement optimised FIN API
- QUIC MULTISTREAM TEST: Test optimised FIN API

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
...actually should we also update the demos/tutorials to use this in preference to SSL_stream_conclude() - or if not at least mention it

**Comment by hlandau** [comment]
@mattcaswell Created an issue: https://github.com/openssl/project/issues/413

**Comment by kroeckx** [comment]
The other option would be that we'd first set an option to queue things (like TCP_CORK) before sending data, and SSL_stream_conclude() could then just clear that option and send all data.

I'm not sure when we start to send data to the socket now, but I know there are applications that want to use TCP_NODELAY, because otherwise things are really slow. Maybe we can have a better API. For instance, an other flag could be that we're done with sending data for now, so everything can be sent to the socket as fast as possible.

**Comment by Eimji** [comment]
Hello, 

`SSL_write_ex2` seems to be the required API to implement a DNS over QUIC client (cf https://github.com/openssl/openssl/discussions/23146#discussioncomment-8193643). So, if I understand well, we will be able to write data and set FIN bit == 1 in a same QUIC frame, right?

Thanks a lot.

**Comment by hlandau** [comment]
> Hello,
> 
> `SSL_write_ex2` seems to be the required API to implement a DNS over QUIC client (cf [#23146 (comment)](https://github.com/openssl/openssl/discussions/23146#discussioncomment-8193643)). So, if I understand well, we will be able to write data and set FIN bit == 1 in a same QUIC frame, right?
> 
> Thanks a lot.

It is not a requirement because sending a separate FIN frame is semantically exactly the same. If a DoQ server were to treat this differently, this would be a server bug and a violation of QUIC semantics. It will allow more efficient implementation of this use case though.

**Comment by hlandau** [comment]
> The other option would be that we'd first set an option to queue things (like TCP_CORK) before sending data, and SSL_stream_conclude() could then just clear that option and send all data.
> 
> I'm not sure when we start to send data to the socket now, but I know there are applications that want to use TCP_NODELAY, because otherwise things are really slow. Maybe we can have a better API. For instance, we could have 2 flags:
> 
>     * I'm going to send other data really soon now.
> 
>     * I'm done sending data.
> 
> 
> I'm just not sure how well this works with multiple streams. For instance, the SSL_stream_conclude() could force sending data to the socket, which is probably perfect for the 1 stream case, but might be suboptimal for multiple streams.

Yeah, this is another option for API design.

My general preference in design is to avoid implicit state or dependencies where one API call influences another. Hence SSL_write_ex2 over some kind of 'cork option' that can be temporarily enabled. That also becomes an issue when dealing with multithreaded usage, perhaps not for a given stream (which should have only one thread dealing with it) but it becomes a factor if as you allude above we start to try to optimise between streams as well.

But we could have a cork-style on/off API if that works better for existing applications. In practice it seems like the design in this PR should be reasonably accessible to such applications.

Happy to consider other options, though.

**Comment by hlandau** [comment]
Merged to master. This will go to 3.3. Thanks for the reviews.

**Pull request closed without merging**
