### PR TITLE
possible crash in BIO_parse_hostserv()

### PR DESCRIPTION
**Pull request by ajmohan**
If BIO_parse_hostserv() is invoked with only <host>, it was running into crash when trying to check for any further colons existed in the parsed <port>, which is NULL in this case.

### CODE REVIEW

**Comment by richsalz** [comment]
+1, @levitte for you to do i think :)

**Comment by levitte** [comment]
Sorry, different patch just went in.  Apparently, you weren't the only one to catch this, @ajmohan ;-)

**Comment by levitte** [comment]
Closing this one since the issue is now fixed.

**Comment by ajmohan** [comment]
Ok, thanks :)

**Pull request closed without merging**
