### PR TITLE
add check of return value of i2d_X509_NAME in x509_cmp.c

### LINKED ISSUE #21694: crypto/x509/x509_cmp.c: return value of i2d_X509_NAME is not checked
OpenSSL 3.0, 3.1, master

Function `i2d_X509_NAME()` is called in functions `X509_NAME_hash_old`, `X509_NAME_hash_ex` (file crypto/x509/x509_cmp.c, lines [297](https://github.com/openssl/openssl/blob/6d38ccedb25f31dfab232e2669415fd4db18b20e/crypto/x509/x509_cmp.c#L297C1-L297C28), [328](https://github.com/openssl/openssl/blob/6d38ccedb25f31dfab232e2669415fd4db18b20e/crypto/x509/x509_cmp.c#L328) ) and its return value isn't checked in these 2 instances, but checked in others.

Per documentation, `i2d_TYPE()` returns negative value if an error has occurred. Should I submit a PR to add checks of return value of  `i2d_X509_NAME()` for these 2 instances?

### PR DESCRIPTION
**Pull request by 3lswear**
Fixes #21694
Add checking of return values of `i2d_X509_NAME` and handle errors.

Found by Linux Verification Center (linuxtesting.org) with SVACE.

### CODE REVIEW

**Comment by t8m** [comment]
This is borderline on what we accept with CLA: trivial. Would you please consider submitting a CLA?
https://www.openssl.org/policies/cla.html

**Comment by 3lswear** [comment]
Now that I see that my CLA has been confirmed, what are the next steps?

**Review by t8m — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
