### PR TITLE
Add comments to NULL func ptrs in bio_method_st

### PR DESCRIPTION
**Pull request by danbev**
This commit adds comments to `bio_method_st` definitions where the
function pointers are defined as `NULL`. Most of the structs have comments
but some where missing and not all consitent.

CLA: trivial

### CODE REVIEW

**Comment by richsalz** [comment]
I think I would prefer to go the other way: remove the comments.  But see what others think.

**Comment by levitte** [comment]
I *agree* with the added comments.  It's been more than once that I've felt irritated because I had to look up the structure and compare, and count at times...

I *disagree* with the leading *no*...  it's like explaining what `NULL` is ;-)

**Comment by mspncp** [comment]
I agree with @levitte about the no‘s.

**Comment by levitte** [comment]
note: this should be cherry picked to 1.1.0 as well.  There will be small conflicts 'cause the context is slightly different, but that should not be too hard to handle, I think.

**Comment by paulidale** [comment]
Merged to 1.1.0 and master.

**Pull request closed without merging**
