### PR TITLE
feat: add TCG / platform certificate OIDs

### PR DESCRIPTION
**Pull request by JonathanWilbur**
This PR adds the object identifiers used by the Trusted Computing Group's [Platform Certificates specification](https://trustedcomputinggroup.org/wp-content/uploads/TCG-Platform-Certificate-Profile-Version-2.0-Revision-39.pdf) used for supply chain security. To my knowledge, this is one of the big use cases of attribute certificates.

I know that we can define object identifiers in an external file at run-time, but I plan to follow up with a PR that uses the NIDs to print platform certificate-specific attributes. To my knowledge, this requires OIDs to be added to `objects.txt` so that they get assigned a permanent NID.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by vdukhovni — APPROVED** [review]
Is it at all possible to prune the list? Or are really all of these potentially likely to appear in attribute certificates?

In other regards the change looks routine enough, though I can't claim to be in a position to verify that all the code points are correct.

In Heimdal Kerberos, there is an ASN.1 module compiler, and these OIDs would be machine-generated directly from the definitions in the spec. Are you confident that all the code points are correct (match the source specification)?

All that said, I am approving the PR on the assumption that the additions are not needlessly bloated and that correctness is not an issue.

**Comment by JonathanWilbur** [comment]
@vdukhovni All of those OIDs included are indeed likely to appear in a platform certificate (or one of their superior arcs). All of those object identifiers come from the version 1 and version 2 specifications. Many are for identifying attributes, certificate extensions, key purposes, and others are used to define a few likely-to-be-used `enum` values.

As far as correctness goes, I'll give it another check, since I wrote this code a while ago. One of the Trusted Computing Group members checked my work too and found no issues.

**Comment by JonathanWilbur** [comment]
I don't know why we'd be seeing the above message. I haven't submitted any commits after either approval.

**Comment by JonathanWilbur** [comment]
I compared the OIDs in `objects.txt` to the platform certificates version 1 and 2 specifications and I still find them to be correct.

**Comment by JonathanWilbur** [comment]
@t8m can this be merged in?

**Comment by t8m** [comment]
This will have to wait after 3.4 version is branched. It is too late for merging into 3.4.

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
