### PR TITLE
err/err.c: improve err_clear_last_constant_time's portability.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by levitte** [comment]
For clarity, was this intended for master only, or?

**Comment by kroeckx** [comment]
I think it was for 1.1.x too

**Comment by dot-asm** [comment]
See https://github.com/openssl/openssl/pull/7735#issuecomment-445360990

**Comment by kroeckx** [comment]
@levitte: Feel free to do it, since #7735 isn't merged yet

**Comment by levitte** [comment]
Merged

master:
91d0fd1c2753f0f7d6e0953eed3cfb6eb96d8ff4 err/err.c: improve err_clear_last_constant_time's portability.

1.1.1:
3c1b8562360cff9b2abf954554208565c08176a1 err/err.c: improve err_clear_last_constant_time's portability.

**Comment by levitte** [comment]
Wait hold on...  I'm confused.  I misread 1.1.x as 1.1.1...

**Comment by levitte** [comment]
Chicken and egg problem, #7735 isn't in yet, so this PR isn't applicable at all in 1.1.0 for the moment.  #7735 needs to be merged first.

**Comment by levitte** [comment]
1.1.0:
e29dcc3794bdc3928942ffb38ee383328b0d6dc1 err/err.c: improve err_clear_last_constant_time's portability.

**Pull request closed without merging**
