### PR TITLE
Minor SSL_CTX_sessions DOC improvement

### PR DESCRIPTION
**Pull request by EasySec**
use LHASH_OF(TYPE) macro to make the example consistent with the declaration in ssl.h

### CODE REVIEW

**Comment by kaduk** [comment]
Hmm, the travis failures are doc-nits complaining.  But I don't remember what we've done to appease it in the past for similar issues...

**Comment by richsalz** [comment]
Looks like find-doc-nits might have a bug to complain about the LHASH_OF.
The other errors are because someone merged a broken file.

**Comment by mattcaswell** [comment]
Yes, travis failure is relevant unfortunately. As @richsalz points out there seems to be a bug in doc-nits  that this change is hitting.

**Comment by t8m** [comment]
I'd recommend redoing the PR from scratch by cherry-picking. This rebase went certainly seriously wrong.

**Comment by EasySec** [comment]
> 
> 
> I'd recommend redoing the PR from scratch by cherry-picking. This rebase went certainly seriously wrong.

I think so, sorry for the mess.

**Comment by t8m** [comment]
Unfortunately the find-doc-nits deficiency would have to be fixed first to merge this.

**Comment by t8m** [comment]
One option would be to expand the macro in the manpage. I.e. to use 'struct lhash_st_SSL_SESSION *` instead.

**Comment by EasySec** [comment]
> 
> 
> One option would be to expand the macro in the manpage. I.e. to use 'struct lhash_st_SSL_SESSION *` instead.

IMHO, it would be better to promote the use of the macro

**Comment by t8m** [comment]
Sure, but that requires fixing the find-doc-nits first. Are you able to do that? If not you can open an issue and this PR will be blocked on that issue. Unfortunately I cannot promise this will get fixed any time soon.

**Comment by richsalz** [comment]
This seems to fix it:
```
diff --git a/util/find-doc-nits b/util/find-doc-nits
index 60a2b8c6a0..a5ea78706d 100755
--- a/util/find-doc-nits
+++ b/util/find-doc-nits
@@ -351,6 +351,7 @@ sub name_synopsis {
 
         my $sym;
         my $is_prototype = 1;
+        $line =~ s/LHASH_OF\([^)]+\)/int/g;
         $line =~ s/STACK_OF\([^)]+\)/int/g;
         $line =~ s/SPARSE_ARRAY_OF\([^)]+\)/int/g;
         $line =~ s/__declspec\([^)]+\)//;
; 
```

**Comment by EasySec** [comment]
> 
> 
> This seems to fix it:
> 
And super-Rich save us again. Thanks ! (I wouldn't have been able to fix anything)
Can I assume there is nothing more to do now with that PR except waiting ?
(and there is not urgency ;-)

**Comment by t8m** [comment]
Well, the fix needs to be included - you could just commit it here as a separate commit with `--author="Rich Salz <rsalz@akamai.com>"`

**Comment by richsalz** [comment]
I don't need credit.  If you must add the one-line fix to your  commit and say "find-doc-nits fix courtesy Rich Salz" but it's really not necessary.

**Comment by EasySec** [comment]
> 
> 
> Well, the fix needs to be included - you could just commit it here as a separate commit with `--author="Rich Salz <rsalz@akamai.com>"`

Well, I did not even realize before that you were speaking about a perl script in the source tree...
Will do it.

**Comment by EasySec** [comment]
Ooops, looks not good. Did I miss something ?

**Comment by t8m** [comment]
The check_update failure is unrelated.

**Review by t8m — APPROVED** [review]

**Review by kaduk — APPROVED** [review]
The doc fix is fine.
IIRC, the API itself is a bit dicey, since you get access to the structure but not the lock that protects updates to it.  (It is really bad if you start doing things like #2397, but I think still problematic even as-is.)

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.  Thanks for the improvement.

**Pull request closed without merging**
