### PR TITLE
Fix unit-tests when no-srp configured

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [ ] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
This needs a rebase...

**Comment by tmshort** [comment]
Rebased.

**Comment by mattcaswell** [comment]
Can someone merge this (@richsalz, @levitte)

**Comment by richsalz** [comment]
i will do it now.

**Comment by richsalz** [comment]
b6e3250 in master, thanks!

**Pull request closed without merging**
