### PR TITLE
Release zero length handshake fragment records

### LINKED ISSUE #20821: client infinite loop
The current `client` fuzzer on OSS-Fuzz seems to have an infinite loop (or is at least very slow to finish).

```
$ ./client timeout-aad79c599856ffa8fdb9acebd2db138d0213375e -timeout=5
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1178031846
INFO: Loaded 1 modules   (83798 inline 8-bit counters): 83798 [0x105b5b0, 0x106fd06), 
INFO: Loaded 1 PC tables (83798 PCs): 83798 [0x106fd08,0x11b7268), 
./client: Running 1 inputs 1 time(s) each.
Running: timeout-aad79c599856ffa8fdb9acebd2db138d0213375e
ALARM: working on the last Unit for 5 seconds
       and the timeout value is 5 (use -timeout=N to change)
==1255762== ERROR: libFuzzer: timeout after 5 seconds
    #0 0x4ac401 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x518578 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x4fd1c9 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5
    #3 0x7f6b333a441f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #4 0x5e3c51 in ssl3_read_bytes /src/openssl/ssl/record/rec_layer_s3.c:772:13
    #5 0x5754e3 in ssl3_read_internal /src/openssl/ssl/s3_lib.c:4510:9
    #6 0x575244 in ssl3_read /src/openssl/ssl/s3_lib.c:4533:12
    #7 0x59b272 in ssl_read_internal /src/openssl/ssl/ssl_lib.c:2291:16
    #8 0x59bcd7 in SSL_read /src/openssl/ssl/ssl_lib.c:2305:11
    #9 0x4dfa5f in FuzzerTestOneInput /src/openssl/fuzz/client.c:92:17
    #10 0x4dfc5f in LLVMFuzzerTestOneInput /src/openssl/fuzz/driver.c:28:12
    #11 0x4fe7f3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #12 0x4e9f52 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #13 0x4ef7fc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #14 0x518d32 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #15 0x7f6b3319d082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: libFuzzer: timeout
```

Base64 of the input:

```
FgPwAD0CAAA5AwDe2BEAAAAHCfsL/0AOAQUARzEAAAAAwEcABQAAMAAAAADAFQAAEf8BAAEAABYA
AGZvAACAxQAAFgMAACwMAAAkAwAdIMgH//////3//18AAAAABP/r4/8BAEFveQEAAAAAAAA1DgAA
ABQDAAABARYDAAA9FAAAJBdfy0mr5CEMetylO2MEB4ZxD3JVvKBxrZVbdAijnhIAAAAAAAAAAAAA
AAAAAAAAAwMAPQMDAAAAFxYDAAAUAwEBAAAAAAABFgM98RQAACQXX8s=
```

Run `./client input.bin` after decoding the base64 to `input.bin`.

You can close this if you're already aware of it (OSS-Fuzz should have notified you).

### PR DESCRIPTION
**Pull request by mattcaswell**
If we are processing a hanshake fragment and we end up with a zero length record, then we still need to release it to avoid an infinite loop.

Fixes #20821

### CODE REVIEW

**Comment by mattcaswell** [comment]
Added "tests: deferred". I plan to add the fuzz testcase identified in #20821 in a separate PR.

**Comment by mattcaswell** [comment]
Fuzz test case added in openssl/fuzz-corpora#5

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
We need to update the fuzz-corpora submodule commit hash to the one containing the fuzz testcase. So what about merging the fuzz-corpora pr first and adding the submodule update to this PR?

**Comment by mattcaswell** [comment]
> We need to update the fuzz-corpora submodule commit hash to the one containing the fuzz testcase. So what about merging the fuzz-corpora pr first and adding the submodule update to this PR?

Good point. Will do.

**Comment by mattcaswell** [comment]
Corpora updated. @t8m please reconfirm.

Needs a second review.

**Review by tmshort — APPROVED** [review]
LGTM, though I didn't review the submodule, but I'm ok with it.

**Review by t8m — APPROVED** [review]

**Comment by guidovranken** [comment]
Input which hangs the `server` fuzzer (base64)

```
gCsBA/kAAwAAAB8AAAFkkDFuw5jXOr57sLp3Fwp7F9QiKkxhbxRJX2chhJ/JFgMDAQYQAAECAQAA
CQAAGMgIAAAAABgAEWT8AAAAcXB3AAAAAAAAAAAWAxAAOiEAADhgkl7UnonS/v8AAwBoQIMD/1EA
ABUAAAAEAAD/f/8ABgkqAAACwBUERasAqwAIAAoABAACABgWAwMANRAAADIxAgAAAAAAAAAAPgAA
AAAAAPkEALUkjMN8+gOxdf+1tbW1tbW1tbW1tbW1tbW1EQAAAAAAtgCVtbW1tbW1tbW1tbW1tbW1
AAAAAAAAAP9//wBVHREEQQkqAAgACgICAAEGAAAAAAAABQAjAAAAAAAAAAB2YWxpAAAAAAoAfgYA
AAAAAAAAAAAAAAAAAAAAAAAARUUy5++QGu8YFAMDAAEBFgMDACMUAAAMSLZpdmw808qzFwMDABHR
Ftf///////8AXhQDAwABMBYDAwAQAAACAAQWABRelAEDAwAQAAAClBc=
```

**Comment by mattcaswell** [comment]
> Input which hangs the server fuzzer

The server based hang is the same underlying problem as the client one (I already checked this). We should probably also add the server testcase to the fuzz-corpora, but I'll do that in other PRs since this one is ready-to-merge.

**Comment by mattcaswell** [comment]
Merged. Thanks.

> We should probably also add the server testcase to the fuzz-corpora, but I'll do that in other PRs since this one is ready-to-merge.

https://github.com/openssl/fuzz-corpora/pull/7

**Pull request closed without merging**
