### PR TITLE
Don't ignore ASN1 when checking for undocumented symbols

### PR DESCRIPTION
**Pull request by mattcaswell**
When we run "make doc-nits" (which happens during travis runs) it will
complain if we add any new symbols that aren't documented. However it
was suppressing anything starting with ASN1. There's no reason why we
should allow ASN1 symbols to go undocumented any more than any others.
Therefore we remove that exception.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
H'oh boy...

Did you find a reasoning re skipping those functions in the commit log?

**Comment by mattcaswell** [comment]
> Did you find a reasoning re skipping those functions in the commit log?

Seems to have always been there. No specific reasoning mentioned in the logs that I could find.

**Comment by richsalz** [comment]
We never considered the ASN1 parsing to be really part of the public API.  Nobody on the team was really thrillled with the way that stuff works, and there was also a bubbling undercurrent of replacing it.  When developing find-doc-nits, I just codified that sentiment :)  Perhaps a more tractable solution is to just ignore the common new/free/it names?  And then trim down the missing list significantly.

**Comment by mattcaswell** [comment]
Ping?

**Comment by paulidale** [comment]
Knowing which of these isn't documented seems like a good idea.

**Comment by mattcaswell** [comment]
Darn. PR #10942 went in and added a new and undocumented ASN1 function with the promise from @levitte that he would add the docs real soon. Until that happens we need to add that function to missingcrypto.txt in this PR to avoid a "make doc-nits" failure.

@paulidale (or anyone) please can you reconfirm?

**Comment by mattcaswell** [comment]
Travis red cross is not relevant.

Ping?

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
