### PR TITLE
Fix various mistakes in ec_GFp_nistp_recode_scalar_bits comment.

### PR DESCRIPTION
**Pull request by davidben**
(Comment-only change, so tests, etc., not applicable.)

### CODE REVIEW

**Comment by mspncp** [comment]
Thanks @davidben for sharing your corrections (and reformatting the comment style :-)

_FWIW:  the corresponding commit in BoringSSL can be found here: https://github.com/google/boringssl/commit/326f12135b7e226af1fd1a5f24ee040d78a6aa2d_

**Comment by mattcaswell** [comment]
@romen are you able to take a look?

**Comment by romen** [comment]
I believe this should go to both `master` and `1.1.1`.

What is the policy about the other 2 branches? This is technically fixing a documentation error.

**Comment by mattcaswell** [comment]
> What is the policy about the other 2 branches? This is technically fixing a documentation error.

Not a security fix, so I'd keep it to master and 1.1.1

**Comment by davidben** [comment]
Merged to master in 8be6a4ed02297f380bbea269f2e1c08a592444bc.

How do you all usually merge to other branches? Just `git cherry-pick -x` and push it directly, or do I open a separate PR and do the full song and dance?

**Comment by mattcaswell** [comment]
As long as it cherry picks without non-trivial conflicts, and the PR had the relevant branch labels against it prior to approval (as this one did), then you just `git cherry-pick -x` and push.

**Comment by davidben** [comment]
Done in 9517295b7f3c3ea7bed254b426ee45dcb60e655a.

**Pull request closed without merging**
