### PR TITLE
openssl-3.1#20290: Fixed typo in "config" man page

### PR DESCRIPTION
**Pull request by blazmonster**
CLA: trivial

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
LGTM, agree trivial

**Review by tmshort — APPROVED** [review]
Agree with trivial.

**Comment by tmshort** [comment]
@beldmit, do you need to actually do the formal github approval?

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
@tmshort sorry, forgot it. Thanks!

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the fix.

**Pull request closed without merging**
