### PR TITLE
Move BLAKE2 digests completely to the default provider

### PR DESCRIPTION
**Pull request by levitte**
This leaves minimal implementations of EVP_blake2b512 and EVP_blake2s256,
that are now only there to provide a name for implicit fetches.

### CODE REVIEW

**Comment by mattcaswell** [comment]
This suffers from the same problems as #9076 (see my comments there).

**Comment by slontis** [comment]
When this actually does work do you perhaps need to leave the size fields in the old legacy EVP_MD structures?

**Comment by levitte** [comment]
> When this actually does work do you perhaps need to leave the size fields in the old legacy EVP_MD structures?

Why? For DigestInit, only the type is interesting...

**Comment by slontis** [comment]
> Why? For DigestInit, only the type is interesting...

So what does EVP_MD_size(md) return? it doesnt have a md->prov right?

**Comment by levitte** [comment]
> So what does EVP_MD_size(md) return? it doesnt have a md->prov right?

Ohhhhhhhhhhhhhhhh!!!!!!  Now this raises an interesting question, how is that size relevant for legacy (constant) EVP_MDs if any actual use of that EVP_MD will result in an implicit fetch, i.e. a completely different set of data?  There's a potential that `EVP_MD_size()` will give the wrong answer...

**Comment by mattcaswell** [comment]
> So what does EVP_MD_size(md) return? it doesnt have a md->prov right?

Good point. `EVP_MD_block_size` has a similar issue.

**Comment by slontis** [comment]
> There's a potential that `EVP_MD_size()` will give the wrong answer...

But at least it would be right in most cases :)

**Comment by levitte** [comment]
> But at least it would be right in most cases :)

yeeeaaahhh I dunno how I like that...  but OK, for the moment being, I'll keep the sizes.  I wonder if we should have controls of such things in DigestInit, though.

**Comment by levitte** [comment]
Ping.  We really should do this kind of cleanup for everything that we move to the provider.

**Review by paulidale — APPROVED** [review]

**Review by mattcaswell — CHANGES_REQUESTED** [review]
This suffers from the same problem that I noted in #10059 so should not be merged before that is resolved.

**Comment by levitte** [comment]
Ping

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

8c77d45adab101f10b323de3d59fb47b8f8d3a93 Move BLAKE2 digests completely to the default provider

**Pull request closed without merging**
