### PR TITLE
Avoid __GNUC__ warnings when defining DECLARE_DEPRECATED [1.1.0]

### PR DESCRIPTION
**Pull request by levitte**
We need to check that __GNUC__ is defined before trying to use it.
This demands a slightly different way to define DECLARE_DEPRECATED.

-----

This is a backport of #6680 and #6689 for 1.1.0

### CODE REVIEW

**Comment by dot-asm** [comment]
> This is a backport of #6680 for 1.1.0

Along with red cross from travis.

**Comment by levitte** [comment]
Thanks for the reminder.  Fixup pushed

**Comment by levitte** [comment]
Itäs looking good so far...

**Review by petrovr — CHANGES_REQUESTED** [review]
Why ifdef __GNU ... is not in else statement above?

**Comment by levitte** [comment]
Right you are, @petrovr.  Fixed

**Comment by mspncp** [comment]
Richard, this pr has now deviated from #6680. Do you intend to "forward port" your additional changes to master?

**Comment by levitte** [comment]
The "additional change" comes from #6689, which should really have been part of #6680.

**Comment by levitte** [comment]
What you're missing is that `no-deprecated` is handled differently between 1.1.0 and 1.1.1.
However, the `#else` part in this corresponds to the change in #6680, does it not?

**Comment by mspncp** [comment]
> What you're missing is that no-deprecated is handled differently between 1.1.0 and 1.1.1.

Ok, I understand now. I had thought about that possibility, but I overlooked 973abf52304b454e8f2220a11aa8b6c6512c44fb. Maybe it would be a good idea to add a short note to the CHANGES file?

```
msp@msppc:~/src/openssl$ grep -r NO_DEPRECATED
CHANGES:1175:  *) Revert default OPENSSL_NO_DEPRECATED setting.  Instead OpenSSL
CHANGES:1446:  *) config has been changed so that by default OPENSSL_NO_DEPRECATED is used.
CHANGES:5496:     this change is covered by the OPENSSL_NO_DEPRECATED symbol. As always,
CHANGES:5558:     if OPENSSL_NO_DEPRECATED is defined, BN_zero() is a void macro.
CHANGES:5611:     OPENSSL_NO_DEPRECATED is defined. Some "openssl" subcommands and a few of
CHANGES:5807:     the new ones. The OPENSSL_NO_DEPRECATED symbol can be used to hide
NEWS:507:        functionality with the OPENSSL_NO_DEPRECATED macro or the
```


> However, the #else part in this corresponds to the change in #6680, does it not?

Agreed. :-)

**Comment by levitte** [comment]
> Maybe it would be a good idea to add a short note to the CHANGES file?

Maybe you should read [the whole entry](https://github.com/openssl/openssl/blob/master/CHANGES#L1175-L1202) for that line you found (line 1175) ;-)

**Comment by mspncp** [comment]
Ok, you win. And I'll shut up ;-).

**Comment by levitte** [comment]
... or if you're satisfied, you could approve ;-)

**Review by mspncp — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

dcb8333087d56eef97c482aabb506b8be8299cde Avoid __GNUC__ warnings when defining DECLARE_DEPRECATED

Thank you!

**Pull request closed without merging**
