### PR TITLE
Move provider der_XXX.h.in files to the include directory.

### LINKED ISSUE #15506: FIPS derxxx.h.in in wrong directory
Files like `der_digests.h.in` are in `providers/common/der`.  For every other `.in` file in OpenSSL (all 130 of them), they exist in the same directory where the target file exists.  There is no reason this should be otherwise.

### PR DESCRIPTION
**Pull request by slontis**
Fixes #15506

The .in and generated .h files are now in the same directory.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Is there some way to macro this??

$INC_PATH=../prov
GENERATE[$DER_DIGESTS_H]=$INC_PATH/der_digests.h.in

**Comment by slontis** [comment]
I believe this is better - we are already redirecting the output to another folder, so I see no reason why the input cant also be directed from the same location.

**Review by t8m — APPROVED** [review]
In the end I agree this makes some sense as for all the other .in files we place them along the resulting files. And yeah, the build instructions should stay here.

**Comment by richsalz** [comment]
> Is there some way to macro this??
> 
> $INC_PATH=../prov
> GENERATE[$DER_DIGESTS_H]=$INC_PATH/der_digests.h.in

Won't normal make stuff work for the right-hand side of the equal sign?  @levitte?
```
DIR=../prov
GENERATE($DER_DIGEST_H] = $DIR/der_digests.h.in
```

?

**Comment by levitte** [comment]
I'm surprised no one even tried 😆

Yes, it should work to put the include directory in a variable.

**Comment by petrovr** [comment]
Shane wrote:
> Fixes #15506
>
> The .in and generated .h files are now in the same directory.[]
Really???

Generated files are always in build tree!

Roumen

**Comment by slontis** [comment]
> I'm surprised no one even tried 😆

I tried and failed.

**Comment by slontis** [comment]
> Generated files are always in build tree!

These are header files which are generated from .h.in files. The headers were already being put in a include directory.. The .h.in files have been put in the same place (it is hard enough to remember there is a .in file even when they are in the same directory :)).
Note the generated .c and .c.in files are in the build directory still..

**Comment by slontis** [comment]
Thanks. Merged to master

**Comment by levitte** [comment]
> I tried and failed.I tried and failed.

I went looking, and indeed, the GENERATE value isn't variable expanded...  there are historical reasons, but they do not apply any more, and the internal docs for build.info files does say that variables are expanded in all values, so this is a bug in Configure.  Fixup PR coming up

**Comment by levitte** [comment]
See #15554

**Comment by petrovr** [comment]
Shane wrote:
>> Generated files are always in build tree!
> 
> These are header files which are generated from .h.in files. The headers were already being put in a include directory.. The .h.in files have been put in the same place (it is hard enough to remember there is a .in file even when they are in the same directory :)).
> Note the generated .c and .c.in files are in the build directory still..
> 

Situation with headers is even worse. Source is more or less capable to handle different configuration while headers are adjusted to specific configuration!

Roumen

**Comment by richsalz** [comment]
> while headers are adjusted to specific configuration!

The OpenSSL solution to this is to do an "out of tree" build.  Make a directory, and then invoke Configure with the pathname to the source.  For example:
```
mkdir foo
cd foo
../openssl/Configure ...flags...
```

**Pull request closed without merging**
