### PR TITLE
apps/speed: add SM3/4 algorithm benchmark

### PR DESCRIPTION
**Pull request by uudiin**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
What's wrong with using: `speed -evp sm3` and `speed -evp sm4-cbc`?

I thought we'd added code to not require the `-evp` but it seems not.  I think this would be a better approach but it will require some rework in the speed app.

**Comment by InfoHunter** [comment]
@paulidale , it seems that you prefer to avoid `-evp` and would like to make current `-evp` enabled algorithms workable without specifying `-evp`?

**Comment by paulidale** [comment]
At some point I think we'll need to allow multiple `-evp` options.
Then we can move to ignoring `-evp` and handling everything uniformly.

**Comment by InfoHunter** [comment]
Why don't jump to ignoring `-evp` directly?

**Comment by paulidale** [comment]
Yes, that's the step after.  Or at the same time.

**Comment by InfoHunter** [comment]
CI failures are very related to the new commits.

**Comment by InfoHunter** [comment]
I prefer all algorithms in `speed` are called from EVP interface, and thus we don't need to specify `-evp` explicitly any more since all are EVP based

**Comment by t8m** [comment]
All algorithms in speed are already called through the EVP interface. The problem is the -evp option has slightly different speed measurement loop so by removing the option we would loose comparability of the results between versions.

**Comment by InfoHunter** [comment]
> by removing the option we would loose comparability of the results between versions.

One possible way of addressing this is measuring those `-evp` algorithms (say, GCM mode of AES) still in old style measurement loop in the new version of `speed`

**Comment by paulidale** [comment]
So fixing speed is a 4.0 problem?
Or is adjusting the loop (so it is faster than not) more sensible?  E.g. perform one or a few iterations to prime the branch prediction.

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Sel, 11 Jan 2022, 4:02 PM Tianjia Zhang ***@***.***>
menulis:

**Comment by eenthropy** [comment]
A1

**Comment by Sashan** [comment]
this PR seems to be stale/abandoned. it will be closed if we won't hear back by end of June 2024

**Pull request closed without merging**
