### PR TITLE
Avoid GOST sigalgs in TLSv1.3

### PR DESCRIPTION
**Pull request by mattcaswell**
As noted in [this comment](https://github.com/openssl/openssl/pull/6168#issuecomment-397839161) and [this one](https://github.com/openssl/openssl/pull/6168#issuecomment-397839196), and also in issue #6513, there are some concerns about the use of GOST sigalgs in TLSv1.3. Primarily those sigalgs are using unregistered/private codepoints. We probably can't remove them entirely for backwards compat reasons - but we can try not to use them in TLSv1.3 (where possible).

This PR is an attempt to address that issue and takes the following approach:
- A client will only offer GOST sigalgs iff: the GOST engine is loaded *and* GOST ciphersuites are configured *and* the client is willing to negotiate TLSv1.2 or lower
- A server will never use GOST sigalgs if TLSv1.3 has been negotiated
- A server will never negotiate TLSv1.3 if it is only configured with certificates that aren't suitable for TLSv1.3 (GOST certs, and DSA certs) - unless PSKs are configured.

This doesn't completely eliminate the use of GOST sigalgs in TLSv1.3 but will avoid them in most circumstances. They *could* still be used if an OpenSSL client that is configured to allow TLSv1.3, and has the GOST engine loaded, and has configured GOST ciphersuites attempts to talk to a TLSv1.3 and GOST capable non-OpenSSL server. In that case the GOST sigalgs will be present in the ClientHello, and the server may then use them in TLSv1.3. If that occurs then an OpenSSL client will tolerate it.

This is WIP because I have no idea how to write a test for this yet. Before I take on that challenge I'd like some feedback on this approach (particularly from @vdukhovni and @beldmit).

### CODE REVIEW

**Comment by kroeckx** [comment]
I assume we have a way to configure the sigalgs. Is there a reason it shouldn't also be configured, and not just the ciphersuite?

**Comment by beldmit** [comment]
Quickly looking it seems OK, but I am far from computer now and will be able to review it on Monday.

**Comment by beldmit** [comment]
I think everything is OK with this code.

**Comment by richsalz** [comment]
Thanks very much, @beldmit !

**Comment by richsalz** [comment]
@mattcaswell is this still WIP or are you ready to merge?

**Comment by mattcaswell** [comment]
Fix up for travis failure pushed. Please reconfirm!

**Comment by richsalz** [comment]
Reconfirm.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
