### PR TITLE
Add a case for 64-bit OS X in config

### PR DESCRIPTION
**Pull request by levitte**
This makes it possible to just run ./config on a x86_64 machine with
no extra fuss.

RT#4356

### CODE REVIEW

**Comment by levitte** [comment]
Ping?  Someone?

**Comment by t-j-h** [comment]
+1 and long overdue - although this change may surprise some as default building is changing

**Comment by levitte** [comment]
Good point, is it worthy of a note in CHANGES?

**Comment by t-j-h** [comment]
A note in changes would be appropriate IMHO.

**Comment by levitte** [comment]
Note in CHANGES added.  Still +1?

**Comment by t-j-h** [comment]
+1 thanks

**Comment by levitte** [comment]
Thank you!  Merged.

**Pull request closed without merging**
