### PR TITLE
Limit sequence number for GOST TLS 1.2 ciphers

### PR DESCRIPTION
**Pull request by NMorozxov**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
I'm not sure it's the best possible solution. I try to avoid GOST-specific patches as much as possible and do this on the engine level. 

We have a TLSTREE ctrl call accepting sequence, and I think that it's better to place comparison there. And we have, e.g., OpenVPN with its own sequence generation: the engine seems to be a more relevant place for such a check.

**Comment by NMorozxov** [comment]
ping @openssl/committers need some one else review

**Comment by NMorozxov** [comment]
I think my ping not working

**Comment by NMorozxov** [comment]
@beldmit Can you set the "review required" label. May be  this will attention other developers

**Comment by beldmit** [comment]
Done

**Comment by t8m** [comment]
I agree with Dmitry that this should be more general check - either in the engine/provider or it should be a property of a TLS ciphersuite and checked for all supported ciphersuites where limiting the number makes sense - I suppose all 64bit-block ciphersuites should have limit.

**Comment by NMorozxov** [comment]
@t8m ciphersuite property sounds like good idea

**Comment by kaduk** [comment]
> I agree with Dmitry that this should be more general check - either in the engine/provider or it should be a property of a TLS ciphersuite and checked for all supported ciphersuites where limiting the number makes sense - I suppose all 64bit-block ciphersuites should have limit.

Even some of the AES modes (128-bit blocksize) have reachable limits, too.

**Pull request closed without merging**
