### PR TITLE
Fix formatting of NOTES-WINDOWS.md and doc-nits failure

### PR DESCRIPTION
**Pull request by t8m**
This fixes doc-nits failure in CI, so marking urgent.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Aargh, the GitHub actions seem to be not running again.

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
Agree urgent.

**Review by mspncp — APPROVED** [review]
It’s urgent

**Comment by t8m** [comment]
Merged to master and 3.0 branch. Thank you for the reviews.

**Pull request closed without merging**
