### PR TITLE
Fix the checks of X509_REVOKED_add1_ext_i2d and X509_LOOKUP_* functions

### PR DESCRIPTION
**Pull request by PeiweiHu**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by petrovr** [comment]
There is no real need to change return values for boolean like methods. Even is wrong to do this.

If there is change in return value of a method - it must be documented first. Then impacted projects should start changing code.

**Comment by PeiweiHu** [comment]
> There is no real need to change return values for boolean like methods. Even is wrong to do this.
> 
> If there is change in return value of a method - it must be documented first. Then impacted projects should start changing code.

Thanks for your comment. First, they are not boolean like functions since both positive, zero, and negative numbers can be returned. Second, it seems I didn't change the return values of APIs.

**Comment by t8m** [comment]
@petrovr all these functions are documented (albeit fairly cryptically) to also possibly return negative values.

**Review by t8m — APPROVED** [review]

**Comment by petrovr** [comment]
For instance in case of  X509_L_ADD_DIR ret is zero or result of add_cert_dir() .  Result of add_cert_dir is zero or one. 
It seems to me negative in not case in this universe.

**Comment by t8m** [comment]
Yeah, maybe with fine static code analysis you can come to conclusion that in this particular code context the result cannot be negative. However that does not change the fact that these functions can return negative values in other contexts.

**Comment by t8m** [comment]
There is for example in X509_LOOKUP_ctrl_ex()
```
    if (ctx->method == NULL)
        return -1;
```

So clearly, if you call X509_LOOKUP_add_dir() on ctx with NULL method you can get -1. Yeah, probably in these contexts you cannot happen to call it on such ctx. But it is a good practice to handle all possible return values as documented and not make assumptions depending on the current implementation as that might later change.

**Comment by PeiweiHu** [comment]
@t8m It seems this pr is waiting for merging.

**Comment by t8m** [comment]
> @t8m It seems this pr is waiting for merging.

It needs second review from @openssl/committers

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for your contribution.

**Comment by petrovr** [comment]
Tomáš Mráz wrote:
> @petrovr all these functions are documented (albeit fairly cryptically) to also possibly return negative values.
> 

Please double check code.


Regards,
Roumen Petrov

**Pull request closed without merging**
