### PR TITLE
Rename DRBG_CTX to RAND_DRBG

### PR DESCRIPTION
**Pull request by richsalz**
The API is named RAND_DRBG_xxx, so rename the datatype.

-----

I could have renamed the API, but this is less typing.
There are also a couple of really minor comment cleanups.

### CODE REVIEW

**Comment by levitte** [comment]
Ok, so that's not a context structure...  in that case, may I bother you to rename `dctx` to something like `drbg`?

**Comment by mspncp** [comment]
@levitte +1 from me

**Comment by snhenson** [comment]
Well I'd certainly intended it to be a context when I wrote the stuff this was derived from.

**Comment by mspncp** [comment]
Would RAND_DRBG_CTX be a good compromise?

**Comment by levitte** [comment]
If it's a context, then `RAND_DRBG_CTX` (and `struct rand_drbg_ctx_st`) is a better name, yes.

**Comment by richsalz** [comment]
What's a "context" ?  It's a complicated opaque type, more like a BN than a factory like BN_CTX.
I will rename the "dctx" parameters and local variables to "drbg"

**Comment by richsalz** [comment]
Additional commit added.

**Comment by snhenson** [comment]
A context in this sense is the internal state of a specific instance. As in EVP_MD_CTX, EVP_CIPHER_CTX etc. Yes BN_CTX isn't a context in that sense and arguably SSL_CTX isn't either but those were ancient names from SSLeay days.

**Comment by richsalz** [comment]
I see.  So something like BN or X509 aren't really "mutable" and therefore aren't CTX's.  Do you want me to rename the API -- which is only internal -- to ```RAND_DRBG_CTX_xxx``` or rename the datatypes, which are also only internal, to ```RAND_DRBG``` ?

**Comment by snhenson** [comment]
Well by analogy with EVP_CIPHER_CTX et al it would go something like this if we're calling something RAND_DRBG:

Higher level functions that implement the algorithm would be named RAND_DRBG_foo.
An specific instance of a RAND_DRBG would use a context called RAND_DRBG_CTX.
Simple accessors to RAND_DRBG_CTX would be called RAND_DRBG_CTX_get_foo etc,

However if this is all internal only APIs then there is a separate convention: normally (with the usual plethora of exceptions!) internal only APIs have all lower case names.

**Comment by richsalz** [comment]
The names are defined in libcrypto and will be used in libssl.  We already have RAND as a prefix we use, so I kept that to avoid namespace pollution into developers's names.  I am going to cancel this PR.  If there are names you think I should use, email me :)

**Pull request closed without merging**
