### PR TITLE
Fix a HPKE API to put libctx, propq as last (optional parameters).

### PR DESCRIPTION
**Pull request by slontis**
This keeps the interface consistent with other HPKE API's.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
@sftcd FYI.

**Comment by slontis** [comment]
This was observed when reviewing https://github.com/openssl/openssl/pull/20567

**Comment by slontis** [comment]
This can only be changed if HPKE was not merged into OpenSSL 3.1

**Review by paulidale — CHANGES_REQUESTED** [review]
Documentation?

**Review by paulidale — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by sftcd** [comment]
'case it's useful, that seems fine.

S.

**Comment by paulidale** [comment]
Kicking CIs

**Comment by hlandau** [comment]
Is this suitable for merge?

**Comment by slontis** [comment]
yes it can be merged.

**Comment by paulidale** [comment]
Merged

**Pull request closed without merging**
