### PR TITLE
openssl pkcs12 -export: Ignore the fetch error when a legacy algorithm is found

### LINKED ISSUE #21034: openssl pkcs12 -export: Ignore the fetch error when a legacy algorithm is found during
```
openssl pkcs12 -engine gost -export -inkey seckey.pem -in cert.pem -out user.pfx -keypbe gost89 -certpbe gost89 -macalg md_gost12_256
Engine "gost" set.
Enter Export Password:
Verifying - Enter Export Password:
00E45779D87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../../../../openssl/crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (md_gost12_512 : 107), Properties (<null>)
00E45779D87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../../../../openssl/crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (md_gost12_512 : 107), Properties (<null>)
00E45779D87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../../../../openssl/crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (GOST R 34.11-2012 with 256 bit hash : 101), Properties (<null>)
0
```

### PR DESCRIPTION
**Pull request by ypenkin**
```
openssl pkcs12 -engine gost -export -inkey seckey.pem -in cert.pem -out user.pfx -keypbe gost89 -certpbe gost89 -macalg md_gost12_256
Engine "gost" set.
Enter Export Password:
Verifying - Enter Export Password:
00040D4CB27F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../../../../openssl/crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (md_gost12_512 : 107), Properties (<null>)
00040D4CB27F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../../../../openssl/crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (md_gost12_512 : 107), Properties (<null>)
00040D4CB27F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../../../../openssl/crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (GOST R 34.11-2012 with 256 bit hash : 101), Properties (<null>)
0
```

### CODE REVIEW

**Comment by beldmit** [comment]
This change is beyond trivial and you will have to submit the CLA to make it accepted.
LGTM otherwise

**Comment by ypenkin** [comment]
I have submitted a signed ICLA today

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
@mattcaswell could you please check the CLA status?

**Review by t8m — APPROVED** [review]

**Comment by beldmit** [comment]
Merged to 3.0, 3.1, an master.
Many thanks for your contribution!

**Pull request closed without merging**
