### PR TITLE
code health : move ECDH tests to evptests.txt

### PR DESCRIPTION
**Pull request by romen**
This pull request address the ecdhtest.c file.

We moved the NAMED CURVES TESTS and the KATs to the evptests.txt format.

We also plan to move the cofactor KATs test to the evptests.txt, but this will also require changes to evp_test.c, hence we plan to do this in a separate PR.

### CODE REVIEW

**Comment by romen** [comment]
@richsalz it should!

What is the best way to check?

I tried cherry-picking the commits in this PR on a test branch forked from OpenSSL_1_1_0e and I have some merge conflicts on evptests.txt due to concurrent changes, but other than that the changes should be orthogonal!

**Comment by richsalz** [comment]
Great.  Could you open a PR with the 1.1.0 version of this?  Thanks!

**Comment by romen** [comment]
@richsalz Done: #3188

**Comment by bbbrumley** [comment]
+1 I reviewed this.

@romen Good work!

**Comment by levitte** [comment]
Merged.  d663c2db5619088800695d5cb074c3ec5d158aec to e80a0f65d473833908bece6f2d0a2ecc16639474

**Pull request closed without merging**
