### PR TITLE
Fix comment placement in ecp_nistp256.c

### PR DESCRIPTION
**Pull request by scottarc**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Hi @scottarc
For this type of change "CLA: trivial" needs to be added to the commit message.
(Search for the above string in the CONTRIBUTING file for further info).

**Comment by scottarc** [comment]
I added CLA: Trivial and force-pushed but the bot is still complaining.

**Comment by mspncp** [comment]
That's because you placed it into the subject line.

```
Fix comment placement in ecp_nistp256.ci CLA: trivial
```

It needs to go in the commit message `body` instead, which is separated by an empty line from the subject line:

```
Fix comment placement in ecp_nistp256.ci

CLA: trivial
```

**Comment by mspncp** [comment]
Sorry if we strained your patience too much. I would have offered now to fix it for you, but unfortunately, you already deleted your repository... :-/

**Comment by scottarc** [comment]
@mspncp You're fine! I just feel bad for wasting other people's time over such a trivial fix.

**Comment by mspncp** [comment]
The question is: who was wasting who's time. ;-)

Never mind, let's just reboot this as #11175 and I'll take care of the rest.

**Pull request closed without merging**
