### PR TITLE
Clarify DRBG seeding.

### PR DESCRIPTION
**Pull request by paulidale**
There is a legacy code path that OpenSSL won't use anymore but applications could.  Add a comment indicating this to avoid confusion for people not intimately conversant with the nuances in the RNG code.

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by shahsb — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Review by nhorman — APPROVED** [review]

**Comment by paulidale** [comment]
Not sure what the `@paulidale
[Merge branch 'master' of github.com:openssl/openssl into rng-comment](https://github.com/openssl/openssl/pull/24745/commits/8c52b8bbd4ace4bb19883b61d18c34fc65a9ab68)` line is about.

**Comment by paulidale** [comment]
I did a fixup to remove a spurious single quote.  This will need reapproval but I don't think it should reset the timer.

**Comment by nhorman** [comment]
approval holds

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
> Not sure what the `@paulidale [Merge branch 'master' of github.com:openssl/openssl into rng-comment](https://github.com/openssl/openssl/pull/24745/commits/8c52b8bbd4ace4bb19883b61d18c34fc65a9ab68)` line is about.

You probably clicked on something in the Github UI that created the merge commit. It can be dropped when merging.

**Comment by paulidale** [comment]
The confusing part is that I was not awake when it happened.

**Comment by paulidale** [comment]
Merged, thanks for the reviews.

**Pull request closed without merging**
