### PR TITLE
Cleaned up tls1_prf and added comments.

### PR DESCRIPTION
**Pull request by davidmakepeace**
Added a description of the PRF algorithm from RFC 2246 and RFC 5246.
Added comments and made minor code changes to make it easy to associate steps in the algorithm description with lines of code in the implementation.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
maybe add a "conforms to" section into the EVP_KDF_TLS1_PRF.pod file

**Comment by slontis** [comment]
Maybe a reference to SP800-135 r1 should also be in there..

**Comment by levitte** [comment]
I'm surprised to see this added in the "3.0 New Core + FIPS" project...  that's not really what this is.

**Comment by slontis** [comment]
Richard - this goes inside the FIPS boundary, see SP800-135 r1

**Comment by levitte** [comment]
...  I thought this was a KDF backend that was being documented...  so while there is a relationship, this doesn't look like New Core or FIPS module work *per se*.

Ah well, I'll leave it to someone else to make a final call.

**Comment by slontis** [comment]
Documenting the steps just makes it easier to see that is following the standards.

**Comment by paulidale** [comment]
I was indecisive about adding the FIPS project tag -- happy for it to be removed.

**Pull request closed without merging**
