### PR TITLE
Improve documentation of behaviour of DEFAULT in the cipherstring.

### LINKED ISSUE #5420: Strange behavior of `DEFAULT` in cipher list
For example, following commands will return the same set:

    openssl ciphers DEFAULT
    openssl ciphers DEFAULTz

despite `DEFAULTz` not being a valid cipher string.

I have already [reported this to Fedora][1].  According to @t8m, the `DEFAULTz` is equivalent to `DEFAULT:z`, in which case it would be valid behavior (because `z`, not being a valid cipher string can be ignored).  [ciphers(1)][2] does not seem to allow such interpretation, though (or at very least this is very counterintuitive).

  [1]: https://bugzilla.redhat.com/show_bug.cgi?id=1547067
  [2]: https://www.openssl.org/docs/man1.1.0/apps/ciphers.html

I'm observing this with `openssl-1.1.0g-1.fc26` on Fedora 26.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #5420 
##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by AloisMahdal** [comment]
Sorry, but "does not need to be separated from rest of the cipherstring" does not make so much sense given that the subject *is* a cipherstring (notice difference between *cipherlist* and *cipherstring* in man page).

Also the #5420 is about `DEFAULT`, not `COMPLEMENTOFDEFAULT`.

**Comment by AloisMahdal** [comment]
IOW, the behavior (as I observed it--the actual processing in the code might be superset of that) seems to me as completely different syntax of *cipherlist*.

**Comment by vdukhovni** [comment]
In addition to opposing the documentation change (to freeze-in a bug), the real documentation lapse with "DEFAULT" is that unlike various more "primitive" cipherlist elements, it does not support additional boolean combinations, e.g. "DEFAULT+kECDHE" or similar.  It is a special "macro" that can only occur at the start of the list, and is logically replaced with its definition, and then anything else that follows after the next ":".

We can document that limitation as a non-bug, is that is less likely to change, is a good part of the reason why "DEFAULT" is first.  This PR is not progress as it stands IMHO.

**Comment by t8m** [comment]
Victor, would you be able to propose a different PR with your suggestions?

**Pull request closed without merging**
