### PR TITLE
Fix coverity 1451515: out of bounds memory access

### PR DESCRIPTION
**Pull request by paulidale**

### CODE REVIEW

**Comment by t8m** [comment]
Present in 1.1.1 as well. Is this possibly CVE worthy?

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
My big question would be if it is possible or not.
But yes, it might be worth considering for a CVE.

**Comment by paulidale** [comment]
Definitely not CVE.  The problem can only occur if the client callback writes over the end of the buffer -- i.e. it's an application programming error.

**Comment by paulidale** [comment]
Merged to master and 1.1.1 (after a trivial fix for a conflict).

**Pull request closed without merging**
