### PR TITLE
util/perl/OpenSSL/OID.pm: remove the included unit test

### PR DESCRIPTION
**Pull request by levitte**
The unit test uses features that appeared in perl 5.12, and is
therefore a source of trouble when building.

### CODE REVIEW

**Comment by levitte** [comment]
Merged

6d81bb2676f6a210f15f17324ab6852f52cc7f55 util/perl/OpenSSL/OID.pm: remove the included unit test

**Comment by romen** [comment]
@levitte is there a way to retrieve this test by making it conditional to the perl version?

Or is there a good reason why this test is not important anymore?

**Comment by levitte** [comment]
We never ran that test suite, but the original that this comes from (see comment at the beginning of the module) does.

**Comment by levitte** [comment]
But to answer your question, I don't think it's possible to have part of a module considered separately depending on the perl version. It's an interesting idea, but...

**Comment by romen** [comment]
Ah great, thanks for answering!

**Comment by richsalz** [comment]
It might be worthwhile putting it into the regular test suite.

**Comment by levitte** [comment]
I dunno.  After all, it's run during the build, so testing it as part of the test suite becomes an afterthought...

**Pull request closed without merging**
