### PR TITLE
Have the Travis builds do a "make update"

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by richsalz** [comment]
+1 once the build is clean.

**Comment by levitte** [comment]
Heh, you know as well as I that this build *will* fail.  If it fails on `make update`, then this PR is doing exactly what it should and is therefore a success ;-).  Are you ok with that criterium?

**Comment by richsalz** [comment]
Yes, exactly

**Comment by levitte** [comment]
Hmmm, on some of the Travis builds, `make update` didn't fail.  Curious.  But, for `.travis.yml`, I still say this is a success.  If `make update` fails, the build will fail, and if `make update` doesn't fail, neither does the  build.  Good enough for a merge?

**Comment by richsalz** [comment]
So maybe it’s not perfect, it’s definitely better. Ship it.

**Comment by levitte** [comment]
Shipped

**Pull request closed without merging**
