### PR TITLE
Fix no longer implicitly refresh the cached TBSCertificate for 3.0+

### LINKED ISSUE #19388: Regression: X509_sign, etc., no longer implicitly refresh the cached TBSCertificate
#18879 regressed `i2d_re_X509_REQ_tbs` by setting the modified bit after, rather than before, serializing the TBS structure, which was fixed in #19299. It looks like that wasn't the only such regression. It did the same to `X509_sign` and friends.

The changes in that PR to x_all.c should be reverted. The aim with setting the modified bit in `X509_sign` is not to mark that something changed, but to refresh the cached TBS structure before signing it. (OpenSSL's `X509` API returns too many mutable pointers to properly manage that dirty bit automatically, alas.)

(Marking the TBS structure dirty after adding a signature doesn't make sense because the signature isn't in the TBS structure.)

The practical implications here are that code which starts with an existing, parsed `X509` object as template (so the cache is filled), then modifies it and re-signs it, will break in OpenSSL 1.1.1r and 3.0.6. Likewise with the other crypto/x509 types.

### PR DESCRIPTION
**Pull request by gibeom-gwon**
…call was successful"

This reverts commit 9249a34b076df9a9d55ab74ab465d336980cae6a. Fixes #19388

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by kroeckx** [comment]
It would be nice if we had some tests covering the expected behaviour so that it doesn't regress again, and maybe some comments to explain the variable.

**Comment by gibeom-gwon** [comment]
Thanks @slontis for the test, and I added comments about `modified` variable. Please let me know if there are any content or grammatical errors.

**Comment by t8m** [comment]
ping for second review.

**Review by tmshort — APPROVED** [review]
LGTM

**Comment by hlandau** [comment]
Looks like this wasn't closed. I believe this has now been merged to master and 3.0. Thank you.

**Pull request closed without merging**
