### PR TITLE
Travis: try a non sudo container

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by kroeckx** [comment]
This gives us the same errors as we see in the 1.1.0 stable branch

**Comment by kroeckx** [comment]
@ekasper: Is there any reason you used sudo: required? It seems to work fine in the non-sudo container now.

**Comment by ekasper** [comment]
@kroeckx the cross-compile tests use sudo. Try adding [extended tests] to the commit message to run all tests.

(FWIW I think it's thoroughly confusing that tests appear as "passed" that were in fact not run.)

**Comment by levitte** [comment]
> @kroeckx the cross-compile tests use sudo. Try adding [extended tests] to the commit message to run all tests.

D'oh.  I'm retracting my approval

**Pull request closed without merging**
