### PR TITLE
Unix Makefile: Some sed implementation truncate long lines.  Use perl instead

### LINKED ISSUE #1781: Build problem on Solaris 8
I am trying to build openssl 1.1.0b on a Solaris 8 sparc box. Building on Solaris 10 sparc with the same
configure command works OK. The Configure command line is:

./Configure shared --prefix=/opt/verylocal enable-rc5 enable-mdc2 zlib-dynamic  -I/opt/verylocal
/include -R/opt/verylocal/lib solaris-sparcv9-cc

Perl is v5.22.2 and C is Forte Developer 7 C 5.4.

Make finishes without error and all the libraries are made. But if I type make test or just make, make
now complains as follows:

> gmake
> gmake depend && gmake _all
> gmake[1]: Entering directory `/home/projects/tools/openssl/openssl-1.1.0b.sol8'
> gmake[1]: Leaving directory`/home/projects/tools/openssl/openssl-1.1.0b.sol8'
> gmake[1]: Entering directory `/home/projects/tools/openssl/openssl-1.1.0b.sol8'
> gmake[1]: *** No rule to make target`crypto/co', needed by `libcrypto.a'. Stop.
> gmake[1]: Leaving directory`/home/projects/tools/openssl/openssl-1.1.0b.sol8'
> gmake: **\* [all] Error 2

If I create an empty crypto/co  with touch, make now proceeds to add crypto/co to libcrypto.a  and
then recreate the shared libraries and re-link everything. Now I can run make test without finding
any missing files.

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [x] CLA is signed

##### Description of change

instead.

Fixes #1781

### CODE REVIEW

**Comment by t-j-h** [comment]
Is that placing a dependency on having perl to run a build now that wasn't present before?

**Comment by levitte** [comment]
> Is that placing a dependency on having perl to run a build now that wasn't present before?

Nope.  We're using perl all over the place.

**Comment by richsalz** [comment]
yeah,. perl is a requirement.  +1

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
... and @teschulz confirmed the fix is working as well.  Perfect.

**Comment by levitte** [comment]
Merged!

**Pull request closed without merging**
