### PR TITLE
Recycle the TLS key that holds thread_event_handler

### PR DESCRIPTION
**Pull request by zhihaoy**
fixes: #25278

### CODE REVIEW

**Comment by zhihaoy** [comment]
`tlocal` may need to be freed here as well https://github.com/openssl/openssl/blob/c37e21763b1d460b06a4f94baf6682f96000810f/crypto/initthread.c#L291-L294

**Comment by zhihaoy** [comment]
QUIC people please help.

**Comment by slontis** [comment]
When the fips provider starts up it runs self tests.
If the self tests fail (probably due to your change somehow), the fips provider goes into an error state.
So any requests for crypto to the fips provider will just return an error after this point.

**Comment by zhihaoy** [comment]
> When the fips provider starts up it runs self tests. If the self tests fail (probably due to your change somehow), the fips provider goes into an error state. So any requests for crypto to the fips provider will just return an error after this point.

That doesn't explain why only the quic case failed while there are many test cases in the enable-fips flow.

**Comment by slontis** [comment]
You would need to debug..

After you build,
run make tests just to run the first test and then quit (this generates the fipmodule.conf needed)..
And then run something similar to the following..
(This is what I run on linux)

````
LD_LIBRARY_PATH=. OPENSSL_MODULES=providers OPENSSL_CONF_INCLUDE=test ./test/quicapitest fips test/fips-and-base.cnf test/certs some_dir
````

some_dir is just an existing directory to write test data to - so change the name to whatever suits you.

**Comment by slontis** [comment]
Check to see if OSSL_provider_init_int() in fipsprov.c returns 0.

**Comment by slontis** [comment]
Breaking in ossl_set_error_state() in self_test.c should also help.

**Comment by zhihaoy** [comment]
Progress so far: looking into this part in gdb. The interesting bit about the QUIC test is that it's the only place that involves two threads accessing the FIPS provider. Looking at my R0 proposed change again with that information, `ossl_ctx_thread_stop` is not the right place to `TlsFree`.

**Pull request closed without merging**
