### PR TITLE
Remove all trace of FIPS_mode functions

### PR DESCRIPTION
**Pull request by richsalz**
Removed error codes, and the mention of the functions.
This removal is already documented in the CHANGES doc.

Nerd-sniped by @mspncp's comment https://github.com/openssl/openssl/pull/15132#issuecomment-831853316 :)

### CODE REVIEW

**Review by mspncp — APPROVED** [review]
[LGTM](https://imgs.xkcd.com/comics/nerd_sniping.png)

**Review by slontis — APPROVED** [review]

**Review by paulidale — APPROVED** [review]
It feels good to see old cruft disappearing...

**Comment by richsalz** [comment]
> It feels good to see old cruft disappearing...

If I could only do a PR to remove 30 pounds :)

**Comment by mspncp** [comment]
> If I could only do a PR to remove 30 pounds :)

Don't let them pull too hard, you might regret it...

neulich_beim_masseur_101108_2345_2

**Comment by paulidale** [comment]
Merged to master, thanks for this.

**Pull request closed without merging**
