### PR TITLE
Add SM2 support for EVP_PKEY_Q_keygen

### PR DESCRIPTION
**Pull request by FlyGoat**
There is no reason preventing this API to support SM2, which gives us a simple method to do SM2 key gen.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by slontis — COMMENTED** [review]
Try adding a similar test to the ones in evp_extra_test2.c
See line 362: test_ec_tofrom_data_select()

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
Could you please amend the commit message with `git commit --amend` so it contains `CLA: trivial` on a separate line in the commit message body?

**Comment by paulidale** [comment]
Agreed that this can count as trivial.

**Comment by hlandau** [comment]
Agree trivial

**Comment by FlyGoat** [comment]
Pushed with:

```
tests: exempted
CLA: trivial
```

**Comment by slontis** [comment]
If it is so trivial to write test why are we deferring it..

**Comment by t8m** [comment]
> If it is so trivial to write test why are we deferring it..

For example because it would no longer be a CLA: trival change.

**Comment by mattcaswell** [comment]
> For example because it would no longer be a CLA: trival change.

Trying to see the section in our testing policy that says that's a reason to not include tests...

**Comment by t8m** [comment]
> Trying to see the section in our testing policy that says that's a reason to not include tests...

That's why I've added `tests: deferred` and not `tests: exempted`!

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master, 3.1, 3.0 branches. Thank you for your contribution. I'll add test in a followup PR.

**Pull request closed without merging**
