### PR TITLE
Make speed benchmark support the SM3 hash algorithm.

### PR DESCRIPTION
**Pull request by 0x9527-zhou**
test results:

[root@openssl]# /opt/openssl/bin/openssl speed sm3
Doing sm3 for 3s on 16 size blocks: 9657786 sm3's in 2.99s
Doing sm3 for 3s on 64 size blocks: 5748529 sm3's in 3.00s
Doing sm3 for 3s on 256 size blocks: 2468054 sm3's in 3.00s
Doing sm3 for 3s on 1024 size blocks: 817668 sm3's in 3.00s
Doing sm3 for 3s on 8192 size blocks: 113456 sm3's in 3.00s
Doing sm3 for 3s on 16384 size blocks: 57138 sm3's in 3.00s
version: 3.1.0-dev
built on: Thu Feb 17 08:15:18 2022 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0xfffa32034f8bffff:0x1c009c47ab
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
sm3              51680.46k   122635.29k   210607.27k   279097.34k   309810.52k   312049.66k
[root@openssl]# /opt/openssl/bin/openssl speed -evp sm3
Doing sm3 for 3s on 16 size blocks: 9624213 sm3's in 3.00s
Doing sm3 for 3s on 64 size blocks: 5728523 sm3's in 3.00s
Doing sm3 for 3s on 256 size blocks: 2451121 sm3's in 3.00s
Doing sm3 for 3s on 1024 size blocks: 815629 sm3's in 3.00s
Doing sm3 for 3s on 8192 size blocks: 112035 sm3's in 3.00s
Doing sm3 for 3s on 16384 size blocks: 56448 sm3's in 3.00s
version: 3.1.0-dev
built on: Thu Feb 17 08:15:18 2022 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0xfffa32034f8bffff:0x1c009c47ab
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
sm3              51329.14k   122208.49k   209162.33k   278401.37k   305930.24k   308281.34k
[root@AnolisOS-163 openssl]# /opt/openssl/bin/openssl speed -multi 2 sm3
Forked child 0
+DT:sm3:3:16
Forked child 1
+DT:sm3:3:16
+R:9561060:sm3:3.000000
+DT:sm3:3:64
+R:9552519:sm3:3.000000
+DT:sm3:3:64
+R:5618988:sm3:3.000000
+DT:sm3:3:256
+R:5595770:sm3:3.000000
+DT:sm3:3:256
+R:2444156:sm3:3.000000
+DT:sm3:3:1024
+R:2436615:sm3:3.000000
+DT:sm3:3:1024
+R:791236:sm3:3.000000
+DT:sm3:3:8192
+R:790780:sm3:3.000000
+DT:sm3:3:8192
+R:111181:sm3:3.000000
+DT:sm3:3:16384
+R:110760:sm3:3.000000
+DT:sm3:3:16384
+R:56391:sm3:3.000000
+R:56201:sm3:3.000000
Got: +H:16:64:256:1024:8192:16384 from 0
Got: +F:29:sm3:50992320.00:119871744.00:208567978.67:270075221.33:303598250.67:307970048.00 from 0
Got: +H:16:64:256:1024:8192:16384 from 1
Got: +F:29:sm3:50946768.00:119376426.67:207924480.00:269919573.33:302448640.00:306932394.67 from 1
version: 3.1.0-dev
built on: Thu Feb 17 08:15:18 2022 UTC
options: bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0xfffa32034f8bffff:0x1c009c47ab
sm3             101939.09k   239248.17k   416492.46k   539994.79k   606046.89k   614902.44k

### CODE REVIEW

**Comment by t8m** [comment]
The sm3 benchmark is available with -evp sm3. I am not sure we want this.

**Comment by 0x9527-zhou** [comment]
> The sm3 benchmark is available with -evp sm3. I am not sure we want this.

Just like other hash algorithm.

**Comment by paulidale** [comment]
Do we want this alternative to the -evp option?

**Comment by t8m** [comment]
Closing this as benchmarking SM3 is supported by `-evp sm3`

**Pull request closed without merging**
