### PR TITLE
doc: update copyright year in README.md

### PR DESCRIPTION
**Pull request by preveen-stack**
Updated the end copyright year in README.md to 2023

##### Checklist

- [ x] documentation is added or updated

 CLA: trivial

### CODE REVIEW

**Comment by preveen-stack** [comment]
@openssl-machine I have amended the commit message with the " CLA: trivial " line. You may please remove the hold: cla required label.

**Review by paulidale — APPROVED** [review]

**Comment by tmshort** [comment]
This should _not_ be a FIPS change‽‽

**Review by levitte — APPROVED** [review]

**Comment by paulidale** [comment]
No, it shouldn't be flagged as a FIPS change.

**Comment by tmshort** [comment]
CI failures should not be related. I mean, this is _literally_ just updating the readme.

**Comment by paulidale** [comment]
Merged.  Thanks for the fix.

**Comment by DimitriPapadopoulos** [comment]
See also #21265.

**Pull request closed without merging**
