### PR TITLE
Update extensions.c

### LINKED ISSUE #13183: SSL_CTX_sess_accept gives negative value
Hi,
I am seeing this issue in openssl-1.1.1d.
These are the steps to see the negative value.
* Start with a default SSL_CTX, initiate a TLS 1.3 connection with SNI, "Accept" count of default context gets incremented
* After servername lookup, "Accept" count of default context gets decremented and that of SNI context is incremented
* Server sends a "Hello Retry Request"
* Client sends the second "Client Hello", now again "Accept" count of default context is decremented. Hence giving a negative value.

Please let me know if you need any more information on this.

### PR DESCRIPTION
**Pull request by anupamam13**
Fixes #13183

" CLA: trivial "

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
This change looks good - so approved.

It would be nice if you could provide a more descriptive comment in the commit message explaining why this was necessary. Also this PR has 5 commits in it (including a merge commit which is not allowed). It would be good if they can all be replaced by a single commit - or alternatively this can be done at merge stage by whoever commits this to the repo.

For the record, I agree this is trivial.

**Review by kaduk — COMMENTED** [review]
I started working on a similar change locally, but did not want to make a pull request without tests.

**Review by paulidale — APPROVED** [review]
I'm with @mattcaswell, a better description would be very beneficial.

**Comment by slontis** [comment]
This is also based off 111 as opposed to master.

**Comment by romen** [comment]
As the reviewers suggested it but this has been stalling for quite a long time, I took the liberty of editing the commit message to incorporate the description that @anupamam13 wrote in #13183 plus the rationale behind the change implemented here as expained by @kaduk in the same issue.

I am assuming this is fine given that these are the author's words anyway, and that those that aren't are a straight-forward description of the change given its trivial nature.

**Comment by romen** [comment]
Merged to `master` with

- 42141197a1 *Fix for negative return value from `SSL_CTX_sess_accept()`*

and to `1.1.1` with:

- 212d7118a7 *Fix for negative return value from `SSL_CTX_sess_accept()`*


Thanks @anupamam13 , and congratulations on your first merged contribution to the project!

**Pull request closed without merging**
