### PR TITLE
Revert "Fix AES-CBC perf test failure issue"

### PR DESCRIPTION
**Pull request by paulidale**
This reverts commit bec9289143c955b330a8f9ad32f26f3da76e2685 because I stuffed up merging #14778

### CODE REVIEW

**Comment by paulidale** [comment]
Adding urgent since this fixes a crazy mistake.

**Comment by slontis** [comment]
Not sure I understand what this change does (or doesn't do)..

**Comment by mattcaswell** [comment]
So - just so that I understand - you merged the wrong PR when merging #14778? You accidentally merged the alternative (unapproved) #14777 instead?

**Review by mattcaswell — APPROVED** [review]
Assuming I'm correct above - approved.

**Comment by paulidale** [comment]
Yep, spot on.  A single digit typo :(

**Comment by paulidale** [comment]
Merged to fix the mistake.

**Pull request closed without merging**
