### PR TITLE
sha/keccak1600.c: add pair of optimized implementations.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by t-j-h** [comment]
Performance improvements measurements are?

**Comment by dot-asm** [comment]
When it comes to optimizations correct question actually is not how much faster does this or that get, but how far is it from theoretical limit. Latter is naturally platform-specific. But to make such estimates you have to be intimately familiar with algorithm [and platform]. So I'm getting acquainted with permutation patters, dependency chains... Haven't actually measured anything yet...

**Comment by t-j-h** [comment]
Actually what counts is what has been achieved. Whether more is possible is answering an entirely separate question. You have put this up as optimised. It needs measurements to know if that is true and to what level to know if it makes sense to commit.

**Comment by kaduk** [comment]
Should any of this be macro-ized?  Comments on any of the functions?

**Comment by dot-asm** [comment]
> Should any of this be macro-ized?

Maybe. It's a tricky question. It's a balance between how large textual presentation of the code is and how easy is it to "visualize" the flow. Current focus is latter. It might change in future. If I learned anything is that it pays off to "visualize" the flow... Besides it's actually problematic to macro-ize 1X variant, because `T[][]` references are irregular. As for comments, added.

Side note. Even though 4X is referred to as "[probably] best instruction per processed byte ratio", 2X effectively provides same ratio, but at 1/2 code size, which is also an advantage, as it takes less time to warm code cache. For reference, I reckon that full unroll is meaningless to consider, because it would be too tough on L1 code cache for marginal improvement it can provide with warm cache.

**Comment by dot-asm** [comment]
Minor commentary updates.

**Comment by dot-asm** [comment]
As for macro-ization and current focus being "flow visualization". It's also meant to be used as possible reference for assembly implementation[s] and excessive macro-ization (say on complete row operations) would make it harder to single-step and compare results side by side. In case question is why not assembly from https://github.com/gvanas/KeccakCodePackage. Some portions will surely be re-used, but I would still insist on at least understanding the algorithm better than just calling a subroutine.

**Comment by dot-asm** [comment]
As for "what has been achieved" and if "it's true". Loop fusion and code motion is recognized optimization technique. True or not? Achieved or not? It makes sense to optimize references to temporary storage. True or not? Achieved or not? 2x unroll minimizes references to temporary storage. True or not? Achieved or not? 4x eliminates need for temporary storage. True or not? Achieved or not? Or was it rendered worthless as template for assembly implementation in result of proposed modification?

**Pull request closed without merging**
