### PR TITLE
Explicitly enable or disable fips if it is or is not relevant for the test

### PR DESCRIPTION
**Pull request by t8m**
We might change the default to not build the fips module. But we still want to build it in most of the CI test builds.

Related to #13684 

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by mspncp — APPROVED** [review]
I see three jobs (check_update, check_docs, minimal) for which you didn't  enable/disable fips explicitly. I assume you did that deliberately?

**Comment by t8m** [comment]
> I see three jobs (check_update, check_docs, minimal) for which you didn't enable/disable fips explicitly. I assume you did that deliberately?

Yes, check_update and check_docs does not do build, so it is really irrelevant whether fips is or isn't enabled and the minimal has no-bulk which includes no-fips.

**Comment by t8m** [comment]
@mspncp you can cherry pick b33a401 to your PR or we might just merge this PR first.

**Comment by mspncp** [comment]
I'll rebase mine on yours this evening, and merge it after yours.

**Comment by mspncp** [comment]
Since I need to rebase on master to resolve conflicts, I decided to cherry-pick your fixes before rebasing.

**Comment by mspncp** [comment]
Second force-push was a plain rebase without changes to the PR to resolve the conflicts in CHANGES.md.

**Comment by mspncp** [comment]
Ups, the last two comments were intended for #13684.

**Review by mspncp — APPROVED** [review]
I thought I had approved the second commit already. Anyway, reapproved.

**Comment by t8m** [comment]
@mspncp I've decided to explicitly enable fips also for the check_update and check_docs in case it becomes relevant in future as in #8871. Still OK?

**Review by mspncp — APPROVED** [review]
Yup, ok. FWIW: this trivial change does not require resetting the grace period imho.

**Comment by t8m** [comment]
Merged to master. Thank you for the review!

**Pull request closed without merging**
