### PR TITLE
QUIC TXP: Probe Emission Support & fix rollups

### PR DESCRIPTION
**Pull request by hlandau**
This ended up not needing any changes to the CSM. Because of that, I've elected to extract out the relevant commits so that they can be reviewed separately, as I believe they should be able to be merged separately.

This combines a rollup of various tweaks and fixes to the ACKM and TXP needed to support the CSM with the probe implementation changes. The former are fairly constrained so I don't believe they should pose that much of a challenge for review, and can be merged independently of the CSM. Moreover, it will make the CSM PR smaller once merged.

```
--- Probe Implementation ---
7dd56835e0 QUIC TXP: Allow TXP to generate probes
d3e49d9900 QUIC ACKM: Rework probe reporting to allow use for bookkeeping
aa7e4db629 QUIC ACKM: Clarify probe types
--- Commits from CSM/server/FIN PRs ---
3f7025262b QUIC TXP: Fix handling of FIN stream chunks
84c1a25224 QUIC TXP: Fix generation of CONNECTION_CLOSE
b9e714d19d QUIC TXP: Correct an issue with an uninitialized variable
06ee4d6811 QUIC TXP: Don't send STREAM frames until handshake is complete
2c9716df1a QUIC TXP: Make discard_enc_level match documentation
0f461f55f6 QUIC TXP: Add a function to query if the TXP wants to generate a packet
b36633bd21 QUIC ACKM: Add function to get PTO
4800422954 QUIC ACKM: Add support for psuedo-loss
```

### CODE REVIEW

**Review by t8m — APPROVED** [review]
Apart from the char/int for flag value consideration this is OK.

**Comment by h-vetinari** [comment]
> `4800422954 QUIC ACKM: Add support for psuedo-loss`

General comment (from watching these PRs) about two frequently recurring typos:
* supercede -> [supersede](https://writingexplained.org/supercede-vs-supersede-difference)
* psuedo -> [pseudo](https://www.thefreedictionary.com/pseudo)

**Review by t8m — APPROVED** [review]

**Comment by hlandau** [comment]
Looking for a second approval.

**Comment by hlandau** [comment]
Rebased. Needs reapproval and still looking for a second approval.

**Review by t8m — APPROVED** [review]

**Review by mattcaswell — CHANGES_REQUESTED** [review]

**Comment by hlandau** [comment]
Updated.

**Review by mattcaswell — APPROVED** [review]
Approved.

@t8m please reconfirm

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master branch. Thank you.

**Pull request closed without merging**
