### PR TITLE
Move providers/common/{ciphers,digests}/* to providers/implementations

### PR DESCRIPTION
**Pull request by levitte**
The idea to have all these things in providers/common was viable as
long as the implementations was spread around their main providers.
This is, however, no longer the case, so we move the common blocks
closer to the source that use them.

### CODE REVIEW

**Review by paulidale — DISMISSED** [review]

**Comment by levitte** [comment]
> CI failures might be relevant.

Very relevant.  Fixed

**Review by paulidale — APPROVED** [review]

**Comment by slontis** [comment]
LGTM

**Comment by levitte** [comment]
Merged.

68a51d59a29796803af3b6e7f0142feca2622c9e Move providers/common/{ciphers,digests}/* to providers/implementations

**Comment by levitte** [comment]
I've discovered that there are "common" things that aren't so "common".  Follow-up PR coming up

**Pull request closed without merging**
