### PR TITLE
Stop using and deprecate ENGINE_setup_bsd_cryptodev

### PR DESCRIPTION
**Pull request by levitte**
The calls we made to it were redundant, as the same initialization is
done later in OPENSSL_init_crypto() anyway.

---

Inspired by #1285

### CODE REVIEW

**Comment by vdukhovni** [comment]
Please check that this is OK with Christos Zoulas (NetBSD OpenSSL maintainer).

**Comment by levitte** [comment]
Okie, will do

**Comment by richsalz** [comment]
merge it!

**Comment by levitte** [comment]
Cool, and I just got a LGTM from Christos (both on this and on #1285), so all is fine :-)

**Comment by levitte** [comment]
Found a fault, be back with an update in a few

**Comment by levitte** [comment]
Ok, looks like it's going better now...  @richsalz , reconfirm?

**Comment by richsalz** [comment]
reconfirm

**Comment by levitte** [comment]
Ok, thanks!  Merged

**Pull request closed without merging**
