### PR TITLE
Add github action for macosx

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Eventually this could become part of a matrix in CI.yml. But for now just get it to build.. Note that mac consumes lots more minutes resources (10 * ??)..

**Comment by levitte** [comment]
Another way would be this:

``` yaml
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 85fbe952dc..18a700438c 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -71,7 +71,10 @@ jobs:
       run: make test HARNESS_JOBS=${HARNESS_JOBS:-4}
 
   minimal:
-    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        os: [ ubuntu-latest, macos-latest ]
+    runs-on: ${{matrix.os}}
     steps:
     - uses: actions/checkout@v2
     - name: config
```

A positive thing with this is that if it doesn't build on one of the listed operating systems, builds on the remaining ones are automatically cancelled.

**Comment by t8m** [comment]
I do not think we would want to run many different builds on MacOSX but the minimal build is really too limited. I suppose doing the basic possibly with an additional install phase would be sufficient?

**Comment by levitte** [comment]
> I do not think we would want to run many different builds on MacOSX but the minimal build is really too limited. I suppose doing the basic possibly with an additional install phase would be sufficient?

Sounds good to me

**Comment by slontis** [comment]
I will add it to the out-of-source-and-install

**Comment by levitte** [comment]
Do you plan to add it elsewhere in this PR, or is it time for final review?

**Comment by slontis** [comment]
Isnt where I put it now good enough to test it?

**Comment by levitte** [comment]
It is good enough

**Review by levitte — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by slontis** [comment]
Thanks for the input.. Merged to master.

**Pull request closed without merging**
