### PR TITLE
[WIP] Support calling SHA3_squeeze multiple times

### PR DESCRIPTION
**Pull request by kroeckx**
This allows to call EVP_DigestFinalXOF multiple times.

This is WIP because all the assembler versions of SHA3_squeeze need to be modified.

It contains a commit from #13402.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
I'm not sure it's a good idea to use the `EVP_DigestFinalXOF` function for this purpose. It seems an API change compared to the current behaviour.

IMHO, the KDF API fits your intentions better

**Comment by t8m** [comment]
> I'm not sure it's a good idea to use the `EVP_DigestFinalXOF` function for this purpose. It seems an API change compared to the current behaviour.
> 
> IMHO, the KDF API fits your intentions better

I do not think it would be an API break on EVP_DigestFinalXOF - calling it multiple times without re-initializing the context is IMO currently undefined behavior. So we could define it to mean to mean final + squeeze on first call and further calls would do just additional squeezes.

I agree with @kroeckx that is is actually very useful interface that we should support. We should at least avoid setting to stone that multiple EVP_DigestFinalXOF are not allowed with 3.0 so we can implement it in 3.1.

**Comment by kaduk** [comment]
I am not sure that we want to do this at all -- I don't have a picture in my mind of how this could be used to encourage safe application behavior (and indeed have worries that it would lead to *un*safe application behavior).  Do you have some cases in mind for how you envision applications using this functionality?

**Comment by paulidale** [comment]
Would an additional function to squeeze out more data be more appropriate than calling final multiple times?

I'd like to see our algorithms as mini state-machines where illegal/invalid/crazy calls result in errors.

**Comment by kroeckx** [comment]
When I was looking at this in the 1.1.1 branch, I could return an
error in case it's not a XOF, but it seems I can't get to that
information anymore in master.

**Comment by t8m** [comment]
I do not see a reason to have a separate API call (which would have to be added to the providers API as well) when all that would be sufficient is to record whether the final was already called and just call the squeeze if it was.

IMO the provider implementation should be responsible for returning error in case Final is called multiple times for non XOF hashes.

**Comment by t8m** [comment]
We have squeeze support implemented. Closing the PR.

**Pull request closed without merging**
