### PR TITLE
fix spelling error

### PR DESCRIPTION
**Pull request by andreasschulze**
- [x] documentation is added or updated

trivial fix for a spelling error in a manpage
CLA: trivial

### CODE REVIEW

**Comment by mspncp** [comment]
Reconfirmed (for second commit).

@andreasschulze if you don't mind, I would like to squash both commits into a single one with the following commit message:

```
Fix two spelling errors

CLA: trivial
```

This saves precious disk space worldwide and helps preserving the rain forest ;-).

**Comment by mspncp** [comment]
@andreasschulze I just noticed that you previously committed with a different email address (see aa3b328541ff67dde7c40ae73dd11a296647ae3d). Do you really want to use a new address? If you prefer using the other one, please let me now. You can either change the author email address yourself and force-push, or ask me to change it for you.  (Either way, you would have to change your locally configured email address and the GitHub email address for the next time).

**Comment by andreasschulze** [comment]
@mspnsp removed the "sca+git*" mailaddress from my github account. Now "git@and..." is the only address I intend to use. Thanks for pointing to this confusion

**Comment by mspncp** [comment]
Merged, thanks!

3dcbb6c4a3 master
d38ef8c89e 1.1.1

**Pull request closed without merging**
