### PR TITLE
rand: allow seed sources to be given a parent

### PR DESCRIPTION
**Pull request by paulidale**
The parent is then ignored.

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
@paulidale looks like there is a issue on master..

**Comment by slontis** [comment]
Generally if something is a 'source',  it doesnt have a parent. So this sounds a bit wonky..

**Comment by paulidale** [comment]
I know, but do we need to check and enforce the no-parent part?
There is a legitimate reason to make the primary DRBG a seed source feeding the public and private ones: FIPS compliance now that chaining is out, at least temporarily.

**Comment by rsbeckerca** [comment]
> I know, but do we need to check and enforce the no-parent part? There is a legitimate reason to make the primary DRBG a seed source feeding the public and private ones: FIPS compliance now that chaining is out, at least temporarily.

Will this apply to automatically seeded hardware randomizers? Asking for a friend.

**Comment by paulidale** [comment]
You'll need to configure things appropriately, so not automatically.

**Comment by rsbeckerca** [comment]
> You'll need to configure things appropriately, so not automatically.

What I have is configuring `rdcpu`. Is there more?

**Comment by paulidale** [comment]
There will be.  Details uncertain until the direction is chosen -- i.e. this might not be the final solution.

**Review by Sashan — APPROVED** [review]
looks good to me.

**Comment by t8m** [comment]
This allows for _misconfiguring_ a seed source as a direct private/public RNG.  I assume that for GETRANDOM or properly whitened jitter source it is OK. However there might be seed sources which do not provide such output. Should we somehow prevent that in a different way?

**Review by xnox — CHANGES_REQUESTED** [review]
I think this alone will not do much.

The intention, as described in #25168 is to provide mechanisms to get entropy into drbg, without an interim primary drbg.

This code will allow to initiate for example "public" drbg as type seed-src with parent set to primary. Yet chaining will remain in place, as `drbg->parent_get_seed` is always used. And the rest of the logic stops making any sense too, despite not really needed for these drbgs at all.

We might want this change, but IMHO we should only consider it, if it is included as part of a complete unchaining solution which works, and has tests. As without all that, this change may have unintended consequences which are untested.

**Comment by paulidale** [comment]
@t8m, yes we should make an effort -- **if this approach is taken**.

Jitter is careful about each bit being produced being equiprobable so should be okay without whitening.  Likewise, getrandom, getentropy, RDRAND should also be.  But not all.  Autocorrelation also comes into play, most sources do not guarantee that they are free from this.

I'm not sure about the FIPSness of not including a DRBG. That would be a lab question I suspect.

**Comment by paulidale** [comment]
Turns out there was an open request for exactly this: #18026

**Pull request closed without merging**
