### PR TITLE
Sync 1.1.1 GitHub CI with master

### PR DESCRIPTION
**Pull request by romen**
This is an attempt at syncing the GitHub CI infrastructure for the 1.1.1 branch with what we do in `master`

# Tasks

- [x] Sync `ci.yml` file
  - [x] Ensure tests are running
- [x] Import `windows.yml`
  - [x] Ensure tests are running
- [x] Import `cross-compiles.yml`
  - [x] Ensure tests are running
- [x] Import run-checker workflows
  - [x] Ensure tests are running
- [x] Disable problematic tests (they will be dealt with in separate PRs)
  - 9c3a9ab176 `[cross-compiles.yml] Disable sparcv9`
    - [x] Dedicated PR: #16336
  - f73c3720e1 `[ci.yml] Disable krb5 external tests`
    - [x] Dedicated PR: #16339
  - 850ed18505 `[ci.yml] Disable pyca external tests`  
    - [x] Dedicated PR: #16340
  - f9c3c9cdff `[run-checker-ci.yml] Disable no-tls1_3 tests`
    - [x] Dedicated PR: #16335
  - e88314973a `[ci.yml] Disable memory sanitizer build` (fails due to timeout)
    - [x] Dedicated PR: #16338
  - 111244dec5 `[run-checker-merge.yml] Disable ubsan build`
    - [x] Dedicated PR: #16337
- [x] Evaluate `run-checker-daily.yml`

### CODE REVIEW

**Comment by t8m** [comment]
Missing CI is of course bug. But I would not spend much time trying to fix for example the failing cross-compiles.

**Comment by t8m** [comment]
And I would not expect all the run-checker jobs to work out of the box on 1.1.1.

**Comment by romen** [comment]
Thanks for the feedback @t8m !

I added a roadmap to the description on top to track the progress, and included your feedback

**Comment by t8m** [comment]
In other words, please expect to put quite a lot of work into this, if you want to have the CIs really "synced" with master. IMO a different approach of just adding the Windows CI and maybe the MacOS builds would be more reasonable. Basically to have some coverage similar to what we had with Travis.

**Comment by paulidale** [comment]
Runchecker should work -- we don't run them anymore but we used to and we don't make many changes to 1.1.1.

I do agree that it's not worth a lot of effort getting this going.

**Comment by romen** [comment]
> Runchecker should work -- we don't run them anymore but we used to and we don't make many changes to 1.1.1.
> 
> I do agree that it's not worth a lot of effort getting this going.

I strongly disagree.

Runchecker must be skipping something, because I think I have uncovered at least 3 legit issues, 2 uncertain ones, and there is still room for more.

Also, runchecker only runs post-merge, which is not ideal on what is supposed to be the "stable" branch of our only current production release.

Additionally relying only on runchecker and having exclusively a very minimal CI setup on PRs might deter external contributors, due to lack of access to the miriad of supported options and platforms.

As long as 1.1.1 is supported, we really should have at least as good a CI infrastructure as we had when we were using Travis and Appveyor.

**Comment by romen** [comment]
This PR is now ready for review.

As mentioned in the description, the last 6 commits are disabling some of the imported tests due to failures.

I plan to open separate PRs to revert the disabling commits alongside the fix, or to discuss full removal separately.
This is because each of them warrants a separate discussion, and also to avoid slowing down the review of this PR as I believe it is quite important to improve our current 1.1.1 test coverage ASAP to bring it back to a level comparable to what we had before (non)migrating the CI to a different provider.

**Comment by romen** [comment]
Ping @mattcaswell @t8m @paulidale

**Comment by romen** [comment]
All the disabled tests now have separate PRs dedicated to track the issues.
They cross-reference back to this PR, and are listed in the description post for this PR.

For convenience, here is the list of PRs sprouting from this:

- #16335
- #16336
- #16337
- #16338
- #16339
- #16340

**Review by paulidale — COMMENTED** [review]
Looks okay.  Have you run with all of the tests set to `on: pull_request`.  If not, lots won't be running.

I.e. push a commit that turns this on globally and wait for the tests to finish.....

**Comment by romen** [comment]
> Looks okay. Have you run with all of the tests set to `on: pull_request`. If not, lots won't be running.
> 
> I.e. push a commit that turns this on globally and wait for the tests to finish.....

I was just going to say this!
For the ones running on `push` only, I was monitoring on my fork.

For some reason on my fork the scheduled workflows do not seem to be running.

I will add a `drop!` commit to run them all on `pull_request` so the results will be visible here.

**Comment by paulidale** [comment]
It's not just `push`, there are also the daily tests.

**Comment by romen** [comment]
> It's not just `push`, there are also the daily tests.

Yes, that is what I referred to with "scheduled ones"!

**Comment by romen** [comment]
`1f8d887` whould trigger all workflows

I might have to put this PR back into draft mode as the daily tests were previously untested!

**Comment by romen** [comment]
> I might have to put this PR back into draft mode as the daily tests were previously untested!

Depending on the number of failures I might instead opt for not including the daily tests in this PR, and treat the addition of the daily tests as a separate PR

**Comment by paulidale** [comment]
Looking promising so far.

**Comment by romen** [comment]
> Looking promising so far.

image

@paulidale Color me impressed and surprised!

I was expecting many failures, and not to run that quickly!

Should those just run normally on each PR instead of daily?

**Comment by paulidale** [comment]
The balance is between the time taken and the number of jobs.  We're allowed 180 concurrent jobs in total across the entire project.  Currently we're running about 60 on pull_request, a few more on push and a pile per day.  So three simultaneous PRs should finish quickly enough.  Given that most jobs run quickly, this could scale up to 5 or 6 without problem.

Moving more jobs into the pull_request category will limit the number of parallel builds (from different PRs) we can handle.  We got into quite some strife over this with our older CI hosts -- remember builds taking the best part of a day to run.  We really want to avoid that again.

I've been trying to limit total job time per job to around 20-30 minutes (there are some longer ones I know of), with most jobs running in the sub 5 minute range.  There are some longer lived CIs -- up to an hour and I try to delegate these to push or daily rather than pull_request.

Still, there is no hard and fast rule about what runs when or where.  Make a suggestion about bettering the CIs -- Ideally I'd like the pull_request jobs to be the ones catching most of the problems and the push and daily being predictably boring successes.  Just make an effort to rationally justify the inclusions/changes.

Thinks like the sanitiser builds, we know catch problems often.  So even though they are slow they are worthwhile on pull_request.  A lot of the daily builds are unlikely to catch much since they are checking options can be turned off and on, so they are fine not running as much.  The demarkation between pull_request and pull_request + push is the difficult choice.  I believe we should do all pull_request jobs as part of push too.  The question is how many more should there be.

I don't have a good answer but I think we're converging on a practical number and we should get better as we gain experience.

**Comment by romen** [comment]
> @paulidale perhaps your comment above should be written down, such as a README near the yaml files?

I like the suggestion: I took the liberty of taking Pauli's comment and turning into a README in the workflows folder. Some of it is written in the first person and I kept unchanged: authorship and date match https://github.com/openssl/openssl/pull/16252#issuecomment-900303979

**Comment by romen** [comment]
That being said, all the tests added in this PR are passing, and dropping 1f8d887293ceab01e90a873945b0f8246fb32285 as planned, will result in matching the strategy we adopted in `master`, that @paulidale expressed in its comment.

Everything should be ready for a final review.

**Review by paulidale — APPROVED** [review]
@romen great stuff.

**Comment by romen** [comment]
Merged to `OpenSSL_1_1_1-stable` with:

- c10d86c9fd `[github-ci] Sync ci.yml workflow with master`
- d9fdb3a69e `[github-ci] Import windows.yml workflow from master`
- 048c06124d `[github-ci] Import cross-compiles.yml workflow from master`
- 4c038f59a3 `[github-ci] Import run-checker workflows from master`
- 4c7b49d37d `[github-ci] Import run-checker daily workflow from master`
- aa23aa759c `[github-ci][cross-compiles.yml] Disable sparcv9`
- 7952f04ddf `[github-ci][ci.yml] Disable krb5 external tests`
- 6398f974e9 `[github-ci][ci.yml] Disable pyca external tests`
- ce5b8f101d `[github-ci][run-checker-ci.yml] Disable no-tls1_3 tests`
- 854b6fa89a `[github-ci][ci.yml] Disable memory sanitizer build`
- 9e12ea3ae5 `[github-ci][run-checker-merge.yml] Disable ubsan build`
- a7ce0c00a2 `[github-ci] Add comment about our approach to GitHub Actions CI`


Thanks!

**Pull request closed without merging**
