### PR TITLE
More tests for CLI usage of asymmetric keys

### PR DESCRIPTION
**Pull request by romen**
As followup to #10312 this PR started with adding `req` tests for Ed25519 keys similar to the ones in the parent PR.

I then went ahead and added "Conversion tests" similar to what is currently done for ECDSA keys and other asymmetric keys.

Finally, noticing that there was limited testing for generating and verifying signatures using `dgst` or `pkeyutl` I added more tests to give full coverage for this use case with RSA/DSA/ECDSA/EdDSA keys.

Currently this is limited to Ed25519 keys, as I used RFC 8410 Sec. 10 to retrieve a "test vector" key and could not find something similar in the standards for Ed448.

Note this is currently based on top of #10312 and not on latest `master`, so only the last 2 commits are actually relevant when reviewing.

@levitte (and any other Perl savvy reviewer): I ask forgiveness in advance for the way the perl code is written. Please don't spare any feedback on better ways to achieve what I wanted, so that I can improve my (nonexistent) perl-fu.

##### Checklist
- [x] tests are added or updated

### CODE REVIEW

**Comment by romen** [comment]
Notice https://github.com/openssl/openssl/blob/1ee53d38822258c0c9c41fd1415bf4de935acf1b/test/recipes/20-test_dgst.t#L87-L98

that this last test is always skipped, because of #6988 .

The idea of having it there is so that when we (or a generous contributor) add support for EdDSA in `dgst` line 91 can be simply removed to assist TDD (and include testing for the new feature right away).

**Comment by romen** [comment]
Suggestions are welcome for a "normative" source of test vectors for encoding of Ed448 keys.

**Comment by romen** [comment]
Rebased on latest `master` after #10312 got merged.

Ready for approval.

**Comment by mattcaswell** [comment]
> Currently this is limited to Ed25519 keys, as I used RFC 8410 Sec. 10 to retrieve a "test vector" key and could not find something similar in the standards for Ed448.

While its a nice to have to use a key from the RFC (i.e. to prove that we can read and use such keys), I don't think that's the only type of key we should use. There is a great value from a regression test perspective in using a self-generated key if we can't get one from somewhere else. I'm not aware of a source for "test vector" Ed448 keys, therefore I would just generate one and create tests using that.

Aside from the above this PR looks good and I have no comments.

**Comment by romen** [comment]
> > Currently this is limited to Ed25519 keys, as I used RFC 8410 Sec. 10 to retrieve a "test vector" key and could not find something similar in the standards for Ed448.
> 
> While its a nice to have to use a key from the RFC (i.e. to prove that we can read and use such keys), I don't think that's the only type of key we should use. There is a great value from a regression test perspective in using a self-generated key if we can't get one from somewhere else. I'm not aware of a source for "test vector" Ed448 keys, therefore I would just generate one and create tests using that.
> 
> Aside from the above this PR looks good and I have no comments.

I am actually planning to use this, generated using openssl from the values in RFC 8032:
https://github.com/openssl/openssl/blob/3cc26f2eba8a8c16ac559e68c05c094d7ea6bd8b/test/recipes/30-test_evp_data/evppkey.txt#L17609-L17615

and associated 
https://github.com/openssl/openssl/blob/3cc26f2eba8a8c16ac559e68c05c094d7ea6bd8b/test/recipes/30-test_evp_data/evppkey.txt#L17659-L17663

**Comment by mattcaswell** [comment]
Works for me.

**Comment by romen** [comment]
Pushed commits for Ed448 testing!

**Comment by romen** [comment]
@mattcaswell could you review this?
@levitte do you have comments on Perl?

**Comment by levitte** [comment]
The perl looks good. I found it very readable.

**Comment by levitte** [comment]
Having read what @mattcaswell has written so far, I'm confident he'd approve as well.

**Comment by levitte** [comment]
Merged.

master:
81722fdf2e01cfa71c46abbcc19e65aa003e083f More testing for CLI usage of Ed25519 and Ed448 keys
ef1e59ed833e8ed1d5f4de5b0c734da8561890e3 More testing for sign/verify through `dgst` and `pkeyutl`

I couldn't cherry-pick cleanly to 1.1.1, please make a backport PR

**Comment by levitte** [comment]
Ping @romen

**Comment by romen** [comment]
Will do!

**Pull request closed without merging**
