### PR TITLE
Set return code in more places on alloc failure

### PR DESCRIPTION
**Pull request by richsalz**
This knocks another handful of items off the #5841 list.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Sorry,  I should have looked first at the CI logs:
threads_win.c
..\crypto\threads_win.c(23): warning C4013: 'CRYPTOerr' undefined; assuming extern returning int
..\crypto\threads_win.c(23): error C2065: 'ERR_R_MALLOC_FAILURE': undeclared identifier

**Comment by richsalz** [comment]
I can fix the windows build.  But yeah, what happens is malloc fails while openssl is starting?  not sure i want to address that, but i'll think about it.  thanks!

**Comment by bernd-edlinger** [comment]
I will think a while about possible recursions, not sure if there are really any,
but there might be new code paths...

**Comment by richsalz** [comment]
The code snippet you pasted doesn't have any codepaths that set malloc-error.  The err code only wants a thread-local-storage key.

**Comment by bernd-edlinger** [comment]
yes.  more analysis needed.

**Comment by bernd-edlinger** [comment]
OPENSSL_init_crypto:
```
    if (opts & OPENSSL_INIT_LOAD_CONFIG) {
        int ret;
        CRYPTO_THREAD_write_lock(init_lock);
        appname = (settings == NULL) ? NULL : settings->appname;
        ret = RUN_ONCE(&config, ossl_init_config);
        CRYPTO_THREAD_unlock(init_lock);
        if (!ret)
            return 0;
```

**Comment by bernd-edlinger** [comment]
there is a code path from
ERR_get_state => OPENSSL_init_crypto(0, NULL) => ossl_init_base => CRYPTO_THREAD_lock_new

**Comment by bernd-edlinger** [comment]
The changes in the stack module seem safe.

**Comment by bernd-edlinger** [comment]
ERR_get_state => OPENSSL_init_crypto(OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL)
=> ossl_init_load_crypto_strings => err_load_crypto_strings_int => ERR_load_ERR_strings
=> do_err_strings_init => CRYPTO_THREAD_lock_new

**Comment by FdaSilvaYY** [comment]
Even if I don't have the position for, I think this change deserve a -1 .?
as stated here , https://github.com/openssl/openssl/pull/5842#discussion_r178969851, stack changes are useless.
And as bernd noticed, I jump on a mined-land, with crypto lock inits.
May be adding a OPENSSL_INIT_THREAD flag dedicated to these per-thread init can solve this tricky case.

**Comment by bernd-edlinger** [comment]
I agree, maybe it is too fine grained to add error traces so deep in internal functions,
and the caller should in general be responsible to log the error from these functions.
Anyway I think there is a problem waiting to be triggered in ERR_get_state,
see #5863 for what might be a more stable solution.

**Comment by richsalz** [comment]
giving up, closing.

**Pull request closed without merging**
