### PR TITLE
Change rand_pool_add[_end] prototypes to match

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by mspncp — APPROVED** [review]
Approved, **provided the CI's pass**  :wink:

**Comment by mspncp** [comment]
Travis succeeded and Windows is still en queue (as usual). So you are free to go...

**Comment by levitte** [comment]
Yay!

**Comment by levitte** [comment]
Merged.

4845aeba4c49e1bd65259a5014d7e3ab38657d42 Change rand_pool_add[_end] prototypes to match

**Pull request closed without merging**
