### PR TITLE
Make it possible to disable building and running tests

### PR DESCRIPTION
**Pull request by levitte**
---

For both _master_ and _1.1.0_

### CODE REVIEW

**Comment by richsalz** [comment]
+1

**Comment by vszakats** [comment]
Any chance to get this merged? It nicely reduces log output by a third and noticeably reduces build-time as well.

With:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.947

Without:
https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.945

**Comment by levitte** [comment]
Merged

**Comment by vszakats** [comment]
Could this patch be merged to the next release of 1.1.0 (and 1.1.1)?

**Pull request closed without merging**
