### PR TITLE
rsaz_exp_x2.c: Avoid potential undefined behavior with strict aliasing

### LINKED ISSUE #19584: Undefined Behaviour in `crypto/bn/rsaz_exp_x2.c`
The supposed fix from <https://github.com/openssl/openssl/pull/19394> (<https://github.com/openssl/openssl/commit/8511520842b744d1794ea794c032ce5f78cd874b>) is incomplete.

The problem was correctly diagnosed in that accessing misaligned data is Undefined Behaviour in C.

*See C17 §6.3.2.3 Pointer p.7*:
> A pointer to an object type may be converted to a pointer to a different object type. If the resulting pointer is not correctly aligned for the referenced type, the behavior is undefined. [...]

This applies regardless of guarantees of the targeted architecture.

However, the *fix* does not work for various reasons:
 1. GCC only documents `__attributed__((aligned(#))` on a `typedef` to be able to reduce the natural alignement requirements from GCC 9 onwards.
    See GCC 9 <https://gcc.gnu.org/onlinedocs/gcc-9.5.0/gcc/Common-Type-Attributes.html#Common-Type-Attributes>:
    > When used on a struct, or struct member, the aligned attribute can only increase the alignment; in order to decrease it, the packed attribute must be specified as well. When used as part of a typedef, the aligned attribute can both increase and decrease alignment, and specifying the packed attribute generates a warning.

    and GCC 8 <https://gcc.gnu.org/onlinedocs/gcc-8.5.0/gcc/Common-Type-Attributes.html#Common-Type-Attributes>:
    > The aligned attribute can only increase alignment. Alignment can be decreased by specifying the packed attribute. See below.

    Thus, if OpenSSL can still target GCC earlier than GCC 9, the attribute cannot be assumed to do anything and thus cannot be assumed to solve the problem.
    Also, it would need to be researched how compilers other than GCC which also define `__GNUC__` (i.e. Clang or icc/icx) handle this particular case.
 2. For MSVC, `__declspec(align(#))` has the same restrictions as for GCC <= 8.
    See <https://learn.microsoft.com/en-us/cpp/cpp/align-cpp?view=msvc-170>:
    > __declspec(align(#)) can only increase alignment restrictions.
 3. For any other compilers, the problem was not addressed at all.

Additionally, this is not just a mere problem of silencing a CI issue. Compilers are known to optimize based on alignment guarantees of the C standard and **will miscompile** (in relation to developer intent) such code (example: <https://godbolt.org/z/zs1hb1rdh>).

However, that's not all. Even if the pointer was properly aligned (which it is not in the general case), it would still be Undefined Behaviour due to type punning.

*See C17 §6.5 Expressions p.5*:
> An object shall have its stored value accessed only by an lvalue expression that has one of the following types:
>  -  a type compatible with the effective type of the object,
>  -  a qualified version of a type compatible with the effective type of the object,
>  -  a type that is the signed or unsigned type corresponding to the effective type of the object,
>  -  a type that is the signed or unsigned type corresponding to a qualified version of the effective type of the object,
>  -  an aggregate or union type that includes one of the aforementioned types among its members (including, recursively, a member of a subaggregate or contained union), or
>  -  a character type.

The proper way to portably issue mis-aligned or wrong-type loads and stores in C is to use helper functions based on memcpy, like:
```C
uint64_t load8(const void * p) {
    uint64_t result = 0;
    memcpy(&result, p, 8);
    return result;
}

void store8(void * p, uint64_t value) {
    memcpy(p, &value, 8);
}
```

*Related Question*: What is OpenSSL's policy on issueing security notices for Undefined Behaviour? I did read <https://www.openssl.org/policies/general/security-policy.html>, but it does not talk about Undefined Behaviour at all.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #19584

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by thesamesam — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
The code looks rather complicated, did you compare the generated assembler code with and without this patch?
Does it look the same as before, or does this cause a performance degradation?

**Comment by t8m** [comment]
I do not think any small performance degradation in these from_words52/to_words52 is relevant. It would surely depend on how much optimizing the compiler is. These functions are called only as the first and last step of the algorithm so they should not have big impact on the overall performance of the mod_exp computation.

**Comment by bernd-edlinger** [comment]
Did you know there is also a `may_alias` attribute, why no using it instead ?

**Comment by thesamesam** [comment]
> Did you know there is also a `may_alias` attribute, why no using it instead ?

It's not portable.

**Comment by bernd-edlinger** [comment]
Okay, when I wrote #19394 I had no way whatsoever to test anything,
only a 1:1000 chance that the CI picks up an affected CPU arch.

Are you able to effectively test this, and maybe get performance numbers
with/without this patch?

**Comment by t8m** [comment]
I have no readily available computer that I could test the performance impact on. As for correctness of the code, I'd suggest merging it to master branch and wait a few days to see if there is any CI regression detected due to this. The probability to get a CI build on machine capable of AVX512_IFMA is much higher than 1:1000, so within a few days we would see if there is any regression or not.

**Comment by davidben** [comment]
We've found [Intel SDE](https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html) to be extremely useful for this thing. (To the point that we even run it in CI.) I'd suggest getting that out and running through the usual suite of sanitizers, etc.

**Comment by t8m** [comment]
> You probably remember this?

Yes, on the other hand there were CI failures after that change which we ignored as at that time we did not recognize the connection to the change. That's why I am saying we should merge this only to master and wait to see if there are any CI failures.

**Comment by t8m** [comment]
Of course if anyone has AVX512_IFMA capable machine and/or the Intel SDE installation readily available, it would be welcome to test this right away.

**Comment by slontis** [comment]
@t8m this does not seem like an acceptable strategy. Putting a hold on this so it is discussed within OTC. i.e. This needs to have a CI solution.

**Comment by thesamesam** [comment]
While I get the point, with that rationale, you want to revert the original and disable the code entirely for the timebeing if you feel it can't be adequately tested.

**Comment by slontis** [comment]
I don't have a problem with your PR,
but I do think it would be quite embarrassing if OpenSSL shipped another release that crashed with a similar issue.
If there is some way to address this via CI is should be added.

**Comment by thesamesam** [comment]
I'm giving SDE a go in CI, but no promises yet. It's not the fastest so we'll see how it goes.

**Comment by slontis** [comment]
> I'm giving SDE a go in CI, but no promises yet (I'm also new to the tool). It's not the fastest so we'll see how it goes.

Thanks for having a look...

**Comment by slontis** [comment]
Not sure if this is helpful 
https://ci.chromium.org/ui/p/boringssl/builders/ci/linux32_sde/b8798585425292411169/steps

**Comment by davidben** [comment]
On a phone so I can't look it up easily, but we just use the flags that tell it to simulate a particular CPU model and run through a bunch of them. (Though we haven't yet taken any AVX512 code so I'm not sure if we currently run with one of those.)

If setting it up in CI is tricky, probably at least manually test the PR with it to confirm it works.

**Comment by t-j-h** [comment]
> Of course if anyone has AVX512_IFMA capable machine and/or the Intel SDE installation readily available, it would be welcome to test this right away.

It is trivial to set up an AWS machine that meets the requirement. That is what I did last time we had to check something. This is something the team should be able to do.

**Comment by slontis** [comment]
> It is trivial to set up an AWS machine that meets the requirement. That is what I did last time we had to check something. This is something the team should be able to do.

Would it be possible to add as a buildbot runner?

**Comment by thesamesam** [comment]
> 

That'd be great. So far, my efforts with GH aren't going well, as the job keeps expiring (they have a limit when using their runners) 😢

**Comment by bernd-edlinger** [comment]
Well, all the trouble to get a test setup for this fragile piece of code (and we would need at least a test for each
of the following Compilers to be sure: GCC, CLANG, and MSVC) this looks to me like the maintenance cost
of this code is not worth the benefit for an optimization that runs only on on very very few devices out there.

So, I'd say I am

+1 for removing the AVX512_IFMA optimization altogether.

**Comment by slontis** [comment]
@thesamesam We didnt get time to cover this one in this weeks OTC meeting, It will hopefully be looked at next week.

**Comment by t8m** [comment]
**OTC: We would like at least one-off test run on AVX512_IFMA capable machine to confirm this is OK. Otherwise this is subject to the normal review process.**

**Comment by t8m** [comment]
I've run tests that cover the RSAZ exponentiation on a build from this PR with Intel SDE. (Run under SDE reproduced the issue with 3.0.4 release.)

Unfortunately the run of tests under Intel SDE is too slow to be executed in regular CI.

Ping for second review.

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches. Thank you for the reviews.

**Pull request closed without merging**
