### PR TITLE
Some platforms provide getcontext() but it does not work

### PR DESCRIPTION
**Pull request by mattcaswell**
Some platforms claim to be POSIX but their getcontext() implementation
does not work. Therefore we update the ASYNC_is_capable() function to test
for this.

RT#4366

This fixes the build on some platforms - notably MacOSX PPC64

### CODE REVIEW

**Comment by mattcaswell** [comment]
Ping @levitte...are we able to pull this one in too? Its a build fix for MacOSX PPC64. All tests were green, although someone (you?) cancelled the AppVeyor build halfway through (it looked good so far though!)

**Comment by levitte** [comment]
Restarted it on Appveyor

**Comment by mattcaswell** [comment]
Rebased on top of #887

**Comment by mattcaswell** [comment]
Rebased with latest #887

**Comment by levitte** [comment]
This is looking good.

+1, merging when Appveyor is finished

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
