### PR TITLE
fips-checksums: The define for fips module is FIPS_MODULE

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Haha! That's quite significant!!

**Review by levitte — APPROVED** [review]
Ok, that was painful...  :wink:

**Comment by mspncp** [comment]
FWIW: maybe someone should doublecheck the remaining occurrences of "FIPS_MODE"?

msp@msppc:~/src/openssl$ git grep -n FIPS_MODE | ghlink --markdown
[crypto/cpt_err.c:21:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/cpt_err.c#L21)     {ERR_PACK(ERR_LIB_CRYPTO, 0, CRYPTO_R_FIPS_MODE_NOT_SUPPORTED),
[crypto/err/openssl.txt:395:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/err/openssl.txt#L395) CRYPTO_F_FIPS_MODE_SET:109: FIPS_mode_set
[crypto/err/openssl.txt:2319:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/err/openssl.txt#L2319) CRYPTO_R_FIPS_MODE_NOT_SUPPORTED:101: fips mode not supported
[crypto/err/openssl.txt:2545:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/err/openssl.txt#L2545) EVP_R_ERROR_SETTING_FIPS_MODE:166: error setting fips mode
[crypto/err/openssl.txt:2556:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/err/openssl.txt#L2556) EVP_R_FIPS_MODE_NOT_SUPPORTED:167: fips mode not supported
[crypto/err/openssl.txt:2566:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/err/openssl.txt#L2566) EVP_R_INVALID_FIPS_MODE:168: invalid fips mode
[crypto/err/openssl.txt:3136:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/err/openssl.txt#L3136) SSL_R_AT_LEAST_TLS_1_0_NEEDED_IN_FIPS_MODE:143: \
[crypto/evp/evp_cnf.c:42:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/evp/evp_cnf.c#L42)                 EVPerr(EVP_F_ALG_MODULE_INIT, EVP_R_INVALID_FIPS_MODE);
[crypto/evp/evp_err.c:55:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/evp/evp_err.c#L55)     {ERR_PACK(ERR_LIB_EVP, 0, EVP_R_ERROR_SETTING_FIPS_MODE),
[crypto/evp/evp_err.c:73:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/evp/evp_err.c#L73)     {ERR_PACK(ERR_LIB_EVP, 0, EVP_R_FIPS_MODE_NOT_SUPPORTED),
[crypto/evp/evp_err.c:89:](https://github.com/openssl/openssl/blob/7927ee6ba2/crypto/evp/evp_err.c#L89)     {ERR_PACK(ERR_LIB_EVP, 0, EVP_R_INVALID_FIPS_MODE), "invalid fips mode"},
[include/openssl/cryptoerr.h:39:](https://github.com/openssl/openssl/blob/7927ee6ba2/include/openssl/cryptoerr.h#L39) #  define CRYPTO_F_FIPS_MODE_SET                           0
[include/openssl/cryptoerr.h:83:](https://github.com/openssl/openssl/blob/7927ee6ba2/include/openssl/cryptoerr.h#L83) # define CRYPTO_R_FIPS_MODE_NOT_SUPPORTED                 101
[include/openssl/evperr.h:184:](https://github.com/openssl/openssl/blob/7927ee6ba2/include/openssl/evperr.h#L184) # define EVP_R_ERROR_SETTING_FIPS_MODE                    166
[include/openssl/evperr.h:195:](https://github.com/openssl/openssl/blob/7927ee6ba2/include/openssl/evperr.h#L195) # define EVP_R_FIPS_MODE_NOT_SUPPORTED                    167
[include/openssl/evperr.h:205:](https://github.com/openssl/openssl/blob/7927ee6ba2/include/openssl/evperr.h#L205) # define EVP_R_INVALID_FIPS_MODE                          168
[include/openssl/sslerr.h:468:](https://github.com/openssl/openssl/blob/7927ee6ba2/include/openssl/sslerr.h#L468) # define SSL_R_AT_LEAST_TLS_1_0_NEEDED_IN_FIPS_MODE       143
[ssl/ssl_err.c:25:](https://github.com/openssl/openssl/blob/7927ee6ba2/ssl/ssl_err.c#L25)     {ERR_PACK(ERR_LIB_SSL, 0, SSL_R_AT_LEAST_TLS_1_0_NEEDED_IN_FIPS_MODE),
[util/perl/OpenSSL/Test.pm:887:](https://github.com/openssl/openssl/blob/7927ee6ba2/util/perl/OpenSSL/Test.pm#L887) C<FIPS_MODE> is undefined, otherwise it is equivalent to C<not ok>. This can be
[util/perl/OpenSSL/Test.pm:899:](https://github.com/openssl/openssl/blob/7927ee6ba2/util/perl/OpenSSL/Test.pm#L899) C<FIPS_MODE> is undefined, otherwise it is equivalent to C<isnt>. This can be
[util/perl/OpenSSL/Test.pm:911:](https://github.com/openssl/openssl/blob/7927ee6ba2/util/perl/OpenSSL/Test.pm#L911) C<FIPS_MODE> is undefined, otherwise it is equivalent to C<is>. This can be
[util/perl/OpenSSL/Test.pm:925:](https://github.com/openssl/openssl/blob/7927ee6ba2/util/perl/OpenSSL/Test.pm#L925)     return ok(!$_[0], @_[1..$#_]) if defined $ENV{FIPS_MODE};
[util/perl/OpenSSL/Test.pm:930:](https://github.com/openssl/openssl/blob/7927ee6ba2/util/perl/OpenSSL/Test.pm#L930)     return isnt($_[0], $_[1], @_[2..$#_]) if defined $ENV{FIPS_MODE};
[util/perl/OpenSSL/Test.pm:935:](https://github.com/openssl/openssl/blob/7927ee6ba2/util/perl/OpenSSL/Test.pm#L935)     return is($_[0], $_[1], @_[2..$#_]) if defined $ENV{FIPS_MODE};
[util/perl/OpenSSL/Test.pm:969:](https://github.com/openssl/openssl/blob/7927ee6ba2/util/perl/OpenSSL/Test.pm#L969) =item B<FIPS_MODE>

**Comment by t8m** [comment]
The check-update is already failing in master due to this. Marking as urgent.
Also I've had to rebase and re-run make update.

**Comment by t8m** [comment]
@levitte @mattcaswell OK to merge immediately?

**Comment by mattcaswell** [comment]
> OK to merge immediately?

Ok.

**Comment by t8m** [comment]
Merged. Thank you.

**Comment by richsalz** [comment]
> FWIW: maybe someone should doublecheck the remaining occurrences of "FIPS_MODE"?

See #15140

**Pull request closed without merging**
