### PR TITLE
[1.1.0] Disable encrypt_then_mac negotiation for DTLS.

### PR DESCRIPTION
**Pull request by dwmw2**
I use the word 'negotiation' advisedly. Because that's all we were doing.
We negotiated it, set the TLS1_FLAGS_ENCRYPT_THEN_MAC flag in our data
structure, and then utterly ignored it in both dtls_process_record()
and do_dtls1_write().

Turn it off for 1.1.0; we'll fix it for 1.1.1 and by the time that's
released, hopefully 1.1.0b will be ancient history.

cf. #1705

### CODE REVIEW

**Comment by mattcaswell** [comment]
@dwmw2 I can't see a CLA on file for you. Please could you submit one? Details here:

https://www.openssl.org/policies/cla.html

Note that the email in the CLA should match the one in your commits! Thanks.

**Comment by richsalz** [comment]
David Woodhouse of Intel.  But I think we need an individual one dwm@infradead now.

**Comment by dwmw2** [comment]
David Woodhouse at Intel wrote that patch last week. But I had updated my environment so when I recommitted to 1.1 it had my personal email. I'll fix that for now and then we can work out a personal or Amazon CLA later.

**Comment by dwmw2** [comment]
I've submitted a personal CLA by email *(under my new terms of employment, copyright for this kind of stuff will be my own)*. But attributing this one to my @intel.com address is correct nonetheless.

**Comment by mattcaswell** [comment]
Taking the "Need CLA" label away. We need a second team review on this.

**Comment by mattcaswell** [comment]
Merged.

**Pull request closed without merging**
