### PR TITLE
Changes declaration of secure heap sh_malloc and sh_free

### PR DESCRIPTION
**Pull request by TheMassController**
##### Description of change
sh_malloc and sh_free act as masks of malloc and free as specified by ISO C (POSIX follows this standard). For the sake of consistency, it seems wise to make sure that the signature of sh_malloc matches malloc's signature and to make sure that the signature of sh_free matches the signature of free.

This small code change fixes this. It compiles under config -d --strict-warnings without any issues. I ran the included testsuite (make test), and it finished without problems.

### CODE REVIEW

**Comment by richsalz** [comment]
Please sign our CLA or put "CLA: trivial" in one of the commit *text messages*
Needs another reviewer who also agrees that this is trivial.

**Comment by TheMassController** [comment]
I will just look into siging the CLA. What is the commit text message?

**Comment by richsalz** [comment]
great, thanks.  The text message means anything after the first line.  When you do "commit" it's any other lines before the clump starting with the hashtag character.

**Comment by TheMassController** [comment]
So, it is in both text messages?

**Comment by richsalz** [comment]
It will be merged into a single commit, so just tweak the latest.

**Comment by richsalz** [comment]
merged to master; not doing 1.1.0 unless you think I should andy.

**Pull request closed without merging**
