### PR TITLE
Make unit tests less dependent on FIPS_MODULE define

### PR DESCRIPTION
**Pull request by paulidale**
- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Oops, this is a draft, perhaps a bit too soon for approval...
See it as a sign that I like what I see?

**Comment by paulidale** [comment]
The FIPS_MODULE part is done.  The handling of disable("fips") isn't.

**Comment by paulidale** [comment]
The FIPS_MODULE part is done.  The handling of disable("fips") isn't.

**Review by levitte — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the reviews.

**Pull request closed without merging**
