### PR TITLE
Fix up bad libcrypto.num

### PR DESCRIPTION
**Pull request by jon-oracle**
Fix up bad merge

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by slontis** [comment]
This is urgent right?

**Comment by levitte** [comment]
I'm marking this urgent

**Review by slontis — APPROVED** [review]

**Comment by levitte** [comment]
Merging it

**Comment by slontis** [comment]
You happy for me to merge this now richard?

**Comment by levitte** [comment]
Merged

0608afe0963fc8188f0df1093e0eb42c32cd0a47 Fix up bad libcrypto.num

**Pull request closed without merging**
