### PR TITLE
Handle the case when file names in build.info files may have spaces

### PR DESCRIPTION
**Pull request by levitte**
This adds a tokenizer that treats " and ' much in the same way as a Unix shell.

This should solve [RT#4492](https://rt.openssl.org/Ticket/Display.html?id=4492)

### CODE REVIEW

**Comment by levitte** [comment]
Something to note is that without this, configuration will produce a flawed Makefile if there's a space in any component of the current directory path, *even with in-source builds*

**Comment by t-j-h** [comment]
Why change all the build.info syntax to have to have explicit quotes around it? I would have thought you could solve this without changing the build.info file at all ...

**Comment by levitte** [comment]
Nope.  `Configure` assumes that the INCLUDE values are paths in the source directory, but sometimes, we do have them in the build directory, so the paths to those are made as *absolute* directories in the `build.info` files and let `Configure` calculate the relative path between that and the source directory.

However, if one of those absolute directory paths contains a space..  let's just say that hell breaks loose.

**Comment by levitte** [comment]
(see RT4492 for an example)

**Comment by levitte** [comment]
The other option is to change the `build.info` files to generate relative paths instead of absolute ones.  However, that won't clear the out-of-source build where there's a space in the build directory name.

**Comment by t-j-h** [comment]
What I'm suggesting is to change the handling so the input file format does not need to change.
Make {- rel2abs(catdir($builddir,"../include")) -} result in a quoted string - then doesn't that sort it out without having to hit each instance in build.info?

**Comment by levitte** [comment]
`rel2abs` and `catdir` are `File::Spec::Functions` functions, they do not put quotes around their result.  Why should they?  So either way you turn things around, the `build.info` files are going to get hit.

**Comment by t-j-h** [comment]
Isn't {- <stuff-here> -} a syntax you introduced?

**Comment by levitte** [comment]
Yes and no, it's a delimiter that I use with `Text::Template`.  It won't quote everything that's inside it, and even if I could, *that* would create its own form of hell in all *other* places where that delimiter is used.

**Comment by levitte** [comment]
I really don't understand why explicit quotes in the `build.info` files are so scary?  To begin with, it's less magic, you don't have to wonder where the hell the quotes in the results are coming from.

**Comment by t-j-h** [comment]
+1

**Comment by levitte** [comment]
Thank you for the review!  Merged

**Pull request closed without merging**
