### PR TITLE
Add an explicit cast to time_t

### LINKED ISSUE #7204: nmake fatal error, 32-bit time_t
Thomas Hruska points out the following issue in this post to openssl-users:

https://mta.openssl.org/pipermail/openssl-users/2018-September/008757.html

````
        cl  /Z7 /Fdapp.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX /I "include" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG" -D_USE_32BIT_TIME_T -D_USING_V110_SDK71_ -D_WINSOCK_DEPRECATED_NO_WARNINGS /Zs /showIncludes "test\ct_test.c" 2>&1 > test\ct_test.d
NMAKE : fatal error U1077: 'cl' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

test\ct_test.c(503): error C2220: warning treated as error - no 'object' file generated
test\ct_test.c(503): warning C4244: 'initializing': conversion from 'uint64_t' to 'const time_t', possible loss of data
````

Probably triggered by the usage of:

````
-D_USE_32BIT_TIME_T
````

I use that define for 32-bit builds on my 64-bit hardware as per this old post:

https://groups.google.com/forum/#!topic/mailing.openssl.users/AGuOi4yEY9A

Casting to time_t appears to correct the issue and the build completes successfully:

````
    const time_t default_time = (time_t)CT_POLICY_EVAL_CTX_get_time(ct_policy_ctx) /
                                1000; 
````

@vdukhovni adds the following:

>Since the CT time value is in "ms" since epoch, you really don't want
to down-convert that to 32 bit *before* the division.  You'll need
some parentheses:
>
>  https://en.cppreference.com/w/c/language/operator_precedence
>
> type cast has higher precedence than division, but you need to
divide first, then cast.

### PR DESCRIPTION
**Pull request by mattcaswell**
Caused a compilation failure in some environments

Fixes #7204

### CODE REVIEW

**Comment by mattcaswell** [comment]
Pushed to master and 1.1.1. @vdukhovni - I haven't pushed this to 1.1.0 yet - on the basis that its in security fix only mode. Should I?

**Comment by vdukhovni** [comment]
Though failure to compile is not a "security fix", I think it warrants merging.

**Comment by mattcaswell** [comment]
Ok. I cherry-picked to 1.1.0 too.

**Comment by kaduk** [comment]
One could think about it as "failing to compile prevents getting any subsequent security fixes, so fixing the build is a prerequisite for future security fixes, and is thus roughly like a security fix"

**Pull request closed without merging**
