### PR TITLE
Make prov/names.h a public header file openssl/prov_names.h

### PR DESCRIPTION
**Pull request by richsalz**
While finishing off #14182  it became clear that having the cipher names public would be helpful.
So this PR moves the header file.

### CODE REVIEW

**Comment by t8m** [comment]
I believe this is really bad idea. We would be making the defines part of the API and in strict sense even adding an alias would be an API break.

I could probably accept having the canonical first names as public defines although I am still unsure about that.

23. 4. 2021 23:07, 23:07, Rich Salz ***@***.***> napsal/a:

**Comment by richsalz** [comment]
If the first name is "canonical", then the first name should be part of the API.  Otherwise a third-party crypto provider will have to dig around in the source, no?

**Comment by richsalz** [comment]
This is no longer needed for #14182.  So the OTC can figure out if they want to expose the cipher names publically, partially, or not.   I think you should but it's up to the project to decide.

**Comment by levitte** [comment]
There's really nothing special about the first name from a fetching standpoint.  In that sense, all identities are equal.
@t8m recently added code to get the first / canonical name of a fetched algorithm, is that the API you meant?

**Comment by levitte** [comment]
Providers don't really need to know any other name than they are willing to declare, i.e. the providers can be said to have an authority.  However, if one of their algorithms have at least one common name with an implementation from another providers, the union of all those names are becoming aliases for each other.  That's how the namemaps in libcrypto operate.

Most algorithms have some sort of official name, among others given by the inventor of the algorithm, but also other names, like the OID names given by NIST, IETF, ...  *We* don't really need to dictate this...  we do pre-populate our namemaps with some algorithm names known by libcrypto, though, and the rest is filled in as our providers, or other providers are loaded.

**Comment by richsalz** [comment]
I'm a third-party developer and I want to make sure that *my* FIPS-validated module is used.  Can that be done now, without looking at the source? I want to interop with all existing applications that build against openssl.  Do I need to download the source and duplicate the names?  Right now, yes.  With this PR, the answer is no.  Up to the project to decide if they want to support that case.

**Comment by levitte** [comment]
> I'm a third-party developer and I want to make sure that _my_ FIPS-validated module is used.

Then you should define some property with your algorithm declarations that is unique for your module.
We allow complete freedom of property keys that include a period (`vendor.name=whatever`), if I remember correctly.

> Can that be done now, without looking at the source?

It's assumed that any provider author will document their module.  That documentation should include such things as properties defined with the algorithms it provides.

> I want to interop with all existing applications that build against openssl. Do I need to download the source and duplicate the names?

There's no need to download the source.  This goes for any provider whose names you're interested in sharing names with:

``` console
$ openssl list -provider fips -cipher-algorithms
...
 Provided:
  { 2.16.840.1.101.3.4.1.47, aes-256-ccm, id-aes256-CCM } @ fips
  { 2.16.840.1.101.3.4.1.3, AES-128-OFB } @ fips
...
  AES-128-CBC-HMAC-SHA256 @ fips
  AES-256-CBC-HMAC-SHA256 @ fips
  { DES-EDE3, DES-EDE3-ECB } @ fips
```

**Comment by slontis** [comment]
I still don't agree that the OID should be included in this name (It should be a separate field)
For this reason alone I would not want it to be public.

**Comment by paulidale** [comment]
The OIDs really make the output ugly too.

**Comment by richsalz** [comment]
I am going to close this as my argument for making the "canonical" name part of the API is useful to downstream was not persuasive. As seems appropriate for the day, "use the source, Luke" :)

**Pull request closed without merging**
