### PR TITLE
Fixed state transitions for the HTML version of the life_cycle-kdf.pod

### PR DESCRIPTION
**Pull request by astraujums**
The MAN version was fine and so are kdf.dot and lifecycles.ods from doc/life-cycles

CLA: trivial

##### Checklist
- [x] documentation is added or updated

### CODE REVIEW

**Comment by astraujums** [comment]
I am contributing for the first time so sorry for the mess with trying to mark the CLA as trivial.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
I am OK with CLA: trivial.

**Review by paulidale — APPROVED** [review]
Nice catch.

Too much manual work was involved in the HTML versions :(

**Comment by paulidale** [comment]
Okay with trivial too.

**Comment by paulidale** [comment]
Merged to 3.0 and master.

**Pull request closed without merging**
