### PR TITLE
Updated list formatting, added hyperlinks, modernized syntax

### PR DESCRIPTION
**Pull request by c-danielewicz**
Updated list formatting to allow for easier readability, Added/adjusted hyperlinks, modernized command substitution syntax

CLA: trivial

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I'm okay with trivial.

**Review by beldmit — APPROVED** [review]
LGTM

**Review by shahsb — APPROVED** [review]
thanks!

**Comment by t8m** [comment]
@beldmit please confirm you're ok with CLA: trivial.

**Comment by beldmit** [comment]
Agree with trivial

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
