### PR TITLE
Fix typos in fipsinstall test

### PR DESCRIPTION
**Pull request by mspncp**

### CODE REVIEW

**Comment by mspncp** [comment]
@paulidale is there a reason why you reverted the approval state from 'ready to merge' to 'done'? Is it because of the failed [property test](https://travis-ci.org/openssl/openssl/jobs/615906556?utm_medium=notification&utm_source=github_status)? Do you want me to rebase?

**Comment by mspncp** [comment]
I rebased the pr without further changes to pickup #10505-

**Comment by paulidale** [comment]
I don't remember why, too tired.  _By mistake_ or the _property fix_ are about equally likely.

**Comment by paulidale** [comment]
It's good to go now at least.

**Comment by mspncp** [comment]
Merged to master in be3acd799bfd0fb09ea934e4984ec9eda19d8b8f, thanks!

**Pull request closed without merging**
