### PR TITLE
doc: remove unnecessary note in OSSL_ENCODER.pod

### LINKED ISSUE #14212: Wording fix in doc/man3/OSSL_ENCODER.pod
As noted in #13932:

https://github.com/openssl/openssl/pull/13932#pullrequestreview-574892059

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #14212

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
This is still a bit confusing to me..

using the caller functions

I dont even know why the statement is necessary. The function has a libctx and propq - if it gets called by another function isnt it a no-brainer that the caller needs to set these?

**Comment by paulidale** [comment]
Removing it is an option.

**Comment by slontis** [comment]
Maybe a second opinion is needed? I would remove it.

**Comment by paulidale** [comment]
I'm the second opinion and I'm for removing it too.

**Review by t-j-h — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master, thanks for the reviews.

**Pull request closed without merging**
