### PR TITLE
Correct small typo in CRYPTO_GET_REF

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by dot-asm** [comment]
Previous commit was flagged red by travis for this exact reason. Why wasn't it addressed then? Are we just wasting resources?

And I fail to see why does it have to be addition of 0. As well as what does one need this function for (is there meaningful decision that you can make based on counter value when you don't change it?).

**Comment by levitte** [comment]
> Previous commit was flagged red by travis for this exact reason. Why wasn't it addressed then? Are we just wasting resources?

We are humans, sometimes something looks so self evident that we miss details.  So no, generally speaking, I don't think we are wasting resources, and quite frankly, I don't see why the relatively few anecdotes like this one should make you think otherwise.

> And I fail to see why does it have to be addition of 0. As well as what does one need this function for (is there meaningful decision that you can make based on counter value when you don't change it?).

Say you have a reference counter associated with object FOO, and you want to allow freeing FOO only when the reference counter is zero.

``` C
static whatever *FOO;
static CRYPTO_REF_COUNT FOO_refs = 0;
static CRYPTO_RWLOCK *FOO_refs_lock = NULL;

int destroy_FOO(void)
{
    int i;

    CRYPTO_GET_REF(FOO_refs, &i, FOO_refs_lock);
    if (i != 0)
        return 0;
    OPENSSL_free(FOO);
    return 1;
}
```

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Merged.  c27bc74698ed043b7549d5637ec0a8cf65b39e59

**Comment by dot-asm** [comment]
> So no, generally speaking, I don't think we are wasting resources.

Of course I don't suggest that we generally do, it was just a rhetoric expression to call upon *everybody*, not you personally, to be more attentive. What can be simpler than to look at ci summary? Why can't/shouldn't you take it personally or refer to human fallibility? One of major points with review requirement is to eliminate the human fallibility factor.

> relatively few anecdotes like this one

Well, what can I say, I felt compelled to say it, i.e. I don't feel that it was few enough not to bring it up. One can argue that it shouldn't have been brought up in any specific context, in which case apologies. It just was so glaring simple to avoid...

**Comment by levitte** [comment]
Yes, I agree, it was glaringly simple, and I am embarassed.

**Comment by dot-asm** [comment]
> static whatever *FOO;

This is inadequate example. Because in order to be able to do as suggested, you have ensure that nobody can read the FOO between you read reference counter and pointer is invalidated. I mean let's say somebody increases reference counter right after you've read it, but before free happens. Right thing to do would be to protect reference to FOO with lock(`*`), but then you should be able to just read reference counter without any special call. Bottom line is that this is not common usage pattern for reference counters. Common usage pattern is to pass non-static pointer and have last one to decrement reference counter to zero free the object. I mean you have to actually decrement counter to make decision, you can't make decision on just read value...

(`*`) This implies that there is "give me FOO" and "release FOO" subroutines that claim lock, in which case they can as well just operate on reference counter directly. Since it's already serialized.

**Comment by levitte** [comment]
Hmmm, good point.

**Comment by levitte** [comment]
#3576

**Comment by kaduk** [comment]
This one should be closed now that the original was reverted, right?

(The only use case I could easily see for CRYPTO_GET_REF() would be for debugging output, which would be enough of a use case for me, since mixing atomic and non-atomic accesses is a bad idea.)

**Comment by levitte** [comment]
But, err, it *is* closed...

**Pull request closed without merging**
