### PR TITLE
Update rsautl.pod for typo

### PR DESCRIPTION
**Pull request by multics**
Fixes the typo
CLA： trivial

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
@multics : you need to add "CLA: trivial" in your commit text (and push -f) or sign a CLA at: https://www.openssl.org/policies/cla.html
It will avoid  cla-check failure.

@openssl/team : github PR message template could be amend to mention this point, no ?

**Comment by richsalz** [comment]
That's a good idea about updating the template, thanks!

**Comment by multics** [comment]
Thanks for the tip. I've added the 'CLA: trivial' in the commit text.

**Comment by dot-asm** [comment]
Do note that this can't cherry-pick to anything but master. Because sudirs were renamed. I mean if you really mean 1.0.2 and 1.1.0 labels, then one should probably clarify that we would expect separate request for branches other than master...

**Comment by richsalz** [comment]
sometime git understands renames.  if not easy enough to manually fix

**Comment by richsalz** [comment]
merged.  Thanks for the fix!

**Pull request closed without merging**
