### PR TITLE
Correct comment in crypto/ec/curve448/ed448.h

### PR DESCRIPTION
**Pull request by chrschmidt**
Obvious Copy&Paste&not edit error.

CLA: trivial

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by mattcaswell** [comment]
CI failure is interesting....but not related.

**Comment by t8m** [comment]
> CI failure is interesting....but not related.

I've seen that one before - we would need to guard the access to the time counter for the fake time with a lock or use atomics as it can be accessed from multiple threads.

**Review by paulidale — APPROVED** [review]
Yep, trivial

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
