### PR TITLE
ctrls: add missing control string translation for key -> priv for HMAC

### LINKED ISSUE #16200: openssl dgst -macopt hexkey not supported
The command
```
openssl dgst -sha256 -mac HMAC -macopt hexkey:FFFF -binary -out hmac.out
```
works on OpenSSL 1.1.1, but fails on 3.0.0 beta2 with
```
C00102FC167F0000:error:03000093:digital envelope routines:default_fixup_args:command not supported::0:[action:2, state:4] name=hexkey, value=FFFF
```

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #16200

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Should there be a testcase?

**Comment by paulidale** [comment]
Yeah, there ought to be.

**Comment by paulidale** [comment]
Test case added.

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
Merged. Thanks!

**Comment by t8m** [comment]
@beldmit nothing critical, but you should wait with the merge at least some hours to give me some chance to provide re-approval.

I reconfirm my approval here.

**Comment by beldmit** [comment]
Sorry, my fault.

**Comment by paulidale** [comment]
That's the reason I didn't merge this earlier :)

**Pull request closed without merging**
