### PR TITLE
Enable some legacy code in UEFI system due to memory limit

### PR DESCRIPTION
**Pull request by liyi77**
Always try legacy path in x509_pubkey_decode() and int_ctx_new().
This allows users who are sensitive to size to use legacy ameth/pmeth,
and removes the related providers.

Will reduce ~150KB binaries size when building crypto library in EDK2 (original size is 1578KB).

Background:
Compared with 1.1.1, the output size of openssl 3.0 has almost doubled, so we tried to cut the provider to reduce the size to meet the memory limit of the old platform.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
IMO, this is a bad thing.  Providers are the future, we should not be avoiding them.

**Comment by liyi77** [comment]
> IMO, this is a bad thing. Providers are the future, we should not be avoiding them.

Yes, but the upgrade of openssl 3.0 has been stuck by the memory limit.

In long-term the better way is to remove all legacy code paths, I believe this will also help reduce the size. I'm worried if this will be done by September and EDK2 has to be upgraded to 3.0 by then.

So this is a temporary solution.

**Comment by paulidale** [comment]
Legacy code paths will be removed, but this cannot happen until OpenSSL 4.

**Comment by liyi77** [comment]
> Legacy code paths will be removed, but this cannot happen until OpenSSL 4.

Oh... thanks for this info.

We have to update openssl and release secure firmware for older platforms which are almost impossible to extend memory after 1.1.1 stops supporting.

I'm using OPENSSL_SYS_UEFI to limit these changes, hopefully no impact to other users.

**Pull request closed without merging**
