### PR TITLE
Learn from the lessons of GOTOFAIL

### PR DESCRIPTION
**Pull request by paragonie-scott**
Use explicit braces around if statements to prevent catastrophes down the line.

### CODE REVIEW

**Comment by paragonie-scott** [comment]
If the openssl team agrees that this is a good move, I can send a superseding patch that covers more.

**Comment by richsalz** [comment]
that code can probably be restructured better, but adding a curly braces around every single nested statement doesn't seem like a good idea.

**Comment by paragonie-scott** [comment]
> adding a curly braces around every single nested statement doesn't seem like a good idea

What leads you to believe this isn't a good idea?

**Comment by richsalz** [comment]
IMHO it makes the code needless cluttered and complex.  And a massive edit to do it for all of the source base is risky.  What other project does it?

**Comment by paragonie-scott** [comment]
> What other project does it?

I don't know of any C projects that do things the OpenSSL way. I'd argue that this change is long overdue. If you need an example: [libsodium](https://github.com/jedisct1/libsodium).

```c
if (x) {
    foo();
} else
    bar();
```
This is harder to audit than
```c
if (x) {
    foo();
} else {
    bar();
}
```
Option A (what OpenSSL does) means that whitespace can trick the reviewer. Option B is more explicit. You have curly braces that clearly define what each control structure encapsulates.

Apple's gotofail could have been prevented by consistent use of curly braces.

**Comment by richsalz** [comment]
We follow the kernel coding style; perhaps you might want to look at Chapter 3 of https://www.openssl.org/policies/codingstyle.html

**Comment by t-j-h** [comment]
Refer to Chapter 3 of the [coding style](https://www.openssl.org/policies/codingstyle.html) which covers the appropriate places to insert braces which I think addresses this issue more cleanly. Patches which apply that style will of course be welcome.

**Comment by paragonie-scott** [comment]
So basically:

```c
if (x)
    foo();
else
    bar();
```
... is expected, but...

```c
if (x) {
    foo();
} else
    bar();
```

... is still a style violation? I'll update the patch if that's the rules you want to follow, since this certainly doesn't follow that.

**Comment by richsalz** [comment]
Surely there are better things to spend time on :)

**Comment by paragonie-scott** [comment]
Y'know what? You're right.

See, I was going to start with this and spend time seeing if I can find anything more substantial to improve, but I'll go find something better to spend my time on.

Best of luck.

**Pull request closed without merging**
