### PR TITLE
[1_1_0-stable] Fix regression in evptests.txt

### PR DESCRIPTION
**Pull request by romen**
When compiling without EC support the test fails abruptly parsing some keys.

Some keys pulled in #3188 start with
------BEGIN EC PRIVATE KEY-----

this format is not supported without EC support.

This commit reformat those keys with the generic format. After this change the
test simply skips the unsupported EC keys when EC is disabled, without parsing
errors.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Good catch.  Can you do the same for master?

**Comment by romen** [comment]
@levitte done #3223

**Comment by romen** [comment]
@richsalz @levitte @bbbrumley while testing this issue I noticed another problem in evp_test.c:

currently if EC support is enabled but binary EC support is disabled, an error goes uncatched:
~~~
Error reading private key KAS-ECC-CDH_K-163_C0
140662336259840:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:crypto/ec/ec_curve.c:3100:
140662336259840:error:100D5010:elliptic curve routines:eckey_priv_decode:EC lib:crypto/ec/ec_ameth.c:211:
140662336259840:error:0606F091:digital envelope routines:EVP_PKCS82PKEY:private key decode error:crypto/evp/evp_pkey.c:44:
140662336259840:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:crypto/pem/pem_pkey.c:86:
~~~

I already have a [commit pushed][fix] and I was thinking that it might make sense to add it to this PR (and it's clone for master). What do you think about it?

[fix]: https://github.com/romen/openssl/commit/54824f8acef73f31c718419f830c9bb8d824eed1

**Comment by richsalz** [comment]
Make a separate PR (well, two if necessary; master and 1.1.0).
Your other PR's have been reviewed and are going in now.
That is a nice-to-have, but not strictly required right now, so let's do it separately.

**Comment by richsalz** [comment]
merged, thank you!

**Comment by romen** [comment]
As a follow up to the last comment, #3226 and #3227 are the PRs fixing the issue mentioned earlier

**Pull request closed without merging**
