### PR TITLE
Avoid mallocing unprocessed_rcds and processed_rcds fields in dtls record layer

### PR DESCRIPTION
**Pull request by fwh-dc**
Should be better performing.

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
> Should be better performing.

I can't imagine it saves a lot. But ok.

**Comment by mattcaswell** [comment]
To confirm you meant this to target master right? As opposed to the dtlsv1.3 featur branch?

**Comment by fwh-dc** [comment]
> To confirm you meant this to target master right? As opposed to the dtlsv1.3 featur branch?

Hmm I've also been wondering where the best place to put it would be... I also have https://github.com/openssl/openssl/pull/26150

Maybe it is better to target the feature branch for both of the changes to avoid possible conflicts. Should I rebase on the feature branch or does the merge scripts handle that?

**Comment by fwh-dc** [comment]
> > Should be better performing.
> 
> I can't imagine it saves a lot. But ok.

Agree, but memory management logic is also simplified.

**Comment by mattcaswell** [comment]
> Maybe it is better to target the feature branch for both of the changes to avoid possible conflicts. Should I rebase on the feature branch or does the merge scripts handle that?

Yeah, I'd be tempted to put this on the feature branch. Please rebase, and then retarget this PR (click "Edit" to the right of the title, and change the target branch in the drop down that appears underneath the title).

**Review by mattcaswell — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Review by shahsb — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the feature branch. Thank you for your contribution.

**Pull request closed without merging**
