### PR TITLE
Fixed pkey_ecx_keygen issue.

### LINKED ISSUE #19580: ossl_ecx_key_op not able to access in openssl3.0 Engine
From QAT Engine we are accessing OpenSSL's default implementation incase of synchronous request. From openssl 3.0 in ossl_ecx_key_op function always below condition is satisfied and hence key generation is failing.

```
openssl/crypto/ec/ecx_backend.c:
        if (p == NULL || id == EVP_PKEY_NONE || plen != KEYLENID(id)) {
            ERR_raise(ERR_LIB_EC, EC_R_INVALID_ENCODING);
            return 0;
        }
```

### PR DESCRIPTION
**Pull request by ShuaiYuan21**
Fixes #19580

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by Yogaraj-Alamenda — APPROVED** [review]

**Review by slontis — COMMENTED** [review]
@levite this got changed in
https://github.com/openssl/openssl/commit/cf333799979755dd46193b49c15db0afd262c6a0#diff-88b27e46df54e1b6e454c17d1b2eba953cc6479e5bc8aaf59d7ae87356bfe84a

I assume it was a block copy bug?

**Review by slontis — APPROVED** [review]

**Comment by slontis** [comment]
Really wish we had some way of testing this kind of thing.

**Comment by ShuaiYuan21** [comment]
Hi, is that possible to backport this change to 3.0 branch so that it will be available in the next 3.0.x release?

**Comment by paulidale** [comment]
Merged to all three branches.  Thanks for the fix.

**Pull request closed without merging**
