### PR TITLE
Use __BYTE_ORDER__ to test the endianness when available

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
LGTM

**Comment by kroeckx** [comment]
So the problem is that it doesn't like "{; int foo;" or "int bar;; int foo;".

So there are 2 solutions to the problem:
- Move the ; inside the define. This might look weird to some and has as disadvantage that we don't test the correct placement on most platforms anymore
- Move the DECLARE_IS_ENDIAN to be after all the variables.

I'm going for the 2nd.

**Comment by kroeckx** [comment]
Pushed a new commit

**Comment by kroeckx** [comment]
MSVC  doesn't support __BYTE_ORDER__, so we would actually also have CI covering the first option.

**Review by paulidale — COMMENTED** [review]
Rather than forcing `DECLARE_IS_ENDIAN` to be the final declaration.  Would something like this make more sense:
``` C
# if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__)
#  define DECLARE_IS_ENDIAN const int ossl_is_little_endian = __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
#  define IS_LITTLE_ENDIAN (ossl_is_little_endian)
#  define IS_BIG_ENDIAN (!ossl_is_little_endian)
# else
...
# endif
```

It just seems a little less invasive.

**Review by paulidale — APPROVED** [review]

**Pull request closed without merging**
