### PR TITLE
BIO: at the end of BIO_new, declare the BIO inited if no create method present

### PR DESCRIPTION
**Pull request by levitte**
Without this, every BIO implementation is forced to have a create method, just to set bio->init = 1.

### CODE REVIEW

**Comment by richsalz** [comment]
I feel like removing the "dummy" init functions should really be part of this PR.

**Comment by levitte** [comment]
I can do that

**Comment by levitte** [comment]
Done

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
Gonna wait on Appveyor, just to be safe

**Comment by levitte** [comment]
Merged.

master: 7f55808fe723c146428415a470ed42331548007b and 94f1c9379c3ed4b088718b35d0dd807d619d50c5
1.1.0: cd1caea433d44e63af517a8149eee6ed9f45f681 and d4577a1474cd67afbfa5a48729c979180144b9d6

**Comment by davidben** [comment]
A bit late now, but worth noting this was not _quite_ a backwards-compatible change, and in a rather subtle way.

It's pretty common in more complex OpenSSL applications for a custom `BIO` to require some extra parameter to initialize themselves, such as a file descriptor or a custom application socket object, or whatever.

In that case, the pattern is that `BIO_new` leaves the `init` flag _unset_, and then it is explicitly set only after the extra parameter is passed in. You can see this in OpenSSL itself, how the fd BIO doesn't set `init` until later.
https://github.com/openssl/openssl/blob/master/crypto/bio/bss_fd.c

Prior to this change, such an application would not need to provide a create callback at all. While OpenSSL does provide `fd_new`, it was (prior to this CL) mostly redundant. The only meaningful line in there is `bi->num = -1`, because otherwise the default for `num` is 0 instead of -1. An external application would not be able to use `num` in the first place and instead would use `ptr` via `BIO_set_data`. But since the default value is already `NULL`, it is quite common that they wouldn't need to do anything.

After this change, the application would need to provide a no-op create callback to avoid triggering the default auto-initialization behavior, if they want to take advantage of the `init` flag to avoid passing half-initialized `BIO`s to their callbacks.

**Pull request closed without merging**
