### PR TITLE
Prevent extended tests run unexpectedly in appveyor

### PR DESCRIPTION
**Pull request by bernd-edlinger**
so debug why this happens

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Oh, no...
```
git log -2
commit 9a6129d33cfe517043f286c821897c9ee04ea81c
Merge: 9e6cb43442 1edcecefc0
Author: Bernd Edlinger <bernd.edlinger@hotmail.de>
Date:   Thu May 28 16:32:41 2020 +0200
    Merge 1edcecefc051847f6d56401d118ef954dfcd38ba into 9e6cb4344233aeefe91c6092567f887015ee345a
commit 9e6cb4344233aeefe91c6092567f887015ee345a
Author: Dmitry Belyavskiy <beldmit@gmail.com>
Date:   Wed May 27 13:03:04 2020 +0300
    Update gost-engine commit to match the API changes
    
    [extended tests]
    
    Reviewed-by: Richard Levitte <levitte@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/11970)
if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER` 
```

**Comment by bernd-edlinger** [comment]
No longer WIP.  I wonder if this *ever* worked as advertised :-)

**Comment by kaduk** [comment]
> No longer WIP. I wonder if this ever worked as advertised :-)

I am not super-familar with appveyor specifically, but the general idea of the CI is to make a temporary merge commit from the topic branch into master (or some other target branch) and try to build at that merge commit.  So `git log -2` would most of the time pick up the desired commit (which is `HEAD^2`), but I assume in some cases would pick up the wrong parent of the merge (`HEAD^`).  This would have to do with how `git log` orders commits, which probably involves the commit date (not author date) but I'd have to check to be sure.

**Comment by bernd-edlinger** [comment]
My initial experiments show that `git log -2`
prints HEAD and HEAD^  that is the merge commit itself and
whatever is the latest commit.  `git log -1 HEAD^2` could work too.

**Comment by bernd-edlinger** [comment]
BTW: The solution in this PR is very similar to how .travis.yml works:
https://github.com/openssl/openssl/blob/082c041b4233b17b80129d4ac6b33a28014442b0/.travis.yml#L145-L146

**Comment by bernd-edlinger** [comment]
Merged to master as d805b83 and 1.1.1 as 3476de9.
Thanks!

**Comment by richsalz** [comment]
Nice detective work BTW!

**Pull request closed without merging**
