### PR TITLE
check_sig_alg_match(): weaken sig nid comparison to base alg (RSA-PSS -> RSA)

### PR DESCRIPTION
**Pull request by DDvO**
This is an upstream fix for #13931.

It also generalizes the `genca` function of `mkcert.sh`.

- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
There is one thing that might not be correct - the RSA-PSS key should not allow verification of a PKCS#1 v1.5 signatures. Where the other way around should be fine.

**Comment by t8m** [comment]
Although that might be possibly enforced later during the actual signature verification. So it is probably ok to keep the check as is here. However we probably should add a negative test case for that. Which should be quite possible to easily create with the current master as there seems to be a related bug: #13969

**Comment by DDvO** [comment]
> There is one thing that might not be correct - the RSA-PSS key should not allow verification of a PKCS#1 v1.5 signatures. Where the other way around should be fine.

Ah, then maybe the check was correct and the example misleading?
Strange yet that the signature verification must have succeeded still.
I'm not an expert on crypto/signing algorithms such as RSA-PSS, so I'm confused.

**Comment by t8m** [comment]
I do not think the original check was correct. It definitely has to be adjusted to properly support RSA-PSS. The mentioned paragraph of RFC4158 imo does not really account for RSA-PSS keys.

**Comment by t8m** [comment]
But with your adjustment I think we should be OK in this part of code as this check is just an auxiliary check and what really matters is the actual signature verification.

But I need to test the actual verification case of RSA signature with RSA-PSS key. That should fail during the verification.

**Comment by DDvO** [comment]
> There is one thing that might not be correct - the RSA-PSS key should not allow verification of a PKCS#1 v1.5 signatures. Where the other way around should be fine.
> Although that might be possibly enforced later during the actual signature verification.

Yes - I tried it out and got
```
error 7 at 0 depth lookup: certificate signature failure
error test/certs/ee-pss-wrong1.5-cert.pem: verification failed
C087DB0D6C7F0000:error:068000C8:asn1 encoding routines::wrong public key type:crypto/asn1/a_verify.c:165:
```

> So it is probably ok to keep the check as is here.

I'm going to add a special check ruling this out already in the chain building because otherwise it will lead into a dead end.

> However we probably should add a negative test case for that. Which should be quite possible to easily create with the current master as there seems to be a related bug: #13969

Indeed - I'll add such a test as well to this PR.

**Comment by t8m** [comment]
> > So it is probably ok to keep the check as is here.
> 
> I'm going to add a special check ruling this out already in the chain building because otherwise it will lead into a dead end.

Well in any real world scenario outside of artificial testcases I do not think it would ever happen that you'd have two CA certificates in the trusted or untrusted chains which would have the same subject key id but one of them would have an RSA key and the other an RSA-PSS key.

**Comment by DDvO** [comment]
True, but in real-world scenarios it is not unlikely that SKID and/or AKID are missing and then it might happen.

**Comment by DDvO** [comment]
I've just enhanced this PR by adding (separate) commits 
* fixing `rsa_pss_asn1_meth` to refer to `rsa_sig_info_set`
* fixing `obj_xref`: `rsassaPss` must map to 'undef rsassaPss' (not 'undef rsaEncryption')

and 
* making the check in `check_sig_alg_match()` stronger again and cleaning it up
* adding a negative test case to demonstrate that 
  a RSA-PSS key cannot be used to verify a plain RSA signature.

**Review by t8m — APPROVED** [review]
Hmm, actually this is less invasive than I thought it will have to be.

**Comment by DDvO** [comment]
Merged - thanks @t8m

**Pull request closed without merging**
