### PR TITLE
 EVP,KDF: add error code on alloc failure (1.1.0)

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Backport of PR #5783 ...

Error framework has changed between these branches, so it needs some work.

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
@mspncp : PR good to go ?

**Comment by richsalz** [comment]
@fdasilvayy are you planning on doing more?  Because I might take this on, too.  I'll at least do libssl.

**Comment by FdaSilvaYY** [comment]
@richsalz : I gota branch in WIP, I can push it .

**Comment by mspncp** [comment]
This is a backport of PR #5783, so I wouldn't add anything more to this.

 @FdaSilvaYY answering your question: An OMC approval was missing.

 @richsalz: you can merge it if you like. If I shall do it, let me know.

**Comment by mspncp** [comment]
Sorry, I misunderstood. I will merge.

**Comment by mspncp** [comment]
Merged, thanks again!

**Comment by FdaSilvaYY** [comment]
@mspncp : thanks ! Can you open an issue with your grep extractions to fix, in order to track them, please.

**Comment by mspncp** [comment]
Done, see #5838. Thanks for volunteering to fix it!

**Pull request closed without merging**
