### PR TITLE
Build fixes for 1.0.2

### PR DESCRIPTION
**Pull request by ghedo**
Still a work-in-progress.

### CODE REVIEW

**Comment by ghedo** [comment]
All green, can be reviewed now!

**Comment by dot-asm** [comment]
I object the approach of obfuscating code as way of working around *silly* bugs elsewhere, in *some* gcc versions in this case. If on-site compiler can't handle it, then it shouldn't be given the opportunity. In the context by passing -Wno-error=shadow or -Wno-shadow as additional config argument *through* .travis.yml.

**Comment by ghedo** [comment]
I generally agree, although slightly changing one variable name isn't that much of an obfuscation. I wonder if there's actually any value in running the older gcc version in our linux builds though. If not then maybe we could just enable gcc-5 (as in #429) and drop the older one. Disabling shadow warnings would also work I guess, but they should be disabled only for that particular gcc version and would probably involve quite some work to implement... not sure if that would be worth it.

**Comment by dot-asm** [comment]
Every little step will look innocent, but question is about overall result in long run. I mean it's more about principle than this particular change. As for disabling warning depending on particular version, I'd be "brutally" pragmatic. Instead of trying to chase exact versions, just pass it unconditionally and periodically, once a year, try to remove it. After all, this is about very specific environment.

As for older gcc. There is great value in testing things in not-latest environments. It's at least some feedback to legacy platforms that still deserve support.

**Comment by levitte** [comment]
I agree with @dot-asm here.  One argument is that this is catering for others' silly bugs...  I'm definitely not a fan, it doesn't help anyone.  Another argument is the one of accomplishment.  What does the name change accomplish?  Does it clear out a bug in *our* code?

So if it's up to a vote, I vote +1 on @dot-asm's suggestion.

**Comment by ghedo** [comment]
Ok. I updated the travis config to pass `-Wno-error=shadow` to gcc and remove the other patch. I suppose that since the clang builds have that warning enabled proper problems will probably get caught anyway.

The build is still green btw.

**Comment by dot-asm** [comment]
Great! As possible *next* step, i.e. not in the context of this request. Depending on how it plays out with binfmt and wine, it might be possible to run mingw tests even for 1.0.2...

**Comment by richsalz** [comment]
Reviewed by Andy, submitted be me.  Closing.  THANKS!

**Pull request closed without merging**
