### PR TITLE
WIP: parameter checking

### PR DESCRIPTION
**Pull request by levitte**
Related to #8454

### CODE REVIEW

**Comment by levitte** [comment]
This is currently *very* early coding of thoughts related to a "live lint" kind of functionality related to `OSSL_PARAM` setup and processing.  The intention is to provide tools to code assertions.  The information for those tools will be generated as `OSSL_PARAM` arrays from XML.

**Comment by paulidale** [comment]
Just a thought but would a literate programming approach work? Parse the params from the code to produce the documentation?

**Comment by levitte** [comment]
Welllllll...

Who decides what type the diverse parameters should have? My take is that the owner of the objects they apply to do. To figure out the proper types means parsing code and detect when  a OSSL_PARAM is handled, what algorithm it's associated with, yada yada yada. Certainly an interesting exercise, but might be a bit over the top, especially if you keep in mind that using the API is *optional* (we can't make its use mandatory)

**Comment by paulidale** [comment]
I was thinking of comments in the code that provide the information.
I don’t like having stuff split in two places.

**Comment by levitte** [comment]
Is this still interesting at all?  We seem to have taken a different path with descriptor OSSL_PARAM arrays.

**Comment by levitte** [comment]
I just had a call with @mattcaswell on this, and we both concluded that this won't go anywhere.  So I'm killing this

**Comment by levitte** [comment]
(this was the last remaining branch in my original 3.0.0 replumbing workspace, meaning I could clean that off my disk...  yay)

**Pull request closed without merging**
