### PR TITLE
State machine rewrite

### PR DESCRIPTION
**Pull request by mattcaswell**
This pull request implements a new state machine with the following objectives:
* Remove duplication of state code between client and server
* Remove duplication of state code between TLS and DTLS
* Simplify transitions and bring the logic together in a single location so that it is easier to validate
* Remove duplication of code between each of the message handling functions
* Receive a message first and then work out whether that is a valid transition - not the other way around (the other way causes lots of issues
where we are expecting one type of message next but actually get something else)
* Separate message flow state from handshake state (in order to better understand each)
    * message flow state = when to flush buffers; handling restarts in the event of NBIO events; handling the common flow of steps for reading a message and the common flow of steps for writing a message etc
    * handshake state = what handshake message are we working on now
* Control complexity: only the state machine can change state: keep all the state changes local to the state machine component

The message flow state machine is divided into a reading sub-state machine and a
writing sub-state machine. See the source comments in ssl/statem/statem.c for a more
detailed description of the various states and transitions possible. Also see ssl/statem/README for additional info.

One issue is that this removes support for DTLSv1_listen. I have another patch to add that back in (in a completely different way) - but it needs a bit more work yet.

### CODE REVIEW

**Comment by ghedo** [comment]
So, what's the status on this? Could you rebase it onto master so it's run through travis?

**Comment by mattcaswell** [comment]
It's awaiting internal review. Tim has started looking at it.

**Comment by mattcaswell** [comment]
Rebased, added some updates based on feedback received, and some additional fixes. Travis is now green! :-)

**Comment by mattcaswell** [comment]
This has now been merged. Closing.

**Pull request closed without merging**
