### PR TITLE
Reword repeated words.

### PR DESCRIPTION
**Pull request by slontis**
A trivial PR to remove some commonly repeated words. It looks like this is
not the first PR to do this.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by slontis** [comment]
thanks thanks

**Review by levitte — APPROVED** [review]

**Comment by slontis** [comment]
to to approvals!

**Comment by paulidale** [comment]
It's two.  It's two.

**Review by mattcaswell — APPROVED** [review]

**Comment by slontis** [comment]
Ta. Merged to master.

**Pull request closed without merging**
