### PR TITLE
EVP: Change the output size type of EVP_Q_digest() and EVP_Q_mac()

### LINKED ISSUE #15839: `unsigned int` instead of `size_t` in `EVP_Q_mac()`
PR #14664 added `EVP_Q_mac()` as a wrapper around the `EVP_MAC` functionality to improve usability.

Unfortunately we did not notice that the parameter type of the last argument of the new function is inconsistent with the underlying function, as it swapped `size_t*` for `unsigned int*`.

This is evident when comparing `(unsigned int*) outlen` in

https://github.com/openssl/openssl/blob/openssl-3.0.0-beta1/include/openssl/evp.h#L1215-L1219

against `(size_t*) outl` in

https://github.com/openssl/openssl/blob/openssl-3.0.0-beta1/include/openssl/evp.h#L1223-L1224

### PR DESCRIPTION
**Pull request by levitte**
This makes them more consistent with other new interfaces.

Fixes #15839

### CODE REVIEW

**Comment by levitte** [comment]
For the moment, I want to see how this fares through the CIs.  Either way, comments welcome!

**Comment by levitte** [comment]
CIs are happy!

**Review by t-j-h — APPROVED** [review]

**Review by paulidale — COMMENTED** [review]
The documentation needs updating too.

**Comment by levitte** [comment]
> The documentation needs updating too.

Thanlk you for the reminder.  Done

**Review by paulidale — APPROVED** [review]

**Comment by t-j-h** [comment]
Still approved ...

**Review by DDvO — APPROVED** [review]
LGTM

**Comment by DDvO** [comment]
There is a mem leak in **non-caching** CI `test_threads`.

**Comment by levitte** [comment]
> There is a mem leak in **non-caching** CI `test_threads`.

Yeah...  I believe it's not relevant for this PR, and it seems like @paulidale is working on that issue

**Comment by levitte** [comment]
Merged

006de7670a12dff617e86a55b6db7c6e3b1f8fef EVP: Change the output size type of EVP_Q_digest() and EVP_Q_mac()
21dfdbef4965d95d65bfc942aafafd342cb61e4c Adapt other parts of the source to the changed EVP_Q_digest() and EVP_Q_mac()

**Pull request closed without merging**
