### PR TITLE
doc: fix two invalid <B> tags

### PR DESCRIPTION
**Pull request by bbolli**
Signed-off-by: Beat Bolli <dev@drbeat.li>

I stumbled upon the first one by chance, then checked if there were any others.

##### Checklist
- [x] documentation is added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
Hey, @bbolli nice to see you again :)

**Comment by bbolli** [comment]
Hey, @richsalz Or, as my Twitter handle says: "Occasional OSS contributor"...

**Comment by kaduk** [comment]
Setting ready-to-merge since the comments after 'approval:done' was set were just socializing.
Did anyone have plans to merge?

**Comment by kaduk** [comment]
Hearing nothing, I will go ahead and merge.

**Comment by kaduk** [comment]
Merged to master, so closing.
Thanks for the fix!

**Pull request closed without merging**
