### PR TITLE
Fix missing INVALID_EXTENSION

### PR DESCRIPTION
**Pull request by dongbeiouba**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Review by kaduk — APPROVED** [review]

**Comment by kaduk** [comment]
In an amusing coincidence, I had noticed the same thing last week but didn't get a chance to put together a PR.
I believe there was no practical effect because all entries after this in the table are related to TLS 1.3, and if EC is disabled that cascades through to disable TLS 1.3 as well, so we didn't actually reference anything at the wrong index.

**Comment by kaduk** [comment]
The AppVeyor failures seem unrelated

**Comment by kaduk** [comment]
Merged to 1.1.1, so closing.
Thank you for the submission!

**Pull request closed without merging**
