### PR TITLE
Clarify the POD source for the list command.

### PR DESCRIPTION
**Pull request by paulidale**
Make the POD source less confusing, refer #7541 

- [x] documentation is added or updated

### CODE REVIEW

**Comment by levitte** [comment]
An alternative for quotes is C<>, which will render the enclosed text in monospace where applicable, or in quotes (!) otherwise

**Comment by levitte** [comment]
https://perldoc.perl.org/perlpod.html#Formatting-Codes

**Comment by paulidale** [comment]
I've switch over.  The `>` needed escaping too.

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
