### PR TITLE
chore: typo fix

### PR DESCRIPTION
**Pull request by willmafh**
CLA: trivial

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — COMMENTED** [review]
agreed trivial

**Review by tom-cosgrove-arm — APPROVED** [review]
ok with trivial

There's also

```
ssl/quic/quic_record_shared.h:    /* 1 if for TX, else RX. Initialised when secret provided. */
```

but I'm not sure if that needs to be fixed in the feature branch

**Comment by tom-cosgrove-arm** [comment]
@paulidale did you intend to approve?

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
