### PR TITLE
Add X509_STORE lock and unlock functions

### PR DESCRIPTION
**Pull request by levitte**
Since there are a number of function pointers in X509_STORE that might
lead to user code, it makes sense for them to be able to lock the
store while they do their work.

---

Partly fixes [RT#4602](https://rt.openssl.org/Ticket/Display.html?id=4602)

_login on RT with user 'guest' and password 'guest'_

### CODE REVIEW

**Comment by levitte** [comment]
This mostly makes sense if #1294 is applied as well.

**Comment by richsalz** [comment]
docs?

**Comment by kroeckx** [comment]
Shouldn't the X509_STORE take the lock itself when needed?  @mattcaswell: Do you have an opinion on this?

**Comment by mattcaswell** [comment]
@kroeckx, generally I think locks should be an internal only thing...but there may be use cases where user code needs to lock something over multiple function calls to ensure consistency is maintained. If that is the case here then I can't think of a better way of doing it.

**Comment by richsalz** [comment]
I think for things like callbacks in stores, and such, it is going to make sense to expose the lock.

**Comment by mattcaswell** [comment]
Just needs docs I think.

**Comment by levitte** [comment]
I'm having second thoughts about this PR, and am thinking that we would be better off providing a lock/unlock functions. 
Also, along with second thoughts about #1294, I wonder if external use of the lock is really necessary. I'll get back on the matter, but meanwhile, please share your thoughts.

**Comment by mattcaswell** [comment]
Like I said in an earlier comment I'd prefer locks to be an internal only thing...so lock/unlock functions would work for me too. I can't really advise on #1294...not familiar enough with the variables exposed to know whether they are internal only or not.

**Comment by richsalz** [comment]
I'm not sure which is the right way to go: get the lock object, or add methods.  The first is half of API size, but the second is what we do for smaller low-level objects.  Of course, we can also not do this now, and require applicatoins to put their own lock around the x509store object.

**Comment by kroeckx** [comment]
I'm confused by this whole thing, and clearly the documentation isn't very helpful.  There is an X509_STORE and an X509_STORE_CTX.  From what I understand, I would expect that multiple threads can use multiple X509_STORE_CTX at the same time, but probably not the same one.  You actually need to init() an X509_STORE_CTX again after it's been used, so you actually want to either lock it over the multiple calls you do with it or have 1 per thread/connection.

But X509_STORE is less clear to me, and I currently don't even see why it would need a lock.

**Comment by levitte** [comment]
I think X509_STORE_CTX isn't supposed to be shared between threads, while X509_STORE can.  X509_STORE contains caches of loaded certificates, so updating those would require locking, surely?

**Comment by kroeckx** [comment]
If it needs updating, then it would only require the lock internally?

**Comment by levitte** [comment]
Yeah...  but considering all the functions that can be implemented externally (see #1294), I can see scenarios where locking might be required...

(on the other hand, we do very little locking ourselves...)

**Comment by levitte** [comment]
Reimplemented as lock and unlock functions.  This is more along the lines of what we usually do.

**Comment by richsalz** [comment]
will plus-one was soon as you write the six lines of doc :)

**Comment by levitte** [comment]
Documentation added

**Comment by richsalz** [comment]
+1

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
