### PR TITLE
Force flush in BIO_free.

### PR DESCRIPTION
**Pull request by rsbeckerca**
CLA: Trivial

Fixes: #14517

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Uhmmmm, CIs are going belly up

**Comment by rsbeckerca** [comment]
> Uhmmmm, CIs are going belly up

On a one-liner?

**Comment by levitte** [comment]
The CI crashes are weird, and indicate that flushing has bugs in BIO

**Comment by rsbeckerca** [comment]
> 
> 
> The CI crashes are weird, and indicate that flushing has bugs in BIO

I just ran tests on both NonStop and Windows x86 under gcc/cygwin and am not seeing any issues. `BIO_ctrl` has all the guards in place to prevent null problems.

**Comment by rsbeckerca** [comment]
> 
> 
> > The CI crashes are weird, and indicate that flushing has bugs in BIO
> 
> I just ran tests on both NonStop and Windows x86 under gcc/cygwin and am not seeing any issues. `BIO_ctrl` has all the guards in place to prevent null problems.

There may be a possible problem if `parg` is null in `BIO_ctrl`, but that seems like a legitimate use of the argument. `BIO_flush` is a simple invocation and has a guard test on the file not being null evaluated by `BIO_ctrl`, unless there is a timing thing that the file is not null but is in a closed state by the time `BIO_flush` is invoked. Can this condition be tested for in code inside `BIO_ctrl`?

**Comment by rsbeckerca** [comment]
The multiple CI tests are failing for an unrelated reason.
```
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
```

**Comment by levitte** [comment]
> The multiple CI tests are failing for an unrelated reason.
> ```
> *** WARNING : deprecated key derivation used.
> Using -iter or -pbkdf2 would be better.
> ```

That's hardly the actual reason

**Comment by rsbeckerca** [comment]
> 
> 
> > The multiple CI tests are failing for an unrelated reason.
> > ```
> > *** WARNING : deprecated key derivation used.
> > Using -iter or -pbkdf2 would be better.
> > ```
> 
> That's hardly the actual reason

Just trying to help ;)

**Comment by levitte** [comment]
Found the issue, this is a quick fix that should be good enough:

``` diff
diff --git a/crypto/bio/bio_lib.c b/crypto/bio/bio_lib.c
index da61544937..1d317248cc 100644
--- a/crypto/bio/bio_lib.c
+++ b/crypto/bio/bio_lib.c
@@ -114,7 +114,9 @@ int BIO_free(BIO *a)
     if (a == NULL)
         return 0;
 
-    (void) BIO_flush(a);
+    /* It's only safe to do this on source BIOs */
+    if (a->next_bio == NULL)
+        (void) BIO_flush(a);
 
     if (CRYPTO_DOWN_REF(&a->references, &ret, a->lock) <= 0)
         return 0;
```

What happens is that if this is a filter BIO, whose underlying source BIO has been freed first, running anything that goes down the BIO chain will crash.  BIO_flush() is one of those.

**Comment by rsbeckerca** [comment]
> 
> 
> Found the issue, this is a quick fix that should be good enough:
> 
> ```diff
> diff --git a/crypto/bio/bio_lib.c b/crypto/bio/bio_lib.c
> index da61544937..1d317248cc 100644
> --- a/crypto/bio/bio_lib.c
> +++ b/crypto/bio/bio_lib.c
> @@ -114,7 +114,9 @@ int BIO_free(BIO *a)
>      if (a == NULL)
>          return 0;
>  
> -    (void) BIO_flush(a);
> +    /* It's only safe to do this on source BIOs */
> +    if (a->next_bio == NULL)
> +        (void) BIO_flush(a);
>  
>      if (CRYPTO_DOWN_REF(&a->references, &ret, a->lock) <= 0)
>          return 0;
> ```
> 
> What happens is that if this is a filter BIO, whose underlying source BIO has been freed first, running anything that goes down the BIO chain will crash. BIO_flush() is one of those.

I feel bad about this. I had that code there in the first place and thought it was unnecessary because of the checks in `BIO_ctrl`.

**Comment by rsbeckerca** [comment]
> 
> 
> > Found the issue, this is a quick fix that should be good enough:
> > ```diff
> > diff --git a/crypto/bio/bio_lib.c b/crypto/bio/bio_lib.c
> > index da61544937..1d317248cc 100644
> > --- a/crypto/bio/bio_lib.c
> > +++ b/crypto/bio/bio_lib.c
> > @@ -114,7 +114,9 @@ int BIO_free(BIO *a)
> >      if (a == NULL)
> >          return 0;
> >  
> > -    (void) BIO_flush(a);
> > +    /* It's only safe to do this on source BIOs */
> > +    if (a->next_bio == NULL)
> > +        (void) BIO_flush(a);
> >  
> >      if (CRYPTO_DOWN_REF(&a->references, &ret, a->lock) <= 0)
> >          return 0;
> > ```
> > 
> > 
> > What happens is that if this is a filter BIO, whose underlying source BIO has been freed first, running anything that goes down the BIO chain will crash. BIO_flush() is one of those.
> 
> I feel bad about this. I had that code there in the first place and thought it was unnecessary because of the checks in `BIO_ctrl`.

@levitte  Shouldn't it be `!= NULL`?

**Comment by levitte** [comment]
> I feel bad about this. I had that code there in the first place and thought it was unnecessary because of the checks in `BIO_ctrl`.

`BIO_ctrl` has the potential of traveling down the BIO chain, by design.  Unfortunately, we have the situation in `apps/dgst.c` with this chain: `bmd` -\> `in`.  At the end of the main function, `in` gets freed before `bmd`, leaving a dangling `next_bio` in the latter.  **KABOOM**
(resolving this *properly* has implications that I think goes beyond this PR)

**Comment by t8m** [comment]
I am worried about the effect this might have on input BIOs. From the manpage: `For input streams associated with seekable files (e.g., disk files, but not pipes or terminals), fflush() discards any buffered data  that  has been fetched from the underlying file, but has not been consumed by the application.` Not sure if that means the file pointer will be moved and the file will be just re-read on subsequent reads. In that case it is just a minor inefficiency. Otherwise it would be a problem.

**Comment by levitte** [comment]
@t8m, good point.  Perhaps that should only be done when the flag `BIO_CLOSE` is set.

**Comment by rsbeckerca** [comment]
> 
> 
> @t8m, good point. Perhaps that should only be done when the flag `BIO_CLOSE` is set.

I am fine with dropping this PR if it's going to present problems. PR #14623 should fix the root problem.

**Comment by levitte** [comment]
> I am fine with dropping this PR if it's going to present problems. PR #14623 should fix the root problem.

It might be wise at this point, as we seem to be heading into a rabbit hole.  I merged #14623 a minute ago

**Comment by rsbeckerca** [comment]
Fixed by #14623

**Pull request closed without merging**
