### PR TITLE
Avoid potential memory leak

### LINKED ISSUE #17827: Potential memory leak in append_ia5
If we didn't succeed duplicating passed email address we don't free the  STACK_OF(OPENSSL_STRING) *sk

https://github.com/openssl/openssl/blob/e9492d1cecf459261f1f5ac0eb03e9c631600537/crypto/x509/v3_utl.c#L541-L543

I think it can cause a memory leak in case of malloc failure.

### PR DESCRIPTION
**Pull request by beldmit**
Resolves #17827

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by Dridi** [comment]
This doesn't plug a memory leak, it prevents call sites of this function from operating on a partial success. All error conditions used to ensure that the stack was cleared, but when this strdup failure led to an early return it was no longer the case.

It looks like building an all-or-nothing stack was an invariant broken by 98624776c4d501c8badd6f772ab7048ac9191cb9.

**Comment by t8m** [comment]
It does plug it because some of the callers do not clear the stack on error return from the function.

**Comment by Dridi** [comment]
I'll stand corrected and amend my comment to "This doesn't [just] plug a memory leak".

When I first reported this to Red Hat I was focused on one call site (`X509_get1_ocsp()`) and didn't look further than the parts involved the two functions. I did check other call sites, only to see whether they were also incrementally building a stack across multiple calls.

**Comment by mattcaswell** [comment]
Pushed to master, 3.0 and 1.1.1. Thanks for the contribution.

**Pull request closed without merging**
