### PR TITLE
Fix man page to indicate SHA256 MAC for PKCS12

### LINKED ISSUE #19078: PKCS12 man pages says that the default macalg is SHA1 but it's SHA256
This:
https://github.com/openssl/openssl/blob/5639ee79bdc905c1b7ed308fcd29e515e4f01a50/doc/man1/openssl-pkcs12.pod.in#L343-L345

does not agree with this:

https://github.com/openssl/openssl/blob/5639ee79bdc905c1b7ed308fcd29e515e4f01a50/crypto/pkcs12/p12_mutl.c#L207-L209

The man page should be changed to say SHA256.

### PR DESCRIPTION
**Pull request by sharhalakis**
CLA: trivial
Fixes #19078

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]
Agreed trivial

**Comment by paulidale** [comment]
@beldmit, do you are with trivial?

**Comment by beldmit** [comment]
Yes, I agree

**Review by t8m — APPROVED** [review]

**Pull request closed without merging**
