### PR TITLE
Fix crypto/bn/bn_prime.pl and apps/progs.pl to generate correctly formatted source (1.0.2)

### PR DESCRIPTION
**Pull request by levitte**
It was still generating EAY style source.

This is an alternative to #2888

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
Yes, I like this approach as well.
Could you also update the progs.pl from trunk ?

**Comment by levitte** [comment]
Uhmm, why does progs.pl need an update?

**Comment by bernd-edlinger** [comment]
If I touch apps/progs.pl and build everything, then apps/progs.h looks also totally different.
So I guess that would not happen on master...

**Comment by levitte** [comment]
I see what you mean.  I've added a commit for that one as well.

@richsalz, could you reconfirm, please?

**Comment by richsalz** [comment]
reconfirm

**Comment by levitte** [comment]
Merged.  f4675a10f8f42d7e1505ac98e85d2350123e6666 to acdf0814234c8a20bcbdab7f1cf0b4d452adb415

**Pull request closed without merging**
