### PR TITLE
Fix NULL dereference when ENCODER does not implement IMPORT_OBJECT

### PR DESCRIPTION
**Pull request by gotthardp**
External ENCODER may not implement `OSSL_FUNC_ENCODER_IMPORT_OBJECT` as it's an optional function, so a check for NULL is needed.

### CODE REVIEW

**Comment by t8m** [comment]
Hmm, I wonder if this should not be caught much earlier somewhere. I mean when collecting the encoders in collect_encoder we should check whether import_object is implemented and if not and the provider of the pkey is different from the encoder's provider we should not add the encoder to the collection.

**Comment by gotthardp** [comment]
I can easily go up by one step. (I just did.) Is this what you mean, or it should be even higher?

**Comment by t8m** [comment]
> I can easily go up by one step. (I just did.) Is this what you mean, or it should be even higher?

I am afraid it should be checked even earlier (in collect_encoder()) and it will require adding the provider of the EVP_PKEY as a member of the struct collected_encoder_st so you could check whether the provider of the encoder is the same or not.

**Comment by gotthardp** [comment]
Thank you for the hint! Please take another look.

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master. Thank you for the contribution!

**Pull request closed without merging**
