### PR TITLE
Fixed typo in X509_STORE_CTX_new description

### PR DESCRIPTION
**Pull request by cacamille3**
'X509_XTORE_CTX_cleanup' ->  'X509_STORE_CTX_cleanup'

### CODE REVIEW

**Comment by richsalz** [comment]
@cacamille3 we either need you to sign the CLA, or put "CLA: trivial" in your commit message and push an update.

**Comment by cacamille3** [comment]
I have sent the signed CLA to legal@opensslfoundation.org

**Comment by richsalz** [comment]
CLA received ,thanks.

**Comment by richsalz** [comment]
pushed to master, 1.1.0, and 1.02;  thanks!

**Pull request closed without merging**
