### PR TITLE
Read a REQUEST not RESPONSE in ocsp responder

### PR DESCRIPTION
**Pull request by richsalz**
Still a good issue for a newcomer, but can't wait release imminent.

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Is this done correctly on 1.1.1?

**Comment by richsalz** [comment]
Yes this works properly in 1.1.1  It seems that commit 582311d7b46 (PR #11736) broke it.

**Comment by levitte** [comment]
Thanks

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master. Thank you for the contribution!

**Pull request closed without merging**
