### PR TITLE
evp_test: Support testing of stitched TLS ciphers

### LINKED ISSUE #15749: Missing tests for stitched ciphers
We need to test stitched ciphers (AES+SHA, maybe also RC4+MD5) to avoid cases like #15706.

Follow-up to #15740

### PR DESCRIPTION
**Pull request by t8m**
Add a few testcases.

Fixes #15749

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
@t8m could you please confirm that it catches the bug #15706? LGTM if yes

**Comment by t8m** [comment]
Yes, it does. I can apply temporarily a revert of that patch if you want.

**Review by beldmit — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]
Great stuff!

**Comment by paulidale** [comment]
Merged.

**Pull request closed without merging**
