### PR TITLE
Fix #25625: Memory leaks in ossl_quic_calculate_retry_integrity_tag

### LINKED ISSUE #25625: Potential memory leaks in ossl_quic_calculate_retry_integrity_tag
Hello. I'm working on a static analysis tool to detect incomplete error handling code.

My tool reported the following.

In `ossl_quic_calculate_retry_integrity_tag` there are several error handling code blocks that return a value without cleaning up the allocated objects.

https://github.com/openssl/openssl/blob/76c4f0e8ea6e885b2b0727c43778fe54ae224135/ssl/quic/quic_wire_pkt.c#L912-L915

https://github.com/openssl/openssl/blob/76c4f0e8ea6e885b2b0727c43778fe54ae224135/ssl/quic/quic_wire_pkt.c#L918-L922

https://github.com/openssl/openssl/blob/76c4f0e8ea6e885b2b0727c43778fe54ae224135/ssl/quic/quic_wire_pkt.c#L924-L928

https://github.com/openssl/openssl/blob/76c4f0e8ea6e885b2b0727c43778fe54ae224135/ssl/quic/quic_wire_pkt.c#L930-L935

All of these return 0 immediately without going through the `err` label or without cleaning up at least `cctx`, `cipher`, and `wpkt`.

I could also be wrong because my results are based on static analysis even though I manually read the code as well.

Thanks in advance

### PR DESCRIPTION
**Pull request by ndossche**
Several error paths return 0 directly instead of going to err to clean up the objects.

CLA: trivial

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
OK with CLA: trivial

**Review by tom-cosgrove-arm — APPROVED** [review]
ok with trivial

**Review by kroeckx — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]
Ok with trivial

**Review by shahsb — APPROVED** [review]
Okay with CLA: trivial

Thanks for making the changes!

**Comment by t8m** [comment]
Merged (with slightly tweaked commit message) to the master, 3.4, 3.3 and 3.2 branches. Thank you for your contribution.

**Pull request closed without merging**
