### PR TITLE
Add EVP_PKEY_meth setter and getter for digestsign and digestverify

### PR DESCRIPTION
**Pull request by anhu**
Added EVP_PKEY_meth_set_digestsignverify() and EVP_PKEY_meth_get_digestsignverify()

Ran `make tests` and `make doc-nits`. 
Everything passed.

### CODE REVIEW

**Comment by InfoHunter** [comment]
Branch 1.1.1 accepts only bug-fixes at current stage. This should go into master branch.

**Comment by anhu** [comment]
Please note that I have two email addresses associated with this account.  anth_hu@homtail.com is the one that is on file for the CLA. Therefore, you can waive the cla-check failure.

**Comment by anhu** [comment]
> Branch 1.1.1 accepts only bug-fixes at current stage. This should go into master branch.

oops...ok.  Will submit to master.

**Comment by richsalz** [comment]
BUT ... if making things opaque means that code broke, then adding these kinds of things is treated as a bug.

**Comment by anhu** [comment]
> BUT ... if making things opaque means that code broke, then adding these kinds of things is treated as a bug.

So in 1.0.2 there was no `digestsign` and `digestverify` and as such, nothing could be broken. So... I think this is some kind of weird edge case.  I'll keep it closed for now.

**Comment by anhu** [comment]
By the way, I'm really impressed with the responsiveness here.  Thank you very much.

**Comment by mattcaswell** [comment]
Looks like a missing accessor to me so could be eligible for 1.1.1.

**Comment by mattcaswell** [comment]
> Please note that I have two email addresses associated with this account. anth_hu@homtail.com is the one that is on file for the CLA.

Please could you send an updated CLA listing *all* the email addresses you are likely to use for submissions? This helps us to keep our paper trail complete.

**Comment by mspncp** [comment]
See #10388

**Pull request closed without merging**
