### PR TITLE
CI: compilers zoo in containers

### PR DESCRIPTION
**Pull request by quarckster**
Simplify "Compiler Zoo CI" workflow by running jobs in containers.

### CODE REVIEW

**Comment by t8m** [comment]
Can you temporarily with a commit marked with `drop!` in the commit message switch the compiler zoo CI to on pull request so we can see the results here?

**Comment by quarckster** [comment]
> Can you temporarily with a commit marked with `drop!` in the commit message switch the compiler zoo CI to on pull request so we can see the results here?

I'm not sure why it's not started but I ran the workflow against my fork https://github.com/quarckster/openssl/actions/runs/6106417364

**Comment by thesamesam** [comment]
Not sure about this. The current setup does work and it means we're testing the compilers used in the wild, using Ubuntu's patches and default flags (for hardening and such).

I'm also in a routine with the current setup and regularly add new compilers. I don't know if the Docker containers are built regularly enough / adapted to new compilers in a timely enough manner.

Also, who provides the 'tuxmake' containers?

**Comment by quarckster** [comment]
> Not sure about this. The current setup does work and it means we're testing the compilers used in the wild, using Ubuntu's patches and default flags (for hardening and such).

Why Ubuntu is preferred over Gentoo, Debian, RHEL or any other distribution? Why Ubuntu's patches are preferred?

> I don't know if the Docker containers are built regularly enough / adapted to new compilers in a timely enough manner.

According to the Docker Hub images with new versions are released regularly although with some delay so I'm not sure if it's a "timely enough manner".

With that said I don't insist on merging my PR but I'm really curious about the intentions of why it's done as is.

**Comment by thesamesam** [comment]
> > Not sure about this. The current setup does work and it means we're testing the compilers used in the wild, using Ubuntu's patches and default flags (for hardening and such).
> 
> Why Ubuntu is preferred over Gentoo, Debian, RHEL or any other distribution? Why Ubuntu's patches are preferred?

I didn't write it fwiw, I've just ended up adapting it and adding new environments as time goes on.

I've never bothered changing it to something like Gentoo (even though more Gentoo in the world's CI is not something I'd complain about) because I figured it was intentional to have Ubuntu as a common distro people will try to build OpenSSL on. Dunno.

My point here was a distro compiler might be preferable to a vanilla build. Distros tend to use the same set of default flags baked in (via e.g. spec file changes) unlike vanilla GCC.

> 
> > I don't know if the Docker containers are built regularly enough / adapted to new compilers in a timely enough manner.
> 
> According to the Docker Hub images with new versions are released regularly although with some delay so I'm not sure if it's a "timely enough manner".

GCC 13.2 was added day of release, so it's probably fine: https://github.com/docker-library/gcc/commit/af458ec8254ef7ca3344f12631e2356b20b4a7f1.

(Possibly even better given I'd prefer to use the latest point releases of each compiler, not whatever Ubuntu happens to have.)

**Pull request closed without merging**
