### PR TITLE
Remove receiving of unused return value

### PR DESCRIPTION
**Pull request by JohnnySavages**
Found by Linux Verification Center (linuxtesting.org) with SVACE.

CLA: trivial

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Agree trivial

**Comment by tom-cosgrove-arm** [comment]
Wouldn't a better fix be to actually check the result of `BIO_snprintf()` and behave (abort?) accordingly, rather than just ignore the error? We're going to perform file operations on the output of `BIO_snprintf()`, so if the buffer's aren't filled there could be some weird filenames!

**Comment by JohnnySavages** [comment]
> Wouldn't a better fix be to actually check the result of `BIO_snprintf()` and behave (abort?) accordingly, rather than just ignore the error? We're going to perform file operations on the output of `BIO_snprintf()`, so if the buffer's aren't filled there could be some weird filenames!

Actually function cannot cause an "insufficient buffer" failure due to check higher. In the case of an incorrect string literal specifying the format, the use of the information specified in the buffer will fail, for which there is a check below.

Nevertheless, it might still be better to add a check for return codes. idk.
And if so, should I use assert everywhere?

**Comment by shahsb** [comment]
> Wouldn't a better fix be to actually check the result of `BIO_snprintf()` and behave (abort?) accordingly, rather than just ignore the error? We're going to perform file operations on the output of `BIO_snprintf()`, so if the buffer's aren't filled there could be some weird filenames!

I agree with @tom-cosgrove-arm

**Review by tom-cosgrove-arm — APPROVED** [review]
While it would definitely be better to add checks, rather than just omit them, the rest of the code in `apps/` appears to be no better. Even in tests I see a `TEST_true(BIO_snprintf(...))` (and that's insane, since `BIO_snprintf()` returns number of chars written or -1 for error, so is presumably almost never going to return zero).

So I'm now approving this PR as-is - any further fixing would need to have a wider scope

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
