### PR TITLE
fix: LINEAR search doesn't work properly (if CHARSET_EBCDIC is defined)

### PR DESCRIPTION
**Pull request by pstetsuk**
#22107

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by davidben** [comment]
Is there a test which fails on EBCDIC platforms without this fix? If not, perhaps it's worth writing one?

(Though it also seems this goofy linear search could be avoided by passing in a custom comparator.)

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
@davidben There is no unit test for OBJ_bsearch* functions. I would think that some tests could fail on EBCDIC due to this, but we do not have a CI run that would use EBCDIC so we cannot know.

It would be nice to have a unit test for OBJ_bsearch of course.

**Comment by t8m** [comment]
@mattcaswell @paulidale If you agree this is CLA: trivial, please remove the hold label. For me it is borderline but probably OK.

**Comment by t8m** [comment]
Even better would be if @pstetsuk could sign a regular CLA.

**Comment by paulidale** [comment]
I'm okay with trivial.

**Comment by t8m** [comment]
Merged to the master, 3.1 and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
