### PR TITLE
test/build.info: add missing inclusion for ssl_ctx_test

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
This is a minor build fixup, i.e. is exempt of the 24h grace period

**Review by p-steuer — APPROVED** [review]

**Comment by richsalz** [comment]
Please see #10337 for more important problems -- the test fails.

**Comment by p-steuer** [comment]
> This is a minor build fixup, i.e. is exempt of the 24h grace period

Okay, going to merge this one.

**Comment by p-steuer** [comment]
merged.

master: https://github.com/openssl/openssl/commit/2321c25dec8402c4bd48bac0edd3c2ef1ee4b6ad

**Comment by mspncp** [comment]
> This is a minor build fixup, i.e. is exempt of the 24h grace period
> 
> (@mspncp, @mattcaswell, @t-j-h, didn't about having a label for these cases?)

Wid did have some discussion about it, but no decision was made IIRC. The easiest solution which comes to my mind is to have a single general-purpose 'urgent' label (in screaming orange and some description like "This is an urgent fix exempt of the 24h grace period").

If this is too simple, we can still turn it into something more fine-grained by making 'urgent' a label category:  'urgent: ci break', 'urgent: \<some other reason\>', ...

**Comment by levitte** [comment]
"urgent" would be good enough as a start.

**Comment by mspncp** [comment]
Done:

image

**Comment by mspncp** [comment]
Needless to say that the 'urgent' label needs to be applied before approval (like the branch labels) so it can be approved together with the pr by the other reviewers.

**Pull request closed without merging**
