### PR TITLE
Make running individual ssl-test easier

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [X] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Awesome!! Why didn't I think of this years ago??

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
@tmshort Sorry, but it is necessary to adjust the doc file - tests are failing.

**Comment by tmshort** [comment]
Yup, I'll fixup the docs.

**Comment by tmshort** [comment]
`emacs` strikes again; it automatically indented...

**Comment by beldmit** [comment]
Are we OK with adding this to 3.0? Formally it's a feature...

**Comment by tmshort** [comment]
> Are we OK with adding this to 3.0? Formally it's a feature...

It's for testing; it doesn't impact library functionality at all. I put the **branch: 3.0** on there.

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Sorry, didn't spot the 3.0 label on this. I don't think this can go there. The stable release updates policy says:

> New tests and test cases are allowed only as part of a bug fix.

https://www.openssl.org/policies/technical/stable-release-updates.html

I'm still ok with master

**Review by mattcaswell — APPROVED** [review]

**Comment by tmshort** [comment]
> 24 hours has passed since 'approval: done' was set, but as this PR has been updated in that time the label 'approval: ready to merge' is not being automatically set. Please review the updates and set the label manually.

I'll wait 24 hours after @mattcaswell's approval.

Although, one could argue that it's not new tests, nor new test cases.

**Comment by beldmit** [comment]
I'd like to have this feature added to 3.0, and can raise an OTC hold if necessary.

**Comment by paulidale** [comment]
I'd like to see this in 3.0 too.

**Comment by mattcaswell** [comment]
> I'd like to have this feature added to 3.0, and can raise an OTC hold if necessary.

I'd suggest merging this to master anyway (there is no disagreement there), but then keeping this PR open with an OTC hold to specifically address the 3.0 question.

**Review by t8m — APPROVED** [review]

**Comment by tmshort** [comment]
In a couple hours, I'll merge to master. And keep it open pending OTC.

**Comment by tmshort** [comment]
Merged to master.

**Comment by beldmit** [comment]
Question to OTC:
**1. Do we allow this PR to be merged to 3.0?
2. Do we want to adjust our policy and allow test framework features to be merged without OTC decision?**

**Comment by tmshort** [comment]
The vote did not pass. Since this has already been merged to master, I am closing this PR.

**Pull request closed without merging**
