### PR TITLE
Update fuzz corpora to latest commit

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
I wonder if the corpora files need to be merged to the 3.0 and 3.1 branches as well
since #20243 was merged there and the x509 files not updated, or was that too eager?

**Comment by kroeckx** [comment]
This should get merged in all branches.

**Comment by t8m** [comment]
> This should get merged in all branches.

This cannot get merged to all branches as it will conflict. A separate PR will be needed for 3.1 and 3.0 branches.

**Review by t8m — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
@t8m is there a reason you didn't remove the `approval: otc review pending` label?

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
