### PR TITLE
Fix uninitialized value $s warning in windows static builds

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Fixes: #6826

[extended tests]

### CODE REVIEW

**Comment by levitte** [comment]
Please double check the CIs

**Comment by bernd-edlinger** [comment]
Looks like Andy's work

**Comment by bernd-edlinger** [comment]
..\crypto\asn1\tasn_utl.c(60): error C2065: 'CRYPTO_REF_COUNT': undeclared identifier
..\crypto\asn1\tasn_utl.c(60): error C2065: 'lck': undeclared identifier
..\crypto\asn1\tasn_utl.c(60): warning C4552: '*': operator has no effect; expected operator with side-effect
..\crypto\asn1\tasn_utl.c(70): error C2065: 'lck': undeclared identifier
..\crypto\asn1\tasn_utl.c(70): warning C4047: '=': 'int' differs in levels of indirection from 'void *'
..\crypto\asn1\tasn_utl.c(75): error C2065: 'lck': undeclared identifier
..\crypto\asn1\tasn_utl.c(75): error C2100: illegal indirection
..\crypto\asn1\tasn_utl.c(83): warning C4013: 'CRYPTO_UP_REF' undefined; assuming extern returning int
..\crypto\asn1\tasn_utl.c(83): error C2065: 'lck': undeclared identifier
..\crypto\asn1\tasn_utl.c(87): warning C4013: 'CRYPTO_DOWN_REF' undefined; assuming extern returning int
..\crypto\asn1\tasn_utl.c(87): error C2065: 'lck': undeclared identifier

**Comment by dot-asm** [comment]
Right, it's my fault. Addressed now, just re-base.

**Comment by bernd-edlinger** [comment]
Ok, re-based, I'll assume the approvals are still valid.

**Comment by bernd-edlinger** [comment]
Merged to 1.1.0 branch as 831a2b0637b0eb21c9c2f8cc67f4579368637077

**Pull request closed without merging**
