### PR TITLE
Fix SHA3_squeeze on armv4.

### PR DESCRIPTION
**Pull request by slontis**
For armv4 - Only the first 4 parameters can be passed via registers (r0..r3).

As all of the general registers are already used,
r11 was used to store the 'next' param.
R11 is now pushed/poped on entry/exit.

Tested using the same qemu settings as our CI uses.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
See  also #22722

**Comment by slontis** [comment]
Partially fixes https://github.com/openssl/openssl/issues/22692

**Review by t8m — APPROVED** [review]
Assuming you've tested this with qemu.

**Comment by slontis** [comment]
Yes, also ran evp_test and evp_xof_test..

**Review by paulidale — APPROVED** [review]

**Comment by zorrorffm** [comment]
The fix Looks good to me!

**Comment by t8m** [comment]
Merged to the master branch. Thank you.

**Comment by t8m** [comment]
@slontis unfortunately it still did not fix the problem completely as seen in the evp_test failures here:

https://github.com/openssl/openssl/actions/runs/6874516007/job/18696334986
https://github.com/openssl/openssl/actions/runs/6874516007/job/18696335508

**Comment by slontis** [comment]
Well that is embarrassing. I did run this test and get it to work, but I must of not rerun this after I did some cleanups..
Stack was off by 1. verified this by writing $next to the output buffer and confirmed it was 01 at the start and 00 later.

**Pull request closed without merging**
