### PR TITLE
Backport #23887 to 3.1/3.0 

### PR DESCRIPTION
**Pull request by nhorman**
Backport of #23887 to 3.1/3.0 branches

##### Checklist
- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by Sashan — COMMENTED** [review]
changes for 3.1 are identical to changes found in the referenced pull request [#23887](https://github.com/openssl/openssl/pull/23887)

**Comment by nhorman** [comment]
@Sashan  but #23887 didn't merge cleanly to 3.1/3.0 as per the comment [here ](https://github.com/openssl/openssl/pull/23887#issuecomment-2045856412), so there must be some minor line difference

**Review by Sashan — APPROVED** [review]
all looks good.

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the 3.0 and 3.1 branches. Thank you.

**Pull request closed without merging**
