### PR TITLE
Convert _meth_get_ functions to const getters

### PR DESCRIPTION
**Pull request by jablko**
##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated
- [x] CLA is signed

### CODE REVIEW

**Comment by kroeckx** [comment]
I'm guessing that @dot-asm is going to have a problem with this, at least the 1.1.0 part, unless we come up with rules for such changes.

**Comment by FdaSilvaYY** [comment]
i.e: https://github.com/openssl/openssl/pull/1603#issuecomment-248649700

**Comment by richsalz** [comment]
yeah, sigh.  time for a team vote and discussion.

**Comment by FdaSilvaYY** [comment]
Suggestion:  may be, a STRICT mode could be introduced to prepare the switch.

Something like this :
```
#fndef` STRICT
#define CONST
#else
# define CONST const
#endif
...
int (*BIO_meth_get_write(CONST BIO_METHOD *biom)) (BIO *, const char *, int)
...
```

So we could push this kind of changes now.
People who control his build chain can use it now.
When the 1.2.0 time will come, we can make these changes definitive from everyone.

My 2'cents.

**Comment by levitte** [comment]
Compatibility aside, would you mind rebasing again?  I don't know what the current build errors are about and would like it if we could eliminate as many possible factors as possible.

@richsalz, I agree, it's time we vote on this.  I disagree with @dot-asm in this case, and we're having this discussion again and again...

**Comment by jablko** [comment]
@levitte Sure thing -- I rebased this.

**Comment by levitte** [comment]
Oh wow, I left this one hanging.  So sorry about that.  It would need another rebase, although it looks fairly easy to resolve on merge...

**Comment by jablko** [comment]
@levitte Done, I rebased again just now.

**Comment by mattcaswell** [comment]
Pushed to master only. Unfortunately this did not cherry-pick cleanly back to 1.1.0. We'll need to do that with a separate PR. @jablko please could you raise one for the backport?

**Comment by dot-asm** [comment]
> I disagree with @dot-asm in this case

I sense contradiction between what I'm trying to say and what you disagree with. I mean I sense that you disagree with something you hear, but I don't feel that you hear what I'm saying. Why? Because you say "in this case", while my whole point is that "per-case" should be taken out of equation. Assertion is that we would be [have been] better off if there was a set of **verbalized** rules we can refer to. I'm not saying that they have to be verbalized at the same time, so there still is "per-case" factor, but in sense that a case would be a triggering factor for formulating or amending a rule, not just totally isolated thing with no bearing to anything. (Well, even so, it doesn't actually preclude possibility of an exceptional circumstances. Perhaps #4338 could be.) To summarize, I'm not actually against constification per se, what I'm against is leaving it, (more specifically any mods to public headers,) to informal/casual domain. Well, whatever... If nobody feels for it, I can't do anything about it...

**Comment by jablko** [comment]
> Pushed to master only.

Thanks for committing this!

> Unfortunately this did not cherry-pick cleanly back to 1.1.0. We'll need to do that with a separate PR. @jablko please could you raise one for the backport?

Sure thing, I opened #5750.

**Pull request closed without merging**
