### PR TITLE
Enable the ARIA ciphers by default.

### PR DESCRIPTION
**Pull request by paulidale**
Enable ARIA.
Remove the _enable-aria_ options from the extended tests.

### CODE REVIEW

**Comment by paulidale** [comment]
Thanks for the quick approval.  Merged.

**Comment by richsalz** [comment]
I didn't look, but does no-aria config option work?

**Comment by kaduk** [comment]
I generally like to see commit messages that mention the "why" of a change, as well as the "what" (since the "what" can be deduced from the changes itself, but the "why" can easily be lost to the winds of time).

**Comment by dot-asm** [comment]
And I'd like to hear what has changed. See even new comment in #4741.

**Comment by paulidale** [comment]
@kaduk fair suggestion.  I added after messages from @richsalz and @t-j-h suggesting I do so and advising me of a policy decision that new ciphers be on by default but not in the TLS _DEFAULT_ list.

@richsalz the _no-aria_ option works.

**Comment by kroeckx** [comment]
On Mon, Dec 18, 2017 at 09:35:35AM +0000, Andy Polyakov wrote:
> And I'd like to hear what has changed. See even new comment in #4741.

We had various discussions at the f2f, and one of the things
discussed is that crypto algorithms should probably be enabled by
default unless we have a good reason not to, like it's not
considered secure.

This should get turned into a policy at some point.

(This is probably not the best place to discus this.)

**Pull request closed without merging**
