### PR TITLE
remove ms/.rnd and add it to .gitignore

### PR DESCRIPTION
**Pull request by vszakats**
Ref: https://github.com/openssl/openssl/commit/87326458aa67c7452cd55e3deab8a258170a3665#commitcomment-16588483

### CODE REVIEW

**Comment by richsalz** [comment]
+1

**Comment by levitte** [comment]
+1 (although, I don't reeeeally see a need to add it to `.gitignore`...  but ok)

**Comment by levitte** [comment]
Feel free to merge, @richsalz

**Comment by richsalz** [comment]
merged at c54bae9 thanks.

**Comment by vszakats** [comment]
Indeed, I played it safe with the `.gitignore` bit. Most likely this file was once created 18 years ago and updated never since. Shout, and I'll remove that line.

**Comment by richsalz** [comment]
nah, we're good.  an extra entry in .gitignore... who cares :)

**Comment by levitte** [comment]
Naah, that's fine.  It'll have as avoid adding it again ;-)

(now, to sleep)

**Pull request closed without merging**
