### PR TITLE
Improve the implementation of X509_STORE_CTX_get1_issuer()

### PR DESCRIPTION
**Pull request by mattcaswell**
It is possible for the stack of X509_OBJECTs held in an X509_STORE_CTX to
have a custom compare function associated with it. Normally (by default)
this uses X509_NAME_cmp(). The X509_STORE_CTX_get1_issuer() function
assumed that it would always be X509_NAME_cmp(). By a small refactor we can
avoid that assumption.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by t8m — CHANGES_REQUESTED** [review]
Actually I was too hasty.

This is less efficient than the original code and it could be made more efficient easily by using the internal x509_object_idx_cnt() function instead of X509_OBJECT_idx_by_subject().

**Comment by t8m** [comment]
Heh, or actually not as x509_object_idx_cnt() would not use the stack compare function either for the count.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
So approved as apart from digging out the compfunc from the actual stack there is no other way than this.

**Comment by t8m** [comment]
So I was tempted by this so much that I implemented alternative patch in #14728

**Comment by mattcaswell** [comment]
Closing in favour of #14728.

**Pull request closed without merging**
