### PR TITLE
Win10 iot core

### PR DESCRIPTION
**Pull request by przemysx**
Adding support for building the OpenSSL's deliverables for Win10 IoT core.

### CODE REVIEW

**Comment by mattcaswell** [comment]
You are making these changes on the wrong branch. It is highly unlikely that we will add new platform support to a released branch. You should apply them to master instead.

**Comment by przemysx** [comment]
according to: https://github.com/openssl/openssl/issues/971
I thought that I've to put it to 1.0.2 line. 
So the ultimate question is: If I'll create PR to master branch, is it going to land in a 1.0.2 line ever?

**Comment by mattcaswell** [comment]
No. 1.0.2 is a stable branch. We don't add new features or platforms - they only appear in new releases.

**Comment by przemysx** [comment]
Ok. I'll work on pr to master branch instead.

**Comment by richsalz** [comment]
And just to set expectations:  we're in bugfix only right now for 1.1, so this will be in a future release.

**Pull request closed without merging**
