### PR TITLE
Remove x86/x86_64 BSAES and AES_ASM support [1.1.1]

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This leaves VPAES and AESNI support.
The VPAES performance is comparable but BSAES is not
completely constant time. There are table lookups
using secret key data in AES_set_encrypt/decrypt_key
and in ctr mode short data uses the non-constant
time AES_encrypt function instead of bit-slicing.
Furthermore the AES_ASM is by far outperformed
by recent GCC versions.
Since BSAES calls back to AES_ASM for short
data blocks the performance on those is also
worse than the pure software implementaion.

Fixes: #9640

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Do we know what would be the performance with older compilers or even better at least roughly which oldest gcc version produces performance that is on-par with the BSAES and AES_ASM?

**Comment by bernd-edlinger** [comment]
The comment in aes-x86_64.pl says
`aes-*-cbc benchmarks are improved by >70% [compared to gcc 3.3.2 on Opteron 240 CPU]`
That is a long time ago.
It is certain that the removed assembler modules do not operate in constant time.
But so does the software implementation as well.

**Comment by bernd-edlinger** [comment]
Is this something for the upcoming release?

**Comment by levitte** [comment]
I wonder, has anyone done a corresponding comparison with an MSVC build?

**Comment by bernd-edlinger** [comment]
Could you do that?
It is easy to compare
`openssl speed -evp aes-128-ctr / aes-128-cbc / aes-128-gcm`
with no-asm vs. with asm and OPENSSL_ia32cap = "0:0"
the difference is **huge** with all versions of GCC.

**Comment by bernd-edlinger** [comment]
the numbers are much better with 1.1.1 than with master, but that is another story.

**Comment by levitte** [comment]
Sure

**Comment by levitte** [comment]
## VC-WIN64A + NASM, OPENSSL_ia32cap=0:0

### aes-128-ctr

```
C:\Users\Richard\Work\_openssl-1.1.1-64>apps\openssl speed -evp aes-128-ctr
Doing aes-128-ctr for 3s on 16 size blocks: 20483123 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 64 size blocks: 5901690 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 256 size blocks: 1558615 aes-128-ctr's in 3.00s
Doing aes-128-ctr for 3s on 1024 size blocks: 396501 aes-128-ctr's in 3.00s
Doing aes-128-ctr for 3s on 8192 size blocks: 49930 aes-128-ctr's in 3.00s
Doing aes-128-ctr for 3s on 16384 size blocks: 24788 aes-128-ctr's in 3.02s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 19:25:04 2019 UTC
options:bn(64,64) rc4(8x,int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-ctr     108677.30k   125250.37k   133001.81k   135339.01k   136342.19k   134674.10k
```

### aes-128-cbc

```
C:\Users\Richard\Work\_openssl-1.1.1-64>apps\openssl speed -evp aes-128-cbc
Doing aes-128-cbc for 3s on 16 size blocks: 21311521 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 64 size blocks: 6597990 aes-128-cbc's in 3.00s
Doing aes-128-cbc for 3s on 256 size blocks: 1743839 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 1024 size blocks: 990489 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 8192 size blocks: 127087 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 16384 size blocks: 63135 aes-128-cbc's in 3.02s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 19:25:04 2019 UTC
options:bn(64,64) rc4(8x,int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     113072.53k   140757.12k   148036.57k   336335.17k   345234.14k   343014.74k
```

### aes-128-gcm

```
C:\Users\Richard\Work\_openssl-1.1.1-64>apps\openssl speed -evp aes-128-gcm
Doing aes-128-gcm for 3s on 16 size blocks: 16169483 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 64 size blocks: 4837075 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 256 size blocks: 1265378 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 1024 size blocks: 317367 aes-128-gcm's in 3.00s
Doing aes-128-gcm for 3s on 8192 size blocks: 40213 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 16384 size blocks: 20123 aes-128-gcm's in 3.02s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 19:25:04 2019 UTC
options:bn(64,64) rc4(8x,int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm      85790.42k   102656.27k   107419.45k   108327.94k   109239.34k   109328.99k
```

## VC-WIN64A no-asm

### aes-128-ctr

```
C:\Users\Richard\Work\_openssl-1.1.1-64>apps\openssl speed -evp aes-128-ctr
Doing aes-128-ctr for 3s on 16 size blocks: 29795175 aes-128-ctr's in 3.03s
Doing aes-128-ctr for 3s on 64 size blocks: 9982399 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 256 size blocks: 2674154 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 1024 size blocks: 683021 aes-128-ctr's in 3.00s
Doing aes-128-ctr for 3s on 8192 size blocks: 86128 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 16384 size blocks: 43052 aes-128-ctr's in 3.02s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 19:48:42 2019 UTC
options:bn(64,64) rc4(int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -DL_ENDIAN -DOPENSSL_PIC
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-ctr     157269.38k   211854.44k   227012.12k   233137.83k   233968.27k   233903.08k
```

### aes-128-cbc

```
C:\Users\Richard\Work\_openssl-1.1.1-64>apps\openssl speed -evp aes-128-cbc
Doing aes-128-cbc for 3s on 16 size blocks: 34186891 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 64 size blocks: 10946411 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 256 size blocks: 2922599 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 1024 size blocks: 744965 aes-128-cbc's in 3.00s
Doing aes-128-cbc for 3s on 8192 size blocks: 93699 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 16384 size blocks: 46863 aes-128-cbc's in 3.00s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 19:48:42 2019 UTC
options:bn(64,64) rc4(int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -DL_ENDIAN -DOPENSSL_PIC
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     181385.37k   232313.47k   248102.91k   254281.39k   254535.03k   255934.46k
```

### aes-128-gcm

```
C:\Users\Richard\Work\_openssl-1.1.1-64>apps\openssl speed -evp aes-128-gcm
Doing aes-128-gcm for 3s on 16 size blocks: 19672526 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 64 size blocks: 5815730 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 256 size blocks: 1493612 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 1024 size blocks: 378282 aes-128-gcm's in 3.00s
Doing aes-128-gcm for 3s on 8192 size blocks: 47394 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 16384 size blocks: 23723 aes-128-gcm's in 3.00s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 19:48:42 2019 UTC
options:bn(64,64) rc4(int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -DL_ENDIAN -DOPENSSL_PIC
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm     104376.51k   123426.06k   126794.50k   129120.26k   128746.66k   129559.21k
```

------

Wow, that was quite noticable!  Not extremely for gcm, but the other two?

This is, btw, with MSVC 19.00.24225.1 and NASM 2.13.03 where applicable.

I expect VC-WIN32 to show similar numbers

**Comment by levitte** [comment]
VC-WIN32 numbers turned out to be similarly dramatic

## aes-128-ctr

### NASM, OPENSSL_ia32cap=0:0

```
C:\Users\Richard\Work\_openssl-1.1.1-32>apps\openssl speed -evp aes-128-ctr
Doing aes-128-ctr for 3s on 16 size blocks: 17097590 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 64 size blocks: 4755875 aes-128-ctr's in 3.00s
Doing aes-128-ctr for 3s on 256 size blocks: 1262131 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 1024 size blocks: 322515 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 8192 size blocks: 40849 aes-128-ctr's in 2.98s
Doing aes-128-ctr for 3s on 16384 size blocks: 20007 aes-128-ctr's in 3.02s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 20:04:30 2019 UTC
options:bn(64,32) rc4(4x,int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-ctr      90714.67k   101458.67k   107143.80k   109514.73k   112129.01k   108698.76k
```

### no-asm

```
C:\Users\Richard\Work\_openssl-1.1.1-32-noasm>apps\openssl speed -evp aes-128-ctr
Doing aes-128-ctr for 3s on 16 size blocks: 26398307 aes-128-ctr's in 3.00s
Doing aes-128-ctr for 3s on 64 size blocks: 8128511 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 256 size blocks: 2091755 aes-128-ctr's in 3.00s
Doing aes-128-ctr for 3s on 1024 size blocks: 530055 aes-128-ctr's in 3.02s
Doing aes-128-ctr for 3s on 8192 size blocks: 65964 aes-128-ctr's in 3.00s
Doing aes-128-ctr for 3s on 16384 size blocks: 33262 aes-128-ctr's in 3.00s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 20:07:10 2019 UTC
options:bn(64,32) rc4(int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -DL_ENDIAN -DOPENSSL_PIC
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-ctr     140790.97k   172509.75k   178496.43k   179988.00k   180125.70k   181654.87k
```

## aes-128-cbc

### NASM, OPENSSL_ia32cap=0:0

```
C:\Users\Richard\Work\_openssl-1.1.1-32>apps\openssl speed -evp aes-128-cbc
Doing aes-128-cbc for 3s on 16 size blocks: 19772500 aes-128-cbc's in 3.00s
Doing aes-128-cbc for 3s on 64 size blocks: 5949864 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 256 size blocks: 1545998 aes-128-cbc's in 3.00s
Doing aes-128-cbc for 3s on 1024 size blocks: 818576 aes-128-cbc's in 3.00s
Doing aes-128-cbc for 3s on 8192 size blocks: 104562 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 16384 size blocks: 52305 aes-128-cbc's in 3.02s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 20:04:30 2019 UTC
options:bn(64,32) rc4(4x,int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     105453.33k   126272.76k   131925.16k   279407.27k   284044.57k   284174.96k
```

### no-asm

```
C:\Users\Richard\Work\_openssl-1.1.1-32-noasm>apps\openssl speed -evp aes-128-cbc
Doing aes-128-cbc for 3s on 16 size blocks: 31072982 aes-128-cbc's in 3.03s
Doing aes-128-cbc for 3s on 64 size blocks: 9339550 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 256 size blocks: 2403369 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 1024 size blocks: 622524 aes-128-cbc's in 3.02s
Doing aes-128-cbc for 3s on 8192 size blocks: 78021 aes-128-cbc's in 3.00s
Doing aes-128-cbc for 3s on 16384 size blocks: 38926 aes-128-cbc's in 3.02s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 20:07:10 2019 UTC
options:bn(64,32) rc4(int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -DL_ENDIAN -DOPENSSL_PIC
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     164014.09k   198211.38k   204024.86k   211387.22k   213049.34k   211486.37k
```

## aes-128-gcm

### NASM, OPENSSL_ia32cap=0:0

```
C:\Users\Richard\Work\_openssl-1.1.1-32>apps\openssl speed -evp aes-128-gcm
Doing aes-128-gcm for 3s on 16 size blocks: 11292104 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 64 size blocks: 3001336 aes-128-gcm's in 3.00s
Doing aes-128-gcm for 3s on 256 size blocks: 754019 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 1024 size blocks: 192584 aes-128-gcm's in 3.00s
Doing aes-128-gcm for 3s on 8192 size blocks: 24533 aes-128-gcm's in 3.00s
Doing aes-128-gcm for 3s on 16384 size blocks: 11992 aes-128-gcm's in 3.02s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 20:04:30 2019 UTC
options:bn(64,32) rc4(4x,int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm      59912.51k    64028.50k    64009.57k    65735.34k    66991.45k    65152.97k
```

### no-asm

```

C:\Users\Richard\Work\_openssl-1.1.1-32-noasm>apps\openssl speed -evp aes-128-gcm
Doing aes-128-gcm for 3s on 16 size blocks: 15266780 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 64 size blocks: 4109022 aes-128-gcm's in 2.98s
Doing aes-128-gcm for 3s on 256 size blocks: 1058091 aes-128-gcm's in 3.00s
Doing aes-128-gcm for 3s on 1024 size blocks: 270432 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 8192 size blocks: 33804 aes-128-gcm's in 3.02s
Doing aes-128-gcm for 3s on 16384 size blocks: 16806 aes-128-gcm's in 3.00s
OpenSSL 1.1.1d-dev  xx XXX xxxx
built on: Thu Sep  5 20:07:10 2019 UTC
options:bn(64,32) rc4(int) des(long) aes(partial) idea(int) blowfish(ptr)
compiler: cl /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -DL_ENDIAN -DOPENSSL_PIC
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm      81000.95k    88118.08k    90290.43k    91829.18k    91829.18k    91783.17k
```

**Comment by bernd-edlinger** [comment]
Merged to 1.1.1 as 87bea65.  Thanks!

**Pull request closed without merging**
