### PR TITLE
Support minimum and maximum protocol version

### PR DESCRIPTION
**Pull request by levitte**
If for nothing else, they are needed when doing a regression test

### CODE REVIEW

**Comment by levitte** [comment]
This is simply a port of #5662 to master

**Comment by mspncp** [comment]
dito ;-)

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

43110de041b77aef08bf744cba9330969895a321 Support "-min_protocol" and "-max_protocol" in s_server and s_client
2e2faa8c4802f2fcecea699ddda246929b2ca329 In TLSProxy::Proxy, specify TLSv1.3 as maximum allowable protocol
7d7f6834e542e53f604b46a72d57fad773d4b2bc Enhance ssltestlib's create_ssl_ctx_pair to take min and max proto version

**Comment by levitte** [comment]
Thank you!

**Comment by mattcaswell** [comment]
Looks like commit 2e2faa8c4 broke master :-(

**Comment by levitte** [comment]
Huh? It built fine with Travis here...
I'll like in a few...

**Pull request closed without merging**
