### PR TITLE
Make the -inform option to be respected if possible

### LINKED ISSUE #14569: The -inform option is ignored because store does not support enforcement of encoding format
The apps -inform option to choose whether input format is PEM or DER is currently ignored because store does not support enforcement of encoding format and tries to parse the input as PEM and if that fails it tries DER. This is useful behavior in case -inform option is not specified however there might be use cases (checking the correctness of the format) where the enforcement is needed.

There is also no CHANGES.md entry for the automatic behavior of the apps.

### PR DESCRIPTION
**Pull request by t8m**
Add OSSL_STORE_PARAM_INPUT_TYPE and make it possible to be
set when OSSL_STORE_open_ex() or OSSL_STORE_attach() is called.

The input type format is enforced only in case the file
type file store is used.

By default we use FORMAT_UNDEF meaning the input type
is not enforced.

Fixes #14569

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Any comments welcome. I still need to cleanup the docs in regards to the -inform option and add at least some test cases.

**Comment by beldmit** [comment]
Will do a bit later

**Comment by beldmit** [comment]
@t8m, https://github.com/gost-engine/engine/commit/1b684f3f906bc81154ca1d5af7d6bc60199f1f9c 
I'd suggest temporary set it into your PR as GOST state. Then I'll merge it to master and we will update the submodule

**Comment by t8m** [comment]
> I'd suggest temporary set it into your PR as GOST state. Then I'll merge it to master and we will update the submodule

Even better if you are able to manually do a FF merge of the commit so the commit hash is not changed after the merge, we will not need a separate git submodule update.

**Comment by t8m** [comment]
Ah, I see that 1b684f3 commit is already behind the current master so you'll need rebase. Perhaps we can update in sync?

**Comment by beldmit** [comment]
If you provide a clear guideline, I'm OK wit it

**Comment by t8m** [comment]
Ready for reviews.

**Review by paulidale — APPROVED** [review]

**Comment by slontis** [comment]
I wonder if this is right to use undef as the default? Previously it would have chosen pem right - unless der was specifically asked for.. Isnt that a breaking change?

**Comment by t8m** [comment]
Rebased to fix minor conflict in apps.c and fips checksums. 
Added fixup with the Changes entry as requested by @slontis.

@paulidale please re-approve.

@beldmit could you please rebase and merge your gost_engine PR now so I can include the final commit id for the gost_engine submodule when merging?

**Comment by t8m** [comment]
> I wonder if this is right to use undef as the default?

This was discussed at the meeting where OTC triaged this issue and it was deemed as acceptable.

**Comment by t8m** [comment]
I do not think these changes require restart of the 24 h ready-to-merge period.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Good to merge IMO.

**Comment by mattcaswell** [comment]
Pushed.

**Pull request closed without merging**
