### PR TITLE
Corrected 'cms' exit status when key or certificate cannot be opened

### LINKED ISSUE #4996: Wrong return value for 'openssl cms -sign' when signing certificate cannot be opened
When `openssl cms` cannot read the signing certificate, it returns `3`:

```
$ echo "data" | openssl cms -sign -signer foo -inkey bar; echo $?
Error opening signer certificate foo
139840430016416:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('foo','r')
139840430016416:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
3
```
But `man cms` says that it should return `2`:

```
EXIT CODES
[...]
  2   one of the input files could not be read.
```

### PR DESCRIPTION
**Pull request by KonstantinShemyak**
Fixes #4996.

Should tests be added? I do not see any testing for nonzero exit codes in `tests/cms-examples.pl`...

### CODE REVIEW

**Comment by mattcaswell** [comment]
Please either send us a CLA, or if you think the contribution is trivial add "CLA: trivial" to the commit description.

> Should tests be added? I do not see any testing for nonzero exit codes in tests/cms-examples.pl...

Tests are always welcome, although historically we don't have much in the way of tests for the command line apps. Probably we should, but so far we don't. Therefore I don't think we would insist on tests (although the question does make me wonder whether we should have a policy on this)

**Comment by KonstantinShemyak** [comment]
> Please either send us a CLA [...]
Just done.

**Comment by KonstantinShemyak** [comment]
It looks to me that Travis CI build failure is the failure of the CI itself (packages were not downloaded to the build system) - correct? Should I retrigger the build?

**Comment by KonstantinShemyak** [comment]
> Are 1.1.0 and 1.0.2 similarly affected?

Versions tagged with `OpenSSL_1_1_0` and `OpenSSL_1_0_2` also return `3` like the `master` version.

**Comment by dot-asm** [comment]
I'd say it would be appropriate to back-port to 1.1.0 and 1.0.2, but it won't cherry-pick. And it looks like 1.1.0 version won't cherry-pick to 1.0.2... Separate requests then?

**Comment by KonstantinShemyak** [comment]
Do you suggest that I make (seemingly unrelated) GitHub pull requests to `OpenSSL_1_1_0-stable` and `OpenSSL_1_0_2-stable` branches?

**Comment by mattcaswell** [comment]
> Do you suggest that I make (seemingly unrelated) GitHub pull requests to OpenSSL_1_1_0-stable and OpenSSL_1_0_2-stable branches?

Yes please! You can reference this PR in the description.

**Comment by bernd-edlinger** [comment]
Oh, as this was already approved, I will go ahead and merge now.

**Comment by bernd-edlinger** [comment]
Merged to all branches.  Thanks!

**Pull request closed without merging**
