### PR TITLE
X509 `v2i_AUTHORITY_KEYID()`: Improve error reporting on parsing config values/options

### PR DESCRIPTION
**Pull request by DDvO**
A further spin-off if #16300:

complete configuration parsing for AKID extensions and respective error reporting in `v2i_AUTHORITY_KEYID()`.

### CODE REVIEW

**Comment by t8m** [comment]
IMO this is a feature unfortunately so it cannot be merged to 3.0 without an exception.

**Comment by DDvO** [comment]
> IMO this is a feature unfortunately so it cannot be merged to 3.0 without an exception.

No urgency from my perspective. So I've marked it post.3.0.0

**Comment by DDvO** [comment]
> IMO this is a feature unfortunately so it cannot be merged to 3.0 without an exception.

Can we continue with this now?

**Comment by DDvO** [comment]
Rebased this PR to fix a doc merge conflict.
Please let's finish this PR now, too.

**Review by paulidale — APPROVED** [review]

**Comment by DDvO** [comment]
Merged - thanks @paulidale

**Pull request closed without merging**
