### PR TITLE
Fix memory leak of conn in new_conn()

### PR DESCRIPTION
**Pull request by zengwei2000**
fix the Memory leak: conn

Signed-off-by: zengwei zengwei1@uniontech.com

CLA: trivial

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
@zengwei2000 If you closed this PR because of the CLA requirement, I think this one-line addition of `free(conn)` is likely to be accepted as "CLA: trivial" - see https://www.openssl.org/policies/cla.html.

To do this, you need to edit the commit message and put `CLA: trivial` on a line on its own, and `git push -f` to update this PR. (It can't be done by adding another commit.)

**Comment by zengwei2000** [comment]
> @zengwei2000 If you closed this PR because of the CLA requirement, I think this one-line addition of `free(conn)` is likely to be accepted as "CLA: trivial" - see https://www.openssl.org/policies/cla.html.
> 
> To do this, you need to edit the commit message and put `CLA: trivial` on a line on its own, and `git push -f` to update this PR. (It can't be done by adding another commit.)

Okay, I will modify the commit information again

**Comment by zengwei2000** [comment]
> @zengwei2000 If you closed this PR because of the CLA requirement, I think this one-line addition of `free(conn)` is likely to be accepted as "CLA: trivial" - see https://www.openssl.org/policies/cla.html.
> 
> To do this, you need to edit the commit message and put `CLA: trivial` on a line on its own, and `git push -f` to update this PR. (It can't be done by adding another commit.)

I have modified the commit information. Could you please check if it is correct

**Comment by tom-cosgrove-arm** [comment]
> Could you please check if it is correct

Ah, sorry, you've done exactly what I asked, but looks like I missed two things: (1) there should be a blank line before the line with `CLA: trivial` and it should be at the end of the commit message (i.e. after the sign-off line)

See https://github.com/openssl/openssl/blob/master/CONTRIBUTING.md?plain=1#L27 (which I should have checked first, sorry)

**Comment by zengwei2000** [comment]
> > Could you please check if it is correct
> 
> Ah, sorry, you've done exactly what I asked, but looks like I missed two things: (1) there should be a blank line before the line with `CLA: trivial` and it should be at the end of the commit message (i.e. after the sign-off line)
> 
> See https://github.com/openssl/openssl/blob/master/CONTRIBUTING.md?plain=1#L27 (which I should have checked first, sorry)

Okay, I have revised the submission according to your suggestion

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM, agree trivial (repeated pattern, missing one line)

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
OK with CLA:trivial

**Comment by t8m** [comment]
Merged to the master and 3.2 branches. Thank you for your contribution.

**Pull request closed without merging**
