### PR TITLE
Misc docs fixups

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by richsalz** [comment]
can you update util/doc-nit-check to look for missing NAME section?  I am surprised that the podchecker didn't find that.

**Comment by levitte** [comment]
Is there a reason why you closed this?

**Comment by richsalz** [comment]
wrong click

**Comment by levitte** [comment]
Found some bugs and added more debugging output.

**Comment by richsalz** [comment]
+1

**Comment by levitte** [comment]
Merged!  Thanks for reviewing

**Pull request closed without merging**
