### PR TITLE
fix spell: adroideabi -> androideabi

### PR DESCRIPTION
**Pull request by pass86**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
@kaduk, can you merge and fix the CLA trivial marker when you do so?

**Comment by kaduk** [comment]
sure, I'll merge.

**Comment by kaduk** [comment]
@richsalz does approval extend to 1.1.0 backport?

**Comment by richsalz** [comment]
it does now :)

**Comment by kaduk** [comment]
Okay, pushed to both master and 1.1.0, and closing.
Thanks!

**Pull request closed without merging**
