### PR TITLE
Making "test_ca" to run happy

### PR DESCRIPTION
**Pull request by andrejs-igumenovs**
Running prior my change:
    
    @@@ START test_ca
    CA certificate filename (or enter to create)
    Use of uninitialized value $FILE in scalar chop at ../apps/CA.pl line 124.
    Making CA certificate ...

### CODE REVIEW

**Comment by richsalz** [comment]
Do you have the latest version?  Look at "my $FILE" on line 42.

**Comment by andrejs-igumenovs** [comment]
Yes, I've got the latest version.

**Comment by richsalz** [comment]
then why does your perl complain?

**Comment by andrejs-igumenovs** [comment]
Try to run the test...

**Comment by andrejs-igumenovs** [comment]
$ perl script.pl < /dev/null
    empty

**Comment by richsalz** [comment]
and what happens if you run it but just hit a return?  it is NOT empty.  that is why the chop() is there.

**Comment by andrejs-igumenovs** [comment]
Should it be like this then?:

    $FILE = <STDIN>;
    if ($FILE) {chop $FILE;}

**Comment by richsalz** [comment]
yeah, basically.  about to check that in.  How do you want your name to be credited in the commit message?

**Comment by andrejs-igumenovs** [comment]
I'm ok to stay uncredited for this one, it's just a small 'side effect'.:)
At least for now, my main contribution is to write unit tests, but seems I'm a bit lonely on this one...

**Comment by richsalz** [comment]
thanks for pushing on this one, and your contributions to help improve openssl!

**Pull request closed without merging**
