### PR TITLE
Fix a collision in function err numbers

### PR DESCRIPTION
**Pull request by InfoHunter**
Both `EVP_F_GMAC_CTRL` and `EVP_F_POLY1305_CTRL` use number 215, which leads to 'make update' failed.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by InfoHunter** [comment]
CI failures are not related (seems gmac is not compiled).

**Comment by levitte** [comment]
Yup.  See #7572

**Comment by InfoHunter** [comment]
I assume this doesn't need a grace time period, so I decide to merge this soon to make Is happier.

**Comment by InfoHunter** [comment]
Pushed to master as 41eac6122a

**Pull request closed without merging**
