### PR TITLE
Enable TLSProxy tests on Windows

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
this is the silly behavior of windows when SO_REUSEADDR is around.

**Comment by levitte** [comment]
Thanks @bernd-edlinger, that confirmed my suspicions.

I've just rewritten `TLSProxy::Proxy` to only create the proxy socket *once* per object instance.  That seems to resolve the problem quite nicely.

**Comment by bernd-edlinger** [comment]
maybe "ReuseAddr   => 1" is not a good idea for windows?

**Comment by levitte** [comment]
Maybe not, but without it, the pile of TIME_WAIT builds up quickly...  Have a look at #5095, that seems to solve the problem quite nicely.

**Comment by levitte** [comment]
Taking this out of WIP.  This depends on #5095 for proper function

**Comment by bernd-edlinger** [comment]
not that I know really much about windows...
You say when you use ReuseAddr on the listening socket there are no TIME_WAIT sockets?

**Comment by bernd-edlinger** [comment]
@levitte I grabbed an old Windows /7 32bit machine, with VS2008 and Strawberry perl on it, and
tried to find out if I can reproduce your problem.

But actually I have something different, with and without this patch:
```
   0 cache full overflows (128 allowed)
invalid engine "ossltest"
151136:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:107:filename(C:\Program Files\OpenSSL\lib\engines-1_1\ossltest.dll)
151136:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:162:
151136:error:260B6084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:414:
151136:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto\engine\eng_list.c:334:id=ossltest
151136:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:107:filename(ossltest.dll)
151136:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:162:
151136:error:260B6084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:414:
CONNECTION FAILURE
151136:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl\record\ssl3_record.c:507:
Waiting for client process to close: -150852
not ok 5 - Noncompliant supported_groups extension
#   Failed test 'Noncompliant supported_groups extension'
#   at test\recipes\70-test_sslextension.t line 181.
Server command: ..\..\apps\openssl.exe s_server -no_comp -rev -engine ossltest -accept 4443 -cert ..\..\apps\server.pem -cert2 ..\..\apps\server.pem -naccept 1 -cipher AES128-SHA:TLS13-AES-128-GCM-SHA256
Proxy started on port 4453
Client command: echo test | ..\..\apps\openssl.exe s_client -engine ossltest -connect localhost:4453 -no_tls1_3
Using default temp DH parameters
ACCEPT
Connection opened
Received client packet
Packet length = 202
Processing flight 0
 Record 1 (client -> server)
  Content type: HANDSHAKE
  Version: TLS1.0
  Length: 197
  Message type: ClientHello
  Message Length: 193
    Client Version:771
    Session ID Len:0
    Ciphersuite len:56
    Compression Method Len:1
    Extensions Len:96

Forwarded packet length = 202

Received server packet
Packet length = 1093
Processing flight 1
 Record 1 (server -> client)
  Content type: HANDSHAKE
  Version: TLS1.2
  Length: 61
  Message type: ServerHello
  Message Length: 57
    Server Version:771
    Session ID Len:0
    Ciphersuite:47
    Compression Method:0
    Extensions Len:17
 Record 2 (server -> client)
  Content type: HANDSHAKE
  Version: TLS1.2
  Length: 1013
  Message type: Certificate
  Message Length: 1009
    Certificate List Len:1006
    Certificate Len:1003
 Record 3 (server -> client)
  Content type: HANDSHAKE
  Version: TLS1.2
  Length: 4
  Message type: ServerHelloDone
  Message Length: 0

Forwarded packet length = 1099

Received client packet
Packet length = 7
Processing flight 2
 Record 1 (client -> server)
  Content type: ALERT
  Version: TLS1.2
  Length: 2

Forwarded packet length = 7

Connection closed
Waiting for server process to close: -150264
CONNECTED(00000110)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 72 bytes and written 209 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1516290516
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
invalid engine "ossltest"
151016:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:107:filename(C:\Program Files\OpenSSL\lib\engines-1_1\ossltest.dll)
151016:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:162:
151016:error:260B6084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:414:
151016:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto\engine\eng_list.c:334:id=ossltest
151016:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:107:filename(ossltest.dll)
151016:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:162:
151016:error:260B6084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:414:
151016:error:1423406E:SSL routines:tls_parse_stoc_sct:bad extension:ssl\statem\extensions_clnt.c:1415:
   0 items in the session cache
   0 client connects (SSL_connect())
   0 client renegotiates (SSL_connect())
   0 client connects that finished
   1 server accepts (SSL_accept())
   0 server renegotiates (SSL_accept())
   0 server accepts that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
   0 callback cache hits
   0 cache full overflows (128 allowed)
invalid engine "ossltest"
144904:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:107:filename(C:\Program Files\OpenSSL\lib\engines-1_1\ossltest.dll)
144904:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:162:
144904:error:260B6084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:414:
144904:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto\engine\eng_list.c:334:id=ossltest
144904:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:107:filename(ossltest.dll)
144904:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:162:
144904:error:260B6084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:414:
CONNECTION FAILURE
144904:error:14094456:SSL routines:ssl3_read_bytes:tlsv1 unsupported extension:ssl\record\rec_layer_s3.c:1587:SSL alert number 110
Waiting for client process to close: -10200
ok 6 - Unsolicited sct extension
ok 7 # skip TLS 1.3 disabled
# Looks like you failed 2 tests of 7.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/7 subtests
        (less 1 skipped subtest: 4 okay)
```

I have not installed anything yet, therefore the test tries to load the engine from the wrong place.

**Comment by bernd-edlinger** [comment]
above comment is actually meant to be posted at #5095 so "with and without _this_ patch"
refers to #5095...

**Comment by levitte** [comment]
Either way, that's unrelated to the TLSProxy work, it seems. For some reason, openssl doesn't look for openssl.dll in the build tree, despite OPENSSL_ENGINES being set?

I'm not in a position to see for myself right now, unfortunately...

**Comment by bernd-edlinger** [comment]
Hmm, it looks like OPENSSL_ENGINES is only set for unix?

```
grep -r OPENSSL_ENGINES *
apps/version.c:        printf("%s\n", OpenSSL_version(OPENSSL_ENGINES_DIR));
CHANGES:     time with the environment variable OPENSSL_ENGINES.
Configurations/unix-Makefile.tmpl:	  OPENSSL_ENGINES=`cd ../$(BLDDIR)/engines; pwd` \
Configurations/descrip.mms.tmpl:        DEFINE OPENSSL_ENGINES {- builddir("engines") -}
Configurations/descrip.mms.tmpl:        DEASSIGN OPENSSL_ENGINES
crypto/cversion.c:    case OPENSSL_ENGINES_DIR:
crypto/engine/eng_list.c:        if ((load_dir = getenv("OPENSSL_ENGINES")) == NULL)
doc/man3/OPENSSL_VERSION_NUMBER.pod:=item OPENSSL_ENGINES_DIR
doc/man3/ENGINE_add.pod:=item B<OPENSSL_ENGINES>
doc/man1/engine.pod:=item B<OPENSSL_ENGINES>
include/openssl/crypto.h:# define OPENSSL_ENGINES_DIR      5
test/recipes/30-test_afalg.t:$ENV{OPENSSL_ENGINES} = bldtop_dir("engines/afalg");
util/opensslwrap.sh:if [ -d "${HERE}../engines" -a "x$OPENSSL_ENGINES" = "x" ]; then
util/opensslwrap.sh:	OPENSSL_ENGINES="${HERE}../engines"; export OPENSSL_ENGINES
```

**Comment by levitte** [comment]
Oh darn, did I forget it in `Configurations/windows-makefile.tmpl`? That needs fixing. Fell free :-)

**Review by bernd-edlinger — APPROVED** [review]

**Comment by levitte** [comment]
Merged!  c5856878f709edb00759d56a55ccddb2ecd67d87

And thanks for fighting through all the issues with me!

**Pull request closed without merging**
