### PR TITLE
Make Windows build more robust

### PR DESCRIPTION
**Pull request by Nekto89**
(cherry picked from commit b5756085078f43c0a6c9a22ba6e87bc073515780)

##### Checklist
- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by Nekto89** [comment]
After applying this patch on top of 1.1.1w I was able to build OpenSSL locally with $(CC) that has spaces.
https://github.com/conan-io/conan-center-index/issues/21167

**Comment by FdaSilvaYY** [comment]
1.1.1 is End-Of-Life, sorry.
So, this will not be merged.
Ping @bernd-edlinger, who is maintaining its own 1.1.1 branch.

**Comment by bernd-edlinger** [comment]
Well, if you want I can look into back-porting b575608 into my 1.1.1 feature branch,
which is located here: https://github.com/bernd-edlinger/openssl/tree/openssl-111-features

I have a few questions, since I've noticed that one change of quotes around the
CPP macro:
https://github.com/openssl/openssl/blob/b5756085078f43c0a6c9a22ba6e87bc073515780/Configurations/windows-makefile.tmpl#L191
was later reverted by 16f2a44
https://github.com/openssl/openssl/blob/16f2a44435fccbd7466b0659220c765a17e5d0c0/Configurations/windows-makefile.tmpl#L229

I think the C pre-processor is only used for creating dependencies,
can you please double-check that dependencies are still working with your patch?

**Comment by levitte** [comment]
This is a bit controversial, really. If `ccache` is ever implemented and used, this change would make something like `nmake "CC=ccacha cl"` impossible. Likewise if someone wants some special flag on all `cl` runs.

**Pull request closed without merging**
