### PR TITLE
Fix copyright disclaimer.

### PR DESCRIPTION
**Pull request by paulidale**
The mention of the GPL shouldn't have been there.

### CODE REVIEW

**Review by t-j-h — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Side note: that note was added in 2013 (e0202d946d68bd91a3e99f223c66d1fce7db136a), before we had our CLAs.  Not sure we can say whether it should or shouldn't have been added *at that time*...

**Comment by t-j-h** [comment]
> Side note: that note was added in 2013 ([e0202d9](https://github.com/openssl/openssl/commit/e0202d946d68bd91a3e99f223c66d1fce7db136a)), before we had our CLAs. Not sure we can say whether it should or shouldn't have been added _at that time_...

It should not have been added then either as the statement is actually both confusing (to some) and incorrect.

**Comment by tom-cosgrove-arm** [comment]
I've "reached out" to Ard to get him to confirm. Otherwise we can raise with Linaro if you like

**Comment by t8m** [comment]
> I've "reached out" to Ard to get him to confirm. Otherwise we can raise with Linaro if you like

We've already got confirmation from him.

**Comment by t8m** [comment]
Merged to all active branches. Thank you.

**Pull request closed without merging**
