### PR TITLE
Fix compile err when build VC-CLANG-WIN64-CLANGASM-ARM target 

### PR DESCRIPTION
**Pull request by zhiqxie**
Fix compile err when build VC-CLANG-WIN64-CLANGASM-ARM target on MSVC v143,C++ Clang Compiler for Windows(16.0.5)

Error is "brackets expression not supported on this target" in libcrypto-shlib-bsaes-armv8.obj.asm

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Review by shahsb — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Comment by zhiqxie** [comment]
Hi @t8m, I want merge this change to 3.0/3.1/3.2/3.3 branch, what do I need to do?  Thanks,

**Comment by t8m** [comment]
This target is not present on 3.0 branch so it cannot be merged there.

For the other branches if @nhorman agrees, I will just cherry-pick the commit.

**Comment by t8m** [comment]
Reopening for merging to other branches.

**Comment by nhorman** [comment]
Yeah, seems reasonable to be

**Comment by t8m** [comment]
Cherry picked to 3.3, 3.2 and 3.1 branches.

**Pull request closed without merging**
