### PR TITLE
fix generated Makefile for Windows builds made on *nix (1.1.1d)

### PR DESCRIPTION
**Pull request by bernd-edlinger**
I revived this PR as I wrote there https://github.com/openssl/openssl/pull/9864#issuecomment-562827050
I fixed the merge conflict mentioned here https://github.com/openssl/openssl/pull/9864#issuecomment-562827634 in a trivial way

I hope that can be included in 1.1.1f

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
@vszakats please speak up if you have objections to this being included in 1.1.1f

**Comment by bernd-edlinger** [comment]
Travis looks unrelated:
```
$ git clone --depth=50 --quiet https://github.com/openssl/openssl.git openssl/openssl

$ cd openssl/openssl

63.42s$ git fetch origin +refs/pull/11434/merge: --quiet

fatal: unable to access 'https://github.com/openssl/openssl.git/': Could not resolve host: github.com

The command "eval git fetch origin +refs/pull/11434/merge: --quiet " failed. Retrying, 2 of 3.

fatal: unable to access 'https://github.com/openssl/openssl.git/': Could not resolve host: github.com

The command "eval git fetch origin +refs/pull/11434/merge: --quiet " failed. Retrying, 3 of 3.

fatal: unable to access 'https://github.com/openssl/openssl.git/': Could not resolve host: github.com

The command "eval git fetch origin +refs/pull/11434/merge: --quiet " failed 3 times.

The command "git fetch origin +refs/pull/11434/merge: --quiet" failed and exited with 128 during .

Your build has been stopped.
```

**Comment by vszakats** [comment]
@bernd-edlinger No objections — On the contrary, I'm glad if this can make into the next release. Thanks for reviving it.

**Comment by levitte** [comment]
Travis failure are irrelevant timeouts

**Comment by bernd-edlinger** [comment]
Merged to 1.1.1 as ff3e9e1
Thanks!

**Pull request closed without merging**
