### PR TITLE
Remove ECDH(E) ciphers from SSLv3

### PR DESCRIPTION
**Pull request by tmshort**
SSLv3 does not support TLS extensions, and thus, cannot provide any
curves for ECDH(E). With the removal of the default (all) list of curves
being used for connections that didn't provide any curves, ECDHE is no
longer possible.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by kroeckx** [comment]
My understanding is that even though the standard is about TLS, it still works with SSLv3 because of defaults. That it, if it's configured to only support SSLv3 and doesn't send extensions, it can still use ECDHE successfully. But I have no problem with this change.

**Comment by tmshort** [comment]
@rsalz removed the default "all" list of curves when no curves were provided by the client (as in the case of SSLv3), so these ciphers don't actually work anymore in master and OpenSSL 1.1.0e with SSLv3.  It was PR #1597.

**Comment by richsalz** [comment]
fe55c4a in master and 9d522f0 in 1.1.0; thanks!

**Comment by rsalz** [comment]
stop including me in your github threads please

**Comment by kroeckx** [comment]
I'm not sure how we include you, or what we can do about it. But @richsalz uses rsalz in his email address.

**Comment by richsalz** [comment]
The problem is that Todd put rsalz in the thread, not @richsalz  Because yes my email is rsalz at wherever.  Sorry, rsalz.  You can mute the threads when these mistakes happen again; click on the "mute this thread" at the bottom of the email you get.

**Comment by kroeckx** [comment]
For some reason I didn't notice that he did that.

**Comment by tmshort** [comment]
Yes, my bad. I already fixed it. rsalz opened his account ~2/2014, richsalz opened his account ~12/2014... I missed my chance at tshort by several years, apparently.

**Comment by mattcaswell** [comment]
This change broke stuff. The Boring tests are failing as a result of this change.

**Comment by tmshort** [comment]
That could happen if the Boring tests use SSLv3+ECDHE. The Boring tests are not run via 'make test' AFAIK; how does one run them?

**Comment by levitte** [comment]
Have a look at [test/README.external](https://github.com/openssl/openssl/blob/master/test/README.external)

**Comment by davidben** [comment]
BoringSSL tests currently believe servers should never negotiate ECDHE at SSL 3.0, for the same reasons as this PR, but that clients which offer it (because perhaps they support both TLS 1.0 and SSL 3.0) should be prepared to accept a server selecting it at SSL 3.0 as existing servers may still select it.

(I actually like this behavior better for simplicity, but it risks breaking clients which enable both SSL 3.0 and TLS 1.0+, less of a concern now. On our end I hope to delete the SSL 3.0 code in not too long, so I figured I'd leave it alone until then.)

**Comment by tmshort** [comment]
> should be prepared to accept a server selecting [ECDHE] at SSL 3.0 as existing servers may still select it.

Yeah, that no longer works with this PR.

**Comment by richsalz** [comment]
Which "this"?  And what curve do your servers pick for SSL3?
I *think* the reasonable thing to do is for us to disable that test for now

**Comment by tmshort** [comment]
I agree with @richsalz

**Comment by davidben** [comment]
@richsalz "this" being the client behavior in this PR. I like it better for simplicity, but we didn't go with it back then because it has a compatibility risk with clients that enable SSL 3.0 and TLS 1.0+. Such clients will offer ECDHE ciphers since they are compatible with the version range. Should a server pick SSL 3.0 + ECDHE (which existing OpenSSLs happily do), this PR will cause it to break.

This is less of a concern now and, yes, I think disabling the tests makes sense. They'll end up being deleted once we've removed the SSL 3.0 code.

> And what curve do your servers pick for SSL3?

Umm, none? Like I said, we do not negotiate ECDHE + SSL3 on servers and the tests assert accordingly.

**Comment by levitte** [comment]
Anyone that knows exactly what tests should be disabled is welcome to make a PR for it ;-)

**Comment by tmshort** [comment]
I'll do it. I "broke" it, I'll fix it.

**Comment by mattcaswell** [comment]
So what I don't understand is why this test only broke as a result of this change, and not as a result of the removal of the default curve concept.

**Comment by davidben** [comment]
This PR comes with a behavior change on the client.

**Comment by mattcaswell** [comment]
Right. Rewinding a bit to the basic premise of this change. I was under the impression from the discussion at the top of this PR that ECHDE was broken in SSLv3 anyway, so this didn't make a big difference. However I just tested this out and discovered that prior to this change master was perfectly able to negotiate an SSLv3 ECDHE connection, but after this change it is no longer able to.

To test I set up a 1.0.2 s_server instance with "-ssl3" as an argument. I then attempted to connect to it from a master s_client instance. Before this change it works perfectly and uses ECDHE-RSA-AES256-SHA with P-256. After this change it fails: the client reports "wrong cipher returned" and sends an illegal parameter exception.

It seems to me we need to rethink this. Perhaps a revert is in order rather than disabling the test?

**Comment by richsalz** [comment]
A more interesting question is what do post-PR servers do with pre-PR clients?  ECDHE isn't broken, its just not defined.

**Comment by tmshort** [comment]
ECDHE ciphers are not defined for SSLv3, they are defined for TLSv1, as SSLv3 does not support the TLS extensions necessary to specify the curves to be used with ECDHE. The relevant spec is https://tools.ietf.org/html/rfc4492 And as @richsalz points out what about 1.0.2 s_client to master s_server (both before and after this PR)? I believe it fails due to PR #1597

**Comment by davidben** [comment]
Post-PR servers with pre-PR clients is easy: the client offers ECDHE at SSL 3 but the server declines it and picks a different cipher.

Pre-PR servers with post-PR clients is the messy one. That one causes an interop failure in some circumstances. See my comments.

**Comment by mattcaswell** [comment]
So, this change makes things better on the server side (if people deploy version 1.1.0/master with SSLv3 enabled - which doesn't sound very likely) because it means we never select ECDHE. But it makes things worse on the client side if people using 1.1.0/master clients encounter an SSLv3 server which selects ECDHE. That second scenario sounds like something much more likely to happen, than people enabling SSLv3 on the server side with a recent version of OpenSSL.

Reverting this change seems like the correct response to me. Perhaps followed up by a change adding logic that only impacts the server side that prevents the selection of ECDHE on the server in SSLv3.

**Comment by tmshort** [comment]
In terms of use, OpenSSL is much more frequently used as a server-side engine than client-side (NSS, BoringSSL, MS SChannel, Apple Secure Transport, and Java SSE being the large majority of client-side engines), so I disagree with @mattcaswell's assessment.

A beneficial side-effect of this change is that it updates he list of ciphers shown via "ciphers -<proto> -s".

 This boils down to: do we want to be correct, or do we want to remain compatible with an out-of-date protocol? (I could really insult SSLv3 here, but I'll just leave it at that.)

**Comment by mattcaswell** [comment]
We should not break compatibility unnecessarily - and that is exactly what this change does IMO. For now (rightly or wrongly) we have chosen to support SSLv3 - presumably on the basis that we think people are going to continue to use it. Whilst it might be undefined it wasn't broken before - and now it is. I have no objection to us preventing ECHDE selection on the server side - but this change breaks clients - and that I do object to.

**Comment by richsalz** [comment]
1. It's SSLv3
2. Clients that used to work were clients that were out of spec.

**Comment by tmshort** [comment]
The only way this could really happen is if a server supported only SSLv3 and offered up ECDHE; that's a very rare combination, and the s_client software will not offer ECDHE if it only supports SSLv3. So the error case really is:

s_client (SSLv3 or TLS) + ECDHE <-> server SSLv3 + ECDHE only (or preferred)

If TLS was available, the server should use that, and everything would be fine...
If the new s_client only offered SSLV3, then ECDHE would not be an option, so it wouldn't be a problem.

I find it highly unlikely that there'd be a server configured for only SSLv3 and has ECDHE ciphers configured; ECDHE ciphers post-date SSLv3 and TLSv1.

**Comment by levitte** [comment]
Leaning back on policy, minor updates (i.e. any 1.1.*x*) should retain backward ABI and API compatibility.  Does this count as a breach?  In that case, a revert is our only resort.

**Pull request closed without merging**
