### PR TITLE
Update CHANGES.md and NEWS.md for new release (master)

### PR DESCRIPTION
**Pull request by mattcaswell**

### CODE REVIEW

**Review by levitte — APPROVED** [review]
Approved with acclamation!

**Comment by mattcaswell** [comment]
Now with added "Release: yes" line in the commit

**Review by levitte — APPROVED** [review]

**Comment by mattcaswell** [comment]
Ummm...after further discussion with @levitte, I've removed the "Release: yes" again from this one since this is the master branch!!

**Comment by mattcaswell** [comment]
> 24 hours has passed since 'approval: done' was set, but this PR has failing CI tests.

No idea what the bot is on about. There are no failing tests. Applying the ready-to-merge label.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
