### PR TITLE
Validate ClientHello extension field length (1.0.2 and 1.0.1)

### PR DESCRIPTION
**Pull request by ghedo**
RT#4069

### CODE REVIEW

**Comment by ghedo** [comment]
The `data > (d + n - len)` check after the one I added seem superfluous now, but I wasn't sure so I left it.

**Comment by mattcaswell** [comment]
It is superfluous. It should be removed.

**Comment by ghedo** [comment]
Ok, done.

**Comment by mattcaswell** [comment]
Patch applied. Many thanks.

**Pull request closed without merging**
