### PR TITLE
Disallow overwriting md_size if already set

### PR DESCRIPTION
**Pull request by beldmit**
If EVP_MD is already initialized, changing the digest size can cause many problems. Let's forbid it.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Why not the others?

**Comment by beldmit** [comment]
Hmmm... block_size and ctx_size? And the similar for EVP_CIPHER?

**Comment by levitte** [comment]
I actually think that this kind of check should be done uniformly in all `_meth_set_` functions. After all, some building a new `EVP_MD`, `EVP_CIPHER` or whatnot should only need to call each such function once.

**Comment by beldmit** [comment]
OK. Will do tomorrow.

**Comment by kroeckx** [comment]
I suspect this will actually break existing applications that try to reuse it.

**Comment by levitte** [comment]
We've just cleared one such misuse in gost. Do you have other examples to point at, @kroeckx ?

**Comment by kroeckx** [comment]
I don't have any examples. And if you find 1, there probably will
be others.

**Comment by levitte** [comment]
Point is, spuriously re-defining an EVP_MD or similar should be considered misuse.

**Comment by kroeckx** [comment]
I agree that it's misuse, that doesn't prevent people from doing it.

**Comment by beldmit** [comment]
A major release is a good time to stop it.

**Comment by levitte** [comment]
Not only is it misuse, but it has turned out to be unsafe to modify these structures after they started to be used, or quite confusing.  That, to me, is justification enough for this mod.

**Comment by beldmit** [comment]
Can it be committed now, approved by @levitte? And how can I squash the 1st commit as a part of the 2nd?

**Comment by levitte** [comment]
> And how can I squash the 1st commit as a part of the 2nd?

Interactive rebase, i.e. `git rebase -i master`.  You'll get a TODO to edit, in which you should set the second commit to be squashed.  Save, and then you'll get the combined commit message from both, for you to edit as you see fit.  Save.  Done.

**Comment by beldmit** [comment]
Merged.

**Comment by petrovr** [comment]
Richard Levitte wrote:
> Point is, spuriously re-defining an EVP_MD or similar should be considered misuse.
>

In general until use of a module program must be able to preset 
respective parameters.
But some programs decide to use value set first and to ignore override.

So to use initial value of parameters or current values? Which one is 
better? No one!

 From general point of view -1 on this.

Regards,
Roumen Petrov

**Pull request closed without merging**
