### PR TITLE
testutil: always print errors on failure

### PR DESCRIPTION
**Pull request by ekasper**

### CODE REVIEW

**Comment by levitte** [comment]
I'm noticing all those empty teardowns...  do they have to exist or could we remove them and have `EXECUTE_TEST()` accept a `NULL`?

**Comment by ekasper** [comment]
I plan to clean up some more so that we can have an `ADD_SIMPLE_TEST` that has no setup or teardown.

**Comment by ekasper** [comment]
(Or rather, we can just reuse `ADD_TEST`... anyway I'll clean those up in a separate PR.)

**Comment by levitte** [comment]
Would you mind rebasing?  I hope the latest master builds green on Travis...

**Comment by ekasper** [comment]
Rebased. Part two is in https://github.com/openssl/openssl/pull/1841

**Comment by ekasper** [comment]
I think the remaining Travis failure is unrelated (it's the shlib_loadtest).

**Comment by levitte** [comment]
Agreed

**Pull request closed without merging**
