### PR TITLE
fix: let util/mkbuildinf.pl use SOURCE_DATE_EPOCH, even if it's zero

### LINKED ISSUE #25475: SOURCE_DATE_EPOCH Value of 0 Does Not Override Date
I discovered this on OpenSSL version 1.1.1d, but it is present in the latest master branch as well. The issue is that if you use a SOURCE_DATE_EPOCH value of 0, the test in util/mkbuildinf.pl will always grab the current time. Setting SOURCE_DATE_EPOCH to a value of 0 is useful for other projects that use it to disable certain timestamp inclusions in their compiled binaries to generate reproducible builds.

This issue was introduced by this commit:

https://github.com/openssl/openssl/commit/8a8d9e190533ee41e8b231b18c7837f98f1ae231#diff-60728b88cb2b16f42e41cee0c1ca3c632f2f951619d6b26dac54d2bd38e39958

Something like this could work:

```
my $source_date_epoch = $ENV{'SOURCE_DATE_EPOCH'};

my $date="";
if (defined $source_date_epoch){
    $date = gmtime($source_date_epoch);
}
else{
    $date = gmtime(time());
}
$date .= " UTC";
```

### PR DESCRIPTION
**Pull request by levitte**
Doing this allows reproducible builds, for those who want this.

Fixes #25475

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
SOURCE_DATE_EPOCH is also mentioned in #10061

**Review by shahsb — APPROVED** [review]
LGTM.

**Comment by levitte** [comment]
Merged

3.0:
50d79e0916d8d6e38c458e35f5a4863c5d6f4ca2 fix: let util/mkbuildinf.pl use SOURCE_DATE_EPOCH, even if it's zero

3.1:
c5e0f55f73a7f8d6c5cf15d7e14dc2b5a5f380b5 fix: let util/mkbuildinf.pl use SOURCE_DATE_EPOCH, even if it's zero

3.2:
503e26990969ef03e4becaf058f2b7f101519d67 fix: let util/mkbuildinf.pl use SOURCE_DATE_EPOCH, even if it's zero

3.3:
1260253a4444d5bb618801adef7cbe94b53eea2e fix: let util/mkbuildinf.pl use SOURCE_DATE_EPOCH, even if it's zero

3.4:
fb2f348ece6928cb19cb20636a95c07320aacebc fix: let util/mkbuildinf.pl use SOURCE_DATE_EPOCH, even if it's zero

master:
7b36037e2201ea6927458c1b5fc31502d0747b6f fix: let util/mkbuildinf.pl use SOURCE_DATE_EPOCH, even if it's zero

**Pull request closed without merging**
