### PR TITLE
a_strex.c: prevent out of bound read in do_buf()

### PR DESCRIPTION
**Pull request by mspncp**
...which is used for ASN1_STRING_print_ex*() and X509_NAME_print_ex*().

### CODE REVIEW

**Comment by mspncp** [comment]
Should I backport this?

**Comment by levitte** [comment]
> @levitte, you're faster than the speed of light! :wink: 

Are you on the moon?  :grin: 

> Should I backport this?

Sure...  although, does it cherry-pick cleanly to 1.1.0?  Then there's no need to make a separate PR...

**Comment by mspncp** [comment]
>> @levitte, you're faster than the speed of light! :wink: 

> Are you on the moon?  :grin: 

Well, you approved the pull request _before_ I finished documenting it. So you must have travelled _back_ in time, i.e. faster than the speed of light.

>> Should I backport this?

> Sure...  although, does it cherry-pick cleanly to 1.1.0?  Then there's no need to make a separate PR...

Well, the changes to `crypto/asn1/a_strex.c` can be cherry-picked, but the error codes not. They require a separate `make errors`, after which `ASN1_F_DO_BUF` gets assigned a different number on 1.1.0. How do you normally deal with these cases?

**Comment by mspncp** [comment]
[Travis failure](https://travis-ci.org/openssl/openssl/jobs/371718077) is caused by `apt-get`.

**Comment by levitte** [comment]
> Well, the changes to `crypto/asn1/a_strex.c` can be cherry-picked, but the error codes not. They require a separate `make errors`, after which `ASN1_F_DO_BUF` gets assigned a different number on 1.1.0. How do you normally deal with these cases?

For 1.0.2, we don't care, since 1.1.0 has renumbered more or less everything anyway.

**Comment by mspncp** [comment]
> For 1.0.2, we don't care, since 1.1.0 has renumbered more or less everything anyway.

I was actually talking about backporting from master to 1.1.0. Is it necessary and/or desirable that the error codes (here: ASN1_F_DO_BUF) are the same value on both branches? If yes, the conflicts need to be resolved manually. If no, it would be sufficient to only cherry-pick the changes made to ` crypto/asn1/a_strex.c` and then rerun `make errors` afterwards.

**Comment by levitte** [comment]
Hmmm, we usually do keep the numbers in sync between 1.1.0 and 1.1.1, so...

**Comment by mspncp** [comment]
Richard, since you approved this pr, would you mind approving the backports #6117 and #6118, too?

**Comment by mspncp** [comment]
Merged thanks!

c671843770  master
ebdeeb363f  1.1.0 (#6117)
7e6c0f56e6  1.0.2 (#6118)

**Pull request closed without merging**
