### PR TITLE
Added debug log callback capabilities

### PR DESCRIPTION
**Pull request by OlegPekar**
Due to intensive usage of OpenSSL libs linked to my product, sometimes there's a need to investigate OpenSSL behaviour while troubleshooting specific problem in the product. Debugging is not always possible to the best option is to add debug log to OpenSSL code. However logging using  printf() sometimes is not an option - the stdout/stderr may be redirected and not accessible directly. So the best solution is to let OpenSSL libs to log into a product debug log. Another profit is seeing OpenSSL debug log lines bound to the relevant product debug log lines.

### CODE REVIEW

**Comment by t8m** [comment]
This is a new feature and as such it needs to be submitted against the master branch. Please also note that there is already the OSSL_trace() API, that basically serves the same purpose.

Also to merge any contribution of non-trivial size we would need a CLA signed by you. https://www.openssl.org/policies/cla.html

**Comment by OlegPekar** [comment]
> This is a new feature and as such it needs to be submitted against the master branch. Please also note that there is already the OSSL_trace() API, that basically serves the same purpose.
I see - OSSL_trace() in the master branch does the function that I need. Is it planned to be ported to 1.1.1 branch? My interest is to get the debug logging callback from this upstream delivery to my product (otherwise I will need to patch my product's OpenSSL libs on every OpenSSL 1.1.1 release). If there're not plans for double-commit OSSL_trace() to 1.1.1 - which options do I have?
 
> Also to merge any contribution of non-trivial size we would need a CLA signed by you. https://www.openssl.org/policies/cla.html
I have already provided ICLA on Nov 28, 2019 and got a confirmation mail

**Comment by t8m** [comment]
I am sorry but we do not backport features to stable branches by policy. So the only thing you could do is to maintain a backported OSSL_trace support by yourself in a forked repository.

**Comment by OlegPekar** [comment]
> I am sorry but we do not backport features to stable branches by policy. So the only thing you could do is to maintain a backported OSSL_trace support by yourself in a forked repository.

Tomáš, thank you very much for the explanation. I have a bunch of other features done in my local OpenSSL repo. I will check whether they exist in the master branch and will submit the delta. What is about bug fixes - can I still submit them to 1.1.1 stable branch?

**Comment by t8m** [comment]
Bug fixes in general should go to the master branch and then can be backported into older stable branches if those bugs are there too. Only in case a bug fix would not be applicable to the master branch because it is not relevant there anymore, it can be merged only into the stable branch directly.

**Pull request closed without merging**
