### PR TITLE
Modify type of variable and remove needless type casting.

### PR DESCRIPTION
**Pull request by komainu8**
I suggest modify type of variable "file" from char * to const char *.
Because return value of getenv() should not change through a pointer.

And I think needless type casting of getenv()'s return value in line 50.
Because type of getenv()'s return value is char *.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
merged to master.  okay for 1.0.2 and 1.1.0?

**Comment by levitte** [comment]
+1 for a cherry pick to all other release branches.

**Comment by richsalz** [comment]
pushed.  but i just realized I didn't add you to the Reviewed line.  oops.

**Comment by levitte** [comment]
Let's call it even...  I forgot you once, remember?

**Pull request closed without merging**
