### PR TITLE
QUIC: Clarify idle timeout and make error codes public

### PR DESCRIPTION
**Pull request by hlandau**
Since applications are liable to rely on QUIC transport error codes we should make our definitions for these public and document them.

Document what value is returned in the event of idle timeout and add a definition for it.

### CODE REVIEW

**Comment by hlandau** [comment]
Updated.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
@paulidale please reconfirm

**Review by shahsb — APPROVED** [review]
LGTM

**Comment by hlandau** [comment]
Still awaiting second approval...

**Review by mattcaswell — APPROVED** [review]

**Review by t-j-h — APPROVED** [review]

**Comment by hlandau** [comment]
Merged to master. Thanks for the reviews.

**Pull request closed without merging**
