### PR TITLE
Add 4 new OIDs for PKIX key purposes and 3 new CMP information types

### PR DESCRIPTION
**Pull request by DDvO**
New PKIX key purpose identifier OIDs from https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#smi-numbers-1.3.6.1.5.5.7.3
```
id-kp 29                : cmcArchive            : CMC Archive Server
id-kp 30                : id-kp-bgpsec-router  : BGPsec Router
id-kp 31                : id-kp-BrandIndicatorforMessageIdentification : Brand Indicator for Message Identification
id-kp 32                : cmKGA                 : Certificate Management Key Generation Authority
 ```
New CMP information type OIDs from https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#smi-numbers-1.3.6.1.5.5.7.4
```
id-it 17               : id-it-caCerts
id-it 18               : id-it-rootCaKeyUpdate
id-it 19               : id-it-certReqTemplate
```

Most stuff in this PR is auto-generated from the above declarations.

### CODE REVIEW

**Comment by DDvO** [comment]
I hope this straightforward extension of OIDs will make it in before feature freeze,
and therefore I ask for a quick review.

**Comment by t-j-h** [comment]
Why this particular subset?
I find it a little strange to see the intermix of RFC referenced and IETF drafts.

It is it as simple as just adding the ones that are missing from the end of each list?
I note we have some in the middle missing.

**Comment by DDvO** [comment]
The `cmKGA` and the three `id-it` OIDs are brand new. They will be needed for supporting
* the upcoming update to RFC 4210: https://tools.ietf.org/html/draft-brockhaus-lamps-cmp-updates-03
* and the lightweight CMP profile: https://tools.ietf.org/html/draft-brockhaus-lamps-lightweight-cmp-profile-03

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
@t-j-h's implication of add the missing values is reasonable but unless we use them, there is no point.

**Comment by DDvO** [comment]
Merged - thanks @paulidale

**Pull request closed without merging**
