### PR TITLE
Update gcm128.c

### PR DESCRIPTION
**Pull request by zjd87**
gcm algorithm  calculate  mac or tag  fix

Signed-off-by: Zhang Jinde <zjd5536@163.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Are there test vectors available that can be added to verify your changes?

**Comment by zjd87** [comment]
> Are there test vectors available that can be added to verify your changes?

how to add test vector. First time, commit to openssl

**Comment by slontis** [comment]
Can you point me to the test vector so I can look first?

**Comment by slontis** [comment]
If you look in test/recipes/30-test_evp_data/evpmac_common.txt
there are some GMAC entries.. (starting on line 251).

**Comment by slontis** [comment]
You can run these via..
```
> export LD_LIBRARY_PATH=.
> ./test/evp_test test/recipes/30-test_evp_data/evpmac_common.txt
```

To test just one thing locally you can just put one test into a separate file and then use it as input like the above line.

**Comment by slontis** [comment]
The link on the existing tests were from
http://www.ieee802.org/1/files/public/docs2011/bn-randall-test-vectors-0511-v1.pdf (which is fairly old).

**Comment by zjd87** [comment]
I think  we can follow test: in openssl code ,  #undef GHASH,  then test, because  usually  not go my fix logic,  algorithm use AES-128-GCM , TLSv1.2, then  use test any data  "test/recipes/30-test_evp_data/evpmac_common.txt", such line 254

**Comment by slontis** [comment]
You should probably also verify that the tests fail without your fix also..

**Comment by zjd87** [comment]
ok.    later  i test  with my fix and without my fix when #undef GHASH  in code ,  please  review my CLA email ,  just now  i  mailed to legal@opensslfoundation.org. Thank you!

**Comment by richsalz** [comment]
You should test to make sure that non-asm builds still work with standard browsers.

**Comment by slontis** [comment]
@paulidale  - can you update the CLA..

**Comment by paulidale** [comment]
I don't see the ICLA anywhere and can't find it in mail email history.  Is it possible for it to be resent?

**Comment by zjd87** [comment]
> I don't see the ICLA anywhere and can't find it in mail email history. Is it possible for it to be resent?

just now,  I resent to your email (
pauli@openssl.org)

**Comment by zjd87** [comment]
just now, I have resubmitted CLA form

**Comment by zjd87** [comment]
@paulidale  please add my ICLA, thanks

**Comment by paulidale** [comment]
As @mattcaswell replied, the form needs to contain your postal address.

**Comment by zjd87** [comment]
I have resubmitted a new form which contains my posted address two days ago.

**Comment by zjd87** [comment]
> I have resubmitted a new form which contains my posted address two days ago.

@paulidale

**Comment by mattcaswell** [comment]
Close/reopen to kick CLA bot.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
ping @openssl/committers  for the second review

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
I've amended the commit message to make it more clear.

Merged to master and 1.1.1 branch. Thank you for the contribution and for the patience with the review/CLA process.

**Comment by zjd87** [comment]
get!  you are welcome

**Pull request closed without merging**
