### PR TITLE
Detect arm64-*-*bsd and enable assembly optimizations

### PR DESCRIPTION
**Pull request by allanjude**
CLA: trivial

### CODE REVIEW

**Comment by t8m** [comment]
I am not sure this is acceptable with CLA: trivial. Would you please consider signing a regular CLA? https://www.openssl.org/policies/cla.html

**Review by paulidale — APPROVED** [review]
Border line on the trivial.  A CLA is the best way forwards.
Otherwise it looks good.

**Comment by allanjude** [comment]
I've signed an ICLA

**Comment by paulidale** [comment]
CLA is good.

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master, thanks for the contribution.

**Comment by t8m** [comment]
This needs to be cherry-picked to 3.0 when merging #17085 to avoid regression.
@paulidale  do you agree?

**Comment by paulidale** [comment]
Agreed.

**Comment by t8m** [comment]
Cherry picked to 3.0 branch.

**Pull request closed without merging**
