### PR TITLE
test/evp_test.c: try fetching algorithms

### PR DESCRIPTION
**Pull request by levitte**
Instead of relying on implicit fetches, try explicit fetches when available.

### CODE REVIEW

**Comment by levitte** [comment]
This uncovers a few things that need our attention:

*SHAKE output length*

```
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE128 is fetched
        # ERROR: (int) 'expected->output_len == got_len' failed @ ../master/test/evp_test.c:434
        # [512] compared to [16]
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpdigest.txt:479: Source of above error; unexpected error DIGEST_LENGTH_MISMATCH
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE128 is fetched
        # ERROR: (int) 'expected->output_len == got_len' failed @ ../master/test/evp_test.c:434
        # [512] compared to [16]
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpdigest.txt:483: Source of above error; unexpected error DIGEST_LENGTH_MISMATCH
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE128 is fetched
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE128 is fetched
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE256 is fetched
        # ERROR: (int) 'expected->output_len == got_len' failed @ ../master/test/evp_test.c:434
        # [512] compared to [32]
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpdigest.txt:496: Source of above error; unexpected error DIGEST_LENGTH_MISMATCH
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE256 is fetched
        # ERROR: (int) 'expected->output_len == got_len' failed @ ../master/test/evp_test.c:434
        # [512] compared to [32]
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpdigest.txt:500: Source of above error; unexpected error DIGEST_LENGTH_MISMATCH
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE256 is fetched
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE256 is fetched
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE128 is fetched
        # ERROR: (int) 'expected->output_len == got_len' failed @ ../master/test/evp_test.c:434
        # [140] compared to [16]
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpdigest.txt:516: Source of above error; unexpected error DIGEST_LENGTH_MISMATCH
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE128 is fetched
        # ERROR: (int) 'expected->output_len == got_len' failed @ ../master/test/evp_test.c:434
        # [140] compared to [16]
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpdigest.txt:520: Source of above error; unexpected error DIGEST_LENGTH_MISMATCH
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE256 is fetched
        # ERROR: (int) 'expected->output_len == got_len' failed @ ../master/test/evp_test.c:434
        # [250] compared to [32]
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpdigest.txt:524: Source of above error; unexpected error DIGEST_LENGTH_MISMATCH
        # INFO:  @ ../master/test/evp_test.c:358
        # SHAKE256 is fetched
        # ERROR: (int) 'expected->output_len == got_len' failed @ ../master/test/evp_test.c:434
        # [250] compared to [32]
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpdigest.txt:528: Source of above error; unexpected error DIGEST_LENGTH_MISMATCH
```

*Misidentified algorithms*

```
        # Starting "HMAC tests (from RFC2104 and others)" tests at line 400
        # INFO:  @ ../master/test/evp_test.c:1149
        # Trying the EVP_MAC HMAC test with MD5
        # INFO:  @ ../master/test/evp_test.c:1183
        # MD5 is fetched DIGEST
        # INFO:  @ ../master/test/evp_test.c:1149
        # Trying the EVP_MAC HMAC test with MD5
        # INFO:  @ ../master/test/evp_test.c:1185
        # MD5 is fetched CIPHER
        # INFO:  @ ../master/test/evp_test.c:2778
        # ../../../master/test/recipes/30-test_evp_data/evpmac.txt:408: Source of above error; unexpected error MAC_CTRL_INVALID
        # 140007107373952:error:060D1093:digital envelope routines:EVP_MAC_ctrl:command not supported:../master/crypto/evp/mac_lib.c:123:
../../util/shlib_wrap.sh ../../test/evp_test ../../../master/test/recipes/30-test_evp_data/evpmac.txt => 139
```

**Comment by levitte** [comment]
For the misidentified algorithm, it's quite simple, we need to register the fetch method's operation_id when storing it.  I have some thoughts on that.

For the SHAKE output length, I haven't investigated yet.  I suspect that some information hasn't been transferred from the legacy methods to the provider based methods...

**Comment by levitte** [comment]
Also, I get a freeze:

```
    # Subtest: ../../test/evp_test
    1..1
        # Subtest: run_file_tests
        1..1
        # INFO:  @ ../master/test/testutil/stanza.c:21
        # Reading ../../../master/test/recipes/30-test_evp_data/evpaessiv.txt
        # INFO:  @ ../master/test/testutil/stanza.c:122
        # Starting "RFC5297 AES-SIV" tests at line 15
```

**Comment by levitte** [comment]
Manual test of the freeze case:

```
: ; OPENSSL_MODULES=providers ./util/shlib_wrap.sh gdb test/evp_test --args test/evp_test ../master/test/recipes/30-test_evp_data/evpaessiv.txt
GNU gdb (Debian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from test/evp_test...done.
(gdb) r
Starting program: /home/levitte/gitwrk/openssl.net/official/_build/test/evp_test ../master/test/recipes/30-test_evp_data/evpaessiv.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
1..1
    # Subtest: run_file_tests
    1..1
    # INFO:  @ ../master/test/testutil/stanza.c:21
    # Reading ../master/test/recipes/30-test_evp_data/evpaessiv.txt
    # INFO:  @ ../master/test/testutil/stanza.c:122
    # Starting "RFC5297 AES-SIV" tests at line 15
^C
Program received signal SIGINT, Interrupt.
futex_wait (private=0, expected=1, futex_word=0x7ffff7fcb9f0 <rand_drbg_init>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:61
61	../sysdeps/unix/sysv/linux/futex-internal.h: Filen eller katalogen finns inte.
(gdb) bt
#0  futex_wait (private=0, expected=1, 
    futex_word=0x7ffff7fcb9f0 <rand_drbg_init>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:61
#1  futex_wait_simple (private=0, expected=1, 
    futex_word=0x7ffff7fcb9f0 <rand_drbg_init>)
    at ../sysdeps/nptl/futex-internal.h:135
#2  __pthread_once_slow (once_control=0x7ffff7fcb9f0 <rand_drbg_init>, 
    init_routine=0x7ffff7e4f58a <do_rand_drbg_init_ossl_>)
    at pthread_once.c:105
#3  0x00007ffff7e19b6e in CRYPTO_THREAD_run_once (
    once=0x7ffff7fcb9f0 <rand_drbg_init>, 
    init=0x7ffff7e4f58a <do_rand_drbg_init_ossl_>)
    at ../master/crypto/threads_pthread.c:113
#4  0x00007ffff7e4f9db in RAND_DRBG_get0_public ()
    at ../master/crypto/rand/drbg_lib.c:1199
#5  0x00007ffff7e4f6f5 in drbg_bytes (out=0x5555555982e8 "", count=63)
    at ../master/crypto/rand/drbg_lib.c:1039
#6  0x00007ffff7e5100f in RAND_bytes (buf=0x5555555982e8 "", num=63)
    at ../master/crypto/rand/rand_lib.c:825
#7  0x00007ffff7e4974a in impl_cache_flush_cache (c=0x5555555a2f20, 
    state=0x7fffffffbe80) at ../master/crypto/property/property.c:400
#8  0x00007ffff7e0edbe in doall_util_fn (lh=0x5555555aa100, use_arg=1, 
    func=0x0, func_arg=0x7ffff7e4970f <impl_cache_flush_cache>, 
    arg=0x7fffffffbe80) at ../master/crypto/lhash/lhash.c:205
#9  0x00007ffff7e0ee59 in OPENSSL_LH_doall_arg (lh=0x5555555aa100, 
    func=0x7ffff7e4970f <impl_cache_flush_cache>, arg=0x7fffffffbe80)
    at ../master/crypto/lhash/lhash.c:220
#10 0x00007ffff7e4970c in lh_QUERY_doall_IMPL_CACHE_FLUSH (lh=0x5555555aa100, 
    fn=0x7ffff7e4970f <impl_cache_flush_cache>, arg=0x7fffffffbe80)
    at ../master/crypto/property/property.c:374
#11 0x00007ffff7e4982e in impl_cache_flush_one_alg (idx=6, alg=0x5555555aa0b0, 
    v=0x7fffffffbe80) at ../master/crypto/property/property.c:418
#12 0x00007ffff7e195a6 in sa_doall (sa=0x555555598340, node=0x0, 
    leaf=0x7ffff7e497e7 <impl_cache_flush_one_alg>, arg=0x7fffffffbe80)
    at ../master/crypto/sparse_array.c:98
#13 0x00007ffff7e19736 in OPENSSL_SA_doall_arg (sa=0x555555598340, 
    leaf=0x7ffff7e497e7 <impl_cache_flush_one_alg>, arg=0x7fffffffbe80)
    at ../master/crypto/sparse_array.c:152
#14 0x00007ffff7e48bf9 in ossl_sa_ALGORITHM_doall_arg (sa=0x555555598340, 
    leaf=0x7ffff7e497e7 <impl_cache_flush_one_alg>, arg=0x7fffffffbe80)
    at ../master/crypto/property/property.c:66
#15 0x00007ffff7e49868 in ossl_method_cache_flush_some (store=0x5555555982c0)
    at ../master/crypto/property/property.c:428
#16 0x00007ffff7e499c4 in ossl_method_store_cache_set (store=0x5555555982c0, 
    nid=2, prop_query=0x7ffff7f18dd7 "", method=0x555555598760)
    at ../master/crypto/property/property.c:474
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x00007ffff7df9095 in evp_generic_fetch (libctx=0x0, operation_id=2, 
    name=0x7ffff7f205b1 "AES-256-ECB", properties=0x7ffff7f18dd7 "", 
    new_method=0x7ffff7df8737 <evp_cipher_from_dispatch>, 
    upref_method=0x7ffff7df8b75 <evp_cipher_upref>, 
    free_method=0x7ffff7df8b8f <evp_cipher_free>)
    at ../master/crypto/evp/evp_fetch.c:170
#18 0x00007ffff7df8bf1 in EVP_CIPHER_fetch (ctx=0x0, 
    algorithm=0x7ffff7f205b1 "AES-256-ECB", properties=0x7ffff7f18dd7 "")
    at ../master/crypto/evp/evp_enc.c:1196
#19 0x00007ffff7df65b5 in EVP_CipherInit_ex (ctx=0x5555555a0d50, 
    cipher=0x7ffff7f9a5a0 <aesni_256_ecb>, impl=0x0, 
    key=0x7ffff7f2b060 <df_key> "", iv=0x0, enc=1)
    at ../master/crypto/evp/evp_enc.c:206
#20 0x00007ffff7e4c9b4 in drbg_ctr_init (drbg=0x5555555a87c0)
    at ../master/crypto/rand/drbg_ctr.c:415
#21 0x00007ffff7e4dde0 in RAND_DRBG_set (drbg=0x5555555a87c0, type=906, 
    flags=4) at ../master/crypto/rand/drbg_lib.c:176
#22 0x00007ffff7e4e148 in rand_drbg_new (secure=1, type=906, flags=4, 
    parent=0x0) at ../master/crypto/rand/drbg_lib.c:283
#23 0x00007ffff7e4e218 in RAND_DRBG_secure_new (type=906, flags=4, parent=0x0)
    at ../master/crypto/rand/drbg_lib.c:315
#24 0x00007ffff7e4f511 in drbg_setup (parent=0x0, drbg_type=0)
    at ../master/crypto/rand/drbg_lib.c:950
#25 0x00007ffff7e4f5fa in do_rand_drbg_init ()
    at ../master/crypto/rand/drbg_lib.c:997
#26 0x00007ffff7e4f593 in do_rand_drbg_init_ossl_ ()
    at ../master/crypto/rand/drbg_lib.c:982
#27 0x00007ffff7bde997 in __pthread_once_slow (
    once_control=0x7ffff7fcb9f0 <rand_drbg_init>, 
    init_routine=0x7ffff7e4f58a <do_rand_drbg_init_ossl_>)
    at pthread_once.c:116
#28 0x00007ffff7e19b6e in CRYPTO_THREAD_run_once (
    once=0x7ffff7fcb9f0 <rand_drbg_init>, 
    init=0x7ffff7e4f58a <do_rand_drbg_init_ossl_>)
    at ../master/crypto/threads_pthread.c:113
#29 0x00007ffff7e4f9db in RAND_DRBG_get0_public ()
    at ../master/crypto/rand/drbg_lib.c:1199
#30 0x00007ffff7e4f6f5 in drbg_bytes (out=0x5555555982e8 "", count=63)
    at ../master/crypto/rand/drbg_lib.c:1039
#31 0x00007ffff7e5100f in RAND_bytes (buf=0x5555555982e8 "", num=63)
    at ../master/crypto/rand/rand_lib.c:825
#32 0x00007ffff7e4974a in impl_cache_flush_cache (c=0x5555555a2f20, 
    state=0x7fffffffc500) at ../master/crypto/property/property.c:400
#33 0x00007ffff7e0edbe in doall_util_fn (lh=0x5555555aa100, use_arg=1, 
    func=0x0, func_arg=0x7ffff7e4970f <impl_cache_flush_cache>, 
    arg=0x7fffffffc500) at ../master/crypto/lhash/lhash.c:205
#34 0x00007ffff7e0ee59 in OPENSSL_LH_doall_arg (lh=0x5555555aa100, 
    func=0x7ffff7e4970f <impl_cache_flush_cache>, arg=0x7fffffffc500)
    at ../master/crypto/lhash/lhash.c:220
#35 0x00007ffff7e4970c in lh_QUERY_doall_IMPL_CACHE_FLUSH (lh=0x5555555aa100, 
    fn=0x7ffff7e4970f <impl_cache_flush_cache>, arg=0x7fffffffc500)
    at ../master/crypto/property/property.c:374
#36 0x00007ffff7e4982e in impl_cache_flush_one_alg (idx=6, alg=0x5555555aa0b0, 
    v=0x7fffffffc500) at ../master/crypto/property/property.c:418
#37 0x00007ffff7e195a6 in sa_doall (sa=0x555555598340, node=0x0, 
    leaf=0x7ffff7e497e7 <impl_cache_flush_one_alg>, arg=0x7fffffffc500)
    at ../master/crypto/sparse_array.c:98
#38 0x00007ffff7e19736 in OPENSSL_SA_doall_arg (sa=0x555555598340, 
    leaf=0x7ffff7e497e7 <impl_cache_flush_one_alg>, arg=0x7fffffffc500)
    at ../master/crypto/sparse_array.c:152
#39 0x00007ffff7e48bf9 in ossl_sa_ALGORITHM_doall_arg (sa=0x555555598340, 
    leaf=0x7ffff7e497e7 <impl_cache_flush_one_alg>, arg=0x7fffffffc500)
    at ../master/crypto/property/property.c:66
#40 0x00007ffff7e49868 in ossl_method_cache_flush_some (store=0x5555555982c0)
    at ../master/crypto/property/property.c:428
#41 0x00007ffff7e499c4 in ossl_method_store_cache_set (store=0x5555555982c0, 
    nid=21, prop_query=0x7ffff7f18dd7 "", method=0x5555555af1c0)
    at ../master/crypto/property/property.c:474
#42 0x00007ffff7df9095 in evp_generic_fetch (libctx=0x0, operation_id=2, 
    name=0x7ffff7f22dee "AES-192-CTR", properties=0x7ffff7f18dd7 "", 
    new_method=0x7ffff7df8737 <evp_cipher_from_dispatch>, 
    upref_method=0x7ffff7df8b75 <evp_cipher_upref>, 
    free_method=0x7ffff7df8b8f <evp_cipher_free>)
    at ../master/crypto/evp/evp_fetch.c:170
#43 0x00007ffff7df8bf1 in EVP_CIPHER_fetch (ctx=0x0, 
    algorithm=0x7ffff7f22dee "AES-192-CTR", properties=0x7ffff7f18dd7 "")
    at ../master/crypto/evp/evp_enc.c:1196
#44 0x00007ffff7df65b5 in EVP_CipherInit_ex (ctx=0x5555555a9d90, 
    cipher=0x7ffff7f9a220 <aesni_192_ctr>, impl=0x0, 
    key=0x5555555a2bb8 "\370\371\372\373\374\375\376\377\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361", <incomplete sequence \360>, iv=0x0, 
    enc=1) at ../master/crypto/evp/evp_enc.c:206
#45 0x00007ffff7df6ed1 in EVP_EncryptInit_ex (ctx=0x5555555a9d90, 
    cipher=0x7ffff7f9a220 <aesni_192_ctr>, impl=0x0, 
    key=0x5555555a2bb8 "\370\371\372\373\374\375\376\377\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361", <incomplete sequence \360>, iv=0x0)
    at ../master/crypto/evp/evp_enc.c:445
#46 0x00007ffff7e270ea in CRYPTO_siv128_init (ctx=0x5555555a3c40, 
    key=0x5555555a2ba0 "\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361\360\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361", <incomplete sequence \360>, klen=24, cbc=0x7ffff7f997a0 <aesni_192_cbc>, 
    ctr=0x7ffff7f9a220 <aesni_192_ctr>) at ../master/crypto/modes/siv128.c:178
#47 0x00007ffff7de53fd in aes_siv_init_key (ctx=0x5555555aa2f0, 
    key=0x5555555a2ba0 "\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361\360\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361", <incomplete sequence \360>, iv=0x0, enc=1) at ../master/crypto/evp/e_aes.c:4401
#48 0x00007ffff7df6d06 in EVP_CipherInit_ex (ctx=0x5555555aa2f0, cipher=0x0, 
    impl=0x0, 
    key=0x5555555a2ba0 "\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361\360\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361", <incomplete sequence \360>, iv=0x0, enc=1) at ../master/crypto/evp/evp_enc.c:401
#49 0x000055555555b4b4 in cipher_test_enc (t=0x55555557c510, enc=1, 
    out_misalign=0, inp_misalign=18446744073709551615, frag=0)
    at ../master/test/evp_test.c:674
#50 0x000055555555bce7 in cipher_test_run (t=0x55555557c510)
    at ../master/test/evp_test.c:828
#51 0x00005555555608da in run_test (t=0x55555557c510)
    at ../master/test/evp_test.c:2840
#52 0x0000555555561421 in run_file_tests (i=0)
    at ../master/test/evp_test.c:3103
#53 0x0000555555563e68 in run_tests (
    test_prog_name=0x7fffffffdea6 "/home/levitte/gitwrk/openssl.net/official/_bu--Type <RET> for more, q to quit, c to continue without paging--
ild/test/evp_test") at ../master/test/testutil/driver.c:386
#54 0x000055555556414d in main (argc=2, argv=0x7fffffffdb58)
    at ../master/test/testutil/main.c:30
```

**Comment by levitte** [comment]
@paulidale, can I ask you to look at the freeze case?  It might be that using RAND for cache flushing might not be the best idea, considering the uses.

**Comment by mattcaswell** [comment]
@levitte - Try applying #9039 and see if the freeze goes away. It looks like it is recursively attempting to initialise the DRBG code from within an initialisation to the DRBG code.

**Comment by levitte** [comment]
> @levitte - Try applying #9039 and see if the freeze goes away. It looks like it is recursively attempting to initialise the DRBG code from within an initialisation to the DRBG code.

Ah, that may solve that issue, yeah

**Comment by levitte** [comment]
Misidentified algorithms fixed with #9109

**Comment by levitte** [comment]
I tried a merge with #9039, and it seems to have fixes, er, *some*thing, but not all.  Looking at the positive, the backtrace isn't as long winded :wink:

```
: ; OPENSSL_MODULES=providers ./util/shlib_wrap.sh gdb test/evp_test --args test/evp_test ../master/test/recipes/30-test_evp_data/evpaessiv.txt
GNU gdb (Debian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from test/evp_test...done.
(gdb) r
Starting program: /home/levitte/gitwrk/openssl.net/official/_build/test/evp_test ../master/test/recipes/30-test_evp_data/evpaessiv.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
1..1
    # Subtest: run_file_tests
    1..1
    # INFO:  @ ../master/test/testutil/stanza.c:21
    # Reading ../master/test/recipes/30-test_evp_data/evpaessiv.txt
    # INFO:  @ ../master/test/testutil/stanza.c:122
    # Starting "RFC5297 AES-SIV" tests at line 15
^C
Program received signal SIGINT, Interrupt.
futex_abstimed_wait (private=0, abstime=0x0, expected=2, 
    futex_word=0x555555598378)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:172
172	../sysdeps/unix/sysv/linux/futex-internal.h: Filen eller katalogen finns inte.
(gdb) bt
#0  futex_abstimed_wait (private=0, abstime=0x0, expected=2, 
    futex_word=0x555555598378)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:172
#1  __pthread_rwlock_wrlock_full (abstime=0x0, rwlock=0x555555598370)
    at pthread_rwlock_common.c:803
#2  __GI___pthread_rwlock_wrlock (rwlock=0x555555598370)
    at pthread_rwlock_wrlock.c:27
#3  0x00007ffff7e19abf in CRYPTO_THREAD_write_lock (lock=0x555555598370)
    at ../master/crypto/threads_pthread.c:73
#4  0x00007ffff7e48c5d in ossl_property_write_lock (p=0x5555555982c0)
    at ../master/crypto/property/property.c:78
#5  0x00007ffff7e4996d in ossl_method_store_cache_set (store=0x5555555982c0, 
    nid=6, prop_query=0x7ffff7f18dd7 "", method=0x5555555a9f10)
    at ../master/crypto/property/property.c:472
#6  0x00007ffff7df9095 in evp_generic_fetch (libctx=0x0, operation_id=2, 
    name=0x7ffff7f20569 "AES-192-CBC", properties=0x7ffff7f18dd7 "", 
    new_method=0x7ffff7df8737 <evp_cipher_from_dispatch>, 
    upref_method=0x7ffff7df8b75 <evp_cipher_upref>, 
    free_method=0x7ffff7df8b8f <evp_cipher_free>)
    at ../master/crypto/evp/evp_fetch.c:170
#7  0x00007ffff7df8bf1 in EVP_CIPHER_fetch (ctx=0x0, 
    algorithm=0x7ffff7f20569 "AES-192-CBC", properties=0x7ffff7f18dd7 "")
    at ../master/crypto/evp/evp_enc.c:1196
#8  0x00007ffff7df65b5 in EVP_CipherInit_ex (ctx=0x5555555a9d90, 
    cipher=0x7ffff7f99760 <aesni_192_cbc>, impl=0x0, key=0x0, iv=0x0, enc=1)
    at ../master/crypto/evp/evp_enc.c:206
#9  0x00007ffff7df6ed1 in EVP_EncryptInit_ex (ctx=0x5555555a9d90, 
    cipher=0x7ffff7f99760 <aesni_192_cbc>, impl=0x0, key=0x0, iv=0x0)
    at ../master/crypto/evp/evp_enc.c:445
#10 0x00007ffff7d44ae4 in CMAC_Init (ctx=0x5555555a38a0, key=0x5555555a2ba0, 
    keylen=24, cipher=0x7ffff7f99760 <aesni_192_cbc>, impl=0x0)
    at ../master/crypto/cmac/cmac.c:119
#11 0x00007ffff7d44415 in cmac_ctrl (cctx=0x5555556e7490, cmd=1, 
    args=0x7fffffffc6a0) at ../master/crypto/cmac/cm_meth.c:102
#12 0x00007ffff7dfce6b in EVP_MAC_vctrl (ctx=0x5555556f97d0, cmd=1, 
    args=0x7fffffffc6a0) at ../master/crypto/evp/mac_lib.c:144
#13 0x00007ffff7dfcdd0 in EVP_MAC_ctrl (ctx=0x5555556f97d0, cmd=1)
    at ../master/crypto/evp/mac_lib.c:119
#14 0x00007ffff7e27073 in CRYPTO_siv128_init (ctx=0x5555555a3c40, 
    key=0x5555555a2ba0 "\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361\360\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361", <incomplete sequence \360>, klen=24, cbc=0x7ffff7f99760 <aesni_192_cbc>, 
    ctr=0x7ffff7f9a1e0 <aesni_192_ctr>) at ../master/crypto/modes/siv128.c:177
#15 0x00007ffff7de53fd in aes_siv_init_key (ctx=0x5555555aa2f0, 
    key=0x5555555a2ba0 "\377\376\375\374\373\372\371\370\367\366\365\364\363\362--Type <RET> for more, q to quit, c to continue without paging--
\361\360\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361", <incomplete sequence \360>, iv=0x0, enc=0) at ../master/crypto/evp/e_aes.c:4401
#16 0x00007ffff7df6d06 in EVP_CipherInit_ex (ctx=0x5555555aa2f0, cipher=0x0, 
    impl=0x0, 
    key=0x5555555a2ba0 "\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361\360\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377\377\376\375\374\373\372\371\370\367\366\365\364\363\362\361", <incomplete sequence \360>, iv=0x0, enc=0) at ../master/crypto/evp/evp_enc.c:401
#17 0x000055555555b4b4 in cipher_test_enc (t=0x55555557c510, enc=0, 
    out_misalign=0, inp_misalign=18446744073709551615, frag=0)
    at ../master/test/evp_test.c:674
#18 0x000055555555bd35 in cipher_test_run (t=0x55555557c510)
    at ../master/test/evp_test.c:837
#19 0x00005555555608da in run_test (t=0x55555557c510)
    at ../master/test/evp_test.c:2840
#20 0x0000555555561421 in run_file_tests (i=0)
    at ../master/test/evp_test.c:3103
#21 0x0000555555563e68 in run_tests (
    test_prog_name=0x7fffffffdea6 "/home/levitte/gitwrk/openssl.net/official/_build/test/evp_test") at ../master/test/testutil/driver.c:386
#22 0x000055555556414d in main (argc=2, argv=0x7fffffffdb58)
    at ../master/test/testutil/main.c:30
(gdb)
```

**Comment by levitte** [comment]
The SHAKE128 output length issue is cause by the lack of flags in provider digests, as I already commented here: https://github.com/openssl/openssl/pull/8763#issuecomment-499080174

I'm already working on a fix for it.

**Comment by levitte** [comment]
Oh, this got auto-closed...  and for some reason, I can't reopen it.

**Comment by slontis** [comment]
> Oh, this got auto-closed... and for some reason, I can't reopen it.

Because you said 'partially fixes' in the commit message of #9109 :)
I dont know if you would have to reopen the parent one to unlock it??

**Comment by levitte** [comment]
The thing is that the "Reopen" button remains gray...  Ah well, I recreated it in #9121, let's continue there

**Pull request closed without merging**
