### PR TITLE
Refactor the provider side DER constants and writers

### PR DESCRIPTION
**Pull request by levitte**
This splits up all the providers/common/der/*.c.in so the generated
portion is on its own and all related DER writing routines are in
their own files.  This also ensures that the DIGEST consstants aren't
reproduced in several files (resulting in symbol clashes).

Finally, the production of OID macros is moved to the generated header
files, allowing other similar macros, or DER constant arrays, to be
built on top of them.

### CODE REVIEW

**Comment by levitte** [comment]
Merged

a30027b680c4ccf69f0600b3a5406821b2d7fe0b Refactor the provider side DER constants and writers

**Comment by zorrorffm** [comment]
With this change,  compiling error will occur on arm machine like
`providers/common/der/der_dsa_sig.c: In function 'DER_w_algorithmIdentifier_DSA_with_MD':
providers/common/der/der_dsa_sig.c:16:23: error: 'der_oid_id_dsa_with_sha1' undeclared (first use in this function); did you mean 'OBJ_dsa_with_sha2'?
         precompiled = der_oid_id_dsa_with_##name;         `

**Comment by zorrorffm** [comment]
> 
> 
> With this change, compiling error will occur on arm machine like
> `providers/common/der/der_dsa_sig.c: In function 'DER_w_algorithmIdentifier_DSA_with_MD': providers/common/der/der_dsa_sig.c:16:23: error: 'der_oid_id_dsa_with_sha1' undeclared (first use in this function); did you mean 'OBJ_dsa_with_sha2'? precompiled = der_oid_id_dsa_with_##name; `

"make -jxx" will make this error happen while "make" won't.

**Comment by levitte** [comment]
Hmmmm...  sounds like i missed a dependency somewhere

**Comment by zorrorffm** [comment]
Yeah, we can fix it with below changes
`diff --git a/providers/common/der/build.info b/providers/common/der/build.info
index 43fe9038fe..56e4d39061 100644
--- a/providers/common/der/build.info
+++ b/providers/common/der/build.info
@@ -10,21 +10,21 @@ SOURCE[../../libnonfips.a]=$FIPSABLE
 GENERATE[der_rsa_gen.c]=der_rsa_gen.c.in
 DEPEND[der_rsa_gen.c]=oids_to_c.pm

-DEPEND[der_rsa_gen.o]=../include/prov/der_rsa.h ../include/prov/der_digests.h
+DEPEND[der_rsa_gen.o der_rsa_key.o der_rsa_sig.o]=../include/prov/der_rsa.h ../include/prov/der_digests.h
 GENERATE[../include/prov/der_rsa.h]=der_rsa.h.in
 DEPEND[../include/prov/der_rsa.h]=oids_to_c.pm

 GENERATE[der_dsa_gen.c]=der_dsa_gen.c.in
 DEPEND[der_dsa_gen.c]=oids_to_c.pm

-DEPEND[der_dsa_gen.o]=../include/prov/der_dsa.h
+DEPEND[der_dsa_gen.o der_dsa_key.o der_dsa_sig.o]=../include/prov/der_dsa.h
 GENERATE[../include/prov/der_dsa.h]=der_dsa.h.in
 DEPEND[../include/prov/der_dsa.h]=oids_to_c.pm

 GENERATE[der_ec_gen.c]=der_ec_gen.c.in
 DEPEND[der_ec_gen.c]=oids_to_c.pm

-DEPEND[der_ec_gen.o]=../include/prov/der_ec.h
+DEPEND[der_ec_gen.o der_ec_key.o der_ec_sig.o]=../include/prov/der_ec.h
 GENERATE[../include/prov/der_ec.h]=der_ec.h.in
 DEPEND[../include/prov/der_ec.h]=oids_to_c.pm
`

**Comment by zorrorffm** [comment]
I submitted one CL fixing it, https://github.com/openssl/openssl/pull/11893. Please help review. Thanks

**Comment by levitte** [comment]
Oh, I totally missed that!  I just submitted #11906...

**Pull request closed without merging**
