### PR TITLE
Remove OPENSSL_SSL_TRACE_CRYPTO and support TLSv1.3 content types in SSL_trace

### PR DESCRIPTION
**Pull request by mattcaswell**
The "enable-ssl-trace" option  is a useful and documented Configure option. There is an additional macro used in the code OPENSSL_SSL_TRACE_CRYPTO which you cannot turn on directly via Configure (you have to use "-DOPENSSL_SSL_TRACE_CRYPTO") which causes addition items to be traced via SSL_trace(). However defining that macro fails to compile in master or in any 1.1.0 version. 

This PR removes this unused option. It also adds support for TLSv1.3 inner content types. Without this all TLSv1.3 records appear as "application data", even though in reality the inner content type may be different.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by richsalz** [comment]
should you backport the fix to remove the broken compile option to 1.1.0?

**Comment by kaduk** [comment]
Am I reading this correctly that for an encrypted TLS 1.3 record the message callback will get both the SSL3_RT_HEADER and SSL3_RT_INNER_CONTENT_TYPE calls?  How are applications expected to link the two events to a single record?  (Both those aforementioned calls can occur in a loop if we read up to max_recs records at a time, so even the naive "attach SSL3_RT_INNER_CONTENT_TYPE to the immediately previous SSL3_RT_HEADER" would not work.)
There's also several potential error paths between the two calls, so that one could get SSL3_RT_HEADER but not the other, though I expect that applications' message callbacks should expect to have to deal with such cases anyway.

I haven't thought hard enough to form an opinion whether it would be easier for the application to have a single event with the header and encrypted content type information combined together; given how far apart the two msg_callback calls are now in ssl3_get_record(), it seems like it would probably be annoying to implement such a thing with suppression of the SSL3_RT_HEADER event when applicable.

**Comment by mattcaswell** [comment]
> should you backport the fix to remove the broken compile option to 1.1.0?

#3413

**Comment by mattcaswell** [comment]
> Am I reading this correctly that for an encrypted TLS 1.3 record the message callback will get both the SSL3_RT_HEADER and SSL3_RT_INNER_CONTENT_TYPE calls?

Yes.

> How are applications expected to link the two events to a single record?

This problem already exists for applications using this mechanism. The callback gets called at various points each time it receives messages. To be useful I imagine a lot of applications will need to link those calls somehow. They can do so using the SSL object as a key. All we're doing here is extending an existing pattern with one more type of event that the callback gets invoked for.

> Both those aforementioned calls can occur in a loop if we read up to max_recs records at a time, so even the naive "attach SSL3_RT_INNER_CONTENT_TYPE to the immediately previous SSL3_RT_HEADER" would not work.

Well technically that isn't a problem at the moment because max_recs will always be 1 for TLSv1.3. You only get a larger value if you have switched on pipelining (which isn't supported in TLSv1.3 at the moment). I suppose it could be an issue in the future though - but in that case an application explicitly has to ask for pipelining and should therefore be pipelining aware. The number of SSL3_RT_HEADER calls should match the number of SSL3_RT_INNER_CONTENT_TYPE calls in that case. I don't think we should be too concerned about this corner case.

> There's also several potential error paths between the two calls, so that one could get SSL3_RT_HEADER but not the other, though I expect that applications' message callbacks should expect to have to deal with such cases anyway.

Yes, and the documentation pretty much says that.

> I haven't thought hard enough to form an opinion whether it would be easier for the application to have a single event with the header and encrypted content type information combined together; given how far apart the two msg_callback calls are now in ssl3_get_record(), it seems like it would probably be annoying to implement such a thing with suppression of the SSL3_RT_HEADER event when applicable.

I went through this thought process when I designed this solution. Combining the calls is actually non-trivial anyway. The SSL3_RT_HEADER call sends through *just* the record header. So you either have to send through a synthetic header where the "app data" content type is replaced with the inner content type, or you have to send through a synthetic header where the inner content type is just appended onto the end of the "real" header. Both of these seem quite nasty to me, so I though that this approach was the best way forward.

**Pull request closed without merging**
