### PR TITLE
Drbg in ssl

### PR DESCRIPTION
**Pull request by richsalz**
This depends on #4019 
    Add a DRBG to each SSL object

    Give each SSL object it's own DRBG, chained to the parent global
    DRBG which is used only as a source of randomness into the per-SSL
    DRBG.  This is used for all session, ticket, and pre-master secret keys.
    It is NOT used for ECDH key generation which use only the global
    DRBG.

### CODE REVIEW

**Comment by kroeckx** [comment]
I would prefer a solution that wasn't specific to DRBG, but that it has it's own instance of RNG.

**Comment by richsalz** [comment]
Why?

**Comment by kroeckx** [comment]
I'm not sure why want to restrict things to the DRBG, any RNG should work.

**Comment by mspncp** [comment]
Kurt, one important feature of the DRBG api is that it supports having multiple instances. The good old RAND_METHOD api has no such concept. So how do you want to support chaining of RNGs based on the RAND_METHOD api?

Nevertheless I believe that it is possible to implement a chacha20 based RNG as an alternative DRBG algorithm, say RAND_DRBG_CHACHA20, as I tried to explain in [#4046](https://github.com/openssl/openssl/pull/4046#issuecomment-318813793).

**Comment by kroeckx** [comment]
My understanding is that we're stuck with the current RAND method APIs because they're still in the public headers and so can't extend them. That shouldn't stop us from using/making something else that's generic and not specific to 1 implementation.

**Comment by richsalz** [comment]
As has been previously mentioned, there are other reasons.  It has a defined model model for lifecycle, chaining, entropy, personalization, and so on.  It is a standard model, well-understood, reviewed, and proven.  You think a single global RAND API is better?

**Comment by kroeckx** [comment]
It might be that is has a proper model, but that's not what I see in the implementation. It's still specific to 1 implementation.

**Comment by mspncp** [comment]
If you mean the fact that there is no public API to plug in your own implementation, well it hasn't and this would probably not be a good idea.

But internally, there could be multiple different implementations to generate the random bit, as you can see in the FIPS DRBG:  There are three different algorithms ([hash,hmac,ctr](https://github.com/openssl/openssl/blob/OpenSSL-fips-2_0-stable/fips/rand/fips_rand_lcl.h#L62))  (hash,hmac,ctr) embedded [as a union](https://github.com/openssl/openssl/blob/OpenSSL-fips-2_0-stable/fips/rand/fips_rand_lcl.h#L179) inside the FIPS DRBG_CONTEXT.

**Comment by levitte** [comment]
But hole on, @kroeckx...  this change only uses DRBG functions *if DRBG is the current default method*.  If not, it does like before.  I don't see the harm.

**Comment by richsalz** [comment]
DRBG is a framework for multiple types of CSPRNG.  When bringing the code over from the FIPS work, I removed the hash and HMAC mechanisms, leaving just AES-CTR.  That's what boring is using (not just for their fips work, it seems) and what Amazon uses.  When doing that, I removed some of the indirection and callbacks and just inlined things like the calls to ctr_instantiate and so on.

If/when we want to add other CSPRNG's (and perhaps #4046 will become one of them), then we will need to put-back some of the indirections and turn the CTR context back into a union. I think the comment about it being related to just one implementation is about this. Matthias is agreeing with me, but maybe we're both wrong and misunderstand Kurt. :)

Richard's right, the libssl code only calls chained DRBG CSPRNG's if the default RAND method is used.  I did that so that fuzzing (which installs a fake deterministic RAND method) works. It could handle other RAND methods, of course. But we lose the ability to chain them, and fall back to a single global CSPRNG, or one that locks and mixes in state. I think that's a step backwards, and arguably a good-sized step in the wrong direction.

Only the last commit in this PR is new; the others are from #4019. I hope that both of these will get a quick review as OpenSSL's RAND, now truly a CSPRNG, is long overdue for revision.

**Comment by levitte** [comment]
> I did that so that fuzzing (which installs a fake deterministic RAND method) works.

Well, it's not just that...  if you didn't do thise, then *everyone* who created their own RAND method (for example with an engine) would be royally screwed, and very suddenly so.  So, errr, wise choise, even if you might not realise how wise it was.

**Comment by richsalz** [comment]
Not quite; any RAND method that implements RAND_add will work (the fuzzing RAND doesn't).

**Comment by levitte** [comment]
Yeah, but their implementation of RAND_bytes() et al would be ignored.  There are random devices with implemented ENGINEs that do this (I've been part of implementing one)...

**Comment by richsalz** [comment]
Ah right, good point; thanks.

**Comment by snhenson** [comment]
I agree with some of the comments here. There are applications that implement their own RAND_METHOD and replacing that with a hard coded PRNG might have performance and even local policy implications (e.g. if local policy requires a specific PRNG is used).

In the longer term we definitely need a mechanism to redirect libssl PRNG to an ENGINE: when we restore FIPS compliance we are **required** to redirect PRNG operations to a validated implementation. That wont happen in time for 1.1.1 though.

**Comment by richsalz** [comment]
If an application uses its own RAND_METHOD, things work exactly as expected; none of this stuff is used.

**Comment by richsalz** [comment]
last commit re-applied to master, thanks!

**Pull request closed without merging**
