### PR TITLE
ssl: SSL_MODE_ASYNC_KEY_EX

### PR DESCRIPTION
**Pull request by indutny**
Support async RSA exchange by providing new SSL_want_rsa_sign(),
SSL_want_rsa_decrypt() API methods.

After getting such want values - SSL_supply_key_ex_data() should be
invoked to continue handshake with a sign/decrypt data that was received
from the remote server.

This time with a test. Supersedes #162.

### CODE REVIEW

**Comment by threed-3d** [comment]
Great feature. I absolutely need this feature for the product I am working. Is it planned to integrate it in a future release?

**Comment by richsalz** [comment]
We are looking at a number of methods for doing this kind of thing, and something is very likely to be part of a release within a year.

**Comment by jfigus** [comment]
+1

**Comment by MichaelLuken** [comment]
+1 - many uses, looking forward to support in OpenSSL

**Comment by ghedo** [comment]
I think this is superseded by #433 now.

**Comment by mattcaswell** [comment]
Yes, #433 would be the preferred way to do this now. Closing.

**Pull request closed without merging**
