### PR TITLE
Added check for __QNX__ define when using in_pktinfo.ipi_spec_dst

### PR DESCRIPTION
**Pull request by klausholstjacobsen**
Added check for __QNX__ define when using in_pktinfo.ipi_spec_dst

### CODE REVIEW

**Comment by nhorman** [comment]
Can you please sign a cla so that we can review and potentially accept this issue

**Comment by tom-cosgrove-arm** [comment]
Why is the bot reporting an incorrect status? This PR needs a CLA, not OTC action - although TBH to me it looks like it could be accepted as trivial - it's extending a `#if` presumably based on a compiler error

**Comment by nhorman** [comment]
I think the bot response is just an artifact of which label it checks first.  As for trivial, I'm honestly not sure

**Comment by tom-cosgrove-arm** [comment]
> As for trivial, I'm honestly not sure

In which case @klausholstjacobsen can you sign and submit a CLA so we can review and hopefully accept this contribution?

**Comment by klausholstjacobsen** [comment]
Yes, will do!

**Comment by t8m** [comment]
Was the CLA submitted? IMO this would be clearly OK with CLA: trivial as well.

**Review by t8m — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Comment by hlandau** [comment]
@t8m Agree trivial.

**Comment by t8m** [comment]
Merged to the master, 3.4, 3.3 and 3.2 branches. Thank you for your contribution.

**Pull request closed without merging**
