### PR TITLE
Fix OSSL_PARAM_allocate_from_text() to do sign extension

### PR DESCRIPTION
**Pull request by levitte**
OSSL_PARAM_allocate_from_text() doesn't do sign extension when it should.
See #17103.

### CODE REVIEW

**Comment by Angelika123456** [comment]
> OSSL_PARAM_allocate_from_text() doesn't do sign extension when it should. See #17103.

**Review by paulidale — APPROVED** [review]
I like.

**Comment by paulidale** [comment]
This looks like a feature, so not for 3.0.  Anyone think differently?

**Comment by paulidale** [comment]
OTC question: **bug fix or feature?**

**Comment by mattcaswell** [comment]
OTC:Bug fix

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Merged

master:
b556713a6f2884eadc7f56428bc82a844e9a49e0 Test the performance of OSSL_PARAM_allocate_from_text with arbitrary size ints
8585b5bc62d0bf394ca6adf24f8590e9b9b18402 Have OSSL_PARAM_allocate_from_text() raise error on unexpected neg number
946bc0e3ec19ca019fcfa95f93c37f34e12fe0bd Allow sign extension in OSSL_PARAM_allocate_from_text()

3.0:
b4175902ffa8cd9c971f650f03c0f48eb418a0ad Test the performance of OSSL_PARAM_allocate_from_text with arbitrary size ints
de54b77ec35c47d4b8da40eeeecc84ab4ea17058 Have OSSL_PARAM_allocate_from_text() raise error on unexpected neg number
f838730d15b6942d3fc401f73715c8789d05b385 Allow sign extension in OSSL_PARAM_allocate_from_text()

**Pull request closed without merging**
