### PR TITLE
Add a comment to this x.509 fuzzer

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by kroeckx** [comment]
The X509_print() does the same thing internally.  Among other things, it does:

    pkey = X509_get0_pubkey(x);

It also actually prints the public key and has the same output as the x509 app -text output.

**Comment by alex** [comment]
@kroeckx Ah, clever; would you accept a PR with a comment mentioning that the `X509_print` will load public key and extensions?

**Comment by kroeckx** [comment]
Sure

**Comment by alex** [comment]
Done

**Comment by kroeckx** [comment]
+1

**Comment by ekasper** [comment]
+1

**Pull request closed without merging**
