### PR TITLE
PROV: check for memory allocation failure in digest _dupctx.

### LINKED ISSUE #10481: Null-pointer-dereference at digestcommon.h
Hello, I have found an out-of-memory bug with my fuzzing tool **FIFUZZ**. The bug information is following.

**Describe the bug**
The **malloc()** in the call stack shown below may fail:

    #0 Call malloc() in CRYPTO_malloc(), at mem.c: 222
    #1 Call CRYPTO_malloc() in sha256_dupctx(), at digestcommon.h: 51
    #2 Call sha256_dupctx() in EVP_MD_CTX_copy_ex(), at digest.c: 4444
    #3 Call EVP_MD_CTX_copy_ex() in HMAC_CTX_copy(), at hmac.c: 200
    #4 Call HMAC_CTX_copy() in pbkdf2_derive(), at pbkdf2.c: 318
    #5 Call pbkdf2_derive() in kdf_pbkdf2_derive(), at pbkdf2.c: 142
    #6 Call kdf_pbkdf2_derive() in EVP_KDF_derive(), at kdf_lib.c: 138
    #7 Call EVP_KDF_derive() in PKCS5_PBKDF2_HMAC(), at p5_crpt2.c: 58
    #8 Call PKCS5_PBKDF2_HMAC() in enc_main(), at enc.c: 484
    #9 Call enc_main() in do_cmd(), at openssl.c:481
    #10 Call do_cmd() in main(), at openssl.c: 294

If the **malloc()** in this call stack fails, **CRYPTO_malloc()**  in **sha256_dupctx()** will return NULL, so **ret** in **sha256_dupctx()** is NULL at digestcommon.h: 51. And then *ret = *in causes a null-pointer-dereference at digestcommon.h: 52.

The Stack Traceback when the bug occurs:

    (gdb) backtrace
    #0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:340
    #1  0x00007ffff76f2cb4 in sha256_dupctx (ctx=0x848170) at providers/implementations/digests/sha2_prov.c:61
    #2  0x00007ffff73e299b in EVP_MD_CTX_copy_ex (out=0x7b6f80, in=0x876750) at crypto/evp/digest.c:444
    #3  0x00007ffff74641bd in HMAC_CTX_copy (dctx=0x8077e0, sctx=0x808ad0) at crypto/hmac/hmac.c:200
    #4  0x00007ffff76fe7e3 in pbkdf2_derive (pass=0x81f220 "testtesttesttrhash", passlen=12, salt=0x80a680 "\262\"\224\324<I\320\377f2_init", saltlen=8, iter=10000, digest=0x7f4880, key=0x7fd6c0 "\344\341\023T\221\202g\235\333_y\203\264u\252\067t)\204V\254\351Mt\265\064\342\323A\313\031\255", keylen=32      , lower_bound_checks=0) at providers/implementations/kdfs/pbkdf2.c:318
    #5  0x00007ffff76fd26b in kdf_pbkdf2_derive (vctx=0x88cc20, key=0x7fd6c0 "\344\341\023T\221\202g\235\333_y\203\264u\252\067t)\204V\254\351Mt\265\064\342\323A\313\031\255", keylen=32) at providers/implementations/kdfs/pbkdf2.c:142
    #6  0x00007ffff743566e in EVP_KDF_derive (ctx=0x7b7870, key=0x7fd6c0 "\344\341\023T\221\202g\235\333_y\203\264u\252\067t)\204V\254\351Mt\265\064\342\323A\313\031\255", keylen=32) at crypto/evp/kdf_lib.c:138
    #7  0x00007ffff7442a68 in PKCS5_PBKDF2_HMAC (pass=0x7fe60f "testtesttest", passlen=12, salt=0x7fd810 "\262\"\224\324<I\320\377\200\227{", saltlen=8            , iter=10000, digest=0x7ffff777ce48 <sha256_md>, keylen=32, out=0x7fd6c0 "\344\341\023T\221\202g\235\333_y\203\264u\252\067t)\204V\254\351Mt\265\064\342\323A\313\031\255") at crypto/evp/p5_crpt2.c:58
    #8  0x0457f68 in enc_main (argc=12, argv=         0x7fe2a0) at apps/enc.c:484
    #9  0x047cee2 in do_cmd (prog=0x7b7700, argc=12, argv=         0x7fe2a0) at apps/openssl.c:481
    #10 0x047bd1f in main (argc=12, argv=0x7fe2a0)                at apps/openssl.c:294

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Type openssl enc -e -des3 -a -salt -in /tmp/test.c -out test.cipher -k testtesttest -pbkdf2
1. Make the _malloc()_ shown at **Describe the bug** fail.
2. The program will crash.

**Expected behavior**
The program would not crash when _malloc()_ fails.

**Environment (please complete the following information):**
 - Version: 3.0.0-dev
 - OS: Ubuntu 18.04
 - Compiler: Clang-6.0
 - Application: openssl 3.0.0-dev

**Additional context**
This bug is found by my fuzzing tool and the bug is triggered at runtime.

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #10481

### CODE REVIEW

**Comment by slontis** [comment]
There is one more of this pattern in sha3_prov.c

**Comment by paulidale** [comment]
Thanks @slontis, I've added a fix for that one.

Re-review needed @levitte.

**Comment by levitte** [comment]
Done

**Comment by paulidale** [comment]
Merged to master.  Thanks all.

**Pull request closed without merging**
