### PR TITLE
apps/ciphers.h: Ensure ossl_assert() is properly declared [3.0 only]

### PR DESCRIPTION
**Pull request by levitte**
This is necessary for this branch to build

### CODE REVIEW

**Comment by levitte** [comment]
Marked urgent, because 3.0 builds are currently failing:

https://ci.buildbot.openssl.org/#/builders

**Review by beldmit — APPROVED** [review]
LGTM, agree urgent

**Comment by levitte** [comment]
Ping @openssl/committers

**Review by slontis — APPROVED** [review]

**Comment by slontis** [comment]
Ok with it a urgent also.

**Comment by levitte** [comment]
Merged

e711c4b32b09d6ea00626ba0df01e2bb0c139a19 apps/ciphers.h: Ensure ossl_assert() is properly declared

**Pull request closed without merging**
