### PR TITLE
This fix shows actual Key Block size - to demonstrate the bug of wrong Key Block Size calculation

### PR DESCRIPTION
**Pull request by maximmasiutin**
CLA: trivial

This fix shows actual Key Block size when tracing to help demonstrate the bug described in https://github.com/openssl/openssl/issues/12007

[x] Tracing shows Key Block size

### CODE REVIEW

**Comment by maximmasiutin** [comment]
CLA: trivial

This is a trivial contribution.

**Comment by maximmasiutin** [comment]
I have just sent the signed CLA to legal@opensslfoundation.org

**Comment by mattcaswell** [comment]
I've registered your CLA, but it looks like you have an incorrect setting in your git setup. the Author field looks very odd:

````
Author:     unknown <C:\Users\Maxim Masiutin\AppData\Roaming\The Bat!>
````

This should be your email address - and its what the cla-check uses to verify your CLA.

**Comment by maximmasiutin** [comment]
Could you please update my author field to maxim.masiutin@gmail.com  "Maxim Masituin" or let me know where can I edit it?

**Comment by maximmasiutin** [comment]
Thank you! I have configured the following:

git config --global user.email "maxim.masiutin@gmail.com"
git config --global user.name "Maxim Masiutin"


...and created a pull request again.

Could you please advise whether https://github.com/openssl/openssl/pull/12028 is OK?

**Comment by mattcaswell** [comment]
> Thank you! I have configured the following:

That should fix it for new commits that you make. It won't amend commits that you've already created though. You will need to go back and edit the existing commits. Look into "git rebase -i" and "git commit --amend --author"

**Pull request closed without merging**
