### PR TITLE
Bumped HMAC_MAX_MD_CBLOCK to 200

### PR DESCRIPTION
**Pull request by fxdupont**
cf issue #4335

### CODE REVIEW

**Comment by snhenson** [comment]
Note: we should consider the binary compatibility issues associated with this change I mentioned in #4335. In the worst case (admittedly highly unlikely) this could result in a OOB write in application code.

**Comment by dot-asm** [comment]
HMAC was designed to counter specific shortcomings in then contemporary digests. It's asserted that SHA-3 doesn't need HMAC to deliver the corresponding security property. But of course relevant question is rather if HMAC-SHA-3 is expected to be available nevertheless. But even then the problem would have to be solved *without* modification of the public header. Then one can argue if it's sensible to change or even remove the macro in *next* major release.

**Comment by kroeckx** [comment]
I agree that we shouldn’t change this 1.1.1.

**Comment by dot-asm** [comment]
Well, we can modify public header, but it doesn't *necessarily* mean that it's impossible to get SHA-3 working with HMAC. After all HMAC_CTX is not something application can allocate by itself... Also note that HMAC_size has nothing to do with SHA-3 block size...

**Comment by dot-asm** [comment]
> Well, we can modify public header,

Brainslip! I naturally meant "we can *not* modify public header".

**Comment by snhenson** [comment]
Hmm... I'd be in favour or removing all the "max length" macros from public headers in the next major release because they stop us exceeding them in an ciphers or digests in minor releases. However that will complicate application code.

Here is an example of what I mean. Suppose an application wants to store a digest, it's very common to do something like this:
`unsigned char md[EVP_MAX_MD_SIZE];`
That currently guarantees that any digest we have can fit in it. If we change `EVP_MAX_MD_SIZE` in a minor release or have a digest that exceeds this length then the application could end up overwriting the buffer.

We _potentially_ have a problem with block lengths too. Imagine an application that wants to store one block length of a digest somewhere and similarly does:
`unsigned char md_block[HMAC_MAX_MD_CBLOCK];`
and then uses a digest where the block length exceeds that value and uses (say) EVP_MD_block_size(). I say _potentially_ because this scenario is far less likely.

**Comment by fxdupont** [comment]
I believe we can split required changes into 1.1.1 and next major release:
 - for the next major release it seems the best is to remove HMAC_MAX_MD_CBLOCK from the public hmac.h header as there is no legitimate use of it outside OpenSSL private code.
 - as this can be considered as a change in the API it should not be done for master / next minor release branch. Options are:
  *1* do nothing but this means a known defect is left
  *2* change the value in hmac.h but it is a public header
  *3* redefine the macro (e.g. changing its name) in the hmac code. As it is compiled into one (*only*) binary file this should not raise other issue than to leave a misleading value in the public header.
BTW the PR implements 2.

**Comment by dot-asm** [comment]
And provided that HMAC is actually expected to work with SHA-3 (it's discussed in specification and it's validated by NIST), 1 can hardly be tolerated. 2 is no go, so 3 is the one to go for. And if there is an application the uses HMAC_MAX_MD_CBLOCK (for whichever unlike reason), it's not unreasonable to expect/assume that this application will abstain from SHA-3.

**Comment by snhenson** [comment]
That depends on how the application uses digests. 

If it hard codes the functions as EVP_sha256() etc then yes an existing application will never use any SHA-3 digests (because the functions didn't exist at that time) and there is no problem with an inconsistency in HMAC_MAX_MD_BLOCK. 

If however an existing application looks up digests based on EVP_get_digestbyname() or variants (e.g. via ASN.1) then it could use SHA-3 digests.

**Comment by snhenson** [comment]
Note: putting this on hold as I think it needs to further thought and discussion.

**Comment by dot-asm** [comment]
> If however an existing application looks up digests based on EVP_get_digestbyname() or variants (e.g. via ASN.1) then it could use SHA-3 digests.

Initially I started writing "application will abstain from SHA-3, directly or indirectly", which would have to be followed by explanation which meaning do I put into "directly or indirectly". But then I decided that it would be too long. It seems that it was worth discussing anyway. "Directly" obviously means explicitly not calling any of EVP_sha3\*(). I.e. equivalent of "hard-coded" case discussed above. And "indirectly" means that even if application linked with 1.1.0 ends up with SHA-3 EVP_MD *and* relies on the macro in question, it would be reasonable to hold it responsible for checking EVP_MD's block size and abstaining from using it, taking suitable actions handling it as an error condition. [Kind of the way crypto/hmac/hmac.c currently does. I mean if you pass SHA-3 EVP_MD as it stands now, HMAC_Init_ex will return 0 signaling error.] However, if we switch to private version of the disputed macro, 1.1.0 application that relies on HMAC_\* interface would actually be able to [indirectly] work even with SHA-3, without having to be recompiled. Because in such case it has no dependency on the macro.

**Comment by snhenson** [comment]
Well that's the crucial point here. Is it reasonable to assume an application will check that `EVP_MD_block_size(digest) <= HMAC_MAX_MD_BLOCK_SIZE` and if not do something sensible? 

It might assume that we are always guaranteeing that and such a check is unnecessary. For the constant `EVP_MAX_MD_SIZE` then there are many cases where we don't check that internally for example.

**Comment by dot-asm** [comment]
> Well that's the crucial point here. Is it reasonable to assume an application will check that EVP_MD_block_size(digest) <= HMAC_MAX_MD_BLOCK_SIZE and if not do something sensible?

Correct, this is the point. And I argue that it's reasonable assumption to make. If application is up to performing HMAC calculations by itself, it should pay attention. Note that if we can't make this assumption, then formally speaking we would have to consider the macro in question as "contract" that we won't provide digests with block size larger than the macro value. In such case we would actually have to remove all EVP_shake\* and EVP_sha3_\*, but EVP_sha3_512.

On related note it might be worth noting that none of our public functions use caller's supplied buffer of HMAC_MAX_MD_BLOCK_SIZE size. So that there won't be any incompatibilities on that level.

**Comment by dot-asm** [comment]
> remove all EVP_shake\* and EVP_sha3_\*

If it actually becomes to such point, what might be possible to do is to arrange things in such manner that application compiled with 1.1.1 would call alternative initialization subroutine. One that accepts version caller expects from the library. This way libcrypto would "know" if application was linked with 1.1.0 or 1.1.1. And in former case simply not register EVPs in question, leaving them inaccessible through EVP_get_digestby\*.

**Comment by dot-asm** [comment]
Regarding last commit, see #4355. Or in other words it will be disregarded.

**Comment by mattcaswell** [comment]
Close/reopen to kick CLA bot

**Comment by mattcaswell** [comment]
Please could you rebase this? There have been some changes in master which are now conflicting. Also it looks like part off this PR  already got implemented.

**Comment by t8m** [comment]
Closing due to bitrot and having replacement in #15125.

**Pull request closed without merging**
