### PR TITLE
Fix NULL access in ssl_build_cert_chain() when ctx is NULL.

### LINKED ISSUE #14294: SSL_build_cert_chain crashed
Recently I am testing the new OpenSSL 3.0 alpha release and I find a regression that track to commit 6725682d77510bf6d499957897d7be124d603f40.
 
The file in question is ssl/ssl_cert.c 
My application crashes at line 887 because ctx is null.
    xs_ctx = X509_STORE_CTX_new_with_libctx(real_ctx->libctx, ctx->propq);
 
The crash callstack is:
ssl_build_cert_chain
ssl3_ctrl (case SSL_CTRL_BUILD_CERT_CHAIN: it pass in ctx as null)
SSL_ctrl
SSL_build_cert_chain

### PR DESCRIPTION
**Pull request by slontis**
Fixes #14294

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by mattcaswell — CHANGES_REQUESTED** [review]
There is another reference to `ctx` later in the function which probably should be `real_ctx`

Can we have a test case for calling SSL_build_cert_chain/SSL_CTX_build_cert_chain?

**Comment by slontis** [comment]
> There is another reference to `ctx` later in the function which probably should be `real_ctx`

I am not seeing this reference? The only line down using a ctx is ````ssl_security_cert(s, ctx, x, 0, 0);```` and that is ok.

**Review by paulidale — APPROVED** [review]

**Comment by slontis** [comment]
> Can we have a test case for calling SSL_build_cert_chain/SSL_CTX_build_cert_chain?

I am not quite sure how to set the certs up - I tried doing this in sslapitest.. 

````
static int test_build_cert_chain(void)
{
    int ret = 0;
    SSL_CTX *ssl_ctx = NULL;
    SSL *ssl = NULL;
    /* server key, cert, chain, and root */
    char *skey = test_mk_file_path(certsdir, "leaf.key");
    char *leaf = test_mk_file_path(certsdir, "leaf.pem");
    //char *int2 = test_mk_file_path(certsdir, "subinterCA.pem");
    //char *int1 = test_mk_file_path(certsdir, "interCA.pem");
    //char *root = test_mk_file_path(certsdir, "rootCA.pem");

    if (!TEST_ptr(ssl_ctx = SSL_CTX_new_ex(libctx, NULL, TLS_server_method())))
        goto end;
    if (!TEST_ptr(ssl = SSL_new(ssl_ctx)))
        goto end;
    if (!TEST_int_eq(SSL_use_certificate_chain_file(ssl, leaf), 1)
        || !TEST_int_eq(SSL_use_PrivateKey_file(ssl, skey,
                                                SSL_FILETYPE_PEM), 1)
        || !TEST_int_eq(SSL_check_private_key(ssl), 1))
        goto end;
    if (!TEST_true(SSL_build_cert_chain(ssl, 0)))
        goto end;
    ret = 1;
end:
    SSL_free(ssl);
    SSL_CTX_free(ssl_ctx);
    return ret;
}
````

**Comment by mattcaswell** [comment]
> I am not seeing this reference? The only line down using a ctx is ssl_security_cert(s, ctx, x, 0, 0); and that is ok.

Ah yes, you're right. I wasn't reading the code right.

> I am not quite sure how to set the certs up

The simplest thing is probably to set the entire chain (including the leaft and the root) as a single pem file with the different certs concatenated together (in order), i.e. leaf.pem, subinterCA.pem, interCA.pem, rootCA.pem, and then use the flag `SSL_BUILD_CHAIN_FLAG_NO_ROOT` to omit the root from the final built chain.

**Review by t8m — APPROVED** [review]

**Comment by mattcaswell** [comment]
I'd still like to see a test here...

**Comment by slontis** [comment]
ssl_build_cert_chain tests added for ssl  and ssl_ctx inputs.

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by slontis** [comment]
Oops - pushed to wrong branch... undoing now!!

**Comment by slontis** [comment]
Thanks.. Merged to master.

**Pull request closed without merging**
