### PR TITLE
Recognise mingw64 in config script

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
Note that this is taken down the whole way to 1.0.2.  We've had `mingw64` for a long time, and yet, `./config` would never recognise it and choose `mingw` instead, [which has been shown to give bad results on `x86_64-whatever-mingw`](https://mta.openssl.org/pipermail/openssl-users/2017-March/005425.html)

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

master: 57cb3385b109ff66f7cb0b81ad3a89543bfd6f68
1.1.0: 1a25ec7379a33cd8051d373e47043172ce2ad0b9
1.0.2: c4bfccfff85cea4dd16d701868e0efa9d80384cc

**Comment by dot-asm** [comment]
You regularly install updates on your computer, right? Would you appreciate if some utility would interpret a flag you would normally use differently as result of such *maintenance* update? What I'm saying is that there are changes that are not *always* appropriate and would argue that for example this one doesn't *necessarily* belong in [deep-support] 1.0.2. Yes, one can argue that this is a bug, but judging from feedback people do know how to compile 1.0.2 for mingw64 and might even rely on current ./config behaviour. One can argue that it's a bad choice to do the latter, but question is if we are in position to judge it. At the very least I'd say that it deserves a note in CHANGES...

**Comment by levitte** [comment]
You're right.  I'm going for the note in CHANGES.

**Comment by levitte** [comment]
See #2917

**Comment by dot-asm** [comment]
When you install MSYS2 you get MinGW 32-bit and MinGW 64-bit icons. Difference? Different $PATH pointing at 32- or 64-bit compiler. Different uname -s output, but[!] same uname -m. Here ./config effectively "looks" at latter, while it should probably "look" at former...

**Comment by dot-asm** [comment]
As mentioned in #2917 this modification breaks 32-bit mingw auto-config.

**Comment by levitte** [comment]
Only when you attempt to use a 32-bit environment on a x86_64 machine.  Just the same as the lack of this fix breaks mingw auto-config on a x86_64 machine in a 64-bit environment.

Either way, it breaks somewhere, so my conclusion is that *only* looking at `uname -s` is just as bad as *only* looking at `uname -m'  We need to do both.  I'll be back with an update after some thought.

**Comment by dot-asm** [comment]
> Only when you attempt to use a 32-bit environment on a x86_64 machine.

And I'd say that that's what majority of users would actually do. At least if you are given a choice of having dual-bitness setup on *one* machine or having *two* machines (and you can't actually buy second one today), you'd naturally choose former. Looking at `uname -s` produces more correct/consistent output. Consistent with prior users' experience and current state of MSYS2 affairs that is. Looking at `uname -s` does produce unexpected result if 32-bit Windows installation offers 64-bit "shell", but this isn't a case that can be formally classified as suitable for auto-config. That's what we are talking about here, aren't we? Auto-config...

**Pull request closed without merging**
