### PR TITLE
Fix docs for CRYPTO_secure_allocated

### PR DESCRIPTION
**Pull request by richsalz**

### CODE REVIEW

**Comment by richsalz** [comment]
If backported, the missingcrypto111.txt file will also have to be edited.

**Comment by mattcaswell** [comment]
I notice there is no description of this in the "DESCRIPTION" section - only in the "RETURN VALUES" section. Which I find odd.

**Comment by levitte** [comment]
Yup, description missing.

**Comment by richsalz** [comment]
updated commit pushed.

**Comment by levitte** [comment]
Merged.

master:
20c09f00346aec3a20ceacc9c9d44c5f050e13dd Fix docs for CRYPTO_secure_allocated

1.1.1:
3814dfe8df847d49f8040b3b9cbad4a8a494d46b Fix docs for CRYPTO_secure_allocated

**Pull request closed without merging**
