### PR TITLE
VMS: stricter acquisition of entropy for the pool

### PR DESCRIPTION
**Pull request by levitte**
Fail harshly (in debug builds) when rand_pool_acquire_entropy isn't
delivering the required amount of entropy.  In release builds, this
produces an error with details.

We also take the opportunity to modernise the types used.

### CODE REVIEW

**Comment by levitte** [comment]
Note: this is related to #5849 but doesn't solve the issue, only makes it clear where the issue is.

**Review by richsalz — APPROVED** [review]

**Comment by kroeckx** [comment]
So I understand that this is a combination of getting the time, setting the time as seed using srand(), and then generating some random data using rand(). Can I suggest you don't do this, and just say that the OS does not provide random data?

An alternative is that you use rdrand/rdseed as source. That's going to be so much better than what you have now.

**Comment by levitte** [comment]
> ... and just say that the OS does not provide random data?

What happens then?  Is that the equivalent of configuring with `--with-rand-seed=none`?

> An alternative is that you use rdrand/rdseed as source. That's going to be so much better than what you have now.

Sure.  Do you have that available for Alpha and IA64?

**Comment by richsalz** [comment]
There is no security justification for increasing the seeding requirement to 384 bits.

**Comment by levitte** [comment]
@richsalz, I imagine that changing the base cipher from AES-128-CTR to AES-256-CTR is seen as a security justification.  The requirement for more entropy (256 bits) comes along with that.  And then there's the nonce thing that added 128 more required bits...

**Comment by kroeckx** [comment]
> What happens then? Is that the equivalent of configuring with --with-rand-seed=none?

Yes that would be the effect. You would get an error.

You're really only asking the time N times (and doing some math with it), that really does not contain anything close to required entropy. Doing math with it also does not increase the entropy.

**Comment by richsalz** [comment]
@levitte yes I understand how we got here.  I started a thread on openssl-project.  I think the current state is *misguided and wrong.*

**Comment by levitte** [comment]
Merged.

fc1d73bb0c4f2977c999031debc7946c9b29fc8b VMS: stricter acquisition of entropy for the pool

**Comment by levitte** [comment]
@kroeckx, it does a little more than that.  See all those `JPI$_` items?  Those are diverse system data that has been judged changing enough to be seen as "good enough" entropy (à 4 bits per byte).

**Comment by levitte** [comment]
(this discussion should really be conducted in #5849)

**Pull request closed without merging**
