### PR TITLE
Windows CI: Continue on error during cpuinfo

### PR DESCRIPTION
**Pull request by t8m**
We recently see errors during the cpuinfo commands on windows runners. This would allow some further investigation.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
When merging, the commit marked drop! must be dropped.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
This is actually urgent as we have CI failures.

**Comment by t8m** [comment]
@tom-cosgrove-arm @paulidale OK with urgent?

**Comment by tom-cosgrove-arm** [comment]
OK with urgent

**Review by mattcaswell — APPROVED** [review]
Agree urgent

**Comment by t8m** [comment]
Merging.

**Comment by t8m** [comment]
Merged to the master branch. Thank you for the reviews.

**Pull request closed without merging**
