### PR TITLE
Ensure our buffer allocation allows for the Explicit IV

### PR DESCRIPTION
**Pull request by mattcaswell**
Some ciphers/protocol versions have an explicit IV. We need to make sure we
have sufficient room for it in the underlying buffer.

This fixes a regression introduced during the record layer refactor.

### CODE REVIEW

**Comment by t8m** [comment]
CI is relevant

**Comment by t8m** [comment]
minimal CI fails still

**Comment by mattcaswell** [comment]
Fixup pushed hopefully addressing the minimal CI failure. I also added a commit to extend the test to include DTLS.

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged.

**Pull request closed without merging**
