### PR TITLE
import .travis.yml from master

### PR DESCRIPTION
**Pull request by richsalz**
Yet another attempt to fix the msan build.  Sigh.  Can someone who actually *knows* this stuff land a hand?  msan builds on 1.1.0 are broken.

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
This will fail as it contains BORINGSSL_TESTS="yes" 
but the _boringssl_ folder external link (and the wrapping test scripts?) were not backported.

**Comment by richsalz** [comment]
sure, but i only want to see if msan passes.  but fixed.

**Comment by ekasper** [comment]
https://github.com/openssl/openssl/pull/2295

**Comment by richsalz** [comment]
great.

**Pull request closed without merging**
