### PR TITLE
Fix windows and other O/S init_fork_handlers

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Not sure how VMS is doing...

### CODE REVIEW

**Comment by richsalz** [comment]
The intent was that the fork handlers are NOT called by default.  So why is this necessary?

**Comment by bernd-edlinger** [comment]
because it is called?

**Comment by bernd-edlinger** [comment]
libcrypto-1_1.dll!openssl_init_fork_handlers()  Line 138	C
>	libcrypto-1_1.dll!OPENSSL_init_crypto(unsigned __int64 opts=0x0000000000000000, const ossl_init_settings_st * settings=0x00000000)  Line 556 + 0x12 bytes	C
 	libcrypto-1_1.dll!do_ex_data_init_ossl_()  Line 39 + 0xb bytes	C
 	libcrypto-1_1.dll!CRYPTO_THREAD_run_once(long * once=0x00632230, void (void)* init=0x0052d8e0)  Line 81 + 0x4 bytes	C
 	libcrypto-1_1.dll!get_and_lock(int class_index=0x00000000)  Line 59 + 0xf bytes	C
 	libcrypto-1_1.dll!CRYPTO_new_ex_data(int class_index=0x0000000c, void * obj=0x01601cd8, crypto_ex_data_st * ad=0x01601d20)  Line 214 + 0xc bytes	C
 	libcrypto-1_1.dll!BIO_new(const bio_method_st * method=0x005b7bb4)  Line 85 + 0x19 bytes	C
 	libcrypto-1_1.dll!BIO_new_fp(_iobuf * stream=0x6c9e73a8, int close_flag=0x00000010)  Line 105 + 0xa bytes	C
 	openssl.exe!dup_bio_in(int format=0x00008001)  Line 2421 + 0x25 bytes	C
 	openssl.exe!main(int argc=0x00000001, char * * argv=0x01601c70)  Line 125	C
 	openssl.exe!__tmainCRTStartup()  Line 586 + 0x17 bytes	C
 	kernel32.dll!@BaseThreadInitThunk@12()  + 0x12 bytes	
 	ntdll.dll!___RtlUserThreadStart@8()  + 0x27 bytes	
 	ntdll.dll!__RtlUserThreadStart@8()  + 0x1b bytes

**Comment by richsalz** [comment]
Rats.  The code in crypto/init.c is wrong.  The intent is that unless you specify the flag, the fork handlers *are not called.*   So the define should be renamed from ``` OPENSSL_INIT_NO_ATFORK``` to ``` OPENSSL_INIT_ATFORK``` and the test in init.c inverted.  Does that make sense?

**Comment by bernd-edlinger** [comment]
whatever helps...

**Comment by richsalz** [comment]
Please see #3815

**Comment by bernd-edlinger** [comment]
closing.

**Pull request closed without merging**
