### PR TITLE
Improving locale test

### LINKED ISSUE #18205: locatetest doesn't seem to test properly
Refer:

https://github.com/openssl/openssl/blob/bbe909d00e9a593bd5954dfca4d3020467977565/test/localetest.c#L94-L103

Should the TEST_ptr on line 94 and the TEST_false on line 99 both be wrapped by `if (...) return 0;`?
Without this, the test won't fail but will log output with ERROR in it.  IMO, this is not a good thing.

### PR DESCRIPTION
**Pull request by beldmit**
Fixes #18205
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
Done

**Comment by petrovr** [comment]
Dmitry Belyavskiy wrote:
>    * Improving locale test
>
Is locale test skipped if system does not support "locale" used in test?
I could found "skip" message.

Roumen

**Comment by beldmit** [comment]
For Github CI purposes I added explicit installation of the Turkish langpack. I have no idea how to check if the particular locale is present

**Review by paulidale — APPROVED** [review]

**Comment by beldmit** [comment]
Merged both to 3.0 and master. Thanks!

**Pull request closed without merging**
