### PR TITLE
openssl req command checking digest.  Fixes: #15285 

### LINKED ISSUE #15285: openssl req command fails to spot an invalid option until very late
In 1.1.1 supplying an invalid option to the `req` command would fail immediately:

````
$ openssl req -foo -x509 -newkey rsa:2048 -keyout key.pem -out req.pem -nodes
req: Unrecognized flag foo
req: Use -help for summary.
````

In master it believes the unrecognised option is a digest name, but doesn't discover the problem until it attempts to use it:

````
$ openssl req -foo -x509 -newkey rsa:2048 -keyout key.pem -out req.pem -nodes
Generating a RSA private key
.....+...+.....+...+...+.+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+............+.+..+....+...+...........+.+...........+...+....+...+.....+.........+.+..............+...............+...+...+...+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+......+.........+.+..+...+....+...+..+...+...+.+......+...+............+.....+............+.......+......+...............+..+............+.+...+..............+...+.......+..+.........+............+....+...+......+...............+..+....+......+...+.....+.......+..+.+..+............+.......+..............+......+...+..........+......+..+...+.........+.+..+...+.+...+..+...+.......+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+....+...+..+......+......+.+..............+...................+..+...................+..................+......+.........+..+...+................+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+..+............+.+.........+......+............+..+.+.....+.+...+...........+..........+.........+...+...+..+.......+..+....+.........+...+........+....+..+...+.+.....+.+......+.....+..........+....................+...+......+...+...+.........+....+..+....+..............+..........+.....+...............+.+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Writing new private key to 'key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:
Warning: No -copy_extensions given; ignoring any extensions in the request
80026005537F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:332:Global default library context, Algorithm (foo : 0), Properties (<null>)
80026005537F0000:error:03000086:digital envelope routines:do_sigver_init:initialization error:crypto/evp/m_sigver.c:192:
````

### PR DESCRIPTION
**Pull request by luxinyou**
openssl req checking digest

Fixes #15285 

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
For the third time :) look at how CMS does it -- *after* all options are processed, like @mattcaswell said.  In particular, look at the context of https://github.com/openssl/openssl/blob/master/apps/cms.c#L710 and see when it is done.

**Comment by luxinyou** [comment]
> For the third time :) look at how CMS does it -- _after_ all options are processed, like @mattcaswell said. In particular, look at the context of https://github.com/openssl/openssl/blob/master/apps/cms.c#L710 and see when it is done.

**Comment by luxinyou** [comment]
> For the third time :) look at how CMS does it -- _after_ all options are processed, like @mattcaswell said. In particular, look at the context of https://github.com/openssl/openssl/blob/master/apps/cms.c#L710 and see when it is done.

Oh, thanks, I try to correct it and test.

**Comment by levitte** [comment]
The commit message needs an edit, it shouldn't have `Fix #15285` in the subject line (the first line).  Changing it this is better:

```
openssl req checking digest

Fixes #15285 

CLA: trivial
```

**Comment by t8m** [comment]
CLA: trivial would be also wrong. This is not within what is acceptable for CLA: trivial change.

**Comment by luxinyou** [comment]
> The commit message needs an edit, it shouldn't have `Fix #15285` in the subject line (the first line). Changing it this is better:
> 
> ```
> openssl req checking digest
> 
> Fixes #15285 
> 
> CLA: trivial
> ```

Thanks

**Comment by luxinyou** [comment]
> CLA: trivial would be also wrong. This is not within what is acceptable for CLA: trivial change.

I have provide my CLA files via e-mail, should I remove this mark for trivial change?

**Comment by t8m** [comment]
Yes, please

22. 5. 2021 4:55, 4:55, luxinyou ***@***.***> napsal/a:

**Comment by kaduk** [comment]
> I want to know what's wrong with this pull request, should I do something for it?

I believe that it's currently waiting for code review from the project members.  Two reviews are necessary, at least one of which must be from an OTC member.
Unfortunately, developer energy is almost entirely focused on the forthcoming 3.0.0 release at the moment (which is subject to an external deadline for getting FIPS validation), so it may be a couple months before the required review occurs.

But, to be clear: there is not currently anything you need to do for it -- when code review happens, there may be comments that require you to make changes to the PR, but not right now.

**Comment by t8m** [comment]
There is actually something that needs to be done here. The commit message still contains the `CLA: trivial` and that is wrong. This is not within the limits of changes acceptable for `CLA: trivial`. Please amend the message with `git commit --amend` and force-push.

**Comment by luxinyou** [comment]
> There is actually something that needs to be done here. The commit message still contains the `CLA: trivial` and that is wrong. This is not within the limits of changes acceptable for `CLA: trivial`. Please amend the message with `git commit --amend` and force-push.

I removed CLA remarks and I have submitted CLA but the cla-check still not pass.

**Comment by paulidale** [comment]
It is possible that the wrong author email is set on your commits.

It's also possible we missed your CLA: send an email to legal@openssl.org with your details and I'll check.

**Comment by luxinyou** [comment]
> It is possible that the wrong author email is set on your commits.
> 
> It's also possible we missed your CLA: send an email to [legal@openssl.org](mailto:legal@openssl.org) with your details and I'll check.

Oh, I mistook email as legal@opensslfoundation.org, I resend again.

**Comment by luxinyou** [comment]
> > It is possible that the wrong author email is set on your commits.
> > It's also possible we missed your CLA: send an email to [legal@openssl.org](mailto:legal@openssl.org) with your details and I'll check.
> 
> Oh, I mistook email as [legal@opensslfoundation.org](mailto:legal@opensslfoundation.org), I resend again.

I send CLA files to legal@openssl.org, but it's not reachable. The  guide show me email-address with legal@opensslfoundation.org.

**Comment by paulidale** [comment]
It's meant to be legal@opensslfoundation.org, my mistake there.

**Comment by luxinyou** [comment]
> It's meant to be [legal@opensslfoundation.org](mailto:legal@opensslfoundation.org), my mistake there.

I have just send CLA files. I wanna to get reply if these files can works.

**Comment by paulidale** [comment]
Your CLA files didn't arrive here.  @levitte any idea?

**Comment by luxinyou** [comment]
My colleague (yangmingjun@uniontech.com) has commit CCLA files . Should recheck cla ?

**Comment by mattcaswell** [comment]
Your colleague has sent us the CCLA, and we have you listed on it. However all developers *also* need an ICLA. Your colleague has done so for themselves but I don't see one for you.

**Comment by ymj-uos** [comment]
image

**Comment by t8m** [comment]
Closing as #15285 was already closed.

**Pull request closed without merging**
