### PR TITLE
Remove -C from dhparam,dsaparam,ecparam

### PR DESCRIPTION
**Pull request by richsalz**
The other half of #13313 :)

ping @paulidale

### CODE REVIEW

**Review by paulidale — COMMENTED** [review]
Looks good.

x509 also has a `-C` option

**Comment by paulidale** [comment]
Thanks 👍 

Very quick after the vote results 😃

**Comment by richsalz** [comment]
Removed -C from the x509 command; additional commit pushed (should be squashed when merging)

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Assuming CIs pass...

**Review by levitte — APPROVED** [review]

**Comment by mattcaswell** [comment]
The `dhparam` change duplicates what is in #13231

**Comment by levitte** [comment]
> The `dhparam` change duplicates what is in #13231

Is that why @paulidale removed the "approval: done" label?  That seems a bit unnecessary.  I suppose that rebasing #13231 after this gets merged isn't a hard task (with some luck, git will realise that the patch has already been applied, and simply skip over it)

**Comment by paulidale** [comment]
Removing the label was a mistake.  I've reinstated it and switched it to ready.

I agree that rebasing isn't too onerous.

**Comment by levitte** [comment]
Merged

1696b8909bbe1485871ce68ed129bf91af5e17e2 Remove -C from dhparam,dsaparam,ecparam
a18cf8fc634a8834e505e60ebb7f947d4c0c2552 Remove -C option from x509 command

**Comment by arekm** [comment]
What's the correct way to replace lack of this code generation via -C (migarion guide seems to be silent in this area) ?

**Comment by paulidale** [comment]
There isn't a direct replacement.

**Review by Sunnix01 — APPROVED** [review]

**Pull request closed without merging**
