### PR TITLE
test/build.info: add missing ../apps/include

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by romen — APPROVED** [review]
LGTM!

We should try to remember to run a final complete build and test run before pushing a PR after a rebase!

Today we got a lot of commits to fixup build errors introduced by `git rebase` when committing PRs.

**Comment by levitte** [comment]
Yup, agreed

**Comment by levitte** [comment]
Merged.

953315ae60e135057e308ebd0778ed823d620970 test/build.info: add missing ../apps/include

**Comment by romen** [comment]
Thanks for fixing this quickly, I was going to open a similar PR as I noticed the problem rebasing an upcoming PR I am working on!

**Pull request closed without merging**
