### PR TITLE
Add a configure option for sec mem [1.1.0]

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This is the back-port of test part.

### CODE REVIEW

**Comment by levitte** [comment]
I think you forgot to change `crypto/mem_sec.c`...

**Comment by levitte** [comment]
But also, I think we need to ask ourselves if this constitutes a new feature.  If that's the case, this PR is a no go for 1.1.0.

What say the rest of @openssl?

**Comment by bernd-edlinger** [comment]
That part I intend to cherry-pick from the other PR,

**Comment by bernd-edlinger** [comment]
IMO passing -DOPENSSL_NO_SECURE_MEMORY to the config options is not a new feature,
it does not change the exported interface in any way.

**Comment by levitte** [comment]
Nope, but it adds a behavior that wasn't there before...  let's take it from another angle, would you say this is a bug fix?

**Comment by bernd-edlinger** [comment]
Yes:
The main purpose of the secure memory handling is to avoid leaking secrets
via the page file.
But there are targets where no page file is in use, like in your mobile phone.
So it is not completely unexpected that the code in mem_sec.c can cause
trouble on those environments.
On the other hand, it is also a step to reducing the footprint.
So avoiding portability issues, and reducing footprint is worth to have.

**Comment by richsalz** [comment]
Seems like adding a build option is a new feature.  But I don't care very much.

**Comment by bernd-edlinger** [comment]
closing based on the discussion.

**Comment by richsalz** [comment]
I was just expressing an opinion, that's all.  The "not feel strongly" is a hint :)

**Pull request closed without merging**
