### PR TITLE
Configure: do not check for an absolute prefix in cross-builds

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Review by t8m — APPROVED** [review]
The change seems OK to me now. However it is no longer acceptable with CLA: trivial. Could you please submit a regular CLA? https://www.openssl.org/policies/cla.html

**Comment by vszakats** [comment]
I feel this to be trivial. But at this time I'm not willing to disclose personal data to submit this, sorry (I already did before, for an earlier commit email address). You have all my persmission to use this and I hold no copyright for this change.

**Comment by t-j-h** [comment]
@t8m is correct in that although this is a simple change, it steps outside the project comfort zone for legally trivial (a different measurement).

**Comment by t8m** [comment]
> (I already did before, for an earlier commit email address)

Perhaps you could change the commit's e-mail address to use this old one?

**Comment by vszakats** [comment]
Going back to the old email isn't an option. So, I reported this issue in detail multiple times, waited two years, did the patch, reworked it according to your preference, offered it for free/unlimited use for the project. That is all I'm able to do here.

**Comment by vszakats** [comment]
Here's the patch for the record, if someone is willing to fix this security issue in OpenSSL under their own name:

License [CC0](https://creativecommons.org/publicdomain/zero/1.0/) / Public Domain:
```patch
diff --git a/Configure b/Configure
index b00b91ac63f5..2b090dbb0ad1 100755
--- a/Configure
+++ b/Configure
@@ -936,8 +936,6 @@ while (@argvcopy)
                 if (/^--prefix=(.*)$/)
                         {
                         $config{prefix}=$1;
-                        die "Directory given with --prefix MUST be absolute\n"
-                                unless file_name_is_absolute($config{prefix});
                         }
                 elsif (/^--api=(.*)$/)
                         {
@@ -1380,6 +1378,11 @@ foreach (keys %useradd) {
 # At this point, we can forget everything about %user and %useradd,
 # because it's now all been merged into the corresponding $config entry
.
+if ($config{prefix} && !$config{CROSS_COMPILE}) {
+    die "Directory given with --prefix MUST be absolute\n"
+        unless file_name_is_absolute($config{prefix});
+}
+
 if (grep { $_ =~ /(?:^|\s)-static(?:\s|$)/ } @{$config{LDFLAGS}}) {
     disable('static', 'pic', 'threads');
 }
```

**Pull request closed without merging**
