### PR TITLE
Configuration: make sure the shared_sources table doesn't contain empty elements [1.1.1 & 1.1.0]

### LINKED ISSUE #7634: Annoying Perl warnings in recent builds.
In recent builds of 1.1.1, there are many warnings output, all:
```
Use of uninitialized value in pattern match (m//) at ./util/add-depends.pl line 40.
```

### PR DESCRIPTION
**Pull request by levitte**
Fixes #7634

### CODE REVIEW

**Review by vdukhovni — APPROVED** [review]
Problem fixed.  Thanks.  I think this is needed for both 1.1.1 and master.

**Comment by levitte** [comment]
Master ? I tested there and didn't get the same issue.
I saw that 1.1.0 may have a similar issue, so cherry picking there.

**Comment by vdukhovni** [comment]
> @levitte Master ? I tested there and didn't get the same issue.

Perhaps I am mistaken, I did not look recently.

**Comment by vdukhovni** [comment]
Yeah, master is different, and does not exhibit the same symptoms in my tests.

**Comment by vdukhovni** [comment]
Please go ahead and merge.

**Comment by levitte** [comment]
Thanks!

Merged

1.1.1:
0c594ccc29f6ba241627f436ba3d05fc400d1066 Configuration: make sure the shared_sources table doesn't contain empty elements

1.1.0:
013aefc5f03c95f5366cc854ffb02b0df49af90d Configuration: make sure the shared_sources table doesn't contain empty elements

**Pull request closed without merging**
