### PR TITLE
md2: test doesn't require direct low level access

### PR DESCRIPTION
**Pull request by paulidale**
Low level access isn't required beyond the block size which remains available.

- [x] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Do we test md2 with evp_test? In that case, I see no use for this test program and would simply throw it away.

**Comment by romen** [comment]
Should we though have in place something that is testing that the _legacy_ low level API is still working? (I see this is not the case anymore for this PR, but I am just wondering about the risk of losing coverage on the ancient API)

**Comment by paulidale** [comment]
We don't seem to have any other MD2 tests.

This test is unchanged by the deprecation work -- i.e. the low level APIs were not tested previously.

**Comment by levitte** [comment]
My suggestion would be to copy the test vectors to the appropriate evp_test input file, and refractor this one into testing the low-level API. Otherwise, this program is just redundant cruft.

**Comment by paulidale** [comment]
I'm more inclined to copy the test cases to EVP and just remove this one.

**Comment by levitte** [comment]
Sure. After all, that should still test the low level stuff, just via EVP

**Comment by paulidale** [comment]
The low level calls will be as well tested as they were :)

I've pushed the changes.

**Comment by levitte** [comment]
Approval is, of course, as long as CIs agree

**Comment by paulidale** [comment]
CI failure was relevant.  Forgot to delete `05-test_md2.t`.  Scarily, most CIs passed with this omission.

**Comment by paulidale** [comment]
@levitte this will need a new approval -- the only change is the file deletion.

**Comment by levitte** [comment]
> Scarily, most CIs passed with this omission.

MD2 is disabled by default, isn't it? So of course, only the jobs that enable it explicitly will get failures...

**Comment by paulidale** [comment]
Merged to master with one end of line space removed.

**Pull request closed without merging**
