### PR TITLE
Avoid undefined behavior with unaligned accesses

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Fixes: #4983

[extended tests]

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

back-port of #6074 to 1.1.1

### CODE REVIEW

**Comment by romen** [comment]
> back-port of #6074 to 1.1.1

This is a bit misleading: #6074 was not merged, so this is not a backport.

Actually before approving this we need to approve and merge the same changes for `master`, and then we can backport this to `1.1.1`.

**Comment by bernd-edlinger** [comment]
Oh thanks!

**Comment by bernd-edlinger** [comment]
> Actually before approving this we need to approve and merge the same changes for master, and then we can backport this to 1.1.1.

When will you understand that this will never happen

**Comment by levitte** [comment]
> This is a bit misleading: #6074 was not merged, so this is not a backport.

One could argue that it's a backport of the PR, no matter if it has been merged or not. Let's not split hairs over choice of words, yeah? 

> Actually before approving this we need to approve and merge the same changes for master, and then we can backport this to 1.1.1.

We have plenty of previous examples where PRs for both branches have been active at the same time, and I don't really see a reason why they should be submitted in sequence. However, those approving can do so in the desired sequence.

**Comment by levitte** [comment]
I had a look at #6074, and while I see a lot of discussion that I haven't read through, I'm most concerned that it was *closed* without merging. I'm unclear on if it was seen as disapproved, but if that's the case, I can't stand for my approving this.

I'll have to read more when I'm more awake.

**Comment by bernd-edlinger** [comment]
Due to the discussion in #11596 I fixed also the unaligned accesses which
happen when enable-ec_nistp_64_gcc_128 is used.  I added this option to one
test case with ubsan to show this indeed fixes the issue.
```
diff --git a/.travis.yml b/.travis.yml
index 94b313a..6cf1ba0 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -134,7 +134,7 @@ matrix:
                   sources:
                       - ubuntu-toolchain-r-test
           compiler: gcc-5
-          env: UBUNTU_GCC_HACK="yes" EXTENDED_TEST="yes" CONFIG_OPTS="--debug no-asm enable-ubsan enable-rc5 enable-md2" OPENSSL_TEST_RAND_ORDER=0
+          env: UBUNTU_GCC_HACK="yes" EXTENDED_TEST="yes" CONFIG_OPTS="--debug no-asm enable-asan enable-ubsan enable-rc5 enable-md2 enable-ec_nistp_64_gcc_128" OPENSSL_TEST_RAND_ORDER=0
         - os: linux
           addons:
               apt:
diff --git a/crypto/ec/ecp_nistp224.c b/crypto/ec/ecp_nistp224.c
index 9a9ced8..6f7d66c 100644
--- a/crypto/ec/ecp_nistp224.c
+++ b/crypto/ec/ecp_nistp224.c
@@ -72,6 +72,7 @@ typedef uint64_t u64;
  */
 
 typedef uint64_t limb;
+typedef uint64_t limb_aX __attribute((__aligned__(1)));
 typedef uint128_t widelimb;
 
 typedef limb felem[4];
@@ -307,10 +308,10 @@ const EC_METHOD *EC_GFp_nistp224_method(void)
  */
 static void bin28_to_felem(felem out, const u8 in[28])
 {
-    out[0] = *((const uint64_t *)(in)) & 0x00ffffffffffffff;
-    out[1] = (*((const uint64_t *)(in + 7))) & 0x00ffffffffffffff;
-    out[2] = (*((const uint64_t *)(in + 14))) & 0x00ffffffffffffff;
-    out[3] = (*((const uint64_t *)(in+20))) >> 8;
+    out[0] = *((const limb *)(in)) & 0x00ffffffffffffff;
+    out[1] = (*((const limb_aX *)(in + 7))) & 0x00ffffffffffffff;
+    out[2] = (*((const limb_aX *)(in + 14))) & 0x00ffffffffffffff;
+    out[3] = (*((const limb_aX *)(in + 20))) >> 8;
 }
 
 static void felem_to_bin28(u8 out[28], const felem in)
diff --git a/crypto/ec/ecp_nistp521.c b/crypto/ec/ecp_nistp521.c
index 75eeba8..08b3278 100644
--- a/crypto/ec/ecp_nistp521.c
+++ b/crypto/ec/ecp_nistp521.c
@@ -128,6 +128,7 @@ static const felem_bytearray nistp521_curve_params[5] = {
 # define NLIMBS 9
 
 typedef uint64_t limb;
+typedef limb limb_aX __attribute((__aligned__(1)));
 typedef limb felem[NLIMBS];
 typedef uint128_t largefelem[NLIMBS];
 
@@ -141,14 +142,14 @@ static const limb bottom58bits = 0x3ffffffffffffff;
 static void bin66_to_felem(felem out, const u8 in[66])
 {
     out[0] = (*((limb *) & in[0])) & bottom58bits;
-    out[1] = (*((limb *) & in[7]) >> 2) & bottom58bits;
-    out[2] = (*((limb *) & in[14]) >> 4) & bottom58bits;
-    out[3] = (*((limb *) & in[21]) >> 6) & bottom58bits;
-    out[4] = (*((limb *) & in[29])) & bottom58bits;
-    out[5] = (*((limb *) & in[36]) >> 2) & bottom58bits;
-    out[6] = (*((limb *) & in[43]) >> 4) & bottom58bits;
-    out[7] = (*((limb *) & in[50]) >> 6) & bottom58bits;
-    out[8] = (*((limb *) & in[58])) & bottom57bits;
+    out[1] = (*((limb_aX *) & in[7]) >> 2) & bottom58bits;
+    out[2] = (*((limb_aX *) & in[14]) >> 4) & bottom58bits;
+    out[3] = (*((limb_aX *) & in[21]) >> 6) & bottom58bits;
+    out[4] = (*((limb_aX *) & in[29])) & bottom58bits;
+    out[5] = (*((limb_aX *) & in[36]) >> 2) & bottom58bits;
+    out[6] = (*((limb_aX *) & in[43]) >> 4) & bottom58bits;
+    out[7] = (*((limb_aX *) & in[50]) >> 6) & bottom58bits;
+    out[8] = (*((limb_aX *) & in[58])) & bottom57bits;
 }
 
 /*
@@ -159,14 +160,14 @@ static void felem_to_bin66(u8 out[66], const felem in)
 {
     memset(out, 0, 66);
     (*((limb *) & out[0])) = in[0];
-    (*((limb *) & out[7])) |= in[1] << 2;
-    (*((limb *) & out[14])) |= in[2] << 4;
-    (*((limb *) & out[21])) |= in[3] << 6;
-    (*((limb *) & out[29])) = in[4];
-    (*((limb *) & out[36])) |= in[5] << 2;
-    (*((limb *) & out[43])) |= in[6] << 4;
-    (*((limb *) & out[50])) |= in[7] << 6;
-    (*((limb *) & out[58])) = in[8];
+    (*((limb_aX *) & out[7])) |= in[1] << 2;
+    (*((limb_aX *) & out[14])) |= in[2] << 4;
+    (*((limb_aX *) & out[21])) |= in[3] << 6;
+    (*((limb_aX *) & out[29])) = in[4];
+    (*((limb_aX *) & out[36])) |= in[5] << 2;
+    (*((limb_aX *) & out[43])) |= in[6] << 4;
+    (*((limb_aX *) & out[50])) |= in[7] << 6;
+    (*((limb_aX *) & out[58])) = in[8];
 }
 
 /* BN_to_felem converts an OpenSSL BIGNUM into an felem */
```

**Comment by romen** [comment]
> We have plenty of previous examples where PRs for both branches have been active at the same time, and I don't really see a reason why they should be submitted in sequence. However, those approving can do so in the desired sequence.

@levitte 

- In this case we had an open PR for 1.1.1 with no open or merged PR on master.
- Opening the 2 PRs in parallel is fine, but extra care is required to avoid splitting the discussion in 2 threads.
- Not adhering to some order in this can lead to unnecessary differences in the diffs merged to different branches, or also the case where stuff is merged in a fix-only branch and not in the active branch.

**Comment by bernd-edlinger** [comment]
@romen so if you dont like this PR just go ahead and close it.

**Comment by romen** [comment]
I don't have a problem with this PR per se, other than we need to approve and merge the one on master first, and avoid to duplicate the conversation among the 2 PRs.

I put the hold label to prevent a merge as in the past not doing so led to merging to 1.1.1 before the changes were committed to master.

**Comment by bernd-edlinger** [comment]
I have been waiting way too long for my PRs to be approved for master.
Therefore I do not care any more for master.
Yes there are more than this PR alone, for 1.1.1 and with master version abandoned.
You can place Your HOLD on them as well if you like.
Whether or not You want my contributions for master I do not care.
I do not even care if any of my PRs do make it into the LTS branch,
or if you want to revert some of my PRs in the LTS branch.
Just go ahead and do so if You like.

**Comment by romen** [comment]
Thanks @bernd-edlinger for reopening and taking care once more of #6074 , even though it was left unattended for so long.

I am really sorry this happened, and I agree we should make it a project priority to find ways to address the bulk of pending PRs to check which ones are still relevant and to prevent this from happening again.

I believe @iamamoose efforts into bots and analytics are already a good start, but we need to do more.

**Comment by bernd-edlinger** [comment]
Merged to  OpenSSL_1_1_1-stable d03ffea
Thanks!

**Pull request closed without merging**
