### PR TITLE
Avoid leak in error path of asn1_parse2

### PR DESCRIPTION
**Pull request by kinichiro**

### CODE REVIEW

**Comment by mattcaswell** [comment]
Approved on the assumption that the CI passes.

**Comment by t8m** [comment]
I have now realized that the commit is with CLA:trivial. However I am not sure the patch is really trivial from the copyright perspective. It would be borderline case at least. @mattcaswell What do you think?
@kinichiro would it be possible for you to submit the ICLA?

**Comment by mattcaswell** [comment]
Border line I'd say. I'd prefer a CLA.

**Comment by kinichiro** [comment]
I think this fix is small and trivial.

**Comment by t8m** [comment]
It is small but it is questionable it is really trivial from the copyright perspective. The CLA:trivial is reserved for things like typo changes or other really small changes that cannot be reasonably implemented differently. In this case this bug fix definitely could be implemented differently.

**Comment by kinichiro** [comment]
I would not like to submit that.
I just wanted to report this for the better.
Shall I close this PR ?
Then you can fix this by yourself.

**Comment by mspncp** [comment]
@kinichiro thank you very much for your contributions, we appreciate them very much!

Please understand that our policy requires that we can only accept changes covered by a [Contributor License Agreement](https://www.openssl.org/policies/cla.html). There are exceptions for contributions, which are trivial in a legal sense, but since we are not lawyers, we set the bar very low: only corrections of typographical or grammatical errors or whitespace changes are considered trivial, sometimes also simple one-line fixes. A [blog post](https://www.openssl.org/blog/blog/2015/08/01/cla) from 2015 explains the reasoning behind our licensing policy.

> I would not like to submit that.

Could you please explain the reason why you prefer not to submit a CLA?

> I just wanted to report this for the better.
> Shall I close this PR ?

It would be a pity if you would close this PR and stop submitting more improvements. I hope you change your mind and submit a CLA, we are looking forward to your future contributions!

Regards,
Matthias

**Comment by t8m** [comment]
Without the rename of the variable names it could be acceptable as trivial.

**Comment by t8m** [comment]
On the other hand at least one of the variables would have to be renamed anyway.

**Comment by t8m** [comment]
Merged to master as 6a165fab23
Merged to 1.1.1 as 902a97b586

**Pull request closed without merging**
