### PR TITLE
Note that EVP_CIPHER_get_iv_length returns negative values on error

### PR DESCRIPTION
**Pull request by paulidale**
- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Please note that the function is called EVP_CIPHER_CTX_iv_length on 1.1.1. So the commit message is slightly confusing. Can be amended when merging.

**Comment by paulidale** [comment]
Updated the commit message.  No other changes, I'll assume approvals stand.

**Comment by hlandau** [comment]
Merged to 1.1.1. Thank you.

**Pull request closed without merging**
