### PR TITLE
Fix build on OS X

### PR DESCRIPTION
**Pull request by ghedo**
Not sure if this is going to work though....

### CODE REVIEW

**Comment by ghedo** [comment]
Looks good so far:
https://travis-ci.org/openssl/openssl/builds/79096023

I think this can be merged now.

**Comment by ghedo** [comment]
Test build complete, everything gseems to work ok:
https://travis-ci.org/openssl/openssl/builds/79096186

**Comment by richsalz** [comment]
did this and a bunch of return-value fixes as well.  thanks.

**Comment by ghedo** [comment]
Um, you haven't actually merged my patch
https://github.com/openssl/openssl/blob/master/apps/rehash.c#L63

and the OS X builds are still failing
https://travis-ci.org/openssl/openssl/jobs/79166213#L1923

**Pull request closed without merging**
