### PR TITLE
AES CTR-DRGB: do not leak timing information

### PR DESCRIPTION
**Pull request by p-steuer**
10.2.1.1 CTR_DRBG Internal State, NIST SP 800-90A Rev. 1 :
> The values of V and Key are the critical values of the internal state upon which the security of this DRBG mechanism depends (i.e., V and Key are the “secret values” of the internal state). 

So better not leak any timing information when incrementing V.

### CODE REVIEW

**Comment by slontis** [comment]
travis is not your friend :)

**Comment by p-steuer** [comment]
missing include. build error should be fixed now.

**Comment by p-steuer** [comment]
travis evp test fails probably not related to this PR

**Comment by slontis** [comment]
Kicking off the builds again..

**Comment by p-steuer** [comment]
travis red cross seems to be due to a time out

**Comment by slontis** [comment]
Travis failure is just a timeout..

**Comment by p-steuer** [comment]
Is this wanted for 1.1.1 ?

**Comment by romen** [comment]
My approval does not count toward the threshold in this case, but personally I believe this fixes a minor potential vulnerability, so it would meet the requirements for 1.1.1 backporting.

If @paulidale agrees I would even think there is no need to restart the grace time counter on this.

**Comment by t8m** [comment]
Travis failure is just an unrelated timeout.

**Comment by paulidale** [comment]
For both branches too.

**Comment by paulidale** [comment]
Merged to master and 1.1.1.  Apologies for letting this one slip through.

**Comment by zz85** [comment]
this seems to be failing builds on Ubuntu (See #11487)

**Pull request closed without merging**
