### PR TITLE
Configuration: stop defaulting to use `-Wall` in CFLAGS

### PR DESCRIPTION
**Pull request by levitte**
From a practical point of view, it means that when `--strict-warnings`
is used, any modifications such as disabling certain warnings become
useless, because the CFLAGS settings come after.  By consequence, this
too forces us to use DEFINE macros from safestack.h and others in
header files only.

### CODE REVIEW

**Comment by levitte** [comment]
I'm carefully making this master only.

**Comment by paulidale** [comment]
I'm far less keen on disabling `-Wall`.  It feels worse than having the definitions in headers.

**Comment by romen** [comment]
Don't know much about compiler flags, and how portable they are across compilers/platforms, but if the main problem is due to "unused function" warnings coming from the expansion of DECLARE_* macros, could we just fix this by annotating the function definitions in the macro with something like `__unused__`?

https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes

**Comment by levitte** [comment]
Okie.  I'm pretty sure the situation will bite us in the behind again, 'cause what this means is that any fine tuning we do with the `--strict-warnings` flags is rendered useless by our defaults...  but fine.  In that case, though, #8234 should be reverted.

**Comment by levitte** [comment]
Oh wait, I have another option, which is obvious when I think of it...

**Comment by paulidale** [comment]
The unused attribute should work on all of the platforms that are hurting at the moment.
Putting the definitions in their own header that is absent anything else might be okay too.

**Comment by paulidale** [comment]
Agree, revert #8234

**Comment by levitte** [comment]
Nah. The idea I have in mind is to treat `--strict-warnings` like any other user provided C / C++ flag. That will take care if the order problem, as user provided flags are placed later. Also, that makes more sense, since `--strict-warnings` *is*, in fact, a user provided option.

I'm currently out and about, but will get back on that later today.

**Comment by levitte** [comment]
Closed in favor of #8239

**Pull request closed without merging**
