### PR TITLE
Update b_sock.c

### PR DESCRIPTION
**Pull request by rvdn**
Replace gethostname by getaddrinfo

### CODE REVIEW

**Comment by richsalz** [comment]
well.... maybe.  not all our supported platforms have getaddrinfo.

**Comment by Xe** [comment]
Which platforms are those?

**Comment by richsalz** [comment]
VMS.  Netware.  Probably others.  Others are working on full IPv6 support, and at that point getaddrinfo or its equivalent will need to be used.  Until that's done, there doesn't seem a real need to do this.

**Comment by Xe** [comment]
Is there really a need to support such ancient platforms?

**Comment by richsalz** [comment]
Yes.

**Comment by levitte** [comment]
Current VMS (*) does have getaddrinfo.

(* VMS is still a current operating system, and I'll maintain that it's less ancient than Unix ;-) )

**Comment by richsalz** [comment]
good to know.  for whoever is doing the ipv6 work.  which isn't me. :)

**Comment by h-yamamo** [comment]
This patch occures memory leak.
See man 3 getaddrinfo.
Caller of this function CANNOT free memory by freeaddrinfo().

**Pull request closed without merging**
