### PR TITLE
Fix propotype to include the const qualifier

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by mspncp** [comment]
Just for curiosity: fixes for const-correctness are not considered an API change?  (I know things are different between C and C++, because the former has no name mangling).

**Comment by mspncp** [comment]
It might force people to rewrite their code, though. So is it really allowed to backport this fix?

**Comment by FdaSilvaYY** [comment]
This point has been discussed and resolved few months ago :
In short, C standard guarantee that it is ABI compatible ...

**Comment by kroeckx** [comment]
And this is really just a documentation change, it's already const in 1.0.2

**Comment by richsalz** [comment]
Adding const is okay, removing it is not.

**Comment by levitte** [comment]
It doesn't break compatibility. That's at least my reasoning.

**Pull request closed without merging**
