### PR TITLE
fix typo in x509 documentation

### PR DESCRIPTION
**Pull request by iluxonchik**
##### Checklist
- [x] documentation is added or updated

### CODE REVIEW

**Comment by iluxonchik** [comment]
@richsalz sure. To which e-mail should I send the CLA to?

**Comment by richsalz** [comment]
Get them here: https://www.openssl.org/policies/cla.html and the CLA says to mail to legal@opensslfoundation.org  thank you.

**Comment by iluxonchik** [comment]
@richsalz oh, you're right.

CLA sent. Please, check your spam folder, as it might be marked as such.

**Comment by richsalz** [comment]
close/open to kick the CLA bot.

**Comment by richsalz** [comment]
Merged to master, thanks!

**Comment by iluxonchik** [comment]
@richsalz you're welcome :)

**Pull request closed without merging**
