### PR TITLE
Remove debugging prints from util/add-depends.pl

### PR DESCRIPTION
**Pull request by levitte**
Oops...

### CODE REVIEW

**Comment by dot-asm** [comment]
It also leaves Makefile.$$ behind.

**Comment by richsalz** [comment]
"rm Makefile.$$" if 1;
 approved.

**Comment by dot-asm** [comment]
As it stands now one can execute nmake on Windows only once. After that it's syntax error about colon being unexpected. This is because compiler warnings are blended in...

**Comment by levitte** [comment]
> As it stands now one can execute nmake on Windows only once. After that it's syntax error about colon being unexpected. This is because compiler warnings are blended in...

...  I don't understand how that happens.  Lines that do not start with `Note: including file:` should be discarded (`$line = undef`) ...

**Comment by levitte** [comment]
I think I've fixed the stray temp Makefile.$$ issue

**Review by dot-asm — APPROVED** [review]
Let's resolve remaining Windows issues in #5591.

**Comment by levitte** [comment]
Good idea.

Merged.  4ba5ce651790264cdd0e1af3564cf68f8be9ac81 to d3313a1f4cc6cb641c3bb68fd40625c118a4b7b7

**Pull request closed without merging**
