### PR TITLE
WIP: Lhash optional statistics collection.

### PR DESCRIPTION
**Pull request by paulidale**
- [x] documentation is added or updated
- [x] tests are added or updated

This PR makes the statistics collection in the lhash object optional and disabled by default.
This means zero locking overhead unless the gathering is enabled.

This depends on #4418 for the locking changes to the lhash object.  Only the final commit is relevant and this will be squashed before merge.

This is an API breaking change in the sense that the statistics functions `OPENSSL_LH_stats` and `OPENSSL_LH_stats_bio` will not function properly without adding an enable call.  The other stats calls still work.

### CODE REVIEW

**Comment by paulidale** [comment]
This is WIP until #4418 is resolved.

**Comment by dot-asm** [comment]
> This is WIP

You can edit subject to denote it as such :-) And apparently I can do it for you. I mean I wanted to test and it worked and I decided to leave it like that...

**Comment by paulidale** [comment]
Thanks.

**Comment by paulidale** [comment]
This PR is unnecessary in light of #4429

**Pull request closed without merging**
