### PR TITLE
Configurations/descrip.mms.tmpl: Fix small errors

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
There was more, so you need to reconfirm...

**Comment by levitte** [comment]
.. and argh, there seems to be more, so I've marked this WIP

**Comment by levitte** [comment]
Ok, it seems I found them all.  Please review once more.

**Comment by levitte** [comment]
(and even taken out of WIP now ;-) )

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
Merged.  5de20b26e5a1ac3f42c5c3e8ce0a3e6c427d10c7

Thank you :-)

**Pull request closed without merging**
