### PR TITLE
Revert "(Temporarily) don't download clang package"

### PR DESCRIPTION
**Pull request by richsalz**
This reverts commit a15cfae6561e9f68e6fd505f718e04fd9adae86a.
Restore CLANG to Travis.
We'll just watch this CR until it goes green.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Probably you will need to rebase every now and then. It won't go green without a new push (CI only gets run when there is a new push I think).

**Comment by richsalz** [comment]
Yes, that’s my plan.  Every day or so rebase and push.

**Comment by ekasper** [comment]
llvm apt is back! But I'm confused about this PR - it doesn't do what it says?

**Comment by richsalz** [comment]
No, it doesn't  I gave up waiting and was trying the various work-arounds mentioned in Travis build logs.  I will close this and submit a new PR to revert the change.  Or, better, if you want to you have a plus-one from me. :)

**Pull request closed without merging**
