### PR TITLE
Ensure text mode file BIOs are buffered on Windows

### PR DESCRIPTION
**Pull request by joshcooper**
Commit 8300a8742b2abc487594a09b5e6ee726dbd30771 disabled file buffering for text mode file BIOs on Windows to work around a bug in UCRT ftell. This is surprising to applications that expect BIO read/writes to be buffered, such as when reading cert.pem.

This wraps text mode file BIOs with a buffered BIO, so the overall result is buffered (just once).

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
Would it be possible to add some kind of test? (I assume there isn't a test or this would have been detected before now?)

**Comment by t8m** [comment]
I do not think this is a good idea. This is going to surprisingly return a BIO chain instead of a single BIO on one platform and that means to free it you'd have to use BIO_free_all() instead of BIO_free(). This is an API change.

**Comment by joshcooper** [comment]
@t8m ah sorry, I thought `BIO_free` behaved like `BIO_free_all`.

Would it make sense to instead create macros to wrap `BIO_new_file` and `BIO_free` like:

```c
#if defined(OPENSSL_SYS_WINDOWS)
#define BIO_NEW_TEXT_FILE(f,m) BIO_push(BIO_new(BIO_f_buffer()), BIO_new_file((f), (m))
#define BIO_FREE_TEXT_FILE(b) BIO_free_all(b)
#else
#define BIO_NEW_TEXT_FILE(f,m) BIO_new_file((f), (m))
#define BIO_FREE_TEXT_FILE(b) BIO_free(b)
#endif
```

And then update the places where openssl creates file BIOs in text mode?

```
$ git grep 'BIO_new_file(.*"r")' crypto providers
crypto/conf/conf_def.c:    in = BIO_new_file(name, "r");
crypto/conf/conf_def.c:                next = BIO_new_file(include_path, "r");
crypto/conf/conf_def.c:    next = BIO_new_file(include, "r");
crypto/conf/conf_def.c:            bio = BIO_new_file(newpath, "r");
crypto/conf/conf_lib.c:    in = BIO_new_file(file, "r");
crypto/engine/eng_openssl.c:    in = BIO_new_file(key_id, "r");
crypto/ts/ts_conf.c:    if ((cert = BIO_new_file(file, "r")) == NULL)
crypto/ts/ts_conf.c:    if ((certs = BIO_new_file(file, "r")) == NULL)
crypto/ts/ts_conf.c:    if ((key = BIO_new_file(file, "r")) == NULL)
crypto/x509/by_file.c:    in = BIO_new_file(file, "r");
crypto/x509/v3_pci.c:            BIO *b = BIO_new_file(valp, "r");
```

For example in [by_file.c](https://github.com/openssl/openssl/blob/c81b7b059f614a6c43ad6a6907b1a740b783fbfd/crypto/x509/by_file.c#L231-L237):

```diff
-   in = BIO_new_file(file, "r");
+   in = BIO_NEW_TEXT_FILE(file, "r");
    if (in == NULL) {
        ERR_raise(ERR_LIB_X509, ERR_R_BIO_LIB);
        return 0;
    }
    inf = PEM_X509_INFO_read_bio_ex(in, NULL, NULL, "", libctx, propq);
-   BIO_free(in);
+   BIO_FREE_TEXT_FILE(in);
```

**Comment by t8m** [comment]
I would like to know what problem is this trying to solve. Does it matter if reading certificates/keys is not buffered? These data files aren't large.

**Comment by joshcooper** [comment]
Sure, the problem is our application takes more than 10% longer to start up using openssl 3.0 due to 116k calls to `ReadFile`, each one of which reads 2 bytes from `cert.pem`. Details are in https://github.com/puppetlabs/puppet-runtime/issues/786

**Comment by davidben** [comment]
I might suggest that OpenSSL consider just open everything internally in binary mode. The PEM parser already handles CRLF itself and this helps avoid platform differences in processing the same bytes. The ftell bug is then moot in those cases.

That doesn't account for the cases where OpenSSL takes a FILE* from the caller. But in those cases, the caller presumably is just expecting OpenSSL to call the libc functions on that FILE, platform warts and all. I.e. I think you can just assume the caller either doesn't care about ftell (most likely) or has applied a suitable workaround on their end.

Put those together and I would suggest reverting the ftell workaround and leaving it to the call sites to apply, seeing as the workaround has significant perf costs.

**Comment by t8m** [comment]
> I might suggest that OpenSSL consider just open those cases internally in binary mode. The PEM parser already handles CRLF itself and this helps avoid platform differences in processing the same bytes. The ftell bug is then moot in those cases.

Yeah, that would make sense.

**Comment by nhorman** [comment]
@joshcooper are you able.to sign a cla on this so it can be reviewed and merged?

**Comment by joshcooper** [comment]
Thanks for the ping. I signed the CLA and wanted to close and reopen the PR but I don't seem to have permission for the latter. Since this PR needs work, I'll just submit a new one later.

**Comment by nhorman** [comment]
Don't quite understand whats going on, but your change seems to have broken several windows tests

**Comment by t8m** [comment]
@joshcooper Also you're saying that you have the problem with openssl-3.0. Could you please try openssl-3.3? There are several other improvements that could help fixing the performance issue for you.

**Comment by davidben** [comment]
@t8m are you referring to the various mitigations/workarounds for the provider system? Those seem unrelated to this PR, which is about a performance regression in file I/O caused by 8300a8742b2abc487594a09b5e6ee726dbd30771.

Also see https://github.com/openssl/openssl/pull/24249#issuecomment-2077482502. I don't think making Windows `BIO`s even more weird is the right solution to a regression caused by making Windows `BIO`s weird and not actually return the same `BIO` type. Rather, OpenSSL should:

1. Open PEM files, etc., in binary mode, not text mode. The PEM parser, for instance, handles CRLF just fine.
2. Revert 8300a8742b2abc487594a09b5e6ee726dbd30771 as the cure is worse than the disease. In the very rare instances where the application wants `ftell` and text mode, the application can apply the workaround themselves. After all, that is what it would do if it were just using `FILE` directly. In the vast, vast majority of cases where the application isn't using `ftell`, it does not make sense to completely change the performance properties of a file `BIO`.

Indeed, this PR itself breaks `BIO_C_FILE_TELL` anyway! It causes file `BIO`s to secretly be buffer `BIO`s and buffer `BIO`s  do not internally adjust `BIO_C_FILE_TELL` by the buffer amount.

**Comment by t8m** [comment]
@davidben I am just saying some of the performance penalties that they can see with 3.0 could be gained back by performance improvements in other areas in the 3.3 version.

Otherwise yeah, I agree with your proposal to fix this particular regression.

**Comment by t8m** [comment]
@joshcooper Will you open a new PR implementing what @davidben suggests above?

**Comment by joshcooper** [comment]
@t8m sure, I will submit a PR with the changes proposed by @davidben Feel free to close this one.

**Comment by nhorman** [comment]
as requested, closing in favor of a new PR

**Pull request closed without merging**
