### PR TITLE
DSA/RSA_print(): Fix potential memory leak

### LINKED ISSUE #10777: Potential memory leak in DSA_print and DSAparams_print
In the DSA_print and DSAparams_print functions, the pk error handling might be improved.
Instead of 
```
    pk = EVP_PKEY_new();
    if (pk == NULL || !EVP_PKEY_set1_DSA(pk, (DSA *)x))
        return 0;
```
replace by
```
    pk = EVP_PKEY_new();
    if (pk == NULL) return 0;
    if  (!EVP_PKEY_set1_DSA(pk, (DSA *)x)) {
        EVP_PKEY_free(pk);
        return 0;
    }
```
Is it correct ?
Thanks

### PR DESCRIPTION
**Pull request by t8m**
Fixes #10777

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Good for 1.1.1 and master.

**Review by slontis — COMMENTED** [review]
The changes are fine.
Should we be doing fixes in master for deprecated functions?

**Comment by t-j-h** [comment]
> Should we be doing fixes in master for deprecated functions?

Yes - it is simply deprecated - not actually removed.

**Comment by t8m** [comment]
Merged to master and 1.1.1 branches. Thank you for the review.

**Pull request closed without merging**
