### PR TITLE
`check-format.pl`: three fixes on false positives and statistics

### PR DESCRIPTION
**Pull request by DDvO**
* fix detection of function body start
* detection of `#ifdef __cplusplus` used in header files
* fix statistics on whitespace and nesting issues

### CODE REVIEW

**Comment by DDvO** [comment]
These are just a couple of small changes.
They prevent many false positives on headers in `include/openssl/`.
So would be good to get them approved soon.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
Ping for 2nd review/approval

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master branch. It did not cherry-pick cleanly to 3.1 branch. I assume some of the recent check-format changes were not merged there. @DDvO can you please either submit a separate PR for this on 3.1 branch or a PR that would contain the missing cherry-picks.

I'll keep this open for now.

**Comment by DDvO** [comment]
> Merged to master branch. It did not cherry-pick cleanly to 3.1 branch. I assume some of the recent check-format changes were not merged there. @DDvO can you please either submit a separate PR for this on 3.1 branch or a PR that would contain the missing cherry-picks.
> 
> I'll keep this open for now.

Thank you. I've meanwhile implemented the latter option, in #20254.

**Pull request closed without merging**
