### PR TITLE
Clear CRMF vs CMP confusion

### PR DESCRIPTION
**Pull request by levitte**
In the development of the CRMF sub-system, it was decided that
'no-crmf' would be the configuration option to disable it.  However,
some of the C macro guards were using OPENSSL_NO_CMP rather than
OPENSSL_NO_CRMF...

### CODE REVIEW

**Comment by DDvO** [comment]
We originally had NO_CRMF and NO_CMP, but some reviewer of CMP chunk 1 or 2 did not want to have that many NO_... options and requested to change this such that CRMF is disabled whenever CMP is disabled.
We tried to implement this in CMP chunk 3 #8669, but as discussed there it looks like we used an unsuitable mechanism in `Configure`, and moreover it seems to me that `mkerr.pl` should respect `@disable_cascades`. See https://github.com/openssl/openssl/pull/8669#pullrequestreview-233986531 for details.

**Comment by levitte** [comment]
`@disable_cascades` does not matter in this case, there really is no disabling of `cmp` anywhere.

**Comment by mattcaswell** [comment]
So shouldn't everything just be no-cmp?

**Comment by DDvO** [comment]
Yes, this was at least was the idea so far.
Yet it seems `mkerr.pl` does not directly support the dependency of a sub-lib like CRMF on some other  like CMP? Or can this be handled in conjunction with some other setting than we tried so far?

**Comment by levitte** [comment]
Simple:

``` diff
diff --git a/Configure b/Configure
index 701368d5c6..87bcb7332c 100755
--- a/Configure
+++ b/Configure
@@ -345,9 +345,9 @@ my @disablables = (
     "cast",
     "chacha",
     "cmac",
+    "cmp",
     "cms",
     "comp",
-    "crmf",
     "crypto-mdebug",
     "crypto-mdebug-backtrace",
     "ct",
```

That is, after all, what you're all hinting at, that there should be a `no-cmp` rather than a `no-crmf`?

**Comment by levitte** [comment]
... although, the CRMF implementation is quite messy.  API-wise, a lot of it works with the thought that the API name is the same, making a configuration option `no-xxx` match `XXXerr`, `XXX_F_*`, `XXX_R_*`...  that's the assumption that `mkerr.pl` works with.

So it seems to me like we will have to have both `no-cms` and `no-crmf` and have the latter depend on the former.

**Comment by DDvO** [comment]
@levitte, listing "cmp" but not "crmf" in `@disablables` is exactly what we currently have in chunk 3 - 
see https://github.com/openssl/openssl/pull/8669/files

Yet, as mentioned, this does not suffice: `mkerr.pl` does not know that it should disable the CRMF string function when NO_CMP is set, because all it can check these days is NO_CRMF, despite the dependency between the two sub-libs declared (in one way or the other) in `Configure`.

**Comment by DDvO** [comment]
For some reason, the your comments as I see them in this thread are not chronological...

**Comment by levitte** [comment]
> For some reason, our comments as I see them in this thread are not chronological...

Yup, I noticed that too.  It seems to be a general github problem, I noticed the same thing in the comment stream in a different PR

**Comment by richsalz** [comment]
> So it seems to me like we will have to have both `no-cms` and `no-crmf` and have the latter depend on the former.

Or you teach mkerr about aliases, and where it would use NO_CRMF it should use NO_CMS.
This makes the internal tool a little uglier, but makes the code and user conceptual burden cleaner and smaller which seems like the right trade-off.

**Comment by mattcaswell** [comment]
> Or you teach mkerr about aliases, and where it would use NO_CRMF it should use NO_CMS.
This makes the internal tool a little uglier, but makes the code and user conceptual burden cleaner and smaller which seems like the right trade-off.

Right. I'm not a fan of introducing multiple options where one will do. We should just be able to do "no-cmp" and have crmf disabled automatically.

**Comment by levitte** [comment]
Aliases have ramifications. What do you grep for? What do you write in `crypto/err/openssl.ec`? What do you write in `opensslconf.h`? Or are you basically asking for another array like `@disablables`, but that holds "options" that aren't really that, just a placeholder for perusal of any script that finds an interest?

**Comment by richsalz** [comment]
Leaving the design to you, but my thought was add this near the beginning:
```
my %aliased = { 'CMRF' : 'CMP' };
```
And then replace
```
            print OUT <<"EOF";
# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_${lib}

EOF
```
with this:
```
            my $aliased = $aliased{$lib} || $lib;
print OUT <<"EOF";
# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_${aliased}

EOF
```

I am sure there is a more pearl-purist way to do this.

**Comment by levitte** [comment]
OK. So what I'm wondering is, will `cmp` eventually be "alias" for more than just `crmf`? Also, I will have you notice that `@disable_cascades` is essentially already an aliasing mechanism, except it allows a one-to-many model. I really see no need to make *another* mechanism that provides the same thing. 

But yeah, I understand that there may be reasons to ensure mkerr knows about the aliases. Them simpler way is another list like `@disablables`, that is inaccessible to the user, but provides the necessary information...

**Comment by richsalz** [comment]
My philosophy is do the simple fix now; predicting the future is hard and often wrong.

**Comment by levitte** [comment]
I just did the simple fix

**Comment by DDvO** [comment]
@levitte, at least in my perspective your simple fix is sufficient (at least for the dependency of CMP on CRMF).

Can this be merged soon? 
This appears to block #8669 (i.e., chunk 3 of the CMP contribution).

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

538f38db50e4ead178025689d28bda316b15c242 Clear CRMF vs CMP confusion

**Pull request closed without merging**
