### PR TITLE
Fix inconsistent doc of `CMS_verify` and `PKCS7_verify` etc. - backporting #18915

### PR DESCRIPTION
**Pull request by DDvO**
This is a copy of the doc changes in #18915 for backporting to 3.0 and 1.1.1, as discussed [there](https://github.com/openssl/openssl/pull/18915#issuecomment-1232696066).

### CODE REVIEW

**Comment by DDvO** [comment]
@t8m since you [wrote](https://github.com/openssl/openssl/pull/18915#issuecomment-1232541220) that `missingcrypto111.txt` should not be touched even when doc of 1.1.1. is extended (as done here), I wonder what this file is good for?

**Comment by t8m** [comment]
> @t8m since you [wrote](https://github.com/openssl/openssl/pull/18915#issuecomment-1232541220) that `missingcrypto111.txt` should not be touched even when doc of 1.1.1. is extended (as done here), I wonder what this file is good for?

It's there basically to compare what documentation we added after 1.1.1. Not sure if the file should be kept forever in the tree.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
@paulidale can you please give the 2nd approval here (for 3.0 and 1.1.1), too.

**Comment by DDvO** [comment]
Ping for 2nd review

**Comment by DDvO** [comment]
Being a copy of #18915, it's a very low-hanging fruit 😉 :

**Comment by DDvO** [comment]
@paulidale, can you give the 2nd approval on this backport?
Should be a no-brainer as you already approved the original PR.

**Review by paulidale — APPROVED** [review]

**Comment by DDvO** [comment]
Merged to 3.0 and 1.1.1, fixing merge conflicts in the `.pod` files.
Thanks @t8m and @paulidale for the reviews.

**Pull request closed without merging**
