### PR TITLE
s390x assembly pack: import chacha from cryptogams repo

### PR DESCRIPTION
**Pull request by p-steuer**
Import chacha from @dot-asm's cryptogams repo featuring 6x"horizontal" code path which is up to 25% faster than present 4x"vertical" for larger blocks.

### CODE REVIEW

**Comment by levitte** [comment]
I just ran a test.

Speed measurement before this patch:

```
> ./util/shlib_wrap.sh apps/openssl speed -evp chacha20
Doing chacha20 for 3s on 16 size blocks: 18901265 chacha20's in 2.96s
Doing chacha20 for 3s on 64 size blocks: 17021915 chacha20's in 2.96s
Doing chacha20 for 3s on 256 size blocks: 13307710 chacha20's in 2.95s
Doing chacha20 for 3s on 1024 size blocks: 3834257 chacha20's in 2.90s
Doing chacha20 for 3s on 8192 size blocks: 499396 chacha20's in 2.88s
Doing chacha20 for 3s on 16384 size blocks: 257033 chacha20's in 2.97s
version: 3.0.0-dev
built on: built on: Mon Mar  4 07:40:18 2019 UTC
options:bn(64,64) rc4(8x,char) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DOPENSSL_USE_NODELETE -DB_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DAES_ASM -DAES_CTR_ASM -DAES_XTS_ASM -DGHASH_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
chacha20        102169.00k   368041.41k  1154838.56k  1353889.37k  1420504.18k  1417922.11k
```

speed measurement after:

```
> ./util/shlib_wrap.sh apps/openssl speed -evp chacha20
Doing chacha20 for 3s on 16 size blocks: 19001493 chacha20's in 2.97s
Doing chacha20 for 3s on 64 size blocks: 17029397 chacha20's in 2.98s
Doing chacha20 for 3s on 256 size blocks: 13486045 chacha20's in 2.94s
Doing chacha20 for 3s on 1024 size blocks: 4308046 chacha20's in 2.99s
Doing chacha20 for 3s on 8192 size blocks: 624128 chacha20's in 2.98s
Doing chacha20 for 3s on 16384 size blocks: 320012 chacha20's in 2.95s
version: 3.0.0-dev
built on: built on: Mon Mar  4 07:40:18 2019 UTC
options:bn(64,64) rc4(8x,char) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DOPENSSL_USE_NODELETE -DB_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DAES_ASM -DAES_CTR_ASM -DAES_XTS_ASM -DGHASH_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
chacha20        102364.95k   365732.02k  1174295.07k  1475397.69k  1715723.68k  1777314.10k
```

**Comment by mattcaswell** [comment]
Ummm....a licence question. Cryptogams has a different licence to OpenSSL. Normally this isn't a problem since Andy, as the copyright owner, submits to both projects. But I wonder why that hasn't happened here? Obviously we have a CLA from Andy, but it only applies to work that he submits. I don't think we can just import other stuff without his explicit approval.

**Comment by p-steuer** [comment]
Andy said its okay for me to contribute the code. From a licence perspective, i thought it was enough that the corresponding module is already under cryptogams. But i see its about putting it under a second licence, that is openssls.

**Comment by mattcaswell** [comment]
> Andy said its okay for me to contribute the code. 

If Andy can explicitly confirm that here then that would be enough I think.

**Comment by dot-asm** [comment]
Code is written to be used, not executing it denies the original purpose and on certain level effectively destroys it, which is formally a bad thing. Public reference to me by the alias (not regular name, because I get notifications only if mentioned by alias) is sufficient. Best straight in initial comment, just as in this case. If it makes you feel better, reserve some time for opportunity to object. Formally speaking it can only be about objection, as all agreements are already in place. And if somebody you already know says they talked to me, there is no reason to believe that they didn't.

**Comment by mattcaswell** [comment]
I interpret the above as confirmation that you're ok with this. Thanks!

> Formally speaking it can only be about objection, as all agreements are already in place.

There is no agreement in place which allows us to take code from the Cryptogams repository and re-license it for use in OpenSSL without your explicit consent. The CLA you have with the project only covers your submissions to the project, not code that you might have written but did not submit. If you think about it that's only right and fair (just because someone signs a CLA with us doesn't mean we have the right to take and re-license anything unrelated that they then produce and don't send to us).

**Comment by levitte** [comment]
Merged.

d1229190bfbb19439589557e4d65f9bccab09b2d s390x assembly pack: import chacha from cryptogams repo

**Pull request closed without merging**
