### PR TITLE
Revert SSL verification callback retry patch

### LINKED ISSUE #17568: `SSL_CTX_set_cert_verify_callback(3)` semantic change
IMNSHO the mechanism chosen to signal this is rather an unfortunate incompatibility with OpenSSL 1.x.  Previously negative return values from the application verificcation callback (i.e. set via `SSL_CTX_set_cert_verify_callback(3)`) had no special semantics, but were typically indications of an internal error performing the verification, rather than a *normal* verification failure.

A typical application callback would manipulate the X509_STORE_CTX object and then just tail-call the standard `X509_verify_cert(3)`, whose return value was expected to be compatible for use as application callback.

Now there appears to a special case where -1 is special when returned by an application callback, but not by the built-in verification code.  This is pretty bad, and breaks existing code.

I think this design decision needs to be reconsidered.

_Originally posted by @vdukhovni in https://github.com/openssl/openssl/issues/13906#issuecomment-1019343986_

### PR DESCRIPTION
**Pull request by hlandau**
This reverts commit 0c3eb2793b2a1fe35beeb90ba8f5cb2a0fdc3270.

Fixes #17568.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Note that the OTC decision in #17568 says "The https://github.com/openssl/openssl/pull/13906 should be reverted on both 3.0 and master branches and alternative mechanism should be provided". Reverting is the easy bit - the harder bit is the alternative mechanism.

**Comment by hlandau** [comment]
Probably that will need to be a separate PR, and a decision on what the alternative mechanism should be will need to be reached.

**Comment by mattcaswell** [comment]
I wouldn't recommend we do the revert until we've figured out the alternative. There is a discussion on some alternative mechanisms in #17568. I think we just need to pick one and run with it.

**Comment by t-j-h** [comment]
The decision was *revert* and make an alternative - it was not *revert-only-when-we-have-an-alternative*. Keeping something around that we have decided needs to go seems a little strange when we didn't form it as a conditional on decision and the revert is logically separate work.

**Comment by mattcaswell** [comment]
The "and" is atomic IMO. We should *not* be doing one without the other, and I do not believe that was the intent of the OTC decision. They *could* be in separate PRs (I have no objection to that) but I do not think it is wise to merge until both are ready. At least for the 3.0 branch. I am less concerned about master, but it is probably sensible to keep them in sync.

**Comment by t-j-h** [comment]
It was not formulated to be conditional. The discussion was clear within the OTC that we didn't have agreement on what should replace it but we did have agreement that this must go. There was no linking of the two needing to happen at the same time. What is there we all agreed needs to come out. So it should be taken out. What the replacement should be is subject to a separate review than the revert. And it should explicitly not be tied. 

If you want to put an OTC hold on this then do so and we can again have the same discussion and see if views have changed. But the OTC decision in plain terms does not make it conditional.

When we want to link PRs together (and we do that occasionally) we do that explicitly and that is not what happened here.

**Comment by mattcaswell** [comment]
> It was not formulated to be conditional.

Implementing just the revert only implements half the decision. That isn't what I thought we were deciding in the OTC and my opinions would have been different it if was. OTC hold applied.

**Comment by t8m** [comment]
I also understood the OTC discussion as that we should do both at once or in sequence such that we do not release a 3.0.x version where the old mechanism is reverted but no replacement is present. So I support matt's hold.

**Review by DDvO — CHANGES_REQUESTED** [review]
I oppose this PR, as it simply removes the feature without providing a better solution.
This also has been stated by others earlier today.
If you really want to contribute something here, you need to improve the existing solution.

I suggest closing this PR, as it is thoughtlessly destructive.

**Comment by hlandau** [comment]
Superceded by #17825.

**Pull request closed without merging**
