### PR TITLE
Fix freshly introduced double-free.

### PR DESCRIPTION
**Pull request by vdukhovni**
We don't need the decoded X.509 Full(0) certificate for the EE usages 1 and 3, because the leaf certificate is always part of the presented chain, so the certificate is only validated as well-formed, and then discarded, but the TLSA record is of course still used after the validation step.

Added DANE test cases for: 3 0 0, 3 1 0, 1 0 0, and 1 1 0

Reported by Claus Assmann.

##### Checklist
- [x] tests are added or updated

### CODE REVIEW

**Review by bernd-edlinger — APPROVED** [review]
LGTM for all branches.  Thanks!

**Comment by vdukhovni** [comment]
Question: Should I add a test case for the last missing DANE parameter combination: 0 1 0, a.k.a. PKIX-TA(0) SPKI(1) Full(0). This specifies a required issuer public key somewhere in the chain, but since it also requires a chain to a local root, the public key is only needed for matching, not signature checks.

This last case would exercise freeing the decoded key: https://github.com/openssl/openssl/blob/e64ad80c72b0743871f02badfe199d713b0cdadd/ssl/ssl_lib.c#L382
which is good to have, but isn't directly related to the issue at hand.

With that, all 24 combinations of `[0123] [01] [012]` would be covered by at least a success-case test.

**Comment by bernd-edlinger** [comment]
Ok go ahead.

**Comment by bernd-edlinger** [comment]
I assume this PR will cherry pick cleanly to all branches, right?

**Review by hlandau — APPROVED** [review]

**Review by bernd-edlinger — APPROVED** [review]
My approval still holds.

**Review by levitte — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master, 3.2, 3.1, and 3.0 branches. Thank you for your contribution.

**Comment by HQuest** [comment]
Can we confirm this fix was pushed as part of release 3.2.1? No mention on the changelog but I suppose there are many things that won't show anyway.

**Comment by t8m** [comment]
Yes, it was.

**Pull request closed without merging**
