### PR TITLE
Fix X509 propq so it does not use references

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
This started out as just fixing propq for just the X509 object.
There was also some additional ones in other X509 objects and the EVP_PKEY_CTX.

**Comment by slontis** [comment]
ping - ready for review.

**Review by mattcaswell — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Comment by slontis** [comment]
Thanks. Merged to master.

**Pull request closed without merging**
