### PR TITLE
Speed for HMACs.

### PR DESCRIPTION
**Pull request by paulidale**
Add support for HMAC over any evp supported digest.

- [x] documentation is added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
@t-j-h is this close to what you were thinking of?

**Comment by t-j-h** [comment]
speed already supports a hmac option that just runs hmac-md5 - the concept would be to support any hmac-<digest> with a default of md5 for compatibility - it would require looking at the current hmac handling logic which you've left intact but would be unreachable I think with the new option you are added in there. Look at the current D_HMAC handling ...

**Comment by paulidale** [comment]
The old code still lives -- `speed hmac` runs it.  The equivalent with this code is `speed -hmac md5`.

There isn't provision for non-option arguments to take extra arguments.  I.e. `speed hmac md5` would require deeper changes.  However, it is tempting to remove the old hmac code path, but that's an API change.

The other approach would be to add a function to libcrypto that maps from object name to hmac / digest.

**Comment by t-j-h** [comment]
I missed that context - and having duplicate code there makes me uncomfortable.

What you are timing here is a slightly different - the existing HMAC-md5 code times init-update-final and you are also catching ctx-new, ctx-free in the timing. Not an issue - just an observation.

I'll leave this open for others to comment for a day ...

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
