### PR TITLE
Reverting check to correct

### LINKED ISSUE #9773: Reverted check?
https://github.com/openssl/openssl/blob/master/crypto/evp/cmeth_lib.c#L40-L46

The NULL check seems to be reverted.
Also gcc 8.3.0 complains about this code, so it may be useful to add it to Travis.

### PR DESCRIPTION
**Pull request by beldmit**
Fixes #9773.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
For future understanding: in your own github branches, you can do whatever you wish, so you could have rebased and then done a `git push -f` on branch `9773_fix`, and that would have removed all the merge commits from that pull request, problem fixed.

We disallow merge commits in the main repository on git.openssl.org, though, so you would have had to rebase prior to pushing there.

Either way, no biggie, we can handle re-created PRs too :wink:

**Comment by beldmit** [comment]
I'm not so familiar with git so I prefer to follow the simplest way to get rid of merge commits and other unrelated stuff...

**Comment by levitte** [comment]
Sure.  Git takes a while getting comfortable with...

**Comment by beldmit** [comment]
Merged.

**Pull request closed without merging**
