### PR TITLE
Configure: move the processing of predefined macros to a function

### PR DESCRIPTION
**Pull request by levitte**
This is useful for cases when one might want to find out from more places, as shown in #4840.  It's not a *complete* solution, but combined with #4854, there is potential.

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
Actually, Appveyor uncovered a bug.  I just corrected it, and it will need reconfirmation.

**Comment by richsalz** [comment]
reconfirm

**Comment by levitte** [comment]
Cool, let's just hope Appveyor approves as well...  it seems a bit sluggish right now

**Comment by levitte** [comment]
Ok, Appveyor passed, time to merge!

**Comment by levitte** [comment]
Merged. 6d75a83c076f569289e63541ebb8473c37bd1ac6

**Pull request closed without merging**
