### PR TITLE
Run daily CI in a PR

### PR DESCRIPTION
**Pull request by hlandau**
Do not merge.

This is to run daily CI.

### CODE REVIEW

**Comment by paulidale** [comment]
This won't fully cover the cross compile builds.  it will build but not test them.

All lines like this need updating: https://github.com/openssl/openssl/blob/c7ed5e4697a71012e0a2d9dd5eaf997754ae5156/.github/workflows/cross-compiles.yml#L186

**Comment by hlandau** [comment]
@paulidale Updated.

**Comment by paulidale** [comment]
Thanks.

**Comment by mattcaswell** [comment]
Close/reopen after merge of #22491

**Comment by paulidale** [comment]
Tests (apart from Coverity) passed.
Re-running them all.

**Comment by paulidale** [comment]
All tests (apart from Coverity) passed a second time.

**Comment by paulidale** [comment]
Kick for a third go around.

**Comment by paulidale** [comment]
Third time around is good too.

**Pull request closed without merging**
