### PR TITLE
PKCS12: change safeContentsBag from a SET OF to a SEQUENCE OF

### LINKED ISSUE #6665: NID_safeContentsBag wants SET-OF, RFC says SEQUENCE-OF
The ASN.1 module in IETF RFC 7292 (https://tools.ietf.org/html/rfc7292#appendix-D) says

```asn.1
SafeContents ::= SEQUENCE OF SafeBag

safeContentsBag BAG-TYPE ::=
     {SafeContents        IDENTIFIED BY {bagtypes 6}}
```

So a SafeContentsBag value should look like

```
SEQUENCE
    OID("1.2.840.113549.1.12.10.1.6"),
    CONSTRUCTED [0]
        SEQUENCE(-OF)
            bag0, ...
```

The ASN in [RSA PKCS#12](https://www.emc.com/collateral/white-papers/h11301-pkcs-12v1-1-personal-information-exchange-syntax-wp.pdf) (2012) is the same, and I haven't managed to find a copy of the 1997 version.

But the implementation ASN says it's a SET-OF, not a SEQUENCE-OF.

https://github.com/openssl/openssl/blob/6f0ac0e2f27d9240516edb9a23b7863e7ad02898/crypto/pkcs12/p12_asn.c#L51-L58

It looks like the original implementation had writing as SEQUENCE-OF and reading as SET-OF, and the SET-OF is what got maintained during the ASN.1 template conversion:

https://github.com/openssl/openssl/blob/8d8c7266d4de9887fb0190a0770df9dc254a16a3/crypto/pkcs12/p12_sbag.c#L91-L94

https://github.com/openssl/openssl/blob/8d8c7266d4de9887fb0190a0770df9dc254a16a3/crypto/pkcs12/p12_sbag.c#L127-L130

https://github.com/openssl/openssl/blob/8d8c7266d4de9887fb0190a0770df9dc254a16a3/crypto/pkcs12/p12_sbag.c#L187-L191

### PR DESCRIPTION
**Pull request by levitte**
As per RFC 7292.

Fixes #6665

### CODE REVIEW

**Review by bartonjs — APPROVED** [review]

**Comment by levitte** [comment]
So, a note in CHANGES? A discussion on the project list? What do you have in mind?

**Comment by bernd-edlinger** [comment]
Will this bread IOP with windows ?

**Comment by levitte** [comment]
@bartonj might be able to shed some light on that. According to what he wrote in #6665, windows seems to be a non-issue in this regard...

**Comment by bartonjs** [comment]
Whether encoding it as SET-OF or SEQUENCE-OF, `PFXImportCertStore` reports only one certificate imported with my test case of one cert within a SafeContentsBag and another at the normal level.

That fairly well suggests (to me) that Windows (Server 2012 R2) doesn't traverse into SafeContentsBag at all.  (At least, not at a semantic level, it probably still walked through it to verify the BER encoding didn't have length issues)

**Comment by richsalz** [comment]
I think it should be raised on the project list and/or users and see if anyone has concerns.

**Comment by davidben** [comment]
This also fixes interop with NSS, at least skimming their code. Presumably also any other non-OpenSSL stack that bothered to implement safeContents. (safeContentsBag is kind of pointless and appears virtually unused, so I don't expect this OpenSSL bug to have had an effect on the ecosystem. Odd it's in the spec at all if Windows didn't implement it...)

**Comment by levitte** [comment]
I sent a message to openssl-users just now.

**Review by kroeckx — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

master / 1.1.1:
b709babbca0498cd2b05f543b09f57f4a670298e PKCS12: change safeContentsBag from a SET OF to a SEQUENCE OF

1.1.0:
46905cd473db84649b39850c02056883c3da0960 PKCS12: change safeContentsBag from a SET OF to a SEQUENCE OF

1.0.2:
7ccc506b56c3f20f08565b5aff268cb2f3bd046d PKCS12: change safeContentsBag from a SET OF to a SEQUENCE OF

**Comment by dot-asm** [comment]
Read cross at https://travis-ci.org/openssl/openssl/builds/406776736 appears relevant.

**Comment by kroeckx** [comment]
Can you point at which part of that log?

What I find is:
```
go test: FAILED (ServerNameExtensionServer-TLS1)
go test: unexpected failure: local error 'read tcp4 127.0.0.1:41484->127.0.0.1:42704: read: connection reset by peer', child error 'signal: segmentation fault (core dumped)', stdout:
go test: 
go test: stderr:
```

But I'm not sure that's related or not.

**Comment by dot-asm** [comment]
I had just really quick look, and apparently got it wrong. The failure actually stems from previous merge, or from https://travis-ci.org/openssl/openssl/builds/406252276. Apologies for caused confusion.

**Pull request closed without merging**
