### PR TITLE
Fix the brainpool support

### PR DESCRIPTION
**Pull request by bernd-edlinger**
There were several issues here:

- The table in provider/common/capabilites.c was preventing brainpool curves for tls1.3
- The key share message was using the internal curve encoding, not the tls1.3 encoding

This is a straight forward fix that uncovers some test cases that should have been passing but these issues prevented them to succeed.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
This needs to be rebased.

**Comment by Basskrapfen** [comment]
@mattcaswell Is this pull request still required after https://github.com/openssl/openssl/pull/19315 and  https://github.com/openssl/openssl/pull/19315 have been merged?

**Comment by mattcaswell** [comment]
It's unclear if there is anything useful left in this PR now that #19315 has gone in. I'd like to hear from @bernd-edlinger as to whether he thinks there is anything remaining to be done? If not this PR could just be closed.

**Comment by bernd-edlinger** [comment]
Well, this was meant as an alternative to #19315 that avoids the application to know
the subtle difference of brainpoll curve for TLS1.2 and TLS1.3 which now has a different
NID for use in TLS1.3, while the certificates are identical for TLS1.2 and TLS1.3.

So now this kind of mapping has to be done pretty much everywhere:
https://github.com/openssl/openssl/blob/80935bf5ad309bf6c03591acf1d48fe1db57b78f/test/helpers/ssl_test_ctx.c#L537-L546

That said, this PR can be closed.

**Pull request closed without merging**
