### PR TITLE
Fix HTTP server port output and allow dynamic verbosity setting

### PR DESCRIPTION
**Pull request by DDvO**
Fix various minor issues with the HTTP server:

* Fix the port output of the HTTP server. 
So far, on automatic local port selection, `Awaiting new connection on port 0...` was printed.
* Make the verbosity setting of the HTTP server dynamic.

This has been extracted from #16051 for separate treatment.

### CODE REVIEW

**Comment by DDvO** [comment]
Ping for approval

**Comment by DDvO** [comment]
Please let's have this as bug fix also for openssl-3.0, as motivated in https://github.com/openssl/openssl/pull/16051#issuecomment-878869210.

**Comment by DDvO** [comment]
Ping for OTC review

**Review by paulidale — APPROVED** [review]

**Comment by DDvO** [comment]
Merged - thanks @paulidale

**Pull request closed without merging**
