### PR TITLE
Add -DOPENSSL_BUILDING_OPENSSL to our builds

### PR DESCRIPTION
**Pull request by richsalz**
Our public header files are also used internally. This can cause issues when we want things "slightly different" when building internally: for example, we want to build with no-deprecated *for some things* but we want to allow users to have a choice.

See https://github.com/openssl/openssl/issues/10657#issuecomment-567836928 and the links it points to, etc.

This PR adds a define OPENSSL_BUILDING_OPENSSL which is only set in our internal Makefiles.
This means we can do things like this in files that use lhash.h but don't want the static inline functions declared when building openssl.
```
#if defined(OPENSSL_BUILDING_OPENSSL) || !defined(OPENSSL_NO_DEPRECATED_3)
... old code ...
DEFINE_STACK_OF(xxxx)
#else
... new code ...
STACK_OF(xxxx);
#endif 
```

This can be used in other places when we want to deprecate internally but not externally, such as perhaps the recent AES low-level functions #10587

### CODE REVIEW

**Comment by richsalz** [comment]
@levitte I don't know how/where to modify descrip.mms template; cluebat appreciated.

**Comment by levitte** [comment]
I'm curious to know how you think that changing our C sources solves the problem.

*The problem lies entirely in the public header files, and affects **other** applications that, somehow, includes `safestack.h` but don't link with libcrypto*

**Comment by richsalz** [comment]
Does the example not make sense?  OpenSSL wants to deprecate something in a public header file, but we don't want to force it for users.  Using the code fragment above *exactly* solves the problem you raise.  Perhaps wait to see the PR that uses this.

**Comment by levitte** [comment]
The example makes zero sense.  Apparently, you need a demonstration:

``` C
/* This is inc_safestack.c */
#include <openssl/safestack.h>
int main()
{
}
```

```
# This is compiling it
$ cc -fkeep-inline-functions inc_safestack.c
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_num':
inc_safestack.c:(.text+0x14): undefined reference to `OPENSSL_sk_num'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_value':
inc_safestack.c:(.text+0x36): undefined reference to `OPENSSL_sk_value'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_new':
inc_safestack.c:(.text+0x50): undefined reference to `OPENSSL_sk_new'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_new_null':
inc_safestack.c:(.text+0x5b): undefined reference to `OPENSSL_sk_new_null'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_new_reserve':
inc_safestack.c:(.text+0x7d): undefined reference to `OPENSSL_sk_new_reserve'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_reserve':
inc_safestack.c:(.text+0x9f): undefined reference to `OPENSSL_sk_reserve'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_free':
inc_safestack.c:(.text+0xb9): undefined reference to `OPENSSL_sk_free'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_zero':
inc_safestack.c:(.text+0xd4): undefined reference to `OPENSSL_sk_zero'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_delete':
inc_safestack.c:(.text+0xf7): undefined reference to `OPENSSL_sk_delete'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_delete_ptr':
inc_safestack.c:(.text+0x11c): undefined reference to `OPENSSL_sk_delete_ptr'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_push':
inc_safestack.c:(.text+0x141): undefined reference to `OPENSSL_sk_push'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_unshift':
inc_safestack.c:(.text+0x166): undefined reference to `OPENSSL_sk_unshift'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_pop':
inc_safestack.c:(.text+0x180): undefined reference to `OPENSSL_sk_pop'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_shift':
inc_safestack.c:(.text+0x19a): undefined reference to `OPENSSL_sk_shift'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_pop_free':
inc_safestack.c:(.text+0x1bf): undefined reference to `OPENSSL_sk_pop_free'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_insert':
inc_safestack.c:(.text+0x1eb): undefined reference to `OPENSSL_sk_insert'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_set':
inc_safestack.c:(.text+0x215): undefined reference to `OPENSSL_sk_set'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_find':
inc_safestack.c:(.text+0x23a): undefined reference to `OPENSSL_sk_find'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_find_ex':
inc_safestack.c:(.text+0x25f): undefined reference to `OPENSSL_sk_find_ex'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_sort':
inc_safestack.c:(.text+0x279): undefined reference to `OPENSSL_sk_sort'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_is_sorted':
inc_safestack.c:(.text+0x294): undefined reference to `OPENSSL_sk_is_sorted'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_dup':
inc_safestack.c:(.text+0x2ae): undefined reference to `OPENSSL_sk_dup'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_deep_copy':
inc_safestack.c:(.text+0x2db): undefined reference to `OPENSSL_sk_deep_copy'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_STRING_set_cmp_func':
inc_safestack.c:(.text+0x300): undefined reference to `OPENSSL_sk_set_cmp_func'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_num':
inc_safestack.c:(.text+0x31a): undefined reference to `OPENSSL_sk_num'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_value':
inc_safestack.c:(.text+0x33c): undefined reference to `OPENSSL_sk_value'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_new':
inc_safestack.c:(.text+0x356): undefined reference to `OPENSSL_sk_new'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_new_null':
inc_safestack.c:(.text+0x361): undefined reference to `OPENSSL_sk_new_null'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_new_reserve':
inc_safestack.c:(.text+0x383): undefined reference to `OPENSSL_sk_new_reserve'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_reserve':
inc_safestack.c:(.text+0x3a5): undefined reference to `OPENSSL_sk_reserve'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_free':
inc_safestack.c:(.text+0x3bf): undefined reference to `OPENSSL_sk_free'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_zero':
inc_safestack.c:(.text+0x3da): undefined reference to `OPENSSL_sk_zero'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_delete':
inc_safestack.c:(.text+0x3fd): undefined reference to `OPENSSL_sk_delete'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_delete_ptr':
inc_safestack.c:(.text+0x422): undefined reference to `OPENSSL_sk_delete_ptr'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_push':
inc_safestack.c:(.text+0x447): undefined reference to `OPENSSL_sk_push'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_unshift':
inc_safestack.c:(.text+0x46c): undefined reference to `OPENSSL_sk_unshift'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_pop':
inc_safestack.c:(.text+0x486): undefined reference to `OPENSSL_sk_pop'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_shift':
inc_safestack.c:(.text+0x4a0): undefined reference to `OPENSSL_sk_shift'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_pop_free':
inc_safestack.c:(.text+0x4c5): undefined reference to `OPENSSL_sk_pop_free'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_insert':
inc_safestack.c:(.text+0x4f1): undefined reference to `OPENSSL_sk_insert'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_set':
inc_safestack.c:(.text+0x51b): undefined reference to `OPENSSL_sk_set'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_find':
inc_safestack.c:(.text+0x540): undefined reference to `OPENSSL_sk_find'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_find_ex':
inc_safestack.c:(.text+0x565): undefined reference to `OPENSSL_sk_find_ex'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_sort':
inc_safestack.c:(.text+0x57f): undefined reference to `OPENSSL_sk_sort'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_is_sorted':
inc_safestack.c:(.text+0x59a): undefined reference to `OPENSSL_sk_is_sorted'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_dup':
inc_safestack.c:(.text+0x5b4): undefined reference to `OPENSSL_sk_dup'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_deep_copy':
inc_safestack.c:(.text+0x5e1): undefined reference to `OPENSSL_sk_deep_copy'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_CSTRING_set_cmp_func':
inc_safestack.c:(.text+0x606): undefined reference to `OPENSSL_sk_set_cmp_func'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_num':
inc_safestack.c:(.text+0x620): undefined reference to `OPENSSL_sk_num'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_value':
inc_safestack.c:(.text+0x642): undefined reference to `OPENSSL_sk_value'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_new':
inc_safestack.c:(.text+0x65c): undefined reference to `OPENSSL_sk_new'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_new_null':
inc_safestack.c:(.text+0x667): undefined reference to `OPENSSL_sk_new_null'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_new_reserve':
inc_safestack.c:(.text+0x689): undefined reference to `OPENSSL_sk_new_reserve'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_reserve':
inc_safestack.c:(.text+0x6ab): undefined reference to `OPENSSL_sk_reserve'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_free':
inc_safestack.c:(.text+0x6c5): undefined reference to `OPENSSL_sk_free'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_zero':
inc_safestack.c:(.text+0x6e0): undefined reference to `OPENSSL_sk_zero'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_delete':
inc_safestack.c:(.text+0x703): undefined reference to `OPENSSL_sk_delete'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_delete_ptr':
inc_safestack.c:(.text+0x728): undefined reference to `OPENSSL_sk_delete_ptr'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_push':
inc_safestack.c:(.text+0x74d): undefined reference to `OPENSSL_sk_push'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_unshift':
inc_safestack.c:(.text+0x772): undefined reference to `OPENSSL_sk_unshift'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_pop':
inc_safestack.c:(.text+0x78c): undefined reference to `OPENSSL_sk_pop'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_shift':
inc_safestack.c:(.text+0x7a6): undefined reference to `OPENSSL_sk_shift'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_pop_free':
inc_safestack.c:(.text+0x7cb): undefined reference to `OPENSSL_sk_pop_free'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_insert':
inc_safestack.c:(.text+0x7f7): undefined reference to `OPENSSL_sk_insert'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_set':
inc_safestack.c:(.text+0x821): undefined reference to `OPENSSL_sk_set'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_find':
inc_safestack.c:(.text+0x846): undefined reference to `OPENSSL_sk_find'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_find_ex':
inc_safestack.c:(.text+0x86b): undefined reference to `OPENSSL_sk_find_ex'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_sort':
inc_safestack.c:(.text+0x885): undefined reference to `OPENSSL_sk_sort'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_is_sorted':
inc_safestack.c:(.text+0x8a0): undefined reference to `OPENSSL_sk_is_sorted'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_dup':
inc_safestack.c:(.text+0x8ba): undefined reference to `OPENSSL_sk_dup'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_deep_copy':
inc_safestack.c:(.text+0x8e7): undefined reference to `OPENSSL_sk_deep_copy'
/usr/bin/ld: /tmp/ccOqmSAH.o: in function `sk_OPENSSL_BLOCK_set_cmp_func':
inc_safestack.c:(.text+0x90c): undefined reference to `OPENSSL_sk_set_cmp_func'
collect2: error: ld returned 1 exit status
```

The example is silly, but to the point.  I suppose that *actual* use cases included safestack.h indirectly, because of some other library's headers that includes it.  Either way, the mere *inclusion of a header* should force you to link to any specific library.

Changing our own source will do *nothing* to change the above, *unless* you plan in doing your example in our public header files, but in that case, it should be simpler to simply *remove* the offending `DEFINE_STACK_OF` calls from there and use them in the C source that need them instead.

**Comment by levitte** [comment]
... and before you say "don't use `-fkeep-inline-functions`", let me remind you that this is what the Solaris compiler does by default, reportedly (and some others as well, but I forget the details)

**Comment by richsalz** [comment]
> Changing our own source will do nothing to change the above, unless you plan in doing your example in our public header files

Exactly.  (Like I said :)

**Comment by levitte** [comment]
> (Like I said :)

Sorry, that wasn't clear at all to me

**Comment by richsalz** [comment]
So, can you tell me how to fix the MMS template? :)

**Comment by levitte** [comment]
``` diff
diff --git a/Configurations/descrip.mms.tmpl b/Configurations/descrip.mms.tmpl
index f9f3aea4f4..701cd3eaed 100644
--- a/Configurations/descrip.mms.tmpl
+++ b/Configurations/descrip.mms.tmpl
@@ -179,7 +179,8 @@ MODULESDIR_C={- platform->osslprefix() -}MODULES{- $sover_dirname.$target{pointe
 
 CC={- $config{CC} -}
 CPP={- $config{CPP} -}
-DEFINES={- our $defines1 = join('', map { ",$_" } @{$config{CPPDEFINES}}) -}
+DEFINES={- our $defines1 = join('', map { ",$_" } ('OPENSSL_BUILDING_OPENSSL',
+                                                   @{$config{CPPDEFINES}})) -}
 INCLUDES={- our $includes1 = join(',', @{$config{CPPINCLUDES}}) -}
 CPPFLAGS={- our $cppflags1 = join('', @{$config{CPPFLAGS}}) -}
 CFLAGS={- join('', @{$config{CFLAGS}}) -}
```

**Comment by levitte** [comment]
FYI, I would like to see how you actually use that macro in this PR.  I cannot see approving this otherwise.  The example in the description isn't enough for me.

**Comment by DDvO** [comment]
> This can be used in other places when we want to deprecate internally but not externally, such as perhaps the recent AES low-level functions #10587

I just came across this reference. 
@richsalz, did you really mean #10587, which is not about AES but about HTTP, OCSP, etc.?

The hitherto HTTP-related API that so far is part of OCSP is somewhat weird, partly documented, and very limited, so #10587 tries to deprecate it at least internally. On the other hand that old API presumably needs to be retained externally to some extent for backward compatibility.

**Comment by richsalz** [comment]
@ddvo, no 10587 is a typo for #10580   oops.

**Comment by levitte** [comment]
This should be rebase to pick up the existing windows makefile changes

**Comment by richsalz** [comment]
Rebased this and pushed.  Also rebased the two dependant PR's, #10669 and #10724

**Comment by richsalz** [comment]
@levitte I think your desired change broke things.  the lib_defines setting does not seem to be inherited:
```
; g grep OPENSSL_BUILDING
Configurations/00-base-templates.conf:  lib_defines     => [ 'OPENSSL_BUILDING_OPENSSL' ],
include/openssl/conf.h:#if defined(OPENSSL_BUILDING_OPENSSL) || defined(OPENSSL_NO_DEPRECATED_3_0)
include/openssl/err.h:#if defined(OPENSSL_BUILDING_OPENSSL) || defined(OPENSSL_NO_DEPRECATED_3_0)
include/openssl/lhash.h:# if defined(OPENSSL_BUILDING_OPENSSL) || defined(OPENSSL_NO_DEPRECATED_3_0)
include/openssl/lhash.h:# if defined(OPENSSL_BUILDING_OPENSSL) || defined(OPENSSL_NO_DEPRECATED_3_0)
; grep OPENSSL_BUILDING Makefile
        exit 1
; 
```

I am going to undo this change for now.

**Comment by levitte** [comment]
> @levitte I think your desired change broke things. the lib_defines setting does not seem to be inherited:

Congrats, you found a bug in the template.  See #10753

**Comment by richsalz** [comment]
Whee, what's my prize? :)

Once #10753 gets merged, I will revert the commit.  You also have to tell me that it works :)  Or you could add this define to your that PR, heh heh.

**Comment by mspncp** [comment]
> Whee, what's my prize? :)

Tadaaa, here comes your bug bounty:

image

**Comment by richsalz** [comment]
Thanks, very tasty.  (My wife wants to know what kind of bug that is)

**Comment by mspncp** [comment]
It's a [brown marmorated stink bug from Australia](https://www.carsales.com.au/editorial/details/stink-bug-crisis-delays-thousands-of-new-australian-cars-116485). 🤣

**Comment by levitte** [comment]
>  You also have to tell me that it works :)

I imagined that you might want to merge #10753 with, say, #10669 and see for yourself.

**Comment by richsalz** [comment]
What's a good way to do that kind of test merge?

**Comment by levitte** [comment]
```
git checkout -b RL-fix-Makefile master
git pull https://github.com/levitte/openssl.git fix-Makefile-templates-20200104
git checkout -b declare-stack+RL-fix-Makefile declare-stack
git merge RL-fix-Makefile
```

You then have my fix in `RL-fix-Makefile`, and the merge of your stack stuff with it in `declare-stack+RL-fix-Makefile`.  Whenever you do more work in `declare-stack`, all you need to do to update the merge branch is this:

```
git checkout declare-stack+RL-fix-Makefile
git merge RL-fix-Makefile
```

I recommend that you avoid rebases of `declare-stack` while having the merge branch around, the merges can become nasty...  if you do, it may be worth just starting the merge branch over, like this:

```
git branch -f declare-stack+RL-fix-Makefile declare-stack
git checkout declare-stack+RL-fix-Makefile
git merge RL-fix-Makefile
```

**Comment by richsalz** [comment]
Thanks!  I did the first four commands and it builds fine.  Good enough proof I guess. :)

**Comment by levitte** [comment]
#10753 has now been merged.

**Comment by richsalz** [comment]
This was done as part of #10753

**Comment by levitte** [comment]
> This was done as part of #10753

Oh, it was!  That was...  unintentional.  But no problem

**Pull request closed without merging**
