### PR TITLE
Fix typos in EdDSA algorithm names

### PR DESCRIPTION
**Pull request by emillon**
Hi,

This fixes a couple typos:

- Ed488 -> Ed448
- Ed25591 -> Ed25519

Thanks!

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
LGTM

**Comment by mattcaswell** [comment]
I agree this is trivial

**Review by t8m — APPROVED** [review]
I agree with the CLA:trivial

**Comment by t8m** [comment]
Merged to master. Thank you for your contribution.

**Pull request closed without merging**
