### PR TITLE
Add a warning about using enable-crypto-mdebug-backtrace

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by mattcaswell** [comment]
It might be worth also noting that on some platforms the execinfo.h implementation this relies on is a stub and does nothing. Therefore this might compile, but not actually do anything.

**Comment by levitte** [comment]
Nope.  According to [this page](https://www.gnu.org/software/gnulib/manual/html_node/execinfo_002eh.html), that's on systems where the `execinfo.h` header file is missing, so you will *still* get compile problems because of the lack of that header file.

**Comment by levitte** [comment]
The header file is key.

**Comment by mattcaswell** [comment]
That's not the way I read it. I read it that on systems that don't provide execinfo.h, gnulib will provide one. But the implementation is a stub. So it will compile but won't work (otherwise whats the point of having a stub implementation if you still get compile problems!).

**Comment by levitte** [comment]
Gah!  Ok, thanks...  I forget that 'gnulib' is an add-on lib and not the same as `libc` (which is also a GNU library on some systems).

**Comment by levitte** [comment]
Added a note, please review again

**Comment by mattcaswell** [comment]
+1

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
