### PR TITLE
Optional property query support.

### PR DESCRIPTION
**Pull request by paulidale**
Add the possibility of a property query clause to be optional by preceding
it with a question mark.

- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
Ping?

**Comment by levitte** [comment]
Do I understand it correctly, that an optional property comes into played when all non-optional properties match exactly, i.e. gives extra "weight" to the property definitions that happen to have the option properties?

**Comment by paulidale** [comment]
Exactly.  Of the providers that match all of the non-optional properties, the one that matches most of the optional ones is returned.

**Comment by levitte** [comment]
Side note: the property API is seriously lacking docs.  Would you mind putting an effort into some, in `doc/internal`?

**Comment by paulidale** [comment]
I should be able to do some documentation.  The README there isn't great.

**Comment by paulidale** [comment]
Merged, thanks.

**Comment by paulidale** [comment]
> 
> 
> Side note: the property API is seriously lacking docs. Would you mind putting an effort into some, in `doc/internal`?

There is some documentation in `internal/man3/OSSL_METHOD_STORE.pod`.  Is this what you'd liked filled out?

**Comment by levitte** [comment]
Never mind...  I wasn't thinking about the method store, I really don't see that as a property API per se...  but I realised that the property API itself is private behind the method store API, so like I said, never mind.

However, it would probably be good to have some manuals about properties themselves, and since that's public, something in `doc/man7` would probably be suitable.

**Comment by paulidale** [comment]
Refer to #9011

**Pull request closed without merging**
