### PR TITLE
CONF: On VMS, treat VMS syntax inclusion paths correctly

### PR DESCRIPTION
**Pull request by levitte**
non-VMS syntax inclusion paths get the same treatment as on Unix.

### CODE REVIEW

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
I discovered that it doesn't work quite right with VMS syntax paths yet, so putting this in WIP.

**Comment by levitte** [comment]
Yup, found something...  Interestingly, if you `opendir` on VMS with a path that looks Unixy, `readdir` will get you straight file names like you do on Unix.  However, if the path looks more VMSy (such as `[.conf-includes]`, these are the kinds of file names you get from `readdir`:

includes1.cnf;2
includes1.cnf;1
includes2.cnf;2
includes2.cnf;1

All things considered, this makes perfect sense, the VMS crowd get what they expect and the Unix crowd as well.  But when you're accepting both...

(for those not so savvy, VMS has a concept of file generations, with the syntax being a ';' followed by an incrementing number for each new generation of the file)

**Comment by levitte** [comment]
So, uhmmm, there's a little bit more tweaking to do...

**Comment by levitte** [comment]
This change became a bit more involved.  Please have a look at the commit messages for some explanations.

**Comment by levitte** [comment]
Time for a review!

**Comment by t-j-h** [comment]
Why do we have a LPdir_unix.c with VMS stuff in it and an LPdir_vms.c?

**Comment by levitte** [comment]
The answer lies within [`crypto/o_dir.c`](https://github.com/openssl/openssl/blob/master/crypto/o_dir.c#L26-L30), i.e. `LPdir_vms.c` is for VMS versions that don't have `opendir`, `readdir`, `closedir` (versions < 7.0), while newer VMS versions use `LPdir_unix.c`.

(side note: we don't really support pre-7.0 VMS any more, so `LPdir_vms.c` could simply be thrown away...  and `LPdir_unix.c` should probably be renamed `LPdir_posix.c`.  However, such cleanup is for another PR)

**Comment by levitte** [comment]
Where are we on this?

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Merged.  Thank you!

4f7c840a4dba37d8465137eae6867968e251c13c to a5829ae282f47c39d1dd0642e4a84c0a6f3d80f4

**Pull request closed without merging**
