### PR TITLE
Configure: disable new trace api by default

### LINKED ISSUE #8472: OPENSSL_TRACE should be disabled by default
Subject line says it all.

Well, except that this should be mentioned somewhere in NEWS or README or something.

But, again, DISABLED BY DEFAULT.

### PR DESCRIPTION
**Pull request by mspncp**
Fixes #8472

##### Checklist

- [x] documentation updated

### CODE REVIEW

**Comment by t-j-h** [comment]
I agree with this approach. However I think we should leave this PR open for 24 hours for @levitte and others to comment.

**Comment by mspncp** [comment]
Sure, I'll wait for the discussion. I'm not in a hurry.

**Comment by mspncp** [comment]
All commits squashed. Ready for review and comments.

**Comment by levitte** [comment]
I'm fine with these changes.  However, Travis is having a fit...

**Comment by levitte** [comment]
#8475 should fix the Travis issue

**Comment by mspncp** [comment]
Ok, I'll rebase when #8475 is merged.

**Comment by levitte** [comment]
#8475 is now merged

**Comment by mspncp** [comment]
Rebased without changes to get the bugfix from #8475.

**Comment by mspncp** [comment]
Ok then. Since @levitte approved, I decided to merge it as-it-is and open a new pull request for Pauli's suggestion later.

**Comment by mspncp** [comment]
> Ok then. Since @levitte approved, I decided to merge it as-it-is and open a new pull request for Pauli's suggestion later.

Arghh! Wrong pull request :-/  I shouldn't do too many things in parallel.

**Comment by mspncp** [comment]
Merged, thanks!

**Pull request closed without merging**
