### PR TITLE
Fix X509_STORE_CTX_set_purpose() (1.1.1)

### PR DESCRIPTION
**Pull request by mattcaswell**
This is a backport of #17382 to the 1.1.1 branch

### CODE REVIEW

**Comment by mattcaswell** [comment]
The test needed various changes to resolve conflicts.

**Comment by slontis** [comment]
Is missingcrypto.txt not needed for 1.1.1?

**Comment by mattcaswell** [comment]
> Is missingcrypto.txt not needed for 1.1.1?

Doesn't exist in that branch.

**Review by slontis — APPROVED** [review]

**Comment by mattcaswell** [comment]
> paulidale force-pushed the OpenSSL_1_1_1-stable branch from 0b13bd0 to 8a5dbc1 10 hours ago

@paulidale was this an intentional force push of the 1.1.1 branch? It sent the 1.1.1 branch back in time by several commits (compared to the "real" git repo) and is now causing PRs that target the 1.1.1 branch explicitly (like this one) to show extra commits.

**Comment by paulidale** [comment]
No it wasn't intentional.  I must have got something badly muddled somewhere -- a forced push is not something I plan to do to the main repo.

**Comment by t8m** [comment]
I do not see the force-push on the git.openssl.org so I do not think @paulidale did this. It seems something is rather botched with the mirroring. @levitte?

**Comment by mattcaswell** [comment]
> I do not see the force-push on the git.openssl.org so I do not think @paulidale did this. 

I think @paulidale accidentally pushed to the *github* 1.1.1 branch. This would not show on git.openssl.org.

**Comment by mattcaswell** [comment]
> It seems something is rather botched with the mirroring

The mirroring logs in via openssl-machine, so if this was a problem with the mirroring it would say openssl-machine force pushed.

**Comment by levitte** [comment]
> > It seems something is rather botched with the mirroring
> 
> The mirroring logs in via openssl-machine, so if this was a problem with the mirroring it would say openssl-machine force pushed.

Correct

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
