### PR TITLE
Assorted fixes

### PR DESCRIPTION
**Pull request by ghedo**
Just a bunch of little fixes I've been accumulating.

### CODE REVIEW

**Comment by ghedo** [comment]
I've merged in the commit from #423 as well.

**Comment by levitte** [comment]
Is this meant as master only?

**Comment by ghedo** [comment]
@levitte I fixed all the issues locally, but I can 't currently push to GitHub (again...). I'll do it later.

> Is this meant as master only?

They are all pretty simple fixes, so backporting them shouldn't be difficult. I can open new PRs for 1.0.2 and 1.0.1 if needed.

**Comment by levitte** [comment]
Backporting is usually the matter of a cherry pick and perhaps one or two small conflicts to resolve.  However, I usually want to know the intent of a pull request, hence my question.

**Comment by ghedo** [comment]
Ah ok. While they are all pretty small issues, I think they'd be worth backporting to at least 1.0.2.

I was also looking at the `bugs/` directory, does it have any use? I think it can be removed along the other useless code.

**Comment by ghedo** [comment]
I also just pushed the fixes for your comments.

**Comment by ghedo** [comment]
There's also `crypto/threads/` which doesn't seem to be used at all.

**Comment by ghedo** [comment]
So I went ahead and removed `bugs/` and `crypto/threads/` as well. I left that in a separate commit though, so it can be easily discarded if you want.

I also have another patch that removes the remaining FIPS code (~500 lines) but I don't know if you want to get rid of that as well.

**Comment by levitte** [comment]
Actually, the removal of `bugs/` and `crypto/thread/` is something that I'd like to keep in master only, so ideally it should be in a different pull request.

**Comment by ghedo** [comment]
Ok, I moved that commit to #448.

**Comment by levitte** [comment]
+1 as it stands now

**Comment by richsalz** [comment]
+1 from me too.  you want to commit/push?  let me know if you want me to do it.  (i agree master and 1.0.2)

**Comment by levitte** [comment]
I'll do it...  and if we're backporting to 1.0.2, there's no reason whatsoever not to backport to 1.0.1.

**Comment by levitte** [comment]
Pushed on master, 1.0.2 and 1.0.1

**Comment by ghedo** [comment]
Since this has been merged, [RT#4090](https://rt.openssl.org/Ticket/Display.html?id=4090), [RT#4081](https://rt.openssl.org/Ticket/Display.html?id=4081) and [RT#4068](https://rt.openssl.org/Ticket/Display.html?id=4068) can be closed now.

**Pull request closed without merging**
