### PR TITLE
util/find-doc-nits: when loading "missing" files, check if documented

### LINKED ISSUE #10681: bit-rot in missingXXXX files
The current missingcrypto and missingmacro files are subject to bit-rot.  There is no way to notice that something is now documented, except by hand.

find-doc-nits, when loading those files, could/should check for something mentioned in the file that is, in fact, documented.

### PR DESCRIPTION
**Pull request by levitte**
It may be that some "missing" manuals have been written since their
insertion in the "missing" files.  Make sure to alert when such manual
references are found.

This works, because we collect all existing manual references into
%name_map first.

Fixes #10681

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
Typo in commit message: `exissting`

**Comment by levitte** [comment]
> Typo in commit message: exissting

Fixed

**Comment by mattcaswell** [comment]
Travis failures are relevant.

**Comment by richsalz** [comment]
This check should really be part of "make doc-nits"

**Comment by levitte** [comment]
> This check should really be part of "make doc-nits"

It is, hence the Travis failure (I haven't edited the missing files accordingly...)

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

17fa385d2cd4443707aa42ab752a00aacf87d750 util/find-doc-nits: when loading "missing" files, check if documented
b2b90922c2cfdfaa6a6f3588a014c74ff445508a Removed now documented stuff from util/missing*.txt

**Pull request closed without merging**
