### PR TITLE
ci: add 3.4 to the provider compatibility test

### PR DESCRIPTION
**Pull request by paulidale**
This really should have been done with the 3.4 branch was first created.  I'd consider this urgent because of this.

Extended tests label included to see what's currently broken.

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
Test failures are most likely related to #25582.

**Review by levitte — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM, the failures should be fixed as urgent

**Comment by t-j-h** [comment]
Agree this should have been in - it is coming in too late in reality - but we should accommodate it but any failures should not be beta blockers.

**Comment by paulidale** [comment]
Suggest adding it to whatever checklist is used to create release branches.

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Added 3.4 branch with @t-j-h's proviso.

**Comment by t8m** [comment]
Merged to the master and 3.4 branches. Thank you for your contribution.

**Pull request closed without merging**
