### PR TITLE
Fix EVP_MD_meth_dup and EVP_CIPHER_meth_dup

### LINKED ISSUE #16157: EVP_MD_meth_dup() on global EVP_MDs leaks memory in OpenSSL 3.0
When EVP_MD_meth_dup() is called on a global EVP_MD in OpenSSL 3.0, the origin of the newly allocated EVP_MD is initially set to EVP_ORIG_METH in EVP_MD_meth_new(), but is later overwritten with the origin of the source EVP_MD in memcpy(), which turns EVP_MD_meth_free() into a no-op.

The following excerpt works with OpenSSL 1.1.1, but leaks memory with OpenSSL 3.0:

```c
#include <openssl/evp.h>
#include <stdlib.h>

int main(void) {
        EVP_MD *md = EVP_MD_meth_dup(EVP_sha256());
        if (md) EVP_MD_meth_free(md);
}
```

A potential fix might be to set origin back to EVP_ORIG_METH in EVP_MD_meth_dup() after the call to memcpy():

```diff
diff --git a/crypto/evp/evp_lib.c b/crypto/evp/evp_lib.c
index f78df52a..42331b0b 100644
--- a/crypto/evp/evp_lib.c
+++ b/crypto/evp/evp_lib.c
@@ -822,6 +822,7 @@ EVP_MD *EVP_MD_meth_dup(const EVP_MD *md)
         CRYPTO_RWLOCK *lock = to->lock;
 
         memcpy(to, md, sizeof(*to));
+        to->origin = EVP_ORIG_METH;
         to->lock = lock;
     }
     return to;
```

### PR DESCRIPTION
**Pull request by mattcaswell**
Make sure the origin is set correctly when duping an EVP_MD or EVP_CIPHER.

Fixes #16157

### CODE REVIEW

**Comment by beldmit** [comment]
@mattcaswell, isn't it worth adding an asan test according to #16157?

**Review by beldmit — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Does this warrant a test case?

**Comment by mattcaswell** [comment]
Test case added. Please reconfirm.

**Comment by beldmit** [comment]
no-deprecated failure seems relevant

**Comment by mattcaswell** [comment]
Fixup pushed to address the no-deprecated problem.

**Comment by beldmit** [comment]
Formal reapprove.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master, thanks for this.

**Pull request closed without merging**
