### PR TITLE
Fix missing sendmmsg/recvmmsg on AIX

### PR DESCRIPTION
**Pull request by t8m**
This at least fixes the build failures on AIX

This will not fix the test failures though.

### CODE REVIEW

**Comment by nhorman** [comment]
what issue is this related to?  I ask because I know some versions of AIX have recvmmsg, so it might be good to constrain this conditional to a specific version range

**Comment by t8m** [comment]
On 7.1 they get a build failure on 7.3 the build passes but with a severe warning - a missing prototype for these functions. So I believe that until they fix their headers we should not use sendmmsg/recvmmsg on AIX.

**Comment by t8m** [comment]
This is the issue: https://github.com/openssl/openssl/issues/23751 (that's on 7.1)

**Review by nhorman — APPROVED** [review]

**Review by Sashan — APPROVED** [review]
looks good to me, thanks.

**Comment by shahsb** [comment]
> On 7.1 they get a build failure on 7.3 the build passes but with a severe warning - a missing prototype for these functions. So I believe that until they fix their headers we should not use sendmmsg/recvmmsg on AIX.

Till we get the fix. We could think of a workaround patch in our source code, which would essentially define the missing prototypes.

For example, it would look something similar to following:

```
#ifdef __AIX__
extern int sendmmsg(int, struct mmsghdr *, unsigned int, int);
extern int recvmmsg(int, struct mmsghdr *, unsigned int, int, struct timespec *);
#endif
```

**Review by shahsb — CHANGES_REQUESTED** [review]
would request skipping only for AIX < 7.2 and for the above AIX versions we can do a tweaking/workaround patch from our end.

**Comment by t8m** [comment]
Until we have a person using all the affected versions of AIX submitting a better patch, I do not think we should spend more time on this. We have no way to easily test this and we depend on community to provide AIX support.

**Comment by t8m** [comment]
Merged to the master, 3.4, 3.3 and 3.2 branches. Thank you for the reviews.

**Pull request closed without merging**
