### PR TITLE
Optimize chacha20 on aarch64 by SVE2

### PR DESCRIPTION
**Pull request by daniel-hu-arm**
This patch improves existing chacha20 SVE patch by using SVE2,
which is an optional architecture feature of aarch64, with XAR
instruction that can improve the performance of chacha20.

Signed-off-by: Daniel Hu <Daniel.Hu@arm.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
@tom-cosgrove-arm any chance you could check this?

**Comment by zorrorffm** [comment]
I've reviewed this PR, it looks good to me.

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for this improvement.

**Comment by t8m** [comment]
This is scheduled for next minor release - i.e, 3.1

**Comment by t8m** [comment]
Patch releases (3.0.x) do not get feature fixes (optimizations are not bug fixes).

**Comment by daniel-hu-arm** [comment]
thanks for prompt reply!

**Pull request closed without merging**
