### PR TITLE
HPKE

### PR DESCRIPTION
**Pull request by slontis**
This is an alternative to PR #17172 that  places the DHKEM into a provider..

OTC will need to decide if the API is acceptable.
Open questions
(1) Should HPKE be sitting inside a provider as an algorithm, or is it sufficient to keep it as a KEM + KDF + AEAD that sits outside..
(2) the KDF is just HKDF.. Does the keyschedule need to sit inside its own KDF? 
(3) DHKEM has derivekey functionality.. Where does this belong - inside the KEM, or should the KEM interface to KDF that gets fed info about the EC or ECX key.. (NOTE the algorithms are different)?

Also At the higher level I had  bit of trouble deciding what space to keep the keys in, It needs EVP_PKEY for setting up KEM's but in other places it deals with encoded private/public keys. Inside the KEM's it keeps keys mainly as EC_KEY or ECX_KEY objects. Only the encoded public key returned by the encapsulate() is left in Byte data form. 

I have not added comprehensive tests or documentation, since this may change depending on the API design.
There are still some // comments in the code. - raising errors still needs to be done.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by sftcd** [comment]
- I *really* don't understand the intent here - the author (a member of the OTC who are being asked to decide this) hasn't commented on #17172 which was created in Nov 2021, (nor been in touch otherwise), yet this pops up not as a sketch of an api (which I asked for a couple of times and would have welcomed) nor is it a correct or complete implementation. (See below) What's the intent with this PR?

- This crashes if ``AES_128_GCM`` is provided instead of ``AES-128-GCM`` due to a static list of AEADs being over-run in a simple for [loop](https://github.com/slontis/openssl/blob/hpke_test/crypto/hpke/hpke.c#L131), so this code clearly hasn't been tested 

- I've not succeded in getting a roundtrip with NSS code encrypting and this code decrypting so this doesn't interop (code   [here](https://github.com/sftcd/happykey/blob/9180-api/nss_slontis.c)) - I get an error when trying to decrypt, no idea why. Interoperability is 99% of the value of HPKE, so failing there seems to indicate prioritising the wrong things. (The equivalent [code](https://github.com/sftcd/happykey/blob/9180-api/neod.c) from #17172 does interop.)

- An HPKE api ought use the IANA codepoints from the RFC and not strings defined by the OpenSSL library that are hard to find for  a developer. Any mapping from IANA codepoints to OpenSSL-defined strings ought be internal to the api. I don't think it'd be good if an HPKE api could easily, accidentally or deliberately, produce outputs that have no well-defined HPKE codepoints as that can damage interop. So the idea here to use those strings in the api seems wrong to me.

- An HPKE api needs to help with ECH GREASEing - producing random values of plausible lengths - which requires knowledge of KEM internals and supported IANA codepoints and so ought be part of this api and not reproduced above.

- Otherwise the api defined here seems to me more or less as good or as bad as the one I [proposed a month ago](https://github.com/sftcd/happykey/blob/master/hpke-9180.h) and about which I only received feedback from one person

- I've no strong opinion as to whether the internals here would be easier to maintain longer term. I defer to those who know those OpenSSL internals better than I on that one. I do note that this PR modifies many more files than #17172 (33 vs. 9) which seems like a negative.

- Unsurprisingly I think the best thing for the OTC to do would be to merge #17172 which is tested and interops. As I said before I'd be fine with implementing an external api that looks like this one (or [that](https://github.com/sftcd/happykey/blob/master/hpke-9180.h) one) before or after that merge.  But mostly I think the OTC needs to decide which PR they want to proceed with asap - given all the above, I'd find it hard to justify spending yet more effort on this topic until that decision has been made.

**Comment by sftcd** [comment]
> > An HPKE api ought use the IANA codepoints from the RFC and not strings defined by the OpenSSL library that are hard to find for a developer.
> 
> Algorithms in providers are fetchable by name, hence the strings. From the perspectives of previous algorithms, it's a bit surprising to see these code points where at least I would have expected ASN.1 OIDs. Incidently, we do support fetching by such OIDs as well, as long as they are in canonical text form. I currently don't know if codepoints like you asked for can be retrofitted into the algorithm names forms, but it's probably not impossible.

Well, HPKE has new codepoints defined in [RFC9180[(https://datatracker.ietf.org/doc/html/rfc9180#section-11) and those codepoints are also used by ECH/MLS etc (the specs that use HPKE) so it seems much less error prone and simpler for the consumer of the API to use those. There's no table mapping those codepoints to OIDs that I know of, nor to the strings used in the library - while those could be provided, again doing that seems more error prone and also make it easy to accidentally emit things that other HPKE implementations can't consume. Fetching the algs by name in the implementation of the API seems like it'll mean any provider controls etc should work fine.

**Comment by slontis** [comment]
Hello @sftcd,

I make no claims that this is better than your PR. It is also a draft so it is neither fully tested nor documented.

My intention here is to try to get the actual API figured out. Once we add a API into OpenSSL it is very hard to get rid of it, so we have to get it roughly right. I dont know that I like the large number of one shot API's that are in this PR. We could possibly use OSSL_PARAM to pass through some of the additional params maybe.  Your PR stalled because the API needs to be figured out. My comment about the OTC was related to the design of the API.

Quite a lot of the code here is related to working with providers, and that does influence the API design to some extent.
I deliberately left the greasing out for the moment, but did notice it in your implementation.
I could of commented on your PR, but you should be able to see that the approach here is quite a bit different once you start to plumb things into providers.
At some point the HPKE could  become a NIST standard, which means that it needs to fit nicely into providers. The algorithms can't just sit outside as a group of methods.
Some other things related to the API's. Inits are separated out from the updates in quite a few places (e.g the seal/open). this is a fairly standard pattern within OpenSSL.

**Comment by slontis** [comment]
> Well, HPKE has new codepoints defined in [RFC9180](https://datatracker.ietf.org/doc/html/rfc9180#section-11) and those codepoints are also used by ECH/MLS etc (the specs that use HPKE) so it seems much less error prone and simpler for the consumer of the API to use those. There's no table mapping those codepoints to OIDs that I know of, nor to the strings used in the library - while those could be provided, again doing that seems more error prone and also make it easy to accidentally emit things that other HPKE implementations can't consume. Fetching the algs by name in the implementation of the API seems like it'll mean any provider controls etc should work fine.

It is not much different to change this to ID's if you think that is better. It may still needs to do a mapping from an ID to  a string in order to find the algorithm..

**Comment by slontis** [comment]
I also have no problem making you a co-contributor on this PR, since I know it probably took quite a while to create your PR.

**Comment by slontis** [comment]
I have not tested the one shot interface. I know the individual calls work since the test vectors are working. it i likely that I am not passing a param through correctly to a individual call. This is just a bug in untested code.

**Comment by sftcd** [comment]
On 15/08/2022 20:20, Shane wrote:
> Hello @sftcd,
> 
> I make no claims that this is better than your PR. It is also a draft
> so it is neither fully tested nor documented.

That's partly what's confused me (in addition to the surprise
element;-() - I could understand an outline API sketch or a
fully working thing, but I still don't know how to interpret
this PR based on in-between code.

> My intention here is to try to get the actual API figured out. Once
> we add a API into OpenSSL it is very hard to get rid of it, so we
> have to get it roughly right. 

Agreed. (And that's something I said in Nov 2021 when I first
posted my PR.) And to be clear - the external API does not
need to be tied into the internal approach to implementing
that API.

> I dont know that I like the large
> number of one shot API's that are in this PR. 

 From reading the I-Ds using HPKE, those are the APIs that'll
be used - HPKE is almost entirely a one-shot thing so I
suspect there'll be very few re-uses of e.g. vars with your
OSSL_HPKE_KEM type. In ECH that's only needed at all because
of HelloRetryRequest so clients will make at most 2 calls
(ever) with one KEM instance, servers won't have to bother
with a 2nd call ever. (ECH-enabled servers could keep KEM
strutures in memory but it's simpler and probably safer to
just keep the EVP_PKEY pointers in memory instead and even
with your API treat the KEM vars as purely ephemeral for each
attempted ECH-decryption.)

So overburdening the caller with intermediate structures that
don't really help is a danger here, and one into which your
API falls IMO.

The upside of an API like yours though is making the one-shot
APIs more like the pseudo code from the RFC seems useful as
other I-Ds using HPKE do seem to be referencing those. (Which
is what I proposed doing last month.)

> We could possibly use
> OSSL_PARAM to pass through some of the additional params maybe.  

Personally, I think _seal and _unseal APIs that take the huge
number of potential inputs is the least-worst thing in the
end - I think the caller gets to write less code even if they
have to read the docs a bit more to figure out what all those
NULL/0 inputs mean:-)

> Your
> PR stalled because the API needs to be figured out. 

Stalled? Yes, the API needs deciding but there's been an
awful lot of what now feels like syntactic bring-me-a-rock
on that PR over the months. (Apologies if irritation about
that seeps though;-)

> My comment about
> the OTC was related to the design of the API.
> 
> Quite a lot of the code here is related to working with providers,
> and that does influence the API design to some extent. 

Yes. I'm still not seeing any real benefit from all that code
TBH. HPKE is not like a new crypto alg or even a mode - it's
a much more lightweight CMS-like thing intended for protocol
developers to use and not intended for generic application
use. And crypto agility is something to be supported within
an HPKE API but does not need to be exposed by the API other
than via the suites defined in the RFC. (Doing the latter as
you do, and allowing the caller to emit things that don't map
to any IANA registered HPKE codepoint risks damaging interop
IMO.)

> I deliberately
> left the greasing out for the moment, but did notice it in your
> implementation. I could of commented on your PR, but you should be
> able to see that the approach here is quite a bit different once you
> start to plumb things into providers. 

I'm still at a loss to understand why a different internal
approach makes it sensible to not communicate.

> At some point the HPKE could
> become a NIST standard, 

No. That's getting it wrong. I don't believe NIST have ever
created a standard for CMS - they refer to CMS in other stuff
but they don't standardise CMS. The same is the case here.

HPKE is not a new alg and won't be the subject of some future
version of FIPS-140, ever. HPKE is just not like x25519. Nor
is it like GCM.

> which means that it needs to fit nicely into
> providers. 

I believe you are just wrong about "needs" above when the
"it" is the external HPKE API.

> The algorithms can't just sit outside as a group of
> methods. 

They don't. It's entirely correct that the implementation of
an HPKE API needs to use the provider stuff so any controls
that ought apply, do apply. But that does not need to be
exposed to the consumer of the HPKE API other than via error
returns if some provider policy stuff precludes use of some
HPKE_defined suite.

> Some other things related to the API's. Inits are separated
> out from the updates in quite a few places (e.g the seal/open). this
> is a fairly standard pattern within OpenSSL.

Again, a single shot, and possible 2nd-shot if needed, will
be the main pattern with HPKE. I don't believe there's any
case where the same OSSL_HPKE_KEM instance from your API need
be repeatedly used for many calls to seal or unseal. (That
said, I need to check MLS again to be certain, but I think
that's the case there. It is definitely the case for ECH,
which is the most mature consumer of HPKE.)

Cheers,
S.

**Comment by sftcd** [comment]
On 15/08/2022 20:35, Shane wrote:
> I also have no problem making you a co-contributor on this PR, since
> I know it probably took quite a while to create your PR.

I've no idea what a co-contributor on a PR is tbh;-)

To be open though - yes if the end result is some other PR
being merged, some attribution of my work would be helpful
as there has been a funder for that work and they like to
know their funds have resulted in something.

But that's secondary to getting the right code merged.

S.

**Comment by sftcd** [comment]
On 15/08/2022 20:45, Shane wrote:
> I have not tested the one shot interface. I know the individual calls
> work since the test vectors are working. it i likely that I am not
> passing a param through correctly to a individual call. This is just
> a bug in untested code.

Perhaps that's an insider/outsider difference, I'd not have
submitted a PR with code that didn't work but I can see how
being an insider might make it seem ok to make a PR from an
early work-in-progress. Getting new code to interop may not
be that simple though - the combinatorics of the (too many)
IAMA codepoints from RFC9180 adds up to 480 different ways
you need to get it right, and then you need to multiply that
by the number of different ways your API allows you to do
the same thing. (Again, that's another benefit of fewer APIs
with more parameters so there's one way to do one thing.)
And then there are at least three important interop targets
(nss, boring, CF's ECH server) to test against. I don't see
that losing the benefit of that having been done is something
to do lightly.

S.

**Comment by slontis** [comment]
> 
I just put up a draft for a few reasons:
- It took a considerable time to get it to this stage, and I wanted others to be aware to be I was looking at it.
- I dont want to waste time completing it, if it is not needed. I/We need input from others before we can move forward,
- It has been discussed in an OTC meeting, which will hopefully cause other OTC members to look at HPKE, now that I have given an overview.. Further discussions will hopefully happen.
- There is an existing RSASVE KEM that is implemented using providers, which is why this PR uses a similar encapsulate_init, encapsulate interface for the KEM.

Note that boring have used a seal_init, seal_update interface..

**Comment by slontis** [comment]
CIRCL also implement the AEAD iterface as shown in the RFC..

**Comment by davidben** [comment]
> Note that boring have used a seal_init, seal_update interface..

No, we have not. Applying init, update*, finish (as in `EVP_CIPHER`) to a single AEAD operation is not a good idea and has serious security consequences. See https://www.imperialviolet.org/2014/06/27/streamingencryption.html . Do not do this.

What we have is a setup, (seal*/open*) interface, matching the spec. This is because HPKE allows a sequence of ordered encryption operations on a single context. That does not have the `EVP_CIPHER` problem. Indeed the current draft of ECH requires that mode in the HRR flow.

I think there may be some mixed up terminology here. I imagine OpenSSL's problematic `EVP_CIPHER` API isn't helping. There are two kinds of state one might set up:

1. The _message-independent_ key state (AES key schedule, GCM H value, etc.)
2. Partial, _message-dependent_ state for a single encryption operation (pending GCM product, buffered blocks, etc.)

(1) is for whenever a single AEAD key is used multiple times (with different nonces each time!). It is pretty common to do and indeed applies to HPKE. You should try to set up (1) at SetupR/SetupS in HPKE. (2) is if you decided to spread a single, atomic seal/open operation across multiple function calls, aka "streaming". (2) is the footgun with AEADs.

When we talking about "init", "update", and "final", this is usually about (2). Indeed even if you believe in both (1) and (2), an ideal API would separate them out because there's no sense wasting memory carrying around (2) when all you need is (1). (Consider a TLS connection: (2) is only around in the middle of decrypting a record, but (1) is retained across the whole connection.)

Where I suspect this got confusing is that OpenSSL mixes up (1) and (2). `EVP_CIPHER_CTX` is _both_ message-independent and message-dependent state. If you're trying to set up (1), you pass a NULL IV. That's what `ossl_aead_init` is doing. Then, for the actual operation, you _re-init_ with the full IV later, possibly making a copy if you don't want to mutate your copy of (1). See `ossl_aead_seal`. (This copy is also a consequence of the mixed up API.) So this isn't right:

> Inits are separated out from the updates in quite a few places (e.g the seal/open). this is a fairly standard pattern within OpenSSL.

But the mistake is in the description, not the PR. The PR does not separate them. `ossl_aead_seal` calls (re)init, update, and final all in one go, as it should, because we should not continue perpetuating the `EVP_CIPHER` mistake in new APIs. It _does_ separately have `ossl_aead_init`, but that function is setting up the key schedule.

**Comment by slontis** [comment]
> I think there may be some mixed up terminology here. I imagine OpenSSL's problematic `EVP_CIPHER` API isn't helping. There are two kinds of state one might set up:

Yes my terminology is wrong :)

**Comment by slontis** [comment]
Closing this in favor or the original PR #17172 that will use PR #19068 (which is based off the KEM related code of this PR).

**Pull request closed without merging**
