### PR TITLE
GitHub CI: Add 'check-update' and 'check-docs'

### PR DESCRIPTION
**Pull request by levitte**
'check-update' runs a 'make update' to check that it wasn't forgotten.

'check-docs' runs 'make doc-nits'.  We have that as a separate job to
make it more prominent.

### CODE REVIEW

**Comment by levitte** [comment]
I added 'check-update' specifically because 'make update' was forgotten lately, which went unnoticed.

**Comment by levitte** [comment]
... and well, it didn't take long to fail.  Good :wink:

**Comment by levitte** [comment]
`make update` commit added

**Review by kroeckx — APPROVED** [review]

**Comment by richsalz** [comment]
There's also ```cmd-nits```

**Comment by kroeckx** [comment]
Any reason not to do this in 1.1.1-stable?

**Comment by levitte** [comment]
> Any reason not to do this in 1.1.1-stable?

Other than "didn't think of it"? No...

**Comment by levitte** [comment]
Labeled for 1.1.1 as well

**Comment by t8m** [comment]
> There's also `cmd-nits`

And md-nits. But neither of these are on 1.1.1 so they should be probably in a separate PR as this one can be easily cherry-picked.

**Review by t8m — APPROVED** [review]
Approved (with the first commit also for 1.1.1).

**Comment by levitte** [comment]
Merged

master:

8175476b81c6b54bfa1c8555b35561099b202c4d GitHub CI: Add 'check-update' and 'check-docs'
f3f2dd9dfb5fe89fff44c413e9d6c788e0fa6300 make update

1.1.1:

5a5d87a936ceeca1648288e1efe4296687193b16 GitHub CI: Add 'check-update' and 'check-docs'

**Pull request closed without merging**
