### PR TITLE
Fixed typo in inner_evp_generic_fetch() error handling

### PR DESCRIPTION
**Pull request by Futaura**

### CODE REVIEW

**Review by mspncp — COMMENTED** [review]
> Think I've done it correctly - let me know if I messed something up!

Well done! Just a tiny little detail: we prefer not to reference the issue in the subject line, but rather as a `Fixes #xxxxx` comment in the body of the commit message:

```
Fixed typo in inner_evp_generic_fetch() error handling

Fixes #17876

CLA: trivial
```

_(If you have a local checkout, you can change the commit message by amending your last commit and force-pushing the changed commit to your fork on GitHub.  If you are not able to do it, just let me know, then I will correct it when the commit gets merged.)_

**Comment by mspncp** [comment]
For the records: I agree that it's a trivial change.

**Comment by mspncp** [comment]
> Just a tiny little detail: we prefer not to reference the issue in the subject line

It's not just a matter of taste: only if the reference is in the body, GitHub connects your pull request to the issue, such that it will be closed automatically when the pull request gets merged.

**Comment by Futaura** [comment]
Ok, I think I changed it correctly. I'll try to remember this for next time! I also admit that I forgot to add `CLA: trivial` in the first place, which I already amended earlier on (I did the commit initially via the website, whereas I'm more familiar with using the command-line Git).

**Review by mspncp — APPROVED** [review]

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
Agree trivial.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Agree with CLA: trivial.

**Comment by t8m** [comment]
Merged to 3.0 and master branches. Thank you for your contribution.

**Pull request closed without merging**
