### PR TITLE
crypto/trace.c: Remove unexisting categories

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
This was a slip up and came along with the last minute fixup for #9212

**Comment by mspncp** [comment]
Uh... I don’t see how this is related to #9212?

**Comment by mspncp** [comment]
Ah, I see: it‘s in the merged commit.

**Review by mspncp — APPROVED** [review]

**Comment by mspncp** [comment]
Note: you could mention in your commit message that it reverts an inadvertent change from commit ...   (can’t look up the id now)

**Comment by mspncp** [comment]
> Note: you could mention in your commit message that it reverts an inadvertent change from commit ... (can’t look up the id now)

E.g.

```
crypto/trace.c: Remove unexisting categories

Reverts an inadvertent change from commit fe26f798526c.
```

**Comment by mspncp** [comment]
Oh, and you can also add "Fixes #9220".

**Comment by levitte** [comment]
Done

**Comment by levitte** [comment]
Merged.

1d12afc310e8334e731d2c7acf1c3f1d0395cd03 crypto/trace.c: Remove unexisting categories

**Pull request closed without merging**
