### PR TITLE
LoongArch64 assembly pack: Fix ChaCha20 ABI breakage

### PR DESCRIPTION
**Pull request by xry111**
The [LP64D ABI][1] requires the floating-point registers f24-f31 (aka fs0-fs7) callee-saved.  The low 64 bits of a LSX/LASX vector register aliases with the corresponding FPR, so we must save and restore the callee-saved FPR when we writes into the corresponding vector register.

This ABI breakage can be easily demonstrated by injecting the use of a saved FPR into the test in bio_enc_test.c:

    static int test_bio_enc_chacha20(int idx)
    {
        register double fs7 asm("f31") = 114.514;
        asm("#optimize barrier":"+f"(fs7));
        return do_test_bio_cipher(EVP_chacha20(), idx) && fs7 == 114.514;
    }

So fix it.  To make the logic simpler, jump into the scalar implementation earlier when LSX and LASX are not enumerated in AT_HWCAP, or the input is too short.

[1]: https://github.com/loongson/la-abi-specs/blob/v2.20/lapcs.adoc#floating-point-registers

### CODE REVIEW

**Comment by xry111** [comment]
I'm not sure how to properly add a test for psABI conformance...

**Review by t8m — APPROVED** [review]

**Comment by davidben** [comment]
> I'm not sure how to properly add a test for psABI conformance...

https://github.com/openssl/openssl/discussions/22056 discusses this a bit. Given the number of ABI issues that have come up recently, OpenSSL investing in this area seems worthwhile. The ABI testing framework has been incredibly useful for us in BoringSSL.

**Comment by xry111** [comment]
@openssl/committers  Ping for a second approve.

**Review by nhorman — APPROVED** [review]

**Comment by xry111** [comment]
Removing the test TODO box for now...

**Comment by t8m** [comment]
Merged to the master and 3.2 branches. Thank you for your contribution.

**Pull request closed without merging**
