### PR TITLE
Remove unnecessary if condition from apps.c

### LINKED ISSUE #3593: If condition always true in apps/apps.c
https://github.com/openssl/openssl/blob/master/apps/apps.c#L304

`ok >=0` will always result true in the above line. Would love to remove the if condition after someone gives a go to it.

### PR DESCRIPTION
**Pull request by aashil**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

Fixes #3593

### CODE REVIEW

**Comment by InfoHunter** [comment]
You should add the text `CLA: trivial` in your commit message or sign a CLA [here](https://www.openssl.org/policies/cla.html)

**Comment by aashil** [comment]
@InfoHunter Just emailed the CLA to info@opensslfoundation.org. Any idea how long it takes to come in effect?

**Comment by InfoHunter** [comment]
It will be soon. But I think the CLA should be sent to 'legal@opensslfoundation.org'.

Ping @richsalz

**Comment by richsalz** [comment]
CLA received, removing tag.

**Comment by dot-asm** [comment]
Redundant if is present in 1.1.0 and 1.0.2, but this is not actually a bug. So I'd agree that master is sufficient.

**Comment by aashil** [comment]
@richsalz @dot-asm I can backport if you guys want me to.

**Comment by richsalz** [comment]
@aashil don't bother, too much hassle (when doing the merge) for too little gain :)
This is commit 5e44201 on master.

**Pull request closed without merging**
