### PR TITLE
Fix grammar-o in CONTRIBUTING

### PR DESCRIPTION
**Pull request by kaduk**

### CODE REVIEW

**Comment by levitte** [comment]
(for the openssl team, there's a review tool that I just used...)

**Comment by mattcaswell** [comment]
Oh....what branches?

**Comment by kaduk** [comment]
It exists back to 1.0.2

**Comment by mattcaswell** [comment]
Ok. My plus 1 applies to master, 1.1.0 and 1.0.2

**Comment by richsalz** [comment]
It goes all the way back to 1.0.1 if you want :)

**Comment by mattcaswell** [comment]
No strong view. If you want to push it there, my plus one applies.

**Comment by richsalz** [comment]
+1 to merge to all branches, since it was introduced as the "retire RT" commit in 12 oct.

**Comment by levitte** [comment]
I'm fine with all branches, for the record

**Comment by richsalz** [comment]
pushed to all releases, closing.

**Pull request closed without merging**
