### PR TITLE
apps: remove internal/cryptlib.h include that isn't used.

### PR DESCRIPTION
**Pull request by paulidale**
This include doesn't seem to prevent compilation.  The CI's will confirm.

Running the extended tests for better coverage.

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by t8m** [comment]
Apparently it is needed for the ossl_assert() call in enable-trace build.

**Comment by kaduk** [comment]
> Apparently it is needed for the ossl_assert() call in enable-trace build.

That doesn't really seem like a great reason to keep using an internal header in the applications, to me.

**Comment by paulidale** [comment]
I've changed the `ossl_assert` calls into diagnostics to stderr, so the dependency on the internal header is gone.

**Comment by paulidale** [comment]
These changes are large enough to justify a re-review.

**Review by kaduk — APPROVED** [review]
Thanks for sticking with it

**Comment by paulidale** [comment]
Merged to master.  Thanks for the comments and feedback.

**Pull request closed without merging**
