### PR TITLE
Rename FIPS_MODE to FIPS_MODULE

### LINKED ISSUE #11538: Use FIPS_MODULE not FIPS_MODE for ifdef's
Consensus seems to agree that using FIPS_MODE wasn't a great choice for ifdef'ing code, and that it should be FIPS_MODULE.

### PR DESCRIPTION
**Pull request by levitte**
This macro is used to determine if certain pieces of code should
become part of the FIPS module or not.  The old name was confusing.

Fixes #11538

### CODE REVIEW

**Comment by richsalz** [comment]
A quick compatibility hack is to do this in e_os.h:
```
#ifdef FIPS_MODULE
# define FIPS_MODE
```
for a time.

**Comment by mspncp** [comment]
@richsalz I think @slontis is more worried about unnecessary merge conflicts caused by all the renamings. Since this change here is a perl (or sed) one-liner which can easily reapplied, I would say it's only fair to respect @slontis' wish.

**Comment by levitte** [comment]
> @richsalz I think @slontis is more worried about unnecessary merge conflicts caused by all the renamings

Most of all, I think we're looking at harsh triage of stuff that *must* go into alpha1 vs what is fairly cosmetic, with approval grace periods and all that.  I see no reason to rush this one...

**Comment by paulidale** [comment]
Is this safe to go in now that alpha1 is released?

**Comment by slontis** [comment]
I am fine with it going in as long as it is up to date..

**Comment by levitte** [comment]
Updated

**Comment by levitte** [comment]
Merged

f844f9eb44186df2f8b0cfd3264b4eb003d8c61a Rename FIPS_MODE to FIPS_MODULE

**Pull request closed without merging**
