### PR TITLE
QUIC: Allow stream write buffer stats to be queried

### PR DESCRIPTION
**Pull request by hlandau**
Fixes https://github.com/openssl/project/issues/411

Note: This is built on top of the explicit event handling PR, so only the top two commits belong to this PR.

### CODE REVIEW

**Comment by hlandau** [comment]
Needs review for 3.3.

**Comment by hlandau** [comment]
address/ubsan failure seems unrelated. We have been getting this one stochastically lately. Created an issue for someone to look into it: https://github.com/openssl/project/issues/478

**Comment by nhorman** [comment]
Agree, both unsan and asan failures are in sslapi test, which I believe @mattcaswell  and @bernd-edlinger have fixes for pending. 

Only question I have is related to QUIC_RAISE_NON_NORMAL_ERROR.  I'm on my phone so I can't see the definition.  What value does it return?  You have it return in the default case of a switch statement, and I'm a little concerned that it might return a value that conflicts with a legitimate non-error case for the other getter functions.

Other than that LGTM.

**Review by t-j-h — APPROVED** [review]

**Comment by hlandau** [comment]
> Agree, both unsan and asan failures are in sslapi test, which I believe @mattcaswell and @bernd-edlinger have fixes for pending.
> 
> Only question I have is related to QUIC_RAISE_NON_NORMAL_ERROR. I'm on my phone so I can't see the definition. >What value does it return? You have it return in the default case of a switch statement, and I'm a little concerned that it might return a value that conflicts with a legitimate non-error case for the other getter functions.

It always returns 0, for failure. Note that these APIs output values via pointers always, not return codes, to ensure that errors can always be unambiguously indicated regardless of the semantics of the output value.

**Review by Sashan — APPROVED** [review]

**Comment by hlandau** [comment]
Merged to master. Thanks for the reviews.

**Pull request closed without merging**
