### PR TITLE
rsa/rsa_ossl.c: cache MONT_CTX for public modulus earlier.

### PR DESCRIPTION
**Pull request by dot-asm**
Blinding is performed more efficiently and securely if MONT_CTX for public
modulus is available by the time blinding parameter are instantiated. So
make sure it's the case.

This can go all the way down to 1.0.2. Modification apparently slipped from "smooth RSA" series.

### CODE REVIEW

**Comment by levitte** [comment]
Merged.

2cc3f68cde77af23c61fbad65470602ee86f2575 rsa/rsa_ossl.c: cache MONT_CTX for public modulus earlier.

**Comment by mspncp** [comment]
@levitte @mattcaswell shouldn't this be cherry-picked at least to 1.1.1?


@dot-asm even mentioned 1.0.2. I tried a cherry-pick to 1.0.2 and the patch applied cleanly after a successfull "inexact rename detection" by git (rsa_ossl.c -> rsa_eay.c), except for the following conflict 

```
<<<<<<< variant A
        if (rsa->flags & RSA_FLAG_CACHE_PUBLIC)
            if (!BN_MONT_CTX_set_locked(&rsa->_method_mod_n, CRYPTO_LOCK_RSA,
                                        rsa->n, ctx))
                goto err;

>>>>>>> variant B
======= end
```

which was caused by the fact that the `BN_free()` call [exists only in master](https://github.com/openssl/openssl/pull/7586/files#diff-c589297ccee9fa01c43478fca0682c35L324) but not in 1.0.2. This conflict can be trivially resolved by choosing variant B.

The result of the cherry-pick can be found at https://github.com/mspncp/openssl/commit/e3a21c0a2222a030c166740753ba8fcc7b4dd813 and is ready for pushing. If you approve the cherry-pick to 1.0.2, I can push it as it is, without creating a separate pull request.

**Comment by mspncp** [comment]
Ok, it looks like I was too optimistic about the cherry-picking without creating a separate pull request: There is a little more adjustment to be done, because of the struct opacity changes.

* [AppVeyor Builds](https://ci.appveyor.com/project/mspncp/openssl/builds/20475467)
* [Travis Builds](https://travis-ci.org/mspncp/openssl/builds/458186470?utm_source=github_status&utm_medium=notification)

@dot-asm if you wan't to submit the pull request yourself, I'll step back and let you do it.

**Comment by mspncp** [comment]
I fixed the build and created a pr, see #7683

**Comment by dot-asm** [comment]
> I'm wondering if this classifies as a "security fix",

In essence it was *unintentionally* omitted from "smooth RSA", and "smooth RSA" is all about security. Well, it can appear a bit misleading, because blinding is not part of "smooth RSA" in its *original* meaning, which is about CRT calculations. But in the course of "smoothing" CRT, even surrounding components were "smoothed" including blinding. And without this modification blinding can take "non-smooth" path.

**Comment by mspncp** [comment]
> > I'm wondering if this classifies as a "security fix",

> In essence it was *unintentionally* omitted from "smooth RSA", and "smooth RSA" is all about security. Well, it can appear a bit misleading, because blinding is not part of "smooth RSA" in its *original* meaning, which is about CRT calculations. But in the course of "smoothing" CRT, even surrounding components were "smoothed" including blinding. And without this modification blinding can take "non-smooth" path.

So in essence your reply means "yes, it's a security fix and  should be cherry-picked to 1.1.0", right?

**Comment by dot-asm** [comment]
Right, the intention was to make you [in plural] draw this conclusion. I mean it's all about convincing others, not just say "yes" or "no"...

**Comment by mattcaswell** [comment]
Pushed to 1.1.0.

**Pull request closed without merging**
