### PR TITLE
storeutl: make sure s2i_ASN1_INTEGER is correctly declared

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by kaduk — APPROVED** [review]
That's a rather unexpected place for s2i_ASN1_INTEGER to live, but if it works...

**Comment by kaduk** [comment]
The appveryor log:

```
git fetch -q origin +refs/pull/5482/merge:
fatal: unable to access 'https://github.com/openssl/openssl.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
Command exited with code 128
```

A bit meta, but since it was only one of the builds presumably it's not the thing where github disabled TLS 1.0 and 1.1 connections...

**Comment by levitte** [comment]
> That's a rather unexpected place for s2i_ASN1_INTEGER to live, but if it works...

We do have some declarations tucked in strange places, yes...

**Comment by levitte** [comment]
Merged.  946ec58448d664c10ee05c1c8d3c2a3915c9d5f5

**Pull request closed without merging**
