### PR TITLE
All lh_stats functions were deprecated in 3.1

### PR DESCRIPTION
**Pull request by t8m**
This is alternative to #22245

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
There still seem to be references to `OPENSSL_NO_DEPRECATED_3_2` in `crypto/lhash/lh_stats.c` - is that intentional?

**Comment by mspncp** [comment]
@t8m since the deprecation happened in 3.1, the manual pages for 3.2 and 3.1 shouldn't have unnecessary diffs.

You can just cherry-pick it backwards, preferring the master version over the 3.1 version in the conflict below, right?

I will close #22245 in favour of your PR.


```diff
msp@debian:~/src/openssl/master$ git diff
diff --cc doc/man3/OPENSSL_LH_stats.pod
index 5bc69674f8,fb95928d8f..0000000000
--- a/doc/man3/OPENSSL_LH_stats.pod
+++ b/doc/man3/OPENSSL_LH_stats.pod
@@@ -16,10 -20,6 +20,18 @@@ see L<openssl_user_macros(7)>
   void OPENSSL_LH_node_stats_bio(LHASH *table, BIO *out);
   void OPENSSL_LH_node_usage_stats_bio(LHASH *table, BIO *out);
  
++<<<<<<< HEAD
 +The following functions have been deprecated since OpenSSL 3.1, and can be
 +hidden entirely by defining B<OPENSSL_API_COMPAT> with a suitable version value,
 +see L<openssl_user_macros(7)>:
 +
++||||||| parent of ffceef6b4e (All lh_stats functions were deprecated in 3.1)
++The following functions have been deprecated since OpenSSL 3.2, and can be
++hidden entirely by defining B<OPENSSL_API_COMPAT> with a suitable version value,
++see L<openssl_user_macros(7)>:
++
++=======
++>>>>>>> ffceef6b4e (All lh_stats functions were deprecated in 3.1)
   void OPENSSL_LH_stats(LHASH *table, FILE *out);
   void OPENSSL_LH_stats_bio(LHASH *table, BIO *out);
  
@@@ -61,9 -60,6 +72,16 @@@ These calls should be made under a rea
  L<OPENSSL_LH_COMPFUNC(3)/NOTE> for more details about the locks required
  when using the LHASH data structure.
  
++<<<<<<< HEAD
 +The functions OPENSSH_LH_stats() and OPENSSH_LH_stats_bio() were deprecated in
 +version 3.1.
 +
++||||||| parent of ffceef6b4e (All lh_stats functions were deprecated in 3.1)
++The functions OPENSSH_LH_stats() and OPENSSH_LH_stats_bio() were deprecated in
++version 3.2.
++
++=======
++>>>>>>> ffceef6b4e (All lh_stats functions were deprecated in 3.1)
  =head1 SEE ALSO
  
  L<bio(7)>, L<OPENSSL_LH_COMPFUNC(3)>
```

**Comment by mspncp** [comment]
Commit 45ada6b92bc has **a lot of renamings** from 3.1 to 3.2.  Do these all need to be checked?

**Comment by t8m** [comment]
> There still seem to be references to `OPENSSL_NO_DEPRECATED_3_2` in `crypto/lhash/lh_stats.c` - is that intentional?

Nope, I did not grep properly. Fixup pushed.

**Comment by t8m** [comment]
@mspncp There is #22248 for 3.1 branch.

**Review by mspncp — APPROVED** [review]
Theses deprecation macros always tend to create knots in my brain.

**Review by tom-cosgrove-arm — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
