### PR TITLE
Change X509_get_pathlen return to int32_t

### PR DESCRIPTION
**Pull request by richsalz**
Also rename test/v3ext.c to test/v3ext_test.c

Addesses issues raised by @ekasper in #1089

### CODE REVIEW

**Comment by ekasper** [comment]
Is there a specific reason why you prefer explicit width?

Just curious. I prefer plain int whenever 4 bytes is sufficient to hold the value and the exact width isn't important (it's not e.g. crypto code with exactly-4-byte-counters etc) - but I don't think we have consensus on what we should use? So just wondering out of curiosity.

It's better than a meaningless long in any case, so +1 either way, thanks!

**Comment by richsalz** [comment]
Since this comes from DER encoded objects, I think a specific size makes sense, avoid interop problems when sizeof(int) various across machines.

**Comment by richsalz** [comment]
thanks for raising the issues.  merged.

**Comment by ekasper** [comment]
Good point, makes sense to say "we support 4-byte pathlens but no more". In practice of course 1 byte should be plenty but the RFC does not impose any limit, so yeah.

**Pull request closed without merging**
