### PR TITLE
QEMU: include more test runs for all bar one cross compilation target

### PR DESCRIPTION
**Pull request by paulidale**
For the cross compiles where the tests couldn't be run, most are capable of being run when statically linked. For these, a shared with FIPS build but not test run is also included to maximise compilation coverage. The builds take a couple of minutes so the impact of these extra jobs isn't great.

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
#16141 rebased to master but a new PR for some reason.

**Comment by paulidale** [comment]
The repeated failures for `test_includes`, `test_store` and `test_x509_store` are related the the `OPENSSL_DIR_read()` call.  This gets an _Value too large for defined data type_ error calling the standard library's `readdir()` wrapper.  That is, the failure is during the translation from the x86-64 structure to the 32 bit structure.  I've tried tweaking the include defines to use larger fields but couldn't figure out how to make it work.  I suggest we live with these tests disabled.

The failure of `test_params_conversion` for the m68k build is due to the handling of infinite floating point values.  The test has been modified to handle this case (and other NaN situations) correctly.

The failure of the `test_async` for the SH4 build is due to a lack of support.  The run has been modified to use the `no-async` option.

**Comment by paulidale** [comment]
Added the note about the three failing tests to the commit so it doesn't get lost.

**Comment by paulidale** [comment]
Ping for review.

**Comment by paulidale** [comment]
Reping for review.

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
I would have preferred the test change to be in a separate PR rather than mixed in here - but approved anyway.

**Comment by t-j-h** [comment]
Also marked as urgent given this is testing and the beta is imminent.

**Comment by paulidale** [comment]
It's in a separate commit so all is not lost.

Merged after removing a spurious debug printf(), thanks for the review.

**Pull request closed without merging**
