### PR TITLE
Fix intermittent sanitizer build failures in ecdsa_test

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Comment by t8m** [comment]
@paulidale This fixes a new failure: https://github.com/openssl/openssl/runs/1965304218

But I am not sure if it is the right fix or just a workaround and the fix should be different.

**Comment by t8m** [comment]
Without the RAND_bytes() call if the actual initialization happens when we setup fake bytes callback the initialization consumes bytes from the callback which breaks the expectations of the test that sets up the callback.

**Comment by t8m** [comment]
Hmm, apparently the workaround is not correct.

**Comment by paulidale** [comment]
I'm not sure I fully understand the cause but I think #14300 should fix it.

Is it related to calling `fake_rand_set_callback()` before the RNG instance is created?

**Comment by t8m** [comment]
... because I forgot about the private instance. This fix works better.

**Comment by t8m** [comment]
Hehe, we did the same synchronously

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I looked at your changes and thought that I'd gone to the wrong PR :)

**Comment by t8m** [comment]
> Is it related to calling `fake_rand_set_callback()` before the RNG instance is created?

Yes. Because the callback will be imo used to seed which will use the bytes that the tests expect to be used for key generation.

**Comment by paulidale** [comment]
I'm happy to flag this as urgent if the CIs are failing often enough.

**Comment by paulidale** [comment]
Thanks, the seeding was what hadn't clicked.

**Comment by t8m** [comment]
OK, let's mark it urgent if you agree. The fix is small enough to be safe.

**Comment by paulidale** [comment]
Hmmmm, the fake_random doesn't seed: `evp_rand_reseed_locked` just returns success if the function isn't defined.  Something else in the initialisation must consume the randomness.

**Comment by t8m** [comment]
> Hmmmm, the fake_random doesn't seed: `evp_rand_reseed_locked` just returns success if the function isn't defined. Something else in the initialisation must consume the randomness.

Heh, sorry for misleading you. It is actually the `fake_rand.cb = NULL;` in the fake_rand_newctx() that is being called as part of the initialization that overwrites the cb set by the test. So IMO another option would be just drop that call as this is static data that is initialized to NULL anyway. But doing this initialization explicitly via the get0 calls is also IMO fine.

**Comment by t8m** [comment]
IMO it is not that urgent so unless you prefer dropping the `fake_rand.cb = NULL;` I'll just merge after the regular 24 hour window.

**Comment by paulidale** [comment]
Dropping the `fake_rand.cb = NULL;` as well seems reasonable.  It starts zeroed and the free clears it again.

**Comment by paulidale** [comment]
There is an additional problem for a test that uses _both_ the public and the private DRBGs.  The automatic instantiation of the second of these will wipe the callback.  The remove of `fake_rand.cb = NULL;` should fix this.

I also think that the early instantiation should be included to avoid other surprises.

A better fix would be to not share state between the `fake_random` instances but that's more difficult.

**Comment by t8m** [comment]
@paulidale Still approved?

**Review by paulidale — APPROVED** [review]
I wonder what the implications of setting the state to uninitialised here is.  I'll ponder this today.

**Comment by t8m** [comment]
Merged to master.

**Pull request closed without merging**
