### PR TITLE
VSI submission: redirect terminal input through socket

### PR DESCRIPTION
**Pull request by levitte**
This is needed, because on VMS, select() can only be used on sockets.  being
able to use select() on all kinds of file descriptors is unique to Unix.

So, the solution for VMS is to create a layer that translates input from
standard input to socket communication.

### CODE REVIEW

**Comment by levitte** [comment]
This fixes a bug that's been around on VMS since the dawn of time.  CompHP has had this fix for quite some time, but it's not before VSI took over VMS development that we got this feedback.

Note that I will make a PR for 1.0.2 as well.

**Comment by richsalz** [comment]
I think the code in apps/s_client can be simplified -- i.e., fewer ifdefs -- by makefile fileno_stdin variable the same as fileno(stdin) on non-vms.

**Comment by richsalz** [comment]
and maybe have raw_read_stdin take the fileno/stdin param and put only the vms-specific IFDEF in that utility function and not in all places that call it.

**Comment by levitte** [comment]
Sure.  Will look it over with simplification in mind.

**Comment by levitte** [comment]
So I did some refactoring in the 1.0.2 variant (#1577), see if you like that better.

**Comment by richsalz** [comment]
+1 nice.

**Comment by levitte** [comment]
Added a couple of fixups. Two bugs and the formatting that @dot-asm asked for are included.

Reconfirm?

**Comment by richsalz** [comment]
Yes from me

**Comment by dot-asm** [comment]
Do fix -Werror=missing-prototypes in --strict-warnings first :-)

**Comment by levitte** [comment]
Errr, what the hell????

```
../master/apps/apps.c:2322:5: error: no previous prototype for 'fileno_stdin' [-Werror=missing-prototypes]
 int fileno_stdin()
     ^~~~~~~~~~~~
../master/apps/apps.c:2328:5: error: no previous prototype for 'fileno_stdout'  -Werror=missing-prototypes]
 int fileno_stdout()
     ^~~~~~~~~~~~~
```

But...  those functions *are* declared, in `apps.h`!  And if I do a `-E` compile and check the output, it does show the declarations before the definitions of those functions.  I must be running blind.  Please help?

**Comment by dot-asm** [comment]
> But... those functions are declared, in apps.h!

Yeah... Except that declaration should be int `fileno_stdin(void);`. Yeah, it's essentially ridiculous...

**Comment by levitte** [comment]
Aaargh...

**Comment by levitte** [comment]
Okie, issue fixed, both here and in #1577

**Comment by dot-asm** [comment]
Seconded.

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
