### PR TITLE
Visual Studio compiler switch changes:  Stack probing, string pooling.

### PR DESCRIPTION
**Pull request by ideafarm**
CLA: trivial

This is truly a trivial change.  If you agree, please remove the "hold: cla required" tag.  On request, I will email a CLA.

Changed use of two compiler switches for Visual Studio (Windows):  /Gs0 removed.  (Nondefault stack probing.)  /GF removed for debug but not release.  (String pooling.)  Both changes are to fix problems stepping through code for "openssl.exe s_server -WWW".

### CODE REVIEW

**Comment by paulidale** [comment]
Are the 40Mbytes of files really required?

I'm very hesitant adding that much to the repository, it represents a double digit percentage increase in the size of OpenSSL.

**Comment by ideafarm** [comment]
No, the intended change is only a couple of edits.  I must have screwed up
the commit.  (I'm new at this.)  Please deny and close my pull request.  I
will submit another one, making sure that it doesn't contain other things.

--------------------------------
NOTICE:  This conversation will be published on IDEAFARM.COM.  (Click
"privacy" there.)
--------------------------------

**Comment by paulidale** [comment]
I'll have to let somebody knowledgeable about Visual Studio sort this one out -- more knowledge is zero (or possibly below due to misconceptions :)

It doesn't seem like your ICLA went through properly.  Could you please email legal@openssl.org and confirm the email address you are using for github?  Thanks.

**Comment by ideafarm** [comment]
This PR contains unintended changes, so I am closing it, with intent to open a new PR.

**Pull request closed without merging**
