### PR TITLE
Add Travis builds with GCC v5

### PR DESCRIPTION
**Pull request by ghedo**
This includes an additional debug build with address sanitizer enabled.

### CODE REVIEW

**Comment by ghedo** [comment]
All green, can be reviewed now!

**Comment by dot-asm** [comment]
Can you see if adding -fsanitize=undefined works? At some point it was sanitized even for undefined...

**Comment by dot-asm** [comment]
In the context of -fsanitize it might be appropriate be note that --strict-warnings can actually generate code different from production one, because it adds -DPEDANTIC, which masks few things. I also wonder how does -fsanitize work with optimization on. Or in other words I wonder if we might get more valuable feedback if we exercise -fsanitize *without* --debug and --strict-warnings...

**Comment by ghedo** [comment]
ubsan has the same problem as the clang's memory sanitizer in #434: it causes a ton of test failures so it needs additional work. Regarding the --debug thing, yes, ubsan finds more failures without debug and strict-warnings (not sure if strictly a superset or not, that is, debug builds may show different failures).

I made a couple of changes to this PR:
* Added non-debug builds with the sanitizer (but left the debug one as it is).
* Merged the basic clang-3.6 support (without msan) into this PR from #434.

What I propose is that we can merge this PR as it is to add the basic gcc-5 and clang-3.6 support with asan, close #434, and then I can work on making ubsan and msan happy separately, thoughts?

**Comment by dot-asm** [comment]
Sounds perfectly reasonable. +1

**Comment by richsalz** [comment]
merged and closed.  thanks.

**Comment by ghedo** [comment]
@richsalz seems like you merged the older gcc-5 commit, with only the sanitizer build with `--debug` (so it doesn't include the change I mentioned above, see https://github.com/ghedo/openssl/commit/0e39653978e22ca4b27a164597b699786258779d). It also didn't include the clang-3.6 support from https://github.com/ghedo/openssl/commit/6188f8db5641e11bece2d8de4e8c1778dbb8ca03, so the commit message seems strange (also considering that we already had clang support in there....)  Should I open a new PR to with the additional changes?

**Comment by richsalz** [comment]
please do.

**Comment by ghedo** [comment]
Ok, see #440.

**Comment by richsalz** [comment]
Yup, thanks, got it marked for review.

**Pull request closed without merging**
