### PR TITLE
Fix broken link to codingstyle.html

### PR DESCRIPTION
**Pull request by zuiderkwast**

### CODE REVIEW

**Review by DDvO — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Comment by tmshort** [comment]
@DDvO are you ok with merge to 3.0?

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Does this qualify as a policy change?  The trivial changes exception isn't a policy yet.  Thus if this is a policy change, there is a two week wait and a vote required.

**Comment by zuiderkwast** [comment]
@paulidale I give you one week. Then I withraw the PR. 🤔😝

**Comment by mspncp** [comment]
> Does this qualify as a policy change? The trivial changes exception isn't a policy yet. Thus if this is a policy change, there is a two week wait and a vote required.

@paulidale this is not a change in the `openssl/web` repository, it's simple fixing a broken link in the CONTRIBUTING file. I wouldn't consider that a policy change.

**Review by mspncp — APPROVED** [review]

**Comment by mspncp** [comment]
> @paulidale I give you one week. Then I withraw the PR. 🤔😝

If I were you, I would wait. Meanhwile, your PR has collected five approvals, only a few more remaining for an official OpenSSL record. ;-)

**Comment by DDvO** [comment]
This PR is ready to merge already since yesterday.
Unless anyone objects, I'll merge it tomorrow.

**Comment by DDvO** [comment]
BTW, I doubt that it was a smart move to change the URL of the coding guidelines at all
from https://www.openssl.org/policies/codingstyle.htm
to https://www.openssl.org/policies/technical/coding-style.htm

Many search engines etc. still point people to the old location.
At least, a forward pointer/redirect should be placed there.

**Comment by mspncp** [comment]
> BTW, I doubt whether it was a smart move to change the URL of the coding guidelines

I disagree. The change makes perfect sense if you look at the big picture, i.e., https://github.com/openssl/web/pull/312. And the search engines will adopt.

**Comment by mspncp** [comment]
Anyway, I agree that a redirect  or rewrite rule from the old URL to the new one might be helpful. (cc @levitte)

**Comment by paulidale** [comment]
Okay, this isn't a policy change.  It should be merged IMO.

**Comment by paulidale** [comment]
And merged, thanks for the fix.

**Pull request closed without merging**
