### PR TITLE
Add AES implementation in RISC-V64 Zkn asm

### PR DESCRIPTION
**Pull request by ZenithalHourlyRate**
This PR adds the support of AES implementation for RISC-V 64 platform with Zkn capability.

This PR is strongly related to #17640. Actually, to test this file, you should checkout that PR and replace `aes-riscv64.pl`  with it. As that PR has not been merged, these build infra (e.g. `build.info`)  is needed but not included. A more reasonable approach is discussed below.

This has been compiled using the lastest toolchain from [riscv-collab/riscv-gnu-toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain) and run against a QEMU that is currently [in a maintainer's tree](https://github.com/alistair23/qemu/tree/riscv-to-apply.next), and should be in the master branch shortly.
I have not explored the usability of Zk in the main branch/in ubuntu-latest version of gnu-toolchain, but QEMU definitely needs that patch.

For the toolchain to work, I have adopted the `.option arch` trick. For QEMU to work, we need to start QEMU in
the following way
```
qemu-system-riscv64 -cpu rv64,zkn=true
```

I have tested the correctness of these implemented functions using `qemu-user` with my own manual invoking of these functions, side by side with [riscv-crypto](https://github.com/riscv/riscv-crypto/tree/master/benchmarks/aes/zscrypto_rv64). `make test` will be done shortly after I have setup `qemu-system`. I do not have a RISC-V chroot recently.

BTW, I am a [hardware implementer of Zk/Zb](https://github.com/chipsalliance/rocket-chip/pull/2950).

Cc @hbrausen

##### Detection of features at compile time:
mainly discussed in #17640
##### Detection of features at runtime : environment variable or SIGILL or mconfigptr/misa or hwcap.

Currently #17640 uses environment variable to detect whether the CPU supports one extension. I think this is a temp workaround but I do accept it because there is just no other mature way.

Historically, OpenSSL has been using SIGILL to detect the capability of some instructions. I do appreciate this arcane but if it is done for a new ISA it is pitiful.

RISC-V Scalar Crypto Extension said the detection of one extension is still WIP. I know this [effort](https://github.com/riscv/configuration-structure/blob/master/schema/zk-extensions.asn) but it seems that it still has a long way to go from hardware to sbi, to bootloader, to kernel, then to userspace. After all, they are "M" mode things. Also, no matter how "M" mode things change, The kernel (e.g. Linux) still needs to offer some API to the userspace, one way is hwcaps, other ways are /proc/cpuinfo ad /proc/device-tree, which is not so acceptable as every userspace tool now has to bear a ISA string parser (seems no `riscv-software-src/riscv-isa-parser` though).

Then for userspace, AFAIK there are only 4 ways to go: env var, sigill, hwcap, procfs.

Personally I prefer hwcaps (e.g. glibc-hwcaps and `armcap.c` in OpenSSL), as this is more friendly for Linux Distributions as their binary is more portable now. (BTW I also work with a Linux distribution RISC-V port). 

I have worked on this in [my linux fork](https://github.com/ZenithalHourlyRate/linux/tree/riscv-zbzk-hwcap) and it has been tested. I will send this patch in one day or two after I have cleaned up it. But it is not so optimistic as Zb/Zk along takes 14 bits of `AT_HWCAP2`. For the compatibility of linux riscv32 both `AT_HWCAP` and `AT_HWCAP2` only have 32 bits available, and 26 bits of `AT_HWCAP` are reserved for single-letter extension now. I'm thinking of some thing like to `AT_HWCAP_PTR` or `AT_HWCAP_V` but it is far from mature now.

My planned route is that the device tree provides the full isa string (note that the current [dt binding spec in linux kernel](https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/riscv/cpus.yaml) does not disallow it), then the kernel parses device tree `riscv,isa` and enable some capability at `AT_HWCAP`/`AT_HWCAP2`, then the userspace tools can happily detect it.

After this patch I will try to make this change in device trees in [My PR for Rocket-Chip](https://github.com/chipsalliance/rocket-chip/pull/2950) and [Xiangshan](https://cs.github.com/OpenXiangShan/XiangShan/blob/92e3bfefd90c9c71e8a65e5955c61ee13765fb9d/src/main/scala/xiangshan/XSDts.scala#L33), which is another Zk/Zb implementer. Note that QEMU already provides `riscv,isa` like that.

Now it comes to the relation with #17640. After OpenSSL has happily detected the features of one RISC-V platform one day via some eventually existing mechanism, how does it dispatch the function call to one optimal implementation? Currently I find that `build.info` seems to be incapable of handling so much extensions/implementations; Also, I think all the implementations should be compiled and dispatch at runtime. I think that we should implement something like `aes_riscv.c` and dispatch it according to the runtime capability, just like the `RISCV_HAS_ZBB() && RISCV_HAS_ZBC()` had done in #17640, instead of both me and #17640 occupying the name of `AES_encrypt`/`AED_decrypt`.

Note that #17640 is not superseded by this PR and it is even more important than this PR as the actual implementation of Zb/Zk platform still takes a long time and rv64gc is still the main stream now.

A side note though, it seems that for other architecture even they have different ASM implementations, they provide different APIs to the library users (instead of internal different implementations) like `VPAES_ASM`. i.e. it seems that they do not have the problem like us.

#### Checklist

- [x] CLA is signed (will do so in one day or two once a printer is available)
- [x] passed `make test`
- [ ] documentation is added or updated
- [ ] CI/tests are added or update
- [x] toolchain is ready (e.g. hit ubuntu-latest) with Zk support
- [ ] qemu is ready with Zk support

Other good to have checklist

- [ ] Linux HWCAP or some other API
- [x] add riscv dispatch mechanism (together with #17640)
- [x] benchmark is provided (cycle accurate emulator like verilator) among this PR, #17640 and base C implementation.

### CODE REVIEW

**Comment by t8m** [comment]
We will need your ICLA (and possibly CCLA) to be signed to proceed. https://www.openssl.org/policies/cla.html

**Comment by cmuellner** [comment]
Note, that on RISC-V there is currently no capability discovery mechanism. There are several ideas floating around, but nothing has been concluded/implemented.

Therefore Henry's patch uses environment variables to provide the available RISC-V extensions. It should be easy to use this mechanism here as well. And once a HWCAP API is defined and available it should be trivial to switch to that. Also note, that the environment-variable mechanism is also used in the AArch64 code (i.e. nothing new here).

**Comment by ZenithalHourlyRate** [comment]
> We will need your ICLA (and possibly CCLA) to be signed to proceed. https://www.openssl.org/policies/cla.html

I've submitted my ICLA, please check that.

> Also note, that the environment-variable mechanism is also used in the AArch64 code (i.e. nothing new here).

Thanks for pointing this out!

> It should be easy to use this mechanism here as well.

Yes, I will add these files shortly. I do understand that this is the most convenient approach for now.

**Comment by hbrausen** [comment]
One thing to note: if you provide an ASM implementation of AES for an architecture, and enable AES_ASM in the build, the generic C implementation is then excluded from the build.

This means that the ASM implementation of AES -- the one that implements the low-level AES_encrypt() and AES_decrypt() routines -- should be generic, using only basic instructions, as the C routine cannot be used as a fallback.

How can we, then, enable crypto extensions at runtime? There needs to be a runtime check. Let's look at how aesni works for insipration: see `e_aes_cbc_hmac_sha1.c` for an example. You'll see the following:

`# define AESNI_CAPABLE   (1<<(57-32))`

and

```
const EVP_CIPHER *EVP_aes_128_cbc_hmac_sha1(void)
{
    return (OPENSSL_ia32cap_P[1] & AESNI_CAPABLE ?
            &aesni_128_cbc_hmac_sha1_cipher : NULL);
}
```

So you can see how the runtime mux works here. Note that if aesni is supported, I believe we call the aesni functions directly -- we do not call AES_encrypt(). So the muxing happens pretty far away from the `crypto/aes/*` source files in the codebase.

**Comment by ZenithalHourlyRate** [comment]
I've made several changes

1. rename the function name from generic `AES_encrypt` to `rv64i_zkne_encrypt` (also for other functions)
2. avoid `.option arch` completely using the same trick as #17640
3. add scalar crypto related capability (that file should merge into #17640 after it gets merged)
4. add runtime selection in `crypto/evp/e_aes` and `providers/implementations/ciphers`.

I think the toolchain issue is now resolved, but the Zk capable QEMU issue still exists.

I'm marking this PR as draft now as it depends on #17640 being merged, and it still waits for QEMU

After merging this PR with #17640, `demos/ciphers/aesgcm` now runs happily with both aes and ghash hardware acceleration

```
export OPENSSL_riscvcap="rv64gc_zknd_zkne_zbb_zbc"
qemu-riscv64 -cpu rv64,zknd=false,zkne=true,zbb=true,zbc=true
```
 
One concern here is that aes-gcm does not use `zknd` instructions but the current codebase needs to enable both zknd and zkne capability to work.

> So the muxing happens pretty far away from the `crypto/aes/*` source files in the codebase.

Thanks for pointing this out! This helped me a lot when I was finding out the runtime selection mechanism.

After digging around the codebase I found two places that uses these `CAPABLE` macro, one is `crypto/evp/e_aes` and another one is `providers/implementations/ciphers`. However, if I only add the selection to evp, it does not work (always fallback to the not accelerated version). So I did not know if the commit "evp: aes: add riscv64 zknd/zkne asm" is necessary or not, and when would that mechanism be used. Also I wonder what is the relationship between the mechanism in `crypto/evp/e_aes` and that in `providers/implementations/ciphers`.

**Comment by ZenithalHourlyRate** [comment]
I've made a benchmark of this PR and #17640 at https://gist.github.com/ZenithalHourlyRate/7b5175734f87acb73d0bbc53391d7140. Surprisingly, aes-cfb/ctr/ofb perform drastically worse than the C implementation. I'll look into it later.

**Comment by ZenithalHourlyRate** [comment]
> Surprisingly, aes-cfb/ctr/ofb perform drastically worse than the C implementation. I'll look into it later.

It turned out to be a memory alignment issue with some openssl internal struct. The detail can be found at https://gist.github.com/ZenithalHourlyRate/7b5175734f87acb73d0bbc53391d7140#file-2-openssl-long-md . I'll send a new PR with a better solution on this.

**Comment by ptomsich** [comment]
The Platform standardisation for the rich OS (i.e., Linux-class) operating systems requires fast unaligned accesses for all such platforms in its current drafts (this might even make it into Profiles).

**Comment by ZenithalHourlyRate** [comment]
> The Platform standardisation for the rich OS (i.e., Linux-class) operating systems requires fast unaligned accesses for all such platforms in its current drafts (this might even make it into Profiles).

Thanks for this information! Then misalignment handling in AES kernel is not needed in this PR.

I'll evaluate my implementation with aligned IV in further benchmarks as my platform is poor currently.

**Comment by kuroro99** [comment]
### Testing
The following testing has been done：
This PR was merged with https://github.com/openssl/openssl/pull/17640 and was built and run under qemu with both `OPENSSL_riscvcap="rv64gc_zba_zbb_zbc_zbs"`and `OPENSSL_riscvcap=""`.
Here are some details:
The qemu was built with 
```
-cpu rv64,zba=true,zbb=true,zbc=true,zbs=true,zbkb=true,zbkc=true,zbkx=true,\
zk=true,zkn=true,zknd=false,zkne=true,zknh=true,zkr=true,zks=true,zksed=true,zksh=true,zkt=true 
```
then run the first test with `OPENSSL_riscvcap=""`:
```
./Configure no-afalgeng
make  -j $(nproc)
make test -j $(nproc)
```
And here is the result 
```
All tests successful.
Files=248, Tests=3385, 6918 wallclock secs (109.70 usr 15.78 sys + 5673.22 cusr 1281.77 csys = 7080.47 CPU)
Result: PASS
```
Then run the second test:
```
export OPENSSL_riscvcap="rv64gc_zba_zbb_zbc_zbs"
make test -j $(nproc)
```
All passed

**Comment by ZenithalHourlyRate** [comment]
[CI](https://github.com/openssl/openssl/actions/runs/2336679910) failed because cb2764f2a8165421dc5ab52159af99cbf766fa2c in is master (i.e. infra is ready) but #17640 has not been merged (i.e. no aes-riscv64.pl)

Should retrigger CI after that one gets merged.

**Comment by ZenithalHourlyRate** [comment]
> run against a QEMU that is currently [in a maintainer's tree](https://github.com/alistair23/qemu/tree/riscv-to-apply.next), and should be in the master branch shortly.

Side note: QEMU support for RISC-V scalar crypto has landed on master. Ref to https://github.com/qemu/qemu/commit/731340813fdb4cb8339edb8630e3f923b7d987ec

**Comment by ZenithalHourlyRate** [comment]
evp support is reverted as maintaining both provider and evp API is painful. I can not find a way to use the evp API so I can not test it either. I think the provider API is sufficient now.

As #17640 has been merged, this PR is ready for review. For the ease of review new changes (e.g. mergeing with master) are in new commit instead of fixing the previous commits. When it is ready for merge, I'll rebase it and make the history clean.

**Comment by t8m** [comment]
CI is relevant. Yeah, having this applied to providers should be sufficient.

**Comment by ZenithalHourlyRate** [comment]
> CI is relevant.

CI passed

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
I see there are merge commits. Could you please rebase this branch on top of the master and drop the merge commits? (`git rebase -i` can help.)

**Comment by ZenithalHourlyRate** [comment]
> Could you please rebase this branch on top of the master and drop the merge commits?

Done

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
@paulidale still OK?

**Review by paulidale — APPROVED** [review]
Still approved.

**Comment by ZenithalHourlyRate** [comment]
This still passes `make test` (done by @kuroro99)

```
All tests successful.
Files=249, Tests=3379, 7169 wallclock secs (121.12 usr 15.69 sys + 5875.42 cusr 1322.52 csys = 7334.75 CPU)
Result: PASS
make[1]: Leaving directory '/root/openssl'
root@debian10-riscv64:~/openssl# echo $OPENSSL_riscvcap
rv64gc_zknd_zkne
```

The qemu argument
```
-cpu rv64,zba=true,zbb=true,zbc=true,zbs=true,zbkb=true,zbkc=true,zbkx=true,zk=true,zkn=true,zknd=false,zkne=true,zknh=true,zkr=true,zks=true,zksed=true,zksh=true,zkt=true
```

Could you please add a `Tested-by` tag when merging? Thanks!

```
Tested-by: Jiatai He <jiatai2021@iscas.ac.cn>
```

**Comment by t8m** [comment]
> Could you please add a `Tested-by` tag when merging? Thanks!

Yes, done.

Merged to master branch. Thank you for your contribution.

**Comment by ZenithalHourlyRate** [comment]
FYI, this PR and all the following PRs (#18285, #18287, #18289, #18290, #18308) on RISC-V Zk are part of my undergraduate thesis (in Chinese) and I have made it public in my blog. Any one interested could find it [here](https://blog.zenithal.me/2022/06/25/%E6%9C%AC%E7%A7%91%E6%AF%95%E4%B8%9A%E8%AE%BA%E6%96%87-%E5%9F%BA%E4%BA%8E-Chisel-%E5%AE%9E%E7%8E%B0-RISC-V-%E6%8C%87%E4%BB%A4%E9%9B%86%E6%A0%87%E9%87%8F%E5%AF%86%E7%A0%81%E5%AD%A6%E6%89%A9%E5%B1%95/) and there are two presentations (in English) on that thesis.

**Pull request closed without merging**
