### PR TITLE
3.0 PEM reading perf cherry picks: PR 17881, 18354 and 17921

### PR DESCRIPTION
**Pull request by krk**
This PR cherry picks 3 performance improvements, removing lock contention while reading PEM files, improving `ossl_lh_strcasehash` and decoder resolution speed:

1. https://github.com/openssl/openssl/commit/927d0566ded0dff9d6c5abc8a40bb84068446b76 from https://github.com/openssl/openssl/pull/17881
2. https://github.com/openssl/openssl/commit/a4e21d18d5b7cb4fef66c10f13b1b3b55945439f from https://github.com/openssl/openssl/pull/18354
3. https://github.com/openssl/openssl/commit/4a1108eb5906cd3cf47a3f70bd58722dbe2023a4 from https://github.com/openssl/openssl/pull/17921

### CODE REVIEW

**Comment by paulidale** [comment]
OTC: **do we want these changes in 3.0?**

**Comment by beldmit** [comment]
What is the performance boost after applying these patches?

**Comment by slontis** [comment]
This doesnt currently build.

**Comment by paulidale** [comment]
OTC: this should not go into 3.0

**Comment by krk** [comment]
What is the policy for getting an exception so that these would land on the 3.0 branch?

**Comment by slontis** [comment]
OTC votes on issues such as these.
Once you start applying 'exceptions' to stable branches it can become a slippery slope of changes being applied. Some of the performance changes (such as the libctx locking) are quite complex and it becomes hard to argue that this should be an exception.
As there is also a 3.1 release coming (that should be released today), that contains all the fixes, the changes are not likely to be merged back to 3.0. Note that if you need FIPS you can build the OpenSSL 3.0 FIPS provider and use it with OpenSSL 3.1 (which supplies libcrypto, and the providers default, base and legacy). This gives you a validated FIPS 140-2 module as well as all the fixes.

**Comment by krk** [comment]
Thanks a lot for the explanation of the process. Now that OpenSSL 3.1 is out, I will not apply for an exception on top of 3.0.x.

**Pull request closed without merging**
