### PR TITLE
fips: make installations FIPS compliant by default

### PR DESCRIPTION
**Pull request by paulidale**
- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by slontis** [comment]
Not sure how this doesnt break some test somewhere?

**Comment by paulidale** [comment]
None of our tests broke.  Our test suite doesn't rely on the file this generates.

**Comment by mspncp** [comment]
Shouldn't there be a big heads-up in NEWS and/or CHANGES for this change? See also @beldmit's https://github.com/openssl/technical-policies/pull/69#issuecomment-1623075276.

**Comment by paulidale** [comment]
@mspncp, I'd prefer to add that separately.  This is the minimal immediate time critical fix.

**Comment by paulidale** [comment]
Needing second approval now that the vote has finished.

**Comment by paulidale** [comment]
What would the changes/news entry say?

The fips provider is now installed in a compliant manner by default?

**Review by slontis — APPROVED** [review]

**Comment by mattcaswell** [comment]
> What would the changes/news entry say?

It should talk about the change in default behaviour with truncated hashes and EMS (and the reasons why we're making this breaking change)

**Comment by beldmit** [comment]
Smth like "This is a strict NIST requirement and it is breaking compatibility with old systems that don't support either EMS in TLS 1.2 or TLS 1.3"

**Comment by paulidale** [comment]
Merged, thanks for the reviews.

**Pull request closed without merging**
