### PR TITLE
Set the default value of id to SM2_DEFAULT_USERID when signing and verifying with sm2.

### PR DESCRIPTION
**Pull request by xicilion**
##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by nhorman** [comment]
can you please sign an icla so that we can review and potentially accept this change?

**Comment by xicilion** [comment]
I have signed an ICLA before. Do I need to sign it separately for each PR?

**Comment by nhorman** [comment]
no, you shouldn't have to, but that makes me wonder why the cla check is failing.  Let me try close and reopen the pr to run the test again

**Comment by nhorman** [comment]
no, still failing.  The cla check is failing against your email address lion@xxxxxxxx

Is that the email you signed the cla against?

**Comment by xicilion** [comment]
yes it is.

**Comment by nhorman** [comment]
@quarckster any chance you can fixup the cla database regarding the incorrect email address described [above](https://github.com/openssl/openssl/pull/25005#issuecomment-2251244638)

**Comment by xicilion** [comment]
haha, thank you.

**Review by nhorman — APPROVED** [review]

**Comment by mattcaswell** [comment]
I'd like @InfoHunter's opinion on this. I am fairly sure there is a reason why this hasn't been done before.

**Comment by xicilion** [comment]
This is also a confusing point for me, because without setting this default value, users need to add extra parameters every time they use openssl for SM2 signing. Also, the absence of this default value has caused discrepancies between the SM2 signature results in many languages (such as Node.js) and the results after adding parameters in openssl.

**Comment by InfoHunter** [comment]
> I'd like @InfoHunter's opinion on this. I am fairly sure there is a reason why this hasn't been done before.

Right, there is a reason, should date back to 2018...

> This is also a confusing point for me...

You are not the only one coming up with this idea and similar patch ;-), read this: https://github.com/openssl/openssl/pull/23162#issuecomment-1871741691

**Comment by mattcaswell** [comment]
Thanks @InfoHunter. Given this opinion I think we should not proceed with this PR.

**Comment by InfoHunter** [comment]
> Given this opinion I think we should not proceed with this PR.

Right. I am going to add this PR a 'won't fix' label

**Pull request closed without merging**
