### PR TITLE
Add support for llvm proof formulas

### PR DESCRIPTION
**Pull request by levitte**
This adds base support for the stuff that #2148 need to build cleanly as part of our build system.

In addition to this, #2148 needs some modifications...  that's for a different PR.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by richsalz — DISMISSED** [review]

**Comment by levitte** [comment]
Well, I'm waiting on the continued discussion in #2148...

**Comment by levitte** [comment]
If #2147 is closed, this should be closed.  I'll wait and see what happens there.

**Comment by richsalz** [comment]
Perhaps a new tag "parked" (ietf working groups use that), kinda like hold, but meaning waiting for someone else to pick it up?

**Comment by levitte** [comment]
Closing this since #2148 just got closed.

**Pull request closed without merging**
