### PR TITLE
Document OSSL_SERIALIZER_PUBKEY_TO_DER_PQ and friends

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by slontis** [comment]
travis failed so rebuilding..

**Comment by levitte** [comment]
> Looks like travis has errors ..

.... argh

**Comment by levitte** [comment]
Travis failure fixed, I hope

**Comment by levitte** [comment]
> Approved provided the appveyor tests pass.

If it doesn't, it's not relevant here.  We don't do documentation checks on Appveyor :wink:

**Comment by slontis** [comment]
> If it doesn't, it's not relevant here. We don't do documentation checks on Appveyor 😉

Wouldnt suprise me if it failed.  I have never seen util/other.syms before... :)

**Comment by levitte** [comment]
> Wouldnt suprise me if it failed. I have never seen util/other.syms before... :)

We used to call it `private.num` (still do in 1.1.1), which was a bad name as it had nothing to do with any kind of enumeration.

Anyway, it's used by `util/find-doc-nits` only, so...

**Comment by levitte** [comment]
Merged

9ea59241745e0ca17dc05a142544aca032cc75a0 Document OSSL_SERIALIZER_PUBKEY_TO_DER_PQ and friends

**Pull request closed without merging**
