### PR TITLE
Fix unit tests when no-bf

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Shouldn't the implementation in `bftest` be done similarly to the `casttest` one?

**Comment by tmshort** [comment]
One would think so; but bftest uses a custom test_main(), whereas casttest uses the standard test_main()

**Comment by levitte** [comment]
Idea:

``` C
int test_main(int argc, char *argv[])
{
    int ret;
#ifndef OPENSSL_NO_BF
# ifdef CHARSET_EBCDIC
    int n;

    ebcdic2ascii(cbc_data, cbc_data, strlen(cbc_data));
    for (n = 0; n < 2; n++) {
        ebcdic2ascii(bf_key[n], bf_key[n], strlen(bf_key[n]));
    }
# endif

    ADD_ALL_TESTS(test_bf_ecb_raw, 2);
    ADD_ALL_TESTS(test_bf_ecb, NUM_TESTS);
    ADD_ALL_TESTS(test_bf_set_key, KEY_TEST_NUM-1);
    ADD_TEST(test_bf_cbc);
    ADD_TEST(test_bf_cfb64);
    ADD_TEST(test_bf_ofb64);

    if (argc > 1)
        ret = print_test_data();
    else
#endif
        ret = run_tests(argv[0]);

    return ret;
}
```

**Comment by tmshort** [comment]
trying to avoid multiple defintions of test_main?

**Comment by levitte** [comment]
Yes, and most of all, we use the test framework either way, the only output difference is that it says "bftest: 0 test cases".  Also, since we're already doing exactly this with a number of tests (and you propose that for `casttest`), I'm thinking that consistency is king as well.

**Comment by tmshort** [comment]
cast was previously fixed; this just includes bf now.

**Comment by richsalz** [comment]
80b06b0 in master; thanks!

**Pull request closed without merging**
