### PR TITLE
Configure: base compiler-specific decisions on pre-defines.

### PR DESCRIPTION
**Pull request by dot-asm**
The commit subject is a bit misleading in sense that decisions affect
only gcc and gcc-alikes, like clang, recent icc...

### CODE REVIEW

**Comment by dot-asm** [comment]
Well, this doesn't preclude possibility of remodeling the way the warning flags are accessed. I mean something similar to #4275, it simply changes "base-line" for it...

**Comment by levitte** [comment]
Yup, #4275 can certainly be adapted.

But, this means that we're taking a first step at an autoconf-like check of on location features.  Not that I mind, rather the contrary!  I just find that notable (I'll be certain to follow up for 1.2.0 ;-) )

**Comment by richsalz** [comment]
+1 to backport

**Comment by dot-asm** [comment]
It didn't cherry-pick :-( Hence, #4291...

**Pull request closed without merging**
