### PR TITLE
obj: Add SM4 GCM/CCM OID

### PR DESCRIPTION
**Pull request by uudiin**
Add the following OID:

  SM4-GCM: 1.2.156.10197.1.104.8
  SM4-CCM: 1.2.156.10197.1.104.9

Signed-off-by: Tianjia Zhang <tianjia.zhang@linux.alibaba.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
The test failure seems relevant but I'm not at all sure why.

**Comment by beldmit** [comment]
Is it a `make update` failure or you forgot to commit the fuzz.txt changes by accident?

**Comment by uudiin** [comment]
> Is it a `make update` failure or you forgot to commit the fuzz.txt changes by accident?

Thanks for pointing it out, `fuzz/oids.txt` has updated already.

**Review by beldmit — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master. Thank you for your contribution.

**Pull request closed without merging**
