### PR TITLE
All lh_stats functions were deprecated not just some

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Comment by mspncp** [comment]
Since you had to touch macros.h anyway, would you mind to also cherry-pick 4d5cfb229be8a52cdf961d9b7c5f6c1c0fa3b4f7? Since it was just a typo in the comment, it wasn't backported.

**~/src/openssl/3.1$ git diff gh-22248 gh-22247  --  include/openssl/macros.h**

```patch
diff --git a/include/openssl/macros.h b/include/openssl/macros.h
index a614cd66e3..e9ef938747 100644
--- a/include/openssl/macros.h
+++ b/include/openssl/macros.h
@@ -158,7 +158,7 @@
 /*
  * Define macros for deprecation and simulated removal purposes.
  *
- * The macros OSSL_DEPRECATED_{major}_{minor} are always defined for
+ * The macros OSSL_DEPRECATEDIN_{major}_{minor} are always defined for
  * all OpenSSL versions we care for.  They can be used as attributes
  * in function declarations where appropriate.
  *
@@ -169,6 +169,7 @@
  * 'no-deprecated'.
  */
 
+# undef OPENSSL_NO_DEPRECATED_3_1
 # undef OPENSSL_NO_DEPRECATED_3_0
 # undef OPENSSL_NO_DEPRECATED_1_1_1
 # undef OPENSSL_NO_DEPRECATED_1_1_0
```

**Comment by mspncp** [comment]
> would you mind to also cherry-pick 4d5cfb229be8a52cdf961d9b7c5f6c1c0fa3b4f7

Alternatively, you can just do the simple fix yourself without a cherry-pick.

**Comment by t8m** [comment]
> Since you had to touch macros.h anyway, would you mind to also cherry-pick [4d5cfb2](https://github.com/openssl/openssl/commit/4d5cfb229be8a52cdf961d9b7c5f6c1c0fa3b4f7)? Since it was just a typo in the comment, it wasn't backported.
> 
> **~/src/openssl/3.1$ git diff [gh-22248](https://github.com/openssl/openssl/pull/22248) [gh-22247](https://github.com/openssl/openssl/pull/22247) -- include/openssl/macros.h**
> 
> ```diff
> diff --git a/include/openssl/macros.h b/include/openssl/macros.h
> index a614cd66e3..e9ef938747 100644
> --- a/include/openssl/macros.h
> +++ b/include/openssl/macros.h
> @@ -158,7 +158,7 @@
>  /*
>   * Define macros for deprecation and simulated removal purposes.
>   *
> - * The macros OSSL_DEPRECATED_{major}_{minor} are always defined for
> + * The macros OSSL_DEPRECATEDIN_{major}_{minor} are always defined for
>   * all OpenSSL versions we care for.  They can be used as attributes
>   * in function declarations where appropriate.
>   *
> @@ -169,6 +169,7 @@
>   * 'no-deprecated'.
>   */
>  
> +# undef OPENSSL_NO_DEPRECATED_3_1
>  # undef OPENSSL_NO_DEPRECATED_3_0
>  # undef OPENSSL_NO_DEPRECATED_1_1_1
>  # undef OPENSSL_NO_DEPRECATED_1_1_0
> ```

I was not touching the macros.h on 3.1 branch yet. Are these changes really worth it?

**Comment by mspncp** [comment]
> I was not touching the macros.h on 3.1 branch yet.

My fault, I looked at the change set of #22248.

> Are these changes really worth it?

Nah, it's ok, no need to do it.

**Review by mspncp — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
