### PR TITLE
Fix a nit of copyright date range

### PR DESCRIPTION
**Pull request by InfoHunter**
Should be 2018 instead of 20018.

[skip ci]

### CODE REVIEW

**Comment by InfoHunter** [comment]
Pushed to master (5c1bd555d3c81cbd46d5032e84c29d16bb4a8f06)

Thanks guys!

**Comment by mspncp** [comment]
Side note: I wouldn’t call an off-by-18000-error a nit. ;-)

**Comment by mspncp** [comment]
But now seriously: Shouldn't this fix be backported to 1.1.1?

https://github.com/openssl/openssl/blob/a7ee1ef61b1893038008691a4a6979cf2da91439/crypto/poly1305/poly1305_ieee754.c#L2

**Comment by InfoHunter** [comment]
I agree to cherry-pick to 1.1.1, will do that soon

**Comment by InfoHunter** [comment]
Pushed to 1.1.1 as 8848b14fda7eded1c5a88f9f84eb13dcf69c3960

**Pull request closed without merging**
