### PR TITLE
Do not falsely start the QUIC connection through some SSL functions

### LINKED ISSUE #25054: QUIC when used via s_client fails to populate quic_transport_parameters extension in client hello
While investigating interop testing, I was experimenting with https://interop.seemann.io/?run=2024-07-30T08:28 .

Specifically when running an interop test between our s_client implementation for quic and the quic-go implementation, I noted that the quic-go implementation dropped a connection from s_client indicating a fatal error due to the initial source connection id being unspecified.

Interestingly, when I attempted the same test with a slightly modified version of quic-client-non-block (modified to pass the h3 alpn), the connection succeded.

A comparitive tcpdump set revealed the following:

When using quic-client-non-block:
Screenshot from 2024-07-30 15-10-01

When using s_client:
Screenshot from 2024-07-30 15-10-34

note in the quic-client-non-block case the quic_transport_parameters extension is specified and several parameters are included, while in the s_client case, the extension is added, but without any parameters.

Some debugging revealed that in the quic-client-non-block case, the parameters are generated during a call to SSL_connect

In the s_client case SSL_connect is not called. As a result, while ossl;_quic_channel_start gets called during the handshake, it occurs _after_ tls_construct_extensions is called

### PR DESCRIPTION
**Pull request by t8m**
Fixes #25054

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by nhorman** [comment]
unfortunately this doesn't seem to fix this issue in #25054 .  Gives the same error as previously

**Comment by nhorman** [comment]
Additional data, the handshake is no longer driven by the call to SSL_has_pending, but the handshake is then generated by the later call in s_client_main to SSL_handle_events which goes through this stack:
```
#0  tls_construct_extensions (s=0x5724d0, pkt=0x7fffffffd030, context=128, x=0x0, chainidx=0) at ssl/statem/extensions.c:853
#1  0x00007ffff7f53f64 in tls_construct_client_hello (s=0x5724d0, pkt=0x7fffffffd030) at ssl/statem/statem_clnt.c:1344
#2  0x00007ffff7f50d93 in write_state_machine (s=0x5724d0) at ssl/statem/statem.c:894
#3  0x00007ffff7f50076 in state_machine (s=0x5724d0, server=0) at ssl/statem/statem.c:487
#4  0x00007ffff7f4faa8 in ossl_statem_connect (s=0x5724d0) at ssl/statem/statem.c:297
#5  0x00007ffff7ec660d in SSL_do_handshake (s=0x5724d0) at ssl/ssl_lib.c:4760
#6  0x00007ffff7f19f95 in ossl_quic_tls_tick (qtls=0x584c60) at ssl/quic/quic_tls.c:795
#7  0x00007ffff7ef76ef in ch_tick_tls (ch=0x576d30, channel_only=0) at ssl/quic/quic_channel.c:1993
#8  0x00007ffff7ef74c5 in ossl_quic_channel_subtick (ch=0x576d30, res=0x7fffffffd2d0, flags=0) at ssl/quic/quic_channel.c:1904
#9  0x00007ffff7f0722f in ossl_quic_port_subtick (port=0x576140, res=0x7fffffffd330, flags=0) at ssl/quic/quic_port.c:379
#10 0x00007ffff7efbdfa in qeng_tick (res=0x7fffffffd380, arg=0x5760b0, flags=0) at ssl/quic/quic_engine.c:137
#11 0x00007ffff7f08a4b in ossl_quic_reactor_tick (rtor=0x5760d8, flags=0) at ssl/quic/quic_reactor.c:109
#12 0x00007ffff7eff742 in ossl_quic_handle_events (s=0x572330) at ssl/quic/quic_impl.c:1068
#13 0x00007ffff7ecc6b7 in SSL_handle_events (s=0x572330) at ssl/ssl_lib.c:7353
#14 0x000000000046bf1c in s_client_main (argc=6, argv=0x7fffffffdda0) at apps/s_client.c:3062
#15 0x00000000004544d5 in do_cmd (prog=0x51e790, argc=6, argv=0x7fffffffdda0) at apps/openssl.c:426
#16 0x00000000004540e7 in main (argc=6, argv=0x7fffffffdda0) at apps/openssl.c:307
```

Note the call to ossl_quic_tls_tick, which is passed a QUIC_TLS object.  These objects are created in ossl_quic_new as SSL_TYPE_SSL_CONNECTION.  As such they go through the regular TLS path rather than the QUIC handshake path, which generally seems fine, but the call to tls_construct_extensions is made prior to those parameters getting generated (as this path never calls ossl_quic_do_handshake).

**Review by nhorman — APPROVED** [review]

**Comment by mattcaswell** [comment]
> Additional data, the handshake is no longer driven by the call to SSL_has_pending, but the handshake is then generated by the later call in s_client_main to SSL_handle_events which goes through this stack:

Similarly it seems to me we should not be initiating a connection from `SSL_handle_events()`.

**Comment by nhorman** [comment]
that fixes the issue

**Comment by t8m** [comment]
@mattcaswell @nhorman please reapprove

**Comment by nhorman** [comment]
approval holds

**Review by mattcaswell — APPROVED** [review]

**Comment by nhorman** [comment]
merged to master and 3.3.  3.2 appears to have some significant conflicts that may require a separate pr.  @t8m if  you could take a look at that please

**Review by shahsb — APPROVED** [review]

**Comment by t8m** [comment]
Backport in #25082

**Pull request closed without merging**
