### PR TITLE
Coverity fixes

### PR DESCRIPTION
**Pull request by kaduk**
Attempt to fix some issues reported by coverity.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Does any of this apply to 1.1.0?

**Comment by richsalz** [comment]
No, it was just introduced by recent changes to ocsptest.

**Comment by kaduk** [comment]
Well, #4723 is still pending and does backport the new ocspapitest to 1.1.0.
But I plan to apply the relevant commits from here on that pull request before merging.

**Comment by kaduk** [comment]
This was incorporated into #4873 (qualitatively, at least -- it seems I forgot that this one was already open), so closing.

**Pull request closed without merging**
