### PR TITLE
d2i_X509: revert calling X509v3_cache_extensions()

### LINKED ISSUE #13754: d2i_X509 and d2i_X509_AUX behavior has become inconsistent and non-intuitive and is not documented
@slontis wrote in https://github.com/openssl/openssl/pull/12153#issuecomment-650094516:

> NOTE that `d2i_X509()` calls `X509v3_cache_extensions()` if the cert object is passed in.

Why has this non-intuitive behavior been added? At least, this must be documented.
If calling `X509v3_cache_extensions()` is really helpful then better do this also in case no cert object is passed in.

(**Update:** The issue described in this paragraph is fixed by #13755:
The call of  `X509v3_cache_extensions()` causes trouble: if the caller passed in a pointer to a NULL cert pointer the caller must be very careful in case NULL is returned after the cert was parsed successfully but is invalid such that `X509v3_cache_extensions()` failed.
In this case the caller needs to free the cert object which has been allocated regardless.)

I have already fixed part of this in #13755 (because I needed it there) such that `d2i_X509()` behaves consistently at least with `d2i_X509_AUX`, which deallocates the just created cert object in case an error occurred in its further processing. This way a mem leak is avoided.

@slontis, ~do you agree with the small improvement I did, and~ 
can you please properly document `d2i_X509()` and `d2i_X509_AUX()`?
The description in `i2d doc/man3/d2i_X509.pod` so far does not cover that new special feature of conditionally calling `X509v3_cache_extensions()`in `d2i_X509()` and thus also in `d2i_X509_AUX()`.
Moreover, the deallocation behavior for any passed-in object pointer is not documented for any `d2i_TYPE()` , neither for  `d2i_X509_{CERT_,}AUX()`.

### PR DESCRIPTION
**Pull request by DDvO**
Fixes #13754

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
I think I explained to you why it was doing this.
i.e. By the time the load has finished the X509 object should be setup (which is why it did the caching here also).

Are you sure ossl_x509v3_cache_extensions() is now called everywhere where it needs to be? Some of these calls may have been removed in the original PR that did the change.

**Comment by DDvO** [comment]
> I think I explained to you why it was doing this.
> i.e. By the time the load has finished the X509 object should be setup (which is why it did the caching here also).

Yes, but thinking more about it, the conclusion is that this is not the right level to add the call of `X509v3_cache_extensions().`
For cert objects, we have essentially three levels:

1. structure construction (by parsing or generation from scratch)
2. caching structure internals
3. use of the structure

As I mentioned in https://github.com/openssl/openssl/issues/13754#issuecomment-857703049,
adding `X509v3_cache_extensions()` may make `d2i_X509()` and `d2i_X509_AUX()` fail unexpectedly (you did not document this),
and worse: it needlessly prevents the use of for low-level parsing/loading certs that may be somewhat malformed, which may be crucial for instance for negative tests.
So we must not mix up levels 1 and 2.

BTW, you pointed out yourself in https://github.com/openssl/openssl/issues/13754#issuecomment-754949701 that
* you were uncertain under which exact situations `ossl_x509v3_cache_extensions()` should be called in `d2i_x509()`
* and that there are situations where adding it there is not sufficient, namely if X509 structures are embedded as sub-structures of larger ones.

The correct solution is to do the caching independently of cert structure construction.
The right place to make sure completeness of caching is whenever a cache item is about to be used.
And as far as I recall from `x509_vfy.c` and `v3_purp.c`, this has been done since long.

> Are you sure `ossl_x509v3_cache_extensions()` is now called everywhere where it needs to be?

Yes. At least in `x509_vfy.c` and `v3_purp.c` it is (indirectly) called more than often, and so far no case is known where it is was missing.
If it was missing anywhere, this would come up immediately: the cert would appear 'naked', and CA certs would not be recognized as such.
The question could also go in the other direction: Did you identify any case where `ossl_x509v3_cache_extensions()` was not called, although needed?

> Some of these calls may have been removed in the original PR that did the change.

I checked in #12153: you did not remove any previous call to  `ossl_x509v3_cache_extensions()` but just added it to `d2i_X509()`.
So also from this perspective we are safe to remove it again.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
As this basically reverts to what we have in 1.1.1 I think this change is right.

**Comment by DDvO** [comment]
Merged - thanks @t8m

**Pull request closed without merging**
