### PR TITLE
Work around Windows ftell() bug as per Microsoft engineering's suggestion

### PR DESCRIPTION
**Pull request by levitte**
See
https://developercommunity.visualstudio.com/content/problem/425878/fseek-ftell-fail-in-text-mode-for-unix-style-text.html

### CODE REVIEW

**Comment by levitte** [comment]
I have no idea if Cygwin is affected by this...

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Merged

8300a8742b2abc487594a09b5e6ee726dbd30771 Work around Windows ftell() bug as per Microsoft engineering's suggestion

**Comment by mspncp** [comment]
@levitte once again, I was surprised to see a low number pull request (`gh-2067`) in my fetch list:


**gh-2067**

    msp@msppc:~/src/openssl$ git fetch github
    remote: Enumerating objects: 199, done.
    remote: Counting objects: 100% (199/199), done.
    remote: Compressing objects: 100% (38/38), done.
    remote: Total 203 (delta 161), reused 189 (delta 160), pack-reused 4
    Receiving objects: 100% (203/203), 175.46 KiB | 223.00 KiB/s, done.
    Resolving deltas: 100% (161/161), completed with 101 local objects.
    From https://github.com/openssl/openssl
       4b7595e3ec..b11aa831cf  OpenSSL_1_1_1-stable -> github/OpenSSL_1_1_1-stable
       0a737e16b2..8300a8742b  master               -> github/master
     + 16dd5f9e44...da96b3e904 refs/pull/12998/head -> github/gh-12998  (forced update)
     + a0b2a60158...bbbec78831 refs/pull/13116/head -> github/gh-13116  (forced update)
       f56aafac14..5ea7cd15cf  refs/pull/13140/head -> github/gh-13140
       2c59531420..b743c099df  refs/pull/13189/head -> github/gh-13189
     + 54f766cbc5...a1e5350720 refs/pull/13195/head -> github/gh-13195  (forced update)
     + b8c30f6bbc...c25747b32f refs/pull/13198/head -> github/gh-13198  (forced update)
     * [new ref]               refs/pull/13199/head -> github/gh-13199
     * [new ref]               refs/pull/13200/head -> github/gh-13200
     * [new ref]               refs/pull/13201/head -> github/gh-13201
     * [new ref]               refs/pull/13202/head -> github/gh-13202
     * [new ref]               refs/pull/13204/head -> github/gh-13204
     * [new ref]               refs/pull/13207/head -> github/gh-13207
       0a737e16b2..8300a8742b  refs/pull/2067/head  -> github/gh-2067


As the merge comment correctly indicates, this commit was just merged by you and belongs to this pull request.

    commit 8300a8742b2abc487594a09b5e6ee726dbd30771 (origin/master, origin/HEAD, github/master, github/gh-2067)
    Author: Richard Levitte <levitte@openssl.org>
    Date:   Tue Oct 20 06:48:10 2020 +0200
    
        Work around Windows ftell() bug as per Microsoft engineering's suggestion
        
        See
        https://developercommunity.visualstudio.com/content/problem/425878/fseek-ftell-fail-in-text-mode-for-unix-style-text.html
        
        Reviewed-by: Paul Dale <paul.dale@oracle.com>
        (Merged from https://github.com/openssl/openssl/pull/13190)


I get those `github/gh-*` references, because I added a fetch rule
```
remote.github.fetch=+refs/pull/*/head:refs/remotes/github/gh-*
```
But it is not a local problem, because `git ls-remote` shows that the `refs/pull/13190/merge` reference is missing in openssl/openssl:

    msp@msppc:~/src/openssl$ git ls-remote github | grep -e /2067/ -e /13190/
    82d1ca56fc4bb730ef55252a3a74ddd6125bc4b5    refs/pull/13190/head
    8300a8742b2abc487594a09b5e6ee726dbd30771    refs/pull/2067/head
    8f4b62db049555c01f35a1c13a08a81dea4fea60    refs/pull/2067/merge

One possible explanation for this could be that somehow the commit id 8300a8742b2abc487594a09b5e6ee726dbd30771 was erroneously written to `refs/pull/2067/head` instead of `refs/pull/13190/head`.

This might simple be a GitHub bug. Or is it possible that this strange bug is caused by one of our scripts? (E.g., some hook script on GitHub, or the mirror hook script from git.openssl.org to GitHub?)

**Comment by mspncp** [comment]
Moved into a separate issue #13209.

**Comment by joshcooper** [comment]
We ran into this issue after discovering openssl 3.0.12 on Windows makes 116k calls to `ReadFile` when loading the default `cert.pem`, reading 2 bytes each time. It can be reproduced using:

```
#include <openssl/ssl.h>

int main(int argc, char **argv)
{
    SSL_CTX* ctx = SSL_CTX_new(TLS_client_method());
    SSL_CTX_set_default_verify_file(ctx);
    return 0;
}
```

Seems like changing this line to `rb` mode would avoid the perf penalty (with the caveat `cert.pem` has to contain `\n` line endings):

 https://github.com/openssl/openssl/blob/c3cc0f1386b0544383a61244a4beeb762b67498f/crypto/x509/by_file.c#L226

**Pull request closed without merging**
