### PR TITLE
Workaround the relocation truncated to fit problem on m68k builds

### PR DESCRIPTION
**Pull request by t8m**
We add `-mxgot` to use 32bit GOT type.

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Comment by nhorman** [comment]
Note, I've opened https://github.com/openssl/openssl/pull/24030 to consider removing this arch entirely from CI as its not on any supported platform list

**Comment by t8m** [comment]
Marking as urgent as this is a recent CI regression fix.

**Comment by t8m** [comment]
@nhorman do you agree with urgent?

**Comment by nhorman** [comment]
Ack, concur urgent

**Review by slontis — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master, 3.3 and 3.2 branches. Thank you for the reviews.

**Pull request closed without merging**
