### PR TITLE
Fix CHANGES.md issues reported by markdownlint

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
Heh, this i kind of a "You missed a spot!" PR :wink:

**Comment by levitte** [comment]
This one is URGENT.  Builds are failing!

**Comment by levitte** [comment]
Merged

885a2a399dcf25860f471e59af43db2917c39335 Fix CHANGES.md issues reported by markdownlint

**Comment by richsalz** [comment]
This was also fixed by #11770 as well, which all added a new make target :(  I wish that had been marked urgent.  What should I do with that PR?  Close it?  (@levitte you asked me to add commentary)

**Pull request closed without merging**
