### PR TITLE
Add documentation for the -sigopt option.

### LINKED ISSUE #8516: Commands 'req', 'x509' and 'ca': missing documentation for option '-sigopt'
Commands `req`, `x509` and `ca`: missing documentation for option '-sigopt'

Hi, I think I found a minor deficiency in manuals of `req(1)`, `x509(1)` and `ca(1)`:
they don't contain the description of option `-sigopt`;
I think it could be simply copied from `dgst(1)` manual:

```
=item B<-sigopt nm:v>

Pass options to the signature algorithm during sign or verify operations.
Names and values of these options are algorithm-specific.
```

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #8516 

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
I'll update the dates, they are automatically updated for a release so it isn't critical.

**Comment by slontis** [comment]
One handed typing in the title :)

**Comment by paulidale** [comment]
Merged, thanks @InfoHunter

**Comment by mspncp** [comment]
Backported to 1.1.1 via #10094.

**Pull request closed without merging**
