### PR TITLE
test/recipes/02-err_errstr: skip errors that may not be loaded on Windows

### LINKED ISSUE #8091: Windows7 nmake test failure test\recipes\02-test_errstr.t Dubious, test returned 19
Hello,
This is my first time working with OpenSSL so please forgive me if I have missed something obvious.

using  OpenSSL 3.0.0-dev according to README
(Should I maybe just take a step back and go to 1.1.1?)

I configured OpenSSL using:
>perl configure VC-WIN32

then successfully built using:
>nmake

from the Developer Cmd Prompt VS2015

Failure occurs when I run:
>nmake test

The following results, only one of the tests fails, command line returns:
image

"test\recipes\02-test_errstr.t .................... Dubious, test returned 19 <wstat 4864, 0x1300>
Failed 19/73 subtests "

All other tests come back as "ok" or "skipped" due to not available or not supported.

Test Summary Report is as follows:
image

Please let me know if you require any additional information.
Thank you for your time!

### PR DESCRIPTION
**Pull request by levitte**
Fixes #8091

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
travis is unhappy:
```
../../_srcdist/test/recipes/02-test_errstr.t ................... 
Bareword "EUCLEAN" not allowed while "strict subs" in use at ../../_srcdist/test/recipes/02-test_errstr.t line 45.
Bareword "ENOTNAM" not allowed while "strict subs" in use at ../../_srcdist/test/recipes/02-test_errstr.t line 45.
Bareword "ENAVAIL" not allowed while "strict subs" in use at ../../_srcdist/test/recipes/02-test_errstr.t line 45.
Bareword "ENOMEDIUM" not allowed while "strict subs" in use at ../../_srcdist/test/recipes/02-test_errstr.t line 45.
Bareword "ENOKEY" not allowed while "strict subs" in use at ../../_srcdist/test/recipes/02-test_errstr.t line 45.
Execution of ../../_srcdist/test/recipes/02-test_errstr.t aborted due to compilation errors.
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```

**Comment by levitte** [comment]
Fixed

**Comment by mattcaswell** [comment]
Travis still seems unhappy.

**Comment by levitte** [comment]
So a little bit of normal perl trickery might fix that issue.

**Comment by levitte** [comment]
Ping?

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

master:
6e68f244f48bd7118b9262ff5905da1c3b15cae9 test/recipes/02-err_errstr: skip errors that may not be loaded on Windows


1.1.1:
0e1b0e510dfe078b3fb2586d987d7b49ff8ef0b2 test/recipes/02-err_errstr: skip errors that may not be loaded on Windows

**Pull request closed without merging**
