### PR TITLE
Fix return value of ASN1_TIME_compare

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [ ] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
This overrides PR #4218

**Comment by tmshort** [comment]
Appveyor results seem unrelated (Perl & STORE?)

**Comment by tmshort** [comment]
ping @openssl/committers?

**Comment by dot-asm** [comment]
Rich, you should have set "pending 2nd review" to flag need for attention ;-)

**Comment by richsalz** [comment]
I set it on mine :)  But you're right.  Merging now.... done. thanks!

**Comment by dot-asm** [comment]
> I set it on mine :)

Original intention behind "pending 2nd review" was specifically for **2nd** review, i.e. for non-committer requests, or when 2nd opinion is requested. One might argue that it's appropriate to set the flag even for 1st review, if it's a hurry, or it doesn't get attention it deserves after some grace period, or something like that, but otherwise it's confusing...

**Comment by richsalz** [comment]
I was being light-hearted.  Yes, the 'pending 2nd' should be used regularly.

**Pull request closed without merging**
