### PR TITLE
Add GOST OIDs for Edwards parameter sets

### PR DESCRIPTION
**Pull request by longagofaraway**
Add OIDs for parameter sets of Edwards elliptic curves.

### CODE REVIEW

**Comment by kroeckx** [comment]
Do you plan to sign a CLA? If not, do you agree this is a trivial change and not covered by copyright?

**Comment by kroeckx** [comment]
You need to run make update and commit fuzz/oids.txt

**Comment by richsalz** [comment]
And if you agree, you need to put "CLA: trivial" in your comment text.

**Comment by longagofaraway** [comment]
Added fuzz/oids.txt to commit and "CLA: trivial" to commit message.

**Comment by richsalz** [comment]
Merged, thank you!

**Comment by richsalz** [comment]
Merged, thank you!

**Pull request closed without merging**
