### PR TITLE
Backport the RSA_get0_pss_params() function from master

### PR DESCRIPTION
**Pull request by mattcaswell**
This is a missing accessor in order to obtain PSS parameters from an
RSA key, which should also be available in 1.1.1.

Mostly this targets 1.1.1. However the second commit also updates the docs in master to add a HISTORY update, so that change will be applied to both branches.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Travis red cross was relevant due a doc-nits failure. Fixup pushed.

@levitte please can you reconfirm?

**Comment by t8m** [comment]
The Travis failure is still relevant.

**Comment by mattcaswell** [comment]
Another fixup pushed to address a different travis failure.

@levitte please reconfirm

**Comment by mattcaswell** [comment]
Travis is now happy. Ping @levitte?

**Comment by levitte** [comment]
A missing comma won't change my approval, it still holds.

**Comment by mattcaswell** [comment]
Pushed to 1.1.1 with second commit cherry-picked to master.

**Pull request closed without merging**
