### PR TITLE
Unify assembler scripts

### PR DESCRIPTION
**Pull request by levitte**
##  Build files: Unify standard arguments for assembler generating scrips

- Make the last argument always be the output file.
- Make the first argument always be the flavour, even if there is no
  flavour (i.e. it might become the empty string).
- Make the next to last argument to be $(PROCESSOR) if that one has a
  value.
- Remaining arguments are C prepropressor arguments.

Perl scripts that should handle this may use the following code:

    $output = pop;
    $flavour = shift;
    if ($ARGV[$#ARGV] eq '386') {
        # Do 386 specific things
    } else {
        # Do whatever else, with the knowledge the @argv contains
        # C preprocessor arguments
    }

Some scripts don't care about anything than $output, and that's ok.
Some scripts do care, but handle it a little differently, and that's
ok too (notably, the x86 scripts call asm_init() with the first and
the last argument after having popped $output).
As long as they handle the argument order right, they are going to
be fine.

## build.info: For all assembler generators, remove all arguments

Since the arguments are now generated in the build file templates,
they should be removed from the build.info files.

## Unify all assembler file generators

They now generally conform to the following argument sequence:

    script.pl "$(PERLASM_SCHEME)" [ C preprocessor arguments ... ] \
              $(PROCESSOR) <output file>

However, in the spirit of being able to use these scripts manually,
they also allow for no argument, or for only the flavour, or for only
the output file.  This is done by only using the last argument as
output file if it's a file (it has an extension), and only using the
first argument as flavour if it isn't a file (it doesn't have an
extension).

While we're at it, we make all $xlate calls the same, i.e. the $output
argument is always quoted, and we always die on error when trying to
start $xlate.

There's a perl lesson in this, regarding operator priority...

This will always succeed, even when it fails:

    open FOO, "something" || die "ERR: $!";

The reason is that '||' has higher priority than list operators (a
function is essentially a list operator and gobbles up everything
following it that isn't lower priority), and since a non-empty string
is always true, so that ends up being exactly the same as:

    open FOO, "something";

This, however, will fail if "something" can't be opened:

    open FOO, "something" or die "ERR: $!";

The reason is that 'or' has lower priority that list operators,
i.e. it's performed after the 'open' call.

### CODE REVIEW

**Comment by levitte** [comment]
This is ready for review

**Comment by levitte** [comment]
In addition to what Travis and Appveyor can show, I'm also testing on s390x

**Comment by levitte** [comment]
With #9892 added, this builds and tests fine on s390x

**Comment by levitte** [comment]
Oops, #9890 was also needed for s390x...

**Comment by levitte** [comment]
With those two other PRs merged, s390x finally builds and tests fine:

```
All tests successful.
Files=176, Tests=1661, 219 wallclock secs ( 1.94 usr  0.08 sys + 200.88 cusr  8.08 csys = 210.98 CPU)
Result: PASS
```

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

593d5c2fadd3c1322fa995e9ac9ced3af4d6468d Build files: Unify standard arguments for assembler generating scrips
a1c8befd661fa2145d330bb04ebc6061660db4fd build.info: For all assembler generators, remove all arguments
1aa89a7a3afb053d0c0b7fad8d3ea1b0a5447289 Unify all assembler file generators

**Pull request closed without merging**
