### PR TITLE
Remove '=for openssl ifdef'

### PR DESCRIPTION
**Pull request by richsalz**
No longer needed after rewrite of cmd-nits

Depends on #15298

### CODE REVIEW

**Comment by DDvO** [comment]
Nice.
Consequently, please also remove 
```
        if ( /=for openssl ifdef (.*)/ ) {
            foreach my $f ( split / /, $1 ) {
                #$localskips{$f} = 1;
            }
            next;
        }
```
from `find-doc-nits`.

**Comment by richsalz** [comment]
> Consequently, please also remove

Done.  I would have thought it would be in the other PR, but sure.

**Review by DDvO — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged after fixing conflicts.  Thanks.

**Pull request closed without merging**
