### PR TITLE
Ignore tsget.pl and c_rehash.pl, as well as *.exp and *.lib

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by mattcaswell** [comment]
+1

**Comment by huangqinjin** [comment]
The following are my compiler outputs.
```shell
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	app.pdb
	apps/openssl.exp
	apps/openssl.lib
	apps/openssl.pdb
	apps/tsget.pl
	dso.pdb
	engines/capi.exp
	engines/capi.ilk
	engines/capi.lib
	engines/capi.pdb
	engines/dasync.exp
	engines/dasync.ilk
	engines/dasync.lib
	engines/dasync.pdb
	engines/ossltest.exp
	engines/ossltest.ilk
	engines/ossltest.lib
	engines/ossltest.pdb
	engines/padlock.exp
	engines/padlock.ilk
	engines/padlock.lib
	engines/padlock.pdb
	libcrypto-1_1.def
	libcrypto-1_1.ilk
	libcrypto-1_1.pdb
	libcrypto-1_1.rc
	libcrypto-1_1.res
	libcrypto.exp
	libcrypto.lib
	libssl-1_1.def
	libssl-1_1.ilk
	libssl-1_1.pdb
	libssl-1_1.rc
	libssl-1_1.res
	libssl.exp
	libssl.lib
	ossl_static.pdb
	tools/c_rehash.pl
```

**Comment by levitte** [comment]
Ok, I added a few more lines in `.gitignore`, would you mind pulling this branch and seeing if that changes things, @huangqinjin ?

**Comment by mattcaswell** [comment]
+1 still applies to the new commit.

**Comment by huangqinjin** [comment]
Wonderful for me now! Thank you.

**Comment by levitte** [comment]
Grand, and now it's part of master.  Closing.

**Pull request closed without merging**
