### PR TITLE
replace "will lookup up" by "will look up"

### PR DESCRIPTION
**Pull request by triska**
##### Checklist

- [x] CLA: Trivial patch.

##### Description of change

Typographic correction.

### CODE REVIEW

**Comment by t-j-h** [comment]
+1

**Comment by levitte** [comment]
Merged into master (67adf0a7c273a82901ce8705ae8d71ee2f1c959c)

This should be backported to 1.1.0 and 1.0.2 as well.  Ok, @richsalz and @t-j-h?

**Comment by richsalz** [comment]
+1 for whatever branches are needed.

**Comment by levitte** [comment]
Goody good.

1.1.0: 72b993cfdf51d6cfc8705691ecda66285c507f7a
1.0.2: 18b8431f3b8a593bdcceb0d8f1c9612bddb77541

**Pull request closed without merging**
