### PR TITLE
CMP: generalize `ossl_cmp_calc_protection()` to handle Edwards curves correctly

### LINKED ISSUE #21564: CMP message protection with Ed25519 fails with error: `unsupported key type`
### Summary
I am working on CMP, and I try to use the IR and KUR commands with an EJBCA backend. 

This is the output I get when using the following command with Ed25519 keys :
```
+ openssl cmp -cmd kur -server localhost:80 -path ejbca/publicweb/cmp/cmp -ref ed_test -srvcert ManagementCA.pem -certout ed_cert2.pem -newkey ed_private2.pem -cert ed_cert1.pem -key ed_private1.pem -extracerts ed_cert1.pem -subject /CN=ed_test
cmp_main:../apps/cmp.c:2831:CMP info: using section(s) 'cmp' of OpenSSL configuration file '/usr/lib/ssl/openssl.cnf'
cmp_main:../apps/cmp.c:2839:CMP info: no [cmp] section found in config file '/usr/lib/ssl/openssl.cnf'; will thus use just [default] and unnamed section if present
Warning: certificate from 'ed_cert1.pem' with subject '/CN=ed_test' is not a CA cert
setup_request_ctx:../apps/cmp.c:1590:CMP warning: given -subject '/CN=ed_test' overrides the subject of 'ed_cert1.pem' for KUR
setup_client_ctx:../apps/cmp.c:2009:CMP info: will contact http://localhost:80/ejbca/publicweb/cmp/cmp
CMP error: unsupported key type
CMP error: error protecting message
CMP error: error creating certreq
```
I believe this is similar to issue #18230 
The attached patch fixes the issue but not really cleanly. I would appreciate if someone could have a look.

### More details
The backend is the current Docker image lauched with the command : 
```
docker run -it -p 80:8080 -p 443:8443 -h mycahostname -e TLS_SETUP_ENABLED="simple" keyfactor/ejbca-ce
```
I created a CMP instance and two end entities, rsa_test and ed_test in the container.

The script I use to test the CMP is the following. It does IR and KUR with RSA and Ed25519 keys using the /usr/bin/openssl binary from Debian. The last step is a patched openssl binary that demonstrates the expected output. 
```
openssl genpkey -algorithm ed25519 -out ed_private1.pem
openssl genpkey -algorithm ed25519 -out ed_private2.pem
openssl genpkey -algorithm rsa -out rsa_private1.pem
openssl genpkey -algorithm rsa -out rsa_private2.pem

openssl version

openssl cmp \
                -cmd ir \
                -server localhost:80 \
                -path ejbca/publicweb/cmp/cmp \
                -ref rsa_test \
                -srvcert ManagementCA.pem \
                -secret pass:rsa_test \
                -certout rsa_cert1.pem \
                -newkey rsa_private1.pem \
                -subject "/CN=rsa_test"

openssl cmp \
                -cmd kur \
                -server localhost:80 \
                -path ejbca/publicweb/cmp/cmp \
                -ref rsa_test \
                -srvcert ManagementCA.pem \
                -certout rsa_cert2.pem \
                -newkey rsa_private2.pem \
                -cert rsa_cert1.pem \
                -key rsa_private1.pem \
                -extracerts rsa_cert1.pem \
                -subject "/CN=rsa_test"

openssl cmp \
                -cmd ir \
                -server localhost:80 \
                -path ejbca/publicweb/cmp/cmp \
                -ref ed_test \
                -srvcert ManagementCA.pem \
                -secret pass:ed_test \
                -certout ed_cert1.pem \
                -newkey ed_private1.pem \
                -subject "/CN=ed_test"


openssl cmp \
                -cmd kur \
                -server localhost:80 \
                -path ejbca/publicweb/cmp/cmp \
                -ref ed_test \
                -srvcert ManagementCA.pem \
                -certout ed_cert2.pem \
                -newkey ed_private2.pem \
                -cert ed_cert1.pem \
                -key ed_private1.pem \
                -extracerts ed_cert1.pem \
                -subject "/CN=ed_test"

LD_LIBRARY_PATH=/home/debian/openssl-3.0.9/ /home/debian/openssl-3.0.9/apps/openssl cmp \
                -cmd kur \
                -server localhost:80 \
                -path ejbca/publicweb/cmp/cmp \
                -ref ed_test \
                -srvcert ManagementCA.pem \
                -certout ed_cert2.pem \
                -newkey ed_private2.pem \
                -cert ed_cert1.pem \
                -key ed_private1.pem \
                -extracerts ed_cert1.pem \
                -subject "/CN=ed_test"
```

The output is : 
```
debian@debian:~$ sh -x test_cmp
+ openssl genpkey -algorithm ed25519 -out ed_private1.pem
+ openssl genpkey -algorithm ed25519 -out ed_private2.pem
+ openssl genpkey -algorithm rsa -out rsa_private1.pem
........+.......+..................+.....+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...............+...+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+...+..+......+..........+.................+................+..+.............+......+......+..+......+.........+.............+.....+.........+...+...+............+.+.........+.....+.+.....+.+......+.........+.....+.+.....+............+..................+...+.........+..........+..+...................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.+..........+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+.+.....+.........+.........+....+......+.....+....+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+...+...+.........+.....+.+......+...........+..........+..+...+.......+...+...+...........+....+..+...+.+......+.........+.......................+..........+........+.......+...+........+....+......+...........+.+........+.+.....+.........+.+...+...+...............+...+......+...............+......+.........+......+...+.....+.+.........+..+....+........+...+...+.+...+...........+....+......+..+.......+..+...+...+.......+...+...+......+.....+.+..................+.....+....+...........+......+.+............+..+...+.......+.....+...+..........+...+...+......+...+..+.+....................+.......+.....+...+...............+.......+.................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ openssl genpkey -algorithm rsa -out rsa_private2.pem
.+..+.......+...+..+.+...........+...+......+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+....+.....+.+.....+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.........+............+...+.............+..+...+.........+.+...+.....+....+.....+...+.......+..+....+.....+............+.......+......+......+.....+....+.....+....+...+.....+....+.....+......+...+....+..+...+.+..............+......+.+......+.........+.........+.....+.+.........+............+..+.......+.....+.+.............................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..+......+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..........+........+....+...........+..........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+..+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ openssl version
OpenSSL 3.0.9 30 May 2023 (Library: OpenSSL 3.0.9 30 May 2023)
+ openssl cmp -cmd ir -server localhost:80 -path ejbca/publicweb/cmp/cmp -ref rsa_test -srvcert ManagementCA.pem -secret pass:rsa_test -certout rsa_cert1.pem -newkey rsa_private1.pem -subject /CN=rsa_test
cmp_main:../apps/cmp.c:2831:CMP info: using section(s) 'cmp' of OpenSSL configuration file '/usr/lib/ssl/openssl.cnf'
cmp_main:../apps/cmp.c:2839:CMP info: no [cmp] section found in config file '/usr/lib/ssl/openssl.cnf'; will thus use just [default] and unnamed section if present
setup_client_ctx:../apps/cmp.c:2009:CMP info: will contact http://localhost:80/ejbca/publicweb/cmp/cmp
CMP info: sending IR
CMP info: received IP
CMP info: sending CERTCONF
CMP info: received PKICONF
save_free_certs:../apps/cmp.c:2056:CMP info: received 1 enrolled certificate(s), saving to file 'rsa_cert1.pem'
+ openssl cmp -cmd kur -server localhost:80 -path ejbca/publicweb/cmp/cmp -ref rsa_test -srvcert ManagementCA.pem -certout rsa_cert2.pem -newkey rsa_private2.pem -cert rsa_cert1.pem -key rsa_private1.pem -extracerts rsa_cert1.pem -subject /CN=rsa_test
cmp_main:../apps/cmp.c:2831:CMP info: using section(s) 'cmp' of OpenSSL configuration file '/usr/lib/ssl/openssl.cnf'
cmp_main:../apps/cmp.c:2839:CMP info: no [cmp] section found in config file '/usr/lib/ssl/openssl.cnf'; will thus use just [default] and unnamed section if present
Warning: certificate from 'rsa_cert1.pem' with subject '/CN=rsa_test' is not a CA cert
setup_request_ctx:../apps/cmp.c:1590:CMP warning: given -subject '/CN=rsa_test' overrides the subject of 'rsa_cert1.pem' for KUR
setup_client_ctx:../apps/cmp.c:2009:CMP info: will contact http://localhost:80/ejbca/publicweb/cmp/cmp
CMP info: sending KUR
CMP info: received KUP
CMP info: sending CERTCONF
CMP info: received PKICONF
save_free_certs:../apps/cmp.c:2056:CMP info: received 1 enrolled certificate(s), saving to file 'rsa_cert2.pem'
+ openssl cmp -cmd ir -server localhost:80 -path ejbca/publicweb/cmp/cmp -ref ed_test -srvcert ManagementCA.pem -secret pass:ed_test -certout ed_cert1.pem -newkey ed_private1.pem -subject /CN=ed_test
cmp_main:../apps/cmp.c:2831:CMP info: using section(s) 'cmp' of OpenSSL configuration file '/usr/lib/ssl/openssl.cnf'
cmp_main:../apps/cmp.c:2839:CMP info: no [cmp] section found in config file '/usr/lib/ssl/openssl.cnf'; will thus use just [default] and unnamed section if present
setup_client_ctx:../apps/cmp.c:2009:CMP info: will contact http://localhost:80/ejbca/publicweb/cmp/cmp
CMP info: sending IR
CMP info: received IP
CMP info: sending CERTCONF
CMP info: received PKICONF
save_free_certs:../apps/cmp.c:2056:CMP info: received 1 enrolled certificate(s), saving to file 'ed_cert1.pem'
+ openssl cmp -cmd kur -server localhost:80 -path ejbca/publicweb/cmp/cmp -ref ed_test -srvcert ManagementCA.pem -certout ed_cert2.pem -newkey ed_private2.pem -cert ed_cert1.pem -key ed_private1.pem -extracerts ed_cert1.pem -subject /CN=ed_test
cmp_main:../apps/cmp.c:2831:CMP info: using section(s) 'cmp' of OpenSSL configuration file '/usr/lib/ssl/openssl.cnf'
cmp_main:../apps/cmp.c:2839:CMP info: no [cmp] section found in config file '/usr/lib/ssl/openssl.cnf'; will thus use just [default] and unnamed section if present
Warning: certificate from 'ed_cert1.pem' with subject '/CN=ed_test' is not a CA cert
setup_request_ctx:../apps/cmp.c:1590:CMP warning: given -subject '/CN=ed_test' overrides the subject of 'ed_cert1.pem' for KUR
setup_client_ctx:../apps/cmp.c:2009:CMP info: will contact http://localhost:80/ejbca/publicweb/cmp/cmp
CMP error: unsupported key type
CMP error: error protecting message
CMP error: error creating certreq
+ LD_LIBRARY_PATH=/home/debian/openssl-3.0.9/ /home/debian/openssl-3.0.9/apps/openssl cmp -cmd kur -server localhost:80 -path ejbca/publicweb/cmp/cmp -ref ed_test -srvcert ManagementCA.pem -certout ed_cert2.pem -newkey ed_private2.pem -cert ed_cert1.pem -key ed_private1.pem -extracerts ed_cert1.pem -subject /CN=ed_test
Warning: certificate from 'ed_cert1.pem' with subject '/CN=ed_test' is not a CA cert
setup_request_ctx:apps/cmp.c:1590:CMP warning: given -subject '/CN=ed_test' overrides the subject of 'ed_cert1.pem' for KUR
setup_client_ctx:apps/cmp.c:2009:CMP info: will contact http://localhost:80/ejbca/publicweb/cmp/cmp
CMP info: sending KUR
CMP info: received KUP
CMP info: sending CERTCONF
CMP info: received PKICONF
save_free_certs:apps/cmp.c:2056:CMP info: received 1 enrolled certificate(s), saving to file 'ed_cert2.pem'

```

### Patch

```
debian@debian:~/openssl-3.0.9$ diff -BurN ../orig/openssl-3.0.9/./crypto/cmp/cmp_protect.c crypto/cmp/cmp_protect.c--- ../orig/openssl-3.0.9/./crypto/cmp/cmp_protect.c    2023-05-30 14:31:57.000000000 +0200
+++ crypto/cmp/cmp_protect.c    2023-07-26 15:18:04.863212257 +0200
@@ -113,7 +113,7 @@
             return NULL;
         }
         if (!OBJ_find_sigid_algs(OBJ_obj2nid(algorOID), &md_nid, NULL)
-                || (md = EVP_get_digestbynid(md_nid)) == NULL) {
+                || (OBJ_obj2nid(algorOID) != NID_ED25519 && (md = EVP_get_digestbynid(md_nid)) == NULL)) {
             ERR_raise(ERR_LIB_CMP, CMP_R_UNKNOWN_ALGORITHM_ID);
             return NULL;
         }
@@ -228,11 +228,17 @@
     int nid = 0;
     ASN1_OBJECT *algo = NULL;
 
-    if (!OBJ_find_sigid_by_algs(&nid, EVP_MD_get_type(ctx->digest),
-                                EVP_PKEY_get_id(ctx->pkey))) {
-        ERR_raise(ERR_LIB_CMP, CMP_R_UNSUPPORTED_KEY_TYPE);
-        return 0;
-    }
+       if (EVP_PKEY_get_id(ctx->pkey) == NID_ED25519){
+               nid = NID_ED25519;
+       }
+       else {
+               if (!OBJ_find_sigid_by_algs(&nid, EVP_MD_get_type(ctx->digest),
+                                                                       EVP_PKEY_get_id(ctx->pkey))) {
+                       ERR_raise(ERR_LIB_CMP, CMP_R_UNSUPPORTED_KEY_TYPE);
+                       return 0;
+               }
+       }
+
     if ((algo = OBJ_nid2obj(nid)) == NULL)
         return 0;
     if (*alg == NULL && (*alg = X509_ALGOR_new()) == NULL)


```

### PR DESCRIPTION
**Pull request by DDvO**
Fixes #21564

This fix was more difficult to do than expected,
but on the bright side it simplifies the code by 
* getting rid of legacy, no more calling `OBJ_find_sigid_algs()` and `OBJ_find_sigid_by_algs()`, and
* assigning `msg->header->protectionAlg` in an abstract way via `ASN1_item_sign_ex(ASN1_ITEM_rptr()`.

The tests and internal doc are extended according to the peculiarities of Edwards keys,
where also the `verify_signature()` test function had to be updated, which in fact simplified its implementation.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
IMO this is a new feature -> master branch only.

**Comment by DDvO** [comment]
The CI failure *[external-test-cf-quiche](https://github.com/openssl/openssl/actions/runs/6010394016/job/16301737531?pr=21884#logs)* is unrelated.

**Comment by DDvO** [comment]
The underlying issue #21564 was reported by @mchazaux as a bug.

> IMO this is a new feature -> master branch only.

Yet in #21564 you added the labels for bug, master, 3.0, and 3.1.
This is IMO correct since there is no reason not to support Edwards curves.
In the original code simply the special treatment unfortunately needed for Edwards curves was missing.

Also the very similar issue #18230 was treated as a bug.

**Review by t8m — APPROVED** [review]
OK for master only.

**Comment by t8m** [comment]
Hmm... this looks like a significant refactoring was needed (although it mostly simplifies things). I'm really unsure this can be treated as a bug fix.

**Comment by t8m** [comment]
If someone else has an opinion this is a bug I can be persuaded to OK it for 3.1, 3.0.

**Comment by DDvO** [comment]
> Hmm... this looks like a significant refactoring was needed (although it mostly simplifies things). I'm really unsure this can be treated as a bug fix.

How if I provide in addition for 3.0 and 3.1 a stripped-down fix along the lines suggested by  @mchazaux
(yet using `EVP_PKEY_get_default_digest_name()` instead of the hard-coded `NID_ED25519`)
and not extending the tests and internal doc?

**Comment by DDvO** [comment]
Also the failing CI test [out-of-source-and-install (macos-latest)](https://github.com/openssl/openssl/actions/runs/6010394016/job/16301739360?pr=21884#logs) is unrelated.

**Comment by DDvO** [comment]
BTW, both #18230 and #21564 and their solutions raise a more general issue:

Looks like that for ECX/Edwards keys (and possibly in the further further ones with implicit digest algorithms)
require some awkward special treatment with both the legacy and new OpenSSL API, 
such as (extracted from `crmf_lib.c`):

```
    char name[80] = "";

    if (EVP_PKEY_get_default_digest_name(pkey, name, sizeof(name)) > 0
            && strcmp(name, "UNDEF") == 0) /* at least for Ed25519, Ed448 */
        digest = NULL;

    return ASN1_item_sign_ex(ASN1_ITEM_rptr(OSSL_CRMF_CERTREQUEST),
                             ps->algorithmIdentifier, /* sets this X509_ALGOR */
                             NULL, ps->signature, /* sets the ASN1_BIT_STRING */
                             cr, NULL, pkey, digest, libctx, propq);
```

**Comment by DDvO** [comment]
Any further thoughts by anyone how best to proceed here w.r.t. backporting the fix?

**Comment by beldmit** [comment]
I'd better document lack of Edwards curve support for old versions and fixed this in 3.2

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
Approved. Test failures seem irrelevant.

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
