### PR TITLE
openssl rehash: exit 0 on warnings, same as c_rehash

### LINKED ISSUE #6083: return codes for duplicate certificates differs between c_rehash and openssl rehash
The return code in c_rehash is 0 if a duplicate certificate is found.

https://github.com/openssl/openssl/blob/master/tools/c_rehash.in#L172

While in openssl rehash the return code is 1.

https://github.com/openssl/openssl/blob/master/apps/rehash.c#L126

This seems contrary to the documentation which says that "A warning will be displayed if a duplicate is found." Additionally, this is causing an issue with the Debian and Ubuntu package ca-certificates which calls 'openssl rehash' as a part of a mainter script which then causes the package installation to fail e.g.:

Setting up ca-certificates (20180409) ...
Updating certificates in /etc/ssl/certs...
rehash: skipping duplicate certificate in Go_Daddy_Class_2_CA.pem
dpkg: error processing package ca-certificates (--configure):
 installed ca-certificates package post-installation script subprocess returned error exit status 1

Full details can be found in the following Debian and Ubuntu bug reports.

https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1764848
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895473

I've been able to resolve the issue by having openssl rehash return 0 when a duplicate certificate is found.

### PR DESCRIPTION
**Pull request by levitte**
Fixes #6083

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Review by mspncp — APPROVED** [review]

**Comment by levitte** [comment]
Merged into master.

e6a833cb97ed762408b57ea3efa83bd10c1d2a78 openssl rehash: exit 0 on warnings, same as c_rehash

**Comment by levitte** [comment]
I forgot that this should be cherry-picked to 1.1.0 as well.  Do you approve?

**Comment by richsalz** [comment]
approve to pick to 1.1.0

**Comment by levitte** [comment]
Good, thanks.  So, merged into 1.1.0.

00937429502a160fbb96a47a47e6a0a7f7a6e9ca openssl rehash: exit 0 on warnings, same as c_rehash

**Pull request closed without merging**
