### PR TITLE
Update LICENSE year to 2018.

### PR DESCRIPTION
**Pull request by sdbedi**
##### Checklist

- [X] documentation is added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
This appears to be a trivial change. If you agree please add the text "CLA: trivial" to your commit description to clear the "need-cla" label.

**Comment by bernd-edlinger** [comment]
you can use "git commit --amend" to do that.

**Comment by richsalz** [comment]
If @sdbedi won't agree, then we have to close this and resubmit ourselves.
-1

**Comment by mspncp** [comment]
Note that this single line change is also part of #5027, so you could just close this PR and continue discussion there.

**Comment by richsalz** [comment]
see the other referenced issues; closing this as a dup.  Thank you for bringing this to our attention!

**Pull request closed without merging**
