### PR TITLE
Add system guessing for linux64-riscv64 target

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Review by t8m — APPROVED** [review]
This could be accepted under CLA: trivial if you amend the commit message to contain `CLA: trivial` on a separate line in the commit message body.

Or you can submit a CLA. https://www.openssl.org/policies/cla.html

**Review by levitte — APPROVED** [review]
I prematurely agree on this being trivial.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Agreed, trivial change.

**Comment by levitte** [comment]
Merged

e6760e3e84caa341e6b93d87d98edcbccd2d3003 Add system guessing for linux64-riscv64 target

**Pull request closed without merging**
