### PR TITLE
Improve SSL_shutdown documentation.

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by kroeckx** [comment]
So I've been wondering if we should document on how to use it a not standard compliant way, and currently think we shouldn't document that.

**Comment by t8m** [comment]
@kroeckx Can you please merge?

**Comment by levitte** [comment]
I'll merge this now

**Comment by levitte** [comment]
Merged

master:
e307e616f25a6b7b0f343fc1e62a35b2cba888f3 Improve SSL_shutdown documentation.

1.1.1:
184b0f14173fd69120767d86227d1db3a4e60ec0 Improve SSL_shutdown documentation.

**Pull request closed without merging**
