### PR TITLE
CI: Fix GCM IV check in acvp_test for crosstest

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
okay with urgent.

**Comment by paulidale** [comment]
CI failure is _the other problem: #25221_

**Comment by slontis** [comment]
ping @openssl/committers for CI fix

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
OK with urgent.

**Comment by t8m** [comment]
Merged to the master branch as urgent.

**Pull request closed without merging**
