### PR TITLE
Move MD5-SHA1 digest completely to the default provider

### PR DESCRIPTION
**Pull request by levitte**
This leaves minimal implementations of EVP_md5_sha1, which is now only
there to provide a name for implicit fetches.

### CODE REVIEW

**Comment by mattcaswell** [comment]
This will fail if an ENGINE implements this digest.

**Comment by mattcaswell** [comment]
Or to be clearer, if an EVP_MD_CTX is used with an ENGINE, and then the same EVP_MD_CTX is reused with this digest (even if the engine doesn't implement it) then it will fail. 

Of if EVP_DigestInit_ex is called with an ENGINE that doesn't implement this digest it will also fail.

**Comment by mattcaswell** [comment]
Or (perhaps less likely with this particular digest - but still possible), if it is used as part of a DigestSign operation.

**Comment by levitte** [comment]
> Of if EVP_DigestInit_ex is called with an ENGINE that doesn't implement this digest it will also fail.

Doesn't it anyway?  If someone specifies an ENGINE, then it's because they fully expect that engine to implement the digest they want, and if the ENGINE doesn't, then DigestInit *should* fail, no?  It sure looks like it does, here:

https://github.com/openssl/openssl/blob/fac9200a881a83bef038ebed628ebd409786a1a6/crypto/evp/digest.c#L220-L228

> Or to be clearer, if an EVP_MD_CTX is used with an ENGINE, and then the same EVP_MD_CTX is reused with this digest (even if the engine doesn't implement it) then it will fail.

Same thing here, surely?

**Comment by mattcaswell** [comment]
> Doesn't it anyway? If someone specifies an ENGINE, then it's because they fully expect that engine to implement the digest they want, and if the ENGINE doesn't, then DigestInit should fail, no? It sure looks like it does, here:

Ah...yeah I think in that case it just fails.

>> Or to be clearer, if an EVP_MD_CTX is used with an ENGINE, and then the same EVP_MD_CTX is reused with this digest (even if the engine doesn't implement it) then it will fail.
>
> Same thing here, surely?

If an EVP_MD_CTX has previously been used with an engine then ctx->engine is set. That's enough to send us into the legacy handling. If "impl == NULL" then we check if there is an ENGINE can handle this digest (see tmpimpl)...if not then we just end up in the standard legacy handling

**Comment by levitte** [comment]
> If an EVP_MD_CTX has previously been used with an engine then ctx->engine is set. That's enough to send us into the legacy handling.

Ah, yeah, I can see that.  This is because the code currently always sees the context as legacy if there *was* an engine involved, regardless of if it implements the new desired algo or not.  The 1.1.1 code simply drops the currently attached engine when a new type is given, and starts over the process of figuring out if there is an engine that implements the type or not, which is slightly different semantics...

I'm thinking that the portion of the legacy code that drops the engine should appear higher up and not be tucked away in the legacy portion.  Do you agree with that line of thinking?

**Comment by mattcaswell** [comment]
> I'm thinking that the portion of the legacy code that drops the engine should appear higher up and not be tucked away in the legacy portion. Do you agree with that line of thinking?

So there's two section of legacy handling code. That between then comment `/* TODO(3.0): Legacy work around code below. Remove this */` and the comment `/* TODO(3.0): Start of non-legacy code below */`. And then everything below the comment `/* TODO(3.0): Remove legacy code below */`. My expectation is that, eventually, both sections will be removed and we'll just have providers. In the interim, I'm fine with moving code around between the two legacy sections as we see fit to streamline things.

Once ENGINEs are seen as just another provider then a lot of the existing legacy code will be able to be removed.

That doesn't solve the other problem though which is the DigestSign stuff. That code hasn't been implemented yet so we're forced into the legacy handling in that case.

**Comment by levitte** [comment]
See #9077

**Comment by levitte** [comment]
Ok, #9077 is in, are your immediate concerns cleared?

**Comment by mattcaswell** [comment]
Like I said:
> That doesn't solve the other problem though which is the DigestSign stuff. That code hasn't been implemented yet so we're forced into the legacy handling in that case.

**Comment by levitte** [comment]
I'll have to look more closely at that tomorrow.  Too tired for the moment.

**Comment by slontis** [comment]
I think this PR will hang around until after PKEY is moved to the provider.

**Comment by levitte** [comment]
> I think this PR will hang around until after PKEY is moved to the provider.

Why?  If DigestSign is the problematic part, that's what we need to wait on, but the rest of PKEY?  Nah...

**Comment by levitte** [comment]
Rebased.  It tests cleanly on my laptop...

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

f50958b8c80ae267c02b2d534da8bde091010707 Move MD5-SHA1 digest completely to the default provider

**Pull request closed without merging**
