### PR TITLE
Fix a missing function prototype in AFALG engine

### PR DESCRIPTION
**Pull request by mattcaswell**
##### Checklist

- [x] CLA is signed

### CODE REVIEW

**Comment by mattcaswell** [comment]
Could do, but that would require making internal/engine.h visible to the engine code. It's not at the moment.

**Comment by levitte** [comment]
Mm, good point...  it's just a bit weird that this engine doesn't have access to the declaration of a function it defines!  Ah well...

**Comment by kroeckx** [comment]
The warnings themselves also cause a build failure with --strict-warnings.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

> The warnings themselves also cause a build failure with --strict-warnings.

Yes, I know. I wasn't attempting to address that here - just fixing that actual "real" warning. Maybe we do want to remove those warnings - which would be one way of fixing the current 1.1.0 travis failure. Although I see in #1992 you have managed to recreate the issue on master as well. I'm not clear on why this is suddenly a problem now, since those warnings have been in there for quite a while. Did we change the 1.1.0 travis config recently?

Anyway closing this PR now.

**Pull request closed without merging**
