### PR TITLE
Fix typos found by codespell in openssl-3.3 doc

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
##### Checklist
- [x] documentation is added or updated

### CODE REVIEW

**Review by kroeckx — APPROVED** [review]

**Comment by kroeckx** [comment]
It seems the 3.0 to 3.3 are exactly the same, you could have just made 1 PR for all 4.

**Comment by DimitriPapadopoulos** [comment]
Sure. How do I do that? I mean, which branch do I merge into? How do I suggest the changes should be backported to earlier branches?

**Review by shahsb — APPROVED** [review]

**Comment by kroeckx** [comment]
You could just say in the title or comment that this PR is for all those branches. The person merging it will then just apply the patch to all the branches.

**Review by InfoHunter — APPROVED** [review]

**Comment by InfoHunter** [comment]
Now the person who is merging this can cherry-pick the commit to all branches.

**Comment by DimitriPapadopoulos** [comment]
Yes, this 3.3 patch could be backported to 3.2, 3.1, 3.0. However, only the `branch: 3.3` label is currently visible.

**Comment by t8m** [comment]
Merged to the 3.3, 3.2, 3.1 and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
