### PR TITLE
`check-format.pl`: fix detection of missing/extra blank lines in local decls

### PR DESCRIPTION
**Pull request by DDvO**
This fixes issues like the one reported in https://github.com/openssl/openssl/pull/17172#discussion_r915941668.

Also 
* fix false positive on `for(;; stmt)`
* improve wording: 'no' -> 'missing'
* further minor improvements

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by DDvO** [comment]
@paulidale can you please approve this as well?

**Review by paulidale — APPROVED** [review]

**Comment by hlandau** [comment]
Merged to master. Thank you.

This did not merge cleanly to 3.0, do you want to open another PR for it?

**Comment by DDvO** [comment]
> Merged to master. Thank you.

I'm pleased to provide fixes like these.

> This did not merge cleanly to 3.0, do you want to open another PR for it?

I'll do - likely I forgot backporting some previous fix of the tool to 3.0.

**Comment by DDvO** [comment]
After cherry-picking the other recent fixes to `check-format.pl` to 3.0,
cherry-picking the commits of this PR to 3.0 succeeded cleanly.

**Pull request closed without merging**
