### PR TITLE
Do not use stitched AES-GCM implementation on PPC32

### LINKED ISSUE #21301: `error:0A0001BB:SSL routines::bad record type` errors with openssl-3.1.1 on ppc32
Noticed this first when packages failed to fetch after upgrading from 3.0.9->3.1.1. Gentoo bug: https://bugs.gentoo.org/909306.

Everything is fine (tests pass + curl is ok) with `asm` disabled.

Then reproduced with curl:
```shell
$ curl https://github.com/ -vvvvvvvvv
*   Trying 192.30.255.113:443...
* Connected to github.com (192.30.255.113) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (OUT), TLS alert, unexpected_message (522):
* OpenSSL/3.1.1: error:0A0001BB:SSL routines::bad record type
* Closing connection 0
curl: (35) OpenSSL/3.1.1: error:0A0001BB:SSL routines::bad record type
```

The test suite fails pretty badly (passes for 3.0.9):
```
Test Summary Report
-------------------
80-test_ssl_new.t                (Wstat: 4864 (exited 19) Tests: 30 Failed: 19)
  Failed tests:  1-5, 9-10, 12-15, 17-18, 20-21, 24, 26-28
  Non-zero exit status: 19
70-test_recordlen.t              (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
70-test_asyncio.t                (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
70-test_servername.t             (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
30-test_evp.t                    (Wstat: 256 (exited 1) Tests: 74 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
90-test_sslbuffers.t             (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
90-test_tls13ccs.t               (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
90-test_tls13encryption.t        (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
80-test_ssl_old.t                (Wstat: 512 (exited 2) Tests: 7 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 2
90-test_sslapi.t                 (Wstat: 256 (exited 1) Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=250, Tests=3363, 182 wallclock secs (15.85 usr  1.90 sys + 699.29 cusr 214.61 csys = 931.65 CPU)
Result: FAIL
```

Full log at https://bugs.gentoo.org/attachment.cgi?id=864720.

```shell
# perl configdata.pm --dump

Command line (with current working directory = .):

    /usr/bin/perl ../openssl-3.1.1/Configure linux-ppc no-sse2 enable-camellia enable-ec enable-ec2m enable-sm2 enable-srp enable-idea enable-mdc2 enable-rc5 enable-asm no-ktls no-rfc3779 no-sctp no-zlib no-weak-ssl-ciphers --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared threads

Perl information:

    /usr/bin/perl
    5.36.1 for powerpc-linux

Enabled features:

    afalgeng
    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    idea
    legacy
    loadereng
    makedepend
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    rc2
    rc4
    rc5
    rdrand
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    acvp-tests          [cascade]        OPENSSL_NO_ACVP_TESTS
    asan                [default]        OPENSSL_NO_ASAN
    buildtest-c++       [default]
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [default]        OPENSSL_NO_EGD
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fips                [default]
    fips-securitychecks [cascade]        OPENSSL_NO_FIPS_SECURITYCHECKS
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    ktls                [option]         OPENSSL_NO_KTLS
    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]        OPENSSL_NO_MSAN
    rfc3779             [option]         OPENSSL_NO_RFC3779
    sctp                [option]         OPENSSL_NO_SCTP
    sse2                [option]
    trace               [default]        OPENSSL_NO_TRACE
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [option]         OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [option]
    zlib-dynamic        [default]
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "qc",
    CC => "gcc",
    CFLAGS => "-Wall -O3",
    CXX => "g++",
    CXXFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    asm_arch => "ppc32",
    bn_ops => "BN_LLONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-pthread",
    cppflags => "",
    cxxflags => "-std=c++11 -pthread",
    defines => [ "OPENSSL_BUILDING_OPENSSL" ],
    disable => [  ],
    dso_ldflags => "-Wl,-z,defs",
    dso_scheme => "dlfcn",
    enable => [ "afalgeng" ],
    ex_libs => "-ldl -pthread -latomic",
    includes => [  ],
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DOPENSSL_USE_NODELETE -DB_ENDIAN",
    lib_defines => [  ],
    module_cflags => "-fPIC",
    module_cxxflags => undef,
    module_ldflags => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    perl_platform => "Unix",
    perlasm_scheme => "linux32",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,--version-script=",
    shared_defines => [  ],
    shared_ldflag => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-soname=",
    shared_target => "linux-shared",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",

Recorded environment:

    AR = powerpc-unknown-linux-gnu-ar
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC = powerpc-unknown-linux-gnu-gcc
    CFLAGS = -O2 -mcpu=powerpc -mtune=powerpc -pipe -fno-strict-aliasing -Wa,--noexecstack
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX = powerpc-unknown-linux-gnu-g++
    CXXFLAGS = -O2 -mcpu=powerpc -mtune=powerpc -pipe -fno-strict-aliasing -Wa,--noexecstack
    HASHBANGPERL =
    LD =
    LDFLAGS = -Wl,-O1 -Wl,--as-needed
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB = powerpc-unknown-linux-gnu-ranlib
    RC = windres
    RCFLAGS =
    RM =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =

Makevars:

    AR              = powerpc-unknown-linux-gnu-ar
    ARFLAGS         = qc
    CC              = powerpc-unknown-linux-gnu-gcc
    CFLAGS          = -O2 -mcpu=powerpc -mtune=powerpc -pipe -fno-strict-aliasing -Wa,--noexecstack
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXX             = powerpc-unknown-linux-gnu-g++
    CXXFLAGS        = -O2 -mcpu=powerpc -mtune=powerpc -pipe -fno-strict-aliasing -Wa,--noexecstack
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = -Wl,-O1 -Wl,--as-needed
    LDLIBS          =
    PERL            = /usr/bin/perl
    RANLIB          = powerpc-unknown-linux-gnu-ranlib
    RC              = windres
    RCFLAGS         =

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    ../openssl-3.1.1/Configurations/common0.tmpl
    ../openssl-3.1.1/Configurations/unix-Makefile.tmpl
```

### PR DESCRIPTION
**Pull request by t8m**
The implementation is not usable there at all.
Fixes #21301

### CODE REVIEW

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
@hlandau one more tweak to not build the file that is not going to be used anyway.

**Review by hlandau — APPROVED** [review]

**Review by thesamesam — APPROVED** [review]
Thanks for the quick turnaround.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to 3.1 and master.
Was basing this from 3.1 intentional?

**Comment by t8m** [comment]
> Was basing this from 3.1 intentional?

Yes, because the original report was against 3.1

**Pull request closed without merging**
