### PR TITLE
Make abidiff less sensitive

### PR DESCRIPTION
**Pull request by t8m**
Check only exported interfaces and do not record
useless information.

### CODE REVIEW

**Comment by nhorman** [comment]
I think what you're doing here makes sense, particularly restricting the analysis to our exported ABI (though its frustrating that our runners ubuntu version ships an old version of abigail that doesn't support those features).

That said, I think, no matter how small we make the xml file, its still going to be a headache to have a human read and update it.  It may be better to consider the abi changes to be something that we rely on abidiff output to warn us of, which we can waive with a PR flag.  Updates to the xml can happen during merge

**Comment by t8m** [comment]
> I think what you're doing here makes sense, particularly restricting the analysis to our exported ABI (though its frustrating that our runners ubuntu version ships an old version of abigail that doesn't support those features).
> 
> That said, I think, no matter how small we make the xml file, its still going to be a headache to have a human read and update it. It may be better to consider the abi changes to be something that we rely on abidiff output to warn us of, which we can waive with a PR flag. Updates to the xml can happen during merge.

I could agree with this. However please note that even doing the update during the merge won't be an easy task. I thought the .xml file I am creating is compatible but apparently it is not as it is indicating ABI changes when there are none.

I have a different idea how to do this - we should do the same what we are doing with the FIPS Checksums CI job and basically not carry the .xml file in the tree. I am going to work on this next sprint.

**Comment by nhorman** [comment]
agreed, a lookasside cache for the xml file makes sense to me, as it removes the need to review the xml changes in a PR, treating the file as truly opaque.

Regarding its regneration, I think there is an extra advantage in doing this during merge, namely the similarity of environment.  I expect you ran into an issue similar to some I have encountered, in that small compiler differences impact the abi for the purposes of checking.  For instance when building on my local system, my version of gcc defaults CET features to on, which cause various ifdef triggers in the source base to add fields to some public structures.  Its abi consistent local to my system, but comparisons from my local build to whats produced on an ubuntu vm (which disables CET in 22.04) result in abi diffs.  My solution has been to rebuild in an ubuntu container, but that is likely not a great solution going forward.  Constraining the build environment on which the abi xml is updated solves that

**Comment by t8m** [comment]
Closing in favour of #22901

**Pull request closed without merging**
