### PR TITLE
mk1mf: dtlstest needs ssltestlib, include it with a hack

### PR DESCRIPTION
**Pull request by levitte**
We don't really have a mechanism to include other object files into a given
test program.  For now, a simple hack in mk1mf.pl will do.

### CODE REVIEW

**Comment by richsalz** [comment]
+1 once original poster verifies the fix.

**Comment by levitte** [comment]
#1478 needs to be merged before this one will be buildable

**Comment by richsalz** [comment]
still +1. do it.

**Comment by levitte** [comment]
Yup.  I'll just wait to see that appveyor goes through properly...

**Comment by levitte** [comment]
Ok, appveyor does fine, so time to merge

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
