### PR TITLE
fix "info" spelling

### PR DESCRIPTION
**Pull request by glensc**
fix typical spelling error of uncountable words like information

more reading:
http://dictionary.cambridge.org/grammar/british-grammar/nouns-countable-and-uncountable

patch produced with:
$ grep -r build_infos . -l|xargs sed -i s/build_infos/build_info/g

### CODE REVIEW

**Comment by richsalz** [comment]
really worth doing this?

**Comment by levitte** [comment]
It's a variable name... 
Of course, it could have been named `build_info_files`, 'cause that's what this array is. 

My opinion? Not worth it. Sorry.

**Comment by glensc** [comment]
don't get offended, but mis-spelling words is lame and looks unprofessional. i could change variable to `build_info_files` if that makes PR better

**Comment by richsalz** [comment]
surely there are worse things to fix, and more ways that we look lame and unprofessional :)

**Pull request closed without merging**
