### PR TITLE
QUIC: Test connection with large client and server cert chains

### PR DESCRIPTION
**Pull request by t8m**
I had to raise the initial crypto buffer size, but that is probably not the right fix.
Please suggest how to handle this.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
There should be no datagram reordering happening during the test, however in fact in real world there can happen some reordering.

> We call `ossl_quic_rxfc_on_retire` when QUIC_TLS releases a record; is it possible it's actually holding onto records for longer than I assumed? If so the 'correct' fix would probably be to change this.

I assume QUIC_TLS holds onto the records until it reads the whole Certificate message. @mattcaswell ?

**Comment by mattcaswell** [comment]
> I assume QUIC_TLS holds onto the records until it reads the whole Certificate message.

No, it doesn't. It reads a record, copies it into the init_buf, releases it, then reads another one - continuing like that until the whole message has been read. So we should never be holding on to a record for a long time, and definitely never holding onto more than one record at a time.

**Comment by t8m** [comment]
@mattcaswell then I have no explanation why this test does not work without raising the size. Would you be able to look at this?

**Comment by mattcaswell** [comment]
Yes, I can look.

**Comment by mattcaswell** [comment]
I've looked at this. There are numerous strange things going on here. Partly this is related to the semi-flow control that we have on CRYPTO streams. The RFC says that there is no fc for CRYPTO streams, but nonetheless we still have an rxfc instance for them to keep an eye on how much data we are being sent.

Initially we have 8192 buffer size for the CRYPTO stream and that much credit available.

The server sends us a bunch of data for its flight containing the large certificate chain. This happens to be exactly 8192 bytes (presumably because that's how much we've defaulted to allow it to send in one go) - and its spread across multiple datagrams.

We then process all the datagrams queuing the CRYPTO stream data as we go. Strangely the first crypto frame we process happens to be the last chunk of 222 bytes out of the 8192. So the fc decides we've used the entire available 8192 bytes of credit in one go. The subsequent crypto frames in the remaining datagrams are then processed. These supply the remaining bytes out of the 8192 so no more credit is consumed. At the end of this we have 8192 bytes available in the crypto stream and the entire credit is consumed (but no more).

Then we tick TLS. This starts reading chunks of data out of the crypto stream and releasing them shortly afterwards. After each time TLS releases some data we check whether to allow more credit on the crypto stream. Sometimes we bump it, sometimes we don't. When we bump it, we do so by less than the amount we have retired. Eventually TLS has read and released all of the data in the crypto stream. At this point there is no data left to be read and the fc has bumped the credit so that there is 6812 bytes of credit available.

Then we process more datagrams. Weirdly, even though the first time around we seemed to process the crypto frames in reverse order, this time around we seem to do them in order. I haven't investigated why this is. The amount of crypto data that we receive in the second set of frames is another 8192 bytes (I think). We only queue the first 6812 bytes (which was the amount of credit we had available) and then we give up queuing any more and signal a protocol error. But we still continue the ticking process.

Next we tick TLS and it reads, processes and releases the 6812 of available data. Finally the tick completes and SSL_connect finally notice the protocol error we raised earlier and returns with an error.

This raises all sort of questions and issues:

1) It is "by luck" that the first tranche of data sent by the server happens to be 8192 which is exactly the size of our crypto stream. If a different implementation chose a larger amount to send then we would fail earlier.

2) It is strange that we queue the data in reverse order. I'm not sure if that is because they are sent in reverse order or because we process them in reverse order. We definitely don't want to send them in reverse order because then the receiver can't do anything except buffer it until it receives the first bytes.

3) The flow control logic seems a bit messed up here. Given that we can't communicate the amount of credit available to the sender, shouldn't the amount of credit simply be the amount of space we have remaining?

4) It is slightly concerning that we keep queuing data without ticking TLS. This makes it much more likely for us to blow our available buffer space. If we ticked TLS as we receive data (as long it is not "future" data) then we wouldn't have to buffer as much.

5) The 8192 figure gives me some concerns. Consider the case where the server sends us a large certificate chain that exceeds this size (probably not that unlikely). The server will just keep sending the data until it is finished (because there is no flow control). If the datagram containing the first bytes gets lost then we have to buffer everything and we are very likely to blow our buffers resulting in a protocol error.

**Comment by mattcaswell** [comment]
6. The fact that we tick TLS after we have already decided that a protocol error has occurred is sub-optimal

**Comment by hlandau** [comment]
Great investigation.

>1. It is "by luck" that the first tranche of data sent by the server happens to be 8192 which is exactly the size of our crypto stream. If a different implementation chose a larger amount to send then we would fail earlier.

We may want to determine this figure empirically based on what other implementations do.

>2. It is strange that we queue the data in reverse order. I'm not sure if that is because they are sent in reverse order or because we process them in reverse order. We definitely don't want to send them in reverse order because then the receiver can't do anything except buffer it until it receives the first bytes.

Yeah, this is worth investigating.

>3. The flow control logic seems a bit messed up here. Given that we can't communicate the amount of credit available to the sender, shouldn't the amount of credit simply be the amount of space we have remaining?

Kind of. Define "amount of space we have remaining" &mdash; since RSTREAM handles out of order segments there is not a clear definition of this per se. This is why RXFC was used &mdash; it is designed to handle this correctly by clamping the maximum *logical* offset received. It is possible we need to tune RXFC differently for this use case (or introduce a CRYPTO_RXFC which has a simpler logic if it turns out to be simpler).

>4. It is slightly concerning that we keep queuing data without ticking TLS. This makes it much more likely for us to blow our available buffer space. If we ticked TLS as we receive data (as long it is not "future" data) then we wouldn't have to buffer as much.
>5. The 8192 figure gives me some concerns. Consider the case where the server sends us a large certificate chain that exceeds this size (probably not that unlikely). The server will just keep sending the data until it is finished (because there is no flow control). If the datagram containing the first bytes gets lost then we have to buffer everything and we are very likely to blow our buffers resulting in a protocol error.

Yeah. I think my assumption when choosing 8192 was that we would handle a single datagram immediately (so limited to 1500 on the public internet) so the only way you would get close to 8192 is if you have severe reordering. But `ch_rx` nowadays handles as many incoming packets as possible before we ever get to the `ossl_quic_tls_tick` call (at one point it only handled one packet IIRC) that happens subsequently. We may wish to interleave these two calls &mdash; I'd suggest doing that.

So my suggestion would be:

- `ch_rx` and `ossl_quic_tls_tick` (if `!channel_only`, of course) need to be interleaved
- We should make sure the FC implementation for crypto streams (whether we tweak RXFC or make a new module) always leads to `k` bytes credit in the simple case where `k` bytes credit were previously given and then `k` bytes were consumed.

**Comment by mattcaswell** [comment]
> so the only way you would get close to 8192 is if you have severe reordering

I'm not sure this is the case. It is sufficient for only the first datagram to be dropped for us to have to buffer everything after that until the datagram is resent - which might take some time. So I could easily see us exceeding 8192.

> ch_rx and ossl_quic_tls_tick (if !channel_only, of course) need to be interleaved
We should make sure the FC implementation for crypto streams (whether we tweak RXFC or make a new module) always leads to k bytes credit in the simple case where k bytes credit were previously given and then k bytes were consumed.

These are both good suggestions. I agree. Will you be taking that on?

I will do some more investigation to try and figure out why things are processed in the reverse order.

**Comment by t8m** [comment]
> * We should make sure the FC implementation for crypto streams (whether we tweak RXFC or make a new module) always leads to `k` bytes credit in the simple case where `k` bytes credit were previously given and then `k` bytes were consumed.

Why is it that the current implementation does not behave like this?

**Comment by hlandau** [comment]
The tick logic should be something like

```
tick:
  Set the 'have ticked QUIC_TLS flag' to false
  ch_rx:
    For each packet:
      Handle each frame
      If any CRYPTO frames were handled:
        tick QUIC_TLS
        Set the 'have ticked QUIC_TLS flag' to true
  If the 'have ticked QUIC_TLS flag' is not true:
    tick QUIC_TLS
```

Premise:
- We only need to call QUIC_TLS once per packet (even if there are multiple CRYPTO frames in it)
- If there are no CRYPTO frames processed during a tick, we should still call QUIC_TLS at least once in case it wants to spontaneously do something

**Comment by hlandau** [comment]
>These are both good suggestions. I agree. Will you be taking that on?

OK

>Why is it that the current implementation does not behave like this?

I will investigate the RXFC issue. Matt says he will investigate the reverse order thing.

**Comment by t8m** [comment]
> I'm not sure this is the case. It is sufficient for only the first datagram to be dropped for us to have to buffer everything after that until the datagram is resent - which might take some time. So I could easily see us exceeding 8192.

Yeah, I came to that conclusion too. So we probably want to fix the issues with the credit and calling tls tick after ch_rx, but we might want to do something with the crypto buffer size anyway.

And/or perhaps we might want to react to packets received with frames exceeding the crypto buffer size somehow differently?? I can imagine treating them as lost packets at least for a while to give chance for the previously lost or delayed earlier crypto frames to be received. It won't be easy to handle this in the code though as there might be other frames in the packet and it would basically mean that we would have to first try to handle the crypto frame and only after that the rest of the frames.

**Comment by t8m** [comment]
> And/or perhaps we might want to react to packets received with frames exceeding the crypto buffer size somehow differently?? I can imagine treating them as lost packets at least for a while to give chance for the previously lost or delayed earlier crypto frames to be received. It won't be easy to handle this in the code though as there might be other frames in the packet and it would basically mean that we would have to first try to handle the crypto frame and only after that the rest of the frames.

However this sounds like something for TODO(QUIC FUTURE).

**Comment by mattcaswell** [comment]
> And/or perhaps we might want to react to packets received with frames exceeding the crypto buffer size somehow differently?? I can imagine treating them as lost packets at least for a while to give chance for the previously lost or delayed earlier crypto frames to be received. It won't be easy to handle this in the code though as there might be other frames in the packet and it would basically mean that we would have to first try to handle the crypto frame and only after that the rest of the frames.

I was thinking along the same lines

> However this sounds like something for TODO(QUIC FUTURE).

I am less sure about that. I think this is going to be a very real issue.

**Comment by mattcaswell** [comment]
The reordering issue is solved. When we transfer deferred URXEs from the `urx_deferred` list to the `urx_pending` list we reverse the order. This explains why it only happened with the first tranche of datagrams and not the second. Only the first tranche gets deferred, because by the time we get to the second TLS has been ticked and the encryption level is provisioned. PR in the works.

**Comment by mattcaswell** [comment]
> The reordering issue is solved.

#22452

**Comment by hlandau** [comment]
https://github.com/openssl/openssl/pull/22476

**Comment by t8m** [comment]
The test is included in #22476. Closing this.

**Pull request closed without merging**
