### PR TITLE
Update iOS and iOS sim configure targets 

### PR DESCRIPTION
**Pull request by ckelley-1992**
CLA: trivial
Update ios-xcrun and ios64-xcrun configurations for Configure

### Tests Performed
Verified that after these changes it was possible to run 
 ./Configure ios64-xcrun enable-fips enable-fips-securitychecks -mios-version-min=11.0 && make
 ./Configure iossimulator-xcrun enable-fips enable-fips-securitychecks -mios-version-min=11.0 && make

to successfully configure and build iOS targets without needing to set the CROSS_TOP, etc

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
We will need a CCLA and ICLA submitted to be able to merge PRs from you.

Also with this change the assembler implementations are not used for these targets. Is that intentional?

**Comment by ckelley-1992** [comment]
The assembler was working successfully with the initial version I checked out two weeks ago, as well as with openssl-3.0.0-alpha9. However when I pulled this morning in order to get it to compile for FIPS without no-asm I needed to remove those three asm directives.

**Review by paulidale — COMMENTED** [review]
This is not a fix.

The fix is to get the assembly code correct.

The problem is known: #15321

**Comment by paulidale** [comment]
The problematic assembly will be reverted.

**Pull request closed without merging**
