### PR TITLE
Add optional support for EC implicitCurve parameters

### LINKED ISSUE #12895: Correctly parse but reject certs for EC keys with implicitCurve
[RFC 5480 section 2.1.1](https://tools.ietf.org/html/rfc5480#section-2.1.1) requires that implicitCurve and specifiedCurve MUST NOT be used in PKIX.
Lacking a suitable example/test cert it is currently unclear if OpenSSL can parse ECC certs with implicitCurve.
While #12683 handles the specifiedCurve case, I suspect that rejection of both cases can be achieved simply by checking
```
EC_GROUP_get_curve_name(EC_KEY_get0_group(EVP_PKEY_get0_EC_KEY(pkey))) != NID_undef
```

This is a spin-off of the discussion in https://github.com/openssl/openssl/pull/12683#discussion_r486980401.

### PR DESCRIPTION
**Pull request by DDvO**
* Add `X509_V_FLAG_INHERIT_PKPARAM` and `-inherit_pkparam` verification apps option
      implemented by new `X509_PUBKEY_chain_inherit_parameter()` etc.
* Add `-null_pkparam` option to apps/x509 for producing certs with `implicitCurve`
* Various corrections for misleading cert handling/verification errors
* Add TODO for removing legacy `X509_get_pubkey_parameters()`
* Add 10 test cases to 25-test_verify.t demonstrating these improvements

This fixes #12895.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by kroeckx** [comment]
I'm not sure we want to support this, even when you need to opt-in for the support.

**Comment by DDvO** [comment]
It also improves the so far not very to-the point errors on trying to use such certs.
For instance, 
```
openssl x509 -noout -text -in test/certs/p384-inter-implicitCurve.pem
```
used to print
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = ECDSA P-384 root
        Validity
            Not Before: Sep 26 17:43:38 2020 GMT
            Not After : Sep 27 17:43:38 2120 GMT
        Subject: CN = ECDSA P-384 inter
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
            Unable to load Public Key
139970204808320:error:100DC08E:elliptic curve routines:eckey_type2param:decode error:../crypto/ec/ec_ameth.c:124:
139970204808320:error:100D7010:elliptic curve routines:eckey_pub_decode:EC lib:../crypto/ec/ec_ameth.c:151:
139970204808320:error:0B09407D:x509 certificate routines:x509_pubkey_decode:public key decode error:../crypto/x509/x_pubkey.c:125:
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                B7:FC:08:8B:B1:7F:67:76:7C:52:3B:AD:B2:85:55:E0:90:26:00:CA
            X509v3 Authority Key Identifier: 
                keyid:26:D0:8F:1D:7B:5F:DC:1E:7F:41:80:7D:63:CA:1C:75:81:D6:85:69

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: ecdsa-with-SHA256
         30:65:02:31:00:f7:4a:51:64:d1:fb:25:f4:0a:d8:05:55:2e:
         a9:c4:ce:d2:ef:b2:01:b5:c1:9f:67:59:23:46:a8:df:de:aa:
         b3:34:d8:fe:9a:15:8c:fc:8a:74:80:c2:d9:f7:66:37:a3:02:
         30:1f:7f:0c:bf:4b:f3:34:b5:fc:74:61:28:ac:87:1b:e3:ba:
         54:c6:91:06:24:c3:80:5d:21:c3:63:8a:0a:ec:f1:6d:d2:bc:
         f3:2e:76:c8:5d:79:87:4e:b2:8b:48:11:b4
```
and with this PR it prints
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = ECDSA P-384 root
        Validity
            Not Before: Sep 26 17:43:38 2020 GMT
            Not After : Sep 27 17:43:38 2120 GMT
        Subject: CN = ECDSA P-384 inter
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
            Unable to load Public Key
C0578F63187F0000:error::elliptic curve routines:(unknown function):implicit curve:crypto/ec/ec_ameth.c:142:
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                B7:FC:08:8B:B1:7F:67:76:7C:52:3B:AD:B2:85:55:E0:90:26:00:CA
            X509v3 Authority Key Identifier: 
                26:D0:8F:1D:7B:5F:DC:1E:7F:41:80:7D:63:CA:1C:75:81:D6:85:69
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: ecdsa-with-SHA256
    Signature Value:
        30:65:02:31:00:f7:4a:51:64:d1:fb:25:f4:0a:d8:05:55:2e:
        a9:c4:ce:d2:ef:b2:01:b5:c1:9f:67:59:23:46:a8:df:de:aa:
        b3:34:d8:fe:9a:15:8c:fc:8a:74:80:c2:d9:f7:66:37:a3:02:
        30:1f:7f:0c:bf:4b:f3:34:b5:fc:74:61:28:ac:87:1b:e3:ba:
        54:c6:91:06:24:c3:80:5d:21:c3:63:8a:0a:ec:f1:6d:d2:bc:
        f3:2e:76:c8:5d:79:87:4e:b2:8b:48:11:b4
```

**Comment by DDvO** [comment]
I've just removed in `x509_vfy.c` the two calls of the legacy function  `X509_get_pubkey_parameters()`.
It would just add spurious error queue entries in some situation.
I suggest deprecating or entirely removing that function when we have more freedom to do API changes.

**Comment by t8m** [comment]
> It also improves the so far not very to-the point errors on trying to use such certs.

Could we have just this instead of the "complete" support?

**Comment by DDvO** [comment]
The currently reported Travis CI failure is unrelated and will be fixed by #13022.

**Comment by davidben** [comment]
Improving the error is reasonable enough, but I agree OpenSSL should not actually implement it. It's explicitly forbidden by RFC5480 and I'm not aware of any other implementation which allows this. It also risks introducing some weird problems coming from a certificate's public key being interpreted differently in context.

Cryptography is sadly mired with a history of specification mistakes and unnecessary complexity. This is a mistake that we have happily moved on from. Supporting this feature in OpenSSL would be a regression for both the project and the ecosystem as a whole.

**Comment by DDvO** [comment]
Thanks @t8m and @davidben for your comments.

I am aware that since 2009, RFC 5480 forbids the use of implicitCurve (and specifiedCurve) parameters in PKIX
while by that time the key idea for implicitCurve was the following (quoting from RFC 3279):
> If the elliptic curve parameters are specified as implicitlyCA in the
   SubjectPublicKeyInfo AlgorithmIdentifier and the CA signed the
   subject certificate using ECDSA, then the certificate issuer's ECDSA
   parameters apply to the subject's ECDSA key. 

I do not know what the specific actual concerns were when forbidding for EC certs everything else but namedCurve,
but there are certainly cases for which this is overzealous. And I do not really see what should go wrong
if in an - up to that point already verified - chain some security parameters from the issuing CA get inherited to the subject cert.

Actually right from its beginning in 1998, OpenSSL has been supporting implicitCurve,
with the help of the function ` X509_get_pubkey_parameters()`, which BTW has a rather unclear name.
This function apparently got neglected over the years and either should have been updated, 
clarified, and documented or it should have been deprecated and removed. Neither happend.
Currently it simply does not work and in some situations even adds needless error queue entries.
So one of the commits in this PR removes its calls from `verify_chain()`, and a TODO for deprecation is added.

Following the current model of handling specifiedCurve, for which here is still quite some support in OpenSSL
and where just recently (in #/12683) a check has been added to throw an error if used in proper certificate chains
to be verified in `verify_chain()`, I updated/corrected and completed here the treatment of its sibling, implicitCurve.

Maybe some more discussion would be needed to find out whether there are still cases where it can be helpful
if OpenSSL can continue supporting such deprecated mechanisms where explicitly requested.
For the time being, as soon as I'll have some spare time for this non-urgent task, 
I'm going to split this PR into
* those changes that are indubitably helpful and even important (such as correcting misleading error output 
and by default refusing to verify certificates that use the implicitCurve option with a proper error) and
* those that - upon being explicitly enabled - support the use of the deprecated implicitCurve mechanism.

**Comment by kroeckx** [comment]
If we ever supported it, it's clearly been broken for a long time
without anybody complaining about it. Don't fix it, just remove
it. Don't bother with deprecating it first.

**Comment by t8m** [comment]
Closing as we are not going to add implictCurve support.

**Pull request closed without merging**
