### PR TITLE
Add alias for des-ede-ecb and Fix generate scripts order

### PR DESCRIPTION
**Pull request by Kirill-Marinushkin**
See commits comments

### CODE REVIEW

**Comment by levitte** [comment]
+1

**Comment by richsalz** [comment]
No, why add aliases?

**Comment by levitte** [comment]
@richsalz, he does explain it in the commit message.  I don't see the harm.  However, the other commit is important.

**Comment by richsalz** [comment]
RTFC :)
+1
I can merge if you need me to.

**Comment by levitte** [comment]
by my guest :-)

**Comment by richsalz** [comment]
done.

**Pull request closed without merging**
