### PR TITLE
Don't run MSBLOB conversion tests when RSA or DSA are disabled

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [x] tests are added or updated
- [x] CLA is signed

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
okay to backport if you want.

**Review by richsalz — APPROVED** [review]
okay to backport if you want.

**Comment by levitte** [comment]
Merged

**Comment by levitte** [comment]
@richsalz, I'm sorry, I didn't see your comment before now.  Backported to 1.1.0: 4b74b511131cf6703c82c25656bac7058d8ebe2f

**Pull request closed without merging**
