### PR TITLE
Update copyright years of auto-generated header files to 2021

### PR DESCRIPTION
**Pull request by DDvO**
Apparently I've been the only one since New Year who has been submitting or updating PRs.

It turns out there is an issue with `make update`,
and this PR just provides a quick workaround for 2021.

I've labeled this urgent since without it the CI check_update fails.

### CODE REVIEW

**Review by mspncp — APPROVED** [review]

**Comment by DDvO** [comment]
This was really quick (and sufficiently trivial) - thanks @mspncp.
Merged.

**Comment by richsalz** [comment]
Don't folks do a "make update" as part of doing a complete build before submitting a PR?  You should; it would catch this.

**Comment by DDvO** [comment]
> Don't folks do a "make update" as part of doing a complete build before submitting a PR? You should; it would catch this.

I thought so, too, and had tried it, but it did not help in this case.

**Comment by richsalz** [comment]
> but it did not help in this case

oh, that's disappointing.  I'll add some comments to #13765 and not this closed thread.

**Pull request closed without merging**
