### PR TITLE
des/des_locl.h: clean up unused macros.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by t-j-h** [comment]
OPENSSL_SYS_WIN32 is used in a lot of places - why change that here?

**Comment by t-j-h** [comment]
And that isn't an unused macro - you have two things mixed in the one commit.

**Comment by levitte** [comment]
Hmmm?  Has this removed the definition of a macro that's actually used?   I'm confused...

**Comment by t-j-h** [comment]
No - Andy has two changes there - one removing macros that are unused - and other changing from OPENSSL_SYS_WIN32 to _WIN32- which is not the same thing (and should only be looked at if we are deciding to stop using OPENSSL_SYS_WIN32 everywhere - rather than just in one place).

It drops out three macros and changes the use of one define - it is mixing in the change of a define that is widely used and entirely unrelated to removing unused macros that I am noting.

**Comment by levitte** [comment]
Ah, right, good point

**Comment by dot-asm** [comment]
Update pushed. Commit message will be changed to "clean up unused/irrelevant macros."

**Comment by levitte** [comment]
(with the clarification, I think this answers @t-j-h's concern)

**Pull request closed without merging**
