### PR TITLE
Test the FIPS provider from openssl-3.0 branch with the master and vice versa

### PR DESCRIPTION
**Pull request by t8m**
There was one change necessary in the EVP test to skip testcases of a feature unimplemented in 3.0.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
I'll drop the on pull-request in a fixup commit as I do not think we want to run these tests for every pull request.

**Comment by paulidale** [comment]
Is it reasonable to run both tests from the one build rather than building everything twice?
Swap the `build-3.0/providers/fips.so` the `build/providers/fips.so` files and run the tests twice (once for each).

Agreed, this doesn't need to be on pull request, either push or daily -- daily is probably enough but I like the faster response of push.

**Comment by t8m** [comment]
> Is it reasonable to run both tests from the one build rather than building everything twice?

I think for clarity of the results in case of failure it is better to not do that. We have quite some redundancy in the CI anyway and the tests speed up things by doing just build_modules for the provider build so it takes just one and half minute.

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
@paulidale fixup pushed with minor fix and dropping the on pull_request.

**Comment by paulidale** [comment]
A single run could also make future expansion to more branches easier, if properly parameterised.
Still, no need to worry about this now.

**Comment by t8m** [comment]
For the record the passing builds before the dropped on pull_request are here: https://github.com/openssl/openssl/actions/runs/1817771621

**Comment by t8m** [comment]
> A single run could also make future expansion to more branches easier, if properly parameterised.
> Still, no need to worry about this now.

I'd probably still do it in a way that always does just a full build of one branch and just fips provider build of the other branch and does the test. Otherwise inspecting the test results in case of a failure would be hard.

**Comment by t8m** [comment]
@paulidale assuming the approval holds after the fixup.

**Comment by paulidale** [comment]
Yes, all good.

**Comment by t8m** [comment]
Merged to master branch. Thank you for the review.

**Pull request closed without merging**
