### PR TITLE
Fix PKCS7_verify to not have an error stack if it succeeds.

### LINKED ISSUE #15389: PKCS7_verify can add errors to stack even when successful - alpha17
Similar to #14996 it is possible to make a call to `PKCS7_verify` that succeeds in the 3.0.0 alphas, but adds errors to the stack. Reproducer:

```c
#include <openssl/bio.h>
#include <openssl/pkcs7.h>
#include <openssl/pem.h>
#include <openssl/err.h>
#include <assert.h>
#include <string.h>

int main(void) {
    int res = 0;
    const char *sig = "MIME-Version: 1.0\nContent-Type: multipart/signed; protocol=\"application/x-pkcs7-signature\"; micalg=\"sha-256\"; boundary=\"----9B5319FF2E4428B17CD26B69294E7F31\"\n\nThis is an S/MIME signed message\n\n------9B5319FF2E4428B17CD26B69294E7F31\nContent-Type: text/plain\r\n\r\nhello world\n------9B5319FF2E4428B17CD26B69294E7F31\nContent-Type: application/x-pkcs7-signature; name=\"smime.p7s\"\nContent-Transfer-Encoding: base64\nContent-Disposition: attachment; filename=\"smime.p7s\"\n\nMIIDEgYJKoZIhvcNAQcCoIIDAzCCAv8CAQExDzANBglghkgBZQMEAgEFADALBgkq\nhkiG9w0BBwGgggFVMIIBUTCB96ADAgECAgIDCTAKBggqhkjOPQQDAjAnMQswCQYD\nVQQGEwJVUzEYMBYGA1UEAwwPY3J5cHRvZ3JhcGh5IENBMB4XDTE3MDEwMTEyMDEw\nMFoXDTM4MTIzMTA4MzAwMFowJzELMAkGA1UEBhMCVVMxGDAWBgNVBAMMD2NyeXB0\nb2dyYXBoeSBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBj/z7v5Obj13cPu\nwECLBnUGq0/N2CxSJE4f4BBGZ7VfFblivTvPDG++Gve0oQ+0uctuhrNQ+WxRv8GC\n177F+QWjEzARMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhANES\n742XWm64tkGnz8DnpG6u2lHkZFQr3oaVvPcemvlbAiEA0WGGzmYx5C9UvfXIK7NE\nziT4pQtyESE0uRVKXw4nMqkxggGBMIIBfQIBATAtMCcxCzAJBgNVBAYTAlVTMRgw\nFgYDVQQDDA9jcnlwdG9ncmFwaHkgQ0ECAgMJMA0GCWCGSAFlAwQCAQUAoIHkMBgG\nCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIxMDUyMDE4\nNTA0OVowLwYJKoZIhvcNAQkEMSIEIOdwMRgQrqcnmMYvag+BVvErcc6bwUXI94Ds\nQkiyIU9pMHkGCSqGSIb3DQEJDzFsMGowCwYJYIZIAWUDBAEqMAsGCWCGSAFlAwQB\nFjALBglghkgBZQMEAQIwCgYIKoZIhvcNAwcwDgYIKoZIhvcNAwICAgCAMA0GCCqG\nSIb3DQMCAgFAMAcGBSsOAwIHMA0GCCqGSIb3DQMCAgEoMAoGCCqGSM49BAMCBEcw\nRQIhANYMJku1fW9T1MIEcAyREArz9kXCY4tWck5Pt0xzrYhaAiBDSP6e43zj4YtI\nuvQW+Lzv+dNF8EPuhgoPNe17RuUSLw==\n\n------9B5319FF2E4428B17CD26B69294E7F31--\n\n";
    const char *signed_data = "Content-Type: text/plain\r\n\r\nhello world";
    BIO *msg_bio = BIO_new_mem_buf(signed_data, strlen(signed_data));
    const char *cert_pem = "-----BEGIN CERTIFICATE-----\nMIIBUTCB96ADAgECAgIDCTAKBggqhkjOPQQDAjAnMQswCQYDVQQGEwJVUzEYMBYG\nA1UEAwwPY3J5cHRvZ3JhcGh5IENBMB4XDTE3MDEwMTEyMDEwMFoXDTM4MTIzMTA4\nMzAwMFowJzELMAkGA1UEBhMCVVMxGDAWBgNVBAMMD2NyeXB0b2dyYXBoeSBDQTBZ\nMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBj/z7v5Obj13cPuwECLBnUGq0/N2CxS\nJE4f4BBGZ7VfFblivTvPDG++Gve0oQ+0uctuhrNQ+WxRv8GC177F+QWjEzARMA8G\nA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhANES742XWm64tkGnz8Dn\npG6u2lHkZFQr3oaVvPcemvlbAiEA0WGGzmYx5C9UvfXIK7NEziT4pQtyESE0uRVK\nXw4nMqk=\n-----END CERTIFICATE-----";
    BIO *x509_bio = BIO_new_mem_buf(cert_pem, strlen(cert_pem));
    X509 *cert = PEM_read_bio_X509(x509_bio, NULL, NULL, NULL);
    assert(cert != NULL);
    assert(ERR_peek_error() == 0);

    X509_STORE *store = X509_STORE_new();
    assert(store != NULL);
    res = X509_STORE_add_cert(store, cert);
    assert(res == 1);

    BIO *bio = BIO_new_mem_buf(sig, strlen(sig));
    PKCS7 *p7 = SMIME_read_PKCS7(bio, NULL);
    assert(p7 != NULL);
    assert(ERR_peek_error() == 0);
    int flags = PKCS7_TEXT;
    res = PKCS7_verify(p7, NULL, store, msg_bio, NULL, flags);
    assert(res == 1);
    if (ERR_peek_error() != 0) {
        printf("error on stack but verify succeeded\n");
        return 1;
    }
}
```

### PR DESCRIPTION
**Pull request by slontis**
Fixes #15389

The documentation for PKCS7_verify() indicates that the 'out' bio can be
NULL. Fix this function so that in this case no error is raised.

Note: that in 3.0 bio_write_intern() was changed to raise an error if
the bio is NULL. Any code that does not check the return value will have
this issue. This affects  BIO functions that write such as BIO_write.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
I feel like this is needlessly invasive and we should just revert that part of the commit that caused the regression.

**Comment by DDvO** [comment]
> I feel like this is needlessly invasive and we should just revert that part of the commit that caused the regression.

Yes, the newly added checking for NULL input to `BIO_write()` should be reverted along with my suboptimal change to `BIO_write_intern()`.
Yet the rest of this PR, including some code style fixes and new tests, looks good to have!

**Comment by DDvO** [comment]
The return value of `BIO_write_ex()` is inconsistent in various ways.
* When writing the empty string, i.e, zero bytes, it flags an error.
* It is by some strange design different from the codes returned by `BiO_write()`, 
which returns negative values on error and can flag unsupported operation.
* It takes `b == NULL` as error, while `BIO_write()` does not.

**Comment by DDvO** [comment]
> The comment is basically a warning saying dont raise an error here. For when someone tries to do what you did in a few years time :).

I agree that it's good to have a warning there, but IMO it should be phrased differently, e.g.
```
    /* b == NULL is not an error but just means that zero bytes are written. */
```

> This matches the behavior from 111 now.

Right. Unfortunately, it is inconsistent as I just pointed out in more detail.

> i.e BIO_write and BIO_write_ex both return 0 if BIO is NULL.

Yes, but for `BIO_write()` this means no error (but just nothing printed), while for `BIO_write_ex()` this is considered an error.

> It is commented in the return values section.

Yes, but the behavior on `b == NULL` is not documented.

**Comment by slontis** [comment]
> > The comment is basically a warning saying dont raise an error here. For when someone tries to do what you did in a few years time :).
> 
> I agree that it's good to have a warning there, but IMO it should be phrased differently, e.g.
> 
> ```
>     /* b == NULL is not an error but just means that zero bytes are written. */
> ```
> 

ok will change..


> > This matches the behavior from 111 now.
> 
> Right. Unfortunately, it is inconsistent for `BIO_write_ex()` as I just pointed out in more detail.
> 
> > i.e BIO_write and BIO_write_ex both return 0 if BIO is NULL.
> 
> Yes, but for `BIO_write()` this means no error (but just nothing printed), while for `BIO_write_ex()` this is considered an error.

NOT that I can see - both call bio_write_intern() which returns 0.
BIO_write() returns ret which is 0
BIO_write_ex returns 0>0 which is also 0.
What am I missing for the NULL case?

> 
> > It is commented in the return values section.
> 
> Yes, but the behavior on `b == NULL` is not documented.

I am confused.. See line 61 of the BIO_read.pod
BIO_write() and BIO_write_ex() return 0 if the BIO I<b> is NULL.

**Comment by slontis** [comment]
Will change the comment to 
   /*
     * b == NULL is not an error but just means that zero bytes are written.
     * Do not raise an error here - it will break code.
     */

**Comment by DDvO** [comment]
> > I agree that it's good to have a warning there, but IMO it should be phrased differently, e.g.
> > ```
> >     /* b == NULL is not an error but just means that zero bytes are written. */
> > ```
> 
> ok will change..

Thanks.


> > > This matches the behavior from 111 now.
> > 
> > 
> > Right. Unfortunately, it is inconsistent for `BIO_write_ex()` as I just pointed out in more detail.
> > > i.e BIO_write and BIO_write_ex both return 0 if BIO is NULL.
> > 
> > 
> > Yes, but for `BIO_write()` this means no error (but just nothing printed), while for `BIO_write_ex()` this is considered an error.
> 
> NOT that I can see - both call bio_write_intern() which returns 0.
> BIO_write() returns ret which is 0
> BIO_write_ex returns 0>0 which is also 0.
> What am I missing for the NULL case?

As I wrote, for `BIO_write()` the 0 is no error, but for `BIO_write_ex()` it is!


> > > It is commented in the return values section.
> > 
> > Yes, but the behavior on `b == NULL` is not documented.
> 
> I am confused.. See line 61 of the BIO_read.pod (It must be friday :))
> BIO_write() and BIO_write_ex() return 0 if the BIO I is NULL.

Oops, I overlooked that in your latest version.

**Comment by slontis** [comment]
> So b == NULL is forbidden for BIO_write_ex() but not for BIO_write().

I dont see any way around this - this behaviour already existed..
For apps that just print out values and dont check the return value it makes no difference..

What is it you want me to do here? return -1 instead of 0 in bio_write_intern()?
What we have now matches what it did pre 3.0

**Comment by slontis** [comment]
BIO_write() already returns 0 if dlen < 0 which you could also consider to be an error..

**Comment by DDvO** [comment]
> BIO_write() already returns 0 if dlen < 0 which you could also consider to be an error..

Yes, unfortunately here is also a semantic inconsistency, but a very minor one.

I fear that for backward compatibility we cannot correct/change any of the error checking and reporting.
Yet please let us point out all the subtleties/inconsistencies in the documentation.

**Comment by slontis** [comment]
> Yet please let us point out all the subtleties/inconsistencies in the documentation.

This is out of scope for this PR. Please raise an issue or PR.

**Review by t8m — APPROVED** [review]

**Comment by slontis** [comment]
Thanks for the input.. Merged to master.

**Comment by DDvO** [comment]
> > Yet please let us point out all the subtleties/inconsistencies in the documentation.
> 
> This is out of scope for this PR. Please raise an issue or PR.

This is now being handled in #15608.

**Pull request closed without merging**
