### PR TITLE
Github workflows: re-implement a no-shared build

### PR DESCRIPTION
**Pull request by levitte**
We do this both on Ubuntu and MacOS X

### CODE REVIEW

**Comment by t8m** [comment]
And now you have to solve the duplicate symbols problem.

**Comment by levitte** [comment]
Re-created in #14755

**Comment by levitte** [comment]
For testing purposes, I've a merge of this and #14755 in https://github.com/levitte/openssl/tree/fix-11281%2B%2Bworkflow-reimplement-no-shared

**Review by slontis — APPROVED** [review]
This is good to go when the dependancy is fixed..
Try not to add too many more macos builds if we can help it..

**Comment by levitte** [comment]
Rebased just to prove that it now builds without failure

**Review by slontis — APPROVED** [review]
Reapproved.

**Comment by levitte** [comment]
Merged

4a95b70d1e3df791ea569e94067cf0bec1f69557 Github workflows: re-implement a no-shared build

**Pull request closed without merging**
