### PR TITLE
testutil/init.c rename to testutil/testutil_init.c

### PR DESCRIPTION
**Pull request by p-steuer**
Avoid conflicts with some linkers.

Namely z/os linker complaints about two init.o s:
```
find . -name "init\.c"
./test/testutil/init.c
./crypto/init.c
```

### CODE REVIEW

**Comment by levitte** [comment]
I assume that's with static libraries. It's actually surprising that we haven't seen this issue already on, well, *any* no-shared build...

**Comment by p-steuer** [comment]
I asked myself the same ..

**Comment by p-steuer** [comment]
appveyor red cross not relevant

**Comment by p-steuer** [comment]
merged.

master: https://github.com/openssl/openssl/commit/e74b5dcf16dfd7c91d9f9a7e69c447f00d778e17
1.1.1: https://github.com/openssl/openssl/commit/31c3127a94506700a045d00bfe6333cf1258db07

**Pull request closed without merging**
