### PR TITLE
chacha/asm/chacha-ppc.pl: optimize AltiVec/VMX code path.

### PR DESCRIPTION
**Pull request by dot-asm**
32-bit vector rotate instruction was defined from beginning, it
not being used from the start must be a brain-slip...

### CODE REVIEW

**Comment by dot-asm** [comment]
Green check from travis means that modified code was exercised on hardware...

**Comment by dot-asm** [comment]
I apologize for inconvenience, but I spotted couple of "problems". One in ppc-xlate.pl commentary, and minor ABI incompatibility in chacha-ppc.pl, so re-approval is needed...

**Comment by richsalz** [comment]
reconfirm.

**Comment by dot-asm** [comment]
Hmm... It didn't apply, conflicted with 83cf7abf8e9abbd4d0b68c63dc1cb43374aafe63. The torture never stops. Re-based. This calls for following question. The conflict is in commentary, copyright year thing. Re-base worked without conflict, in sense that it detected that referred year update is equivalent to one in this request and just skipped over lines from this request without much fuss. But all this means that I couldn't have an incremental post-approval commit that would show that it's commentary-only modification. In other words there no "tangible" evidence that it's originally submitted code modifications. This formally means that I can't evoke "commentary-only modification, object if you consider that it voids approval" and it formally has to be re-reviewed as if it was new submission. So shall I ask for re-approval?

**Comment by richsalz** [comment]
reconfirm.  this suffering is good for your russian soul :)

**Comment by dot-asm** [comment]
I have to object the rationale, rules should be same for everybody, there should be no room for adjustments for darkness of individual's souls :-)

**Comment by bernd-edlinger** [comment]
reconfirmed.
The most important rule is: break the rules when appropriate.

**Comment by dot-asm** [comment]
> The most important rule is: break the rules when appropriate.

I disagree. To me it's *amend* the rules, but don't break them.

**Pull request closed without merging**
