### PR TITLE
Fix a bad merge in sslapitest

### PR DESCRIPTION
**Pull request by mattcaswell**
A bad merge from #20208 into the 3.0 branch caused a build break.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Marking this as urgent because its a build break. Slightly concerned that the CIs have been red for a week on the 3.0 branch and no-one noticed!

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
OK with urgent

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
Agree urgent

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
