### PR TITLE
Fix a memory leak in X509_STORE_add_cert/crl error handling

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This PR is for 1.0.2 only, as usual that was already fixed on 1.1.0 ...

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Ping?

**Comment by richsalz** [comment]
Hey, @levitte you've  commented on other store stuff :)

**Comment by levitte** [comment]
Oh wow, I had forgotten how different the 1.0.2 implementation is compared to the 1.1.0 one...  Just as for 1.1.0 and on, I find it questionable that an already present object in the store should be considered an error, but there you go...  However, in the 1.0.2 case, it seems appropriate to keep this behavior.

**Comment by richsalz** [comment]
commit c8ee68a.  Thanks!

**Pull request closed without merging**
