### PR TITLE
Fix util/wrap.pl.in for VMS usage

### PR DESCRIPTION
**Pull request by levitte**
In the name of consistency, make sure that this same script is used
across more platforms, in this case VMS.  This removes the need for
`util/local_shlib.com.in` and `util/unlocal_shlib.com.in`, which were
under-used anyway.

### CODE REVIEW

**Comment by levitte** [comment]
There have been other modifications already that has VMS use this
script in all the test recipes, just like Unix.  However, it currently
doesn't work right and needs a bit of fixing.

**Comment by levitte** [comment]
At the very least, this works well as a command line wrapper.  I just
tried this:

``` console
$ perl [.util]wrap.pl [.apps]openssl.exe version -a

OpenSSL 3.2.0-dev  (Library: OpenSSL 3.2.0-dev )
built on: Wed Mar  1 15:40:53 2023 UTC
platform: vms-alpha
options:  bn(64,64)
compiler: CC/DECC  /DEFINE=(OPENSSL_PIC,OPENSSL_BUILDING_OPENSSL,NDEBUG,OPENSSLD
IR="""OSSL$DATAROOT:[000000]""",ENGINESDIR="""OSSL$ENGINES03:""",MODULESDIR="""O
SSL$MODULES:"""'extradefines')/INCLUDE=()/DEFINE=(OPENSSL_PIC,OPENSSL_BUILDING_O
PENSSL,NDEBUG,OPENSSLDIR="""OSSL$DATAROOT:[000000]""",ENGINESDIR="""OSSL$ENGINES
03:""",MODULESDIR="""OSSL$MODULES:"""'extradefines')
OPENSSLDIR: "OSSL$DATAROOT:[000000]"
ENGINESDIR: "OSSL$ENGINES03:"
MODULESDIR: "OSSL$MODULES:"
Seeding source: os-specific
CPUINFO: N/A
```

Without the wrapper, I get this:

``` console
$ mcr [.apps]openssl.exe version -a
%DCL-W-ACTIMAGE, error activating image OSSL$LIBCRYPTO03_SHR
-CLI-E-IMAGEFNF, image file not found DSA101:[SYS0.SYSCOMMON.][SYSLIB]OSSL$LIBCR
YPTO03_SHR.EXE;
```

I could also get other errors, or something like this:

``` console
$ mcr [.apps]openssl.exe version -a
OpenSSL 3.2.0-dev  (Library: OpenSSL 3.0.0 )
...
```

The VMS system I play on doesn't have OpenSSL 3.0 installed yet, so I
get the activation error.

**Comment by levitte** [comment]
I'm still getting weird errors when running the test suite, so there's
more weirdness going on that I need to resolve.

**Comment by levitte** [comment]
This is ready for review.  VMS testing still fails, though, but for a
different reason, which is subject for a different PR.

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Ping.  This is necessary to be able to use `[.util]wrap.pl` manually, the same way that we can use `util/wrap.pl` on Unix.

**Review by beldmit — APPROVED** [review]
LGTM and I trust that you checked it...

**Comment by levitte** [comment]
> LGTM and I trust that you checked it...

Every day for the moment...  I run tests manually like this (this example related to #20449):

``` console
$ perl [.util]wrap.pl [.test]bio_dgram_test.exe
1..2
    # Subtest: test_bio_dgram
    1..4
    # INFO: 
    # # Testing with AF_INET, local=0
    # 
    ok 1 - iteration 1
    # INFO: 
    # # Testing with AF_INET6, local=0
    # 
    # SKIP: 
    # BIO_bind() failed - assuming it's an unavailable address family
    # 
    ok 2 - iteration 2 # skipped
    # INFO: 
    # # Testing with AF_INET, local=1
    # 
    ok 3 - iteration 3
    # INFO: 
    # # Testing with AF_INET6, local=1
    # 
    # SKIP: 
    # BIO_bind() failed - assuming it's an unavailable address family
    # 
    ok 4 - iteration 4 # skipped
ok 1 - test_bio_dgram
    # Subtest: test_bio_dgram_pair
    1..2
    ok 5 - iteration 1
    ok 6 - iteration 2
ok 2 - test_bio_dgram_pair
```

**Comment by levitte** [comment]
Merged

1939ee7f252ffebd91c29384db4133290489e026 Fix util/wrap.pl.in for VMS usage
5ec4f45ef56dfe7733b70413f8e78426f19fb433 Fix how util/wrap.pl is used in OpenSSL::Util::fixup_cmd()

**Pull request closed without merging**
