### PR TITLE
Restore the generic DRBG implementation

### PR DESCRIPTION
**Pull request by mspncp**
This pull request consists of two related commits, the first one being mainly a preparation for the second.

## crypto/rand: rename drbg_rand.c to drbg_ctr.c

The generic part of the FIPS DRBG was implemented in fips_drbg_lib.c and the algorithm specific parts in fips_drbg_<alg>.c for <alg> in {ctr, hash, hmac}. Additionally, there was the module fips_drbg_rand.c which contained 'gluing' code between the RAND_METHOD api and the FIPS DRBG.

When the FIPS code was ported to master in #4019, for some reason the AES-CTR DRBG implementation from fips_drbg_ctr.c ended up in drbg_rand.c instead of drbg_ctr.c.

This commit renames the module drbg_rand.c back to drbg_ctr.c, thereby restoring a simple relationship between the original fips modules and the drbg modules
in master:

```
 fips_drbg_lib.c    =>  drbg_lib.c    /* generic part of implementation */
 fips_drbg_<alg>.c  =>  drbg_<alg>.c  /* algorithm specific implementations */
```

## crypto/rand: restore the generic DRBG implementation

The DRGB concept described in NIST SP 800-90A provides for having different algorithms to generate random output. In fact, the FIPS object module used to implement three of them, CTR DRBG, HASH DRBG and HMAC DRBG.

When the FIPS code was ported to master in #4019, two of the three algorithms were dropped, and together with those the entire code that made RAND_DRBG generic was removed, since only one concrete implementation was left.

This commit restores the original generic behaviour of the DRBG, making room for adding new implementations using different algorithms in the future (like RAND_DRBG_CHACHA20).

### CODE REVIEW

**Comment by richsalz** [comment]
Why is anything other than CTR needed?  It is what s2n and boring use, for example.

**Comment by mspncp** [comment]
> Why is anything other than CTR needed? It is what s2n and boring use, for example.

For me it's not about the question whether we currently need more than one DRBG implementation. Currently, I'm happy with AES-CTR. But can you tell that this won't change in the future?

What I like about the original FIPS DRBG design is the fact that it separates the generic concepts like lifetime management (instantiation, reseeding, error recovery, ...) from the technical details of the underlying algorithm. The latter is exchangeable by a pluggable method. Isn't it precisely this flexibility which is one of the strengths of OpenSSL? This generic concept already existed and I was sad to see it dropped. So I wanted to save it from oblivion.

Maybe you and the other team members think that my change is a useless generalization (we mathematicians are good at those ;-) ). If this is the case, I won't feel offended and close the PR. At least I've tried. But I would be happy to hear @kroeck'x and @paulidale's opinion about it.

**Comment by mspncp** [comment]
@kroeckx, @paulidale, is there any interest in pursuing this pull request?

**Comment by kroeckx** [comment]
On Tue, Jan 02, 2018 at 09:46:30AM +0000, Matthias St. Pierre wrote:
> @kroeckx, @paulidale, is there any interest in pursuing this pull request?

Yes

**Comment by mspncp** [comment]
> Yes

Thanks, good to know. There's no hurry, i'm on vacation until friday.

**Comment by paulidale** [comment]
Yes from me too.

If the current DRBG were found to be vulnerable, where would we be?  A fallback DRBG might change it from world shattering to just painful.  Having a backup just in case seems prudent.  I have concerns about our seeming over reliance on AES.  Maybe, I'm paranoid :)

**Comment by t-j-h** [comment]
I've reviewed an am okay to approved - pending whether or not other omc or committers have objections.
This also does clean up the global namespace - moving the ctr_ functions into drbg_ctr and making them static which is also an improvement.

**Comment by richsalz** [comment]
I am not in favor of this because I think it brings needless complexity.  If AES has problems, the whole world does.  And if we need to replace the CTR DRBG we would need a source upgrade anyway.

But I do not feel strongly enough to oppose those who want it, however misguided they may be :)

**Comment by mspncp** [comment]
> But I do not feel strongly enough to oppose those who want it, however misguided they may be :)

I really like your dry sense of humour. :-)  And I agree in one point: If it ever turns out that AES is broken, then we will be in big trouble and have a lot more problems than just fixing the random generator.

**Comment by nickthetait** [comment]
@richsalz could the design be improved to reduce this additional complexity? Or do you really not think there is value in having a backup ready for when AES vulnerabilities are discovered?

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
