### PR TITLE
Fix some params which should be const in the API

### LINKED ISSUE #1526: const values e.g. const SSL* ssl
We experienced a change between beta6 and release version 1.1.0 concerning const values.
At some stage you return a const SSL\* which is fine, but at other places a non const parameter is required. That generates the need of unwanted casts.

parameter 1: **const SSL\* s**
parameter 2: **SSL_is_server((SSL*)s)**

```
int security_callback(**const SSL* s,** const SSL_CTX* ctx, int op,
                                         int bits, int nid, void *other,
                                         void *ex) {
    int rc = 1;

    security_cb_ex *sdb = (security_cb_ex *)ex;

    switch (op) {
    case SSL_SECOP_TMP_DH: {
        DH* dh = NULL;
        if (**SSL_is_server((SSL*)s)** == 1) {
....
```

### PR DESCRIPTION
**Pull request by mattcaswell**
Fixes #1526

### CODE REVIEW

**Comment by mattcaswell** [comment]
> can we change the API of pre-master functions?

Why not? I thought we'd gone around that circle a hundred times already. We've done it before, it doesn't break source or binary compatibility and it fixes real problems. Why would we not do it?

**Comment by levitte** [comment]
For *function parameters*, constifying is trivial and backward compatible, it only enforces us to keep a social promise.  For *function return types*, it's a different story altogether.

**Comment by richsalz** [comment]
I thought I remember @dot-asm and/or @kroeckx arguing const'ifying params...  Maybe they can comment and correct me or re-argue their position?

**Comment by mattcaswell** [comment]
> I thought I remember @dot-asm and/or @kroeckx arguing const'ifying params... Maybe they can comment and correct me or re-argue their position?

Not had any reply to this last comment. I will leave for another day or so and otherwise take @levitte's approval.

**Comment by mattcaswell** [comment]
>> I thought I remember @dot-asm and/or @kroeckx arguing const'ifying params... Maybe they can comment and correct me or re-argue their position?
>
> Not had any reply to this last comment. I will leave for another day or so and otherwise take @levitte's approval.

Still got no reply, so I took @levitte's approval and pushed.

**Comment by mattcaswell** [comment]
Ok, so it looks like this *did* actually cause an unexpected breakage. Specifically the adding of "const" to the arguments of ASN1_TIME_to_generalizedtime() has broken the pyca tests with this error:

````
ccache gcc-5 -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/home/travis/build/openssl/openssl/test/../include -I/home/travis/build/openssl/openssl/test/../include -L/home/travis/build/openssl/openssl/test/.. -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
build/temp.linux-x86_64-2.7/_openssl.c:756:23: error: conflicting types for 'ASN1_TIME_to_generalizedtime'
 ASN1_GENERALIZEDTIME *ASN1_TIME_to_generalizedtime(ASN1_TIME *,
                       ^
In file included from build/temp.linux-x86_64-2.7/_openssl.c:468:0:
/home/travis/build/openssl/openssl/test/../include/openssl/asn1.h:628:23: note: previous declaration of 'ASN1_TIME_to_generalizedtime' was here
 ASN1_GENERALIZEDTIME *ASN1_TIME_to_generalizedtime(const ASN1_TIME *t,
````

The pyca file src/_cffi_src/openssl/asn1.py has this line in it:

ASN1_GENERALIZEDTIME *ASN1_TIME_to_generalizedtime(ASN1_TIME *,
                                                   ASN1_GENERALIZEDTIME **);

i.e. a copy of the ASN1_TIME_to_generalizedtime() declaration but without the added const. I'm not sure how exactly this is used but I assume it is auto-generating some C code and ending up with mis-matched function declarations.

Not sure what to do about it though? Revert this PR and ban all future addition of "const" until 1.2.0? Or is it a pyca problem?

Ping @levitte, @dot-asm, @kroeckx, @alex, @jon-oracle

**Comment by kaduk** [comment]
I believe the general consensus is that having ones own declarations for functions provided by a third-party library (instead of using that library's headers) is considered Wrong, i.e., that pyca is at fault.  (I expect they have some technical reason in their build process that prevents them from easily just using our headers, but that means they need to be prepared to cope if our stuff changes.)

**Comment by reaperhulk** [comment]
@mattcaswell addition of `const` breaks cryptography because we (perhaps unwisely) decided to try to ensure that function signatures we declare and the ones that OpenSSL declares are identical. We originally took this path because we wanted to avoid scenarios where we declared a type as `int` when in reality it was `size_t` or other potentially dangerous mismatches, but a consequence of our approach is that it also breaks on constification.

 We can resolve this in our own tree by moving the declaration to a different section.

**Comment by mattcaswell** [comment]
Thanks @reaperhulk. So it seems the consensus is that this is an issue for the python cryptography project an not us. I have created #3569 to update our external tests to pull in the fix for this.

**Pull request closed without merging**
