### PR TITLE
 Make ASYNC manuals conform with man-pages(7)

### PR DESCRIPTION
**Pull request by levitte**
Details from man-pages(7) that are used:

     Formatting conventions for manual pages describing functions

         ...
         Variable names should, like argument names, be specified in italics.
         ...

     Formatting conventions (general)

         ...
         Special macros, which are usually in uppercase, are in bold.
         Exception: don't boldface NULL.
         ...

Additionally, expanded some lists to make better use of POD formatting.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
Same  comment as https://github.com/openssl/openssl/pull/10041#issuecomment-536189609

Splitting this up was a bad idea.

**Comment by levitte** [comment]
This change has nothing to do with the things you say in #10041.  Please look.

**Comment by richsalz** [comment]
ENOCOFFEE.  Sorry for the noise.

**Review by t8m — APPROVED** [review]
Nice work.

**Comment by levitte** [comment]
Merged.  Thanks.

dfe1752c8414840b25bf094db2f24f810fefce85  Make ASYNC manuals conform with man-pages(7)

**Pull request closed without merging**
