### PR TITLE
Add the self test type OSSL_SELF_TEST_TYPE_PCT_SIGNATURE

### LINKED ISSUE #16457: Query regarding  ECDSA POST test
Hello,

The POST log says "ECDSA : (KAT_Signature) : Pass"
But when i debugged the code , it is actually doing a pairwise consistency test, i.e generate signature using random k and verify the signature at the end.
But as far as i know , for KAT we need to fix the random value K for generating the signature and compare with the know signature value.   Please let me know if i missing anything here  and about my understanding regarding  KAT and PWCT(pairwise consistency test).

Thanks,
Nagarjun

### PR DESCRIPTION
**Pull request by slontis**
Fixes #16457

The ECDSA and DSA signature tests use Pairwise tests instead of KATS.
Note there is a seperate type used by the keygen for conditional Pairwise Tests.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]
Whether this is a bug fix or not is debatable so OTC should look at this tomorrow whether this can go in 3.0.0. I am OK with it though.

**Comment by t-j-h** [comment]
It is not a bug and unless it was really fixing an actual bug this is simply way too late for 3.0.

**Comment by t-j-h** [comment]
OTC view is this is not required, but harmless and correct and hence should be included.

**Review by t-j-h — APPROVED** [review]

**Comment by paulidale** [comment]
To be merged before the 3.0 branch.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.

**Pull request closed without merging**
