### PR TITLE
Fix leaks on 1.0.2 branch

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Backported from master, for the sake of stability...
Applicable to 1.0.1 branch too.

### CODE REVIEW

**Comment by richsalz** [comment]
+1

**Comment by kroeckx** [comment]
+1

**Comment by richsalz** [comment]
pushed, thanks!

**Comment by kroeckx** [comment]
This actually seems to fail in the test suite:
*** glibc detected *** ../apps/openssl: free(): invalid pointer: 0x00000000012f34c1 ***

**Comment by kroeckx** [comment]
It might be caused by an other patch ...

**Comment by FdaSilvaYY** [comment]
Oups ! There is a miss:
tasn_dec.c:720:33: error:excess elements in struct initializer [-Werror]
    BUF_MEM buf = { 0, NULL, 0, 0 };

The 1.0.2 definition of BUF_MEM_st is shorter than in the trunk.
Want a PR ?

**Comment by kroeckx** [comment]
On Sun, Feb 28, 2016 at 04:22:32AM -0800, FdaSilvaYY wrote:
> Oups ! There is a miss:
> tasn_dec.c:720:33: error:excess elements in struct initializer [-Werror]
>     BUF_MEM buf = { 0, NULL, 0, 0 };
> 
> The 1.0.2 definition of BUF_MEM_st is shorter than in the trunk.
> Want a PR ?

I already fixed that, and free_cont shouldn't be set when you
didn't allocate anything.


Kurt

**Pull request closed without merging**
