### PR TITLE
[DOCS] Fix table inconsistencies detected by mdl

### PR DESCRIPTION
**Pull request by levitte**
This includes a fix in Configurations/unix-Makefile.tmpl to allow
running `make md-nits` from an out-of-source build tree as well.

### CODE REVIEW

**Review by t8m — APPROVED** [review]
IMO urgent as CI is broken due to this.

**Review by beldmit — APPROVED** [review]
LGTM, agree urgent

**Review by paulidale — APPROVED** [review]
okay with urgent

**Comment by levitte** [comment]
Okie, thanks, merging now

**Comment by levitte** [comment]
Merged

5995dc37197dd85baa749325ba23f5aa8ccbe1f6 [DOCS] Fix table inconsistencies detected by mdl
0c74339c730dc74f9f7aeac866f02c780f39b3a9 Configurations/unix-Makefile.tmpl: Ensure that md-nits always works

**Pull request closed without merging**
