### PR TITLE
Add $debug variable and use it to silence build diagnostics

### PR DESCRIPTION
**Pull request by richsalz**
Left behind by commit a6a4d0acd.  Rather than just remove it, I added a ```$debug``` variable.

### CODE REVIEW

**Comment by richsalz** [comment]
ping @levitte et al.

**Comment by levitte** [comment]
Second reviewer, please?

**Comment by iamamoose** [comment]
This pull request is ready to merge

**Comment by paulidale** [comment]
Merged to master.  Thanks.

**Pull request closed without merging**
