### PR TITLE
Don't run the symbol presence test on windows

### LINKED ISSUE #17109: [v3.0.0] C++ v120 toolset support
Hi there,
I Couldn't find anywhere if the OpenSSL v3.0 supports compilation in v120 toolset on Windows platform.
I ask because I tried running the vcvarsall.bat from the VisualStudio v12.0 (2013).
The Configure part went smooth (perl Configure VC-WIN64A enable-fips)
The nmake part went smooth (nmake)
But the nmake test part fails on fips.dll problem.. 
Now before I provide more information maybe using v120 is not OK?

Thanks!

### PR DESCRIPTION
**Pull request by mattcaswell**
Fixes #17109

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Not sure this is the right fix...  The `nm` command that's apparently present in that particular environment probably gives some unexpected output (surprise!!!!!).  I would rather we learn how to parse it.

**Comment by levitte** [comment]
> The `nm` command that's apparently present in that particular environment probably gives some unexpected output (surprise!!!!!).

I just had a look.  Oh boy...

Okie, for now, this PR will have to do.

**Comment by levitte** [comment]
CI failure not relevant

**Review by levitte — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you.

**Pull request closed without merging**
