### PR TITLE
Unable to run asm code on OpenBSD

### LINKED ISSUE #23312: Unable to run asm code on OpenBSD
perlasm files should keep constants/data in '.section .rodata':

Running openssl tests on OpenBSD is futile unless build is configured with `./Configure  no-asm` which disables optimized routines written in assembly. I'll demonstrate the issue on simple example. This is a `main.c`
```
#include <stdio.h>

extern int get_fee();
extern int get_foo();

int
main(int argc, const char *argv[0])
{
        printf("%x\n", get_fee());
        printf("%x\n", get_foo());

        return (0);
}
```
The code above is linked with .o file which is produced from .s below:
```
.global  get_foo
.type   get_foo,@function
get_foo:
        mov .foo(%rip), %rax
        ret

.global  get_fee
.type   get_fee,@function
get_fee:
        mov .fee(%rip), %rax
        ret

.foo:
        .long 0x00f00f00

.section .rodata

.fee:
        .byte 0x00,0xfe,0xef,0xee
```
The module above defines functions `get_foo()` and `get_fee()`. both functions return `int` which
is a constant `foo` (`fee`) in module `test.s` Code can be built using Makefile as follows:
```
test: main.o test.o
        $(CC) -o test main.o test.o

main.o: main.c
        $(CC) -g -O0 -c -o main.o main.c

test.o: test.s
        $(CC) -c  test.s 

clean:
        rm -f test.o main.o
``` 
Building it and running it as-is on linux (Ubuntu) yields following output:
```
sashan@ubuntu:~/rodata$ make && ./test
cc -g -O0 -c -o main.o main.c
cc -c  test.s 
cc -o test main.o test.o
eeeffe00
f00f00
```
doing the same on OpenBSD box gives me a .core file.
```
lifty$ make && ./test
cc -g -O0 -c -o main.o main.c
cc -c  test.s 
cc -o test main.o test.o
eeeffe00
Segmentation fault (core dumped) 
```
Poking at core file we see we die as soon as we load constant `foo` to `eax` output register
```
lifty$ egdb test test.core  
...
Core was generated by `test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000b9e9d689a20 in get_foo ()
(gdb) disassemble get_foo
Dump of assembler code for function get_foo:
=> 0x00000b9e9d689a20 <+0>:     mov    0x9(%rip),%rax        # 0xb9e9d689a30 <.foo>
   0x00000b9e9d689a27 <+7>:     retq   
End of assembler dump.
(gdb) quit
```
Apart from returning different constants the functions `get_foo()` and `get_fee()` are identical
```
(gdb) disassemble get_fee
Dump of assembler code for function get_fee:
   0x00000b9e9d689a28 <+0>:     mov    -0x1523(%rip),%rax        # 0xb9e9d68850c
   0x00000b9e9d689a2f <+7>:     retq   
End of assembler dump.
```
What makes difference here is where `fee` and `foo` constants/data are placed. The constant `fee` is found in .rodata segment, while constant `foo` is placed to .text segment along the code. OpenBSD does not like variables/constants (a.k.a. data) to be placed into .text segment where code lives.

The CPU I was using to convey my test was amd ryzen.

### PR DESCRIPTION
**Pull request by Sashan**
In order to get asm code running on OpenBSD we must place all constants into .rodata sections.

change comes from @botovq who happens to be OpenSSL port maintainer in OpenBSD community. @botovq says he has ICLA signed, so there should be no risk in taking his changeset.

It fixes asm code for amd64 only.

closes #23312

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Please could you make @botovq the Author of the commit, or if there are parts which you did yourself, mark him as `Co-author`

**Comment by Sashan** [comment]
I've just forced pushed my branch with new author name. To change commit author I've done this:
```
git commit --amend --author="Theo Buehler <tb@openbsd.org>" 
```
I've also updated commit message to:
```
    Unable to run asm code on OpenBSD (amd64)
    
    In order to get asm code running on OpenBSD we must place
    all constants into .rodata sections.
    
    davidben@ also pointed out we need to adjust `x86_64-xlate.pl` perlasm
    script to adjust read-olny sections for various flavors (OSes). Those
    changes were cherry-picked from boringssl.
    
    closes #23312

```
@davidben point me to perl-asm tweak which adjusts `.rodata` sections for various assembler compilers used to build openssl.

**Comment by Sashan** [comment]
@t8m  CI  Windows failures are gone. relevant changes since last time:
- had to add `align=` option where `.rodata` section is used. I'm using it as hint form `masm` flavor, it's ignored for all other assembler flavors. this deals with build-time errors in masm builds
- new version comes with stack which helps us to deal with masm.

**Comment by Sashan** [comment]
@davidben and @botovq your feedback on those changes will be appreciated. the changes to x86_64-xlate.pl are kind of hack which deals with assembler flavors on windows. I think it would be possible to avoid the hack (at least part of it) if we would -re-arrange stuff in various .pl files for x86_64. However I'd like to keep those files as much same as possible so OpenSSL can share legacy (a.k.a. pain) with other *SSL projects. thanks.

**Comment by t8m** [comment]
Could you please amend the commit message to add `Co-authored-by:` annotation to add yourself the credits you deserve? Given the original patch is much smaller I would even say that you should be the author and @botovq should be the co-author.

**Comment by botovq** [comment]
I haven't followed closely, and I don't object to handling it as @t8m
suggests, but it might be cleaner to split this into two commits, where
@sashan is the author of all the perl changes (where I have contributed
nothing) and I am the author of the (mostly mechanical) part moving the
constants into .rodata.

**Comment by t8m** [comment]
Yeah, that would be even better.

**Comment by Sashan** [comment]
Is it still OK to split it to two commits although the Theo's changes don't build on widnows? we need xlate and `align` to get build going, just asking to find it out.

**Comment by Sashan** [comment]
> On Wed, Apr 10, 2024 at 08:55:28AM -0700, Sashan wrote: Is it still OK to split it to two commits although the Theo's changes don't build on widnows? we need xlate and `align` to get build going, just asking to find it out.
> Can't your commit go first? Then mine?

yes, this might work. thanks.

**Comment by t8m** [comment]
We do not require every commit in a PR being built successfully so it does not really matter.

**Comment by levitte** [comment]
I've looked at the failing `basic_clang` build...  it turns out not to be relevant for this PR.

**Comment by levitte** [comment]
Regarding the order of the two commits, it's not really a big deal, like @t8m says.  You could view it in TDD terms, i.e. the first commit is the "test" and the second commit is the fix for the test.  Fine by me.

**Review by levitte — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master branch. Thank you.

**Comment by t8m** [comment]
> This breaks x86_64 llvm-mingw. backtrace: [mpv.txt](https://github.com/openssl/openssl/files/15021871/mpv.txt)

@Andarwinux Could you please open a new issue?

**Pull request closed without merging**
