### PR TITLE
Fix windows 32-bit build

### PR DESCRIPTION
**Pull request by matthauck**
Breakage introduced by #4718

### CODE REVIEW

**Comment by matthauck** [comment]
Ah. There's a CLA now. I'll have to get to that next week...

**Comment by dot-asm** [comment]
If #4718 broke it and this one is supposed to fix it, then how come feedback from appveyor was "green" in #4718 and "red" here? And in preparation for last 1.0.2 release I've attempted *several* VC versions myself. And adding a compiler flag next to BN_LLONG has no effect, and is equivalent to omitting the flag. And it just doesn't work, see appveyor logs. Closing...

**Comment by matthauck** [comment]
In your testing prior to release, did you test a 32-bit windows FIPS build in VC14? Does appveyor do a FIPS 32-bit windows build? If not, that would explain why it was green for you but failed for me. 

That is what I was attempting to do which failed, strangely looking for `FIPS_crypto_set_id_callback`. I found that when I reverted the Configure script changes in f1206f9fadc5ce41694f69129aecac26R597 it built successfully. 

I tried to revert the part of that commit that looked accidental/broken to me, but was admittedly not what I had done locally to get the build to work. Some of the appveyor changes look like intermittent failures (like build timing out before it started, or `nmake` command not being found), but some of them do look legitimate.

I may have messed up the patch, but there is a real build issue here I believe.

**Comment by richsalz** [comment]
We do not test FIPS builds as a general rule.

**Comment by matthauck** [comment]
I see. Interesting...

**Comment by mattcaswell** [comment]
The `FIPS_crypto_set_id_callback` issue was fixed in commit 18df0adda98 just recently. This was a long standing issue that only ever presented a warning on Windows. Commit b2921cf7f2 made that warning an error which is why this is suddenly an issue now. See also #4870 and #2533.

**Comment by matthauck** [comment]
Awesome. Glad to hear it. I wasn't clear why reverting that change fixed as they seemed like pretty separate things. 

Thanks.

**Comment by coffeeaddict19** [comment]
@richsalz If as you say FIPS builds are excluded from testing why continue to provide FIPS support in OpenSSL? Why do something if you are not going to do it well? My organization relies on OpenSSL FIPS. Is OpenSSL moving away from supporting FIPS?

**Comment by richsalz** [comment]
We are not moving away from FIPS; we hope to say something positive soon.

But do not that the 1.0.2-based FIPS module does not allow *any changes.*  This means no bugfixes, no changes to the build procedure, and so on.  If any changes are made, somebody has to work with the FIPS validation lab to make an update.  Right now, those cost us money.

So if your company relies on OpenSSL FIPS, then you should (a) treat it as a frozen thing and/or contribute some money to help offset the costs.  But, we don't want to keep the 1.0.2 module alive.  Alive the code was removed from 1.1.0, and we'll have a new approach to doing FIPS in the future.

Ok?

**Comment by coffeeaddict19** [comment]
@richsalz Yes. Making OpenSSL FIPS even work is tricky...almost a right of passage since I am using OpenSSL from the API level not through the OpenSSL.EXE APP. The ambiguity was disconcerting. Thank you for the clarification. I suppose OpenSSL is making the best of a bad situation.

**Pull request closed without merging**
