### PR TITLE
Fix simpledynamic.c - a typo and missed a header

### PR DESCRIPTION
**Pull request by kiyolee**
CLA: trivial

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
LGTM. I agree this is trivial

**Comment by levitte** [comment]
Aha!  I believe we have so many github actions going that we don't see anything else, and regularly forget to scroll down to see how Appveyor fared...

**Review by t8m — APPROVED** [review]
Approved if Appveyor succeeds.

**Comment by levitte** [comment]
Merged

9feb2fce6553df7b2d75cf283826b97407eea55b Fix simpledynamic.c - a typo and missed a header

**Pull request closed without merging**
