### PR TITLE
Add NOTES.UNIX, with a description on how to deal with runpaths

### PR DESCRIPTION
**Pull request by levitte**
[skip ci]

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
for master and 1.1.0

**Comment by levitte** [comment]
Merged

master: 45632ee3bb7ab4ed405d5251d76dd5b94d782adb
1.1.0: 41371618f72b93bdf3e0a4be369e4df6b65334cd

**Comment by levitte** [comment]
Merged

master: 45632ee3bb7ab4ed405d5251d76dd5b94d782adb
1.1.0: 41371618f72b93bdf3e0a4be369e4df6b65334cd

**Comment by petrovr** [comment]
Richard Levitte wrote:
> [SKIP]
>
-rpath work partially : on linux without -Wl,--enable-new-dtags test 
that try to load libraries fail.

**Pull request closed without merging**
