### PR TITLE
Remove DRBG from SSL structure.

### PR DESCRIPTION
**Pull request by paulidale**
The field is unused.

### CODE REVIEW

**Comment by paulidale** [comment]
It is a bit strange.  Merged to master.
I'll assume 1.1.1 as well since it's the same.

**Comment by t-j-h** [comment]
Indeed. Remove where ever it is sitting their unused.

**Comment by paulidale** [comment]
And done.

**Comment by mspncp** [comment]
> It is strange that the commit that introduced this into the structure didn't use it.

FWIW: per-ssl DRBGs were used at some time, but it turned out that per-thread DRBGs are a better alternative, so they were removed in 16cfc2c90d9e7776965db07c1f31bbec2f6c41e3 as part of #5547.

**Pull request closed without merging**
