### PR TITLE
Add test from "Fix re-signing certificates with different key sizes" (3.0)

### PR DESCRIPTION
**Pull request by tmshort**
Tests for #16080 and #18836

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
The issuer comparison has whitespace differences, so a simple cherry-pick from master to 3.0 won't work.

**Review by t8m — APPROVED** [review]
Approved assuming CI passes. I wonder why is there the whitespace difference on master. If that was intentional change or not.

**Review by mattcaswell — APPROVED** [review]

**Comment by tmshort** [comment]
> Approved assuming CI passes. I wonder why is there the whitespace difference on master. If that was intentional change or not.

Looks to be a difference in the `openssl x509 -text` output. The master branch no longer has spaces in the DNs

**Comment by tmshort** [comment]
It was just a comment.

**Comment by tmshort** [comment]
Merged to openssl-3.0

**Pull request closed without merging**
