### PR TITLE
providers: remove unused function pointer definitions

### PR DESCRIPTION
**Pull request by uudiin**

### CODE REVIEW

**Review by paulidale — CHANGES_REQUESTED** [review]
No!  These are forward declarations that allow the functions to be checked against what they are meant to be.

**Comment by uudiin** [comment]
> No! These are forward declarations that allow the functions to be checked against what they are meant to be.

This looks like a pointer variable definition of a function, not a function prototype declaration.
And it is an unused variable.

**Comment by paulidale** [comment]
Removing these is wrong and will never be accepted.

**Comment by richsalz** [comment]
Yes, it is strange to see
```
typedef void (*function_type)(int arg1, ... etc );
```
In a header file and then see
```
static function_type myfunc;
void myfunc(int arg1, ...etc )
{
```

The reason is that because in C you can't do
```
static function_type foo
{
```

The typedef is in a header file shared by the providers and the infrastructure.  There's no other way to ensure that the provider functions match what the infrastructure wants.

**Comment by uudiin** [comment]
> Yes, it is strange to see
> 
> ```
> typedef void (*function_type)(int arg1, ... etc );
> ```
> 
> In a header file and then see
> 
> ```
> static function_type myfunc;
> void myfunc(int arg1, ...etc )
> {
> ```
> 
> The reason is that because in C you can't do
> 
> ```
> static function_type foo
> {
> ```
> 
> The typedef is in a header file shared by the providers and the infrastructure. There's no other way to ensure that the provider functions match what the infrastructure wants.

Thanks, It’s true that I rarely see anything written like this.

**Pull request closed without merging**
