### PR TITLE
apps/passwd: remove the -crypt option.

### PR DESCRIPTION
**Pull request by paulidale**
- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
OMC hold awaiting the outcome of the vote.

**Review by mattcaswell — CHANGES_REQUESTED** [review]
Can we remove the OPENSSL_SUPPRESS_DEPRECATED from this file as a result of this change?

Also, this needs a CHANGES.md entry

**Comment by paulidale** [comment]
Yes, OPENSSL_SUPPRESS_DEPRECATED can and has been removed.  I've added a CHANGES entry.  I also added a history section in the man page noting the removal.

**Review by levitte — APPROVED** [review]
Pending OTC decision

**Comment by t8m** [comment]
> Pending OTC decision

OMC actually

**Review by mattcaswell — APPROVED** [review]
LGTM, pending OMC decision.

**Comment by paulidale** [comment]
Merged to master.  Thanks for the reviews.

**Pull request closed without merging**
