### PR TITLE
Set AFL_MAP_SIZE to avoid breakage in the AFL CI job 

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Comment by t8m** [comment]
This is urgent fix as the AFL Fuzz CI job is broken on the master branch.

**Review by nhorman — APPROVED** [review]

**Comment by t8m** [comment]
@nhorman Are you OK with urgent?

**Review by Sashan — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]
Okay with urgent

**Review by mattcaswell — APPROVED** [review]
Ok with urgent

**Comment by tom-cosgrove-arm** [comment]
Not sure about the `approved` labels - Neil's name is missing from https://www.openssl.org/community/otc.html, so do you actually have two committer approvals?

**Comment by mattcaswell** [comment]
> Not sure about the approved labels - Neil's name is missing from https://www.openssl.org/community/otc.html, so do you actually have two committer approvals?

I just approved anyway, so no matter

**Comment by t8m** [comment]
Merged to the master branch. Thank you for the reviews.

**Comment by nhorman** [comment]
Ack, concur this is urgent

**Pull request closed without merging**
