### PR TITLE
Update asn1 corpora

### PR DESCRIPTION
**Pull request by kroeckx**
This significantly improves the coverage of the asn1 fuzzer.

It's been suggested that we actually move this to a separate repository, so it can be shared across the branches and git doesn't slow down. Can someone make a new repository for this?

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Hmm, this increases the number of files from 19716 to 24898.
I would not be happy if make test would no longer executable without internet connection.
And OTOH al teast on windows creating 25000 small files is painfully slow, no matter where
they are pulled from.

**Review by bernd-edlinger — APPROVED** [review]

**Comment by paulidale** [comment]
We could treat this as an external test -- if downloaded they get run, if not they don't.

**Comment by kroeckx** [comment]
All other corpora are also going to get larger. It's what I now get
for creating a minimal size corpus.

**Comment by kroeckx** [comment]
Also note that it's not part of the tar we release.

**Comment by bernd-edlinger** [comment]
one question: this adds 7680 new uniqe files, but removes 2498 at the same time, why?

**Comment by kroeckx** [comment]
The procedure I use is:
- put all files I have in 1 big directory
- from that directory generate a new minimal set using libfuzzer's merge
  function to an empty directory.
- Use libfuzzer again to merge a 32 bit into that same directory.

This results in 8505 files having a combined size of 3310325 bytes.
Of those files, 825 files happen to be the same as from the previous
corpus.

I could, instead of generating a new minimal set, start from the old set
and only merge files with new coverage. It would still be 2 merges like
before, but now start with a non-empty directory. It would add 2332
files to get a total corpus of 5655 files and 6035862 bytes.

I think libfuzzer prefers smaller files because they're faster.

**Comment by bernd-edlinger** [comment]
By the way, do you have numbers how significant the test coverage increased by this?

**Comment by kroeckx** [comment]
I think it's 587 new coverage edges (and 6786 new features). The
edges are things like braches taken or functions called.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Is this relevant for 3.1 too?
Additional testing alone wouldn't justify 3.0 according to policy.

**Comment by kroeckx** [comment]
> Is this relevant for 3.1 too?

Yes, but I suggest we move all the corpora to an external repository in
all branches, so we have all of the branches use the same corpus.

**Comment by mattcaswell** [comment]
> Yes, but I suggest we move all the corpora to an external repository in
all branches, so we have all of the branches use the same corpus.

Isn't the corpus specific to a particular fuzzer? So if the fuzzer's are slightly different in each branch then can you reuse them in this way?

**Comment by kroeckx** [comment]
> Isn't the corpus specific to a particular fuzzer? So if the fuzzer's are slightly different in each branch then can you reuse them in this way?

The corpus mostly depend on what the rest of the code supports. So some
files might be non-interesting in older branches.

**Comment by bernd-edlinger** [comment]
Cool work.  I just copied the new files over my running error injection test.
and today it found a new bug in the 1.1.1 branch, (well actually in my feature branch):

```
$ ERROR_INJECT=1668583266 ../util/shlib_wrap.sh ./asn1-test ./corpora/asn1/fa3e83c6324c9ae936e6e66b09e155aae02d67ee
# ./corpora/asn1/fa3e83c6324c9ae936e6e66b09e155aae02d67ee
    #0 0x7f42fc532d4f in __sanitizer_print_stack_trace ../../../../src/libsanitizer/asan/asan_stack.cc:36
    #1 0x55c2f6f48bf4 in my_realloc fuzz/test-corpus.c:129
    #2 0x7f42fb1c91e7 in ASN1_STRING_set crypto/asn1/asn1_lib.c:297
    #3 0x7f42fb1a6939 in asn1_string_set_int64 crypto/asn1/a_int.c:350
    #4 0x7f42fb1a6939 in ASN1_INTEGER_set_int64 crypto/asn1/a_int.c:520
    #5 0x7f42fb1dc399 in PKCS8_pkey_set0 crypto/asn1/p8_pkey.c:43
    #6 0x7f42fb59def7 in rsa_priv_encode crypto/rsa/rsa_ameth.c:171
    #7 0x7f42fb4b6994 in EVP_PKEY2PKCS8 crypto/evp/evp_pkey.c:71
    #8 0x7f42fb1d9dfb in i2d_PrivateKey crypto/asn1/i2d_pr.c:23
    #9 0x55c2f6f4814f in FuzzerTestOneInput fuzz/asn1.c:345
    #10 0x55c2f6f48789 in testfile fuzz/test-corpus.c:182
    #11 0x55c2f6f466ef in main fuzz/test-corpus.c:226
    #12 0x7f42f9f32082 in __libc_start_main ../csu/libc-start.c:308
    #13 0x55c2f6f4689d in _start (.../openssl-111-features/fuzz/asn1-test+0x889d)


=================================================================
==624788==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0x7f42fc525808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f42fb1eaa0b in asn1_item_flags_i2d crypto/asn1/tasn_enc.c:64
    #2 0x7f42fb1eaa0b in ASN1_item_i2d crypto/asn1/tasn_enc.c:44
    #3 0x7f42fb59ddea in rsa_priv_encode crypto/rsa/rsa_ameth.c:163
    #4 0x7f42fb4b6994 in EVP_PKEY2PKCS8 crypto/evp/evp_pkey.c:71
    #5 0x7f42fb1d9dfb in i2d_PrivateKey crypto/asn1/i2d_pr.c:23
    #6 0x55c2f6f4814f in FuzzerTestOneInput fuzz/asn1.c:345
    #7 0x55c2f6f48789 in testfile fuzz/test-corpus.c:182
    #8 0x55c2f6f466ef in main fuzz/test-corpus.c:226
    #9 0x7f42f9f32082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 46 byte(s) leaked in 1 allocation(s).
```

this is one of the test files from this PR.  Thanks!

**Comment by bernd-edlinger** [comment]
Actually asn1 corpus is by far the largest set of files, and the hashes are already in the github with this PR.
So I don't think we need the external repository for this PR, but maybe in the future when the growth gets larger.

**Comment by kroeckx** [comment]
OTC: Should a new repository be created to hold the fuzz corpora?

**Comment by t8m** [comment]
**OTC: The corpora files should go into a separate repository which we would make a submodule. This can be done on all the branches.**

**Comment by levitte** [comment]
I suggest `openssl/corpora`.  Agree?  Disagree?  If all agree, then I can make it happen

**Comment by hlandau** [comment]
Fine by me.

**Comment by kroeckx** [comment]
Any update on this?

I would suggest fuzz-corpora instead.

**Comment by paulidale** [comment]
I'd prefer `fuzz` in the name too.

**Comment by kroeckx** [comment]
@levitte Can you create them?

**Comment by kroeckx** [comment]
@levitte ping

**Comment by kroeckx** [comment]
@levitte @t8m Can someone please create the repository? I've been waiting for 4 months for this now. This is blocking various other work.

**Comment by t8m** [comment]
Now we have openssl/fuzz-corpora repo so this PR should be done against that one.

There is also #20683 that makes the openssl/fuzz-corpora repo to be a submodule.

**Comment by levitte** [comment]
I can create a PR against the fuzz-corpora from this.

**Comment by levitte** [comment]
Done, see openssl/fuzz-corpora#1.

I created that PR as follows:

- checked out this PR, then created a patch:

  ``` console
  $ git format-patch HEAD^
  0001-Update-asn1-corpora.patch
  ```
- Applied that patch in my fuzz-corpora clone:

  ``` console
  $ git am -p3 ../master/0001-Update-asn1-corpora.patch
  Tillämpar: Update asn1 corpora
  Packar arkivet automatiskt i bakgrunden för optimal prestanda.
  Se "git help gc" för manuell hushållning.
  ```

  (pardon all the swedish)

**Comment by levitte** [comment]
Closing this in favor of https://github.com/openssl/fuzz-corpora/pull/1.

**Pull request closed without merging**
