### PR TITLE
Make util

### PR DESCRIPTION
**Pull request by richsalz**
This moves all files in the crypto directory, to a new util subdirectory.

### CODE REVIEW

**Comment by levitte** [comment]
I've had a similar though, but with a few differences:

-   not all files are what I would call "utility", some of them are very central core:
    -   the cpuid stuff.
    -   some of the things should really move to an architecture structure.  `vms_rms.h` is one of them.
        (that architecture structure needs to be discussed, or rather, we need to conclude the discussion)
-   I was actually inspired by a comment of yours, and would rather see `lib/` than `util/`

**Comment by levitte** [comment]
Most all, I think we need to have an overall restructuring discussion rather than the random PRs that do just one bit

**Comment by mattcaswell** [comment]
Yes I agree. We should be looking at this as a whole and consider restructuring for 3.0. We have that listed as one of the tasks for 3.0 already.

**Comment by richsalz** [comment]
Does the project intend to do anything in this space?  Should I just close this PR?  (I find the juxtaposition of https://github.com/openssl/openssl/pull/8211#issuecomment-462864509 and #8919 amusing)

**Comment by richsalz** [comment]
There's been no feedback nor action on this since my https://github.com/openssl/openssl/pull/8211#issuecomment-503258828 two weeks ago.  Is the project interested in me udpating this, or should I just close it (and delete the branch) in a few days?

**Comment by mattcaswell** [comment]
I'd like to see a fuller proposal discussed on how we should structure the code moving forwards before we do anything further with this PR.

**Comment by richsalz** [comment]
The *HOLD* was placed in mid-February and the only actionable item is "we need discussion first." So I am closing out this PR now; I opened #9331 as an issue to start discussion. I will delete the branch in a few days.

**Pull request closed without merging**
