### PR TITLE
`p12_kiss.c`: clean sloppy use of `sk_X509_shift()`

### LINKED ISSUE #19389: PKCS12_parse leaves errors on stack [3.0.6]
OpenSSL 3.0.6 has a regression where successful parse of a PKCS12 via `PKCS12_parse` leaves errors on the stack. This appears to be due to changes to error handling in functions that `PKCS12_parse` calls.

### PR DESCRIPTION
**Pull request by DDvO**
After adding error queue entries, an error showed up at this point.

Fixes #19389 in a direct way, alternatively to #19400.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
This is the best fix for the regression IMO.

**Review by paulidale — APPROVED** [review]

**Comment by DDvO** [comment]
On this occasion, 
I've just added a small commit to remove the remaining sloppy use patterns `while (... sk_TYPE_pop...)`.
There were just further two such ones in the OpenSSL code base.

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
I disagree with this. The existing use of the sk_shift() is perfectly legitimate.

**Comment by DDvO** [comment]
> I disagree with this. The existing use of the `sk_shift()` is perfectly legitimate.

The sloppy/legacy pattern `while ((x = sk_TYPE_pop(st)) != NULL)` has at least the drawback that it cannot distinguish between NULL entries on the stack and the empty stack (or `st == NULL`).

**Comment by t8m** [comment]
If the code does not put NULL entries on the stack I do not see any sloppiness in that use of the API.

**Comment by DDvO** [comment]
> If the code does not put NULL entries on the stack I do not see any sloppiness in that use of the API.

Yes, but it is not always clear that the context makes sure that this is the case.

**Comment by t8m** [comment]
**OTC: This is not a bug fix. This should not go in 3.0.**

**Comment by DDvO** [comment]
> **OTC: This is not a bug fix. This should not go in 3.0.**

This is meant as a bug fix, alternatively to #19400.

**Comment by t8m** [comment]
> This is meant as a bug fix, alternatively to #19400.

But OTC decided that this is not a bug fix and #19400 should be accepted.

**Pull request closed without merging**
