### PR TITLE
Fixup conflicting SSL_R_ECH_REQUIRED

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Agree urgent

**Comment by t8m** [comment]
Yeah, this can be seen as urgent as it is a CI fix.

**Review by vdukhovni — COMMENTED** [review]
Please make that 423, the quic-server branch is using 421 and 422.

**Comment by Sashan** [comment]
> Please make that 423, the quic-server branch is using 421 and 422.

I'm not sure about this. I think those numbers should be determined/resolved when branch gets merged to master.

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
Okay with urgent - and whatever number @t8m ends up picking ...

**Comment by t8m** [comment]
I'll keep 421

**Comment by t8m** [comment]
Merged to the feature branch. Thank you for the reviews.

**Pull request closed without merging**
