### PR TITLE
Add 'documentation policy' link to CONTRIBUTING guide.

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]
IMO this should go in all branches. @nhorman @slontis @beldmit do you agree?

**Comment by nhorman** [comment]
ACK, yes to all branches, once the tree thaws

**Comment by t8m** [comment]
Merged to all the active branches. Thank you for your contribution.

**Pull request closed without merging**
