### PR TITLE
Adding JPAKE with Elliptic Curves

### PR DESCRIPTION
**Pull request by mccurryd**
Some context from the original issue I opened: https://github.com/openssl/openssl/issues/6442

This pull request (re)introduces Password Authenticated Key Exchange by Juggling in to Openssl.  This iteration of JPAKE uses elliptic curves instead of finite field.

To learn more about JPAKE, see the RFC here:
https://tools.ietf.org/html/rfc8236

This commit adds an API, `#include <openssl/ecjpake.h>`, for creating and validating each of JPAKE's three rounds.  This implementation can also validate payloads created from mbedTLS (the same algorithm is used).  However, this addition makes no assumption about how a client might coordinate each round of a JPAKE exchange.  It's up to each application to determine their server/client relationships, and how each payload is communicated.

I've refactored this to be more consistent with the coding style in Openssl, but I've not contributed to this project before.  I'll do my best to address any comments that come up on this pull request.

- [ ] documentation is added or updated
- [x] tests are added or updated

Test pass:
```
../test/recipes/80-test_ecjpake.t .. 
1..1
    # Subtest: ../../test/ecjpake_test
    1..3
    ok 1 - test_ecjpake_successful_exchange_with_self
    ok 2 - test_ecjpake_failed_exchange_with_self
    ok 3 - test_ec_zero_knowledge_proof
../../util/shlib_wrap.sh ../../test/ecjpake_test => 0
ok 1 - running ecjpake_test
ok
All tests successful.
Files=1, Tests=1,  3 wallclock secs ( 0.04 usr  0.02 sys +  0.17 cusr  0.06 csys =  0.29 CPU)
Result: PASS
```

### CODE REVIEW

**Comment by richsalz** [comment]
Where is this being used?  We changed our crypto policy, as documented in https://www.openssl.org/blog/blog/2018/01/18/f2f-london/

**Comment by mccurryd** [comment]
Looks like, from the post you linked, I'll at least need to add a build time flag to enable this (and disable by default).  I'm less sure about how the EVP interface would work with this, or how to validate this algorithm being recognized by a standard (which standards/groups are accepted?).

Regarding usage: this was developed to create a symmetric session key, used to encrypt data, between disparate applications; this was for a project I was a part of.  I built this on top of Openssl, and I decided to take a step further to see if I could contribute it.  It's meant to be an API for any application that would want to use it.

**Comment by kroeckx** [comment]
The IETF is clearly a body we recoginize to publish standards. But
that RFC is an independent submission, and it's informational.

What would really help is that there is an actual RFC that makes
use of this, and says which of the many alternative
implementations should be used. It does not specify anything about
how to deal with passwords, just provides some options. It can be
done over DSA or ECDSA and different curves.

What we would need it somethng that says J-PAKE with all those
options.  It should probably also come with test vectors. That way
multiple implementations can really be implemented.

I'm not sure why we would need something like J-PAKE where both
sides share the same secret. I really don't want my password
stored in plain text. Why not just use something like PSK instead?

**Comment by mccurryd** [comment]
> The IETF is clearly a body we recoginize to publish standards. But
> that RFC is an independent submission, and it's informational.

From the RFC author's [blog](https://www.lightbluetouchpaper.org/2008/05/29/j-pake/):
- https://www.iso.org/standard/67933.html

> What would really help is that there is an actual RFC that makes
> use of this, and says which of the many alternative
> implementations should be used. It does not specify anything about
> how to deal with passwords, just provides some options. It can be
> done over DSA or ECDSA and different curves.
> 
> What we would need it somethng that says J-PAKE with all those
> options.  It should probably also come with test vectors. That way
> multiple implementations can really be implemented.

As is, you can choose the elliptic curve group and digest method. A DSA implementation is a little different, and I didn't consider it in scope of this addition.  I'll see if there's more documentation I can dig up.

> I'm not sure why we would need something like J-PAKE where both
sides share the same secret. I really don't want my password
stored in plain text. Why not just use something like PSK instead?

This algorithm assumes you're using a password that's been shared beforehand between both participants, and I'm not making an assumption here of how participants are going to create or share the passwords they use.  The session key that's created should only be valid for one exchange.  

I'm not a cryptography expert so I'll lean on the RFC author's argument to more directly address your point. The password being used is a low entropy, "bad", password.  Given a headless device, which has no intuitive inputs or UI, a person with physical access could more easily derive a password, use it on some other application, and establish a secure channel with a session key that's resistant to dictionary attacks.

**Comment by richsalz** [comment]
We're not discussing the features of the algorithm.  We are interested in knowing if there any standards-track RFC's that use it.  The RFC itself is an individual submission, and while it was published by the IETF, it doesn't represent an Internet standard.  Because of this, it doesn't meet our requirements (at least not so far), and the team is unlikely to accept this PR.  I hope you understand.

**Comment by mccurryd** [comment]
Got it.  And no worries; I misunderstood, and I want to respect your process. There is the [ISO/IEC 11770-4:2017 publication](https://www.iso.org/standard/67933.html) I linked earlier which J-PAKE Is published in.  However, there does not appear to be an IETF standard which adopts this (that I could find).

**Comment by kaduk** [comment]
> As is, you can choose the elliptic curve group and digest method.

I think the point was that we *don't* want to choose -- it's better in some senses if there is a central document that we point to that say "use exactly these parameters and options", and everyone implements that set of things, and can interoperate without worrying about the parameter negotiation.

**Comment by kaduk** [comment]
> The RFC itself is an individual submission, and while it was published by the IETF, it doesn't represent an Internet standard.

And since this is apparently a hot topic in some circles, "independent submission" != "published by the IETF".  This one is from the independent submissions editor, which is unaffiliated with the IETF.

**Comment by paulidale** [comment]
Wouldn't the existence of an ISO standard for this mean it meets the requirements for inclusion?

**Comment by mccurryd** [comment]
I can't review a copy of the ISO standard, without paying for it, to see if it can answer @kroeckx's questions or not.  I don't have context to know why it's not sufficient, but I'm interested in knowing the reason.  Is the assumption that ISO publications don't provide enough detail to have confidence in crypto additions?

**Comment by richsalz** [comment]
As I said, Kurt's questions are also relevant and important.
ISO standards are often called "pay for play" -- anyone willing to fund the work of the group can get a standard made. They are also, as you point out, not freely available.
There are too many options, no test vectors, and as far as we can see, no project is using this.

**Comment by kroeckx** [comment]
I doubt that the ISO version is much different than what is in the
RFC, they have been published around the same time.

I think before we add this we need a standard that makes use of it,
not just the standard itself.

In general, I don't think JPAKE is that interesting. About the
only use case I see is something like wifi.

**Comment by p5n** [comment]
https://tools.ietf.org/html/rfc8236

> Since 2015, J-PAKE has been included in Thread [THREAD] as a standard key agreement mechanism for IoT (Internet of Things) applications

**Pull request closed without merging**
