### PR TITLE
Add support for elf_aux_info() on OpenBSD

### PR DESCRIPTION
**Pull request by brad0**
https://github.com/openbsd/src/commit/ef873df06dac50249b2dd380dc6100eee3b0d23d

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
I would be happy for this to go in as `CLA: trivial`, but I don't know what @openssl/otc think. My reasoning: OpenBSD has adopted `getauxval()` in much the same way as FreebSD has, the detection is similar (check OS version) and this is pretty much the obvious way to write the code

**Comment by brad0** [comment]
Thank you. That is correct.

**Comment by beldmit** [comment]
I agree that it's trivial

**Comment by tom-cosgrove-arm** [comment]
@brad0 To be accepted as "CLA: trivial" we need you to amend the commit message (replacing the existing commit) to contain `CLA: trivial` on a separate line in the commit message body, separated from the rest of the commit message by an empty line. See https://openssl-library.org/policies/cla/index.html. For an example, see [my comment here](https://github.com/openssl/openssl/pull/25257#pullrequestreview-2255031758).

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM, okay with trivial

**Review by tom-cosgrove-arm — CHANGES_REQUESTED** [review]
@brad0 Bah, sorry, the code style check is failing:

```
Style report for commits 0cd9dd703ea575699b2d3cd74f1b8224447f4352..83345488e20de454750e2a2ca9a3c98ca4b1eb75
  crypto/armcap.c:83:'#if' nesting indent = 1 != 2:# if (defined(__FreeBSD__) && __FreeBSD_version >= 1200000) || \
```

Could you put back the extra space after `#` and before `if` on line 83 of `crypto/armcap.c` please?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by beldmit — APPROVED** [review]
LGTM

**Review by shahsb — APPROVED** [review]
LGTM. OK with CLA: trivial

**Comment by shahsb** [comment]
Please mention the issue no in commit on new line. `Fixes #<issue_no>`

Also, please update the description of the PR. Thanks!

**Comment by brad0** [comment]
> Please mention the issue no in commit on new line. `Fixes #<issue_no>`

There isn't an issue to mention.

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Comment by brad0** [comment]
@t8m @shahsb Would it be possible to have this backported to the various 3.x branches?

**Comment by t8m** [comment]
This is a performance feature so no, it is not eligible for backporting to stable branches.

**Pull request closed without merging**
