### PR TITLE
segfault seen with 'openssl s_client -prexit -keymatexport abc'

### PR DESCRIPTION
**Pull request by mmiyashita**
'openssl s_client' dumps core after connection failure trying to export keying material.

% openssl s_client -prexit -keymatexport abc
connect: Connection refused
<...>
Keying material exporter:
    Label: 'abc'
    Length: 20 bytes
Segmentation Fault (core dumped)

### CODE REVIEW

**Comment by richsalz** [comment]
+1

**Comment by mmiyashita** [comment]
Thank you, Rich!

**Comment by kroeckx** [comment]
Should we print any of the export if there is no session?

**Comment by richsalz** [comment]
Isn’t that what the added session-is-null test does?

**Comment by kroeckx** [comment]
No, I mean the whole if() before it

**Comment by richsalz** [comment]
ah right.  yes i agree with you.

**Comment by mmiyashita** [comment]
Should I move the session check to line 2634?

**Comment by richsalz** [comment]
Yes

**Comment by mmiyashita** [comment]
I moved the session check to line 2636 as SSL_SESSION_print() at line 2635 already handle the case where session is NULL.

**Comment by kroeckx** [comment]
+1

**Comment by richsalz** [comment]
commit 1d8b4eb.  thanks!

**Comment by mmiyashita** [comment]
Great! Thank you, Rich and Kurt!

**Comment by bryongloden** [comment]
🎉

**Pull request closed without merging**
