### PR TITLE
asn1/a_int.c: fix "one less minimal negative" corner case in c2i_ibuf.

### PR DESCRIPTION
**Pull request by dot-asm**
Thanks to Kazuki Yamaguchi for report.

----
This is alternative to #3339.

### CODE REVIEW

**Comment by kroeckx** [comment]
This should probably update the existing tests.

**Comment by dot-asm** [comment]
> This should probably update the existing tests.

Trouble there is that I don't find my way in asn1_encode_test. There was suggestion to rearrange it in the way that byte sequence is associated with expected values by pointer and and not by cross-referencing commentaries and indices. I've added a test, but I don't really know what I'm doing...

**Comment by levitte** [comment]
Well, you did get it right.  Please poke at me again next week for a more intermixed set of data...

**Comment by dot-asm** [comment]
1.0.2 is not affected, it was wrong to mark it as target. Other than that, committed and closing.

**Pull request closed without merging**
