### PR TITLE
Build fix 20200222

### PR DESCRIPTION
**Pull request by levitte**
A couple of incorrect things went through in merges of diverse pieces of code.

URGENT!  We have builds failing because of this

### CODE REVIEW

**Comment by levitte** [comment]
Turns out I overdid this PR, one fix cancelled out the other error.  It's now been reduced to something that should work

**Comment by paulidale** [comment]
Travis timeout isn't relevant.
Merged to master.

**Comment by levitte** [comment]
PING!

**Comment by paulidale** [comment]
Ah, the PING! was deleted :)
I was feeling confused.

**Comment by levitte** [comment]
Yeah, I got confused because the tab I had this in wasn't updated before I posted...

**Pull request closed without merging**
