### PR TITLE
EVP_MAC_size()/EVP_KDF_size()/EVP_KDF_reset() rename

### LINKED ISSUE #11320: EVP_MAC_size()
We seem to have an EVP_MAC_size() function:

````
size_t EVP_MAC_size(EVP_MAC_CTX *ctx);
````

However rather than taking an `EVP_MAC` parameter it takes an `EVP_MAC_CTX`.

Shouldn't the function be called `EVP_MAC_CTX_size()`? Or is this deliberate?

### PR DESCRIPTION
**Pull request by slontis**
Fixes #11320

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by levitte — CHANGES_REQUESTED** [review]
Didn't we agree on `EVP_MAC_CTX_get_mac_size()` and `EVP_KDF_CTX_get_mac_size()`?

`EVP_MAC_CTX_size()` and `EVP_KDF_CTX_size()` make me think I'll get the size of the `EVP_MAC_CTX` and `EVP_KDF_CTX` structures...

**Comment by t-j-h** [comment]
I did suggest the _get_ form as being more consistent with our current style. Without it would be consistent with our historical style.
The longer forms of names tend to avoid someone being confused about what is being returned.

**Comment by levitte** [comment]
> The longer forms of names tend to avoid someone being confused about what is being returned.

Exactly

**Comment by slontis** [comment]
Names updated..

**Comment by slontis** [comment]
ping

**Review by levitte — APPROVED** [review]

**Comment by slontis** [comment]
Rebased - no changes were done

**Comment by slontis** [comment]
Thanks. Merged to master

**Pull request closed without merging**
