### PR TITLE
Abstract out policy and extensions in CA.pl

### PR DESCRIPTION
**Pull request by gtbX**
This lets you customize extensions and policy used in CA.pl in one place rather than scattered around.

CLA: trivial

### CODE REVIEW

**Comment by mattcaswell** [comment]
I'm ok with this, but I think it goes beyond "CLA: trivial" by our definition (which generally is used for very small changes/typos etc). Please can you complete a CLA:

https://www.openssl.org/policies/cla.html

**Comment by gtbX** [comment]
ICLA submitted

**Comment by gtbX** [comment]
I submitted an ICLA corresponding to the email address I used to create the commit. Not sure what else needs to happen.

**Comment by t8m** [comment]
Please use `git commit --amend` and then force push to remove the `CLA: trivial` line from the commit.

**Review by kaduk — APPROVED** [review]
@t8m did you expect the close/reopen to clear the "CLA needed" flag?  (It doesn't seem to have done so.)

**Comment by t8m** [comment]
> @t8m did you expect the close/reopen to clear the "CLA needed" flag? (It doesn't seem to have done so.)

Yes, but I did not realize that the commit has CLA: trivial which is incorrect. So I re-added the label and asked for amending the commit message.

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed to master. Thanks.

**Pull request closed without merging**
