### PR TITLE
Move MD2, MD4 and MD5 digests completely to the providers

### PR DESCRIPTION
**Pull request by levitte**
This leaves minimal implementations of EVP_md2, EVP_md4, EVP_md5 and
EVP_mdc2, that are now only there to provide a name for implicit fetches.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Your commit message (and title for this PR) is somewhat misleading: md2 and md4 are not in the *default* provider at all! They exist in the legacy provider only.

**Comment by levitte** [comment]
Ah, good point.  I'll removed "default" and make "provider" plural

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

3103a616dc6b3150eaec0000af767f268a647f6d Move MD2, MD4 and MD5 digests completely to the providers

**Review by t8m — APPROVED** [review]
Looks OK and CI seems to agree.

**Comment by t8m** [comment]
Ah, I had unrefreshed Github page open. :-)

**Comment by h-vetinari** [comment]
Should be moved back to "Done" in the [project board](https://github.com/openssl/openssl/projects/2).

**Comment by levitte** [comment]
Done.  Ah, @t8m's late approval made it move back to "Reviewer approved"...  good to know

**Pull request closed without merging**
