### PR TITLE
The revert of EOF detection change in libssl for 1.1.1

### PR DESCRIPTION
**Pull request by t8m**
##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by kroeckx** [comment]
I think we should not remove things from the public headers.

**Comment by t8m** [comment]
> I think we should not remove things from the public headers.

If we do 1.1.1f release ASAP I think it should not be a problem in this case. Especially that the presence of SSL_R_UNEXPECTED_EOF_WHILE_READING define can be used in applications to check the proper EOF handling in the OpenSSL 3.0.

**Comment by t8m** [comment]
If you think we should keep the BIO_FLAGS_IN_EOF I would be OK with that, but then we need to drop the revert of all the BIO changes. So please tell me what do you prefer.

**Comment by levitte** [comment]
I see no issue keeping BIO_FLAGS_IN_EOF...  but it could be perceived as an added feature...

**Comment by mattcaswell** [comment]
> I see no issue keeping BIO_FLAGS_IN_EOF... but it could be perceived as an added feature...

Or a bug that it wasn't there in the first place?

**Comment by kroeckx** [comment]
Maybe in case we get the unexpected EOF, we should just simulate
the old behaviour?

**Comment by t8m** [comment]
> Maybe in case we get the unexpected EOF, we should just simulate the old behaviour?

That's what the revert of the changes in libssl does.

**Comment by t8m** [comment]
> I see no issue keeping BIO_FLAGS_IN_EOF... but it could be perceived as an added feature...

We already did this for 1.1.1e because it was needed for the proper EOF handling, so I do not see an issue if we just keep it.

**Comment by t8m** [comment]
So I've changed the PR to revert only the libssl changes.

**Comment by kroeckx** [comment]
I wonder if s_client can detect the unexpected EOF, and if we
should still let it return an error.

**Comment by kroeckx** [comment]
So I think the answer to that is, just it can detect it, it now
prints this "Success" error message. I think we should turn that
into a proper error message.

**Comment by t8m** [comment]
> So I think the answer to that is, just it can detect it, it now prints this "Success" error message. I think we should turn that into a proper error message.

That should be a different PR.

**Comment by t8m** [comment]
Merged to 1.1.1 as 0cd2ee64bffcdece599c3e4b5fac3830a55dc0fa and 30d190caf311d534867df97e26b552e628cb7d85

**Pull request closed without merging**
