### PR TITLE
Fix atfork flag.  Avoid double-negatives :)

### PR DESCRIPTION
**Pull request by richsalz**
Alternate fix for #3814

### CODE REVIEW

**Comment by richsalz** [comment]
ping @bernd-edlinger

**Comment by bernd-edlinger** [comment]
okay wil check if it works.

**Comment by bernd-edlinger** [comment]
your patch works,
but why not simply initialize the at-fork thing when OPENSSL_fork_prepare is called
for the first time?

**Comment by richsalz** [comment]
I think most programs will not fork, and those that do need to add a flag.  Not sure if that’s the best way to go, but at least it’s simplest to understand and explain.

**Comment by bernd-edlinger** [comment]
Fine for me if it's OK for you.

**Comment by richsalz** [comment]
thanks!

**Comment by mattcaswell** [comment]
> I think most programs will not fork, and those that do need to add a flag.  Not sure if that’s the best way to go, but at least it’s simplest to understand and explain.

Not sure why that is simplest. Surely if we just do this by default then most people can forget about it? In some scenarios the code calling us does not even know if a fork will take place or not (e.g. consider a shared library that links to OpenSSL, where the end application does the fork).

**Pull request closed without merging**
