### PR TITLE
travis: Use no-shared for the FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION targets

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by kroeckx** [comment]
There was actually a typo in it ...

**Comment by richsalz** [comment]
+1 for the typo fix.

**Comment by kroeckx** [comment]
I added a new commit that should hopefully fix travis.

**Comment by kroeckx** [comment]
@richsalz: ping

**Comment by richsalz** [comment]
+1,

**Pull request closed without merging**
