### PR TITLE
Readability change - srp_verifier.txt

### PR DESCRIPTION
**Pull request by hrtarsia**
I enclosed each of the values (I, g, and N) in single quotes to increase readability and lessen any confusion for the readers.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by hrtarsia** [comment]
This is one of my PR requests for the Software Engineering Assignment with @bbbrumley.

**Comment by bbbrumley** [comment]
Hi!

This looks fine to me, but the maintainers are still gonna want the `CLA` line in the actual commit message; see [the documentation here](https://github.com/openssl/openssl/blob/master/CONTRIBUTING.md), particularly the part about "To amend a missing .."

**Review by mattcaswell — APPROVED** [review]
Agree trivial

**Review by shahsb — APPROVED** [review]

**Comment by shahsb** [comment]
Hence forth, Please add the issue number in the commit message.
Fixes #<no>
Thanks!

**Comment by hrtarsia** [comment]
Will do! Thank you.

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
