### PR TITLE
Fix comment placement in ecp_nistp256.ci

### PR DESCRIPTION
**Pull request by mspncp**
CLA: trivial

_(restores #11160)_

### CODE REVIEW

**Comment by mspncp** [comment]
@scottarc if you agree, I'll raise and merge the pull request for you.

**Comment by scottarc** [comment]
Yep, I agree. :)

**Comment by mspncp** [comment]
Hmmm... GitHub says I can't approve my own pull request. :-P  Somebody else will have to chime in.

**Comment by mspncp** [comment]
Merged to master and 1.1.1, thank you!

c590be6f12 Fix comment placement in ecp_nistp256.ci [master]
93c50f4680 Fix comment placement in ecp_nistp256.ci [1.1.1]

**Pull request closed without merging**
