### PR TITLE
convert tabs to spaces in two distributed Perl scripts

### PR DESCRIPTION
**Pull request by vszakats**
Also fix indentation in `c_rehash.in` to 4 spaces, where a mixture of 4 and 8 spaces was used before, in addition to tabs.

CLA: trivial

This PR without whitespace changes:
https://github.com/openssl/openssl/pull/16459/files?w=1

### CODE REVIEW

**Review by t8m — APPROVED** [review]
IMO this is OK for 3.0.0 as this is just whitespace cleanup.

Also OK with CLA: trivial.

**Comment by vszakats** [comment]
Do you want me to squash these two commits into a single one?

**Comment by t8m** [comment]
> Do you want me to squash these two commits into a single one?

We can do that when merging. It's good to use git commit --fixup in these cases to ease merging though.

**Comment by vszakats** [comment]
Good idea! I've now replaced the second commit with a `commit --fixup` one. If there is something else to do, please let me know.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Second review needed.

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by vszakats** [comment]
Is there anything missing to merge this?

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I've merged this to master and 3.0.  Thanks for the fixups.
Sometimes things slip through cracks....

**Comment by vszakats** [comment]
Thank you @paulidale!

**Pull request closed without merging**
