### PR TITLE
bn_nist: fix strict aliasing problem

### LINKED ISSUE #18225: Elliptic Curve code without ASM is broken with Clang 14
Hello,

It looks like on Linux (x86_64), starting with Clang 14, the code for Elliptic Curves (when assembler is not enabled) is broken when compiled with optimizations (O2/O3). It is totally fine when using assembler, but when using regular C code, some curves will fail in OpenSSL internals. It doesn't seem to be new (I tested a few older versions) and it seems to be also affecting the 3.0.x branch although I have personally experienced it on the 1.1.1 branch.

From running the tests, it seems to be only affecting a few curves (like `secp384r1`, `prime192v1`, `prime256v1`) and it seems to be that some validation does not pass, potentially due to bad codegen. I don't know if OpenSSL has some undefined behaviors in that section of the code as I haven't investigated yet. But, it was working well up to Clang 13, and GCC 11 is good too.

I've tested and generated logs for the following configs:
- 1.1.1n | Clang 14 | No ASM (**broken**)
- 1.1.1n | Clang 14 | ASM (working)
- 1.1.1n | GCC 11 | No ASM (working)

All these tests were done in a Docker container based on Ubuntu 22.04. I've also tested `1.1.1k | Clang 14 | No ASM` and `3.0.2 | Clang 14 | No ASM` which reproduce the exact same issue, so didn't generated logs for them.

[config_1_1_1n_noasm_clang14.txt](https://github.com/openssl/openssl/files/8606273/config_1_1_1n_noasm_clang14.txt)
[tests_1_1_1n_noasm_clang14.txt](https://github.com/openssl/openssl/files/8606276/tests_1_1_1n_noasm_clang14.txt)
[tests_verbose_1_1_1n_noasm_clang14.txt](https://github.com/openssl/openssl/files/8606278/tests_verbose_1_1_1n_noasm_clang14.txt)

[config_1_1_1n_asm_clang14.txt](https://github.com/openssl/openssl/files/8606272/config_1_1_1n_asm_clang14.txt)
[tests_1_1_1n_asm_clang14.txt](https://github.com/openssl/openssl/files/8606275/tests_1_1_1n_asm_clang14.txt)

[config_1_1_1n_noasm_gcc.txt](https://github.com/openssl/openssl/files/8606274/config_1_1_1n_noasm_gcc.txt)
[tests_1_1_1n_noasm_gcc.txt](https://github.com/openssl/openssl/files/8606277/tests_1_1_1n_noasm_gcc.txt)

### PR DESCRIPTION
**Pull request by paulidale**
As of clang-14 the strict aliasing is causing code to magically disappear.
By explicitly inlining the code, the aliasing problem evaporates.

Fixes #18225

I'd like to wait until llvm/llvm-project#55255 gets commented on before commiting this.

### CODE REVIEW

**Review by t8m — APPROVED** [review]
I like this.

**Comment by guidovranken** [comment]
This is the LibreSSL patch for this issue: https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libcrypto/bn/bn_nist.c.diff?r1=1.19&r2=1.20

**Comment by paulidale** [comment]
Thanks for the counterpoint @guidovranken, @t8m any thoughts on which you prefer?

**Comment by bernd-edlinger** [comment]
I would rather lower the global optimization level for this compiler version.

**Comment by paulidale** [comment]
We'd need to drop it to -O1 or less.  -O2 adds -fstrict-aliasing.  We could single this file out for -fno-strict-aliasing, or perhaps just build everything with -fno-strict-aliasing since it isn't going to hurt the assembly code.

**Comment by t8m** [comment]
I prefer the fix as is in this PR. It fixes the UB as it keeps the union visible in the macro.

**Review by mattcaswell — APPROVED** [review]

**Review by t-j-h — APPROVED** [review]

**Comment by paulidale** [comment]
Merged.

**Comment by mattcaswell** [comment]
Any reason this wasn't backported to 1.1.1? The original issue says that 1.1.1 is also affected

**Comment by mattcaswell** [comment]
> Any reason this wasn't backported to 1.1.1? The original issue says that 1.1.1 is also affected

I created a backport in #18948

**Pull request closed without merging**
