### PR TITLE
Fix serialization of DSA keys to text

### PR DESCRIPTION
**Pull request by jon-oracle**
The call to dsa_priv_print() requires the parameters to be present as they get printed in text form, plus the 'p' value is used to denote the DSA size in bits.
Also added a FIPS test case for this, based off the one in 15-test_genrsa.t.

- [x] tests are added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]
The changed selector overlaps a little bit with work @slontis is doing, but the added test is added value all the same.

**Comment by slontis** [comment]
Hmm while this is good I can see that there are a lot more of these that need to be fixed..
I think they got block copied from the first one which was rsa which doesnt have domain params..

**Review by mattcaswell — APPROVED** [review]

**Comment by slontis** [comment]
Needs a rebase..

**Comment by jon-oracle** [comment]
After the rebase it seems that @slontis already fixed this in a recent commit. Probably worth merging the tests though.

**Comment by slontis** [comment]
The rebase did not modify code so the PR is still ok..
The changes I did were across all encoders, which managed to kit this one that you found also.
Will merge when the tests pass.

**Comment by kroeckx** [comment]
@slontis: Any update on this?

**Comment by slontis** [comment]
kicking off again - it looks like the test was not passing.

**Comment by t8m** [comment]
I suppose this should be rebased to make the test pass?

**Comment by slontis** [comment]
@jon-oracle ?

**Comment by jon-oracle** [comment]
> @jon-oracle ?

Tests seem to be failing. Might be caused by #12876 but I've not had a chance to investigate.

**Comment by paulidale** [comment]
@jon-oracle could you rebase this please?

**Comment by slontis** [comment]
It appears to be the USE_LIBCTX = 1 line.. Which probably means there is a missing libctx accessor somewhere during the write now.. Will track down where it comes from..

**Comment by slontis** [comment]
So this has nothing to do with FIPS at all.
I have added another issue https://github.com/openssl/openssl/issues/13542

**Comment by t8m** [comment]
@jon-oracle Could you please rebase this?

**Pull request closed without merging**
