### PR TITLE
ossl_shim: include core_names.h to resolve undeclared symbols

### LINKED ISSUE #11987: Travis failure
Travis in master is failing with:
```
test/ossl_shim/ossl_shim.cc: In function 'int bssl::TicketKeyCallback(SSL*, uint8_t*, uint8_t*, EVP_CIPHER_CTX*, EVP_MAC_CTX*, int)':
test/ossl_shim/ossl_shim.cc:396:43: error: 'OSSL_MAC_PARAM_DIGEST' was not declared in this scope
   *p++ = OSSL_PARAM_construct_utf8_string(OSSL_MAC_PARAM_DIGEST, "SHA256", 0);
                                           ^~~~~~~~~~~~~~~~~~~~~
test/ossl_shim/ossl_shim.cc:396:43: note: suggested alternative: 'OSSL_PARAM_DEFN'
   *p++ = OSSL_PARAM_construct_utf8_string(OSSL_MAC_PARAM_DIGEST, "SHA256", 0);
                                           ^~~~~~~~~~~~~~~~~~~~~
                                           OSSL_PARAM_DEFN
test/ossl_shim/ossl_shim.cc:397:44: error: 'OSSL_MAC_PARAM_KEY' was not declared in this scope
   *p++ = OSSL_PARAM_construct_octet_string(OSSL_MAC_PARAM_KEY, kZeros,
                                            ^~~~~~~~~~~~~~~~~~
test/ossl_shim/ossl_shim.cc:397:44: note: suggested alternative: 'OSSL_PARAM_BLD'
   *p++ = OSSL_PARAM_construct_octet_string(OSSL_MAC_PARAM_KEY, kZeros,
                                            ^~~~~~~~~~~~~~~~~~
                                            OSSL_PARAM_BLD
Makefile:27670: recipe for target 'test/ossl_shim/ossl_shim-bin-ossl_shim_cc.o' failed
make[1]: *** [test/ossl_shim/ossl_shim-bin-ossl_shim_cc.o] Error 1
```

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #11987

- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
Merged to master.  Thanks all.

**Comment by bernd-edlinger** [comment]
not fixed:
```
test/ossl_shim/ossl_shim.cc: In function 'int bssl::TicketKeyCallback(SSL*, uint8_t*, uint8_t*, EVP_CIPHER_CTX*, EVP_MAC_CTX*, int)':
test/ossl_shim/ossl_shim.cc:397:77: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   *p++ = OSSL_PARAM_construct_utf8_string(OSSL_MAC_PARAM_DIGEST, "SHA256", 0);
                                                                             ^
test/ossl_shim/ossl_shim.cc:399:58: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
                                            sizeof(kZeros));
                                                          ^
In file included from include/openssl/evp.h:27:0,
                 from test/ossl_shim/include/openssl/base.h:15,
                 from test/ossl_shim/packeted_bio.h:13,
                 from test/ossl_shim/ossl_shim.cc:14:
include/openssl/params.h:88:12: note:   initializing argument 2 of 'OSSL_PARAM OSSL_PARAM_construct_octet_string(const char*, void*, size_t)'
 OSSL_PARAM OSSL_PARAM_construct_octet_string(const char *key, void *buf,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:27674: recipe for target 'test/ossl_shim/ossl_shim-bin-ossl_shim_cc.o' failed
make[1]: *** [test/ossl_shim/ossl_shim-bin-ossl_shim_cc.o] Error 1
Makefile:3126: recipe for target 'build_sw' failed
```

**Comment by paulidale** [comment]
The CIs were clean when I pushed :(

See #12022 for a fix.

**Comment by bernd-edlinger** [comment]
you need [extended tests]

**Pull request closed without merging**
