### PR TITLE
Simplify configudata.pm dependency generation

### PR DESCRIPTION
**Pull request by levitte**
While we're at it, correct the fault in windows-makefile.tmpl

### CODE REVIEW

**Comment by dot-asm** [comment]
+1 since makefiles are in shape.

**Comment by levitte** [comment]
Forgot to say, this is for both master and 1.1.0.  Still fine?

**Comment by dot-asm** [comment]
> this is for both master and 1.1.0.

Yes, plus-one applied under this assumption.

**Comment by levitte** [comment]
Good.  Thanks.  Merged...

**Pull request closed without merging**
