### PR TITLE
Fix a test_verify failure

### PR DESCRIPTION
**Pull request by mattcaswell**
A recently added certificate in test/certs expired causing test_verify to fail.
This add a replacement certificate with a long expiry date.

Marking this as urgent because it is causing current build and Travis failures.

### CODE REVIEW

**Comment by mattcaswell** [comment]
It seems strange that AppVeyor is passing in builds in spite of the problem fixed in this PR. It looks like the tests are not running properly in AppVeyor builds.

**Comment by mattcaswell** [comment]
Ping? This impacts all current builds...

**Comment by paulidale** [comment]
Merged to master.

**Comment by DDvO** [comment]
This fix has a bug. 
`test/certs/ee-self-signed.pem` obviously should be an EE cert,
but it became a CA cert.
`openssl x509 -noout -text -in test/certs/ee-self-signed.pem | grep CA` yields
```
                CA:TRUE
```

**Comment by DDvO** [comment]
> A recently added certificate in test/certs expired causing test_verify to fail.
> This add a replacement certificate with a long expiry date.

IMO it would have been better to keep the original cert and use `-no_check_time`.

**Comment by t8m** [comment]
Please do not reopen pull requests with merged commits. Open a new issue or even better a PR to fix the problem.

**Pull request closed without merging**
