### PR TITLE
Update expired SCT certificates [1.1.1]

### LINKED ISSUE #15179: Test certificates will expire soon
While working on reproducible builds for openSUSE, some tests fail with expired certificates when setting the build date after 2022-06-01. Originally reported by Bernhard Wiedemann in [openSUSE bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=1185637). See also:

```
for cert in `find test -name \*pem` ; do openssl x509 -text < $cert | grep After |grep 2022 && echo $cert ; done 2>&1 |grep -A1 2022
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/ISIC_D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/WSNIC_D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/WKIC_D1_Issuer_ICA.pem
            Not After : Jun  1 00:00:00 2022 GMT
test/certs/embeddedSCTs1_issuer.pem
            Not After : Jun  1 00:00:00 2022 GMT
test/certs/embeddedSCTs1.pem
```

The verbose ouput of test `80-test_ssl_new.t` shows:
```
# ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:33
# [2] compared to [0]
# INFO:  @ test/ssl_test.c:34
# ExpectedResult mismatch: expected Success, got ClientFail.
# 139919277639040:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:ssl/record/rec_layer_s3.c:1543:SSL alert number 45
not ok 2 - iteration 2
```

Since the expiring date is a year from now, could you update these certificates?

### PR DESCRIPTION
**Pull request by t8m**
This is the 1.1.1 version of #18444

It syncs the certificates with master/3.0.

Fixes #15179

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM, agree it's urgent

**Comment by t8m** [comment]
Yes. This is intentional. There are other tests with SHA1 signed certificates (not with embedded SCT but that is not relevant).

**Comment by vdukhovni** [comment]
It may be useful to also commit a script for (re)generating these if the need arises...  Or is that already in place?

**Comment by Bo98** [comment]
> This needs to go to 3.0 also for #18447. Is there a PR for that?

That was handled by #18444.

**Comment by terryzwt** [comment]
When this fixed can release?

**Comment by mattcaswell** [comment]
> When this fixed can release?

Undecided so far

**Comment by rsbeckerca** [comment]
> > When this fixed can release?
> 
> Undecided so far

As a packager, of `1.1.1`, we do need 100% PASS of tests to release anything, so it would be important for us to have this go with `1.1.1p`

**Comment by mattcaswell** [comment]
It will definitely be in 1.1.1p. What is undecided is when 1.1.1p will be.

**Pull request closed without merging**
