### PR TITLE
Remove annoying and pointless pause.

### PR DESCRIPTION
**Pull request by benlaurie**

### CODE REVIEW

**Comment by dot-asm** [comment]
Side comment. I'm reluctant to do this on "all-or-none" grounds. Or in other words I consider it disadvantageous to give special treatment to *one* platform. Well, one can argue that platform in question already has special treatment, because "stty technique used elsewhere" doesn't work. But maybe something similar would? Say
```
(trap "stty `stty -g`; exit 1" 2; stty -icanon min 0 time 50; read waste; exit 0) <&1 || exit
```
...

**Comment by dot-asm** [comment]
> I consider it disadvantageous to give special treatment to one platform.

Natural alternative to seeking for working "stty technique" on platform in question is of course omitting it in all other cases. I.e. core thing of the side comment is non-uniform treatment of one platform.

**Comment by levitte** [comment]
This probably needs to be rebased

**Comment by dot-asm** [comment]
Closed in favour of #4311.

**Pull request closed without merging**
