### PR TITLE
Increase x509 reference

### PR DESCRIPTION
**Pull request by junfx**
when SSL_CTX_add_extra_chain_cert called
CLA: trivial

### CODE REVIEW

**Comment by levitte** [comment]
Nit pick: the `CLA: trivial` line needs to be in the commit messsage, it's not enough for it to be in the PR description.

**Comment by levitte** [comment]
Did you close on purpose?

**Comment by junfx** [comment]
I reopened it.

**Comment by mattcaswell** [comment]
-1

**Comment by mattcaswell** [comment]
Why do you feel this change is necessary. The memory management semantics of this function are well documented:

`The B<x509> certificate provided to SSL_CTX_add_extra_chain_cert() will be
freed by the library when the B<SSL_CTX> is destroyed. An application
B<should not> free the B<x509> object.`

In other words ownership of the X509 object is passed to the SSL_CTX by this function - so a new reference is not required

**Comment by junfx** [comment]
I did not notice that information before.
But it looks odd that let library manage thing created by user.

**Comment by mattcaswell** [comment]
> But it looks odd that let library manage thing created by user.

It is a common pattern in OpenSSL. Often a user only created the object in the first place to pass it to the library.

In any case, whether we like it or not, we cannot change the semantics of this well established function in this way. Applications that were written with the assumption that the library takes ownership would suddenly start leaking x509 objects.

**Pull request closed without merging**
