### PR TITLE
Use native X509_STORE for verify(1)

### PR DESCRIPTION
**Pull request by kaduk**
It seems that the -trusted option to verify(1) used the stack-based version for convenience or lack of documentation of the native functionality.  Switch to using the native (and potentially more performant) native X509_STORE functionality for that application, and supply documentation for such usage of X509_STORE objects.

I had to read the code to write the documentation, so it's possible some details and statements about intent are incorrect and need closer review.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by kaduk** [comment]
@snhenson is this in your bailiwick?

**Comment by kaduk** [comment]
Needs @openssl/omc review.  (I suppose we can just take the X509_STORE documentation if the other change is not desired for some reason.)

**Comment by kaduk** [comment]
I'm not sure who would be the best OMC reviewer for this now that Dr. Steve is gone --  @vdukhovni maybe?

**Comment by levitte** [comment]
I can try and have a look tomorrow...  and it would be good if @vdukhovni looked as well indeed, as he has dealt quite a bit with the verify code lately

**Comment by kaduk** [comment]
I'll wait another day to see if Viktor wants to look, before merging.  Thanks for the review!

**Comment by kaduk** [comment]
Whoops, doc-nits complains about missing RETURN VALUES; @levitte please reconfirm

**Comment by vdukhovni** [comment]
In other words, "-trusted" was used not for convenience, but in order to exercise that feature and increase test coverage.

**Comment by kaduk** [comment]
Interestingly, this started out as an exercise to provide some examples of how X509_STORE itself is used, since I didn't fine any non-TLS consumers, and extracting the core bits from TLS is not something we should require our users to do.

**Comment by vdukhovni** [comment]
Yes, I applaud the documentation.  Perhaps we could even find a way to test both code-paths, but we should not remove the use of the trusted stack entirely.  We could add a "-store" option, that uses a store instead of a stack, and perhaps since it is not functionally different not document it, but use it in some tests?  Or document it anyway, but point out that it does not do anything noticeably different than what happens without it.

**Comment by kaduk** [comment]
It sounds like you are not leaning towards adding some dedicated test utilities (in addition to the one use in crltest), then?

**Comment by vdukhovni** [comment]
The tests of various edge-cases of certificate verification logic in `test/recipes/25-test_verify.t` are implemented via `verify(1)`. I don't think it makes sense to write custom C code for this.

**Comment by kaduk** [comment]
I will go ahead and merge the man page "now" (today), and think about the code change some more.

**Comment by mattcaswell** [comment]
> I will go ahead and merge the man page "now" (today), and think about the code change some more.

So any thoughts about what do with this PR @kaduk?

**Comment by kaduk** [comment]
I don't think the verify implementation change needs to go into 1.1.1 in any form.
I'm somewhat philosophically disinclined to add another option just so that we can have the test suite exercise both paths; adding standalone testing binaries would be more attractive to me in that regard.  But it's not entirely clear how many/which tests would be needed for it to be considered comprehensive.
I'll move this out of the 1.1.1 milestone for now, at least.

**Comment by t8m** [comment]
Please close if this is not really relevant anymore.

**Comment by kaduk** [comment]
I do think we could have better examples of `X509_STORE` usage -- there's currently a `sk_X509_to_store()` helper in `apps/lib/apps.c` that is not terribly illumiating.
We may be better served by a demo or something than the code in this PR, though, but I'm not quite ready to close it out.

**Pull request closed without merging**
