### PR TITLE
Move engines/afalg to engines

### PR DESCRIPTION
**Pull request by richsalz**
No reason why afalg should be its own subdirectory.

### CODE REVIEW

**Comment by levitte** [comment]
Hmmm, care to figure out the CI failures?  I don't have any guesses :-/

**Comment by richsalz** [comment]
engines/build.info is broke, i'll have to look at it in a day or two.

**Comment by levitte** [comment]
Hmmm, I can't reproduce it...

**Comment by richsalz** [comment]
refactored engines/build.info, let's see if it's fixed :)

**Comment by levitte** [comment]
Nope

**Comment by richsalz** [comment]
build.info has afalg and it's apparently afalgeng.  trying now.

**Comment by levitte** [comment]
If that makes a difference, how on *earth* did it work before, on wonders?!? O.o

**Comment by richsalz** [comment]
WOOT!  It works, all is good now :)

**Comment by richsalz** [comment]
merged, done, thanks.!

**Pull request closed without merging**
