### PR TITLE
apps: Stop pretending to care about Netscape keys

### PR DESCRIPTION
**Pull request by levitte**
The documentation says some commands care, but the code says differently.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
For master only.  I agree that for 1.1.1 it is an API change.

**Comment by levitte** [comment]
Ah... I could leave the option in with a comment, in `apps/opt.c`

**Comment by levitte** [comment]
It's been ignored since July 2015, as off 0bc2f365558ed5980ce87d6b2704ca8649ca2a4a

So basically, the last time it was at all used was with 1.0.2

**Comment by levitte** [comment]
BTW, this doesn't break anything in 1.1.1, it's already broken in this respect (and [ahem] hilariously so, I might add):

```
: ; ./util/shlib_wrap.sh openssl rsa -in ../1.1.1/test/testrsa.pem -out foo.ns -outform netscape
rsa: Bad format "netscape"; must be one of:
   PEM/DER
   pkcs12
   smime
   engine
   msblob
   netscape
   nss
   text
   http
   pvk
rsa: Invalid format "netscape" for -outform
rsa: Use -help for summary.
: ; ./util/shlib_wrap.sh openssl rsa -in ../1.1.1/test/testrsa.pem -out foo.ns -outform net
rsa: Bad format "net"; must be one of:
   PEM/DER
   pkcs12
   smime
   engine
   msblob
   netscape
   nss
   text
   http
   pvk
rsa: Invalid format "net" for -outform
rsa: Use -help for summary.
```

So I still think this should be cherry-picked back to 1.1.1.

**Comment by mspncp** [comment]
Replacing a failure by a more sensible failure is _not_ a regression, it's a bugfix. So in this case, go ahead to cherry-pick it, if @paulidale approves.

**Comment by paulidale** [comment]
Yes, 1.1.1 is good too.  Broken is broken and I don't mind why.

**Comment by levitte** [comment]
Merged.

master:
d91d443f0d26262148d1dc9d29f9fdf025b958ca apps: Stop pretending to care about Netscape keys

1.1.1:
b33e7698b8cb853bf94623e5e26f860a893eb677 apps: Stop pretending to care about Netscape keys

**Pull request closed without merging**
