### PR TITLE
Avoid including decoder/encoder/store headers into fips module

### LINKED ISSUE #18618: Too many files added to fips.module.sources
The recent 3.0.4 release added a significant number of header files to fips.module.sources:

https://github.com/openssl/openssl/commit/7d4c4e3113197bbcac7952e4494944a046b66a92

This doesn't seem right. Those header files should probably only be included conditionally, i.e. inside `#ifndef FIPS_MODULE`

### PR DESCRIPTION
**Pull request by t8m**
Fixes #18618

The first commit should cherry pick cleanly to master and the second commit is not necessary there.

### CODE REVIEW

**Comment by mattcaswell** [comment]
The CI failure is surprising - but I don't think related to this change?

**Review by mattcaswell — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
> The CI failure is surprising - but I don't think related to this change?

Eh gods, what???

**Comment by t8m** [comment]
> Do you mean to say we've another one of those test order problems?

No, this time it is a real bug that causes heap corruption when the tests run on a CPU with AVX512 instructions.

**Comment by levitte** [comment]
> > Do you mean to say we've another one of those test order problems?
> 
> No, this time it is a real bug that causes heap corruption when the tests run on a CPU with AVX512 instructions.

It's just that...  #18626 CIs pass.  How does this PR cause that bug to be triggered?

**Comment by beldmit** [comment]
> It's just that... #18626 CIs pass. How does this PR cause that bug to be triggered?

Just runs tests.

**Review by paulidale — APPROVED** [review]
Nice find.

**Comment by t8m** [comment]
Merged to 3.0 and master (only the first commit there). Thank you for the reviews.

**Pull request closed without merging**
