### PR TITLE
Rename ssltest -> ssltest_old

### PR DESCRIPTION
**Pull request by ekasper**
ssltest_old.c is deprecated. New tests should use ssl_test.c, and the
recipes in 80-test_ssl_new.t

### CODE REVIEW

**Comment by levitte** [comment]
+1

**Comment by levitte** [comment]
(only eyeballing this time.  Looks right)

**Comment by richsalz** [comment]
why are we keeping the old test program?

**Comment by ekasper** [comment]
I'm working on migrating everything over to the new test but I'm alone and it takes time. Meanwhile, I want to make it clear that no new tests should be added to the old one.

**Comment by richsalz** [comment]
Ah, so the migration isn’t complete yet.  Got it, thanks.

**Pull request closed without merging**
