### PR TITLE
Enable SHA3 unrolling and EOR3 optimization for Ampere

### PR DESCRIPTION
**Pull request by jiangning-liu-ampere**
Ampere designed chips always support ARMv8 SHA-3 feature.

CLA: trivial

### CODE REVIEW

**Comment by davidben** [comment]
Keep in mind that either direction is making a prediction about the future. By allowlisting individual CPUs, this code is predicting that new CPUs should *not* hit this codepath.

Indeed I don't know if one can say that OpenSSL "generally" prefers this pattern. This allowlisting of CPUs seems to be unique to Arm's contribution here. Indeed what OpenSSL "generally" does is to detect CPU capabilities, *not* list individual CPUs. I think it's clear from the high traffic to this file that Arm's divergence from OpenSSL standard practice here has not been pretty high maintainence. I might suggest a different strategy. (We would have rejected this overall strategy, were it contributed to BoringSSL.)

**Comment by jiangning-liu-ampere** [comment]
Hi @tom-cosgrove-arm,

I totally aggree with @davidben. Can you please explain more why ARM is doing it this way? SHA3 is a kind of ISA level support, e.g. EOR3 instructoin, so openssl should check feature only, and why does part IDs matter?

Would you mind completely removing part IDs check there? If yes, I won't bother adding Ampere support any longer.

Thanks,
-Jiangning

**Comment by slontis** [comment]
@tom-cosgrove-arm any further thoughts on this PR?

**Review by tom-cosgrove-arm — APPROVED** [review]
As I said, we've generally not done it this way because we've found that specific optimisations aren't always faster for future cores, but I won't block this

**Review by t8m — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
@t8m Thanks for removing the label for me - I was getting 500 errors from GitHub and couldn't do it!

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
