### PR TITLE
Simpler square-root computation for Ed25519

### PR DESCRIPTION
**Pull request by jamuir**
**Description:**
Mark Wooden and Franck Rondepierre noted that the square-root-mod-p
operations used in the EdDSA RFC (RFC 8032) can be simplified.  For
Ed25519, instead of computing `u*v^3 * (u * v^7)^((p-5)/8)`, we can
compute `u * (u*v)^((p-5)/8)`.  This saves 3 multiplications and 2
squarings.  For more details (including a proof), see the following
message from the CFRG mailing list:

  https://mailarchive.ietf.org/arch/msg/cfrg/qlKpMBqxXZYmDpXXIx6LO3Oznv4/

Note that the Ed448 implementation (see
ossl_curve448_point_decode_like_eddsa_and_mul_by_ratio() in
./crypto/ec/curve448/curve448.c) appears to already use this simpler
method (i.e. it does not follow the method suggested in RFC 8032).

**Testing:**
Build and then run the test suite:

```
  ./Configure -Werror --strict-warnings
  make update
  make
  make test
```

Numerical testing of the square-root computation can be done using the
following sage script:

```python
  def legendre(x,p):
      return kronecker(x,p)

  # Ed25519
  p = 2**255-19
  # -1 is a square
  if legendre(-1,p)==1:
      print("-1 is a square")

  # suppose u/v is a square.
  # to compute one of its square roots, find x such that
  #    x**4 == (u/v)**2 .
  # this implies
  #    x**2 ==  u/v, or
  #    x**2 == -(u/v) ,
  # which implies either x or i*x is a square-root of u/v (where i is a square root of -1).
  # we can take x equal to u * (u*v)**((p-5)/8).

  # 2 is a generator
  # this can be checked by factoring p-1
  # and then showing 2**((p-1)/q) != 1 (mod p)
  # for all primes q dividing p-1.
  g = 2
  s = p>>2  # s = (p-1)/4
  i = power_mod(g, s, p)

  t = p>>3  # t = (p-5)/8
  COUNT = 1<<18
  while COUNT > 0:
      COUNT -= 1

      r = randint(0,p-1)   # r = u/v
      v = randint(1,p-1)
      u = mod(r*v,p)

      # compute x = u * (u*v)**((p-5)/8)
      w = mod(u*v,p)
      x = mod(u*power_mod(w, t, p), p)

      # check that x**2 == r, or (i*x)**2 == r, or r is not a square
      rr = power_mod(x, 2, p)
      if rr==r:
          continue

      rr = power_mod(mod(i*x,p), 2, p)
      if rr==r:
          continue

      if legendre(r,p) != 1:
          continue

      print("failure!")
      exit()

  print("passed!")
```

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
We'll need an [CLA](https://www.openssl.org/policies/cla.html) filled in for this.

**Comment by paulidale** [comment]
I just processed it.  It can take a few minutes to wend it's way through the system...

**Comment by paulidale** [comment]
Which wouldn't meet the trivial criteria :)

**Review by t8m — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
Out of curiosity I tried to measure if this has an impact on the Ed25519 performance,
I tried `./util/shlib_wrap.sh apps/openssl speed ed25519` but could not see any, measurable difference.
Did you collect some performance data?

**Comment by jamuir** [comment]
Hi Bernd.  No, I did not do any performance measurements.

Point decoding (the operation that needs a square-root-mod-p) is used only in Ed25519 verification.  Some implementations do two point decodes inside verification, but the openssl implementation does only one.  The time to compute the square root is dominated by the computation `w^((p-5)/8)`.  This change saves 3 mults and 2 squares, but that makes little difference next to `w^((p-5)/8)`.

I did try `./util/shlib_wrap.sh apps/openssl speed ed25519` a few times with this change and without it.  I agree that there is no measurable improvement (note that I did confirm that the code I changed is indeed being executed during verification :-) ) .  I think I would need to modify the verification speed test to uncover the (very) small performance benefit of the simpler computation.

**Comment by bernd-edlinger** [comment]
Yes, thanks for confirmation.
I was just wondering if there is a significant performance improvement that it would justify back-porting to stable branches.

**Comment by t8m** [comment]
Merged to master branch. Thank you for your contribution.

**Comment by jamuir** [comment]
that was quick.  Thanks, Tomas :-)

**Pull request closed without merging**
