### PR TITLE
CRYPTO_secure_malloc_init: Do not dump region support for FreeBSD.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by levitte — APPROVED** [review]
Ok.  Do you know if this is applicable for the other popular BSDs as well?  Considering how much cross pollination there is between Open-, Net- and FreeBSD, I wouldn't be surprised...

**Comment by levitte** [comment]
BTW, is this a 1.1.1 fix or a master fix, or both?

**Comment by devnexen** [comment]
> Ok. Do you know if this is applicable for the other popular BSDs as well? Considering how much cross pollination there is between Open-, Net- and FreeBSD, I wouldn't be surprised...

On OpenBSD there is is similar feature but in mmap level, usual approach is to use this flag and define to 0 for all other platforms.

**Comment by devnexen** [comment]
Good question well if it can apply to both would be great :-)

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
> Good question well if it can apply to both would be great :-)

It seems you just did :wink:

**Review by paulidale — APPROVED** [review]

**Comment by richsalz** [comment]
If I can make a suggestion, the commit title currently reads like "Don't add dont_dump support" :)  Mabe put the  commit title like "Add FreeBSD support for secure-mallc dont-dump-region" or similar.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master. Thank you for the contribution.

Unfortunately this will not cherry-pick cleanly to 1.1.1 so please create a new PR against 1.1.1 if you want this to be merged there as well.

**Pull request closed without merging**
