### PR TITLE
fix code indentation issue

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
... related to engine_ref_debug macro.

### CODE REVIEW

**Comment by richsalz** [comment]
take the semi-colon off the macro definition in eng_int.h and make sure everything still compiles :)

**Comment by FdaSilvaYY** [comment]
Fixed.

**Comment by richsalz** [comment]
+1 so maybe another team member can review and pull it.

**Comment by kroeckx** [comment]
+1

**Comment by richsalz** [comment]
pushed, thanks.  commit 43d6702

**Comment by FdaSilvaYY** [comment]
So let's close it.

**Pull request closed without merging**
