### PR TITLE
Use rd instead rmdir because if rmdir.exe from cygwin or msys is pres…

### PR DESCRIPTION
**Pull request by mturk**
nmake clean fails if rmdir.exe is present in the path.
Use rd (which is synonym from rmdir) as cmd.exe command

### CODE REVIEW

**Comment by levitte** [comment]
It would make sense to change all `mkdir` to `md` as well...

**Comment by mturk** [comment]
Probably would, but since mkdir does not use any of the Microsoft’s options (actually the are none) so no errors are reported. Well, if mkdir.exe does not handle Windows paths with backslashes, it can break. But yes, using MD would be much safer

**Comment by mturk** [comment]
Actually it’s a weird thing. For example cmd.exe will use his internal rmdir and mkdir unless you explicitly call rmdir.exe, but NMAKE first looks in the PATH, and then uses internal cmd.exe’s command. Having git or using msys perl, you are bound with those posix utils

**Comment by levitte** [comment]
Uhmm, what's this static-crt that got sneaked into this PR?

**Comment by t8m** [comment]
Please rebase and drop the commit that apparently does not belong to this PR.

**Pull request closed without merging**
