### PR TITLE
Ignoring demo executables

### PR DESCRIPTION
**Pull request by beldmit**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Comment by t8m** [comment]
I am not sure if it would be possible to somehow ensure that we won't forget to add here any new executables added in future.

**Comment by t8m** [comment]
> The failures seem irrelevant (but may deserve a separate investigation)

A known problem, unfortunately I did not find time to investigate it yet.

**Comment by beldmit** [comment]
@t8m adding them on ad-hoc basis seems OK. Now I see a wall of files to be ignored and so I'm disturbed :(

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
