### PR TITLE
Github Action: brutally try to merge libcrypto and libssl

### LINKED ISSUE #20304: Add a github action to check for duplicate symbols across libssl/libcrypto
In particular see [this comment](https://github.com/openssl/openssl/issues/20238#issuecomment-1432408097) by @levitte, and issue #20238

### PR DESCRIPTION
**Pull request by levitte**
This build test does one thing only, it tries to brutally merge libcrypto.a
and libssl.a, thus ensuring that there aren't any duplicate symbols between
them.

Fixes #20304

### CODE REVIEW

**Review by tmshort — APPROVED** [review]
Too bad `ar` or `libtool` can't figure this out.

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
> Maybe rename to duplicate_symbol_check.yml ?

Not sure why?  Do you mean we should have one job per yaml file?  I'm rather thinking that this file would collect other special cases...

**Comment by slontis** [comment]
Yep - one per job.  'Special' doesn't mean much if I was looking for this particular check.

**Comment by levitte** [comment]
> Yep - one per job. 'Special' doesn't mean much if I was looking for this particular check.

That's note *entirely* true, but ok, fair enough

**Comment by levitte** [comment]
Rename done

**Review by slontis — APPROVED** [review]
thanks

**Comment by DDvO** [comment]
Why not simply use something like this?
```
nm -g libcrypto.a libssl.a        | awk '{print $3}' | sort | uniq -d
objdump -T libcrypto.so libssl.so | awk '{print $7}' | sort | uniq -d
```

**Comment by tmshort** [comment]
I'm still good with the rename.

**Comment by levitte** [comment]
> Why not simply use something like this?
> 
> ```
> nm -g      libcrypto.a  libssl.a  | awk '{print $3}' | sort | uniq -d
> objdump -T libcrypto.so libssl.so | awk '{print $7}' | sort | uniq -d
> ```

Oh, that was actually smart...  and actually, we have a test recipe that already plays with `nm`, so it shouldn't be too hard to extend!

**Comment by levitte** [comment]
Following @DDvO's question, I submitted an alternative PR, #20311

**Comment by levitte** [comment]
Closing, since #20331 is now merged

**Pull request closed without merging**
