### PR TITLE
Make sure to set DT_RUNPATH rather than DT_RPATH with the GNU toolchain

### LINKED ISSUE #1635: 'make test' picks up the wrong library files
If I install OpenSSL_1_1_0 to the default location, and then build OpenSSL_1_1_0b the "make test" fails because it picks up the .so files from the first install, rather than the incipient library files.

I do a purely default build, i.e. `(./config && make && make test) > /dev/null`

This problem occurs on both CentOS7 and Ubuntu 16.04.

The problem begins with commit 342a1a23793cb9992.  That commit causes the stanza starting with `if [ -f "$LIBCRYPTOSO" -a -z "$preload_var" ]; then` to disappear from the util/shlib_wrap.sh file, which means LD_PRELOAD does not get set.

### PR DESCRIPTION
**Pull request by levitte**
With the GNU toolchain, directories set with -rpath are searched
before LD_LIBRARY_PATH is considered.  If you're building OpenSSL
1.1.1-dev with a prefix where OpenSSL 1.1.0 is already installed, you
get into trouble no matter what you set LD_LIBRARY_PATH.  That can be
fixed by using LD_PRELOAD, but that comes with its own problems.

A better way is to tell the linker to store the -rpath directories
with DT_RUNPATH tags rather than DT_RPATH ones.  DT_RUNPATH
directories are considered after LD_LIBRARY_PATH.

Other platforms that use ELF may have the same issue.

---

Fixes #1635

### CODE REVIEW

**Comment by dot-asm** [comment]
Of course problem with suggested approach is that it affects *all* platforms that rely on rule in question, and it's not given that all actually support it. Somewhat similar problem with --noexecstack assembler option is solved by looking for it in --help output in assembler at hand. It would be more appropriate to probe even for this option. Not necessarily in same way as --noexecstack. [As for latter, it also might be appropriate to move the probe to Configure...]

**Comment by levitte** [comment]
The whole rpath stuff should be moved to config targets...

**Comment by kaduk** [comment]
FreeBSD at least is also impacted by the rpath issue, and has the "new-dtags" runpath support.
While I agree that this stuff belongs in config targets, I think this is enough of an incremental improvement to be worth doing as an interim measure.

**Comment by dot-asm** [comment]
> The whole rpath stuff should be moved to config targets...

Is it established that *all* [older] versions support of any given platform support it?

**Comment by kaduk** [comment]
> Is it established that all [older] versions support of any given platform support it?

Well, what criteria does openssl use to determine what platforms are supported.  Those OS versions which are supported by their respective upstream?

(FreeBSD has had new-dtags since FreeBSD 5.0, which is long out of support by FreeBSD.)

**Comment by levitte** [comment]
@kaduk, I just pushed a commit fixing it specifically for BSD systems.  However, when looking at libcrypto.so with objdump on a FreeBSD 8.4 box, I notice that there is no `DT_RPATH` tag, just a `RPATH` one, and if memory serves, that one is considered after `LD_LIBRARY_PATH`...

**Comment by kaduk** [comment]
@levitte well, I guess I was speaking more in general than specifically for openssl; I had to patch krb5 to use new-dtags for freebsd back in https://github.com/krb5/krb5/commit/453b89100 and so it was on my mind.  Is there a reason to not move to the new dtags anyway, though?

**Comment by levitte** [comment]
There's really only a reason to do so if they're actually used...  I'm checking on that FreeBSD box I mentioned, just to make sure

**Comment by levitte** [comment]
It looks like `Configurations/unix-Makefile.tmpl` is slightly wrong as well...  that special hack for BSD (see the setting of `LIB_LDFLAGS`) gives this linking command:

```
make -f ../openssl/Makefile.shared -e  PLATFORM=BSD-x86_64  PERL="/usr/local/bin/perl5.20.2" SRCDIR='../openssl' DSTDIR="."  INSTALLTOP='/home/levitte/.private-installs/usr' LIBDIR='lib'  LIBDEPS=' '""' '  LIBNAME=crypto LIBVERSION=1.1  LIBCOMPATVERSIONS=';'  CC='cc' CFLAGS='-DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/levitte/.private-installs/usr/ssl\"" -DENGINESDIR="\"/home/levitte/.private-installs/usr/lib/engines-1.1\"" -DL_ENDIAN -Wall -O3 -pthread -D_THREAD_SAFE -D_REENTRANT  -Wa,--noexecstack -fPIC'  LDFLAGS=''  SHARED_LDFLAGS='-Wl,--enable-new-dtags,-rpath,$(LIBRPATH)' SHLIB_EXT=.so.1.1  RC='windres' SHARED_RCFLAGS=''  link_shlib.bsd-gcc-shared
LD_LIBRARY_PATH=: cc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="/home/levitte/.private-installs/usr/ssl" -DENGINESDIR="/home/levitte/.private-installs/usr/lib/engines-1.1" -DL_ENDIAN -Wall -O3 -pthread -D_THREAD_SAFE -D_REENTRANT -Wa,--noexecstack -fPIC -Wl,--enable-new-dtags,-rpath, -shared -Wl,-Bsymbolic -Wl,-soname=libcrypto.so.1.1 -o ./libcrypto.so.1.1 -Wl,--whole-archive,--version-script=crypto.map ./libcrypto.a -Wl,--no-whole-archive
```

I'll have you not how empty the `-rpath` argument is...

**Comment by dot-asm** [comment]
> > Is it established that all [older] versions support of any given platform support it?

> Well, what criteria does openssl use to determine what platforms are supported

What I tried to say is that one doesn't have to answer that question. One can instead ask ld. Note that DO_GNU_APP is used on all kind of OSes.

**Comment by levitte** [comment]
I found out why the `-rpath` argument is empty on BSD...

**Comment by levitte** [comment]
... and with that, to bed.  I'll figure out asking ld tomorrow.

**Comment by kroeckx** [comment]
Why do we even set an rpath? I actually need to remove this in Debian.

The only time an rpath can be useful is when you install something
to a non-default location. It might also be useful for
non-installed binaries so that you don't have to use
LD_LIBRARY_PATH in that case, but then you'd have to relink them
when installing them.

**Comment by levitte** [comment]
> Why do we even set an rpath? I actually need to remove this in Debian.

Very good point.  We did use it in 1.0.x because the default installation was in `/usr/local/ssl/lib`, which isn't a standard location.  With 1.1.0, the default installation directory for the libraries is `/usr/local/lib`, which *is* a standard location.

One could say that for 1.1.x, we should remove all our fiddling with RPATH and let the user set it on the configuration command line if they wish to.  I'll make an alternate PR for this...  tomorrow.

**Comment by levitte** [comment]
Closing this in favor of #1699

**Pull request closed without merging**
