### PR TITLE
Revert: "Put EdDSA back as approved algorithms."

### PR DESCRIPTION
**Pull request by paulidale**
NIST isn't allowing EdDSA at this stage after all, so make it non-FIPS in the FIPS provider.  Guidance for FIPS 140-3 is expected later this month:

> The use of EdDSA still remains non-approved.
>
> Before the FIPS 186-5 and SP 800-186 algorithms / curves can be used in the approved mode, the CMVP will need to do (at least) the following:
>
> - Incorporate FIPS 186-5 and SP 800-186 into SP 800-140C/D;
> - Update IG 10.3.A to incorporate self-test requirements for the new algorithms/curves.
> - Write a new IG on this transition to clarify the issues raised in this thread and elsewhere and provide a clear transition schedule.
>
> The CMVP is working on all three of these items and hope to have drafts public by the end of March.
>
> Since security relevant changes are not permitted for new 140-2 submissions, and under the assumption that this transition away from FIPS 186-4 algorithms will be 'soft' and not move modules to the historical list, we do not plan on writing 140-2 guidance for this transition.

It seems unlikely that all of these requirements will be completed before we submit.

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by hlandau — APPROVED** [review]
What a shame... oh well.

**Comment by paulidale** [comment]
They'll be back, just not for our first 140-3 validation :disappointed:

**Review by slontis — APPROVED** [review]
Sigh..

**Comment by slontis** [comment]
@paulidale Can you confirm what you meant by the statement 'NIST isn't allowing EdDSA at this stage after all, so remove it from the FIPS provider.'

You have not removed it.. You have changed it to not have fips=true.

**Comment by paulidale** [comment]
Read the description which includes NIST's comments and you'll know as much as I do.

I've updated what I wrote to indicate _not approved_ rather than _removed_.

**Comment by paulidale** [comment]
Merged, thanks for the reviews.

**Comment by slontis** [comment]
@paulidale Do you need to look at the entries in encoders.inc and decoders.inc also?

**Comment by paulidale** [comment]
Outside the boundary :grin:

**Comment by xnox** [comment]
> @paulidale Do you need to look at the entries in encoders.inc and decoders.inc also?

not cryptographic algorithms - as it's pure mechanical data translation / marshaling

**Pull request closed without merging**
