### PR TITLE
Fix stack allocations on ppc asm for secp384r1

### PR DESCRIPTION
**Pull request by rohanmclure**
Fix unmatched stack allocation in assembly for `felem_{mul,square}()`. This should always present as a bug.

### CODE REVIEW

**Comment by kroeckx** [comment]
> This should always present as a bug.

Then why doesn't our CI complain about it? There seems to be missing a test in that case.

**Comment by t8m** [comment]
> > This should always present as a bug.
> 
> Then why doesn't our CI complain about it? There seems to be missing a test in that case.

We would need a build with `enable-ec_nistp_64_gcc_128` on PPC cross-compile. We do not do cross-compile runs with non-default build options because it would be impossible to really run them all. We could maybe add some if we identify them as significant.

**Comment by kroeckx** [comment]
Does that even work on ppc64? I thought it didn't like the unaligned access, or that it's at least slower.

**Comment by rohanmclure** [comment]
@kroeckx Each of the NIST curves lend themselves to manual vectorisation where necessary, so the option should be selected where it is deemed to provide best performance. PPC64 can to my knowledge tolerate unaligned accesses with minimal penalties.

**Comment by slontis** [comment]
I assume this code was derived from the p521. Why is the push/pop not needed?

**Comment by rohanmclure** [comment]
> I assume this code was derived from the p521. Why is the push/pop not needed?

Register renaming leads to fair performance, even while the same architected vector register is used for storing each successive limb of `out`. Simply put, I modified the structure of `p521` to remove the need for using vector registers marked as non-volatile by the GNU abi, and so reduced the stack footprint.

**Comment by rohanmclure** [comment]
I will likely modify `p521` in future, as I believe I may be able to get some easy optimisations with P10's new VSX instructions.

**Review by slontis — APPROVED** [review]

**Comment by hlandau** [comment]
Merged to master. Thank you.

**Pull request closed without merging**
