### PR TITLE
Issue #719:

### PR DESCRIPTION
**Pull request by Castaglia**
If no serverinfo extension is found in some cases, do not abort the handshake,
but simply omit/skip that extension.

Check for already-registered serverinfo callbacks during serverinfo
registration.

Update SSL_CTX_use_serverinfo() documentation to mention the need to reload the
same serverinfo per certificate, for servers with multiple server certificates.

### CODE REVIEW

**Comment by Castaglia** [comment]
Created a clean branch (based on master), with only one commit for the above changes; see:

  https://github.com/openssl/openssl/pull/914

**Comment by Castaglia** [comment]
Created a clean branch (based on `OpenSSL_1_0_2-stable`), with only one commit for the above changes; see: https://github.com/openssl/openssl/pull/915

**Comment by mattcaswell** [comment]
+1

**Comment by mattcaswell** [comment]
Ping? Needs a second team review.

**Comment by levitte** [comment]
Errr, what's the difference between this and #915?

**Comment by levitte** [comment]
Neeever mind that question (now removed)

**Comment by WinPack** [comment]
Any second review here?

**Comment by levitte** [comment]
Same remark here as for #915

**Comment by WinPack** [comment]
@levitte Can you re-review?

**Comment by levitte** [comment]
:+1:

**Comment by richsalz** [comment]
done.  thank you!

**Pull request closed without merging**
