### PR TITLE
Add DSA Key validation to default provider

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Dependent on PR #10910 (which depends on #10860 + #10897) and #10780

**Comment by levitte** [comment]
This looks fine, but please rebase and I'll look again, yeah?

**Comment by slontis** [comment]
rebased..

**Comment by slontis** [comment]
Travis failure is a timeout..

**Comment by levitte** [comment]
> Travis failure is a timeout..

Confirmed

**Comment by slontis** [comment]
Merged to master

**Pull request closed without merging**
