### PR TITLE
Make link to RFC 1578 in CHANGES.md be a proper link

### PR DESCRIPTION
**Pull request by t8m**
This is urgent because it fixes make doc nits CI failure (on all 3 branches).

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
@tom-cosgrove-arm - please confirm you're OK with this being urgent fix

**Comment by tom-cosgrove-arm** [comment]
> @tom-cosgrove-arm - please confirm you're OK with this being urgent fix

Yes, that is fine

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches. Thank you for the reviews.

**Pull request closed without merging**
