### PR TITLE
Cleanup error reporting in ssl/

### PR DESCRIPTION
**Pull request by levitte**
Error reporting in `ssl/` is changed to make better use of the newer ERR building blocks, and to drop the old function codes everywhere.

### CODE REVIEW

**Comment by richsalz** [comment]
I assume the bulk of the changes were done using the script?  That should probably be mentioned in the commit.

**Comment by levitte** [comment]
> I assume the bulk of the changes were done using the script? That should probably be mentioned in the commit.

It got me started, yeah

**Comment by levitte** [comment]
> That should probably be mentioned in the commit.

Done

**Comment by levitte** [comment]
@paulidale, this one too? :wink:

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Merged

6849b73ccc38ea95e4b9d50b01e1c94f5ce8bca7 Convert all {NAME}err() in ssl/ to their corresponding ERR_raise() call
e92519b5a6ad5fa1ca36316dd9256e65dcb2c6db SSL: refactor ossl_statem_fatal() and SSLfatal()
c48ffbcca1d0213c6bcbe85de7bb5dd23c76438d SSL: refactor all SSLfatal() calls

**Pull request closed without merging**
