### PR TITLE
Disable problematic test cases on OSX

### PR DESCRIPTION
**Pull request by bernd-edlinger**

### CODE REVIEW

**Comment by kroeckx** [comment]
Why are they problematic?

**Comment by bernd-edlinger** [comment]
because they fail rather often, see the comment in #5977 for instance.
tcp connections to local host as TLSProxy and ssltest_old -ipv4 / -ipv6 need
do fail too often to make the tests useful in my eyes.
Unless some one finds a better work around I would disable these tests.

**Comment by levitte** [comment]
So this is an issue on Travis, I take it? In that case, it might be more useful to skip these tests specifically on Travis...

**Comment by bernd-edlinger** [comment]
I don't know if it is only a travis problem.

**Comment by dot-asm** [comment]
> So this is an issue on Travis, I take it?

I wouldn't be surprised if it's not actually travis-specific. It just might happen that it's much more rare on people's computers. Because they are likely to be less busy/congested. It also might be recognized problem that is fixed on regular computers, but not on travis. After all, it doesn't run "the latest", you know...

**Comment by richsalz** [comment]
For what it's worth, on my Darwin osx laptop I did the following:
```
./config
make -sj10
make test
```
And it passsed.

**Comment by bernd-edlinger** [comment]
Ah thanks, could you please do the make test in a loop for say 10-20 times?

**Comment by dot-asm** [comment]
I'd like to see if #5986 makes any difference....

**Comment by richsalz** [comment]
I ran 20 in sequence, and they all passed.  I then ran three in parallel (separate subdirs separate windows) and they all passed.

**Comment by bernd-edlinger** [comment]
Thanks.
So it really be a travis problem after all....

Is there a way how the test can figure out if it is run under travis?

**Comment by dot-asm** [comment]
> Is there a way how the test can figure out if it is run under travis?

It sets a number of environment variables. TRAVIS_OS_NAME might be best suited.

**Comment by bernd-edlinger** [comment]
Okay, using environment var TRAVIS_OS_NAME.

**Comment by bernd-edlinger** [comment]
Just for completeness, this was the travis build that hit the 10m0s timeout on test_ssl_old.t:
https://travis-ci.org/openssl/openssl/builds/361106361?utm_source=github_status&utm_medium=notification

**Comment by dot-asm** [comment]
Two related things. It's not unlike that problem is specific to osx version. Travis has newer osx images, so it's not inappropriate to verify if problem persists. So I'm going to revive #5986. Secondly, if problem persists it would be appropriate to leave a note somewhere, in commentaries or commit message, that it would be appropriate to revisit it when even newer image is available...

**Comment by dot-asm** [comment]
29 greens in #5986. In other words it appears to be possible to work around this by adding
```
osx_image: xcode9.3
```
to .travis.yml.

**Comment by bernd-edlinger** [comment]
Should I close this PR?

**Comment by dot-asm** [comment]
> Should I close this PR?

If you agree that #5986 is a sensible alternative. One can't be sure though. Even though one could trigger failure on average in 10 attempts on osx 10.12, 30 greens on 10.13 doesn't actually guarantee that there is no problem. So we would still need to keep an eye on it...

**Comment by levitte** [comment]
I'm closing this, since #5986 got approved and merged

**Pull request closed without merging**
