### PR TITLE
Fix state name abbreviation

### PR DESCRIPTION
**Pull request by tmshort**
The TRSCV state abbrev was used for two states:
* TLS_ST_CR_CERT_VRFY
* TLS_ST_SW_CERT_VRFY

The second one is wrong because it's a write operation.
The state for TLS_ST_SW_CERT_VRFY should be "TWSCV"

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
This might apply to 1.1.1, but that might be a change in the ABI...

**Review by kaduk — APPROVED** [review]
Probably safe for 3.0, but also safe to wait, IMO.

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
OTC: This is ok for master. Please update the other strings to drop trailing spaces, and fix the docs (which say the strings are all 6 characters in length).

**Comment by tmshort** [comment]
> OTC: This is ok for master. Please update the other strings to drop trailing spaces, and fix the docs (which say the strings are all 6 characters in length).

I assume you're asking me, and not the OTC to do this.

**Comment by mattcaswell** [comment]
> I assume you're asking me, and not the OTC to do this.

Yes! Thanks.

**Review by mattcaswell — APPROVED** [review]
Does this justify a CHANGES entry?

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Thanks @tmshort 

I don't see a need for a CHANGES entry personally.
I wouldn't say no to one either.

**Review by kaduk — APPROVED** [review]
Reconfirm +1

**Comment by paulidale** [comment]
Merged to master.  Thanks for the fixes.

**Pull request closed without merging**
