### PR TITLE
Dependabot: no longer set an "approval: otc review pending" label

### PR DESCRIPTION
**Pull request by kroeckx**
The label doesn't exist anymore.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by kroeckx** [comment]
Do we need to fight the machine because the branch was created in the openssl repo?

**Comment by t8m** [comment]
> Do we need to fight the machine because the branch was created in the openssl repo?

Yes, unfortunately.

**Comment by t8m** [comment]
Ping @openssl/committers for the second review.

**Review by tom-cosgrove-arm — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Review by shahsb — APPROVED** [review]

**Comment by t8m** [comment]
@shahsb I am really curious what are your intentions with these approvals on PRs like this one. We very much appreciate external (non-committers) reviews which find issues with PRs. However the formal approvals by non-committers are not counted into the required approvals and thus do not provide that much value. Especially on trivial PRs like this one where there is not much to review at all. On bigger PRs it could be worth it to see that additional pair of eyes looked at the change and did not find any issues.

**Comment by t8m** [comment]
@mattcaswell can you please merge this as this is for master branch only?

**Comment by t8m** [comment]
Merged to the master branch. Thank you

**Pull request closed without merging**
