### PR TITLE
Add demo QUIC blocking server

### PR DESCRIPTION
**Pull request by andrewkdinh**
Adds a new demo blocking QUIC server for use with the existing demo QUIC clients.

The same as https://github.com/openssl/openssl/pull/25317, but I didn't realize GitHub would close the PR when I [renamed the branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch).

Associated PR to add a guide: https://github.com/openssl/openssl/pull/25361

Fixes https://github.com/openssl/project/issues/722

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by Sashan — APPROVED** [review]
still looks good to me.

**Comment by Sashan** [comment]
> still looks good to me.

Question to committers: shall we squash all changesets to single commit when merging?

**Review by nhorman — APPROVED** [review]

**Comment by t8m** [comment]
> > still looks good to me.
> 
> Question to committers: shall we squash all changesets to single commit when merging?

Yes, as the commits are just fixups for the initial commit.

**Comment by andrewkdinh** [comment]
Still waiting on review from member from OTC

**Comment by nhorman** [comment]
@andrewkdinh actually you're good, bylaws changed awhile ago, and two committers meet the current requirement

**Comment by t8m** [comment]
Merged to the feature branch. Thank you.

**Pull request closed without merging**
