### PR TITLE
Fix CMP server cert verification w.r.t. 3GPP trust anchor exception

### PR DESCRIPTION
**Pull request by DDvO**
While preparing the upcoming chunk 12 (CLI-based tests) of the CMP contribution
I found two bugs related to the optional exceptional handling of trust anchors for 3GPP.
This PR fixes them and improves the diagnostic output of CMP server cert selection and verification.

### CODE REVIEW

**Comment by DDvO** [comment]
On this PR Travis suffered not only from the usual timeout issue but also from 
```
Trying to create configdata.pm.new: No space left on device at ./Configure line 2578.
```
So nothing due to the contents of this PR.

**Comment by DDvO** [comment]
@mattcaswell, could you please review this as well?

**Comment by DDvO** [comment]
@mattcaswell, I've just cherry-picked the core commit https://github.com/openssl/openssl/commit/1da812778f9098286b8f069391106d0d2eb05017 of this PR over to #11386 such that we can go on there.

How best to proceed this this PR - should I keep it or merge also the remaining tow (rather small) into that PR?

**Comment by mattcaswell** [comment]
I think we should keep the PRs separate. I've just approved this one.

**Comment by DDvO** [comment]
Pushed - thanks!

**Pull request closed without merging**
