### PR TITLE
Exit the loop on failure

### LINKED ISSUE #1752: bio_asn1 infinite loop
When using an asn1 BIO and the sink BIO fails to write returning -1 (error), the state machine keeps retrying in an infinite loop.

The problem is caused by [this line](https://github.com/openssl/openssl/blob/master/crypto/asn1/bio_asn1.c#L211).

I assume the intention of the `break` was to exit the `for` loop, but it only makes the `switch case` end and thus returning to the same state over and over.

It could be solved by replacing the `break` in the indicated line by a `goto done;`.

### PR DESCRIPTION
**Pull request by jon-oracle**
##### Description of change
Fixes #1752
Exit the loop on failure.

### CODE REVIEW

**Comment by richsalz** [comment]
@jon-oracle , can you change the Author to be your oracle address?  Something like this:
```
git commit --am --no-edit --author=jon.spillett@oracle.com
git push -f github
```

thanks!

**Comment by jon-oracle** [comment]
I've changed the author and rebased/pushed the branch

**Comment by jon-oracle** [comment]
Is there anything else required for the CLA-check?

**Comment by richsalz** [comment]
i don't know why the check says "missing"  i will look into it tomorrow morning (10pm my time now). but as long as you signed the ICLA and are on your employers list -- both of those are true -- things are okay.

**Comment by mattcaswell** [comment]
Spelling error in our cladb. Fixed now.

**Comment by richsalz** [comment]
I had a typo in the cla database; matt fixed it.

**Comment by mattcaswell** [comment]
Ping @snhenson

**Comment by levitte** [comment]
This needs a bit more thought.  If the error happens when some of the data has already been written, the written length will be returned rather than the error code (see the `return` statement at the end).  If this is fine, then this change is good enough.  If it isn't fine, I suggest this additional patch:

``` diff
diff --git a/crypto/asn1/bio_asn1.c b/crypto/asn1/bio_asn1.c
index 31fd7258a..362769cef 100644
--- a/crypto/asn1/bio_asn1.c
+++ b/crypto/asn1/bio_asn1.c
@@ -221,8 +221,10 @@ static int asn1_bio_write(BIO *b, const char *in, int inl)
             if (ctx->copylen == 0)
                 ctx->state = ASN1_STATE_HEADER;
 
-            if (inl == 0)
+            if (inl == 0) {
+                ret = wrlen;
                 goto done;
+            }
 
             break;
 
@@ -239,7 +241,7 @@ static int asn1_bio_write(BIO *b, const char *in, int inl)
     BIO_clear_retry_flags(b);
     BIO_copy_next_retry(b);
 
-    return (wrlen > 0) ? wrlen : ret;
+    return ret;
 
 }
 
```

**Comment by jon-oracle** [comment]
The behaviour of bio_write() methods seems to be to return the amount written in the case where at least some data gets written.

In crypto/evp/bio_enc.c:

```
        while (n > 0) {
            i = BIO_write(next, &(ctx->buf[ctx->buf_off]), n);
            if (i <= 0) {
                BIO_copy_next_retry(b);
                return (ret == inl) ? i : ret - inl;
            }
```

And similar in crypto/evp/bio_b64.c: 

```
        while (n > 0) {
            i = BIO_write(next, &(ctx->buf[ctx->buf_off]), n);
            if (i <= 0) {
                BIO_copy_next_retry(b);
                return ((ret == 0) ? i : ret);
            }
```

**Comment by levitte** [comment]
Ah, ok, never mind then. Thanks for the reminder.

**Comment by richsalz** [comment]
f125430 in master, 723f616 in 1.1.0;  thanks!

**Pull request closed without merging**
