### PR TITLE
Release the drbg in the global default context before engines [3.0]

### LINKED ISSUE #17995: OpenSSL 3.0 : segmentation fault with devcrypto engine
**$ openssl speed -engine devcrypto -multi 8 -elapsed -evp aes-128-cbc**
```
Forked child 0
Forked child 1
Forked child 2
Forked child 3
Forked child 4
Forked child 5
Forked child 6
Forked child 7
Engine "devcrypto" set.
Engine "devcrypto" set.
+DT:AES-128-CBC:3:16
+DT:AES-128-CBC:3:16
...
...
+R:1137:AES-128-CBC:3.000000
[73644.514174] audit: type=1701 audit(1648619903.847:57): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2114 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
Got: +H:16:64:256:1024:8192:16384[73644.529186] audit: type=1701 audit(1648619903.847:58): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2115 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
 from 1
Got: +F:25:AES-128-CBC:3[73644.545401] audit: type=1701 audit(1648619903.863:59): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2116 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
34464.00:1276714.67:4082432.00:56[73644.562267] audit: type=1701 audit(1648619903.863:60): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2118 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
35072.00:6217728.00:6236842.67 fr[73644.579175] audit: type=1701 audit(1648619903.879:61): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2121 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
om 1
+R:1150:AES-128-CBC:3.01000[73644.596193] audit: type=1701 audit(1648619903.883:62): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2119 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
0
+R:1146:AES-128-CBC:3.010000
[73644.613082] audit: type=1701 audit(1648619903.883:63): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2120 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
[73644.630015] audit: type=1701 audit(1648619903.915:64): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2117 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
+R:1147:AES-128-CBC:3.010000
Got: +H:16:64:256:1024:8192:16384 from 2
Got: +F:25:AES-128-CBC:334373.33:1204714.67:4040277.33:5734741.33:6283264.00:6220458.67 from 2
+R:1218:AES-128-CBC:3.010000
Got: +H:16:64:256:1024:8192:16384 from 3
Got: +F:25:AES-128-CBC:338985.95:1124992.00:3988480.00:5527552.00:5999274.67:6629804.65 from 3
Got: +H:16:64:256:1024:8192:16384 from 4
Got: +F:25:AES-128-CBC:334229.33:1451648.00:3937792.00:5718698.67:6250496.00:6204074.67 from 4
Got: +H:16:64:256:1024:8192:16384 from 5
Got: +F:25:AES-128-CBC:337514.67:1411904.00:3860224.00:5584554.67:6122154.67:6243338.21 from 5
Got: +H:16:64:256:1024:8192:16384 from 6
Got: +F:25:AES-128-CBC:338589.97:1354453.33:3834709.33:5509461.33:6144000.00:6259667.77 from 6
Got: +H:16:64:256:1024:8192:16384 from 7
Got: +F:25:AES-128-CBC:337216.00:1426645.33:3949186.58:5605717.33:6119424.00:6237895.02 from 7
version: 3.0.2
built on: Tue Mar 15 14:30:24 2022 UTC
options: bn(64,64)
compiler: aarch64-poky-linux-gcc  -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=recipe-sysroot -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=                      -fdebug-prefix-map=                      -fdebug-prefix-map=                      -fdebug-prefix-map=  -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_armcap=0xbf
evp               2355.37k     9251.07k    27693.10k    39315.80k    43136.34k    44032.08k
```

**$ dmesg**
```
audit: type=1701 audit(1648619903.847:57): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2114 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
audit: type=1701 audit(1648619903.847:58): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2115 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
audit: type=1701 audit(1648619903.863:59): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2116 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
audit: type=1701 audit(1648619903.863:60): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2118 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
audit: type=1701 audit(1648619903.879:61): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2121 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
audit: type=1701 audit(1648619903.883:62): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2119 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
audit: type=1701 audit(1648619903.883:63): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2120 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
audit: type=1701 audit(1648619903.915:64): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2117 comm="openssl" exe="/usr/bin/openssl" sig=11 res=1
```

### LINKED ISSUE #18578: SIGSEGV when registering an engine for default ciphers used by drbg (occurred inside sshd)
When registering an engine for default ciphers used by the DRBG implementation, a process receives a SIGSEGV when running cleanup hooks at exit.  This occurs, e.g., in the monitor child of sshd and leads to a connection termination.  Debugging it, I get this stack trace when the SIGSEGV hits:
```
(gdb) where
#0  0x000003fffd3ac9d8 in pthread_rwlock_wrlock@GLIBC_2.2 () from /lib64/libc.so.6
#1  0x000003fffdaafeb2 in CRYPTO_THREAD_write_lock (lock=<optimized out>) at crypto/threads_pthread.c:100
#2  0x000003fffda5aaf2 in ENGINE_finish (e=0x2aa00105690) at crypto/engine/eng_init.c:106
#3  0x000003fffda7ddd4 in EVP_CIPHER_CTX_reset (ctx=ctx@entry=0x2aa001c4ae0) at crypto/evp/evp_enc.c:61
#4  0x000003fffda7de1c in EVP_CIPHER_CTX_free (ctx=0x2aa001c4ae0) at crypto/evp/evp_enc.c:76
#5  EVP_CIPHER_CTX_free (ctx=0x2aa001c4ae0) at crypto/evp/evp_enc.c:72
#6  0x000003fffdb71acc in drbg_ctr_free (vdrbg=0x2aa00106b20) at providers/implementations/rands/drbg_ctr.c:617
#7  0x000003fffda83af0 in EVP_RAND_CTX_free (ctx=0x2aa001b4d80) at crypto/evp/evp_rand.c:385
#8  EVP_RAND_CTX_free (ctx=<optimized out>) at crypto/evp/evp_rand.c:373
#9  0x000003fffdadeec2 in rand_ossl_ctx_free (vdgbl=0x2aa001af760) at crypto/rand/rand_lib.c:482
#10 rand_ossl_ctx_free (vdgbl=0x2aa001af760) at crypto/rand/rand_lib.c:472
#11 0x000003fffdaa7e7c in CRYPTO_free_ex_data (class_index=class_index@entry=16, obj=<optimized out>, obj@entry=0x0, ad=ad@entry=0x3fffdcbf148 <default_context_int.lto_priv+8>) at crypto/ex_data.c:402
#12 0x000003fffdaa7ffa in context_deinit (ctx=0x3fffdcbf140 <default_context_int.lto_priv>) at crypto/context.c:167
#13 0x000003fffdaaad1e in context_deinit (ctx=<optimized out>) at crypto/context.c:155
#14 ossl_lib_ctx_default_deinit () at crypto/context.c:194
#15 OPENSSL_cleanup () at crypto/init.c:423
#16 OPENSSL_cleanup () at crypto/init.c:337
#17 0x000003fffd35b90c in __run_exit_handlers () from /lib64/libc.so.6
#18 0x000003fffd35b9d0 in exit () from /lib64/libc.so.6
#19 0x000002aa000116c6 in main (ac=<optimized out>, av=<optimized out>) at sshd.c:2362
```

Looking into the details I found that `global_engine_lock` is already NULL since it was already deleted in `engine_cleanup_int` which already finished (see `OPENSSL_cleanup`).  However, the RAND_GLOBAL structure for the default library context still has a reference to an EVP_CTX that is associated with the engine.

This was detected in OpenSSL version 3.0.1, but should still be present.

### PR DESCRIPTION
**Pull request by t8m**
This is the 3.0 version of the fix.
    
Fixes #17995
Fixes #18578

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
Fine with the DRBG change. Don't know enough about the engine change to comment.

**Comment by t8m** [comment]
ping for second approval

**Comment by t8m** [comment]
Instead of merging this also to 3.1 we should cherry-pick #19386 once the libctx refactoring is merged there.

**Comment by t8m** [comment]
Ping for second approval.

**Comment by t8m** [comment]
ping again for the second approval

**Review by bernd-edlinger — APPROVED** [review]

**Comment by t8m** [comment]
Merged to openssl-3.0 branch. Thank you for the reviews.

**Pull request closed without merging**
