### PR TITLE
Fix freshly introduced double-free.

### PR DESCRIPTION
**Pull request by vdukhovni**
We don't need the decoded X.509 Full(0) certificate for the EE usages 1 and 3, because the leaf certificate is always part of the presented chain, so the certificate is only validated as well-formed, and then discarded, but the TLSA record is of course still used after the validation step.

Added DANE test cases for: 3 0 0, 3 1 0, 1 0 0, and 1 1 0

Reported by Claus Assmann.

##### Checklist
- [x ] tests are added or updated

### CODE REVIEW

**Review by bernd-edlinger — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
Sorry, may I ask what is the difference to #22821 ?

**Comment by vdukhovni** [comment]
> Sorry, may I ask what is the difference to #22821 ?

The branch.  This is for `openssl-3.2`, while #22821 is for `master`.

**Review by hlandau — APPROVED** [review]

**Comment by davidben** [comment]
> The branch. This is for openssl-3.2, while https://github.com/openssl/openssl/pull/22821 is for master.

This made its way into the 3.2.0 release, right? Does the project expect to release a 3.2.1?

**Comment by vdukhovni** [comment]
> > The branch. This is for openssl-3.2, while #22821 is for master.
> 
> This made its way into the 3.2.0 release, right? Does the project expect to release a 3.2.1?

Yes, this is made it in 3.2.0, which then tripped regression tests for Claus. The affected audience is fairly narrow, since this only affects applications using OpenSSL for DANE that have already adopted 3.2.0, if they run into a DANE TLSA record of type "3 0 0" or "1 0 0" (full leaf certificate in the TLSA record).  The [DANE survey](https://stats.dnssec-tools.org) finds none of these at present.

But yes, a prompt fix seems prudent.

**Comment by vdukhovni** [comment]
> Just found this bug reported over on homebrew: [Homebrew/homebrew-core#155651](https://github.com/Homebrew/homebrew-core/issues/155651)

Bottom line: Postgres BIO API misuse that finally broke in practice. Not related to this issue.

**Comment by t8m** [comment]
Closing this as the duplicate PR is against master and the patch is identical.

**Pull request closed without merging**
