### PR TITLE
Fix osx travis

### PR DESCRIPTION
**Pull request by levitte**
These fixes are meant for master, 1.0.2 and 1.0.1

### CODE REVIEW

**Comment by levitte** [comment]
Ping @mattcaswell

**Comment by levitte** [comment]
Ok, I might need some help here...  MacOSX says this:

    +tar -n -s '/^/_srcdist\//' -cvf - @_srcdist.tar.list
    +gzip --best
    tar: Invalid replacement flag /

So it seems it doesn't do \ escaping...  In that case, how do I get in a / as part of the replacement???

**Comment by richsalz** [comment]
Does the tar command do -s @foo@bar@ ?

**Comment by levitte** [comment]
That's a good question.  The manual (https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/tar.1.html) specifies slashes as separators and doesn't say anything about the possibility of using other characters.  Otherwise, I would have gone got the same | that we have in `Makefile.org`...

**Comment by mattcaswell** [comment]
I just tried Rich's suggestion and it does seem to work. I think there is another problem though:

````
find: -xtype: unknown primary or operator
````

**Comment by levitte** [comment]
Thanks for the reminder, I changed it to use `-type` instead.  We'll have to make sure *never* to follow symlinks...

**Comment by levitte** [comment]
It seems this PR is finally doing it right.  @richsalz , @mattcaswell , check it out please?

**Comment by richsalz** [comment]
+1

**Comment by levitte** [comment]
Thanks.  Pushed.

**Pull request closed without merging**
