### PR TITLE
docs: fix typo in SSL functions

### PR DESCRIPTION
**Pull request by JamesWP**
fixing a typo in some documentation.

CLA: trivial

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by InfoHunter** [comment]
Just a note: you don't need to check the `tests are added or updated` box since there is no test cases update in this PR :-)

**Comment by InfoHunter** [comment]
It  also seems worth a backport to 1.1.1

**Comment by JamesWP** [comment]
> It also seems worth a backport to 1.1.1
Anything I need to do for this?

**Comment by InfoHunter** [comment]
> Anything I need to do for this?

Not necessarily. We can do that when this PR is being merged.

**Comment by t8m** [comment]
Merged to master (9f44e96e24) and 1.1.1 (004f570821)

**Comment by kaduk** [comment]
It looks like the travis error was just the usual timeout, so this one would be ready to merge.  @InfoHunter I guess that's you?

**Pull request closed without merging**
