### PR TITLE
Remove end of line whitespace to appease CI checks

### PR DESCRIPTION
**Pull request by paulidale**
- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
The release script did this. Should it be fixed?

**Review by t8m — APPROVED** [review]
IMO this is urgent.

**Comment by paulidale** [comment]
Agreed, urgent & merged.  Thanks for the review.
Yes, the release documentation should be updated too.

**Comment by levitte** [comment]
If it were me, I've exclude MD009 in util/markdownlint.rb.  Chasing down a (not so, in this case) spurious space is a waste of our time

**Comment by paulidale** [comment]
It's located other legitimate problems....

**Pull request closed without merging**
