### PR TITLE
Hjl/cet/open ssl 1 1 1 stable

### PR DESCRIPTION
**Pull request by xnox**
Please cherrypick CET fixes from master to 1.1.1-Stable branch.

When CET is not available, these instructions are no-ops.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
note that this breaks some valgrind versions:
```
$ valgrind apps/openssl version
==15154== Memcheck, a memory error detector
==15154== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==15154== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==15154== Command: apps/openssl version
==15154== 
vex amd64->IR: unhandled instruction bytes: 0xF3 0xF 0x1E 0xFA 0x49 0x89 0xD8 0x31
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=0F
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=1
==15154== valgrind: Unrecognised instruction at address 0x5eff50.
==15154==    at 0x5EFF50: OPENSSL_ia32_cpuid (x86_64cpuid.s:36)
==15154==    by 0x4FA749: OPENSSL_cpuid_setup (cryptlib.c:149)
==15154==    by 0x402DA1: ??? (in /home/ed/OPC/openssl/apps/openssl)
==15154==    by 0xF0B0FE: ???
==15154==    by 0x677CB2: __libc_csu_init (in /home/ed/OPC/openssl/apps/openssl)
==15154==    by 0x5076ED4: (below main) (libc-start.c:246)
==15154== Your program just tried to execute an instruction that Valgrind
==15154== did not recognise.  There are two possible reasons for this.
==15154== 1. Your program has a bug and erroneously jumped to a non-code
==15154==    location.  If you are running Memcheck and you just saw a
==15154==    warning about a bad jump, it's probably your program's fault.
==15154== 2. The instruction is legitimate but Valgrind doesn't handle it,
==15154==    i.e. it's Valgrind's fault.  If you think this is the case or
==15154==    you are not sure, please let us know and we'll try to fix it.
==15154== Either way, Valgrind will now raise a SIGILL signal which will
==15154== probably kill your program.
==15154== 
==15154== Process terminating with default action of signal 4 (SIGILL)
==15154==  Illegal opcode at address 0x5EFF50
==15154==    at 0x5EFF50: OPENSSL_ia32_cpuid (x86_64cpuid.s:36)
==15154==    by 0x4FA749: OPENSSL_cpuid_setup (cryptlib.c:149)
==15154==    by 0x402DA1: ??? (in /home/ed/OPC/openssl/apps/openssl)
==15154==    by 0xF0B0FE: ???
==15154==    by 0x677CB2: __libc_csu_init (in /home/ed/OPC/openssl/apps/openssl)
==15154==    by 0x5076ED4: (below main) (libc-start.c:246)
==15154== 
==15154== HEAP SUMMARY:
==15154==     in use at exit: 0 bytes in 0 blocks
==15154==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==15154== 
==15154== All heap blocks were freed -- no leaks are possible
==15154== 
==15154== For counts of detected and suppressed errors, rerun with: -v
==15154== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Illegal instruction (core dumped)
```

**Comment by xnox** [comment]
> note that this breaks some valgrind versions:
> 
> ```
> $ valgrind apps/openssl version
> ==15154== Memcheck, a memory error detector
> ==15154== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
> ==15154== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
> ```

Hm, that's not good. However 3.10 valgrind is quite old. Also what is tripping up on? endbranch? swapcontext?

My expectation was that when built with non-CET enabled toolchain, there is no impact on the binary =/

**Comment by bernd-edlinger** [comment]
I think that is caused by endbranch, sorry.
It would be good to detect if the compiler emits those instructions at all,
when it is invoked with the given the configured options,
and only emit the endbranch instructions if that is the case.

**Comment by xnox** [comment]
Hm I wonder if this code is not quite right then!


> I think that is caused by endbranch, sorry.
> It would be good to detect if the compiler emits those instructions at all,
> when it is invoked with the given the configured options,
> and only emit the endbranch instructions if that is the case.

I wonder if this code is not right then. Because just now, https://github.com/BLAKE3-team/BLAKE3/commit/a3ec6c1ccfe613cca886f6bff5feb0ec9c3710d9 got merged in a different project.

It checks if cet is enabled and if cet header is available, and then uses `_CET_ENDBR` everywhere instead of endbranch. When cet is enabled/available that macro does endbranch, otherwise it's defined to be empty and thus no code is generated.

I wonder if the same should be done in OpenSSL too. Such that one can generate non-cet enabled openssl without any calls to endbranch.

**Comment by xnox** [comment]
so openssl 1.1.1 will not gain CET support?

**Comment by t8m** [comment]
1.1.1 is bug fixes only. So no, this is not eligible for 1.1.1.

**Pull request closed without merging**
