### PR TITLE
doc: fix a mistyped "=item" perldoc marker

### PR DESCRIPTION
**Pull request by bbolli**
Searching didn't reveal any other similar cases.

CLA: trivial

- [x] documentation is added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
Agreed, trivial.

**Review by levitte — APPROVED** [review]

**Comment by paulidale** [comment]
Confirm trivial?

**Comment by levitte** [comment]
Yes, trivial

**Comment by paulidale** [comment]
Merged, thanks for the fix.

**Pull request closed without merging**
