### PR TITLE
Add quotes around perl scripts

### PR DESCRIPTION
**Pull request by keithc-ca**
Otherwise, it seems nmake doesn't invoke perl properly.

See also the discussion here: https://github.com/eclipse-openj9/openj9/pull/14900#issuecomment-1095904613.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Signed CLA sent via email.

**Review by DragonX1301 — APPROVED** [review]

**Review by DragonX1301 — APPROVED** [review]

**Comment by keithc-ca** [comment]
This being my first contribution to the project, I'm not sure what the normal response time should be for pull requests. Could someone please help me understand when I should expect this to be reviewed? Thanks.

**Comment by mattcaswell** [comment]
Response times vary massively depending on what the change is and who is available to review something at any one time.

In this case I'm hoping @levitte will take a look.

**Review by t8m — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
