### PR TITLE
Fix trivial issues in PR#3305

### PR DESCRIPTION
**Pull request by sidhpurwala-huzaifa**
This should fix trivial cppcheck issues discovered in PR#3305

### CODE REVIEW

**Comment by ghedo** [comment]
Except for the `STORE_get_public_key()` fix, the others seem to be fixed or the underlying code was removed.

**Comment by levitte** [comment]
The STORE needs a rework anyway, so fixes to it can largely be seen as irrelevant for now.

**Comment by ghedo** [comment]
What about just removing all of it (as suggested [here](https://mta.openssl.org/pipermail/openssl-dev/2015-October/002963.html))? It's old, no one uses it and it needs rework, sounds like a good candidate for removal in v1.1.

**Comment by levitte** [comment]
Hmm, can't say I'm entirely happy with that idea. I'm hoping I'd take the time to work on it before feature freeze.

**Comment by richsalz** [comment]
So the new dev model seems to be move it to a separate branch, @levitte :)

**Comment by levitte** [comment]
Really? Haven't noticed that...

**Comment by richsalz** [comment]
store will either be rewritten or fixed for 1.1, so closing this.

**Pull request closed without merging**
