### PR TITLE
`build.info`: make sure to generate crypto objects `obj_dat.h` etc. first

### LINKED ISSUE #19087: Build errors for buildtests in parallel builds due to missing dependency
When using parallel make with enabled buildtests, we sometimes see failures like

```
In file included from test/buildtest_obj_mac.c:10:
include/openssl/obj_mac.h:12: error: unterminated #ifndef
  12 | #ifndef OPENSSL_OBJ_MAC_H
```

This happens because `test/buildtest_obj_mac.c` does not have an explicit dependency on `include/openssl/obj_mac.h` which is regenerated in parallel due to the rules added in commit d040a1b9a028e89f0a33b36fb99f0151d2fdd4c3.  The rebuild path in the makefile is:

```
build_sw
->
_build_sw
->
build_libs_nodep
->
libcrypto.pc
->
libcrypto.so
->
libcrypto.so.3
->
libcrypto.ld
->
util/libcrypto.num
->
include/openssl/obj_mac.h (via CRYPTOHEADERS)
```

Since there is no dependency between this chain and the compilation of `build_test_obj_mac.c` into `test/buildtest_c_obj_mac-bin-buildtest_obj_mac.o`, they can run in parallel.  In rare cases, this leads to the situation where regeneration of obj_mac.h is still taking place while compilation reads that (partial) file causing above mentioned error.

I am not sure how to fix this issue.  Once solution would be to add an explicit dependency between the compilation step and the generated header.

Note that this problem does not occur always since parallel builds are non-deterministic.

### PR DESCRIPTION
**Pull request by DDvO**
This is supposed to fix #19087, as discussed there.

### CODE REVIEW

**Comment by levitte** [comment]
You need to do a bit more work.  The "DEPEND[]" array gets those header files built *in the build tree*, but the targets in `Configurations/unix-Makefile.tmpl` are still `${SRCDIR}/...`.  You will have to ensure that those four files are built in the built tree,

This is absolutely important when you build outside of the source directory tree.

**Comment by DDvO** [comment]
Ah, I can try at least removing `$(SRCDIR)/` from the Makefile...

**Comment by levitte** [comment]
Well, the resulting Makefile ends up in the build tree, if that tells you something.

You should try this:

``` console
$ git clone https://github.com/openssl/openssl openssl-master-src
$ mkdir openssl-master-build                                         # <--- this is alongside the source directory!
$ cd openssl-master-build
$ ../openssl-master-src/Configure
```

Voilà, you've set up a build directory outside of the source directory

**Comment by DDvO** [comment]
Thanks for the example.
I'm aware of the distinction between build dir and source dir, though I never made use of that .
Adapting the directory references was straightforward.
Yet I fear that various further tweaks may be needed...

**Comment by DDvO** [comment]
Yeah, now there is at least an issue with `fips-checksums`.
So I'll revert (the core of) commit 89c39bd8f.

**Pull request closed without merging**
