### PR TITLE
chore: typo fix & code style

### PR DESCRIPTION
**Pull request by willmafh**
##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Please run make update and commit the changed copyright line. See the check_update CI failure.

**Comment by willmafh** [comment]
> Please run make update and commit the changed copyright line. See the check_update CI failure.

already done

**Comment by t8m** [comment]
> > Please run make update and commit the changed copyright line. See the check_update CI failure.
> 
> already done

I am sorry but not done the check_update CI still fails. Also the merge commit you've added is wrong, please remove it. You need to run this: `git reset --hard HEAD~; make update; git commit -a --fixup HEAD; git push --force'

**Comment by willmafh** [comment]
> > > Please run make update and commit the changed copyright line. See the check_update CI failure.
> > 
> > 
> > already done
> 
> I am sorry but not done the check_update CI still fails. Also the merge commit you've added is wrong, please remove it. You need to run this: `git reset --hard HEAD~; make update; git commit -a --fixup HEAD; git push --force`

Sorry, I misunderstood what you means! I've already `make update` to update the license line, please review it again!

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
ping for second review

**Comment by tom-cosgrove-arm** [comment]
Okay with trivial (and let's squash commits on merge)

**Comment by t8m** [comment]
Squashed and merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
