### PR TITLE
test/evp_test.c: [ciphers] Test that we get back the same IV we gave

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
When the PR to make it pass is done :)

**Review by paulidale — APPROVED** [review]
Even better :)

Assuming the CI tests pass.

**Comment by petrovr** [comment]
Ok. but this test requires other changes - management of IV, otherwise tests will fail.

**Comment by levitte** [comment]
Yes, see #9328 for the fixups

**Comment by levitte** [comment]
This got merged along with #9328.  Closing

**Pull request closed without merging**
