### PR TITLE
Rename err_load_xxx_strings_int

### PR DESCRIPTION
**Pull request by richsalz**
Use the already-existing prefix ERR_load_xxx_strings_int.

Also fix a confusing comment in the Unix makefile, that specified the
wrong flag to force a rebuild.

This is a partial fix for #15344

### CODE REVIEW

**Comment by levitte** [comment]
> Use the already-existing prefix ERR_load_xxx_strings_int.

Uhm, haven't you noticed the pattern, *public* symbols get uppercase prefix, while *private* symbols get lowercase prefix?

**Comment by richsalz** [comment]
Yes, I noticed the pattern.  Thanks for the reminder.

If you have a better way to keep those symbols inside the library, when they're not static, please close this.

**Comment by levitte** [comment]
Uhmmmmm, making them uppercase doesn't change anything other than making them uppercase, does it?
So yeah, our private non-static symbols are exposed in the static library, there's not very much we can do about that.

**Comment by levitte** [comment]
I just discovered that we have *one* err-related internal symbol exposed in the shared libcrypto: `err_free_strings_int`
I haven't looked at it (for long enough that I've forgotten, at the very least).  Someone else might be able to fill us in on that one.

**Comment by richsalz** [comment]
Making them uppercase moves them into the public namespace.  And yes, that's all it does.  And yes, it goes against the convention of using lower-case prefix, and/or and `_int` suffix for internal and private symbols. If you have another way to have symbols not exposed, great. Perhaps @paulidale's original issue, #15344, is doing something wrong. I think you should (re-)read it and comment there.

If he's doing something wrong, then close this; I'll open a new PR for just the Makefile comment fix.

If he's right, and there's a better way to fix the issue then renaming things -- which is what was done in addressing #12694 -- then close this and I look forward to learning the better way.

**Comment by t8m** [comment]
The right fix is to add the `ossl_` prefix.

21. 5. 2021 19:47, 19:47, Rich Salz ***@***.***> napsal/a:

**Comment by richsalz** [comment]
Replaced the prefix with `ossl_`

**Comment by t8m** [comment]
I'm sorry if I didn't make it clear. I didn't mean replacing err_ prefix with ossl_ but rather adding it. And to keep the name length reasonable you can drop the _int suffix as it is unnecessary.

21. 5. 2021 21:55, 21:55, Rich Salz ***@***.***> napsal/a:

**Comment by richsalz** [comment]
I think `ossl_load_XXX_strings_int` is fine and am not going to change it again.

**Comment by t8m** [comment]
> I think `ossl_load_XXX_strings_int` is fine and am not going to change it again.

Then I am sorry, but I am not going to approve it. But I won't block it either.

**Comment by paulidale** [comment]
Closing in favour of #15446

**Pull request closed without merging**
