### PR TITLE
Replace ;; with ; removing empty statements

### LINKED ISSUE #17525: Empty statement in x509_trust.c
[x509_trust.c](https://github.com/openssl/openssl/blob/57645339ab645fe5abffe14fc005b5402ce03b84/crypto/x509/x509_trust.c#L169) says:
~~~c
goto err;;
~~~

While the extra semicolon is harmless, it nevertheless smells. I only noticed it because I made the same mistake in my own code. I then searched the whole NetBSD/src tree for other instances and found some of them in the OpenSSL source.

### PR DESCRIPTION
**Pull request by paulidale**
A few instances had crept into the code

Not sure if this qualifies as a bug and therefore merging to 3.0 and 1.1.1.

Fixes #17525

### CODE REVIEW

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
For master only. I don't see this as a "bug" fix. The code works.

**Comment by bernd-edlinger** [comment]
Maybe you want to fix this as well?

https://github.com/openssl/openssl/blob/144316d276adf5b8172316f7bc20b372b8e31ac8/engines/e_dasync.c#L211-L212

**Comment by paulidale** [comment]
Fixed that and more.
Review required again.

**Review by bernd-edlinger — APPROVED** [review]
Nice

**Review by mattcaswell — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the reviews.

**Pull request closed without merging**
