### PR TITLE
Dtls1.3 pr

### PR DESCRIPTION
**Pull request by fwh-dc**
This is a temporary "pre-feature" branch for dtls 1.3 development

List of PR's that are part of this branch:
https://github.com/openssl/openssl/pull/22259
https://github.com/openssl/openssl/pull/22260
https://github.com/openssl/openssl/pull/22261
https://github.com/openssl/openssl/pull/22273
https://github.com/openssl/openssl/pull/22275
https://github.com/openssl/openssl/pull/22360
https://github.com/openssl/openssl/pull/22362
https://github.com/openssl/openssl/pull/22363
https://github.com/openssl/openssl/pull/22364
https://github.com/openssl/openssl/pull/22366
https://github.com/openssl/openssl/pull/22376
https://github.com/openssl/openssl/pull/22378
https://github.com/openssl/openssl/pull/22379
https://github.com/openssl/openssl/pull/22380
https://github.com/openssl/openssl/pull/22400
https://github.com/openssl/openssl/pull/22401
https://github.com/openssl/openssl/pull/22402
https://github.com/openssl/openssl/pull/22416
https://github.com/openssl/openssl/pull/22935
https://github.com/openssl/openssl/pull/22936
https://github.com/openssl/openssl/pull/22937
https://github.com/openssl/openssl/pull/22985
https://github.com/openssl/openssl/pull/23041

### CODE REVIEW

**Comment by kroeckx** [comment]
I would like to see at least 2 fuzzers for this (client and server). The current quic_client fuzzer is probably the best example of what it should look like. Is this something you can add?

**Comment by mattcaswell** [comment]
> The current quic_client fuzzer is probably the best example of what it should look like.

Currently our QUIC implementation supports "fake" time which is something our DTLS implementation lacks. We use the fake time capability in the quic_client fuzzer to ensure we get good reproducible results. It would be good to have the same thing in DTLS although it goes a little beyond the scope of DTLSv1.3 specifically.

**Comment by mattcaswell** [comment]
There are CI failures in this branch which might suggest some fixes in some of the constituent PRs.

**Comment by mattcaswell** [comment]
> I keep a list of TODO's for this feature and I'd like to add the fuzzers to it. But I agree with Matt that the DTLS "fake" time support is out of scope for this feature. I don't know if you can create a separate issue for that and fix it on master?

I created an issue for this in #22863.

Note that it is not strictly a requirement to have fake time support in order to do fuzzing in DTLS. It just improves the quality and reproducibility of the output

**Comment by fwh-dc** [comment]
> Note that it is not strictly a requirement to have fake time support in order to do fuzzing in DTLS. It just improves the quality and reproducibility of the output

Noted, I will add a work item to the backlog.

> Regarding the pipeline failures: When we have the feature branch setup and is able to push to that it will be easier to make sure that a change does not introduce regressions.

@mattcaswell Do you have any updates on the feature branch setup?

**Comment by t8m** [comment]
As the feature branch has been created, could you please retarget the individual PRs against the feature/dtls-1.3 branch?

**Comment by fwh-dc** [comment]
> As the feature branch has been created, could you please retarget the individual PRs against the feature/dtls-1.3 branch?

Exciting news! Yes I'll do that. I don't think you need to spend time closing the PR's. I think I can change the branch without creating a new PR. I'm currently abroad, but I'll do it when I get back in to office on thursday the latest.

**Comment by t8m** [comment]
Please also close & reopen the PRs when you retarget them, to get the CI re-run.

**Comment by fwh-dc** [comment]
Sure I will!

**Comment by fwh-dc** [comment]
Closing this since we have the feature branch setup.

**Pull request closed without merging**
