### PR TITLE
ci: add a no-legacy build

### LINKED ISSUE #12091: what's the plan for skipping test cases that use legacy algorithms, with no-legacy?
As of 3.0.0 alpha3, if I configure with `no-legacy` several of the tests do not run successfully:

```
Test Summary Report
-------------------
20-test_enc.t                    (Wstat: 45568 Tests: 180 Failed: 178)
  Failed tests:  3-180
  Non-zero exit status: 178
20-test_enc_more.t               (Wstat: 35584 Tests: 141 Failed: 139)
  Failed tests:  3-141
  Non-zero exit status: 139
30-test_evp.t                    (Wstat: 2304 Tests: 28 Failed: 9)
  Failed tests:  17, 19-20, 22-25, 27-28
  Non-zero exit status: 9
80-test_cms.t                    (Wstat: 256 Tests: 10 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=197, Tests=1996, 206 wallclock secs ( 2.69 usr  0.56 sys + 200.66 cusr 15.32 csys = 219.23 CPU)
Result: FAIL
```

Is now the right time to be going through and skipping specific test cases as they are unuseful, or do we expect there to be further changes in flight that would affect such work?

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #12091

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by slontis — APPROVED** [review]
Looks Ok to me.

**Comment by t8m** [comment]
I am slightly worried about adding further builds to the CI. Could we perhaps use one of the other builds to test for no-legacy? For example the basic-clang or enable_non-default_options might be used.

**Comment by paulidale** [comment]
The no-legacy build could be rolled into one of the others, it could also get extra options to test further things.
What's the concern about adding another build?  I looked around at github's actions limits and I don't think we're close to any.

**Comment by slontis** [comment]
We can also run nightly or weekly or manual workflows if we want this to be coarser..

**Comment by t8m** [comment]
> The no-legacy build could be rolled into one of the others, it could also get extra options to test further things.
> What's the concern about adding another build? I looked around at github's actions limits and I don't think we're close to any.

OK then.

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master, thanks for the feedback.

**Pull request closed without merging**
