### PR TITLE
add no-docs Configure option

### PR DESCRIPTION
**Pull request by vladak**
This change introduces the `no-docs` Configure option. This is handy for minimization.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Can't this mostly be done simply by not installing the docs? i.e. "make install_sw" instead of "make install"

**Comment by vladak** [comment]
> Can't this mostly be done simply by not installing the docs? i.e. "make install_sw" instead of "make install"

Personally I prefer this is done in the configure phase, because in our environment OpenSSL is built multiple times with different options and this allows to concentrate all the changes to the configure phase and not override the install phase.

**Comment by t8m** [comment]
Please add runchecker-daily CI run for this option.

**Comment by vladak** [comment]
> Please add runchecker-daily CI run for this option.

Added.

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the contribution.

**Pull request closed without merging**
