### PR TITLE
Fix BIO_f_cipher flushing and other BIO related fixes (1.1.1)

### PR DESCRIPTION
**Pull request by mattcaswell**
If an error occurs during a flush on a BIO_f_cipher() then in some cases
we could get into an infinite loop. We add a check to make sure we are
making progress during flush and exit if not.

This issue was reported by Octavio Galland who also demonstrated an
infinite loop in CMS encryption as a result of this bug.

The security team has assessed this issue as not a CVE. This occurs on
encryption only which is typically processing trusted data. We are not
aware of a way to trigger this with untrusted data.

Backport of https://github.com/openssl/openssl/pull/19918 for 1.1.1.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Lots of CI failures which don't seem related to this PR!!?

**Comment by bernd-edlinger** [comment]
I have a couple CI-fixes in my 111 feature branch, but I figured it would not be acceptable for 1.1.1
so I did not try to create a PR for that.

**Comment by bernd-edlinger** [comment]
wrong butonj. sorry!

**Comment by t8m** [comment]
I assume backporting the test from 3.0 PR would be too big change as the test_cms recipe has quite evolved since 1.1.1

**Review by t8m — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
Merged to 1.1.1 branch.

**Comment by bernd-edlinger** [comment]
Hmm, I think it seems pointless to back-port commit 1354191,
"Fix SMIME_crlf_copy() to properly report an error" changing the return value
of SMIME_crlf_copy because this return value is never used in 1.1.1
I see it is only propagated in 3.0/3.1/master.
Is this something that also needs to be fixed?

**Pull request closed without merging**
