### PR TITLE
Small STORE registry fixes

### PR DESCRIPTION
**Pull request by levitte**
See commit messages for details

### CODE REVIEW

**Review by kaduk — COMMENTED** [review]
Looks good, but do you need to make update to get the OSSL_STORE_R_LOADER_INCOMPLETE symbol picked up?

**Comment by levitte** [comment]
> Looks good, but do you need to make update to get the OSSL_STORE_R_LOADER_INCOMPLETE symbol picked up?

Thanks for the reminder.  Done!

**Review by kaduk — APPROVED** [review]
Thanks!

**Comment by levitte** [comment]
Merged.  6f9c5062682c0f30d62af54b15ad6904e4dd8cb6 and 5ee407460b3b68aa4695f17cf8c43e0d07cb18a8

**Comment by levitte** [comment]
Thanks!

**Pull request closed without merging**
