### PR TITLE
Fix export of ec parameters

### LINKED ISSUE #17978: ecparam -check in fips mode
Current master

The command
```./util/wrap.pl -fips `pwd`/apps/openssl ecparam -out 384.pem -name secp384r1 -param_enc explicit```
works normally.

The command
```./util/wrap.pl -fips `pwd`/apps/openssl ecparam -check -in 384.pem```
gives the following output:
```
Could not read params etc. of EC parameters from 384.pem
4027A373D87F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
4027A373D87F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
4027A373D87F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
4027A373D87F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:crypto/store/store_result.c:151:
4027A373D87F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
4027A373D87F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
```
Is it desired (and documented) behaviour?

### PR DESCRIPTION
**Pull request by t8m**
Fixes #17978

##### Checklist

- [ ] tests are added or updated

### CODE REVIEW

**Comment by simo5** [comment]
I had this patch in my tree for testing:
```
$ git diff
diff --git a/crypto/ec/ec_asn1.c b/crypto/ec/ec_asn1.c
index 6323131a22..66e805f7f8 100644
--- a/crypto/ec/ec_asn1.c
+++ b/crypto/ec/ec_asn1.c
@@ -1114,6 +1114,12 @@ EC_KEY *d2i_ECParameters(EC_KEY **a, const unsigned char **in, long len)
         return NULL;
     }
 
+    if (ret->group->decoded_from_explicit_params) {
+        ERR_raise(ERR_LIB_EC, ERR_R_DISABLED);
+        EC_KEY_free(ret);
+        return NULL;
+    }
+
     if (EC_GROUP_get_curve_name(ret->group) == NID_sm2)
         EC_KEY_set_flags(ret, EC_FLAG_SM2_RANGE);
```

but clearly completely disabling EC_GROUP_new_from_params() in FIPS mode may be cleaner.

That said this makes the import succeed if the params actually correspond to an approved named curve params ... are you going to add a test with an unapproved key params that will show this actually failing ?

**Comment by simo5** [comment]
I am not sure this is supposed to work?
$ ./util/wrap.pl -fips `pwd`/apps/openssl ecparam -out explicit.pem -name sect283k1 -param_enc explicit
$ ./util/wrap.pl -fips `pwd`/apps/openssl ecparam -check -in explicit.pem
checking elliptic curve parameters: ok
-----BEGIN EC PARAMETERS-----
MIHsAgEBMCUGByqGSM49AQIwGgICARsGCSqGSM49AQIDAzAJAgEFAgEHAgEMMEwE
JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQkAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBEkEBQMhP3jKRIg/GjuBYvGI5VPN
Jl8jwVZ6FodpE7DCrCRYSSg2AczaOA8cnjGNkPldB+VCb+h+RcDoGEaY5FliNk40
EWF33SJZAiQB///////////////////////pri7QdXcmXf9/lEUeBh4WPGECAQQ=
-----END EC PARAMETERS-----


Tested after applying this PR patches.

**Comment by t8m** [comment]
sect283k1 is allowed by NIST.

**Comment by t8m** [comment]
The FIPS provider does not know that the base provider converted the explicit parameters into named ones.

**Comment by t8m** [comment]
> I had this patch in my tree for testing:
>

That patch completely drops support for explicit parameters, not just in the fips module. Doesn't it?

**Comment by simo5** [comment]
Yeah I just wanted to test that it would work and didn't want to be fooled by the export/import dance, it was planning to put #ifdef FIPS_MODULE around it but you opened this Pr in the meanwhile.
With the FIPS_MODULE wrapping around the default module handled the actual asn1 decoding and the export/import dance happened.

**Comment by simo5** [comment]
ok I retested via:
$ ./util/wrap.pl -fips `pwd`/apps/openssl ecparam -out explicit.pem -name brainpoolP160r1 -param_enc explicit
and the import "correctly" failed:
$ ./util/wrap.pl -fips `pwd`/apps/openssl ecparam -check -in explicit.pem
Could not read params etc. of EC parameters from explicit.pem
C0D28DF9147F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
C0D28DF9147F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
C0D28DF9147F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
C0D28DF9147F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:crypto/store/store_result.c:151:
C0D28DF9147F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:
C0D28DF9147F0000:error:07800081:common libcrypto routines:get_ptr_internal:param of incompatible type:crypto/params.c:1416:

**Comment by t8m** [comment]
BTW, the current failures actually indicate the correct behavior - the testcases which should be failing are failing. I just need to adjust the test to actually expect the expected failures with the fips module.

**Comment by simo5** [comment]
@t8m it sure be nice if we could get a real error from the FIPS module in this case instead of this wall of useless and misleading errors.
Any chance we can return an error that says something about explicit parameters being disallowed ?
Or no matching named curve, by raising an error inside the FIPS_MODULE guard in EC_GROUP_new_from_params() ??

**Comment by t8m** [comment]
I've modified the scope of this PR to just fix the export of the EC parameters so it is applicable to both master and 3.0 branches.

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
This patch removes the error preventing loading the custom parameters in FIPS mode. I believe they are rejected by EC_check if they don't match known curve - at least it is documented this way...

**Comment by beldmit** [comment]
#17998 removes a possibility to load custom parameters in FIPS mode.

**Comment by t8m** [comment]
I can add those tests to #17998 if this one is merged first.

Tests of some arbitrary explicit curve with `-check` would fail even without  #17998.

**Comment by t8m** [comment]
ping for second review

**Comment by simo5** [comment]
FWIW LGTM

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for the reviews.

**Pull request closed without merging**
