### PR TITLE
Use the same encryption growth macro consistently

### PR DESCRIPTION
**Pull request by mattcaswell**
We had two different macros for calculating the potential growth due to encryption. The macro we use for allocating the underlying buffer should be the same one that we use for reserving bytes for encryption growth.

Also if we are adding the MAC independently of the cipher algorithm then the encryption growth will not include that MAC so we should remove it from the amount of bytes that we reserve for that growth. Otherwise we might exceed our buffer size and the WPACKET_reserve operation will fail.

This is urgent because it was included as part of #19516 which I over-enthusiastically merged when unfortunately there was a CI failure (unfortunately ready-to-merge was automatically applied anyway). There will need to be a backport because #19517 was previously merged to 3.0/3.1.

### CODE REVIEW

**Comment by t8m** [comment]
OK with urgent

**Comment by mattcaswell** [comment]
3.1/3.0 backport in #19624

**Comment by mattcaswell** [comment]
Ping @openssl/committers. This is causing CI failures in PRs...

**Review by hlandau — APPROVED** [review]
Agree urgent

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
