### PR TITLE
APPS: make apps strict on app_RAND_load() and app_RAND_write() failure

### PR DESCRIPTION
**Pull request by DDvO**
SSIA

### CODE REVIEW

**Comment by richsalz** [comment]
Why not just make the functions like `app_malloc`: print error and exit on failure.

**Comment by DDvO** [comment]
> Why not just make the functions like app_malloc: print error and exit on failure.

Good point - I was also considering that option. 
What do others think?

**Review by paulidale — APPROVED** [review]
I don't have any objection to making this follow the app_malloc path.  A slight preference for it, although we're heading away from random files, so I wonder if it's worth the effort.

**Comment by DDvO** [comment]
Pushed - thanks

**Pull request closed without merging**
