### PR TITLE
Check the return value from ASN1_INTEGER_set

### PR DESCRIPTION
**Pull request by mattcaswell**
Found by Coverity

### CODE REVIEW

**Comment by mattcaswell** [comment]
It's not clear to me why Coverity only started displaying this now...its been like this for a long time.

**Comment by levitte** [comment]
Maybe Coverity got a nit-pick upgrade ;-)

**Comment by mattcaswell** [comment]
Well what's even stranger is that the "First detected" field lists this as having been found on 12th December 2014. But the "Triage history" only lists yesterday's date. I wonder if the reconfigure of the project settings (to list the test issues) for some reason kicked this out of limbo somewhere.

**Comment by levitte** [comment]
Possibly...  could it be that someone marked it as a false positive a long time ago, and it got reset somehow now?

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
