### PR TITLE
appveyor.yml: engage VC-WIN64A-masm.

### PR DESCRIPTION
**Pull request by dot-asm**
See if it works...

### CODE REVIEW

**Comment by dot-asm** [comment]
It does. First red cross is addressed by second commit and second red cross is unrelated. One of the reasons for why masm/ml64 is not supported is that it's problematic to support *multiple* versions. But latest one usually works and/or it's lesser problem to make it work. So idea here is to have a "whistle" when it breaks, so that problems can be evaluated as they emerge. It's kind of "best effort" thing, as opposite to "full support" thing. In the context one can argue that 50-masm.conf should be renamed to 20-masm.conf.

**Comment by levitte** [comment]
Regarding numbering, we haven't really said much, have we?

**Comment by dot-asm** [comment]
> Regarding numbering, we haven't really said much, have we?

Well, at the very least it's kind of implied that larger number means lesser support, since 90-team.conf is obviously unsupported. And 90-thing being unsupported *was* in fact discussed. And 50-thing denoting community-supported was to. Maybe not in public though... In any case intention for 20-thing is to denote kind of between community and fully supported, or as already suggested "best effort"...

**Comment by levitte** [comment]
That's what I meant, it's not documented anywhere...  and you know as well as me how crappy a knowledge database email is ;-)

**Pull request closed without merging**
