### PR TITLE
[WIP]Adjust threadstest to support Nonstop

### PR DESCRIPTION
**Pull request by nhorman**
The nonstop cooperative threading model requires some adjustments to the new threadstest tests:

1) The use of OSSL_sleep in the rwtorture and rcutorture tests
   encounters an error when specifying times of 1000ms or larger, limit
   that on nonstop to 999ms instead

2) The use of rwlocks in the tests is bad.  Because Nonstop appears to
   not consider pthread_rwlock_rdlock to be a yield point, deadlocks can
   occur when a reader thread acquires the cpu, as it will never yield.
   For Nonstop use write locks in the tests exclusively to create thread
   rescheduling events

3) For RCU, the read side by design never has to block, creating a
   simmilar problem to (2).  Insert an explicit yeild for Nonstop
   to force thread scheduling

##### Checklist
- [x] tests are added or updated

### CODE REVIEW

**Comment by rsbeckerca** [comment]
Can you remove the change involving reducing the time size when this is finalized? #23926 fixes this.

**Comment by nhorman** [comment]
Removed

**Comment by rsbeckerca** [comment]
I'm a little (very) confused. I tried merging your changes with `3.3.0-alpha1` and have all kinds of undefined externals. I might have to reset the repository and try again.

More usefully, on the other hand, with #23926 and `master` (at 9abcf11696 actually passes). #23926 also seems to fix #23927 and #23928. I'm now wondering whether the `usleep(1000000)` with that invalid value has somehow messed up the thread library - considering how long I have worked in PUT, this surprises the tar out of me. Although, calling `sleep()` followed by `usleep()` forces invoking the scheduler twice, which can have significant side-effects. @nhorman What do you think?

**Comment by nhorman** [comment]
I'm on my phone so this is just a guess, but could the addition of write.lock in the read side make the usleep error moot (i.e we still need to fix it, but the regular schedule exchanges make the failed sleep irrelevant

**Comment by rsbeckerca** [comment]
> I'm on my phone so this is just a guess, but could the addition of write.lock in the read side make the usleep error moot (i.e we still need to fix it, but the regular schedule exchanges make the failed sleep irrelevant

I'm not sure. With the OSSL_sleep fix I put in, the code seems to be much happier (all tests pass in master), even without your fix. #23926 should be applied to all 3.x series releases at the earliest opportunity. I am suspecting that usleep(1000000) somehow caused problem in the NonStop PUT library - it is documented as "don't do this" but no reason given.

**Comment by rsbeckerca** [comment]
@nhorman FYI: Your fix did work also, including the other two failed tests. At this point, it is a toss-up as to whether to include this or use `master` as is with the OSSL_sleep fix.

**Comment by nhorman** [comment]
I'm in favor of minimal changes, so if you're OSSL_sleep fix fixes the issues you're encountering, I'll just close this.  Please confirm and I will do so.

**Pull request closed without merging**
