### PR TITLE
Fix typo in openssl-verification-options documentation

### PR DESCRIPTION
**Pull request by hablutzel1**
"or" word is missing.

- [ x ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

**Review by tom-cosgrove-arm — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
Ok with trivial

**Review by kroeckx — APPROVED** [review]

**Review by shahsb — APPROVED** [review]
Okay with trivial.

**Comment by t8m** [comment]
Merged to all the active branches. Thank you for your contribution.

**Pull request closed without merging**
