### PR TITLE
QUIC qlog: Fix Windows and add Windows to CI

### PR DESCRIPTION
**Pull request by hlandau**
- QUIC qlog: Enable qlog in Windows CI
- JSON_ENC: Fix unit test for MSVC

Previously scripts were defined like this:

    {
        static const char *const script_name = "xxx";

        static const struct script_info script_info = {
            script_name, ...
        };

        return &script_info;
    }

MSVC cannot handle this, presumably because this technically involves a
load from a variable to determine that script_name equals "xxx" and it
is unable to do this during evaluation of a constant initializer list.
Resolve this by changing script_name and script_title to be arrays
instead, allowing the correct pointer values to be filled into
script_info as symbol addresses/relocations rather than dereferences.

We weren't testing qlog in Windows CI which we should have been.

Repo mirroring seems slow again.

Fixes https://github.com/openssl/openssl/issues/23516

### CODE REVIEW

**Review by t8m — APPROVED** [review]
Approved if CI passes

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by nhorman — APPROVED** [review]

**Comment by nhorman** [comment]
Is the CI relevant?  It seems like the fuzzer is failing for lack of disk space

**Comment by tom-cosgrove-arm** [comment]
The fuzzer has been failing for a while with insufficient disk space

**Comment by tom-cosgrove-arm** [comment]
I am happy with the CI result

**Comment by hlandau** [comment]
Merged to master. Thanks for the reviews.

**Pull request closed without merging**
