### PR TITLE
Circleci project setup

### PR DESCRIPTION
**Pull request by pamobazan12**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
What is the intention of this PR? I do not think we want to add another CI system.

**Review by paulidale — COMMENTED** [review]
Why?

We're currently using GitHub's actions which gives us plenty.

It also looks like there are some unrelated commits included.

**Comment by paulidale** [comment]
`cowsay`, sorry you're spamming us.

**Review by pamobazan12 — COMMENTED** [review]
Aprobado

**Pull request closed without merging**
