### PR TITLE
Fix static builds

### PR DESCRIPTION
**Pull request by ekasper**

### CODE REVIEW

**Comment by mattcaswell** [comment]
Yay. Works for me:
````
All tests successful.
Files=71, Tests=367, 50 wallclock secs ( 0.66 usr  0.11 sys + 42.39 cusr  1.30 csys = 44.46 CPU)
Result: PASS
````

**Comment by mattcaswell** [comment]
+1

**Comment by levitte** [comment]
I'll merge it as soon as Travis and Appveyor show green

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
