### PR TITLE
EVP_PKEY-X25519.pod: Correct EVP_PKEY_Q_keygen function name in example

### PR DESCRIPTION
**Pull request by DDvO**
doc nit fixup for #14695

- [x] documentation is added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by DDvO** [comment]
The smaller the PRs, the more approvals they get :D

**Comment by t8m** [comment]
> The smaller the PRs, the more approvals they get :D

As if that was surprising :grin:

**Comment by paulidale** [comment]
The more trivial nits they attract as well.

**Comment by paulidale** [comment]
Merged to master.

**Pull request closed without merging**
