### PR TITLE
Fix a doc-nit in EVP_PKEY_CTX_ctrl.pod

### PR DESCRIPTION
**Pull request by InfoHunter**
To make `make doc-nits` happy...

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by InfoHunter** [comment]
Errr, I should add `[skip-ci]`...

**Comment by InfoHunter** [comment]
Pushed to master as e5a8712d03

**Comment by mspncp** [comment]
This commit can be cherry-picked cleanly to 1.1.1. Shouldn't it be done before 1.1.1a?

**Comment by InfoHunter** [comment]
Sure, will do that!

**Comment by InfoHunter** [comment]
Cherry-picked to 1.1.1 as 0178459, thanks guys!

**Pull request closed without merging**
