### PR TITLE
Add Content Type OID for id-ct-rpkiSignedPrefixList

### PR DESCRIPTION
**Pull request by job**
References: draft-ietf-sidrops-rpki-prefixlist
Title: "A profile for Signed Prefix Lists for Use in the Resource Public Key Infrastructure (RPKI)"

OID assigned under 'SMI Security for S/MIME CMS Content Type (1.2.840.113549.1.9.16.1)' https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#security-smime-1

### CODE REVIEW

**Comment by job** [comment]
This failure seems unrelated to my diff, other than that I'm the first to change that file this year? https://github.com/openssl/openssl/actions/runs/7702204582/job/20989970996?pr=23426

**Comment by job** [comment]
https://github.com/openssl/openssl/actions/runs/7702396658/job/20990621963?pr=23426 failing seems unrelated to this pull request

**Review by t8m — APPROVED** [review]

**Comment by job** [comment]
ping?

**Comment by job** [comment]
Can this one please be merged? It is a trivial change

**Comment by t8m** [comment]
ping for a second review

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
