### PR TITLE
`OSSL_CRMF_CERTTEMPLATE_get0_publicKey()`: fix return type and doc

### PR DESCRIPTION
**Pull request by DDvO**
This is a fixup of #18930.

Preparing CMP support for central key generation,
I found that the return type of `OSSL_CRMF_CERTTEMPLATE_get0_publicKey()`
was not flexible enough - it should not be `const`,
and it does not need to be according to the structure decl in `crmf_local.h`:
```
struct ossl_crmf_certtemplate_st {
    [...]
    const X509_NAME *issuer;
    OSSL_CRMF_OPTIONALVALIDITY *validity;
    const X509_NAME *subject;
    X509_PUBKEY *publicKey;
    [...]
} /* OSSL_CRMF_CERTTEMPLATE */;
```

Luckily, this can still be fixed without an API break because the new function has not been released yet.

On this occasion, also added the missing related HISTORY entry in `OSSL_CRMF_MSG_get0_tmpl.pod`.

### CODE REVIEW

**Comment by t8m** [comment]
What about the other get0 functions - In general they should NOT constify members that are not const already in the structure. Could you please fix them too?

**Comment by t8m** [comment]
Ah, I did not realize the OSSL_CRMF_CERTTEMPLATE_get0_serialNumber() was there in 3.0 already. In that case I am afraid we should not change it - even if the API break is just very minor - applicable only when using the function as function pointer.

**Comment by DDvO** [comment]
> Ah, I did not realize the OSSL_CRMF_CERTTEMPLATE_get0_serialNumber() was there in 3.0 already. In that case I am afraid we should not change it - even if the API break is just very minor - applicable only when using the function as function pointer.

Thinking a again about the API break topic, situations where
* a function parameter type is added a `const` qualifier
* a `const` qualifier is removed from a function result type

AFICS do not constitute an API break:
In the first case, it just adds a promise that the function won't modify the argument
In the seconde case, it just gives the caller more freedom, namely to modify the result.

So two more items for the list in https://github.com/openssl/technical-policies/issues/65.

**Comment by t8m** [comment]
> AFAICS do not constitute an API break: In the first case, it just adds a promise that the function won't modify the argument In the seconde case, it just gives the caller more freedom, namely to modify the result.

They do not constitute ABI break but unfortunately they do (in case this is removing const from the dereference of pointer) constitute API break. You can try having a function pointer that differs from the function signature just in constness of return value or argument and you'll see that this will give warnings during compilation. And that is unfortunately not acceptable.

**Comment by t8m** [comment]
Removing/adding const is safe only on non-pointers as there the const does not really have any effect.

**Comment by DDvO** [comment]
Bummer. 
So reverted the change to the return type of `OSSL_CRMF_CERTTEMPLATE_get0_serialNumber()`.

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Closing as this was merged.

**Pull request closed without merging**
