### PR TITLE
Add OID for id-ct-geofeedCSVwithCRLF detached CMS signature

### PR DESCRIPTION
**Pull request by job**
draft-ietf-opsawg-finding-geofeeds describes a mechanism to authenticate  RFC 8805 Geofeed files with RPKI

real-world example: https://mailarchive.ietf.org/arch/msg/opsawg/FoRMmqkdNU6MOaTgNQs9sa-Tn9Q/

CLA: trivial

### CODE REVIEW

**Comment by slontis** [comment]
This is in a draft document currently see https://datatracker.ietf.org/doc/draft-ymbk-opsawg-finding-geofeeds/
I don't know at what point OID's are actually properly registered..

**Comment by job** [comment]
> This is in a draft document currently see https://datatracker.ietf.org/doc/draft-ymbk-opsawg-finding-geofeeds/
> I don't know at what point OID's are actually properly registered..

Yes, it is a draft, but the OID has been assigned by IANA (as per https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#security-smime-1 see 'id-ct-geofeedCSVwithCRLF') and can never ever be repurposed or recycled. Whether the draft becomes RFC or not is immaterial after IANA adds it to the 'SMI Security for S/MIME CMS Content Type ' registry.

This changeset does not introduce any validation logic, it merely acknowledges that the OID exists and gives it a name, which is super helpful for development.

**Review by slontis — APPROVED** [review]
I think this is trivial. Do other reviewers agree that this as a trivial change?

**Review by paulidale — APPROVED** [review]
Agree that this is trivial

**Comment by paulidale** [comment]
Merged to master, thanks.

**Pull request closed without merging**
