### PR TITLE
util/fix-deprecation: DEPRECATEDIN conversion util for public headers

### PR DESCRIPTION
**Pull request by levitte**
Use this for quick and easy conversion of old-style to new-style deprecation:

    perl util/fix-deprecation \
         < include/openssl/rsa.h > include/openssl/rsa.h.new
    mv include/openssl/rsa.h.new include/openssl/rsa.h

This is not a perfect utility, but it does the job.  It doesn't try to
re-indent, that's left for manual post processing.

### CODE REVIEW

**Comment by levitte** [comment]
This was advertised at least once (https://github.com/openssl/openssl/pull/13276#discussion_r515254675), so maybe a review / approval could be a thing?  @mattcaswell

**Review by mattcaswell — APPROVED** [review]
I got a little lost in the perl regex magic. But I got the gist.

**Comment by levitte** [comment]
Hold on, I think I found a strange bug...  I got some very odd results when trying this on ssl.h.in...

**Comment by levitte** [comment]
Fixed it.  Re-approval needed

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Found one last little bug, see cee4ae8 
Does your approval stand or do we have to restart the clock, @mattcaswell?

**Comment by mattcaswell** [comment]
Approval stands. Changes seems trivial so I don't think we need to restart.

**Comment by levitte** [comment]
Merged

5053394aa6bc989e1ce8f0e47578c691aee6aa47 util/fix-deprecation: DEPRECATEDIN conversion util for public headers

**Pull request closed without merging**
