### PR TITLE
Fix compilation with CMS disabled

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
The build errors are unrelated to this patch.

**Comment by kroeckx** [comment]
+1

**Comment by kroeckx** [comment]
Don't we have a tool to test combinations like this?

**Comment by richsalz** [comment]
Yes, run-checker in the bureau (internal) but it requires the 1.1 out-of-tree build system, and would need some porting for 1.0.2

**Comment by richsalz** [comment]
pushed at 23aec60.  thanks!

**Pull request closed without merging**
