### PR TITLE
Fix DSA/ECDSA sign infinite loop(s)

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
I assume this should not go into 3.1

**Review by paulidale — APPROVED** [review]
I don't see why this shouldn't go to 3.1 or even 3.0.
It's fixing a bug that results in a DoS.

**Comment by slontis** [comment]
DSA is not part of FIPS 186-5

**Comment by mattcaswell** [comment]
> DSA (signing) is not part of FIPS 186-5

But doesn't this impact the default provider?

**Review by mattcaswell — APPROVED** [review]

**Comment by paulidale** [comment]
Merged with manual fixes for 3.0 and 3.1

**Comment by bernd-edlinger** [comment]
Is there a reason why this should not be back-ported to 1.1.1 ?

**Pull request closed without merging**
