### PR TITLE
doc: Random spell checking

### PR DESCRIPTION
**Pull request by sebastianas**
A little spell checking.

Signed-off-by: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>

### CODE REVIEW

**Comment by mspncp** [comment]
_(Side note: It's annoying that links with line numbers don't work for markdown files, because GitHub always attempts to display them rendered.)_

**Comment by paulidale** [comment]
Good for 1.1.1 too.

**Comment by paulidale** [comment]
Merged to master.  1.1.1 did some funky stuff and ended up with way too large a commit.
I think 1.1.1 should be a separate PR.

**Comment by sebastianas** [comment]
On 2020-04-27 16:12:47 [-0700], Pauli wrote:
> Merged to master.  1.1.1 did some funky stuff and ended up with way too large a commit.
> I think 1.1.1 should be a separate PR.
Should I prepare a PR for 1.1.1?

Sebastian

**Comment by mspncp** [comment]
> Should I prepare a PR for 1.1.1?

Yes, that would be appreciated.

**Pull request closed without merging**
