### PR TITLE
Travis: Add a docs checking job

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
Prepare for a surprise...  our 1.1.0 docs are in less than perfect condition.

**Comment by levitte** [comment]
Docs fixups in #4633

**Comment by mattcaswell** [comment]
Right...there seems to be a whole stack of issues here. Are you going to fix those before merging this?

**Comment by levitte** [comment]
Well, I believe I have now merged all the fixes.  Let's see what a rebase does...

**Review by richsalz — APPROVED** [review]
hell yes

**Comment by richsalz** [comment]
There are some bugs and nits that aren't worth fixing, especially when the 1.1.0 to 1.1.1 migration is so "simple."  I think we have more important things to fix than doc-nits in a 1.1.0 release.
IMO YMMV etc :)

**Comment by levitte** [comment]
Me, I found it curious that we have a high quality standard for master, but not as high for the stuff we actually release.  Seemed counter intuitive.  Anyhow, now that you've approved...

**Comment by levitte** [comment]
Merged. bb0c588ab2c6dae55bb8adbcf72cab3bca390e0f

**Comment by richsalz** [comment]
That's always the way -- some bugs aren't worth the effort to port back to previous releases.  Especially for 1.1.0 which we hope will soon get widely replaced with 1.1.1  It's about prioritizing the effort.  Shrug.

**Comment by kroeckx** [comment]
This seems to have broken travis for 1.1.0

**Comment by kroeckx** [comment]
Never mind

**Pull request closed without merging**
