### PR TITLE
GOST2012 TLS Supported Groups Identifiers Support

### PR DESCRIPTION
**Pull request by NMorozxov**
For GOST2012-GOST8912-GOST8912 IANA introduce TLS Supported Groups Identifiers
https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by NMorozxov** [comment]
> One of the Travis builds is quite unhappy.
> Otherwise this looks good.
 Got very strange errors "malloc failure" f.ex
rebased to re-trigger travis

**Comment by beldmit** [comment]
It's a known (to me :) )problem.
I don't have a better solution for it than suppose that `no-ec` implies `no-gost`.

**Comment by NMorozxov** [comment]
Ok move no-gost block under no-ec block
> It's a known (to me :) )problem.
> I don't have a better solution for it than suppose that `no-ec` implies `no-gost`.

**Comment by beldmit** [comment]
Not sure it's a good solution. I think it's better to do it on the configure level.

**Comment by NMorozxov** [comment]
Ok. let's try this one
> Not sure it's a good solution. I think it's better to do it on the configure level.

**Comment by NMorozxov** [comment]
Now travis is happy

**Comment by kaduk** [comment]
> Not sure it's a good solution. I think it's better to do it on the configure level.

You mean, to use the `disable_cascades` in Configure to have no-ec imply no-gost?

**Comment by NMorozxov** [comment]
ping @beldmit @paulidale 
Travis happy waiting your reaction

**Comment by beldmit** [comment]
> You mean, to use the `disable_cascades` in Configure to have no-ec imply no-gost?

Yes. It's a disputable decision, though.

**Comment by NMorozxov** [comment]
@beldmit  What about the commit?

**Comment by beldmit** [comment]
> @beldmit What about the commit?

I'd recommend using `disable_cascades` instead of Travis tuning.

**Comment by NMorozxov** [comment]
Where i must add disable_cascades? I have only idea in travis....
> I'd recommend using `disable_cascades` instead of Travis tuning.

**Comment by beldmit** [comment]
You must use the disable_cascades in `Configure`

**Comment by NMorozxov** [comment]
can't what fails now :(

**Comment by beldmit** [comment]
Restarted the failed job

**Comment by NMorozxov** [comment]
thx
> Restarted the failed job

**Comment by NMorozxov** [comment]
Running for 3h 43m... omg...

**Comment by beldmit** [comment]
Restarted again.

**Comment by beldmit** [comment]
Travis failure seems not relevant here.

**Comment by beldmit** [comment]
Merged. Thanks!

**Comment by beldmit** [comment]
I was not attentive enough :(
The secbits value for GOST groups should be 128/256, so @NMorozxov  could you please provide a fixup PR?

**Comment by NMorozxov** [comment]
> I was not attentive enough :(
> The secbits value for GOST groups should be 128/256, so @NMorozxov could you please provide a fixup PR?
Ok. I don't know can i have 2 PRs i will try

**Pull request closed without merging**
