### PR TITLE
Add loongarch64 target

### PR DESCRIPTION
**Pull request by shipujin**
add loongarch64 config for no-asm.

### CODE REVIEW

**Comment by lina-not-linus** [comment]
I have sented a signed CLA pdf file to tolegal@opensslfoundation.org

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
The platform policy says this:

"Support for a new platform should only be added if it is being adopted as a primary, secondary or community platform."

https://www.openssl.org/policies/platformpolicy.html

Since this is a new platform we would need someone to volunteer to maintain it as a community platform before we could add this. Someone wishing to volunteer can do so by creating a PR to add the platform to the community platform section of the website here:

https://github.com/openssl/web/blob/e7a0d18986e378b0ce84a5a05c9b4279eb8fe937/policies/platformpolicy.html#L183-L510

> I have sented a signed CLA pdf file to [tolegal@opensslfoundation.org](mailto:tolegal@opensslfoundation.org)

The correct email address is [legal@opensslfoundation.org](mailto:legal@opensslfoundation.org)

**Comment by lina-not-linus** [comment]
I have sented a signed CLA pdf file to legal@opensslfoundation.org

**Comment by lina-not-linus** [comment]
Ping

**Comment by paulidale** [comment]
We'll need a commitment from someone to be the community maintainer for this new platform.

A PR against the [platform policies page](https://github.com/openssl/web/blob/master/policies/platformpolicy.html) is the way to do this.

**Comment by lina-not-linus** [comment]
> platform policies page

thanks, I'll go read it carefully

**Comment by tmshort** [comment]
I'm actually wondering why this is necessary? There's no special settings; and it duplicates `linux64-riscv64`. I almost think a new, generic `linux-perlasm64` with `perlasm_scheme = linux64` could be created, and `linux64-riscv64` inherit from that; and subsequently, loongarch64 could use `linux-perlasm64`, potentially without requiring support of a new platform.
```
    # linux-generic64 with perlasm_scheme
    "linux-perlasm64" => {
        inherit_from     => ["linux-generic64"],
        perlasm_scheme   => "linux64",
    },
    # riscv64 below refers to contemporary RISCV Architecture
    # specifications,
    "linux64-riscv64" => {
        inherit_from     => [ "linux-perlasm64"],
    },

**Comment by shipujin** [comment]
> I'm actually wondering why this is necessary? There's no special settings; and it duplicates`linux64-riscv64`. I almost think a new, generic`linux-perlasm64`with`perlasm_scheme = linux64`could be created, and`linux64-riscv64`inherit from that; and subsequently, loongarch64 could use`linux-perlasm64`, potentially without requiring support of a new platform.
> 
> ```
>     # linux-generic64 with perlasm_scheme
>     "linux-perlasm64" => {
>         inherit_from     => ["linux-generic64"],
>         perlasm_scheme   => "linux64",
>     },
>     # riscv64 below refers to contemporary RISCV Architecture
>     # specifications,
>     "linux64-riscv64" => {
>         inherit_from     => [ "linux-perlasm64"],
>     },
> ```

Sorry, do you mean the code should be changed to this?

```
    # linux-generic64 with perlasm_scheme
    "linux-perlasm64" => {
        inherit_from     => ["linux-generic64"],
        perlasm_scheme   => "linux64",
    },
    # riscv64 below refers to contemporary RISCV Architecture
    # specifications,
    "linux64-riscv64" => {
        inherit_from     => [ "linux-perlasm64"],
    },
    # loongarch64 below refers to contemporary LoongArch Architecture
    # specifications,
    "linux64-loongarch64" => {
        inherit_from     => [ "linux-perlasm64"],
    },
```

**Comment by tmshort** [comment]
No, I'm actually suggesting to _not_ define `linux64-loongarch64`, as that will require someone to to be a maintainer for that platform (although I see you made your request). Instead you would use the `linux-perlasm64` as a target, rather than a "loongarch" target. In other words, if it's possible to treat your platform as generic linux, you could do so.

**Comment by shipujin** [comment]
> No, I'm actually suggesting to _not_ define `linux64-loongarch64`, as that will require someone to to be a maintainer for that platform (although I see you made your request). Instead you would use the `linux-perlasm64` as a target, rather than a "loongarch" target. In other words, if it's possible to treat your platform as generic linux, you could do so.

I know what you mean. Currently, LoongArch Binutils and LLVM have been merged upstream, while gcc, glibc, Linux and other major components have been gradually merged upstream.
hoped that Openssl NO ASM Patch can be merged first,so that the release version can compile directly and solve the actual dependency problem.
openSSL ASM version is in development.

thanks

binutils:
https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=e9a0721f8274daeffaedbc3cabc12c52d43a38a7

llvm:
https://github.com/llvm/llvm-project/commit/42fd2bfc90653d67607f83a2bf569a9fc8fae7b8

**Review by tmshort — APPROVED** [review]
While I think that a generic `perlasm64` target could be made for this PR instead, there's nothing wrong with this. The update to the web site re:maintainer, would also have to be merged,

**Comment by shipujin** [comment]
> While I think that a generic`perlasm64`target could be made for this PR instead, there's nothing wrong with this. The update to the web site re:maintainer, would also have to be merged,

ok
thanks

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.
Thanks for the contribution.

**Comment by shipujin** [comment]
Hi, Will this patch enter the "OpenSSL-3.0" branch？thanks~

**Pull request closed without merging**
