### PR TITLE
Use travis_terminate on failure

### PR DESCRIPTION
**Pull request by richsalz**
Testing travis_terminate.

Fixes: #9616 (eventually)

### CODE REVIEW

**Comment by richsalz** [comment]
With a doc-nits error pushed, things work as expected; the build log ends with
```
 if [ -n "$CHECKDOCS" ]; then if $make doc-nits; then echo -e '+\057\057 MAKE DOC-NITS OK'; else echo -e '+\057\057 MAKE DOC-NITS FAILED'; travis_terminate 1; fi; fi
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" doc/man7/openssl_user_macros.pod.in > doc/man7/openssl_user_macros.pod
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" test/provider_internal_test.conf.in > test/provider_internal_test.conf
(cd .; /usr/bin/perl util/find-doc-nits -n -p -s ) >doc-nits
*** ERROR: Unknown command 'podling' at line 1 in file doc/man1/openssl.pod
Makefile:516: recipe for target 'doc-nits' failed
make: *** [doc-nits] Error 1
+// MAKE DOC-NITS FAILED
```

The job terminates.  Way cool.

**Comment by richsalz** [comment]
Ready to merge.

**Comment by levitte** [comment]
I wouldn't mind to see this cherry-picked to 1.1.1.

**Comment by levitte** [comment]
Merged.

master:
5be78a88aa922a6c43a83a18dbe252c6a358b8e9 .travis.yml: Use travis_terminate on failure

1.1.1:
ec9cbe21519f85e65e2f128d3f04bfd904642079 .travis.yml: Use travis_terminate on failure

**Comment by richsalz** [comment]
Thanks!  So now maybe the hack about multiple slashes to identify the sections should also vanish?

**Pull request closed without merging**
