### PR TITLE
Added '-nameopt' option to the verify command. 

### PR DESCRIPTION
**Pull request by beldmit**
##### Checklist
- [x] documentation is added or updated

##### Description of change
It makes possible to print the certificate's DN correctly in case of verification errors.

### CODE REVIEW

**Comment by dot-asm** [comment]
I'd say enhancement...

**Comment by richsalz** [comment]
I had to make nmflags a "static unsigned long".  @dot-asm, okay?

**Comment by richsalz** [comment]
@beldmit can you change nmflags like I did, and do commit --amend to update the single commit?

**Comment by beldmit** [comment]
I hope I did what you wanted from me.

**Comment by richsalz** [comment]
yes, that's good.  i'll merge/squash.  @openssl/committers  can anyone reconfirm?

**Comment by dot-asm** [comment]
Reconfirmed.

**Comment by beldmit** [comment]
Now the s_cb.c file is the last one in the apps/ folder where the XN_FLAG_ONELINE is hardcoded.

**Comment by richsalz** [comment]
ad39b31 on master; thanks!  Looking forward to your patch for s_cb.c :)

**Pull request closed without merging**
