### PR TITLE
Fix documentation for provider-signature

### LINKED ISSUE #17909: Incorrect provider-signature function declaration
The functions 'OSSL_FUNC_signature_digest_sign_init' & 'OSSL_FUNC_signature_digest_verify_init' have an excess argument 'const char *props' in their declaration. 

Problem in OpenSSL 3.0; doc/man7/provider-signature.html

### PR DESCRIPTION
**Pull request by hlandau**
Fixes #17909.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Review by paulidale — COMMENTED** [review]
On second thought, I think we should allow a property query here.  We're fetching a provided algorithm after all....

I.e. change the function signature not the documentation.

@t8m and @levitte, your thoughts?

**Comment by levitte** [comment]
> On second thought, I think we should allow a property query here. We're fetching a provided algorithm after all....

*Our* providers may do that.  Others may not, depending on if they provide the auxilliary algorithm internally or not.

> I.e. change the function signature not the documentation.
> 
> @t8m and @levitte, your thoughts?

I disagree.  We already pass that as an OSSL_PARAM (as well as an engine name if that's of interest), please don't clutter the function signature further on maybe's

**Comment by levitte** [comment]
> I.e. change the function signature not the documentation.

... furthermore, that would be a public API breach...

**Comment by paulidale** [comment]
Merged to master and 3.0.

**Pull request closed without merging**
