### PR TITLE
Update the gost-engine commit

### LINKED ISSUE #11949: External GOST tests are failing
#11442 was approved and merged before #11792, so we missed the following failure during the rebase on merge:

~~~
[ 90%] Building C object CMakeFiles/test_tlstree.dir/test_tlstree.c.o
/home/travis/build/openssl/openssl/gost-engine/test_tlstree.c: In function 'main':
/home/travis/build/openssl/openssl/gost-engine/test_tlstree.c:130:27: error: 'EVP_CTRL_TLS1_2_TLSTREE' undeclared (first use in this function); did you mean 'EVP_CTRL_TLSTREE'?
  EVP_CIPHER_CTX_ctrl(enc, EVP_CTRL_TLS1_2_TLSTREE, 0, seq0);
                           ^~~~~~~~~~~~~~~~~~~~~~~
                           EVP_CTRL_TLSTREE
/home/travis/build/openssl/openssl/gost-engine/test_tlstree.c:130:27: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/test_tlstree.dir/build.make:62: recipe for target 'CMakeFiles/test_tlstree.dir/test_tlstree.c.o' failed
make[3]: *** [CMakeFiles/test_tlstree.dir/test_tlstree.c.o] Error 1
make[3]: Leaving directory '/home/travis/build/openssl/openssl/gost-engine/build'
CMakeFiles/Makefile2:588: recipe for target 'CMakeFiles/test_tlstree.dir/all' failed
make[2]: *** [CMakeFiles/test_tlstree.dir/all] Error 2
make[2]: Leaving directory '/home/travis/build/openssl/openssl/gost-engine/build'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/travis/build/openssl/openssl/gost-engine/build'
../../util/wrap.pl sh ../../test/recipes/95-test_external_gost_engine_data/gost_engine.sh => 2
not ok 1 - running GOST engine tests
#   Failed test 'running GOST engine tests'
#   at test/recipes/95-test_external_gost_engine.t line 25.
# Looks like you failed 1 test of 1.
95-test_external_gost_engine.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
~~~

This is probably solved by bumping the `gost-engine` submodule to a more recent revision.

@beldmit can you look into this?

### PR DESCRIPTION
**Pull request by beldmit**
Fixes #11949
[extended tests]

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
The tests have passed.
@romen, should this PR be labeled as urgent?

**Comment by romen** [comment]
Yes, I believe this qualifies as urgent, I added the corresponding label.

**Comment by beldmit** [comment]
The build is successful.

**Comment by romen** [comment]
@openssl/otc can someone confirm this is urgent?

**Comment by mspncp** [comment]
I agree it's urgent. But I'd prefer the commit title to be

```
Update the gost-engine submodule
```

which is more descriptive IMHO. (Can be done during merging.)

**Comment by romen** [comment]
@beldmit can you edit the title on merge?

**Comment by beldmit** [comment]
Sure

**Comment by beldmit** [comment]
Merged. Thanks!

**Pull request closed without merging**
