### PR TITLE
Make RAND_METHOD opaque

### PR DESCRIPTION
**Pull request by richsalz**
This makes no changes to the public API.
If anyone has written their own RNG we can add the necessary functions to let them do so.  I'm not going to hold my breath expecting that. :)

### CODE REVIEW

**Comment by mattcaswell** [comment]
I don't think we can do this in 1.1.1 - it would have to wait for 1.2.0. BTW - I do believe that people have implemented their own rand implementations.

**Comment by mattcaswell** [comment]
If you want to use a hardware random number generator then you will have to implement your own RAND implementation. I'm pretty confident that there are such implementations out there.

I am strongly opposed to this. It's a very glaring break in our source code compatibility guarantee which we should not be allowing into 1.1.1.

**Comment by mattcaswell** [comment]
A bit of searching turned up this:

https://github.com/MicrochipTech/cryptoauth-openssl-engine/blob/master/engine_atecc/engine_meth/eccx08_rand.c#L121

**Comment by richsalz** [comment]
Okay, we’ll have to see if the security argument sways people down the line.
I am still pushing for this

**Comment by mattcaswell** [comment]
I could envisage a workaround...e.g. an opaque RAND_METHOD2 structure (or something with a better name) that has all the same stuff as RAND_METHOD plus whatever extra. Introduce RAND_set_rand_method_ex() which takes the RAND_METHOD2 instead. Change RAND_set_rand_method() to wrap the provided RAND_METHOD in a RAND_METHOD2 and then call RAND_set_rand_method_ex().

**Comment by richsalz** [comment]
That would work (modulo cleaning up the memory leaks), but is complex.  I prefer to do the clean thing, for security reasons, even if it breaks a couple of chip-maker’s code.

**Comment by levitte** [comment]
-1

Like it or not, but since `struct rand_meth_st` is in a public header, it's part of the public API.  It doesn't matter if it's undocumented.

On the other hand, this is perfectly acceptable for 1.2.0.  Please label it accordingly.

**Comment by mattcaswell** [comment]
Just another example (this time it looks like a software implementation - not a chip manufacturer):

https://github.com/heimdal/heimdal/blob/master/lib/hcrypto/rand-fortuna.c#L626

**Comment by richsalz** [comment]
I am not going to hold/label it until we see how important it is for other RNG work; and then we’ll take it to an OMC vote.

**Comment by kroeckx** [comment]
Just for the record, I agree with Matt and Richard that we should
not change the public header in 1.1.1.

**Comment by levitte** [comment]
@richsalz, this is not a matter of a vote, it's a matter of policy that we have already voted on.  See the release strategy.

**Comment by t-j-h** [comment]
Many people have written their own RNG implementation! This should go opaque but that has to wait for 1.2.0 - this is in the API.

-1

**Comment by richsalz** [comment]
The question is whether the security issue, which we won’t know yet, trumps it.

**Comment by kroeckx** [comment]
It doesn't.

**Comment by richsalz** [comment]
Okay, clearly the team is opposed.  I'll move this to HOLD/1.2.0 now here's hoping you'll look at my other RAND-related PR's.

**Comment by colmmacc** [comment]
In s2n, we wrote our own rand, and we over-ride OpenSSLs, so that it's what's used when we call OpenSSL for ECDSA, DH, etc. 

https://github.com/awslabs/s2n/blob/master/utils/s2n_random.c

**Comment by richsalz** [comment]
Thanks.  I looked at the DRBG code.  It’s interesting.

**Comment by paulidale** [comment]
I've done a RAND engine to wrap our entropy source.  Changing to a new API wouldn't be an issue for me though.

I did wonder why the other engine structures were hidden but not this.

**Comment by richsalz** [comment]
We missed a few and now we’re stuck until 1.2.0

**Comment by levitte** [comment]
@paulidale, I believe the drive for opacity was driven quite a lot from a EVP and X509 perspective.  RAND is kind of a side-kick from that point of view (not trying to say that RAND is unimportant, quite the contrary!  but it doesn't hold a space in the EVP and X509 modules)...

**Comment by richsalz** [comment]
We goofed and missed it.  We really wanted to make everything opaque, but knew we wouldn’t succeed.

**Comment by richsalz** [comment]
Closing this, and instead opened issue #6829 to capture the idea.

**Pull request closed without merging**
