### PR TITLE
Configure cleanup

### PR DESCRIPTION
**Pull request by levitte**
Cleaning away a bunch of old cruft from `Configure` and `build.info` files.

### CODE REVIEW

**Comment by mspncp** [comment]
Apropos cleanup: I noticed recently that the `Configure` file has mixed whitespace and the indentation looks wrong unless tab-width=8. Would you mind fixing that en passent?

**Comment by levitte** [comment]
Such cleanup will be in a separate PR, as I'll want to make it for 1.1.1 as well (or future cherry-picking will be hellish)

**Comment by levitte** [comment]
I seem to have fixed the issue, CIs are happier...

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

a17089b0d750732d1b9d19ad924b3f8a2d7c3111 Configure: clean away unused variables and double assignments
fb3637d9ae260fa49615f4442127473d0ce27ebf Build: clean away RENAME and SHARED_NAME
da7e31e0c7be390d37b84c6200afd802def700c5 Build: remove EXTRA
77adb75e16142cd4da2af8814090a4f2c2bd5aea Build: Remove BEGINRAW / ENDRAW / OVERRIDE
77550dbf7af4d31b915d076ee968cfc75e14a411 Build cleanup: Remove the VMS hack from test/build.info

**Pull request closed without merging**
