### PR TITLE
Add FIPS indicators to X25519 and X448.

### PR DESCRIPTION
**Pull request by slontis**
X25519 and X448 are unapproved in FIPS 140-3
So always trigger the indicator callback if these Keys are used, and add "fips-indicator" getters that return 0.

This has been added to keygen and key exchange.
(KEM will also require it if ever becomes a FIPS algorithm).

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
Formatting CI seems relevant.

**Review by paulidale — APPROVED** [review]
With the style nit addressed.

**Review by paulidale — APPROVED** [review]

**Comment by slontis** [comment]
Cross Testing PR against master is not a relevant test

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged!

**Pull request closed without merging**
