### PR TITLE
Fix BIO_printf function replaces the last char of the output with \0 under certain conditions.

### PR DESCRIPTION
**Pull request by soushi**
I was contacted the same problem to the mailing list in the past, have requested even here because it was ignored.

http://marc.info/?l=openssl-users&m=137722533630452&w=2

### CODE REVIEW

**Comment by ghedo** [comment]
Looking at the [code in master ](https://github.com/openssl/openssl/blob/master/crypto/bio/b_print.c#L710), this seems to be fixed, correct? (I haven't tried to reproduce the issue though).

**Comment by richsalz** [comment]
We'll have to check the other branches before closing.

**Comment by richsalz** [comment]
+1.
This is for 1.0.2 / 1.0.1 only!

**Comment by levitte** [comment]
for the BIO printing variants, 1.0.2 essentially has the same code as master.  1.0.1 is in its last year meaning security fixes only.  This change isn't a security fix as far as I know.

For all these reason, this PR is done.  Closing.

**Pull request closed without merging**
