### PR TITLE
Constify command option arrays

### PR DESCRIPTION
**Pull request by FdaSilvaYY**

### CODE REVIEW

**Comment by richsalz** [comment]
Please do not add the nunnecessary NULL inititliazers.

**Comment by FdaSilvaYY** [comment]
@richsalz : code fixed and rebased.

**Comment by levitte** [comment]
> The style guide puts no spaces on curly-brace initializers.

Could you please tell me where the style guide says anything about that?  I must be blind, 'cause I can't find it.

**Comment by richsalz** [comment]
Okay, our indent program.  My mistake.

**Comment by levitte** [comment]
The reason we try to skip having spaces after opening and before closing braces of initialisers is because indent will massage this:

``` C
    { foo, "bar" }
```

into:

``` C
    {
        foo, "bar"
    }
```

While this is left alone:

``` C
    {foo, "bar"}
```

So yes, if you want the one line initialisers of this sort to remain as they are through some automatic source formatting, it's recommended to avoid the spaces.

**Comment by richsalz** [comment]
Until we get a different tool, either really fix the {} spaces or take them out of this PR.

**Comment by FdaSilvaYY** [comment]
@richsalz commit added to fix style issue in prog.pl and prog.h

**Comment by levitte** [comment]
Yup

**Comment by richsalz** [comment]
thanks for your cooperation.

**Pull request closed without merging**
