### PR TITLE
Vms build addition

### PR DESCRIPTION
**Pull request by msteve1**
The following will allow the openssl libraries to be built in mixed case linkages for OpenVMS using the decc compiler. The compiler option "decc_ai" must be used explicitly as a parameter to the build scripts for this to be applied.

### CODE REVIEW

**Comment by levitte** [comment]
Nice initiative!

There's one thing to think of, though, and that other applications that use OpenSSL, they won't pick up the NAME=AS_IS condition and will have linking problems.

The solution for this is to have the special prologue and epilogue header files, as explained [here](http://h71000.www7.hp.com/commercial/c/docs/5492profile_008.html#prolog_epilog_sec).  Feel free to copy those we have in the [master branch](https://github.com/openssl/openssl/tree/master/include/openssl)
This also means that you don't have to add `/NAME=AS_IS` in `apps/makeapps.com` or in `test/maketests.com`, since those builds will pick up the correct name settings from said header files.
I'd say this is a *must* for this kind of change.

-----
** *[optional]* **

Another thing you might want to think of is having uppercase aliases when creating the shared libraries for libcrypto and libssl.  This doubles the size of the transfer vector for sure, but seems to be a convention that's worth following.  With the alpha/ia64 symbol vector, it looks like this (taken from master):

```
SYMBOL_VECTOR=(-
 D2I_EC_PUBKEY/d2i_EC_PUBKEY=PROCEDURE -
  ,d2i_EC_PUBKEY=PROCEDURE -
 ,B2I_PVK_BIO/b2i_PVK_bio=PROCEDURE -
  ,b2i_PVK_bio=PROCEDURE -
...
```

I have no idea how one should do the same thing in a VAX C transfer vector, as we've given up VAX in master....

This is *optional*, really at your leasure.

**Comment by levitte** [comment]
Before you get started on more, let's check with the rest of the team if this is an appropriate change for a stable branch.

**Comment by msteve1** [comment]
I’m unaware of a #pragma that controls names. I will look into your suggestions (thank you for them).  This issue with the /names compiler option is synonymous to the building of 32 and 64 bit versions of the library; I had pondered possibly using a suffix on the library name to alleviate the confusion (openssl64ai, opensslai, etc.). This was not something that I can decree. My solution is an attempt to provide an optional middle ground.

Michael Steve

**Comment by levitte** [comment]
Hi,

while I still like the initiative, I must deny it for our source.  We (the team) found that it's much too late in the cycle of this OpenSSL version to insert what amounts to another platform (even if said new platform is a variation of something already existing).  My appologies if I gave you any false hopes.

Meanwhile, I invite you to add the patch to our Wiki (wiki.openssl.org).  You must register to do so.
Also, I'd be happy if you'd try out the upcoming OpenSSL 1.1 (that is, the master branch).

**Pull request closed without merging**
