### PR TITLE
Fix int_ctx_new() error when use 1.1.1n sm2 key and ec method engine

### LINKED ISSUE #21169: EVP_DigestSignInit() failed when use 1.1.1n sm2 key and set ec meth engine
OpenSSL version: master

Issue Description:
My application set customised ec method using the Engine_register_EC interface and then loaded the sm2 private key generated by 1.1.1n for signing, but failed.

Error log:
error:0300009C:digital envelope routines:int_ctx_new:unsupported algorithm

Preliminary analysis:
The foreign value of the SM2 pkey is set in detect_foreign_key function.

### PR DESCRIPTION
**Pull request by lan1120**
Fix #21169

### CODE REVIEW

**Comment by t8m** [comment]
This means the custom EC method will not be used for the key. I assume this is OK.

**Review by t8m — APPROVED** [review]
This would be acceptable with CLA: trivial. If you agree, please amend the commit message and put `CLA: trivial` on a separate line in the commit message body.

**Comment by lan1120** [comment]
OK

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
okay with trivial

**Comment by paulidale** [comment]
Merged, thanks for the contribution.

**Pull request closed without merging**
