### PR TITLE
Rename XXX_new_with_libctx to XXX_new_ex

### PR DESCRIPTION
**Pull request by richsalz**
Fixes: #11509

### CODE REVIEW

**Comment by mattcaswell** [comment]
It was an explicit decision following review feedback quite some while ago (I don't recall which PR) to use "with_libctx" in preference to "_ex" as it is more descriptive. Since then I've used it for all "new" type functions. In other functions the "libctx" seemed more incidental and I stuck with "_ex". I dislike "_ex" but have an imagination failure every time I try to think of a new function name. I could live with a decision to make all "_ex" functions that take a libctx be called "with_libctx". Or a decision to just rename any existing "_new_ex" functions that take a libctx to "_new_with_libctx" (I actually think that *should* be done). What I don't think is a good idea is to rename existing "with_libctx" functions to "_ex".

**Comment by richsalz** [comment]
I think it is more important to pick *one scheme* and use it.  Historically, OpenSSL has added the ```_ex``` suffix whenever it added a similar API with new parameters.  It has not added descriptive suffixes.

"Join us" :)  No, seriously, you shouldn't add a new naming convention.  I mean, you're the one who created "RAND_DRBG_new_ex" ...

**Comment by slontis** [comment]
> I think it is more important to pick _one scheme_ and use it. Historically, OpenSSL has added the `_ex` suffix whenever it added a similar API with new parameters. It has not added descriptive suffixes.
> 
> "Join us" :) No, seriously, you shouldn't add a new naming convention. I mean, you're the one who created "RAND_DRBG_new_ex" ...

So what happens when there is already an _ex??, 
ex2?
ex_ex

**Comment by richsalz** [comment]
*   So what happens when there is already an _ex??

I don’t know.  Presumably the OTC decides on a policy. But none of the functions here (nor OPENSSL_CTX_get0_master_drbg etc) have that problem.

**Comment by richsalz** [comment]
Pushed commit to rename OPENSSL_CTX_get0_public_drbg to RAND_DRBG_get0_master_ex, etc.

**Comment by mattcaswell** [comment]
I disagree with the premise behind this PR.

**Comment by richsalz** [comment]
I am working on making DRBG FIPS-compatible.  I just happened to stumble across the OPENSSL_CTX_get0_master_drbg.

Consistent naming conventions help the user, but *also help the OpenSSL developer.*

Sorry you disagree with the premise: consistency is important.

**Comment by mattcaswell** [comment]
> Sorry you disagree with the premise: consistency is important.

I don't disagree with consistency. I disagree with your interpretation of what consistency should look like.

**Comment by richsalz** [comment]
Given an existing API, that has a history of adding "_ex" suffix when additional parameters are added... I am curious to know what you think consistency should look like?  This PR changes two families of functions to match the existing convention.  Clearly all three should not exist.  Which should change, and to what?

**Comment by richsalz** [comment]
rebased to address conflict in libcrypto.num

**Comment by levitte** [comment]
`_ex` was, I think, inspired from Microsoft :astonished: 

https://stackoverflow.com/questions/4039054/what-does-ex-stand-for-in-windows-api-function-names

I'm one of those that find it perfectly non-descript, and worse, if you look at the English language where "ex" usually implies "previous", confusing. 

Also, the issue with needing to change a function that already has that suffix remains unanswered... and we already have a few cases where we went for more descriptive names for that reason among others, the new variants of `EVP_PKEY_CTX_new`.

**Comment by kaduk** [comment]
> inspired from Microsoft

I believe I've even seen some `Ex3` APIs from Microsoft.  But maybe it was "just" a data structure and not an API; it's been a while.

**Pull request closed without merging**
