### PR TITLE
s390x assembly pack: import poly from cryptogams repo

### PR DESCRIPTION
**Pull request by p-steuer**
Import poly1305 s390 implementation from @dot-asm   's cryptogams repo. Improves performance for both short and long inputs (>= 20% faster for long inputs).

### CODE REVIEW

**Comment by mattcaswell** [comment]
In #8387 you said "Andy said its okay for me to contribute the code", and I'm assuming the same applies here (please confirm?).

In #8387 @dot-asm said "If it makes you feel better, reserve some time for opportunity to object. .... And if somebody you already know says they talked to me, there is no reason to believe that they didn't." by which I interpret he is ok with us taking your word for it. We should leave it a few days before merge just in case there are objections.

@levitte will you review?

**Comment by p-steuer** [comment]
Yes, andy said its okay for me to contribute the poly code also.

**Comment by dot-asm** [comment]
It was also said "Public reference to me by the alias (not regular name, because I get notifications only if mentioned by alias) is **sufficient**." In other words minimal algorithm is "reference by alias -> no objection -> green light."

**Comment by levitte** [comment]
Will have a look tomorrow

**Comment by levitte** [comment]
Notable results:

master:

```
levitte@lxossl2:~/gitwrk/openssl.org/master> ./util/shlib_wrap.sh apps/openssl speed -evp chacha20-poly1305
Doing chacha20-poly1305 for 3s on 16 size blocks: 15230888 chacha20-poly1305's in 2.90s
Doing chacha20-poly1305 for 3s on 64 size blocks: 13127344 chacha20-poly1305's in 2.95s
Doing chacha20-poly1305 for 3s on 256 size blocks: 9223939 chacha20-poly1305's in 2.95s
Doing chacha20-poly1305 for 3s on 1024 size blocks: 2858835 chacha20-poly1305's in 2.95s
Doing chacha20-poly1305 for 3s on 8192 size blocks: 410212 chacha20-poly1305's in 2.95s
Doing chacha20-poly1305 for 3s on 16384 size blocks: 206804 chacha20-poly1305's in 2.91s
version: 3.0.0-dev
built on: built on: Fri Mar 29 07:31:12 2019 UTC
options:bn(64,64) rc4(8x,char) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DOPENSSL_USE_NODELETE -DB_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DAES_ASM -DAES_CTR_ASM -DAES_XTS_ASM -DGHASH_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
chacha20-poly1305    84032.49k   284796.62k   800450.30k   992354.93k  1139137.87k  1164356.27k
```

This PR:

```
levitte@lxossl2:~/gitwrk/openssl.org/master> ./util/shlib_wrap.sh apps/openssl speed -evp chacha20-poly1305
Doing chacha20-poly1305 for 3s on 16 size blocks: 15123029 chacha20-poly1305's in 2.88s
Doing chacha20-poly1305 for 3s on 64 size blocks: 12204315 chacha20-poly1305's in 2.94s
Doing chacha20-poly1305 for 3s on 256 size blocks: 9743347 chacha20-poly1305's in 2.94s
Doing chacha20-poly1305 for 3s on 1024 size blocks: 3039421 chacha20-poly1305's in 2.91s
Doing chacha20-poly1305 for 3s on 8192 size blocks: 437624 chacha20-poly1305's in 2.92s
Doing chacha20-poly1305 for 3s on 16384 size blocks: 224182 chacha20-poly1305's in 2.94s
version: 3.0.0-dev
built on: built on: Fri Mar 29 07:25:04 2019 UTC
options:bn(64,64) rc4(8x,char) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DOPENSSL_USE_NODELETE -DB_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DAES_ASM -DAES_CTR_ASM -DAES_XTS_ASM -DGHASH_ASM -DPOLY1305_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
chacha20-poly1305    84016.83k   265672.16k   848400.28k  1069541.96k  1227745.14k  1249319.01k
```

**Comment by levitte** [comment]
Merged.

2e6b615f795e8ca8ae830a00079c4ea064eaae42 s390x assembly pack: import poly from cryptogams repo

**Pull request closed without merging**
