### PR TITLE
Add x25519-ppc64.pl module.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by dot-asm** [comment]
Is world black or white? I mean there are things that you can't definitely label one or another... So shall we say two approvals would be required here?

**Comment by dot-asm** [comment]
> Is this a feature? Or a bugfix?

Is 6772 feature? Or a bugfix? Think same thoughts... :-)

**Comment by t-j-h** [comment]
That is a bit of a challenge. 

#6672 is security hardening whereas this is a performance improvement.
It does entirely change the implementation on the platform.

I don't see performance improvement by itself as a bugfix - that is too far of a stretch for me.

However things aren't black and white either so I would evaluate it based on the risk of it going wrong. 
Algorithm implementations are easy to test.

However our focus as a team is meant to be on completing the 1.1.1 release and this certainly wasn't on the list for that.

So no approval from me, but also no -1 either.

**Comment by richsalz** [comment]
I am glad to see this discussion.

**Pull request closed without merging**
