### PR TITLE
Add support for BSD-riscv64 target to 1.1.1

### PR DESCRIPTION
**Pull request by pkubaj**
Reviewed-by: Tomas Mraz <tomas@openssl.org>
Reviewed-by: Ben Kaduk <kaduk@mit.edu>
Reviewed-by: Paul Dale <pauli@openssl.org>
(Merged from https://github.com/openssl/openssl/pull/17306)

(cherry picked from commit c2d1ad0e048dd3bfa60e6aa0b5ee343cc6d97a15)
(cherry picked from commit c9ede1ee2058f067274929e813e257394d0ef6bb)

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by kaduk — APPROVED** [review]

**Comment by kaduk** [comment]
Hmm, should we update the second "cherry picked from" line to match the sha1 that is actually on the 3.0 branch?

**Comment by mattcaswell** [comment]
> Hmm, should we update the second "cherry picked from" line to match the sha1 that is actually on the 3.0 branch?

Yes. Such a trivial change can just be done during merge.

**Comment by kaduk** [comment]
> 24 hours has passed since 'approval: done' was set, but this PR has failing CI tests. Once the tests pass it will get moved to 'approval: ready to merge' automatically, alternatively please review and set the label manually.

I see all-green on the checks.  I'd like to have someone else confirm before I push (or someone else could just push themselves, too), even though this change should be totally orthogonal to the CI...

**Comment by mattcaswell** [comment]
> I'd like to have someone else confirm before I push

All looks in order to me. I don't know why the bot is complaining about CI failures. Adding the ready-to-merge label

**Comment by kaduk** [comment]
Pushed to 1.1.1.  Thanks for the backport and the review; closing

**Pull request closed without merging**
