### PR TITLE
Fix typos newly found by codespell in branch 3.0

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fix only typos in `doc/man*` for inclusion in branch 3.0.

CLA: trivial

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]
Okay with trivial

**Review by hlandau — APPROVED** [review]
Agree trivial

**Review by paulidale — APPROVED** [review]
Yes, trivial.

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
