### PR TITLE
limit bignums to 128 bytes in fuzzer

### PR DESCRIPTION
**Pull request by nhorman**
@toralf discovered that running the bignum fuzzer was spending large amounts of time doing computations for large bignums under the AFL fuzzer, leading to reported hangs/delays.  Like we do for several other fuzzers, limit the input size for a bignum to no more than 512 bytes to prevent those warnings

### CODE REVIEW

**Comment by levitte** [comment]
That subject was a bit alarming, until you read the rest.  Almost clickbait 😆

**Comment by nhorman** [comment]
@levitte ha!  yeah, I can see how that would be alarming, let me fix that.  Right now this is just a test to see if it makes the latency in #21645 go away

**Comment by kroeckx** [comment]
I think we have special code paths for certain sizes, not sure 1024 bit is enough. We would need to compare the coverage before and after.

**Comment by nhorman** [comment]
@kroeckx the most obvious limit that I see is that we disable consttime computations if a bignum has more than 1048575 elements in it, which on an x86_64 system is 8388600 bits for a bignum.  I'm not sure the AFL fuzzer will ever provide input bignums that will reach that limit.

**Comment by kroeckx** [comment]
I think it will do that, but it's going to be much to slow.
I can only find RSAZ_1024_mod_exp_avx2 and RSAZ_512_mod_exp currently.

**Comment by kroeckx** [comment]
> I think it will do that, but it's going to be much to slow.

I think by default it generates files up to 1 MB, so I guess it won't reach it.

**Comment by nhorman** [comment]
so is there a consensus on bignum size here?  Is 128 bytes reasonable, or should it be increased

**Comment by paulidale** [comment]
I'd suggest larger.  512 bytes is 4k bits which is a size in fairly wide use.

**Comment by nhorman** [comment]
I've updated the limit to 512 bytes

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by nhorman** [comment]
merged to active branches, thank you!

**Pull request closed without merging**
