### PR TITLE
Convert asynciotest for the new test framework

### PR DESCRIPTION
**Pull request by mattcaswell**
##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
One thing I wasn't sure what to do with when doing this conversion was this statement:
````
    if (!testresult)
        ERR_print_errors_fp(stderr);
````
Any opinions @pauli-oracle or @jon-oracle? For the moment I've left it in.

**Comment by levitte** [comment]
> One thing I wasn't sure what to do with when doing this conversion was this statement:
> ````
>     if (!testresult)
>         ERR_print_errors_fp(stderr);
> ````
> Any opinions @pauli-oracle or @jon-oracle? For the moment I've left it in.

If I may...  originally, this was displayed at the end of the whole run, so if you want to mimic that, you can remove those lines since `finalize()` does a `ERR_print_errors_fp()` call.  However, if you want to display errors per subtest, then keep it.

**Comment by pauli-oracle** [comment]
I've been removing calls to `ERR_print_errors_fp()` on the premise that the test harness is doing them for us.

For consistency, I'd suggest that this should be the responsibility of the framework not the test.  Unless there are compelling reasons for the test to require otherwise.

**Comment by richsalz** [comment]
That makes sense to me!

**Comment by mattcaswell** [comment]
Updated to remove ERR_print_errors_fp(). @richsalz please reconfirm?

**Comment by richsalz** [comment]
+1

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
