### PR TITLE
Publishes the function RSA_encode_pkcs1 (from internal encode_pkcs1)

### PR DESCRIPTION
**Pull request by opensignature**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
May I ask why?

**Comment by opensignature** [comment]
I would use it here https://github.com/opensignature/openssl/blob/signonly-pkcs11-engine/engines/e_pkcs11.c#L42
PKCS#11 C_Sign wants to input an pkcs1 encoded digest.
But I think it can also be useful to others ( https://mta.openssl.org/pipermail/openssl-users/2018-October/008950.html )

**Comment by levitte** [comment]
May I suggest you look at [this manual page](https://www.openssl.org/docs/manmaster/man3/RSA_padding_add_PKCS1_type_1.html)?

**Comment by opensignature** [comment]
> May I suggest you look at [this manual page](https://www.openssl.org/docs/manmaster/man3/RSA_padding_add_PKCS1_type_1.html)?

then it should also be used here? https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_sign.c#L94

I will do some tests, thanks

**Comment by opensignature** [comment]
RSA_encode_pkcs1 produces DER encoding T of the DigestInfo value as defined here https://tools.ietf.org/html/rfc3447#section-9.2 instead RSA_padding_add_PKCS1_type_1 only pad with block type and 0xff data

**Comment by opensignature** [comment]
Can I close this PR?
You don't think this change is useful, right @levitte ?

**Pull request closed without merging**
