### PR TITLE
fix BN_hex2bn()/BN_dec2bn() memory leak

### PR DESCRIPTION
**Pull request by huangqinjin**
```c
BIGNUM* n = NULL;
if (BN_hex2bn(&n, "g")){
    ...
    BN_free(n);
}
else{
     // error handling
}
```
  According to returned error code(0), we need to handle the error and generally expect that n is still NULL so that we don't need call to BN_free(), but we are disappointed and may cause potential memory leak. In additionI, "-g" isn't a valid hex string but `BN_hex2bn(&n, "-g")` returns 1 and eats the char '-'.

  This fix may be a breaking change for someone?!

### CODE REVIEW

**Comment by kroeckx** [comment]
So one of the problem is that `BN_hex2bn(&n, "")` returns 0 now, and that 0 is documented as error while it actually seems to return a BN with the number 0 I think.

The `BN_hex2bn(&n, "-g")` returning 1 seems to be intentional, but the documentation is silent about:
- That the `-` is part of the returned for the length, it returns the number of characters read.
- That it stops at the first invalid char  (like strtol()) and that you might need to compare the return value against the length of the string.

And if you would document it as such, you could argue whether the old behaviour is wrong or not, either works for me, but I would actually prefer the behaviour of the patch.

**Comment by huangqinjin** [comment]
If we compare the return value against the length of the string, we will not accept "-g" a vaild hex string, by the way, `strtol()` doesn't eat `-` in this case. If this patch won't be accepted, we should fix memory leak issue in  `EC_POINT_hex2point()`:
```c
    BIGNUM *tmp_bn = NULL;

    if (!BN_hex2bn(&tmp_bn, buf)){
        BN_free(tmp_bn);  // Add this!
        return NULL;
    }
```

**Comment by kroeckx** [comment]
All I'm saying is that we should figure out what the behaviour is that we want, and that we should document it.

**Comment by mattcaswell** [comment]
Ping @huangqinjin. What is the status of this?

**Comment by huangqinjin** [comment]
Pong @mattcaswell .As kroeckx said, we should clearly document the behavior of return value 0 (need to call BN_free?). I don't know if there're anyone's codes work depending on the old behavior. The conservative fix is to add `BN_clear_free(tmp_bn);` in `EC_POINT_hex2point()`.

**Comment by mattcaswell** [comment]
IMO the behaviour of the patch is correct. @huangqinjin please could you update the documentation to make it clear that "-" is part of the returned length, and that it will stop at the first invalid character.

@kroeckx I'm not sure what you mean about `BN_hex2bn(&n, "")`. AFAICT this would return 0 and no BN would be allocated in this patch?

**Comment by huangqinjin** [comment]
Help to polish the language.

**Comment by mattcaswell** [comment]
Looks good to me.

+1

**Comment by kroeckx** [comment]
@mattcaswell: The behaviour before the patch with "" is different, and the whole point of the patch.

Anyway, +1

**Comment by richsalz** [comment]
No CLA.  Is this okay to merge?

**Comment by mattcaswell** [comment]
It is non-trivial so should have a CLA really.

**Comment by mattcaswell** [comment]
CLA issues resolved. Merged! Thanks.

**Pull request closed without merging**
