### PR TITLE
Add 'copy' and 'move' Configuration Values for DNS Subject Alternative Names

### PR DESCRIPTION
**Pull request by OscarAyoy**
This is a tiny patch intended to simplify the creation of server certificates using the OpenSSL command line tools. What it does is to replace the existing method for copying/moving email addresses from the subject name with a slightly more flexible version that at handles both email addresses and common names. The latter is then used to populate the DNS field(s) of the resulting subject alternative name extension.

In order to use it, simply include the line "subjectAltName = DNS:copy" in the certificate extensions section of your OpenSSL config file.

### CODE REVIEW

**Comment by pearcep** [comment]
I think some clarification is needed with "copy_extensions = copy(all)"
If copy_extensions = copy then this patch will take precedence over any CSR SAN, since "copy_extensions" already has a SAN extension.
If copy_extensions = copyall then any CSR SAN will take precedence over this patch, since "copy_extensions" will delete the "patch SAN".

In other words the patch comes first, copy_extensions comes next.

**Comment by koeppea** [comment]
Is there anything been done in the meantime that tries to fix the issue this PR tried to address?

**Comment by t8m** [comment]
Are you still interested in having this feature included in OpenSSL? If so please rebase the PR to resolve conflicts.

Marking as inactive to be closed at the end of 3.4 dev barring further input.

**Comment by OscarAyoy** [comment]
> Are you still interested in having this feature included in OpenSSL? If so please rebase the PR to resolve conflicts.
> 
> Marking as inactive to be closed at the end of 3.4 dev barring further input.

I'll be honest -- I'd pretty much forgotten all about this PR as it's almost nine years old. If, as has been suggested in the thread, there's already similar functionality available maybe I could just remove this?

**Pull request closed without merging**
