### PR TITLE
Add reason codes with the correct offset for two alerts

### LINKED ISSUE #24300: `ERR_reason_error_string()` returns `NULL` for `no_application_protocol` alert
Hello all,

OpenSSL 3.0 doesn't correctly report a reason string when handling the `no_application_protocol` alert; instead, `ERR_reason_error_string()` returns `NULL`. `ERR_print_errors()` and friends are similarly unhelpful:
```
E01FFFF7FFFF0000:error:0A000460:SSL routines:ssl3_read_bytes:reason(1120):ssl/record/rec_layer_s3.c:1590:SSL alert number 120
```
From inspection, later versions of OpenSSL 3.x also have this issue, but I haven't tested with all of them.

-------
To my eyes, it looks like the lookup machinery expects the reason code to be 1120 (that is, `SSL_AD_REASON_OFFSET + TLS1_AD_NO_APPLICATION_PROTOCOL`), but `SSL_R_NO_APPLICATION_PROTOCOL` is [defined to be 235](https://github.com/openssl/openssl/blob/f945986/include/openssl/sslerr.h#L187).

I'm suspicious that the `unknown_psk_identity` alert may have the same issue, since `SSL_R_PSK_IDENTITY_NOT_FOUND` is defined as 223 and not 1115.

Here is a sample patch. If this looks close to right, I can open a pull request, but I'm unsure what to do with the existing `SSL_R_NO_APPLICATION_PROTOCOL` code.

```patch
diff --git a/crypto/err/openssl.ec b/crypto/err/openssl.ec
index 3612c195f0..3d395a92a4 100644
--- a/crypto/err/openssl.ec
+++ b/crypto/err/openssl.ec
@@ -78,4 +78,4 @@ R SSL_R_TLSV1_BAD_CERTIFICATE_STATUS_RESPONSE   1113
 R SSL_R_TLSV1_BAD_CERTIFICATE_HASH_VALUE        1114
 R TLS1_AD_UNKNOWN_PSK_IDENTITY                  1115
 R SSL_R_TLSV13_ALERT_CERTIFICATE_REQUIRED       1116
-R TLS1_AD_NO_APPLICATION_PROTOCOL               1120
+R SSL_R_TLSV1_ALERT_NO_APPLICATION_PROTOCOL     1120
diff --git a/include/openssl/sslerr.h b/include/openssl/sslerr.h
index b156fc2ffd..7e37ef4f16 100644
--- a/include/openssl/sslerr.h
+++ b/include/openssl/sslerr.h
@@ -283,6 +283,7 @@
 # define SSL_R_TLSV1_ALERT_INAPPROPRIATE_FALLBACK         1086
 # define SSL_R_TLSV1_ALERT_INSUFFICIENT_SECURITY          1071
 # define SSL_R_TLSV1_ALERT_INTERNAL_ERROR                 1080
+# define SSL_R_TLSV1_ALERT_NO_APPLICATION_PROTOCOL        1120
 # define SSL_R_TLSV1_ALERT_NO_RENEGOTIATION               1100
 # define SSL_R_TLSV1_ALERT_PROTOCOL_VERSION               1070
 # define SSL_R_TLSV1_ALERT_RECORD_OVERFLOW                1022
diff --git a/ssl/ssl_err.c b/ssl/ssl_err.c
index 41898844ff..48ff9f0142 100644
--- a/ssl/ssl_err.c
+++ b/ssl/ssl_err.c
@@ -457,6 +457,8 @@ static const ERR_STRING_DATA SSL_str_reasons[] = {
     "tlsv1 alert insufficient security"},
     {ERR_PACK(ERR_LIB_SSL, 0, SSL_R_TLSV1_ALERT_INTERNAL_ERROR),
     "tlsv1 alert internal error"},
+    {ERR_PACK(ERR_LIB_SSL, 0, SSL_R_TLSV1_ALERT_NO_APPLICATION_PROTOCOL),
+    "no application protocol"},
     {ERR_PACK(ERR_LIB_SSL, 0, SSL_R_TLSV1_ALERT_NO_RENEGOTIATION),
     "tlsv1 alert no renegotiation"},
     {ERR_PACK(ERR_LIB_SSL, 0, SSL_R_TLSV1_ALERT_PROTOCOL_VERSION),
```

Thanks!

### PR DESCRIPTION
**Pull request by jchampio**
_note: this is currently based on branch `openssl-3.0`; see below_

Attempts to fix #24300. The current `SSL_R_NO_APPLICATION_PROTOCOL` value doesn't allow for a correct lookup of the reason string, so add a constant that is equal to `SSL_AD_REASON_OFFSET + TLS1_AD_NO_APPLICATION_PROTOCOL`. Do the same for `SSL_R_PSK_IDENTITY_NOT_FOUND`.

Here are my "open items" (edit: all answered [here](https://github.com/openssl/openssl/pull/24338#issuecomment-2096567836)):
1. I'm pretty sure `UNKNOWN_PSK_IDENTITY` is going to have the same bug.
1. I don't understand how this interacts with #19950, which removed both of the affected codes from the `master` branch entirely. (That's why I haven't forward-ported this yet.) Should I just add them back?
1. What's the best place to put a test for this? I see tests for `ExpectedServerAlert` during the ALPN exchange, but I don't see any tests for the error message itself.
1. What should be done with the existing `SSL_R_NO_APPLICATION_PROTOCOL` code? Does that constant need to remain for compatibility?

##### Checklist

- [ ] ~documentation is added or updated~
- [ ] ~tests are added or updated~

### CODE REVIEW

**Comment by nhorman** [comment]
can you rebase this on the master branch please?  We will apply tags to the PR to backport it appropriately

**Comment by t8m** [comment]
> _note: this is currently based on branch `openssl-3.0`; see below_
> 
> Attempts to fix #24300. The current `SSL_R_NO_APPLICATION_PROTOCOL` value doesn't allow for a correct lookup of the reason string, so add a constant that is equal to `SSL_AD_REASON_OFFSET + TLS1_AD_NO_APPLICATION_PROTOCOL`.
> 
> Here are my "open items":
> 
>     1. I'm pretty sure `UNKNOWN_PSK_IDENTITY` is going to have the same bug.

Yes, it looks like so.

>     2. I don't understand how this interacts with [Write SSL_R alerts to error state to keep updated strings #19950](https://github.com/openssl/openssl/pull/19950), which removed both of the affected codes from the `master` branch entirely. (That's why I haven't forward-ported this yet.) Should I just add them back?

Just add the codes back with the proper SSL_R_ name

>     3. What's the best place to put a test for this? I see tests for `ExpectedServerAlert` during the ALPN exchange, but I don't see any tests for the error message itself.

Hmm... that would be non-trivial. Perhaps we can allow this without a test case.

>     4. What should be done with the existing `SSL_R_NO_APPLICATION_PROTOCOL` code? Does that constant need to remain for compatibility?

Yes, just keep it unused.

**Comment by t8m** [comment]
> can you rebase this on the master branch please? We will apply tags to the PR to backport it appropriately

We would need a separate PR for 3.0/3.1 (which can be this PR) because of the changes on master/3.3/3.2 - please create a new PR that will be applied to these 3 branches.

**Comment by jchampio** [comment]
> > ```
> > 1. I'm pretty sure `UNKNOWN_PSK_IDENTITY` is going to have the same bug.
> > ```
> 
> Yes, it looks like so.

I took the liberty to add that one, too; if that's unhelpful I can split it back out or revert it.

> > ```
> > 4. What should be done with the existing `SSL_R_NO_APPLICATION_PROTOCOL` code? Does that constant need to remain for compatibility?
> > ```
> 
> Yes, just keep it unused.

For the record, it's still referenced on the server side. Same with `SSL_R_PSK_IDENTITY_NOT_FOUND`, both client and server.

> > can you rebase this on the master branch please? We will apply tags to the PR to backport it appropriately
> 
> We would need a separate PR for 3.0/3.1 (which can be this PR) because of the changes on master/3.3/3.2 - please create a new PR that will be applied to these 3 branches.

[Done!](https://github.com/openssl/openssl/pull/24351)

**Comment by jchampio** [comment]
(Oh, and I got `mkerr.pl` to kick in this time; hence the new copyright updates in the fixed files.)

**Review by t8m — APPROVED** [review]
As most of the changes are result of mkerr.pl. I am OK with CLA: trivial.

**Review by nhorman — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
@nhorman You are a committer, so can remove the committer `approval: review pending` label and mark the review as `approval: done`, right?

**Comment by t8m** [comment]
Waiting on #24351 to be merged to the master branch.

**Comment by t8m** [comment]
Merged to the 3.0 and 3.1 branches. Thank you for your contribution.

**Pull request closed without merging**
