### PR TITLE
Updating ifdefs to account for xlclang compiler frontend on AIX. The …

### PR DESCRIPTION
**Pull request by robmcgee-mag**
…fallback DEP works fine there.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by hlandau** [comment]
Thanks for the PR. This looks good, but you will need to sign an ICLA:

https://www.openssl.org/policies/cla.html

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I think this is withing the realms of a trivial commit.  If you agree, could you please add "CLA: trivial" to the commit message on a line by itself.  (git commit --amend, edit the message, git push -f).

**Comment by robmcgee-mag** [comment]
If that's okay with ye, I'll just add the trivial part for now.

**Comment by paulidale** [comment]
You'll need to rebase to get rid of the merge commit (we don't allow merge commits in the repository).
`get rebase master` ought to do it.

**Comment by robmcgee-mag** [comment]
That didn't seem to do anything. Sorry it's been nearly ten years since I last used git in a professional context. 😅 

```
$ git rebase master
Current branch master is up to date.
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by t8m** [comment]
Just drop the merge commit and squash the two previous commits - `git rebase -i master` should help.

**Comment by robmcgee-mag** [comment]
Sorry guys I'm making a mess of this, I blame Perforce for locking me into a walled garden the last few years.
I've just started over with a new pull request: https://github.com/openssl/openssl/pull/18892

**Pull request closed without merging**
