### PR TITLE
Add include of e_os2.h in quictestlib.c to allow symbol definition consistency.

### PR DESCRIPTION
**Pull request by rsbeckerca**
Fixes: #22178

Signed-of-by: Randall S. Becker <randall.becker@nexbridge.ca>

### CODE REVIEW

**Comment by rsbeckerca** [comment]
This should be applicable to other branches.

**Comment by rsbeckerca** [comment]
I have made this change NonStop-specific but I think it might apply to any c99 builds because the unspecified type, `timeval`, is rejected by the c99 compiler, not the platform. Please review and let me know if the include needs to move and what `ifdef` wrapping it otherwise needs.

**Comment by rsbeckerca** [comment]
This passed builds on our platform.

**Review by paulidale — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM

**Review by mattcaswell — CHANGES_REQUESTED** [review]
We have plenty of code already that uses struct timeval which, as far as I know has compiled just fine on NonStop. I don't think this is the correct fix. I have an alternative suggestion in #22183.

**Comment by rsbeckerca** [comment]
I originally called this "Move" instead of "Add" because it was in comparison to the proposed change by @mattcaswell. This just moves where the `#include` is done compared to commit b01151dfbd107bce6e88de64acc541178e520fa0 to make c99 happy.

**Comment by rsbeckerca** [comment]
FYI: This change, commit [71c7128](https://github.com/openssl/openssl/pull/22179/commits/71c7128e3909c3db86c772ae22efc791d5aee559), did pass build/test on NonStop with c99.

**Review by paulidale — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed.

**Pull request closed without merging**
