### PR TITLE
ignore various files in commit checker

### PR DESCRIPTION
**Pull request by nhorman**
*.cnf
*.conf
*.md
*.info
Configure

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
Would be more safe if the regexps had a trailing `$`
such that they match only at file name end and Configure also had a leading `^`.

**Comment by nhorman** [comment]
I'm actually starting to wonder if we shouldn't just replace the list entirely with a whitelist of "*\.c[.in]*$ | *\.h[.in]*$"

**Comment by DDvO** [comment]
> I'm actually starting to wonder if we shouldn't just replace the list entirely with a whitelist of "_.c[.in]_$ | _.h[.in]_$"

Even better.
Yet more correct and lean regexp:  `"\.[ch](\.in)?$"`

**Comment by nhorman** [comment]
I'll make that change separately since the timers about to expire here

**Comment by nhorman** [comment]
merged to master

**Pull request closed without merging**
