### PR TITLE
1.1.1 beta1 release commits

### PR DESCRIPTION
**Pull request by mattcaswell**

### CODE REVIEW

**Comment by mattcaswell** [comment]
Should I create the branch before or after I merge these?

**Comment by levitte** [comment]
Before.  I think 1.1.1-pre3 should be on that branch, not on master.

**Comment by richsalz** [comment]
Can we keep master frozen for awhile and then rebase all the fixes onto it?

**Comment by mattcaswell** [comment]
> Can we keep master frozen for awhile and then rebase all the fixes onto it?

If we were going to do that then it would be better not to create the branch at all!! It's a bit late in the day for that!!

**Comment by levitte** [comment]
Yeah, I don't think that's a good idea...

**Comment by richsalz** [comment]
I am curious why you don't think it's a good idea, @levitte.  I also don't see why keeping master frozen requires doing anything other than what we're aleady doing.

**Comment by mattcaswell** [comment]
I'm holding the release until this is resolved (I am literally sat here about to push the branch creation).

**Comment by levitte** [comment]
1. @mattcaswell is entirely correct, if we freeze master "for a while", there's really no point in creating a 1.1.1 branch at all.  Our published plan, though, is to create this branch.
2. There is work going on that is for post-1.1.1 that has been on pause for a while (because we've obviously worked only on 1.1.1 stuff), you want to prolongue that further?

Of course I can see where you're going, you want to make sure that everything we do is about 1.1.1, no "distractions" such as post-1.1.1 stuff.  I'm just not at all sure this is the right path to take.

**Comment by mattcaswell** [comment]
If there is any doubt about whether we should create the branch then we can decouple it from the release. We can create the branch at any time - it doesn't need to be at the same time as a release. We could continue with the release (without creating the branch), and then take the discussion to the project list. If the consensus view is that the branch should still be created then we can do it immediately.

**Comment by levitte** [comment]
Also, I react at the vagueness of "for a while".

**Comment by levitte** [comment]
> We can create the branch at any time - it doesn't need to be at the same time as a release.

That's a good point, the "starting point" of the branch is really not that important so long as the content of 1.1.1 branch doesn't differ from the master branch...  which actually makes your initial question kinda moot ;-)
(this holds at most until `include/openssl/opensslv.h` becomes different in the 1.1.1 and master branches)

**Comment by levitte** [comment]
... this actually begs the question when it's time to change the master version to `1.1.2-dev`...  but that doesn't have to be answered now

**Comment by richsalz** [comment]
My point is that we will have two months of fixes going that must be picked and tested going to two branches, and I don't see the reason for that. I would prefer we kept working off master, and kept feature submits out of it, but just keeping master locked for now seems simpler. 

And yes, I want to keep us completely focused *as a project* on getting this release out.  As a team, we should be working on nothing else.  Keep it in your own branch, or share it if necessary.

I am disappointed that we extended the deadline and still had to squeak some third-party PR's in at the last minute. We don't seem to have discipline that we need.

I used informal words, and saying you disagree because it's vague is kinda silly.  But if you prefer, I want to keep master frozen until we are much closer to releasing 1.1.1  Maybe up until the day that we actually release 1.1.1; let the OMC decide.

Branch and proceed with the release.  Let's have a discusssion about keeping master frozen, if we need to have that discussion. And until we have it, don't unfreeze the branch. We can always keep master effectively frozen by putting -1 on all feature PR's.  And during that time, everyone will have double the amount of work.

**Comment by levitte** [comment]
I think that at this point, I can be satisfied with postponing branch creation and otherwise carry on with the release.

**Comment by mattcaswell** [comment]
> I think that at this point, I can be satisfied with postponing branch creation and otherwise carry on with the release.

Ok. @richsalz is that a good enough compromise for now, and we can continue the discussion on openssl-project?

**Comment by levitte** [comment]
> And during that time, everyone will have double the amount of work.

I dunno about you, but I think coding and reviewing is the larger part of the job.  Cherry-picking is small stuff in comparison...

**Comment by levitte** [comment]
> ... and we can continue the discussion on openssl-project?

Good idea.

**Comment by richsalz** [comment]
Yes I am fine with that, thanks.
As for the relative amount of work, it's also the *perception* and *discipline* that bothers me.  The team should not be working on anything other than 1.1.1 from now until it's done.

**Comment by mattcaswell** [comment]
Ok, I will continue on that basis.

**Pull request merged**
