### PR TITLE
Add support sm3 sm4 for zxc zxd

### PR DESCRIPTION
**Pull request by bubble932**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by InfoHunter** [comment]
Since you opened a new PR, why don't you squash all the commits into one incidentally?

**Comment by InfoHunter** [comment]
Besides, you still have the conflicts in your patch unsolved, I checked you patch and find the conflicts are something as follows:

```
<<<<<<< HEAD
#  define EVP_CIPHER_block_size_ECB       AES_BLOCK_SIZE
#  define EVP_CIPHER_block_size_CBC       AES_BLOCK_SIZE
#  define EVP_CIPHER_block_size_OFB       1
#  define EVP_CIPHER_block_size_CFB       1
#  define EVP_CIPHER_block_size_CTR       1
=======
static int
gmi_sm4_ecb_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out_arg,
                   const unsigned char *in_arg, size_t nbytes)
{
    struct gmi_cipher_data *cdata = ALIGNED_CIPHER_DATA_GMI(ctx);
    gmi_sm4_encrypt(out_arg, in_arg, cdata, nbytes);
    return 1;
}
```

You need to resolve this in your local git repo and then have a `git push -f ` to force-update your patch.

**Comment by InfoHunter** [comment]
When I pulled your branch from your Github repo into master, I encountered the conflict, this is exactly the same problem in your last PR (the one you closed):

```
$ git pull https://github.com/bubble932/openssl.git add-support-sm3-sm4-for-zxc-zxd
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Total 17 (delta 9), reused 9 (delta 9), pack-reused 8
Unpacking objects: 100% (17/17), done.
From https://github.com/bubble932/openssl
 * branch                  add-support-sm3-sm4-for-zxc-zxd -> FETCH_HEAD
Auto-merging engines/e_padlock.c
CONFLICT (content): Merge conflict in engines/e_padlock.c
```

**Comment by InfoHunter** [comment]
Another thing is that you need to use `git rebase` to sync your branch with master instead of `merge` to avoid introducing the *Merge...* (like eb0ae04) commits into the PR...

**Comment by bubble932** [comment]
> Another thing is that you need to use `git rebase` to sync your branch with master instead of `merge` to avoid introducing the _Merge..._ (like [eb0ae04](https://github.com/openssl/openssl/commit/eb0ae0497c9750be0dac3f07f199eae0f33f41e2)) commits into the PR...

Thanks. I'll retry.

> <<<<<<< HEAD

@InfoHunter Thanks for your help. But 
<<<<<<< HEAD
#  define EVP_CIPHER_block_size_ECB       AES_BLOCK_SIZE
#  define EVP_CIPHER_block_size_CBC       AES_BLOCK_SIZE
#  define EVP_CIPHER_block_size_OFB       1
#  define EVP_CIPHER_block_size_CFB       1
#  define EVP_CIPHER_block_size_CTR       1
=======

are the same codes between the origin e_padlock.c file and my local new e_padlock.c file.

**Comment by InfoHunter** [comment]
I suggest you to have a new clone of OpenSSL and apply your current patch to the master branch of that new OpenSSL repo in your local environment, and you will see the conflicts.

**Comment by bubble932** [comment]
> I suggest you to have a new clone of OpenSSL and apply your current patch to the master branch of that new OpenSSL repo in your local environment, and you will see the conflicts.

when I git clone https://github.com/openssl/openssl.git， and in this local repo：
yunshen@sec-share:~/workspace/openssl/bubble932_openssl/openssl_openssl/openssl$ git apply --stat 0109-Support-zxc-zxd-s-SM3-SM4-Instructions.patch
 engines/asm/e_padlock-x86.pl    |  132 +++++++++
 engines/asm/e_padlock-x86_64.pl |  109 ++++++++
 engines/e_padlock.c             |  543 ++++++++++++++++++++++++++++++++++++++-
 engines/e_zx.h                  |   57 ++++
 4 files changed, 832 insertions(+), 9 deletions(-)
yunshen@sec-share:~/workspace/openssl/bubble932_openssl/openssl_openssl/openssl$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        0001-modify-some-indents.patch
        0109-Support-zxc-zxd-s-SM3-SM4-Instructions.patch
        0109-modify-indents.patch
        0110-modify-indents.patch
        0110-modify-some-indents.patch
        0111-modify-some-indents.patch

nothing added to commit but untracked files present (use "git add" to track)

I guess，the root cause is that the codes in https://github.com/openssl/openssl.git are different from the codes in https://github.com/bubble932/openssl.git.

But should I do? @InfoHunter

**Comment by InfoHunter** [comment]
You need to make sure the master branch of https://github.com/bubble932/openssl.git is always the same to https://github.com/openssl/openssl.git, and then your local git repo (which usually should be cloned from https://github.com/bubble932/openssl.git) is the same to https://github.com/bubble932/openssl.git

**Pull request closed without merging**
