### PR TITLE
Remove unit-test config param

### PR DESCRIPTION
**Pull request by richsalz**
Unused code.

### CODE REVIEW

**Comment by snhenson** [comment]
Even though this is unused it's deleting a global function which is technically a binary compatibility issue. What do people thing: is it OK for this case?

**Comment by richsalz** [comment]
Yes it is.  On the other hand, it's one that is not enabled by default.

**Comment by dot-asm** [comment]
This is somewhat asymmetric. In sense that [given context of previous internal discussion] you're effectively seeking only for positive feedback. [Yes, it means that I don't have any positive feedback here.]

**Comment by richsalz** [comment]
well, all code reviews (if it goes in) are positive feedback, no?
and negative feedback is expressed via -1.

**Comment by paulidale** [comment]
I don't see a problem.  A disabled by default function that I can't imagine calling is being removed (am I misguided?).  Yes, it is a binary compatible change.  If that's a problem, what about replacing it with a stub that does nothing for the moment and removing it fully for 1.2?

The build failure looks unrelated.

**Comment by mattcaswell** [comment]
We should not be removing an option to Configure in 1.1.1. That could break stuff (e.g. people explicitly listing no-unit-test in scripts - even though its redundant). Possibly having a do nothing stub might be ok. I'm not sure.

**Comment by richsalz** [comment]
Has anyone been able to config with, or without, the unit-tests option?
The code isn't used.
@openssl, please decide if you'll ever move this forward or just close it.

**Comment by richsalz** [comment]
I am withdrawing this, as the next release pledges to maintain compatibility.

**Pull request closed without merging**
