### PR TITLE
QUIC: Fix multistream script 19 stochastic test failure

### PR DESCRIPTION
**Pull request by hlandau**
Urgent due to CI breakage on FreeBSD.

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Looks fine. Agree urgent.

But, out of interest - why does this fix it?

**Comment by hlandau** [comment]
*#!$!. I am just outright dumping this line, it is not even needed because the thing it is supposed to be testing is tested perfectly fine by script 17.

```diff
-    OP_CHECK                (check_key_update_ge, 4)
```

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
OK with urgent. @mattcaswell please reconfirm.

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Agree urgent

**Comment by hlandau** [comment]
Merged to master. Thanks.

**Pull request closed without merging**
