### PR TITLE
Address issue #10600 by adding 3 APIs

### PR DESCRIPTION
**Pull request by InfoHunter**
ASN1_TIME_dup and related APIs are added in this commit to address #10600.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Does this need a CHANGES entry?
Also I dont know the rules about what the commit message has to look like - Does it actually have to say Fixes #XXXXX

**Comment by InfoHunter** [comment]
Not sure if this needs a line in CHANGES. But it seems it's good to say Fixex #xxxx in the commit message body I think - I have seen such lines before in other commits and I assume that will close the original issue automatically?

**Comment by t8m** [comment]
In addition to the Fixes #10600 line the commit message should be amended to be more descriptive. Using GH issue number in the subject line of the commit message is not convenient when quickly going through the shortlog of the git, so please consider using something 'Add duplication apis to ASN1_TIME and related types'.

**Comment by InfoHunter** [comment]
Commit message changed

**Comment by t8m** [comment]
As the only change in force-push was the commit message, I do not think it needs re-reviews and restart of the 24 hour waiting period.

**Comment by InfoHunter** [comment]
Force-pushed to resolve the conflict in util/libcrypto.num

**Comment by InfoHunter** [comment]
I still assume that this could be merged without re-review or re-approval?

**Comment by mspncp** [comment]
Fixing a conflict in libcrypto.num is not a substantial change which requires reapproval, resetting the timer.

**Comment by InfoHunter** [comment]
No problem, going to merge.

**Comment by InfoHunter** [comment]
Pushed to master as fe4309b0de64502398116f648cc7f2068e1a1537

**Pull request closed without merging**
