### PR TITLE
Configure: untabify indentation

### PR DESCRIPTION
**Pull request by mspncp**
The indentation in the Configure file is currently very strange when
viewed in an editor with a tab width of four spaces, because it has
mixed tab-and-whitespace indentation, which was apparently done with
a tab width of eight spaces.

This commit converts all tabs to spaces in a reproducible way using
emacs and the following lisp function.
```lisp
    (defun ossl-whitespace-cleanup ()
      "Run whitespace cleanup on current buffer"
      (interactive)
      (set-variable 'tab-width 8)
      (set-variable 'indent-tabs-mode nil)
      (whitespace-cleanup))
```
To verify that there are only whitespace changes, use
```
   git show --ignore-space-change  <this commit>
```

To make future merging from `master` to `1.1.1` feasible, the same
cleanup needs to be done synchonously on the OpenSSL_1_1_1-stable
branch. I'll create the pull request for it, as soon as I get
your consent.

### CODE REVIEW

**Comment by mspncp** [comment]
And just in case you are wondering: this is a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests).

**Comment by levitte** [comment]
The whole style of Configure is sort of...  antique, as it mimics the old pre-2015 code style.  The perl stuff wa never touched when we did the sweeping source style change, amongst others because we hadn't quite figured out a perl style.

I've had it in the back of my mind that we should reformat Configure and other perl scripts to conform with some style guide, and if it was up to me, I would just go with the [default perl style](https://perldoc.perl.org/perlstyle.html), something that perltidy generates by default.

**Comment by mspncp** [comment]
In this case I think it's best if you do the job yourself. So just consider this pull request a little étude of mine. You can close it or keep it open as a reminder, as you prefer.

**Comment by paulidale** [comment]
I use the `expand(1)` utility for this kind of change.

I'd support a full reformatting but would still approve this PR in the meantime.

**Comment by mspncp** [comment]
> I use the expand(1) utility for this kind of change.

Thanks @paulidale for the hint. Since I usually fix whitespace issues interactively in Emacs (the lisp function above was only for documentation purpose), I never had the need for such a tool yet, but it's good to know about it.

> I'd support a full reformatting but would still approve this PR in the meantime.

This pull improves the readability of the configuration file for people who use a different tab-width (e.g. 4). But meanwhile I'm not sure anymore whether it would have been better to tabify the indentation instead of untabifying it. So IMHO there are three possible ways to proceed with this pull request:

- untabify the entire file using tab-width = 8
- tabify the entire file using tab-width = 8
- close this pull request and wait for a proper reformatting

Whether a preliminary reformatting makes sense, depends on Richard's plans and time schedule for a reformatting of the perl codebase. So @levitte just let me know which variant you prefer.


**Note**

Looking for the preferred perl indentation style, I was surprised to find out that [perlstyle](https://perldoc.perl.org/perlstyle.html) does not seem to favour tabs or spaces, it only talks about 4-column indent. Searching further, I found some interesting links which I'd like to share FWIW. But I'll leave it to Richard and the other Perl experts to figure out their favourite style.

- [Perl Best Practices (by Damian Conway)](https://en.wikipedia.org/wiki/Perl_Best_Practices)

- [Ten Essential Development Practices, Chapter 6. - Agree Upon a Coherent Layout Style and Automate It with perltidy (Jul 14, 2005 by Damian Conway)](https://www.perl.com/pub/2005/07/14/bestpractices.html/)

- [perltidy manual page](http://perltidy.sourceforge.net/perltidy.html)

- [Perl::Critic](https://metacpan.org/pod/Perl::Critic) and [Perl::Critic::Policy::CodeLayout::RequireTidyCode](https://metacpan.org/pod/Perl::Critic::Policy::CodeLayout::RequireTidyCode)

**Comment by levitte** [comment]
Re spaces vs tabs, I'll note that perltidy defaults to spaces only.

**Comment by paulidale** [comment]
At the risk of starting a war: my experience is that tabs often cause problems eventually.

For reference, the `unexpand(1)` utility puts tabs back.

**Comment by levitte** [comment]
Our C code style stipulates spaces, so that's not very controversial...

**Comment by mspncp** [comment]
Ok @levitte and @paulidale, I take your answers as an indication that you might accept an untabifying of the Configure file. So I rebased it to get rid of the AppVeyor failure and removed the DRAFT state. It's still up to you whether you take it or discard it, I won't make a fuzz about it.


### Notes on perltidy

I also did some experiments using `perltidy` with default settings. While in general it produces nice results, for the Configure file there is one notable exception: the list of disablables is formatted using two columns, which is somewhat unpractical.

**Before reformatting**

```perl
my @disablables = (
    "ktls",
    "afalgeng",
    "aria",
    "asan",
    "asm",
    "async",
    #...
    "weak-ssl-ciphers",
    "zlib",
    "zlib-dynamic",
    );
foreach my $proto ((@tls, @dtls))
	{
	push(@disablables, $proto);
	push(@disablables, "$proto-method") unless $proto eq "tls1_3";
	}
```

**After reformatting**

```perl
my @disablables = (
    "ktls",                "afalgeng",
    "aria",                "asan",
    "asm",                 "async",
	#...
    "weak-ssl-ciphers",    "zlib",
    "zlib-dynamic",
);
foreach my $proto ( ( @tls, @dtls ) ) {
    push( @disablables, $proto );
    push( @disablables, "$proto-method" ) unless $proto eq "tls1_3";
}
```

**Found a bug?**

Also, it seems like I encountered a bug in perltidy: three lines are not indented properly using spaces.

```
~/src/openssl$ perltidy Configure
~/src/openssl$ grep -P '^\t+' Configure.tdy | sed 's/\t/\\t/g'
\t    foreach (sort keys %{$config{perlenv}}) {
\t        print '    ',$_,' = ',($config{perlenv}->{$_} || ""),"\n";
\t    }
```

(I used the original version from master for this. If I run perltidy on my untabified version, the tabs disappear.)

**Comment by mspncp** [comment]
**Editorial note:** I added the [1.1.1] label to indicate my intent to do an identical reformatting on the 1.1.1, to facilitate future merging from master to 1.1.1.  I won't do a `git merge`, but apply the same emacs function above instead. Please let me know whether you require a separate pull request for that, or whether I can just refer to this one.

**Comment by levitte** [comment]
If you make a separate effort for 1.1.1, you should make it a separate PR, so it can be reviewed as well.

**Comment by levitte** [comment]
Regarding perltidy quirks...  there are others.  Something I've noticed is an ...  interesting aligned of conditionals:

``` perl
    elsif ( ( $predefined_C{__GNUC__} // -1 ) >= 3
        && !( $predefined_C{__APPLE_CC__} && !$predefined_C{__clang__} ) )
```

And sure, that probably looks nice, but it's not the easiest to maintain such a style in an editor, no matter what indentation assistance being present.

**Comment by mspncp** [comment]
It turned out that a simple `untabify` (with tab-width 8) produced better results than `whitespace-cleanup`, because the latter did not convert tabs in comments and after non-comment chars. So following @paulidale's hint, I simply used `expand(1)` with default settings.

PR for 1.1.1 follows immediately...

**Comment by mspncp** [comment]
see #8512.

**Comment by mspncp** [comment]
Job https://ci.appveyor.com/project/openssl/openssl/builds/23151914/job/a9xqvo8qlj1dabl8/messages was killed after 60 minutes. I have no idea what caused the problem.

**Comment by mspncp** [comment]
Close and reopen to kick the CI's once more.

**Comment by mspncp** [comment]
Merged, thanks!

**Pull request closed without merging**
