### PR TITLE
doc: replace the private exponent d with the public exponent e in the RSA public key parameters

### PR DESCRIPTION
**Pull request by jeljeli**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Approved. This looks like a trivial change to me that should not require a CLA. @jeljeli do you agree this is trivial? If so please update the commit description to add the line "CLA: trivial" (as a line on its own)

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
I would be OK with CLA: trivial if the commit message is amended as well.

**Comment by t8m** [comment]
BTW, you could also shorten the first line of the commit message a little and perhaps add longer description into the message body.

**Review by t8m — APPROVED** [review]
OK with CLA trivial

**Review by paulidale — APPROVED** [review]
Agreed, trivial.

**Comment by paulidale** [comment]
Merged, thanks for the contribution.

**Pull request closed without merging**
