### PR TITLE
[test][15-test_genec] Improve EC tests with genpkey

### PR DESCRIPTION
**Pull request by romen**
> Test separately EC parameters and EC key generation.
> 
> For some curves we have had cases in which generating the parameters
> under certain conditions failed, while generating and serializing a key
> under the same conditions did not.
> See <https://github.com/openssl/openssl/issues/12306> for more details.

This follows up on #12080 (`master`) and #12085 (`1.1.1`, merging is not trivial due to the TODO annotations required in `master` until #12102 is fixed, a separate PR will follow).

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by romen** [comment]
Rebased on top of #12313 and #12305 .

Individually the above PRs fail the tests (intentionally), because they need the changes to the tests included in this PR.

**Comment by romen** [comment]
@Ddvo I see Travis already has some red crosses which seem related to the cmp cli tests failing again with ubsan, can you look into it?

**Comment by romen** [comment]
> @DDvO I see Travis already has some red crosses which seem related to the cmp cli tests failing again with ubsan, can you look into it?

The problems seem to be with both `ubsan` and `msan`.

- https://travis-ci.com/github/openssl/openssl/jobs/355619805
- https://travis-ci.com/github/openssl/openssl/jobs/355619806

**Comment by romen** [comment]
The other 2 errors are timeouts, I just restarted those jobs to see if kicking the container helps

**Comment by DDvO** [comment]
> > @DDvO I see Travis already has some red crosses which seem related to the cmp cli tests failing again with ubsan, can you look into it?
> 
> The problems seem to be with both `ubsan` and `msan`.
> 
>     * https://travis-ci.com/github/openssl/openssl/jobs/355619805
> 
>     * https://travis-ci.com/github/openssl/openssl/jobs/355619806

These issues are duplicates of issue that @mattcaswell for the most part already solved #12275
yet he has paused pursuing that for a couple of days.

If you cherry-pick his two commits and also do the following patch I proposed there:
```
diff --git a/test/recipes/81-test_cmp_cli.t b/test/recipes/81-test_cmp_cli.t
index 8ddb3c2daf..98833e04aa 100644
--- a/test/recipes/81-test_cmp_cli.t
+++ b/test/recipes/81-test_cmp_cli.t
@@ -14,7 +14,7 @@ use warnings;
 use POSIX;
 use File::Spec::Functions qw/catfile/;
 use File::Compare qw/compare_text/;
-use OpenSSL::Test qw/:DEFAULT with data_file data_dir bldtop_dir/;
+use OpenSSL::Test qw/:DEFAULT with data_file data_dir bldtop_dir bldtop_file/;
 use OpenSSL::Test::Utils;
 use Data::Dumper; # for debugging purposes only
 
@@ -24,8 +24,10 @@ plan skip_all => "These tests are not supported in a no-cmp build"
     if disabled("cmp");
 plan skip_all => "These tests are not supported in a no-ec build"
     if disabled("ec");
+open(CONFIG, bldtop_file("configdata.pm"));
 plan skip_all => "These tests are not supported in a fuzz build"
-    if !disabled("fuzz-libfuzzer") || !disabled("fuzz-afl");
+    if (grep { /-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION/ } <CONFIG>);
+close CONFIG;
 plan skip_all => "Tests involving server not available on Windows or VMS"
     if $^O =~ /^(VMS|MSWin32)$/;
 ```

those test failures should be gone.

**Comment by DDvO** [comment]
Thanks again @richsalz for the hint on decting `-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` which you gave very I asked for help about that in https://github.com/openssl/openssl/pull/12275#issuecomment-651226278.

**Comment by romen** [comment]
> I'm assuming I'm just supposed to be reviewing the test changes right? The other changes are from the other PRs? On that assumption this looks good.

Yes @mattcaswell, the commits prefixed with drop are from the other PRs!

**Comment by romen** [comment]
Merged to `master` as:

- 1c9761d0b547d2d135037d215cd16feb4d0b698c `[test][15-test_genec] Improve EC tests with genpkey`


Thanks!

**Pull request closed without merging**
