### PR TITLE
Add SM3/SM4 algorithms to openssl command-line tool

### PR DESCRIPTION
**Pull request by ronaldtse**
This adds SM3 and SM4 (and its various modes) to the `openssl` command line tool.

I have also replace the remaining "tabs" in the "digest" section of `apps/progs.pl` with spaces following convention used in the file.

There seem to be other algorithms missing as well in `apps/progs.pl`. Is the preference to add those remaining ones to this file, or was it the intention to keep them separate?

cc: @richsalz @levitte @paulidale @InfoHunter

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @t-j-h !

**Comment by levitte** [comment]
Merged.  6df34091bac6f82b7d9553dc857123b2bd478c22

**Comment by levitte** [comment]
Merged.  6df34091bac6f82b7d9553dc857123b2bd478c22

**Comment by ronaldtse** [comment]
Thank you @levitte !

**Pull request closed without merging**
