### PR TITLE
Fix the return type of felem_is_zero_int which should be int

### LINKED ISSUE #4413: Suspicious return type
ec_GFp_nistp_points_make_affine_internal(...) accepts a function pointer which has a suspicious type (ecp_nistputil.c):

`int (*felem_is_zero) (const void *in)`

The return type is "int", but one of the assumed values of the function pointer is felem_is_zero_int(...) from ecp_nistp224.c, which returns "limb" (uint64_t).

This shouldn't result in an accidental register clobber on the standard set of x86/ARM calling conventions (RAX, EAX/EDX, and r0-r4 are generally not preserved across function calls). This may be an issue if some other calling convention is in use.

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Should be merged to all branches.

Fixes #4413

### CODE REVIEW

**Comment by dot-asm** [comment]
Ready label is removed because of possible follow-up, see #4413.

**Comment by dot-asm** [comment]
Now we wait for CIs...

**Comment by dot-asm** [comment]
Actually waiting for CIs makes no sense. Because the code in question is exercised only in extended tests. So for this reason amend last commit [optionally squash it?], add `[extended tests]` to commit message and force-push it, please...

**Comment by bernd-edlinger** [comment]
okay, here you are.

**Comment by bernd-edlinger** [comment]
Merged, thanks!

**Pull request closed without merging**
