### PR TITLE
Fix line continuation check in config parser

### LINKED ISSUE #8038: NCONF_load fails when config file has a "\" at the wrong place
We encountered a strange error when we tried to sign a certificate using the openssl cli with a very long custom extension (basically a json string encoded as an UTF8 string).
We included the extension inside the configuration file like documented here https://www.openssl.org/docs/man1.1.0/apps/x509v3_config.html.

example:
```
[req_extensions]
1.3.6.1.4.1.99999.3.100.10.10=ASN1:UTF8String:"[{\"licenseType\":\"rent\",\"dateStart\":\"2017-05-28T00:00:00+00:00\",\"dateEnd\":\"2020-02-29T00:00:00+00:00\",\"isOem\":true,\"isBrandable\":true,\"comment\":\"some fillup to reach more than 510 characters in one line to fool openssls unescape reader.some fillup to reach more than 510 characters in one line to fool openssls unescape reader.some fillup to reach more than 510 characters in one line to fool openssls unescape reader.123456789\",\"multiTenancy\":true}]"
```

When loading this configuration file openssl strips the last backslash which then results in some corrupt json.

During debugging we found the responsible code for this behavior in https://github.com/openssl/openssl/blob/master/crypto/conf/conf_def.c#L295
Which looks quite strange for me. Why would you need to strip some escaping characters when reading a file in parts?

Hope this was clear enough, if not feel free to ask for more information.

### PR DESCRIPTION
**Pull request by erbsland-dev**
Fixes #8038: Previously, line continuation logic did not account for the 'again' flag, which could cause incorrect removal of a backslash character in the middle of a line. This fix ensures that line continuation is correctly handled only when 'again' is false, thus improving the reliability of the configuration parser.

- [x] tests are added or updated

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
@erbsland-dev How hard would it be to add a testcase?

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
@nhorman please reconfirm

**Comment by nhorman** [comment]
Ack, approval holds

**Comment by t8m** [comment]
Merged to all the active branches. Thank you for your contribution.

**Pull request closed without merging**
