### PR TITLE
Adding ccache action to ci.yml jobs

### PR DESCRIPTION
**Pull request by nhorman**
Improve build times by trading off some artifact storage to enable c caching for our pull request ci jobs

### CODE REVIEW

**Comment by paulidale** [comment]
How much time does this save?

**Comment by nhorman** [comment]
Early estimates say about two minutes, but I need to convert the other builds to get a better average

**Comment by paulidale** [comment]
That's quite significant.  I know ccache makes a big difference here.

**Comment by nhorman** [comment]
yeah, this is currently just some experimentation in pursuit of 
https://github.com/openssl/project/issues/853

The goals as I understand it are:
1) Accelerate build time 
2) Make build time results visible on a PR quickly, ahead of any unit test results

**Comment by t8m** [comment]
Instead of splitting the basic_gcc/basic_clang tests with uploading the artifacts I would just make the basic_gcc job into a smoke test with just a few tests running. And put all long-running tests as conditional on the basic_gcc test passing. 

Similarly for Windows CI - the minimal test would be a smoke test and all others would start only after the minimal is passing. Or you could split the minimal test into a build and test phases. There it would make sense because it already takes 10 minutes to run it.

You would have to also select one of the cross-compile jobs and runchecker jobs as smoke tests as well.

This would save resources only for build-time-broken changes but IMO it would be worth it anyway.

I do not think we can really save resources for the non-broken cases - that would require manual action to trigger the additional jobs.

**Comment by quarckster** [comment]
Sorry for bumping of this closed PR, I discovered that using `ccache` and `sccache` won't help. I tried it in hope to speed up building on Windows but ccache didn't hit the cache at all. In the ccache debug log I found

```
[2025-04-17T04:36:25.122349 1600 ] Compiler option /Zi is unsupported
[2025-04-17T04:36:25.122370 1600 ] Failed; falling back to running the real compiler
```

And here are some ccache sccache threads:

- https://github.com/ccache/ccache/issues/1040
- https://github.com/mozilla/sccache/issues/956

**Pull request closed without merging**
