### PR TITLE
Add missing getters and setters for the X509_STORE_CTX and X509_STORE functions

### PR DESCRIPTION
**Pull request by levitte**
Partly fixes [RT#4602](https://rt.openssl.org/Ticket/Display.html?id=4602)

_login on RT with user 'guest' and password 'guest'_

### CODE REVIEW

**Comment by richsalz** [comment]
need docs....

**Comment by levitte** [comment]
Yes, it does.  Also, I think I might be over shooting, as I'm unsure there should be setters for the majority of the `X509_STORE_CTX` function pointers...

**Comment by richsalz** [comment]
perhaps viktor or drh has views?

**Comment by levitte** [comment]
So I went with the idea that implementation of X509_STORE functions should be done on X509_STORE, that the copies in X509_STORE_CTX are just that...  a cache.

While I was at it, I corrected a couple of small inconsistencies.

**Comment by levitte** [comment]
Please also have a look at #1339

**Comment by levitte** [comment]
Documentation added, commits squashed, all rebased on top of a fresh master checkout.

**Comment by richsalz** [comment]
+1

**Comment by levitte** [comment]
Merged, thanks for the review

**Pull request closed without merging**
