### PR TITLE
The param to string optimisation in #17325 was merged to 3.0 by mistake, revert it.

### PR DESCRIPTION
**Pull request by paulidale**
Reverting the relevant commits.

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
Also marked urgent as this should not have gone into 3.0 - so removing it rapidly is appropriate IMHO.

**Comment by paulidale** [comment]
Wasn't sure about the urgent, but will merge now.

**Comment by paulidale** [comment]
Merged to 3.0, thanks for the prompt review.

**Comment by bernd-edlinger** [comment]
@paulidale could you please have a look at issue #23809
it looks like one of the reverted commits is able to fix it, do you agree?

**Pull request closed without merging**
