### PR TITLE
Patch for copy and copy-if-different scripts with whitespace problem #1023 - CLA: trivial

### PR DESCRIPTION
**Pull request by simon-p-r**
Small "CLA: trivial" fix related to #1023

### CODE REVIEW

**Comment by InfoHunter** [comment]
You may need to add `CLA: trivial` in your commit message or sign a CLA at: https://www.openssl.org/policies/cla.html, to avoid cla-check failure.

**Comment by richsalz** [comment]
Simon, we need you to put "CLA: trivial" in your commit text (and push -f) or sign our CLA.
I agree this is trivial.
Ping @levitte

**Comment by simon-p-r** [comment]
@richsalz is that ok?

**Comment by InfoHunter** [comment]
Seems you should put the `CLA: trivial` line into the commit text, not the commit title:

```
patch for copy and copy-if-different whitespace problem

CLA: trivial 
```

**Comment by richsalz** [comment]
What @InfoHunter said.

**Comment by richsalz** [comment]
commit b832656 in 1.0.2-stable, thank you!

**Comment by simon-p-r** [comment]
Thanks and no problem

**Pull request closed without merging**
