### PR TITLE
COMP_expand_block: spelling (algorithm)

### PR DESCRIPTION
**Pull request by SergeCroise**
CLA: trivial

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
agree with trivial

**Review by mattcaswell — APPROVED** [review]
Agree trivial

**Comment by mattcaswell** [comment]
Looks like you pushed a new merge commit into this - after this was approved. Merge commits are not allowed and it will be dropped when we push this to the repo. This is ready-to-merge but the repo is currently frozen due to the release tomorrow, so it won't be merged until after that.

**Comment by hlandau** [comment]
Merged to master. Thank you.

**Pull request closed without merging**
