### PR TITLE
Avoid call inefficient strlen.

### PR DESCRIPTION
**Pull request by raniervf**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
@raniervf actually you don't have to create a separate pull request for every micro change.

You can collect several commits on a single pull request branch, even with the Web Interface (although GitHub might give you the impression that you have open a new pull request for every change). Here's how to do it:

## Adding more commits to an existing pull request

The trick is to switch to the pull request branch _before_ you edit the file(s):

Just switch to the branch of your existing pull request _before_ editing the file

image

After editing choose to commit the change to the existing branch instead of creating a new pull request:

image


## Add commits on a branch _before_ creating a pull request

You can even avoid to create the pull request before you actually made all your changes (commits) to the branch. Again there is trick for it: Create a new branch for your changes, but _don't_ make the pull request right away:

* Create a *new branch* for this commit and start a pull request
* Enter the branch name
* Click [Propose file change]

image

* *Cancel* the pull request dialog

Even though the pull request was cancelled, the branch has already been created. So you can switch to the branch (see beginning) and commit your changes. In the end, you can go to the branches tab and create a pull request for your branch.

HTH,
Matthias

**Comment by mspncp** [comment]
Note that the title of the pull request can be edited. If your pull request already exists but you are still working on it, you can indicate that to us by adding the "WIP: " prefix (for "work in progress") to the title of the pull request, like it is for example currently in #10367:

image

This is helpful for the reviewers to know that it is not ready for final review yet.

**Comment by mspncp** [comment]
I think it would be easier for us reviewers to have a single strlen pull request where we get to see an overview of all your changes instead of all these equally named tiny pull requests.

Pull request #10361 has already been approved, so I would leave it untouched.  But I could offer to join [all your other strlen() pull requests](https://github.com/openssl/openssl/pulls/raniervf) into a single pull request branch, for example #10380. There you could continue editing without haste, as described previously.

Please let me know whether you want me to do the joining, and whether you appreciate further assistance.

**Comment by raniervf** [comment]
Hi,
Thank you for the hints, please go ahead with joining.

**Comment by mspncp** [comment]
Joined with #10380.

**Pull request closed without merging**
