### PR TITLE
Fix code format: BLOCK_CIPHER_custom

### PR DESCRIPTION
**Pull request by jiuhaizhang**
Fix code format: BLOCK_CIPHER_custom

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]
I agree this is trivial. @paulidale - do you agree?

**Review by t8m — APPROVED** [review]
This is surely OK for CLA: trivial.

**Review by paulidale — APPROVED** [review]
yes trivial.

**Comment by paulidale** [comment]
Merged, thanks for the fix.

**Pull request closed without merging**
