### PR TITLE
test_fipsinstall: Fallback to config(FIPSKEY) for the FIPSKEY

### PR DESCRIPTION
**Pull request by t8m**
This can be useful if running the test directly and not through the Makefile.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I'm not sure this is a bug fix.  I don't see how it can hurt however.

**Comment by t8m** [comment]
> I'm not sure this is a bug fix. I don't see how it can hurt however.

Given this new requirement to pass the environment variable broke existing albeit unsupported third party build scripts we might call it a bug fix, can't we? :grin:

**Comment by paulidale** [comment]
I'm not formally objecting.

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for the reviews.

**Pull request closed without merging**
