### PR TITLE
ci: Add GitHub token permissions for workflows

### PR DESCRIPTION
**Pull request by varunsh-coder**
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows.

GitHub recommends defining minimum GITHUB_TOKEN permissions for securing GitHub Actions workflows 
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/  
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) treats not setting token permissions as a high-risk issue 

This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve security.

Signed-off-by: Varun Sharma <varunsh@stepsecurity.io>

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by t8m** [comment]
We would need a CLA to be signed to be able to merge this. I am afraid this is outside of what we allow for CLA: trivial contributions.
https://www.openssl.org/policies/cla.html

**Review by paulidale — APPROVED** [review]

**Comment by varunsh-coder** [comment]
> We would need a CLA to be signed to be able to merge this. I am afraid this is outside of what we allow for CLA: trivial contributions.
> https://www.openssl.org/policies/cla.html

I have printed, signed, and emailed a scanned copy of the ICLA.

**Comment by varunsh-coder** [comment]
After signing the ICLA, I got an email to close and re-open open PRs for the CLA hold to go away.

**Comment by slontis** [comment]
I assume 111 has the same issue?

**Comment by paulidale** [comment]
It will do, yes.

**Comment by paulidale** [comment]
Merged to 1.1.1, 3.0 and master.  3.0 and 1.1.1 had fewer files but otherwise cherry-picked okay.

Thanks for the fixes.

**Pull request closed without merging**
