### PR TITLE
Final cleanup after move to leaner EVP_PKEY methods

### PR DESCRIPTION
**Pull request by levitte**
Now that KEYMGMT method pointers have moved away from the diverse
methods that are used with EVP_PKEY_CTX, we no longer need to pass
special argument to evp_generic_fetch() and evp_generic_do_all().

### CODE REVIEW

**Comment by levitte** [comment]
This can obviously not go in before #10303 and #10305 have been merged.  Until then, this remains WIP / draft.

**Comment by levitte** [comment]
Now that #10303 and #10305 are both merged, time to finalize this

**Comment by levitte** [comment]
This is not a draft or WIP any more.  Reviews welcome1

**Review by slontis — COMMENTED** [review]
Changes looks fine, could you update your commit message slightly..

Now that KEYMGMT method pointers have moved away from the diverse
methods that use EVP_PKEY_CTX, we no longer need to pass special arguments
to evp_generic_fetch() and evp_generic_do_all().

**Comment by levitte** [comment]
Done

**Comment by levitte** [comment]
Ah, yeah, ok.  How about now?

**Review by slontis — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

0ddf74bf1c47b554c3d2c086ff2acb18bcc81bc6 Final cleanup after move to leaner EVP_PKEY methods

**Pull request closed without merging**
