### PR TITLE
Update RAND_DRBG.pod

### PR DESCRIPTION
**Pull request by agnosticdev**
Fixed a minor typo while reading the documentation.

### CODE REVIEW

**Comment by romen** [comment]
Thanks for your contribution, @agnosticdev.

To be able to merge this, OpenSSL requires that all non-trivial contributors submit an Individual CLA (and possibly a Corporate CLA in some cases). You can read about it at https://www.openssl.org/policies/cla.html .

I believe this contribution qualifies as trivial, which would waive the requirement for a CLA.
If you agree with this, we would ask you to amend the commit message (and then force push to this PR branch) to include in its body (on its own line) the string `CLA: trivial`.

**Comment by agnosticdev** [comment]
@romen I agree that this contribution qualifies as trivial.  I will make the change to the commit message now.

**Comment by agnosticdev** [comment]
@romen I also just sent in my CLA document.

**Comment by mspncp** [comment]
> https://www.agnosticdev.com/blog-entry/python-network-security-networking/ssl-and-tls-updates-python-37
> https://docs.python.org/3/library/ssl.html#tls-1-3

@agnosticdev, I just happened to see your blog post.  Cool!

**Comment by agnosticdev** [comment]
@mspncp Thank you very much!  And thank you to everyone on this project for the great work that has been done on the latest release on the recent updates to TLS!

**Comment by romen** [comment]
Merged:
- 01e04f4 to `master`
- 9b977af to `OpenSSL_1_1_1-stable`

Thanks again @agnosticdev !

**Pull request closed without merging**
