### PR TITLE
Fixed default value of the "ess_cert_id_alg" option

### PR DESCRIPTION
**Pull request by olszomal**
The "ess_cert_id_alg" option specifies the hash function to be used to calculate the TSA's public key certificate identifier. 
The man page says default is sha256.

### CODE REVIEW

**Review by t8m — COMMENTED** [review]
So this actually changes the default. I'd like to see a corresponding PR targeted at 3.1/3.0 branches that corrects the documentation of the default in those branches.

**Comment by tom-cosgrove-arm** [comment]
Hmm, I have to say I'm not sure that this is trivial. Yes, there are simple updates to `ess_cert_id_alg` in some configuration files, but if you'd asked me to "update the default ess_cert_id_alg to be sha256" the change to `ts_conf.c` wouldn't have been obvious

**Comment by olszomal** [comment]
Either works for me. I have already provided a CLA on Oct 27, 2021.

**Comment by tom-cosgrove-arm** [comment]
@olszomal If you have a CLA on file, would you mind amending the commit with the `CLA: trivial` line and force-pushing? (Do please ensure the email address in the commit matches that in the ICLA you submitted.)

**Review by t-j-h — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
@t-j-h please reconfirm.

**Comment by t-j-h** [comment]
+1

**Comment by t8m** [comment]
Squashed and merged to the master branch. Thank you for your contribution.

**Comment by mattcaswell** [comment]
Shouldn't there be an update to CHANGE.md for a change like this?

**Comment by t8m** [comment]
See #21845

**Pull request closed without merging**
