### PR TITLE
Made foreign bit field unsigned in evp.h

### LINKED ISSUE #16010: Suggestion: signed bit field
I'm just wondering whether the following bit field should be explicitly unsigned. c99 reports this as a warning.
https://github.com/openssl/openssl/blob/ef1e0242a9aec5210845df86162c0b9219ff0f11/include/crypto/evp.h#L689
should really be:
```
unsigned int foreign:1;
```
If a pull request is wanted for this, I can handle it.

### PR DESCRIPTION
**Pull request by rsbeckerca**
Fixes #16010

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

### CODE REVIEW

**Comment by richsalz** [comment]
A one-bit bitfield is an attempt at optimization that fails. The compiler will allocate at least a byte, probably an int. And then do shifting/masking to get the right one-bit value set.  Better to make it an integer and test for zero/non-zero.

**Comment by rsbeckerca** [comment]
> 
> 
> A one-bit bitfield is an attempt at optimization that fails. The compiler will allocate at least a byte, probably an int. And then do shifting/masking to get the right one-bit value set. Better to make it an integer and test for zero/non-zero.

So, char or int? The previous field will force `foreign` to align so, I'm not sure there's a difference.

**Review by paulidale — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Side note: it's a bit surprising that no one has caught on and made `save_parameters` a one-bit field too....

**Comment by rsbeckerca** [comment]
> Side note: it's a bit surprising that no one has caught on and made `save_parameters` a one-bit field too.... 

Well, not just anyone has my funky c99 compiler  ;)

**Review by kaduk — APPROVED** [review]

**Comment by levitte** [comment]
> > Side note: it's a bit surprising that no one has caught on and made `save_parameters` a one-bit field too....
> 
> Well, not just anyone has my funky c99 compiler ;)

... which isn't relevant for my remark

**Review by mattcaswell — APPROVED** [review]

**Comment by richsalz** [comment]
bitfields are more work for the compiler than using an int.

**Comment by rsbeckerca** [comment]
> 
> 
> bitfields are more work for the compiler than using an int.

Personally, I would rather use `stdbool.h` and `bool`, but that is not fully portable. My company got rid of `:1` some years ago in favour of `bool`.

**Comment by rsbeckerca** [comment]
> 
> 
> > > Side note: it's a bit surprising that no one has caught on and made `save_parameters` a one-bit field too....
> > 
> > 
> > Well, not just anyone has my funky c99 compiler ;)
> 
> ... which isn't relevant for my remark

I'm sorry. It was a feeble attempt at self-deprecating humour.

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Yeah, bit fields are a classic space/time trade off on most platforms.  I did hit an interesting problem recently where multiple bit fields were defined and one needed locked access.  This mean that they all did.  It's not possible to determine which groups of bit fields a compiler might update in parallel.

**Comment by paulidale** [comment]
Merged to master, thanks.

**Pull request closed without merging**
