### PR TITLE
Disable loader_attic on VMS

### PR DESCRIPTION
**Pull request by levitte**
The reason is that it currently doesn't build properly, due to the of
pvkfmt.c, causing multiply defined symbols since libcrypto exports
them as well.  At the same time, it can't do without that source file,
or it won't have access to certain internal symbols from there.

### CODE REVIEW

**Comment by levitte** [comment]
I'm currently having this in draft, as I'm going to look if I can fiddle with some of the compiler knobs to make this go through.
The other option is to split `crypto/pem/pvkfmt.c`, but I frankly don't know that it's worth the effort.

**Comment by levitte** [comment]
This is not draft any more.  This is unfortunately necessary for now.

**Comment by richsalz** [comment]
You do like the word *attic* don't you? :)

**Comment by levitte** [comment]
Kind of found it fitting...  you know, the attic is where you *store* old stuff, and this being the old `file:` loader...

But otherwise, no particular preference, really.

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Merged

b2981f13e6d2090a656dec5e877b849331c3b69 Make it possible to disable the loader_attic engine
d0ccefdb77f94bec662d75aeadd0b081641abd19 Disable loader_attic by default on VMS

**Pull request closed without merging**
