### PR TITLE
Avoid NULL pointer dereference.

### PR DESCRIPTION
**Pull request by paulidale**
[manual merge from #9059 to 1.1.0]

Fixes: #9043

### CODE REVIEW

**Comment by beldmit** [comment]
So what is a procedure? Can I approve this PR and merge to 1.1.0 branch or not? (Sorry, I'm still unfamiliar with the procedures).

**Comment by levitte** [comment]
When someone with write access to the main repo is the author, then the *usual* procedure is for that person to merge.  This isn't a matter of policy, it's simply habits that have built up over time.  Formally speaking, nothing stops you from doing the merge if you want to, or even me...  however, it's likely that @paulidale wants to clean the branch out locally, so that might be a reason to leave it all to him.

We're also trying to pace ourselves, i.e. give the PR a grace period if someone else has a late opinion.  This is also a matter of habit more than anything else, and we're not always very good at the pacing thing, especially with this kind of small fixes.

Not sure if that gave you some answer, even thought not definitive...

**Comment by paulidale** [comment]
I forgot to update before bringing the changes across, I've rebased.

**Comment by paulidale** [comment]
I don't mind if someone else wants to merge this, but I'm also happy to do it.  As @levitte wrote, the author generally does (or first reviewer if the author doesn't have write permissions to the repository).  It isn't a hard and fast rule.

**Comment by paulidale** [comment]
The only changes on the rebase are in the generated errors.

**Comment by paulidale** [comment]
Merged to 1.1.0

**Pull request closed without merging**
