### PR TITLE
Add padding spaces before printing signature algorithm for CRL and cert output

### PR DESCRIPTION
**Pull request by levitte**
Inspired by #1513

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
Oh, do you want to include the Cert changes and fixes too?  From the thread in #4745

**Comment by levitte** [comment]
I can do that.

**Comment by levitte** [comment]
Now includes everything, starting with @hotpxl's original commit (already reviewed in #1513)

**Comment by levitte** [comment]
@richsalz, considering the added stuff, I'd like a reconfirm

**Review by richsalz — APPROVED** [review]
Thanks for cleaning this up.

**Comment by levitte** [comment]
Cool.  I'll just wait on the CIs to finish...  just to make sure.

**Comment by levitte** [comment]
Merged.  e6cccb5f0523f5a61f5d963ca1708d02e3e83ccc d1453d60a58b3e5de24a71d6fa65938629c144c8 be63fc1223579e7eb4ff747bfbd4b4fd3b0b01ea 8e4ec5b2e7c9a5d12c348b2a3430c4b51ab041c5

**Pull request closed without merging**
