### PR TITLE
Admit unknown pkey types at security level 0

### PR DESCRIPTION
**Pull request by vdukhovni**
Reworked comment and squashed #7906

### CODE REVIEW

**Comment by vdukhovni** [comment]
Pushed and closed. Thanks!

**Comment by vdukhovni** [comment]
Actually, should this also be backported to 1.1.1?

**Comment by vdukhovni** [comment]
I'm inclined to say "yes".

**Comment by levitte** [comment]
Yes.

**Comment by vdukhovni** [comment]
New PR, or cherry-pick and push?

**Comment by vdukhovni** [comment]
My guess is that the "1.1.1" tag means the same PR will suffice for both, please confirm.

**Comment by levitte** [comment]
Yes, it means that cherry-pick is a good method.  I usually do `git cherry-pick -x`.

Note that if you can't make a clean enough (in your judgement) cherry-pick, then you will be forced to make a separate PR for 1.1.1.

**Comment by vdukhovni** [comment]
Merge was clean.  Pushed to 1.1.1, thanks!  All done.

**Comment by mspncp** [comment]
FWIW: merged as follows with "Merged from #7906" annotation.

baba154510  Admit unknown pkey types at security level 0  (master)
ea7d2c5808  Admit unknown pkey types at security level 0   (1.1.1)

**Pull request closed without merging**
