### PR TITLE
Rename evp_pkey_get_EC_KEY_curve_nid to EVP_PKEY_get_curve_nid and us…

### PR DESCRIPTION
**Pull request by slontis**
…e EVP_PKEY_get_utf8_string_param()

Note that inside EVP_PKEY_get_curve_nid() that the if (pkey->keymgmt == NULL) path
is still being hit during TLS tests.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
NOTE: this is related to evp_pkey_get_EC_KEY_curve_nid() being undocumented currently (See #13192)

**Comment by slontis** [comment]
@mattcaswell - not sure if this is the right approach for this..

**Review by levitte — CHANGES_REQUESTED** [review]
Considering that this is a function that's *only* used in TLS code, I find it a bit misplaced, and am strongly opposed to make it a public function (as in declared in a public header).

An alternative would be to move it entirely to libssl, which is less of a challenge than you might imagine.  Something like this should do (untested):

``` C
ssl_get_EC_KEY_curve_nid(const EVP_PKEY *pkey)
{
    int ret = NID_undef;

    if (EVP_PKEY_id(pkey) != EVP_PKEY_KEYMGMT) {
        if (EVP_PKEY_base_id(pkey) == EVP_PKEY_EC) {
            EC_KEY *ec = EVP_PKEY_get0_EC_KEY(pkey);

            ret = EC_GROUP_get_curve_name(EC_KEY_get0_group(ec));
        }
    } else {
        char name[80] = { 0 };
        size_t name_len;

        if (EVP_PKEY_get_utf8_string_param((EVP_PKEY *)pkey,
                                           OSSL_PKEY_PARAM_GROUP_NAME,
                                           name, sizeof(name), &name_len))
            ret = ec_curve_name2nid(name);
    }

    return ret;
}
```

**Comment by slontis** [comment]
The biggest question with this is why do we still need the legacy path?

**Comment by levitte** [comment]
> The biggest question with this is why do we still need the legacy path?

Possible engines?

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Er, that approval came as a bit of a surprise.  I object and would really want to at least have my proposed alternative tried out.

**Comment by mattcaswell** [comment]
@levitte - since you objected I added the OTC hold label.

**Comment by levitte** [comment]
Thanks

**Comment by slontis** [comment]
Closing since the alternative has been merged.

**Pull request closed without merging**
