### PR TITLE
More typo/spelling fixes

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Same as #869 who was merged and revert.
So its branch becomes empty when I rebased it against the trunk.

As #689 was twice reviewed ( Ping @richsalz , @t-j-h ), it should be ok for merge.
If not, please say a word.

### CODE REVIEW

**Comment by richsalz** [comment]
+1 @t-j-h please re-confirm.

**Comment by richsalz** [comment]
ping @t-j-h

**Comment by levitte** [comment]
Looks good.  Unless you really want @t-j-h's review, I'd say this is ready to merge.

**Comment by FdaSilvaYY** [comment]
I have no preference if it could be merged ;).

**Comment by richsalz** [comment]
done, thanks! ( I had only pinged tim since he had looked at this before)

**Pull request closed without merging**
