### PR TITLE
s_client: Better response success check for CONNECT

### LINKED ISSUE #1663: s_client CONNECT/proxy issue with case sensitivity
According to https://www.ietf.org/rfc/rfc2817.txt any "successful (2xx) response to a CONNECT request indicates that the proxy has established a connection to the requested host and port, and has switched to tunneling the current connection to that server connection."
The current code checks for "200" and "established" in lower case. Connections to proxy servers which send "HTTP/1.1 200 Connection Established" (upper case E) fail with 's_client: HTTP CONNECT failed'.

Keeping the current code a simple fix would replace strstr(..) with strcasestr(mbuf, "established") != NULL) in https://github.com/openssl/openssl/blob/master/apps/s_client.c#L2014 . It would still not conform to the RFC but allow the usage of more proxy servers. For me this works fine and as I do not code C I'll live with this fix.
Anyhow as there is a RFC one could also rewrite the code to do an RFC compliant check.

### PR DESCRIPTION
**Pull request by levitte**
Instead of looking for "200" and "established" (and failing all other
2xx responses or "Established"), let's look for a line that's not a
header (i.e. doesn't contain a ':') and where the first space is
followed by a '2'.

---

Fixes #1663

### CODE REVIEW

**Review by godly — CHANGES_REQUESTED** [review]
This looks good, except of the check for ':' which is not necessary.
I'm still concerned about retrieving only parts (e.g. the first 8 bytes) of the reply and not one full line as I have no idea about the BIO_gets() work. So tmp_search[1] could be the end of the string (\0) and the check may fail. Coming from java I would implement:

``` c
mbuf_len = BIO_gets(fbio, mbuf, BUFSIZZ);
/* do we ever need this loop to fill mbuf or do we always get one at least one line and can remove the following code */
if (strlen(mbuf) < 13) {
        BIO_printf(bio_err, "HTTP CONNECT received partitial response: '%s'\n", mbuf);
        char *mbuf2 = NULL;
        mbuf2 = app_malloc(16, "mbuf2");
        do {
                mbuf_len = BIO_gets(fbio, mbuf2, 16);
                strcat(mbuf, mbuf2);
        } while ( (strlen(mbuf) < 13) && (mbuf_len > 3) );
        OPENSSL_free(mbuf2);
}
```

Having one line the check should be more easy to implement. In any case as soon as a SP is found and the upcoming character is not a '2' one can also exit.

``` c
/* check for ' 2' in 'HTTP/1.1 200 Connection Established\r\nHeader: Value\r\n\r\n' */
if ((mbuf[8]==' ') && (mbuf[9]=='2')) {
        foundit++;
} else {
        /* more robust check for ' 2' */
        for (i=0; i < strlen(mbuf)-2; i++) {
                if (mbuf[i]==' ') {
                        if (mbuf[i+1]=='2') {
                                foundit++;
                        }
                        break;
                }
        }
}
```

I hope that the inline code is formatted properly as I don't comment to often on Github.

PS: For my tests I also improved the error reporting, it may be nice to add it:

``` c
            if (!foundit) {
                BIO_printf(bio_err, "%s: HTTP CONNECT failed. Received: '%s'\n", prog, mbuf);
                goto shut;
            }
```

**Comment by levitte** [comment]
> This looks good, except of the check for ':' which is not necessary.

You cannot guarantee that the first space in a header line will not be followed by a '2'...

> I'm still concerned about retrieving only parts (e.g. the first 8 bytes) of the reply and not one full line as I have no idea about the BIO_gets() work. So tmp_search[1] could be the end of the string (\0) and the check may fail.

`fbio` is a buffered BIO, so `BIO_gets()` is guaranteed to get a full line, i.e. everything until a `\n`.

> Having one line the check should be more easy to implement. In any case as soon as a SP is found and the upcoming character is not a '2' one can also exit.

No.  You need to read past all the headers.

> PS: For my tests I also improved the error reporting, it may be nice to add it:

Good point, but a little more complex than what you did.  I'll figure something out.

**Comment by godly** [comment]
@ You cannot guarantee that the first space in a header line will not be followed by a '2'...
https://tools.ietf.org/html/rfc7230#section-3.1.2 defines:
```
start-line     = request-line / status-line
status-line = HTTP-version SP status-code SP reason-phrase CRLF
HTTP-name = %x48.54.54.50 ; HTTP
HTTP-version = HTTP-name "/" DIGIT "." DIGIT
status-code    = 3DIGIT
```
The RFC compliant server will always return "HTTP/d.d ddd Random Reason\r\n" as the first line.
The status code appears always after the first space and, and after reading the definitions, the 1st space is always at position 8. So no need to check it.
```c
if ( (strlen(mbuf) > 10) && (mbuf[9]=='2')) {
        foundit++;
}
```
should be a safe check. Maybe >9 would be sufficient, I'm not sure about the C length checks.


PS: I just realized that my 1st for loop does hang forever as the 2nd call to BIO_gets() hangs if the initial call returned -1. But it's not needed anyway.

**Comment by richsalz** [comment]
so @levitte what do you want to do with this?

**Comment by levitte** [comment]
I reimplemented it.  It should now satisfy a few things: 

1. that the response status *is* the first line received (if not, something is seriously wrong)
2. that the response headers should be read past *at all times* if this is determined to be a HTTP response.

**Review by richsalz — CHANGES_REQUESTED** [review]
Maybe make foundit be an enum?  Or get rid of the magic numbers with define's.

**Comment by levitte** [comment]
A local enum makes sense

**Comment by levitte** [comment]
Better?  (there are other instances of `foundit` that I will *not* fix in this PR)

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

master: ec2a0e60652c0e61e90dde367756c5d92cd882d3
1.1.0: 07cd2f84d1480ca714bc14233b3c023ba9874e9d

No merge into 1.0.2, since that one doesn't support `PROTO_CONNECT`

**Comment by levitte** [comment]
Merged.

master: ec2a0e60652c0e61e90dde367756c5d92cd882d3
1.1.0: 07cd2f84d1480ca714bc14233b3c023ba9874e9d

No merge into 1.0.2, since that one doesn't support `PROTO_CONNECT`

**Pull request closed without merging**
