### PR TITLE
Fix pkeyutl inability to directly access keys on hardware tokens

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
Cleaned up version of #548, rebased on top of fresh master.  @mouse07410, please confirm that this looks like your stuff

**Comment by richsalz** [comment]
+1 from me, if @mouse07410 confirms.

**Comment by mouse07410** [comment]
Yes it is a cleaner version of my stuff, thank you!  +1 from me.  Please commit/merge this!


One thing, we may have a problem with these (around line 109 in `apps/pkeyutl.c`):
```
    {"peerform", OPT_PEERFORM, 'F'},
    {"keyform", OPT_KEYFORM, 'f', "Private key format - default PEM"},
```
`The problem is - both `-peerform` and (especially!) `-keyform` can (or should be able to) take as argument one of: `PEM`, `DER`, `**engine**`. The current specification of these two seems to have dropped the `engine` part. 

Can you address it, replacing 'F' (and 'f') with whatever's appropriate to ensure all the three alternatives are enabled?

**Comment by levitte** [comment]
> One thing, we may have a problem with these (around line 109 in `apps/pkeyutl.c`):
> ```
>     {"peerform", OPT_PEERFORM, 'F'},
>     {"keyform", OPT_KEYFORM, 'f', "Private key format - default PEM"},
> ```
> The problem is - both `-peerform` and (especially!) `-keyform` can (or should be able to) take as argument one of: `PEM`, `DER`, `**engine**`. The current specification of these two seems to have dropped the `engine` part. 

Both are `'E'` in master, so...

**Comment by levitte** [comment]
Ok, that issue resolved, I'm merging

**Comment by levitte** [comment]
Aaaand merged!

**Comment by mouse07410** [comment]
Thank you!! !! !! ;)

**Pull request closed without merging**
