### PR TITLE
Use curve_id not the nid

### PR DESCRIPTION
**Pull request by kroeckx**
Found by OSS-Fuzz

### CODE REVIEW

**Comment by dot-asm** [comment]
If this addresses failures after #4406, it would be appropriate to add [extended tests] to commit ;-)

**Comment by kroeckx** [comment]
This might fix the issue, so I've added it.

**Comment by kroeckx** [comment]
test_ssl_new.t fails

**Comment by dot-asm** [comment]
Well, it's half-full vs. half-empty, thing, there were 3 failed tests, now there is one :-)

**Comment by kroeckx** [comment]
New commit pushed

**Comment by kroeckx** [comment]
Everything passed now

**Pull request closed without merging**
