### PR TITLE
Add some missing cfi frame info in aesni-gcm-x86_64.pl

### PR DESCRIPTION
**Pull request by bernd-edlinger**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
@slontis please help.
I can't get any of these assembler modules to be executed in master,
while 1.1.1 can be executed using
`apps/openssl speed -evp aes-128-gcm` and `apps/openssl speed -evp aes-128-gcm -aead`

Also the performance numbers (on a aesni-capable CPU)
are very much worse in master than in 1.1.1:
```
1.1.1:

$ apps/openssl speed -evp aes-128-gcm
OpenSSL 1.1.1e-dev  xx XXX xxxx
built on: Sun Dec 22 14:22:58 2019 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -pthread -m64 -Wa,--noexecstack -Wall -O3 -g -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm     645702.71k  1623859.41k  3237498.11k  5089249.52k  6397897.39k  6520318.63k

$ apps/openssl speed -evp aes-128-gcm -aead
OpenSSL 1.1.1e-dev  xx XXX xxxx
built on: Sun Dec 22 14:22:58 2019 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -pthread -m64 -Wa,--noexecstack -Wall -O3 -g -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
The 'numbers' are in 1000s of bytes per second processed.
type              2 bytes     31 bytes    136 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm      24167.67k   268349.23k  1059745.98k  3846256.30k  6085454.51k  6348439.55k

master:

$ apps/openssl speed -evp aes-128-gcm
version: 3.0.0-dev
built on: built on: Sun Dec 22 14:34:46 2019 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -pthread -m64 -Wa,--noexecstack -Wall -O3 -g -DOPENSSL_USE_NODELETE -DL_ENDIAN -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0x7ffaf3ffffebffff:0x29c6fbf
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm     564192.11k  1854365.44k  3470407.06k  4030295.04k  4213303.98k  4218432.17k

$ apps/openssl speed -evp aes-128-gcm -aead
version: 3.0.0-dev
built on: built on: Sun Dec 22 14:34:46 2019 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -pthread -m64 -Wa,--noexecstack -Wall -O3 -g -DOPENSSL_USE_NODELETE -DL_ENDIAN -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0x7ffaf3ffffebffff:0x29c6fbf
The 'numbers' are in 1000s of bytes per second processed.
type              2 bytes     31 bytes    136 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-gcm      12928.37k   166567.41k   675519.93k  2563522.90k  3913231.02k  4062096.04k
```

**Comment by kroeckx** [comment]
Open an issue about the performance regression?

**Comment by slontis** [comment]
> I can't get any of these assembler modules to be executed in master,
> while 1.1.1 can be executed using
> `apps/openssl speed -evp aes-128-gcm` and `apps/openssl speed -evp aes-128-gcm -aead`

Put a breakpoint in aesni_gcm_initkey - if it doesnt get there then something is wrong if you are on an aesni capable machine.
Also breakpoint PROV_AES_HW_gcm - it should look like this...

const PROV_GCM_HW *PROV_AES_HW_gcm(size_t keybits)
{
    return AESNI_CAPABLE ? &aesni_gcm : &aes_gcm;
}
If it is not returning aesni_gcm then it probably means the header is not getting included properly.
(The header iwas ciphermode_platform.h - and it is has just recently changed to aes_platform.h).

**Comment by bernd-edlinger** [comment]
I can confirm aesni_gcm_initkey is executed,
but after that only aesni_encrypt is executed, never aesni_gcm_encrypt
which is where I wanted to test the improved CFI instrumentation.

**Comment by bernd-edlinger** [comment]
Merged to master and 1.1.1 branch.  Thanks!

**Pull request closed without merging**
