### PR TITLE
Don't fail when tracing is disabled

### PR DESCRIPTION
**Pull request by levitte**
When tracing is disabled, don't generate errors, especially during
init.  Instead, just pretend the everything is fine.

### CODE REVIEW

**Review by mspncp — APPROVED** [review]

**Comment by romen** [comment]
Either here or in #8474 , should we add targets in the CI configuration to try both with and without TRACE enabled?

**Comment by levitte** [comment]
That's more of a [run-checker](https://github.com/openssl/tools/tree/master/run-checker) thing.  We can't load the CIs with too many things, they simply can't take the load (we've seen it before).

**Comment by levitte** [comment]
Submitted a PR for it: https://github.com/openssl/tools/pull/37

**Comment by levitte** [comment]
Merged.

d33d76168fb7642916cdcb7ccb0513abdb6f5f05 Don't fail when tracing is disabled

**Pull request closed without merging**
