### PR TITLE
Refactor how providers/fipsmodule.cnf is generated

### LINKED ISSUE #15166: The fipsmodule.cnf to be installed cannot be created by openssl fipsinstall in cross-compiled builds
#13684 broke cross-compiled builds by making `install_fips` automatic.

Our project cross-compiles OpenSSL for ARM on x86_64 as part of a larger distribution. Other open-source components of this distribution have dependencies on OpenSSL. As such, we depend on the `install` target working properly so we can build OpenSSL and install the artifacts into a staging directory which we then specify on the "configure" command lines when we subsequently build those other components. Prior to #13684 the install target completed successfully (and `providers/fips.so` was getting installed into the correct location). Now the install target in our cross-compile builds fails with:

`make[2]: *** No rule to make target 'providers/fipsmodule.cnf', needed by 'install_fips'.  Stop.`

This aborts installation and prevents the copying of `fips.so` into our staging directory.

We use this command line to configure OpenSSL:

`./Configure linux-generic32 -DL_ENDIAN -DOPENSSL_NO_COMP shared --prefix=/usr --openssldir=/conf/openssl enable-fips no-zlib no-comp no-tests`

It appears that `no-tests` prevents the creation of the `providers/fipsmodule.cnf` Makefile target (which we can't actually build anyway when cross-compiling). Since `providers/fipsmodule.cnf` is now a prerequisite for installing `fips.so` into our staging directory, that module is missing from our final product.

### PR DESCRIPTION
**Pull request by levitte**
It was made to only be generated for testing.  However, it was also
referred to from the 'install_fips' target, which suggests that it
should be generated any time the FIPS provider module itself is built.

To do this, we use the FILES build.info statement that's added in this PR.

The 'tests' target is still made to depend conditionally on
providers/fipsmodule.cnf.

Fixes #15166

### CODE REVIEW

**Comment by t8m** [comment]
This does not fix the #15166 - the openssl fipsinstall cannot be used to generate the fipsmodule.cnf to be installed with install_sw target because when cross-compiling there is no openssl to be run on the build system. And the self-test-has-been-run indicator should not be set in the fipsmodule.cnf to be installed either as that would make the build once / deploy many times use case fips non-compliant.

The `self-test-has-been-run indicator` should be seen as something optional which can have a separate make target.

**Comment by levitte** [comment]
Ah, point, it doesn't fix the cross compilation bit.  So two files then?  Darn this is getting complicated 😕

**Comment by levitte** [comment]
Regarding the self-test-has-been-run indicator, I'm at a loss.  I haven't followed that part of the development

**Comment by t8m** [comment]
> Regarding the self-test-has-been-run indicator, I'm at a loss. I haven't followed that part of the development

See Shane's and Tim's comments in the #15166

**Comment by t-j-h** [comment]
Self-test at install should be on by default and there should be an option to disable this for distributions and for cross-compilation.

**Comment by levitte** [comment]
Dropping this in favor of #15436

**Pull request closed without merging**
