### PR TITLE
CMP: Add missing oldCertID check to test server; add missing related API elements

### PR DESCRIPTION
**Pull request by DDvO**
Preparing #15778, I found that the CMP test server was missing a critical check.
Implementing it, I found that some CMP and CRMF API elements were missing, part of which are needed for the fix.
Hope it is not too late to fix this and add those elements now.

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t-j-h** [comment]
Too late for 3.0 - this really needed to be in for the final alpha and not proposed the day before beta close.

**Comment by t8m** [comment]
If this missing check is making the CMP implementation useless we should at least discuss this within OTC for inclusion in 3.0 as an exception.

**Comment by t8m** [comment]
So definitely not to be included in beta1 but we can discuss it within OTC for 3.0.

**Comment by t8m** [comment]
Also, would there be some way how to make the change less invasive and not adding a new public APIs?

**Comment by DDvO** [comment]
> If this missing check is making the CMP implementation useless we should at least discuss this within OTC for inclusion in 3.0 as an exception.

The check is important for the server-side handling of KUR: (key update requests, i.e, cert updates) in situations where the client cannot use the private key related to cert-to-be-updated for signature-based protection of the request. Then the server needs the OldCertID to identify the cert-to-be-updated, which may then also be needed to authorize the request.

The client side is not affected, and this is why so far the missing checks and API elements did not come up: They are needed for implementing a realistic CMP server.

> Also, would there be some way how to make the change less invasive and not adding new public APIs?

For the OldCertID check, two API functions need to be added.

The rest of the newly added API functions are for completeness of the server-side API,
so not strictly needed for fixing the issue in the test server, but would be needed for implementing more capable servers, which may need to access further controls and registration information provided by the client in any types of requests.

**Comment by DDvO** [comment]
> So definitely not to be included in beta1 but we can discuss it within OTC for 3.0.

Thanks - would be great if we can still squeeze at least part of it into 3.0.

**Comment by t8m** [comment]
Hmm, given this is affecting only the server side, I do not think it is likely to get an exception. But we should discuss it at the OTC meeting next Tuesday anyway. If you could attend it to present the problem, it would be helpful.

**Comment by DDvO** [comment]
> But we should discuss it at the OTC meeting next Tuesday anyway.
> If you could attend it to present the problem, it would be helpful.

Tuesday should work out for me. At which time should I attend?

**Comment by t8m** [comment]
> Tuesday should work out for me. At which time should I attend?

10:00 UTC+2 - the same link as previously.

**Comment by t-j-h** [comment]
OTC: reduce this to the minimal PR with only getters included and avoid changing reason codes and altering signatures (adding the extension parameters) for OTC vote consideration as an exception to the beta rules in next weeks OTC meeting.

**Comment by DDvO** [comment]
> OTC: reduce this to the minimal PR with only getters included and avoid changing reason codes and altering signatures (adding the extension parameters) for OTC vote consideration as an exception to the beta rules in next weeks OTC meeting.

Done. 
Moreover, as requested by @levitte, split the commit into
* API (and reason code) extensions
* fix of mock server, making use oft two new getters.
  This includes new test case as witness for improved `oldCertID` checks in test server.

**Review by t8m — APPROVED** [review]
LGTM, of course merging depends on OTC approval.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Will need to wait for the OTC to make a yes/no call before merging or not.

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
OTC vote passed to allow this change post-beta

**Review by paulidale — APPROVED** [review]
With or without the additional `const` being included or not.

**Comment by DDvO** [comment]
Thanks @openssl/otc for discussing this.
I'm glad that the vote passed to include in 3.0 the getter functions so far missing from the API.

As agreed, also changed the result of`OSSL_CRMF_{CERTTEMPLATE,CERTID}_get0_serialNumber()` to `const`, 
for consistency and because this fits better with the intended use.

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master. Thank you.

**Pull request closed without merging**
