### PR TITLE
Fix coverity issues with certificate compression

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [X] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
I don't know how to confirm if this fixes the coverity issues?

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
> I don't know how to confirm if this fixes the coverity issues?

We'll see if they disappear after merging.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged with end of line white space removal.  Thanks.

**Comment by t8m** [comment]
> Where does one see the Coverity results? I looked under actions, but no details are provided.

https://scan.coverity.com/projects/openssl

**Comment by t8m** [comment]
The 1516093 is still unfixed by this PR. IMO there should be some maximum possible length check on `uclen`.

**Comment by tmshort** [comment]
> The 1516093 is still unfixed by this PR. IMO there should be some maximum possible length check on `uclen`.

That might be the case. Coverity isn't always clear as to how to fix things.

**Pull request closed without merging**
