### PR TITLE
Clarify dashes are required for openssl list command

### LINKED ISSUE #19013: Invalid syntax of 'openssl list' command options
_release:_ openssl-3.0.5

_manual reference:_
```
$ man 'OPENSSL(1ossl)'
(...)
SYNOPSIS
       (...)
       openssl list standard-commands | digest-commands | cipher-commands |
       cipher-algorithms | digest-algorithms | mac-algorithms | public-key-
       algorithms
```
Hello. Options tied to `openssl list <option>` missing the presence of character _-_ in front of them, which thus make the above mentioned syntax invalid; illustration:
```
$ openssl list standard-commands
list: Use -help for summary.
```
As opposed, illustration of output made against a valid syntax
```
$ openssl list -standard-commands | head -1
asn1parse         ca                ciphers           cmp
```

### PR DESCRIPTION
**Pull request by crox**
Fixes #19013

CLA: trivial

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
Agree trivial

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Agree trivial

**Comment by paulidale** [comment]
Merged, thanks for the contribution.

**Comment by tmshort** [comment]
This appears to have broken `make doc-nits`:
```
/usr/bin/perl ./util/find-doc-nits -c -n -l -e
doc/man1/openssl.pod: openssl does not implement -cipher-algorithms
doc/man1/openssl.pod: openssl does not implement -cipher-commands
doc/man1/openssl.pod: openssl does not implement -digest-algorithms
doc/man1/openssl.pod: openssl does not implement -digest-commands
doc/man1/openssl.pod: openssl does not implement -mac-algorithms
doc/man1/openssl.pod: openssl does not implement -public-key-algorithms
doc/man1/openssl.pod: openssl does not implement -standard-commands
doc/man1/openssl.pod:1: SYNOPSIS entry B<-standard-commands> missing from OPTIONS
doc/man1/openssl.pod:1: SYNOPSIS entry B<-digest-commands> missing from OPTIONS
doc/man1/openssl.pod:1: SYNOPSIS entry B<-cipher-commands> missing from OPTIONS
doc/man1/openssl.pod:1: SYNOPSIS entry B<-cipher-algorithms> missing from OPTIONS
doc/man1/openssl.pod:1: SYNOPSIS entry B<-digest-algorithms> missing from OPTIONS
doc/man1/openssl.pod:1: SYNOPSIS entry B<-mac-algorithms> missing from OPTIONS
doc/man1/openssl.pod:1: SYNOPSIS entry B<-public-key-algorithms> missing from OPTIONS

**Comment by levitte** [comment]
Hmmm, actions weren't enabled in this PR, right (because it apparently needs to be enabled once on per-user basis)?
This goes to show that we need to enable running actions whenever we see it not being so...

**Comment by crox** [comment]
@tmshort  yes I noticed that was an issue - I have started looking at the Perl in find-doc-nits to see how it needs to be fixed.

@levitte Is that a suggestion for me?  I'm able to run 'make doc-nits' and view the problem locally.

Sorry - this was supposed trivial way to get involved with the project....... I'm happy to continue to dig into it.

**Comment by tmshort** [comment]
See #19044

**Comment by levitte** [comment]
> @levitte Is that a suggestion for me?

Ah, no, sorry, that was to @openssl, especially those among us who admin this repo. There's a button we see that we need to press to enable github actions to run on PRs that you (@crox) make. We didn't, and thereby didn't see that failing doc checks, which are otherwise caught by our actions setup.

**Pull request closed without merging**
