### PR TITLE
[WIP] Openssl 111 features

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This contains 1.1.1 features I have
#2986 
#6516 
#11525 
#11577 
#11666 
#11780 
#11782 
#11846 
#11895 
#11934 
#11956 
#11995 
#12079

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Some openssl speed results follow :-)
Summary: The AES speed is much higher with this PR, while HMAC speed is much slower in master.

This PR:
```
OpenSSL 1.1.1j-dev  xx XXX xxxx
built on: Tue Feb  2 15:12:39 2021 UTC
options:bn(64,64) rc4(8x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN
 -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT
 -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM
 -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
 -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0x3e983a0b078bffff:0x8
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
hmac(md5)        16624.98k    48422.63k   129789.95k   218423.98k   272373.08k   241893.38k
aes-128 cbc     205035.68k   214994.01k   235380.27k   239841.96k   241369.09k   241325.40k
aes-192 cbc     182248.97k   182586.75k   197160.28k   200586.24k   201648.81k   201758.04k
aes-256 cbc     158688.05k   159745.43k   170027.52k   172667.56k   173509.29k   173533.87k
```
1.1.1 :
```
OpenSSL 1.1.1j-dev  xx XXX xxxx
built on: Tue Feb  2 14:44:59 2021 UTC
options:bn(64,64) rc4(8x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE
 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT
 -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM
 -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
 -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
hmac(md5)        15504.83k    46094.08k   125609.98k   213659.31k   270592.68k   252160.68k
aes-128 cbc      36293.51k    38649.39k    39906.90k    92897.96k    94401.88k    94546.60k
aes-192 cbc      30687.49k    32379.39k    33132.03k    79068.84k    79951.19k    79839.23k
aes-256 cbc      26539.78k    27727.89k    28413.87k    68765.01k    69186.90k    69216.94k
```
master:
```
version: 3.0.0-alpha12-dev
built on: built on: Tue Feb  2 13:28:43 2021 UTC
options:bn(64,64) rc4(8x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE
 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0x3e983a0b078bffff:0x8
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
hmac(md5)        11394.15k    36440.09k   103444.14k   188451.84k   262482.60k   246786.73k
aes-128 cbc      36293.51k    38649.39k    39906.90k    92897.96k    94401.88k    94546.60k
aes-192 cbc      30687.49k    32379.39k    33132.03k    79068.84k    79951.19k    79839.23k
aes-256 cbc      26539.78k    27727.89k    28413.87k    68765.01k    69186.90k    69216.94k
```

**Review by paulidale — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
Here are some performance comparison between 1.1.1 / 3.0 / 3.1 and 111-feature branches:
```
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
OpenSSL-1_1_1-stable:
md5              43573.94k    87662.90k   191117.91k   251465.05k   281258.67k   258517.67k
hmac(md5)        16758.59k    48939.63k   126291.63k   219938.82k   275218.43k   258397.53k
sha1             37646.53k    92188.27k   178838.27k   227958.10k   255513.94k   258413.91k
aes-128 cbc      66135.31k    70324.05k    71131.82k    71556.44k    71644.50k    71734.61k
aes-192 cbc      58725.66k    61275.97k    62015.06k    62279.68k    62281.05k    62412.12k
aes-256 cbc      51050.83k    54148.50k    54832.90k    55150.59k    55184.04k    55186.77k
ghash           298329.37k   695077.12k   860462.59k   912843.78k   926602.58k   926367.74k
rand              4847.24k    19380.31k    74776.92k   253453.99k   806013.61k   936656.90k
openssl-3.0
md5              19422.70k    53796.22k   141357.57k   228241.75k   271570.26k   244673.19k
hmac(md5)        12483.87k    38686.25k   107670.44k   202653.35k   262086.66k   239501.31k
sha1             18220.48k    55591.94k   135932.92k   210595.36k   253468.67k   255726.93k
aes-128-cbc     159102.81k   194985.69k   228536.32k   238494.04k   241404.59k   241390.93k
aes-192-cbc     141001.41k   168883.03k   193639.34k   200615.30k   201921.88k   201845.42k
aes-256-cbc     126093.02k   148058.11k   166131.97k   171749.72k   173323.61k   173167.96k
ghash           146500.37k   399813.80k   678572.29k   831203.33k   907575.30k   860225.54k
rand              4254.77k    18199.42k    71241.90k   235458.22k   760930.30k   911491.07k
openssl-3.1:
md5              19114.52k    52154.58k   138810.11k   226335.06k   269927.77k   233226.24k
hmac(md5)        12532.00k    38253.63k   111140.61k   203133.95k   255210.84k   246841.34k
sha1             16512.47k    51129.39k   128558.25k   208005.12k   253364.91k   255546.71k
aes-128-cbc     162711.87k   198484.46k   229484.20k   238483.46k   241306.28k   241401.86k
aes-192-cbc     143788.28k   170974.27k   193470.12k   199916.89k   201880.92k   201932.80k
aes-256-cbc     128818.23k   149759.04k   166527.66k   171856.90k   173506.56k   173566.63k
ghash           147927.99k   407154.54k   704536.15k   861270.36k   916220.59k   919289.86k
rand              6790.09k    26879.96k   102099.54k   328147.63k   860678.83k   980456.79k
openssl-111-features:
md5              41955.29k    99535.00k   178449.21k   249150.50k   281231.36k   251363.33k
hmac(md5)        16805.88k    48477.35k   130934.02k   218656.43k   274713.26k   244979.03k
sha1             37298.41k    91881.05k   178288.30k   232750.42k   255481.17k   259566.25k
aes-128 cbc     213962.44k   214721.15k   235101.44k   240096.60k   241080.42k   240741.03k
aes-192 cbc     181611.29k   183663.77k   197467.31k   200948.05k   201845.42k   201708.89k
aes-256 cbc     158942.47k   160362.49k   169514.89k   172266.84k   173675.86k   173621.25k
ghash           298884.27k   693753.43k   860028.33k   912365.91k   925906.26k   924685.65k
rand              4867.63k    18975.70k    74597.80k   253489.83k   805063.34k   939141.80k
``'

**Comment by t8m** [comment]
Bernd, IMO at this point this branch is a fork of openssl-1.1.1 and so it should live outside of OpenSSL project.

**Comment by bernd-edlinger** [comment]
Well, yeah, of course, since 1.1.1 is nearly at its EOL date, it is now time for some decisions to be made,
and I just wanted to share some numbers, and get an overview for myself how the different options compare.
To me it was new to see the performance of the rand function improved from 3.0 to 3.1 quite a bit.

**Comment by mattcaswell** [comment]
> To me it was new to see the performance of the rand function improved from 3.0 to 3.1 quite a bit.

Also see: https://github.com/openssl/openssl/pull/20929#issuecomment-1559745547

**Comment by bernd-edlinger** [comment]
Yeah, that's interesting...
BTW: a major part of the speed-up between 3.0 3.1 is due to bbbccd7 which would to be easy to cherry-pick to 3.0

**Comment by mspncp** [comment]
@bernd-edlinger why are the aes-cbc numbers for OpenSSL-1_1_1-stable much lower than for all other branches, including your 111 feature branch? Did you backport a new hardware implementation?

**Comment by mspncp** [comment]
Is the speedup caused by the bit-sliced implementation?

**Comment by bernd-edlinger** [comment]
I've added a patent-free bit-sliced implementation but only for CBC in decrypt mode and only for the constant time.
But the measured performance numbers are for the AES_encrypt case, where bit-slicing is not possible.
The better speed of the features branch is due to the fact that I've implemented a hardware-acceleration
for the legacy AES APIs, which the openssl speed command uses in 1.1.1 and in the features branch,
but the speed command in openssl-3.x accesses AES via EVP and/or provider APIs and is therefore
by definition slower, while 1.1.1 still uses the legacy API which is neither constant time, nor very performant.

**Comment by t8m** [comment]
@bernd-edlinger Given the 1.1.1 EOL I am going to close this PR.

People can still get the patches from:
https://github.com/bernd-edlinger/openssl/tree/openssl-111-features
if interested.

**Pull request closed without merging**
