### PR TITLE
X509_NAME_cmp: if canon_enclen is 0 for both names return 0

### LINKED ISSUE #14813: X509_verify_cert() behavior change between alpha13 and alpha14
I have a test that does the following

```
ver_ctx = X509_STORE_CTX_new();
store = X509_STORE_new();
X509_STORE_add_cert(store, certificate);
X509_STORE_CTX_init(ver_ctx, store, certificate, NULL);

TS_ASSERT_EQUALS(1, X509_verify_cert(ver_ctx));
```

The 'certificate' is a self-signed (non-CA) certificate. I don't believe details beyond that to be relevant, but it's generated like so

```
certificate = X509_new();
X509_set_version(certificate,3);
ASN1_INTEGER_set(X509_get_serialNumber(certificate),100);
X509_gmtime_adj(X509_get_notBefore(certificate),0);
X509_gmtime_adj(X509_get_notAfter(certificate),(long)60 * 60 * 24 * 365);
X509_set_pubkey(certificate, public_key);
X509_sign(certificate, private_key, md);
```

The 'private_key' and 'public_key' are a key-pair generated elsewhere. 'md' doesn't seem to matter, it fails for various algorithms (SHA1, SHA256, etc.)

Beginning in alpha14, the TS_ASSERT_EQUALS (the meaning of which I hope is obvious even if it's a macro from something not understood by OpenSSL proper) fails.

Interestingly, a similar test assertion that uses X509_verify() continues to work fine.

While I would certainly understand if any deliberate attempt had been made to make such self-signed certificates harder to trust unintentionally, I would worry about the behavior change surprising existing applications. I would have expected a prominent entry in CHANGES if this change in behavior were indeed intentional.

### PR DESCRIPTION
**Pull request by t8m**
We do not care whether canon_enc is NULL in this case.

Fixes #14813

This is less invasive alternative to #14819

### CODE REVIEW

**Comment by DDvO** [comment]
> This is less invasive alternative to #14819

Correct that this is less invasive, 
but the downside is that it keeps following weird and error-prone implicit invariant:
`n->canon_enc == NULL` if (and only if) `n->canon_enclen == 0`

**Comment by t8m** [comment]
The invariant was there since ages. I do not think we should try to fix it now.

**Comment by DDvO** [comment]
Then please make it at least explicit, to avoid mistakes being made such those that lead to #14813.

**Comment by DDvO** [comment]
Yet I see no good reason to keep that strange behavior.
If my PR #14819 is seen too bulky, I can remove from it the rather unrelated streamlining of malloc failure reporting.

**Comment by richsalz** [comment]
Keeping a pointer and length is common in C.  Keeping the invariant is also common.  I would not in any way call it unusual. It might be error-prone, but the code originally was correct :)  Look at all the `_len` fields in various ssl header files for example.

I mean blaming #14183 seems a little disingenuous, since the problem was introduced by broken code added in #14357, right?

**Comment by t8m** [comment]
The regression was introduced in #14589.
@DDvO What do you mean by explicit? Add a comment in the X509_NAME_cmp or?

**Comment by DDvO** [comment]
> The regression was introduced in #14589.

Right - I had confused the numbers when writing https://github.com/openssl/openssl/issues/14813#issuecomment-816959526.

> @DDvO What do you mean by explicit? Add a comment in the X509_NAME_cmp or?

Since the source of the invariant is in the internal function 
`static int x509_name_canon(X509_NAME *a)`, 
which has an internal documentation in the form of a multi-line comment above its definition,
a prominent remark should be added there, for instance:
```
 * NOTE: For empty X509_NAME (NULL-DN), canon_enclen == 0 && canon_enc == NULL.
```

**Comment by t8m** [comment]
Added

**Review by DDvO — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
Merged to master. Thank you for the review.

**Pull request closed without merging**
