### PR TITLE
Made several BIO functions have signatures which are consistent with their documentation

### PR DESCRIPTION
**Pull request by alex**
`BIO_ctrl` returns a `long`, while these are all documented as returning `int`.

### CODE REVIEW

**Comment by richsalz** [comment]
I think this patch is reasonable.  @kroeckx  you okay with it?
+1

**Comment by levitte** [comment]
+1

**Comment by richsalz** [comment]
pusehd at 5a33936, closing.  thanks!

**Comment by alex** [comment]
Wooo! Thanks.

**Comment by richsalz** [comment]
gotta take our time and be careful about these things :)

**Pull request closed without merging**
