### PR TITLE
Hjl/cet/master

### PR DESCRIPTION
**Pull request by hjl-tools**
This set of patches enables CET on Linux/i686 and Linux/x86-64.   Tested on CET processor.

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
Please take a look at https://github.com/openssl/openssl/blob/a0e594d6b5265efd412d248bd12e9d5305370286/CONTRIBUTING#L19-25

**Comment by hjl-tools** [comment]
I emailed my ICLA.   I don't have Windows.  My changes shouldn't change Windows assembly
codes.  Can someone tell me what are the differences in Windows assembly codes before and
after my changes.

**Comment by FdaSilvaYY** [comment]
There is a windows build issue :

````
 Assembling: crypto\aes\aes-x86_64.asm
crypto\aes\aes-x86_64.asm(350
crypto\aes\aes-x86_64.asm(350) : error A2008:syntax error : endbcrypto\aes\aes-x86_64.asm(832
crypto\aes\aes-x86_64.asm(832) : error A2008:syntax error : endbcrypto\aes\aes-x86_64.asm(929
crypto\aes\aes-x86_64.asm(929) : error A2008:syntax error : endbcrypto\aes\aes-x86_64.asm(1217)e
crypto\aes\aes-x86_64.asm(1217) : error A2008:syntax error : endcrypto\aes\aes-x86_64.asm(1440)e
crypto\aes\aes-x86_64.asm(1440) : error A2008:syntax error : endNMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\ml64.EXE"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
Command exited with code 2
````
See https://ci.appveyor.com/project/openssl/openssl/builds/29984410/job/15fs11u06tcwlxdh#L1259

**Comment by hjl-tools** [comment]
Is the Windows build issue caused by my changes? If yes, how can I fix it?  I don't have Windows
to reproduce the Windows build issue.

**Comment by hjl-tools** [comment]
I will close it and open a new one.

**Pull request closed without merging**
