### PR TITLE
Fix potential memory leaks

### PR DESCRIPTION
**Pull request by ghedo**

### CODE REVIEW

**Comment by ghedo** [comment]
I added an additional patch that fixes some memory leaks in `test/gost2814789test.c`.

**Comment by ghedo** [comment]
...and another for a leak in `test/clienthellotest.c`.

**Comment by ghedo** [comment]
Ping? All these patches are pretty simple and straightforward.

**Comment by richsalz** [comment]
yes they are.  but we have a big backlog :(

**Comment by ghedo** [comment]
I've just added yet another for leaks in X509_verify_cert(), following the fix in cc2829e.

**Comment by richsalz** [comment]
done in master and 1.0.2; thanks.

**Pull request closed without merging**
