### PR TITLE
ecp_sm2p256-armv8.pl: Copy the argument handling from ecp_nistz256

### LINKED ISSUE #21874: Windows Arm64 regression after merging "Optimize SM2 on aarch64"
Arm64 build for VC-CLANG-WIN64-CLANGASM-ARM configuration is failing after [PR Optimize SM2 on aarch64](https://github.com/openssl/openssl/pull/20754)
@xu-yi-zhou 
logs could be found [here](https://github.com/Windows-on-ARM-Experiments/openssl/actions/runs/6007501438/job/16293717106)
clang-cl: error: no such file or directory: 'crypto\ec\ecp_sm2p256-armv8.S'

### LINKED ISSUE #21876: Master fails to compile on Apple Silicon M2 (AARCH64)
Apple Silicon M2 computer running MacOS 13.5.1 with Xcode-14.3.1. OpenSSL - current master.

`perl configdata.pm --dump`:
[configdata.dump.txt](https://github.com/openssl/openssl/files/12455651/configdata.dump.txt)

Apparent error:
```text
clang  -Icrypto -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DBSAES_ASM -DECP_NISTZ256_ASM -DECP_SM2P256_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DOPENSSL_SM3_ASM -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DSM4_ASM -DVPAES_ASM -DVPSM4_ASM -fPIC -arch arm64 -O3 -std=gnu18 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I//Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -g -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/ur20980/openssl-3/etc\"" -DENGINESDIR="\"/Users/ur20980/openssl-3/lib/engines-3\"" -DMODULESDIR="\"/Users/ur20980/openssl-3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DZLIB_SHARED  -c -o crypto/ec/libcrypto-lib-ecp_sm2p256-armv8.o crypto/ec/ecp_sm2p256-armv8.S
clang: error: no such file or directory: 'crypto/ec/ecp_sm2p256-armv8.S'
clang: error: no input files
make[1]: *** [crypto/ec/libcrypto-lib-ecp_sm2p256-armv8.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [tests] Error 2
```
In the build log there seems a problem with generating the appropriate .S file...

Complete build log: [make-out.txt](https://github.com/openssl/openssl/files/12455672/make-out.txt)
Log of failed "make test" (obviously fails because the build failed): [test-out.txt](https://github.com/openssl/openssl/files/12455979/test-out.txt)

### PR DESCRIPTION
**Pull request by t8m**
Fixes #21874
Fixes #21876

### CODE REVIEW

**Comment by levitte** [comment]
I would mention in the commit message that popping the arguments to get the output file is more robust.

**Comment by t8m** [comment]
@levitte commit message adjusted

**Review by tom-cosgrove-arm — APPROVED** [review]
Okay, this is the way it's done in all the other `*-armv8.pl` scripts, so it's good

**Comment by levitte** [comment]
> Okay, this is the way it's done in all the other `*-armv8.pl` scripts, so it's good

Historically, we've had a mix of popping the output argument from the end of the argument list, or shifting from the start to find it...  or none of them and always sending the output the STDOUT.  This very much depended on when those scripts were authored and how the method for output had developed at that time.

I did some sort of streamlining effort years ago, to at least make sure that they would all take an output file as last argument.  It's possible, though, that they haven't all been streamlined to use the popping method.  That could be a worthy endeavor if someone is inclined, as it would probably stop new perlasm scripts from being inspired by other scripts that don't use that methid.

**Comment by tom-cosgrove-arm** [comment]
@levitte If you're happy with the commit message can you update the approval labels?

**Review by levitte — APPROVED** [review]
Happy

**Comment by t8m** [comment]
Merged to the master branch. Thank you for the reviews.

**Pull request closed without merging**
