### PR TITLE
req: Avoid segfault when -modulus is used

### LINKED ISSUE #16196: openssl req segfault
Current master (and beta2) crashes on 
```
openssl req -newkey rsa:2048 -keyout test.key -out test.csr
openssl req -modulus -in test.csr -noout
```
The stack trace is
```
#0  0x00007ffff7bce05e in BN_print (bp=bp@entry=0x4eb250, a=0x0) at crypto/bn/bn_print.c:36
#1  0x00000000004504f8 in req_main (argc=<optimized out>, argv=<optimized out>) at apps/req.c:1001
#2  0x0000000000444f28 in do_cmd (prog=prog@entry=0x4e3df0, argc=argc@entry=5, argv=argv@entry=0x7fffffffde80) at apps/openssl.c:414
#3  0x00000000004224a7 in main (argc=5, argv=0x7fffffffde80) at apps/openssl.c:295
```

It's not a problem to add a check to req_main, but it looks like we get an invalid DER structure:

```
  0 650: SEQUENCE {
  4 370:   SEQUENCE {
  8   1:     INTEGER 0
 11  69:     SEQUENCE {
 13  11:       SET {
 15   9:         SEQUENCE {
 17   3:           OBJECT IDENTIFIER countryName (2 5 4 6)
 22   2:           PrintableString 'AU'
       :           }
       :         }
 26  19:       SET {
 28  17:         SEQUENCE {
 30   3:           OBJECT IDENTIFIER stateOrProvinceName (2 5 4 8)
 35  10:           UTF8String 'Some-State'
       :           }
       :         }
 47  33:       SET {
 49  31:         SEQUENCE {
 51   3:           OBJECT IDENTIFIER organizationName (2 5 4 10)
 56  24:           UTF8String 'Internet Widgits Pty Ltd'
       :           }
       :         }
       :       }
 82 290:     SEQUENCE {
 86  13:       SEQUENCE {
 88   9:         OBJECT IDENTIFIER rsaEncryption (1 2 840 113549 1 1 1)
 99   0:         NULL
       :         }
101 271:       BIT STRING, encapsulates {
106 266:         SEQUENCE {
110 257:           INTEGER
       :             00 9B 84 EF 75 4B 16 14 96 E0 4B DA 4A C6 0C B6
       :             FF 89 27 B3 07 FE B8 E8 AE A7 00 5C C9 34 3B 73
       :             C1 9A F2 E4 40 98 09 4B B1 4C 2B 6A 5B 7B F0 BB
       :             E4 73 E7 A5 71 DD AF 3A 58 8E 8A 92 6E 99 39 58
       :             7B 36 50 E6 7F CE EB 59 66 A8 1B 32 72 A2 EF 80
       :             A5 35 BF 23 7E 96 D2 B8 78 1A BF 78 8D C2 53 6C
       :             E8 43 A1 55 40 73 8B 4F 62 01 9A D1 6F D5 80 B6
       :             17 98 87 19 12 BE 32 B0 7F 1B 25 84 E4 1C F5 ED
       :                     [ Another 129 bytes skipped ]
371   3:           INTEGER 65537
       :           }
       :         }
       :       }
376   0:     [0]
       :       Error: Object has zero length.
       :     }
378  13:   SEQUENCE {
380   9:     OBJECT IDENTIFIER sha256WithRSAEncryption (1 2 840 113549 1 1 11)
391   0:     NULL
       :     }
393 257:   BIT STRING
       :     8F 94 12 3C 45 E2 D5 0F 31 D6 E4 8F 2C AE D1 E6
       :     41 72 74 EC 90 55 C6 78 17 6C 91 C7 9E D5 EC 0B
       :     65 16 0F 47 1C 32 B4 01 B5 20 A3 9F DE C8 2E 3C
       :     77 C5 27 F6 39 31 A9 F1 E9 4B F1 F5 E0 43 55 F5
       :     60 1A 8B 5A 16 DE AE 23 62 DC F4 2D 4C 57 09 B6
       :     29 34 7F 4B 54 91 B2 3A 53 60 D4 D9 D0 31 B4 04
       :     D8 44 3C DE 39 89 3D 0A 62 DB 50 18 0D F4 29 39
       :     89 16 4C 75 46 C6 D2 8C EF FD D3 94 88 EB 84 C2
       :             [ Another 128 bytes skipped ]
       :   }

0 warnings, 1 error.
```

### PR DESCRIPTION
**Pull request by t8m**
Fixes #16196

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by beldmit** [comment]
@t8m, I'm not sure it's a true fix. If you parse the private key using dumpasn1, you'll get a report about bad ASN1 structure. So maybe we need to fix a private key generation also.

**Comment by t8m** [comment]
> @t8m, I'm not sure it's a true fix. If you parse the private key using dumpasn1, you'll get a report about bad ASN1 structure. So maybe we need to fix a private key generation also.

This is a true fix for the -modulus crashing. Please note the change from pkey to tpubkey.

**Comment by beldmit** [comment]
> This is a true fix for the -modulus crashing. Please note the change from pkey to tpubkey.

Got it, thanks! Do we need a separate issue for a private key?

**Comment by t8m** [comment]
I do not see any issue with a private key.

Also the dump is probably doing something wrong, because if I generate a .csr with 1.1.1k I get exactly the same ASN.1 structure.

**Comment by beldmit** [comment]
OK, got it, thanks!

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
Is this issue ready to merge now?

**Comment by t8m** [comment]
Merged to master. Thank you for the reviews.

**Pull request closed without merging**
