### PR TITLE
darwin platform replacing getentropy usage by platform api instead.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
due to risks of refusal in App Store, example of discussion here https://dev.gnupg.org/T5375

**Comment by kroeckx** [comment]
Why isn't it using SecRandomCopyBytes()?

**Comment by devnexen** [comment]
1/ The first parameter of SecRandomCopyBytes does not matter it s always the default rng regardless.
2/ More direct call work for both iOs and macOs.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Is this something we'd want in 1.1.1 too?

**Comment by devnexen** [comment]
since 1.1.1 is stable we might leave as it is I think

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Given this is needed for OpenSSL applications being acceptable for AppStore IMO this can be treated as a bug fix.

**Pull request closed without merging**
