### PR TITLE
apps/ca.c: only output DER with SPKAC input and when -out is chosen

### LINKED ISSUE #8055: ca behaviour with -spkac and stdout changed/broke text interface in 1.1.0i
Since around 1.1.0i, the following openssl ca command (with -spkac option and no -out option, i.e. use stdout) now generates binary certificate details rather than text (which breaks applications that parse that output):

```
OPENSSL_ENABLE_MD5_VERIFY=1 openssl ca -config test.openssl.cnf -passin stdin -batch -spkac input_file -startdate 190121130654Z
```

```
Check that the SPKAC request matches the signature
Signature ok
Certificate Details:
...
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            Netscape Cert Type: 
                SSL Client
...
Certificate is to be certified until Jan 19 01:58:28 2029 GMT (3650 days)

Write out database with 1 new entries
...(elided binary goop)...
```

This was observed in openssl-1.1.0i from Fedora 28:
openssl-1.1.0i-1.fc28.x86_64

In earlier versions it would output the PEM format Base64 encoded certificate data in a block surrounded with:
```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

This interface change/breakage is quite painful.

### PR DESCRIPTION
**Pull request by levitte**
So say the docs

Fixes #8055

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
I have checked that this behaves as advertised. The advertised behaviour is pretty weird if you ask me (i.e. its does in binary if -out is specified and using -spkac, otherwise PEM is used)...but still.

**Comment by levitte** [comment]
I agree re weirdness, but you know, historical reasons...

**Comment by levitte** [comment]
Merged

69f6b3ceaba493e70e1296880ea6c93e40714f0f apps/ca.c: only output DER with SPKAC input and when -out is chosen

**Comment by xnox** [comment]
@mattcaswell @levitte ping, still don't see this in 1.1.1 branch

**Comment by levitte** [comment]
Oops, that was an oversight indeed. Please feel free... Otherwise I will do it in a couple of hours (currently on the road)

**Comment by levitte** [comment]
Merged into 1.1.1:

2ec8ad1bd8b1ae7a61ae8fe46a5633a1b50c0049 apps/ca.c: only output DER with SPKAC input and when -out is chosen

**Pull request closed without merging**
