### PR TITLE
Digest function deprecation CHANGES.

### PR DESCRIPTION
**Pull request by paulidale**
Add a changes entry to cover the deprecation of the low level digest functions.

### CODE REVIEW

**Comment by paulidale** [comment]
The function list will be reformatted once complete.

**Comment by paulidale** [comment]
Move out of WIP, although not all the digests have been deprecated yet.

**Comment by paulidale** [comment]
Once #10791 is merged, this CHANGES entry will be complete and accurate.

**Comment by levitte** [comment]
Shouldn't there be a NEWS entry as well?  Duplicating the first CHANGES sentence should be enough.

**Comment by paulidale** [comment]
Would it be better to say that the "Cipher, digest, MAC and public key low level functions are deprecated" in NEWS?

I'm happy to make each algorithm type individual...

**Comment by levitte** [comment]
If you look at the NEWS items for 1.1.1, you can see how we've done it before.  Following that pattern, it seems like a repeat of that first sentence is more fitting.

**Comment by paulidale** [comment]
NEWS updated.

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
