### PR TITLE
cms: Do not try to check binary format on stdin and -rctform fix

### LINKED ISSUE #16195: cms stdin parsing regression
We've found a regression related to `openssl cms` stdin context parsing on decryption.

OpenSSL 3.0-beta3 dev output:
```
cat bug.txt |LD_LIBRARY_PATH=. apps/openssl cms -inkey privkey.pem -recip cert.pem -decrypt
Error reading SMIME Content Info
C091DDB71E7F0000:error:068000D1:asn1 encoding routines:SMIME_read_ASN1_ex:no content type:crypto/asn1/asn_mime.c:415:
```
bug.txt is a regular S/MIME format:
```
MIME-Version: 1.0
Content-Disposition: attachment; filename="Certificates.p7m"
Content-Type: application/x-pkcs7-mime; name="Certificates.p7m"
Content-Transfer-Encoding: base64

(Some base64 content)
```
OpenSSL 1.1.1 successfully decrypts the same file in the same circumstances.

### PR DESCRIPTION
**Pull request by t8m**
Two issues in the cms application are fixed by this PR.

Fixes #16195

### CODE REVIEW

**Comment by beldmit** [comment]
Do we have the same problem with smime?

**Comment by t8m** [comment]
> Do we have the same problem with smime?

No, there is no such warn_binary() check there.

**Review by beldmit — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master. Thank you for the reviews.

**Comment by sahanaprasad07** [comment]
@t8m Hi Tomas, we continue to notice the same error
'cat input.cms | openssl cms -decrypt -in /dev/stdin -inkey TransportPrivate.pem -recip TransportCert.pem | openssl pkcs12 -nodes -password pass:'
Error reading SMIME Content Info
805BEF99767F0000:error:068000D1:asn1 encoding routines:SMIME_read_ASN1_ex:no content type:crypto/asn1/asn_mime.c:415:

**Pull request closed without merging**
