### PR TITLE
Fix dtls mtu test.c

### PR DESCRIPTION
**Pull request by EasySec**
dtl_mtu_test doesn't follow BIO_* conventions and make Windows build fail

### CODE REVIEW

**Comment by kroeckx** [comment]
This all seems to contain other changes.

**Comment by EasySec** [comment]
Yes, sorry, I am still having trouble with my repo and TortoiseGit. I amTrying to just add the 1 modified file to this PR...
:-(

**Comment by richsalz** [comment]
Save a copy of the one file you want to  change.  Start a brand new repo cloned from master.  Create a branch for your change. Restore your saved copy of that one file.  Add and commit that one file.  Push the change to github.

**Comment by EasySec** [comment]
That's exactly what I made for this PR. Don't understand what I missed...
Will try again.

**Comment by EasySec** [comment]
Finally succeeded (but not yet understood what happened)
Again, sorry for the noise :-(
What a big trouble for such a little change.

**Comment by levitte** [comment]
Reviewed and merged.

**Pull request closed without merging**
