### PR TITLE
Fix SYNOPSIS for ASN1_ENUMERATED_get_int64 and ASN1_ENUMERATED_set_int64

### PR DESCRIPTION
**Pull request by bukka**
Fixed declarations of ASN1_ENUMERATED_get_int64 and ASN1_ENUMERATED_set_int64 that don't match the implementation type for `a`.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
@levitte I assume your approval on #9807 holds here?

**Comment by mspncp** [comment]
Is this ready for merge, or does this need to be revisited?

**Comment by bukka** [comment]
It's ready from my side...

**Comment by mattcaswell** [comment]
Pushed to master and 1.1.1. Thanks!

**Pull request closed without merging**
