### PR TITLE
coding style: remove extra whitespace charactor

### PR DESCRIPTION
**Pull request by hongliang5316**
Fix coding style.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
IMHO this needs obviously no CLA

**Comment by t-j-h** [comment]
But these neeed CLA trivial from the author first!!!!

**Comment by hongliang5316** [comment]
@t-j-h 
Do you have any idea to fix this? 
I do not know how to fix it.

**Comment by t-j-h** [comment]
You can edit the commit message - or just note it here in the comments that you agree this is CLA: trivial and then when the person who does the actual merge does the work they will fix it up.

See https://help.github.com/articles/changing-a-commit-message/

**Comment by hongliang5316** [comment]
@t-j-h 
Okay, i agree this is CLA:  trivial and then when the person who does the actual merge does the work they will fix it up.
Will you merge this PR to master? many thanks!

**Comment by bernd-edlinger** [comment]
Merged, thanks!

**Pull request closed without merging**
