### PR TITLE
Update and apply patches from RT-2275

### PR DESCRIPTION
**Pull request by xoloki**

### CODE REVIEW

**Comment by richsalz** [comment]
+1 way cool, thanks.  waiting for another dev team member to do this now.

**Comment by levitte** [comment]
I'll have a closer look in a couple of hours

**Comment by kroeckx** [comment]
@levitte: That couple of hours was a week ago.  Still plan to look at it?

**Comment by levitte** [comment]
@xoloki, could you rebase this on a fresh master?

**Comment by xoloki** [comment]
Done @levitte.

**Comment by levitte** [comment]
This is ready to be merged.  @richsalz, wanna do it?

**Comment by richsalz** [comment]
Sure, I'll do it now.  Thanks!

**Comment by richsalz** [comment]
done with 27f172d  (I had to move the new error code from 6 to 7).  closing the RT ticket now.

**Pull request closed without merging**
