### PR TITLE
Use ctx2 instead ctx.

### PR DESCRIPTION
**Pull request by Richard-Koenning**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
Looks ok - and it looks trivial to me from a CLA perspective.

@Richard-Koenning if you agree please can you amend your commit message to include the text "CLA: tivial" in a line on its own the body of the message.

**Comment by kaduk** [comment]
Looks okay to me, too, and I agree it is trivial.

**Comment by kaduk** [comment]
@mattcaswell I added the 1.1.1 label since the bug is present there as well; your comments so far are ambiguous as to whether it should be merged back to that branch as well.

**Comment by mattcaswell** [comment]
Yes. 1.1.1 too. Whoever merges will have to remove the merge commit.

**Comment by kaduk** [comment]
I will plan to do the merge, to save Matt's time for 3.0 stuff

**Comment by kaduk** [comment]
Pushed to master and 1.1.1; closing.
Thanks for submitting the fix!

**Pull request closed without merging**
