### PR TITLE
ASN1_item_verify_ctx(): Return -1 on fatal errors

### LINKED ISSUE #24575: In OpenSSL 3, ASN1_item_verify*() can return 2 on error.
Introduced in https://github.com/openssl/openssl/pull/10942  as part of extracting `ASN1_item_verify_ctx()` from `ASN1_item_verify()` when a `ret = -1;` was deleted after the `goto err` here:

https://github.com/openssl/openssl/blob/5bbdbce856c7ca132e039a24a315618484874c81/crypto/asn1/a_verify.c#L143-L154

If `item_verify()` returns `2` (which it usually will for RSA-PSS for example) the control flow would skip here and return 2 if `ASN1_item_i2d()` errors:

https://github.com/openssl/openssl/blob/5bbdbce856c7ca132e039a24a315618484874c81/crypto/asn1/a_verify.c#L202-L210

### PR DESCRIPTION
**Pull request by t8m**
Fixes #24575

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]

**Review by nhorman — APPROVED** [review]

**Comment by botovq** [comment]
> Presumably a non-regression test would be quite a bit of work (i.e. not worth it)?

@tom-cosgrove-arm The output of the simple program below is this because `ASN1_item_i2d()` fails on NULL input and `item_verify()` ignores its `data` parameter:

```shell
$ ./a.out
2
00000000:error:068C0103:asn1 encoding routines:ASN1_item_verify_ctx:internal error:crypto/asn1/a_verify.c:204:
```

the cert is [./test/certs/ca-pss-cert.pem][1]. Should be easy to hook this into your test framework if you want to do it.

```C
#include <openssl/asn1.h>
#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/x509.h>

static const char *pss_cert =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDXjCCAhagAwIBAgIBAjA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCAaEa\n"
    "MBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgGiAwIBIDASMRAwDgYDVQQDDAdSb290\n"
    "IENBMCAXDTIxMDEyNjEwMDUwOFoYDzIxMjEwMTI3MTAwNTA4WjARMQ8wDQYDVQQD\n"
    "DAZDQS1QU1MwggEgMAsGCSqGSIb3DQEBCgOCAQ8AMIIBCgKCAQEAtclsFtJOQgAC\n"
    "ZxTPn2T2ksmibRNVAnEfVCgfJxsPN3aEERgqqhWbC4LmGHRIIjQ9DpobarydJivw\n"
    "epDaiu11rgwXgenIobIVvVr2+L3ngalYdkwmmPVImNN8Ef575ybE/kVgTu9X37DJ\n"
    "t+8psfVGeFg4RKykOi7SfPCSKHKSeZUXPj9AYwZDw4HX2rhstRopXAmUzz2/uAaR\n"
    "fmU7tYOG5qhfMUpP+Ce0ZBlLE9JjasY+d20/mDFuvFEc5qjfzNqv/7okyBjaWB4h\n"
    "gwnjXASrqKlqHKVU1UyrJc76yAniimy+IoXKAELetIJGSN15GYaWJcAIs0Eybjyk\n"
    "gyAu7Zlf/wIDAQABo2AwXjAPBgNVHRMBAf8EBTADAQH/MAsGA1UdDwQEAwIBBjAd\n"
    "BgNVHQ4EFgQUGfmhA/VcxWkh7VUBHxUdHHQLgrAwHwYDVR0jBBgwFoAUjvUlrx6b\n"
    "a4Q9fICayVOcTXL3o1IwPQYJKoZIhvcNAQEKMDCgDTALBglghkgBZQMEAgGhGjAY\n"
    "BgkqhkiG9w0BAQgwCwYJYIZIAWUDBAIBogMCASADggEBAF6rSSBj+dkv0UGuE1El\n"
    "lB9zVpqVlV72RY8gAkmSJmbzblHEO/PYV/UnNJ2C2IXEhAQaE0xKCg+WC2RO56oc\n"
    "qZc6UXBCN8G9rJKVxgXVbciP4pQYN6POpmhJfQqzNPwzTADt3HY6X9gQtyG0fuQF\n"
    "OPDc+mXjRvBrcYMkAgYiKe+oA45WDWYpIvipWVQ3xP/BSGJqrdKx5SOrJA72+BLM\n"
    "bPbD3tBC2SVirDjv0N926Wcb/JQFkM+5YY2/yKNybstngr4Pb1T/tESsIZvGG2Tk\n"
    "3IhBl1dJtC9gpGTRa8NzQvcmPK9VUjWtv5YNA+FxD9FTxGibh7Aw1fbFCV91Qjc3\n"
    "JQQ=\n"
    "-----END CERTIFICATE-----\n";

int
main(void)
{
    BIO *bio = BIO_new_mem_buf(pss_cert, -1);
    X509 *x509 = PEM_read_bio_X509(bio, NULL, NULL, NULL);
    EVP_PKEY *pkey = X509_get0_pubkey(x509);
    RSA *rsa = EVP_PKEY_get1_RSA(pkey);
    const ASN1_BIT_STRING *sig = NULL;
    const X509_ALGOR *alg = NULL;

    X509_get0_signature(&sig, &alg, x509);
    EVP_PKEY_set1_RSA(pkey, rsa);

    printf("%d\n", ASN1_item_verify(ASN1_ITEM_rptr(X509_CINF),
        (X509_ALGOR *)alg, (ASN1_BIT_STRING *)sig, NULL, pkey));

    return 0;
}
```

[1]: https://github.com/openssl/openssl/blob/master/test/certs/ca-pss-cert.pem

**Review by shahsb — APPROVED** [review]

**Comment by slontis** [comment]
Thanks @botovq, @t8m can you add a test please.

**Review by tom-cosgrove-arm — APPROVED** [review]

**Comment by t8m** [comment]
ping @openssl/otc for review

**Review by nhorman — APPROVED** [review]

**Comment by t8m** [comment]
Merged to all the active branches. Thank you for the reviews.

**Pull request closed without merging**
