### PR TITLE
Fix typo in ssl_ciph.c

### PR DESCRIPTION
**Pull request by Lipovlan**
CLA: trivial

### CODE REVIEW

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

**Comment by t8m** [comment]
We do not merge PRs that just contain typo fixes in comments to stable branches. So this should go into master branch only.

@hlandau OK with CLA: trivial?

**Comment by hlandau** [comment]
OK with trivial.

**Review by tom-cosgrove-arm — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
Failing CI tests are the existing issue with CIFuzz, and unrelated. Updating labels to `approval: ready to merge`

**Comment by hlandau** [comment]
Merged to master. Thank you.

**Pull request closed without merging**
