### PR TITLE
Don't assume to know the shared library extension

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [x] CLA is signed

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
are you going to wait for travis to pass?

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
I assume this is for master and 1.1.0...my plus one counts for both.

**Comment by levitte** [comment]
I'll wait for Travis to pass

**Comment by levitte** [comment]
... and yes, master and 1.1.0.  I just keep forgetting those lables!

**Comment by levitte** [comment]
> I'll wait for Travis to pass

You know, I'm changing my mind on this, 'cause essentially, *all* builds are going to fail until this one goes on.

**Comment by levitte** [comment]
Good point, @FdaSilvaYY.  Fixed.

@richsalz, @mattcaswell, could you please reconfirm?

**Comment by mattcaswell** [comment]
reconfirmed

**Comment by richsalz** [comment]
reconfirmed

**Comment by levitte** [comment]
Merged.  Thank you very much.

**Pull request closed without merging**
