### PR TITLE
e_os file moved to the "internal" include tree

### PR DESCRIPTION
**Pull request by davxy**
Storing it with the other private header files in place of the project root directory looks more appropriate.

All the files that includes it were update accordingly:
 include "e_os.h" -> include "internal/e_os.h"

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
Nice to have, perhaps, but we have many other PR's in the backlog to look at.

**Comment by davxy** [comment]
That means that will be left pending? There is a motivation why the file is under the.root? The same applies to the /osdep/haiku.h Thanks

**Comment by richsalz** [comment]
The file is there because that's where it always was. We used to have files in the source dirs and then we created  the include directories and put them there. We just never got around to it.  My preference is that we spend time on existing PR's that have real issues, not nice-to-have, for the rest of this release.  The team may feel otherwise.

**Comment by kroeckx** [comment]
This is really a really easy PR. Approving it would have cost less
time than argueing about it.

**Comment by davxy** [comment]
I understood the point. But removing it from the the proj root was a start since has been there since the begin of the times.

**Comment by richsalz** [comment]
I'll put a -1 because of @dot-asm's argument, and because this is a distraction right now.

**Comment by kroeckx** [comment]
Are you confusing e_os.h an e_os2.h?

**Comment by richsalz** [comment]
No I am not confusing the two files.  Nor was Andy.

**Comment by kroeckx** [comment]
Then I really have no idea what you're talking about

**Comment by levitte** [comment]
I'm siding with @dot-asm here. `e_os.h` doesn't need to be moved, it needs to be split into pieces, primarily bound to different platforms. @richsalz made an attempt at this specifically for msvc stuff.
`osdep/haiku.h` is another start at the same thing. Instead of shoving yet more stuff into `e_os.h`, we placed it in an os dependent header.

All this comes from a long term intention to make a better intern architecture / platform layer, instead of a gazillion platform specific guards throughout the code.

So I think this PR is the wrong move. As @dot-asm says, there's a risk that it "legitimizes" `e_os.h` further and delays the move to the better layer I mentioned.

-1  (with thanks to @davxy for reactualising the bigger issue, even though that wasn't your intent)

**Comment by davxy** [comment]
@levitte That is clear now. Anyway I think that is a work that should be done. That's really ugly to have it in the root dir (again... IMHO). And my move is supported by two core motivs:

- e_os.h is there from the start of the times
- osdep/haiku.h has been done 2 years ago

With this peace maybe in 10 years the thing is addressed :D (just joking). 

Technically speaking I don't see the problem so challenging (maybe I'm missing some details).
I'll see if I can help in that sense after that 1.1.1 has been released

BR

**Comment by richsalz** [comment]
Moving this to post-1.1.1

**Comment by richsalz** [comment]
(If you disagree and think that this should block the 1.1.1 release, please comment.0

**Pull request closed without merging**
