### PR TITLE
Faster probable prime generator

### PR DESCRIPTION
**Pull request by erbridge**
Continue #116.

Add a function for generating a probable prime using the biased method and coprimes. Still assumes `add == 2 && rem == 1`, and only seems to give a 5-10% speed improvement on the trial division method.

@benlaurie.

### CODE REVIEW

**Comment by richsalz** [comment]
any chance of rebasing this and updating it for master?  otherwise perhaps we should close it and remove the "experimental" probably_prime function.

**Comment by erbridge** [comment]
Yup. I'm taking a look at this now.

**Comment by erbridge** [comment]
Rebased at #583.

**Comment by richsalz** [comment]
Made obsolete by #583 so closing this.

**Pull request closed without merging**
