### PR TITLE
Add OIDs for UA-PKI certification policies

### PR DESCRIPTION
**Pull request by artemMartynenko**
### Add OIDs for UA-PKI certification policies

Full list of OIDs is available on related enactment page
at [http://zakon0.rada.gov.ua/laws/show/z1399-12/page2](http://zakon0.rada.gov.ua/laws/show/z1399-12/page2)

CLA: trivial

### CODE REVIEW

**Comment by kroeckx** [comment]
I'm not sure why we should add them, you can just use something like OBJ_txt2obj() if you need to use those OIDs.

**Comment by richsalz** [comment]
It's a small change, but we're only focused on bug-fixes right now; not sure if this qualifies.

**Comment by artemMartynenko** [comment]
@richsalz , sure, I totally agree with you. I just reviewed pull request according to DSTU and other Ukrainian crypto issues and saw that not all of UA-PKI and DSTU OIDs were added, and some developers asked about. So I sink it will be useful to add other OIDs with (which were not added in pull request [5216](https://github.com/openssl/openssl/pull/5216)) and also in my request to bring maximum profit and avoid future small changes for making OpenSSL compatible with Ukrainian law. What will you say about this purpose?

**Comment by richsalz** [comment]
I understand your desires, and they make sense.  Please understand our goals and timetable.

**Comment by artemMartynenko** [comment]
@richsalz , sure, I totally understand that you have the timetable and don't want to bring you more complication. But can I ask you to advise me the next milestone after nearest release where my request can be accepted? And maybe I can make the pull request to another branch to avoiding affecting you in the nearest release?

**Comment by richsalz** [comment]
Just keep this PR here and it will get merged into the next release. Schedule is at https://www.openssl.org/policies/releasestrat.html

**Comment by kroeckx** [comment]
There are OIDs from the CAB Forum that are used way more often
that are not included in OpenSSL.

Note that I don't object, but I'm not sure where we should draw
the line in which OIDs we add.

**Comment by kroeckx** [comment]
I would also like to point out that even if this gets merged, it will probably take a long time before people actually have a version with this included. OBJ_txt2obj() clearly is a faster way to get this deployed.

**Comment by artemMartynenko** [comment]
@kroeckx, Maybe I do not clearly understand what do you mean about OBJ_txt2obj(). Can you please explain or provide some examples.

**Comment by kroeckx** [comment]
With your patch, to use the OID, you probably do use something like OBJ_nid2obj(NID_ua_pki_cp_scwl). Instead you would use OBJ_txt2obj("1.2.804.2.1.1.1.2.1", 1).

**Comment by artemMartynenko** [comment]
Unfortunately, I'm not interrupting with OpenSSL directly. I use Apache APR which use mod_ssl to communicate with OpenSSL. In my case, OpenSSL works for a certificate verification (with OCSP) in the process of user mutual authentication. (but it`s only my case). So I need a way to describe OpenSSL an OIDs for certificate verification

**Comment by kroeckx** [comment]
I don't know much about the apache / APR code. What do you need to give it? Can you show some example code?

**Comment by FdaSilvaYY** [comment]
May be https://www.openssl.org/docs/manmaster/man5/config.html can help solve this issue ?
IT allow you to declare and configure some additional OID's.

**Comment by artemMartynenko** [comment]
@FdaSilvaYY , in my case, I have those OIDs in qcStatements. When  I am trying to do `openssl verify` I get `error 34 at 0 depth lookup:unhandled critical extension`. I also Tried to add this OIDS to openssl.cnf, but it also didn`t solve a problem.

**Comment by richsalz** [comment]
If you have critical extensions, you have to add code to understand them; you cannot just add the OID's and ignore them.  The code you add can do the ignore, but the definition of critical means "must know the semantics or return an error."

This might be very hard to do in Apache.

**Comment by kroeckx** [comment]
It's the qcStatements itself that is marked as critical. If we need to add support for that being critical, we probably should do it by having a callback and let the application say the OIDs inside it are handled or not.

**Comment by t-j-h** [comment]
Can you provide real-world example certificates using these OIDs?

**Comment by outspace** [comment]
Here is example [https://czo.gov.ua/download/certificates/CZOROOT.cer](url). You can try add oid dynamically by OBJ_create(). In your case adding OIDs will not help.

**Comment by DejavuDmitry** [comment]
Okay. What's we have at the moment?

**Pull request closed without merging**
