### PR TITLE
COMP_expand_block: spelling (algorithm)

### PR DESCRIPTION
**Pull request by SergeCroise**
##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
We'll either need a CLA filled in or the line 'CLA: trivial' added to the commit message to indicate that this is a trivial change (which I think it is).

**Comment by paulidale** [comment]
From the command line: `git commit --amend` to reedit the commit message.  Add CLA: trivial on a line by itself down the bottom (best to surround this with blank lines).  Then `git push -f` to send the amended version back here.

**Review by t8m — APPROVED** [review]
I'd be OK with CLA: trivial.

**Comment by t8m** [comment]
Please do not add merge commits. Instead use git rebase to rebase the commits.

**Comment by SergeCroise** [comment]
missing CLA: trivial

**Pull request closed without merging**
