### PR TITLE
Revert "bn: Add fixed length (n=6), unrolled PPC Montgomery Multiplication"

### PR DESCRIPTION
**Pull request by t8m**
This reverts commit 0d40ca47bd86e74a95c3a2f5fb6c67cdbee93c79.

It was found that the computation produces incorrect results in some
cases.

### CODE REVIEW

**Comment by davidben** [comment]
Any tests for those cases, or is this the same tests as the mod-exp fix?

**Review by paulidale — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
Maybe add some test cases?

**Comment by beldmit** [comment]
Do we have wycherproof tests running on the platforms we support?

**Comment by t8m** [comment]
> Do we have wycherproof tests running on the platforms we support?

Only the primary ones currently and not all of them.

**Comment by t8m** [comment]
> Maybe add some test cases?

Working on that

**Comment by t8m** [comment]
Testcase added @paulidale please re-approve.
Ping for second review.

**Review by beldmit — APPROVED** [review]
LGTM.

May make sense providing a link to exact wycherproof test case, if it is doable.

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for the reviews.

**Pull request closed without merging**
