### PR TITLE
mkerr.pl: When writing internal FOOerr.h, pay attention to disablable modules

### PR DESCRIPTION
**Pull request by levitte**
If a module is disablable (i.e. can be configured with 'no-FOO'), the
resulting header file needs to be guarded with a check of the
corresponding OPENSSL_NO_FOO.  While this seem fairly innocuous, it
has an impact on the information in util/*.num, generated by mkdef.pl.

### CODE REVIEW

**Comment by levitte** [comment]
What got me worried is what's happening in #5150

**Comment by levitte** [comment]
Someone might ask why we need to be this meticulous around `ERR_load_FOO_strings` symbols.  On Linux, we don't, because even though a symbol is specified in `libcrypto.map` (generated on the fly), it's ok if that symbol is missing, the shared library will be created anyway.

Not so on VMS, or on Windows (I think)...  On those systems, symbols that are given in a `libcrypto.def` or `libcrypto.opt` *must* be defined among the object files that are used to create a shared library, or creating the latter will fail.

**Review by richsalz — APPROVED** [review]
You could make the code simpler:
```
#ifdef __cplusplus
extern "C"
#endif
ERR_load_lib...
```

**Comment by levitte** [comment]
I'd rather leave that simplification for another PR (and possibly someone else)

**Comment by mspncp** [comment]
Title of PR and commit message contain a typo: disablable

**Comment by levitte** [comment]
Hmm? What do you think it should say?

**Comment by mspncp** [comment]
Oh, I misunderstood! It’s no typo, sorry!

**Comment by levitte** [comment]
It's cool, glad we got that sorted out easily

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Merged.  cb7b7275683655537c63e42b5e3ef3d7045e4104 and 048ebccb8840f7abd90adc59654d959feb25715b

**Pull request closed without merging**
