### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by finnhakansson**
This is just a minor fix to a man page.

### CODE REVIEW

**Comment by richsalz** [comment]
@finnhakansson do you agree this is a trivial change?

**Comment by richsalz** [comment]
(sorry, but we either need a CLA or we need you to definitely say yes it's trivial)

**Comment by finnhakansson** [comment]
It is definitely trivial.

**Comment by kroeckx** [comment]
@richsalz: Feel free to merge this

**Comment by levitte** [comment]
This goes to master, 1.1.0 and 1.0.2.

**Comment by levitte** [comment]
Done, in all mentioned branches

**Pull request closed without merging**
