### PR TITLE
Add openssl/fuzz-corpora as submodule

### PR DESCRIPTION
**Pull request by t8m**
Instead of carrying the fuzz corpora data in the source code repository we move it into a submodule pulled from  https://github.com/openssl/fuzz-corpora

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Review by t-j-h — APPROVED** [review]

**Comment by t8m** [comment]
Fixup was needed - we do not want submodules for check update and check docs CI runs.

**Comment by t8m** [comment]
@levitte @t-j-h please reconfirm

**Comment by t-j-h** [comment]
Reconfirmed.

**Comment by t8m** [comment]
Additional question - do we want to move the fuzz/corpora data to submodule also in 3.1 and 3.0 branches?

**Comment by t-j-h** [comment]
I would leave stable branches alone for this sort of stuff - but I won't put a hold if others think differently.

**Comment by t8m** [comment]
> I would leave stable branches alone for this sort of stuff - but I won't put a hold if others think differently.

Yeah, unless we would like to add more testing data to older branches we can keep them as is.

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
I would actually do this same thing on the release branches too, simply to avoid all the duplication.  Stuff in new subdirectories will be ignored by them, as they won't have the corresponding fuzz testing driver.

But, I don't see a need to do this nownownow.

**Comment by slontis** [comment]
Just an observation, looking at some other builds this seems to add a few minutes of build time  to some of the builds (i.e. we are now always retrieving 10 submodules)

**Comment by paulidale** [comment]
Any chance of limiting the submodules to just the fuzzer?
I don't see an option to do this in the checkout action :disappointed:

**Comment by t8m** [comment]
> Any chance of limiting the submodules to just the fuzzer? I don't see an option to do this in the checkout action disappointed

Yeah, there is no such option. I assume we would have to call git explicitly.

**Comment by t8m** [comment]
> Assuming the last change works grin

Yeah, it seems to.

@levitte, @t-j-h please reconfirm

**Review by levitte — APPROVED** [review]

**Pull request closed without merging**
