### PR TITLE
Fix inadvertent NULL assignments in ternary ops

### PR DESCRIPTION
**Pull request by neverpanic**
As identified by both clang with a warning and `$> git grep -P '(?<![!=])= NULL \?'`

Signed-off-by: Clemens Lang <cllang@redhat.com>

##### Checklist

not applicable

### CODE REVIEW

**Comment by beldmit** [comment]
BTW, @neverpanic should be covered by Red Hat CCLA, I suppose
I'd also consider these changes trivial.

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by neverpanic** [comment]
I already have an ICLA on file, but without my Red Hat email address, so the check fails. How do I get this updated? Mail to legal@, or submit a new ICLA?

**Comment by mattcaswell** [comment]
> I already have an ICLA on file, but without my Red Hat email address, so the check fails. How do I get this updated? Mail to legal@, or submit a new ICLA?

Just an email to legal telling us that both email addresses are you should be enough

**Review by mattcaswell — APPROVED** [review]

**Comment by beldmit** [comment]
Merged. Thanks for the contribution!

**Pull request closed without merging**
