### PR TITLE
fix compile error (SIZE_MAX not found) on HP-UX

### LINKED ISSUE #21554: compile error on HP-UX (ssl/priority_queue.c) using HP compilers
compile error on HP-UX:
```
	cc  -I. -Iinclude  +Z -Ae +DD32 +Olit=all -z +W612 -D_LARGEFILE64_SOURCE +O2 -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/vobs/public/openssl/openssl-build-IBM/3.2.0/ssl\"" -DENGINESDIR="\"/vobs/public/openssl/openssl-build-IBM/3.2.0/lib/hpux32/engines-3\"" -DMODULESDIR="\"/vobs/public/openssl/openssl-build-IBM/3.2.0/lib/hpux32/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -D_HPUX_ALT_XOPEN_SOCKET_API -DNDEBUG   -c -o ssl/libssl-lib-priority_queue.o ssl/priority_queue.c
"ssl/priority_queue.c", line 63: error #2020: identifier "SIZE_MAX" is undefined
          SIZE_MAX / (sizeof(struct pq_heap_st) > sizeof(struct pq_elem_st)
```
Looks like `ssl/priority_queue.c` needs to include `internal/numbers.h` ?

```
perl configdata.pm --dump

Command line (with current working directory = .):

    /opt/rational/common/bin/ratlperl ./Configure hpux-ia64-cc-ctg --prefix=/vobs/public/openssl/openssl-build-IBM/3.2.0 no-rc5 threads shared

Perl information:

    ratlperl
    5.16.1 for IA64.ARCHREV_0-thread-multi-64int

Enabled features:

    apps
    argon2
    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    default-thread-pool
    deprecated
    des
    dgram
    dh
    docs
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    ecx
    engine
    err
    filenames
    gost
    http
    idea
    legacy
    loadereng
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    quic
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    thread-pool
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    acvp-tests          [cascade]        OPENSSL_NO_ACVP_TESTS
    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
    asan                [default]        OPENSSL_NO_ASAN
    brotli              [default]        OPENSSL_NO_BROTLI
    brotli-dynamic      [default]        OPENSSL_NO_BROTLI_DYNAMIC
    buildtest-c++       [default]        
    winstore            [not-windows]    OPENSSL_NO_WINSTORE
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [default]        OPENSSL_NO_EGD
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fips                [default]        
    fips-securitychecks [cascade]        OPENSSL_NO_FIPS_SECURITYCHECKS
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    ktls                [default]        OPENSSL_NO_KTLS
    makedepend          [unavailable]    
    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]        OPENSSL_NO_MSAN
    rc5                 [option]         OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                [default]        OPENSSL_NO_SCTP
    tfo                 [default]        OPENSSL_NO_TFO
    trace               [default]        OPENSSL_NO_TRACE
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]        OPENSSL_NO_ZLIB
    zlib-dynamic        [default]        OPENSSL_NO_ZLIB_DYNAMIC
    zstd                [default]        OPENSSL_NO_ZSTD
    zstd-dynamic        [default]        OPENSSL_NO_ZSTD_DYNAMIC
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "qc",
    CC => "cc",
    CFLAGS => "+O2",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    asm_arch => "ia64_32",
    bin_lflags => "-Wl,+s,+cdp,../:,+cdp,./:",
    bn_ops => "SIXTY_FOUR_BIT MD2_CHAR RC4_INDEX DES_UNROLL DES_RISC1 DES_INT",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-Ae +DD32 +Olit=all -z +W612 -D_LARGEFILE64_SOURCE",
    cppflags => "-D_REENTRANT",
    defines => [ "OPENSSL_BUILDING_OPENSSL", "_XOPEN_SOURCE", "_XOPEN_SOURCE_EXTENDED", "_HPUX_ALT_XOPEN_SOCKET_API" ],
    disable => [  ],
    dso_scheme => "dlfcn",
    enable => [  ],
    ex_libs => "-ldl -lpthread",
    includes => [  ],
    lflags => "-Wl,+b,/opt/rational/common/shlib\\:/usr/lib/hpux32",
    lib_cflags => "",
    lib_cppflags => "-DB_ENDIAN",
    lib_defines => [  ],
    module_cflags => "+Z",
    module_cxxflags => undef,
    module_ldflags => "-b -Wl,-B,symbolic,+vnocompatwarnings,-z,+s,+cdp,../:,+cdp,./:",
    multilib => "/hpux32",
    perl_platform => "Unix",
    perlasm_scheme => "void",
    shared_cflag => "+Z",
    shared_defines => [  ],
    shared_ldflag => "-b -Wl,-B,symbolic,+vnocompatwarnings,-z,+s,+cdp,../:,+cdp,./:",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,+h,",
    shared_target => "hpux-shared",
    shlib_variant => "-ratl",
    thread_cflag => "-mt",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = /opt/rational/common/bin/ratlperl
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar
    ARFLAGS         = qc
    ASFLAGS         = 
    CC              = cc
    CFLAGS          = +O2
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /opt/rational/common/bin/ratlperl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = /opt/rational/common/bin/ratlperl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
```

and the config stanza:
```
	"hpux-ia64-cc-ctg" => {
		inherit_from 	=> [ "hpux-ia64-cc" ],
		asm_arch => "ia64_32",
		cflags			=> add("+W612 -D_LARGEFILE64_SOURCE"),
		# CFLAGS			=> "+O0",
		thread_cflag	=> add("-mt"),
		lflags			=> add("-Wl,+b,/opt/rational/common/shlib\\:/usr/lib/hpux32"),
		bn_ops			=> add("MD2_CHAR RC4_INDEX DES_UNROLL DES_RISC1 DES_INT"),
		shared_target	=> "hpux-shared",
		shlib_variant   => "-ratl",
	},

```

### PR DESCRIPTION
**Pull request by johnkohl-hcl**
Fixes #21554

CLA: trivial

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
I agree this is trivial

**Review by hlandau — APPROVED** [review]
Agree trivial

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Agreed trivial.

**Comment by paulidale** [comment]
Merged, thanks for the fix.

**Pull request closed without merging**
