### PR TITLE
Store delete 3

### PR DESCRIPTION
**Pull request by beldmit**
Trying to improve #21901 and avoid code duplication.

We create an operation context containing all the data via store_open, pass it to delete callback, and let the provider to deal with it. Then we close the store after the operation.

##### Checklist
- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
@simo5 one more approach

**Comment by simo5** [comment]
I do not see the difference from the previous, and having parallel PRs makes diff hard

**Comment by beldmit** [comment]
The public API is the same. The internal implementation is open-delete-close

**Comment by beldmit** [comment]
I can. It seems to me it causes a lot of code duplication :(

**Comment by beldmit** [comment]
Closing in favor of #21901

**Pull request closed without merging**
