### PR TITLE
  Add X509_get0_authority_key_id() function

### PR DESCRIPTION
**Pull request by opencrypto**
Add X509_get0_authority_key_id() function  

This function makes it easier to retrieve a reference to the
authority key identifier (akid->keyid) inside a certificate.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by opencrypto** [comment]
BTW: Just sent the CLA via e-mail.

**Comment by richsalz** [comment]
Let's kick the CLA bot.

**Comment by richsalz** [comment]
Is this needed in 1.1.0?  It could be backported as we'd treat it as a bugfix because of making everything opaque.

**Comment by dot-asm** [comment]
Needs re-base...

**Comment by Romain-Geissler** [comment]
Hi,

Any update on this pull request ? What is missing except the rebase on top of recent commits ?

Cheers,
Romain

**Comment by richsalz** [comment]
Max needs to rebase and make sure the CI builds are clean.  Or someone needs to take over and do a new PR using this one.

**Comment by mattcaswell** [comment]
This PR seems to have stalled. We seem to be waiting on a rebase @opencrypto. Although it also looks like an additional commit has been added at some point for some additional OCSP functions that seem unrelated to the original intent of this PR. I think that commit should be separated out to a different PR. The X509_get0_authority_key_id() is function seems quite straight forward and can be backported. But the OCSP stuff looks like new functionality that can't.

**Comment by Romain-Geissler-1A** [comment]
Hi,

FYI, X509_get0_authority_key_id() has been merged (and even backported to 1.1.x) already.

Cheers,
Romain

**Comment by mattcaswell** [comment]
> FYI, X509_get0_authority_key_id() has been merged (and even backported to 1.1.x) already.

Ah! Right - thanks for pointing this out. In which case I think this PR should be closed.

**Pull request closed without merging**
