### PR TITLE
CI fixes and workarounds for the recent CI failures

### PR DESCRIPTION
**Pull request by t8m**
Fuzz checker CI: Use more generic include dir for fuzzer includes.

Cross compiles CI: Disable stringop-overflow warning on s390x and m68k

Run-checker merge CI: Replace no-shared with no-modules

### CODE REVIEW

**Review by levitte — APPROVED** [review]
Ok urgent

**Comment by t8m** [comment]
@levitte one more fix added, please reconfirm. The last failure should be fixed with #19841 - I wonder though, why it wasn't detected before.

**Review by hlandau — APPROVED** [review]
Agree urgent.

**Comment by slontis** [comment]
There was still a failure here..

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Agreed, urgent and merged to all three branches.  The remain CI failure should be a separate PR IMO.

**Pull request closed without merging**
