### PR TITLE
SSL: refactor ssl_cert_lookup_by_pkey() to work with provider side keys

### LINKED ISSUE #11720: ssl_cert_lookup_by_pkey() assumes the EVP_PKEY contains legacy internal key
There are two ways to deal with this:

- downgrade the input key (this should be a *temporary* measure)
- change it to deal with provider side internal keys as well (this should be the ultimate result, before the final 3.0 release)

Ref: https://github.com/openssl/openssl/issues/11549#issuecomment-623297414

### PR DESCRIPTION
**Pull request by levitte**
Fixes #11720

### CODE REVIEW

**Comment by levitte** [comment]
Temporarly in WIP, until I feel confident enough

**Comment by levitte** [comment]
Good thing I made this tentative...  this wasn't entirely error free

**Comment by levitte** [comment]
> this wasn't entirely error free

... it turned out to be a small thing.

Now out of WIP

**Comment by mattcaswell** [comment]
The Travis failure looks odd - but not related to this PR.

**Comment by beldmit** [comment]
Gost engine tests are passed.

**Comment by levitte** [comment]
Rebased to get rid of the odd Travis failure

**Comment by levitte** [comment]
Merged

92dc275f95a5a87465a1ae3bac54bb2ead9732ca SSL: refactor ssl_cert_lookup_by_pkey() to work with provider side keys

**Pull request closed without merging**
