### PR TITLE
Fix CRLF help messages

### PR DESCRIPTION
**Pull request by blar**
Fix help messages for CRLF

##### Checklist
- [x] documentation is added or updated

CLA: trivial

### CODE REVIEW

**Comment by t8m** [comment]
This would be acceptable with CLA: trivial. Could you please amend the commit message to contain `CLA: trivial` on a separate line in the commit message body? You can use `git commit --amend ; git push --force` to do that.

**Review by tmshort — APPROVED** [review]
Agree with trivial.

**Review by shahsb — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]
okay with trivial

**Comment by tom-cosgrove-arm** [comment]
@t8m would you mind reviewing for @openssl/otc ?

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

**Comment by t8m** [comment]
Merged to all the active branches with slightly tweaked commit message. Thank you for your contribution.

**Pull request closed without merging**
