### PR TITLE
Fix "Error finalizing cipher loop" when running openssl speed -evp -decrypt

### LINKED ISSUE #23657: "Error finalizing cipher loop" when running openssl speed -evp -decrypt
Despite #20291 and its fix in #20306 (which I reviewed 🙁) I am still seeing

```
$ openssl speed -evp aes-128-gcm -decrypt
Doing AES-128-GCM ops for 3s on 16 size blocks: Error finalizing cipher loop
78635252 AES-128-GCM ops in 2.99s
Doing AES-128-GCM ops for 3s on 64 size blocks: Error finalizing cipher loop
71754219 AES-128-GCM ops in 3.00s
Doing AES-128-GCM ops for 3s on 256 size blocks: Error finalizing cipher loop
36803208 AES-128-GCM ops in 3.00s
Doing AES-128-GCM ops for 3s on 1024 size blocks: Error finalizing cipher loop
12900790 AES-128-GCM ops in 3.00s
Doing AES-128-GCM ops for 3s on 8192 size blocks: Error finalizing cipher loop
1823445 AES-128-GCM ops in 3.00s
Doing AES-128-GCM ops for 3s on 16384 size blocks: Error finalizing cipher loop
916364 AES-128-GCM ops in 3.00s
version: 3.3.0-dev
built on: Thu Feb 22 09:43:53 2024 UTC
options: bn(64,64)
compiler: clang -fPIC -pthread -m64 -Wa,--noexecstack -Qunused-arguments -Wall -O3 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-missing-field-initializers -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0x7ed8320b078bffff:0x400004219c91a9
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
AES-128-GCM     420790.65k  1530756.67k  3140540.42k  4403469.65k  4979220.48k  5004569.26k
```

on all systems I use: macOS/arm64, Linux/aarch64 and Linux/x86_64.

Builds were simply

```
ryzen $ perl Configure   
Configuring OpenSSL version 3.3.0-dev for target linux-x86_64
:
ryzen $ make -j20
:
make[1]: Leaving directory '/home/tom/projects/openssl/master'
ryzen $ echo $?
0
ryzen $ LD_LIBRARY_PATH=. apps/openssl speed -evp aes-128-gcm -decrypt
Doing AES-128-GCM ops for 3s on 16 size blocks: Error finalizing cipher loop
78635252 AES-128-GCM ops in 2.99s
:
```

```
m2-pro $ perl Configure
Configuring OpenSSL version 3.3.0-dev for target darwin64-arm64
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile
Created include/openssl/configuration.h
:
m2-pro $ make -j12
:
${LDCMD:-cc} -arch arm64 -O3 -Wall -L. -Wl,-search_paths_first  \
		-o test/uitest \
		apps/lib/uitest-bin-apps_ui.o test/uitest-bin-uitest.o \
		-lssl test/libtestutil.a -lcrypto  
m2-pro $ echo $?
0
m2-pro $ DYLD_LIBRARY_PATH=. apps/openssl speed -evp aes-128-gcm -decrypt
Doing AES-128-GCM ops for 3s on 16 size blocks: Error finalizing cipher loop
210051952 AES-128-GCM ops in 2.97s
```

```
ubuntu-22.04-aarch64 $ perl Configure CC=clang-15
Configuring OpenSSL version 3.3.0-dev for target linux-aarch64
Using os-specific seed configuration
:
ubuntu-22.04-aarch64 $ make -j4
:
${LDCMD:-clang-15} -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -L.   \
	-o test/uitest \
	apps/lib/uitest-bin-apps_ui.o test/uitest-bin-uitest.o \
	-lssl test/libtestutil.a -lcrypto -ldl -pthread 
make[1]: Leaving directory '/media/psf/Home/home/tom/projects/openssl/master'
ubuntu-22.04-aarch64 $ echo $?
0
ubuntu-22.04-aarch64 $ LD_LIBRARY_PATH=. apps/openssl speed -evp aes-128-gcm -decrypt
Doing AES-128-GCM ops for 3s on 16 size blocks: Error finalizing cipher loop
211134220 AES-128-GCM ops in 2.99s
```

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
When using CCM, openssl speed uses the loop function EVP_Update_loop_ccm() which sets a (fake) tag when decrypting. When using -aead (which benchmarks a different sequence than normal, to be comparable to TLS operation), the loop function EVP_Update_loop_aead() is used, which also sets a tag when decrypting.

However, when using defaults, the loop function EVP_Update_loop() is used, which does not set a tag on decryption, leading to "Error finalizing cipher loop".

To fix this, set a fake tag value if we're doing decryption on an AEAD cipher in EVP_Update_loop(). We don't check the return value: this shouldn't really be able to fail, and if it does, the following EVP_DecryptUpdate() is almost certain to fail, so that can catch it.

The decryption is certain to fail (well, almost certain, but with a very low probability of success), but this is no worse than at present. This minimal change means that future benchmarking data should be comparable to previous benchmarking data.

(This is benchmarking code: don't write real apps like this!)

Fixes #23657

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
This is silencing a warning, so not sure if it counts as a bug fix or a cleanup

**Review by t8m — APPROVED** [review]
IMO this is a bug fix and eligible for stable branches.

**Review by InfoHunter — APPROVED** [review]
Glad to see this get fixed!

**Comment by t8m** [comment]
Merged to all the active branches. Thank you for your contribution.

**Comment by ravulapx** [comment]
Still seeing "Error finalizing cipher loop" in master branch with sm4-gcm -decrypt.
 
image
image

**Pull request closed without merging**
