### PR TITLE
Fix function documentation

### PR DESCRIPTION
**Pull request by ecnepsnai**
##### Checklist

- [x] documentation is added or updated

##### Description of change

Fixed function documentation for some methods in `ec.h`

### CODE REVIEW

**Comment by ecnepsnai** [comment]
CLA submitted. Really need a web form to do that.

**Comment by richsalz** [comment]
No Webform, we need a signature.

**Comment by richsalz** [comment]
These look pretty trivial to me.  If you agree, add "CLA: trivial" to the text of the commit message, (commit --amend) and push -f.

**Comment by richsalz** [comment]
CLA on file, thank you!  Just needs another reviewer.

**Comment by levitte** [comment]
Merged.

master: f5fd3848fe5033534b92d2d18ed6fbd16741a0a2
1.1.0: f4944142b82d557799c2a73361202a07a54fd69d

**Pull request closed without merging**
