### PR TITLE
FIPS friendly the MD5-SHA1 digest.

### PR DESCRIPTION
**Pull request by paulidale**
This likely depends on some of the design decisions that will be upcoming in the FIPS planning.  This particular one will need to be addressed in some form at some stage.  I'd be happy if it wasn't in this form.

Rework the combined MD5-SHA1 digest into a form that uses EVP internally rather than calling the low level digest functions directly.  An engine can still override this and implement the algorithm directly.

This produces a performance loss.  However, the TLS stack looks like it tries to not use this if it can and it is only used in TLS 1.1 and earlier.  I tried `EVP_MD_CTX_FLAG_CLEANED` and `EVP_MD_CTX_FLAG_REUSE` but neither helped the _speed_ measurements.

If this isn't acceptable for the main line code, it could still be useful
later as part of a FIPS solution.

- [x] tests are added or updated

### CODE REVIEW

**Comment by dot-asm** [comment]
I for one am against "self-dependency" at EVP ciphers/digests levels. I mean EVP ciphers/digest should not call EVP. Or at least should do so as absolutely last resort. So that if this actually has to be done that way, then it should be done only when needed. In the context, when FIPS mode of operation is actually requested/engaged. Well, this specific digest is not actually interesting/critical, so argument is rather against suggested approach in general.

**Comment by paulidale** [comment]
This doesn't have to be done this way.  There are a few options:

1. If the padding needs to be inside the FIPS boundary, then the old code could be used as is.
2. If the padding is okay outside, this code can be used from outside the FIPS boundary.
3. If we don't care about supporting this functionality, the old code should be used from outside the FIPS boundary.
4. The design, once it is done, might present a totally different way to do this.
5. I'm sure there are other things I've not considered.

I'm betting on 2 but there isn't certainty at this stage.

I also wonder why the objection to implementing a compound algorithm this way?  EVP calls itself in several places (HMAC e.g.) and MD5-SHA1 isn't a primitive algorithm.

What I will do, is move the new test cases to a separate PR since they are useful immediately and leave this as just the MD5-SHA1 changes pending more planning.

**Comment by fatz7812** [comment]
Y

**Comment by paulidale** [comment]
Should this one be closed and redone if required?

**Comment by paulidale** [comment]
Closing after a week without comments about closing this or not.

**Pull request closed without merging**
