### PR TITLE
quic: redraw the overview diagram using dot

### PR DESCRIPTION
**Pull request by paulidale**
- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by hlandau — CHANGES_REQUESTED** [review]
Should this not update the Markdown file to point to the new image and remove the old one?

I guess dot can also output SVG, which might be preferable.

**Comment by paulidale** [comment]
Yes, forgot to include that update yesterday.  Yes, dot can produce SVG.  PNG is more widely supported and I don't see a requirement for image scaling here.

**Comment by t8m** [comment]
I am not quite sure I like this more than the original SVG. But I certainly won't block this if others prefer this one.

**Comment by paulidale** [comment]
The original does look better.  However, this one is editable :grinning:

**Comment by levitte** [comment]
SVG is editable too 😜

But most of all, dot is not made for layered graphs. The chaotic result isn't worth this change 😕

**Comment by paulidale** [comment]
@levitte, I challenge you to edit the original with Inkscape.

**Comment by t8m** [comment]
I can add the LibreOffice original later. That should be editable reasonably.

4. 7. 2022 8:14, 8:14, Pauli ***@***.***> napsal/a:
***@***.***, I challenge you to edit the original with Inkscape.

**Comment by levitte** [comment]
> SVG files are not editable with a text editor.

I wonder what it was I've edited in emacs, then... 😉

**Comment by paulidale** [comment]
> I wonder what it was I've edited in emacs, then... wink

Cool, sound like you volunteered to add "framing" and "deframing" boxes and all the relevant links.  Fixing the splines ought to be a heap of fun :grin:

Seriously, adding these with dot is trivial.  Adding them using LibreOffice's draw is more than a little work moving all the lines etc.  I am expecting that this diagram will be updated multiple times before we're done.  Make that easy, even if it costs some prettiness.

**Comment by levitte** [comment]
If the hierarchical / layered bit can be preserved with dot, I'm 100% for it. If not, then not so much.

**Comment by paulidale** [comment]
Please explain.  I don't understand.

**Comment by levitte** [comment]
[sigh]

The old picture shows the layering of what's supposed to be going on between the SSL API and the kernel, as far as we've imagined it.  The new picture lost that information, it's essentially all over the place, or rather, no where.

**Comment by paulidale** [comment]
You want the SSL API box at the top and the Kernel at the bottom and the rest between?
The write and read paths are stacked vertically, I ensure that bit.  The rest was kind of scattered so didn't bother trying to order it.

**Comment by paulidale** [comment]
Look at the last and second from last alternatives.  The last does what I think @levitte wants, the second from last adds some highlighting that shows what I think he wants.

The second from last is far easier to modify since it's not forcing vertical positioning.  I think it's less cluttered and easier to comprehend.

**Comment by paulidale** [comment]
LO Draw isn't as easy to make changes with as dot but it's good enough I think.

**Pull request closed without merging**
