### PR TITLE
Missed a mention of RT

### PR DESCRIPTION
**Pull request by richsalz**
Missed on mention of rt.
For all release branches.

### CODE REVIEW

**Comment by richsalz** [comment]
```
  OpenSSL_1_0_1-stable ca88f01 [origin/OpenSSL_1_0_1-stable] Missed a mention of RT
  OpenSSL_1_0_2-stable 95873c5 [origin/OpenSSL_1_0_2-stable] Missed a mention of RT
  OpenSSL_1_1_0-stable dc691e8 [origin/OpenSSL_1_1_0-stable] Missed a mention of RT
* master               1e62cc1 [origin/master] Missed a mention of RT
```

**Comment by FdaSilvaYY** [comment]
There is one more remaining mention of RT :
https://wiki.openssl.org/index.php/Use_of_Git#Making_patches

**Comment by richsalz** [comment]
made a bunch of edits to the wiki, thanks @FdaSilvaYY!

**Comment by FdaSilvaYY** [comment]
Have you try this :
https://wiki.openssl.org/index.php?title=Special%3ASearch&search=RT&go=Go
I just think a it, few seconds ago.

**Comment by richsalz** [comment]
I don't know about the manpage-on-wiki stuff, the "process" is outdated, and the "developing for" is also outdated, to be replaced by the web "getting started" maybe.

**Pull request closed without merging**
