### PR TITLE
TEST: Display the correct shared library name

### PR DESCRIPTION
**Pull request by levitte**
In test/recipes/01-test_symbol_presence.t

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Please note that MacOS build regressed due to the earlier test/recipes/01-test_symbol_presence.t fix.

**Comment by mattcaswell** [comment]
Should we just skip this test on macos? Its a developer thing really

**Comment by levitte** [comment]
> Should we just skip this test on macos? Its a developer thing really

I pushed an extra commit that does exactly that

**Comment by levitte** [comment]
Because of the regression, I made this urgent

**Review by mattcaswell — APPROVED** [review]
Approved. Agreed urgent. The Windows CI failures are not relevant (a power failure knocked out the nasm website...its just come back up).

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.

**Pull request closed without merging**
