### PR TITLE
Fix typographical error in 80-test_cms.t ( missing ; )

### PR DESCRIPTION
**Pull request by rsbeckerca**
Fixes: #22045

CLA: Trivial

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by rsbeckerca** [comment]
This applies to OpenSSL 3.0 only. 3.1 and 3.2 are correct.

**Comment by beldmit** [comment]
If the current CI fails, I'd say it's urgent

**Comment by rsbeckerca** [comment]
> If the current CI fails, I'd say it's urgent

@beldmit That's why I opened the issue and PR. :)

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM - I think this is urgent, as the CI is currently broken

**Comment by beldmit** [comment]
Pushed. Thanks!

**Comment by paulidale** [comment]
Thanks for the quick fix here.

**Comment by rsbeckerca** [comment]
> Thanks for the quick fix here.

YW. It passed on the NonStop CI build/test, btw.

**Pull request closed without merging**
