### PR TITLE
Apps: change provider_path option to provider-path.

### PR DESCRIPTION
**Pull request by paulidale**
The applications use '-' in options not '_'.

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
Merged to master, thanks.

**Comment by richsalz** [comment]
Lots still exist; cmp is new in 3.0, right? Worth adding aliases for all the others?

```
; g grep -c '{".*_.*OPT_'
ca.c:8
ciphers.c:3
cmp.c:42
cms.c:19
crl.c:1
dgst.c:1
ec.c:4
ecparam.c:5
fipsinstall.c:5
include/opt.h:21
ocsp.c:18
pkcs7.c:1
pkcs8.c:3
pkey.c:3
pkeyutl.c:2
req.c:2
rsa.c:2
s_client.c:38
s_server.c:44
s_time.c:3
speed.c:1
ts.c:3
verify.c:2
x509.c:9
; 
```

**Comment by paulidale** [comment]
I'm not sure, it would be nice to have aliases but it adds clutter to the code base.  Removing the `_` versions would be nigh on impossible.

**Comment by richsalz** [comment]
The cmp command is new for 3.0 and perhaps should be fixed.

**Pull request closed without merging**
