### PR TITLE
Clear the error before handle and change the error stack priority

### LINKED ISSUE #8470: SSL_get_error return value was not expect in some case
Version: OpenSSL1.1.1
Scenario: 
      The application call some other OpenSSL API and did not call ERR_clear_error() in every place. and SSL_read return failed in case of socket non-block error. and the expected error currently is SSL_ERROR_WANT_READ. but the actual error was SSL_ERROR_SSL, as the error stack have keeped some other error which have pushed before SSL_read. 
Adapter:
...
Some other OpenSSL API. //error stack did not clear with ERR_clear_error().
...
k = SSL_read(con, sbuf, 1024 /* BUFSIZZ */ );
switch (SSL_get_error(con, k)) {
...
case SSL_ERROR_WANT_WRITE:
...
case SSL_ERROR_WANT_READ:
...
case SSL_ERROR_SSL: 
...
}

Analysis:
The error stack did not clear in the beginning of SSL_read and SSL_get_error will try to get the error with ERR_peek_error firstly. state_machine have clear the error, so SSL_dohandshake  will not report such error.

int SSL_get_error(const SSL *s, int i){
...
    if ((l = ERR_peek_error()) != 0) {
        if (ERR_GET_LIB(l) == ERR_LIB_SYS)
            return SSL_ERROR_SYSCALL;
        else
            return SSL_ERROR_SSL;
    }
    if (SSL_want_read(s)) {
        bio = SSL_get_rbio(s);
        if (BIO_should_read(bio))
            return SSL_ERROR_WANT_READ;
        else if (BIO_should_write(bio))
            return SSL_ERROR_WANT_WRITE;
...
}

static int state_machine(SSL *s, int server){
...
    ERR_clear_error();
    clear_sys_error();
...
}

Suggestion:
1 Clear the error stack at the beginning of SSL_read/SSL_write/SSL_shutdown.
2 move the SSL_want_read logic before the ERR_peek_error,so that the SSL_ERROR_WANT_READ/ SSL_ERROR_WANT_WRITE have the high priority and will reported Correctly when the application missed to clear some error before SSL_read.
int SSL_get_error(const SSL *s, int i){
...
    if ((l = ERR_peek_error()) != 0) {
        if (ERR_GET_LIB(l) == ERR_LIB_SYS)
            return SSL_ERROR_SYSCALL;
        else
            return SSL_ERROR_SSL;
    }
    if (SSL_want_read(s)) {
        bio = SSL_get_rbio(s);
        if (BIO_should_read(bio))
            return SSL_ERROR_WANT_READ;
        else if (BIO_should_write(bio))
            return SSL_ERROR_WANT_WRITE;
...
}

### PR DESCRIPTION
**Pull request by KanPlus**
Fix #8470

### CODE REVIEW

**Comment by mattcaswell** [comment]
I am not keen on this change. Clearing the error queue as part of every IO call seems like a "nuclear" option and over kill.

IMO the inspection of the error stack in `SSL_get_error()` is really nasty and hacky. It's been there since forever, but it really should not be necessary since in the event of any error going onto the error stack we should have called `ossl_statem_fatal` - so we should *know* that the connection has failed without having to resort to looking at the error stack. Distinguishing between SSL_ERROR_SSL and SSL_ERROR_SYSCALL might be tricker - but still should be achievable.

**Comment by kaduk** [comment]
> IMO the inspection of the error stack in `SSL_get_error()` is really nasty and hacky. It's been there since forever, but it really should not be necessary since in the event of any error going onto the error stack we should have called `ossl_statem_fatal` - so we should _know_ that the connection has failed without having to resort to looking at the error stack.

We should have called `ossl_statem_fatal`, yes, but bugs in this space are inevitable.  That said, the symptoms when we fail to call `ossl_statem_fatal` are, while admittedly fairly opaque messages, not actually harmful from a security perspective. (If I remember correctly.)  So it's probably reasonable to proceed down a path that presumes we've called it where needed.

**Comment by KanPlus** [comment]
> 
ossl_statem_fatal push the error with ERR_LIB_SSL, this limited ossl_statem_fatal called in the failed case in ssl libs, this may not the indicate the origin error.

**Comment by KanPlus** [comment]
> ossl_statem_fatal push the error with ERR_LIB_SSL, this limited ossl_statem_fatal called in the failed case in ssl libs, this may not the indicate the origin error.

ossl_statem_fatal push the error with ERR_LIB_SSL, this limited ossl_statem_fatal called in the failed case in ssl libs, this may not the indicate the origin error.

**Comment by KanPlus** [comment]
> I am not keen on this change. Clearing the error queue as part of every IO call seems like a "nuclear" option and over kill.
> 
> IMO the inspection of the error stack in `SSL_get_error()` is really nasty and hacky. It's been there since forever, but it really should not be necessary since in the event of any error going onto the error stack we should have called `ossl_statem_fatal` - so we should _know_ that the connection has failed without having to resort to looking at the error stack. Distinguishing between SSL_ERROR_SSL and SSL_ERROR_SYSCALL might be tricker - but still should be achievable.

ossl_statem_fatal push the error with ERR_LIB_SSL, this limited ossl_statem_fatal called in the failed case in ssl libs, this may not the indicate the origin error.

**Comment by KanPlus** [comment]
> That said, the symptoms when we fail to call `ossl_statem_fatal` are
    SSL_get_error used to obtain result code for TLS/SSL I/O operation, ossl_statem_fatal will only indicate the error in SSL operation.

**Comment by mattcaswell** [comment]
> We should have called ossl_statem_fatal, yes, but bugs in this space are inevitable. That said, the symptoms when we fail to call ossl_statem_fatal are, while admittedly fairly opaque messages, not actually harmful from a security perspective. (If I remember correctly.) So it's probably reasonable to proceed down a path that presumes we've called it where needed.

When `ossl_statem_fatal` is called it sets `s->statem.in_init` to true and `s->statem.state` to `MSG_FLOW_ERROR`. I consider this a much more reliable indicator of whether we are in an unrecoverable error state than checking the error stack. It is those variables that we check in various locations throughout libssl via the `check_fatal` macro and the `ossl_statem_in_error()` functions - and we abort if set. It is a bit anomalous that we use a different test in `SSL_get_error` to what the rest of libssl uses.

We don't currently have an easy way to test whether we should return `SSL_ERROR_SYSCALL` or `SSL_ERROR_SSL` - but I would prefer to detect that at the time of the syscall failure and set a new state variable accordingly, e.g. everywhere we do a `BIO_read` or `BIO_write` call that fails and `BIO_should_retry` returns false then we assume a syscall error failure...or something like that.

**Comment by KanPlus** [comment]
> > We should have called ossl_statem_fatal, yes, but bugs in this space are inevitable. That said, the symptoms when we fail to call ossl_statem_fatal are, while admittedly fairly opaque messages, not actually harmful from a security perspective. (If I remember correctly.) So it's probably reasonable to proceed down a path that presumes we've called it where needed.
> 
> When `ossl_statem_fatal` is called it sets `s->statem.in_init` to true and `s->statem.state` to `MSG_FLOW_ERROR`. I consider this a much more reliable indicator of whether we are in an unrecoverable error state than checking the error stack. It is those variables that we check in various locations throughout libssl via the `check_fatal` macro and the `ossl_statem_in_error()` functions - and we abort if set. It is a bit anomalous that we use a different test in `SSL_get_error` to what the rest of libssl uses.
> 
> We don't currently have an easy way to test whether we should return `SSL_ERROR_SYSCALL` or `SSL_ERROR_SSL` - but I would prefer to detect that at the time of the syscall failure and set a new state variable accordingly, e.g. everywhere we do a `BIO_read` or `BIO_write` call that fails and `BIO_should_retry` returns false then we assume a syscall error failure...or something like that.

This seems better, I will check further,thanks.

**Comment by KanPlus** [comment]
> > > We should have called ossl_statem_fatal, yes, but bugs in this space are inevitable. That said, the symptoms when we fail to call ossl_statem_fatal are, while admittedly fairly opaque messages, not actually harmful from a security perspective. (If I remember correctly.) So it's probably reasonable to proceed down a path that presumes we've called it where needed.
> > 
> > 
> > When `ossl_statem_fatal` is called it sets `s->statem.in_init` to true and `s->statem.state` to `MSG_FLOW_ERROR`. I consider this a much more reliable indicator of whether we are in an unrecoverable error state than checking the error stack. It is those variables that we check in various locations throughout libssl via the `check_fatal` macro and the `ossl_statem_in_error()` functions - and we abort if set. It is a bit anomalous that we use a different test in `SSL_get_error` to what the rest of libssl uses.
> > We don't currently have an easy way to test whether we should return `SSL_ERROR_SYSCALL` or `SSL_ERROR_SSL` - but I would prefer to detect that at the time of the syscall failure and set a new state variable accordingly, e.g. everywhere we do a `BIO_read` or `BIO_write` call that fails and `BIO_should_retry` returns false then we assume a syscall error failure...or something like that.
> 
> This seems better, I will check further,thanks.

The application will get the non-blocking and keep the error stack by Fetching the IO status with high priority.
As the base changed so much, I will close this PR and raised #18559

**Pull request closed without merging**
