### PR TITLE
Copyright update of more files that have changed this year [1.1.0]

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
My script had a slight fault. I've corrected it and recommitted. Please reconfirm

**Review by paulidale — APPROVED** [review]
Reconfirmed.

**Comment by mattcaswell** [comment]
@levitte looks like this is ready to merge.

**Review by tgabb68 — APPROVED** [review]

**Comment by mattcaswell** [comment]
Ping @levitte

**Comment by levitte** [comment]
Because we've decided to do this automagically when releasing, I see no point with this PR any more. Closing it.

**Pull request closed without merging**
