### PR TITLE
support parse sm2 key encryped by legacy or 1.1.1

### PR DESCRIPTION
**Pull request by lan1120**
fix https://github.com/openssl/openssl/issues/21036

### CODE REVIEW

**Comment by t8m** [comment]
Could you please add a testcase?

**Comment by lan1120** [comment]
I will add a testcase

**Comment by t8m** [comment]
ping, are you still interested in adding the testcase?

**Comment by lan1120** [comment]
I'm sorry to be so late with this PR. It should be clarified that this PR does not solve the problem that the SM2 encryption key is generated in version 1.1.1, it depends https://github.com/openssl/openssl/pull/20488 @JerryDevis

Describe the test scenario again:
OpenSSL version：master
Command line test：
(1) openssl genpkey -algorithm SM2 -out sig.key or ./apps/openssl ecparam -name SM2 -genkey -out sm2.key
(2) openssl ec -in sig.key -sm4 -out sig.key.enc
(3) openssl ec -noout -text -in sig.key.enc or ./apps/openssl pkey -noout -text -in sig.key.enc

if use "./apps/openssl pkey -in sig.key -sm4 -out sig.key.enc" to encrypt, there will be no problems. so is this PR still necessary?

**Comment by t8m** [comment]
Could you please drop the merge commit?

**Comment by levitte** [comment]
Er....  why are we adding an SM2 PEM type? Encoding-wise, they do not differ from EC keys, as we have finally (and repeatedly) determined in #22184

**Comment by mattcaswell** [comment]
It seems no progress has been made on this PR.

Perhaps it should be closed and reopened if @lan1120 is able to make progress on it?

**Pull request closed without merging**
