### PR TITLE
Fix a misuse of NULL check

### PR DESCRIPTION
**Pull request by liwg06**
Fixes: #17356

### CODE REVIEW

**Review by kaduk — APPROVED** [review]
Change seems to be good on the face of it, but there's always some risk that other consumers have come to depend on the weird behavior.  It seems unlikely that we will detect any with our current test suite, though...

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
I am OK with CLA: trivial.

**Comment by t8m** [comment]
@kaduk Can you please confirm if you are OK with CLA:trivial?

**Comment by kaduk** [comment]
Yes, I am OK with CLA:trivial

**Comment by liwg06** [comment]
That's fine. Thanks @t8m @kaduk for the approval and discussion.

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
