### PR TITLE
Add propq to RAND_get0_public(), etc

### PR DESCRIPTION
**Pull request by slontis**
This PR relates to issue #14286

Open question:
    In this PR - How do we propagate the propq to the keymanager
    dh_newdata() recieves a libctx but does not recieve a propq,
    and then we also have import and export functionality also.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
The `RAND_get0_` calls are sufficiently different to the rest to justify separate consideration.  Once the DRBG/RNGs are instantiated in a libctx, the propq **can never** be used.  Instead the libctx argument for these functions is used to select the DRBG/RNG from the libctx.

That it serves a double purpose currently isn't great.  I do not believe that adding the propq is the right way to go.

**Comment by slontis** [comment]
Happy to close it again if we decided this is not a good idea.
Note that this is related to the question raised by PR #14064

**Comment by paulidale** [comment]
The non-RAND ones are fine.  RAND is different, that's all.

**Comment by slontis** [comment]
> The non-RAND ones are fine. RAND is different, that's all.

Yes but this really all bubbles up from the RAND calls. Otherwise the propq is not really needed, right?

**Comment by t8m** [comment]
If you need special handling for RAND you should set it up in advance. I do not think adding propq to all calls where RAND is used makes sense.

**Comment by richsalz** [comment]
This change is going to make things ugly for application developers.  If the project is still planning on revisiting and change the `RAND` API in the near future, stop futzing with what there is now.

**Comment by paulidale** [comment]
The RAND APIs are staying.  `RAND_get_bytes()` is pretty much the perfect API just as it is.

What's going is the fluff around engines (i.e. RAND_METHOD).

**Comment by richsalz** [comment]
> What's going is the fluff around engines (i.e. RAND_METHOD).

I know.  I still think you should just leave it alone for now.

**Comment by paulidale** [comment]
I suggest we close this one.  The RAND_get0_() calls are not using the library context like any other call that takes a propq and they shouldn't be made to since it won't do what's expected.

**Comment by slontis** [comment]
This is kind of related to the OTC hold on https://github.com/openssl/openssl/pull/14064. I will at least link it to there..

**Pull request closed without merging**
