### PR TITLE
Add configuration option no-alpn.

### LINKED ISSUE #16625: `./Configure no-alpn`?
I want to create the minimal OCI image, providing LDAP with OpenLDAP.  In the LDAP world NPN and ALPN are not used.  I call `./Configure no-nextprotoneg` to disable NPN.  I want in addition to disable ALPN.

* Add an option to disable ALPN, so that the (static) libraries (libssl and libcrypto) and the binaries (using static libraries) get smaller.

### PR DESCRIPTION
**Pull request by slontis**
Fixes #16625

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Note that in  #16625 @kaduk objects to doing this.. So I will put a hold on it..

**Comment by kaduk** [comment]
https://alpaca-attack.com/ is another reference that is perhaps relevant; it served as something of a trigger or prompt for increased evangelism for ALPN use in the IETF.

**Comment by slontis** [comment]
This still relies on the user setting up the ALPN extension....

**Comment by mattcaswell** [comment]
From #16625:

> Add an option to disable ALPN, so that the (static) libraries (libssl and libcrypto) and the binaries (using static libraries) get smaller.

How much smaller do the binaries get with this option applied compared to when its not?

**Comment by slontis** [comment]
> How much smaller do the binaries get with this option applied compared to when its not?

Numbers from  macOS with
> ./config -Werror --strict-warnings [no-alpn]

libcrypto is not affected as all the changes are in ssl code.
libcrypto.a          6,805,896
libcrypto.3.dylib 3,942,984

                      alpn        no_alpn
libssl.a          913,104   905,320
libssl.3.dylib 659,616   658,888

So maybe it is not worth it (when compared to the size of libcrypto)?

**Comment by t8m** [comment]
OTC: We do not see any real need for having no-alpn as a build time configuration option. There is not much to spare by switching it off.
Closing.

**Pull request closed without merging**
