### PR TITLE
quic http3 demo: minor updates

### PR DESCRIPTION
**Pull request by jamuir**
-update run command to include LD_LIBRARY_PATH
-suggest installing libnghttp3-dev on Ubuntu

Part of https://github.com/openssl/project/issues/253

### CODE REVIEW

**Review by hlandau — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Review by hlandau — APPROVED** [review]
Please don't force push and use fixup commits when changing commits.

**Comment by jamuir** [comment]
> Please don't force push and use fixup commits when changing commits.

coincidentally, I was going to that up at the next wg :-)

My last update (after approvals were given) dropped an unnecessary "-f" flag from the "clean" recipe, so I think I need new approvals from the others.

**Comment by paulidale** [comment]
Keeping the `-f` avoids getting errors when not everything being cleaned is present.
I'd prefer to see it retained.

**Comment by jamuir** [comment]
> Keeping the `-f` avoids getting errors when not everything being cleaned is present. I'd prefer to see it retained.

`-f` is still being used.  It is part of the variable `$(RM)`.

**Comment by paulidale** [comment]
Merged, thanks.

**Comment by jamuir** [comment]
Thanks, Pauli.

**Pull request closed without merging**
