### PR TITLE
WIP: Add a chacha20 based RNG

### PR DESCRIPTION
**Pull request by kroeckx**
This is a WIP, I need to check that what I'm doing actually makes sense.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
Any thoughts as to why this is better than #4019 ?

**Comment by t-j-h** [comment]
There is nothing in here that is chacha20 specific - this could just be a general RNG approach for using a cipher as the base. 
As currently written you are always using a fixed all-zeros key as the starting point and simply adding in RAND_poll output then switching to a new key that is the output of the encrypt of that information. An interesting approach to take - and entirely generic (in that the user could reasonable use any cipher as the basis for this approach).

**Comment by mspncp** [comment]
The DRGB concept described in NIST SP 800-90A provides for having different algorithms to generate random output. In fact, there used to be two more (not counting the infamous Dual_EC) of which only RAND_DRBG_CTR survived in #4019.  

However, the DRBG concept is much more than just about random bit generation. It has a clear concept for reseeding and chaining. Only the chaining part is new, the rest originates from the FIPS DRBG which has extensively been tested and evaluated.

So why not also have alternative implementations such as  RAND_DRBG_CHACHA20 (or even RAND_DRBG_EJB implementingn [ejb's fast key-erasure algorithm](https://blog.cr.yp.to/20170723-random.html)? That would be great?

**Comment by kroeckx** [comment]
As far as I can see, the main difference between djb's fastrandombytes and this are:
- He just reads the key from the kernel, but we have an API that allows you to give an entropy value that's different than the size that you gave so I need a way to deal with that
- He seems to just keeps the nonce at 0, I've been wondering what I should do with the nonce.
- He clears the bytes he has read from the buffer, which is probably a good idea
- He used an uninitialized buffer for encrypting?

**Comment by kroeckx** [comment]
I made some minor changes, so that it's closer to djb's fastrandombytes.

I would really like someone to say if this design for an RNG makes sense or not.

I'm wondering how I should test this. I at least believe that if you call RAND_add() with the same values it should give the same output.

**Comment by paulidale** [comment]
Would this be worth revisiting after the rands go into providers (#11682)?  The DRBG infrastructure there would allow it to be added without having to worry about lots of the nitty gritty.

I think an alternative to the NIST DRBGs would be accepted and used.

**Comment by richsalz** [comment]
It's been DRBG since 1.1.1 released in Sept 2018 and nobody has asked for this.

**Comment by kroeckx** [comment]
Sure, it just looks like I don't have time for it.

**Pull request closed without merging**
