### PR TITLE
KTLS: use EVP_CIPHER_is_a instead of nid

### PR DESCRIPTION
**Pull request by uudiin**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
The question is whether this should be considered a bug fix eligible for backport to 3.0?

**Comment by t8m** [comment]
> The question is whether this should be considered a bug fix eligible for backport to 3.0?

What bug does it fix? I do not see any rationale.

**Comment by paulidale** [comment]
I think it's the case where a third party provider implements a cipher not then being able to offload to the kernel.  I.e. one of our built in implementations would need to be fetched rather than a third party.

**Comment by t8m** [comment]
> I think it's the case where a third party provider implements a cipher not then being able to offload to the kernel. I.e. one of our built in implementations would need to be fetched rather than a third party.

Shouldn't the EVP_CIPHER_get_nid() work correctly if the cipher is one of these that have the NID even if it is implemented externally?

**Comment by paulidale** [comment]
I didn't spend too long looking but the code looks like it uses the integer ID that is allocated per lib ctx.  This won't match the NID in general.

**Comment by uudiin** [comment]
> Shouldn't the EVP_CIPHER_get_nid() work correctly if the cipher is one of these that have the NID even if it is implemented externally?

The latest linux kernel KTLS supports the SM4 GCM/CCM algorithm. In OpenSSL, these two algorithms have no NID, only the implementation of the provider. I believe that more algorithms will be supported in the kernel in the future. Thus, it is difficult to support this type of algorithm by using NID.

**Comment by paulidale** [comment]
That's a better reason :)

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
> The question is whether this should be considered a bug fix eligible for backport to 3.0?

I think so.

**Comment by levitte** [comment]
> > The question is whether this should be considered a bug fix eligible for backport to 3.0?
> 
> I think so. A cherry-pick should suffice

I've labeled accordingly.  Should there be disagreement, feel free to remove or place a hold on this

**Comment by InfoHunter** [comment]
Pushed to master (ff3e4508bde0d7f7ab211ca9f027bef820ba1d70) and 3.0 (ff3e4508bde0d7f7ab211ca9f027bef820ba1d70). Thanks for the contribution, closing...

**Pull request closed without merging**
