### PR TITLE
Update gost-engine to fix API rename

### PR DESCRIPTION
**Pull request by beldmit**
[extended tests]

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
> Approved assuming CIs pass. Was this a newly introduced API for 3.0 that got renamed?

It was EVP_MAC_CTX/EVP_MAC_ctx/EVP_MAC_CTX renaming
I don't remember when it was introduced.

**Comment by mattcaswell** [comment]
> It was EVP_MAC_CTX/EVP_MAC_ctx/EVP_MAC_CTX renaming

Ah, ok. That's new for 3.0 so its never been in a public release.

**Comment by beldmit** [comment]
95-test_external_gost_engine.t .. ok

The Travis failure is related to BoringSSL, so I assume the approval persists.

**Comment by mattcaswell** [comment]
> so I assume the approval persists.

It does.

**Comment by beldmit** [comment]
Merged. Thanks!

**Pull request closed without merging**
