### PR TITLE
hpke.h, thread.h: Add extern "C" for C++ inclusion

### LINKED ISSUE #21305: Undefined reference to `OSSL_set_max_threads`
Hello,

I built openssl from master branch (with `./Configure no-deprecated no-apps`) and installed it (`sudo make install_sw`). But I'm having a problem with compiling a program which has openssl as dependency. If I use `OSSL_set_max_threads`, it will fail with 

```
/usr/bin/ld: /tmp/cc0eDR8y.o: in function `main':
main.cpp:(.text+0x16c): undefined reference to `OSSL_set_max_threads(ossl_lib_ctx_st*, unsigned long)'
collect2: error: ld returned 1 exit status
```

If i remove usage of that function from the code, it does compile and everything else from openssl works properly. In `configuration.h` macro `OPENSSL_THREADS` is being defined. So it does seem to have multithreading enabled. But I can't understand what's the problem.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #21305

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by beldmit** [comment]
Is it worth having smth like a header-nits for it?

**Comment by paulidale** [comment]
> Is it worth having smth like a header-nits for it?

Definitely.

**Comment by t8m** [comment]
> Is it worth having smth like a header-nits for it?

Sure, but it should not be required for this PR.

It is also a little bit non-trivial as we have multiple headers where there are just defines which do not need the `extern "C"`.

**Comment by paulidale** [comment]
What about something along the lines of:
- find a function definition
- write a C++ program that calls that function (with NULL / zero arguments)
- try to compile & link it

Alternatively, find all function definitions and call them all.

Definitely not for this PR.

**Comment by paulidale** [comment]
merged

**Pull request closed without merging**
