### PR TITLE
Update gost-engine sub-module to match EVP_MAC renaming

### PR DESCRIPTION
**Pull request by beldmit**
[extended tests]

Depends on #12121

### CODE REVIEW

**Comment by beldmit** [comment]
@paulidale, should this PR be labeled as urgent?

**Comment by levitte** [comment]
I'd suggest changing "gost-engine commit" to "gost-engine submodule" in the commit message.  That is, after all, what you're doing...

**Comment by paulidale** [comment]
The OpenSSL side is urgent since it is build breaking in two ways.  I suspect that this should also be urgent since it addresses one of the breaks.

Unfortunately, I can't set labels on this repo.

**Comment by beldmit** [comment]
I mean this PR. Your PR to gost-engine is already merged, so I want to update the commit for openssl extended tests

**Comment by beldmit** [comment]
Need to re-run tests when #12121 is merged.

**Comment by beldmit** [comment]
@paulidale , Travis is happy

**Comment by beldmit** [comment]
Ping @paulidale

**Comment by paulidale** [comment]
Oops, this slipped past.

**Comment by paulidale** [comment]
Merged to master.

**Pull request closed without merging**
