### PR TITLE
bio_err.c: remove a reappeared filename comment

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by kroeckx** [comment]
Maybe this is causing by running make update?

**Comment by levitte** [comment]
Ah, that's quite likely yes...

**Comment by levitte** [comment]
(just marked it "reviewed", all it needs is a second reviewer)

**Comment by richsalz** [comment]
+1 if you want to merge this.

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
