### PR TITLE
Add platform certificate and CAdES OIDs

### PR DESCRIPTION
**Pull request by JonathanWilbur**
Signed-off-by: Jonathan M. Wilbur <jonathan@wilbur.space>

### CODE REVIEW

**Comment by JonathanWilbur** [comment]
Replaces #16265

**Comment by t8m** [comment]
Please do make update and add that change to the commit.

**Comment by JonathanWilbur** [comment]
FYI, I am trying to get `jonathan.wilbur@wildboarsoftware.com` added to the contributor license agreement database. That is my own sole proprietorship. Obviously, I authorize me to submit this PR. 😄 

The email that I have been using for sign-off is already present in the CLA database.

**Comment by JonathanWilbur** [comment]
Closing. I'll just create a separate PR for the platform certificate OIDs, since the CAdES OIDs were already merged in.

**Pull request closed without merging**
