### PR TITLE
Add short name "Email" to "emailAddress" object

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [X] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
References:
https://ldapwiki.com/wiki/EmailAddress
It apparently used to be used in PHP4:
https://www.php.net/manual/en/function.openssl-x509-parse.php
As suggested by @t-j-h:
https://www.oasis-open.org/committees/download.php/57150/CertificateAttributes.pdf
Microsoft (although there appear to be typos in EEMAIL, GGivenName and SST):
https://docs.microsoft.com/en-us/windows/desktop/api/certenroll/nn-certenroll-ix500distinguishedname
So, not a standard, but common use (even though Email/emailAddress itself seems to be deprecated).

**Comment by petrovr** [comment]
Todd Short wrote:
> References:
> https://ldapwiki.com/wiki/EmailAddress
> It apparently used to be used in PHP4:
> https://www.php.net/manual/en/function.openssl-x509-parse.php
> As suggested by @t-j-h:
> https://www.oasis-open.org/committees/download.php/57150/CertificateAttributes.pdf
> Microsoft (although there appear to be typos in EEMAIL, GGivenName and SST):
> https://docs.microsoft.com/en-us/windows/desktop/api/certenroll/nn-certenroll-ix500distinguishedname
> So, not a standard, but common use (even though Email/emailAddress itself seems to be deprecated).
>
Quite interesting list with references .

It was in OpenSSL.
Looking into my notes 
(https://gitlab.com/secsh/pkixssh/blob/master/ssh-x509.c#L536) it is 
removed in 0.9.7, i.e. OpenSSL supports only official attribute - 
emailAddress  (rfc2459).


Regards,
Roumen Petrov

**Comment by kroeckx** [comment]
The references don't seem to be very convincing.

**Comment by kaduk** [comment]
Yeah, per http://rt.openssl.org/Ticket/Display.html?id=3723 OpenSSL has been all-"emailAddress" since 2002.

**Comment by tmshort** [comment]
But, @kaduk it also indicates that it was removed without much reasoning.

**Comment by tmshort** [comment]
It sounds as though it's leaning towards "no" for this commit? I'll close it if that's the case. @kroeckx @kaduk

**Comment by kaduk** [comment]
My personal stance is that the current state has been the de facto state of affairs for enough releases that changing it back would be a regression rather than a regression fix.  That is, "leaning towards 'no'", as you say.

**Comment by kroeckx** [comment]
I'm also leaning towards no

**Comment by tmshort** [comment]
Ok, based on feedback, I will close this. It's not a big diff for us to keep in our own set of patches.

**Pull request closed without merging**
