### PR TITLE
Add des ciphers to default provider

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
I did try moving this cipher into the legacy provider, but because it pulls in rand there is a dependency chain.. Will look into this in another PR.

**Comment by levitte** [comment]
Intuitively, that would mean we could do with a RAND libcrypto\<-\>provider interface, i.e. make RAND implementations fetchable.

**Comment by paulidale** [comment]
> Intuitively, that would mean we could do with a RAND libcrypto<->provider interface, i.e. make RAND implementations fetchable.

I think that this is desirable.  Both the RAND calls and the entropy seeding calls should be independent fetchable.

**Comment by slontis** [comment]
Thanks for reviewing.. Merged to master.

**Comment by mattcaswell** [comment]
> Intuitively, that would mean we could do with a RAND libcrypto<->provider interface, i.e. make RAND implementations fetchable.

Oh, yes. I always thought that we would do this eventually.

**Comment by paulidale** [comment]
We **need** RAND from providers.  FIPS mandates that the DRBGs are inside the module boundary.

I'd like to see the entropy/randomness source also be inside the boundary, even though it defers to the kernel/OS.

When I get a chance, I was planning on looking into this.

**Comment by mattcaswell** [comment]
> We need RAND from providers. FIPS mandates that the DRBGs are inside the module boundary.

The DRBGs are already inside the module boundary. There is a difference though between making the DRBGs be inside the module boundary and making them fetchable. We have the former already - we need to do some more work to have the latter.

**Comment by paulidale** [comment]
I'll have to think on this and maybe check up.  The DRBGs aren't in the `providers/fips` directory which could have confounded me.  I've had a bit of this recently :(

Fetchable would be ideal but probably not essential.  How else do we **guarantee** that the rest of libcrypto, libssl and the calling application are getting the "right" RNG?  I don't think we easily can as things currently stand.

I'll dig deeper this week...

**Comment by levitte** [comment]
> Fetchable would be ideal but probably not essential.  How else do we **guarantee** that the rest of libcrypto, libssl and the calling application are getting the "right" RNG?

Where is this guarantee needed?  That would be inside the FIPS module, right?  So the solution would be an internal fetch of the RAND implementation, wouldn't it, just like we're already going to do internal fetches of MDs in relation to asymmetric crypto?

**Comment by paulidale** [comment]
Moving this off-topic discussion to the project list.

**Pull request closed without merging**
