### PR TITLE
Support the attributeMappings X.509v3 Extension

### PR DESCRIPTION
**Pull request by JonathanWilbur**
This PR adds support for the `attributeMappings` X.509v3 extension defined in ITU-T Recommendation X.509 for usage in attribute certificates.

For reference, the ASN.1 definition of this extension is as follows:

```asn1
attributeMappings EXTENSION ::= {
  SYNTAX         AttributeMappings
  IDENTIFIED BY  id-ce-attributeMappings }

AttributeMappings ::= SET OF CHOICE {
  typeMappings      [0]  SEQUENCE {
    local             [0]  AttributeType,
    remote            [1]  AttributeType,
    ... },
  typeValueMappings [1]  SEQUENCE {
    local             [0]  AttributeTypeAndValue,
    remote            [1]  AttributeTypeAndValue,
    ... } }

AttributeType ::= OBJECT IDENTIFIER
```

##### Checklist
- [x] tests are added or updated

### CODE REVIEW

**Comment by JonathanWilbur** [comment]
The full output of `./apps/openssl x509 -text -noout -in ./test/certs/ext-attributeMappings.pem` is:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 203569230 (0xc22384e)
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: CN=Hi mom
        Validity
            Not Before: Dec 12 19:37:08 2022 GMT
            Not After : Dec 12 19:37:08 2022 GMT
        Subject: CN=Hi mom
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b6:78:cb:9b:5b:6c:d6:10:b8:7c:d3:6d:dd:49:
                    d0:0f:dc:bb:dd:b0:d7:82:2a:13:c9:66:12:23:77:
                    1a:fc:a3:5f:b9:3c:9d:8c:54:c4:60:09:aa:9e:e1:
                    ab:04:e5:1f:81:b9:87:dc:f4:50:d0:09:a9:aa:58:
                    e0:59:36:f7:77:72:bc:1f:85:05:bc:35:90:4c:f4:
                    92:db:52:0c:8e:6f:28:a9:dd:7d:9c:4e:46:c5:68:
                    ab:1a:ed:28:0d:1c:e1:58:b1:de:d5:16:7b:66:ba:
                    21:08:f8:3f:d4:e7:2c:cb:8e:d0:66:e2:b6:95:a1:
                    41:d2:b1:26:ad:15:81:98:46:1b:0e:5d:ff:c3:17:
                    f9:5d:fa:88:aa:93:b2:9c:90:74:da:d8:57:ad:30:
                    9c:4c:ce:d1:cf:51:6a:08:5b:7f:65:56:41:e6:12:
                    98:d9:2f:82:4d:d1:3d:38:85:4a:96:be:16:1c:c7:
                    ee:bd:46:1e:3a:3d:3a:1a:4c:0b:14:91:cd:bf:6b:
                    54:fa:da:2f:23:79:98:47:15:2e:63:85:2e:a6:44:
                    b7:30:2f:8e:b5:ec:bb:5c:a9:b5:3f:e2:0d:8d:65:
                    a8:7a:09:ba:88:20:2d:dd:5b:ac:a5:5c:fe:ea:95:
                    36:c6:09:77:9e:b0:15:31:01:c1:e1:f4:5e:40:f1:
                    f4:a5
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Attribute Mappings: 
                commonName == localityName
                commonName:asdf == localityName:03:3E

    Signature Algorithm: sha1WithRSAEncryption
    Signature Value:
```

**Comment by JonathanWilbur** [comment]
This PR is ready for review. I believe the style validation failure is in error.

**Comment by t8m** [comment]
This needs rebase to resolve conflicts.

**Review by t8m — APPROVED** [review]

**Comment by JonathanWilbur** [comment]
@nhorman would you care to review?

**Review by nhorman — APPROVED** [review]

**Comment by JonathanWilbur** [comment]
Hello, @t8m can this get merged? I would be able to rebase my other PRs then.

**Comment by mattcaswell** [comment]
Pushed to master. Thanks for your contribution.

**Comment by mattcaswell** [comment]
Hmmm. CI failures in master as a result of this PR. See for example:

https://github.com/openssl/openssl/actions/runs/12466143014/job/34793145184?pr=26247

Seems to be because #26188 got merged that adds extra doc-nits checks, but that happened after CI was run for this PR.

**Comment by JonathanWilbur** [comment]
I see. I'll create a PR to fix it.

**Comment by JonathanWilbur** [comment]
@mattcaswell PR to fix the CI failures here: https://github.com/openssl/openssl/pull/26250

**Pull request closed without merging**
