### PR TITLE
Fix rpath-related Linux "test_shlibload" failure. [1.1.0]

### PR DESCRIPTION
**Pull request by levitte**
When libssl and libcrypto are compiled on Linux with "-rpath", but
not "--enable-new-dtags", the RPATH takes precedence over
LD_LIBRARY_PATH, and we end up running with the wrong libraries.
This is resolved by using full (or at least relative, rather than
just the filename to be found on LD_LIBRARY_PATH) paths to the
shared objects.

-----

This is a backport of #7626

### CODE REVIEW

**Comment by vdukhovni** [comment]
Thanks. Looks promising, will let you know how the tests went shortly...

**Review by vdukhovni — APPROVED** [review]
This is good to go.  Moving on to the 1.1.1 version next...

**Comment by levitte** [comment]
Appveyor disagrees with you...  hold on

**Review by vdukhovni — APPROVED** [review]
Reconfirming.

**Comment by levitte** [comment]
Thanks.  Merged

841303dad2d0bb28db2317d36ef430e73d137d3d test/recipes/90-test_shlibload.t needs $target{shared_extension}
75711510f08c33f55c40b89b21cb71d1a1679abf Fix rpath-related Linux "test_shlibload" failure.

**Pull request closed without merging**
