### PR TITLE
Implement TLSv1.3 anti replay protection

### PR DESCRIPTION
**Pull request by mattcaswell**
This implements replay protection when using early_data. Essentially it forces single use tickets whenever max_early_data > 0 on the server.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
Question: Should there be an option to disable this?

Also - I think this should be in the beta.

**Comment by mattcaswell** [comment]
I realised I forgot to mention external PSKs in the documentation, so I pushed a fixup commit to add something about that.

**Comment by kroeckx** [comment]
The test suite segfaults.

I'm wondering 2 things:
- What happens on the client side? Will it also not reuse the session, or will it just attempt to use it and hope the server does the right thing?
- Why do we have an internal cache when the applications also has an external cache?

**Comment by mattcaswell** [comment]
> What happens on the client side? Will it also not reuse the session, or will it just attempt to use it and hope the server does the right thing?

We don't do anything special on the client side. We can't really know if a session has been reused or not. It is up to the application. It should never be a problem to attempt to reuse a session. The worst that can happen is that the server will refuse to use it.

> Why do we have an internal cache when the applications also has an external cache?

This is long standing functionality. Not all applications have an external cache - that is optional functionality, and I guess many do not. I also suspect that some applications use the API to know about session creation/removal events but don't actually implement a cache at all.

It is possible to configure things to not use the internal cache and only use the external cache - but this protection won't work in that scenario (early data won't be possible). This is because there is no way, with the current API, of knowing whether a session has been removed or not from the external cache. You can ask it to be removed but you don't know whether it was in the cache and it was removed, or wasn't in the cache and the request was ignored. We could "get" the session from the external cache, and then immediately try to remove it if its there - but unless we add locking to that there could be all sorts of race conditions. If we add locking then it is likely to be a huge bottleneck.

**Comment by kaduk** [comment]
> Question: Should there be an option to disable this?

This level of replay protection is mandated by the spec. I have a hard time believing that we should speculatively add a knob to violate the spec with no particular justification in mind for doing so.

**Comment by mattcaswell** [comment]
The CIs seem to be failing in two different tests. I can reproduce one of the failures (fix pushed), but not the other one at the moment.

**Comment by mattcaswell** [comment]
I think I found the problem (new fixup commit pushed). Lets see how the CIs do.

**Comment by mattcaswell** [comment]
The CIs are now happy. Ready for review!

**Comment by mattcaswell** [comment]
Ping!! Please can someone look at this? I really think this should be in the beta.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
