### PR TITLE
migrate to github boringssl  mirror

### PR DESCRIPTION
**Pull request by daleydeng**

### CODE REVIEW

**Comment by tmshort** [comment]
Why?

**Comment by InfoHunter** [comment]
> Why?

I guess it's because Google services has been filtered out (blocked) in some areas but Github has less such problem…… ;-)

**Comment by mspncp** [comment]
I have a question for curiosity's sake: What about users which already have the submodule checked out? Will they have to run [git submodule sync](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-sync--recursive--ltpathgt82308203) manually in order to notice the URL change? If yes, and if they don't do it, do we care if they remain on the old URL?

**Comment by InfoHunter** [comment]
> If yes, and if they don't do it, do we care if they remain on the old URL?

As long as the old URL still works fine, even if they remain it, there seems no harm

**Comment by kaduk** [comment]
I guess @daleydeng isn't going to confirm that this change is trivial from a copyright perspective, so we will have to close it unmerged.

**Comment by paulidale** [comment]
Closing due to inactive contributor

**Pull request closed without merging**
