### PR TITLE
Fix test failure on AArch64 Kunpeng-920

### PR DESCRIPTION
**Pull request by zzl360**
fix https://github.com/openssl/openssl/pull/20498#discussion_r1168125677

### CODE REVIEW

**Comment by zzl360** [comment]
@xu-yi-zhou please check this code.

**Comment by tom-cosgrove-arm** [comment]
(marking `tests: exempted` because the existing tests catch this)

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTMLGTM

**Comment by xu-yi-zhou** [comment]
LGTM

**Review by paulidale — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
> Does this need to go to any other branches?

The bug was introduced in #20498 on Mar 13 this year, so hasn't yet been released

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the fix.

**Pull request closed without merging**
