### PR TITLE
WIP: Templated text for manpages

### PR DESCRIPTION
**Pull request by richsalz**
#10153 

I'm doing something wrong, this doesn't work.  So it's WIP.

### CODE REVIEW

**Comment by levitte** [comment]
> this doesn't work.

Yup

The way things work is that you need a GENERATE line in some appropriate `build.info` to trigger file generation, like this:

https://github.com/openssl/openssl/blob/e78253f2d0c1a9fe6b023d867ee02342b4560150/build.info#L21

Now, `.in` at the end of the generator (the first token in the value) is significant, it triggers automatic call of `util/dofile.pl`, in this example with `doc/man7/openssl_user_macros.pod.in` as the argument and `doc/man7/openssl_user_macros.pod` as the output file.

You also need to hook the generation of the intended file to something.  In the top `build.info`, there's a "magic" depend line:

https://github.com/openssl/openssl/blob/e78253f2d0c1a9fe6b023d867ee02342b4560150/build.info#L12-L13

The empty `[]` is "magic" insofar that it makes the whole build depends on those files being generated.  It's kind of a last resort when you can't easily figure another way to have them automatically built.

As for loading perlvar, there's a whole world of complication trying to add that to `util/dofile.pl`.  It would be better to be explicit in your `.in` file, like this:

``` perl
{- use File::Spec::Functions;
    do catfile($config{sourcedir}, 'doc/perlvars.pl');
    "" -}
```

**Comment by richsalz** [comment]
Oh sorry (it was late), when I said "it doesn't work" I meant by doing it manually, I haven't hooked it up to the build system yet:
```
perl -Mconfigdata util/dofile.pl -s doc/perlvars.pl doc/man1/openssl-smime.pod
```

Doing that gives me no output.

I can figure out the build stuff.  I'd like to put all the stuff in dofile.pl, not add three magic lines, so I might muddle through it a bit more.  Even if I change openssl-mime.pod to have "print yes" I get no output, so clearly I'm doing something wrong in the invocation.

**Comment by richsalz** [comment]
When I replace the pathname with /tmp/x it works  /tmp/foo.in it does not.  Something strange in the invocation of dofile that I need to understand.

**Comment by richsalz** [comment]
Argh.  I had ```(-``` in my "real" file, not ```{-```  I think dofile should have a way to signal processing errors :)

Conceptually, this is ready to go.  I added a few other sample files so you can see the changes.

I will make a new PR with just the infrastructure.

**Comment by levitte** [comment]
> not add three magic lines

?????  I'm not sure I understand what's magic about those lines, they're actually quite explicit.
The real magic would be for you to figure out how to pass the `-s` option with its value.

**Comment by richsalz** [comment]
#10159 does it right.  You just need to put
```
{- $OpenSSL::safe::do_not_edit -}
```
for example at the start of any ```pod.in``` files.

Closing this.

**Pull request closed without merging**
