### PR TITLE
Convert shlibloadtest to new framework

### PR DESCRIPTION
**Pull request by richsalz**

### CODE REVIEW

**Comment by levitte** [comment]
Don't make a separate `main` for when no test can be performed.  Instead, guard the addition of tests in `test_main()`.  As an example, have a look at `test/bftest.c`.  The C test framework will treat the absence of tests to run as a `skip_all`.

**Comment by richsalz** [comment]
done.

**Comment by richsalz** [comment]
appveyor failures are unrelated.

**Comment by richsalz** [comment]
ping @levitte

**Comment by richsalz** [comment]
and now every test uses the framework!

**Pull request closed without merging**
