### PR TITLE
Fix EVP_DigestSign interface when used with DES CMAC

### PR DESCRIPTION
**Pull request by p-steuer**
DES implementations were missing the dup/copy ctx routines
required by CMAC implementation. A regression test is added.

- [x] tests are added or updated

### CODE REVIEW

**Comment by p-steuer** [comment]
needs a rebase due to https://github.com/openssl/openssl/commit/f5056577ba08b3694aab2722eae1c97bf00acc80

**Comment by p-steuer** [comment]
Rebased. please Re-review.

I noticed during rebase that a lot of header files are missing include guards (e.g. all headers in providers/implementations/ciphers/ but also include/crypto/modes.h ..). I wonder if they were just forgotten or if there is a reason for it ?

**Comment by mattcaswell** [comment]
> I noticed during rebase that a lot of header files are missing include guards (e.g. all headers in providers/implementations/ciphers/ but also include/crypto/modes.h ..). I wonder if they were just forgotten or if there is a reason for it ?

I suspect this is just an error - but I've not looked into it.

**Comment by p-steuer** [comment]
merged .

master: https://github.com/openssl/openssl/commit/abfc73f374c2b80e15f6c9d0b3a7437b3e94afa8

**Pull request closed without merging**
