### PR TITLE
Remedy a little bit this lousy, lousy programming style

### PR DESCRIPTION
**Pull request by BertramScharpf**
The Heartbleed vulnerability surely was concealed by this awkward programming style.

### CODE REVIEW

**Comment by richsalz** [comment]
ping @mattcaswell who wanted to keep heartbeats :)
+1

**Comment by richsalz** [comment]
@BertramScharpf I appreciate your sense of humor. :)

**Comment by mattcaswell** [comment]
Yes we should do this, but the PR needs updating because it no longer applies.

**Comment by mattcaswell** [comment]
Ping @richsalz see gitlab MR 2731

**Comment by richsalz** [comment]
Saw it, plus-one to that internal MR.

**Comment by mattcaswell** [comment]
Pushed as 485b78dd. Closing this.

**Pull request closed without merging**
