### PR TITLE
Be less sensitive to CRLF line endings in perl scripts

### PR DESCRIPTION
**Pull request by orgads**
Git for Windows sets core.autocrlf=true by default. This causes the input files that the scripts use have CRLF line endings.

Perl's cho[m]p only strips LF, but leaves the CR behind.

Replace it with substitution of all trailing space with nothing.

### CODE REVIEW

**Comment by orgads** [comment]
I'm not sure this qualifies as a bugfix, but we went through hell because of that, so please consider it :)

**Comment by levitte** [comment]
I know what you're talking about, we dealt with the same thing in master / 1.1.0.  There, we replaced `chomp` with `s|\R$||`.  `\R` is a recognise-all-possible-line-endings thing...

**Comment by orgads** [comment]
hmm... That was introduced in Perl 5.10, I have 5.8.8 in one of my envs. Perl 5.10 requirement only starts in 1.1.0 branch.

**Comment by levitte** [comment]
Yup, that's the main reason the `\R` method wasn't backported.

**Comment by dot-asm** [comment]
For reference, I can't reproduce the problem. I.e. if 'git clone' with git for Windows, VC-WINxxx build complete without problem...

**Comment by orgads** [comment]
I build with mingw, not msvc.

בתאריך 16 בספט׳ 2016 23:51,‏ "Andy Polyakov" <notifications@github.com> כתב:

**Comment by dot-asm** [comment]
Trouble is this. So you can confirm suggested modification works for you, but what can we tell about *all* other platforms? Yes, we can use our judgement and deem it safe, but question is if it would be *formally* appropriate without testing on other systems? Software in maintenance mode has this kind of inertia, for good or bad, but it does. And first question in situation like this is if there is anything you can do to make it work without modifications. I gather that `git -c core.autocrlf=false clone ...`, i.e. cloning with an additional flag, would do the trick.

Secondly, "build with mingw" is a slippery term. Normally you use mingw compiler in a "hosted" environment, most commonly MSYS, but there are mingw compilers for cygwin and Linux. And they all customarily come with own git, one targeting specific "hosted" environment, just like they have own perls. I suppose adhering to matching perl would work too. And question would be if it's actually *more* appropriate to do so...

**Comment by dot-asm** [comment]
Just in case, my comment means that I for one am not going to plus-one proposed changes. This formulation in turn means that I'm not going to oppose if somebody else does.

**Comment by dot-asm** [comment]
Also just in case for record. What's difference between "mingw" and "msys" applications. Latter import msys run-time dlls, such as msys-2.0.dll, while former - exclusively Windows system dlls. "Import" refers to information that can be collected with "dumpbin /imports" or by examining "Import tables" in "objdump -x" output.

**Comment by orgads** [comment]
I use the msys2 bash and perl provided by Git for Windows, with a separate mingw installation from [mingw-w64](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.2.0/threads-posix/dwarf/), that does not depend on msys.

Cloning with a flag might be appropriate when you clone openssl alone, but what do you suggest to do when openssl is used as a submodule of another repository?

I understand your concerns regarding other systems. I did test these changes on Windows and Linux, but that's all I have. I doubt any system actually *requires* trailing spaces though...

**Comment by dot-asm** [comment]
> I use the msys2 bash and perl provided by Git for Windows, with a separate mingw installation from mingw-w64, that does not depend on msys.

As I said, it's a slippery thing. Indeed, note that bash, perl and I suppose make are msys applications. But in such case why would you insist on using non-msys git? Wouldn't it be more natural/appropriate to adhere even to msys git and have homogeneous chain? There *is* one! Can you tell if it works for you?

Once again. Software in maintenance mode has certain "inertia". And this "inertia" has maximum in platform-neutral part. I mean it's much easier to accept platform-specific modifications, because they can be tested on specific target platform. Suggested modifications affect [build procedures on] *all* platforms. One can argue that we should be less rigid with LTS branch such as 1.0.2, because world after all changes faster, and we ought to keep up with it. But there should be prior discussion about how flexible can/should we be. And till we have it, we are effectively bound by the said "inertia" and formally have to suggest workarounds over fixes similar to suggested one.

> What do you say?

Note that my objection (and once again, *personal*) is not matter of preference of `[\r\n]+$` over `\s+$` (or vice versa), but about formal side of considering this *kind* of modifications specifically to branch in maintenance mode.

**Comment by richsalz** [comment]
I'll go a bit further than @dot-asm :  We don't know the impact on everyone else using 1.0.2, so we're not going to do this in a LTS maintenance branch.  Closing.

**Pull request closed without merging**
