### PR TITLE
Fix UEFI build on FreeBSD by not including system headers

### PR DESCRIPTION
**Pull request by bcran**
CLA: trivial

### CODE REVIEW

**Comment by kroeckx** [comment]
Why is __FreeBSD__ defined when the target is UEFI?

**Comment by kaduk** [comment]
```
[bjk@kduck ~]$ uname
FreeBSD
[bjk@kduck ~]$ clang -x c /dev/null -dM -E|grep FreeBSD
#define __FreeBSD__ 13
#define __FreeBSD_cc_version 1300000
#define __VERSION__ "4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)"
```

**Comment by levitte** [comment]
Can you build for UEFI on other operating systems? Will they hit the same issue? I imagine that's what @kroeckx is trying to ask.

**Comment by bcran** [comment]
> Can you build for UEFI on other operating systems? Will they hit the same issue? I imagine that's what @kroeckx is trying to ask.

Oh. Yes, the TianoCore EDK2 project builds on macOS, Windows and Linux and have successfully built with the latest OpenSSL 1.1.1 update. So it appears that other operating systems build fine, without hitting this issue.

**Comment by t8m** [comment]
[master 1fa90bb3a9]
[OpenSSL_1_1_1-stable 444ec8d5e7]

**Pull request closed without merging**
