### PR TITLE
adding a  '-updatecrl' to openssl ca

### PR DESCRIPTION
**Pull request by LampmanYao**
'-updatecrl': updates CRL from `new_revoked.txt`
'-gencrl': generates CRL from `index.txt`
where `new_revoked.txt` <= `index.txt`

### CODE REVIEW

**Comment by richsalz** [comment]
I don't understand the purpose of this?  To have an incremental "new_revoked" file of revoked certificates?

**Comment by LampmanYao** [comment]
Yes, i think it's unnecessary to read the revoked certificates which have already in CRL when generate CRL.
Or there's another way to do this?

**Comment by richsalz** [comment]
It doesn't read the CRL, it reads the index file.  (Actually, it has already loaded the index file, it just scans the parsed data).  Look around line 1200 of ca.c

**Comment by LampmanYao** [comment]
I know, the index file will be loaded first.
The line 1227 of ca.c, if we test it in this way:
> db_count = sk_OPENSSL_PSTRING_num(db->db->data);
> BIO_printf(bio_err, "db count is %d\n", db_count);
> for (i = 0; i < db_count; i++) {  

It  will prints the count of records in index.txt file. It means that, whatever those certificates have added to the CRL or not, it will loads them, parses them, creates a new CRL and add all the records to CRL.

**Comment by richsalz** [comment]
It does not load and parse the certs.  It only reads the text file.

**Comment by LampmanYao** [comment]
Yeah, it doesn't.
The all records in index.txt file will be read in db, right?

**Comment by richsalz** [comment]
yes

**Comment by LampmanYao** [comment]
In order to avoid that we need a new_reovked.txt file to store the record just like index.txt file.
We must make sure of these:
when ‘-revoke’, adds the record to index.txt and new_revoked.txt
when ‘-gencrl’, just like the old way doing, but must clean the new_revoked.txt
when ‘-updatecrl’, reads all the records in new_revoked.txt to db, adds them to CRL, and cleans the new_revoked.txt

**Comment by richsalz** [comment]
And my point is that we do not need to avoid it.  You are adding way too much complexity for very little benefit.

**Comment by LampmanYao** [comment]
OK. Maybe you are right.

**Comment by richsalz** [comment]
Thanks for the discussion and thinking about it!

**Pull request closed without merging**
