### PR TITLE
Fix typo in Windows makefile template: quotify, not quotiry

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
Noted.  Just gonna see that Appveyor agrees with me...

**Comment by levitte** [comment]
There was one glitch in appveyor.  It looks like my additional correctin fixed it...  reconfirm?

**Comment by levitte** [comment]
CIs are happy now :-)

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Merged.  85b8bea72e2434de5708462f0bf642c5f6bd2f0e

**Pull request closed without merging**
