### PR TITLE
[crypto/ec] for ECC parameters with NULL or zero cofactor, compute it (1.0.2)

### PR DESCRIPTION
**Pull request by bbbrumley**
Backport of #9727 to 1.0.2.

I still want to do some more testing, but it will have to wait until Sunday night. I thought I'd at least get the PR up for review.

### CODE REVIEW

**Comment by romen** [comment]
> Needs a CHANGES entry

This has been fixed

**Comment by romen** [comment]
I put the `hold` label just to remind us that @bbbrumley wanted to do more testing before merging.

**Comment by bbbrumley** [comment]
Thanks @romen for cleaning up my PRs. Enjoy your vacation :)

I carved out some time this morning to finish testing this.

The "hack test" with the `assert` from the other PR went swell again. I also verified the codepath in `gdb` that it early exits to ladder. Basically confirming what @romen did above.

I wanted to still test manually with a few custom PEMs, since 1.0.2 doesn't have robust `evp_test` support. That testing also went swell.

So ... ready to go from my behalf.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
