### PR TITLE
Added the .include directive in openssl configuration file.

### PR DESCRIPTION
**Pull request by nmav**
That allows including other files from a single configuration file.
The directive accepts a full path, and allows a single level of
inclusion (an included file cannot include others).

That simplifies the management of custom strings. Related to #192.

Also in: http://rt.openssl.org/Ticket/Display.html?id=3300

### CODE REVIEW

**Comment by richsalz** [comment]
Sorry I'm only just now looking at this.  It's nice.  We need an error to catch multiple includes?  And documentation.

**Comment by nmav** [comment]
Thanks. I'll add a test suite case and document it. Any recommendation on which documents should be updated for the latter?

**Comment by richsalz** [comment]
Ugh, it turns out there's no good place where the config file syntax is described :(  For now, how about OPENSSL_config.pod, and I'll work on pulling all of the rest into that file?

**Comment by nmav** [comment]
Tomas Mraz pointed me to apps/config.pod. Would that be sufficient?

**Comment by richsalz** [comment]
Yes, that's great!

**Comment by nmav** [comment]
Not sure I understand why the appveyor build failed. Let me know if there is anything I could address.

**Comment by richsalz** [comment]
Probably not your issue, wait a bit.

**Comment by nmav** [comment]
It seems that the appveyor build gets cancelled every time.

**Comment by richsalz** [comment]
+1 i'll merge and touch this up if needed.  This is RT 3300.

**Comment by nmav** [comment]
@mattcaswell @richsalz are you still interested in merging such feature? Should we revive it?

**Comment by richsalz** [comment]
I am still interested.  But I am not sure what the community thanks.  Before you spend more time on this, how about opening a GH issue where folks can talk about it?

**Comment by tiran** [comment]
I'd like to see an include statement in OpenSSL's config files. But you should consider me biased, @nmav and @t8m are co-workers of mine.

**Comment by nmav** [comment]
@richsalz see #4962

**Comment by mattcaswell** [comment]
Looks like this needs rebasing.

**Comment by t8m** [comment]
Yes, but I would also like to improve it to be able to load all conf files from a directory, not just a single file.

**Comment by nmav** [comment]
This was replaced by #5351

**Pull request closed without merging**
