### PR TITLE
rand: note that locking needs to be explicitly enabled.

### LINKED ISSUE #13912: EVP_RAND_CTX_new documentation
`EVP_RAND_CTX_new` needs to note that the parent random should have locking enabled before any child is created.  A parent must be lockable if it has more than one child.  Not doing so is an error.

Refer: https://github.com/openssl/openssl/pull/13660#discussion_r560847550

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #13912

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
I notice in the issue that you mention that it must be does before creating the children.. Should this text say this?

**Comment by paulidale** [comment]
It needs to be done before instantiating the children.  However, it's only concurrent accesses that are a problem.  Thus, this sequence is fine:

``` C
parent = EVP_RAND_CTX_new(...);
child1 = EVP_RAND_CTX_new(..., parent);
child2 = EVP_RAND_CTX_new(..., parent);
EVP_RAND_instantiate(parent, ...);
EVP_RAND_instantiate(child1, ...);
EVP_RAND_instantiate(child2, ...);
EVP_RAND_enable_locking(parent);
```

Trying to capture all the possible cases in a paragraph will be more confusing I expect.

**Comment by slontis** [comment]
That example might be useful?

**Comment by paulidale** [comment]
How's about I add _before any concurrent access_ to the end on the paragraph?

Something else that is unmentioned is that the parent needs to be instantiated before any children.  Spelling everything out is a deep dark hole full of grues.  When @mattcaswell removed the automatic lock enabling call, I figured a note was worthwhile but I'm not intending to dig into every possible minutæ.

**Comment by paulidale** [comment]
Ping for review.

**Review by slontis — APPROVED** [review]

**Comment by slontis** [comment]
Is the label supposed to by hydrogen for this one.. I changed it to beta1 thinking it wasnt a toggle?

**Comment by paulidale** [comment]
This was something I did in addition to the scheduled hydrogen work.

**Comment by paulidale** [comment]
Merged to master.  Thanks.

**Pull request closed without merging**
