### PR TITLE
property: reduce memory consumption when OPENSSL_SMALL_FOOTPRINT is defined.

### PR DESCRIPTION
**Pull request by paulidale**
This takes out the lock step stacks that allow a fast property to name resolution.  Follow on from #17325.

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
check_update is failing because the year has changed for copyright purposes.

**Comment by paulidale** [comment]
Ping?

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
A rebase should fix the test failure -- it was the year rollover issue.

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the review.

**Pull request closed without merging**
