### PR TITLE
Remove unused internal functions evp_pkey_ctx_get1_id_prov and evp_pkey_ctx_get1_id_len_prov

### LINKED ISSUE #20701: Crash if ctx equal to NULL is passed to evp_pkey_ctx_get1_id_prov or evp_pkey_ctx_get1_id_len_prov
OpenSSL 3.0.7

If the first argument pointer EVP_PKEY_CTX *ctx equal to NULL is passed to the functions evp_pkey_ctx_get1_id_prov or evp_pkey_ctx_get1_id_len_prov (evp.h 893-894) then the application crashes with read access violation.

Maybe need to add a check EVP_PKEY_CTX *ctx to NULL like in a functions EVP_PKEY_CTX_get1_id and EVP_PKEY_CTX_get1_id_len?

### PR DESCRIPTION
**Pull request by nv-dmd**
Fixes #20701 
Remove unused internal functions evp_pkey_ctx_get1_id_prov and evp_pkey_ctx_get1_id_len_prov

### CODE REVIEW

**Comment by t8m** [comment]
CI is relevant.

**Comment by t8m** [comment]
As this is just removal it would be acceptable with CLA: trivial. Could you please amend the commit message with `git commit --amend` so it contains `CLA: trivial` on a separate line in the commit message body?

**Comment by slontis** [comment]
@levitte These look like leftovers from this..
https://github.com/openssl/openssl/commit/86df26b3943509219057ae87f8764b3c15e0d8b8
Not sure evp_pkey_ctx_set1_id_prov() is useful either?

**Comment by nv-dmd** [comment]
Maybe I should also remove get1_id_data function, which is not used after the changes and so failed checks?

**Comment by nv-dmd** [comment]
And can I do the same Pull Request in the 3.0 branch, because I use this branch? And what about 3.1 branch?

**Comment by t8m** [comment]
> Maybe I should also remove get1_id_data function, which is not used after the changes and so failed checks?

Yes, please.

**Comment by t8m** [comment]
> And can I do the same Pull Request in the 3.0 branch, because I use this branch? And what about 3.1 branch?

This will not be merged to 3.0 branch as this is just a cleanup and not a bug fix.

**Comment by nv-dmd** [comment]
Is there anything else I need to do?

**Review by t8m — APPROVED** [review]
OK with CLA: trivial.

**Comment by t8m** [comment]
We will squash the commits when merging.

**Review by paulidale — APPROVED** [review]
yes to trivial

**Comment by slontis** [comment]
Is evp_pkey_ctx_set1_id_prov() used anywhere?

**Comment by nv-dmd** [comment]
> Is evp_pkey_ctx_set1_id_prov() used anywhere?

I agree with this. Function evp_pkey_ctx_set1_id_prov() is not used now and there is function EVP_PKEY_CTX_set1_id instead

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]
Still OK with CLA: trivial and assuming @paulidale is too.

**Comment by nv-dmd** [comment]
What else can I do?

**Comment by paulidale** [comment]
Merged to master, thanks for the contribution.

**Pull request closed without merging**
