### PR TITLE
Integrate dtls1.3 in s_client and s_server

### PR DESCRIPTION
**Pull request by fwh-dc**
Another dtls 1.3 specific update. It is dependent on https://github.com/openssl/openssl/pull/22259

### CODE REVIEW

**Review by mattcaswell — CHANGES_REQUESTED** [review]
Looks good. Looks like the s_client and s_server man pages also need to be tweaked.

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Ping @openssl/committers for second review

**Comment by mattcaswell** [comment]
I wonder whether "branch:master" is the right label for this? Do we need a new "branch:feature" label instead?

**Comment by fwh-dc** [comment]
> Could you please fix the CI issues?

Done ✅

**Comment by mattcaswell** [comment]
Ping @t8m

**Review by t8m — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed to the feature/dtls-1.3 branch

**Comment by mattcaswell** [comment]
Note that I squashed the "fix docnits" commit into the other documentation commit before merge.

**Pull request closed without merging**
