### PR TITLE
Removes unsed function: ssl_bad_method()

### PR DESCRIPTION
**Pull request by fwh-dc**

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Comment by FdaSilvaYY** [comment]
Typo in commit message : unsed

**Comment by tom-cosgrove-arm** [comment]
I don't know the history of this function: is it something that is no longer used, or might it still want to be included much like a 'NOP' or abort() function, to be used as a placeholder?

**Review by t8m — APPROVED** [review]
As this is no longer used there is no point in keeping it.

**Comment by mattcaswell** [comment]
> I don't know the history of this function: is it something that is no longer used, or might it still want to be included much like a 'NOP' or abort() function, to be used as a placeholder?

As far as I can tell this has been dead code for a *long* time and no one noticed. I see its use being removed in commit 01a9792f05a2 in 2005!!

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master branch. Thank you for your contribution.

**Pull request closed without merging**
