### PR TITLE
[WIP] CI build of #11250

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Rather than wrapping whole files in "ifndef OPENSSL_NO_xxx" we handle
the changes in build.info

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
No thank you this is WIP, please hold the horses.

**Comment by bernd-edlinger** [comment]
@levitte  this is #11250 rebased, to save Rich some extra work.
If you like please re-confirm #11250

**Comment by t8m** [comment]
The no-deprecated build failure is known. The memleak test failure in -fsanitize build with gcc is weird but unrelated.

**Comment by bernd-edlinger** [comment]
what is appveyor doing?

**Comment by bernd-edlinger** [comment]
Appveyor also OK

**Comment by bernd-edlinger** [comment]
Is the CI fuzz thing ok or not?
there is one no parking sign: Upload Crash ?
Guess that is normal?

**Pull request closed without merging**
