### PR TITLE
Add a params argument to key manager generate function.

### PR DESCRIPTION
**Pull request by paulidale**
- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
This change surprises me.  I would have expected the gen init function to be modified thusly...

**Comment by paulidale** [comment]
It wasn't clear if the _gen or _gen_init needed update (I'm tired).  I guess _gen_init makes more sense.

There are other set_params that might be adjusted, I'll look tomorrow.

**Comment by paulidale** [comment]
Closing this in favour of a version based on gen_init() instead.

**Comment by paulidale** [comment]
Replaced by #14350

**Pull request closed without merging**
