### PR TITLE
Coverity 1515953: negative loop bound

### PR DESCRIPTION
**Pull request by paulidale**

### CODE REVIEW

**Comment by slontis** [comment]
You beat me to it.. it should not hit this in practice but it is better this way.

**Review by slontis — APPROVED** [review]
I need to beat it into my head that sk_num() can return -1..
Whether it should or not is a different matter.

**Comment by paulidale** [comment]
Sadly, it can return -1 and is documented as doing so.  It's idiotic IMO.  sk_num(NULL) ought to return 0 since there are no elements.

**Review by t8m — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
How about adding a new API `OPENSSL_sk_count()` where `sk_count(NULL) -> 0, else sk_count(s) -> sk_num(s)` ?

**Comment by paulidale** [comment]
Adding APIs is essentially a permanent commitment to maintaining them.  OpenSSL has a very conservative policy about API changes.  While I like the suggestion, I'm not sure the ongoing support is worth the pain.

**Review by hlandau — APPROVED** [review]

**Comment by paulidale** [comment]
Merged.

**Pull request closed without merging**
