### PR TITLE
Fix no-blake2

### PR DESCRIPTION
**Pull request by mattcaswell**
If blake2 has been disabled then the legacy_blake2.c has no content,
which was causing a compilation failure. Therefore we add the macro
NON_EMPTY_TRANSLATION_UNIT.

### CODE REVIEW

**Comment by slontis** [comment]
I would prefer these to get fixed in build.info
See https://github.com/openssl/openssl/pull/10407

**Comment by levitte** [comment]
I agree with @slontis

**Comment by mattcaswell** [comment]
> I would prefer these to get fixed in build.info

Sure. Done.

**Comment by richsalz** [comment]
Consistency is important.  Does it make sense to change most similar ifdef's to do it in the build.info file?

**Comment by richsalz** [comment]
An issue with doing it in the build.info file is that this makes it harder for other projects to just pick up and re-use OpenSSL sources in their project.  I prefer doings things in the standalone approach everywhere, but please be consistent.

**Comment by levitte** [comment]
"standalone" is sooo 1.0.x 😉

I prefer the build.info way. The `NON_EMPTY_TRANSLATION_UNIT` macro is an ugly kludge... Always been.

**Comment by richsalz** [comment]
You can say it's a kludge, but you can also say that about many things done for portability. :)

At any rate, the main point is please do things CONSISTENTLY.

**Comment by richsalz** [comment]
I created #10434 to address the consistency issue.

**Comment by mattcaswell** [comment]
Pushed. Thanks!

**Pull request closed without merging**
