### PR TITLE
doc: fix EVP_SignInit.pod

### PR DESCRIPTION
**Pull request by rurban**
Fixes GH #19786

### CODE REVIEW

**Comment by t8m** [comment]
Could you also remove or generalize (i.e., not mention particular key type algorithms) the paragraph at line 68?

**Comment by rurban** [comment]
@t8m: I don't get that. Looks ok to me. Do you have a suggestion for that wording?

**Comment by t8m** [comment]
I've actually meant the paragraph at line 63.

Something like this would do:

```
When signing with some private key types the random number generator must
be seeded. If the automatic seeding or reseeding of the OpenSSL CSPRNG fails
due to external circumstances (see L<RAND(7)>), the operation will fail.
```

**Review by mattcaswell — APPROVED** [review]
Sorry that was meant to be "approve" not "request changes"

**Comment by t8m** [comment]
Merged to master, 3.1, 3.0 branches after squashing the commits. Thank you for your contribution.

**Pull request closed without merging**
