### PR TITLE
Provider cross validation CI runs

### PR DESCRIPTION
**Pull request by paulidale**
- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
Cross validation tests are [passing](https://github.com/openssl/openssl/pull/20552/checks).

**Comment by t8m** [comment]
I believe this is still testing too much and it would require too much maintenance that has no real effect.

IMO from the released versions we should only test the fips provider against the libcrypto & test suite from all the current branches. The full cross testing should be done only across the tips of the branches.

This is sufficient to test that the fips providers are forwards compatible - this is actually the main use-case we need to support. The test suites from the old branches CANNOT in principle be fully compatible with updated providers, otherwise we would not be ever able to change things in providers. So you cannot ever expect the test suite from the 3.0.0 release (or any other release) to fully pass with new fips providers.

If I count it properly we should have 3 released fips providers * 3 branches + 3*2 branches tests -> 15 tests and you can also drop the old FIPS provider compat test as that is just duplicate.

**Comment by paulidale** [comment]
I'm basically doing what you suggest.  No release is tested against any other release.  Nothing is tested against itself.
I set up the jobs to cross test everything because I couldn't figure out a workable alternative.  However, the unwanted cases are immediately short-circuited and early exit.  E.g. look at [this run](https://github.com/openssl/openssl/actions/runs/4496359573/jobs/7911063157).

The old FIPS provider compatibility check is per push not daily, so more timely.  Happy to drop it though.

**Comment by t8m** [comment]
> I suggest we leave any "additional" tests here, they can be removed once there is a problem.

You already have some hacks there such as skipping the ssl tests from 3.0.0 release. I am afraid they will become unmaintainable at some point. I would simply drop the cases where you're running tests from released version tree.

**Comment by paulidale** [comment]
Isn't it useful to learn when the 3.1.x FIPS prodiver ceases working with the 3.1.0 release?
Dropping these cases loses this information.

**Comment by paulidale** [comment]
https://github.com/openssl/openssl/actions/runs/4558459775 passing with the reduced testing.

**Review by t8m — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Comment by paulidale** [comment]
Trivial edit before merge to remove end of line white space from the new test.
Thanks for the reviews.

**Pull request closed without merging**
