### PR TITLE
Fix improper return check of do_X509_verify

### PR DESCRIPTION
**Pull request by PeiweiHu**
**do_X509_verify** returns 0 or 1. 

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
It can return -1 from `ASN1_item_verify_ex()` (via `X509_verify()`).

I don't think this should be merged.

**Comment by PeiweiHu** [comment]
rv is assigned with&nbsp;rv = (X509_verify(x, pkey) &gt; 0), the negative value is changed to 0. 




------------------ Original ------------------
From: Pauli ***@***.***&gt;
Date: Wed,Nov 10,2021 8:07 AM
To: openssl/openssl ***@***.***&gt;
Cc: Peiwei Hu ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [openssl/openssl] Fix improper return check of do_X509_verify (PR #17000)





 
It can return -1 from ASN1_item_verify_ex() (via X509_verify()).
 
I don't think this should be merged.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeiweiHu** [comment]
> It can return -1 from `ASN1_item_verify_ex()` (via `X509_verify()`).
> 
> I don't think this should be merged.

rv is assigned with rv = (X509_verify(x, pkey) > 0), the negative value is converted to 0.

**Comment by paulidale** [comment]
Oops...

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]
OK for master branch.

**Comment by kroeckx** [comment]
I prefer that we change do_X509_verify() so that it can return -1

**Comment by PeiweiHu** [comment]
> I prefer that we change do_X509_verify() so that it can return -1

There are several functions (**do_X509_sign**, **do_X509_REQ_sign**, **do_X509_CRL_sign**, **do_X509_verify**. and **do_X509_REQ_verify**). They return values in a similar manner, i.e. return the result of comparison between an inner function return value and zero. But the errors happen while invoking two of them (do_X509_verify and do_X509_REQ_verify).  

If do_X509_verify() is changed, these APIs don't keep the same return pattern. I wonder do the other APIs' behaviors need to be changed? Maybe we need to keep their consistency?

**Comment by kroeckx** [comment]
I think functions should always properly propagate errors. Since they are non-public functions, there is no reason we can't change the return value.

**Comment by PeiweiHu** [comment]
This pr is contained with in https://github.com/openssl/openssl/pull/17001 now.

**Pull request closed without merging**
