### PR TITLE
Fix migration guide mappings for i2o/o2i_ECPublicKey

### LINKED ISSUE #23854: Improve migration guide in regards to i2o/o2i_ECPublicKey()
We should document what is the straightforward replacement (EVP_PKEY_get1/set1_encoded_public_key()).

See also:

https://github.com/openssl/openssl/discussions/23820#discussioncomment-8764694

### PR DESCRIPTION
**Pull request by slontis**
Fixes #23854

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by slontis** [comment]
ping

**Review by romen — APPROVED** [review]
LGTM

**Review by beldmit — COMMENTED** [review]
Why 2 times?

**Comment by t8m** [comment]
> Why 2 times?

This is o2i and i2o - different functions.

**Comment by nhorman** [comment]
merged to all branches, thank you!

**Pull request closed without merging**
