### PR TITLE
CMP: fix #23706 and add warning notes on `OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR`

### LINKED ISSUE #23706: Trust Anchor for CMP IR
Hi,
I'm performing CMP IR operation by setting the CMP CTX APIs.

But I don't have the trust anchor for setting it to CMP_CTX for performing IR. we have gone through the docs and tried using the OSSL_CMP_CTX_set_option(cmpCtx, **OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR**, 1); so that extracerts output that is generated as part of IR will be used as trust anchor.  So, I'm not setting the **OSSL_CMP_CTX_set0_trustedStore** , thinking after setting that option(**OSSL_CMP_OPT_PERMIT_TA_IN_EXTRACERTS_FOR_IR**)  will be enough to perform IR, but IR is failing saying, 
**00C73F5B8D7F0000:error:1D0000B3:CMP routines:OSSL_CMP_validate_msg:missing trust anchor:crypto/cmp/cmp_vfy.c:624:
00C73F5B8D7F0000:error:1D00008C:CMP routines:ossl_cmp_msg_check_update:error validating protection:crypto/cmp/cmp_vfy.c:716:**

Since we **don't have trust anchor CA cert** how can we achieve **IR**. **Also, we don't want to use the Preshared Key and reference number (OSSL_CMP_CTX_set1_referenceValue, OSSL_CMP_CTX_set1_secretValue)**.

**Is there any way we can get trust anchor on the go?**

Thanks in advance.

### PR DESCRIPTION
**Pull request by DDvO**
Fixes #23706
and adds warning notes on the use of that 3GPP quirk

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by shahsb — APPROVED** [review]
LGTM

**Comment by DDvO** [comment]
Ping @openssl/committers for 2nd review

**Comment by DDvO** [comment]
Pinging @openssl/committers again for 2nd review

**Comment by DDvO** [comment]
Pinging again @openssl/committers for 2nd review.

This PR just changes one code line and adds some doc lines.

**Review by nhorman — APPROVED** [review]

**Comment by DDvO** [comment]
Thanks you also for the 2nd approval on this PR.
This meanwhile should be applied also to 3.3 - ok to add `branch: 3.3`?

**Comment by nhorman** [comment]
I think thats fine @DDvO, though please monitor this issue for the next 24 hours, as doing so may cause the openssl bot to not set the ready to merge flag.  Just need to know if that happens so we can set it manually

**Comment by DDvO** [comment]
Merged to master and 3.* - thanks for the approvals.

**Pull request closed without merging**
