### PR TITLE
Add function to compute digest of RSA public/private key DER form

### PR DESCRIPTION
**Pull request by pprindeville**

### CODE REVIEW

**Comment by richsalz** [comment]
Sorry to let this sit for so long.  Any chance of a doc update?

**Comment by richsalz** [comment]
@pprindeville I know this has sat here for a long time.  can you rebase and push an updated PR?  This can be useful for subjectKeyIdentifier things.

**Comment by richsalz** [comment]
@pprindeville sorry, this fell through the cracks.  can you rebase and add documentation?

**Comment by pprindeville** [comment]
I will try to get to it this week.

**Comment by pprindeville** [comment]
BTW, is there some good documentation about how the crypto stuff is represented internally?  I want to avoid having to (re)canonicalize stuff if it's already in x509 format.

**Comment by richsalz** [comment]
There’s no good documentation.

Anything in DER is already in canonical form.  That’s that DER does. ☺

**Comment by snhenson** [comment]
This is also adding unrelated wrapper functions round some DSAPublicKey functions. Those are an ancient none standard form which has been about since SSLeay which I don't think we should be encouraging.

**Comment by richsalz** [comment]
well, let's close it then :)

**Pull request closed without merging**
