### PR TITLE
Remove VOS support

### PR DESCRIPTION
**Pull request by richsalz**
VOS was only supported on HP-PARISC and Itanium, so remove it.

### CODE REVIEW

**Comment by richsalz** [comment]
Related to #6232

**Comment by levitte** [comment]
PARISC and Itanium are still actively used architectures. I don't know much about vos, but am noticing that it wasn't mentioned in #6232.

**Comment by richsalz** [comment]
No, #6232 wasn't a comprensive list of platforms to  unsupport.

The only VOS support is in the hacky RAND seeding (see the comment in rand_unix.c); do we still want to support *that* these days?

**Comment by richsalz** [comment]
I posted to openssl-users nearly a month ago, https://mta.openssl.org/pipermail/openssl-users/2019-June/010772.html, and there was no comment.  Okay to move forward on this?

**Comment by richsalz** [comment]
If you look at the PR, and [this comment](https://github.com/openssl/openssl/pull/9208#issuecomment-504419056) from a month ago, the only thing this really removes is seeding by repeatedly sampling a real-time clock.  Ugh

**Comment by levitte** [comment]
This is incomplete, there's still a `vos-gcc` config target in `Configurations/10-main.conf`.

**Comment by levitte** [comment]
> the only thing this really removes is seeding

This is not true, it's not the *only* thing being removed

**Comment by richsalz** [comment]
No it's not the only thing, but the use of "really" is perhaps an Americanism to mean "the only thing really of substance"  Additional commit pushed, thanks for catching it.

**Comment by levitte** [comment]
You and I value things differently, I find the removal of a config target *substantial*, no matter how old and ill updated it is.

**Comment by richsalz** [comment]
But, I didn't remove the config target at the time I wrote the "really the only thing" :)

**Comment by levitte** [comment]
You kinda sorta did, since you removed the guessing code in `config`.

**Comment by richsalz** [comment]
This goes against the stated compatibility plans so I'm closing this. If someone wants to recreate for a future release, feel free to adopt the branch. :)

**Pull request closed without merging**
