### PR TITLE
Add diacritics to my name in CHANGES.md

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Review by mspncp — APPROVED** [review]
Nice to see that my PR #14029 inspired you to make this change. :-)

**Comment by mspncp** [comment]
The only downside is that the Windows console still doesn't have UTF-8 as default.

```diff
diff --git a/CHANGES.md b/CHANGES.md
index e512b080c7..8aebba7689 100644
--- a/CHANGES.md
+++ b/CHANGES.md
@@ -27,7 +27,7 @@ OpenSSL 3.0
    BN_X931_generate_Xpq(), BN_X931_derive_prime_ex(), and
    BN_X931_generate_prime_ex().

-   *Tomas Mraz*
+   *Tom<C3><A1><C5><A1> Mr<C3><A1>z*

  * Deprecated the type OCSP_REQ_CTX and the functions OCSP_REQ_CTX_new(),
    OCSP_REQ_CTX_free(), OCSP_REQ_CTX_http(), OCSP_REQ_CTX_add1_header(),
@@ -110,7 +110,7 @@ OpenSSL 3.0
    read or write an EVP_PKEY directly using the OSSL_DECODER and OSSL_ENCODER
    APIs. Or load an EVP_PKEY directly from EC data using EVP_PKEY_fromdata().

-   *Shane Lontis, Paul Dale, Richard Levitte, and Tomas Mraz*
+   *Shane Lontis, Paul Dale, Richard Levitte, and Tom<C3><A1><C5><A1> Mr<C3><A1>z*
...
```

But a reasonable editor (e.g. Notepad++) has no problem displaying it correctly:

image

**Comment by mspncp** [comment]
Ups. Closed accidentally.

**Comment by mspncp** [comment]
> But a reasonable editor (e.g. Notepad++) has no problem displaying it correctly:

Oh, and even Notepad get's it right on Windows 10. I wouldn't have expected that ;-)

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
> The only downside is that the Windows console still doesn't have UTF-8 as default.

I have some _vague_ recollection that it's possible to switch codepage to UTF8...

**Comment by mspncp** [comment]
> I have some _vague_ recollection that it's possible to switch codepage to UTF8...

It's code page 10001. But changing the code page does not have any effect on the output of the `git show` command:

image

Code pages on Windows are a mystery to me: the `echo` command seems to work correctly regardless of the codepage:

image

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master. Thank you for the reviews.

**Pull request closed without merging**
