### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by FraGoTe**

### CODE REVIEW

**Comment by CrazyPython** [comment]
@richsalz Well, no one wants to look at monospace code, do they?

**Comment by levitte** [comment]
Our README isn't strictly markdown, only heavily inspired.  You might notice these lines:

```
The OpenSSL toolkit includes:

 libssl (with platform specific naming):
     Provides the client and server-side implementations for SSLv3 and TLS.

 libcrypto (with platform specific naming):
     Provides general cryptographic and X.509 support needed by SSL/TLS but
     not logically part of it.

 openssl:
     A command line tool that can be used for:
        Creation of key parameters
        Creation of X.509 certificates, CSRs and CRLs
        Calculation of message digests
        Encryption and decryption
        SSL/TLS client and server tests
        Handling of S/MIME signed or encrypted mail
        And more...
```

This is how they render on github:

> The OpenSSL toolkit includes:
> 
>  libssl (with platform specific naming):
>      Provides the client and server-side implementations for SSLv3 and TLS.
> 
>  libcrypto (with platform specific naming):
>      Provides general cryptographic and X.509 support needed by SSL/TLS but
>      not logically part of it.
> 
>  openssl:
>      A command line tool that can be used for:
>         Creation of key parameters
>         Creation of X.509 certificates, CSRs and CRLs
>         Calculation of message digests
>         Encryption and decryption
>         SSL/TLS client and server tests
>         Handling of S/MIME signed or encrypted mail
>         And more...

With other markdown implementations, line breaks aren't necessarely respected either.

In other words, pure horror.

**Comment by CrazyPython** [comment]
Would it be acceptable to send a PR that converts it to Markdown as well as preserving the original formatting? (ex. converting the indentations to bullet points)

**Comment by levitte** [comment]
No.  I agree with @richsalz on this one.

**Pull request closed without merging**
