### PR TITLE
Add Serializers for EC

### PR DESCRIPTION
**Pull request by slontis**
Provide EC serializers for test, pem and der.

##### Checklist

- [ ] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Depends on #10631 (In order to become a non draft)

**Comment by kroeckx** [comment]
I have the same comments here as in #11095: it needs to actually have tests for the various file formats, it needs to document the format EVP_PKEY_fromdata() is expecting.

**Comment by slontis** [comment]
Dependent on #11095 being merged..

**Comment by levitte** [comment]
@kroeckx, I'm currently updating the fromdata docs.  Separate PR

**Comment by slontis** [comment]
Merged to master..

**Pull request closed without merging**
