### PR TITLE
Ecdsa revert blinding 102

### PR DESCRIPTION
**Pull request by dot-asm**
This is backport of #6662 and #6664.

### CODE REVIEW

**Comment by dot-asm** [comment]
Red cross from appveyor was relevant. Add-on commit should fix it...

**Comment by richsalz** [comment]
reconfirm.

**Comment by mattcaswell** [comment]
Yes. Really the existing reviewed-by headers should be removed from that commit and replaced with yourself and rich.

**Comment by dot-asm** [comment]
I've added myself as reviewer for commit in question. Just in case for reference. I did replace reviewed-by and "merged from" but kept "cherry-picked from". Merged.

**Pull request closed without merging**
