### PR TITLE
Add a CI to check for the existence of C++ style comments

### PR DESCRIPTION
**Pull request by paulidale**
- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Is there a point to finding // inside c comments?
The compiler already picks up // inside source which is what I thought we would care about..

**Comment by paulidale** [comment]
I didn't bother working out a basic regular expression to distinguish // in comments from not.  Feel free to try.  It's theoretically possible.

We've had a few PRs where this was missed by the reviewers.  By making it a CI failure that prints the instances out, this should be less likely.

**Comment by slontis** [comment]
Is there not a build that already picks up // in source code?

**Comment by levitte** [comment]
Uhmmmm, shouldn't the `check-ansi` job find these issues for us already?  It used to...

**Comment by t8m** [comment]
Yeah, imo this is unnecessary. The check-ansi finds the comments unless placed in code that is actually not compiled in the check-ansi build. And yeah it won't find them inside a C style comments but that is also harmless.

**Comment by paulidale** [comment]
The ANSI build catches these.  Closing.

**Pull request closed without merging**
