### PR TITLE
Include image files when installing the HTML documentation

### LINKED ISSUE #15305: Lost images in HTML documentation
There are [images](https://www.openssl.org/docs/manmaster/man7/life_cycle-kdf.html) in `doc/man7` that aren't copied across when installing the HTML version of the manual pages.

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #15305

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]
Not quite the approach I would have taken...  but it does the work!

I suppose you leave it to me to play catch up on the VMS front 😉

**Comment by paulidale** [comment]
I'd be interested to see what your approach would have been.

**Comment by paulidale** [comment]
Merged to master.

**Comment by t8m** [comment]
Unfortunately this broke make install on Windows - the AppVeyor CI is broken due to that.

**Comment by paulidale** [comment]
Hmmmm.  Not good.  I'm not seeing an error in the logs.

**Comment by t8m** [comment]
You can see the error here:
https://github.com/openssl/openssl/pull/15433/checks?check_run_id=2656530024

The problem is when the copy.pl is invoked to copy images if there are none to be copied. One option would be to drop directory creation and image copying for any directory that currently has no images in manuals.

**Comment by t8m** [comment]
I've included a crude tentative fix in #15433

**Comment by paulidale** [comment]
Thanks for investigating and fixing this.  I almost didn't include the additional copies -- I wish I hadn't now :unamused:

**Pull request closed without merging**
