### PR TITLE
Updates documentation of RC4_CHAR and RC4_INT

### PR DESCRIPTION
**Pull request by fwh-dc**
##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Comment by fwh-dc** [comment]
Please let me know if this change is acceptable without a CLA.

**Comment by paulidale** [comment]
I'm okay calling this trivial.

To do so, the commit message needs a line `CLA: trivial` at the end.

**Comment by tmshort** [comment]
@hlandau are you also good with CLA: Trivial?
I think it qualifies.

**Review by tmshort — CHANGES_REQUESTED** [review]
Looks as though there's extraneous whitespace at the end of some of the added lines.

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
