### PR TITLE
Fix memory leak where fdlookup linked list is not freed during ASYNC_WAIT_CTX_free

### PR DESCRIPTION
**Pull request by stevelinsell**
There is memory leak when freeing the ASYNC_WAIT_CTX structure that means the linked list of fd_lookup_st is not freed up. This can cause a considerable leak of memory over time as you tend to use one ASYNC_WAIT_CTX per connection at the SSL level. The fix is to free each fd_lookup_st as we loop through them cleaning up.

### CODE REVIEW

**Comment by mattcaswell** [comment]
+1

**Comment by richsalz** [comment]
+1 from me.  You going to merge?

**Comment by mattcaswell** [comment]
Yes. I'll merge

**Comment by mattcaswell** [comment]
Merged 55327ddfc

**Comment by mattcaswell** [comment]
Thanks Steve!

**Pull request closed without merging**
