### PR TITLE
demos/evp: add make clean

### PR DESCRIPTION
**Pull request by pfsmorigo**
Add make clean for evp demos and remove white space from a line.

### CODE REVIEW

**Comment by InfoHunter** [comment]
Hi @pfsmorigo , we need you either add a `CLA: trivial` text in the commit message body or sign a CLA file at: https://www.openssl.org/policies/cla.html, to pass the CLA check :-)

**Comment by levitte** [comment]
Note that `CLA: trivial` must not be part of the first paragraph of the commit message, for git technical reason.  The safest way is to put it at the bottom, with an empty line separating it from the rest of the commit message.

**Comment by mattcaswell** [comment]
@levitte and/or @paulidale - can this be merged?

**Comment by paulidale** [comment]
Merged.  Thanks everyone.

**Comment by paulidale** [comment]
Merged.  Thanks everyone.

**Pull request closed without merging**
