### PR TITLE
Update CHANGES.md and NEWS.md for new release

### PR DESCRIPTION
**Pull request by mattcaswell**
Release: yes

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by nhorman — APPROVED** [review]

**Review by nhorman — APPROVED** [review]

**Comment by hlandau** [comment]
Should we not follow the new format in NEWS.md as exemplified by 3.2.0?

https://github.com/openssl/openssl/blob/master/dev/NEWS-FORMAT.md

**Comment by mattcaswell** [comment]
Fixup applied to make it clearer that the PPKCS12 issue has been fixed.

Please reconfirm approvals.

I also reformulated the NEWS entry as per @hlandau's comment

**Review by t8m — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed.

**Comment by ifranzki** [comment]
Just noticed now: You have a typo in CHANGES.md:

`OSSL_PKEY_PARAM_DERIVE_FROM_PQ` should be `OSSL_PKEY_PARAM_RSA_DERIVE_FROM_PQ` (note the missing `_RSA`)

**Comment by t8m** [comment]
> Just noticed now: You have a typo in CHANGES.md:
> 
> `OSSL_PKEY_PARAM_DERIVE_FROM_PQ` should be `OSSL_PKEY_PARAM_RSA_DERIVE_FROM_PQ` (note the missing `_RSA`)

Would you like to submit a PR?

**Pull request closed without merging**
