### PR TITLE
Fix x509_acert_sign_ctx() function in crypto/x509/x_all.c.

### PR DESCRIPTION
**Pull request by uchina1**
##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

We fixed a bug of X509_ACERT_sign_ctx() function in `crypto/x509/x_all.c`.
Issue #26107 https://github.com/openssl/openssl/issues/26107#issue-2715801551

CLA: trivial

### CODE REVIEW

**Comment by t8m** [comment]
Also the fix can be accepted with `CLA: trivial` - could you please amend the commit message (`git commit --amend`) to include `CLA: trivial` in the commit message body?

**Comment by uchina1** [comment]
I finished reverting commits and add CLA: trivial to the corresponding comment.

**Review by shahsb — APPROVED** [review]
LGTM.

Okay with CLA: trivial

Thanks for Identifying and fixing it..!

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

Commits to be squashed when merging.

**Review by beldmit — APPROVED** [review]
LGTM and agree with trivial.

As we have an example code in #26107 - if you are willing, it would be great if you added the code snippet as a test (beyond the trivial, of course, and probably as a separate PR)

**Comment by t8m** [comment]
Squashed and merged to the master and 3.4 branches. Thank you for your contribution.

**Pull request closed without merging**
