### PR TITLE
RT4669: dgst can only sign/verify one file.

### PR DESCRIPTION
**Pull request by richsalz**
Check arg count and print an error message.

For master and 1.1.0

### CODE REVIEW

**Comment by levitte** [comment]
Will there be a 1.0.2 variant?

**Comment by richsalz** [comment]
I started, but gave up for now.  The original RT has some code, but I think it's wrong.  So yes, soon.

**Comment by richsalz** [comment]
okay, @levitte, 1.0.2 version at #1557 :)

**Comment by levitte** [comment]
+1

**Comment by richsalz** [comment]
done in master and 1.1.0; closing this.

**Pull request closed without merging**
