### PR TITLE
Fix build failures on AIX

### LINKED ISSUE #18145: Build fails on AIX/Power7 due to unrecognised asm instructions
This issue is found on master, but does not exist in the 3.0.2 release. Some recent updates have introduced asm that is not compatible with older PPC machines.

The machine I'm using is:

```
-bash-4.2$ prtconf       
System Model: IBM,9109-RMD
Machine Serial Number: 100FCFP
Processor Type: PowerPC_POWER7
Processor Implementation Mode: POWER 7
Processor Version: PV_7_Compat
Number Of Processors: 2
Processor Clock Speed: 3416 MHz
CPU Type: 64-bit
Kernel Type: 64-bit
LPAR Info: 10 den00dld
Memory Size: 16384 MB
Good Memory Size: 16384 MB
Platform Firmware level: AM770_123
Firmware Version: IBM,AM770_123
Console Login: enable
Auto Restart: true
Full Core: false
NX Crypto Acceleration: Capable and Enabled
```

Using GCC:

```
-bash-4.2$ gcc --version
gcc (GCC) 4.2.1
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Configure step:

```
./Configure aix64-gcc
```

Config output:

```
-bash-4.2$ perl ./configdata.pm --dump

Command line (with current working directory = .):

    perl ./Configure aix64-gcc

Perl information:

    perl
    5.20.1 for aix-thread-multi

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    idea
    legacy
    loadereng
    makedepend
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    acvp-tests          [cascade]        OPENSSL_NO_ACVP_TESTS
    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
    asan                [default]        OPENSSL_NO_ASAN
    buildtest-c++       [default]        
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [default]        OPENSSL_NO_EGD
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fips                [default]        
    fips-securitychecks [cascade]        OPENSSL_NO_FIPS_SECURITYCHECKS
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    ktls                [default]        OPENSSL_NO_KTLS
    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]        OPENSSL_NO_MSAN
    rc5                 [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                [default]        OPENSSL_NO_SCTP
    tfo                 [default]        OPENSSL_NO_TFO
    trace               [default]        OPENSSL_NO_TRACE
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]        
    zlib-dynamic        [default]        
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar -X64",
    ARFLAGS => "qc",
    CC => "gcc",
    CFLAGS => "-O",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib -X64",
    RC => "windres",
    asm_arch => "ppc64",
    bn_ops => "SIXTY_FOUR_BIT_LONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-maix64 -pthread",
    cppflags => "",
    defines => [ "OPENSSL_BUILDING_OPENSSL" ],
    disable => [  ],
    dso_scheme => "dlfcn",
    enable => [  ],
    ex_libs => "-pthread",
    includes => [  ],
    lflags => "-Wl,-bsvr4",
    lib_cflags => "",
    lib_cppflags => "-DB_ENDIAN",
    lib_defines => [  ],
    module_cflags => "",
    module_cxxflags => undef,
    module_ldflags => "-Wl,-G,-bsymbolic,-bnoentry",
    perl_platform => "AIX",
    perlasm_scheme => "aix64",
    shared_cflag => "",
    shared_defflag => "-Wl,-bE:",
    shared_defines => [  ],
    shared_extension => "64.so.\$(SHLIB_VERSION_NUMBER)",
    shared_fipsflag => "-Wl,-binitfini:_init:_cleanup",
    shared_ldflag => "-shared -static-libgcc -Wl,-G,-bsymbolic,-bnoentry",
    shared_rcflag => "",
    shared_target => "aix",
    sys_id => "AIX",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar -X64
    ARFLAGS         = qc
    CC              = gcc
    CFLAGS          = -O
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = perl
    RANLIB          = ranlib -X64
    RC              = windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
```

Build failure:

```
        gcc -maix64 -pthread -O -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -c -o crypto/chacha/libcrypto-lib-chachap10-ppc.o crypto/chacha/chachap10-ppc.s
Assembler:
crypto/chacha/chachap10-ppc.s: line 12: Instruction stvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 14: Instruction stvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 16: Instruction stvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 18: Instruction stvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 20: Instruction stvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 21: Instruction stvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 39: Instruction vxor is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 41: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 42: Instruction vsldoi is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 43: Instruction vsldoi is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 44: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 46: Instruction lvsl is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 47: Instruction vspltisb is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 48: Instruction vxor is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 56: Instruction lvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 57: Instruction lvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 58: Instruction lvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 59: Instruction lvx is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 61: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 62: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 63: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 64: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 66: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 67: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 68: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 69: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 71: Instruction vor is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 72: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 73: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 74: Instruction vspltw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 76: Instruction vspltisw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 77: Instruction vspltisw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 78: Instruction vspltisw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 79: Instruction vspltisw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 82: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 83: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 84: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 85: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 86: Instruction vxor is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 87: Instruction vxor is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 88: Instruction vxor is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 89: Instruction vxor is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 90: Instruction vrlw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 91: Instruction vrlw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 92: Instruction vrlw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 93: Instruction vrlw is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 94: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 95: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 96: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 97: Instruction vadduwm is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 98: Instruction vxor is not implemented in the current assembly mode PPC64.
crypto/chacha/chachap10-ppc.s: line 99: Instruction vxor is not implemented in the current assembly mode PPC64.

```

### PR DESCRIPTION
**Pull request by t8m**
Fixes #18145

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
@paulidale still OK?

@jon-oracle Does it fix the build for you now?

**Comment by jon-oracle** [comment]
Tried another build, seems like the main compile is OK now. It's getting stuck later in the test code:

```
gcc  -Iinclude  -maix64 -pthread -O -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/timing_load_creds-bin-timing_load_creds.d.tmp -MT test/timing_load_creds-bin-timing_load_creds.o -c -o test/timing_load_creds-bin-timing_load_creds.o test/timing_load_creds.c
test/timing_load_creds.c: In function 'main':
test/timing_load_creds.c:198: error: expected ';' before ')' token
test/timing_load_creds.c:198: error: expected statement before ')' token
test/timing_load_creds.c:198: error: expected ';' before ')' token
test/timing_load_creds.c:198: error: expected statement before ')' token
test/timing_load_creds.c:199: error: expected ';' before ')' token
test/timing_load_creds.c:199: error: expected statement before ')' token
test/timing_load_creds.c:199: error: expected ';' before ')' token
test/timing_load_creds.c:199: error: expected statement before ')' token
test/timing_load_creds.c:200: error: expected ';' before ')' token
test/timing_load_creds.c:200: error: expected statement before ')' token
test/timing_load_creds.c:200: error: expected ';' before ')' token
test/timing_load_creds.c:200: error: expected statement before ')' token
make: The error code from the last command is 1.

Stop.
make: 1254-004 The error code from the last command is 2.

Stop.
```

Could be the timersub macro. The compiler is notoriously picky with macros.

**Comment by t8m** [comment]
> Tried another build, seems like the main compile is OK now. It's getting stuck later in the test code:
> 
> ```
> gcc  -Iinclude  -maix64 -pthread -O -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/timing_load_creds-bin-timing_load_creds.d.tmp -MT test/timing_load_creds-bin-timing_load_creds.o -c -o test/timing_load_creds-bin-timing_load_creds.o test/timing_load_creds.c
> test/timing_load_creds.c: In function 'main':
> test/timing_load_creds.c:198: error: expected ';' before ')' token
> test/timing_load_creds.c:198: error: expected statement before ')' token
> test/timing_load_creds.c:198: error: expected ';' before ')' token
> test/timing_load_creds.c:198: error: expected statement before ')' token
> test/timing_load_creds.c:199: error: expected ';' before ')' token
> test/timing_load_creds.c:199: error: expected statement before ')' token
> test/timing_load_creds.c:199: error: expected ';' before ')' token
> test/timing_load_creds.c:199: error: expected statement before ')' token
> test/timing_load_creds.c:200: error: expected ';' before ')' token
> test/timing_load_creds.c:200: error: expected statement before ')' token
> test/timing_load_creds.c:200: error: expected ';' before ')' token
> test/timing_load_creds.c:200: error: expected statement before ')' token
> make: The error code from the last command is 1.
> 
> Stop.
> make: 1254-004 The error code from the last command is 2.
> 
> Stop.
> ```
> 
> Could be the timersub macro. The compiler is notoriously picky with macros.

Could you please do some experiments to see what is needed to fix it? Otherwise we might want to just skip building this for AIX.

**Comment by t8m** [comment]
Hmm, I actually see what's wrong with it.

**Review by paulidale — APPROVED** [review]

**Comment by jon-oracle** [comment]
Compile is good now. 

I cannot run the tests yet due to a broken perl on my system, but will try to fix this up and run them.

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Merged to 3.1 and master branches. Thank you for the reviews and testing.

**Pull request closed without merging**
