### PR TITLE
Release the DRBG in global default libctx early

### PR DESCRIPTION
**Pull request by t8m**
This builds upon the test case from @bernd-edlinger in #18024.

The fix for 3.0 will need to be a separate PR as it won't merge cleanly.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
Fine with the DRBG change.  Don't know enough about the engine change to comment.

**Comment by t8m** [comment]
@paulidale still OK? I've changed the name of the function that releases the default drbg context so it is in sync with the 3.0 PR.

**Comment by paulidale** [comment]
Still okay.

**Comment by t8m** [comment]
Rebased to resolve minor conflict in context.h.

@paulidale still OK?
Ping for second review.

**Review by paulidale — APPROVED** [review]

**Review by bernd-edlinger — APPROVED** [review]

**Comment by bernd-edlinger** [comment]
I leave the review pending flag as is, since part of the PR is from myself.

**Comment by t8m** [comment]
> I leave the review pending flag as is, since part of the PR is from myself.

That part is approved by me.

**Comment by t8m** [comment]
Merged to master branch.

This will cherry-pick to 3.1 as soon as it has the libctx refactoring merged. So I am keeping this open for now.

**Pull request closed without merging**
