### PR TITLE
Convert more tests to framework

### PR DESCRIPTION
**Pull request by richsalz**
randtest, cipher_overhead_test, bioprintest
constant_time_test

### CODE REVIEW

**Comment by dot-asm** [comment]
Red cross from travis is relevant, needs to be addressed.

**Comment by richsalz** [comment]
updated commit pushed; let's see what travis says now.

**Comment by dot-asm** [comment]
As for bioprinttest, care to weigh in https://github.com/openssl/openssl/pull/3220#issuecomment-294339999?

**Comment by richsalz** [comment]
@dot-asm, good point -- moved to the 01 group.
it runs second :)

**Comment by dot-asm** [comment]
Main point in https://github.com/openssl/openssl/pull/3220#issuecomment-294339999 is that *if* testutil.c is modified to use BIO_printf, then bioprinttest.c should *not* use testutil.c. Because formally you wouldn't know who is to blame.

**Comment by richsalz** [comment]
I agree that testutil should *not* use BIO.  But I am not worried too much since if it breaks, or we port to somewhere that it doesn't work, all sorts of things will have to be addressed.

**Comment by levitte** [comment]
I'd run the bio print test in group 04...

**Comment by richsalz** [comment]
okay.  curious why, but i moved it.

**Comment by dot-asm** [comment]
> I agree that testutil should not use BIO.

Note that it's not like I object to using BIO_printf, I'm only saying that *if* we do, then we would be better off it bioprinttest.c is kept as is, and the test is moved upfront.

**Comment by levitte** [comment]
> okay. curious why, but i moved it.

'cause that's where all the other essential API tests are

**Comment by dot-asm** [comment]
Do we agree to not ever use BIO_print in testutil.c?

**Comment by richsalz** [comment]
I agree :)

**Comment by t-j-h** [comment]
Do we ever want to support systems without stdio handling and still have test suites working?

**Comment by levitte** [comment]
@t-j-h makes a good point.  I *dis*agree with never using `BIO_print` in `testutil.c`

The other solution is to have a few shims in `test_test.c` that replace the `testutil.c` writing stuff with its own printing routines, perhaps directly to file descriptors, using open(), write(), close()?  I'm sure we can isolate things properly to allow this.

**Comment by richsalz** [comment]
At any rate, putting the bio-print test in section four addresses the only thing needed for this PR.

**Comment by richsalz** [comment]
3304d57 on master, thanks.

**Pull request closed without merging**
