### PR TITLE
property: improve ossl_property_find_property() function

### PR DESCRIPTION
**Pull request by paulidale**
This function searches a property list for a specific property and returns a pointer to the definiton if found.  The improved version does this efficiently.

Based from #15570

### CODE REVIEW

**Comment by paulidale** [comment]
That fixed the errant build, thanks.

But why did only one platform have a problem???

**Comment by paulidale** [comment]
Possibly, the functions were identical in both libraries.  Perhaps some linkers detect this.

Anyway, thanks for the assistance.

**Comment by levitte** [comment]
> Possibly, the functions were identical in both libraries. Perhaps some linkers detect this.

oh, so duplicate symbols?  Yup, the MacOS X linker hates that...  and if I remember correctly, so does the MSVC linker...

**Review by mattcaswell — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
I suppose #15570 will be merged first and then this will be rebased.

**Comment by levitte** [comment]
> I suppose #15570 will be merged first and then this will be rebased.

Yes

**Comment by paulidale** [comment]
I've rebased this one.  It would suffice to merge it and #15570 will get picked up too.

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the reviews.

**Pull request closed without merging**
