### PR TITLE
WIP: Curve25519: avoid undefined behaviour

### PR DESCRIPTION
**Pull request by ekasper**
Avoid left shifts of negative values.

This is an uphill battle, but since it turned out to be not so hard, might as well. There are also implementation-defined right shifts in this code; these remain.

### CODE REVIEW

**Comment by richsalz** [comment]
i know this is third-party code, but a few define's would make it much shorter ..._1
+1
since it's a team member, no second review needed.

**Comment by kroeckx** [comment]
I'm going to guess that we only care about 2-complement systems and that the test suite is just going to fail if you try this on something that isn't 2-complement.  And that if someone really cares about a non 2-complemt system he's going to have to convert this to real multiples and divisions.

I think in that case for the left shits it's an option to use an unsigned left shift instead.

So I'm wondering if those changes have any impact on speed or not.

**Comment by richsalz** [comment]
Could we perhaps add some kind of test to "catch" such a macnine?  Like test/nptest.c ?

**Comment by ekasper** [comment]
Are you serious about testing for twos-complement? :)

As I said, you could also cast to unsigned and back, but I think this is a little less obnoxious.

Also, I benchmarked, obv. No difference on x86_64.

**Comment by richsalz** [comment]
No, but perhaps we can do a test that does some shifts and casts.  It will be too late for the build (just like nptest) but at least you'd know ...

**Comment by ekasper** [comment]
I'll add it to the bottom of my long list of things to do? :)

In practice, we did get a report of a compiler bug in similar code (the constant time stuff), so that can happen. But simple shift tests wouldn't catch it.

**Comment by richsalz** [comment]
No problem.
+1 on this.

**Comment by ekasper** [comment]
Merged.

**Comment by kaduk** [comment]
> perhaps we can do a test that does some shifts and casts. It will be too late for the build (just like nptest) but at least you'd know ...

krb5 added some configure-time checks in a similar vein at https://github.com/krb5/krb5/commit/5e54fa769 ; might provide some motivation

**Comment by richsalz** [comment]
Pushing to get this built/run as part of our config system


--
Senior Architect, Akamai Technologies
IM: richsalz@jabber.at Twitter: RichSalz

**Pull request closed without merging**
