### PR TITLE
Clear execbits on internally used perl scripts

### PR DESCRIPTION
**Pull request by bernd-edlinger**

### CODE REVIEW

**Comment by levitte** [comment]
Mind telling us why?

**Comment by bernd-edlinger** [comment]
Just for consistency.  Most scripts don't have the exec bit set.

**Comment by dot-asm** [comment]
Just in case for reference, these are not all executable internal scripts. Also for reference, the reason for why some perlasm scripts are executable some are not is incidental. When developing I customarily execute them manually, since they are not in Makefile yet. Initially I also pipe output to corresponding *-xlate. Yes, one can say that one can as well invoke perl manually and pass script name as argument. Programming is exercise in concentration, assembly programming is several times that, and then question would be if there is actual need to test it, concentration, with "one-can-do-this-instead"? In the essence it means that I for one can't guarantee that next script won't be presented for review as non-executable, or that any of *-xlate won't change mode in the process. In other words if that kind of consistency is desired, then please watch for access bits in future requests.

**Comment by bernd-edlinger** [comment]
Well, it is nothing important.  I just thought, sometimes if something is executable it might
be accidentally executed, just by accidentally forgetting typing "vi" for instance..
It may be quite possible that these scripts do no harm even if executed.

**Comment by levitte** [comment]
I'm not sure I see this as useful...  you could as well go the other way and set the exec bit on all perl scripts where this makes sense (it does not make sense on modules - i.e. `.pm` files - or on perl scripts that we know are only used via perl's `require` and similar).

I'll let someone else judge...

**Comment by bernd-edlinger** [comment]
I do just not like to invoke scripts by accident.
So it is just useful for my own security.

**Comment by t8m** [comment]
Unless it is actually dangerous to invoke these scripts by accident, and I do not think it is, I think this should be closed as this is not a real bug fix.

Some cleanup of the exec bits of .pl scripts that are not supposed to be executed directly on master branch might be acceptable.

**Pull request closed without merging**
