### PR TITLE
Adding some selected MS OIDs for #19630

### PR DESCRIPTION
**Pull request by dzuvic**
Adding some selected MS OIDs for #19630. I also added the alias ms-corp for the OID 1.3.6.1.4.1.311. Hopefully changed all occurrences for that.

##### Checklist
- documentation does not apply: registering some OIDs
- [] tests are added or updated - I did not found any related tests

##### legal notice

Unfortunately i have to add this information: 

Dragan Zuvic <dragan.zuvic@mercedes-benz.com> on behalf of Mercedes-Benz Tech Innovation GmbH

[https://github.com/mercedes-benz/mercedes-benz-foss/blob/master/PROVIDER_INFORMATION.md](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

### CODE REVIEW

**Comment by mattcaswell** [comment]
Did you run "make update"? The "check_update" CI job is failing.

**Comment by dzuvic** [comment]
> Did you run "make update"? The "check_update" CI job is failing.

Indeed, i was not aware of that. Currently running tests locally. Thank you for pointing that out.

**Comment by t8m** [comment]
> I did sent second regular CCLA from our current CEO and received a positive answer on 22nd May 2022. But i accidentally used a different email address for my last git commit. That email stated, i have to close the PR and reopen it. Should i do that?

Ah, OK. Then please recreate the commit with the e-mail that was submitted on the CLA and force-push.

**Comment by paulidale** [comment]
Changing the email of a commit: https://www.git-tower.com/learn/git/faq/change-author-name-email

**Review by t8m — APPROVED** [review]

**Comment by hlandau** [comment]
Merged to master. Thank you.

**Pull request closed without merging**
