### PR TITLE
SCT signature verification, encode/decode and accessor functions

### PR DESCRIPTION
**Pull request by robstradling**

### CODE REVIEW

**Comment by ghedo** [comment]
@robstradling @ekasper Hello, what's the status of this PR? I was looking into adding support for the signed_ceritificate_timestamp TLS extension as well (used by all Google services), but it would probably merge conflict with this work.

**Comment by ghedo** [comment]
So, I just tried to rebase @robstradling's branch on master, but it seems some work will be needed to properly merge all the changes.

**Comment by robstradling** [comment]
@ghedo In Sept 2014, Steve Henson, Emilia and I made some fairly extensive changes to the code in this PR.  It's all in one of Steve's private git branches.  Initially we were aiming to get the code into 1.0.2, but it became clear that that was just too ambitious.
Since we missed 1.0.2, and since RFC6962-bis is in the works, we decided to wait for RFC6962-bis to settle down a bit more before finalizing the OpenSSL SCT API.
So hopefully this will be picked up again within the next few months.

**Comment by mattcaswell** [comment]
Steve H says he will dust this off. The work was done prior to the reformatting so the patch will need reformatting too.

**Comment by robstradling** [comment]
@mattcaswell Thanks!

**Comment by ghedo** [comment]
Given #396 and the other work from @aeijdenberg I think this can be closed now.

**Comment by mattcaswell** [comment]
Closing in favour of #396 as per @ghedo's comment

**Comment by robstradling** [comment]
Thanks.

**Pull request closed without merging**
