### PR TITLE
Use switch instead of multiple ifs

### PR DESCRIPTION
**Pull request by ghedo**
Makes the logic a little bit clearer.

### CODE REVIEW

**Comment by dot-asm** [comment]
+1

**Comment by richsalz** [comment]
@ghedo we need a CLA....

**Comment by mattcaswell** [comment]
CLA is now registered.

**Comment by richsalz** [comment]
commit 4f8a5f4 on master.  should we backport @dot-asm to make future cherry-picks easier?

**Comment by dot-asm** [comment]
> should we backport @dot-asm to make future cherry-picks easier?

I'm confused. Labels were 1.1.0 and master and this normally means that it will be cherry-picked to 1.1.0. Or does it mean that cherry-pick is impossible already?

**Comment by richsalz** [comment]
Just wanted to be explicit.  I often forget to look at the labels, even when I assigned them :)  Thanks, will cherry-pick.

**Comment by richsalz** [comment]
commit 64d1cc0 in 1.1.0

**Pull request closed without merging**
