### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by andrewkdinh**
Update links in CONTRIBUTING.md and and fix some minor typos

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Review by shahsb — APPROVED** [review]

**Comment by FdaSilvaYY** [comment]
this seems ready to merge, but labels are off, no ?

**Comment by andrewkdinh** [comment]
@FdaSilvaYY What are the correct labels for this PR? Should I change them?

**Comment by nhorman** [comment]
labels look ok to me I think, assuming these docs exist in all the right branches.  If there are conflicts with any, we can just open a new PR to address them

**Comment by nhorman** [comment]
merged to all active branches.  Thanks!

**Pull request closed without merging**
