### PR TITLE
[apps/rand] Modifications to output file generation.

### PR DESCRIPTION
**Pull request by heavycrystal**
Two modifications to the code:

1. the size of the random output is now represented by a long, so much larger output can be generated.
2. the output chunk size is now changeable [it was 4096 by default] allowing for higher performance is some situations.

### CODE REVIEW

**Comment by paulidale** [comment]
Do you have figures backing up the higher performance claim?  I'm asking because OpenSSL's DRBGs generate in lumps of the cipher/digest block size which is much less than 4096 (okay, this is not strictly true, the CTR DRBG has assembly that does several such blocks at once but it's not a large number).  There are overheads with the generate call but amortised over 4k, I would expect them to be the critical path.

This doesn't preclude other RNGs from becoming significantly more efficient for large sizes, I'm just not aware of any.

The change to a long argument for the output length **is** worthwhile.

**Comment by heavycrystal** [comment]
I haven't had a look at how the underlying RNGs work, but I did notice performance improvements when using the -out option with a bigger chunk size. This could be attributed to other factors such as fewer write() syscalls and less tight loops and might not have anything to do with the performance of the underlying RNG itself. 

I did some rudimentary syscall profiling via strace and the overall time spent in write() syscalls does decrease as we go to higher chunk sizes, at least on my Linux machine. The performance improvements might be very system dependent, but I feel this option can be useful in some cases. 

One particular test yielded a ~7% time improvement between chunk sizes of 4096 bytes and 8MB when generating 64GB of random data.

**Comment by t8m** [comment]
I would not add a new buflen option when there is already a chunk option. Just increase the size of the buffer to something reasonable for where the performance difference is minimal when it would be larger and allocate it on the heap.

I think something like 128kB buffer would do.

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master after squashing the commits.
Thanks for the contribution.

**Pull request closed without merging**
