### PR TITLE
Correct memory ordering for rcu atomic assign/deref on Apple M1 cpus

### PR DESCRIPTION
**Pull request by nhorman**
Since the addition of macos14 M1 runners in our CI jobs we've been
seeing periodic random failures in the test_threads CI job.
Specifically we've seen instances in which the shared pointer in the
test (which points to a monotonically incrementing uint64_t went
backwards.
    
I believe the following is whats happening:
1) ossl_rcu_uptr_deref and ossl_rcu_assign_uptr are implemented using
       __atomic_load_n and __atomic_store_n.  The store operation is tagged
    as __ATOMIC_RELEASE and the load is tagged as __ATOMIC_ACQUIRE.
    
2) On strongly ordered memory access cpus, like x86, this is sufficient,
       as instructions are emitted for these builtins to ensure proper
    fencing of any prior reads/writes (i.e. a lock prefix may be prepended
    to ensure cache synchronization.  See:
    [https://en.cppreference.com/w/c/atomic/memory_order](https://en.cppreference.com/w/c/atomic/memory_order)
    Specifically the section on release-acquire ordering
    
3) On weakly ordered memory access cpus, like arm, additional fencing
       instructions must be issued to ensure prior reads/writes become
    visible to other cpus.  Again see:
    [https://en.cppreference.com/w/c/atomic/memory_order](https://en.cppreference.com/w/c/atomic/memory_order)

4) Ostensibly, I would have assumed that an
       __atomic_load_n/__atomic_store_n with the tagged semantics would
    have resulted in the implicit emission of a fence instruction to ensure
    ordering.  However, disassembling the output of a build on a macosx 14
    system with the clang compiler shows that not to be the case:
    0000000100120488 <_ossl_rcu_uptr_deref>:
    100120488: f8bfc000     ldapr   x0, [x0]
    10012048c: d65f03c0     ret
    
    0000000100120490 <_ossl_rcu_assign_uptr>:
    100120490: f9400028     ldr     x8, [x1]
    100120494: c89ffc08     stlr    x8, [x0]
    100120498: d65f03c0     ret
    
    I'm not well versed enough in the standard to know if this translation
    would be a compiler bug or not, but it does seem that, in a weakly
    ordered system, this series of instructions, when run on multiple
    threads may lead to writes getting published to other threads late,
    resulting in a counter that appeared to go backwards.
    
    So what to do about it?  From my interpretation of memory fencing:
    https://en.cppreference.com/w/c/atomic/atomic_thread_fence
    It seems we can issue these atomic loads/stores with a relaxed ordering
    and independent fencing.

    by doing so, the M1 assembly turns into this:
    0000000100120488 <_ossl_rcu_uptr_deref>:
    100120488: f9400000     ldr     x0, [x0]
    10012048c: d50339bf     dmb     ishld
    100120490: d65f03c0     ret
    
    0000000100120494 <_ossl_rcu_assign_uptr>:
    100120494: d5033bbf     dmb     ish
    100120498: f9400028     ldr     x8, [x1]
    10012049c: f9000008     str     x8, [x0]
    1001204a0: d65f03c0     ret
    
    In which dmb (memory barrier) instructions are inserted as expected,
    enforcing publishing of all prior issued memory instructions.
    
    I've run these changes 10 times through CI (which is the only place
    we've found that reproduces this issue), and encountered no subsequent
    failures.
    
    Note: To avoid tsan errors that arise from the inability of the
    gcc/clang thread sanitizer to properly interpret thread fences, the
    addition of TSAN notifications are required to properly inform the
    sanitizer that this code is properly ordered

### CODE REVIEW

**Comment by nhorman** [comment]
@tom-cosgrove-arm would greatly appreciate your input on this issue please.  Specifically if you could comment on the memory synchronization properties of arm cores in general (and the M1 specifically if possible) that would be a big help.  Trying to concretely understand if an __atomic_[load|store] operation with __ATOMIC_RELEASE | __ATOMIC_ACQUIRE ordering is expected to imply a memory fence on code targeting those processors.  The assembly I've observed seems to say "no, it doesnt" but I'm not sure if thats expected or not

**Comment by nhorman** [comment]
To clarify what I think is happening here, as a sequence diagram:
sequence

In the above sequence diagram, because (as I believe) arm cpus don't imply fencing on atomic loads/stores, what we see happening is that, multiple writer threads issue store instructions for data in addresses shared by multiple threads, but because of their weak memory ordering semantics, its possible for those writes to be completed in a different order than what two independent cpus issued in the timeline.  As a result, two subsequent reads of that data might see out of order results (i.e. a reading thread might see the value posted by writer thread B first, and then later see the value posted by writer thread A, leading to the error we see in which the reader thinks the shared updated counter went "backwards")

**Comment by tom-cosgrove-arm** [comment]
@nhorman Yes, I would generally expect an `__atomic_load_n(foo, __ATOMIC_ACQUIRE)` or `__atomic_store(foo, bar, __ATOMIC_RELEASE)`to issue the required memory barrier instructions, and I would assume lack of these to be a compiler bug.

I will check with our compiler folks to get their opinions, however - and with the bank holidays, it will probably take a few days to get an answer

**Comment by nhorman** [comment]
@tom-cosgrove-arm thank you, no rush.  We have a workaround for the 3.3 release on this, just trying to get it fixed properly during 3.4

**Comment by nhorman** [comment]
@tom-cosgrove-arm that matches my observations in the initial problem statement here.  My assumption is that the memory order parameter to these operations only specify restrictions to code hoisting/sinking within the given compilation unit.  It just so happens that on x86, the compiler, in its use of the lock prefix on the load and store instruction implies memory synchronization between cpu caches that isn't guaranteed to exist on other arches.  I'll be interested to see if your compiler team agrees with that assessment.

**Comment by nhorman** [comment]
@tom-cosgrove-arm apologies, don't mean to rush you here, but theres been some shared interest here in determining what the expected behavior on arm is, and if this patch is on the right track for fixing it.

**Review by paulidale — APPROVED** [review]
I find it difficult to believe that this isn't working around a compiler problem.

**Comment by nhorman** [comment]
I agree that it certainly seems like atomic_load/store should imply a memory fence, but apparently it's consistent across several versions of clang and gcc.

On a lark I took a look at the assembly for pthread_mutex_lock on arm, and a dmb instruction is emitted on that call to do proper fencing.  I need to follow up and see if the c level code uses a built-in or some hand rolled asm to do it

**Comment by paulidale** [comment]
That it emits locked instructions on x86 but doesn't try on ARM is telling.

If the compiler were just ordering memory accesses, it wouldn't need to emit the lock prefix.

**Comment by tom-cosgrove-arm** [comment]
Ah, okay, so actually what's happening is that the Armv8-A ISA includes a pair of instructions Load-Acquire (LDAR)/Store-Release (STLR) with the required semantics, and those instructions are used by the compilers.

For example, `__atomic_load(p1, p2, __ATOMIC_ACQUIRE)` becomes

```
        ldar    x8, [x0]
        str     x8, [x1]
```

and `__atomic_store(p1, p2, __ATOMIC_RELEASE)` becomes

```
        ldr     x8, [x1]
        stlr    x8, [x0]
```

on clang 9, 10, 11, 12, 13 and 14 (and armclang) and

```
        ldar    x0, [x0]
        str     x0, [x1]
```

and

```
        ldr     x1, [x1]
        stlr    x1, [x0]
```

on gcc 10, 11 and 12.

Unfortunately I missed the `a` in the `ldar` and the `l` in `stlr` when reading the assembly.

Looking at the assembly in the description we do indeed see `ldapr` (https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/enabling-rcpc-in-gcc-and-llvm) and `stlr`, so I'm not sure what the cause of the random failures is now, or that this PR would fix them.

**Comment by nhorman** [comment]
@tom-cosgrove-arm thank you for the update.  Looking further into the lda[p]r and strl instructions here:
https://developer.arm.com/documentation/ddi0602/2023-09/Base-Instructions/LDAPR--Load-Acquire-RCpc-Register-

It indicates:
```
Load-Acquire RCpc Register derives an address from a base register value, loads a 32-bit word or 64-bit doubleword from the derived address in memory, and writes it to a register.

The instruction has memory ordering semantics as described in Load-Acquire, Load-AcquirePC, and Store-Release, except that:

There is no ordering requirement, separate from the requirements of a Load-AcquirePC or a Store-Release, created by having a Store-Release followed by a Load-AcquirePC instruction.
The reading of a value written by a Store-Release by a Load-AcquirePC instruction by the same observer does not make the write of the Store-Release globally observed.
This difference in memory ordering is not described in the pseudocode.
```

Looking at the Load-AcquirePC instructions docs:
https://developer.arm.com/documentation/102336/0100/Load-Acquire-and-Store-Release-instructions

It documents (I think) the sequential ordering requirements or ldar/stlr instruction, and also (perhaps notably) discusses limited ordering regions, which (again, I think) constrain the areas of memory to which the ordering of an ldar/stlr instruction apply.  

Looking at figure 7, it would seem that, if an area of memory isn't covered by a limited ordering region, the ldar/stlr instructions might effectively reduce to regular loads/stores

Given that this problem (so far) has only been observed on virtualized M1 cpus, I'm wondering if the virtualization software doesn't properly emulate ordering regions (maybe)?

I can try to write some assembly that dumps out the values of the region descriptor to confirm that

**Comment by nhorman** [comment]
well, thats a bust. Accessing LOR* registers while in EL0 is undefined, so we can't actually dump the load ordering regions at run time.

**Comment by kroeckx** [comment]
All I've read so far seems to say that the old code was correct, and that we should avoid the memory barrier that this is introducing.

So I'm assuming this is some bug in the virtualization. I think we should at least attempt to report this bug.

**Comment by t8m** [comment]
In that case we will probably have to workaround this issue somehow? It can be something Apple aarch64 specific. I do not think we want to detect the virtualization.

**Comment by nhorman** [comment]
I've got a hunch that I'm tracking down now, standby

**Comment by nhorman** [comment]
So, Based on @tom-cosgrove-arm input (thanks again!) I noticed something.  In his analysis [here](https://github.com/openssl/openssl/pull/23974#issuecomment-2034152773) he indicates that __atomic_load builtins should produce the following:
```
ldar    x8, [x0]
str     x8, [x1]
```

However ,using the clang compiler installed on w-mac-mini-m1-2.openssl.org:
```
SSL2:~ nhorman$ clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I see the following instruction emitted for an __atomic_load builtin:
```
 ldapr   x0, [x0]
 ret
```

Note the use of ldapr rather than ldar.  Both are atomic load-acquire operations, but the latter is subtly different.  Most notably, according to:
https://developer.arm.com/documentation/ddi0602/2023-09/Base-Instructions/LDAPR--Load-Acquire-RCpc-Register-

ldapr has more relaxed ordering requirements than ldar (I think).  Specifically it honors the Limited ordering register in the arm coprocessor, rather than performing global ordering (again I think).  The LDAR page here:
https://developer.arm.com/documentation/dui0802/b/A64-Data-Transfer-Instructions/LDAR
Is somewhat quiet on its specific ordering constraints, but it seems sensible given that there are 2 instructions to do the same thing.

My hypothesis is that, while I can't dump out the Limited order registers on the M1 (they are only accessible in EL1 and above), that on the physical M1 CPU the entirety of main memory is considered a single ordering region, while on the virtualized cpu there may be multiple (or perhaps there is just a bug in the MacOSX virtualization software, leading to unexpected out of order loads/stores.

As such, I created this dummy PR:
https://github.com/openssl/openssl/pull/24031

It makes the following change:
https://github.com/openssl/openssl/pull/24031/commits/cc8bb7b96b02191ad44528d5f96d5a52d7441235#diff-33114a13bd417cbc08f1be5b6ba0ae94f1a86516e0635d508d6e7fc55908a423R561-R567

So, now, for arm64 builds in the PR, we manually create an atomic load specifically using the ldar instruction

I would assert that, if this makes the threadstest failure abate on the virtualized M1 cpu, then we can at least have a strong suspicion that either this is in fact a compiler bug (as the ldapr instruction can't be used reliably, dependent on the LOR register configuration), or that the virtualized M1 cpu has an ordering problem.

If thats the case, I would say we need to work around this problem by using relaxed ordering and an explicit memory fence (as thats the most portable solution).

and as @kroeckx mentions, we should definately raise this as an issue with apple.  If anyone has a contact method to do so, I would be glad to follow up on that

**Comment by kroeckx** [comment]
Note that https://developer.arm.com/documentation/102336/0100/Load-Acquire-and-Store-Release-instructions does describe the ldapr (Load-AcquirePC) intructions semantics. It's now "processor consistent". If there are multiple processors, it does not guarantee the order that the test checks for.

**Comment by kroeckx** [comment]
At first sight, the compiler seems to generate code that does not comply with the C11 memory model.

**Comment by kroeckx** [comment]
For gcc the defaults are:
from 5.5 gnu11
from 11: gnu17

Can't really find it for clang

**Comment by nhorman** [comment]
@tom-cosgrove-arm, no to the best of my knoweldge we are compiling with either -ansi (for the ansi builds) or -c89 otherwise.

I agree that ldapr is available for use on the M1 platform, just questioning under what conditions its safe to do so.  As @kroeckx indicates ldapr is processor consistent, but only with the limiting odering regions that the coprocessor registers define (which are admittedly opaque).  There is also of course the possibility of a bug in the M1 virtualization code that changes the sematics of ldapr in some way as of yet unknown to us.

trying to make  a developer account with apple now to raise the issue, but the site is failing at the moment, unsure why.

so far, my test pr here  https://github.com/openssl/openssl/pull/24031 is on 5 iterations of the mac os 14 test without failure.  Starting to feel like ldapr in a virt system is a problem here

**Comment by kroeckx** [comment]
I don't think we override the default std except in some special builds

**Comment by kroeckx** [comment]
My understanding is that our test is written for the acquire release semantics as in C11, but that the compiler generates code for a weaker model, and so that this is a compiler bug.

The RCU code doesn't actually need the acquire release semantics, acquire consume would be enough, but I don't think even that is provided by the compiler.

**Comment by tom-cosgrove-arm** [comment]
Actually, could I suggest that we keep the current implementation for most builds, and special case with `#ifdef` for Apple Silicon the fix in your other PR? i.e. your possible solution (1).

The reason is to have the code reflect reality: the reality that (we think) the current could should work, but a workaround is needed on Apple Silicon (because of the issue when virtualised)

If we don’t do this, and change the code along the lines of solution (2), at some point in the future a well-meaning engineer could easily "improve" the code to the current implementation, at which point we’ll have the virtualised Apple Silicon issue all over again. If not in this project (we might remember, and not allow the change) then if this code gets copied and used elsewhere.

**Comment by kroeckx** [comment]
I do have to wonder if #24031 has other optimization side effects, that probably only show up in an LTO build. Is the ldapr vs ldar the only change in generate code? I think we should at least also try this with LTO, and possibly have LTO in CI.

**Comment by t8m** [comment]
Do we actually have multiple CPUs on the Apple M1 hardware where you've tested this @nhorman ? Because the difference might be in presence of multiple CPUs (not cores) on the testing platform.

**Comment by nhorman** [comment]
I need to augment the get cpu info step in CI to test that, but running:
```
sysctl -a
```
on our M1 shows this:
```
hw.cachesize: 3540500480 65536 4194304 0 0 0 0 0 0 0
hw.l2cachesize: 4194304
hw.physicalcpu: 8
```
Which suggests to me there that we have 8 cpu cores, each at least with their own l1 cache, and a shared l2 cache

**Comment by nhorman** [comment]
The github runner reports the following:
```
machdep.cpu.cores_per_package: 3
machdep.cpu.core_count: 3
machdep.cpu.logical_per_package: 3
machdep.cpu.thread_count: 3
machdep.cpu.brand_string: Apple M1 (Virtual)
hw.cachesize: 3209920512 131072 12582912 0 0 0 0 0 0 0
hw.l2cachesize: 12582912
hw.physicalcpu: 3
CPUINFO: OPENSSL_armcap=0x987d
```
which I think suggests that we have 3 physical cpus

**Comment by nhorman** [comment]
@tom-cosgrove-arm yeah, I can be on board with that.

Question: How do we want to detect apple silicon?  The easy method would be to use #ifdef __aarch64__, but that nets in all arm silicon, not just apple.  I could detect MACOSX, which would be a bit closer to the mark, but would net both physical and virtual cpus, which may be the best we can do without a runtime check (which I would like to avoid for performance reasons)

**Comment by nhorman** [comment]
ok, so since the other PR was just for testing, and all our conversations have been here, I'm going to update this PR with the change to implement __atomic_load using ldar rather than ldpar here

**Comment by tom-cosgrove-arm** [comment]
> Question: How do we want to detect apple silicon?

I would suggest `#if defined(__APPLE__) && defined(__aarch64__)`. Yes, this will catch physical CPUs as well as virtual ones, but I don't think we can help that.

(And please, a lovely succinct comment explaining why we're special-casing Darwin/aarch64, for when we come back to it in N months time and wonder "huh?"!)

**Comment by paulidale** [comment]
Do both gcc and clang output the errant instruction?
If not, we should condition on the compiler too.

**Comment by nhorman** [comment]
@pauli, unsure, gcc command on our m1 is aliased to clang

**Comment by paulidale** [comment]
The cross compile builds include aarch64 with gcc from memory.

**Comment by nSircombe** [comment]
> @pauli, unsure, gcc command on our m1 is aliased to clang

@nhorman  - you can install an actual gcc on macOS alongside Clang with [Homebrew](https://brew.sh).

```
> gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

> gcc-12 --version
gcc-12 (Homebrew GCC 12.3.0) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by nhorman** [comment]
@nSircombe interestingly, I installed gcc-13 via homebrew on our development M1 and built with:
```
CC=gcc-13 ./Configure
```

dumping out the assembly for the ossl_rcu_uptr_deref function:
```
0000000100143a40 <_ossl_rcu_uptr_deref>:
100143a40: c8dffc00     ldar    x0, [x0]
100143a44: d65f03c0     ret     
100143a48: d503201f     nop     
100143a4c: d503201f     nop   
```

so there is clearly a discrepancy here between gcc and apples clang, which produces:
```
0000000100120488 <_ossl_rcu_uptr_deref>:
100120488: f8bfc000 ldapr x0, [x0]
10012048c: d65f03c0 ret
```

The CI job we run on this doesn't install any additional software from homebrew, so I'm relatively certain that its using the apple clang 15 compiler.

**Comment by nhorman** [comment]
Ok, I've updated this patch to no use the relaxed ordering/fencing approach, and instead implemented an ldar based atomic_load function, to be used only when __APPLE__ && __clang__ and __aarch64__ is defined.  I've run it several times, and encountered no issues on macosx.  Please review and (re)approve when you all can.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM - nice. Now let's hope we never get one of these test failures again!

**Comment by tom-cosgrove-arm** [comment]
I've updated the labels to indicate my committer approval and that an OTC (re-)approval is required

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master and 3.3 branches. Thank you.

**Pull request closed without merging**
