### PR TITLE
doc: Fix typo in manpage

### PR DESCRIPTION
**Pull request by Jakuje**
CLA: trivial

Signed-off-by: Jakub Jelen <jjelen@redhat.com>

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Its trivial for CLA purposes.
Maybe update the commit message to 'doc: Fix typo in  EVP_DigestSignInit manpage'.

**Comment by slontis** [comment]
Looks like someone may have already fixed this as part of another PR that has been merged..
My guess is @levitte

**Comment by Jakuje** [comment]
No, it was not fixed, but now it conflicts with #10815, which got merged. I will re-push it with the suggested commit message and rebase on top of current master.

**Comment by Jakuje** [comment]
Rebased. Now applies cleanly.

**Comment by mattcaswell** [comment]
@levitte please confirm you consider this trivial

**Comment by mspncp** [comment]
Merged to master and 1.1.1, thank you!

099a398268 doc: Fix typo in EVP_DigestSignInit manpage
6b9c86c471 doc: Fix typo in EVP_DigestSignInit manpage

**Pull request closed without merging**
