### PR TITLE
Make OSSL_PARAM descriptions uniformly formatted.

### PR DESCRIPTION
**Pull request by paulidale**
```
=item B<MACRO> ("name") <type>
```

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Personally, I would prefer this:

``` perl
=item "name" (B<macro>) <type>
```

The difference is subtle, but denotes that macros are optional rather than the main thing. I hope that will avoid having people ask us to insert macros (work as a name registry) for all kinds of external things.

**Comment by paulidale** [comment]
Easy to change -- it's a short _sed_ script if I caught all instances.

**Comment by paulidale** [comment]
The format has been switched around.

**Comment by paulidale** [comment]
Merged, thanks.

**Pull request closed without merging**
