### PR TITLE
correct spelling errors detected by Debian lintian

### PR DESCRIPTION
**Pull request by andreasschulze**
trivial contribution
CLA: trivial

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by andreasschulze** [comment]
unsure about the best way to put "CLA: trivial" in a commit message.
I now followed https://help.github.com/articles/changing-a-commit-message/
and see an updated commit message in my repo: https://github.com/andreasschulze/openssl/commit/eda70ef8a6722ad3f92261e2e901dcb30c6dbb6e

Is this enougth or should I create a new pull request?

**Comment by levitte** [comment]
The reason that the CLA checker can't process this correctly is that the commit message looks like this:

```
correct spelling errors detected by Debian lintian
CLA: trivial
```

There's no empty line between the two, which means that they get merged into a subject line in git terms.  If you look at the resulting [patch](https://github.com/openssl/openssl/pull/5801.patch), you can see clearly what happens.  This is an impossible thing to check correctly...

So I think that we can approve this, and if need be, edit the commit message to insert that empty line when merging.  I can take it upon myself, if everyone that approves agrees this is legally trivial.

**Comment by mspncp** [comment]
I agree it's trivial.

**Comment by levitte** [comment]
Merged into master.

aa3b328541ff67dde7c40ae73dd11a296647ae3d correct spelling errors detected by Debian lintian

**Comment by levitte** [comment]
This should really be cherry-picked to 1.1.0 and possibly 1.0.2.  Does anyone approve?

**Comment by mspncp** [comment]
+1. Go ahead, if it applies.

**Comment by levitte** [comment]
Actually, it seems the changes here only apply to master, so closing this

**Pull request closed without merging**
