### PR TITLE
test/evp_test.c: try fetching algorithms

### PR DESCRIPTION
**Pull request by levitte**
Instead of relying on implicit fetches, try explicit fetches when available.

-----

Note: this is #9106 continued

### CODE REVIEW

**Comment by levitte** [comment]
In #9106, we could see three problem cases:

- *SHAKE output length*
- ~*Mismatched algorithms*~ [solved in #9109]
- *AES-SIV freeze*

All of them related with explicitly fetched algorithms.

**Comment by levitte** [comment]
Oh!  It looks like the freeze stopped happening too.  I assume it has to do with the recent reversal of RAND stuff.

So there's only one thing left to deal with, *SHAKE output length*

**Comment by levitte** [comment]
With all EVP_CIPHER and EVP_MD changes that have been merged, this modification can now do its job correctly.  Time for a final review, methinks!

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
I had to rebase and do some minor mods.  Re-review needed

**Review by paulidale — APPROVED** [review]

**Pull request closed without merging**
