### PR TITLE
Remove redundant check for saltlen > UINT32_MAX

### PR DESCRIPTION
**Pull request by faramir-dev**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Typo in the commit message UINT32_MAC->UINT32_MAX.

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you.

**Comment by mattcaswell** [comment]
I don't understand why this is a redundant check? `unsigned int` could be greater than `UINT32_MAX` on some platforms?? i.e. if `UINT_MAX > UINT32_MAX`?

**Comment by t8m** [comment]
Is there any concrete 64 bit platform where UINT_MAX > UINT32_MAX?

**Comment by mattcaswell** [comment]
I don't know - but it seems perfectly plausible to me. Even if there are none now it is perfectly possible that such a platform might be interesting in the future. Given that - this check seems perfectly reasonable and sensible. Any decent compiler will optimise it out where it isn't relevant.

**Pull request closed without merging**
