### PR TITLE
Fixed range of random produced in BN_is_prime_fasttest_ex()

### PR DESCRIPTION
**Pull request by slontis**
According to the FIPS 186-4 C.3.1 (4.1)  The range is expected to be 1 < b < w-1.
It was using 1 <= b < w (which is wrong by 1 on both ends).
This is because rand_range(n) returns 0 <= b < w-1 (and then it added 1).
So instead use 2 + rand_range(w-3).
There is also a check for the number '3' added that early exits (in the case where trial_divisions is not used).
Also removed a redundant check for is_zero after subtracting 1 as it already checks <= 1

##### Checklist
- [x] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Should this be backported to 1.1.0?

**Comment by paulidale** [comment]
The probability of hitting either of the end points is low: 2^(1-w).  I think hitting the low end could reject a legitimate prime, which would be a slow down, but would otherwise be harmless.  I'm not sure about the high end -- I'd need to check for being even and if not work through the mathematics.

If this is back ported to 1.1.0, it should also go to 1.0.2.  I don't see a need for either but would be easily convinced otherwise.

**Comment by richsalz** [comment]
We don't claim FIPS compliance, so this seems like just a bugfix for master.

**Comment by paulidale** [comment]
I'm happy with just master.  Looking more deeply, it seems that the only result at the limits is that a prime number can be declared not prime which shouldn't be harmful.

**Comment by paulidale** [comment]
Merged to master only.

**Comment by paulidale** [comment]
Thanks!

**Pull request closed without merging**
