### PR TITLE
Addressed build failure because of missing #ifdef AF_UNIX guard

### PR DESCRIPTION
**Pull request by fractalb**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by kaduk** [comment]
It could be useful to note (e.g., in the commit message) which types of environment are affected.
Formality: I think this is a trivial change.
If you agree, and do not want to sign the CLA, you should amend the commit message to include the text "CLA: trivial" as a line by itself at the end of the commit message.

**Comment by fractalb** [comment]
@kaduk updated the commit message with "CLA:trivial". Do I need to issue a new pull request now?

**Comment by kaduk** [comment]
@fractalb no, the new commit is showing up on this pull request.
(The automated need-cla check may have been confused by spelling it "CLA:trivial" (no space) rather than "CLA: trivial", but that is easy for us to fix.)

**Comment by kaduk** [comment]
@fractalb I still am curious to know what sort of system you ran into this on, if you're willing to share.

**Comment by levitte** [comment]
@kaduk, that would be any system that doesn't have Unix sockets. That's all apart of Unix (windows and VMS)

**Comment by fractalb** [comment]
@kaduk OpenSSL on top of a custom TCP stack on baremetal OCTEON boards of Cavium's.  (no UNIX/LINUX environment and no UNIX sockets)

**Comment by mattcaswell** [comment]
@richsalz - ok for this to go into 1.1.0 too?

**Comment by richsalz** [comment]
yes for 1.1.0

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
