### PR TITLE
test/test_test.c: fix wrong BN test [and rearrange tests a little bit].

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by richsalz** [comment]
why did this pass?  is it because @pauli-oracle used ```|``` and not ```||``` >

**Comment by dot-asm** [comment]
> why did this pass?

It didn't. The failure was masked by run_tests.pl. *All* failures were masked, i.e. CI reports were coming out green even if there were failures. Currently there is one more failure in test_secmem...

**Comment by richsalz** [comment]
AHA!  Thanks.  Look at #3455 which is ready to merge.

**Comment by richsalz** [comment]
I merged this because I  also merged #3455 so maybe now we get clean builds?

**Pull request closed without merging**
