### PR TITLE
Updates CT log list

### PR DESCRIPTION
**Pull request by RJPercival**
Latest list of Certificate Transparency logs that have completed at least 90 days of Google's compliance monitoring successfully.

Generated by https://github.com/RJPercival/certificate-transparency/blob/0a753fb4487bbf33de7b202133aac95cd0bf21b2/python/utilities/log_list/openssl_generator.py from the log list found at https://sites.google.com/site/certificatetransparency/known-logs.

### CODE REVIEW

**Comment by richsalz** [comment]
+1.  I'd argue this is a bugfix for 1.1.0 but could be persuaded if another team member feels strongly about it.

**Comment by vdukhovni** [comment]
I think that (tests aside) we should exclude *all* CT logs from the OpenSSL distribution. We are not curators of trust anchors and ship no trusted CAs with OpenSSL.  Similarly we should ship no CT log definitions.

Which logs are in and which are out should be decided by downstream distributions that augment OpenSSL with trusted CAs, ... and curate those lists.

**Comment by richsalz** [comment]
I would be fine with that approach as well.

**Comment by vdukhovni** [comment]
So I think the solution is to:

1. Not install the CT log server configuration file.
2. Leave in only the entries needed for testing, and move it into the test directory.
3. Make no further attempts to keep the file complete or up to date.

**Comment by RJPercival** [comment]
I'd also prefer that approach, though it adds a barrier to adoption. Does anyone know how that could be orchestrated? At least contacting the distributors and letting them know that this responsibility is falling to them seems wise. There's already a test log list in `test/ct/log_list.conf`, but it'd be nice to distribute this one as an example under the `doc` directory; perhaps along with a short HOWTO for enabling CT by specifying a policy and log list.

A counter-argument is that, if OpenSSL ceases to distribute the log list immediately, `openssl s_client -ct` will no longer work out-of-the-box.

**Comment by richsalz** [comment]
How about this.  We update this file.  Put a URL in the file comments where Google will keep a current version.

**Comment by vdukhovni** [comment]
I say we ship an "empty" file with just a comment that directs users to the location of the Google-curated CT logs.

As for "s_client -ct" not working out of the box, this is not different than "s_client" not being to authenticate any peers out of the box.  CT users will quickly figure out where to obtain suitable CT log server lists (in practice almost always provided by the distributions once CT catches on).

I don't think that the OpenSSL project should be in the business of designating trust anchors.

**Comment by richsalz** [comment]
That’s also fine with me.  And I share the concern about just adopting Chrome's logs as trustpoints.

**Comment by RJPercival** [comment]
SGTM.

**Comment by richsalz** [comment]
Okay, so give us a link we can put in the file, or update this PR ☺

**Comment by richsalz** [comment]
This is superceeded by #1559.

**Pull request closed without merging**
