### PR TITLE
GH715: ENGINE_finish can take NULL

### PR DESCRIPTION
**Pull request by richsalz**
Simplifies calling code.  Also fixed up any !ptr tests that where
nearby, turning them into NULL tests.
Addresses https://github.com/openssl/openssl/issues/715

### CODE REVIEW

**Comment by levitte** [comment]
I'm fine with this

**Comment by richsalz** [comment]
Is that a plus-one? :)

**Comment by FdaSilvaYY** [comment]
I was working on it .
I push the concept a bit further : https://github.com/FdaSilvaYY/openssl/tree/ENGINE_finish_upg

**Comment by richsalz** [comment]
I think removing the ifdef's goes too far.

**Comment by FdaSilvaYY** [comment]
I also add a no-engine build to travis, and fix openssl/test/dtlsv1listentest.c for it .

**Comment by levitte** [comment]
> I think removing the ifdef's goes too far.

I agree, at least that generally.  However, if we limit that to `apps/*.[ch]`, I see nothing wrong with that.

**Comment by richsalz** [comment]
If we do a no-engine build (great idea, is that a separate commit or PR we can use) then the *NO* ```ENIGINE_xxx``` API should be available.  So adding that build and fixing the test you mentioned would be great.

**Comment by FdaSilvaYY** [comment]
Ok, I push it ASAP.

**Comment by richsalz** [comment]
great, thanks.  btw, can you email me rsalz at openssl.org ?  thank you.

**Comment by richsalz** [comment]
ping, @levitte , did "i'm fine with it" mean plus-one? :)

**Comment by levitte** [comment]
yes

**Comment by richsalz** [comment]
thanks.  pushed at 7c96dbc

**Comment by richsalz** [comment]
there were some missing found by @FdaSilvaYY , fixed in 412bafd

**Pull request closed without merging**
