### PR TITLE
Update X509_STORE_new.pod

### PR DESCRIPTION
**Pull request by sambitdash**
Minor typo.

##### Checklist

- [x] documentation is added or updated

CLA: trivial

### CODE REVIEW

**Comment by levitte** [comment]
To avoid needing a CLA, I suggest adding this line in your commit message:

```
CLA: trivial
```

You need to separate it from the rest of the commit message with an empty line.

(for formality: this looks legally trivial to me, I will approve it as such)

**Comment by sambitdash** [comment]
Please consider as a suggestion and "Not Contribution".

**Comment by sambitdash** [comment]
CLA: trivial

**Comment by levitte** [comment]
> we normally only accept pull requests against our master branch

I think that for such a small thing, it's perfectly ok to make a PR against the branch where you discovered the problem.  I don't see an actual problem cherry-picking from 1.1.1 to master in a case like this.

**Comment by mspncp** [comment]
Merged, thanks!

3527cfcf28 Update X509_STORE_new.pod [master]
d2b736df0e Update X509_STORE_new.pod [1.1.1]

**Pull request closed without merging**
