### PR TITLE
Rename EVP_PKEY_cmp() to EVP_PKEY_eq() and EVP_PKEY_cmp_parameters()  to EVP_PKEY_parameters_eq()

### PR DESCRIPTION
**Pull request by DDvO**
As discussed in #11870

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by DDvO** [comment]
All right, done.

**Comment by romen** [comment]
Should these changes be reflected also on the provider interface?

**Comment by levitte** [comment]
> Should these changes be reflected also on the provider interface?

The name in that interface is `OP_keymgmt_match()`.  Semantically speaking, I don't see that it needs to be changed.

**Comment by vt-alt** [comment]
Is it correct just to replace `EVP_PKEY_cmp` with `EVP_PKEY_eq`? I thought it's decided they should return different values.

```
-        ret = EVP_PKEY_cmp(xk, k);
+        ret = EVP_PKEY_eq(xk, k);
```

**Comment by DDvO** [comment]
@vt-alt, no, it would be very hard to change the semantics of `EVP_PKEY_cmp()` to properly do an order-like comparison. Instead we make clear that it basically just checks for equality.
OTOH, the name and return values of `X509_PUBKEY_cmp()`, now `X509_PUBKEY_eq()`, will change due to #11894, and will be consistent with `EVP_PKEY_eq()`.

**Comment by vt-alt** [comment]
I don't say to change `EVP_PKEY_cmp`, but isn't `EVP_PKEY_eq` should return 1 for a match? Now it will return 0, isn't it?

**Comment by DDvO** [comment]
On equal input, `EVP_PKEY_eq()`, which is the same as the former `EVP_PKEY_cmp()`, continues to return 1, and `X509_PUBKEY_eq()`, which is the fixed `X509_PUBKEY_cmp()`, will return also 1 (making direct internal use of `EVP_PKEY_eq/cmp()`, which is now correct, see https://github.com/openssl/openssl/pull/11894/files#diff-a4d3e5a924de45dc8e27b1f12c1907ad).

**Comment by vt-alt** [comment]
@DDvO Ah, yes! Thanks.

**Comment by t8m** [comment]
Of course this will require update after #11894 is merged.

**Comment by levitte** [comment]
Sorry for throwing this in so late, but I'm not sure `eq` is much better than `cmp`.  What does "equality" mean, precisely?  For example, `EVP_PKEY_cmp()` compares key parameters and the public key, does that make two EVP_PKEYs equal?  One could contain the private half while the other doesn't, are they equal?

How about "match" instead of "eq"?

(I'll totally blame @romen for reminding me of the name used in the provider interface :wink:)

**Comment by DDvO** [comment]
> Of course this will require update after #11894 is merged.

Right - done.

**Comment by DDvO** [comment]
> Sorry for throwing this in so late, but I'm not sure `eq` is much better than `cmp`. What does "equality" mean, precisely? For example, `EVP_PKEY_cmp()` compares key parameters and the public key, does that make two EVP_PKEYs equal? One could contain the private half while the other doesn't, are they equal?
> 
> How about "match" instead of "eq"?


I agree that "match" typially has a broader meaning than "eq" (equality). Both should be instances of an equivalence relation (mathematically speaking).

Both "match" and "eq" are certainly better here than "cmp" (compare), which typically involves an ordering relation (such as "<" or ">="), not an equivalence relation.

Also the meaning of equality is generally not as narrow as one might naively expect, not only in mathematics/logics (where AFAICS any equivalence relation would do), but think also of user-defined equality operations that many OO programming languages offer.

In our concrete case here in my view "eq" would be broad enough to cover also the case that a private key is not present while the public keys are the same, and in particiular the difference cannot be much because if the public keys are equal the corresponding private keys (most likely) are equal, too.
Moreover, "eq" is shorter than "match" :wink:

**Comment by levitte** [comment]
I see you're not much acquainted with [lisp](https://stackoverflow.com/questions/547436/whats-the-difference-between-eq-eql-equal-and-equalp-in-common-lisp) :wink:

But yeahok, I can accept that argument

**Comment by t8m** [comment]
You should also rename the EVP_PKEY_cmp call from X509_PUBKEY_eq().

**Comment by DDvO** [comment]
> You should also rename the EVP_PKEY_cmp call from X509_PUBKEY_eq().

Ah, I thought I had already done this, but my `--amend` missed that  `x_pubkey.c` file.
Now it's really pushed.

**Comment by DDvO** [comment]
Merged after sufficient discussion :)

**Pull request closed without merging**
