### PR TITLE
x86[_64]cpuid.pl: fix potential bias of OPENSSL_ia{32,64}_{rdrand,rdseed}.

### PR DESCRIPTION
**Pull request by wmark**
Changes OPENSSL_ia32_{rdrand,rdseed} to accept a buffer to be filled with num QWORDs. Returns how many QWORDs have actually been changed, so a failure occurred if num < return value.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Ping @dot-asm. I think this one will need you to review before any progress can be made.

**Comment by mattcaswell** [comment]
@dot-asm?

**Comment by wmark** [comment]
Since then I've observed something more, to add to the above comment of mine: On some microcode versions with Intel C2758 RDRAND didn't return »randomness« more often than it did.

**Comment by mattcaswell** [comment]
Ping @dot-asm!

**Comment by mattcaswell** [comment]
@dot-asm considers the bias to be very small, therefore pushing this to post 1.1.0

**Comment by wmark** [comment]
I can rewrite this using C-intrinsics if you lack the manpower or time to review code written in Assembly.

**Comment by richsalz** [comment]
it would help, but the view still seems to be that it's not worth changing now.

**Comment by dot-asm** [comment]
> it would help

No, it wouldn't. Intrinsics are toolchain-specific and we don't want to track specific versions. Note that there is minimum that makes *no* assumption about toolchain version, i.e. it will work with *any*, old or new, buggy or not. The minimum covers SSSE3, AES-NI, SHAEXT and actually RDRAND. Things like AVX do depend on version though.

But couple of comments on the matter. "Broken" or not, correct course of action is to add new interfaces rather than modify old in completely incompatible manner. And if we do something, it better be size_t-neutral, for example with byte granularity. That's why there were OPENSSL_ia32_rd[rand|seed]_bytes recently added.

[Suggested 32-bit version doesn't follow calling convention by clobbering register that is supposed to be preserved. And we choose not to use red zone in 64-bit code, so that code can be re-used in arbitrary context.]

**Comment by wmark** [comment]
Thanks for the detailed feedback!

Closing this in favour of another attempt.

**Pull request closed without merging**
