### PR TITLE
Test more curves - 1.1.1

### PR DESCRIPTION
**Pull request by bernd-edlinger**
- Add tests with various curves in TLS1.3

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
About the background of this PR:
This PR removes just a few TODO lines in test/ssl-tests/14-curves.conf.in
```
- # TODO(TLS1.3): Can we get this to work for TLSv1.3?
- "MaxProtocol" => "TLSv1.2"
```
I had originally discovered that these tests work just fine with TLS1.2 AND TLS1.3
while working in #18130 (1.1.1 version of the RFC 8449 implementation)
but in master/3.0 I had to drop this change, since these version do not tolerate these
curves if TLS1.3 is negotiated.
I believe this is an error that the curves behave differently in master and 1.1.1,
I am also sure that 1.1.1 is more correct here, since TLS1.3 uses these curves
just for the key share, not to restrict the certificate, that is the job of the
signature algorithm extension.

**Comment by bernd-edlinger** [comment]
It is also very awkward how master/3.0 behaves, because if the server knows it's certificate curve,
it will mist likely add that curve to the -groups parameter, in order to make TLS1.2 accept that certificate group,
but at the same time TLS1.3 will fail when this group is negotiated.

**Comment by bernd-edlinger** [comment]
Thanks @paulidale for the approval, I agree that more test can never hurt, not even for 1.1.1

**Comment by bernd-edlinger** [comment]
Yes, it kind of relies on the CI to do tests with all combinations of no-tls1_2 and no-tls1_3

**Comment by t8m** [comment]
I am afraid we would have to explicitly approve this with OTC to be merged in 1.1.1. As this is not a bug fix in strict sense.

**Comment by bernd-edlinger** [comment]
Never mind, with this PR, I just wanted to point out that there is a significant difference
between in the handling of the curve parameter vs. tls1.3

**Pull request closed without merging**
