### PR TITLE
WIP: set upcall table with (swapped) malloc

### PR DESCRIPTION
**Pull request by richsalz**
This is WIP until (unless? if?) #8886 gets merged. I'll then rebase against master and take this out of WIP.

This PR makes the malloc/realloc/free upcalls work properly if the application called ```CRYPTO_set_mem_functions```

### CODE REVIEW

**Comment by richsalz** [comment]
Only the last commit (https://github.com/openssl/openssl/pull/9343/commits/7f0b86c6a4fe18f8550cb4a9f18263b723ac57cf) is new to this PR.

**Comment by richsalz** [comment]
took out of WIP.  I could not think of a short way to describe this.

**Comment by levitte** [comment]
> took out of WIP.

Uhmmm, no? 

Also, do check the Travis failure

**Comment by richsalz** [comment]
So doing this turns out that CRYPTO_get_mem_functions isn't in the providers.  Should it be? Is this become too much work for a corner-case?  On the other hand, not having providers work properly if an application has called ```CRYPTO_set_mem_functions``` -- especially since a provider could be quietly installed without the application knowing -- seems wrong.  Thoughts?

**Comment by richsalz** [comment]
left it in WIP until I get feedback on what to do about the problem i mentioned in https://github.com/openssl/openssl/pull/9343#issuecomment-510462751

**Comment by levitte** [comment]
I just looked at the change, and I strongly dislike it, it's horrible hackery.
Also, I don't what this has to do with #8886. If that one is merged, the providers are calling back into libcrypto and getting the benefit of `CRYPTO_set_mem_functions` gratis, no?

**Comment by richsalz** [comment]
oh h*ck you are right.  This is completely unnecessary.  closing.

**Pull request closed without merging**
