### PR TITLE
Update certificates in demos directories

### LINKED ISSUE #6412: In openssl/demos/smime/ directory,  cacert.pem and signer.pem has expired !
Dear Developers:
       In openssl/demos/smime/ directory,  cacert.pem and signer.pem has expired !

### PR DESCRIPTION
**Pull request by dcooper16**
This PR Fixes #6412 by updating cacert.pem and signer.pem in the openssl/demos/smime/ directory. It also updates all of the keys with longer key lengths.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by kroeckx** [comment]
In demos/certs/ is an mkcerts.sh, maybe we should have such a script in demos/smime too?

**Comment by dcooper16** [comment]
> In demos/certs/ is an mkcerts.sh, maybe we should have such a script in demos/smime too?

I don't think that's necessary, as mkcerts.sh was just created as an example of how to generate certificates.

I did just notice, however, that there are four PEM files in demos/cms that are exactly the same as the four PEM files in demos/smime. So, perhaps the new certificates and keys that I created should be copied to that directory as well.

All of the certificates in demos/bio are still valid, but the root expires in February 2024 and the intermediate certificate expires in June 2025, so perhaps they should be updated as well, before this issue is forgotten about.

**Comment by richsalz** [comment]
How about changing the PR to (a) remove both instances of the certs; and (b) put them in a new demo/certs directory?

**Comment by dcooper16** [comment]
I modified this PR to update all of the certificates in demos/smime, demos/cms, and demos/bio. The new certificates are all valid for 100 years. So this PR now fixes #6412, fixes the same issue in demos/cms, and avoids having a similar problem in demos/bio in a few years.

> How about changing the PR to (a) remove both instances of the certs; and (b) put them in a new demo/certs directory?

At the moment I have not made this change, as a demo/certs directory already exists - it is a directory intended to demonstrate how to create certificates using scripts.

I'm not against moving the certificates into a separate directory and then modifying all of the test programs to look in the new directory for the certificates. I'm not sure how to do it in a way that doesn't create confusion between the directory containing test certificates and the directory demonstrating how to create test certificates. At the moment, each directory in demos/ is self-contained, and there might be an advantage in leaving it that way.

**Comment by richsalz** [comment]
Thanks for your work on this.  100 years is more than enough and I'm willing to let our descendants handle that.

**Comment by paulidale** [comment]
Squashed and merged thanks.

**Pull request closed without merging**
