### PR TITLE
Add documentation for the SSL_export_keying_material() function

### PR DESCRIPTION
**Pull request by mattcaswell**
This is the 1.1.0 version of #3735.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
argh.  this changes the API.  Can we do that?  Can we do that for 1.1.1?  Argh.  Perhaps better to just break things for 1.1.1 and not do this for 1.1.0

**Comment by mattcaswell** [comment]
It doesn't change the API??? I just renamed some of the args so that their purpose was clearer.

**Comment by richsalz** [comment]
All those question marks... Sorry, you're right, false alarm.  Once you address my feedback in master, and do the same thing here, it's approved.

**Comment by mattcaswell** [comment]
Updated with changes from master

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
