### PR TITLE
crypto: Separate text and rodata section for armv8

### PR DESCRIPTION
**Pull request by Sankyou**
Separate data in `.text` section to `.rodata` section to support eXecute-Only-Memory(XOM) feature.

Fixes:#23911

### CODE REVIEW

**Comment by Sankyou** [comment]
@tom-cosgrove-arm @t8m

**Comment by t8m** [comment]
@Sankyou we will need a CLA signed to be able to accept your contribution.
https://www.openssl.org/policies/cla.html

**Comment by Sankyou** [comment]
------------------ Original ------------------
From: Tomáš Mráz ***@***.***&gt;
Date: Wed,Mar 27,2024 6:57 PM
To: openssl/openssl ***@***.***&gt;
Cc: Sankyou ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [openssl/openssl] crypto: Separate text and rodata section forarmv8 (PR #23984)





 
@Sankyou we will need a CLA signed to be able to accept your contribution.
 https://www.openssl.org/policies/cla.html

**Review by Sashan — COMMENTED** [review]
I'm just curious: why we use a `.pushsection ".rodata", "a"` in this pull request? How does it differ from using `.rodata` ... `.previous`. the google is not helpful much on `.pushsection`/`.popsection`. thanks.

**Pull request closed without merging**
