### PR TITLE
Properly protect access to the provider flag_activated field

### LINKED ISSUE #15005: Data race in the provider code
While working on PR #14991 (issue #14925) I spotted a potential data race in the provider code. The provider `flag_activated` field is sometimes protected by a lock and sometimes not. If multiple threads load/unload a provider it could end up getting the wrong value. I wrote a small test to demonstrate the issue:

````
==================
WARNING: ThreadSanitizer: data race (pid=205205)
  Read of size 1 at 0x7b3400000000 by main thread:
    #0 ossl_provider_available crypto/provider_core.c:874 (libcrypto.so.3+0x305c9d)
    #1 OSSL_PROVIDER_available crypto/provider.c:57 (libcrypto.so.3+0x302057)
    #2 thread_provider_load_unload test/threadstest.c:427 (threadstest+0x5c9b)
    #3 test_multi test/threadstest.c:512 (threadstest+0x6086)
    #4 run_tests test/testutil/driver.c:370 (threadstest+0xae2c)
    #5 main test/testutil/main.c:30 (threadstest+0xb9aa)

  Previous write of size 1 at 0x7b3400000000 by thread T2 (mutexes: write M54):
    #0 provider_activate crypto/provider_core.c:713 (libcrypto.so.3+0x305600)
    #1 ossl_provider_activate crypto/provider_core.c:727 (libcrypto.so.3+0x3056a3)
    #2 OSSL_PROVIDER_try_load crypto/provider.c:26 (libcrypto.so.3+0x301f20)
    #3 OSSL_PROVIDER_load crypto/provider.c:38 (libcrypto.so.3+0x301f93)
    #4 thread_provider_load_unload test/threadstest.c:424 (threadstest+0x5c52)
    #5 thread_run test/threadstest.c:77 (threadstest+0x4359)
    #6 <null> <null> (libtsan.so.0+0x2d1af)

  Location is heap block of size 208 at 0x7b3400000000 allocated by main thread:
    #0 malloc <null> (libtsan.so.0+0x30343)
    #1 CRYPTO_malloc crypto/mem.c:184 (libcrypto.so.3+0x2f28f8)
    #2 CRYPTO_zalloc crypto/mem.c:191 (libcrypto.so.3+0x2f2944)
    #3 provider_new crypto/provider_core.c:263 (libcrypto.so.3+0x303b02)
    #4 provider_store_new crypto/provider_core.c:170 (libcrypto.so.3+0x303647)
    #5 ossl_lib_ctx_generic_new crypto/context.c:258 (libcrypto.so.3+0x2ea2ee)
    #6 ossl_crypto_alloc_ex_data_intern crypto/ex_data.c:432 (libcrypto.so.3+0x2efe88)
    #7 ossl_lib_ctx_get_data crypto/context.c:362 (libcrypto.so.3+0x2ea8b1)
    #8 get_provider_store crypto/provider_core.c:200 (libcrypto.so.3+0x3037c2)
    #9 ossl_provider_disable_fallback_loading crypto/provider_core.c:211 (libcrypto.so.3+0x30383f)
    #10 OSSL_PROVIDER_load crypto/provider.c:37 (libcrypto.so.3+0x301f77)
    #11 test_multi test/threadstest.c:463 (threadstest+0x5e18)
    #12 run_tests test/testutil/driver.c:370 (threadstest+0xae2c)
    #13 main test/testutil/main.c:30 (threadstest+0xb9aa)

  Mutex M54 (0x7b1000000bc0) created at:
    #0 pthread_rwlock_init <null> (libtsan.so.0+0x3699f)
    #1 CRYPTO_THREAD_lock_new crypto/threads_pthread.c:41 (libcrypto.so.3+0x308b6b)
    #2 provider_new crypto/provider_core.c:270 (libcrypto.so.3+0x303b75)
    #3 provider_store_new crypto/provider_core.c:170 (libcrypto.so.3+0x303647)
    #4 ossl_lib_ctx_generic_new crypto/context.c:258 (libcrypto.so.3+0x2ea2ee)
    #5 ossl_crypto_alloc_ex_data_intern crypto/ex_data.c:432 (libcrypto.so.3+0x2efe88)
    #6 ossl_lib_ctx_get_data crypto/context.c:362 (libcrypto.so.3+0x2ea8b1)
    #7 get_provider_store crypto/provider_core.c:200 (libcrypto.so.3+0x3037c2)
    #8 ossl_provider_disable_fallback_loading crypto/provider_core.c:211 (libcrypto.so.3+0x30383f)
    #9 OSSL_PROVIDER_load crypto/provider.c:37 (libcrypto.so.3+0x301f77)
    #10 test_multi test/threadstest.c:463 (threadstest+0x5e18)
    #11 run_tests test/testutil/driver.c:370 (threadstest+0xae2c)
    #12 main test/testutil/main.c:30 (threadstest+0xb9aa)

  Thread T2 (tid=205208, finished) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x5ea99)
    #1 run_thread test/threadstest.c:83 (threadstest+0x43cc)
    #2 test_multi test/threadstest.c:509 (threadstest+0x6056)
    #3 run_tests test/testutil/driver.c:370 (threadstest+0xae2c)
    #4 main test/testutil/main.c:30 (threadstest+0xb9aa)

SUMMARY: ThreadSanitizer: data race crypto/provider_core.c:874 in ossl_provider_available
==================
    ok 1 - iteration 6
ok 1 - test_multi
ThreadSanitizer: reported 1 warnings
````

### PR DESCRIPTION
**Pull request by mattcaswell**
This flag was not always locked when it should be

Fixes #15005

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Fixup pushed to address CI failures. @paulidale - please can you reconfirm?

**Review by paulidale — APPROVED** [review]
Still looks good

**Comment by mspncp** [comment]
This pull request is ready to merge

**Comment by mattcaswell** [comment]
Pushed. I tweaked the commit message so that it was in English.

**Comment by mattcaswell** [comment]
> I tweaked the commit message so that it was in English.

Sorry this comment was actually intended for #15033

**Pull request closed without merging**
