### PR TITLE
apps/speed.c: add non-evp sha224 and sha384

### PR DESCRIPTION
**Pull request by mpeylo**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by dot-asm** [comment]
I'd say no. The sha224 and sha384 results are bound to be and are exactly same as sha256 and sha512, so there is really no point. If one says that there is educational value in actually seeing that the results are the same, one can do that with -evp sha224 vs. -evp sha256 or -evp sha384 vs. -evp sha512.

As for skipping everything non-evp. Generally speaking, yes, it makes sense. But looking at it more specifically it has a value of evaluating efficiency of EVP layer itself. And it's becoming even more meaningful with introduction of "reptoline". One can of course argue that it's not end user's business to compare evp and raw interfaces, but it's at least our busyness and question is if it has to be kept private.

**Comment by mpeylo** [comment]
No hard feelings for me if it'd be rejected, I basically only handed it in as I anyway had done the rather trivial code addition for my own education.

From a user perspective: I was wondering why evp isn't the default, and native the option. I assumed historic reasons.

**Comment by romen** [comment]
I am more familiar with the asymmetric part of libcrypto than with message digests, but I would definitely make a point that, for applications developers and users, using `speed` in its current state can actually even be misleading: applications should always go through the EVP API, so making performance evaluations based on the benchmarks of the raw algorithm underneath, without accounting for the rest of operations performed at the EVP level (which in most cases even application developers willing to use the raw crypto implementations should also implement on their own) can actually lead to wrong assumptions. 

From this perspective I would rather prefer, for a future release, to have the public `speed` app always going through the high level API and strip out the raw crypto benchmarks to a private test utility.

**Comment by t-j-h** [comment]
I agree with the logic and the conclusion - this is something we should discuss for the next major release.

**Comment by romen** [comment]
> this is something we should discuss for the next major release

@t-j-h I opened #7053 to keep track of that!

**Comment by t8m** [comment]
This does not make much sense anymore with the move to providers and with the related deprecations. Closing.

**Pull request closed without merging**
