### PR TITLE
Add SEED ciphers to default provider

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
The speed at which these algos are now added, I feel tempted to utter a loud "yeeeee-haw!" :laughing:

**Comment by slontis** [comment]
> The speed at which these algos are now added, I feel tempted to utter a loud "yeeeee-haw!"

Its only because I did the difficult ones first :)

**Comment by levitte** [comment]
> Its only because I did the difficult ones first :)

Plus all the ground work...

**Comment by slontis** [comment]
Thanks.... Merged to master.

**Pull request closed without merging**
