### PR TITLE
Allow null in  X509_CRL_METHOD_free and fix doc

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
X509_CRL_METHOD is not an ASN.1 construct .
debian code search don't show any real use case ...

### CODE REVIEW

**Comment by richsalz** [comment]
+1
and backport

**Comment by FdaSilvaYY** [comment]
@rsalz: it seemes that you plus'one this PR, without putting a review label.
PR rebased over last master.

**Comment by richsalz** [comment]
thanks, added label.  we're still sorting out labels vs the "approved review" thing.

**Comment by t-j-h** [comment]
+1

**Comment by richsalz** [comment]
not relevant for 1.0.2, so 7cb1ece in master and 6fa4d63 in 1.1.0

**Pull request closed without merging**
