### PR TITLE
VMS: implement rand_pool_add_{nonce,additional}_data

### PR DESCRIPTION
**Pull request by levitte**
This is an amendment to #5920.  Only the last commit belongs to this PR.

@mspncp, feel free to cherry pick when I'm done

### CODE REVIEW

**Comment by mspncp** [comment]
cherry-picked to #5920. Thanks for your assistance!

**Comment by levitte** [comment]
I didn't say that I was done...
well, that means you'll get the pleasure of correcting faults with VMS code, if there are any 😉

**Comment by mspncp** [comment]
> I didn't say that I was done...

Oh, I'm sorry! I saw your pull request first and only afterwards your message https://github.com/openssl/openssl/pull/5920#issuecomment-380122671, which I then interpreted as a "Go ahead, I'm done".

Anyway, nothing happened yet: Since your branch was ahead of mine, I actually did a fast-forward merge, not a cherry-pick (maybe git would have noticed it anyway). So your commits are still valid, currently you could even fast-forward to the tip of my branch. 

> well, that means you'll get the pleasure of correcting faults with VMS code, if there are any 😉

Fixing the errors is probably the minor problem compared to obtaining the errors. Or is there - apart from you - any VMS build server which I could check?

**Comment by levitte** [comment]
Ok, I just checked, and I consider this done.  All relevant tests went through fine.

**Comment by mspncp** [comment]
Integrated into #5920. Thanks once again. Apropos: would you mind if I squash #5920 into a single commit at the end?

**Comment by levitte** [comment]
Please go ahead, I was going to suggest that anyway 🙄

**Pull request closed without merging**
