### PR TITLE
Fix syntax of dependabot.yml

### PR DESCRIPTION
**Pull request by kroeckx**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t-j-h** [comment]
Is this just a whitespace change?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by kroeckx** [comment]
> Is this just a whitespace change?

Yes.

**Review by t-j-h — APPROVED** [review]

**Review by shahsb — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
Merged to the master branch. Thank you.

**Pull request closed without merging**
