### PR TITLE
enhancement(md6.c): Added a new hash type called MD6

### PR DESCRIPTION
**Pull request by pneb**
# Changes

- This commit adds a new hash type called MD6 to the md6.c file. This new hash type enhances the capabilities of the file and improves its overall functionality.

### CODE REVIEW

**Comment by pneb** [comment]
> We add only algorithms that are standardized in some standard such as IANA RFCs, international or country-specific standards.
> 
> Second problem is that the implementation as is, is not really useful as it needs to be added to a provider to be usable by applications.

It might be good to include the MD6 hash algorithm in OpenSSL because it is a valid way to create a hash and having more options available to us can be helpful. Even though it is not the most popular algorithm right now, it could be useful in the future.

**Comment by t8m** [comment]
**OTC: We are not aware of any practical usage of this algorithm and it is not standardized. This will not be merged.**

**Comment by pneb** [comment]
That's an unfortunate... Well thank you for assisting me still!

**Comment by romen** [comment]
@pneb, one option, if you are interested, to work with new/alternative algorithms that are not supported upstream in OpenSSL, is to develop a dedicated 3rd party provider, that can then be deployed and loaded by interested users to seamlessly make the functionality available to OpenSSL-based applications.

If you are interested in this path, once your project reaches a sufficient level of maturity, you could also get in contact with @levitte, who maintains <https://github.com/provider-corner>, which lists other 3rd-party providers.
This could help with visibility, to make more users aware of your provider if they need MD6 support.

**Comment by levitte** [comment]
I would recommend expanding on this implementation to allow for different hash size, rounds and modes, if for nothing else, then to be able to test against available test vectors.  As far as I have found within 10 minutes, that seems to be the three Sample MD6 calculations found in, for example, http://www.jayantkrish.com/papers/md6_report.pdf

Those three examples could be summarized like this (all numbers and string in hex):

```
### First example
# "abc"
Input = 616263
# 256 bits in hex notation
Size = 100
Rounds = 5
# 64 in hex notation
Mode = 40
Output = 8854c14dc284f840ed71ad7ba542855ce189633e48c797a55121a746be48cec8

### Third example
# Input string is 800 characters, repeating 11223344556677 as much as possible
Input = 11223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677
# 256 bits in hex notation
Size = 100
## Rounds defaults to decimal 104 (hex 68), for size == decimal 256 (hex 100)
Mode = 0
Output = 4e78ab5ec8926a3db0dcfa09ed48de6c33a7399e70f01ebfc02abb52767594e2
```

If you also want to support keyed hashes, there's one more:

```
### Second example
# Input string is 600 characters, repeating 11223344556677 as much as possible
Input = 112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455667711223344556677112233445566771122334455
# "abcde12345"
Key = 61626364653132333435
# 224 bits in hex notation
Size = e0
Rounds = 5
# 64 in hex notation
Mode = 40
Output = 894cf0598ad3288ed4bb5ac5df23eba0ac388a11b7ed2e3dd5ec5131
```

**Pull request closed without merging**
