### PR TITLE
Fix typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
About `re-use` → `reuse`: `reuse` is found in all dictionaries, and more importantly, it already occurs > 100 times in the repository, so this is more a question of consistency than correctness.

##### Checklist

- [X] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Comment by nhorman** [comment]
personall, I wouldn't worry about the re-use->reuse conversion either way.  the hyphenated variant isn't the correct spelling according to webster, but its pretty common.  Either way works for me

**Review by t8m — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
Merriam-Webster does like [reuse](https://www.merriam-webster.com/dictionary/reuse).

From [Reuse or Re-Use – Which Spelling Is Correct](https://www.grammarcheck.me/reuse-or-re-use/)?
> According to the Chicago style and AP style guides, the correct spelling is reuse. No hyphen is needed when using the prefix “-re”.

The Google Ngram Viewer also shows reuse is usually preferred over re-use:
https://books.google.com/ngrams/graph?content=re-use%2Creuse&year_start=1900&year_end=2019&corpus=en-2019

**Review by hlandau — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
repo is frozen, unable to merge.

**Comment by t8m** [comment]
Repo unfrozen.

Merged to master branch. Thank you for your contribution.

**Pull request closed without merging**
