### PR TITLE
Document SSL_CONF_CTX_finish function

### LINKED ISSUE #22084: `SSL_CONF_CTX_finish` used to be documented (sort of), but now isn't
The `SSL_CONF_CTX_finish` function is undocumented. `SSL_CONF_cmd`, which *is* documented, won't work correctly without a call to `SSL_CONF_CTX_finish`, so it really ought to be documented.

`SSL_CONF_CTX_finish` *used to* be documented, under the name `SSL_CONF_finish`, but the documentation was removed in 1722496fcaa8f2760dd38f7a77ba1256e51e8b7d as part of a cleanup of documentation of nonexistent functions. The author of that commit must not have noticed that the function *does* exist, just under a different name.

### PR DESCRIPTION
**Pull request by heygauri**
Add documentation for the function `SSL_CONF_CTX_finish`.

CLA: trivial

Fixes #22084

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I think this is beyond trivial.

**Comment by heygauri** [comment]
> I think this is beyond trivial.

Hi @paulidale Do you want me to remove the CLA:trivial tag and push the changes?

**Comment by paulidale** [comment]
You'll need to remove it from the commit message: `git commit --amend` then `git push -f`

**Comment by heygauri** [comment]
Closing this pull request to remove "needs CLA" tag.

**Comment by paulidale** [comment]
Please reopen if you've removed the offending line the commit message.

**Comment by heygauri** [comment]
> Please reopen if you've removed the offending line the commit message.

Hi @paulidale I closed this pull request as per the instuctions from @TamaraDale that I have been added in the contributors database so I now need to delete and reopen all my current pull requests to remove the "need of CLA "tag.

About the offending line "The commit message" in my commit message, I will take care of it.

**Comment by heygauri** [comment]
I am opening the pull request again with the new changes.

**Comment by heygauri** [comment]
I need help. I am unable to reopen this PR.

**Comment by heygauri** [comment]
Reopen PR

**Comment by heygauri** [comment]
I am closing this PR. I have created a new one because of the confusions. Apologies.

https://github.com/openssl/openssl/pull/22128

**Pull request closed without merging**
