### PR TITLE
Minor grammar fix in openssl-ca

### PR DESCRIPTION
**Pull request by snorfalorpagus**
This error was introduced by a previous find and replace.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

**Comment by t8m** [comment]
@paulidale are you OK with CLA: trivial?

**Comment by paulidale** [comment]
Yes, CLA: trivial is okay.

**Comment by t8m** [comment]
Merged to master branch. Thank you for your contribution.

**Pull request closed without merging**
