### PR TITLE
Backport dynamic rand_pool buffering to 1.1.1

### PR DESCRIPTION
**Pull request by paulidale**
Refer #9428 

This only includes the dynamic pool size changes, the earlier splitting pools into normal memory changes are not part of this.

### CODE REVIEW

**Comment by kroeckx** [comment]
Does this fix some bug?

**Comment by richsalz** [comment]
It helps (there's another part) alleviate massive over-consumption of secure heap space (16K vs 16 bytes, more or less)

**Comment by paulidale** [comment]
@richsalz as far as I'm aware, the problem addressed by #9423 didn't make it to 1.1.1.  In 1.1.1, the relevant pools are transient, so they are less of a problem.

@kroeckx is excessive secure memory use considered a bug?  The memory allocations for the various entropy pools default to 12288 bytes (which are rounded up to 16384 bytes by the secure memory allocator).  With this change, they'll be 64 bytes.

It's certainly a regression from 1.1.0.  The case that discovered this had 8k threads each of which having at least one DRBG allocated.  That's a lot of memory.

**Comment by kroeckx** [comment]
Can you make the commit message more clear about that, instead of
just saying "backporting something", from which it's very unclear
what it does.

**Comment by paulidale** [comment]
Fair comment.  I've added explanatory text to the commit message.

**Comment by mspncp** [comment]
IMHO #9428 can and should be backported as it is. Bernd's (non-)secure memory changes are also being backported, the pull request is still waiting for reviews.

- #9424 Allocate DRBG additional data pool from non-secure memory [1.1.1]

For the moment, you could base your pull request on his.

**Comment by paulidale** [comment]
With @bernd-edlinger's changes, I'd expect #9428 to cherrypick directly and hence no need for this PR.

**Comment by paulidale** [comment]
#9428  cherrp-picked cleanly (just errors regenerated), so closing this one.

**Pull request closed without merging**
