### PR TITLE
Fix links in `cms_add0_cert.pod` and improve `find-doc-nits` error msg

### PR DESCRIPTION
**Pull request by DDvO**
It turns out that my recently merged changes to  `cms_add0_cert.pod` made `find-doc-nits` unhappy.
Sorry that this went unnoticed and now causes unrelated CI failures in newly pushed PRs.
For this reason, I propose making the fix given here urgent.

As the error messages by `make doc-nits`:
```
/usr/bin/perl ./util/find-doc-nits -c -n -l -e
doc/man3/CMS_add0_cert.pod:1: Section missing in CMS_sign_ex()
doc/man3/CMS_add0_cert.pod:1: Section missing in CMS_sign()
doc/man3/CMS_add0_cert.pod:1: Section missing in CMS_verify()
doc/man3/CMS_add0_cert.pod:1: Section missing in CMS_verify()
```
are unclear and even misleading, such that it took me a while to understand what went wrong,
I propose the improvement of  `find-doc-nits`  given in the 2nd commit.
The error given will then read, e.g.,:
```
doc/man3/CMS_add0_cert.pod:1: Missing man section number (likely, 3) in L<CMS_verify()>
```

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Review by hlandau — APPROVED** [review]
Agree urgent

**Comment by DDvO** [comment]
Merged to master - thanks @mattcaswell and @hlandau for the swift approvals.

I just realized that the same happend also for 3.0 and 3.1 by the backport PR #20275.
Can you please re-approve for these?

**Comment by DDvO** [comment]
Minor CI failures unfortunately are easily overlooked these days
due to the frequent CI false positives on certain Windows builds.

**Review by mattcaswell — APPROVED** [review]
Approved for 3.1/3.0 too

**Review by hlandau — APPROVED** [review]
Approved as urgent for 3.0/3.1 as well

**Comment by DDvO** [comment]
Cherry-picked to 3.0 and 3.1. Thanks.

**Comment by paulidale** [comment]
If we cherry pick from here, it should only be commit c34be62ae8eb3ca1c05e1cf30e11cd44443b5abf

**Comment by DDvO** [comment]
> For some reason the earlier pick didn't stick.

Strange. Thanks for taking care of re-applying the doc fix in #20398.
So we can close this earlier PR again.

**Pull request closed without merging**
