### PR TITLE
PKCS7 certificates list is an implicit SET OF not SEQU…

### LINKED ISSUE #13142: Incorrect DER encoding in PKCS7 signed data objects
TL;DR as of Tuesday Oct 13 Microsoft's wintrust.dll is being very strict in its parsing of DER encoded PKCS7 data and is rejecting signatures made by openssl.

The root cause is that, in the DER encoding, the SET OF certificates in openssl generated PKCS7 signed-data isn't correctly sorted.

RFC2315 §9.1 says:

>    SignedData ::= SEQUENCE {
> [...]
>         [0] IMPLICIT ExtendedCertificatesAndCertificates
>           OPTIONAL,
 
where (§6.6)

>    ExtendedCertificatesAndCertificates ::=
>      SET OF ExtendedCertificateOrCertificate
 
ITU X.690  §11.6 states:

> 11.6 Set-of components
>  The encodings of the component values of a set-of value shall appear in ascending order, the encodings being compared as octet strings with the shorter components being padded at their trailing end with 0-octets. 

Yet the attached test program generates the following asn.1
```
    0:d=0  hl=4 l=1703 cons: SEQUENCE          
    4:d=1  hl=2 l=   9 prim:  OBJECT            :pkcs7-signedData
[...]     
   45:d=3  hl=4 l=1334 cons:    cont [ 0 ]        
   49:d=4  hl=4 l= 660 cons:     SEQUENCE          
   53:d=5  hl=4 l= 380 cons:      SEQUENCE          
   57:d=6  hl=2 l=   1 prim:       INTEGER           :00
[...]
   81:d=9  hl=2 l=   3 prim:          OBJECT            :commonName
   86:d=9  hl=2 l=   5 prim:          UTF8STRING        :Zebra
[...]
  713:d=4  hl=4 l= 666 cons:     SEQUENCE          
  717:d=5  hl=4 l= 386 cons:      SEQUENCE          
  721:d=6  hl=2 l=   1 prim:       INTEGER           :00
[...]
  745:d=9  hl=2 l=   3 prim:          OBJECT            :commonName
  750:d=9  hl=2 l=   8 prim:          UTF8STRING        :Aardvark
```

which violates the X.690 §11.6 requirement.

[test.c.txt](https://github.com/openssl/openssl/files/5384228/test.c.txt)
[out.txt](https://github.com/openssl/openssl/files/5384229/out.txt)

### PR DESCRIPTION
**Pull request by fishsoupisgood**
RFC2315 states that the list of certificates in PKCS7 signed data objects is an implicit SET OF not SEQUENCE OF as is currently in the codebase. Because of this signatures generated by openssl fail to validate on Microsoft's new stricter DER parser in wintrust.dll.

### CODE REVIEW

**Comment by t8m** [comment]
This would be elligible for CLA: trivial. If you agree please amend the commit message so that it contains CLA: trivial on a separate line.

**Review by mattcaswell — APPROVED** [review]
LGTM. It looks like this should be backported to 1.1.1. I agree this is trivial.

**Comment by t8m** [comment]
Apparently we have a test that expects the incorrect output. That needs to be fixed. Does this change have potential of breaking some interoperability if some other software expects the other output?

**Comment by fishsoupisgood** [comment]
Re breaking software expecting the other output, the only visible difference visible would be that certificates weren't written in the order they were added to the pkcs7 object. The only thing one could imagine is that someone writes an application to read pkcs7 written by openssl, that is expecting the first certificate to be the signing certificate. Such an application written in openssl would be looking at the first cert in p7->d.sign->cert, rather than using PKCS7_get0_signers or PKCS7_cert_from_signer_info.

**Comment by richsalz** [comment]
The order of certificates written to a PKCS7 file is now likely to be different.  That should be noted in a clear spot, including a HISTORY section of the manpage.

**Comment by slontis** [comment]
@levitte Although the change looks small, won't this will create issues for existing data.
Should it now need to try both forms when decoding?

**Comment by bukka** [comment]
@fishsoupisgood I'm not really sure what difference this PR makes in terms of encoding and how it can fix your problem. 
Have you actually tested if this fixes your problem with the wintrust.dll parser?

The reason is that this is implicitly tagged sequence so the type is not part of encoding. I actually took a time to generate signed data so you can compare the results below:

Before the patch: https://bit.ly/39d95km
After the patch: https://bit.ly/2JcRHRV

Basically you won't see any difference because the type is not encoded (just the tag is encoded) so it doesn't really matter if it is specified as a sequence or set. The only difference is that the certs will be in correct order from the OpenSSL point of view. I think this is done on purpose to keep order of certificates when re-encoding which is done in the similar way in `PKCS7_SIGNER_INFO`: https://github.com/openssl/openssl/blob/2d4022603a0f09d802bf5cc5f04a08b6880bbfa2/crypto/pkcs7/pk7_asn1.c#L143-L148

Hence I don't think this is a bug and there's anything to fix.

**Comment by fishsoupisgood** [comment]
The issue is very real, perhaps I can suggest you look at the example code which reproduces the issue in the linked bug report?

https://github.com/openssl/openssl/issues/13142

**Comment by bukka** [comment]
Ah ok I haven't seen the linked bug. It validates the order so this makes sense. If that's the case, it might need to also change the `auth_attr` (authenticatedAttributes) that can be set using `PKCS7_set_signed_attributes`. I would guess that if their order is not alphabetical, it will fail as well, right?

I think I can at least answer the question that @slontis asked. As it's implicitly tagged and both SET OF and SEQUENCE OF are consctructed, then there shouldn't be any difference for decoding. At least that's how I understand it - haven't tried it. :)

**Comment by levitte** [comment]
The commit message should be reformatted like this:

```
PKCS7 certificates list is an implicit SET OF not SEQUENCE OF

Fixes #13142

CLA: trivial
```

Github isn't very good at picking up hints from the commit subject line, which is why the links between issue and PR aren't visible in a github supported way.

**Comment by t8m** [comment]
Please rebase and reformat the commit message as @levitte stated above.

**Comment by mspncp** [comment]
> Please rebase and reformat the commit message as @levitte stated above.

Since it's a trivial reformatting of the commit message, I edited it as requested and rebased the pull request branch.

**Review by mspncp — APPROVED** [review]

**Comment by t8m** [comment]
The CI failure is relevant!

**Pull request closed without merging**
