### PR TITLE
GetProcAddress() of W version of functions if UNICODE

### PR DESCRIPTION
**Pull request by Posolsvetla**
for: Process32FirstW, Process32NextW, Module32FirstW, Module32NextW

### CODE REVIEW

**Comment by richsalz** [comment]
This seems like a nice-to-have, maybe, but not strictly required.  i doubt we will do it.

**Comment by levitte** [comment]
Err, you did notice this is a PR, not an issue, right @richsalz?

**Comment by richsalz** [comment]
Yes I did.  For "do it" I should have written "I doubt we will merge it."  If it's an *important* bugfix to 1.0.2, please re-open this PR.

**Comment by dot-asm** [comment]
It's actually totally valid concern. Because of this mismatch some calls will actually fail. It won't crash, it won't access uninitialized data, but couple of loops won't execute.

**Comment by kroeckx** [comment]
Is there a reason this isn't done for all the strings there?

**Comment by kroeckx** [comment]
I actually have no idea what this patch changes. Doesn't the macro just turn it into the same string? Or does it get an L in front of it somehow? Should we be using something like _TEXT() instead?

**Comment by kroeckx** [comment]
Oh, you want to make use of the `#define` in the windows header to turn it into the A or W version.

**Comment by Posolsvetla** [comment]
Hi, sorry for the late comment.
I should have described the details/reasons for this patch at the beginning...
The thing is, that the non-unicode versions of WinAPI functions are called with the unicode versions of parameters, resulting in garbage in those parameters. It's because the parameter type is macro-ed to the unicode version, while the function name for `GetProcAddress()` isn't.
This patch fixes that.
Anyway, this probably causes no real problems, I just found it by coincidence.

**Comment by Posolsvetla** [comment]
Closing as obsolete, 1.0.2 is reaching EOL at 2019-12-31

**Pull request closed without merging**
