### PR TITLE
Make SSL_alloc_buffers() and SSL_free_buffers() work again

### PR DESCRIPTION
**Pull request by mattcaswell**
The recent record layer refactor left SSL_alloc_buffers() and SSL_free_buffers() as no-ops. We make them work again.

While we are making changes to OSSL_RECORD_METHOD functions, we also remove a couple that were no-ops and never called.

### CODE REVIEW

**Review by hlandau — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by slontis** [comment]
Does this need a test?

**Review by t8m — APPROVED** [review]

**Comment by slontis** [comment]
> 

If you add new code to fix something and the tests don't already fail, then there was no test :)

**Review by hlandau — APPROVED** [review]

**Comment by mattcaswell** [comment]
The CI failure appears unrelated to this PR. Setting the "ready-to-merge" label.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
