### PR TITLE
apps: add a -store-loaders option to list.

### LINKED ISSUE #15307: `openssl list` option for OSSL_OP_STORE operations or URI schemes
The `openssl list` allows me to list `-encoders` and `-decoders`, but I didn't find a way to list STORE operations, i.e. to list what URI schemes are supported. Such as:

```
$openssl list -stores
Provided STOREs:
  file @ default
```

I know there is only a single store in the default provider, but external providers may implement additional stores, so a user may want to know what URI schemes are available, or to check whether a specific scheme is available.

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #15307

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by romen** [comment]
Uhm, closing and reopening, as it seems somethign went very wrong with the CI runner

**Review by levitte — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Closing and reopening to kick CIs.

**Comment by t8m** [comment]
Needs a rebase to fix conflict.

**Comment by paulidale** [comment]
Rebased.  I don't think a re-review is required.

**Pull request closed without merging**
