### PR TITLE
Get Windows amd64 build working from a bare cmd shell

### PR DESCRIPTION
**Pull request by gigadude**
I needed to convert Windows `\` to `/` to get the amd64 build working in my environment.

### CODE REVIEW

**Comment by richsalz** [comment]
Is this still an issue?  Doesn't it break everyone else?

**Comment by levitte** [comment]
I defer to @dot-asm on this one

**Comment by gigadude** [comment]
AFAIK still an issue, I don't think it breaks anyone unless paths are supposed to support escape chars on other platforms.

**Comment by dot-asm** [comment]
Well, it kind of depends on definition of "issue". Basically we kind of require that a "matching" perl is used at every occasion. "Matching" refers to chosen make utility and command interpreter it relies on rather than OS. For example if you use Visual Studio nmake, then you should use ActivePerl. If you compile under MSYS, you should use MSYS perl, under Cygwin, use Cygwin perl, etc. Everything outside this should be and is kind of somebody else's problem. And it's not exactly about what is possible or might work, but about combinations that can be meaningfully supported. In practical terms it means that we shouldn't aim for all possible combinations, but rather have the option to forward problem to perl vendor in case it's deemed to be problem with perl.

**Comment by mattcaswell** [comment]
So this sounds like an environmental problem from @dot-asm's write up above, i.e. the use of non-matching perl versions.
@gigadude, are you able to confirm your build steps and environment set up?

**Comment by mattcaswell** [comment]
No response from @gigadue. Assuming this is an environmental issue. Closing this. Please reopen if this is still a problem.

**Pull request closed without merging**
