### PR TITLE
Move params C files into their own directory.

### PR DESCRIPTION
**Pull request by paulidale**
There are three param*.c files, move them into a common subdirectory.

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
I have to ask, what are the implications of this move?

Historically, *anything* that lived in a `crypto/` sub-directory was disablable (with a few exceptions that are hard-coded in `Configure`).  The files in `crypto/` were not.  Since I've been around for quite a long time, that's still on my mind and obviously affects my choices.

So my thinking was that "core" things (at least new "core" things) would end up in `crypto/`.

Now, I don't mind this move...  the params API is and has always been optional, at least from a user perspective.  But I think we need to get to some kind of concensus what belongs where...

**Comment by paulidale** [comment]
I suspect the _optional_ part of the subdirectories was lost quite some time ago.  There are several algorithms that cannot be disabled (even though it would be nice to be able to do so).  To be honest, I hadn't realised that subdirectories were meant to be optional.

For me, this is a declutter.  The params source files were at the top level.  All good when params was one file, but now it's three.  Likewise, I started properties in a subdirectory because there were multiple files.

**Comment by richsalz** [comment]
I think having a bunch of files in the same place with a bunch of subdirectories is "messy" (to use a technical term).  I created a PR to do this, and the team didn't want an ad-hoc (sic) approach, but preferred to have something designed so I created #9331.  

I suggest the team be consistent and not accept this PR until the discussion that the team earlier wanted to do happens.

I completely share Pauli's point about "crypto no longer implies not-optional"  I never thought of it as such.  I thought of it as a dumping ground.  I mean, LPvms_dir is kinda optional for most :)

**Comment by paulidale** [comment]
Is it safe to assume that this PR is dead in the water?

**Comment by paulidale** [comment]
Closing, a more general reorganisation is preferred.

**Pull request closed without merging**
