### PR TITLE
test/drbgtest: improve the reseed after fork test [1.1.1]

### PR DESCRIPTION
**Pull request by mspncp**
Issue #12377 demonstrated that it is not sufficient to verify that
after a fork a reseeding is triggered in the child. This commit
enhances the test by collecting the output of the public and private
drbg for the parent and all children and checking for duplicates.
In case of duplicates, it displays a sorted output.

    *ERROR*: DUPLICATE RANDOM OUTPUT:
        output: bb836def, pid: 30831 (parent, public)
        output: bb836def, pid: 30837 (child 1, public)
        output: bb836def, pid: 30838 (child 2, public)
        output: bb836def, pid: 30839 (child 3, public)
        output: bb836def, pid: 30840 (child 4, public)
        output: bb836def, pid: 30841 (child 5, public)
        output: 02bf7135, pid: 30831 (parent, private)
        output: 02bf7135, pid: 30837 (child 1, private)
        output: 02bf7135, pid: 30838 (child 2, private)
        output: 02bf7135, pid: 30839 (child 3, private)
        output: 02bf7135, pid: 30840 (child 4, private)
        output: 02bf7135, pid: 30841 (child 5, private)

Backport of #12407

**Note: this test is currently expected to succeed because issue #12377 does not apply to the 1.1.1 stable branch.**

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
I converted this pull request to draft mode to indicate that the backport will only be finished after #12407 has been approved. Currently, it is mainly intended to be used for testing by @p-steuer.

**Comment by paulidale** [comment]
Unfortunately, it isn't possible for the parent to reseed as well -- that would be ideal.

**Comment by mspncp** [comment]
It would be nice-to-have. But in theory, it should be already sufficient if all children do it.

**Comment by mspncp** [comment]
Backporting DRBG tests has become significantly more complicated after the replumbing, so I decided that it is not worth to backport #12407 to 1.1.1.

**Pull request closed without merging**
