### PR TITLE
Modified genrsa to generate RSA private key with numbers p and q

### PR DESCRIPTION
**Pull request by sganis**
Hi, I added a feature to genrsa option to be able to generate a private RSA key with a given pair of prime numbers, p and q. This was part of my experiments to audit the strength of RSA keys. Regards, S.

### CODE REVIEW

**Comment by Adamzynoni** [comment]
cool.

**Comment by BenBE** [comment]
I recently needed something similar[1] myself, but found it much more easy to simply hack some script to write some (proper) ASN.1 containing the key I wanted. If I had this patch it might have saved me some hours of work, but this change is rarely useful outside of (academic) research or your ivory tower sandbox. Much more this provides a powerful canon to everyone to not only blow their feet off, while eradicating themselves at the same time.

Given how rarely the above feature is useful I do not see a proper reason to break the API/ABI of the library.

[1] https://github.com/BenBE/kompromat/blob/master/scripts/convert-key.php
And yes: My script is a hack which needs some post-processing under certain conditions.

**Comment by richsalz** [comment]
This is a pretty large patch for a pretty limited-use feature.  See BenBE's script.  (API changes are not an issue, since this would be for 1.1)  But we're not going to take this.

**Comment by sganis** [comment]
Fine, I will have to maintain my own implementation then, thanks. S.

**Comment by sganis** [comment]
I needed that feature for this project https://github.com/sganis/rsa
and I wondered for long time why making a private key from given prime
numbers was not available in openssl, I think it would be useful for
educational purposes, even with limited-use cases.
Regards,

S.

**Pull request closed without merging**
