### PR TITLE
PKCS#11 support in OpenSSL (engine from libp11 project)

### PR DESCRIPTION
**Pull request by opensignature**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
@opensignature as your title indicates and far as I can tell, most of the code you added here is taken from https://github.com/OpenSC/libp11. So you don't own the code, hence it is not possible for you to contribute it. Apart from that, the libp11 code is licensed under the LGPL-2.1 license, which prohibits adding source code from it. (@openssl/omc please correct be if I made any wrong statements here.)

_Note: the engine interface was made to enable third party developers to integrate their crypto algorithms as plugins into OpenSSL without recompiling it. So it is perfectly normal that those engines are developed by other projects and not part of OpenSSL._

**Comment by t-j-h** [comment]
-1 - this code simply cannot go into the tree - it is not covered by a CLA - as noted by @mspncp 

And even if the was a CLA and it was entirely original code it would need to go through a review process rather than be dropped in as a single chunk in this PR with multiple things mixed together.

It also doesn't use the official PKCS#11 header files and does not follow the requirements of the original PKCS#11 copyright and license from RSA, nor the terms noted by OASIS for the current v2.40 and pending v3.0 header files. These are problems for the base libp11 code and not something newly created in this PR.

**Comment by opensignature** [comment]
Ok, sorry for the noise.
Is there another way to add engine pkcs11 (possibly avoiding writing it from scratch) ?
I believe there are more and more requests to simplify the use of pkcs11 within Openssl.
Sometimes there are conflicts between Openssl, external pkcs11 engine and cryptoki.
With a pkcs11 engine compiled inside Openssl we would avoid part of these.

**Comment by mspncp** [comment]
> However being beaten by the legendary @t-j-h is an honor :)

That's for sure. Three red labels and a '-1' veto is worth an entry in the Guiness Book of World Records ;-).

**Comment by mspncp** [comment]
I agree that integrating pkcs11 support into OpenSSL could be useful. But I wouldn't implement it as an ENGINE then, instead as a submodule, say `crypto/pkcs11`, next to `crypto/pkcs12` and `crypto/pkcs7`. Providing PKCS\#11 support via a nested plugin, i.e. an `pkcs11-engine.so` which loads a `pkcs11-library.so`, does not make sense to me.

As for openssl-ibmpkcs11: It seems that the authors kept the original OpenSSL License (see their [LICENSE](https://github.com/opencryptoki/openssl-ibmpkcs11/blob/master/LICENSE) file), which will make it easier to find an agreement if you intend to reuse the code. But still you would need to ask them for their explicit permission, and they would have to sign a CLA. But that's just my personal opinion, [IANAL](https://en.wikipedia.org/wiki/IANAL).

**Comment by opensignature** [comment]
> That's for sure. Three red labels and a '-1' veto is worth an entry in the Guiness Book of World Records ;-).

Even when I sent CAdES PR I was expecting ripples but in the end it came out something good ;)

**Comment by mspncp** [comment]
Well the OpenSSL project has a very positive attitude towards its users and and contributors, as you can read in our [Code of Conduct](https://www.openssl.org/community/conduct.html). It may happen once in a while that a member reacts emotional (after all, we're all just humans), but we generally don't do any bashing or flaming.

**Comment by opensignature** [comment]
My goal is only to improve OpenSSL where, in my opinion, it's a bit behind proprietary software and other free software, ie CAdES and pkcs11. In the first I succeeded in part, thanks also to the precious help of @FdaSilvaYY. In the second I tried and will try if someone gives me the chance.
I have patience and do not discourage failures.
It's true, I make many mistakes (some unforgivable as licenses and "single chunk with multiple things mixed together") but I learn quickly ;)
Now I take some time to study pkcs11, openssl-ibmpkcs11, libp11, opensc-pkcs11, etc.
See you soon.

**Comment by levitte** [comment]
Aren't you all really looking for making libcrypto a full blown PKCS#11 client?  That demands quite a bit more than merely adding a sub-module, it would basically affect everything crypto under the hood.

Thing is that the inner workings of OpenSSL do not quite fit the PKCS#11 model all the way (and then I don't know PKCS#11 at all well)...  so basically, the role of a PKCS#11 engine is to be a translator between OpenSSL's plumbing and the PKCS#11 API, with what is required for the latter to work.

**Comment by opensignature** [comment]
I remain of the opinion that the only problem of libp11 (already engine-pkcs11) is the license and obviously the will of current developers but that from a technical point of view is a good choice.
engine-pkcs11 was initially developed by the same people as OpenSC (Olaf Kirch, Kevin Stefanik, etc.) and on OpenSC, back in 2004, I collaborated to add the PKCS#15 emulation of the smart cards I had at the time.

**Comment by mspncp** [comment]
@opensignature instead of discussing these matters on a closed pull request, it might be better if you would open a separate issue for promoting your pkcs11 feature request.

**Pull request closed without merging**
