### PR TITLE
Update VMS configurations

### PR DESCRIPTION
**Pull request by levitte**
The x86_64 port has been moving forward, there is now a C compiler
available (released in mid-February this year).

Furthermore, OpenSSL has had support for using the OpenVMS port of
Intel's `ias` for years, but not had any actual information about it.
It's about time that it's mentioned.

### CODE REVIEW

**Review by hlandau — APPROVED** [review]

**Review by t8m — APPROVED** [review]
Is this a bug fix? I do not know.

**Review by paulidale — APPROVED** [review]
Definitely not a bug fix IMO.
This is a feature.  It also doesn't meet the config addition only requirement for back porting.

**Comment by paulidale** [comment]
and merged.

**Comment by levitte** [comment]
This is a bug fix.  The cross compiling config target should never have been named `vms-x86_64`, as that suggests native build environment...  and as a matter of fact, the guesser mechanism in [`OpenSSL::config`](https://github.com/openssl/openssl/blob/master/util/perl/OpenSSL/config.pm) is already setup to answer `vms-x86_64` for a VMS instance on x86_64:

https://github.com/openssl/openssl/blob/d500f04400d0acc83fe5270da860764a7d19deee/util/perl/OpenSSL/config.pm#L168-L172
https://github.com/openssl/openssl/blob/d500f04400d0acc83fe5270da860764a7d19deee/util/perl/OpenSSL/config.pm#L950-L953

This means that for 3.0 and 3.1, someone doing the documented minimum configuration and build:

``` console
$ perl Configure
$ mms
```

...  will get a very early build failure looking approximately like this:

```
%DCL-E-OPENIN, error opening SYS$SYSROOT:[SYSMGR]X86_XTOOLS$SYLOGIN.COM; as input
-RMS-E-FNF, file not found
```

Having the cross compiling config target (misnamed) was always meant to be a temporary measure for the state of affairs a few years, and was meant to be updated to a more correctly defined config target as soon as a native compiler for x86_64 appeared.

So, if this isn't backported fully to 3.0 and 3.1, *at least the config target rename in `Configurations/50-vms-x86_64.conf` should*!

**Comment by t8m** [comment]
I am OK treating it as a bug fix.

**Comment by levitte** [comment]
I reopened this and am currently seeking approval to backport, hoping that my explanation helped.  If agreement is impossible, this will require an OTC discussion

**Comment by hlandau** [comment]
OK with this being a bug fix.

**Comment by levitte** [comment]
I'll take that as two approvals to backport.  Thanks

**Comment by levitte** [comment]
Merged to 3.1:

b93c2d360812c4e1ecc1d93f3f1e8d58e9e4e7f4 Update VMS configurations
945834914ffad3548052bbb1c785ec36263af268 Add information on the 'ias' port for OpenVMS

**Comment by levitte** [comment]
Merged to 3.0:

5645d5ff47aa304d2be6c07a5102f47e1193243f Update VMS configurations
3dc175c2d2ef6b9358fca9015010f45b4fb03d3b Add information on the 'ias' port for OpenVMS

**Pull request closed without merging**
