### PR TITLE
Remove cmp generated test Mock files from 'git status'

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
@DDvO -  Ideally these generated files would not sit in the same folder as committed files (somewhere under test-runs).
If they all need to be in the same folder, you could copy the committed ones files into the same place as the generated ones maybe somewhere under test-runs.

**Review by mattcaswell — APPROVED** [review]
I was wondering who was going to crack first and produce a PR for this.

**Comment by levitte** [comment]
This should not be needed, all test artefacts should end up under `test-runs/`. The test recipes is outputting in the wrong location (it's outputting in the source tree, even when the build tree is separate, which is fundamentally wrong, since the source tree should be considered read-only in that kind of setting).

**Comment by DDvO** [comment]
I agree with @levitte and will fix this in the right way soon...

**Comment by DDvO** [comment]
Thanks @slontis for a first attempt on addressing this.
I've just solved the issue at its root: #12934.

**Comment by DDvO** [comment]
This PR has become superseded, so closing it.

**Pull request closed without merging**
