### PR TITLE
Adapt building OpenSSL 3.0 for VMS

### LINKED ISSUE #14247: OpenSSL 3.0 currently doesn't build on OpenVMS, adaptation needed
There are two problems:

1.  For some reason, `OpenSSL::config` (`util/perl/OpenSSL/config.pm`) tries to run the command `uname` instead of using the corresponding POSIX functions, which I'm pretty sure are used.  That needs correcting.
2.  The way include directories are given on the command line in `Configurations/descrip.mms.tmpl` is deeply flawed, as it's hardcoded for pre-3.0 conditions.  The situation in 3.0 is very different, and the proper adjustment is not to make more of the hardcoded cruft, but rather to generalise it properly.
3.  There are a few things that have been updated in the other build file templates that hasn't in `Configurations/descrip.mms.tmpl`.  This should hopefully be a fairly simple task as soon as the two points above are done.

### PR DESCRIPTION
**Pull request by levitte**
The biggest part of adapting the build of OpenSSL 3.0 to VMS was to deal with a larger and varying number of inclusion directories.  

With pre-3.0, these directories were relatively few, so its descrip.mms (what Unix folks call "Makefile") did a few dirty hacks using logical names and that was that, and the command line was still kept within the command line length limit (which is pretty short).
With 3.0, the strategy needed to be changed.  Fortunately, the VMS C compiler has the qualifier `/FIRST_INCLUDE` (corresponding to gcc's `-include` flag) and a useful pragma, `#pragma include_directory "/path/to/header/files"`, so what we do is to automatically generate header files with the appropriate inclusion directories for diverse cases, and use them when compiling.

The rest of the changes is simply playing catch-up with what has happened with the Unix and Windows Makefile templates.

A consequence of this is that many of the rather special variables in descrip.mms are removed, as going through them is pretty cumbersome and benefits no one.  Instead, a set of useful perl variables are set up in descrip.mms.tmpl, and are used directly by the perl fragments

Fixes #14247

Note that this does *not* include diverse C source file changes that are needed to build without errors.  Those will come in a separate PR.

### CODE REVIEW

**Comment by levitte** [comment]
Windows failure fixed

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Small tweak added, please re-approve

**Comment by t-j-h** [comment]
Still approved

**Comment by levitte** [comment]
Merged

58ad786aa7b5c19021686c74e02ead3968050da6 Turn off VMS C's info about unsupported pragmas
22119050ab21ed5c9cf361d29aabc6b5da9c8aad Configurations/descrip.mms.tmpl: Diverse updates
a2625c0fc8ad229871874782ee2b5c46e66f9716 Fix OpenSSL::fallback for VMS
a1181fbdd0df70109c04283c564718b6f8d6ec18 Fix The VMS variant of platform->staticname()
0c1428f4418cbd4d449bd43100017b85db17b17d Fix configdata.pm.in's "use lib" for VMS
cfc73c230d1766903314f6b088a8da37fec1e9f0 Thrown away all special descrip.mms variables
0cbb6f6a9ac5aa3ff813ef2e5afe6e443708ee20 Configurations/descrip.mms.tmpl: Change strategy for include directories
8ba3a15816c6e417967eac13ee415325c52675b4 Configurations/descrip.mms.tmpl: Add another inclusion hack
31be74d3ca8809752b7dfd37394f28c76c519fa5 VMS need to build DSO with name shortening, because of provider code
bba402ece781db0918e0a27289cf38479bafb023 Tweak apps/build.info for VMS

**Pull request closed without merging**
