### PR TITLE
fix descriptions of credentials and verification app options

### PR DESCRIPTION
**Pull request by DDvO**
Looking for a way to provide extra untrusted certs for chain building during TLS server cert verification
I found that for both `s_client`  and `s_server` the documentation of the certificates given with the `-cert_chain` option attributes them as 'trusted' while in fact they are just untrusted additional certs to use for chain building. 

On the other hand the documentation of most of the `-chainCAfile`, `-chainCApath`, `-chainCAstore`, `-verifyCAfile`, `-verifyCApath`, and `-verifyCAstore` options failed to make clear that all the certificates addressed by them are trusted.

When correcting this I found and fixed some mistakes in the file format options and their descriptions.

I've also slightly improved the description of the `crl_download` and `nameopt` options. 

Moreover, the order of the description of these and related options was somewhat inconsistent, which is fixed as well in this PR.

### CODE REVIEW

**Comment by DDvO** [comment]
BTW, how can one provide untrusted certs to help verifying peer certs, to use in case a peer does not send (all of) its cert chain?

**Comment by DDvO** [comment]
Thanks @beldmit for your very swift approval!

Do you know if/how one can provide untrusted certs to help verifying peer TLS certs, to use in case a peer does not send (all of) its cert chain?
I found this possibility only for the `verify` app and direct use of `X509_STORE_CTX_init()`.

**Comment by beldmit** [comment]
I don't know either :(
Not sure if it's a reasonable option because in real life (e. g. browsers) we don't have such a store so servers must include a full chain to avoid errors

**Comment by DDvO** [comment]
I agree that for web scenarios pre-known untrusted certs make little sense,
but in managed (e.g., industrial) scenarios it can make much sense, 
in particular with limited bandwidth where it would be nice to avoid sending the same untrusted certs over and over.

**Comment by richsalz** [comment]
This is going to be an RFC soon, it's just waiting for text editing: https://datatracker.ietf.org/doc/draft-ietf-tls-certificate-compression/?include_text=1

**Comment by DDvO** [comment]
Nice, but this just compresses the certs being transmitted, but does not stop sending them.
And transmission size is not the only potential reason why a TLS node may need to augment the cert chain it receives from a peer.

**Comment by DDvO** [comment]
Rebased and partly squashed.
Given that the approval was done two days before, can I merge this PR right away?

**Comment by t8m** [comment]
It is missing OTC member approval.

**Comment by kaduk** [comment]
Using extra certs for chain building can come into play when the server is sending a potentially valid chain but you want to use a different one, e.g., chaining up to a different or cross-signed root.

**Comment by DDvO** [comment]
Ping for OTC approval

**Comment by DDvO** [comment]
Rebased this PR. It still needs an OTC approval.

**Comment by DDvO** [comment]
The review/approval by @jaym05700 does not count here.

**Comment by DDvO** [comment]
Pinging again on a OTC member approval.

**Comment by DDvO** [comment]
Merged - thanks!

**Comment by DDvO** [comment]
I just found that the merge did not really happen, likely due to some misspelling or the like.
Now it's actually merged.

**Pull request closed without merging**
