### PR TITLE
Document in CHANGES that config now recognises 64-bit mingw

### PR DESCRIPTION
**Pull request by levitte**
-----

Related to #2914

### CODE REVIEW

**Comment by dot-asm** [comment]
Speaking of #2914. When you install MSYS2 you get MinGW 32-bit and MinGW 64-bit icons. Difference? Different `$PATH` pointing at 32- or 64-bit compiler. Different `uname -s` output, but[!] same `uname -m`. #2914 effectively "looks" at latter, while it should probably "look" at former...

**Comment by dot-asm** [comment]
This is guaranteed not be cherry-pickable to non-master. Shouldn't it be handled with separate requests? And recall [skip ci] ;-) Also with whole thing being that messy, it might be appropriate to say couple of words about how the choice is made, i.e. on `uname -s` output.

Just in case for reference. If MSYS is started with MSYS icon, i.e. not with either MinGW one, `uname -s` returns `MSYS_NT-x.y`...

**Comment by levitte** [comment]
Yeah, but this case is about MingW specifically.  `MSYS_NT-x.y-*whatever*` will still be handled with some generic catch-all [such as this one](https://github.com/openssl/openssl/blob/master/config#L815)

**Comment by levitte** [comment]
I'll have a look at the MingW 32-bit and 64-bit icons to see what may need corrected...  My Windows is only a 32-bit installation, though, so I may miss some nuances.

**Comment by levitte** [comment]
> This is guaranteed not be cherry-pickable to non-master. Shouldn't it be handled with separate requests? And recall [skip ci] ;-) Also with whole thing being that messy, it might be appropriate to say couple of words about how the choice is made, i.e. on `uname -s` output.

Oh wait, are you telling me that there really should be a change [here](https://github.com/openssl/openssl/blob/master/config#L323-L325)?

**Comment by dot-asm** [comment]
> Oh wait, are you telling me that there really should be a change here?

Yes, that's what I'm saying.

And reference to `uname -s` returning `MSYS_NT-x.y` was just a hint on how messy the problem is...

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
But wait, hold on...  if `uname -s` gives "i686", then the 64-bit gcc implementation isn't usable anyway, regardless of what mingw tries to pretend (I just tried)...  #2914 is fixing a report where `uname -m` gave "x86_64" (see the email thread I've linked to).

I'll go with @richsalz's approval for now (which isn't that hard to cherry-pick).

**Comment by levitte** [comment]
master: b1fa4031feb94e1406f3bd2ba0f771e48d0407b5
1.1.0: e342f396142331aa58187afa441581590bc80af9
1.0.2: 7b64c79bd5d3c1183b989de70170b0052b1d6c9e

**Comment by dot-asm** [comment]
Once again, `uname -s` returns either `MINGW32_NT-x.y` or `MINGW64_NT-x.y` (or `MSYS_NT-x.y`) depending on icon you used to open the prompt window. `uname -m` on the other hand is `x86_64` in all cases. So that while #2914 works in `MINGW64_NT-x.y` window, it does *not* in `MINGW32_NT-x.y`. It attempts to use mingw64 config with 32-bit compiler (because that's what on the $PATH) and *does* fail compiling first file.

**Comment by dot-asm** [comment]
Besides, my keyword *here*, i.e. in regards to CHANGES, was to add few words of clarification, primarily for 1.0.2 users, so that they have fair chance to access situation without digging into code.

**Comment by levitte** [comment]
I see.

I have seen the exact same problem but the other way around.  If I choose a MingW64 shell on my 32-bit Windows instance, I get `MINGW64_NT-x.y` from `uname -s`...  so I tried `./Configure mingw64` just to see, and well, it went *BAMF*...

So I guess that the recommendation is to run a shell of "matching bitness"...

I'll ponder over the wordings unless you feel compelled to.  I'm going out for a few hours, so whatever I do, it won't be immediate.

**Comment by dot-asm** [comment]
> If I choose a MingW64 shell on my 32-bit Windows instance, I get MINGW64_NT-x.y from uname -s... so I tried ./Configure mingw64 just to see, and well, it went BAMF...

`which gcc`? Is it possible that you call upon /usr/bin/gcc, which formally is *not* right compiler for mingw configurations, be it 32- or 64-bit one? [At least] under MSYS2 it should be either /mingw32/bin/gcc or /mingw64/bin/gcc...

[Just in case. No, I don't know what does MinGW64 shell on 32-bit Windows instance actually mean in practice. But the least one can be sure about is that if there is installable 32-bit compiler that produces 64-bit code, you wouldn't be able to execute resulting binaries on 32-bit Windows. In other words 32-bit Windows users are not really in position to expect that mingw64 config would work anyway. It would have to classified as cross-compiling case and we don't support auto-config in cross-compile cases.]

**Pull request closed without merging**
