### PR TITLE
Do no mention private headers in public headers

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by mspncp — APPROVED** [review]
LGTM

**Comment by levitte** [comment]
Merged

bd9faf117db1e53b2ad2ee9cbfe8def8c98ecb7b Do no mention private headers in public headers

**Comment by mspncp** [comment]
@levitte this commit can be cherry-picked to 1.1.1 cleanly, except for one trivial conflict, [the hunk in bio.h](https://github.com/openssl/openssl/commit/bd9faf117db1e53b2ad2ee9cbfe8def8c98ecb7b#diff-656edf30aac921eeb1c9418e976f6b95L145-R145), which can be dropped because the line does not exist in 1.1.1 yet. Is it ok for you if I cherry-pick it? Does the (trivial) conflict mandate a separate pull request? Or can I just push the commit below to 1.1.1?

```diff
commit b8f2701c38cf07f364a9899dfc20c972a9dafaef (HEAD -> cherry)
Author: Richard Levitte <levitte@openssl.org>
Date:   Mon Sep 9 02:41:26 2019 +0200

    Do no mention private headers in public headers
    
    Reviewed-by: Matthias St. Pierre <Matthias.St.Pierre@ncp-e.com>
    (Merged from https://github.com/openssl/openssl/pull/9812)
    
    (cherry picked from commit bd9faf117db1e53b2ad2ee9cbfe8def8c98ecb7b)

diff --git a/include/openssl/ct.h b/include/openssl/ct.h
index d4262fa048..ebdba34d67 100644
--- a/include/openssl/ct.h
+++ b/include/openssl/ct.h
@@ -463,8 +463,6 @@ __owur int CTLOG_STORE_load_file(CTLOG_STORE *store, const char *file);
 
 /*
  * Loads the default CT log list into a |store|.
- * See internal/cryptlib.h for the environment variable and file path that are
- * consulted to find the default file.
  * Returns 1 if loading is successful, or 0 otherwise.
  */
 __owur int CTLOG_STORE_load_default_file(CTLOG_STORE *store);
diff --git a/include/openssl/dtls1.h b/include/openssl/dtls1.h
index a312e386cf..d55ca9c332 100644
--- a/include/openssl/dtls1.h
+++ b/include/openssl/dtls1.h
@@ -43,7 +43,7 @@ extern "C" {
 
 # define DTLS1_AL_HEADER_LENGTH                   2
 
-/* Timeout multipliers (timeout slice is defined in apps/timeouts.h */
+/* Timeout multipliers */
 # define DTLS1_TMO_READ_COUNT                      2
 # define DTLS1_TMO_WRITE_COUNT                     2
 
diff --git a/include/openssl/evp.h b/include/openssl/evp.h
index 545654a98b..8abcd8a8a3 100644
--- a/include/openssl/evp.h
+++ b/include/openssl/evp.h
@@ -180,7 +180,7 @@ int (*EVP_MD_meth_get_ctrl(const EVP_MD *md))(EVP_MD_CTX *ctx, int cmd,
  * if the following flag is set.
  */
 # define EVP_MD_CTX_FLAG_FINALISE        0x0200
-/* NOTE: 0x0400 is reserved for internal usage in evp_int.h */
+/* NOTE: 0x0400 is reserved for internal usage */
 
 EVP_CIPHER *EVP_CIPHER_meth_new(int cipher_type, int block_size, int key_len);
 EVP_CIPHER *EVP_CIPHER_meth_dup(const EVP_CIPHER *cipher);
```

**Comment by levitte** [comment]
I approve that cherry pick

**Comment by mspncp** [comment]
_(Needless to say, that the cherry-pick is a preparation for #9681.)_

**Comment by mspncp** [comment]
Ok, thanks!

**Comment by mspncp** [comment]
Pushed to b8f2701c38cf07f364a9899dfc20c972a9dafaef.

**Pull request closed without merging**
