### PR TITLE
Add -verbose/-quiet flags to dhparam

### PR DESCRIPTION
**Pull request by pprindeville**
Allow dhparam to run quietly in scripts, etc.

For other commands that took a -verbose flag already, also support -quiet.

For genpkey which only supported -quiet, add the -verbose flag.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I've flagged this for a decision -- it's technically a breaking change.

**Comment by pprindeville** [comment]
> I've flagged this for a decision -- it's technically a breaking change.

Breaking how and which part?  In that it makes the default quiet?

**Comment by paulidale** [comment]
Any script that _expects_ the verbose output is potentially broken by this change.  Thus, a decision needs to be made to accept this potential breakage.  OpenSSL is very conservative about making changes that might break things.

**Comment by pprindeville** [comment]
> Any script that _expects_ the verbose output is potentially broken by this change. Thus, a decision needs to be made to accept this potential breakage. OpenSSL is very conservative about making changes that might break things.

I see.

So how is this normally handled?  We could add code to handle both `-quiet` and `-verbose` for now, and then flip the default in the future and deprecate unneeded option.

And should I split out the first two commits into a separate PR as housekeeping?

**Comment by paulidale** [comment]
It will depend on the decision...
Breaking changes are usually made with major releases (i.e. OpenSSL 4.0) but typically still require a decision.

The first commit is also breaking by changing from stderr to stdout.
the second looks good.

**Comment by kroeckx** [comment]
This will probably require a NEWS entry

**Comment by pprindeville** [comment]
> The first commit is also breaking by changing from stderr to stdout. the second looks good.

Okay, moved the progress to a standalone PR #17359.

**Comment by t-j-h** [comment]
This would be a change in behaviour from the way it worked before and would make it inconsistent with other apps.
We would need to have a policy and consistency on this - and when would we do this?

**Comment by t8m** [comment]
Breaking changes should go into 4.0 so this PR would have to be postponed to 4.0.

**Comment by t8m** [comment]
If there was a PR to add -quiet flag to suppress the progress output, it could be reviewed and accepted in 3.x.

**Comment by pprindeville** [comment]
> If there was a PR to add -quiet flag to suppress the progress output, it could be reviewed and accepted in 3.x.

Well, there will be, as soon as I can rebase to PR #17359 hitting `master`.

**Comment by pprindeville** [comment]
> > If there was a PR to add -quiet flag to suppress the progress output, it could be reviewed and accepted in 3.x.
> 
> Well, there will be, as soon as I can rebase to PR #17359 hitting `master`.

Actually, it got changed to `-verbose` to be consistent with most other commands... so... hold back for 4.0?

**Comment by pprindeville** [comment]
> If there was a PR to add -quiet flag to suppress the progress output, it could be reviewed and accepted in 3.x.

That would be diverging from what other commands do.

**Comment by t8m** [comment]
> That would be diverging from what other commands do.

There is no consistency right now either - the genpkey command has a `-quiet` option already. The only consistent way that could make it into 3.x would be to add the option that is missing to all the commands and keep the default for the existing command as is.

**Comment by pprindeville** [comment]
> > That would be diverging from what other commands do.
> 
> There is no consistency right now either - the genpkey command has a `-quiet` option already. The only consistent way that could make it into 3.x would be to add the option that is missing to all the commands and keep the default for the existing command as is.

Only `genpkey` is out-of-step.  Can it be flipped for 4.x?

**Comment by t8m** [comment]
No, there are also other applications with -quiet option. s_client, s_server, passwd, and fipsinstall.

Another point to consider is that the dh parameter generation is the slowest one which is a reason to give some progress output by default so users can see something is happenning.

**Comment by paulidale** [comment]
We could rationalise all these options for 4.0.  Ideally, all the commands would support both -quiet and -verbose.  I.e. they should be made into common options.

**Comment by pprindeville** [comment]
> We could rationalise all these options for 4.0. Ideally, all the commands would support both -quiet and -verbose. I.e. they should be made into common options.

Supporting both could happen today since it breaks nothing.  Flipping the defaults would be potentially breaking...

**Comment by paulidale** [comment]
Agreed.

**Comment by pprindeville** [comment]
Redux, something for everyone.  Now we support `-quiet` and `-verbose` for all commands generating status dots, and can easily change the line:

```
static int verbose = 1;
```

to zero in the future across the relevant apps if that's desired (say in 4.0).

**Comment by pprindeville** [comment]
Since this doesn't break existing behavior, can we remove the 4.0.0 milestone?

**Comment by t8m** [comment]
Yeah, in this form this is acceptable in 3.x

**Review by t8m — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master branch. Thank you for your contribution.

**Comment by pprindeville** [comment]
> No, this would not be acceptable for 1.1.1

Out of curiosity, what's the cutoff criteria?

**Comment by t8m** [comment]
Newly added options are a feature. Only bug fixes and documentation improvements are eligible for stable releases.

**Pull request closed without merging**
