### PR TITLE
Fix parameter types int -> integer changes

### PR DESCRIPTION
**Pull request by paulidale**
- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by InfoHunter — APPROVED** [review]
BTW, why is 'int' changed to 'integer;? For non-casualness purposes?

**Comment by levitte** [comment]
> BTW, why is 'int' changed to 'integer;? For non-casualness purposes?

We use 'integer' rather than 'int' when describing OSSL_PARAMs with the data type OSSL_PARAM_INTEGER, so as not to have the reader confuse that with the C type `int`.

**Review by levitte — APPROVED** [review]

**Comment by paulidale** [comment]
For parameters we use _integer_ and _unsigned integer_ because they aren't related to the C type `int`.

**Review by slontis — APPROVED** [review]
Thanks

**Comment by levitte** [comment]
Merged to master

2c3f1a6cad300e3812aee34dab98f23a329296f4 Fix parameter types int -> integer changes

**Pull request closed without merging**
