### PR TITLE
Fix typo in SSL_state_string_long

### PR DESCRIPTION
**Pull request by xiaoyinl**
I guess TLS_ST_SR_NEXT_PROTO means "SSLv3/TLS read next proto" and `TLS_ST_SW_CERT_STATUS` means "SSLv3/TLS write certificate status".

### CODE REVIEW

**Comment by dot-asm** [comment]
It's not clear if it will cherry-pick to 1.1.0, but it does belong even there. Suggestion also is to squash commits...

**Comment by xiaoyinl** [comment]
@dot-asm Do you mean squash by me?

**Comment by dot-asm** [comment]
> Do you mean squash by me?

Not necessarily. Basically it was rather a question to everybody, i.e. does it make sense to squash? I say that it makes sense to do so, while second reviewer might think differently. If we agree that squashing is sensible, it is less relevant who does it in *this* case, because it's rather simple modification. [If modification was more elaborate, I for one would prefer to do it for contributor.]

**Comment by levitte** [comment]
I think it makes sense to squash, not just because it's a simple modification, but also because the changes are very very similar (apart from the copyright header, but since that simply reflects that this file was changed, I don't see that it should be separate either).

Just make sure that the message of the squashed commit is sensible...

**Comment by richsalz** [comment]
squashed and merged to master and 1.1.0 (as shown by the commit messages above)
Thank you!

**Pull request closed without merging**
