### PR TITLE
rsa: replace magic number '11' by RSA_PKCS1_PADDING_SIZE

### PR DESCRIPTION
**Pull request by mspncp**
Suggested by Matt Hart

(see https://github.com/openssl/openssl/commit/ba2de73b185016e0a98e62f75b368ab6ae673919#r35331109)

### CODE REVIEW

**Comment by mspncp** [comment]
For your convenience, here is the #definition of the constant:

https://github.com/openssl/openssl/blob/0bc74d85bb4e3ae267c6c9e411a622c15b8ff81a/include/openssl/rsa.h#L199

**Comment by mspncp** [comment]
@mattcaswell I forgot to label the pull request. Does your approval hold for 1.1.1, too?

**Comment by mattcaswell** [comment]
Yes. 1.1.1 too.

**Comment by mspncp** [comment]
> Thanks for being so responsive.

You're welcome. And thanks again for the suggestion. Merged to master and 1.1.1:

f1d1903dd3 rsa: replace magic number '11' by RSA_PKCS1_PADDING_SIZE [master]
1a9a56865c rsa: replace magic number '11' by RSA_PKCS1_PADDING_SIZE [1.1.1]

**Pull request closed without merging**
