### PR TITLE
ECDSA_SIG_set0: r and s parameters cannot be NULL

### LINKED ISSUE #7731: ECDSA_SIG_set0 does not follow documentation
The documentation attached to the prototype declaration of `ECDSA_SIG_set0` seem to imply that `NULL` can be passed for `r` or `s` and the old value will be retained. The actual implementation returns an error if either is `NULL`.
Either the documentation or the implementation should be updated, with a preference for the latter (if updating only one part of the signature, you would need to create a duplicate for the other one).

### PR DESCRIPTION
**Pull request by t8m**
Fix the comment accordingly.

Fixes #7731

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by slontis** [comment]
ECDSA_SIG_new.pod could also be updated.

**Comment by t8m** [comment]
> ECDSA_SIG_new.pod could also be updated.

Done

@paulidale please re-approve.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the doco.

**Comment by paulidale** [comment]
Was there an intention for this to also go to 1.1.1?
The original issue lists 1.1.1 and master.

**Comment by t8m** [comment]
I am not sure it is worth it.

**Pull request closed without merging**
