### PR TITLE
DOC: POD syntax fixes in doc/man1/openssl-cmp.pod.in

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
@DDvO, I've a question re the SYNOPSIS.  Right now, it renders like this:

> # SYNOPSIS
> 
> **openssl** **cmp** \[**-help**\] \[**-config** _filename_\] \[**-section** _names_\]
> 
> \[**-server** _\[http\[s\]://\]address\[:port\]\[/path\]_\] \[**-proxy** _\[http\[s\]://\]address\[:port\]\[/path\]_\] \[**-no\_proxy** _addresses_\] \[**-path** _remote\_path_\] \[**-msg\_timeout** _seconds_\] \[**-total\_timeout** _seconds_\]
> 
> \[**-trusted** _filenames_\] \[**-untrusted** _sources_\] \[**-srvcert** _filename_\] \[**-recipient** _name_\] \[**-expect\_sender** _name_\] \[**-ignore\_keyusage**\] \[**-unprotected\_errors**\] \[**-extracertsout** _filename_\] \[**-cacertsout** _filename_\]
> 
> \[**-ref** _value_\] \[**-secret** _arg_\] \[**-cert** _filename_\] \[**-own\_trusted** _filenames_\] \[**-key** _filename_\] \[**-keypass** _arg_\] \[**-digest** _name_\] \[**-mac** _name_\] \[**-extracerts** _sources_\] \[**-unprotected\_requests**\]
> 
> \[**-cmd** _ir|cr|kur|p10cr|rr|genm_\] \[**-infotype** _name_\] \[**-geninfo** _OID:int:N_\]
> 
> \[**-newkey** _filename_\] \[**-newkeypass** _arg_\] \[**-subject** _name_\] \[**-issuer** _name_\] \[**-days** _number_\] \[**-reqexts** _name_\] \[**-sans** _spec_\] \[**-san\_nodefault**\] \[**-policies** _name_\] \[**-policy\_oids** _names_\] \[**-policy\_oids\_critical**\] \[**-popo** _number_\] \[**-csr** _filename_\] \[**-out\_trusted** _filenames_\] \[**-verify\_hostname** _cn_\] \[**-verify\_ip** _ip_\] \[**-verify\_email** _email_\] \[**-implicit\_confirm**\] \[**-disable\_confirm**\] \[**-certout** _filename_\] \[**-chainout** _filename_\]
> 
> \[**-oldcert** _filename_\] \[**-revreason** _number_\]
> 
> \[**-certform** _PEM|DER_\] \[**-keyform** _PEM|DER|P12|ENGINE_\] \[**-otherpass** _arg_\]
> 
> \[**-provider** _name_\] \[**-provider-path** _path_\]
> 
> \[**-tls\_used**\] \[**-tls\_cert** _filename_\] \[**-tls\_key** _filename_\] \[**-tls\_keypass** _arg_\] \[**-tls\_extra** _filenames_\] \[**-tls\_trusted** _filenames_\] \[**-tls\_host** _name_\]
> 
> \[**-verbosity** _level_\] \[**-batch**\] \[**-repeat** _number_\] \[**-reqin**\] _filenames_ \[**-reqin\_new\_tid**\] \[**-reqout**\] _filenames_ \[**-rspin**\] _filenames_ \[**-rspout**\] _filenames_ \[**-use\_mock\_srv**\]
> 
> \[**-policy** _arg_\] \[**-purpose** _purpose_\] \[**-verify\_name** _name_\] \[**-verify\_depth** _num_\] \[**-auth\_level** _level_\] \[**-attime** _timestamp_\] \[**-ignore\_critical**\] \[**-issuer\_checks**\] \[**-policy\_check**\] \[**-explicit\_policy**\] \[**-inhibit\_any**\] \[**-inhibit\_map**\] \[**-x509\_strict**\] \[**-extended\_crl**\] \[**-use\_deltas**\] \[**-policy\_print**\] \[**-check\_ss\_sig**\] \[**-crl\_check**\] \[**-crl\_check\_all**\] \[**-trusted\_first**\] \[**-suiteB\_128\_only**\] \[**-suiteB\_128**\] \[**-suiteB\_192**\] \[**-partial\_chain**\] \[**-no\_alt\_chains**\] \[**-no\_check\_time**\] \[**-allow\_proxy\_certs**\]
> 
> \[**-port** _number_\] \[**-max\_msgs** _number_\] \[**-srv\_ref** _value_\] \[**-srv\_secret** _arg_\] \[**-srv\_cert** _filename_\] \[**-srv\_key** _filename_\] \[**-srv\_keypass** _arg_\] \[**-srv\_trusted** _filenames_\] \[**-srv\_untrusted** _filenames_\] \[**-rsp\_cert** _filename_\] \[**-rsp\_extracerts** _filenames_\] \[**-rsp\_capubs** _filenames_\] \[**-poll\_count** _number_\] \[**-check\_after** _number_\] \[**-grant\_implicitconf**\] \[**-pkistatus** _number_\] \[**-failure** _number_\] \[**-failurebits** _number_\] \[**-statusstring** _arg_\] \[**-send\_error**\] \[**-send\_unprotected**\] \[**-send\_unprot\_err**\] \[**-accept\_unprotected**\] \[**-accept\_unprot\_err**\] \[**-accept\_raverified**\]

Did you actually mean it to be this (note the inserted command, which aligns better with how variants of commands are usually specified)?

> # SYNOPSIS
> 
> **openssl** **cmp** \[**-help**\] \[**-config** _filename_\] \[**-section** _names_\]
> 
> **openssl** **cmp** \[**-server** _\[http\[s\]://\]address\[:port\]\[/path\]_\] \[**-proxy** _\[http\[s\]://\]address\[:port\]\[/path\]_\] \[**-no\_proxy** _addresses_\] \[**-path** _remote\_path_\] \[**-msg\_timeout** _seconds_\] \[**-total\_timeout** _seconds_\]
> 
> **openssl** **cmp** \[**-trusted** _filenames_\] \[**-untrusted** _sources_\] \[**-srvcert** _filename_\] \[**-recipient** _name_\] \[**-expect\_sender** _name_\] \[**-ignore\_keyusage**\] \[**-unprotected\_errors**\] \[**-extracertsout** _filename_\] \[**-cacertsout** _filename_\]
> 
> **openssl** **cmp** \[**-ref** _value_\] \[**-secret** _arg_\] \[**-cert** _filename_\] \[**-own\_trusted** _filenames_\] \[**-key** _filename_\] \[**-keypass** _arg_\] \[**-digest** _name_\] \[**-mac** _name_\] \[**-extracerts** _sources_\] \[**-unprotected\_requests**\]
> 
> **openssl** **cmp** \[**-cmd** _ir|cr|kur|p10cr|rr|genm_\] \[**-infotype** _name_\] \[**-geninfo** _OID:int:N_\]
> 
> **openssl** **cmp** \[**-newkey** _filename_\] \[**-newkeypass** _arg_\] \[**-subject** _name_\] \[**-issuer** _name_\] \[**-days** _number_\] \[**-reqexts** _name_\] \[**-sans** _spec_\] \[**-san\_nodefault**\] \[**-policies** _name_\] \[**-policy\_oids** _names_\] \[**-policy\_oids\_critical**\] \[**-popo** _number_\] \[**-csr** _filename_\] \[**-out\_trusted** _filenames_\] \[**-verify\_hostname** _cn_\] \[**-verify\_ip** _ip_\] \[**-verify\_email** _email_\] \[**-implicit\_confirm**\] \[**-disable\_confirm**\] \[**-certout** _filename_\] \[**-chainout** _filename_\]
> 
> **openssl** **cmp** \[**-oldcert** _filename_\] \[**-revreason** _number_\]
> 
> **openssl** **cmp** \[**-certform** _PEM|DER_\] \[**-keyform** _PEM|DER|P12|ENGINE_\] \[**-otherpass** _arg_\]
> 
> **openssl** **cmp** \[**-provider** _name_\] \[**-provider-path** _path_\]
> 
> **openssl** **cmp** \[**-tls\_used**\] \[**-tls\_cert** _filename_\] \[**-tls\_key** _filename_\] \[**-tls\_keypass** _arg_\] \[**-tls\_extra** _filenames_\] \[**-tls\_trusted** _filenames_\] \[**-tls\_host** _name_\]
> 
> **openssl** **cmp** \[**-verbosity** _level_\] \[**-batch**\] \[**-repeat** _number_\] \[**-reqin**\] _filenames_ \[**-reqin\_new\_tid**\] \[**-reqout**\] _filenames_ \[**-rspin**\] _filenames_ \[**-rspout**\] _filenames_ \[**-use\_mock\_srv**\]
> 
> **openssl** **cmp** \[**-policy** _arg_\] \[**-purpose** _purpose_\] \[**-verify\_name** _name_\] \[**-verify\_depth** _num_\] \[**-auth\_level** _level_\] \[**-attime** _timestamp_\] \[**-ignore\_critical**\] \[**-issuer\_checks**\] \[**-policy\_check**\] \[**-explicit\_policy**\] \[**-inhibit\_any**\] \[**-inhibit\_map**\] \[**-x509\_strict**\] \[**-extended\_crl**\] \[**-use\_deltas**\] \[**-policy\_print**\] \[**-check\_ss\_sig**\] \[**-crl\_check**\] \[**-crl\_check\_all**\] \[**-trusted\_first**\] \[**-suiteB\_128\_only**\] \[**-suiteB\_128**\] \[**-suiteB\_192**\] \[**-partial\_chain**\] \[**-no\_alt\_chains**\] \[**-no\_check\_time**\] \[**-allow\_proxy\_certs**\]
> 
> **openssl** **cmp** \[**-port** _number_\] \[**-max\_msgs** _number_\] \[**-srv\_ref** _value_\] \[**-srv\_secret** _arg_\] \[**-srv\_cert** _filename_\] \[**-srv\_key** _filename_\] \[**-srv\_keypass** _arg_\] \[**-srv\_trusted** _filenames_\] \[**-srv\_untrusted** _filenames_\] \[**-rsp\_cert** _filename_\] \[**-rsp\_extracerts** _filenames_\] \[**-rsp\_capubs** _filenames_\] \[**-poll\_count** _number_\] \[**-check\_after** _number_\] \[**-grant\_implicitconf**\] \[**-pkistatus** _number_\] \[**-failure** _number_\] \[**-failurebits** _number_\] \[**-statusstring** _arg_\] \[**-send\_error**\] \[**-send\_unprotected**\] \[**-send\_unprot\_err**\] \[**-accept\_unprotected**\] \[**-accept\_unprot\_err**\] \[**-accept\_raverified**\]

I can make that change part of this PR if that was the intent.

**Review by slontis — APPROVED** [review]
Thanks - didnt get around to fixing them

**Comment by richsalz** [comment]
Put the command name there, like the others do.

**Comment by levitte** [comment]
> Put the command name there, like the others do.

Thanks, but I'm not entirely sure that it's as evident as I believe, and would like to hear from @DDvO if that was the intent, or if more work is needed.

**Comment by DDvO** [comment]
> > Put the command name there, like the others do.
> 
> Thanks, but I'm not entirely sure that it's as evident as I believe, and would like to hear from @DDvO if that was the intent, or if more work is needed.

Thanks @levitte for pointing out this problem and asking what the intention was.
The idea was to structure the large number of CLI options.
It looks like this is not really supported for (the given implementation of) POD files.

Having a closer look I found that also many other apps have problems here, 
at least those having a - meanwhile deprecated -  `-engine` option.

I've provided a not very nice but working solution for that in #12932; please switch over to there for any further discussion.

**Review by DDvO — COMMENTED** [review]
LGTM
I don't really understand why those added empty lines help (`make doc-nits` has been happy since long already), but certainly they don't hurt.

**Comment by levitte** [comment]
> I don't really understand why those added empty lines help

PODs are read in paragraph mode, which means that:

1.  For this one, the whole paragraph, including the explaining text, was interpreted as the item instead of item + explaining text:

    > ```
    > =item B<-no_proxy> I<addresses>
    > List of IP addresses and/or DNS names of servers
    > not to use an HTTP(S) proxy for, separated by commas and/or whitespace
    > (where in the latter case the whole argument must be enclosed in "...").
    > Default is from the environment variable C<no_proxy> if set, else C<NO_PROXY>.
    > ```

    So the mapage output result (surrounding text added) became:

    > ```
    >       -proxy [http[s]://]address[:port][/path]
    >           The HTTP(S) proxy server to use for reaching the CMP server unless
    >           no_proxy applies, see below.  The optional http:// or https://
    >           prefix and any trailing path are ignored.  Defaults to the
    >           environment variable "http_proxy" if set, else "HTTP_PROXY" in case
    >           no TLS is used, otherwise "https_proxy" if set, else "HTTPS_PROXY".
    >
    >       -no_proxy addresses List of IP addresses and/or DNS names of servers
    >       not to use an HTTP(S) proxy for, separated by commas and/or whitespace
    >       (where in the latter case the whole argument must be enclosed in
    >       "..."). Default is from the environment variable "no_proxy" if set,
    >       else "NO_PROXY".
    >       -path remote_path
    >           HTTP path at the CMP server (aka CMP alias) to use for POST
    >           requests.  Defaults to any path given with -server, else "/".
    > ```

2.  The other one:

    > ```
    >   cd /path/to/openssl
    >   export OPENSSL_CONF=openssl.cnf
    > =begin comment
    >   wget 'http://pki.certificate.fi:8081/install-ca-cert.html/ca-certificate.crt\
    >         ?ca-id=632&download-certificate=1' -O insta.ca.crt
    > =end comment
    >   openssl genrsa -out insta.priv.pem
    >   openssl cmp -section insta
    > ```

    Resulted in this manpage output:

    > ```
    >          cd /path/to/openssl
    >          export OPENSSL_CONF=openssl.cnf
    >        =begin comment
    >          wget 'http://pki.certificate.fi:8081/install-ca-cert.html/ca-certificate.crt\
    >                ?ca-id=632&download-certificate=1' -O insta.ca.crt
    >        =end comment
    >          openssl genrsa -out insta.priv.pem
    >          openssl cmp -section insta
    > ```

**Comment by levitte** [comment]
Merged

6600baa9bb6e59be91692791a6251c172a099a65 DOC: POD syntax fixes in doc/man1/openssl-cmp.pod.in

**Pull request closed without merging**
