### PR TITLE
DSA_generate_parameters_ex: use the old method for all small keys

### LINKED ISSUE #14733: DSA key generation fails with legacy API for keys smaller than 1024.
This report is based on OpenSSL 3 alpha 13.

.NET's DSA current DSA key generation code, which has yet to be converted to EVP_PKEY, fails when testing with OpenSSL 3 (alpha 13) for key sizes less than 1024.  (Specifically, it fails with 512 and 512+64 (576))

```C
int32_t CryptoNative_DsaGenerateKey(DSA** dsa, int32_t bits)
{
    if (!dsa)
    {
        assert(false);
        return 0;
    }

    *dsa = DSA_new();
    if (!(*dsa))
    {
        return 0;
    }

    if (!DSA_generate_parameters_ex(*dsa, bits, NULL, 0, NULL, NULL, NULL) ||
        !DSA_generate_key(*dsa))
    {
        DSA_free(*dsa);
        *dsa = NULL;
        return 0;
    }

    return 1;
}
```

When this fails the top error on the stack is `error:05000072:dsa routines::bad ffc parameters`.

Trying to step through to figure out where the problems arise wasn't being very fruitful.  One piece of suspect code:

https://github.com/openssl/openssl/blob/88df2c0b3d6162971304c06a240deb9320c9ae67/crypto/dsa/dsa_gen.c#L60-L69

Since `(seed: NULL, seed_len: 0)` worked in the past, it seems like the check maybe wants to be more complex (e.g. all `bits < 1024` want to be FIPS 186-2, but 1024 only wants to be 186-2 when forced?)

Noticing that `(seed: NULL, seed_len: 20)` doesn't trip any validation errors I tried that to go down the 182-2 path, but then I feel like generation failed because it ended up in the 186-4 routine.  Perhaps this was fixed in #14508?

---

I tried a quick/naive conversion to the EVP_PKEY routines, but that also didn't work.  (I didn't try a previously succeeding test to see if I just failed in my conversion.)

---

I can see this being pretty low priority:
* It's DSA, a nearly dead algorithm.
* It's using massively undersized keys for 2021.
* It's using now-deprecated API.

But thought I'd point it out for compatibility, since effort seems to have gone in to maintaining FIPS 186-2 DSA support.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #14733

### CODE REVIEW

**Comment by slontis** [comment]
Still not sure we should be allowing people to keep generating weak keys..

**Comment by richsalz** [comment]
> Still not sure we should be allowing people to keep generating weak keys..

It can be useful to use openssl to test *other* systems in production.

**Comment by slontis** [comment]
you mean - other systems that are insecure :)

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
> Still not sure we should be allowing people to keep generating weak keys..

This is the legacy API so I would not bother making it incompatible with old tests and similar stuff in this way. 

But yeah in EVP API we should at some point stop allowing weak keys (at least via some configuration). IMO Post 3.0.

**Comment by richsalz** [comment]
> you mean - other systems that are insecure :)

How do you regression test that your firewall rejects weak keys unless you can generate such keys?

**Comment by slontis** [comment]
> > you mean - other systems that are insecure :)
> 
> How do you regression test that your firewall rejects weak keys unless you can generate such keys?

I would hack the code and remove the condition - generate some data and then use that data from then on for your testing.

**Comment by t8m** [comment]
Merged to master. Thank you for the review and other comments.

**Pull request closed without merging**
