### PR TITLE
Add fips self test callback to CRNG output test.

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
@paulidale Just checking that this is the place where the CRNG output test check needs to go..

**Review by paulidale — COMMENTED** [review]
👍

**Review by paulidale — COMMENTED** [review]
I'd have ideally liked to have the CRNGT as a provider RAND filter so it could be plugged in anywhere.  It would simplify testing.

**Comment by slontis** [comment]
ping

**Review by mattcaswell — APPROVED** [review]

**Comment by slontis** [comment]
Thanks. Merged to master.

**Pull request closed without merging**
