### PR TITLE
X509: fix self-signature check for self-issued certs

### LINKED ISSUE #19095: The certificate was misidentified as a self-signed certificate
I created a secondary certificate(server.crt) signed by a CA certificate. In the old version of openssl, it can be correctly verified using command `openssl verify -CAfile ca.crt server.crt`. 
But when I upgrade openssl to the latest version, the signature verification command ends with an error：
```
error 18 at 0 depth lookup: self signed certificate
error server.crt: verification failed
```
By looking at the verification process, I found that this problem was caused by the change in the judgment logic of the self-signed certificate. The code is modified by this [commit](https://github.com/openssl/openssl/commit/e2590c3a162eb118c36b09c2168164283aa099b4?diff=split).

```
    /* latest code */
    if (!X509_NAME_cmp(X509_get_subject_name(x), X509_get_issuer_name(x))) {
        x->ex_flags |= EXFLAG_SI; /* cert is self-issued */
        if (X509_check_akid(x, x->akid) == X509_V_OK /* SKID matches AKID */
                /* .. and the signature alg matches the PUBKEY alg: */
                && check_sig_alg_match(X509_get0_pubkey(x), x) == X509_V_OK)
            x->ex_flags |= EXFLAG_SS; /* indicate self-signed */
    }

    /*  code before modification*/
    if (!X509_NAME_cmp(X509_get_subject_name(x), X509_get_issuer_name(x))) {
        x->ex_flags |= EXFLAG_SI;
        /* If SKID matches AKID also indicate self signed */
        if (X509_check_akid(x, x->akid) == X509_V_OK &&
            !ku_reject(x, KU_KEY_CERT_SIGN))
            x->ex_flags |= EXFLAG_SS;
    }
```

The content of issuer and subject name in my certificate is the same.  There are no akid and skid fields in the certificate, the function `X509_check_akid(x, x->akid) ` return X509_V_OK when `x->akid = NULL`. 
And the certificate is not used for certificate signing, the KU_KEY_CERT_SIGN not set in certificate. 
In older openssl versions, this certificate is correctly recognized as a non-self-signed certificate. But now the certificate is misidentified 
 as a self-signed certificate, causing the verification to fail.

For some reason I can't remake the certificate. Is there any way to modify the openssl code so that the certificate can be recognized correctly.

### PR DESCRIPTION
**Pull request by DDvO**
This fixes #19095 by providing the most accurate certificate self-signature check for self-issued certs that do not have an SKID. 
In this rare case, which can only happen for EE certs and for CA certs not conforming to RFC 5280, we can afford doing the actual self-signature verification on the cert when its data is cached, which is happens once in `x509v3_cache_extensions()`.
**Update:** The effectiveness if this fix is demonstrated by a new test case in  `25-test_req.t` using `self-issued_v1_EE_no_KIDs_signed_by_CA.pem`.

In a separate commit this PR also fixes a subtle bug in the internal `ossl_x509_likely_issued()` function that was revealed after the above change by a failing new test case:
```
apps/openssl verify -partial_chain  \
   -trusted test-runs/test_req/self-issued_v1_CA_no_KIDs.pem \
            test-runs/test_req/self-issued_v1_CA_no_KIDs.pem
```
This is the corner case that its `issuer` and `subject` arguments are (semantically) the same cert and this cert is self-issued and appears self-signed (also according to any included AKID and SKID and signature/key algorithm) but in fact is not self-signed. 
In this case, in combination with the new - and now actually correct - judgement that the cert is not self-signed, the chain building is mislead to form the chain [cert, cert] which then cannot be verified, which leads to incorrect verification failure.
The fix is to use in this case the `ex_flags & EXFLAG_SS` information for the cert(s) in question.

**Update:**
Adding the test case involving `self-issued_v1_CA_no_KIDs.pem`, I discovered a further bug: when the `req`, `x509`, or `ca` apps produce a cert with no extensions and with SKID and/or AKID being explicitly disabled (i.e., with the specifications `subjectKeyIdentifier = none` and/or `authorityKeyIdentifier = none`), the cert version was set to 3 because at first it looked like the cert had extensions, but these were just the intermediate indications that SKID and/or AKID have been disabled.

Moreover, analyzing and fixing thees issues, I noticed that the documentation of `X509_check_issued()` and `X509_check_purpose()` was incomplete.
I fixed this as well, and on this occasion also added the missing documentation of `X509_check_akid()`.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Also we do not have a testcase.

**Comment by DDvO** [comment]
> This is questionable if it is a bug fix or a feature.
> 
> Definitely not something for 1.1.1 and I am hesitant to approve it for 3.0 too.

I'm fine with not backporting this, as it can also be seen as an enhancement (to fix #19095).

> Also we do not have a testcase.

Good point; I'm going to add one.

**Comment by DDvO** [comment]
Adding test cases, I found a further bug, now mentioned in the updated OP above.
Added a fix for it as well, and fixes for incomplete documentation of two functions involved.
Meanwhile I am convinced again that this PR does constitute bug fixes and thus should be backported.

**Comment by DDvO** [comment]
Rebased to fix merge conflicts

**Comment by nhorman** [comment]
Given that this PR has been inactive for a year and requires a rebase, I'm closing for inactivity.  Please reopen if you would like to pick this back up.

**Comment by DDvO** [comment]
> Given that this PR has been inactive for a year and requires a rebase, I'm closing for inactivity. Please reopen if you would like to pick this back up.

@nhorman this PR got closed for no good reason:
while it was waiting very long time for approvals, it accumulated some merge conflicts,
which I was not notified about.

After now rebasing to fix the merge conflicts, 
I tried to reopen it, but GitHub refused this because there was a forced push 👎 
I could have avoided this by re-opening the PR first :-/
So instead I had to open a new PR with the same contents: #28373.

**Pull request closed without merging**
