### PR TITLE
Add a recursive option to 'openssl storeutl'

### PR DESCRIPTION
**Pull request by levitte**
Simply put, any NAME type OSS_STORE_INTO is a new object that can be
looked into, and potentially lead to a whole tree of data to dive
into.  The recursive option allows someone to view the whole tree and
its data in one go.

### CODE REVIEW

**Comment by dot-asm** [comment]
Red crosses for CIs are relevant.

**Comment by levitte** [comment]
Fixed up

**Review by dot-asm — APPROVED** [review]

**Comment by levitte** [comment]
I forgot to document the new option...  please reconfirm

**Review by dot-asm — APPROVED** [review]
Re-confirmed

**Comment by levitte** [comment]
Merged.  fb43ddceda79f0af5fca88b47c794337f207666e and dd8f6edc5ad834fca285f142245a29911f2aecd7

Thank you

**Pull request closed without merging**
