### PR TITLE
Implement Camellia GCM suites (RFC 6367)

### LINKED ISSUE #320: Support for Camellia cipher suites in TLS
Camellia is modern and standardized cipher (by means of ISO, NESSIE and CRYPTREC and IETF), uses higher number of rounds than AES, and no attack able to break full Camellia exists (SFAIK).

Camellia cipher suites for TLS are standardized under [RFC 6367](https://tools.ietf.org/html/rfc6367), including both GCM and CBC modes (with HMAC-SHA-256 and HMAC-SHA-384).

I think they're worth adopting, especially the AEAD modes.

### PR DESCRIPTION
**Pull request by ghedo**
This fixes #320.

The EVP Camellia GCM code is mostly the same as the AES one, so maybe there's an opportunity for some refactoring there.

### CODE REVIEW

**Comment by ghedo** [comment]
Since this is not gonna be merged I'm closing it. I'm tired of keeping this up-to-date for nothing.

**Comment by J0WI** [comment]
D:

**Comment by t8m** [comment]
This could be merged if it was rebased to the current master.

**Comment by mattcaswell** [comment]
I think its a non-trivial rebase due to all the provider changes.

**Comment by t8m** [comment]
Yes, of course.

**Comment by t8m** [comment]
I added this comment to just indicate to @ghedo if he wanted to spend time rebasing it once again that it would be likely merged.

**Pull request closed without merging**
