### PR TITLE
ENCODER & DECODER: Allow en/decoders to have multiple names

### PR DESCRIPTION
**Pull request by levitte**
We had prepared for this a little bit, but apparently not completed it.

### CODE REVIEW

**Comment by levitte** [comment]
This was found thanks to tpm2-software/tpm2-openssl#5, which allowed me to find this little tidbit and wonder why it didn't register:


``` C
static const OSSL_ALGORITHM tpm2_decoders[] = {
    { "DER", "provider=tpm2,input=pem", tpm2_der_decoder_functions },
    { "RSA:rsaEncryption", "provider=tpm2,input=der,structure=TSS2", tpm2_tss_decoder_functions },
    { NULL, NULL, NULL }
};
```

Ref: https://github.com/tpm2-software/tpm2-openssl/blob/618b27c8e8dd595411a1a1c192a1360004b41138/src/tpm2-provider.c#L227-L231

**Review by paulidale — DISMISSED** [review]

**Comment by slontis** [comment]
Approval may be a bit premature here, with lots of tests failures

**Comment by levitte** [comment]
> Approval may be a bit premature here, with lots of tests failures

Hopefully fixed

**Review by paulidale — APPROVED** [review]
Conditional on the remaining CIs being happy.

**Comment by paulidale** [comment]
Merged.

**Pull request closed without merging**
