### PR TITLE
doc: replace "symmetric cipher" phrase in EVP_MD manpages

### PR DESCRIPTION
**Pull request by jengelh**
CLA: trivial

- [x] documentation is added or updated

### CODE REVIEW

**Comment by t8m** [comment]
I am OK with CLA: trivial.

**Review by kaduk — APPROVED** [review]
I am also okay with cla: trivial

**Comment by kaduk** [comment]
I am, however, curious why the bot thinks this is a fips change.

**Comment by t8m** [comment]
> I am, however, curious why the bot thinks this is a fips change.

I think this sometimes happens when things are being merged to master branch during the time the CI is run or something like that.

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
