### PR TITLE
Avoid having ecp_sm2p256-armv8.pl in fips.module.sources

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by levitte** [comment]
I'd argue that SM2 related things in crypto/ec are a bit misplaced...  they would have had a better fit in crypto/sm2, that would have avoided this hack.

**Comment by paulidale** [comment]
@levitte, why?

Germany has custom curves,  What makes SM2 special?

**Comment by levitte** [comment]
> @levitte, why?
> 
> Germany has custom curves, What makes SM2 special?

Why do we have `crypto/sm2`?  After all, it's essentially EC...

**Comment by t8m** [comment]
> Why do we have `crypto/sm2`? After all, it's essentially EC...

The signature (and encryption) algorithm is different from ecdsa but the low-level support used is still the same.

Instead of this hack a different hack could place the assembler .pl file into `crypto/sm2/asm` but the rest of the sm2p256 sources would still be built from crypto/ec as doing otherwise would be too complicated. @levitte Do you think it would be a better hack?

**Comment by t8m** [comment]
Merged to the master branch. Thank you for the reviews.

IMO OK for now as is. It can be redone differently later if needed.

**Pull request closed without merging**
