### PR TITLE
kdfs: FIPS zeroization compliance

### PR DESCRIPTION
**Pull request by xnox**
Zero out salt on cleanup/reset.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

Test exception as this is a pure information leak fix without any impact on any tests.

### CODE REVIEW

**Review by paulidale — COMMENTED** [review]
These should be conditionally included only when the FIPS provider is being compiled.  They are senseless and non-FIPS should not take the performance hit.

As far as I'm aware, the lab OpenSSL is using hasn't insisted these zeroisations be included.  I never was sure of their reason.

Same comment applies to the other zeroization PRs.

**Comment by xnox** [comment]
> These should be conditionally included only when the FIPS provider is being compiled. They are senseless and non-FIPS should not take the performance hit.
> 

Performance hit - or privacy leak? Do we want to leave salt in the memory after the function exits is the question. Salt should be public and non-sensitive, and yet knowing it out of band might help an observer.

> As far as I'm aware, the lab OpenSSL is using hasn't insisted these zeroisations be included. I never was sure of their reason.

I can ask this question to NIST to address it in the implementation guide, such that there are less discrepancies between labs.

Separately multiple vendors that do use other labs clearly do this. Thus having this change upstream would help overall.

Maybe it should be a compile time option? Because I would want to have performance & correctness parity between fips and non-fips builds, including w.r.t. zeroization (despite the performance costs).

> 
> Same comment applies to the other zeroization PRs.

**Comment by paulidale** [comment]
As noted: the salt is public.  There can be no security impact.

It should be conditioned on FIPS_MODULE.

**Comment by xnox** [comment]
See instead https://github.com/openssl/openssl/pull/24355

**Pull request closed without merging**
