### PR TITLE
Backport .gitignore Changes from master

### LINKED ISSUE #23574: Backport .gitignore changes
When the `master` branch adds new entries to `.gitignore` they should be backported to the supported release branches. Otherwise downstream users who do multi-branch development in one git tree will get spurious noise messages.

(And BTW, aren't you behind the names in not changing the name from master to main?)

### PR DESCRIPTION
**Pull request by dgbkn**
CLA: trivial

Fixes #23574

For Branch:openssl-3.2

### CODE REVIEW

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM - okay with trivial

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Agree trivial

**Comment by t8m** [comment]
Merged to the 3.2 branch. Thank you for your contribution.

**Pull request closed without merging**
