### PR TITLE
Simplify and clarify doc/internal/man7/deprecation.pod

### PR DESCRIPTION
**Pull request by levitte**
doc/internal/man7/deprecation.pod was unclear in some areas, and
included general documentation that has no place there.

### CODE REVIEW

**Comment by levitte** [comment]
#13198 sends a message, quite correctly, that deprecation.pod was a bit too involved.  With that message in mind, I looked through it to see what I can do to clarify and simplify, and this is the result.

**Comment by t8m** [comment]
CI failure is relevant

**Comment by levitte** [comment]
> CI failure is relevant

Fixed.  Ping!

**Review by t8m — APPROVED** [review]

**Comment by richsalz** [comment]
I'll point to #13198 as an alternative.

Perhaps more importantly, this doesn't say anything about ```internal/deprecated.h```  Why? If that file isn't to be used any more, then should an issue be opened (for the BETA) that says what should be done?

**Comment by t8m** [comment]
> I'll point to #13198 as an alternative.
> 
> Perhaps more importantly, this doesn't say anything about `internal/deprecated.h` Why? If that file isn't to be used any more, then should an issue be opened (for the BETA) that says what should be done?

It does in the section `Implementations to remain internally`.

**Comment by levitte** [comment]
@richsalz, simply having a look at that header files gives an answer, with this comment:

https://github.com/openssl/openssl/blob/908cf7cefbb2a4c2a8ea1dd4798d1e689db6e3ed/include/internal/deprecated.h#L10-L17

I dunno really what escapes you.  There are two cases for functions that we deprecate:

1.  We plan on removing them, implementation and all.
2.  We plan to remove them from public view but keep them internally.

1 requires that any source that we still use them in for various reason get deprecation warnings turned off.  That's what the `OPENSSL_SUPPRESS_DEPRECATED` does.

2 requires that we not only turn the deprecation warning off, but that the functions also remain internally available when `no-deprecated` is configured.  `#include "internal/deprecated.h"` provides a convenient way to do so, as the technical details are a bit complex and depend on proper ordering of macro definition/removal and header inclusion.

`doc/internal/man7/deprecation.pod` is designed to give instructions on what to do for deprecation, it purposefully doesn't dive too much into the technical details (even less so with this edit).

**Comment by richsalz** [comment]
What escapes me is that this manpage isn't complete, it has a lot of detail but omits an internal header file. You've pointed out that I got it wrong, https://github.com/openssl/openssl/pull/13198#issuecomment-713306250 and explained when/why it's needed https://github.com/openssl/openssl/pull/13198#issuecomment-714919852 

You can say that I'm just not getting it, or you can take this as feedback that a very experienced openssl developer thinks this documentation about deprecation is not complete.

**Comment by levitte** [comment]
> but omits an internal header file

Huh?  @t8m told you already where it's mentioned.

**Comment by richsalz** [comment]
Thank you, I missed it when reading just the diff.

**Comment by levitte** [comment]
Merged

d14e7df8529a3e8fcc2c107369ebcc5abbcccd11 Simplify and clarify doc/internal/man7/deprecation.pod
3b1bfd2160a165a9a1fccc20ab0410e35c435f65 util/find-doc-nits: ignore OSSL_DEPRECATED*, alongside other reserved symbols

**Pull request closed without merging**
