### PR TITLE
Fix SRP client key computation

### PR DESCRIPTION
**Pull request by LeoLogeart**
When computing _K = (B − kg^x)^(a+ux) mod N_,  _(a+ux)_ should not go through _mod N_. 
When _(a+ux) >= N_, the computed key is not the right one.
If a modulo operation is needed on the exponent, only Euler's totient function can be used : _(a+ux) mod phi(N)_. 
However, since we rarely have _(a+ux) >= N_, it is simpler to get rid of the mod operations altogether on the computation of _u*x_ and _a+ux_

### CODE REVIEW

**Comment by kroeckx** [comment]
When trying to follow in RFC5054 I get rather confused.  Could you please document this function better? It's at least confusing that there is a "k" and "K", while K is never mentioned in the rfc.  Maybe that K should get renamed.

I think this function is the client side calculation of the premaster secret, and so should calculate (B - (k * g^x)) ^ (a + (u * x)) % N

The rfc has a test vector in it, but we don't seem to be using that in the test suite and we should probably at least add that one.
I think your change is correct, but it would be nice if you can make the test suite give an error on the old calculation.

**Comment by LeoLogeart** [comment]
In the code, K corresponds to the RFC's "premaster secret". But here it is indeed used as the SRP session key, although in some implementations it is used as a "secret" and the session key is K = H(secret).
So actually it would not be the best idea to rename K by premasterSecret since the function's name is SRP_Calc_client_key.

This issue will almost never be seen with the current implementation because you have to have _a + u*x >= N_. N is at least 1024 bit, "a" is calculated mod N, so "a" has a size inferior or equal to 1024. And u and x are SHA1 digests so only 160 bit numbers. Therefore u*x is of size inferior or equal to 320 bit. So our number "a" of size 1024 inferior to N is not very likely to be only an addition of a 320 bit number away from the value of N.

However, I have been implementing SRP from the openssl code with SHA256. So my u and x are 256 bit long. Which gives u*x a size of 512 bits in my case. That is why I have noticed this issue.

I added a test in the test suite (srptest.c) that failed with the code before the fix, and passes after the fix. For this test, I have created a new 256 bit long N in the constants. Therefore in this test we always have _a + u*x > N_ since u*x is still 320 bit long.

**Comment by kroeckx** [comment]
It looks like a bad idea to add a short one to the list of knowngN, people might start using that.  I suggest you modify the test so it can use that N instead.

**Comment by LeoLogeart** [comment]
You are right.
Sadly I can't seem to be able to modify the N cleanly from within the test. So I removed the small N and the test...

**Comment by kroeckx** [comment]
+1

**Comment by mattcaswell** [comment]
+1

**Comment by kroeckx** [comment]
merged

**Pull request closed without merging**
