### PR TITLE
genpkey: -quiet doesn't take an argument

### LINKED ISSUE #16238: Problems with genpkey
From openssl-users:

Should these be posted here or as github issues?  (May be user error)

1. `openssl genpkey -algorithm rsa -outform der -out key.der -quiet`
  returns:
    `genpkey: Option -quiet needs a value`
  But the docs don't indicate that a value is needed.
2. `openssl genpkey -algorithm rsa -outform der -out key.der -text`
    Docs say that the unencrypted key should be printed, but it isn't.
3. `openssl genpkey .... -cipher des3`
  returns:
    `genpkey: Use -help for summary.`
  I tried other values for -cipher but none worked
4. `-aes-128-cbc` works but is not documented

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #16238

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
This is a behaviour change for 3.0 and 1.1.1.
What it doesn't currently is wrong but could be surprising if it changed.

**Comment by t8m** [comment]
Alternatively, just modify the help text and the manual page to `-quiet <ignored> Do not output status while generating keys (For backwards compatibility it takes an argument which is ignored.)`

**Comment by paulidale** [comment]
I'd prefer to not continue the error.  That `-quiet` takes an argument is a long standing bug.  We should fix it not document it.

Although I'd prefer fixing this now, to avoid breaking things, I'm fine with fixing this post 3.0.

**Review by t-j-h — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.

**Pull request closed without merging**
