### PR TITLE
Avoid potential doublefree on dh object assigned to EVP_PKEY

### PR DESCRIPTION
**Pull request by t8m**
Fixes regression from 7844f3c784bfc93c9b94ae5a4082f9d01e82e0af

### CODE REVIEW

**Comment by t8m** [comment]
Marking also as urgent as this fixes build regression on 1.1.1 branch.

**Review by mattcaswell — APPROVED** [review]
Approved. Is this causing test failures in 1.1.1?

**Comment by t8m** [comment]
Yes, just in the extended tests. https://github.com/openssl/openssl/runs/1264870852

**Comment by t8m** [comment]
Merged to 1.1.1.

**Pull request closed without merging**
