### PR TITLE
Add util/check-doc-links.pl, to be used to check referenses in manuals

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [x] CLA is signed

### CODE REVIEW

**Comment by levitte** [comment]
We have some horrors to clear...

**Comment by levitte** [comment]
Note: the referense fixes don't fix everything.  It's obvious that some of refer to manuals-to-be.

**Comment by richsalz** [comment]
should that be part of util/find-doc-nits instead?
and should find-doc-nits be a top-level make target?

**Review by richsalz — APPROVED** [review]
yeah!!!

**Comment by levitte** [comment]
> should that be part of util/find-doc-nits instead?

Possibly, been thinking about it.  Let me play around for a bit and I'll eventually get to merging them together.

> and should find-doc-nits be a top-level make target?

It's going to be *terribly* annoying until we get around to writing the missing manuals ;-)

**Comment by levitte** [comment]
Either way, I merged this now.

**Pull request closed without merging**
