### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

CLA: trivial

### CODE REVIEW

**Comment by t8m** [comment]
This would be acceptable with CLA: trivial. Could you please amend the commit message to include `CLA: trivial` on a separate line in the commit message body?

**Comment by omahs** [comment]
@t8m just added the mention :)

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
@omahs you need to amend the commit message not just the PR text. Use `git commit --amend` and `git push --force` for that.

**Review by kroeckx — APPROVED** [review]

**Comment by t8m** [comment]
@hlandau assuming you're OK with CLA: trivial.

**Review by t8m — APPROVED** [review]
OK with CLA: trivial.

**Comment by t8m** [comment]
I've amended the commit message to contain the CLA: trivial when merging the PR.
Merged to master branch. Thank you.

**Pull request closed without merging**
