### PR TITLE
Fixed typo in ssl_lib.c

### PR DESCRIPTION
**Pull request by eltociear**
orignal -> original

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by kaduk — APPROVED** [review]
This seems like the epitome of what "CLA: trivial" is for.
@eltociear if you agree that this change is not copyrightable, please (preferred) force-push an updated commit with a separate line in the commit message containing "CLA: trivial", or  (less-preferred) reply here to state so.

**Review by paulidale — APPROVED** [review]
Agreed that this is trivia..

**Comment by eltociear** [comment]
@kaduk  Thank you for your message!
I have added "CLA: trivial"  commit message and force pushed it.

**Comment by kaduk** [comment]
@eltociear Thank you!  There is a 24-hour waiting period after the review criteria are met, so I will probably be merging this in the next day or so.

**Comment by kaduk** [comment]
Pushed to master and 1.1.1, so closing.
Thanks for the submission (and quick turnaround on the commit-message update)!

**Comment by eltociear** [comment]
@kaduk Thank you for your response!

**Pull request closed without merging**
