### PR TITLE
WIP: Add AES-SIV

### PR DESCRIPTION
**Pull request by richsalz**
Based on code written by Daniel Franke.
Still have to implement the EVP interface.

Would appreciate any comments.  Once I finish the EVP stuff, should I not make the other functions public?

### CODE REVIEW

**Comment by snhenson** [comment]
We want to encourage the use of the EVP interface. The lower level interfaces have all sorts of restrictions (such as not being able to redirect them to an ENGINE) and we want to discourage their use. IMHO we should not be adding any new public low level APIs if it can be avoided. We have to retain the existing ones for compatibility of course.

**Comment by richsalz** [comment]
Okay, so hook up the EVP (adding the CTRL functions) and then remove the AES_SIV functions from public view :)  makes sense to me.

**Comment by snhenson** [comment]
Some things can be simplified as a result: some of the structures will be internal only and don't have to be opaque any more. Testing can also be via evp_test.c

**Comment by kaduk** [comment]
How is this different from #3540 ?

**Comment by snhenson** [comment]
Hmm.. I wasn't aware of that. That looks like a more complete version.

**Comment by richsalz** [comment]
yeah, dunh.

**Pull request closed without merging**
