### PR TITLE
Fixes #25917

### LINKED ISSUE #25917: Should jitter RNG use salt for nonce generation?
In 

https://github.com/openssl/openssl/blob/012353bdf21b98def920ac317b94c4a9ed501b79/crypto/rand/prov_seed.c#L114

salt is being passed in.

But in

https://github.com/openssl/openssl/blob/012353bdf21b98def920ac317b94c4a9ed501b79/providers/implementations/rands/seed_src_jitter.c#L170

addin is not used at all.

Should it be added to the pool at least the same way as it is done here in this non-EVP get_nonce implementation?

https://github.com/openssl/openssl/blob/012353bdf21b98def920ac317b94c4a9ed501b79/crypto/rand/prov_seed.c#L91

### PR DESCRIPTION
**Pull request by jsondevers**
add handling for adin in jitter rng (issue #25917)

### CODE REVIEW

**Review by Sashan — APPROVED** [review]
looks good to me.

@openssl/committers: can this change be accepted as CLA-TRIVIAL?

**Comment by t8m** [comment]
IMO this is outside of what is acceptable with CLA: trivial. Could you please sign a CLA? https://openssl-library.org/policies/cla/index.html

**Comment by t8m** [comment]
Could you please amend the commit message to remove `CLA: trivial`?

**Review by t8m — APPROVED** [review]

**Comment by jsondevers** [comment]
I've updated the commit message to replace author with my email address but see the cla-check is still looking for the previous name

**Comment by t8m** [comment]
I still see:
```
Author: jsondevers <jasondevers@Js-M1.local>
Date:   Fri Nov 15 11:12:58 2024 -0800
```
on the commit. Did you use `--reset-author` option?

**Comment by jsondevers** [comment]
Was missing that, thanks!

**Review by shahsb — APPROVED** [review]
LGTM.

**Comment by t8m** [comment]
Merged to the master branch with a tweaked commit message. Thank you for your contribution.

**Comment by t8m** [comment]
This was unfortunately seriously wrong with quite big impact. Fortunately it was catched in CI. Fix in https://github.com/openssl/openssl/pull/26112

**Comment by jsondevers** [comment]
Apologizes for the mistake, thank you for letting me know!
Is there a certain test it was failing in CI? I wasn't able to find where it was caught.
I took a look at the fix and see that to add in the additional input, it was xor'd into the output, similar to that of `jitter_get_seed()`,

**Comment by t8m** [comment]
https://github.com/openssl/openssl/actions/runs/12152102840/job/33887870809 - this build failed

**Pull request closed without merging**
