### PR TITLE
Streamline/Rationalize HPE NonStop Configuration

### LINKED ISSUE #12858: Streamline/Rationalize HPE NonStop Configuration
The configuration for NonStop (`50-nonstop.conf`) needs the following streamlining:

- cleaning up
- removing redundant flag usage
- ensuring consistency between configurations
- reconciling code with a new `OPENSSL_SYS_TANDEM` configuration define.

This enhancement is a followup to issue #5087 and pull request #12800 and applies to OpenSSL version 3.0.0 and HPNS platforms TNS/E (Itanium RVU J06.23.1) and TNS/X (x86 RVU L19.08). **Note:** RVU refers to the platform release version.

### PR DESCRIPTION
**Pull request by levitte**
Using inheritance, the NonStop configuration entries become quite small, and we don't copy values all over the place.

Fixes #12858

### CODE REVIEW

**Comment by levitte** [comment]
@rsbecker, it would be nice if you could test this and confirm that my guesses are correct enough.

**Comment by rsbeckerca** [comment]
> 
> 
> @rsbecker, it would be nice if you could test this and confirm that my guesses are correct enough.

Thanks. I'm going to give it a whirl.

**Comment by rsbeckerca** [comment]
> 
> 
> @rsbecker, it would be nice if you could test this and confirm that my guesses are correct enough.

@levitte I think something is not right in the Makefile. I'm getting:

```
c99  -I. -Iinclude -Iapps/include  ARRAY(0x81724c0)  -DOPENSSL_PIC -DOPENSSLDIR=...
```
which kills the shell pretty fast. This is coming from this block in the generated Makefile:
```
CNF_CFLAGS=ARRAY(0x81724c0)
CNF_CXXFLAGS=
CNF_LDFLAGS=ARRAY(0x8171e30)
CNF_EX_LIBS=ARRAY(0x8171d50)
```

**Comment by rsbeckerca** [comment]
Note also that this change impacts PR #12928 and PR #12923. I can put together a PR to handle that once this is resolved.

**Comment by levitte** [comment]
Okie, I'll have a look at that.

**Comment by rsbeckerca** [comment]
> 
> 
> Okie, I'll have a look at that.

Thanks. Also note that our build is broken (reported #12937) by commit 6600baa9bb6e59be91692791a6251c172a099a65, so that's not helping.

**Comment by rsbeckerca** [comment]
> 
> 
> > Okie, I'll have a look at that.
> 
> Thanks. Also note that our build is broken (reported #12937) by commit [6600baa](https://github.com/openssl/openssl/commit/6600baa9bb6e59be91692791a6251c172a099a65), so that's not helping.

It might not be that commit, specifically, but the build was fine at commit 28833f1465.

**Comment by levitte** [comment]
I've fixed so there are no more ARRAY in the resulting Makefile.

**Comment by rsbeckerca** [comment]
> 
> 
> I've fixed so there are no more ARRAY in the resulting Makefile.

Build is proceeding. I'll report back. It probably will be blocked by #12937

**Comment by rsbeckerca** [comment]
I'm not seeing the `OPENSSL_SYS_TANDEM` define. A sample of what is being generated is, after configuring with `nonstop-nse`:

```
c99  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -g -O0 -Wextensions -Wnowarn=203,220,272,734,770,1506 -Wbuild_neutral_library -Wverbose -Wtarget=tns/e -Wsystype=oss -Wilp32  -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local-ssl3.0/ssl\"" -DENGINESDIR="\"/usr/local-ssl3.0/lib/engines-3\"" -DMODULESDIR="\"/usr/local-ssl3.0/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_VPROC= -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED=1 -D_TANDEM_SOURCE -DB_ENDIAN -D_TANDEM_ARCH=2 -DOPENSSL_TANDEM_FLOSS -D__TANDEM -I/usr/local/include   -c -o crypto/asn1/libcrypto-lib-f_string.o crypto/asn1/f_string.c
```

**Comment by levitte** [comment]
Most config macros are collected in `include/openssl/configuration.h` in the build tree.  You'll find it there.

**Comment by rsbeckerca** [comment]
> 
> 
> Most config macros are collected in `include/openssl/configuration.h` in the build tree. You'll find it there.

My grep didn't find it. Tried again in `configuration.h`:
```
# ifndef OPENSSL_SYS_tandem
#  define OPENSSL_SYS_tandem 1
```

**Comment by levitte** [comment]
Uhmmm...  so what's the difference between `configuration.h` and `configuration.h`?

**Comment by rsbeckerca** [comment]
> 
> 
> Uhmmm... so what's the difference between `configuration.h` and `configuration.h`?

The issue is that tandem should be uppercase, right? like `OPENSSL_SYS_TANDEM` not `OPENSSL_SYS_tandem`. I think.

**Comment by rsbeckerca** [comment]
@levitte would setting `sys_id => 'TANDEM',` fix this or would this be something the perl scripts need to handle (upshifting).

**Comment by rsbeckerca** [comment]
> 
> 
> @levitte would setting `sys_id => 'TANDEM',` fix this or would this be something the perl scripts need to handle (upshifting).

With this change, the build is proceeding nicely so far. I still need to work around the libcrypto.so link issue (#12797), but that's a separate issue. There are two pull requests (#12928, #12923) that will either need to be modified, updated, or have a new PR issued once this is merged. I can handle that or those two can go first and we can include the changes in this PR.

**Comment by levitte** [comment]
> @levitte would setting `sys_id => 'TANDEM',` fix this or would this be something the perl scripts need to handle (upshifting).

Yes, that's the answer of course...
(I haven't had to deal with new platforms in ages, I've obviously forgotten some details)

**Comment by rsbeckerca** [comment]
Argh. I posted results in the wrong PR. OK, here goes.

- `-Wshared` is needed for DLL links and is not being picked up.
- `-Weld="-export_all"` and/or `-Wxld="-export_all"`, depending on the platform, are needed for DLL links.

I turned off `dynamic-engine` so that I don't have to fix this for every DLL in the universe ;). The build is continuing.

**Comment by rsbeckerca** [comment]
@levitte  Something else, really just a nit: The `__TANDEM` define is automatically generated by the compilers. Is it actually needed in the configuration?

Also, just an FYI, while there are still a few MIPS machines out there, they are completely out of support and we are not building/testing any of those.

**Comment by rsbeckerca** [comment]
Would this be the fix for my DLL issue, as a sample, adding the `shared_ldflag`?
```
    'nonstop-archenv-x86_64-oss' => {
        template         => 1,
        defines          => ['_TANDEM_ARCH=3'],
        cflags           => '-Wtarget=tns/x -Wsystype=oss',
        lflags           => '-Wxld="-set systype oss"',
        shared_ldflag    => '-Wshared -Wxld="-export_all"',
        shared_target    => 'nonstop-x86-oss',
    },
```

**Comment by rsbeckerca** [comment]
FYI: I have tested the above and it seems to make the difference.

**Comment by rsbeckerca** [comment]
The build finally completed. The following updates:
```
     # Itanium + oss:
     'nonstop-archenv-itanium-oss' => {
         template         => 1,
         defines          => ['_TANDEM_ARCH=2'],
         cflags           => '-Wtarget=tns/e -Wsystype=oss',
         lflags           => '-Weld="-set systype oss"',
+        shared_ldflag    => '-Wshared -Weld="-export_all"',
         shared_target    => 'nonstop-itanium-oss',
     },
     # x86_64 + oss:
     'nonstop-archenv-x86_64-oss' => {
         template         => 1,
         defines          => ['_TANDEM_ARCH=3'],
         cflags           => '-Wtarget=tns/x -Wsystype=oss',
         lflags           => '-Wxld="-set systype oss"',
+        shared_ldflag    => '-Wshared -Wxld="-export_all"',
         shared_target    => 'nonstop-x86-oss',
     },
```
and we should be good to merge.

**Comment by levitte** [comment]
Hmmm, the `shared_target` was supposed to refer to entries in `Conffigurations/shared-info.pl` (I just misspelt them), but you're right, the way it currently looks, that's an unnecessary indirection.

**Comment by levitte** [comment]
> Also, just an FYI, while there are still a few MIPS machines out there, they are completely out of support and we are not building/testing any of those.

Would you rather I simply removed those templates, then?

**Comment by levitte** [comment]
> @levitte  Something else, really just a nit: The `__TANDEM` define is automatically generated by the compilers. Is it actually needed in the configuration?

Well, no.  If it's always generated automatically, then there's no need for us to add it.

**Comment by levitte** [comment]
Okie, I've made changes as requested.  Considering what you say about multi-hour builds, I suppose another test will take another day :confounded:

**Comment by levitte** [comment]
Considering the positive feedback, I feel confident enough to take this PR out of WIP

**Comment by rsbeckerca** [comment]
> 
> 
> Okie, I've made changes as requested. Considering what you say about multi-hour builds, I suppose another test will take another day 😖

That and I have to get 1.1.1h out the door.

**Comment by rsbeckerca** [comment]
We have 1.1.1h ported at tested (the unthreaded version). The 3.0.0 at 8e3a64fdb6 with your changes looks much cleaner. Both .so files built properly (still subject to #12797). Thank you. This can probably move to approved - I don't think my approval matters, but I've given it.

**Review by rsbeckerca — APPROVED** [review]
This change configures and sets build arguments correctly on NonStop platforms.

**Review by rsbeckerca — APPROVED** [review]

**Comment by levitte** [comment]
@openssl/committers, this can go to a final review

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Merged

c60330cb0efcde5fea80113c110499d352b2abca Configuration: Streamline NonStop entries
37fe90ad17fcaaeb33d01c660ed1c12db723d833 Configure: Show 'enable' and 'disable' config attributes
cdb5129e5c5fd8ad678c5efb1e87c91595d907b4 Use OPENSSL_SYS_TANDEM instead of OPENSSL_SYSNAME_TANDEM

**Pull request closed without merging**
