### PR TITLE
x86_64: Always generate .note.gnu.property section for ELF outputs

### PR DESCRIPTION
**Pull request by hjl-tools**
This reverts commit b2b43d1b698235ee674e588c224db38d9b78d1ea.

This patch is incorrect since .note.gnu.property section is ELF only.
When endbranch is used, .note.gnu.property section is generated for
all targets.  On MacOS, we got

https://travis-ci.org/openssl/openssl/jobs/644331421?utm_medium=notification&utm
_source=github_status

crypto/aes/aes-x86_64.s:2641:11: error: mach-o section specifier requires a segm
ent whose length is between 1 and 16 characters
.section ".note.gnu.property", "a"

### CODE REVIEW

**Comment by hjl-tools** [comment]
@levitte Adding Richard Levitte

**Comment by hjl-tools** [comment]
We should always generate .note.gnu.property section in x86_64 assembly
codes for ELF outputs to mark Intel CET support since all input files
must be marked with Intel CET support in order for linker to mark output
with Intel CET support.  Also .note.gnu.property section in x32 should
be aligned to 4 bytes, not 8 bytes and .p2align should be used
consistently.

Verified with

$ CC="gcc -Wl,-z,cet-report=error" ./Configure shared linux-x86_64 -fcf-protecti
on
$ make
$ make test

and

$ CC="gcc -mx32 -Wl,-z,cet-report=error" ./Configure shared linux-x32 -fcf-prote
ction
$ make
$ make test # <<< 90-test_sslapi.t failed because 8-byte pointer size.

Fix #10896

**Comment by levitte** [comment]
I wonder, what happens if you build OpenSSL *without* `-fcf-protection`?  I assume that with `-Wl,-z,cet-report=error`, it will go through silently, but are there subtleties we need to be aware of with a mixture of object files that have the added GNU properties and object files that don't?

**Comment by hjl-tools** [comment]
> I wonder, what happens if you build OpenSSL _without_ `-fcf-protection`? I assume that without `-Wl,-z,cet-report=error`, it will go through silently, but are there subtleties we need to be aware of with a mixture of object files that have the added GNU properties and object files that don't?

```
$ CC="gcc -Wl,-z,cet-report=error" ./Configure shared linux-x86_64
...
$ make
...
gcc -Wl,-z,cet-report=error -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -Wl,-znodelete -shared -Wl,-Bsymbolic   -Wl,-soname=libcrypto.so.3 \
        -o libcrypto.so.3 -Wl,--version-script=libcrypto.ld \
        crypto/aes/libcrypto-shlib-aes-x86_64.o \
        crypto/aes/libcrypto-shlib-aes_cfb.o \
        crypto/aes/libcrypto-shlib-aes_ecb.o \
        crypto/aes/libcrypto-shlib-aes_ige.o \
```        providers/implementations/asymciphers/libcrypto-shlib-rsa_enc.o \
        providers/libcrypto-shlib-defltprov.o \
        providers/libimplementations.a providers/libcommon.a providers/libnonfips.a  -ldl -pthread
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aes-x86_64.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aes_cfb.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aes_ecb.o: error: missing IBT and SHSTK properties
/usr/local/bin/ld: crypto/aes/libcrypto-shlib-aes_ige.o: error: missing IBT and SHSTK properties
...
```

Mixing object files with and without GNU property is OK.   Older linkers treat them like
input files with just another NOTE section.  Newer linkers will drop GNU property in
output.

**Comment by t8m** [comment]
Pushed to master as 51994e5

**Pull request closed without merging**
