### PR TITLE
Add the correct enum value for DSA public key serialization

### PR DESCRIPTION
**Pull request by jon-oracle**
I noticed that an enum was missing from the DSA serializer code and added in the correct one.

### CODE REVIEW

**Review by slontis — APPROVED** [review]
Thanks for fixing this.

**Review by mattcaswell — APPROVED** [review]

**Comment by slontis** [comment]
Yep that didnt look like a public key :)

**Comment by slontis** [comment]
reconfirmed..

**Comment by slontis** [comment]
@mattcaswell can you reconfirm?

**Comment by jon-oracle** [comment]
Merged changes from master which seems to have worked. Main change has moved from serializer to encode_decode.

**Review by slontis — APPROVED** [review]
Reconfirmed

**Comment by jon-oracle** [comment]
Ping

**Comment by slontis** [comment]
Thanks for the reminder.. Merged to master.

**Comment by RLlane2126** [comment]
approve

**Comment by slontis** [comment]
Just updated the label on this - it has already been merged..

**Pull request closed without merging**
