### PR TITLE
EVP: make it possible to init EVP_PKEY_CTX with provided EVP_PKEY

### PR DESCRIPTION
**Pull request by levitte**
The case when EVP_PKEY_CTX_new() is called with a provided EVP_PKEY
(no legacy data) wasn't handled properly.

### CODE REVIEW

**Comment by levitte** [comment]
This is extracted from #10289.
@slontis, I believe this is of interest to you.

**Comment by levitte** [comment]
Travis issue not relevant

**Review by paulidale — APPROVED** [review]
No idea about the TODO question.

**Review by slontis — COMMENTED** [review]
Seems to work.. Thanks.

**Comment by slontis** [comment]
Travis failure is a timeout that seems to be happening a lot now.

**Comment by levitte** [comment]
Merged.

982efd7765f42ba0329e5db6e3434b072d90842c EVP: make it possible to init EVP_PKEY_CTX with provided EVP_PKEY

**Pull request closed without merging**
