### PR TITLE
Update troublesome copyright years of auto-generated files to 2022

### PR DESCRIPTION
**Pull request by DDvO**
(Basically) same procedure as last year (#13764) or every(?) year.
This is just a quick workaround for the still unsolved New Year issue #13765.

Please approve ASAP since the issue causes needless CI failures for all new/updated PRs.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
I agree with it being urgent.

**Comment by DDvO** [comment]
Thanks @t8m for the immediate treatment - merged.

**Comment by DDvO** [comment]
Ah, and the same will surely be needed for `openssl-3.0` as well.
Shall I cherry-pick this there?

**Comment by t8m** [comment]
> Ah, and the same will surely be needed for `openssl-3.0` as well.
> Shall I cherry-pick this there?

Would the patch be really the same there? If so, then OK.

**Comment by DDvO** [comment]
> > Ah, and the same will surely be needed for `openssl-3.0` as well.
> > Shall I cherry-pick this there?
>
> Would the patch be really the same there? If so, then OK.

It is the same because between 3.0 and the master the set of affected files did not change.
So backported/cherry-picked the workaround to 3.0.

**Comment by DDvO** [comment]
Which reminds me that we might have a related issue also with 1.1.1,
but there certainly some adaptations would be needed,
so we may leave that open until someone actually hits the issue there,
or would it be better if I proactively open a PR for 1.1.1?

**Comment by DDvO** [comment]
I meanwhile think it's better to do the backport already now - see #17401.

**Pull request closed without merging**
