### PR TITLE
Mv manpages

### PR DESCRIPTION
**Pull request by richsalz**
This moves the manpages in the doc directory into standard manX directories.
Once merged, bin/mk-manpages in www repo will need to be updated.

### CODE REVIEW

**Comment by levitte** [comment]
Considering you have one commit starting with `WIP:`, perhaps this PR should be marked accordingly?

**Comment by richsalz** [comment]
i'll merge/squash and remove the WIP.  it's not a WIP any more.

**Comment by levitte** [comment]
Add this patch as well, that covers docs production on Windows and VMS:

``` diff
diff --git a/util/process_docs.pl b/util/process_docs.pl
index 8b8de81..2c54f02 100644
--- a/util/process_docs.pl
+++ b/util/process_docs.pl
@@ -28,26 +28,23 @@ use OpenSSL::Util::Pod;
 my %options = ();
 GetOptions(\%options,
            'sourcedir=s',       # Source directory
-           'subdir=s%',         # Subdirectories to look through,
+           'section=i@',        # Subdirectories to look through,
                                 # with associated section numbers
            'destdir=s',         # Destination directory
            #'in=s@',             # Explicit files to process (ignores sourcedir)
-           #'section=i',         # Default section used for --in files
            'type=s',            # The result type, 'man' or 'html'
            'remove',            # To remove files rather than writing them
            'dry-run|n',         # Only output file names on STDOUT
            'debug|D+',
           );
 
-unless ($options{subdir}) {
-    $options{subdir} = { apps   => '1',
-                         crypto => '3',
-                         ssl    => '3' };
+unless ($options{section}) {
+    $options{section} = [ 1, 3, 5, 7 ];
 }
 unless ($options{sourcedir}) {
     $options{sourcedir} = catdir($config{sourcedir}, "doc");
 }
-pod2usage(1) unless ( defined $options{subdir}
+pod2usage(1) unless ( defined $options{section}
                       && defined $options{sourcedir}
                       && defined $options{destdir}
                       && defined $options{type}
@@ -62,8 +59,8 @@ if ($options{debug}) {
         if defined $options{destdir};
     print STDERR "DEBUG:   --type      = $options{type}\n"
         if defined $options{type};
-    foreach (keys %{$options{subdir}}) {
-        print STDERR "DEBUG:   --subdir    = $_=$options{subdir}->{$_}\n";
+    foreach (sort @{$options{section}}) {
+        print STDERR "DEBUG:   --section   = $_\n";
     }
     print STDERR "DEBUG:   --remove    = $options{remove}\n"
         if defined $options{remove};
@@ -75,8 +72,8 @@ if ($options{debug}) {
 
 my $symlink_exists = eval { symlink("",""); 1 };
 
-foreach my $subdir (keys %{$options{subdir}}) {
-    my $section = $options{subdir}->{$subdir};
+foreach my $section (sort @{$options{section}}) {
+    my $subdir = "man$section";
     my $podsourcedir = catfile($options{sourcedir}, $subdir);
     my $podglob = catfile($podsourcedir, "*.pod");
 
```

**Comment by richsalz** [comment]
great, merged your diff. thanks!

**Comment by richsalz** [comment]
rebased and push -f'd

**Comment by levitte** [comment]
Grand.  Now, we wait for the CIs to be done.

**Comment by levitte** [comment]
Darnit...  with the GH hickup, it seems we don't get an appveyor build on this unless something new is pushed...  Meh...

**Comment by levitte** [comment]
I just tested on VMS, works beautifully.

Re the commits, I assume you're going to squash them all into one?

**Comment by richsalz** [comment]
Yes, squash into one.
Need to prototype the web mk-manpages change first I think, so that the website still works....

**Comment by richsalz** [comment]
Just did a force update, changed the commit message.

**Comment by richsalz** [comment]
done, and did a quick hack for the website.  thanks!

**Pull request closed without merging**
