### PR TITLE
VMS: two small fixes

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
Marked urgent because of current build error:

https://ci.buildbot.openssl.org/#/builders/40/builds/186/steps/7/logs/stdio

**Comment by levitte** [comment]
Also covering <https://ci.buildbot.openssl.org/#/builders/2/builds/333/steps/7/logs/stdio>

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
Agree urgent

**Review by hlandau — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Regarding "urgent"....repo is currently frozen!

**Comment by levitte** [comment]
> Regarding "urgent"....repo is currently frozen!

Yeah, I didn't think of that when I submitted this
(and I still think it's unwise to freeze the master branch)

**Review by t8m — APPROVED** [review]
I agree it is urgent and I'll push it into the master branch.

**Comment by t8m** [comment]
Merged to master branch. Thank you.

**Pull request closed without merging**
