### PR TITLE
EVP_PKEY_ASN1_METHOD: add functions to set siginf_set and pkey_check methods

### PR DESCRIPTION
**Pull request by levitte**
-----

Related to the discussion in #3894

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
how about a test case ;-)

**Comment by bernd-edlinger** [comment]
Interesting, but I fail to see how `EVP_PKEY_asn1_set_siginf` can have an effect,
because `siginf_set` is only ever used here:

crypto/x509/x509_set.c:
```
     if (mdnid == NID_undef) {
        /* If we have one, use a custom handler for this algorithm */
        const EVP_PKEY_ASN1_METHOD *ameth = EVP_PKEY_asn1_find(NULL, pknid);
        if (ameth == NULL || ameth->siginf_set == NULL
                || ameth->siginf_set(siginf, alg, sig) == 0)
            return;
        siginf->flags |= X509_SIG_INFO_VALID;
        return;
    }
```

**Comment by levitte** [comment]
> how about a test case ;-)

Ideally, that should be a complete test of the API around `EVP_PKEY_ASN1_METHOD`.  That will need some time.  We might want to make an engine that defines these sort of things and tests them...  that will take some time to make.

> Interesting, but I fail to see how `EVP_PKEY_asn1_set_siginf` can have an effect, because `siginf_set` is only ever used here:

I'm not sure I understand what the issue is with that.  But hey, perhaps a study of how they are already used with [EC X25519 keys](https://github.com/openssl/openssl/blob/master/crypto/ec/ecx_meth.c#L375-L381) and [RSA keys](https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_ameth.c#L795-L828) might help...

-----

The point here is that we obviously want to support implementation of `EVP_PKEY_ASN1_METHOD`s, and the API to set `siginf_set` and `pkey_check` were lacking.

**Comment by mattcaswell** [comment]
Documentation?

**Comment by levitte** [comment]
I have a branch where I'm working on documentation. Currently, `EVP_PKEY_ASN1_METHOD` is entirely undocumented, so it's a bigger job than just these two functions, and deserves its own PR

**Comment by levitte** [comment]
Documentation is happening in #4596...  note that I'm including the functions I'm adding here in that documentation.

**Comment by levitte** [comment]
Ping?

**Review by bernd-edlinger — APPROVED** [review]

**Comment by levitte** [comment]
Squashed and merged.  5e006082199e9a0f37ba35116ff217bc643dd317

Thank you!

**Pull request closed without merging**
