### PR TITLE
Add cipher alias for TLSv1.3 ciphers

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [X] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by davidben** [comment]
Do note the discussion in issue #2276. In the past, these version aliases have been hugely problematic (see the numerous folks who accidentally required TLS 1.2 when they meant to disable SSL 3.0).

**Comment by kroeckx** [comment]
And I don't think it's a good idea to add to the confusion.

**Comment by tmshort** [comment]
So, this follows consistency with other ciphers, but, yeah, I can see the issue of `!SSLv3.0`, which itself might be considered a bug. What if `!<version>` removed ciphers up-to that level, whereas `<version>` added ciphers starting at that level. That would certainly fix the `!SSLv3.0` and possibly make behavior a little more consistent? 

However, I'm not sure that's a sufficient solution...

**Comment by tmshort** [comment]
@davidben, commit fe55c4a removed the ECDHE ciphers from SSLv3, such that !SSLv3 no longer removes all non-TLSv1.2 ciphers, so TLSv1[.1] would work again, albeit with only ECDHE ciphers.

**Comment by davidben** [comment]
I don't think that's what someone who wrote `!SSLv3` would have been trying to do either. :-)

**Comment by tmshort** [comment]
For consistency with other keywords, adding `TLSv1.3` makes sense.

I think the issue with`!SSLv3` is a user error that should be updated in the documentation, and not necessarily a reason to not have `TLSv1.3`.

Unless we want to change the definition of `!` to mean only ciphers in that particular version of of the protocol, which for `SSLv3` wouldn't do much because `TLSv1` uses the same sets of ciphers.

Other than explicitly adding all TLSv1.3 ciphers, is there a recommendation on how to do this?

**Comment by richsalz** [comment]
If the protocol decision is orthogonal to the ciphersuite decision, and if we don't provide a control for TLS 1.3 ciphers, then that might be cleaner.

**Comment by tmshort** [comment]
That warning is already there:

> Note: these cipher strings **do not** change the negotiated version of SSL or TLS, they only affect the list of available cipher suites.

**Comment by tmshort** [comment]
Rebased.

**Comment by tmshort** [comment]
Since there seems to be no interest in this PR, I'll close it to tidy up the list.

**Pull request closed without merging**
