### PR TITLE
util/mkdef.pl: Trust configdata.pm

### PR DESCRIPTION
**Pull request by levitte**
This script kept its own database of disablable algorithms, which is a
maintenance problem, as it's not always perfectly in sync with what
Configure does.  However, we do have all the data in configdata.pm,
produced by Configure, so let's use that instead.

Also, make sure to parse the *err.h header files, as they contain
function declarations that might not be present elsewhere.

### CODE REVIEW

**Comment by levitte** [comment]
This solves a maintenance problem that became visible while reviewing #5150

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
I found a bug, indicated byt Travis and Appveyor...  please reconfirm

**Review by mattcaswell — APPROVED** [review]

**Comment by richsalz** [comment]
The *err.h files should really only have the define's.  I don't like that we're now scanning generated files.  Not a big concern, but please re-think that.

**Comment by levitte** [comment]
The *err.h files declare `ERR_load_TYPE_strings()`, and #5150 makes sure they are *only* declared in the *err.h files.  That makes them eligile for parsing, and since that function is generated as well, I don't see a way to get around this.

So I'm sorry, but I'm not rethinking this.  In the end, this reduces maintenance hassle.

**Comment by richsalz** [comment]
Since the error-loading function is not really related to the defines, perhaps it should go the other way.

But I don't feel strongly about it to stop this.  I'll shed a tear and move on.
;)

**Comment by levitte** [comment]
Point is that they are both generated jointly.  Trying to maintain declarations *manually* for *generated* functions is another maintenance problem waiting to happen (I've personally developed an allergy to that kind of problem)

**Comment by levitte** [comment]
And, thank you for not blocking

**Comment by levitte** [comment]
Merged.  54f3b7d2f5a313e5c702f75ee030f8a08e6bf6aa (it seems like the `make update` thing was already done...)

**Comment by mattcaswell** [comment]
This PR seems to have broken the `no-deprecated` config option. Ever since commit 54f3b7d2f5a building with `no-deprecated` fails the symbol presence test.

**Comment by levitte** [comment]
Okie, I'll have a look at that

**Comment by levitte** [comment]
Hmmm...  this was never cherry picked to 1.1.0...  It should be, will do now, as well as #5282

**Comment by levitte** [comment]
Cherry picked to 1.1.0 as well.  d8ba72c9f7e397942aabe1a0a3ad7019e774884a

**Pull request closed without merging**
