### PR TITLE
README: add link to OpenSSL 3.2 manual pages

### PR DESCRIPTION
**Pull request by mspncp**

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Review by slontis — APPROVED** [review]

**Comment by mspncp** [comment]
@arapov this was auto-closed by @openssl-machine without being merged, although it had an 'approval: done' label? How can this happen?

grafik

**Comment by t8m** [comment]
@mspncp because you created the branch in the openssl/openssl repo and not in your fork.

**Comment by t8m** [comment]
I'll merge it now.

**Comment by t8m** [comment]
Merged to the master and 3.2 branches. Thank you.

**Comment by mspncp** [comment]
Ah ok, thanks for the hint! I wasn't aware of that. 😊 
I guess this is the first and last time I'll do a quick PR via GitHub webinterface on my mobile phone!  📵

**Pull request closed without merging**
