### PR TITLE
CHANGES: Document the removal of OS390-Unix

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by t-j-h** [comment]
That script exists in earlier branches - I don't know when it was removed - but removal of a platform via this approach seems inappropriate.

**Comment by t-j-h** [comment]
This is the commit which removed the script - commit 71cdcfc6069ca8afe92cda636805a8c46f000862

Given the justification for remove this platform definition is that a script that was removed because it was said to not be used - these two recent updates (and the earlier deletion of the script ) should be reverted.

**Comment by levitte** [comment]
Hmm...  ok, so we have *effectively* removed support for OS390-Unix before the release of 1.1.0 by removing that script, and we now have two interpretation on how to deal:

1.  Consider the config target effectively gone and actually remove it, as it should probably have been back before August 2016.  Done now.
2.  Consider the removal of the script a mistake and restore the target and scripts, i.e *effectively* restore OS390-Unix.

I'm not sure what's really the right move here.

**Comment by t-j-h** [comment]
The justification for the original script removal was that it was unused - that was wrong - that should be reverted. And when that is reverted the justification for the platform removal (that it uses a script that is not present) then disappears - and that should be reverted. To me that is very clear.

If someone had put forward a remove-this-platform request I would have placed a -1 on that request.

I actually have improving the support for the platform on my list of things to work through - just behind other higher priority tasks at the moment.

**Comment by levitte** [comment]
Okie, that's justification enough for me.  I'll put together a restoring PR

**Comment by richsalz** [comment]
We have not been able to reach the config author (who presumably also wrote the script), so it was removed for license/CLA considerations.

**Comment by levitte** [comment]
Errrrrr...  the script was remove in March 2016.

**Comment by levitte** [comment]
Or ah, are you telling me that's the reason the last vestiges went away now?

**Comment by richsalz** [comment]
Yes.  I do not recall how/why/if we removed the script, but those config changes had no CLA and attempts to reach the author failed.

**Comment by t-j-h** [comment]
The script and the config lines are "trivial" in nature. 
Can you point to the specific commits / author details?
If you were removing this for license-non-response reasons then that should have been clear in the commit messages - which it was not referred to or stated in the original commit nor in the subsequent commits.

**Comment by levitte** [comment]
I don't agree that they are "trivial" in nature...  we've opted for non-trivial for lesser things...

**Comment by richsalz** [comment]
I don't recall the reasoning about the script.  When doing the license CLA review, as discussed on the OMC mailing list, we found the config entry. It used a script that was removed in 1.1.0; we thought it wasn't trivial, and since the script was gone, and we could not contact the author, we removed the config entry.  All of those things were discussion via the license email address as we've been doing since forever.

Perhaps it *was* a mistake to remove the script back in 1.1.0.  But our policy is that nothing goes in now without a CLA.

If this is needed and important (still waiting for Andy's feedback), someone will have to submit a new PR.

Hope this explanation helps.

**Pull request closed without merging**
