### PR TITLE
OpenSSL::Test: When prefixing command with $^X on Windows, fix it up!

### LINKED ISSUE #14256: "nmake test" is failing when the path to perl.exe contains a space.
The full path to perl.exe is **C:\Program Files\Perl64\bin\perl.exe**

I'm building OpenSSL 3.0.0 alpha 12. This has worked with previous versions of OpenSSL, including 1.1.1i.

Here are the command lines I ran after starting up the VC x86 shell

```
set path=%path%;c:\Program Files (x86)\NASM-2.15.05;C:\Program Files\Perl64\bin;C:\Program Files\Perl64\site\bin
perl.exe Configure VC-WIN32 no-shared --prefix=c:/openssl --openssldir=c:/openssl/ssl
nmake
nmake test
```

The tests run by "nmake test" are causing the following error, which I'm guessing is because the path to perl.exe is not wrapped in quotes, when calling "wrap.pl"; but **is** wrapped in quotes when calling "run_tests.pl".

**"'C:\Program' is not recognized as an internal or external command, operable program or batch file."**

Here's the sample output. After seeing the first few errors, I used ctrl+c to cancel out of the tests.

```
C:\openssl-3.0.0-alpha12>nmake test

Microsoft (R) Program Maintenance Utility Version 14.28.29337.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\nmake.exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\nmake.exe" /                   _tests

Microsoft (R) Program Maintenance Utility Version 14.28.29337.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 14.28.29337.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        set SRCTOP=.
        set BLDTOP=.
        set PERL=C:\Program Files\Perl64\bin\perl.exe
        set FIPSKEY=f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813
        "C:\Program Files\Perl64\bin\perl.exe" ".\test\run_tests.pl"
01-test_abort.t .................... ok
01-test_sanity.t ...................
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\test\sanitytest.exe => 1
not ok 1 - running sanitytest
01-test_sanity.t ................... 1/? ---------------------------------------
#   Failed test 'running sanitytest'
#   at C:\openssl-3.0.0-alpha12\util\perl/OpenSSL/Test/Simple.pm line 77.
01-test_sanity.t ................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
01-test_symbol_presence.t .......... skipped: Only useful when building shared libraries
01-test_test.t .....................
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\test\test_test.exe => 1
not ok 1 - running test_test
01-test_test.t ..................... 1/? ---------------------------------------
#   Failed test 'running test_test'
#   at C:\openssl-3.0.0-alpha12\util\perl/OpenSSL/Test/Simple.pm line 77.
01-test_test.t ..................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
02-test_errstr.t ................... skipped: This is unsupported on MSYS/MinGW or MSWin32
02-test_internal_context.t .........
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\test\context_internal_test.exe => 1
not ok 1 - running context_internal_test
02-test_internal_context.t ......... 1/? ---------------------------------------
#   Failed test 'running context_internal_test'
#   at C:\openssl-3.0.0-alpha12\util\perl/OpenSSL/Test/Simple.pm line 77.
02-test_internal_context.t ......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
02-test_internal_ctype.t ...........
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\test\ctype_internal_test.exe => 1
not ok 1 - running ctype_internal_test
02-test_internal_ctype.t ........... 1/? ---------------------------------------
#   Failed test 'running ctype_internal_test'
#   at C:\openssl-3.0.0-alpha12\util\perl/OpenSSL/Test/Simple.pm line 77.
02-test_internal_ctype.t ........... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
02-test_internal_keymgmt.t .........
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\test\keymgmt_internal_test.exe => 1
not ok 1 - running keymgmt_internal_test
02-test_internal_keymgmt.t ......... 1/? ---------------------------------------
#   Failed test 'running keymgmt_internal_test'
#   at C:\openssl-3.0.0-alpha12\util\perl/OpenSSL/Test/Simple.pm line 77.
02-test_internal_keymgmt.t ......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
02-test_internal_provider.t ........
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\test\provider_internal_test.exe => 1
not ok 1 - running provider_internal_test
02-test_internal_provider.t ........ 1/? ---------------------------------------
#   Failed test 'running provider_internal_test'
#   at C:\openssl-3.0.0-alpha12\util\perl/OpenSSL/Test/Simple.pm line 77.
02-test_internal_provider.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
02-test_lhash.t ....................
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files\Perl64\bin\perl.exe ..\..\util\wrap.pl ..\..\test\lhash_test.exe => 1
not ok 1 - running lhash_test
02-test_lhash.t .................... 1/? ---------------------------------------
#   Failed test 'running lhash_test'
#   at C:\openssl-3.0.0-alpha12\util\perl/OpenSSL/Test/Simple.pm line 77.
02-test_lhash.t .................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
02-test_ordinals.t ................. NMAKNEM A:K Ef a: tfaalt aelr reorrr oUr1 0U518:05 8t:e rtmeirnmaitneadt ebdy  buys eurs
eSrt
oSpt.o
p.
```

### PR DESCRIPTION
**Pull request by levitte**
The perl interpreter name itself might contain spaces and need quoting.
__fixup_prg() does this for us.

Fixes #14256

Co-authored-by: Tomáš Mráz <tomas@openssl.org>

### CODE REVIEW

**Review by paulidale — DISMISSED** [review]

**Comment by t8m** [comment]
Isn't this missing to really fix the issue:
```
diff --git a/util/perl/OpenSSL/Test.pm b/util/perl/OpenSSL/Test.pm
index 4dc1bad188..55f26cc630 100644
--- a/util/perl/OpenSSL/Test.pm
+++ b/util/perl/OpenSSL/Test.pm
@@ -1232,7 +1232,7 @@ sub __wrap_cmd {
             # In the Windows case, we run perl explicitly.  We might not
             # need it, but that depends on if the user has associated the
             # '.pl' extension with a perl interpreter, so better be safe.
-            @prefix = ( $^X, $std_wrapper );
+            @prefix = ( __fixup_prg($^X), $std_wrapper );
         } else {
             # Otherwise, we assume Unix semantics, and trust that the #!
             # line activates perl for us.
```

**Comment by levitte** [comment]
How did I misread the issue so badly???
Thanks @t8m...

**Comment by levitte** [comment]
Time to re-review this

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Merged

0d6c144e8d0c53e8947e3a76225ea33b3e29abc8 OpenSSL::Test: When prefixing command with $^X on Windows, fix it up!
02669b677e6263b3d337ceb526b8b030477fe26b Windows build file: add forgotten quotes on POD->html command line

**Pull request closed without merging**
