### PR TITLE
Fix PPC64 problems

### PR DESCRIPTION
**Pull request by martin-schwenke**
This patch set fixes issue #15748 and makes some other minor alignment changes.

It also fixes an issue because the code to save registers into vector registers does not work on ISA < 2.07, reverting to the regular method of saving registers to the stack.  The performance penalty is less than 1%.

Overall performance for `ecdhp384` and `ecdsap384` is pretty much unchanged.

I'm happy to break this up into multiple PRs if necessary.

The commits have been locally reviewed by Amitay and have corresponding `Reviewed-by:` tags.  We're not sure what the convention is for non-maintainer reviewers - please let us know if there is something better (e.g. `Acked-by:` ?).  I can update to whatever is suggested and push again, or the commit summaries can be updated by someone who knows better.  ;-)

This has been tested on Linux running on Power 9 (ISA 3.0) and AIX on Power 7 (ISA 2.06).

### CODE REVIEW

**Comment by martin-schwenke** [comment]
I didn't bother updating the FIPs checksums.  Not sure if it should be done in each commit that touches a particular file.  In previous PRs I think these have been fixed during merge.  Please yell if I should have done this.

Please let me know if I have missed anything else...

Thanks!

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
IMO this should be treated as urgent and merged before beta1.

**Comment by paulidale** [comment]
Agreed with urgent, although it would have been nice to confirm it works ....

**Comment by t8m** [comment]
> Agreed with urgent, although it would have been nice to confirm it works ....

I can actually try.

**Comment by martin-schwenke** [comment]
Please let me know if there's any test output I can provide to improve confidence.

One problem is that `make test` seems to have problems on AIX, at least according to some other open issues.  I don't think I'll be able to get the Perl modules installed tonight to give it a proper try.  However, I can (for example) provide `openssl speed ecdhp384` output after a successful build.

Apologies for breaking this and for the late fix.  Mistakes made, lessons learned.  We'll clearly do AIX testing for future Power changes...

**Comment by mattcaswell** [comment]
IMO, this is too  late for beta 1. I'm starting the release process NOW...

**Comment by martin-schwenke** [comment]
There are a couple more commits required to fix the AIX build for the p521 changes that we also submitted.  They're in https://github.com/martin-schwenke/openssl/tree/master-p521 - should they be in this PR too?  Given the title of this PR, I suspect it should be a different PR.

**Comment by t8m** [comment]
Clearing the urgent severity then. Please add the other patches as apparently they are needed to build the assembler code on AIX as well.

**Comment by t8m** [comment]
I see currently:
```
crypto/ec/ecp_nistp521-ppc64.s: line 5: invalid opcode or pseudo-op
crypto/ec/ecp_nistp521-ppc64.s: line 197: invalid opcode or pseudo-op
crypto/ec/ecp_nistp521-ppc64.s: line 202: invalid opcode or pseudo-op
crypto/ec/ecp_nistp521-ppc64.s: line 345: invalid opcode or pseudo-op
```

**Comment by t8m** [comment]
Whether you add the additional patches here or as a separate PR does not matter much.

**Comment by martin-schwenke** [comment]
I've added 3 commits for p521, hence the title change for this PR.

The extra commits:

* Fix the build failures [mentioned above](#issuecomment-863249684) by dropping some problematic assembler pseudo-ops
* Add `.align` at the beginning of functions
* Drop the build of `ecp_nistp521-ppc64.s` unless configured with `enable-ec_nistp_64_gcc_128` - the build failures shouldn't have been seen unless the build was configured with `enable-ec_nistp_64_gcc_128`

**Comment by martin-schwenke** [comment]
Note that there's still a problem with p521 on AIX when configured with `enable-ec_nistp_64_gcc_128`:

```
$ LD_LIBRARY_PATH=. apps/openssl speed ecdhp521 
ECDH computations don't match.
version: 3.0.0-alpha4
built on: built on: Fri Jun 18 04:33:52 2021 UTC
options:bn(64,64) rc4(char) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -maix64 -pthread -O -DB_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: N/A
```
However, this isn't a new problem:
```
$ LD_LIBRARY_PATH=. apps/openssl version
OpenSSL 3.0.0-alpha4 25 Jun 2020 (Library: OpenSSL 3.0.0-alpha4 25 Jun 2020)
```
We don't (yet?) know how to fix this.  It certainly predates our recent assembly code.  Perhaps it has never worked?

I won't hold this patch series until we have some clues on this problem.  Instead, I'll open a new issue to track that and point some AIX developers at it.

**Comment by martin-schwenke** [comment]
> Note that there's still a problem with p521 on AIX when configured with `enable-ec_nistp_64_gcc_128`:

I opened issue #15821 on this.  It has explained that this isn't expected to work on big-endian systems.  It is documented in `INSTALL.md`.  I've suggested a patch to actually make the build fail in this case.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Second review needed.

**Comment by t8m** [comment]
Even with these changes I'm still unable to pass tests on aix64-gcc target:

```
bash-4.3$ make test TESTS='test_enc'
        make depend && make _tests
        ( SRCTOP=.  BLDTOP=.  PERL="perl"  FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813"  EXE_EXT=  perl ./test/run_tests.pl test_enc )
00-prep_fipsmodule_cnf.t .. skipped: FIPS module config file only supported in a fips build
Files=1, Tests=0,  0 wallclock secs ( 0.00 usr  0.00 sys +  0.08 cusr  0.00 csys =  0.08 CPU)
Result: NOTESTS
20-test_enc.t .. 1/? 
aes-128-cbc: unable to load provider legacy
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
00000001:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:
00000001:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
00000001:error:078C0105:common libcrypto routines:provider_init:init fail:crypto/provider_core.c:658:name=legacy
../../util/wrap.pl ../../apps/openssl aes-128-cbc -bufsize 113 -e -k test -provider-path ../../providers -provider default -provider legacy -in ./p -out ./p.aes-128-cbc.cipher => 1
not ok 3 - aes-128-cbc
# ------------------------------------------------------------------------------
#   Failed test 'aes-128-cbc'
#   at test/recipes/20-test_enc.t line 70.
```
I'll file that in as a separate issue.

**Comment by t8m** [comment]
> I'll file that in as a separate issue.

Actually it is exactly the same failure mode as in #13336

**Comment by martin-schwenke** [comment]
> > I'll file that in as a separate issue.
> 
> Actually it is exactly the same failure mode as in #13336

I'll mention that to AIX developers to see if they can fix it...

**Comment by t8m** [comment]
#15828 fixes this

19. 6. 2021 5:55, 5:55, Martin Schwenke ***@***.***> napsal/a:

**Comment by martin-schwenke** [comment]
> > > Actually it is exactly the same failure mode as in #13336 

> > I'll mention that to AIX developers to see if they can fix it...

> #15828 fixes this

Indeed!  :-)

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the fix.

**Pull request closed without merging**
