### PR TITLE
Fix typos found by codespell in openssl-3.1

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Only modify `doc/man*` in the [openssl-3.1](https://github.com/openssl/openssl/tree/openssl-3.1) branch.

##### Checklist

- [X] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the corrections.

**Comment by paulidale** [comment]
oops, repo is frozen can't merge.

**Comment by t8m** [comment]
> oops, repo is frozen can't merge.

Heh, I've forgot to unfreeze. I am sorry for that.

**Comment by t8m** [comment]
Merged to the 3.1 branch. Thank you for your contribution.

**Pull request closed without merging**
