### PR TITLE
sha/asm/sha512-armv8.pl: add NEON version of SHA256.

### PR DESCRIPTION
**Pull request by dot-asm**
This provides up to 30% better performance on some of recent processors.

### CODE REVIEW

**Comment by dot-asm** [comment]
Ping @ardbiesheuvel.

**Comment by ardbiesheuvel** [comment]
I have tested this code with the linux kernel patch I intend to propose based on this code, and it works as expected.

Tested-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>

**Comment by levitte** [comment]
@dot-asm, please lable the branches this is intended for

**Comment by dot-asm** [comment]
I've added 1.1.0 solely in order to minimize discrepancies.

**Comment by dot-asm** [comment]
Ping @levitte :-)

**Comment by dot-asm** [comment]
It didn't cherry-pick without conflict to 1.1.0, so I'm leaving it master-only. It doesn't matter much as it's quite niched case. If there will be some more significant and more essential changes that would actually need to go to 1.1.0, we can resync is as whole then. Closing the request... Thanks.

**Pull request closed without merging**
