### PR TITLE
Revert "Run test_ordinals after update"

### PR DESCRIPTION
**Pull request by aeijdenberg**
This reverts commit 0aca86b313d286be979629a3193a12e17bf7171a.

Previous commit caused "make update" to fail on a clean source tree,
since the test uses "apps/openssl" which isn't built yet.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Could we somehow test for the existence of apps/openssl and run the test if it is there, rather than reverting?

**Comment by kaduk** [comment]
How about running test_ordinals as part of 'make test'?

**Comment by richsalz** [comment]
It is run as part of test.  The idea is to run it before the build gets too far and wastes time, causes needless global warming, melts the polar ice caps, and so on.

**Comment by levitte** [comment]
The other idea is to have `test_ordinals` run `test/run_tests.pl test_ordinals` directly...

**Comment by levitte** [comment]
f6e9c5533101066b2c759986ae8694c0f1926735

**Pull request closed without merging**
