### PR TITLE
Re-added CHIL engine

### PR DESCRIPTION
**Pull request by urcheon**
Re-added CHIL Engine

Now compiles with openssl 1.1

Tested all custom chil/hwchrk functions using a nFast PCI nC1002P/nC3022P ver 2.18.13 card.
Both embed and hwcrhk "application" types work.

### CODE REVIEW

**Comment by richsalz** [comment]
Just FYI, it is too late for this to be part of 1.1.1. Thanks for the submission. But is this just restoring code that was removed before?

**Comment by urcheon** [comment]
I refactored the code to compile with openssl 1.1

**Comment by richsalz** [comment]
We removed it in fee65521e7af40d6fcedf68c515f602bdb11f565 with #3389 because we had no way to support it.  Are you taking on that burden starting with the next release?  Also note that we don't have a CLA.

**Comment by levitte** [comment]
We hoped that it would be updated, but we have removed it from the OpenSSL main source for good reason, maintainability.  It's much better placed as a separate project, *or* with the vendor of the corresponding hardware.

engine-corner/engine-chil#1 noted, btw.  And yes, that's where I would expect these changes to happen.

**Pull request closed without merging**
