### PR TITLE
RISC-V support for the SHA256

### PR DESCRIPTION
**Pull request by marcfedorow**

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
I know we already approved and merged the SHA-512 support. My question is - for other architectures that add new instructions for algorithm acceleration or any other extra instruction sets we usually support building "full featured" assembler code which contains fallback code paths for CPUs which do not support these instructions. Do these RISC-V PRs effectively make the asm build for RISC-V depending on these special instructions being supported?

Please note I do not know almost anything about RISC-V so it is possible that these instructions are widely available and for the rest building with no-asm is sufficient.

**Comment by marcfedorow** [comment]
@t8m
I do not think that I can produce efficient assembler code like [this](https://github.com/openssl/openssl/blob/26a2bbb0c10ae52b3ab5d98b194017ecea1c76ce/crypto/sha/asm/sha256-armv4.pl).
However sha* instructions are not the only that increase performance.
I did not add inline assembler for instructions that can be automatically emitted by the compiler. They are mostly bit manipulation instructions (such as rotations, zero counting, etc).
If riscv-bitmanip instructions are present, compiler should emit them regardless of presence of zkn instructions.

To some point compiler generates more or less efficient code depending on what exact subset is supported. My patches should help it in that cases where it can not generate the most efficient code by itself.

Sorry if I misunderstood your question.

**Comment by t8m** [comment]
I try to ask differently - Other asm implementations for different architectures (such as x86, arm, ppc, or s390x) do runtime selection of the codepath (and thus extra instructions) used. So the code can be built once and run on different CPU models with different extra instructions (AVX2, SSSE3,....). Your patches do not do that, if I understand them correctly. They are just build-time and once you build so the instructions are used you cannot use the binaries on CPUs which do not support these sha512 or sha256 instructions.
I am saying that just for consideration.

**Comment by marcfedorow** [comment]
Yes, you understand my patches correctly.
E.g. this code compiled with -march=izkn will fail with cause 2 (illegal instruction) if run on hardware with no ZKN-extension.

The problem is: RISC-V currently has no consensus about the discovery mechanism. Previously it should be done by checking the machine-ISA register. Currently, both bit-manipulation and cryptographic extensions marked their MISA bits as deprecated (they now should be hard-wired to zero).

Here is the quote from [the pre-release version](https://github.com/riscv/riscv-crypto/releases/tag/v0.9.4-scalar):
`The misa.K bit is no longer used to identify the scalar cryptography extension. Feature detection of scalar cryptography extensions will be done using the work-in-progress discovery mechanisms for RISC-V.`
This applies to the release version too.

So now there is no consensual adequate discovery mechanism at this exact moment.
Previously I could use something like
```
shl x1 1 10 # reg1 = 1 << ('K' - 'A')
csrr x2 0xfc0 # reg2 = CSR_MISA
and x1 x1 x2  # reg1 &= misa
beqz x1 fallback # if (!reg1) goto: fallback
```
But now it is impossible.

The only way it is possible to provide run-time fallbacks is to execute some instruction and then to catch an exception.
Probably another way will be developed -- if so (or if traps become the recommended way to check the extension presence) I will probably implement assembler with run-time fallbacks.
I do not think that it should be done now because the discovery mechanism is not frozen yet.

**Comment by t8m** [comment]
OK, thanks for the explanation. I think I can approve this now.

**Comment by paulidale** [comment]
> The only way it is possible to provide run-time fallbacks is to execute some instruction and then to catch an exception.

Some platforms do exactly this.  It's hideous.

**Comment by t8m** [comment]
> Some platforms do exactly this. It's hideous.

Yeah that approach is causing multiple problems, let's not do it here.

**Comment by kroeckx** [comment]
At least one approach we use on some platforms, is that the OS can provide that information. On linux this would be using getauxval().

**Comment by paulidale** [comment]
Good point @kroeckx

**Comment by t8m** [comment]
Merged to master. Thanks for the contribution.

**Pull request closed without merging**
