### PR TITLE
Core: allow NULL argument to stored_namemap_free().

### LINKED ISSUE #10482: Null-pointer-dereference bug at core_namemap.c
Hello, I have found an out-of-memory bug with my fuzzing tool **FIFUZZ**. The bug information is following.

**Describe the bug**
The **malloc()** in the call stack shown below may fail:

    #0 Call malloc() in CRYPTO_malloc(), at mem.c: 222
    #1 Call CRYPTO_malloc() in CRYPTO_zalloc(), at mem.c: 230
    #2 Call CRYPTO_zalloc() in CRYPTO_THREAD_lock_new(), at threads_pthread.c: 33
    #3 Call CRYPTO_THREAD_lock_new() in ossl_namemap_new(), at  core_namemap.c: 101
    #4 Call ossl_namemap_new() in stored_namemap_new(), at core_namemap.c: 63
    #5 Call stored_namemap_new() in openssl_ctx_generic_new(), at context.c: 172
    #6 Call openssl_ctx_generic_new() in CRYPTO_alloc_ex_data(), at ex_data.c: 424
    #7 Call CRYPTO_alloc_ex_data() in openssl_ctx_get_data(), at context.c: 248
    #8 Call openssl_ctx_get_data() in ossl_namemap_stored(), at core_namemap.c: 92
    #9 Call ossl_namemap_stored() in evp_get_cipherbyname_ex(), at names.c: 95
    #10 Call evp_get_cipherbyname_ex() in EVP_get_cipherbyname(), at names.c: 72
    #11 Call EVP_get_cipherbyname() in pthread_once()
    #12 Call pthread_once() in CRYPTO_THREAD_run_once(), at thread_once.h: 122
    #13 Call CRYPTO_THREAD_run_once() in OPENSSL_init_ssl()
    #14 Call OPENSSL_init_ssl() in apps_startup(), at openssl.c: 57
    #15 Call apps_startup() in main(), at openssl.c: 270

If the **malloc()** in this call stack fails, **stored_namemap_new()** in **openssl_ctx_generic_new()** will return NULL, so **ptr** in **openssl_ctx_generic_new()** is NULL at context.c: 172. Because **ptr** is NULL, the function call **CRYPTO_set_ex_data(ad, index, ptr)** will not be executed (At this time, **index** is **2**). And then, in **openssl_ctx_get_data()**, **data** is assigned by the return value of **CRYPTO_get_ex_data(&ctx->data, ctx->dyn_indexes[index])** at context.c: 250, so **data** is NULL (because **ctx->dyn_indexes[index]** is equal to **2** now). And then **openssl_ctx_get_data()** returns **data** (it is NULL) and triggers the error handling code of **ossl_namemap_stored()**.

However, when the program exits, it call **CRYPTO_free_ex_data()**. In **CRYPTO_free_ex_data()**, **ptr** is assigned by the return value of **CRYPTO_get_ex_data(ad, i)** at ex_data.c: 377. When **i** is equal to **2**, the **ptr** will be NULL. And then, **CRYPTO_free_ex_data()** call **openssl_ctx_generic_free()** at ex_data.c: 378 with **ptr** (it is NULL) as the second argument. And **openssl_ctx_generic_free()** call **stored_namemap_free()** at context.c:183 with ptr (it is NULL) as the argument. In **stored_namemap_free()**, **vnamemap** is equal to **ptr**, so **vnamemap** is NULL. And **namemap->stored** causes a **null-pointer-dereference** at core_namemap.c:76

The Stack Traceback when the bug occurs:

    (gdb) backtrace
    #0  0x00007ffff7471b06 in stored_namemap_free (vnamemap=0x0) at crypto/core_namemap.c:76
    #1  0x00007ffff746fbbe in openssl_ctx_generic_free (parent_ign=0x0, ptr=0x0, ad=0x7ffff7a6a398 <default_context_int+8>, index=2, argl_ign=0, argp=0x7ffff7a416f8 <stored_namemap_method>) at crypto/context.c:183
    #2  0x00007ffff7475dc9 in CRYPTO_free_ex_data (class_index=16, obj=0x0, ad=0x7ffff7a6a398 <default_context_int+8>) at crypto/ex_data.c:378
    #3  0x00007ffff746e206 in context_deinit (ctx=0x7ffff7a6a390 <default_context_int>) at crypto/context.c:110
    #4  0x00007ffff746e085 in openssl_ctx_default_deinit () at crypto/context.c:124
    #5  0x00007ffff7476ed4 in OPENSSL_cleanup () at crypto/init.c:416
    #6  0x00007ffff68f1041 in __run_exit_handlers (status=1, listp=0x7ffff6c99718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
    #7  0x00007ffff68f113a in __GI_exit (status=<optimized out>) at exit.c:139
    #8  0x047c5ba in main (argc=12, argv=         0x7fe2a0) at apps/openssl.c:379

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Type openssl enc -e -des3 -a -salt -in /tmp/test.c -out test.cipher -k testtesttest -pbkdf2
1. Make the _malloc()_ shown at **Describe the bug** fail.
2. The program will crash.

**Expected behavior**
The program would not crash when _malloc()_ fails.

**Environment (please complete the following information):**
 - Version: 3.0.0-dev
 - OS: Ubuntu 18.04
 - Compiler: Clang-6.0
 - Application: openssl 3.0.0-dev

**Additional context**
This bug is found by my fuzzing tool and the bug is triggered at runtime.

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #10482

### CODE REVIEW

**Comment by paulidale** [comment]
I can't see how the Travis failure is relevant...

**Comment by levitte** [comment]
Me neither, but I wonder how that happened...

**Comment by paulidale** [comment]
I've restarted Travis to see if it was transient or not.
I can't reproduce the failure locally.

**Comment by paulidale** [comment]
The build that failed worked.

**Comment by paulidale** [comment]
Merged to master.  thanks.

**Pull request closed without merging**
