### PR TITLE
rand_lib.c: fix null pointer dereferences after RAND_get_rand_method() failure [1.1.1]

### PR DESCRIPTION
**Pull request by mspncp**
Manual backpport of #10483.

### CODE REVIEW

**Comment by slontis** [comment]
@paulidale - does this approval still stand or should the NULL checks not return here?

**Comment by mspncp** [comment]
I intended to do the changes analogously here.

**Comment by paulidale** [comment]
Good question @slontis, I'd forgotten this one 😞
I'm okay either way, the FIPS provider problem isn't present in 1.1.1.

**Comment by mspncp** [comment]
The last commit f63f749053f6b896f33c8df01f768ab3dc1f22b7 makes the implementation more analogous to the one on the master branch.

**Comment by mspncp** [comment]
This won't be merged before #10483 is approved.

**Comment by paulidale** [comment]
#10483 has been merged, so this should be good now.

**Comment by mspncp** [comment]
Thanks for the reminder. I did not forget it, but I made some slight adjustments on master (push some errors to the stack) which I did not have the time yet to update here. Shall I add it as a fixup and you decide whether to keep it or not? Or shall I just merge the pull request as it is now?

**Comment by paulidale** [comment]
Either is okay, I'll try to review quickly.

**Comment by mspncp** [comment]
The code on 1.1.1 is structured slightly differently. Effectively, only the error code in `RAND_pseudo_bytes()` was missing. I know it's deprecated, but nevertheless I added the error code in ef97a3ea981d64ba0316d1e786972fc1d9382a86.

Side note: I noticed that `mkerr.pl` adds 3.0-style include guards in 1.1.1., which it shouldn't. So I reverted that change. Fix coming up...

**Comment by mspncp** [comment]
> Fix coming up...

See #10623.

**Comment by mspncp** [comment]
Merged to 1.1.1 in f9fdb9d2f5a0358a3fd34b060fe23cb0eceb2e2c, thanks!

**Pull request closed without merging**
