### PR TITLE
Add a basic test for BN_bn2dec.

### PR DESCRIPTION
**Pull request by davidben**
This would have caught 099e2968ed3c7d256cda048995626664082b1b30. This is
a port of the test added in
https://boringssl.googlesource.com/boringssl/+/7c040756178e14a4d181b6d93abb3827c93189c4

### CODE REVIEW

**Comment by richsalz** [comment]
I still hope that my #1310 will get in; so can you think about the rebasing against it?

**Comment by davidben** [comment]
Sure. I figure both PRs will merge eventually and this is pretty trivial to rebase or be rebased upon. Or did you mean that this should be something like:

```
Decimal = "12345"
Input = 4d2
```

**Comment by davidben** [comment]
Hahaha. Might want to tweak that coveralls config. It's complaining that test coverage decreased because `bntest.c`'s coverage went down. (Test files sort of inherently have unreachable codepaths. The codepaths that complain the test didn't work shouldn't get reached. :-) )

**Comment by richsalz** [comment]
No, it’s fine as-is.

**Comment by ekasper** [comment]
+1

**Comment by ekasper** [comment]
Re coveralls, I intentionally included test files for now because they're also a mess and we might catch bugs and unreachable code in them. Ideally test file coverage would be shown but not counted in the total - but I don't think the reporting supports that.

But yes we should see how to make the report more useful for individual PRs. What we'd really need is a line coverage diff but coveralls doesn't support that either I think...

**Comment by richsalz** [comment]
will merge to master.  @ekasper ping me if you think i should port back to 1.1.0

**Comment by ekasper** [comment]
@richsalz, would be good to always backport tests if it's not a lot of hassle, I think.

**Comment by richsalz** [comment]
okay commit a7511d7 in 1.1.0;

**Pull request closed without merging**
