### PR TITLE
Remove parentheses of return.

### PR DESCRIPTION
**Pull request by KaoruToda**
Since return is inconsistent, I removed unnecessary parentheses and unified them.

### CODE REVIEW

**Comment by kroeckx** [comment]
Did you use some kind of script to do this? If so, it would probably be easier to review that then to go over the diff.

**Comment by mattcaswell** [comment]
This looks good. I would approve it except it has merge commits which we do not allow. Please can you remove them?

**Comment by KaoruToda** [comment]
Thank you for your review.
I try to remove them and I will create new pull request later.

**Comment by mattcaswell** [comment]
Closing in favour of #4541

**Pull request closed without merging**
