### PR TITLE
Increase maximum rand count to 64 bit int.

### PR DESCRIPTION
**Pull request by batrick**

### CODE REVIEW

**Comment by batrick** [comment]
I would also suggest that this function be usable as an infinite source of random numbers by omitting the count and/or by specifying a negative count.

**Comment by richsalz** [comment]
that's not the best way to generate a random stream.  this was discussed in RT 4227 (https://rt.openssl.org/Ticket/Display.html?id=4227) user guest password guest.

**Comment by batrick** [comment]
I agree with this comment:

>Great. But the normal user does not know this. Why not just use
`openssl rand` as the wrapper that does the above? No need to change
the interface for the functions - simply put the wrapper in `openssl
rand` with a counter and then generate 2 GB at a time (like now) until
enough has been generated.

Expecting the novice user to use symmetric encryption routines for a random data stream is ludicrous. Why not fix the rand app??

**Comment by richsalz** [comment]
Why does the app need a random stream?  Infinite?  The openssl rand app isn't the appropriate place to do it securely.  Or add another option, or something.

**Comment by batrick** [comment]
Trivial use-case: create a large file of random data for testing/experiments/etc.

Why isn't the rand app the appropriate place? What is "insecure" about it?

**Comment by richsalz** [comment]
Did you read the ticket?

**Comment by batrick** [comment]
Of course I read the ticket. It just confirms what I expected: the project will ignore sane user interface and continue this "you're doing it the wrong way non-sense". At least Linux gets `/dev/urandom` right and doesn't expect the USER to design an artificial RNG derived from a synthetic encryption stream. I guess designing a high performance userspace RNG is too fucking hard and we need to rely on the kernel.

Openssl has **no** business calling their CLI utility `rand`. It is a sad joke.

**Comment by richsalz** [comment]
Sorry you're so offended.

A PR that adds a -stream flag and does one of the things suggested in the ticket would be welcomed.

**Pull request closed without merging**
