### PR TITLE
Removal of old VMS cruft

### PR DESCRIPTION
**Pull request by levitte**
This is code to fixup deficiencies in VAX C and older DEC C RTLs.  Since we only support DEC C V7.1 and up, thsi old cruft isn't useful any more.

### CODE REVIEW

**Comment by levitte** [comment]
I'm running a test build on VMS.  As soon as it passes, the WIP: tag goes away.

**Comment by levitte** [comment]
It passed the VMS builds, getting of out WIP

**Comment by richsalz** [comment]
"old vms  cruft"  isn't that triply-redundant? :)
+1

**Review by richsalz — APPROVED** [review]

**Comment by dot-asm** [comment]
> "old vms cruft" isn't that triply-redundant? :)

No, it 3!, i.e. factorial :-)

**Comment by levitte** [comment]
Err, no.  VMS is a current operating system.

**Comment by richsalz** [comment]
We're just teasing you :)

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
