### PR TITLE
Fix negative zero

### PR DESCRIPTION
**Pull request by geoffthorpe**
This branch contains 3 patches relative to master, but the first ("bn: fix BN_DEBUG + ...") is already submitted separately. So this is for the two subsequent patches, which are dependent on that first one.

### CODE REVIEW

**Comment by davidben** [comment]
Do you think you could put together some regression tests for these cases?

**Comment by geoffthorpe** [comment]
(To davidben) Actually, "make test" is a regression test for this. :-) It had been some time since I tried building and running BN_DEBUG + BN_DEBUG_RAND builds, and it turns out that the checking had become ineffective. After fixing that (patch 1 of 3), make test was still completing OK, which is good news. But when I then adjust bn_check_top() (patch 2 of 3) to catch the negative-zero case (which was already enforced within bn_fix_top() by the way), "make test" started spewing. My third patch contains the changes required to allow "make test" complete successfully without triggering these negative-zero cases.

Other than that, what kind of regression test do you think makes sense? When the code is good, the BN_DEBUG build won't assert - how do you regression test that? By trying (and failing) to get the library to produce negative zeroes?

Perhaps in a BN_DEBUG build you could explicitly construct negative-zero BIGNUMs and feed them to different APIs and verify that the library asserts? But I don't think the test framework can do that. (I.e. where API return is a failure, and assert/abort is a success.)

Or if you're talking about adding regression tests for the APIs that I changed, to make sure I haven't broken them, well that should be implicit. I only adjusted code that "make test" was already exercising and that was causing the debugging checks to fire. Ipso facto those APIs (and code-paths therein) are already being tested, and if I broke their functionality, those tests would start failing.

**Comment by davidben** [comment]
This PR seems to fix cases where BIGNUM incorrectly gives negative zero. For example, it looks like `BN_div_word(BIGNUM(-1), 2)` used to set the quotient to -0 but now it is correctly 0. You can just write a test which asserts `BN_is_negative` returns zero.

We'd found various other cases in BoringSSL (the patches have been upstreamed, though it seems the tests are still stuck in #1310), and for each we added a test:
https://boringssl.googlesource.com/boringssl/+/deb2a8769d12bc3675bff67c04ab6892c6eac34d/crypto/bn/bn_test.cc#1131

By regression tests, I mean a test to ensure what you've fixed does not regress in future. It's generally good practice to write those alongside bugfixes. If it was wrong before, that's a good indication it's a non-trivial edge case and deserves a test.

**Comment by geoffthorpe** [comment]
I'm still not sure that what you're suggesting here makes sense relative to what I've fixed. Please bear with me...

Your comments ("This PR seems to fix cases where BIGNUM functions incorrectly give negative zero. [...]") seem to be about on-API-entry/exit considerations, whereas my fixes are *intra-API*.

E.g. take the first example, in BN_div(). Within the bowels of that function, a BIGNUM structure ('res') is being worked on directly, specifically the res->d, res->top, and res->neg fields. As part of that function's logic, there's a call out to bn_wexpand() on that 'res' structure, and explicit manipulations of that structure recommence within BN_div() once bn_wexpand() returns. The issue is *not* that BN_div() or bn_wexpand() are producing negative zeroes. What the debugging checks caught was that the 'res' structure was in an inconsistent/negative-zero state at the point it was passed to bn_wexpand, but this was fully corrected by the time the BN_div() function itself returns. The 'res' structure is in good shape and negative-zero has been eliminated by then. But bn_wexpand() didn't like the fact that BN_div() was asking it to act on a "work-in-progress" BIGNUM at a moment where it was in a negative-zero state. I fixed the ordering inside BN_div() so that the 'res' local variable is well-formed at the moment it is passed out to bn_wexpand() too, that's all.

If you've followed me so far, please clarify if you still think what you're suggesting makes sense here. When you say "a test to ensure what you've fixed does not regress in future", what that translates to here is the creation of a test on BN_div()'s internal logic?! I.e. to catch any future regression where the local variables it is acting on might be negative-zero at the point they're passed to other sub-routines. (I repeat: there was and is no negative-zero case here on-API-return.) But the *only* regression checking of this nature that I'm aware is precisely the BN_DEBUG framework that I reactivated in my earlier patch and that subsequently led to me submitting these fixes. Unless I'm misunderstanding you, you cannot write a test case to check that BN_div()'s *internal logic* doesn't regress in this way. As I pointed out previously, the BN_DEBUG build (once I fixed it) and the existing test coverage already caught this condition, and if it the BN_div()-internal logic regresses on this in the future, that existing coverage would catch it again.

So I'm really not sure what you think could or should be added here.

**Comment by davidben** [comment]
There are changes in this PR that are externally visible. For instance, here is a test for `BN_div_word` that could be added to `test_div_word`.

```
    /* -1 / 2 should be a non-negative zero. */
    BN_set_word(a, 1);
    BN_set_negative(a, 1);
    BN_div_word(a, 2);
    if (!BN_is_zero(a)) {
        fprintf(stderr, "Division (word) failed!\n");
        return 0;
    }
    if (BN_is_negative(a)) {
        fprintf(stderr, "Division (word) produced negative zero!\n");
        return 0;
    }
```

It looks like `BN_rshift` might also want something of the sort?

**Comment by levitte** [comment]
This hasn't been looked at for some time, but should.  Is this only for master or is 1.1.0 a viable target as well?

**Comment by richsalz** [comment]
yes for 1.1.0 as well IMO.

**Comment by levitte** [comment]
I just implemented the tests from the mentioned boringssl commit in #2335

**Comment by levitte** [comment]
#2335 now being merged onto master, I just tried a rebase of this branch onto the updated master, and indeed, `BN_div()` and `BN_rshift()` no longer return negative zero.  `BN_rshift1()` still does, though

**Comment by levitte** [comment]
Additional patch:

``` diff
diff --git a/crypto/bn/bn_shift.c b/crypto/bn/bn_shift.c
index b32060287..6a1eec80a 100644
--- a/crypto/bn/bn_shift.c
+++ b/crypto/bn/bn_shift.c
@@ -74,6 +74,8 @@ int BN_rshift1(BIGNUM *r, const BIGNUM *a)
         c = (t & 1) ? BN_TBIT : 0;
     }
     r->top = j;
+    if (!r->top)
+        r->neg = 0; /* don't allow negative zero */
     bn_check_top(r);
     return (1);
 }
```

If need be, I can add it as a separate PR

**Comment by richsalz** [comment]
+1 to include your pach as part of merging this PR

**Comment by levitte** [comment]
Ok, so I count you as a reviewer of that patch.  Cool.

I'll do the merging now.

**Comment by levitte** [comment]
Merged.

0b50ac1a0fe907f4effcf3f2f36dac32523938c5 .. 0a2dcb6990dacc94337f746f4f4a6dfac1fbeac4

**Pull request closed without merging**
