### PR TITLE
Correct the equation of Y' in the comment of function point_add

### PR DESCRIPTION
**Pull request by kunxian-xia**
In the comment of `point_add`(ecp_nistp224.c), the last part of equation that computes Y' is wrong.

### CODE REVIEW

**Comment by richsalz** [comment]
Can you put "CLA: trivial" in the body of the commit message, not the first (header/subject) line?  Thank you.

**Comment by kunxian-xia** [comment]
@richsalz I've put the "CLA: trivial" in the body.

**Comment by mspncp** [comment]
Sorry for the inconveniencies @kunxian-xia, but the cla bot did not recognize your CLA: trivial statement. It's probably because you wrote `- CLA: trivial` (with a dash) instead of `CLA: trivial`. The latter needs to go on a single line in the commit message body.

**Comment by kunxian-xia** [comment]
@mspncp Thanks for your reminder, I've update the commit message.

**Comment by richsalz** [comment]
@kunxian-xia thank you for your patience with us :)  Merged to master.

**Pull request closed without merging**
