### PR TITLE
OSSL_STORE and PKCS#12: Check if there is a MAC to verify before prompting

### PR DESCRIPTION
**Pull request by levitte**
When a DER object with unknown contents comes all the way to
ossl_store_handle_load_result(), and it attempts to decode them as different
objects, the PKCS#12 decoding attempt would (almost) always prompt for a
passphrase, even if there isn't a MAC to verify it against in the PKCS#12
object.

This change checks if there is a MAC to verify against before attempting to
prompt for a passphrase, leading to less surprising behavior.

### CODE REVIEW

**Comment by levitte** [comment]
This needs a test, that's why it's still a draft

**Comment by vdukhovni** [comment]
Does this fully address the reported issue?  The gist of it was IIRC that "openssl x509 -inform DER" might unexpectedly prompt for a password and block (if the input is a terminal or some other asynchronous source).

At this layer, is there any way to know that the operation in question never expects to be prompted?  Could `openssl-x509(1)` pass some flag or similar to unconditionally suppress prompting, or for that matter decoding of anything other than a certificate or a "trusted certificate".

**Comment by t8m** [comment]
This does NOT prevent x509 or any other app command that uses the generic load certs from store call from prompting.

IMO the possible prompting is not a bug at this point however it should be properly documented.

Redirecting the stdin from /dev/null is IMO sufficient workaround for unix-like systems. Not sure if windows command prompt supports that though.

**Comment by vdukhovni** [comment]
> This does NOT prevent x509 or any other app command that uses the generic load certs from store call from prompting.
> 
> IMO the possible prompting is not a bug at this point however it should be properly documented.

A more "user-friendly" alternative would be to clone a variant the generic function that never prompts, and use that when applicable, assuming of course that we in fact know in some cases that prompting is unexpected.

Punting the responsibility to the user to be sure to redirect input to /dev/null in various scripts is not likely to be appreciated by users who are caught unawares.

**Comment by levitte** [comment]
The thing I expect is that if the user feeds `openssl x509` a valid PKCS#12 file, they know what they're doing. A password prompt shouldn't be a surprise in that case.

This PR fixes the case of garbage finding it's way to this routine. A password prompt is surprising in that case.

Now, I can think of a number of other things that could be strengthened. For example, it seems that d2i_PKCS12 doesn't validate anything, not even the version number. If someone finds it worthwhile to strengthen that, I hope we will see follow-up PRs

**Comment by levitte** [comment]
Test added.  I've verified on current master that it fails there.

**Comment by levitte** [comment]
I expect follow-up PRs related to this one:

- Abort decoding on some ASN.1 errors that make it absurd to continue parsing the input (typically such input where `openssl asn1parse` would abort)
- Better validation of DER input (d2i_PKCS12() seems to do *nothing* to check that the contents are valid...  doesn't even check the PKCS#12 structure version)

**Review by t8m — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
and merged to all three branches

**Pull request closed without merging**
