### PR TITLE
Free allow null

### PR DESCRIPTION
**Pull request by richsalz**
This is currently based on #5757. If/when that PR gets merged, I will rebase this.  Note that it *only* restores the "allow NULL" behavior; other things mentioned in the comment thread were not done.

### CODE REVIEW

**Comment by richsalz** [comment]
Rebased against master; ready for review.

**Comment by levitte** [comment]
Hmmm, is there a reason why Travis didn't kick in at all?

**Comment by richsalz** [comment]
I have no idea.  I will open/close this and see what happens.

**Comment by FdaSilvaYY** [comment]
Is there a reason to keep the changes of commit 2194052e28a53e59ec2e0b91e57207b017fd9855 ?

**Comment by richsalz** [comment]
Those changes will have to be fixed separately.  I only read the text description of the original PR to figure out what to do here.

**Comment by dot-asm** [comment]
Mac OS X back log is off charts, it might be time to drop it from build matrix again...

**Comment by richsalz** [comment]
Merged to master.  Ping @mattcaswell to undo the testing stuff he had to do.

**Pull request closed without merging**
