### PR TITLE
Fix ssl3_do_write() to correctly handle retries

### PR DESCRIPTION
**Pull request by mattcaswell**
A BIO is documented to return -1 on write retry - but sometimes they return
0. ssl3_do_write() was incorrectly handling a 0 response.

Fixes https://github.com/openssl/openssl/issues/21422

### CODE REVIEW

**Comment by mattcaswell** [comment]
Actually this is only really a problem in the 3.1/3.0 branches. By accident of the record layer refactor this doesn't actually impact the master branch. But the code is still wrong so I think we should apply the fix here anyway.

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Ping for second review?

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by paulidale** [comment]
and merged.

**Pull request closed without merging**
