### PR TITLE
The next version in master is at least 1.1.2, not 1.1.1x

### PR DESCRIPTION
**Pull request by levitte**
The OMC hasn't yet decided what the next release version will be, but
it's at least going to 1.1.2, so we set that value for the moment.

### CODE REVIEW

**Comment by mattcaswell** [comment]
> The OMC has decided that the next release will be a major one

No they haven't. It has been discussed and agreed at the FIPS meeting that that is the recommended approach. But no formal OMC decision has been made to ratify that.

**Comment by mattcaswell** [comment]
-1

**Comment by mspncp** [comment]
Since it is beneficial to have different version numbers on `master` and `OpenSSL_1_1_1-stable`, maybe you could just call it 1.1.2-dev for the moment until a decision is made?

**Comment by mattcaswell** [comment]
That seems reasonable to me.

**Comment by levitte** [comment]
Ok, new commit that reflects what's been said here...  also, description changed accordingly.

Thanks for the reminder, there are a few more places to edit

**Review by mattcaswell — APPROVED** [review]
This looks fine. We should also update opensslv.h

**Comment by mspncp** [comment]
And the commit message still contains 1.2.0

**Comment by levitte** [comment]
I just added a fixup with the other affected files.

**Comment by levitte** [comment]
Reconfirm needed

**Comment by levitte** [comment]
(@mspncp, have a look at the squash commit, it talks about a new commit message)

**Comment by mspncp** [comment]
Oh, thanks for the hint! I didn't see that it was a "squash!", not a "fixup!" commit.

**Review by mspncp — APPROVED** [review]
LGTM

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

a4a90a8a3bdcb9336b5c9c15da419e99a87bc6ed The next version in master is at least 1.1.2, not 1.1.1x

Thank you!

**Comment by richsalz** [comment]
Make sure to update the release instructions and/or script to capture all the files that need to be updated.

**Pull request closed without merging**
