### PR TITLE
Small 3.0 C source fixes, needed for VMS

### PR DESCRIPTION
**Pull request by levitte**
A number of inclusions were missing...
(interestingly, `SIZE_MAX` is so taken for granted that we keep forgetting to include our "internal/numbers.h" whenever we use it)

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
You approved a little soon, I had written one inclusion wrong :wink:.  Fixed now.

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
There was one small fix added, please re-approve

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Something's weird with github actions today...  there are a number of failing tests, but with no logs whatsoever.
I'll try to cancel and restart them

**Comment by levitte** [comment]
So, new test runs indicate that 4fa40de might not be necessary, or even plain wrong.  If that turns out to be true (test run still ongoing), then I'll simply drop it.  The rest of the commits are already approve, so I assume that's going to be ok

**Comment by levitte** [comment]
Confirmed, 4fa40de was wrong and will be dropped

**Comment by levitte** [comment]
Merged

ac2aa13aaf6d4c5457fd99edd82659cb5b662816 Fix include/openssl/e_os2.h for VMS
fea559085bbe873f0f81751653cf673a7b00a95c Fix include/internal/sockets.h for VMS
857cbe176f28e3f178e492159fa9f2f203e845cd Fix crypto/bio/b_sock.c for VMS
d2f53212933f751ef76acca9cc05bcb67d799964 Make sure to include "internal/numbers.h" to get SIZE_MAX
bf991b25caa6e915d858dd56c98ee774f248f03c Make sure to include "crypto/ctype.h" to get ossl_isdigit()

**Pull request closed without merging**
