### PR TITLE
Add apps/progs.h to gitignore

### PR DESCRIPTION
**Pull request by tmshort**

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
oh, why do you think that is necessary ?

**Comment by levitte** [comment]
@bernd-edlinger, because `apps/progs.h` changed to not being versioned any more, just an hour or two ago.

**Comment by levitte** [comment]
BTW, this should go to master and 1.1.0. I've labeled accordingly.

**Comment by richsalz** [comment]
merged to both, thanks!

**Comment by t-j-h** [comment]
Why would we do this? It isn't auto-generated by a default make (nor should it be) and it is required to build. What am I missing?

**Comment by kaduk** [comment]
> Why would we do this? It isn't auto-generated by a default make (nor should it be) and it is required to build. What am I missing?

Commit 6a74806ed741db24df3a7155e4bc11fb4ba9bc2a caused it to be generated by a default make (and removed it from version control).

**Comment by levitte** [comment]
@t-j-h, #3688

**Pull request closed without merging**
