### PR TITLE
ecdsatest.c is missing handling of negative ECDSA_size #10485

### PR DESCRIPTION
**Pull request by coolshrid**
##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by coolshrid** [comment]
cla:

**Comment by mattcaswell** [comment]
Close/reopen to kick CLA bot.

**Comment by coolshrid** [comment]
#11151

**Comment by t8m** [comment]
This is no longer relevant. Closing.

**Pull request closed without merging**
