### PR TITLE
Feature/quic server branch rebase

### PR DESCRIPTION
**Pull request by t8m**
Please review the fixup commits as they solve conflicts

### CODE REVIEW

**Comment by t8m** [comment]
> Hmmm. There are CI failures. Should we worry about that during the rebase?

Definitely. I'm looking at them

**Comment by nhorman** [comment]
so, I think thats an artifact of how I created this PR.  I did it mostly as an exercise to figure out how to do a rebase review.  Currently the PR is requesting a merge from my rebased branch to the feature/quic-server branch, which would definately break things all over the place.  I wasn't sure how to properly open the PR as theres no way to indicate that this is going to be a force push to the quic-server branch

**Comment by nhorman** [comment]
all the fixups match the ones I made in my branch

**Review by nhorman — DISMISSED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
It seems there is a conflict

**Comment by t8m** [comment]
The branch was rebased yesterday. I've just forgot to close this. Closing now.

**Pull request closed without merging**
