### PR TITLE
X25519 doc

### PR DESCRIPTION
**Pull request by snhenson**
##### Checklist

- [x] documentation is added or updated

##### Description of change

This adds documentation for the X25519 algorithm. This is straight forward and just uses the EVP_PKEY functionality for key derivation and key generation with no algorithm specific operations.

This has been added as a new "man4" manual page. There will be others to follow for other algorithms and engines. Some of them will have algorithm specific operations which should create appropriate links in man3: that will need to be checked/implemented when the need arises.

Someone check I didn't miss anything out when adding man4

### CODE REVIEW

**Comment by levitte** [comment]
With the new `man4`, which [convention](https://en.wikipedia.org/wiki/Man_page) are you using?  So far, I think we've followed the BSD section numbering, and with that numbering scheme, section 4 doesn't seem appropriate.

**Comment by snhenson** [comment]
The aim is to gather together the description of an algorithm and any associated macros in one place. Similarly for a specific ENGINE and its features (e.g. capi at some point).

@rich suggested man4 for this. There isn't a direct equivalent: we're describing an algorithm (or an ENGINE) which may not (as in this case) have any specific functions or macros tied to it. The only define associated with the algorithm is NID_X25519.

I'm open to alternative suggestions as to how to handle this.

**Comment by richsalz** [comment]
I suggested four, because it's where device-specific stuff goes.  And crypto-specific stuff seems similar.  The problem is that otherwise we really would have to vary depending on platform and that would kinda stink.

**Comment by levitte** [comment]
Not quite.  Section 4 (in the BSD numbering scheme) is "Special files (usually devices, those found in /dev) and drivers".  Algorithms are not that at all, and I find it hard to claim that engines should be there either.  I would rather suggest section 5 or 7.

**Comment by richsalz** [comment]
I don't care which number is picked.  Just make sure it is "reasonable" on all unix variants.
I think 4 is the best choice (having read the wikipedia page), but if you feel otherwise, fine.

**Comment by snhenson** [comment]
Update: used man7 instead of man4.

**Pull request closed without merging**
