### PR TITLE
configure: add no-ecxx build with Ed25519/Ed448 but without X25519/X448

### PR DESCRIPTION
**Pull request by xnox**
For cases when one only wants signature support.

Allowing build with Ed25519/Ed448 enabled without X25519/X448. All tests disabled, as if it was no-ecx build. Ideally pure Ed25519 tests should be turned back on.

### CODE REVIEW

**Comment by t8m** [comment]
I don't think we want so much fine-grained build time options. Why would such option be useful?

**Comment by xnox** [comment]
> I don't think we want so much fine-grained build time options. Why would such option be useful?

Because currently FIPS implementation guidance can support Ed25519 but not yet X25519. Thus for certification purposes one currently has to forgo both. With this option in place one can certify Ed25519. If/when/once NIST testing support X25519 this option will no longer be needed.

**Comment by xnox** [comment]
Given https://github.com/openssl/openssl/commit/759ab5984eb981f2dd165979a7abb950ddad81ae i'm not too sure anymore if this is correct.

**Review by paulidale — COMMENTED** [review]
The Ed tests really should be included.

**Pull request closed without merging**
