### PR TITLE
Fixes #8645: s_client starttls bug handling multiline reply

### LINKED ISSUE #8645: s_client starttls bug handling multiline reply
Openssl s_client using "-starttls ftp" does not correctly handle multi-line replies from FTP servers. This problem exists with openssl packages installed by admins, as well as openssl packages built from source, and with multiple versions of openssl. The bug exists in the source for s_client.c in this repository.

Sample command:
```
openssl s_client -starttls ftp -connect [server]:21
```

In all case I have encountered with an RFC595 compliant multi-line reply prior to AUTH TLS being sent, the read of the multi-line reply terminates prematurely and openssl s_cient fails to complete the connection setup to the server. .  The problem is a single line in s_client.c in the code that implements "-starttls ftp" --

In the block that starts with
```
case PROTO_FTP:
```
there is this line:
```
while (mbuf_len > 3 && mbuf[3] == '-');
```

The condition in that while loop will be false (and the loop will terminate) for any line that has at least 4 characters and does not have a '-' in the 4th position. In most cases I've seen, that's the second line in a multi-line reply. The correct ending condition is a line that starts with a 3 digit number AND has a space in position 4.

The line below reads an entire multi-line reply and only terminates when the final line of the replay has been read:
```
while (mbuf_len > 3 && (!isdigit(mbuf[0]) || !isdigit(mbuf[1]) || !mbuf(buffer[2] || mbuf[3] != ' ')));
```

I've spent months trying to debug my FTPS servers, only to find that the bug is in openssl.

### PR DESCRIPTION
**Pull request by ws0w**
Fixes #8645: s_client starttls bug handling multiline reply

No documentation has changed.
No tests added.

### CODE REVIEW

**Comment by paulidale** [comment]
What is the problem being addressed here?

**Comment by mattcaswell** [comment]
> What is the problem being addressed here?

See the description in #8645

**Comment by mattcaswell** [comment]
The travis red cross appears to be an unrelated problem in master.

**Comment by ws0w** [comment]
Why would it not qualify as trivial?

**Comment by mspncp** [comment]
> Why would it not qualify as trivial?

What is trivial and what is not, is itself a very nontrivial question. In order to avoid endless discussions, the OMC decided to draw the line very low: trivial is something like fixing some typos, changing indentation, adding a semicolon, and so on. Everything else, which requires a little thought to very its correctness is already non-trivial.

In this sense, I would agree with Matt that your change should be considered non-trivial.

The simplest solution would be if you could sign and send us the CLA, in particular if you intend to make further contributions (which we are looking forward to :-) ).

**Comment by mspncp** [comment]
> > What is the problem being addressed here?
> 
> See the description in #8645

_(Whoever will squash and merge this commit: please note that the commits were done using the web interface and don't have a proper commit message. Also, the `Fixes #8645` should go into the body not the title of the commit message)_

**Comment by richsalz** [comment]
@ws0w Note that "trivial" is no reflection on the thought or work involved. It is a legal term, referring to whether or not something is copyrightable. If it is trivial, then it is not copyright and no CLA is needed. If it is 'more than trivial' then you have to sign the CLA giving OpenSSL the rights to use your contribution. For further protection, the project requires (a) the author to assert "CLA: trivial" in their commit message, and (b) both reviewers to agree that it's trivial. For some other details, see https://www.openssl.org/policies/cla.html

**Comment by ws0w** [comment]
I just emailed a signed CLA to legal@opensslfoundation.org ... 

I can do a proper commit ... I think that would then require a new pull request?

Sound good?

**Comment by mspncp** [comment]
> I can do a proper commit ... I think that would then require a new pull request?

It is not necessary to create a new pull request. You can squash your commits locally and force push them.

Here is a rough description how to do it. If you want to learn more about squashing and (interactive) rebasing, see [Section 7.6 Git Tools - Rewriting History](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) from the Pro Git book.

I assume you have a local working copy, which you cloned from your ws0w/openssl repo. Since you committed to the `master` branch(*) of your clone, you need to update your local master branch first:

```
git checkout master
git pull
```

Now undo the last three commits as follows, 

```
git reset HEAD~3
```

which will leave the changes as uncommitted changes in your working copy. You can now commit your change them as a single new commit.


```
git commit -a
```

Now add your commit message, something like

```
s_client starttls: fix handling of multiline reply

Fixes #8645
```

_(Note the empty line between the title and the body of the commit message.)_

Since you rewrote the history of your local master branch, you need to add `--force` when pushing to your github repo:

```
git push origin master --force
```

GitHub will automatically notice the change and update the pull request's page.

Hope that helps.

_(*) Note: normally it is better to create a topic branch before adding commits, instead of using the `master` branch directly, because topic branches can be rebased more easily._

**Comment by ws0w** [comment]
@mspncp -- I followed your instructions.

I assume it takes some time for the CLA to be processed,

**Comment by mattcaswell** [comment]
Close/reopen to kick CLA bot.

**Comment by mattcaswell** [comment]
Hmmm....the email address used in the commit does not match the email address in the CLA so the clabot is still not happy. You can correct that using `git commit --amend --author emailaddresshere`

**Comment by ws0w** [comment]
@mattcaswell , I've fixed the email issue and it passed the cla-check.

**Comment by mattcaswell** [comment]
Needs second review.

**Comment by paulidale** [comment]
Merged to master and 1.1.1.  Thanks for the contribution.

**Pull request closed without merging**
