### PR TITLE
ssl_log_secret call in tls13_key_update

### PR DESCRIPTION
**Pull request by meins111**
Newly computed traffic secrets are now logged upon key update.
Straight forward code change.

One point for discussion however:
- SERVER_APPLICATION_LABEL (and CLIENT_APPLICATION_LABEL respectively) have a _0 postfix for the intial traffic key
- Should this postfix be incremented on key update? If so, there probably is the need for a new ssl variable, tracking the number of key updates - as this is no knowledge the tls13_key_update method currently has (or needs)

[Tests]
Test suites run fine under windows 32/64.
I was unable too find any tests directed at the entire callback / logging feature, so not sure were to start.

### CODE REVIEW

**Comment by hlandau** [comment]
I do not think the suffix of `_0` makes sense here. If adding the actual count is difficult, I'd be OK with `_N`.

We could also survey if any existing software has the ability to make use of these entries and what format they expect. For example, does NSS log these keys for TLS 1.3? Does Wireshark support them, and if so what does it expect?

**Comment by meins111** [comment]
> I do not think the suffix of `_0` makes sense here. If adding the actual count is difficult, I'd be OK with `_N`.
> 
> We could also survey if any existing software has the ability to make use of these entries and what format they expect. For example, does NSS log these keys for TLS 1.3? Does Wireshark support them, and if so what does it expect?

A quick look into wireshark code shows they are only searching for _0 in their key log file and [the nss log description page of mozilla](https://firefox-source-docs.mozilla.org/security/nss/legacy/key_log_format/index.html) also only describes _0.

So we must at least log _0 for the initial key and then _N for updates to not break stuff. I'll quickly look up whether m change is called for the initial key setup or only for the update...

**Comment by MILASTARX84** [comment]
POIOOMG. SO I CANT MAKE A SIMPLE CALL HAVE A SINFUL SEX LIFE WITH 1 MALE?

**Review by mattcaswell — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
@mattcaswell still OK?

**Review by hlandau — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
> Anything left to do from my end?

No. Thanks for the ping. I'll merge shortly.

**Comment by mattcaswell** [comment]
Squashed and merged to maser and 3.0. I resolved a trivial conflict when backporting to 3.0.

**Pull request closed without merging**
