### PR TITLE
minor Windows fixes [1.1.1]

### PR DESCRIPTION
**Pull request by vszakats**
- fix to use secure URL in generated Windows resources
- fix a potentially uninitialized variable
- fix an unused variable warning

CLA: trivial

### CODE REVIEW

**Comment by levitte** [comment]
There's no reason this should be 1.1.1 only.  I've labeled according to where I think this should go.

**Comment by mspncp** [comment]
I will merge to the branches @levitte suggested with the following slightly edited commit (in particular, the [1.1.1] removed from the title), if nobody objects within the next hours:

```
minor fixes for Windows

- fix to use secure URL in generated Windows resources
- fix a potentially uninitialized variable
- fix an unused variable warning

CLA: trivial
```

**Comment by mspncp** [comment]
The patch cherry-picks cleanly to 1.1.0 except for the fact that `BIO_bind()` did not exist yet (it was added in ebc0168384e). Since that conflict can be trivially resolved by reverting `b_sock2.c`, I would argue that this does not require a separate pull request. @levitte, do you agree?

**Comment by levitte** [comment]
Yes

**Comment by mspncp** [comment]
Done, thank you everybody!

**Pull request closed without merging**
