### PR TITLE
gcm-siv mode: add to FIPS provider

### PR DESCRIPTION
**Pull request by paulidale**
The AES-GCM-SIV mode ciphers are testable under FIPS.  Add them to the FIPS provider.

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
Add to OSSL_PROVIDER-FIPS.pod also
Looks good otherwise.

**Comment by paulidale** [comment]
Doesn't the catchall AES item cover this already?
No other AES cipher modes are listed separately there.

**Comment by slontis** [comment]
Does it need a self test?

**Comment by slontis** [comment]
I guess if it only lists AES then it is ok..

**Comment by paulidale** [comment]
Not sure on the self test, I suspect not.  We only test AES-128-ECB and AES-256-GCM currently.

Notably absent are self tests for XTS and CCM modes (amongst many).

**Review by slontis — APPROVED** [review]

**Comment by paulidale** [comment]
Not for 3.1 after all.  The AES-GCM-SIV code wasn't ported there.

**Review by hlandau — APPROVED** [review]

**Comment by tmshort** [comment]
I'm glad this was an easy update. :)

**Comment by paulidale** [comment]
merged after rebase and trivial conflict resolution

**Pull request closed without merging**
