### PR TITLE
Add configuration options to disable GMAC and KMAC.

### PR DESCRIPTION
**Pull request by paulidale**
They are still included by default.

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
I remember some voices in the team being ...  not so positive about added configuration options.
Also, I remember us talking about some future where all implementations would be *built*, but into smaller providers, possibly per algorithm, and them being selectively loaded; this would basically trade all these configuration options for run-time options.  With that in mind, is adding configuration options a good step forward?

I don't know the answer, but thought it better to ask and see where the team stands on this today.

**Comment by paulidale** [comment]
That's a good question.

The toolkit is getting bloated and lots of small providers will replicate the overheads (although it would allow much to be left out as well).

**Comment by paulidale** [comment]
Does anyone have an opinion on this?

**Comment by mattcaswell** [comment]
I do think we tend to add configuration options too easily. On the other hand config options to disable algos have always been present, so I'm kind of on-the-fence on this one.

**Comment by richsalz** [comment]
I think this is silly:
```
; wc providers/common/macs/*.c
  189   504  5595 providers/common/macs/cmac_prov.c
  226   612  6679 providers/common/macs/gmac_prov.c
  213   606  6357 providers/common/macs/hmac_prov.c
  541  1937 16756 providers/common/macs/kmac_prov.c
```

**Comment by paulidale** [comment]
What does file size matter here?  There are other algorithms which have disable options that are both smaller and larger.

**Comment by richsalz** [comment]
I'm not going to count lines, but I would be surprised if there were many no-XXX options that covered as few as 100 lines.  Most of the ones I am thinking of cover several hundred.

And what is the rationale behind wanting to do this?  There are no security weaknesses, patent issues, size/footprint issues, no need to reduce the ciphers offered in ClientHello, no national-standard-only, etc.  I think that covers all the reasons we've used before.

**Comment by paulidale** [comment]
The CMAC conditioning is already present -- that's the 189 line file and the smallest.  This is adding conditioning for GMAC and KMAC which are the two largest at 226 and 531 lines respectively.

**Comment by levitte** [comment]
Counting source lines is a pretty bad metric... I suppose you want to figure out the resulting object size (actual footprint being a factor).

This discussion leads me to believe we might want to consider removing certain `no-xxx` options

**Comment by paulidale** [comment]
Agreed that LoC is a poor metric.  Everyone knows that all problems can be solved in a single line of APL or Snobol. 😀 

Perhaps something to discuss at the face to face?

**Pull request closed without merging**
