### PR TITLE
Update GOST engine commit to deal with test failure

### PR DESCRIPTION
**Pull request by beldmit**
Probably urgent as tests in master fail.

##### Checklist

- [ ] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
Agree urgent

**Review by paulidale — APPROVED** [review]
yes urgent

**Comment by paulidale** [comment]
and merged.

**Comment by paulidale** [comment]
Ought to merge this ASAP so we get a clean test run for the upcoming release.

**Comment by slontis** [comment]
Is this also indicating MAC OS tests are also a problem?

**Comment by paulidale** [comment]
There's an intermittent failure in that test I think.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by t8m** [comment]
@beldmit we have the same failure on 3.1 and 3.0. Should this be cherry-picked there?

**Comment by beldmit** [comment]
I think yes

**Comment by t8m** [comment]
@mattcaswell @paulidale OK to merge to 3.0, 3.1?

**Comment by t8m** [comment]
This is still urgent as on the 3.0 and 3.1 branches external test still fails.

**Comment by paulidale** [comment]
Yes, okay to merge.

**Comment by mattcaswell** [comment]
Yes, ok for 3.0 and 3.1

**Comment by mattcaswell** [comment]
Except it does not cherry-pick there. We'll need a new PR

**Comment by beldmit** [comment]
https://github.com/openssl/openssl/pull/21635

**Pull request closed without merging**
