### PR TITLE
bio.h: fix number of arguments passed to BIO_ptr_ctrl()

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by richsalz** [comment]
+1 for master and 1.1.0

**Comment by vszakats** [comment]
Interestingly, in the past I had submitted patch at least once to fix this exact same bug. It appears to be a notorious one.

Anything else required to get this merged?

**Comment by richsalz** [comment]
maybe @levitte or @mattcaswell can plus-one?

**Comment by mattcaswell** [comment]
+1

**Comment by richsalz** [comment]
sorry it got lost before.  this time we got it :)  commit c2efa78 in master.  backport to 1.1.0 stable shortly.

**Comment by vszakats** [comment]
No worries, thank you for the merges! :)

**Pull request closed without merging**
