### PR TITLE
Only the fips module dependencies are relevant for fips.module.sources

### LINKED ISSUE #15639: FIPS module sources include headers which are not really included
Some of the header files in the fips.module.sources are not really included if FIPS_MODULE is defined. The generator of fips.module.sources currently does not know how to exclude these.

Copying some discussion from #15622 

@paulidale:      

We could run the headers through the unifdef 
and then build the dependencies.  I suspect this would best be done by 
copying the sources before config.  The only other ideas I have involve 
parsing too much source code.
The fallback would be splitting files into FIPS relevant and not.  A big chunk of work.

@levitte:

Hmmm... it should be possible to fine tune exactly which .d files are being included to find header dependencies. It requires another configdata query function that lists the intermediary files (object files, among others), but that shouldn't be terribly hard to do. The raw information is available.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #15639

### CODE REVIEW

**Comment by t8m** [comment]
This fix doesn't have big effect currently but it should enable fine-tunning of the included headers by placing `#ifndef FIPS_MODULE` around includes where appropriate.

**Comment by t8m** [comment]
It also nicely speeds-up the make fips-checksums target.

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Clever!

**Comment by paulidale** [comment]
Merged.

**Pull request closed without merging**
