### PR TITLE
CertificateVerify tests

### PR DESCRIPTION
**Pull request by tomato42**
add test coverage for https://github.com/openssl/openssl/issues/25298 (PR #25302)

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by vdukhovni** [comment]
What is the merge-base for this PR? Is it prior to new padding check PR being merged?

**Comment by tomato42** [comment]
I think they may be failing because of the combined changes in openssl and in tlsfuzzer, will need to debug it further but I'm afraid that https://github.com/openssl/openssl/issues/25277 will be messing up stuff with client certificates :/

**Comment by tomato42** [comment]
@vdukhovni OK, fixed, had to use a separate server configuration.
But that actually means that the logic for the brainpool sigalgs is reversed: they are sent in TLS 1.2 CR but are not sent in TLS 1.3 CR: that's what the `-s` option specifies for `test-tls13-certificate-verify.py`...

**Review by beldmit — APPROVED** [review]
LGTM. To increase the reviewability, it could be better to have a formatting change in a separate fixup commit IMHO

**Comment by beldmit** [comment]
Ping @openssl/committers for the 2nd review

**Comment by beldmit** [comment]
Ping @openssl/committers for the 2nd review

**Review by t8m — APPROVED** [review]

**Review by vdukhovni — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed to master. Thank you for your contribution.

**Pull request closed without merging**
