### PR TITLE
Document possible DRBG reseed issues

### LINKED ISSUE #5330: SSL_new returns NULL because openssl fails to re-open /dev/Xrandom when in chroot.
This bug was not observed on previous versions and seems introduced with commits:

08a65d9686b131cb4193feaaf1d5cef941fa349c and a93ba405b0327db9106f8f224112a2b64fb264e7

### PR DESCRIPTION
**Pull request by lukastribus**
Does not fix #5330 but tries to document it.

@mspncp @richsalz @kroeckx 

##### Checklist
- [x] documentation is added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
The longer I read this amendment to the documentation, the more I wonder whether it wouldn't be better to fix the `chroot()` problem instead of just documenting it. I.e., fix it by opening /dev/Xrandom early and keeping a file descriptor (unconditionally, without the need to reconfigure the application or call a special api). But I didn't have much time lately to tackle this problem.

**Comment by lukastribus** [comment]
@mspncp There is no doubt in my mind about that. I hope we don't need to this doc change at all.

**Comment by richsalz** [comment]
I'm not pleased about keeping an FD open, but I am not going to stand in the way of getting that into the codebase.

**Comment by paulidale** [comment]
#6432 is an attempt at keeping the FD open.

**Comment by mspncp** [comment]
> Before we continue going down the doc road I just want to emphasize that just because I'm suggesting doc improvements does not mean I agree with giving up on finding a technical solution within the library. I still do not think that documenting this and requiring the application to fail early is the best coarse of action, even worse is letting the end-user figure this out by himself (without early-failure).

> I also don't feel like there has been a discussion about why keeping the FD open is a bad idea (as opposed to open/and close it once an hour), or why that would not cover this case.

@lukastribus, it seems that by going through the effort of documenting the chroot misery, you managed to convince us to fix it :-).  Closing the ticket, because I think it is obsoleted by #6432.

**Pull request closed without merging**
