### PR TITLE
Add loongarch64 target for OpenSSL_1_1_1

### PR DESCRIPTION
**Pull request by shipujin**
add loongarch64 config for no-asm.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
This is within the exception for adding config targets.

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
We need to cherry-pick this to 3.0 as well to not regress there. @paulidale OK with that?

**Comment by mattcaswell** [comment]
> We need to cherry-pick this to 3.0 as well to not regress there. @paulidale OK with that?

It already exists there. This is just backporting it to 1.1.1

**Comment by t8m** [comment]
Ah right, I was looking at an old checkout of openssl-3.0 branch.

**Comment by t8m** [comment]
Merged to 1.1.1 branch. Thank you for your contribution.

**Pull request closed without merging**
