### PR TITLE
Mv include/openssl/conf_api.h to conf/conf_lcl.h

### PR DESCRIPTION
**Pull request by richsalz**
Private internal declarations only.

### CODE REVIEW

**Comment by levitte** [comment]
Doesn't matter, it's a public header.  This is for 1.2.0

**Comment by richsalz** [comment]
None of the functions were exported, so I could make a dummy file like ec.h  Okay?

**Comment by levitte** [comment]
You forget static libraries, they're available there.

Look, I agree that this header file should never have been made public, but now it is, and our policy is pretty strict in this regard.  I suggest a team vote at this point.

**Comment by kroeckx** [comment]
And if you make those internal functions only, please rename them not to start with `_CONF`

**Comment by richsalz** [comment]
Nope, I wasn't thinking about static libs.  Fine.  Sad, but fine.

**Comment by levitte** [comment]
For what it's worth, I pre-approve for 1.2.0

**Comment by richsalz** [comment]
Refreshing old PR's.  Also renamed ```_CONF_xxx``` to ```conf_xxx``` per @kroeckx.  Doing that turned up a "bug" -- two instances of SSL_add_conf_module, in both libcrypto and libssl).

Yes, I know this is for 1.2.0.

**Comment by levitte** [comment]
> Yes, I know this is for 1.2.0.

Please label it accordingly.

**Comment by richsalz** [comment]
I am closing this as the next release pledges to maintain compatibility.

**Pull request closed without merging**
