### PR TITLE
When configuring 'no-comp', zlib support should be disabled too [1.0.2]

### LINKED ISSUE #6241: ./Configure no-comp zlib-dynamic
`openssl-1.0.2o/Configure threads no-tls1_1 no-comp shared zlib-dynamic -DPURIFY --prefix=/usr
/local --openssldir=/etc/openssl linux-x86_64 && make depend && depend` calls eventually `cd apps && /usr/local/bin/gcc -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DPURIFY -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -o openssl openssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o srp.o -L.. -lssl -L.. -lcrypto -ldl` and this fails with:
```
/usr/local/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../x86_64-pc-linux-gnu/bin/ld: enc.o: in function `enc_main':
enc.c:(.text+0xfa1): undefined reference to `BIO_f_zlib'
```

Indeed, ../libcrypto.so does not export BIO_f_zlib and does not compile the files in crypto/comp/, where `BIO_f_zlib` is defined.  But the code in env.c requires `BIO_f_zlib()`, as ZLIB is defined.

While removing `zlib-shared` after `./Configure` does help, `./Configure` is supposed to fail when impossible combinations are used.

### PR DESCRIPTION
**Pull request by levitte**
Fixes #6241

### CODE REVIEW

**Comment by mattcaswell** [comment]
Wait...why? Isn't zlib support a libcrypto level thing, while no-comp is a libssl level thing? So it should be possible to have zlib whilst still compiled with no-comp

**Comment by levitte** [comment]
Because the zlib support was designed to be a 'comp' component, nothing else.  'comp' itself may be designed with libssl in mind, but it *is* also designed for general use.

**Review by mattcaswell — APPROVED** [review]
Ok.

**Comment by levitte** [comment]
Merged.

fe4fe67139bc1e1abb62035d9eb0992f614bf645 When configuring 'no-comp', zlib support should be disabled too

**Pull request closed without merging**
