### PR TITLE
Remove OPENSSL_memcmp.

### PR DESCRIPTION
**Pull request by paulidale**
After avoiding `OPENSSL_memcmp` for EC curve comparison, there are no remaining
uses in the source code.  The function is only defined in an internal header
and thus should be safe to remove for 3.0.0.

### CODE REVIEW

**Comment by beldmit** [comment]
LGTM.

**Comment by paulidale** [comment]
Merged to master.  Thanks guys.

**Comment by levitte** [comment]
So who's willing to complete the cleanup?  :wink:

Hint: `git grep CRYPTO_memcmp`

(if no one else will, I will)

**Comment by levitte** [comment]
Never mind that remark...  `CRYPTO_memcmp` is a public function.  But I do wonder if it serves a real purpose any more, or if we should alias it to `memcmp`...

**Comment by beldmit** [comment]
> Never mind that remark... `CRYPTO_memcmp` is a public function. But I do wonder if it serves a real purpose any more, or if we should alias it to `memcmp`...

At least some calls of it provide a constant-time comparison.

**Comment by levitte** [comment]
Ah!  I keep forgetting about constant time, thanks for the reminder.

**Comment by paulidale** [comment]
Would spelling out the constant time make sense?
I.e. `ossl_constant_time_memcmp` and leave `CRYPTO_memcmp` as a stub?

**Pull request closed without merging**
