### PR TITLE
Fix zlib BIO_METHOD for latest BIO_METHOD structure changes

### PR DESCRIPTION
**Pull request by mattcaswell**
Fixes a compilation failure in master when compiling with zlib-dynamic

### CODE REVIEW

**Comment by mattcaswell** [comment]
Merged. Thanks.

**Comment by kaduk** [comment]
Is the need for this patch indicative of a lack of test coverage from travis?

**Comment by richsalz** [comment]
Not travis, we can't afford to test every no-xxx combination there.  But we will be doing such a test on our servers via cron.

**Comment by kaduk** [comment]
> we can't afford to test every no-xxx combination there.

Understood.  I was thinking more of an "enable all the code" build, which I somehow thought there was already one of.

**Pull request closed without merging**
