### PR TITLE
MSC_VERS <= 1200 isn't supported; remove dead code

### PR DESCRIPTION
**Pull request by richsalz**
Based on comment from Andy at https://github.com/openssl/openssl/pull/4246#discussion_r135338931

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
Typo in the commit message,  it's _MSR_VER ( without S)
Please add a note about meaning of _MSC_VER <= 1200  i.e: Visual Studio 6 and anterior ...

**Comment by dot-asm** [comment]
I apologize for not approving it at the spot. I'm reluctant to take decisions [no matter how small] past certain hour, or rather when I start feeling groggy. And I am now, sorry...

**Comment by t-j-h** [comment]
Can you explain why you think vs6 is not able to be supported? What is the issue - Andy's comment has no details on that which I can see.

**Comment by levitte** [comment]
I'm wondering too...  this came kinda out of the blue.  When did we decide to discontinue support of VC6?  Or is a de-facto conclusion, that you've seen that the current source doesn't build?

**Comment by levitte** [comment]
Oh, [NOW](https://github.com/openssl/openssl/pull/4246#discussion_r135338931) I see where this is coming from!

**Comment by t-j-h** [comment]
That comment from Andy doesn't explain anything as I read it - it just states something. What am I missing?

**Comment by richsalz** [comment]
Andy can explain more later

**Comment by t-j-h** [comment]
-1

**Comment by dot-asm** [comment]
>  this came kinda out of the blue. When did we decide to discontinue support of VC6?

So assumption is that no matter how fancy C constructs you throw in, previous century VS6 should just be able compile it? If anything *this* comes out of the blue. If one cares that much, then one should exercise it once in a while, and nobody did [for *years*]...

> Or is a de-facto conclusion, that you've seen that the current source doesn't build?

Yes, this is de-facto conclusion. I don't recall exact details, but at some point I tried, failed miserably, looked at options how to fix it, and it was too much work. I don't think that even 1.1.0 can be compiled. Well, I can have another look now... [Though not now now, but a bit later.] In either case it's not inappropriate to *claim* that it's no longer supported, because vendor is not supporting it for even longer. As for omissions. iswhatever-s can be omitted, because we use internal/ctype. Omission in sha512 is likely to matter only in no-asm case (which should be a debugging option). Omission in ectest is for MIPS (have you seen working MIPS-based WINCE units lately?), and in worst case belongs in command line. Latter means that *if* despite all odds VS6 can compile the whole thing, it would be appropriate to do it through separate Configurations/80-vs6.conf with own command line options.

**Comment by dot-asm** [comment]
> -1

Oh! Then I suppose I don't have to have another look, @t-j-h will...

**Comment by levitte** [comment]
With all that explanation, I can certainly understand the reasoning, we can only go so far in supporting age old compilers.  *However*, maybe the minimum VC version that we support should be noted in `NOTES.WIN`, the same way that I documented a minimum version of DEC C in `NOTES.VMS`?

**Comment by richsalz** [comment]
@t-j-h are you satisfied:  Andy said he tried it, and it didn't work.  And VS6 is 20 years old.  Do you have a copy you can try?

**Comment by t-j-h** [comment]
Consider the -1 removed - even though what Andy said on the other stream was entirely different - basically he thinks it doesn't work but hasn't tried in ages - which is not the same as known to not work - which is how it was presented. VS6 was the last compiler release to support the Win9x range and I do have a copy of it - part of the joys of MSDN access.

**Comment by snhenson** [comment]
I have VC6. It complains about:
```
Command line warning D4002 : ignoring unknown option '-wd4090'
include\openssl/lhash.h(207) : warning C4022: 'OPENSSL_LH_insert' : pointer mismatch for actual parameter 2
```
all over the place but carries on. It then chokes on the IPV6 stuff (the headers for VC6 suggest it supports IPV6 but it has some parts missing). We used to have a way to override the IPV6 auto detect using `-DOPENSSL_USE_IPV6=0` but that doesn't seem to work properly any more. I think there is a way to fix IPV6 support in VC6 but I forget what it is: I always just overrode the autodetect.

**Comment by levitte** [comment]
We could reinstate `OPENSSL_USE_IPV6`, if that's desirable. Considering how long IPv6 and the modernised libraries (most of all the new name and address info functions) have been around, I'm dubious of such a change, but like I said, it can be arranged.

**Comment by snhenson** [comment]
Ideally we should check if fixing IPv6 support for VC6 is sufficient. Anyone know how? I'll check my archives, I can vaguely recall someone (maybe @dot-asm?) mentioning it in the distant past.

**Comment by dot-asm** [comment]
> even though what Andy said on the other stream was entirely different - basically he thinks it doesn't work but hasn't tried in ages - which is not the same as known to not work - which is how it was presented.

Well, as I said many times, I'm not good with [English] words, so I might be wrong interpreting this, but it appears to me that you make it sound like I base my statements on imagination. Then just prove me wrong, don't just tell that you have VS6, but *use* it. "He *thinks* it doesn't work but hasn't tries in ages"? But did *you* try to compile 1.1 even *once* with VS6? Has *anybody* [till now]? [Yes, there will be comment about Steve's experience.] I have tried at several "turning points". As far as I recall *at least* when shift to <inttypes.h> was performed, and when _WIN32_WINNT minimum was increased. I don't recall at which point I've chosen to not pop the question reasoning that since nobody seems to care it's just not worth dragging on. Windows 9x were mentioned. Really? Are you seriously suggesting that we should aim for Windows 9x? That ship has sailed long ago, with increases of _WIN32_WINNT minimum(\*), switch to winsock2... Forget about it. The only value VS6 has to offer [in my mind] is that it uses bundled c:\windows\system32\msvcrt.dll. "Bundled" means that you get it in bare-bones Windows installation. Note that you still do, yes, in Windows 10! So that shared[!] VS6 1.0.2 build still works out-of-the-box. I mean for all other VS versions you have to drag along version-specific VCRT DLLs, if you want to deploy shared build, but not with VS6.

(\*) Just in case. What does _WIN32_WINNT minimum have to do with Windows 9x? Thing is that Windows 9x has all the NT 3.51 symbols, with NT-specific calls being simply stubs that do nothing but return error. But you can start NT 3.51 binary on Windows 9x, you just have to pay attention to return codes or guard NT calls with run-time version check. [This was discussed in e_os.h.] So that even though there never was explicit Windows 9x target, accordingly set _WIN32_WINNT was substituting it.

**Comment by dot-asm** [comment]
> I have VC6. It ... carries on. It then chokes on the IPV6 stuff

Well, mine installation doesn't [choke on IPV6], but I have to say that I'm using it with some Platform SDK headers and libs, not ones that come with VS6 itself. But does it mean that you haven't actually got to compile crypto/ec? Or crypto/siphash in master? For starters, VC6 can't handle LL suffix in constants. But that's easy (it should be sufficient to omit it and let "auto-promote-till-suitable-type" standard rule play out). ecp_nistz256.c is a disaster. Ironically 1.0.2 version compiles fine [naturally in 1.0.2], so it's not like it was disaster from beginning, it "went bad" specifically in 1.1...

**Comment by richsalz** [comment]
Okay, I think Andy has given definitive reasons why this doesn't work and hasn't worked and why we shouldn't care.  I will merge this on Monday unless someone throws a -1 on this.

**Comment by dot-asm** [comment]
> fixing IPv6 support for VC6.

As just said, Platform SDK is the answer. In the context it might be worth noting that 1.0.2 even performs *run-time* probes for IPv6 support. This was removed in 1.1. "Run-time probes" means that you can compile with IPv6 headers yet execute binary code on system that doesn't support it. Even though it wasn't explicitly tested, but you should be able to take 1.0.2 binary back to NT 4.0. Just in case, what was explicitly tested at the time, was to take it back to Windows 2000.

**Comment by snhenson** [comment]
I didn't try and get past the IPv6 errors on master so it never got as far as crypto/ec etc. 

I noticed a reference to platform SDKs in my search for a fix. I'm just using the supplied VC6 headers at present and the whole installation is set up so it doesn't interfere with more recent stuff: I have a batch file that sets up the VC6 environment if I ever need to use it. 

For 1.0.2 it compiles fine with VC6 if I add -DOPENSSL_USE_IPV6=0 to override the IPv6 detection.

My comments BTW are just information. I have no strong feelings either way about VC6 not working on master.

**Comment by levitte** [comment]
> I will merge this on Monday unless someone throws a -1 on this.

-1 until someone adds a few lines on minimum version in `NOTES.WIN`

**Comment by dot-asm** [comment]
Even if despite all the odds we decide to revive VS6 support, the only possibly questionable omission is one in sha512. Once again, iswhatever undefs can and should be omitted, because we use internal/ctype.h. Omission in ectest.c is MIPS[!]-specific warning[!], non-existing user *will* survive. And I can confirm that modified sha512.c still passes the test [verified with 1.0.2 sha512t and by comparing out dgst -sha512 outputs for few files with "before" and "after" 1.0.2 openssl.exe binaries].

**Comment by richsalz** [comment]
Who knows *WHAT* the minimum supported version is?  Anyone?

**Comment by dot-asm** [comment]
> -1 until someone adds a few lines on minimum version in NOTES.WIN

Kind of -1 on this one :-) Well, question is why NOTES.WIN? When it comes to compiler versions aren't we de-facto exercise kind of a "Schrödinger's cat" principle? Do *we* actually have an alternative to this approach? I mean simply put [besides those we use regularly] we support compilers that work and we don't support those that don't, i.e. we don't know if it's supported till we actually "open the box". [Yeah, I know it's inadequate analogy with the actual thought experiment, it's just a fun way to view *our* problem.] Anyway, since we effectively exercise this approach, then why do we have to single out VS6? Besides, if we say VS6 is unsupported wouldn't it mean that next version is supported? And in such case wouldn't we be obliged to at least verify? Bottom line is that *if* anything needs to be said, then it should be said in general notes, and along "we make no actual promises that *all* legacy compilers work" line. It's not Windows-specific thing. Well, one can still mention VS6 as an *example*, but it would be a mistake to explicitly say that it's the one not supported [because as just implied, then we would formally have to compose list of not supported compilers, and do it ourselves, i.e. actively "open all the boxes" there are].

**Comment by dot-asm** [comment]
> Who knows WHAT the minimum supported version is?

The lines are not even contiguous. I mean if there is a compiler version (any compiler, not necessarily Windows or whatever) with bug that is triggered by our code, then do we actually have any other option but to claim it unsupported? Well, one can argue that we could find workaround, and we did in the past, but it's not sustainable path. *Everybody* would be better off if we simply claim it unsupported and force user to another compiler or version. Indeed, if our code triggers a bug, so could user's application code...

**Comment by levitte** [comment]
> Well, question is why NOTES.WIN?

Because details about Windows specifically.  I have no idea where else you'd want to document such a thing.

> Besides, if we say VS6 is unsupported wouldn't it mean that next version is supported? And in such case wouldn't we be obliged to at least verify?

Me, I've gone with likelyhood according to available docs.  For VMS, DEC C 7.1 is very much a breaking point, where a lot of functionality was brought in to make it C99 enough (frankly, it's close but no cigar).  I have *removed* quite a lot of code that dealt with pre-7.1 compilers, as well as code that specifically dealt with VAX C (a much older, and only somewhat ANSI C compiler), for very specific reasons: none of us has access to that compiler, more or less everyone has switched to DEC C and has upgraded to 7.1 or newer, and I see about zero problems "forcing" everyone else to upgrade to 7.1 minimum.

Another way to express things is that *do not* support any VS below version *x*, and for anything from *x* on, we do a "best effort" support, the way you expressed it.  Does that fit the bill better, documenting that we *know* that OpenSSL 1.1 can't be cleanly built with VS6, don't even bother trying?

**Comment by dot-asm** [comment]
> -1 until someone adds a few lines on minimum version in NOTES.WIN

Richard, you referred to NOTES.VMS, but it doesn't actually specify *retrospective* minimum requirement. What it essentially says that "we use version 7.1 *now* and assume that later versions should manage fine." Following this pattern NOTES.WIN would have to read "we use VS14[?one at appveyor?] and assume that *later* version should manage fine." Not more than that. Bottom line is that we can't pinpoint minimum version below one we currently and regularly exercise. So that there is contradiction is suggestion. In sense that we can't actually say anything specific about VS6 as you suggest, we can only write about current state of affairs. But such rigid statement would actually be a setback(\*), I'd say that "Schrödinger's cat" describes situation more adequately...

(\*) Such rigidness is presumably OK in "mono-cultural" case such as VMS, but the rest of the world is probably too dynamic to tolerate it.

**Comment by snhenson** [comment]
FWIW I added platform SDK to my VC6 env and it doesn't have IPV6 problems any more. I then saw similar issues to @dot-asm with LL suffix and ecp_nistz256.c. Hacking round those I get as far as the linker which chokes with unresolved `InitializeCriticalSectionAndSpinCount`

**Comment by dot-asm** [comment]
> I've gone with likelyhood according to available docs.

Now I'm confused. NOTES.VMS reads "We have only tested with DEC C (a.k.a HP VMS C / VSI C) and require version 7.1 or later." "Only tested" doesn't sound like "likelyhood according to available docs" at all.

> we do a "best effort" support

And this is not Windows-specific thing.

> documenting that we know that OpenSSL 1.1 can't be cleanly built with VS6

It's meaningful as an *example* of application of the general principle. Note that I'm not saying that we can't write anything, I just don't see why it has to be in NOTES.WIN.

**Comment by levitte** [comment]
@dot-asm, well, I'm going with "reasonably", even though that's not explicitely said in `NOTES.VMS`.  My personal test environment includes HP C 7.3 (Alpha) and VSI C 7.4 (Itanium)...  much fresher beasts than 7.1, but also knowingly compatible enough with 7.1 to make it reasonable to say that 7.1 is the breaking point.

But yeah, ok...  Windows, even with just Microsoft's compilers, might be diverse enough that it's impossible to view the compiler as a linear development forward from one version on.  Sad, but I can accept that.

With that, I take back my -1

**Comment by dot-asm** [comment]
> I just don't see why it has to be in NOTES.WIN.

More nuanced would probably be *if* we choose to state the obvious, why does it have to be NOTES.WIN?

**Comment by levitte** [comment]
> And this is not Windows-specific thing.

Err, I'm lost...  VS6 is Windows specific, isn't it?  If we're talking about something else, please enlighten me, or even better, *move the discussion to a different issue and not in a PR that deals with a VS6 specific issue*

**Comment by dot-asm** [comment]
> issues ... with LL suffix

I want to emphasize that "it should be sufficient to omit it and let "auto-promote-till-suitable-type" standard rule play out" doesn't actually mean that it *is* sufficient. I mean I don't know if it is *in fact* sufficient *here*, as it might trigger a compiler bug, or "auto-promote" rule doesn't even apply, I haven't checked...

**Comment by richsalz** [comment]
We use LL and changing our code and then testing to see if it works, just to support VS6, is definitely not worth it.  I put a note in CHANGES.

**Comment by dot-asm** [comment]
> Err, I'm lost... VS6 is Windows specific, isn't it?

"we do a "best-effort" support" isn't Windows-specific thing. What I'm trying to say is that *if* we choose to state the obvious, then it would be more appropriate to say it in general notes, *possibly* with reference to VS6 as an *example*.

**Comment by dot-asm** [comment]
> We use LL

Per language standard[!] we don't have to. Note that blake2b.c doesn't.

**Comment by richsalz** [comment]
merged, thanks.

**Pull request closed without merging**
