### PR TITLE
Following the license change, modify the boilerplates in include/ and crypto/include/

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Review by mattcaswell — CHANGES_REQUESTED** [review]
Actually not approved for this one. There are relevant travis failures.

**Comment by levitte** [comment]
Ah, darn, right, it depends on #7766, which was of course not in yet since I did it all in parallel.

A rebase at this point should help.

**Comment by levitte** [comment]
Okie, rebased, let's see if that makes things better

**Comment by levitte** [comment]
Travis seems happier!

**Review by mattcaswell — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

48f4ad7718498577af52878b9e8b0924d8faf83f Following the license change, modify the boilerplates in include/ and crypto/include/

**Pull request closed without merging**
