### PR TITLE
genpkey: introduce -verbose option to suppress output

### PR DESCRIPTION
**Pull request by pprindeville**
Other commands like 'req' support -verbose, so why not genpkey?

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by pprindeville** [comment]
> I think -verbose would be more appropriate here as well

@levitte I'm not sure I understand. So the `-verbose` flag would actually mean, "Don't be verbose"?  Would you want me to change `req` and `ca` to be consistent with that as well?

**Comment by levitte** [comment]
No, sorry if this was confusing. `-verbose` does mean "please be verbose", so introducing that flag does change the default verbosity.

**Comment by pprindeville** [comment]
Isn’t that violating The Rule Of Least Astonishment?

**Comment by pprindeville** [comment]
Well, I'll change it, but it doesn't seem like there's much of a quorum since (1) it was approved as it was with `-batch` (2) and no one else is chiming in to concur.

**Comment by petrovr** [comment]
Philip Prindeville wrote:
> Well, I'll change it, but it doesn't seem like there's much of a quorum since (1) it was approved as it was with `-batch` (2) and no one else is chiming in to concur.
OpenSSL: Both options batch and verbose are used by req and ca commands.

Generic: verbose usually manages details of information output and 
increase of level mean more  details.

Issue title is for "-batch" options . Option "batch" is already used by 
OpenSSL as " do not ask questions" and this is different from "control 
of information details", i.e. "verbose".

-1 for "batch"

**Comment by pprindeville** [comment]
The one failure looks like a Travis configuration issue.

**Comment by t8m** [comment]
I think we are truly sorry that we completely neglected this PR. IMO we still could merge something to suppress the progress output in genpkey in 3.0 if you are still interested. IMO the option should be done the other way around - i.e. it should be named -quiet and be off by default so the default is to still produce the progress output given the users are used to it and key generation can take quite some time. Would you be interested in rebasing and updating your PR in this regard?

**Comment by richsalz** [comment]
See #15249 just to pick this back up.

**Comment by pprindeville** [comment]
> I think we are truly sorry that we completely neglected this PR. IMO we still could merge something to suppress the progress output in genpkey in 3.0 if you are still interested. IMO the option should be done the other way around - i.e. it should be named -quiet and be off by default so the default is to still produce the progress output given the users are used to it and key generation can take quite some time. Would you be interested in rebasing and updating your PR in this regard?

Well, as stated originally, where such a control exists elsewhere, it's `-verbose` so I was trying to be consistent.

But at the end of the day, either way will allow me to complete my scripts.

**Comment by pprindeville** [comment]
Abandoning in favor of PR #15249 as this seems to be languishing anyway.

**Pull request closed without merging**
