### PR TITLE
Add a few more exclusions to the minimal footprint tests

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Add a few missing flags to the minimal tests:

no-rmd160 no-ocb no-ct no-async

### CODE REVIEW

**Comment by paulidale** [comment]
Is it worthwhile considering the `OPENSSL_SMALL_FOOTPRINT` define as well?

**Comment by bernd-edlinger** [comment]
Yes, OPENSSL_SMALL_FOOTPRINT is already included.

**Comment by paulidale** [comment]
Sorry, missed it.  Thanks for the clarification.

**Comment by bernd-edlinger** [comment]
Absolutely no problem, I am still looking for more options to get a smaller footprint...

**Comment by bernd-edlinger** [comment]
I used 1.1.1-stable:
```
$ ./Configure linux-generic32 no-shared no-dso no-pic no-autoload-config no-engine no-comp no-cms no-dh no-dsa no-ec2m no-srp no-des no-mdc2 no-md4 no-rc2 no-rc4 no-bf no-camellia no-cast no-idea no-seed no-whirlpool no-ocsp no-sm2 no-sm3 no-sm4 no-ssl3 no-ssl3-method no-psk no-heartbeats no-nextprotoneg no-sctp no-srtp no-asm -DOPENSSL_SMALL_FOOTPRINT -Os -fno-asynchronous-unwind-tables
$ make
$ ls -la *.a
-rw-rw-r-- 1 ed ed 2978156 Sep 24 21:51 libcrypto.a
-rw-rw-r-- 1 ed ed  722120 Sep 24 21:51 libssl.a
$ ls -la apps/openssl
-rwxrwxr-x 1 ed ed 1924372 Sep 24 21:51 apps/openssl
$ ./config no-shared -Os -fno-asynchronous-unwind-tables
$ make
$ ls -la *.a
-rw-rw-r-- 1 ed ed 4547874 Sep 24 21:54 libcrypto.a
-rw-rw-r-- 1 ed ed  796440 Sep 24 21:54 libssl.a
ed@w-ed:~/OPC/openssl$ ls -la apps/openssl
-rwxrwxr-x 1 ed ed 2848984 Sep 24 21:54 apps/openssl
```
That is not too bad, but someone should give me 130K back
that 1.0.2 was smaller.

**Comment by richsalz** [comment]
What size ```size``` say?  Symbol tables counted in the ```ls``` command.

**Comment by bernd-edlinger** [comment]
Yes, but no debug symbols, and no unwind tables, by the config options.
Nevertheless one can see a difference, and I wish it was possible to configure
openssl more to match our needs here.
FWIW openssl 3.0.0 goes completely in the wrong direction, being larger and slower at
the same time. Coincidentally the openssl speed command is broken on master as well,
so you cannot get correct numbers at all.

**Comment by mspncp** [comment]
> FWIW openssl 3.0.0 goes completely in the wrong direction, being larger and slower at the same time.

If you are concerned about that (me too), you might want to open a separate issue for that.

**Comment by paulidale** [comment]
#9801 was an attempt to start conditioning out code, but wasn't all that well received.

In theory a provider could be made that only contains the desired implementations and the default provider omitted.  This ought to get the size down.  Calls that rely on missing functionality would fail at run time rather than causing a link time error.

**Comment by richsalz** [comment]
I am curious about the speed impact, since crypto algorithms didn't change.  The fetch() overhead is now noticeable?  It should be possible to avoid that with some tuning/caching. (right @paulidale? :)

I guess we need profiling and speed testing to see where the slowdown is.

**Comment by bernd-edlinger** [comment]
Regarding the performance regression, see:
https://github.com/openssl/openssl/pull/9674#issuecomment-524356954
https://github.com/openssl/openssl/pull/9674#issuecomment-524488000

I have not tried if the numbers changed recently, but I would be surprised if...
I am quite busy with other things as openssl, so something might have
changed, in the mean time @slontis ?.

**Comment by paulidale** [comment]
@slontis identified the problem that causes the slow down: `EVP_CIPHER_CTX_block_size` isn't a cheap call anymore.  We need to implement some form of caching of constants to get this back.  We've a fair idea how this needs to be done, it is now a question of finding time to do it properly.

As @richsalz wrote, there will be more overhead on the fetch/setup but the algorithms themselves should run just as fast.

**Comment by bernd-edlinger** [comment]
Reopened, to see if this still builds

**Comment by bernd-edlinger** [comment]
issue was resolved recently

**Pull request closed without merging**
