### PR TITLE
QUIC: Fix incompatible merges causing CI breakage (urgent)

### PR DESCRIPTION
**Pull request by hlandau**
Fix CI breakage in master caused by interaction of two different PRs. Urgent due to CI breakage.

### CODE REVIEW

**Review by tom-cosgrove-arm — CHANGES_REQUESTED** [review]
CI looks relevant, but I don't understand - there are 9 arguments now

```
test/quicapitest.c:813:57: error: too few arguments to function call, expected 9, have 8
                                                    NULL))
```

**Comment by hlandau** [comment]
@tom-cosgrove-arm I think the CIFuzz run must be testing against master rather than this PR. Possibly this was an oversight and it hasn't been testing PRs properly. We should fix that at some point if so. In any case, doesn't seem relevant here.

**Review by tom-cosgrove-arm — APPROVED** [review]
Okay with caveat about CIFuzz

**Review by beldmit — APPROVED** [review]
Agree urgent, LGTM

**Comment by beldmit** [comment]
Merged. Thanks!

**Pull request closed without merging**
