### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by primemaster**
Fix some of the "a ec key" occurrences. There are more places where "a EC*" is used. Shall those also be changed, or is there a rule where "a EC*" is correct?

##### Checklist
- [ ] documentation is added or updated

### CODE REVIEW

**Comment by t8m** [comment]
> Shall those also be changed, or is there a rule where "a EC*" is correct?

IMO these occurrences are also incorrect and should be fixed.

**Review by mattcaswell — APPROVED** [review]

**Review by t8m — APPROVED** [review]
I agree with CLA: trivial.

**Comment by t8m** [comment]
@mattcaswell Do you agree with CLA: trivial?

**Review by paulidale — APPROVED** [review]
Yes, trivial

**Comment by paulidale** [comment]
Merged to master, thanks for the typo fixes.

**Pull request closed without merging**
