### PR TITLE
Remove a statement saying 3.4 is in development in NEWS.md

### PR DESCRIPTION
**Pull request by mattcaswell**
3.4 is about to be released and is no longer in development.

### CODE REVIEW

**Comment by mattcaswell** [comment]
I've put the "urgent" label on this since this is a "NEWS.md" update required for the release tomorrow.

**Review by levitte — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
I agree with urgent

**Comment by t8m** [comment]
I also agree with urgent.

**Review by Sashan — APPROVED** [review]

**Review by arapov — APPROVED** [review]

**Review by shahsb — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed to 3.4. Thanks for the reviews.

**Pull request closed without merging**
