### PR TITLE
Compile the right cmp test sources.

### PR DESCRIPTION
**Pull request by kiyolee**
Looks like there are typos compiling the wrong sources for a couple of new tests.
Note: both cmp_protect_test.c and cmp_msg_test.c cannot be successfully built on windows though.

CLA: trivial

### CODE REVIEW

**Comment by slontis** [comment]
Looking at the travis errors it looks like this would require a
> make update
to generate new error codes.. The generated files also need to be committed.

**Comment by slontis** [comment]
@DDvO

**Comment by DDvO** [comment]
Thanks for reporting and starting to fix this issue.

@Akretsch, there was a copy&paste error in `test/build.info` that hid some further oversights.

I've generated a branch that fixes also the error issue mentioned above:
https://github.com/mpeylo/cmpossl/tree/fix_cmp_msg_test

@kiyolee, can you take over these commits in this PR?
Or would it be better if I do an extra PR that subsumes the current one here?

**Comment by kiyolee** [comment]
Done merge. Windows build ok now. Is that enough?

**Comment by slontis** [comment]
Travis failure is not an issue related to this PR..

This still looks trivial to me..
The CLA tag needs to be part of the 'commit message' if this is still considered trivial.

**Comment by mattcaswell** [comment]
There is a "merge" commit in this PR. We don't allow those. Can you rebase and remove it?

**Comment by kiyolee** [comment]
Have I done the right thing now?

**Comment by mattcaswell** [comment]
> Have I done the right thing now?

Looks fine now. Although your commit seems to have disappeared entirely to be replaced by @DDvO's....which solves the CLA issue!

**Comment by mspncp** [comment]
ping: ready to merge

**Comment by t8m** [comment]
Merged as 6960cf646b3 bce58e7fc 9b2ffec6a0 to master.

**Pull request closed without merging**
