### PR TITLE
Try to fix intermittent CI failures in quic_multistream test

### PR DESCRIPTION
**Pull request by bernd-edlinger**
I am able to reproduce this locally by
```
./config enable-unstable-qlog && make -j8
while OSSL_RUN_CI_TESTS=1 strace -o trace.log -s 2048 -f make test TESTS=test_quic_multistream >console.log 2>&1; do I=$((I+1)); echo next run $I; done
```
the failure happens in 1 out of 100 runs, and can be fixed by this PR.
It seems to originate from script "dyn script" 24, 35 or 36
which seem to inject faulty session close packets.

### CODE REVIEW

**Comment by hlandau** [comment]
I don't think this approach is a good idea. Instead, we should fix this:

```
           QLOG_STR_LEN("reason", f.reason, f.reason_len);
```

Appears to be a spec bug. Created an issue: https://github.com/quicwg/qlog/issues/new

IMO the resolution for now is:

1. Log "reason" if it appears to be valid UTF-8
2. Log "reason_raw" (standardised name TBD, but this works for now) with hex-encoded raw string if "reason" does not appear to be valid UTF-8

**Comment by nhorman** [comment]
why change the key its stored against?  I agree that if the text of the reason isn't valid utf-8 it needs to be hex encoded to a string, but once thats done, it can still be recorded as the "reason" key, even if its not human readable.

**Comment by hlandau** [comment]
> why change the key its stored against? I agree that if the text of the reason isn't valid utf-8 it needs to be hex encoded to a string, but once thats done, it can still be recorded as the "reason" key, even if its not human readable.

Err no. Then if a UTF-8 reason string happens to be a valid hex string it would be ambiguous.

**Comment by bernd-edlinger** [comment]
> ```
>            QLOG_STR_LEN("reason", f.reason, f.reason_len);
> ```

This is by far not the only problem here.  This can also be affected, as my experiment below proves:
```C
        QLOG_STR_LEN("reason", tcause->reason, tcause->reason_len);
```
and I also wonder if this duplicated output is intentional:
```C
            QLOG_U64("error_code_value", f.error_code);
            if (f.is_app)
                QLOG_U64("error_code", f.error_code);
```
Could we output valid UTF-8 characters un-escaped so they stay readable,
and only escape invalid UTF-8 sequences?

FYI: with this patch I was able to reproduce all possible error cases in the first run:
```
diff --git a/test/quic_multistream_test.c b/test/quic_multistream_test.c
index 7c2e1a3d74..d7c172e488 100644
--- a/test/quic_multistream_test.c
+++ b/test/quic_multistream_test.c
@@ -2829,6 +2829,25 @@ static int script_21_inject_plain(struct helper *h, QUIC_PKT_HDR *hdr,
     if (!TEST_true(WPACKET_get_total_written(&wpkt, &written)))
         goto err;
 
+    if (h->inject_word1 == OSSL_QUIC_FRAME_TYPE_CONN_CLOSE_APP && len >= 3) {
+        buf[0] = 0x00; // error_code
+        buf[1] = 0x01; // reason_len
+        buf[2] = 0x80;
+        if (len > 7) {
+           buf[3] = OSSL_QUIC_FRAME_TYPE_CONN_CLOSE_TRANSPORT;
+           buf[4] = 0x00; // error_code
+           buf[5] = 0x01; // frame_type
+           buf[6] = 0x01; // reason_len
+           buf[7] = 0x80;
+       }
+    }
+    if (h->inject_word1 == OSSL_QUIC_FRAME_TYPE_CONN_CLOSE_TRANSPORT && len >= 4) {
+       buf[0] = 0x00; // error_code
+       buf[1] = 0x01; // frame_type
+       buf[2] = 0x01; // reason_len
+       buf[3] = 0x80;
+    }
+
     if (!qtest_fault_prepend_frame(h->qtf, frame_buf, written))
         goto err;
 
@@ -2850,11 +2869,11 @@ static const struct script_op script_21[] = {
     OP_S_BIND_STREAM_ID     (a, C_BIDI_ID(0))
     OP_S_READ_EXPECT        (a, "apple", 5)
 
-    OP_SET_INJECT_WORD      (QUIC_PKT_TYPE_1RTT, OSSL_QUIC_VLINT_MAX)
+    OP_SET_INJECT_WORD      (QUIC_PKT_TYPE_1RTT, OSSL_QUIC_FRAME_TYPE_CONN_CLOSE_TRANSPORT)
 
     OP_S_WRITE              (a, "orange", 6)
 
-    OP_C_EXPECT_CONN_CLOSE_INFO(OSSL_QUIC_ERR_FRAME_ENCODING_ERROR,0,0)
+    OP_C_EXPECT_CONN_CLOSE_INFO(0,0,1)
 
     OP_END
 };
```

**Comment by bernd-edlinger** [comment]
... and why was this \u escape with 4-digit numbers chosen in the first place?
Note: there are more unicode characters defined, than that form can represent.
See also: RFC-5137 https://datatracker.ietf.org/doc/html/rfc5137
which lists it under chapter 6. "Forms that Are Normally Not Recommended"

**Review by t8m — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
This was merged as an interim fix for the CI failures. If @hlandau has better fix, it can be later added and this fix adjusted/reverted.

Thank you for your contribution.

**Pull request closed without merging**
