### PR TITLE
ec: Add PPC64 vector assembly version of p521 field operations

### PR DESCRIPTION
**Pull request by martin-schwenke**
Only field multiplication and squaring (but not reduction) show a
significant improvement.  This is enabled on Power ISA >= 3.0.

On a Power 9 CPU an average 10% performance improvement is seen (ECHDE:
14%, ECDSA sign: 6%, ECDSA verify 10%), compared to existing code.

On an upcoming Power 10 CPU we see an average performance improvement
of 26% (ECHDE: 38%, ECDSA sign: 16%, ECDSA verify 25%), compared to
existing code.

There are some setup commits.  This includes one that updates `crypto/perlasm/ppc-xlate.pl` to do some register number hacking, allowing more readable Power perlasm to be written.

### CODE REVIEW

**Comment by martin-schwenke** [comment]
Note that I don't understand the Actions failure.  Our commits don't touch the files mentioned in the `check_update` `git diff` output.

**Comment by martin-schwenke** [comment]
Request for @amitay to ACK this because some of the commits carry his authorship and Signed-off-by: line.

**Comment by martin-schwenke** [comment]
This has been tested on IBM Power 9 and (pre-release) Power 10 systems.

The assembly was original hand-coded by Amitay. It is a fairly direct translation of `crypto/ec/ecp_nistp521.c:felem_mul()` and `crypto/ec/ecp_nistp521.c:felem_square()`.  Initial testing was done in a standalone test-harness/micro-benchmark, which is not included here.

The Perl wrapping is quite straightforward, it just abstracts out some common functions and (re)produce Amitay's code.

Testing has been done using `openssl speed ecdhp521 ecdsap521` to confirm the performance improvements and to (hopefully ;-) confirm correctness. I've confirmed that the current code falls back as expected to run the existing code using `OPENSSL_ppccap=0` (on a Power 9 box).

I've also run `openssl speed` across all algorithms (on a Power 9 box) to sanity check that there are no unexpected failures (with and without OPENSSL_ppccap=0).  I hope that this also shows that the `crypto/perlasm/ppc-xlate.pl` changes are backward compatible.

**Comment by amitay** [comment]
> Request for @amitay to ACK this because some of the commits carry his authorship and Signed-off-by: line.

This PR is fine by me.

**Comment by richsalz** [comment]
Is @amitay on the CLA list? If not, and if the comment thread above is acceptable to the project, does this mean that anyone on the CLA list can submit non-CLA work by other authors?

**Comment by mattcaswell** [comment]
> Is @amitay on the CLA list?

Yes.

> does this mean that anyone on the CLA list can submit non-CLA work by other authors?

No.

**Comment by richsalz** [comment]
Thanks @mattcaswell .

**Review by t8m — APPROVED** [review]
Just a casual review as I do not have a deep knowledge of PPC64 assembler.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the contribution.

**Pull request closed without merging**
