### PR TITLE
CMP: add subject of any provided CSR as default message sender

### PR DESCRIPTION
**Pull request by DDvO**
This is a minor improvement.

### CODE REVIEW

**Comment by DDvO** [comment]
Somehow, when I reloaded the page some 10 minutes ago, it automatically overrode the label changes by @t8m, so I had to restore them. Hope this weird thing is not a systematic bug that also happens elsewhere.

**Comment by mattcaswell** [comment]
2 reviewers now required so removing "approval: done"

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by DDvO** [comment]
Merged - thanks @t8m and @beldmit

**Pull request closed without merging**
