### PR TITLE
Add demos for sm4gcm and sm4ccm

### PR DESCRIPTION
**Pull request by zzl-360**
CLA: trivial

##### Checklist
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
This is certainly not something than we could accept with CLA: trivial. Please consider signing a CLA. https://www.openssl.org/policies/cla.html

**Comment by paulidale** [comment]
I also wonder what these demos provide beyond the existing AES-GCM and AES-CCM ones?

**Comment by zzl-360** [comment]
> I also wonder what these demos provide beyond the existing AES-GCM and AES-CCM ones?

these demos are for SM4 other than AES

**Comment by zzl-360** [comment]
> This is certainly not something than we could accept with CLA: trivial. Please consider signing a CLA. https://www.openssl.org/policies/cla.html

I has sent a ICLA to the email address

**Comment by mattcaswell** [comment]
ICLA has been received.

**Comment by paulidale** [comment]
> these demos are for SM4 other than AES

They aren't demonstrating anything new.  They simply change the cipher name.  Any programmer should be able to make this change quickly and easily.

Looking at the differences between the AES CCM demo and the proposed SM4 CCM demo, the functional change is converting _AES-192-CCM_ to _SM4-CCM_ in the two fetch calls:
```diff
-    if ((cipher = EVP_CIPHER_fetch(libctx, "SM4-CCM", propq)) == NULL)
+    if ((cipher = EVP_CIPHER_fetch(libctx, "AES-192-CCM", propq)) == NULL)
```
The rest of the changes are the test data, comments and prints.  Even there, the comments and prints are only changing _AES_ to _SM4_.  I simply do not think this is worthwhile as an additional demo.

Having duplicate demos increases the maintenance load without adding any value IMO.  There are a *lot* of ciphers and I see no point having a demo for each -- the surrounding code doesn't change.  As is the case here.

Each demo should attempt to highlight or do something different.


The full diff for reference:
```diff
--- sm4ccm.c	2022-02-09 09:00:58.520156244 +1100
+++ aesccm.c	2021-11-18 09:15:48.240769931 +1100
@@ -1,5 +1,5 @@
 /*
- * Copyright 2013-2022 The OpenSSL Project Authors. All Rights Reserved.
+ * Copyright 2013-2021 The OpenSSL Project Authors. All Rights Reserved.
  *
  * Licensed under the Apache License 2.0 (the "License").  You may not use
  * this file except in compliance with the License.  You can obtain a copy
@@ -8,7 +8,7 @@
  */
 
 /*
- * Simple SM4 CCM authenticated encryption with additional data (AEAD)
+ * Simple AES CCM authenticated encryption with additional data (AEAD)
  * demonstration program.
  */
 
@@ -18,17 +18,17 @@
 #include <openssl/evp.h>
 #include <openssl/core_names.h>
 
-/* SM4-CCM test data obtained from RFC8998 */
+/* AES-CCM test data obtained from NIST public test vectors */
 
-/* SM4 key */
+/* AES key */
 static const unsigned char ccm_key[] = {
-    0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98,
-    0x76, 0x54, 0x32, 0x10
+    0xce, 0xb0, 0x09, 0xae, 0xa4, 0x45, 0x44, 0x51, 0xfe, 0xad, 0xf0, 0xe6,
+    0xb3, 0x6f, 0x45, 0x55, 0x5d, 0xd0, 0x47, 0x23, 0xba, 0xa4, 0x48, 0xe8
 };
 
 /* Unique nonce to be used for this message */
 static const unsigned char ccm_nonce[] = {
-    0x00, 0x00, 0x12, 0x34, 0x56, 0x78, 0x00, 0x00, 0x00, 0x00, 0xab, 0xcd
+    0x76, 0x40, 0x43, 0xc4, 0x94, 0x60, 0xb7
 };
 
 /*
@@ -36,34 +36,27 @@
  * which can be authenticated using the generated Tag value.
  */
 static const unsigned char ccm_adata[] = {
-    0xfe, 0xed, 0xfa, 0xce, 0xde, 0xad, 0xbe, 0xef, 0xfe, 0xed, 0xfa, 0xce,
-    0xde, 0xad, 0xbe, 0xef, 0xab, 0xad, 0xda, 0xd2
+    0x6e, 0x80, 0xdd, 0x7f, 0x1b, 0xad, 0xf3, 0xa1, 0xc9, 0xab, 0x25, 0xc7,
+    0x5f, 0x10, 0xbd, 0xe7, 0x8c, 0x23, 0xfa, 0x0e, 0xb8, 0xf9, 0xaa, 0xa5,
+    0x3a, 0xde, 0xfb, 0xf4, 0xcb, 0xf7, 0x8f, 0xe4
 };
 
 /* Example plaintext to encrypt */
 static const unsigned char ccm_pt[] = {
-    0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xbb, 0xbb, 0xbb, 0xbb,
-    0xbb, 0xbb, 0xbb, 0xbb, 0xcc, 0xcc, 0xcc, 0xcc, 0xcc, 0xcc, 0xcc, 0xcc,
-    0xdd, 0xdd, 0xdd, 0xdd, 0xdd, 0xdd, 0xdd, 0xdd, 0xee, 0xee, 0xee, 0xee,
-    0xee, 0xee, 0xee, 0xee, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
-    0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xaa, 0xaa, 0xaa, 0xaa,
-    0xaa, 0xaa, 0xaa, 0xaa
+    0xc8, 0xd2, 0x75, 0xf9, 0x19, 0xe1, 0x7d, 0x7f, 0xe6, 0x9c, 0x2a, 0x1f,
+    0x58, 0x93, 0x9d, 0xfe, 0x4d, 0x40, 0x37, 0x91, 0xb5, 0xdf, 0x13, 0x10
 };
 
 /* Expected ciphertext value */
 static const unsigned char ccm_ct[] = {
-    0x48, 0xaf, 0x93, 0x50, 0x1f, 0xa6, 0x2a, 0xdb, 0xcd, 0x41, 0x4c, 0xce,
-    0x60, 0x34, 0xd8, 0x95, 0xdd, 0xa1, 0xbf, 0x8f, 0x13, 0x2f, 0x04, 0x20,
-    0x98, 0x66, 0x15, 0x72, 0xe7, 0x48, 0x30, 0x94, 0xfd, 0x12, 0xe5, 0x18,
-    0xce, 0x06, 0x2c, 0x98, 0xac, 0xee, 0x28, 0xd9, 0x5d, 0xf4, 0x41, 0x6b,
-    0xed, 0x31, 0xa2, 0xf0, 0x44, 0x76, 0xc1, 0x8b, 0xb4, 0x0c, 0x84, 0xa7,
-    0x4b, 0x97, 0xdc, 0x5b
+    0x8a, 0x0f, 0x3d, 0x82, 0x29, 0xe4, 0x8e, 0x74, 0x87, 0xfd, 0x95, 0xa2,
+    0x8a, 0xd3, 0x92, 0xc8, 0x0b, 0x36, 0x81, 0xd4, 0xfb, 0xc7, 0xbb, 0xfd
 };
 
 /* Expected AEAD Tag value */
 static const unsigned char ccm_tag[] = {
-    0x16, 0x84, 0x2d, 0x4f, 0xa1, 0x86, 0xf5, 0x6a, 0xb3, 0x32, 0x56, 0x97,
-    0x1f, 0xa1, 0x10, 0xf4
+    0x2d, 0xd6, 0xef, 0x1c, 0x45, 0xd4, 0xcc, 0xb7, 0x23, 0xdc, 0x07, 0x44,
+    0x14, 0xdb, 0x50, 0x6d
 };
 
 /*
@@ -75,7 +68,7 @@
 const char *propq = NULL;
 
 
-int sm4_ccm_encrypt(void)
+int aes_ccm_encrypt(void)
 {
     int ret = 0;
     EVP_CIPHER_CTX *ctx;
@@ -89,7 +82,7 @@
         OSSL_PARAM_END, OSSL_PARAM_END, OSSL_PARAM_END
     };
 
-    printf("SM4 CCM Encrypt:\n");
+    printf("AES CCM Encrypt:\n");
     printf("Plaintext:\n");
     BIO_dump_fp(stdout, ccm_pt, sizeof(ccm_pt));
 
@@ -98,7 +91,7 @@
         goto err;
 
     /* Fetch the cipher implementation */
-    if ((cipher = EVP_CIPHER_fetch(libctx, "SM4-CCM", propq)) == NULL)
+    if ((cipher = EVP_CIPHER_fetch(libctx, "AES-192-CCM", propq)) == NULL)
         goto err;
 
     /* Set nonce length if default 96 bits is not appropriate */
@@ -162,7 +155,7 @@
     return ret;
 }
 
-int sm4_ccm_decrypt(void)
+int aes_ccm_decrypt(void)
 {
     int ret = 0;
     EVP_CIPHER_CTX *ctx;
@@ -174,7 +167,7 @@
         OSSL_PARAM_END, OSSL_PARAM_END, OSSL_PARAM_END
     };
 
-    printf("SM4 CCM Decrypt:\n");
+    printf("AES CCM Decrypt:\n");
     printf("Ciphertext:\n");
     BIO_dump_fp(stdout, ccm_ct, sizeof(ccm_ct));
 
@@ -182,7 +175,7 @@
         goto err;
 
     /* Fetch the cipher implementation */
-    if ((cipher = EVP_CIPHER_fetch(libctx, "SM4-CCM", propq)) == NULL)
+    if ((cipher = EVP_CIPHER_fetch(libctx, "AES-192-CCM", propq)) == NULL)
         goto err;
 
     /* Set nonce length if default 96 bits is not appropriate */
@@ -235,10 +228,10 @@
 
 int main(int argc, char **argv)
 {
-    if (!sm4_ccm_encrypt())
+    if (!aes_ccm_encrypt())
         return 1;
 
-    if (!sm4_ccm_decrypt())
+    if (!aes_ccm_decrypt())
         return 1;
 
     return 0;
```

**Comment by paulidale** [comment]
OTC: **do we want what are essentially duplicated demo?**

**Comment by t8m** [comment]
I agree with @paulidale that this kind of additional demo is useless. I'd suggest, if there is still an interest of having some demo with the SM4 algorithm to do it with some different cipher mode that requires different handling than ccm/gcm.

**Comment by zzl-360** [comment]
maybe I cound add tests to https://github.com/openssl/openssl/blob/master/test/sm4_internal_test.c?

**Comment by paulidale** [comment]
It would be better to add tests to the test_evp suite: `test/recipes/30-test_evp_data/evpciph_sm4.txt`.
We prefer these scripted tests to ad-hoc ones.

**Pull request closed without merging**
