### PR TITLE
Clarify Oracle's license

### PR DESCRIPTION
**Pull request by kroeckx**
@paulidale: Do you agree that this clarifies the situation and that we can merge this?

### CODE REVIEW

**Comment by paulidale** [comment]
I'll pass on the changed version to legal and see what they think.

**Comment by kroeckx** [comment]
So my understanding is that we have the needed legal papers from Oracle to put it either under the existing OpenSSL license or the apache2 license. If legal has a problem with putting it like that, we could also just repeat the license text.

In either case, I think the current situation seems to indicate that there is no license, while we clearly do have one.

**Comment by richsalz** [comment]
Yes.

**Comment by paulidale** [comment]
I've heard back from legal, the location isn't an issue.  The only thing raised was the formatting of the copyright note itself.  The approved format is: 

> Copyright © [_year_,] _year_, Oracle and/or its affiliates. All rights reserved.

Where the first year is the first release and the second is the year of the most recent revision.  In this case it differs from what I added by including a single additional comma.  The `©` can be replaced by `(C)` or `(c)`.  Thus the correct text would be:

> Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved.

I.e. adding a comma after the `2017`.

With this proviso, I approve.

**Comment by paulidale** [comment]
I've taken the liberty of making the comma change in #3684.  I've also addressed this in all files.

**Comment by paulidale** [comment]
I forget to mention, this PR can be closed since the changes are in the other PR.

**Comment by t-j-h** [comment]
Closing as this is covered in #3684 now

**Pull request closed without merging**
