### PR TITLE
This fix shows actual Key Block size - to demonstrate the bug of wrong Key Block Size calculation

### PR DESCRIPTION
**Pull request by maximmasiutin**
CLA: trivial

This fix shows actual Key Block size when tracing to help demonstrate the bug described in #12007

[x] Tracing shows Key Block size

### CODE REVIEW

**Comment by t8m** [comment]
You're just adding new and new commits. You need to git reset --hard your repository to the upstream master branch and then you'll have the repository in clean state and can start over.

**Comment by maximmasiutin** [comment]
I have just reset. Thank you. Could you please see https://github.com/openssl/openssl/pull/12032 ?

Sorry.

Just let me know whether it is OK.

**Comment by maximmasiutin** [comment]
Is https://github.com/openssl/openssl/pull/12032 now OK?

**Comment by maximmasiutin** [comment]
I have just reset. Thank you. Could you please see https://github.com/openssl/openssl/pull/12032 ?

Sorry.

Just let me know whether it is OK.

**Comment by t8m** [comment]
Yeah, that one is OK from the git point of view.

**Pull request closed without merging**
