### PR TITLE
Refactor functions in testdsa.h

### PR DESCRIPTION
**Pull request by InfoHunter**
To reduce duplicated code

### CODE REVIEW

**Comment by InfoHunter** [comment]
Hm, I consider this as a hiccup of appveyor

```
Build started
git clone -q https://github.com/openssl/openssl.git C:\projects\openssl
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
Command exited with code 128
```

**Comment by InfoHunter** [comment]
I don't think it's necessary, wait for others' idea.

**Comment by levitte** [comment]
Nah, not terribly, 't was just an open question

**Comment by richsalz** [comment]
should i merge then?

**Comment by levitte** [comment]
Yeah, feel free :-)

**Comment by richsalz** [comment]
Commit 0848e01 in master.  Thank you!

**Pull request closed without merging**
