### PR TITLE
WIP: DRBG revival: Add and refactor FIPS DRBG random generator

### PR DESCRIPTION
**Pull request by mspncp**
This pull request is related to pull request #3789. It is not intended as replacement or amendment, but rather as an aid to review the code changes made in the initial commit 44e33d56e8a5b5ea14c852fcb8a5990bf86c1489 of pull request #3789 .

When I was trying to review the code changes, I was having a hard time, because many files from the openssl-fips module were added and heavily modified in a single step. As a consequence, the patch sets for files like drbg_lib.c (https://github.com/openssl/openssl/commit/44e33d56e8a5b5ea14c852fcb8a5990bf86c1489#diff-9181ac017a6177a5f2619f65c9b7a346) and drbg_rand.c (https://github.com/openssl/openssl/commit/44e33d56e8a5b5ea14c852fcb8a5990bf86c1489#diff-ba146dc430f478d551b0fe76a59b47de) contained no useful information about the essential changes compared to the original fips source code. The diff sets are just a big fat blob.

Comparing manually with the fips source was tedious, so I started to 'reverse engineer' Rich's initial commit and splitting it into smaller and understandable commits. The first five commits contain transformations which are trivial (no functional changes), but generate a lot of diff noise:

1. Add original source
2. Reformat
3. Rename/move and delete some sources
4. Rename some identifiers 
5. Merge two source files into one.

Only the last commit 9b17fb5cde02bc5e5761d2bef2f25bca3520049e contains true changes, i.e., the remaining changes to make this sequence of commits equivalent to the single commit  44e33d56e8a5b5ea14c852fcb8a5990bf86c1489 by Rich.

I share this "reverse engineered" commit as a pull request because it might be useful for other reviewers, but it is not intended to be merged. If you don't consider it useful, feel free to delete it ;-)

### CODE REVIEW

**Comment by mspncp** [comment]
Just a suggestion: Wouldn't it be a good idea for WIP patch requests, to add small assessable commits and refrain from force-pushing? This would make it much easier to follow the history and understand the changes. At the end of the  review process, before pushing to master, the history could be straightened out by squashing the commits as desired.

**Comment by mspncp** [comment]
CLA has already been signed for PR #1737

**Comment by richsalz** [comment]
Often it’s better to have individual commits.  Often it’s easier to have one and force/push.  ☺

**Comment by mspncp** [comment]
Obsolete, since #3789 has been closed.

**Pull request closed without merging**
