### PR TITLE
Make configdata.pm runnable and move all display of information there

### PR DESCRIPTION
**Pull request by levitte**
The "make variable" information displayed by Configure was selective
and incomplete, and possibly undesirable (too verbose).

Instead, we make configdata.pm and have the user run it to get the
information they desire, and also make it possible to have it perform
a reconfiguration.

Possibilities so far:

```
perl configdata.pm --dump               Displays everything (i.e. the
                                        combined output from
                                        --command-line, --environment,
                                        --make-variables and
                                        --build-parameters.
perl configdata.pm --command-line       Displays the config command
                                        line.
perl configdata.pm --options            Display the features, both
                                        enabled and disabled, and
                                        display defined macro and
                                        skipped directories where
                                        applicable.perl configdata.pm --envirnoment        Displays the recorded
                                        environment variables.
perl configdata.pm --make-variables     Displays the configured "make
                                        variables".
perl configdata.pm --build-parameters   Displays the build file and
                                        the template files to create
                                        it.
perl configdata.pm --reconfigure        Re-runs the configuration with
                                        the recorded environment
                                        variables.
```

--verbose can be used to have --reconfigure be a bit more verbose.

### CODE REVIEW

**Comment by levitte** [comment]
In WIP, 'cause I'm thinking that the display of disabled features could be moved to configdata.pm as well (it could display what's enabled too...)

**Comment by richsalz** [comment]
I like this, but I would rather see the existing options combined into one.  Because when someone has problems, we're going to need to see all the values.

**Comment by levitte** [comment]
Ah, that's a good point.  So something like `--configuration-data`, `-c` for short?

**Comment by levitte** [comment]
... and `--config-data` as a somewhat shorter variant...

**Comment by levitte** [comment]
BTW, I see nothing wrong in supporting both that and the other ones, but then demand `--config-data` when getting reports.

**Comment by richsalz** [comment]
Or --dump/-d ?

This is a generated perl script, so I don't have strong feelings about it.  But when would someone need part of the information and not all of it?  Shrug.  Side-note.

**Comment by levitte** [comment]
I've seen people look with interest at the "make variables" Configure currently output.  I've myself wanted to see the recorded environment, or just the configuration command line that was used (I've grepped for `perlargv`).  Why should anyone that just wants one piece of information have to wade through the rest, let alone scroll back to be able to see it?

`--dump/-d` work, I'll add it

**Comment by levitte** [comment]
Okie, --dump added!

**Comment by levitte** [comment]
I also moved the display of options to configdata.pm, so configuration itself becomes something like this:

```
$ ./config -d --strict-warnings no-err
Operating system: x86_64-whatever-linux2
Using implicit seed configuration
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
for linux-x86_64
Creating configdata.pm
Creating Makefile
```

**Comment by richsalz** [comment]
Yay!  So does running configdata by itself dump the config or list the options or say use -help or what?
:)

**Comment by levitte** [comment]
```
: ; ./configdata.pm 
Usage:
    Interactive:

      perl configdata.pm [options]

    As data bank module:

      use configdata;

```

**Comment by levitte** [comment]
Should probably say to use -help, shouldn't it?

**Comment by levitte** [comment]
I looked at what GNU's `config.status` with no arguments, and that's to recreate build files and config files...  I was actually pondering that, but that's a bigger operation that I'm not ready to take yet.

**Comment by levitte** [comment]
Changed to this with no arguments:

```
: ; ./configdata.pm 
You must give at least one option.
For more information, do './configdata.pm --help'
```

**Comment by levitte** [comment]
Documented, and am making the CIs show us a full dump as well.

**Review by richsalz — APPROVED** [review]
once the CI's pass.

**Comment by levitte** [comment]
I added a small note, and with that I'm done.  Reconfirm that last bit?

**Comment by levitte** [comment]
(note: I haven't tested on VMS yet, will do so now)

**Comment by richsalz** [comment]
reconfirm once the ci's pass

**Comment by levitte** [comment]
All CIs here seems satisfied...  or well, there's something very odd happening in Appveyor, but that's unrelated to this.  I've also verified that VMS is finally happy.  There were a couple of needed fixes, they are in the last two commits, would you mind confirming them as well?

**Comment by richsalz** [comment]
reconfirming my reconfirmation

**Comment by levitte** [comment]
Merged!  b1fafff631e1a10d96a45e4899667d0683a9ba09 to 7187f0e1ea22e63454ec46f128d669acf1128a8f

Thanks!

**Pull request closed without merging**
