### PR TITLE
Open ssl 1 1 1 stable

### PR DESCRIPTION
**Pull request by jdfore**
#

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
This looks like a mistake.

**Comment by jdfore** [comment]
No it's not

**Comment by mspncp** [comment]
What did you intend to do?

**Comment by jdfore** [comment]
Engage with openssl 1.1.1

**Comment by mspncp** [comment]
Sorry, I don't understand. Your reply makes no sense to me.

**Comment by kroeckx** [comment]
You tried to merge 1090 existing commits from 1.1.1-stable into master.

**Pull request closed without merging**
