### PR TITLE
Turn off HARNESS_VERBOSE

### PR DESCRIPTION
**Pull request by richsalz**
Experimenting with less HARNESS_VERBOSE verbosity in travis since we seem to get many "log too long, stopping build" errors these days.

### CODE REVIEW

**Comment by t8m** [comment]
Will this be good enough to find out from the log what is the cause for a test failure if there is one?

**Comment by levitte** [comment]
It will not.  There's a reason why we turned verbosity on...

**Comment by richsalz** [comment]
I'm not done yet. :) I forgot to add the WIP tag; I just did.

I think the full solution requires sving stdout/stderr to a file and dump them if the test fails, util/perl/OpenSSL/Test.pm

**Comment by levitte** [comment]
`util/perl/OpenSSL/Test.pm` is the wrong spot for this, it should be done with harness options in `test/run_tests.pl`.  I think there are such things...

**Comment by richsalz** [comment]
I will look for harness options, thanks.

**Comment by levitte** [comment]
If you look at [Test::Harness](https://metacpan.org/pod/Test::Harness#ENVIRONMENT-VARIABLES-THAT-AFFECT-TEST::HARNESS), you'll see info on the environment variable `HARNESS_OPTIONS`.  One of the options is `a<file.tgz>`, and might be the answer for our problems.

Now, how to make that file downloadable...  does Travis support that kind of artifact?

**Comment by richsalz** [comment]
I would modify our Test.pm to not redirect stdout/stderr, and instead ensure the ```a<file>``` option is set, and dump that file if the test fails.

**Comment by levitte** [comment]
Test.pm is the *wrong* place to do this.

**Comment by levitte** [comment]
BTW, I was wrong, you should look at  [TAP::Harness](https://metacpan.org/pod/TAP::Harness#runtests)...  if you read where I linked, there's this:

> If the environment variable `PERL_TEST_HARNESS_DUMP_TAP` is defined it should name a directory into which a copy of the raw TAP for each test will be written. TAP is written to files named for each test. Subdirectories will be created as needed.

**Comment by levitte** [comment]
Hmmm, `PERL_TEST_HARNESS_DUMP_TAP` wasn't the right thing to do, it seems...

**Comment by richsalz** [comment]
The only I/O redirection is in Test.pm, there is none in run_tests.pl (and futher Test.pm has had 16 changes), so I don't understand your objection to modifying it.

But if you're planning on fixing this with what you see as "the right way," that's great and I'll stop.

**Comment by levitte** [comment]
`HARNESS_VERBOSE` is handled by the TAP::harness code that's called in `test/run_tests.pl`. If you screw up the TAP output that Test::More and OpenSSL::Test provides, it will destroy the harness' function, because it relies on that output to see if tests have gone passed or failed, not the exit codes.

You need to read up on [TAP](https://testanything.org/)

**Comment by t8m** [comment]
Ideally the verbose output for a testcase would be printed to STDOUT only if the testcase failed. Unfortunately TAP::Harness does not support that.

**Comment by richsalz** [comment]
I started reading all the documentation you pointed to, and then trying to map it to what OpenSSL uses or 'mocks up' and, I gave up.  I am surprised that nobody has thought of creating a TAP harness option that only dumps verbose output on test failure, but I couldn't find it. It seems like it would be possible by using https://metacpan.org/pod/TAP::Harness::Archive but creating the necessary shims is beyond me.  (Yes, I could learn, I suppose, if I had enough time and interest, but I don't :)

If a significant number of travis builds are failing because the log is too big, then turning off the verbose output so that at least you get "passed/failed" indications makes sense. I offer this PR as an intermediate step unless/until someone does the item suggested in the first paragraph above.

**Comment by richsalz** [comment]
Removed WIP tag since I can't make further progress; up to the team to decide if this is useful.

**Comment by t8m** [comment]
One option would be to save the make test output (with HARNESS_VERBOSE) to a temporary file and then just cat it out in the travis recipe in case it fails.

**Comment by richsalz** [comment]
Read the whole comment thread, @t8m :)

**Comment by levitte** [comment]
Doing that, i.e `make test V=1 >tests.txt 2>&1` in the Travis script is of course possible, but if that was the original suggestion, that blew by me.

The question is, then, how to make that file downloadable... If someone can figure that out, that would be great.

**Comment by FdaSilvaYY** [comment]
Travis can manage artifacts deployment :
see https://docs.travis-ci.com/user/deployment/

**Comment by richsalz** [comment]
> Doing that, i.e ```make test V=1 >tests.txt 2>&1```

I suppose that is a possibility, but it makes it difficult to find specific test failures.

I was going for something more subtle: capture output of each individual recipe, and only dump it out if the test fails.

**Comment by paulidale** [comment]
An alternative might be to make the tests themselves less verbose.  There is a lot of unnecessary output.

**Comment by levitte** [comment]
Output seems unnecessary...  until a test fails, then you're going to curse the lack of output.

**Comment by levitte** [comment]
> I was going for something more subtle: capture output of each individual recipe, and only dump it out if the test fails.

That may make artifact upload harder...

I do have a solution for a single copy of all underlying output (what the harness parses).  I'm way too tired to submit it now, will do so tomorrow.

**Comment by levitte** [comment]
@FdaSilvaYY, thanks for the links.  Will read tomorrow...

**Comment by richsalz** [comment]
I wasn't going to  do *any* uploads.  If a test fails, the output shows in the log; if a test passes, no additional output.  I am surprised this is not supported by TAP.

**Comment by levitte** [comment]
Hmmmm. Maybe. That will probably depend on the [output Formatter](https://perldoc.perl.org/TAP/Formatter/Base.html), and most of all the Console formatter, which will have to be able to interrupt its progress counter. I will look.

**Comment by richsalz** [comment]
#9862 is the way to do thing; closing this.
But maybe https://github.com/openssl/openssl/pull/9854/commits/da980dd54516de6e617c371bbc0ee884562f54ea can be put into that?

**Comment by levitte** [comment]
> But maybe da980dd can be put into that?

Already there

**Pull request closed without merging**
