### PR TITLE
Enable FIPS in the Windows CI 64 bit shared build and fix related issues

### PR DESCRIPTION
**Pull request by t8m**
Hopefully this also fixes the newest AppVeyor CI build failures.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Tentatively marking as `severity: urgent`, if you disagree, just clear the label.

**Comment by t8m** [comment]
But @levitte should definitely look if I did not do something stupid in the run_tests.pl.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Agreed urgent.  Still want to wait for @levitte's opinion.

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
If you all agree on urgent, why was that label removed?

**Comment by t8m** [comment]
Not sure perhaps @paulidale misclicked. Merging.

**Comment by t8m** [comment]
Merged. Thank you for the reviews.

**Comment by paulidale** [comment]
It was just about at the 24 hour mark...

**Pull request closed without merging**
