### PR TITLE
crypto/initthread.c: fix misspelled OSSL_provider_init() in comment

### PR DESCRIPTION
**Pull request by mspncp**

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]

**Comment by t8m** [comment]
Hm... we usually do not do comment-only fixes in released branches. However this one is really misleading.

**Comment by mspncp** [comment]
I didn't add the labels, I would be content with master only. You decide.

**Review by mattcaswell — APPROVED** [review]
Approved for master. I would personally be fine with taking it back to 3.1/3.0 but it is explicitly against the the stable release updates policy which says:

> Only bug fixes, fixes for security issues, and end-user documentation additions and fixes are allowed in stable releases.

And in the text defining a end-user documentation it says:

> An end-user documentation is not:
> comments in the code (including public header files)

So, if we feel this is worth taking back to to 3.1/3.0 it will have to go OTC. I'm not sure its worth it, but if someone else want to add the OTC hold please feel free.

**Comment by tom-cosgrove-arm** [comment]
I don't think it's worth bothering OTC for this - I'll remove the labels

**Review by paulidale — APPROVED** [review]
Better might be a policy change....

**Comment by hlandau** [comment]
Merged to master. Thank you.

**Comment by mspncp** [comment]
Can this be cherry-picked to 3.2 as long as it is still in beta?

**Comment by mspncp** [comment]
Please reapprove if you agree that this can be cherry-picked to 3.2.

**Comment by mattcaswell** [comment]
I'm actually putting an OTC hold on this because I think there is an important principle here. Do we treat beta as a stable release? Or if not what rules apply to it?

**Comment by t8m** [comment]
**OTC: We treat beta as stable release. This is not a bug fix according to the stable releases policy.**

**Pull request closed without merging**
