### PR TITLE
Exit non-zero if find-doc-nits finds nits

### PR DESCRIPTION
**Pull request by richsalz**
Filter all output to a new &err() routine, which sets the global
exit status, $status.
Also, fix all subroutine definetions and references to be consistent;
no barewords.

This can be cherry-picked.  Has conflicts with #9729, which I will reconcile as this or that one get merged.

### CODE REVIEW

**Comment by levitte** [comment]
Since you had to mention "no barewords", I'll just point out that using `&` as a prefix for a complete normal function call is antiquated.  I vaguely remember that being much more norm with perl 3 or 4, back in the 90's.  Today, though, it's really only useful when the interpreter might misinterpret your function call (it doesn't misinterpret a bareword followed by an opening parenthesis as far as I know) or when you want to override a function's prototype.  So, er, those `&` in this script are pretty pointless.

(there's another use of `&` related to `goto`...  I'll let you read up on that on your own.  Hint: perlsyn)

**Comment by richsalz** [comment]
When I remove them I get errors like this:
```
; ./util/find-doc-nits -u
Too many arguments for main::err at ./util/find-doc-nits line 84, near ""trailing comma before - in NAME")
        "
```

So rather then delve into perl arcana, I'll leave things as they are :)

**Comment by levitte** [comment]
That's because `err` is prototyped with an empty argument list.

Unprototyped function definition:

``` perl
sub foo {
```
Prototyped function définition (no arguments):

``` perl
sub foo() {
```

Prototyped function définition (one scalar argument):

``` perl
sub foo($) {
```

So basically, what ends up happening is that the script defines prototyped functions, and then explicitly overrides those prototypes when calling those functions. That's bad perl.

So the correct move is to either remove the empty argument prototypes and let things happen dynamically, or fill them in with proper protypes that match the arguments we do pick out from `@_`. The latter is better, but not something we habitually do. Your pick

**Comment by richsalz** [comment]
Thanks for the tutorial!  I made all functions be non-prototyped "sub foo {" and pushed a new commit.

**Comment by levitte** [comment]
Cool.  Now, just as a matter of experience, try and remove those unnecessary `&` and see how that goes.

**Comment by richsalz** [comment]
Yes, sensei I will do that when I come back from vacation in about five days :)

**Comment by richsalz** [comment]
Rebased and remove the ampersands.

**Comment by richsalz** [comment]
BTW, once this is merged I have one more set of changes I want to do, which is to print out the "wrong" line when possible.  Some of those nit messages could really use context (e.g., 'all uppercase in subhead')

**Comment by richsalz** [comment]
ping for a second review.

**Comment by InfoHunter** [comment]
Pushed to master as fbad6e79fae1ed12c5d3b5611f490e75066adfad, thanks!

**Pull request closed without merging**
