### PR TITLE
Clean up/enhance memory allocation

### PR DESCRIPTION
**Pull request by tmshort**
free()/malloc()/realloc() were referenced multiple times

Added protection: extra memory is allocated at head and tail of
OpenSSL to track double-frees, stale pointers, buffer over- and
under- runs. This protection also keep track of the free and realloc
routines, such that application-defined allocation can be changed on
the fly.

The extra space is always added for the protect functionality. The
protect flag only impacts whether or not memory is checked when released.
This also means that the application-defined allocators can be
changed at any time; since they are always tracked.

Change customization to occur when there are no outstanding allocations.
This requires the counters to always be available.

Added "simple" functions to be the default allocators.

CRYPTO memory debug (i.e. tracking) now occurs even for application-
defined memory allocation.

Application-defined realloc() is no longer called for simple free()
or malloc() situations; the appliction-defined free and malloc routines
are called instead.

CRYPTO_realloc: FAILTEST() was being called an extra time when a simple
alloc was happening, leading to higher than expected failure rate

CRYPTO_realloc: |realloc_count| was being incremented when a regular
malloc or free was to occur, now it only counts actual realloc's

CRYPTO_zalloc: FAILTEST() was being called an extra time, leading to
higher than expected failture rate

##### Checklist

- [X] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
This guarantees that `free(OpenSSL_malloc(x)` and `OpenSSL_free(malloc(x)` will fail, preventing an application from using OpenSSL memory incorrectly.

**Comment by levitte** [comment]
You're almost at a point of reimplenting malloc() and friends.  It this point, we're not far away from making the implementation in terms of `brk()` or `sbrk()` (or corresponding, Windows doen't implement these as far as I understand, but VMS does!).

Personally, I've wanted to throw away our mdebug stuff for quite a while.  Generally speaking, the likes of valgrind or clang's sanitizers provide better information (our mdebug stuff *sucks* at backtraces).

**Comment by tmshort** [comment]
> You're almost at a point of reimplenting malloc() and friends. It this point, we're not far away from making the implementation in terms of brk() or sbrk() (or corresponding, Windows doen't implement these as far as I understand, but VMS does!).

Ah... "hack", when it would save a game by writing out it's data segment to disk, and reading it back in to restore... those were the days... _wakes up_

We already have a heap implementation in the secure memory allocator; combine these and yes, that's what you get. I agree that valgrind and other tools are good, but they are painful when trying to run them in a large (embedded in my case) system with custom allocators, where it's not easy to identify memory from particular subsystem.

The goal of this was to prevent applications from screwing with OpenSSL memory, and vice-versa. I may have gone a bit overboard with saving the free/realloc pointers, but it makes the system more robust.

**Comment by tmshort** [comment]
Actually, if I _REALLY_ wanted to go overboard, I could add the file:line or backtrace into the allocation itself. I've done this with other embedded systems...

**Comment by t8m** [comment]
The incompatibility of free/OPENSSL_free malloc/OPENSSL_malloc introduced by this will definitely break application software - of course only incorrectly written one, but anyway. Again something that might be acceptable for 3.0 release. But in general I am with @levitte opinion.

**Comment by tmshort** [comment]
@levitte no objection to tossing the mdebug stuff... But sometimes you want something lightweight to deal with the issues of double-free and buffer overruns. Valgrind in an embedded environment with a large application is sometimes unusable. Don't get me wrong, I like Valgrind.

**Comment by richsalz** [comment]
A side-note: one very good thing about the memdebug stuff is that it is easy to run the test suite and find memory leaks, it's a good 80/20 trade-off.

**Comment by richsalz** [comment]
https://github.com/openssl/openssl/issues/8864

**Comment by mattcaswell** [comment]
I *do* object to tossing mdebug. I find it very useful to be able to do "enable-crypto-mdebug" and run "make test" and figure out whether I broke something anywhere in the tests from a memory perspective. If we can find an easy alternative to that I'd be ok.

**Comment by levitte** [comment]
Compared to other tools, I find the mdebug stuff not very useful these days.  It something gives a backtrack of what lead to an allocation, but that requires cooperating code (i.e. calls to `CRYPTO_mem_debug_push` and `CRYPTO_mem_debug_pop`), and we don't do that consistently, and it has *no* capability such as valgrind's "so you're using this memory which appears to have been free'd over there" with corresponding backtraces, or other similar relationships between allocation and usage of memory.

(and to think the mdebug stuff was the code that gained me commit privs back in '99...  I'm splendid at being my own critic :wink:)

**Comment by mattcaswell** [comment]
> I find the mdebug stuff not very useful these days

I use it regularly.

**Comment by tmshort** [comment]
So, ignoring the removal of the mdebug stuff... Is this useful, with, or without additional changes?

**Comment by t8m** [comment]
You should at least consider making it a build time option given it slightly increases the memory footprint and forcing applications incorrectly mixing the allocation calls to crash.

**Comment by tmshort** [comment]
> and forces applications incorrectly mixing the allocation calls to crash.

That's what happens with the option parameter...

> ... `free(OpenSSL_malloc(x))` and `OpenSSL_free(malloc(x))` will fail

Which will happen without the protect parameter.

**Comment by tmshort** [comment]
Rebased, and removed API; now it's a configure-time option.

**Comment by tmshort** [comment]
Since I went back to the original `allow_customize` scheme, I removed the free and realloc pointers from the extra allocation. Fixed the CI, I hope, and updated comments/INSTALL.

**Comment by slontis** [comment]
> I _do_ object to tossing mdebug. I find it very useful to be able to do "enable-crypto-mdebug" and run "make test" and figure out whether I broke something anywhere in the tests from a memory perspective. If we can find an easy alternative to that I'd be ok.

Is there any way of running valgrind for all tests currently? Wouldnt that remove the need for mdebug?

**Comment by tmshort** [comment]
With #8867 committed, do we need this any more? Is there any desire for a "cleaned up" malloc implementation that this contains? I'm willing to remove the extra memory protection and just do the clean up work.

**Comment by tmshort** [comment]
Going to close this due to #8867

**Pull request closed without merging**
