### PR TITLE
Add OID for RPKI id-ct-signedChecklist

### PR DESCRIPTION
**Pull request by job**
Reference: https://datatracker.ietf.org/doc/html/draft-ietf-sidrops-rpki-rsc - Resource Public Key Infrastructure (RPKI) object profile for Signed Checklist (RSC)

OID listed under 'SMI Security for S/MIME CMS Content Type (1.2.840.113549.1.9.16.1)' https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#security-smime-1

LibreSSL also added this OID: https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libcrypto/objects/objects.txt.diff?r1=1.30&r2=1.31&f=h

CLA: Trivial

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM

**Review by slontis — APPROVED** [review]

**Comment by paulidale** [comment]
This has been submitted as _trivial_.  I'm okay with that.  Could someone else confirm too please?

**Comment by slontis** [comment]
Yes it is trivial.

**Comment by paulidale** [comment]
Merged to master.  Thanks for this.

**Pull request closed without merging**
