### PR TITLE
OPENSSL_init_ssl.pod: fix minor typo

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by levitte** [comment]
yeahok, +1, no question about it ;-)

**Comment by mattcaswell** [comment]
+1

**Comment by richsalz** [comment]
@levitte, @mattcaswell , one of you guys should pull it in :)

**Comment by levitte** [comment]
Oh, we've been waiting on each other?  Awright, I fix

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
