### PR TITLE
Set OPENSSL_ppccap_P global variable in fips provider context

### PR DESCRIPTION
**Pull request by sanumesh**
Call OPENSSL_cpuid_setup while loading fips provider so that the value of OPENSSL_ppccap_P global variable gets set with hardware capabilities

This is to address issue : https://github.com/openssl/openssl/issues/23979

CLA: trivial

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
What does bypassing the constructor (DEP) _init in providers/fips/self_test.c do?

**Comment by t8m** [comment]
This would be acceptable with `CLA: trivial`. Could you please amend the commit message body to add `CLA: trivial` on a separate line?

**Comment by paulidale** [comment]
> What does bypassing the constructor (DEP) _init in providers/fips/self_test.c do?

I don't think this bypasses the DEP.  It adds an additional constructor.
I suspect this would better be done by adding the initialisation call to the DEP.

**Comment by ZenithalHourlyRate** [comment]
> I suspect this would better be done by adding the initialisation call to the DEP.

Agreed. Check https://github.com/openssl/openssl/pull/24403#issuecomment-2114033810 and https://github.com/openssl/openssl/discussions/23978#discussioncomment-8985017. My opinion is to remove all `attribute constructor` and use explicit initialisation.  Now the constructor behavior differs among platforms (`!_WIN32`), toolchains (`GNUC`) and archs (`riscvcap.c`), and this PR adds another complexity by LDFLAGS `-Wl`, which is really hard to maintain.

Related snippets

https://github.com/openssl/openssl/blob/a6afe2b29a7b77956ef888653849f8cc38e39106/crypto/init.c#L55-L69

https://github.com/openssl/openssl/blob/a6afe2b29a7b77956ef888653849f8cc38e39106/crypto/riscvcap.c#L116-L122

https://github.com/openssl/openssl/blob/a6afe2b29a7b77956ef888653849f8cc38e39106/crypto/s390xcap.c#L109-L113

https://github.com/openssl/openssl/blob/a6afe2b29a7b77956ef888653849f8cc38e39106/crypto/armcap.c#L32-L44

https://github.com/openssl/openssl/blob/a6afe2b29a7b77956ef888653849f8cc38e39106/crypto/armcap.c#L59-L68

**Comment by ZenithalHourlyRate** [comment]
Another implicit path: https://github.com/openssl/openssl/discussions/23978#discussioncomment-9453410

**Comment by sanumesh** [comment]
> > What does bypassing the constructor (DEP) _init in providers/fips/self_test.c do?
> 
> I don't think this bypasses the DEP. It adds an additional constructor. I suspect this would better be done by adding the initialisation call to the DEP.

By adding this additional -binitfini in configuration file, we can ensure there is no modification done to fips provider code. 
By doing modification to initialization code in DEP _init , we may break fips certification leading to lab re-testing

**Comment by t8m** [comment]
This is really a mess. IMO we should clean it up properly (at least on the master branch).

1. The OPENSSL_cpuid_setup() should not be a constructor by itself.
2. In FIPS provider it should be explicitly called from OSSL_provider_init_int() before self tests are executed.
3. In libcrypto, there should be a common constructor (OS specific, but not arch-specific) that executes OPENSSL_cpuid_setup().

**Comment by slontis** [comment]
> If we have to modify the initialization code in DEP _init , we may break fips certification leading to lab re-testing

Unfortunately changing the config more than likely also breaks FIPS compliance. You cant just build however you want and still assume you are compliant (This is a deviation of the Security Policy instructions on how to build)
Also note that AIX is not a platform that was validated by OpenSSL.

**Comment by paulidale** [comment]
>     2. In FIPS provider it should be explicitly called from OSSL_provider_init_int() before self tests are executed.
>     3. In libcrypto, there should be a common constructor (OS specific, but not arch-specific) that executes OPENSSL_cpuid_setup().

These two are the way to go.

Using a constructor dodges the FIPS change issue but it will cause other problems.  I don't think we should do it.

**Pull request closed without merging**
