### PR TITLE
Delete misleading sentence in doc of sk_TYPE_reserve

### PR DESCRIPTION
**Pull request by InfoHunter**
That sentence is very internal, as discussed in:

https://github.com/openssl/openssl/pull/4559#issuecomment-338937093

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
I'm not convinced this sentence should be removed.  It seems reasonable to be able to say, "I'm done adding stuff, free up any unused memory".  This doesn't require knowledge of the internals and a rewrite of the stack data type such that there was no excess space would make this call a nop.

The reserve call seemed like a good place to put this functionality, rather than adding yet another API.

**Comment by kaduk** [comment]
It's also not entirely clear to me what the motivation is for removing this sentence.

**Comment by InfoHunter** [comment]
The original motivation is here: https://github.com/openssl/openssl/pull/4559#issuecomment-338937093

**Comment by mattcaswell** [comment]
I think this sentence should stay. It's actually a useful part of the API, i.e. call `sk_TYPE_reserve` to reserve some slots. If you don't use them all, free them up later using this capability. Closing this.

**Pull request closed without merging**
