### PR TITLE
Remove a pointless "#if 0" block from BN_mul

### PR DESCRIPTION
**Pull request by bernd-edlinger**
I stumbled over this if 0 block because it contains an unchecked BN_CTX_get,
and I think the code in this commented block is totally out-dated by now
and should be removed.

### CODE REVIEW

**Comment by richsalz** [comment]
There are a few of these in the crypto/bn directory as I recall (from my big cleanup of ifdefs).

@dot-asm often makes the point that this kind of thing is useful for documentation/hacking purposes.  I'm in favor of this PR, but would like him to approve it :)

**Comment by bernd-edlinger** [comment]
Yes, other if0-blocks are often more informative, like, code that would work as well but
is mis-compiled by certain compilers.
But here the code in the if0 block is not at all obvious if it works at all, and it contains
at least one real bug.

**Comment by t-j-h** [comment]
If it is going to remain then it needs to have a decent comment added to it as to its purpose.
i.e. so we don't look at it again and put in a pull request to remove it.

**Comment by bernd-edlinger** [comment]
Yes, and the usage of BN_CTX_get should be fixed even in a comment,
because there is always the possibility that the wrong pattern is learned
by people looking at the false conditional code and used elsewhere.

**Comment by dot-asm** [comment]
I'll merge...

**Comment by dot-asm** [comment]
I've added 1.0.2 label with intention to attempt cherry-pick. If it doesn't, then I'll let it be...

**Comment by dot-asm** [comment]
Merged to all intended branches. Thanks!

**Pull request closed without merging**
