### PR TITLE
Simplify dataflow in TEST_true/TEST_false to prevent

### PR DESCRIPTION
**Pull request by bernd-edlinger**
false positive GCC-7 warnings in clienthellotest.c

without this patch ./config --strict-warnings fails:
```
test/clienthellotest.c: In function 'test_client_hello':
test/clienthellotest.c:60:17: error: 'pkt2.curr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     PACKET pkt, pkt2, pkt3;
                 ^~~~
In file included from test/clienthellotest.c:20:0:
test/../ssl/packet_locl.h:36:20: error: 'pkt2.remaining' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     pkt->remaining -= len;
                    ^~
test/clienthellotest.c:60:17: note: 'pkt2.remaining' was declared here
     PACKET pkt, pkt2, pkt3;
                 ^~~~
In file included from test/clienthellotest.c:20:0:
test/../ssl/packet_locl.h:100:8: error: 'pkt3.remaining' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     if (PACKET_remaining(pkt) != num)
        ^
test/clienthellotest.c:60:23: note: 'pkt3.remaining' was declared here
     PACKET pkt, pkt2, pkt3;
                       ^~~~
In file included from test/clienthellotest.c:20:0:
test/../ssl/packet_locl.h:102:12: error: 'pkt3.curr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     return CRYPTO_memcmp(pkt->curr, ptr, num) == 0;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/clienthellotest.c:60:23: note: 'pkt3.curr' was declared here
     PACKET pkt, pkt2, pkt3;
                       ^~~~
In file included from test/clienthellotest.c:20:0:
test/../ssl/packet_locl.h:36:20: error: 'pkt.remaining' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     pkt->remaining -= len;
                    ^~
test/clienthellotest.c:60:12: note: 'pkt.remaining' was declared here
     PACKET pkt, pkt2, pkt3;
            ^~~
In file included from test/clienthellotest.c:20:0:
test/../ssl/packet_locl.h:35:15: error: 'pkt.curr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     pkt->curr += len;
               ^~
test/clienthellotest.c:60:12: note: 'pkt.curr' was declared here
     PACKET pkt, pkt2, pkt3;
            ^~~
cc1: all warnings being treated as errors
make[1]: *** [test/clienthellotest.o] Error 1
```

This is because test_true is an external function while 
PACKET_get_length_prefixed_1 is an inline function,
and thus gcc knows that the output is only initialized
if the function returns true.
So if TEST_true is an identity function the data flow
is correct, but if you don't know that, test_true could
always return true, and in that case undefined values
could be used, that is what the warnings are all about.

### CODE REVIEW

**Comment by levitte** [comment]
Why not simply initialize the offending PACKETs?

**Comment by bernd-edlinger** [comment]
That would also work, but it would of course defeat the warning when the initial value
is accidentally used, and also valgrind would no longer know that the initial value is
not really intended to be used.
In general I try to not initialize values, in order not to obscure such warnings, but
it is of course a matter of taste.

**Comment by richsalz** [comment]
Look at packettest.c, the cases where i had to initialize ```subpkt```   Does this fix those, too?

**Comment by bernd-edlinger** [comment]
Yes.

**Comment by levitte** [comment]
Generally, when there is the possibility for ambiguity, we initialize explicitely.  These tests are not here to test possible random values because of what happens to be in the stack...  If you truly want to test what happens when there's random crap for a value, feel free to initialize it explicitely with randomness.

**Comment by bernd-edlinger** [comment]
So you generally like the = {0} initializations better?

**Comment by levitte** [comment]
Yes

**Comment by levitte** [comment]
Or well, that's me personally...  but so far, that's the choice the team has made everywhere these kinds of warnings pop up, so...

**Comment by richsalz** [comment]
My view; I think that if the "inline" weren't there, the compiler would not complain so it's more like a compiler bug.

**Comment by bernd-edlinger** [comment]
The warning says only "may be " and how the TEST_true is designed,
that is impossible to fix in gcc.

**Comment by dot-asm** [comment]
Closing since #3328 is committed. Thanks.

**Pull request closed without merging**
