### PR TITLE
Use passed drbg, not global one

### PR DESCRIPTION
**Pull request by snhenson**
This fixes access of uninitialised memory errors in some tests. To see this either compile with enable-msan or run test/bntest under valgrind.

### CODE REVIEW

**Comment by kroeckx** [comment]
I understand this doesn't fix the TLS 1.3 problems. I have a branch that didn't have this problem anymore, but still has the TLS 1.3 problem.

**Comment by dot-asm** [comment]
As a reminder, to demonstrate that sanitizer problem is resolved in merge request, one can add `[extended tests]` to commit message :-)

**Comment by snhenson** [comment]
Yes TLS 1.3 issue seems to be a bit more subtle.

**Comment by snhenson** [comment]
It is indeed subtle, fix coming up.

**Pull request closed without merging**
