### PR TITLE
added cmcCA and cmcRA as per rfc6402

### PR DESCRIPTION
**Pull request by mcr**
This adds the OIDs for the cmcRA and cmcCA bits as defined by RFC6402 and used by RFC7030.
RA == Registration Authority

### CODE REVIEW

**Comment by mcr** [comment]
(CLA was submitted a few hours ago, probably still after EOD in London though)

**Comment by richsalz** [comment]
A large portion of the team is away in China this week, so there will be slower progress.  Your CLA is fine.

**Comment by paulidale** [comment]
Approved if the build failure isn't related.

**Comment by levitte** [comment]
Hmm, I can see considering this legally trivial, i.e not needing a CLA. After all, it's just teo lines actually added, the rest is (or should be) done automatically.

**Comment by levitte** [comment]
I couldn't look closely at the build failures, but a quick look tells me they are serious enough to deserve a closer inspection.

**Comment by dot-asm** [comment]
Red cross from travis is totally relevant. Even though make update returns success, it modifies obj_dat.h so that git diff --quiet returns failure.

**Comment by mcr** [comment]
Richard Levitte <notifications@github.com> wrote:
    > I couldn't look closely at the build failures, but a quick look tells me they
    > are serious enough to deserve a closer inspection.

I'm looking today.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by mcr** [comment]
make update in my tree does not seem to make any changes that git diff notices.
(Would a reference to make update in the "this file generated" text at the top be welcome? I puzzled that part through from other sources google found for me)
I've fought problems like this before where travis gets different results. Let me remove the --quiet on a private branch and see.

**Comment by mcr** [comment]
https://travis-ci.org/mcr/openssl/builds/279045050 is the same branch, from my repo with travis enabled. I can't see a problem.
Can we retry the travis build from https://travis-ci.org/openssl/openssl/jobs/276052401 ?

**Comment by levitte** [comment]
I suggest you do `make update` (from your build tree) and commit the resulting changes too.  The contents in this PR isn't enough...

**Comment by mcr** [comment]
@levitte, make update in my build tree does not update any other files.  I've distclean'ed, ./config again and tried make update again.

**Comment by FdaSilvaYY** [comment]
Any addition to `crypto/objects/objects.txt` file will trigger some changes to 
`crypto/objects/obj_dat.h` after running a 'make update'.

see https://github.com/openssl/openssl/pull/2759 as example

**Comment by mcr** [comment]
I rebased and tried again.

**Comment by snhenson** [comment]
Should CMC be capitalised in the long name?

**Comment by levitte** [comment]
The builds seem to be happy now.

**Comment by mcr** [comment]
Stephen Henson <notifications@github.com> wrote:
    > Should CMC be capitalised in the long name?

I will ask @pritikin


--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by richsalz** [comment]
@levitte is this good to go?  Want me to merge?  I approve

**Comment by levitte** [comment]
As far as I'm concerned, this is good to go. I'm out and about for the moment. Feel free to merge, or I will later tonight.

**Comment by richsalz** [comment]
Added to master, thank you!  Closing.

**Pull request closed without merging**
