### PR TITLE
Add test for EVP_PKEY_Q_keygen

### PR DESCRIPTION
**Pull request by t8m**
Test for #19736

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Remove `tests: deferred` label from https://github.com/openssl/openssl/pull/19736 when merging this.

**Review by hlandau — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by slontis** [comment]
@levitte - the windows buildbot platforms, currently seem to fail in multiple different ways - what is this testing that the GA CI cant do?

**Comment by slontis** [comment]
Not sure if this should go back to 3.0.. Could be classed as a feature.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
3.0 is fine, our policy is quite clear: _New tests and test cases are allowed only as part of a bug fix._

This fix this is testing was merged to 3.0, thus the test should be too.

_Should the fix have been merged?_ is a very different question that should have been raised there.

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches. Thank you for the reviews.

**Pull request closed without merging**
