### PR TITLE
Fix hash support in RSA (SHA512/224, SHA512/256, SM3)

### PR DESCRIPTION
**Pull request by rAndom69**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
"Add more digests to RSA" seems a better description.

**Comment by rAndom69** [comment]
> 
> 
> The implementation is incomplete. You're supposed to change `crypto/objects/objects.txt` and then run a `make update` to get the files you've touched correctly generated.

Actually objects are already added. That is why I call it fix. Unless I'm correct please point out what should be added to objects.txt

**Comment by InfoHunter** [comment]
> You're supposed to change crypto/objects/objects.txt

It seems that only changing `crypto/objects/obj_xref.txt` is adequate to include a new "algorithm combination"

**Comment by InfoHunter** [comment]
Is it really necessary to support RSA-SM3 combination? What is the consideration behind this?

**Comment by InfoHunter** [comment]
Besides, test cases and docs should be updated as well

**Comment by InfoHunter** [comment]
I think you need to follow what @levitte said:

> and then run a make update to get the files you've touched correctly generated.

It's lacking some changes of some automated generated files for those newly added `xref` objects.

Have you updated all the files in this PR manually or by `make update` already?

**Comment by InfoHunter** [comment]
> Have you updated all the files in this PR manually or by make update already?

I am sorry... I rechecked the code, other necessary changes are already made times ago, so there's no need to `make update` any more.

**Comment by rAndom69** [comment]
> 
> 
> Is it really necessary to support RSA-SM3 combination? What is the consideration behind this?

Well, there is OID for it so it's confusing at least why it should not work.

> 
> 
> Besides, test cases and docs should be updated as well

I'm not aware supported hash functions are mentioned anywhere.
Care to point me to existing test cases ?

**Comment by InfoHunter** [comment]
> Besides that we will need a functionality to "duplicate" some X509 properties

Do you mean something like `X509_dup()`?

**Comment by rAndom69** [comment]
> 
> 
> > Besides that we will need a functionality to "duplicate" some X509 properties
> 
> Do you mean something like `X509_dup()`?

Nope. We do MITM for TLS introspection. So we validate HTTPS chain of trust instead of the receiver (browser). However, HTTPS chain of trust has some other properties like hash functions which essentially say if it could be forged. So we take the "weakest" properties of such chain and sign certificate with our CA injected as trusted into the receiver. Thus the receiver sees some properties of previous HTTPS chain and can decide based on them whether those properties are acceptable (without us deciding what is correct for which receiver)

**Comment by InfoHunter** [comment]
> Care to point me to existing test cases ?

I meant that you'd better add some test cases into the `/test` directory to test the newly added 'RSA-hash' combinations - for instance, using RSA-SM3 to sign a piece of data...

For the documentation part, I think at least the `doc/man3/EVP_DigestSignInit.pod` should be updated since it mentions what signature algorithm supports what hash functions...

**Comment by paulidale** [comment]
Closing this.  It is a year stale and doesn't seem to be going anywhere.

**Pull request closed without merging**
