### PR TITLE
Fix typos found by codespell in openssl-3.0

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Only modify `doc/man*` in the [`openssl-3.0`](https://github.com/openssl/openssl/tree/openssl-3.0) branch.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
I presume typo fixes are allowed by [the stable release update policy](https://www.openssl.org/policies/technical/stable-release-updates.html) (as "end-user documentation [...] fixes")

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by shahsb — APPROVED** [review]

**Comment by shahsb** [comment]
LGTM

**Comment by t8m** [comment]
Merged to the 3.0 branch. Thank you for your contribution.

**Pull request closed without merging**
