### PR TITLE
Update expired SCT certificates

### LINKED ISSUE #15179: Test certificates will expire soon
While working on reproducible builds for openSUSE, some tests fail with expired certificates when setting the build date after 2022-06-01. Originally reported by Bernhard Wiedemann in [openSUSE bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=1185637). See also:

```
for cert in `find test -name \*pem` ; do openssl x509 -text < $cert | grep After |grep 2022 && echo $cert ; done 2>&1 |grep -A1 2022
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/ISIC_D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/WSNIC_D1_Issuer_ICA.pem
            Not After : Apr 13 10:00:00 2022 GMT
test/ocsp-tests/WKIC_D1_Issuer_ICA.pem
            Not After : Jun  1 00:00:00 2022 GMT
test/certs/embeddedSCTs1_issuer.pem
            Not After : Jun  1 00:00:00 2022 GMT
test/certs/embeddedSCTs1.pem
```

The verbose ouput of test `80-test_ssl_new.t` shows:
```
# ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:33
# [2] compared to [0]
# INFO:  @ test/ssl_test.c:34
# ExpectedResult mismatch: expected Success, got ClientFail.
# 139919277639040:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:ssl/record/rec_layer_s3.c:1543:SSL alert number 45
not ok 2 - iteration 2
```

Since the expiring date is a year from now, could you update these certificates?

### PR DESCRIPTION
**Pull request by t8m**
Fixes #15179

### CODE REVIEW

**Comment by mattcaswell** [comment]
Is it worth documenting somewhere how you generated these?

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
(Agree urgent)

**Comment by t8m** [comment]
@mattcaswell can you please re-approve.
Also please approve the 1.1.1 PR linked above.

**Review by mattcaswell — APPROVED** [review]
Reconfirm

**Comment by mattcaswell** [comment]
Why is there so much less in this PR compared to the 1.1.1 version?

**Comment by t8m** [comment]
> Is it worth documenting somewhere how you generated these?

I just renewed the existing cert with `openssl x509 -in <existingcert> -signkey <privatekey> -days 36500 -extensions v3_ca -out <newcert>`

**Comment by Bo98** [comment]
That'll be f9f3096fd26ade6c188ae878a627920c0ddbd803 rather than this one.

**Comment by DDvO** [comment]
> I just renewed the existing cert with `openssl x509 -in <existingcert> -signkey <privatekey> -days 36500 -extensions v3_ca -out <newcert>`

Well, due to leap years, 100 years lifetime would have been 24 days more :wink:

**Pull request closed without merging**
