### PR TITLE
Add a clang-7 build target with --strict-warnings

### PR DESCRIPTION
**Pull request by bernd-edlinger**
We need a clang-7 strict warnings build rule

### CODE REVIEW

**Comment by mspncp** [comment]
Would you mind cherry-picking 91f167f7b8880d80cb0b2f236a80c770ffef66de instead of adding a separate hack? Then it could be tested on-the-fly.

**Comment by bernd-edlinger** [comment]
Looks like I am trying to hit a moving target....
I am one step behind, I am currently trying to reproduce the error.
But it is as if the clang-7.0.0 which is used by travis changed since last week.
The problem here, is that I cannot reproduce the error with -Wno-extended-offsetof,
While https://godbolt.org/ clearly shows that -Wno-extended-offsetof -Werror fails
unless additional -Wno-unknown-warning-option is used.

**Comment by bernd-edlinger** [comment]
So, I propose the theory, that debian fixed the -Wno-extended-offsetof issue as well over the last days,
that would explain why your wrong 1.0.2 patch did not fail as it should have.

**Comment by mspncp** [comment]
> So, I propose the theory, that debian fixed the -Wno-extended-offsetof issue as well over the last days,
> that would explain why your wrong 1.0.2 patch did not fail as it should have.

Thanks for digging into this. Good catch!

**Comment by bernd-edlinger** [comment]
Ah, now the build fails with clang-7.0.0 as it should.

**Comment by bernd-edlinger** [comment]
out of WIP now.

**Comment by mspncp** [comment]
Finally I understand the root cause of my confusion: I misread your patch and thought you had _added_ the `-Wno-unknown-warning-option` flag in a6efd5ba854020bcb8a77d4d8e61d660092600d2. Instead you _removed_ the duplicate which I overlooked. Sorry for the inconveniences.

**Comment by bernd-edlinger** [comment]
Ping?

**Comment by bernd-edlinger** [comment]
Merged to master as 3119c84. Thanks!

**Pull request closed without merging**
