### PR TITLE
Doc: fix style

### PR DESCRIPTION
**Pull request by imba-tjd**
Current on the [website](https://www.openssl.org/docs/manmaster/man1/openssl-mac.html):

图片

I don't know how to build it. I hope the fix works.

### CODE REVIEW

**Review by shahsb — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Good catch!

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
I agree this is trivial.

@levitte - please confirm this is trivial

**Comment by levitte** [comment]
I agree that it's trivial

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Merged

master:
52a75f4088f2b2c59721152d9ec6ecf4d17c7e43 Doc: fix style

3.2:
3edd0c17334a16251c0f6a51e206f95c3ba5e94c Doc: fix style

3.1:
161e4ff5477a34235e3a0b8b8dae10137f1e3f7c Doc: fix style

3.0:
650cac22ed95430d15cff9b0ade9edce6c4145aa Doc: fix style

**Pull request closed without merging**
