### PR TITLE
Fix make update

### PR DESCRIPTION
**Pull request by mattcaswell**
The recent DTLS write record layer code and the certificate compression code both added new SSL_R_ reason codes. The numbers are conflicting due to rebase issues and causing make update to fail.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
Marking this as urgent since this is causing CIs to fail.

**Review by hlandau — APPROVED** [review]

**Comment by hlandau** [comment]
Agree urgent.

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
I agree urgent.  You're clear to merge

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
