### PR TITLE
Pass an EVP_PKEY for SSL_SECOP_TMP_DH in the security callback

### PR DESCRIPTION
**Pull request by mattcaswell**
The security operation SSL_SECOP_TMP_DH is defined to take an EVP_PKEY
in the "other" parameter:

````
 /* Temporary DH key */
 # define SSL_SECOP_TMP_DH                (7 | SSL_SECOP_OTHER_PKEY)
````

In most places this is what is passed. All these places occur server side.
However there is one client side call of this security operation and it
passes a DH object instead. This is incorrect according to the
definition of SSL_SECOP_TMP_DH, and is inconsistent with all of the other
locations.

Our own default security callback, and the debug callback in the apps,
never look at this value and therefore this issue was never noticed
previously. In theory a client side application could be relying on this
behaviour and could be broken by this change. This is probably fairly
unlikely but can't be ruled out.

### CODE REVIEW

**Comment by t8m** [comment]
Should Changes entry be added? I agree with this change and 1.1.1 backport as well.

**Comment by kaduk** [comment]
I think we should take this change, but agree with Tomáš that we should have a CHANGES.md entry (hence not pushing the 'approve' button).

**Comment by mattcaswell** [comment]
I added a CHANGES entry as requested.

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Review by kaduk — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed.

I inadvertently referred to this PR in the commit when pushing the 1.1.1 version. Should have been to #13137 instead.

**Pull request closed without merging**
