### PR TITLE
Check return value after loading config file

### LINKED ISSUE #10288: No checking return value of app_load_config() and app_load_config_bio() in apps/req.c
Found this with 1.1.1d.
apps/req.c doesn't check return value of app_load_config() and app_load_config_bio().
It should `goto end;` if req_conf or addext_conf is NULL.
If we provide invalid value for -addext, it shows "req: Error on line 1 of config input", but continues processing like below.

```
$ openssl version
OpenSSL 1.1.1d  10 Sep 2019
$
$ openssl req -new  \
> -addext "subjectAltName := test.com" \
> -newkey rsa:2048 -nodes -keyout key.pem -out req.pem
req: Error on line 1 of config inputGenerating a RSA private key
..........+++++
......................+++++
writing new private key to 'key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
```

### PR DESCRIPTION
**Pull request by kinichiro**
Fixes #10288

### CODE REVIEW

**Comment by InfoHunter** [comment]
The original issue #10288 mentioned this was found in 1.1.1d, so I think this also should be back ported to 1.1.1 branch.

**Comment by paulidale** [comment]
I'm okay with 1.1.1 too.

**Comment by paulidale** [comment]
Merged to master and 1.1.1, thanks.

**Comment by paulidale** [comment]
This change is trivial.

**Comment by InfoHunter** [comment]
Yes, I agree this change is trivial.

**Pull request closed without merging**
