### PR TITLE
Fixed typo in license text

### PR DESCRIPTION
**Pull request by madmason**

### CODE REVIEW

**Comment by levitte** [comment]
+1

**Comment by richsalz** [comment]
ah, this goes back to the original SSLeay license and comments we had about typo's when the text was in every source file.  We are *not* changing the ssleay license code.  The typo stays :(

**Comment by mattcaswell** [comment]
Unfortunately @richsalz is correct. We are unable to change the license text.

**Comment by levitte** [comment]
Ah, darn, didn't look closely enough...

**Pull request closed without merging**
