### PR TITLE
Fix stdio issues

### PR DESCRIPTION
**Pull request by levitte**
Fix all `no-stdio` issues found by #1399.

This branch is made on top of the #1399 one to take advantage of the `no-stdio` checks.  It also replaces #1400 and #1402 by assimilation.

### CODE REVIEW

**Comment by levitte** [comment]
I think I'm done.  Builds will tell.

**Comment by levitte** [comment]
Yup, all clear now

**Comment by richsalz** [comment]
+1
@dwmw2 will be happy :)

**Comment by levitte** [comment]
Cool. Thanks. I'll merge the lot later today

**Comment by levitte** [comment]
Merged (including the #1399 stuff)

**Pull request closed without merging**
