### PR TITLE
Add support for generarting Android 64-bit builds

### PR DESCRIPTION
**Pull request by gmetal**
This patch updates the Configure scripts, so that they can produce android 64-bit binaries, for the aarch64 and x86_64 architectures.

### CODE REVIEW

**Comment by brodybits** [comment]
Can we add mips64?

**Comment by csoon03** [comment]
Any updates on this pull request? We've been hoping to add support for 64bit in our app, and would appreciate any updates on this, thanks!

**Comment by eyalv** [comment]
Any update on this pull request?

**Comment by richsalz** [comment]
the config stuff in master is very different now.  can you look at this and #183 and rebase them?

**Comment by gmetal** [comment]
@richsalz the functionality provided by this patch appears to have been integrated into master. This patch only makes sense for openssl 1.0.2 branches only. If no more 1.0.2x branch builds are to be produced, it can be removed.

**Comment by richsalz** [comment]
so it's a feature, adding platforms.  so not for 1.0.2.  thanks!

**Pull request closed without merging**
