### PR TITLE
INSTALL.md: Remove trailing space

### PR DESCRIPTION
**Pull request by t8m**
This fixes regression from #19882

As this is a CI breakage, this is an urgent fix.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Review by tmshort — APPROVED** [review]
LGTM

**Review by beldmit — APPROVED** [review]
LGTM, agree urgent

**Comment by DDvO** [comment]
Was this really about trailing space?
https://github.com/openssl/openssl/pull/19882/files does not show any, and neither does `git show`.

Looks like the [error message in the CI output](https://github.com/openssl/openssl/actions/runs/3758037915/jobs/6385907858)
```
mdl -s util/markdownlint.rb .
./INSTALL.md:237: MD009 Trailing spaces

Further documentation is available for these failures:
 - MD009: https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md009---trailing-spaces
make: *** [Makefile:4160: md-nits] Error 1
```
is misleading.

**Comment by t8m** [comment]
@DDvO there was a trailing space. Try selection on the `Files changed` view in this PR and you'll see it.

**Comment by DDvO** [comment]
> @DDvO there was a trailing space. Try selection on the `Files changed` view in this PR and you'll see it.

Strange, I still cannot see it:
image

**Comment by tmshort** [comment]
The training space is at the end of `"down "`. Because the word `"both"` was appended to that line, that effectively removed the trailing whitespace.

**Comment by DDvO** [comment]
Hmm, that's subtle.
Yet still I'd say the whitespace should be displayed explicitly at the end of the first line with red background.
When I display diffs in the shell where, e.g., a newly added line has trailing whitespace,
this whitespace is clearly shown, even in strong red.

Yet even at https://github.com/openssl/openssl/pull/19882/files the trailing whitespace was not shown,
so reviewers had little chance spotting it.

**Comment by t8m** [comment]
You can submit that to GitHub as RFE.

**Comment by DDvO** [comment]
Can you point me to the issue tracker of GitHub itself?

**Comment by t8m** [comment]
There is https://github.com/orgs/community/discussions

**Comment by DDvO** [comment]
Posted issue at https://github.com/orgs/community/discussions/42792

**Review by yasoo655 — APPROVED** [review]

**Pull request closed without merging**
