### PR TITLE
Constify some code about X509_VERIFY_PARAM

### PR DESCRIPTION
**Pull request by FdaSilvaYY**

### CODE REVIEW

**Comment by richsalz** [comment]
commit 81f9ce1 in master.  Bug, push to 1.1.0?

**Comment by kaduk** [comment]
> push to 1.1.0

Changing function return type from char* to const char* breaks the API...

**Comment by richsalz** [comment]
Yes, I know that.  We have said that opaque-related things are bugfixes.  This is borderline, the team will have to decide.

**Comment by richsalz** [comment]
@fdasilvayy please recreate your branch.  The API changes mean we put this on-hold for now.

**Pull request closed without merging**
