### PR TITLE
Remove extra `the` in SSL_SESSION_set1_id.pod

### PR DESCRIPTION
**Pull request by danbev**
##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by dot-asm** [comment]
I've added 1.1.0 label, because problem is even there. But the file resides in different directory. It's was earlier suggests that cherry-pick *could* find the way anyway...

**Comment by richsalz** [comment]
@dot-asm did you mean to approve this?

**Comment by dot-asm** [comment]
> @dot-asm did you mean to approve this?

I thought I did... I mean I recall myself choosing "Approve" in the menu...

**Comment by dot-asm** [comment]
Cherry-pick to 1.1.0 didn't work, so I assume that suggestion that git can track renamed files is an urban legend. I suggest not to backport it. Otherwise merged to master. Thanks for report.

**Comment by richsalz** [comment]
I've seen it track things, but not always.  So maybe it's not an urban legend.  Or maybe the Yeti did it :)

**Comment by davidben** [comment]
(git doesn't track renames but heuristically derives the information on demand. It means importing random snapshots as commits is simpler because you don't need to figure when to `git mv` vs `git add`, but sometimes it doesn't figure out the renames you want it to.)

**Pull request closed without merging**
