### PR TITLE
Add aes_ocb cipher to default provider

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
ping
This old PR has been rebased and updated (based on other cipher implementations).

**Comment by levitte** [comment]
You haven't declared the internal arrays properly...

``` console
clang  -I. -Icrypto/include -Iinclude -Iproviders/common/include -Iproviders/default/include -Iproviders/common/ciphers -Icrypto -Iproviders/common/macs -Iproviders/common/kdfs -Iproviders/default/macs -Iproviders/default/ciphers -Iproviders/default/kdfs  -fPIC -arch x86_64 -O3 -Wall -DDEBUG_UNUSED -DPEDANTIC -pedantic -Wno-long-long -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wswitch -Wsign-compare -Wshadow -Wformat -Wtype-limits -Wundef -Werror -Wmissing-prototypes -Wstrict-prototypes -Wno-unknown-warning-option -Wswitch-default -Wno-parentheses-equality -Wno-language-extension-token -Wno-extended-offsetof -Wconditional-uninitialized -Wincompatible-pointer-types-discards-qualifiers -Wmissing-variable-declarations -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -D_REENTRANT -DNDEBUG -D_DEFAULT_SOURCE -ansi  -c -o providers/default/ciphers/libcrypto-lib-cipher_aes_ocb.o providers/default/ciphers/cipher_aes_ocb.c
providers/default/ciphers/cipher_aes_ocb.c:487:1: error: no previous extern declaration for non-static variable 'aes256ocb_functions' [-Werror,-Wmissing-variable-declarations]
IMPLEMENT_cipher(ocb, OCB, AES_OCB_FLAGS, 256, 128, OCB_DEFAULT_IV_LEN * 8);
^
providers/default/ciphers/cipher_aes_ocb.c:462:25: note: expanded from macro 'IMPLEMENT_cipher'
    const OSSL_DISPATCH aes##kbits##mode##_functions[] = {                     \
                        ^
<scratch space>:36:1: note: expanded from here
aes256ocb_functions
^
providers/default/ciphers/cipher_aes_ocb.c:488:1: error: no previous extern declaration for non-static variable 'aes192ocb_functions' [-Werror,-Wmissing-variable-declarations]
IMPLEMENT_cipher(ocb, OCB, AES_OCB_FLAGS, 192, 128, OCB_DEFAULT_IV_LEN * 8);
^
providers/default/ciphers/cipher_aes_ocb.c:462:25: note: expanded from macro 'IMPLEMENT_cipher'
    const OSSL_DISPATCH aes##kbits##mode##_functions[] = {                     \
                        ^
<scratch space>:85:1: note: expanded from here
aes192ocb_functions
^
providers/default/ciphers/cipher_aes_ocb.c:489:1: error: no previous extern declaration for non-static variable 'aes128ocb_functions' [-Werror,-Wmissing-variable-declarations]
IMPLEMENT_cipher(ocb, OCB, AES_OCB_FLAGS, 128, 128, OCB_DEFAULT_IV_LEN * 8);
^
providers/default/ciphers/cipher_aes_ocb.c:462:25: note: expanded from macro 'IMPLEMENT_cipher'
    const OSSL_DISPATCH aes##kbits##mode##_functions[] = {                     \
                        ^
<scratch space>:134:1: note: expanded from here
aes128ocb_functions
^
3 errors generated.
```

**Comment by slontis** [comment]
> You haven't declared the internal arrays properly...

Yes I have - it was missing a include for the declaration of the functions

**Comment by levitte** [comment]
> it was missing a include for the declaration of the functions

Ah ok

**Comment by slontis** [comment]
Thanks. Merged to master.

**Pull request closed without merging**
