### PR TITLE
Handle the out-of-source build where the source directory spec contains a space

### PR DESCRIPTION
**Pull request by levitte**
[RT#4486](https://rt.openssl.org/Ticket/Display.html?id=4486)

### CODE REVIEW

**Comment by levitte** [comment]
I just realised this isn't complete enough.

**Comment by levitte** [comment]
*Now* it is as complete as I can get it

**Comment by levitte** [comment]
Ping?

**Comment by mattcaswell** [comment]
+1

**Comment by levitte** [comment]
Merged, thank you!

**Pull request closed without merging**
