### PR TITLE
`test_cmp_http`: decrease risk of timeouts due to delays by underlying system

### LINKED ISSUE #22870: CMP connect timeout with 3.2.0 or fails on `localhost`
I'm getting:
```
# cmp_main:../apps/cmp.c:3077:CMP info: using section(s) 'Mock connection' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:../apps/cmp.c:2438:CMP warning: -proxy option argument is empty string, resetting option
# setup_client_ctx:../apps/cmp.c:2088:CMP info: will contact http://localhost:36257/pkix/
# CMP info: sending IR
# CMP error: connect timeout
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../build_static/util/wrap.pl ../../../../build_static/apps/openssl cmp -config ../Mock/test.cnf -section 'Mock connection' -certout ../../../../build_static/test-runs/test_cmp_http/test.cert.pem -proxy '' -no_proxy 127.0.0.1 -server 'localhost:36257' => 1
    not ok 2 - server domain name

    #   Failed test 'server domain name'
    #   at ../test/recipes/80-test_cmp_http.t line 151.
    #          got: '0'
    #     expected: '1'
```

Full log at: https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=arm64&ver=3.2.0-1&stamp=1701011796&raw=0

I've scheduled an other build (on arm64) to see if this is a reproducible.

### PR DESCRIPTION
**Pull request by DDvO**
Hopefully fixes #22870 for most situations (such as high load on the system running the test suite),
~while this comes at the cost that some connection-oriented test cases will take longer~.

### CODE REVIEW

**Comment by DDvO** [comment]
Should this be backported?

**Comment by t8m** [comment]
I'd put it on 3.2 branch at least.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
Fuzzing CI failure must be unrelated.

**Comment by DDvO** [comment]
I've just fixed a typo and simplified the approach.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Comment by shahsb** [comment]
How to resolve fuzzer build failure?

**Review by shahsb — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
@shahsb The fuzzer build failures are due to `/usr/bin/ld: final link failed: No space left on device`. To fix this would require larger executors, which would cost (more), or splitting the fuzzing job(s) somehow.

**Comment by DDvO** [comment]
Merged to `master` and 3.2 - thanks for the swift approvals.

**Pull request closed without merging**
