### PR TITLE
Add ECDH to fips provider

### PR DESCRIPTION
**Pull request by slontis**
Note: This PR has not attempted to move the curves into the provider dispatch table.
Mappings between the curve name / nid have been added to the inbuilt curve table.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Currently a WIP until the EC serializer has been added.

**Comment by romen** [comment]
In the curve table, instead of manually inserting the strings, can't we use the defines? `SN_X9_62_prime256v1`, etc?

**Comment by slontis** [comment]
> In the curve table, instead of manually inserting the strings, can't we use the defines? `SN_X9_62_prime256v1`, etc?

We could, but I dont see much point if we end up shifting this stuff into the dispatch table..
(This also took a while :))

**Comment by levitte** [comment]
I assume that @romen meant you could use SN macros in ec_curve.c.  Considering you've put strings alongside actual NIDs, it's perfectly valid to use SN macros there.

**Comment by slontis** [comment]
Can I do it as a seperate PR?

**Comment by levitte** [comment]
> Can I do it as a seperate PR?

You may do it, or not (someone else might), in whatever way you like.  I've approved this regardless

**Comment by slontis** [comment]
Rebased with minor changes to fix a duplicate function with a different name.

**Comment by slontis** [comment]
Thanks. Merged to master.

**Pull request closed without merging**
