### PR TITLE
code health - unit tests for crypto/stack.

### PR DESCRIPTION
**Pull request by pauli-oracle**
- [x] tests are added or updated

A suite of unit tests for the crypto/stack code.  The tests aren't exhaustive but cover everything.

### CODE REVIEW

**Comment by levitte** [comment]
Hi, cool test.

So here, I'll take the opportunity to put you through a learning experience, if you don't mind.

We have a simple test programming framework that we think will make it easier, faster and more consistent to write test programs.

Have a look at `test/testutil.h`, it has some comments at the beginning quickly explaining the structure of the framework.  If you need examples, `grep ADD_ test/*.c`.

**Comment by mattcaswell** [comment]
This is really cool!! :-)

**Comment by pauli-oracle** [comment]
Thanks for the feedback, I'll update the test.
I looked at a couple of the tests that did't use framework.

**Comment by levitte** [comment]
> I looked at a couple of the tests that did't use framework.

Some of them are age old, others...   well, let's just say that we're still on a learning curve ourselves.

**Comment by pauli-oracle** [comment]
I've updated the tests to use the framework -- please let me know if I've done something wrong here.

I also added tests for the remaining macros and functions.  They are still a bit shallow in places.

**Comment by pauli-oracle** [comment]
Does anyone know why that one build sometimes locks up and times out?

**Comment by mattcaswell** [comment]
> Does anyone know why that one build sometimes locks up and times out?

Probably #2955

**Comment by pauli-oracle** [comment]
Thanks for pointing me there.  The intermittent failures were confusing for a while.

**Comment by levitte** [comment]
Merged.  9837496142cf3a4d32c827cb679539c0b239cec9

**Pull request closed without merging**
