### PR TITLE
tls_valid_group: Add missing dereference of okfortls13

### LINKED ISSUE #14153: SSL_connect() valgrind errors in git master
Since a few days, openssl from git master causes valgrind errors in the curl CI setup where we build current curl git with current openssl git master. Example [valgrind output](https://travis-ci.org/github/curl/curl/jobs/758497745#L25577)

It looks like this:
~~~
 ==31564== Conditional jump or move depends on uninitialised value(s)
 ==31564==    at 0x6018A88: tls_construct_ctos_supported_groups (in /home/travis/openssl3/lib/libssl.so.3)
 ==31564==    by 0x6017AB2: tls_construct_extensions (in /home/travis/openssl3/lib/libssl.so.3)
 ==31564==    by 0x602328A: tls_construct_client_hello (in /home/travis/openssl3/lib/libssl.so.3)
 ==31564==    by 0x6021FCE: state_machine.part.5 (in /home/travis/openssl3/lib/libssl.so.3)
 ==31564==    by 0x5FF6953: SSL_do_handshake (in /home/travis/openssl3/lib/libssl.so.3)

### PR DESCRIPTION
**Pull request by t8m**
Fixes #14153

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by bagder** [comment]
How come this wasn't detected by tests? Maybe also make sure that it is for next time?

**Comment by richsalz** [comment]
> How come this wasn't detected by tests? Maybe also make sure that it is for next time?

Hm, it's assigning NULL to a pointer.  Not sure how it could be detected.

**Comment by t8m** [comment]
IMO it would require valgrind to be used with the tests. Or we would have to have a negative test for the curves that might not be used in tls-1.3.

**Comment by mattcaswell** [comment]
This is only relevant when constructing the supported groups extension client side. Its used for counting the number of groups that we add that are suitable for use in TLSv1.3. If TLSv1.3 is supported and we end up with no TLSv1.3 suitable groups then we are supposed to get an error message.

We could have two tests:
1) Ensure that if TLSv1.3 is supported and we only add non-TLSv1.3 suitable groups then we see the "No groups enabled for max supported SSL/TLS version" error message
2) Ensure that if we *only* add TLSv1.3 suitable groups and TLSv1.3 is enabled then we don't get the error message

I suspect (1) was not working correctly before this change.

**Comment by t8m** [comment]
@mattcaswell I've added this to ssl-test/14-curves. Not sure if there is a better place.

**Comment by mattcaswell** [comment]
> Not sure if there is a better place.

Seems good enough to me.

**Review by mattcaswell — APPROVED** [review]

**Comment by bagder** [comment]
It was detected in curl tests 100% reproducible. Surely OpenSSL could run a similar test.

**Comment by mattcaswell** [comment]
> It was detected in curl tests 100% reproducible. Surely OpenSSL could run a similar test. Yes, with valgrind or sanitizers.

We already have sanitizer tests - not sure why this one wasn't picked up by them. In any case @t8m has added a test to this PR.

**Comment by kaduk** [comment]
Coverity spotted this issue as well (albeit in an indirect way): it's CID 1472831.

**Comment by t8m** [comment]
Merged to master. Thank you for the review.

**Pull request closed without merging**
