### PR TITLE
Update master Travis to Trusty

### PR DESCRIPTION
**Pull request by ekasper**
This gets us a newer Clang, and (to be confirmed) newer Go.
1.1.0 already runs on Trusty without issues.

### CODE REVIEW

**Comment by mattcaswell** [comment]
You probably want [extended tests] :-)

**Comment by levitte** [comment]
Yes, please, `[extended tests]`

**Comment by levitte** [comment]
Looks like we need to deal with `wine` somehow...

**Comment by levitte** [comment]
```
10.69s$ if [ -z "$BUILDONLY" ]; then if [ -n "$CROSS_COMPILE" ]; then sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install wine; export EXE_SHELL="wine" WINEPREFIX=`pwd`; fi; HARNESS_VERBOSE=yes BORING_RUNNER_DIR=$top/boringssl/ssl/test/runner make test; else $make build_tests; fi
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 wine : Depends: wine1.6 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by ekasper** [comment]
Yup. Merging!

**Pull request closed without merging**
