### PR TITLE
VMS: disable the shlibload test for now

### PR DESCRIPTION
**Pull request by levitte**
test/shlibloadtest.c needs added code for VMS shared libraries

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Should this go to master too?

**Comment by levitte** [comment]
> Should this go to master too?

Nah, this is really just a temporary measure for releasing...  I prefer to keep the failure on master as a reminder that coding is needed.

**Comment by mattcaswell** [comment]
Ok. I will merge.

**Comment by mattcaswell** [comment]
Pushed.

**Pull request closed without merging**
