### PR TITLE
Validate ClientHello session_id field length and send alert on failure (1.0.1)

### PR DESCRIPTION
**Pull request by ghedo**
RT#4080

### CODE REVIEW

**Comment by mattcaswell** [comment]
+1, subject to the same nit as in #545 being fixed.

**Comment by ghedo** [comment]
Nit fixed just now.

**Comment by mattcaswell** [comment]
+1

**Comment by richsalz** [comment]
+1 same temrs

**Comment by mattcaswell** [comment]
Patch applied. Thanks.

**Pull request closed without merging**
