### PR TITLE
Backport of "Enable brainpool curves for TLS1.3" including later improvements

### PR DESCRIPTION
**Pull request by Basskrapfen**
This pull-request is a backport of the "Enable brainpool curves for TLS1.3" including later simplifications. There are no logic changes.
Original pull request: https://github.com/openssl/openssl/pull/7485

This commit includes cherry picks of (master):
- 0a10825a009c830125fef94c81d34e41300a24a5 (Enable brainpool curves for TLS1.3)
- 16f0e91cf82e13c327f0b0402459dfbf78ef787c (Partial revert and reimplement "Enable brainpool curves for TLS1.3")
- c9ee6e3646258f79a9970be96394cb2b93b7eddd (Reimplement brainpool TLSv1.3 support group support)
- 3f76339a3fe7be412b754ffe7b0a5438a1297f28 (Add some more brainpool tests for TLSv1.3)

Additional changes:
- (obj_dat.h) NUM_NID/NUM_SN/NUM_CN has been increased by 3 to include the brainpool constants. In the other files these new constants are used.
- (tlsgroups.h) Took over constants from master OSSL_TLS_GROUP_ID_brainpoolP256r1_tls13, OSSL_TLS_GROUP_ID_brainpoolP384r1_tls13, OSSL_TLS_GROUP_ID_brainpoolP512r1_tls13
- regenerated 14-curves.cnf using 14-curves.cnf.in

CLA is available.

##### Checklist

- [x] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Please run make update and add the change to the commit.

Also please add some short entry to CHANGES.md with you, Matt Caswell, and Bernd Edlinger as authors.

**Comment by Basskrapfen** [comment]
> Please run make update and add the change to the commit.
> 
> Also please add some short entry to CHANGES.md with you, Matt Caswell, and Bernd Edlinger as authors.

Thanks for the hint, updated the commit accordingly.

**Comment by mattcaswell** [comment]
This may be more than we would want to include in 3.1 which was intended to be FIPS-140-3 + performance improvements. Given the imminent nature of 3.1 beta1 I'm not sure this is a good idea anyway.

**Comment by Basskrapfen** [comment]
> This may be more than we would want to include in 3.1 which was intended to be FIPS-140-3 + performance improvements. Given the imminent nature of 3.1 beta1 I'm not sure this is a good idea anyway.

The support of brainpool curves would help as a lot in our project as our customer heavily relies on EC with brainpool curves. 

Do you see a bigger risk in merging the change? As I understood it, the change is mostly making the curves available for TLS. There is not much logic involved.

**Comment by mattcaswell** [comment]
> Do you see a bigger risk in merging the change?

Mostly in terms of scope-creep. More scope is an incremental increase in the overall risk of the release. Not much for one small thing but if we take this approach for lots of things then the overall risk could increase significantly. We had a clearly understood dividing line between what was allowed into 3.1 and what wasn't. This breaks it. We could make an exception and risk the opening of the flood gates - but I'm not currently seeing the justification for an exception this close to beta.

**Comment by t8m** [comment]
Let's discuss this within OTC.

**Comment by t8m** [comment]
**OTC: This is not within the scope for 3.1 release so this should not be merged.**

**Comment by t8m** [comment]
Very roughly sometime mid 2023 but it depends on completing the QUIC MVP support.

**Pull request closed without merging**
