### PR TITLE
When apps_startup() fails, exit with a failure code and a message

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
print the error stack?

**Comment by levitte** [comment]
> print the error stack?

Not sure there will be much to print, but it can't hurt.  Done.  Re-confirm?

**Comment by levitte** [comment]
Ping?

**Comment by richsalz** [comment]
it was a side-note.  still approved.

**Comment by levitte** [comment]
Merged.

master: f2da4a4917eae1bf66290e1bd8ccd3db69d3fe63
1.1.0: 6650db730960e5c5429e70db1b998c90228f44a1

**Pull request closed without merging**
