### PR TITLE
Fix a bundle of trailing spaces in several files

### PR DESCRIPTION
**Pull request by InfoHunter**
##### Checklist

As the title says...

### CODE REVIEW

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by mattcaswell** [comment]
Oops. Wrong PR.

**Comment by InfoHunter** [comment]
ping?

**Comment by richsalz** [comment]
merging now.

**Comment by richsalz** [comment]
Thanks for your eye to detail! :)  Merged at bd91e3c.

**Pull request closed without merging**
