### PR TITLE
permitting no/empty digest in core_obj_add_sigid

### LINKED ISSUE #16761: OBJ_add_sigid disallows NID_undef for the digest id
The function `OBJ_add_sigid` explicitly disallows `NID_undef` for the digest id:

https://github.com/openssl/openssl/blob/64da15c40d15aac58e211fd25d00e9ae84d0379b/crypto/objects/obj_xref.c#L139-L145

However this makes no sense since we have multiple signature algorithms in the built-in list where it is valid for the digest id to be NID_undef (e.g. Ed25519 and Ed448):

https://github.com/openssl/openssl/blob/64da15c40d15aac58e211fd25d00e9ae84d0379b/crypto/objects/obj_xref.h#L22-L83

There are external provider that need to do this:
https://github.com/open-quantum-safe/oqs-provider/issues/2#issuecomment-936308396

### PR DESCRIPTION
**Pull request by baentsch**
Fixes #16761 (and resolves https://github.com/open-quantum-safe/oqs-provider/issues/2#issuecomment-936343557 ).

### CODE REVIEW

**Comment by levitte** [comment]
`doc/man7/provider-base.pod` should get a similar clarification

**Comment by t8m** [comment]
@mattcaswell can you please re-approve?

**Comment by baentsch** [comment]
> I would expect to see a test for this.

@slontis : Both negative and positive test now added.

**Comment by t8m** [comment]
IMO this can be merged to master as soon as @mattcaswell re-reviews after the added commits. However for 3.0 we will need OTC approval.

**Comment by t8m** [comment]
**Summary of the issue for OTC to decide:**

Should setting no digest be allowed in `OBJ_add_sigid` function and the `core_obj_add_sigid` core callback in the 3.0 branch? We allow that for builtin signature algorithms already so not allowing that for algorithms added by these calls looks like inadvertent omission.

**Comment by t8m** [comment]
@baentsch This won't apply cleanly to openssl-3.0 branch. Would you like to open a new PR against the openssl-3.0 branch?

I'm closing this PR as it was applied to master already.

**Pull request closed without merging**
