### PR TITLE
Configurations/windows-makefile.tmpl: small fixes

### LINKED ISSUE #8467: Error in windows-makefile.tmpl
I found two errors in file **windows-makefile.tmpl**. 
1. On line 151, you must add the import function catpath (change to "MODULESDIR_dev={- use File::Spec::Functions qw(:DEFAULT splitpath **catpath**);" )
2. On line 161 "**out**" change to "**our**".

### PR DESCRIPTION
**Pull request by levitte**
Fixes #8467 #8478

### CODE REVIEW

**Comment by levitte** [comment]
The Appveyor failure isn't related to this.  I am surprised that it didn't get caught in a previous PR...

**Comment by levitte** [comment]
Ping?

**Comment by levitte** [comment]
Ping?

**Comment by levitte** [comment]
Ping!  Easy pickings!  Low hanging fruit!
(and to boot, appveyor builds of master are currently failing, this *fixes it*)

**Comment by levitte** [comment]
The appveyor failure seen here isn't related to this PR.

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

52eb5b7ca46a1bf0bb0e148c651eb7dcaae1a074 Configurations/windows-makefile.tmpl: small fixes

**Pull request closed without merging**
