### PR TITLE
Code Improvement fixes.

### PR DESCRIPTION
**Pull request by ya1gaurav**
In reference to : https://github.com/openssl/openssl/issues/366
Proposing pull request.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Hiroyuki's changes are already going through internal review so hopefully should be in soon. Thanks for raising this as a pull request. Just one point for future reference: please can you ensure that you set the "author" field correctly for such pull's so that we get attribution correct in the git log (or at least mention the original author in the commit description - not just a reference to the issue id). We've inadvertently upset people in the past by not giving proper attribution where someone has raised a pull request on behalf of someone else! :-)

**Comment by ya1gaurav** [comment]
I will take care next time. Thanks.

**Comment by ya1gaurav** [comment]
One more request regarding: https://github.com/openssl/openssl/pull/373
If this is accepted, we can have automatic travis build. Please review it. I have done its background configurations.

**Comment by mattcaswell** [comment]
These fixes have been applied.

**Pull request closed without merging**
