### PR TITLE
Disable running test/shlibloadtest with -dso_ref on Cygwin

### LINKED ISSUE #9330: support "expected failure" for test framework
Current master(2019-07-09) fail on cygwin. In brief failure is verbose mode is:
...
DSO_dsobyaddr() failed
../../util/shlib_wrap.sh ../../test/shlibloadtest.exe -dso_ref cygcrypto-3.dll cygssl-3.dll ...
not ok 7 - running shlibloadtest -dso_ref ...
...
Comment in test/shlibloadtest.c explains failure "We are not testing this on Windows, because it is done there in a completely different way. Especially as a call to DSO_dsobyaddr() will always return an error, because DSO_pathbyaddr() is not implemented there."

With other word "shlibloadtest -dso_ref " is expected to fail on windows platforms.

Goal of request is in similar cases some tests to be marked that are expected to fail. Skip or error is not enough.

### PR DESCRIPTION
**Pull request by levitte**
That platform currently lacks the needed support.

Fixes #9330 

-----

While I'm at it, I refactored test/recipes/90-test_shlibload.t for better readability and maintainability.

### CODE REVIEW

**Comment by levitte** [comment]
@petrovr, if you wouldn't mind testing this?

**Comment by petrovr** [comment]
According comment in "C-test cod"e limitation is due to Microsoft Windows OS, not platform like Cygwin*. If this is true issue/commit title has to be changed. I did not look yet in DSO C-code and I my opinion trust only on correctness of C-comment.

**Comment by levitte** [comment]
Thing is that Cygwin uses the dlfcn variant of DSO, while MSVC and mingw use the win32 variant, and if you look around the comment, that code section is guarded with `# ifdef DSO_DLFCN`, so that code section only becomes relevant for Cygwin, not for the rest of the Windows hosted environments.

Cygwin is kind of an odd beast.  It's claimed to be a complete POSIX sub-system on Windows (as opposed to mingw, which is really just an alternative toolchain), but sometimes shows Windowsy traces.  This is one of them, and it requires special handling.

**Comment by petrovr** [comment]
Thanks for remark. 

Now I review code in more details and note that dso_dlfcn.c has lines:
```
#  define HAVE_DLINFO 1
#  if defined(__CYGWIN__) || \
     defined(__SCO_VERSION__) || defined(_SCO_ELF) || \
     (defined(__osf__) && !defined(RTLD_NEXT))     || \
     (defined(__OpenBSD__) && !defined(RTLD_SELF)) || \
        defined(__ANDROID__)
#   undef HAVE_DLINFO
#  endif
```
Cygwin (#9385)  and Android (#9386) support dladdr() so undef is outdated.

In this defect remains incorrect comment in shlibloadtest.c - DSO_REFTEST is applicable only DLFCN , DLFCN  is not used for  Windows targets, so Windows related comment make no sense.

**Comment by levitte** [comment]
Actually, since we've now added the necessary support, this PR can be killed

**Pull request closed without merging**
