### PR TITLE
Cryptodev linux

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated
- [x] CLA is signed
##### Description of change

Update of cryptodev engine.  This is a straight transfer of #191 to a fresher master.

**NOTE:** The added PKEY related stuff for the MDs didn't get transfered.  This requires more work and is probably worth a PR of its own.

### CODE REVIEW

**Comment by levitte** [comment]
@nmav, for this to actually come through, we need a CLA from you.  Please have a look [here](https://www.openssl.org/policies/cla.html).  An ICLA is the required minimum, but if you're using working time, a CCLA is safer.  Either way, the email address you give us must match the commit author address for your commits.

**Comment by levitte** [comment]
Reading again in #191, I see that @nmav has moved on.  This creates an interesting problem regard CLAs.  @mattcaswell, @richsalz, can you think of a solution?

**Comment by mattcaswell** [comment]
Unless he can be contacted and is willing to provide a CLA then we cannot use his change...although #191 just says he's not working on cryptodev anymore, not that he is uncontactable.

**Comment by levitte** [comment]
Considering he responded in #1784 just a couple of hours ago... ;-)

**Comment by nmav** [comment]
> @nmav, for this to actually come through, we need a CLA from you. Please have a look here. An ICLA is the required minimum, but if you're using working time, a CCLA is safer. Either way, the email address you give us must match the commit author address for your commits.

These patches were submitted by me as an individual several years ago related to some cryptodev work for openssl foundation (I do not remember whether if these specific patches were the object of that contract or if I submitted them later). Anyway I'll sign the CLA; just let me know to which address I should send.

**Comment by levitte** [comment]
@nmav, have a look [here](https://www.openssl.org/policies/cla.html), follow the Individual CLA link, all instructions are present in the PDF you get, including email address.

**Comment by nmav** [comment]
done

**Comment by levitte** [comment]
This is now part of #1784, no need to keep this PR

**Pull request closed without merging**
