### PR TITLE
minor fixes in engines/ccgost

### PR DESCRIPTION
**Pull request by cristian-stoica**

### CODE REVIEW

**Comment by mattcaswell** [comment]
+1

**Comment by mattcaswell** [comment]
Needs another team review.

**Comment by richsalz** [comment]
+1

**Comment by levitte** [comment]
@cristian-stoica, I'm not sure if you got this feedback: we need a signed CLA from you to include this PR into our codebase.  See https://www.openssl.org/policies/cla.html

Note that the email address(es) you specify in the CLA *must* match the address(es) you use in your commits.

**Comment by cristian-stoica** [comment]
@levitte 
See also my other reply on the same issue in another patch. Maybe if Geoff Thorpe can sign off these patches we can make progress before legal signs the CLA.

**Comment by cristian-stoica** [comment]
@levitte  Please see updated pull request with CLA: trivial

**Comment by levitte** [comment]
@richsalz, @mattcaswell, you are the reviewers, please say if you agree with regards to triviality.

**Comment by richsalz** [comment]
the code is trivial, the wording changes are obvoius.  so yes, trivial.

**Comment by mattcaswell** [comment]
Agreed - trivial.

**Comment by mattcaswell** [comment]
Merged. Better late than never.

**Pull request closed without merging**
