### PR TITLE
[1.1.1-bp] Add SSL_kDHEPSK and SSL_kECDHEPSK as PFS ciphersuites for SECLEVEL >= 3

### LINKED ISSUE #17743: PSK ciphersuites at SECLEVEL=3
https://github.com/openssl/openssl/blob/7b3041eba1c6e177eede0d6311d53a6b9ff58051/ssl/ssl_cert.c#L1035-L1038 permits using only SSL_kEDH and SSL_kEECDH KEX modes because of Forward Security. In fact, SSL_kECDHEPSK and SSL_kDHEPSK are also forward-secure, so they may be missed here by accident.

Is it a bug or a design decision?

### PR DESCRIPTION
**Pull request by romen**
This is the `1.1.1` backport of #17763 , as it required non-trivial changes, beyond cosmetic touches for the `CHANGES` file.

The major amendments were required by the third commit, covering tests, as the recipe and the source code of the associated binary changed enough to require manual conflict resolution.

Fixes #17743.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM if tests are passed

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by romen** [comment]
@t8m I don't see failing CI on my side, am I missing something?

**Comment by t8m** [comment]
There is some problem with the bot. Please just merge.

**Comment by romen** [comment]
Merged to `1.1.1` with:

- b6b7e6ff09 `[ssl] Prefer SSL_k(EC)?DHE to the SSL_kE(EC)?DH alias`
- cabebaf818 `[ssl] Add SSL_kDHEPSK and SSL_kECDHEPSK as PFS ciphersuites for SECLEVEL >= 3`
- 4bb34766d4 `[ssl] Add tests for Perfect Forward Secrecy criteria on SECLEVEL >= 3`

**Pull request closed without merging**
