### PR TITLE
Make ossl_ecdh_compute_key() return a boolean

### PR DESCRIPTION
**Pull request by huangqinjin**
The following code in `ECDH_compute_key()` treats the return value of `compute_key` as a boolean.
```shell
    if (!eckey->meth->compute_key(&sec, &seclen, pub_key, eckey))
        return 0;
```
BTW, there're getter/setter for `EC_KEY_METHOD` in openssl-1.1, so it's better to document the fields of it.

### CODE REVIEW

**Comment by mattcaswell** [comment]
x25519_compute_key() also needs to be fixed.

**Comment by huangqinjin** [comment]
Fixed.

**Comment by mattcaswell** [comment]
+1
@richsalz - new commit since your plus one. Reconfirm?

**Comment by richsalz** [comment]
Yes, +1

**Comment by mattcaswell** [comment]
Merged. Thanks.

**Pull request closed without merging**
