### PR TITLE
Check that we got the expected name type when verifying name constraints

### PR DESCRIPTION
**Pull request by mattcaswell**
If a SAN field contains an SmtpUTF8Mailbox name then it is expected to
have a UTF8String type. We should verify that it really does before we
attempt to use the value in it.

Reported by Corey Bonnell

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by DDvO** [comment]
After expiration of `test/certs/bad-othername-namec.pem` on Jul  2 13:42:35 2021 GMT,
the negative test case will succeed for the wrong reason and thus become useless.
I'll fix this by adding `-attime 1623060000`.

**Comment by DDvO** [comment]
Should we really do this check without `-x509_strict`?
So far, we don't do inessential X.509 well-formedness checks without it.

**Comment by mattcaswell** [comment]
> After expiration of test/certs/bad-othername-namec.pem on Jul 2 13:42:35 2021 GMT,
the negative test case will succeed for the wrong reason and thus become useless.
I'll fix this by adding -attime 1623060000.

Good idea.

> Should we really do this check without -x509_strict?

I'm not sure why we need it for this test? It should fail without "-x509_strict".

**Comment by DDvO** [comment]
> > Should we really do this check without -x509_strict?
>>  So far, we don't do inessential X.509 well-formedness checks without it.
>  
> I'm not sure why we need it for this test? It should fail without "-x509_strict".

I actually meant the check implemented in the lib.
This check, and thus also the new test case, is (so far) independent of `X509_V_FLAG_X509_STRICT` / `-x509_strict`.

**Comment by mattcaswell** [comment]
I see many instances of `X509_V_ERR_UNSUPPORTED_NAME_SYNTAX` without any reference to `X509_V_FLAG_X509_STRICT`. This seems correct to me.

**Pull request closed without merging**
