### PR TITLE
ARM assembly pack: translate bit-sliced AES implementation to AArch64

### PR DESCRIPTION
**Pull request by bavison**
This addresses a performance issue on the Raspberry Pi 4, when running in AArch64 mode. This device feature a Cortex-A72 CPU, without the cryptography extensions. OpenSSL includes a bit-sliced AES implementation for Arm cores which is used by the Raspberry Pi 4 in AArch32 mode, but this has not been usable in AArch64 mode until now. In fact, it runs a little faster on AArch64 than AArch32 because there are more registers available (so less spilling of variables to the stack is required) and I have been able to schedule the instructions to better suit modern CPUs that are superscalar for SIMD instructions.

The AArch32 version featured a build variant which was used at one point in the past when the same source file was built into the Linux kernel. Linux has since replaced this with a dedicated implementation, so this build variant is not carried across to the AArch64 version.

Here are some benchmarks for a 1.5 GHz Raspberry Pi 4, using `openssl speed -evp <type>` first with and then without `-decrypt`:

Before

type            | 16 bytes    | 64 bytes    |256 bytes   |1024 bytes   |8192 bytes  |16384 bytes
----------------|-------------|-------------|------------|-------------|------------|------------
aes-256-cbc     | 21080.06k   | 40463.08k   | 41510.40k  |  41852.25k  |  41891.16k |   41888.43k
aes-256-cbc     | 27555.58k   | 29389.46k   | 29891.16k  |  30134.27k  |  30203.90k |   30201.17k
aes-256-ctr     | 26520.26k   | 28642.93k   | 29177.51k  |  29296.64k  |  29379.24k |   29365.59k
aes-256-ctr     | 26820.86k   | 28640.92k   | 29159.85k  |  29328.04k  |  29379.24k |   29360.13k
aes-256-xts     | 12279.51k   | 18661.29k   | 21331.88k  |  22198.12k  |  22407.85k |   22499.23k
aes-256-xts     | 14026.19k   | 23280.00k   | 27721.05k  |  29099.01k  |  29523.97k |   29545.81k

After

type            | 16 bytes    | 64 bytes    |256 bytes   |1024 bytes   |8192 bytes  |16384 bytes
----------------|-------------|-------------|------------|-------------|------------|------------
aes-256-cbc     | 44849.12k   | 53817.86k   | 64527.36k  |  69826.22k  |  71808.34k |   71882.07k
aes-256-cbc     | 27696.58k   | 29474.52k   | 30020.78k  |  30164.31k  |  30203.90k |   30195.71k
aes-256-ctr     | 46442.28k   | 54218.82k   | 74725.72k  |  82485.59k  |  85437.10k |   85469.87k
aes-256-ctr     | 46926.52k   | 54436.48k   | 74833.66k  |  82547.37k  |  85483.52k |   85590.02k
aes-256-xts     | 15969.11k   | 25832.09k   | 59270.91k  |  67184.64k  |  70331.05k |   70593.19k
aes-256-xts     | 16285.46k   | 29252.31k   | 68226.22k  |  79236.44k  |  82747.39k |   83050.50k

This demonstrates a significant speed-up in all cases except CBC encryption (which by its nature is impossible to parallellise across multiple crypto blocks in the manner performed by bit-slicing).

The `make test` suite passes.

A separate PR #14578 has been raised to apply the equivalent change to branch OpenSSL_1_1_1-stable.

One thing that I noticed during debugging is that the `make test` suite occasionally calls the functions with identical input and output pointers. The C prototypes are defined by the types `cbc128_f` and `ctr128_f` in `modes.h` and struct `EVP_AES_XTS_CTX` member `stream` in `e_aes.c`. In all these cases, the `in` and `out` arguments to the function pointers do not feature a `restrict` qualifier, so this is a valid way to call them as far as a C compiler is concerned.

However, I'm aware that the AArch32 implementations (and doubtless many others) do not honour calls with pointers that alias in any other manner than strict equality - in other words, if the input and output buffers only partially overlap. At least for now, this is also the case with my AArch64 implementation. Since the input and output data are of identical size, this could be handled by `memmove`ing the source to the destination, then performing in-place de/encryption at the destination address. Since this would be a fix required in many places, I wonder whether it would be better implemented as a generic wrapper in some way?

The other course of action, of course, is to leave things as they are. But in that case, may I suggest that it's documented somewhere that identical `in` and `out` pointers are permitted, but that is the only form of pointer aliasing that is?

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
I'm not qualified to review the ASM properly.  The rest looks okay.

**Review by t8m — APPROVED** [review]
Same as @paulidale. Just a casual review.

**Comment by kaduk** [comment]
> I'm not qualified to review the ASM properly. The rest looks okay.

One question that is probably worth asking in such cases is how confident we are that there is test coverage for any edge cases in in the implementation (carry bits, max range for intermediate values, etc).  Since this is supposed to just be translating an existing implementation to a new architecture it's possible that the exsiting test coverage is fine, but it would be reassuring if someone could say that they looked into it and confirm that there are tests exercising the edge cases.

**Comment by bavison** [comment]
> how confident we are that there is test coverage for any edge cases in in the implementation

If it helps, I can share the fuzz testers I used during development: https://github.com/bavison/openssl/commit/d5919b335e97add46076f79458e51ad4de861146. They're only really any use for comparing the 32-bit and 64-bit ARM implementations, since they link directly to the accelerated functions. Also, this won't build if you cherry-pick it directly onto the PR, because it requires that all functions have exported symbols for the linker to use (that's just a matter of temporarily adding a handful of `.global` directives though).

Iit demonstrates that I've exercised many different text lengths (important for checking all the different code paths for mopping up the final few blocks at a lower degree of parallelism than is used in the inner loop) and lots of different key lengths (actually more than are used in practice).

What my tests didn't pick up was the requirement to handle in-place en/decryption, but `make test` did find a bug where I was writing to an address ahead of reading its old value if the plaintext and ciphertext pointers were the same. That's what alerted me to the potential problem if the input and output buffers only partially overlap.

If you examine the comments I've inserted at the top of each function, you'll find I've deduced some of the calling constraints (by inspection of the 32-bit version), such as the length of the ciphertext/plaintext being greater than 0 and/or a multiple of 16 bytes. Higher layers may actually impose tighter constraints, but I couldn't find any such documented anywhere and I didn't fancy trying to figure them out :)

**Comment by paulidale** [comment]
Merged to master.  Thanks for this contribution.

**Comment by kaduk** [comment]
> If it helps, I can share the fuzz testers I used during development

thanks, that does help.

**Comment by paulidale** [comment]
@bavison, is it possible to get this change converted to perlasm?
It's not working for OS/X on M1.

**Comment by paulidale** [comment]
We're reverting this for the moment.

**Comment by paulidale** [comment]
The assembler breaks trying to assemble this.  It's not a function of the capabilities of the processor.

**Comment by bavison** [comment]
I meant, I was wondering if the easiest approach might be, at _configuration_ time, to omit the offending file from the build if it's targeting OSX (on the assumption that every ARM processor that runs OSX doesn't actually benefit from the optimisation anyway). That way, the assembler never gets run on this file for OSX builds.

**Comment by paulidale** [comment]
That would be an option.  Better would be to get this working with Perlasm :)

**Comment by tom-cosgrove-arm** [comment]
@bavison Hi, I have a fix for your build issue, would you like me to push a commit to this PR or a diff?

**Comment by bavison** [comment]
@tom-cosgrove-arm Thanks, that would be great - I still hadn't had chance to get to grips with `perlasm` yet. The PR branch is open to edits by maintainers of openssl/openssl, so if you are one then you should be able to add a commit. If not, I guess you could raise a PR targeting branch `bsaes-aarch64-master` on my fork.

**Comment by tom-cosgrove-arm** [comment]
@bavison done, you have a PR on your fork

**Comment by bavison** [comment]
I just removed the merge commit that GitHub added - guessing that's not wanted upstream!

**Comment by tom-cosgrove-arm** [comment]
Cross-compilation `aarch64-linux-gnu-` failure is due to

```
commit 3675334e2b92eabedbd2f0eb452ade30283b0e56
Author: Pauli <pauli@openssl.org>
Date:   Tue May 25 10:40:44 2021 +1000

    aes: rename new bsaes_ symbols -> ossl_bsaes_ ones
    
    bsaes_cbc_encrypt -> ossl_bsaes_cbc_encrypt
    bsaes_ctr32_encrypt_blocks -> ossl_bsaes_ctr32_encrypt_blocks
    bsaes_xts_decrypt -> ossl_bsaes_xts_decrypt
    bsaes_xts_encrypt -> ossl_bsaes_xts_encrypt
    
    Reviewed-by: Shane Lontis <shane.lontis@oracle.com>
    (Merged from https://github.com/openssl/openssl/pull/15445)
```

Those renames will need to be made to the source branch for this PR.

**Comment by tom-cosgrove-arm** [comment]
The build that failed (cross `riscv64-linux-gnu-`) appears to have done so because it couldn’t connect to `packages.microsoft.com` to download packages, not because of anything in this PR

**Comment by tom-cosgrove-arm** [comment]
@paulidale can we remove the `stalled: awaiting contributor response` flag please?

**Comment by paulidale** [comment]
Removed.

**Comment by richsalz** [comment]
Was @appro involved in this, or just the title used in his honor? :)

**Comment by mspncp** [comment]
> Was @appro involved in this, or just the title used in his honor? :)

I guess you meant @dot-asm ?

**Comment by tom-cosgrove-arm** [comment]
@paulidale what's needed to get this moving again? Can it go into the "after beta period" bucket?

**Comment by paulidale** [comment]
Perlasm would be the best way forwards.  Failing that, better tool chain detection so the assembler failure doesn't occur.

This is definitely post 3.0 beta period.

**Comment by paulidale** [comment]
Hmmm, I must have missed that :disappointed:

**Comment by t8m** [comment]
Too late to get into 3.0.

**Comment by t8m** [comment]
Unfortunately this is not usable in the current form - the suggestion is to use the perlasm to avoid build breakage on some platforms.

**Comment by bavison** [comment]
@t8m I think you may have overlooked the commit from @tom-cosgrove-arm that adds perlasm support?

**Comment by t8m** [comment]
> @t8m I think you may have overlooked the commit from @tom-cosgrove-arm that adds perlasm support?

Ah, you're right, I was looking at the older version of the PR.

**Comment by Fredrum** [comment]
Hi I'm interested in building this to get speedup on RPi 4b 64bit.
So just to get som eclarification, this hasn't made it though PR yet?

**Comment by paulidale** [comment]
No this hasn't been merged to the mainline yet.
You could grab the commits from here and build them.

**Review by paulidale — APPROVED** [review]
Slipped off the radar.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master branch. Thank you for your contribution!

**Pull request closed without merging**
