### PR TITLE
Tolerate a bad record version in TLSv1.3 plaintext records

### LINKED ISSUE #19051: Unable to connect via TLS 1.3
Hi!
When building latest commit from master branch it became impossible to connect particular site via TLS 1.3.

I'm using Python 3.7.13 in conjunction with OpenSSL 3.1.0-dev (latest commit),
To reproduce, I'm using this Python script:
```
import socket
import ssl

for j in range (1,10):
  myhost = 'tls13.1d.pw'
  context = ssl.create_default_context()
  with socket.create_connection((myhost, 443)) as mysock:
    with context.wrap_socket(mysock, server_hostname=myhost) as myssock:
      print(str(j) + ' connection to ' + myhost + ' via ' + myssock.version())
```

Got this:
```
Traceback (most recent call last):
  File "mytest.py", line 8, in <module>
    with context.wrap_socket(mysock, server_hostname=myhost) as myssock:
  File "C:\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNABLE_TO_DECODE_ECDH_CERTS] record layer failure (_ssl.c:1091)
```

Everything worked fine
```
1 connection to tls13.1d.pw via TLSv1.3
2 connection to tls13.1d.pw via TLSv1.3
3 connection to tls13.1d.pw via TLSv1.3
4 connection to tls13.1d.pw via TLSv1.3
5 connection to tls13.1d.pw via TLSv1.3
6 connection to tls13.1d.pw via TLSv1.3
7 connection to tls13.1d.pw via TLSv1.3
8 connection to tls13.1d.pw via TLSv1.3
9 connection to tls13.1d.pw via TLSv1.3
```

before this PR: https://github.com/openssl/openssl/pull/18132

### PR DESCRIPTION
**Pull request by mattcaswell**
When a server responds to a second TLSv1.3 ClientHello it is required to
set the legacy_record_version to 0x0303 (TLSv1.2). The client is required
to ignore that field even if it is wrong. The recent changes to the read
record layer in PR #18132 made the record layer stricter and it was
checking that the legacy_record_version was the correct value. This
caused connection failures when talking to buggy servers that set the
wrong legacy_record_version value.

We make us more tolerant again.

Fixes #19051

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by Tarnum-tst** [comment]
Tested/working. Ping @openssl/commiters for second review. :-)

**Comment by mattcaswell** [comment]
Ping @openssl/committers for second review

**Comment by imoan723** [comment]
Wow

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
Merged to master branch. Thank you.

**Pull request closed without merging**
