### PR TITLE
sk_TYPE_dup and sk_TYPE_deep_copy: Avoid potential crash.

### PR DESCRIPTION
**Pull request by triska**
##### Checklist

- [x] CLA: Trivial.

##### Description of change

These functions are now safe to use also when the given stack is NULL,
in analogy to the other functions that are perfectly safe in this case.

### CODE REVIEW

**Comment by levitte** [comment]
While you're at it, there should be a similar check in `OPENSSL_sk_delete_ptr`

**Comment by richsalz** [comment]
No, we really shouldn't check if the main object is NULL and fail at runtime.  This is a programming error.  The existing NULL checks should be removed, actually.
-1

**Comment by levitte** [comment]
> No, we really shouldn't check if the main object is NULL and fail at runtime. This is a programming error. The existing NULL checks should be removed, actually.

We can't do that before 1.2.0, since that changes the stack semantics.  We can certainly experiment with that in a PR, though.  (I wonder what effects that will have on the rest of our code)

Speaking of things stack, we seem to be checking for negative `num` quite a lot.  When can that ever happen?  I've been looking through the code for possible cases, but can't find them...

**Comment by richsalz** [comment]
So we can close this, at any rate.  I don't think we make a strict "same semantics" guarantee, but, sigh okay.

**Comment by t-j-h** [comment]
Actually checking for NULL on input parameters is a common programming style - and it has benefits - not only in making error path handling easier. We have a lot of the API where the input parameter is checked to make sure it isn't NULL - as it stops things going bang (SEGV) on dereference. Otherwise every caller has to do an explicit ptr!=NULL check before calling. 

The current implementation is inconsistent on this point - and this is a style issue.

**Comment by levitte** [comment]
We did decide quite some time ago now to go away from checking for NULL pointers.  The argument was that it was to be considered a programming error and has also helped uncover bugs in our own code.

Yes, it's true that it forces everyone to ensure pointers aren't NULL.  In this case, it makes sure to catch when someone has forgotten to create the stack (`sk_TYPE_new()`) before using the stack.  I see that as a benefit.

**Comment by triska** [comment]
The main issue is that OpenSSL *itself* returns `NULL` in some cases, for example if no certificate chain was provided and I ask for the chain.

Then, when I want to *duplicate* the returned stack, OpenSSL crashes in this case.

Logically, I see two options to handle all cases completely uniformly:

1. Either an *empty* stack (but *not* `NULL`) is returned in such cases *or*
2. `NULL` is returned, and *all* stack operations again return `NULL` in such cases.

If either of these two ways were chosen, then the empty stack *naturally* falls out as a special case without a single additional check.

Currently, the trouble is that NULL is sometimes returned to denote "empty stack", and so I have to treat an empty stack differently from a stack with at least one certificate. Personally, I see no reason to do this, and I find an API that forces me to do it inconvenient and very error-prone.

**Comment by triska** [comment]
> No, we really shouldn't check if the main object is NULL and fail at runtime.

The point of this patch is not to "fail", but rather the opposite: To let application programmers treat the empty stack exactly like any other stack.

> This is a programming error. 

Please note that OpenSSL itself sometimes yields NULL although a stack with zero elements would be much more logical.

**Comment by richsalz** [comment]
I understand the frustration, but there are other things to consider.
 
1. We generally do not check for NULL because it hides programming errors.  Consider the C library which never checks for NULL.
2. The convenience you get in this case is outweighed by the risk of hiding programmer errors (in my view, and others on the team as well).
3. We have to honor a faulty and incomplete API, but we try not to make things worse.

**Comment by levitte** [comment]
> Currently, the trouble is that NULL is sometimes returned to denote "empty stack", and so I have to treat an empty stack differently from a stack with at least one certificate. Personally, I see no reason to do this, and I find an API that forces me to do it inconvenient and very error-prone.

The bigger trouble is that the stack code itself returns `NULL` as an error (for example when malloc failed)...  if we allow `NULL` to denote an empty stack, it will be hard to check if a returned `NULL` by `OPENSSL_sk_dup` is an error condition or not...  just to pick one example.

**Comment by richsalz** [comment]
Note that I am not trying to convince you that "we're right, you're wrong."  I just hope that you'll see there reasonable reasons for the decisions we make.  At least in this case :)

**Comment by triska** [comment]
> if we allow NULL to denote an empty stack

Please note that's currently *the case*! For example, `SSL_get_peer_cert_chain` returns `NULL` to denote that the stack is *empty*! Therefore, I cannot uniformly use the normal stack API to determine the number of elements in this case.

I think the alternative would be much better: In such cases, `SSL_get_peer_cert_chain` should, in my view, return a proper stack, with zero elements.

This would allow a uniform treatment of all chain lengths, *without* having to treat `NULL` meaning "zero elements", and make this pull request completely obsolete.

I fully agree that the pull request is not ideal! If such massive API changes are allowed, please consider returning proper stacks in all such situations, and let `NULL` uniformly denote an exceptional condition, but *not* a stack with zero elements.

**Comment by levitte** [comment]
I agree that it would be much better if functions that should return stacks actually did (... return empty stacks if neede).  In other words, the internal stacks would need to be properly initialised at all times and not just when they are first used.

**Comment by triska** [comment]
OK, I have filed issue #2254 to put this in broader context, together with an example from an actual application.

**Comment by richsalz** [comment]
Thank you for doing that.  Nice writeup over there.

**Pull request closed without merging**
