### PR TITLE
Enable custom extension on resumed connections

### PR DESCRIPTION
**Pull request by waywardgeek**
This tiny PR simply removes a check that the server uses to ignore custom extensions in the client hello on a resumed session.  In my past testing, this one-line change enabled me to successfully negotiate token binding both on the initial and resumed connections, as a custom extension.

I recommend this change because the OpenSSL session cache has exactly zero state devoted to remembering what custom extensions were negotiated on the initial connection.  Any custom extension which needs to remain in effect on a resume most likely needs to renegotiate it.  With this change, any existing custom extensions (I am not aware of any in use today) will need to be modified to perform the s->hit check in the custom extension callback.

The initial version of this PR is missing a test code.  Should we merge this simple change first, or should I create a test example of using custom extensions with resume?  I would be happy to use the token binding custom extension I wrote for BoringSSL as a test case in OpenSSL.

### CODE REVIEW

**Comment by richsalz** [comment]
Yes, please add the token binding stuff as a test to this PR

**Comment by waywardgeek** [comment]
Just checking if I've found the right place for the test:  The ssltest.c test in the test directory already does a lot of custom extension testing.  Should I just add one more custom extension test there to verify token binding extensions can work during resumption?

**Comment by ekasper** [comment]
Can you also update the docs to explicitly say that the callback is called during resumption, and that it is up to the caller to ignore it if the extension should have no effect during resumption? The caller can use `SSL_session_reused` to determine if the session is reused (s->hit is no longer directly available to them). (Some extensions may also need their original state cached in the session rather than starting anew but I guess we'll deal with that when we need to.)

Also, this needs a CHANGES entry since it's changing behaviour.

**Comment by levitte** [comment]
Ping.

**Comment by mattcaswell** [comment]
Ping @waywardgeek

**Comment by waywardgeek** [comment]
Sorry about the delay.  I was swamped with other work.  I am just cleaning up and packaging the TB negotiation code to make an appropriate test case for this change.  I should have it ready for review later this week.

**Comment by mattcaswell** [comment]
I'm wondering whether, because this is a functional change and not a bug fix as such, we should move this to the "Post 1.1.0" milestone.

**Comment by waywardgeek** [comment]
That works for me.

**Comment by waywardgeek** [comment]
It's been forever, but I am finally ready to finish this.  It is a holiday
weekend, so this will probably get done Tuesday.  Is the timing OK?

**Comment by mattcaswell** [comment]
1.1.0 has now been released so we are willing to consider functional changes and enhancements again.

**Comment by richsalz** [comment]
Now that it won’t go until the next release, there’s no rush.

**Comment by mattcaswell** [comment]
Closing this in favour of #3139

**Pull request closed without merging**
