### PR TITLE
manpages: fix manual section order [1.1.1]

### PR DESCRIPTION
**Pull request by mspncp**
This is a cherry-pick of the pull requests #8338 and #8729 (see https://github.com/openssl/openssl/pull/8729#issuecomment-482598419 and ff.).

Two commits had conflicts which were resolved as follows:

- cd32530ea55a08fc936699f157ca629bb0befe3d:  two files did not exist yet in 1.1.1. Their changes were discarded.

- 0f270269afc1550bc70e757daba64075763543d2 two RAND_DRBG_* pod-files contained modifications in the HISTORY sections being swapped. These changes were discarded, only the sections were swapped.

### CODE REVIEW

**Comment by mspncp** [comment]
Editorial note: Since the commits are only cherry-picks with trivially resolved conflicts, I intend to preserve the `Reviewed-by:` and `Merged from` markers from the original pull requests and not add any additional reference to this pull request here. In other words, I won't change the commit message anymore when merging.

**Comment by mspncp** [comment]
The last force-push only affected the commit messages from #8729: I had forgotten to cherry-pick with the `-x` option.

**Comment by mattcaswell** [comment]
>  I intend to preserve the Reviewed-by: and Merged from markers from the original pull requests

IMO that is incorrect. The "Reviewed-by" and "Merged from" headers should be for the specific PR used. That will lead people to this PR, which itself is linked to the original PR.

**Comment by mattcaswell** [comment]
Approved subject to the headers being amended as I note above.

**Comment by mspncp** [comment]
> > I intend to preserve the Reviewed-by: and Merged from markers from the original pull requests
> 
> IMO that is incorrect. The "Reviewed-by" and "Merged from" headers should be for the specific PR used. That will lead people to this PR, which itself is linked to the original PR.

Ok, convinced.

**Comment by mspncp** [comment]
Merged, thanks!

1ced49fbb7 Further harmonisation of manual page HISTORY sections
18bad53564 Update various man pages to place HISTORY section after SEE ALSO
3b01f353b8 Add a check for history section location to find-doc-nits
32a775df9b Make check_example_location() in find-doc-nits generic
a345fa370e Add section order check in util/find-doc-nits
d090fc0019 Place return values after examples in doc

**Pull request closed without merging**
