### PR TITLE
Small optimization.

### PR DESCRIPTION
**Pull request by raniervf**
Avoid calc strlen many times.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
Close/reopen to kick CLA bot.

**Comment by mspncp** [comment]
Note: Since this is a small change, feel free to just amend your commit and force-push it. In case you have never done it before, here's how to do it:

* edit the file
* amend your commit

```
    git commit -a --amend
```

* edit the commit message

* force-push the branch to your clone (assuming it is named 'origin')
```
    git push origin patch-1 --force
```

**Comment by raniervf** [comment]
Sorry, my inexperience. Maybe, better make a new Pull?
I don't have git in my machine. I'm using online only.
Please, feel free to commit with your changes requested.

**Comment by mspncp** [comment]
Ok, don't worry. I'll just do the change for you and force-push it to your repo. Hang on a minute...

**Comment by mspncp** [comment]
@raniervf I just pushed two commits:

* Your original commit, with the new commit message:

   5418689ba1 conf_def.c: Avoid calling strlen() in a loop

* The additional fixes for VMS

   970ecc6b89 fixup! conf_def.c: Avoid calling strlen() in a loop

@levitte could you please double check the VMS fix?

**Comment by raniervf** [comment]
Thanks, looks good to me.

**Comment by slontis** [comment]
Not sure why this is tagged as 1.1.1

**Comment by mspncp** [comment]
> Not sure why this is tagged as 1.1.1

Well, it is not a _feature_, but an _enhancement_ (a small performance improvement), and as such _could_ be considered a bug fix. Also, it cherry-picks cleanly to 1.1.1. So it _could_ be backported, if not for the improvement then maybe just to keep the 1.1.1 branch as close to master as possible to reduce the likelyhood of futher merge conflicts. 

OTOH, I agree that it is debatable whether backporting is worth the effort, even more since there are now many more strlen() micro changes in the queue :-)

**Comment by mspncp** [comment]
@mattcaswell do you have any objections against cherry-picking to 1.1.1?

**Comment by raniervf** [comment]
None, My objective is improve the performance the version 1.1.1d, which i'm using.

**Comment by richsalz** [comment]
> None, My objective is improve the performance the version 1.1.1d, which i'm using.

I am very curious: have you done any profiling that shows repeated strlen is impactful?

**Comment by raniervf** [comment]
No, I did not do, is this really necessary?
Strlen is the most famous performance killers, and any programmer should avoid using.
Compare:
str[0] != '\0' with strlen(str) > 0, what is best to use?
Nginx is the most famous example with this kind of optimization, all strings have size, no need strlen or string copy, but the example is extreme, and we are far...
Please read:
https://books.google.com.br/books?id=V1kPDAAAQBAJ&pg=PA152&lpg=PA152&dq=strlen+call+repeated&source=bl&ots=kWeIJHaX2k&sig=ACfU3U25gYfnY1WK0uOTMkM6_tsHBndt4g&hl=pt-BR&sa=X&ved=2ahUKEwjn8Pe4odvlAhVYIrkGHY-wDn8Q6AEwAXoECAkQAQ#v=onepage&q=strlen%20call%20repeated&f=false

**Comment by richsalz** [comment]
OpenSSL is a crypto library, not a webserver; the first does lots of math, the second deals with lots of strings.  Without profiling, you don't know if this is useful or just a waste of (er) time.  Sure, it makes the code better, but is it the thing to really work on?  I don't know. Without real measurements, nobody knows in fact.

**Comment by mspncp** [comment]
> No, I did not do, is this really necessary?

No, it isn‘t. Your optimizations are standard best practices and not some tricky premature optimization, which nerds to be justified by profiling IMHO.

**Comment by mspncp** [comment]
Funny autocorrection:  ‚nerds‘ should have been ‚needs‘.

**Comment by mattcaswell** [comment]
> @mattcaswell do you have any objections against cherry-picking to 1.1.1?

No objections.

**Comment by mspncp** [comment]
Merged to master and 1.1.1. Thank you @raniervf and congratulation to your first contribution to OpenSSL!

d1c1fb2d41 conf_def.c: Avoid calling strlen() in a loop [master]
30bd3e5160 conf_def.c: Avoid calling strlen() in a loop [1.1.1]

**Comment by mspncp** [comment]
_@raniervf GitHub shows a note that the pull request was closed with an unmerged branch. It is safe to remove the branch now, in fact I recommend doing it, otherwise your pull request branches will be piling up. At least I do it, others think differently about it, YMMV._

**Comment by raniervf** [comment]
Thank you.

**Pull request closed without merging**
