### PR TITLE
Fix versioned GCC detection

### PR DESCRIPTION
**Pull request by ghedo**
Basically this fixes "make depend" when using e.g. "CC=gcc-5" and also makes Travis run "make depend".

### CODE REVIEW

**Comment by ghedo** [comment]
@ekasper seems that your commit 58dd1ce9 broke this, so you might want to take a look to see if my fix is ok.

@levitte I'm not sure if running make depend on Travis is the right thing, care to comment?

**Comment by levitte** [comment]
Running `make depend` is only strictly necessary if you do repeated updates and builds in the same directory.  Since travis builds always starts with a clean dir, a `make depend` isn't necessary there.

**Comment by ghedo** [comment]
@levitte yes, but with the recent build changes we always get the "you must run make depend" message even on Travis: https://travis-ci.org/openssl/openssl/jobs/102411115#L6185

Maybe it's a separate bug...

**Comment by ghedo** [comment]
Also, IIRC @richsalz mentioned somewhere that running "make depend" is mandatory now (or did I just imagine it?), maybe I should have asked him instead :)

**Comment by levitte** [comment]
We are a bit over the top there, it's true...  I did see it as mandatory just a few days ago, but then realised that for those who just download, unpack, build, test and install and then don't touch it any more, that's strictly speaking not true.

... I'm way too sleepy to do anything about it now, but if noone gets there before me, I might think of some way to reword that "error" message tomorrow...

**Comment by levitte** [comment]
What really *is* mandatory is to run `config` or `Configure`...  I've come to understand that there were some who skipped that step (don't ask me how).

**Comment by ghedo** [comment]
Ok, thanks. We might still want to run it on Travis for testing purposes though (e.g. doing that wold have caught the error I got when running make depend with `CC=gcc-6` much sooner).

**Comment by ekasper** [comment]
@ghedo - I can't quite follow how my commit broke it; it would seem that makedepend detection was already broken before that, because it's testing for equality with "gcc". Anyway, fix seems reasonable, @levitte is the best person to approve the MR.

**Comment by ghedo** [comment]
@ekasper hmmm, you are right, I don't remember my original thought process, I guess I was just too quick to jump to conclusions, sorry :/

**Comment by ghedo** [comment]
@levitte ping? should I just remove the "make depend on Travis" commit?

**Comment by richsalz** [comment]
wait a bit for my "remove clean-depend" change to land, and let's see if this is still needed.

**Comment by ghedo** [comment]
This is fixed in master now.

**Pull request closed without merging**
