### PR TITLE
Include CAESAR support

### PR DESCRIPTION
**Pull request by BenBE**
This pull request adds support for the historically proven CAESAR cipher.

Please consider for merging.

If you need something, just drop a note and I'll update the patches to fix any issues that may have slipped.

Kind regards,
BenBE.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by kroeckx** [comment]
This seems to be very unlikely to get merged.

**Comment by richsalz** [comment]
Happy April Fool's Day.  :)

**Comment by levitte** [comment]
This made my Sunday morning :-)

**Comment by mspncp** [comment]
Please send your signed cla to legal@spqr.com.

**Comment by grindhold** [comment]
this is definitely needed

**Comment by sa0mad** [comment]
The name of this crypto should be the Vigernere. Technically that is not the Caesar crypto, the Caesar crypto uses a fixed shift of symbols, such as 3, where as the generalized one in which a key word is used is called Vigenere which seems to be what is implemented. Cute as it is, at least the name-change would be needed. It does show what needs to go into implementing a crypto into OpenSSL, so that may be a reason to accept it, but not have it default enabled.

**Comment by mspncp** [comment]
Side note from a wise guy with a french last name: The correct name is "Vigenère cipher", with an accent grave. And before it can be considered, the build errors need to be fixed...

**Comment by levitte** [comment]
Comment pouvais-je rater ça? La honte!
(eng: How could I miss that? To shame) 

/the (half) french guy

**Comment by fuzxxl** [comment]
@sa0mad The code does actually implement a Caesar cipher.  It supports multiple rounds with different keys all applied to the same input in order to be useful for triple rot13 as well.  It is not a Vigenère cipher as the same key is used for the entire input.

**Comment by mspncp** [comment]
We should really leave this interesting and educating thread open for a while... :wink:

**Comment by hardfalcon** [comment]
Somebody should add support for using this in some TLS ciphersuites and send a draft proposal to the IETF's TLS WG next year to get those ciphersuites adopted into IANA's registry of TLS parameters.
There should definitely be some AEAD ciphersuites (TLS_*_WITH_CAESAR_POLY1305_SHA256), but of course there should also be a simplified/legacy version for older devices, embedded applications and mounted or avian carriers (TLS_PSK_WITH_CAESAR_NULL).

**Comment by mattcaswell** [comment]
On reflection...I think its probably best that this isn't merged :-)

**Pull request closed without merging**
