### PR TITLE
ecdhtest.c: move co-factor ECDH KATs to evptests

### PR DESCRIPTION
**Pull request by romen**
Follow-up from #3187 , move the remaining cofactor KATs for ECDH to evptests.txt and remove ecdhtest altogether.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by romen** [comment]
@richsalz this one is against 1_1_0_stable, should I create a different one against master?

**Comment by richsalz** [comment]
oops, yeah.  please do so.

**Comment by romen** [comment]
@richsalz Done! ( #3219 )

**Comment by bbbrumley** [comment]
+1 I reviewed this.

@romen Great work! Thank you!

**Comment by bbbrumley** [comment]
@richsalz Hold off on merging. We have a compile time issue we're trying to resolve.

Actually @romen is resolving it. I'm just observing ;)

**Comment by romen** [comment]
@bbbrumley actually it came from our previous PRs ( #3187 , #3188 ).
I fixed it in #3222 and #3223  

@richsalz , @levitte this and #3219 should be safe to merge!

**Comment by romen** [comment]
Merging this PR (and #3219 ) would **add test for binary curves**.
As noted in https://github.com/openssl/openssl/pull/3222#issuecomment-294134456 this raises problem when the test is run with EC support enabled and binary EC support disabled.

I already have a commit (mentioned in the comment above) ready to fix evp_test.c, and it's just a matter merging it in the right PR.

**Comment by richsalz** [comment]
done, thanks!

**Comment by romen** [comment]
As a follow up to the last comment, #3226 and #3227 are the PRs fixing the issue mentioned in https://github.com/openssl/openssl/pull/3222#issuecomment-294134456

**Pull request closed without merging**
