### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kaduk**
##### Checklist

- [x] CCLA is signed

### CODE REVIEW

**Comment by richsalz** [comment]
@kaduk we need an ICLA too.

**Comment by kaduk** [comment]
> @kaduk we need an ICLA too.

Oh, so I should have asked whether the new website text meant for all contributions as opposed to just individual contributions, then.  So be it...

**Comment by levitte** [comment]
Has the CLA situation been resolved?

**Comment by kaduk** [comment]
> Has the CLA situation been resolved?

I sent one in, yes.

**Comment by richsalz** [comment]
We don't have it in our recorsd please resend.

**Comment by kaduk** [comment]
Ah, a 300dpi scan clocks in at about 6MB, but the list holds anything over 3MB for moderation, and apparently the original didn't get moderated through.

**Comment by kaduk** [comment]
(A 200-dpi re-scan seems to have gone through.)

**Comment by richsalz** [comment]
CLA on file now.  Merge away, @levitte :)

**Comment by levitte** [comment]
*Now* I'm discovering it's already been fixed as part of the rename in d49661ced5c2b426ce57f1016077674bfcfa7daf !

**Comment by levitte** [comment]
I was wrong, it was fixed later, here: 79ebfc46817bc5da1082bcdc5bd50905c83fa712

**Pull request closed without merging**
