### PR TITLE
Fix regression in i2d_re_X509_REQ_tbs()

### LINKED ISSUE #19297: return value of `i2d_re_X509_REQ_tbs()`
Hello,

I found that the return value of `i2d_re_X509_REQ_tbs()` was changed since 8e39049d38ebe8b8398d6c4aa8a6f7cef9712132. 
Currently it returns `0` on some errors or `1` unexpectedly. Manpage says:

```
i2d_re_X509_tbs(), i2d_re_X509_CRL_tbs() and i2d_re_X509_REQ_tbs() return the length of encoded data or 0 on error.
```

I guess the `NULL` check for `req` parameter is enough, then returns the result of `i2d_X509_REQ_INFO()` straightforward.

### PR DESCRIPTION
**Pull request by t8m**
This fixes regression from commit 8e39049.

Fixes #19297

### CODE REVIEW

**Review by DDvO — APPROVED** [review]
LGTM

**Comment by DDvO** [comment]
Just found in `crypto/x509/x509cset.c`:
```
int i2d_re_X509_CRL_tbs(X509_CRL *crl, unsigned char **pp)
{
    crl->crl.enc.modified = 1;
    return i2d_X509_CRL_INFO(&crl->crl, pp);
}
```
that at least for some related data types the `modified` flag is set before calling `i2d_`*, apparently to be on the safe side.
Maybe such apparent workarounds are no more needed after the adaptations I added yesterday to #19271 ?

**Comment by davidben** [comment]
Should this have a unit test?

**Comment by t8m** [comment]
> Should this have a unit test?

It should. However IMO this falls under much bigger effort to write the test than the actual fix. We do not have any unit test for i2d_re_* functions nor for the i2d_X509_REQ() function. I could squeeze it in x509_check_cert_pkey_test.c easily, on the other hand it is a little bit weird to piggy-back on quite unrelated test.

**Comment by no6v** [comment]
Thanks for your quick works.

> Just found in `crypto/x509/x509cset.c`:
> 
> ```
> int i2d_re_X509_CRL_tbs(X509_CRL *crl, unsigned char **pp)
> {
>     crl->crl.enc.modified = 1;
>     return i2d_X509_CRL_INFO(&crl->crl, pp);
> }
> ```
> 
> that at least for some related data types the `modified` flag is set before calling `i2d_`*, apparently to be on the safe side. 

```
The "re" in i2d_re_X509_tbs stands for "re-encode", and ensures that a
fresh encoding is generated in case the object has been modified after
creation (..snip..)

If, after modification, the X509 object is re-signed with X509_sign(),
the encoding is automatically renewed. Otherwise, the encoding of the
TBSCertificate portion of the X509 can be manually renewed by calling
i2d_re_X509_tbs().
```

My understanding from reading the above part of manpage is that setting the `modified` flag before calling relevant functions tells them to invalidate the internal cache, so the renewed TBS portion will be encoded.

> Maybe such apparent workarounds are no more needed after the adaptations I added yesterday to #19271 ?

If your work resolves this situation, that will be great, thanks.

**Comment by davidben** [comment]
More reason to write a test, since it seems 8e39049d38ebe8b8398d6c4aa8a6f7cef9712132 regressed more than just the return code! :-) (It used to be in the right order, but then 8e39049d38ebe8b8398d6c4aa8a6f7cef9712132 broke it.)

**Comment by t8m** [comment]
> More reason to write a test, since it seems [8e39049](https://github.com/openssl/openssl/commit/8e39049d38ebe8b8398d6c4aa8a6f7cef9712132) regressed more than just the return code! :-) (It used to be in the right order, but then [8e39049](https://github.com/openssl/openssl/commit/8e39049d38ebe8b8398d6c4aa8a6f7cef9712132) broke it.)

Feel free to write one.

**Comment by no6v** [comment]
de54030f4e085fe45f03351f944f9eeab9099d9e looks good to me, thanks!

**Comment by t8m** [comment]
@DDvO still OK?
ping @openssl/otc for otc review.

**Review by hlandau — APPROVED** [review]

**Comment by DDvO** [comment]
> @DDvO still OK?

Yep

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for the reviews.

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Kha, 29 Sep 2022, 7:02 PM Tomáš Mráz ***@***.***>
menulis:

**Pull request closed without merging**
