### PR TITLE
ssl_cert: use the recommended minimum hash from RFC 5480 for EC

### PR DESCRIPTION
**Pull request by sebastianas**
A TLS1.2 connetion with openssl server and gnutls-cli using a SECP384R1
key ends up with SHA256 as the hash algorithm for signing the key exchange.
This is because gnutls sends the hash algorithms from weak to strong
and by default client's preference is used.

gnutls complains about this situation:
|<1>| The hash size used in signature (32) is less than the expected (48)

The complaint is based on the recommendation in RFC 5480, section 4.
Security Considerations. There two ways to fix it:
- Using
  -sigalgs "ECDSA+SHA384:ECDSA+SHA512:ECDSA+SHA256:ECDSA+SHA224:ECDSA+SHA1"
  -serverpref
 The weaker algorithms

- The following patch which eliminates SHA256+SHA224 from the list of
  possible candidates. SHA1 is still available if left out in -sigalgs
  and nothing else matches.

BTS: https://bugs.debian.org/686470
RT:  https://rt.openssl.org/Ticket/Display.html?id=4496
Signed-off-by: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>

### CODE REVIEW

**Comment by mattcaswell** [comment]
Really gnutls should not offer algorithms that it is not prepared to accept.

Also if sha256 with p256 is considered acceptable security, why wouldn't sha256 with p384 be?

OpenSSL is obeying RFC5246 7.4.1.4.1:

   Each SignatureAndHashAlgorithm value lists a single hash/signature
   pair that the client is willing to verify.  The values are indicated
   in descending order of preference.

So I don't think this is an OpenSSL bug. Closing this ticket.

Matt

**Comment by sebastianas** [comment]
RFC5246, fine. But I was talking about [RFC5480](https://tools.ietf.org/html/rfc5480#section-4) saying:

>To promote interoperability, the following choices are RECOMMENDED:
>
>   Minimum  | ECDSA    | Message    | Curves
>   Bits of  | Key Size | Digest     |
>   Security |          | Algorithms |
>   ---------+----------+------------+-----------
>   80       | 192      | SHA-256    | secp192r1
>   ---------+----------+------------+-----------
>   112      | 224      | SHA-256    | secp224r1
>   ---------+----------+------------+-----------
>   128      | 256      | SHA-256    | secp256r1
 >  ---------+----------+------------+-----------
 >  192      | 384      | SHA-384    | secp384r1
 >  ---------+----------+------------+-----------
 >  256      | 512      | SHA-512    | secp521r1
 >  ---------+----------+------------+-----------

The RFC also says:
>It is recommended that the bits of security provided by each choice are roughly equivalent.

So SHA256 has not enough "bits" compared to be roughly equivalent. Please don't close this as it.

**Comment by mattcaswell** [comment]
If SHA256 does not offer sufficient security for the client then the client should not offer it. If SHA256 does provide sufficient security then both p256 or p384 would be acceptable choices. This is not an OpenSSL bug.

**Comment by sebastianas** [comment]
But at the time of sending the supported ciphers, the client does not know the key, does he?

**Comment by mattcaswell** [comment]
The client knows what level of security is acceptable. Is 128 security bits acceptable or is 192 security bits required? If the former then SHA256 is good enough with either p256 or p384. If 192 security bits is required then SHA256 should not be offered.

**Comment by richsalz** [comment]
Also, the RFC says roughly equivalent.  Requiring every stage to have the same number of bits of strength is not a requirement.

**Comment by briansmith** [comment]
I do not understand the argument that Matt and Rich are making. When signing with ECDSA P-384, if the client says it supports ECDSA+SHA-384, then SHA-384 should be used. When signing with ECDSA P-521, if the client says it supports ECDSA+SHA-512, then SHA-512 should be used. etc. Only if the client doesn't advertise support for the recommend paired digest algorithm should the server try a non-recommended pairing.

Note that the above is in line with the current TLS 1.3 draft's changes in this area, and also in line with the Suite B profile for TLS. Making such a change it's purely an improvement with no significant downside.

Is gnutls wrong? Well, it isn't doing what I would do. But, IMO, it hardly matters.

**Comment by kroeckx** [comment]
So as I understand it, the change would like to enforce TLS parameters based on the a property of the certificate.  As far as I know, we currently don't do any such things, and this only seems to change it for 1 case.  As far as I know we only enforce certain TLS settings and certificate properties based on the security level that was set.

A change like this seems to have a high chance of breaking things, as GnuTLS has shown, and we should clearly be careful with that.

**Comment by briansmith** [comment]
>  the change would like to enforce TLS parameters based on the a property of the certificate.

Isn't this already done for the choice of cipher suite? That is, you can't choose a `TLS_...ECDSA...` cipher suite if you only have an RSA certificate and vice versa.

> A change like this seems to have a high chance of breaking things, as GnuTLS has shown, and we should clearly be careful with that.

OTOH, the current behavior is already broken for any Suite B profile client or, apparently, GnuTLS. So, while the likelihood of a change breaking things is > 0%, the likelihood of not making a change breaking things is 100%.

**Comment by mattcaswell** [comment]
> When signing with ECDSA P-384, if the client says it supports ECDSA+SHA-384, then SHA-384 should be used. When signing with ECDSA P-521, if the client says it supports ECDSA+SHA-512, then SHA-512 should be used. etc. Only if the client doesn't advertise support for the recommend paired digest algorithm should the server try a non-recommended pairing.

Where is it specified for TLS1.2 that we should do so?

> Note that the above is in line with the current TLS 1.3 draft's changes in this area, and also in line with the Suite B profile for TLS.

But we are talking about TLS1.2. When it comes to implement TLS1.3 we will obviously follow that standard - but we should not blindly try to retrofit recommendations from TLS1.3 to TLS1.2.

> OTOH, the current behavior is already broken for any Suite B profile client or, apparently, GnuTLS. So, while the likelihood of a change breaking things is > 0%, the likelihood of not making a change breaking things is 100%.

That is an over simplification. How should we rate the scale of breakage (e.g. how many suite B profile clients are there out there vs non suite B profile clients)? Conflicting standards is nothing new of course - but it is far from clear that OpenSSL throwing in our own take on non-standard behaviour is helpful or wise.

**Comment by briansmith** [comment]
> Where is it specified for TLS1.2 that we should do so?

It isn't, as far as I know. I'm not saying that OpenSSL is nonconformant with the TLS spec. I'm just saying it's suboptimal for the reasons given. Also violates the principle of least surprise.

**Comment by mattcaswell** [comment]
> It isn't, as far as I know. I'm not saying that OpenSSL is nonconformant with the TLS spec. I'm just saying it's suboptimal for the reasons given. Also violates the principle of least surprise.

There are lots of things in the TLS specs that are less than optimal ;-) - that doesn't mean it is appropriate for OpenSSL to attempt to redefine the specs. Better is that the specs are improved - and hopefully TLS1.3 represents just such an improvement - which we will implement when the time comes.

**Comment by sebastianas** [comment]
>A change like this seems to have a high chance of breaking things, as GnuTLS has shown, and we 
>should clearly be careful with that.

GnuTLS explictly aborted when a lower hash was used. This change does not abort but it would 
continue with SHA1. The only downside (as of the current implementation) would be if we would have rejected SHA256 and then fallback to SHA1.

>Also, the RFC says roughly equivalent. Requiring every stage to have the same number of bits of strength is not a requirement.

What you mean every stage? Without the change you use the first match (in every stage).

>If 192 security bits is required then SHA256 should not be offered.

As noted earlier, the hash algorithm depends on the key/curve used which (not my understanding) is not know earlier.
GnuTLS sends the hash algorihms in the order: SHA224, SHA256, SHA384, SHA512 while openssl 
does it in the reverse order. So as-is (default) it always aligns with SHA224 because it is the first match. Using the "server prefrence" option would always negotiate with SHA512. This is sub optimal. You basically force people to specify their own hash properties if they want to follow the security considerations from RFC5480.

Until now I got "we follow RFC5246, it is not a bug" and "TLS 1.3 does not matter we care about when time comes". What is wrong with following the security considerations from RFC5480? Is is jut because it says "recommended" instead of "must"? It can't be fulfilled on the client side (at least to my  understanding).

**Comment by mattcaswell** [comment]
>> Also, the RFC says roughly equivalent. Requiring every stage to have the same number of bits of strength is not a requirement.

>What you mean every stage? Without the change you use the first match (in every stage).

There are many components in the ciphersuite. You are just focusing on one aspect. Should we also implement restrictions that the symmetric cipher bit strength should agree with the sigalgs bit strength?

>> If 192 security bits is required then SHA256 should not be offered.

> As noted earlier, the hash algorithm depends on the key/curve used which (not my understanding) is not know earlier.

You do not need to know the curve in order to decide how many security bits you want. If you want 192 security bits only offer curves (in the elliptic curves extension) that you are prepared to accept and offer that security level. Only offer hash algorithms in the sigalgs extension that also offer that security bit level. If you do that you will never get a selection back from the server that falls below the level of security bits that you want. You *might* get some components (such as the curve) using an even higher level than the minimum you offered, with some components only at your offered minimum. But that doesn't matter - it won't be lower than you are prepared to accept.

What you are asking for is a level of control over the selection that TLS1.2 does not provide. If you want that level of control then we need another standard.

It is far from clear to me that forcing OpenSSL to select security bit levels *above* the minimum that both sides are asking for is an improvement. To some that might be considered a detrimental change and I could foresee a scenario where people raise that as a bug report and ask us to change it back again!

> What is wrong with following the security considerations from RFC5480

The section in that RFC that you are referring to is useful generic advice, but it is advice given in another context. It is advice given to CAs in reference to issuing certificates and CRLs. It does not apply directly to TLS. Clearly it is optimal for all components in the ciphersuite to have equivalent security bit level strength. Ideally the target is that you determine what level of security bits you want and choose all components to agree with that. If you select some components that are higher than your required level then that is sub-optimal because you are wasting resources performing operations that are beyond what you need. In some situations though it may be that you are *forced* to select a curve (say) that is higher than you actually need. Yes - that is sub-optimal. It is even less optimal if you then push up all the other components to the same security bit level which was higher than you needed in the first place!

**Comment by kroeckx** [comment]
So it's my understanding that what GnuTLS did was: If the server offers a certificate with a P-384 certificate, it thinks it should upgrade to 192 bit security at the TLS level.  But if the server wasn't configured to do this 192 bit security level, GnuTLS just fails.

In this case the server wasn't configured to do this 192 bit level, and I think it's wrong for the client to require this 192 bit level based on the certificate.  I think it's the server that should force this 192 bit level if it's required.

I think it's also wrong of GnuTLS to send the list of supported algorithms from weakest to strongest and then hope the server picks one GnuTLS is going to like.

It might make sense for the server to automatically prefer a stronger algorithm based on it's certificate, and the strength of certificate is probably related to the strength the admin of the server expects to get.  But that then you might end up with behaviour that you don't really expect.  For instance if a client only offers SHA-256, you still want SHA-256.  If it offers SHA-256, SHA-384 and SHA-512 in that order, and you set to honour the clients preferences, it might suddenly pick SHA-384.  And if it offers SHA-256 and SHA-512 it might pick SHA-512.  So you'd basically reorder the clients preferences to put SHA-256 latest.  It makes more sense to me that you would then explicitly configure the order on the server side and tell it to use that order.

**Comment by sebastianas** [comment]
On 2016-06-08 01:21:20 [-0700], mattcaswell wrote:
> >> Also, the RFC says roughly equivalent. Requiring every stage to have the same number of bits of strength is not a requirement.
> 
> >What you mean every stage? Without the change you use the first match (in every stage).
> 
> There are many components in the ciphersuite. You are just focusing on one aspect. Should we also implement restrictions that the symmetric cipher bit strength should agree with the sigalgs bit strength?

I see. It would be consistent with the RFC but yes I didn't consider
that part.

> >> If 192 security bits is required then SHA256 should not be offered.
> 
> > As noted earlier, the hash algorithm depends on the key/curve used which (not my understanding) is not know earlier.
> 
> You do not need to know the curve in order to decide how many security bits you want. If you want 192 security bits only offer curves (in the elliptic curves extension) that you are prepared to accept and offer that security level. Only offer hash algorithms in the sigalgs extension that also offer that security bit level. If you do that you will never get a selection back from the server that falls below the level of security bits that you want. You *might* get some components (such as the curve) using an even higher level than the minimum you offered, with some components only at your offered minimum. But that doesn't matter - it won't be lower than you are prepared to accept.
> 
> What you are asking for is a level of control over the selection that TLS1.2 does not provide. If you want that level of control then we need another standard.

My understanding was that this is not part of TLS1.2 but can be
implemented since it does not break anything.

> It is far from clear to me that forcing OpenSSL to select security bit levels *above* the minimum that both sides are asking for is an improvement. To some that might be considered a detrimental change and I could foresee a scenario where people raise that as a bug report and ask us to change it back again!

I understand that. My point was simply that the client does not know the
key size before sending the ciphers.
As I said earlier: Using the "server prefences" would get it properly
(without the patch) but you would need to manually alter the default
settings (because otherwise you would end up with SHA512 because OpenSSL
default order is bigger -> smaller).

> > What is wrong with following the security considerations from RFC5480
> 
> The section in that RFC that you are referring to is useful generic advice, but it is advice given in another context. It is advice given to CAs in reference to issuing certificates and CRLs. It does not apply directly to TLS. Clearly it is optimal for all components in the ciphersuite to have equivalent security bit level strength. Ideally the target is that you determine what level of security bits you want and choose all components to agree with that. If you select some components that are higher than your required level then that is sub-optimal because you are wasting resources performing operations that are beyond what you need. In some situations though it may be that you are *forced* to select a curve (say) that is higher than you actually need. Yes - that is sub-optimal. It is even less optimal if you then push up all the other components to the same security bit level which was higher than you needed in the first place!

Undestood. We are not CA here but TLS and forcing higher more than we
got in the initial handshake might be sub-optimal.

What about the default order of the hash ciphers? They start with
SHA512. If you force server's preference you end up with that one
(assuming the client supports, too). Would you prefer changing the
default from smaller to larger or should the user configure the sigalgs
himself?

Thank you for explanation. The way things are now I am going the close
the referenced Debian bug and recommend the reporter to manually specify
the sigalgs if he wants the avoid the GnuTLS warning.

Sebastian

**Comment by sebastianas** [comment]
On 2016-06-08 09:45:56 [-0700], Kurt Roeckx wrote:
> So it's my understanding that what GnuTLS did was: If the server offers a certificate with a P-384 certificate, it thinks it should upgrade to 192 bit security at the TLS level.  But if the server wasn't configured to do this 192 bit security level, GnuTLS just fails.

Correct. GnuTLS sends the smallest hash first and by default OpenSSL
uses client's order. So the connection at TLS level negotiated SHA224
which was not enough for GnuTLS and it aborted.

> In this case the server wasn't configured to do this 192 bit level, and I think it's wrong for the client to require this 192 bit level based on the certificate.  I think it's the server that should force this 192 bit level if it's required.

This is option B. Setting -sigalg and set "server preference".

> I think it's also wrong of GnuTLS to send the list of supported algorithms from weakest to strongest and then hope the server picks one GnuTLS is going to like.

My understanding is (which might be wrong since I know 0 about SSL) that
GnuTLS learns the used key after it sent the ciphers. But still if I
understood Matt correct, then GnuTLS uses a RFC for TLS parameters which
was not meant to be used there (but in a CA).
 
> It might make sense for the server to automatically prefer a stronger algorithm based on it's certificate, and the strength of certificate is probably related to the strength the admin of the server expects to get.  But that then you might end up with behaviour that you don't really expect.  For instance if a client only offers SHA-256, you still want SHA-256.  If it offers SHA-256, SHA-384 and SHA-512 in that order, and you set to honour the clients preferences, it might suddenly pick SHA-384.  And if it offers SHA-256 and SHA-512 it might pick SHA-512.  So you'd basically reorder the clients preferences to put SHA-256 latest.  It makes more sense to me that you would then explicitly configure the order on the server side and tell it to use that order.

So that is actually what I attempted with my patch here. And it does
this based on my testing. Excpet for one tiny thing:
In the current patch if the client offers only SHA-256 and based on the
key in the certificate we would need SHA-384+ then we would fallback to
SHA-1. Continue with SHA-256 instead would be better.

Sebastian

**Comment by mattcaswell** [comment]
> What about the default order of the hash ciphers? They start with
SHA512. If you force server's preference you end up with that one
(assuming the client supports, too). Would you prefer changing the
default from smaller to larger or should the user configure the sigalgs
himself?

Certainly the user should consider configuring the sigalgs. Really it should be a user policy decision - but we need to have some kind of sensible default. At the moment the ordering prefers security over performance, which I guess is a sensible cautious approach. But I'm sure there are good arguments to go the other way too. It won't be changed in any of the stable branches, and I think it's highly unlikely we would change it for the upcoming 1.1.0 release either. Perhaps once past that it is worthy of a debate.

**Pull request closed without merging**
