### PR TITLE
Use C locale in Bash scripts.

### PR DESCRIPTION
**Pull request by faramir-dev**
Fixes openssl#17228.

It looks that eg. `date +%b` is based on current locale and it can print the name of a month in some other language, so it is better to force `C` locale in the scripts.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by levitte — CHANGES_REQUESTED** [review]
The files you touch are sourced by dev/release.sh, precisely here:

https://github.com/openssl/openssl/blob/0fdb31669f88cbf5d63ba16d82d95c6c84575dc0/dev/release.sh#L211-L213

It does seem easier (and cleaner) to simply set LC_ALL directly in dev/release.sh

**Comment by levitte** [comment]
@faramir-dev, FYI, a very simple way to add a commit that fixes up an existing commit is this: `git commit --fixup={commit-id of existing commit}`

Later on, when someone merges this PR, they can do automate squashing the commits together like this: `git rebase -i --autosquash origin/master`

**Review by mattcaswell — APPROVED** [review]
LGTM

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Merged

master:
bd654f7e98e13c0dc3b5c707880b9a77ba9e342f Use C locale in Bash scripts.

3.0:
cfbcfe86c2ccdd308fc6fa3d3245dd6eb5774b0e Use C locale in Bash scripts.

**Pull request closed without merging**
