### PR TITLE
Make all of man1 have .in files

### PR DESCRIPTION
**Pull request by richsalz**
This is easier, and makes .gitignore accurate.

Fixes: 16435

### CODE REVIEW

**Comment by levitte** [comment]
Not sure I understand what is easier...

**Comment by richsalz** [comment]
It is easier than making `.gitignore` be correct.

**Comment by t8m** [comment]
I do not understand how it fixes #16435
Can you please explain?

**Comment by richsalz** [comment]
It fixes #15435 because all `*.pod` files are in the `.gitignore` file and I had an old one from a previous build and it was causing `make` to do strange things regenerating files.  The solution is to update the `.gitignore` file to be correct (having `man1/*.pod` is wrong) or to make that file correct by only have `.in` files there.

**Comment by richsalz** [comment]
Right now, if someone edits `doc/man1/tsget.pod` then git is unlikely to find changed since you told git to ignore it.

**Comment by t8m** [comment]
> Right now, if someone edits `doc/man1/tsget.pod` then git is unlikely to find changed since you told git to ignore it.

Ah ok, but that does not solve the problem of leftover `openssl-provider.pod` because that one will still cause make update to do the thing.

**Comment by richsalz** [comment]
> Ah ok, but that does not solve the problem of leftover openssl-provider.pod because that one will still cause make update to do the thing.

Maybe.  At any rate, `.gitignore` is wrong and this makes it correct. And avoids future problems because everyone will just add a `.pod.in` file when they make a new command now.

I can remove the "Fixes" notation if you remove the "post-3.0" one :)

**Comment by t8m** [comment]
It needs to be decided by OTC whether this is something for 3.0.0.

**Comment by t8m** [comment]
So marking with 3.0.0 milestone.

**Comment by richsalz** [comment]
Is this approved for 3.0 or not?

**Comment by t8m** [comment]
> Is this approved for 3.0 or not?

No, it isn't.

**Comment by richsalz** [comment]
Thanks for the direct, albeit disappointing, answer, @t8m!

**Pull request closed without merging**
