### PR TITLE
Update NOTES-UNIX.md CLA: trivial

### PR DESCRIPTION
**Pull request by Zengit123**
I just wasted almost 2 hours troubleshooting, because lowercase L and 1 look too similar, this should help some people save time.

CLA: Trivial

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
No, it is not sufficient to only place the text in the GitHub pull request description :(

The https://github.com/openssl/openssl/blob/master/CONTRIBUTING.md file contains an instruction.

**Comment by Zengit123** [comment]
I am using the web-version, the fix was done on the web also. Not sure there is anything else I can change this way, sorry, I am not fluent with git in command line.

**Comment by Zengit123** [comment]
Thank you for understanding.
I consider my pull commit trivial.

**Comment by mattcaswell** [comment]
I have no idea why the bot has flagged this as a FIPS change?? @t8m?

**Comment by Zengit123** [comment]
Has this pull request broken the bot?

**Comment by t8m** [comment]
I suppose the evp_enc checksum issue was just a race with the commit being merged and the test running.

**Comment by t8m** [comment]
> Has this pull request broken the bot?

No, not really.

**Review by slontis — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
I agree with CLA: trivial.

**Comment by t8m** [comment]
Merged to master.

**Pull request closed without merging**
