### PR TITLE
Fix two recent MinGW build issues

### LINKED ISSUE #19907: rsapssSaltlen (80-test_cms) failed on MSYS2/Win32/MinGW
Master branch, OpenSSL 3.2 dev building process went fine. During test phase got this:
```
80-test_cms.t ........................... 4/?
    # CMD: openssl cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1.pem -keyopt rsa_padding_mode:pss -keyopt rsa_pss_saltlen:max -out cms2cms-mod-2.cms
../../util/wrap.pl ../../apps/openssl.exe cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1.pem -keyopt 'rsa_padding_mode:pss' -keyopt 'rsa_pss_saltlen:max' -out cms2cms-mod-2.cms => 0
../../util/wrap.pl ../../apps/openssl.exe asn1parse -in cms2cms-mod-2.cms -dump => 0
    # 0
    # CMD: openssl cms -provider-path ../../providers -provider default -verify -in cms2cms-mod-2.cms -inform PEM -CAfile ../../test/smime-certs/smroot.pem -out cms2cms-mod-2.txt
    not ok 3 - signed content test streaming PEM format, RSA keys, PSS signature, saltlen=max
# ------------------------------------------------------------------------------
    # CMD: openssl cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1.pem -md sha256 -keyopt rsa_padding_mode:pss -keyopt rsa_pss_saltlen:16 -out cms2cms-mod-5.cms
../../util/wrap.pl ../../apps/openssl.exe cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1.pem -md sha256 -keyopt 'rsa_padding_mode:pss' -keyopt 'rsa_pss_saltlen:16' -out cms2cms-mod-5.cms => 0
../../util/wrap.pl ../../apps/openssl.exe asn1parse -in cms2cms-mod-5.cms -dump => 0
    # 0
    # CMD: openssl cms -provider-path ../../providers -provider default -verify -in cms2cms-mod-5.cms -inform PEM -CAfile ../../test/smime-certs/smroot.pem -out cms2cms-mod-5.txt
    not ok 6 - signed content test streaming PEM format, RSA keys, PSS signature, saltlen=16
# ------------------------------------------------------------------------------

    #   Failed test 'signed content test streaming PEM format, RSA keys, PSS signature, saltlen=16'
    #   at test/recipes/80-test_cms.t line 721.
    # CMD: openssl cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1.pem -md sha256 -keyopt rsa_padding_mode:pss -keyopt rsa_pss_saltlen:digest -out cms2cms-mod-6.cms
../../util/wrap.pl ../../apps/openssl.exe cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1.pem -md sha256 -keyopt 'rsa_padding_mode:pss' -keyopt 'rsa_pss_saltlen:digest' -out cms2cms-mod-6.cms => 0
../../util/wrap.pl ../../apps/openssl.exe asn1parse -in cms2cms-mod-6.cms -dump => 0
    # 0
    # CMD: openssl cms -provider-path ../../providers -provider default -verify -in cms2cms-mod-6.cms -inform PEM -CAfile ../../test/smime-certs/smroot.pem -out cms2cms-mod-6.txt
    not ok 7 - signed content test streaming PEM format, RSA keys, PSS signature, saltlen=digest
# ------------------------------------------------------------------------------
    # CMD: openssl cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1.pem -md sha256 -keyopt rsa_padding_mode:pss -keyopt rsa_pss_saltlen:auto-digestmax -out cms2cms-comp-1.cms
../../util/wrap.pl ../../apps/openssl.exe cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1.pem -md sha256 -keyopt 'rsa_padding_mode:pss' -keyopt 'rsa_pss_saltlen:auto-digestmax' -out cms2cms-comp-1.cms => 0
../../util/wrap.pl ../../apps/openssl.exe asn1parse -in cms2cms-comp-1.cms -dump => 0
    # 0
    # CMD: openssl cms -provider-path ../../providers -provider default -verify -in cms2cms-comp-1.cms -inform PEM -CAfile ../../test/smime-certs/smroot.pem -out cms2cms-comp-1.txt
    not ok 18 - signed content test streaming PEM format, RSA keys, PSS signature, saltlen=auto-digestmax, digestsize < maximum salt length
# ------------------------------------------------------------------------------

    #   Failed test 'signed content test streaming PEM format, RSA keys, PSS signature, saltlen=auto-digestmax, digestsize < maximum salt length'
    #   at test/recipes/80-test_cms.t line 721.
    # CMD: openssl cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1024.pem -md sha512 -keyopt rsa_padding_mode:pss -keyopt rsa_pss_saltlen:auto-digestmax -out cms2cms-comp-2.cms
../../util/wrap.pl ../../apps/openssl.exe cms -provider-path ../../providers -provider default -sign -in ../../test/smcont.txt -outform PEM -nodetach -signer ../../test/smime-certs/smrsa1024.pem -md sha512 -keyopt 'rsa_padding_mode:pss' -keyopt 'rsa_pss_saltlen:auto-digestmax' -out cms2cms-comp-2.cms => 0
../../util/wrap.pl ../../apps/openssl.exe asn1parse -in cms2cms-comp-2.cms -dump => 0
    # 0
    # CMD: openssl cms -provider-path ../../providers -provider default -verify -in cms2cms-comp-2.cms -inform PEM -CAfile ../../test/smime-certs/smroot.pem -out cms2cms-comp-2.txt
    not ok 19 - signed content test streaming PEM format, RSA keys, PSS signature, saltlen=auto-digestmax, digestsize > maximum salt length
# ------------------------------------------------------------------------------

    #   Failed test 'signed content test streaming PEM format, RSA keys, PSS signature, saltlen=auto-digestmax, digestsize > maximum salt length'
    #   at test/recipes/80-test_cms.t line 721.
    # Looks like you failed 5 tests of 19.
not ok 5 - CMS <=> CMS consistency tests, modified key parameters
80-test_cms.t ........................... 16/? ---------------------------------
80-test_cms.t ........................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/16 subtests
```
If I comment out the lines with rsapssSaltlen calls (5 times in 80-test_cms.t, lines 502, 533, 545, 646 & 659 currently) 80-test_cms.t will pass w/o errors.

### LINKED ISSUE #19921: 25-test_pkcs8 (test 3) failed on MSYS2/Win32/MinGW
Master branch, testing OpenSSL 3.2 dev after successful building process:
```
25-test_pkcs8.t ......................... 1/?
not ok 3 - compare test/certs/sm2.key to sm2.key
# ------------------------------------------------------------------------------
#   Failed test 'compare test/certs/sm2.key to sm2.key'
#   at /home/User/openssl-master/util/perl/OpenSSL/Test.pm line 913.
#          got: '1'
#     expected: '0'
25-test_pkcs8.t ......................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests
```
The reason is absolutely obvious and is related to the differences in new line styling between Windows (\r\n) and POSIX (\n) in file test/certs/sm2.key
I guess it's very easy to fix. Thanks!

### PR DESCRIPTION
**Pull request by t8m**
Fixes #19907
Fixes #19921 

##### Checklist

- [x] tests are added or updated

Only the 80-test_cms.t fix applies to 3.1 branch. The other test is not present on 3.1 branch.

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by Tarnum-tst** [comment]
@t8m
The "$" symbol should also be removed from line 829 (80-test_cms.t) . After that change the test will pass on my system (MSYS2/Win32/MinGW). Thanks!

**Comment by t8m** [comment]
> @t8m The "$" symbol should also be removed from line 829 (80-test_cms.t) . After that change 80-test_cms.t passed on my system without errors (MSYS2/Win32/MinGW). Thanks!

OK, done

**Comment by t8m** [comment]
@beldmit still OK?

Ping for second review.

**Comment by beldmit** [comment]
Yes, still OK

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
Merged both commits to master branch and cherry-picked the test_cms fix to 3.1 and 3.0 branches where it applies cleanly. Thank you for the reviews.

**Pull request closed without merging**
