### PR TITLE
Add missing -verbosity option to apps/cmp.c and add log output also in crypto/cmp

### PR DESCRIPTION
**Pull request by DDvO**
Extend log output, which is important for debugging CMP applications
in particular with non-trivial failures of certificate validation and cert chain building.

* Add `-verbosity` option to apps/cmp.c, which had been missing so far such that debug outpug was invisible.
* Add log output in setup_ssl_ctx() of the cmp app, ossl_cmp_msg_add_extraCerts(),
OSSL_CMP_validate_msg(), and OSSL_CMP_MSG_http_perform().
* Correct suppression of log output with insufficient severity.
* Add logging/severity level `OSSL_CMP_LOG_TRACE` = OSSL_CMP_LOG_MAX.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by DDvO** [comment]
This extension is important for the usability of the CMP application.
Therefore I'd appreciate a swift review such that this PR can be merged before feature freeze on the beta1 release.

**Review by t8m — APPROVED** [review]
LGTM

**Review by t8m — CHANGES_REQUESTED** [review]
Except the build failure is relevant.

**Comment by DDvO** [comment]
Thanks a log for the immediate response!

> Except the build failure is relevant.

I think I found and fixed the reason - a strict compiler warning that my gcc did not give.

**Comment by t8m** [comment]
Still strict warning related failures

**Comment by DDvO** [comment]
> Still strict warning related failures

Ah yes - second try...

**Comment by DDvO** [comment]
Meanwhile found a simpler and cleaner solution, and also those gcc versions are happy with it :)
The delta is in the fixup commit.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
Merged - thanks @t8m

**Pull request closed without merging**
