### PR TITLE
Appveyor: add msvc 2017, 2013, 2012, 2010, 2008; mingw, android

### PR DESCRIPTION
**Pull request by KangLin**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
We used to have many of these targets but removed them because AppVeyor couldn't keep up. I think this is still likely to be the case since there appears to be 40 AppVeyor builds queued for this one PR. So far its been running for over 4 hours and its still only half way through.

**Comment by KangLin** [comment]
Yes, It is slow. so full coverage test only when "$appveyor_repo_tag" = "true". Usually, each platform tests a situation

**Comment by KangLin** [comment]
If don't test mingw and android in appveyor, then you can't find the error in time, just like now.
See: https://ci.appveyor.com/project/KangLin/openssl/builds/20752589

**Comment by KangLin** [comment]
> Current script is cutting the burden , when building any PR .
> Did you keep this point ?

Yes.

**Comment by kroeckx** [comment]
Most of them don't actually seem to be doing anything useful. We used to have many targets on appveyer, but it was really slow, so we made a limit. Maybe it's useful to have an android and mingw target on travis instead?

**Pull request closed without merging**
