### PR TITLE
Exit with error if config fails

### PR DESCRIPTION
**Pull request by bernd-edlinger**
config needs to return an error if Configure fails.

We noticed this because:
"./config && make depend && make"
actually "worked" with perl 5.8.8 installed!

It was just odd, that it did not use gcc but cc...

### CODE REVIEW

**Comment by mspncp** [comment]
@bernd-edlinger, I thought this might interest you: 

only recently I learned that it is possible to [retarget a pull request ](https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request) instead of closing it and creating a new one, if one has chosen the wrong target branch. Just press the [Edit] button next to the pull request's title and the target branch name will be replaced by a combo box.

**Comment by mspncp** [comment]
Bitte, gern geschehen! ;-)

**Comment by levitte** [comment]
Bon alors, "Danke", je pige, mais sinon, l'allemand c'est plutôt pouic, alors si on pouvait se tenir à l'anglais, ce serait super!

**Comment by mspncp** [comment]
> Bitte, gern geschehen! ;-)

En anglais:  Your welcome, my pleasure!

**Comment by bernd-edlinger** [comment]
And many thanks to Google Translator!

**Comment by richsalz** [comment]
If anyone is going to get into a language competition with @levitte, just give up now.

**Pull request closed without merging**
