### PR TITLE
util/find-docs-nits: Extend to handle internal documentation

### PR DESCRIPTION
**Pull request by levitte**
While we're at it, we also check for names that contain white-space,
as they are invalid.

### CODE REVIEW

**Comment by levitte** [comment]
Should this go to 1.1.1 as well?

**Comment by levitte** [comment]
I will not correct uncovered errors in POD files here, that will be for another PR.  I actually do expect Travis to give us a red cross.

**Review by paulidale — APPROVED** [review]
Unsure about 1.1.1, it doesn't have either doc/internal or crypto/sparse_array.c so it isn't immediately useful.

**Comment by levitte** [comment]
Merged.

4460ad90af0338abe31286f29b36baf2e41abf19 util/find-docs-nits: Recognise SPARSE_ARRAY_OF
23ab880d423bb72f4f3e9efc2274bf38918cab74 util/find-docs-nits: Extend to handle internal documentation

**Pull request closed without merging**
