### PR TITLE
Fix double free bugs located by static analyser

### PR DESCRIPTION
**Pull request by paulidale**
Fix a number of double free on error path issues.

Fixes 14913, 14914 & 14915

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by FdaSilvaYY** [comment]
Some of this change deserve a backport to 1.1.1 , no ?

**Comment by t8m** [comment]
> Some of this change deserve a backport to 1.1.1 , no ?

Would you like to submit a PR?

**Comment by FdaSilvaYY** [comment]
> 
> 
> > Some of this change deserve a backport to 1.1.1 , no ?
> 
> Would you like to submit a PR?

Yes, i will .

**Comment by paulidale** [comment]
I cherry picked the relevant commits to 1.1.1.  There were all clean.

**Pull request closed without merging**
