### PR TITLE
Remove internal libctx from legacy provider.

### PR DESCRIPTION
**Pull request by slontis**
The code was originally copied from the fips provider which actually
needs a internal libctx. The libctx is now just set to the core libctx
(like the default provider).
This fixes the issue in PR #14326, which added the first algorithm
(KDF) that fetches another algorithm (digest) - which fell over since the internal
libctx in the legacy provider was empty.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
FYI @jon-oracle

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
This change is incorrect and should not go in. Unlike the default provider, which is internal to libcrypto, the legacy provider is not. This could mean that the legacy provider and the application are linked against different versions of libcrypto and therefore this could go horribly wrong.

**Comment by paulidale** [comment]
Won't the run time linker deal with this?  So long as the libctx pointer is treated as opaque, it should work.

It doesn't look like all of the fetching code is in liblegacy currently.  Some seems to be (properties) but not other bits.

**Comment by mattcaswell** [comment]
> Won't the run time linker deal with this?

What about if the application is statically linked?

**Comment by paulidale** [comment]
This is something we're going to need to address.  And probably before beta 1 since it will likely involve API changes.

It is entirely reasonable for algorithms to fetch other algorithms, either from their provider or another.

**Comment by levitte** [comment]
> This fixes the issue in PR #14326, which added the first algorithm (KDF) that fetches another algorithm (digest) - which fell over since the internal libctx in the legacy provider was empty.

Providers are expected to be fairly self contained...  this *could* be fixed by loading the default provider into the legacy provider's libctx.  After all, the legacy provider in dynamic module form is linked with libcrypto.

**Comment by slontis** [comment]
We can do that, but the issue at the moment is that the libctx that it grabs from within the KDF algorithm (inside the legacy provider) to do a fetch is not the internal libctx of the legacy provider.. It is the one from the core. Obviously that doesn't work real well..

**Comment by levitte** [comment]
> We can do that, but the issue at the moment is that the libctx that it grabs from within the KDF algorithm (inside the legacy provider) to do a fetch is not the internal libctx of the legacy provider.. It is the one from the core. Obviously that doesn't work real well..

Ah, because NULL libctx used in `PKCS5_PBE_keyivgen()`, right?  There needs to be a variant of that function that takes libctx and propq...

**Comment by paulidale** [comment]
>  this _could_ be fixed by loading the default provider into the legacy provider's libctx. After all, the legacy provider in dynamic module form is linked with libcrypto

It would be more a case of loading all loaded providers into the legacy provider's internal libctx.  Plus the default query.  Possibly every time this is called.

**Comment by t8m** [comment]
There has to be different solution for the fetching in PBKDF1 implementation in legacy provider. The issue opened for that is #14925
As this is incorrect approach will you please close this, Shane?

**Pull request closed without merging**
