### PR TITLE
Fix VMS installation

### PR DESCRIPTION
**Pull request by levitte**
Fix VMS installation

VMS installation scripts were forgotten in the 3.0 release, most of
them have remained as they were for 1.1.1, when the new versioning
scheme should have been reflected in these as well.

Furthermore, the IVP is amended to check the presence of the standard
OpenSSL providers.

### CODE REVIEW

**Comment by levitte** [comment]
Currently a draft, until I've verified that it works as expected

**Comment by levitte** [comment]
I've tested this today, it seems to work like it's supposed to, so not a draft any more.  I'll run a few more tests on Sunday

**Comment by levitte** [comment]
Ping!  This really should end up in the upcoming release update

**Review by mattcaswell — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by mattcaswell** [comment]
Agree urgent

**Comment by mattcaswell** [comment]
Pushed to openssl-3.0 and master. There was a trivial conflict in the CHANGES.md file when cherry-picking to master, which I resolve during the merge.

**Pull request closed without merging**
