### PR TITLE
Fix malloc failure handling of `X509_ALGOR_set0()`

### PR DESCRIPTION
**Pull request by DDvO**
Also update and slightly extend the respective documentation and simplify some code.
~and add  internal `ossl_x509_algor_from_nid()` for simplifying code.~

This is all minor stuff, so I'd say can wait until after 3.0 release.

### CODE REVIEW

**Comment by DDvO** [comment]
Due to (rather innocent) API change in `include/openssl/x509.h.in`:
```
-void X509_ALGOR_set_md(X509_ALGOR *alg, const EVP_MD *md);
+int X509_ALGOR_set_md(X509_ALGOR *alg, const EVP_MD *md);
```
this must to wait until 4.0, right?

**Comment by FdaSilvaYY** [comment]
> Due to a (rather innocent) API change in `include/openssl/x509.h.in`:
> 
> ```
> -void X509_ALGOR_set_md(X509_ALGOR *alg, const EVP_MD *md);
> +int X509_ALGOR_set_md(X509_ALGOR *alg, const EVP_MD *md);
> ```
> 
> this has to wait until 4.0, right?

Suggestion : add a private `x509_algor_set_md()` method 
or create a new `X509_ALGOR_set1_md()` ?
so you can keep API compatibility .

**Comment by DDvO** [comment]
Thanks @FdaSilvaYY for your suggestion.
Yet this would add clutter to the API and 
lessen the improvement intended for the original function.

I've just extracted from this PR those changes that are directly related to the changed the result type and put them in #17495.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
This is still master-only as there is plenty of refactoring going in there.

**Comment by DDvO** [comment]
Merged - thanks @t8m

**Pull request closed without merging**
