### PR TITLE
Delete .github/dependabot.yml

### PR DESCRIPTION
**Pull request by fochoao-alt**
##### Checklist

- [ ] documentation is added or updated
- [-] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
What is your intent with this PR. Why should we accept it?

**Comment by fochoao-alt** [comment]
> What is your intent with this PR. Why should we accept it?

That was not me. I will look up.

**Comment by fochoao-alt** [comment]
https://github.com/openssl/openssl/commit/ecc332f82a7ad38a4ad85c71c2f73276d87f69d8

**Comment by fochoao-alt** [comment]
> What is your intent with this PR. Why should we accept it?

Closing the issue as of now. Thanks for telling me.

**Pull request closed without merging**
