### PR TITLE
Fix for #11523

### LINKED ISSUE #11523: openssl speed sm2 not working correctly
I found the following errors after building the latest version(eacd30a703b52f5b3e8e70b58f99bd1128458c7c) of openssl(Ubuntu 18.04.4).

```
$ apps/openssl speed  sm2
SM2 init failure.
00:07:77:C0:5B:7F:00:00:error:digital envelope routines:EVP_PKEY_CTX_ctrl:no operation set:crypto/evp/pmeth_lib.c:935:
version: 3.0.0-dev
built on: built on: Sun Apr 12 04:04:50 2020 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_PIC -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0xfffa32035f8bffff:0xd01e4fbb
                              sign    verify    sign/s verify/s
 256 bits SM2 (CurveSM2)      infs      infs      0.0      0.0

$ apps/openssl speed -multi 2 sm2
Forked child 0
Forked child 1
SM2 init failure.
00:A7:BF:C4:E9:7F:00:00:error:digital envelope routines:EVP_PKEY_CTX_ctrl:no operation set:crypto/evp/pmeth_lib.c:935:
SM2 init failure.
Got: +F6:0:256:CurveSM2:0.000000:0.000000 from 0
00:A7:BF:C4:E9:7F:00:00:error:digital envelope routines:EVP_PKEY_CTX_ctrl:no operation set:crypto/evp/pmeth_lib.c:935:
Got: +F6:0:256:CurveSM2:0.000000:0.000000 from 1
version: 3.0.0-dev
built on: built on: Sun Apr 12 04:04:50 2020 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_BUILDING_OPENSSL -DOPENSSL_PIC -DNDEBUG
CPUINFO: OPENSSL_ia32cap=0xfffa32035f8bffff:0xd01e4fbb
                              sign    verify    sign/s verify/s
 256 bits SM2 (CurveSM2)      infs      infs      0.0      0.0
```

### PR DESCRIPTION
**Pull request by qingfeng14**
Fixes #11523 

`openssl speed sm2` works.

### CODE REVIEW

**Comment by InfoHunter** [comment]
Is #11523 related to some recent changes in the EC/SM2 part?

**Comment by levitte** [comment]
While `sm2_curves` only contains one curve with a NID that happens to match `EVP_PKEY_SM2`, this works...  However, this really isn't quite right.  Furthermore, setting the SM2 curve on an EC key should still work, and autodetect as an SM2 key by default, so there's something going on deeper down.

**Comment by InfoHunter** [comment]
I will look into this later, maybe on the weekend

**Comment by levitte** [comment]
As demonstrated in #11523, the issue has fixed itself, probably through the work in #11328 and related PRs that were merged in the last few days.  This PR is no necessary any more as far as I can tell, so I'm closing it.

@qingfeng14, if you encounter new issues of this sort, please raise a new issue.  Thank you for yourr time.

**Comment by t8m** [comment]
What about the second commit? That seems to be still relevant. Please open a new PR with it.

**Comment by levitte** [comment]
> What about the second commit? That seems to be still relevant. Please open a new PR with it.

Oh!  Totally missed that.  Yes, new PR is a good idea

**Comment by qingfeng14** [comment]
A new PR has been opened to merge the second commit, thanks for your working.

**Pull request closed without merging**
