### PR TITLE
OPENSSL_strcasecmp [3.0]

### PR DESCRIPTION
**Pull request by beldmit**
This is a backport of #18069 for 3.0

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
Does anybody know why do I have to explicitly add `OPENSSL_crypto_init` to fix some tests?

**Comment by t8m** [comment]
> Does anybody know why do I have to explicitly add `OPENSSL_crypto_init` to fix some tests?

It is not called implicitly unless you do some operations that call it.

**Comment by beldmit** [comment]
@t8m, is it a difference to master? I didn't come across any problem with it there and didn't find any changes in `testutil` related to this.

**Comment by t8m** [comment]
I am not sure what causes this difference with master. We probably call more things in testutil or call OPENSSL_init_crypto() from more places in master.

**Comment by t8m** [comment]
I do not think adding the OPENSSL_init_crypto() to test initializations is the right thing. You need to ensure the OPENSSL_strcasecmp is initialized implicitly. Otherwise you basically break the existing API contract for 3.0.

**Comment by beldmit** [comment]
I also don't like this idea much... An initialization on-demand under lock in `ossl_c_locale`?

**Comment by t8m** [comment]
You could do RUN_ONCE in the ossl_c_locale().

The question is what would be the performance impact.

**Comment by beldmit** [comment]
In master OPENSSL_init_crypto is called from 
```
#0  OPENSSL_init_crypto (opts=262144, settings=0x0) at crypto/init.c:476
#1  0x00007ffff7d6b049 in ossl_rand_ctx_new (libctx=0x7ffff7fbbb20 <default_context_int>) at crypto/rand/rand_lib.c:450
#2  0x00007ffff7c7178b in context_init (ctx=0x7ffff7fbbb20 <default_context_int>) at crypto/context.c:105
#3  0x00007ffff7c71e35 in default_context_do_init () at crypto/context.c:339
#4  0x00007ffff7c71e01 in default_context_do_init_ossl_ () at crypto/context.c:336
#5  0x00007ffff7894d48 in __pthread_once_slow () from /lib64/libc.so.6
#6  0x00007ffff7c8937a in CRYPTO_THREAD_run_once (once=0x7ffff7fbbc50 <default_context_init>, init=0x7ffff7c71df8 <default_context_do_init_ossl_>) at crypto/threads_pthread.c:144
#7  0x00007ffff7c71e89 in get_thread_default_context () at crypto/context.c:350
#8  0x00007ffff7c71ebc in get_default_context () at crypto/context.c:358
#9  0x00007ffff7c72173 in ossl_lib_ctx_get_concrete (ctx=0x0) at crypto/context.c:465
#10 0x00007ffff7c723ec in ossl_lib_ctx_get_ex_data_global (ctx=0x0) at crypto/context.c:575
#11 0x00007ffff7c74f44 in ossl_crypto_new_ex_data_ex (ctx=0x0, class_index=12, obj=0x41a2a0, ad=0x41a310) at crypto/ex_data.c:219
#12 0x00007ffff7c751e6 in CRYPTO_new_ex_data (class_index=12, obj=0x41a2a0, ad=0x41a310) at crypto/ex_data.c:260
#13 0x00007ffff7b164cb in BIO_new_ex (libctx=0x0, method=0x7ffff7f9ab60 <methods_filep>) at crypto/bio/bio_lib.c:94
#14 0x00007ffff7b16637 in BIO_new (method=0x7ffff7f9ab60 <methods_filep>) at crypto/bio/bio_lib.c:122
#15 0x00007ffff7b21b43 in BIO_new_fp (stream=0x7ffff79fd5a0 <_IO_2_1_stdout_>, close_flag=16) at crypto/bio/bss_file.c:95
#16 0x0000000000408b28 in test_open_streams () at test/testutil/basic_output.c:27
#17 0x000000000040292a in main (argc=1, argv=0x7fffffffddc8) at test/testutil/main.c:19
```

**Comment by beldmit** [comment]
CI is green. @t8m, @paulidale - please review.

**Comment by beldmit** [comment]
Ping for the review

**Review by t8m — APPROVED** [review]

**Comment by beldmit** [comment]
@t-j-h sure
https://github.com/openssl/technical-policies/issues/44

**Comment by t-j-h** [comment]
We need to cross-reference things like this and make sure a hold is placed so someone doesn't accidentally think this is good to go into the code until a vote is complete. You should have placed the hold when you called the vote IMHO.

**Comment by beldmit** [comment]
Sorry, my fault.

**Comment by beldmit** [comment]
@t-j-h just in case - how do I add non-public exportable function?

**Comment by beldmit** [comment]
@levitte - is everything OK on VMS?

**Comment by beldmit** [comment]
@t-j-h, @levitte - what alternative approach will be OK for you if we don't want to extend the public API?

**Comment by beldmit** [comment]
Did it? We have 5 +1 and 1 +0

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
With the vote to accept this passed, I've removed the OTC decision required and completed the second review.

**Comment by beldmit** [comment]
Many thanks!

**Comment by t8m** [comment]
> Did it? We have 5 +1 and 1 +0

https://www.openssl.org/policies/omc-bylaws.html#otc-voting

0s (or -0 +0s) do not count . There are 5 +1 votes and single -1 vote, there is only a single vote remaining uncast. Even if the remaining vote was -1 it would still be 5 pro and only 2 against which means the vote has passed.

**Comment by beldmit** [comment]
Merged. Many thanks for the approval!

**Pull request closed without merging**
