### PR TITLE
RT4669: dgst can only sign/verify one file

### PR DESCRIPTION
**Pull request by richsalz**
Check arg count and print an error message.

This is the 1.0.2 version of #1530

### CODE REVIEW

**Comment by levitte** [comment]
+1

**Comment by levitte** [comment]
I did +1 this, but I take it back temporarly on the grounds that this change looks very different from the master one...  I'll get back when I've had a chance to look around..

**Comment by levitte** [comment]
Ok, I've looked at it and at #1530, and it seems to me that the latter should be possible to apply fairly easily on 1.0.2 as well.  I find the #1530 change much easier to read and understand than this one.

So, -1 on the current solution here, please make it more like #1530.

**Comment by richsalz** [comment]
okay, updated.

**Comment by levitte** [comment]
And why not place the change in about the same spot as in #1530?  Line 245?

**Comment by richsalz** [comment]
Because I could not follow the twisty flags and such, and thought that putting it right before the argc loop was the most sensible.

**Comment by levitte** [comment]
Ok, would you please align #1530 and this PR then?  I don't really care if you put this change just after the argv parsing look or just before the file fetching loop (which is what you call "the argc loop"), just that they are the same.  That will make future maintainance easier, if such is needed.

**Comment by richsalz** [comment]
No.  I think each diff makes sense.  You disagree, fine, let someone else do it ☺

**Comment by levitte** [comment]
Ok.  #1606

**Pull request closed without merging**
