### PR TITLE
util/process_docs.pl: handle multiple source directories correctly

### LINKED ISSUE #7939: Installation of HTML manpages fails
During `make install`, the command

```
/usr/bin/perl ./util/process_docs.pl --destdir=/opt/openssl-dev/share/doc/openssl/html --type=html
```

invokes `pod2html` several times, which fails frequently with the error message

```
/usr/bin/pod2html: error changing to directory ARRAY(0x56363a9b1e20): No such file or directory
```

A bisection indicates that the error was introduced by commit

b608fabfcc util/process_docs.pl: handle multiple source directories for .pod files

**Build transcript**

```
make clean
perl Configure debug-linux-x86_64 shared enable-crypto-mdebug --strict-warnings --prefix=/opt/openssl-dev
make -j 16
make install

...

*** Installing HTML manpages
/usr/bin/perl ./util/process_docs.pl \
	--destdir=/opt/openssl-dev/share/doc/openssl/html --type=html
/usr/bin/pod2html: error changing to directory ARRAY(0x56363a9b1e20): No such file or directory
/opt/openssl-dev/share/doc/openssl/html/man1/asn1parse.html
/opt/openssl-dev/share/doc/openssl/html/man1/openssl-asn1parse.html -> /opt/openssl-dev/share/doc/openssl/html/man1/asn1parse.html
/usr/bin/pod2html: error changing to directory ARRAY(0x56363a9b1e20): No such file or directory
/opt/openssl-dev/share/doc/openssl/html/man1/CA.pl.html
/usr/bin/pod2html: error changing to directory ARRAY(0x56363a9b1e20): No such file or directory
/opt/openssl-dev/share/doc/openssl/html/man1/ca.html
/opt/openssl-dev/share/doc/openssl/html/man1/openssl-ca.html -> /opt/openssl-dev/share/doc/openssl/html/man1/ca.html
/usr/bin/pod2html: error changing to directory ARRAY(0x56363a9b1e20): No such file or directory
/opt/openssl-dev/share/doc/openssl/html/man1/ciphers.html
/opt/openssl-dev/share/doc/openssl/html/man1/openssl-ciphers.html -> /opt/openssl-dev/share/doc/openssl/html/man1/ciphers.html
/usr/bin/pod2html: error changing to directory ARRAY(0x56363a9b1e20): No such file or directory

...

```

### PR DESCRIPTION
**Pull request by levitte**
The way this script handled multiple source directories wasn't quite
right, it ended up giving pod2html 'ARRAY(0xXXXXXXXXX)' as a source
directory.

This corrects the mistake.

Fixes #7742
Fixes #7939

### CODE REVIEW

**Comment by levitte** [comment]
Ping.  Installation doesn't work right without this

**Comment by mspncp** [comment]
I just verified that this fixes #7939. Could you please add a `Fixes #7939` annotation, too?

**Comment by levitte** [comment]
That was my intention.  Done

**Comment by mspncp** [comment]
Unfortunately I can't approve, because I have no idea what the effect of the two non-whitespace changes ist. Perl is still a mystery for me. But if nobody else finds the time to review it, ping me again and I'll give you a looks-good-and-works-for-me-approval.

**Review by t-j-h — APPROVED** [review]

**Pull request closed without merging**
