### PR TITLE
fix #1730

### LINKED ISSUE #1730: The example in SSL_CTX_set_verify doesn't work with 1.1.0
```
    if (!preverify_ok && (err == X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT))   
    {   
        X509_NAME_oneline(X509_get_issuer_name(ctx->current_cert), buf, 256);   
        printf("issuer= %s\n", buf);   
    }   
```

the error:
invalid use of incomplete type 'X509_STORE_CTX {aka struct x509_store_ctx_st}'

### PR DESCRIPTION
**Pull request by choury**

### CODE REVIEW

**Comment by levitte** [comment]
Note: I added labels for the branches I think this should go to.

**Comment by richsalz** [comment]
This is a trivial change; @choury do you agree?  If not we need a CLA from youj.

**Comment by choury** [comment]
Yes, I agree it. @richsalz

**Comment by richsalz** [comment]
thanks.  @levitte you want to merge?

**Comment by levitte** [comment]
Merged

**Pull request closed without merging**
