### PR TITLE
ssl: add kctl engine for linux

### PR DESCRIPTION
**Pull request by TousakaRin**
Under Linux, cryptodev and afalg can be used to implement the offload of cryptographic calculations, unfortunately, neither of them supports asymmetric encryption.  In order to support asymmetric encryption algorithms, I implemented this kctl engine using keyutils.

I used the speed command to benchmark rsa2048. My platform is a 8-cpu virtual machine with a pci pass-through intel QAT card(C62xx), here are the benchmark result:

openssl speed -engine kctl -elapsed -multi 85 rsa2048 :
image

openssl speed  -elapsed -multi 85 rsa2048 :
image

We are going to use the kctl engine and nginx together, so there is currently no adaptation to openssl3.0. If this pr has the possibility of being merged, I am very happy to add tests/documentation, and make the code compatible to openssl3.0.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

Signed-off-by: Lei He <helei.sig11@bytedance.com>

### CODE REVIEW

**Comment by t8m** [comment]
Unfortunately this is a feature PR against the 1.1.1 branch. This is not going to be accepted as we do not allow new features in stable branches. However even if this was rebased and submitted against the master branch it would not be merged as this adds a new functionality in terms of a new ENGINE. However ENGINEs are deprecated as of 3.0 release and we are not going to include any new engine.

I would like to suggest to you to create a separate project where your engine would be maintained and released.

**Comment by TousakaRin** [comment]
Thank you very much for your suggestion. As far as I know, nginx does not support OpenSSL 3.0 now. Thanks for the dynamic loading capability provided by OpenSSL, so that I can try to maintain this engine in an separate repo.

In addition, maybe I can try to abstract it into a provider in OpenSSL 3.0? I think it should be a good idea to offload cryptographic operations through the standard system calls provided by the Linux kernel.

> Unfortunately this is a feature PR against the 1.1.1 branch. This is not going to be accepted as we do not allow new features in stable branches. However even if this was rebased and submitted against the master branch it would not be merged as this adds a new functionality in terms of a new ENGINE. However ENGINEs are deprecated as of 3.0 release and we are not going to include any new engine.
> 
> I would like to suggest to you to create a separate project where your engine would be maintained and released.

**Comment by t8m** [comment]
Yes, creating a provider would certainly make sense for OpenSSL 3.0. However I cannot promise we would include such provider in the OpenSSL source tree either. The intention is to allow third party providers and the provider API is supposed to be stable so the third party providers should not require arbitrary OpenSSL release to work with.

**Comment by tmshort** [comment]
Intel already provides a QAT engine, and my understanding is that Intel wants to create a QAT provider.

**Comment by beldmit** [comment]
Why do we get autoclose notifications every day?

**Comment by t8m** [comment]
> Why do we get autoclose notifications every day?

Because the bot does not have sufficient permissions to really close the issue.

**Pull request closed without merging**
