### PR TITLE
Add -Wno-parentheses-equality to dev-warnings.

### PR DESCRIPTION
**Pull request by richsalz**
Also fix a block comment formatting glitch.

### CODE REVIEW

**Comment by kroeckx** [comment]
Just fix the warnings instead?

**Comment by richsalz** [comment]
It is complaining about code like this:
```
if (SSL_IS_FIRST_HANDSHAKE(s))
```
There are four instances, and likely to be more in the future.

Fixing the warnings means one of inverting the test, which is awkward; removing the parens around the macro definition, which seems a bit dangerous; or writing the macro to use the ! operator which is against our style.

Maybe I missed something?

**Comment by tmshort** [comment]
I found it odd that it would whine about that... I had the same solution in my clang build wrapper

**Comment by t-j-h** [comment]
+1

**Pull request closed without merging**
