### PR TITLE
Run 'make' with 5 threads instead of an infinite amount

### PR DESCRIPTION
**Pull request by guidovranken**
##### Description of change
In the instructions on how to build the fuzzers, limit the amount of threads spawned by ```make``` to 5.

### CODE REVIEW

**Comment by richsalz** [comment]
er, why?  Maybe the should say
```
-j [#ofthreads]
```
?

**Comment by levitte** [comment]
I agree with @richsalz, leave it to the user to decide the number

**Comment by kroeckx** [comment]
You could also use -j$(nproc), but I guess that's shell specific, or just not mention the -j like I did for the afl case.

**Comment by levitte** [comment]
Why reinvent when the make manual already has something most people have seen?

> -j [jobs]

**Comment by guidovranken** [comment]
The shell commands in the README give the impression that they can be readily copy-pasted or executed verbatim, with the exception of ```make -j````, which essentially crashes your system because it spawns a new thread for every compilation. The first time I compiled the fuzzers this is exactly what happened to me and it's very annoying.

Every solution you have suggested seems more reasonable to me than ```-j```. IMHO it doesn't matter that ```-j$(nproc)``` is shell specific because the file is describing how to create the fuzzers on an Ubuntu system (```sudo apt-get install```); the instructions aren't super "portable" to begin with.

**Comment by guidovranken** [comment]
The rationale behind ```-j5``` is that 5 is the preferred value for systems with 4 cores. Obviously it will also work for people with more cores, it just won't utilize all CPU capacity. Larger values than 5 will possibly hog 4 core systems due to excessive resource consumption.

Anyway, please tell me which changes to apply, or discard the PR..

**Comment by levitte** [comment]
I'd suggest taking any of the suggestions shown here, they will all make it clear enough that it's not just a copy-and-paste line, and let the users decide the appropriate number for themselves.

**Comment by dot-asm** [comment]
And add [skip ci] to commit message.

**Comment by richsalz** [comment]
@guidovranken can you do "-j [jobs]" ?

**Comment by levitte** [comment]
If `-j` is such a source of confusion, then I agree with @JohnAZoidberg

**Comment by mspncp** [comment]
Fixed by https://github.com/openssl/openssl/commit/a81151bd56d55d52c40865f2f135355a2164062e#diff-fe2d9a2689017e4355ae93b37079e792R34-R36 as part of #11386.

**Pull request closed without merging**
