### PR TITLE
When producing man-pages, ensure NAME section is one line only

### PR DESCRIPTION
**Pull request by levitte**
There are *roff parsers that are strict about the NAME section being
one line only.  The man(7) on Debian GNU/Linux suggests that this is
appropriate, so we compensate our multi-line NAME sections by fixing
the *roff output.

Noted by Eric S. Raymond

Related to #6264

### CODE REVIEW

**Review by richsalz — COMMENTED** [review]
This seems like a pod2man bug/misfeature, not ours.

**Comment by mspncp** [comment]
> This seems like a pod2man bug/misfeature, not ours.

Well, but isn't it worth doing it anyway in order to leave @eric-s-raymond's 2.6% grubby urchins corner?

**Comment by richsalz** [comment]
https://www.in-ulm.de/~mascheck/bourne/v7/sh.1

**Comment by levitte** [comment]
Well, one might argue that it's a Pod::Man misfeature, but then one could also argue that it's up to .pod authors to get it right.  After all, `man perlpodstyle` does hint at this when explaining the NAME section.

Thing is, we insist on on making it multiline, some programs (not necessarily just doclifter) may parse it strictly.  I see this PR as smoothing it out to fit all tastes.

And look, I did what was needed.  Took me about 10 minutes.  Are we seriously gonna waste a multiple times that time arguing if this is our fault or someone else's?

**Review by richsalz — APPROVED** [review]
Your last comment was compelling.

**Comment by levitte** [comment]
Thank you :-)

Merged.

master / 1.1.1:
8d483b2de78619e8592f2558301f3295daf59690 When producing man-pages, ensure NAME section is one line only

1.1.0:
0bde96f13837825fa899573728899744a956beff When producing man-pages, ensure NAME section is one line only

**Comment by eric-s-raymond** [comment]
Thanks.  I have made my namme section parser a bit more tolerant, but as levitte notes this cleanup was a good idea anyway.

Cleaning up the corpus has been difficult.  I've been working on it for 13 years and am only now approaching completion.  Every little bit helps.

**Pull request closed without merging**
