### PR TITLE
Add BSD-armv4 target based on linux-armv4

### PR DESCRIPTION
**Pull request by pkubaj**
If possible, please also merge to 1.1.1 and 3.0.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by pkubaj** [comment]
Again? I have already signed one for https://github.com/openssl/openssl/pull/17090

**Comment by t8m** [comment]
Perhaps a different e-mail address was used for this commit?

**Comment by mattcaswell** [comment]
> Perhaps a different e-mail address was used for this commit?

That is the case. #17090 uses your FreeBSD email address. This PR is using an email address that wasn't mentioned in your original ICLA. Is your contribution here on behalf of your employer? If so you will additionally need to be listed in the Intel CCLA. If your contribution is personal can you update the author to match that given in your ICLA?

**Comment by pkubaj** [comment]
No, that was a mistake. It wasn't related to my work. Updated.

**Review by mattcaswell — APPROVED** [review]
I assume you are ok with being named as the nominated community member for this platform on the platform policy (as you already are for other platforms)? If so please can you raise a PR to add yourself?

As to backport to 3.0/1.1.1 they are both LTS releases, and our policy says "The addition of new platforms to LTS branches is acceptable so long as the required changes consist solely of additions to configuration.". So, the changes in Configurations/10-main.conf would be acceptable - but the changes in util/perl/OpenSSL/config.pm are technically code not configuration. A version of this PR that doesn't make those changes would be ok for 3.0/1.1.1

**Review by tmshort — COMMENTED** [review]
Shouldn't there be an `inherit_from` statement somewhere? e.g.
```
    inherit_from => [ "BSD-generic64"],

**Comment by pkubaj** [comment]
Indeed there should, thanks for catching that.

**Review by mattcaswell — APPROVED** [review]
Reconfirm

**Review by hussain2022a — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Review by tmshort — APPROVED** [review]

**Comment by mattcaswell** [comment]
I've applied a temporary hold to this until openssl/web#357 is merged. Once that's in, this one can go in too.

**Comment by tmshort** [comment]
Is this one ready, as openssl/web#357 has been merged?

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master branch. Thank you for your contribution.

**Pull request closed without merging**
