### PR TITLE
Rearrange some CI jobs

### PR DESCRIPTION
**Pull request by t8m**
Those less useful should be in daily or on-push runs.

Those more likely triggering CI failure that do not take too much time should be in main on pull request CI.

### CODE REVIEW

**Comment by t8m** [comment]
This can go into the 3.2 branch as well.

**Comment by nhorman** [comment]
To be clear, on-push runs trigger only on-push to certain branches (master, openssl-3.x, etc), correct?

**Review by paulidale — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
> To be clear, on-push runs trigger only on-push to certain branches (master, openssl-3.x, etc), correct?

They run on push to any branch that contains the workflow yml file. I.e., if you have enabled GH actions on your forked openssl repo, they will run when you push to any branch there. But you can of course disable these workflows individually in your repo GH actions configuration.

**Comment by t8m** [comment]
Fixup to fix the no-stdio runchecker job was pushed. Still OK?

**Review by nhorman — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master and 3.2 branches. Thank you for the reviews.

**Pull request closed without merging**
