### PR TITLE
OpenSSL -> OpenTLS

### PR DESCRIPTION
**Pull request by the-xentropy**
Rename project to openTLS.

### CODE REVIEW

**Comment by slontis** [comment]
This was discussed some time ago
https://github.com/openssl/openssl/issues/6384.

**Comment by mattcaswell** [comment]
This has been discussed from time to time by the OMC. Whilst there are differing views on this within the OMC I don't think there is sufficient support there to make such a change. I doubt this will happen anytime soon.

**Comment by paulidale** [comment]
My suspicion is that if this change is ever made, it will need to be done in a more gradual manner.

**Comment by mattcaswell** [comment]
There are no plans to make this change, so closing this PR.

**Pull request closed without merging**
