### PR TITLE
Fix link to LibFuzzer

### PR DESCRIPTION
**Pull request by ligurio**
##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated
- [x] CLA is signed
##### Description of change

Fixed broken URL to LibFuzzer.

### CODE REVIEW

**Comment by richsalz** [comment]
I can't find your CLA.  But this seems like a trivial change, do you agree?

**Comment by ligurio** [comment]
I'm agree.

**Comment by richsalz** [comment]
CLA: trivial as agreed.

**Comment by richsalz** [comment]
commit fe2582a for master, and 0d72c6c for 1.1.0  thanks!

**Pull request closed without merging**
