### PR TITLE
Check error return from cms_sd_asn1_ctrl() correctly.

### LINKED ISSUE #21986: Return value confusion in cms_sd_asn1_ctrl()
In `cms_sd.c`,  the function `cms_sd_asn1_sign()` is error checked as if it had a Boolean return value. However, since #13088, it can also return -1.

### PR DESCRIPTION
**Pull request by paulidale**
Fixes #21986

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by botovq** [comment]
While this is a possible approach, I think it would make more sense to fix `cms_generic_sign()` to behave the same way as `rsa_cms_sign()` (i.e.,  return 0/1), or to do `return cms_generic_sign(si, cmd) > 0;` twice.

Otherwise the fixup of the return value after the `->pkey_ctrl()` call is a bit strange.

https://github.com/openssl/openssl/blob/25b7025a669737bde50bbf186ce02989797c33f0/crypto/cms/cms_sd.c#L259-L282

**Comment by paulidale** [comment]
Yeah, that's a nicer approach I think.

**Comment by paulidale** [comment]
`ossl_cms_rsa_sign()` can also return -1 on error.

**Comment by botovq** [comment]
I'm pretty sure it doesn't. I first thought so, too, but then noticed that here is a `> 0` hiding at the end:

https://github.com/openssl/openssl/blob/025535ecd11bdebd8eb28ed4f0f6b509b1b54577/crypto/cms/cms_rsa.c#L246

`X509_ALGOR_set0` returns 0/1, so I think we're good.

**Review by slontis — CHANGES_REQUESTED** [review]
Please add a testcase..

The following commandline returns -1  from cms_generic_sign..
It then segfaults inside the shake ctrl.
openssl cms -sign -in test/smcont.txt -signer test/smime-certs/smdsa1.pem -md SHAKE256

**Review by slontis — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by botovq** [comment]
It's your codebase and the diff fixes the bug. However, if I was to write the fix, I would change the -1 returns in `cms_generic_sign()`  to 0 returns. Then making things complicated with the three added `> 0` is unnecessary. We've seen that doing this is confusing in this very thread. I also do not know why you'd want two internal APIs that are supposed to do the same thing that have different API contracts. So I think aligning the APIs is cleaner, leads to simpler code and makes it easier to add new things. Consistency matters.

**Comment by paulidale** [comment]
Ping for reviews @openssl/committers

**Comment by slontis** [comment]
I dont mind either way it is done. Currently I cant see a path where ossl_cms_rsa_sign() could return -1. But the > check doesnt hurt anything..

**Comment by paulidale** [comment]
Thrice merged with conflicts resolved.

**Comment by bernd-edlinger** [comment]
the merge commit 41136a9 to 3.0 branch removed the semicolon:
`plan tests => 17`
therefore now the test_cms test case is faliing due to syntax.

**Comment by paulidale** [comment]
Oops.  Thanks for pointhing this out.  Fixed by #22045 already.

**Comment by bernd-edlinger** [comment]
Okay, but it still fails for `no-des` doesn't it?

**Comment by bernd-edlinger** [comment]
i meant  no-dsa` ....

**Pull request closed without merging**
