### PR TITLE
test/build.info: typo, $ missing

### PR DESCRIPTION
**Pull request by levitte**
##### Checklist

- [x] CLA is signed

### CODE REVIEW

**Comment by levitte** [comment]
The amazing thing is that Text::Template on Linux doesn't seem to react at all.  It took VMS to scream loudly:

```
$ @PROGRAM:[LEVITTE-BUILDS.DOWNLOADS.OPENSSL-1_1_0-STABLE-SNAP-20161103]CONFIG NO-SHARED --PREFIX=PROGRAM:[LEVITTE-BUILDS._INSTALL110.ALPHA.CONFIG0] --OPENSSLDIR=PROGRAM:[LEVITTE-BUILDS._COMMON.ALPHA.CONFIG0]
Something wrong with this line:
  IF[Program fragment delivered error ``Can't locate object method "disabled" via package "shared" (perhaps you forgot to load "shared"?) at program:[levitte-builds.downloads.openssl-1_1_0-stable-snap-20161103.test]build.info line 278.'']
at program:[levitte-builds.downloads.openssl-1_1_0-stable-snap-20161103.test]/build.info at program:[levitte-builds.downloads.openssl-1_1_0-stable-snap-20161103]configure line 1586.
```

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
I forgot to lable...  this is for 1.1.0 as well, do you approve?

**Comment by mattcaswell** [comment]
Reconfirmed.

**Comment by levitte** [comment]
All merged.  Thanks

**Pull request closed without merging**
