### PR TITLE
Use BIO not FILE for test file

### PR DESCRIPTION
**Pull request by richsalz**
This is another step toward making bntest and evp_test share a common file parser.

### CODE REVIEW

**Comment by levitte** [comment]
*g* the title doesn't quite correspond to what this PR does...  ah well, still a good move.

**Comment by richsalz** [comment]
updated commit pushed that fixes the test_recipe to run all files.
(and if no file given, runs the builtin tests)

**Comment by richsalz** [comment]
please reconfirm, @levitte

**Comment by richsalz** [comment]
thanks!

**Pull request closed without merging**
