### PR TITLE
Clear buffer in PEM_write_bio

### PR DESCRIPTION
**Pull request by bernd-edlinger**

### CODE REVIEW

**Comment by levitte** [comment]
Should this go to more than just master?  Like 1.1.0 and 1.0.2?

**Comment by bernd-edlinger** [comment]
> Should this go to more than just master? Like 1.1.0 and 1.0.2?

No, this bug was introduced with 6714cb14 thus only master.

**Comment by richsalz** [comment]
Assume you'll merge, @bernd-edlinger

**Comment by bernd-edlinger** [comment]
Merged.  Thanks!

**Pull request closed without merging**
