### PR TITLE
APPS {`storeutl`,`gendsa`}: give error on extra arguments, improve doc

### LINKED ISSUE #20144: `storeutl` app ignores `-certs`, `-keys`, and `-crls` option
When preparing #20143, I noticed that `openssl storeutl` ignores any provided `-certs`, `-keys`, or `-crls` option.

For instance, this still shows any included keys and certs:
```
apps/openssl storeutl -passin pass:123456 test_123456.pem -crls

0: Pkey
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
1: Certificate
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
2: Certificate
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
3: Certificate
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
Total found: 4
```

### PR DESCRIPTION
**Pull request by DDvO**
Point out that CLI options must be given before the final file/URI arg.
So far, they were silently ignored, as well as any extra args.
Also fix in the `storeutl` doc that there is only one URI arg. 

On this occasion, also improve APPS `load_key_certs_crls()` diagnostics on not finding expected types of contents.

Fixes #20144.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
This won't cherry pick to older branches.

**Comment by t8m** [comment]
I'd suggest doing just a docfix PR for 3.1/3.0

**Comment by DDvO** [comment]
> This won't cherry pick to older branches.

Ah, right.

> I'd suggest doing just a docfix PR for 3.1/3.0

Done in #20179.

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master branch. Thank you for your contribution.

**Pull request closed without merging**
