### PR TITLE
Rename sk lh

### PR DESCRIPTION
**Pull request by richsalz**
testing CI build.

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
IMHO , this renaming is not coherent with the current  naming schema.
The OPENSSL_ prefix addition is too much.
LH_-only prefix for LH-struct dedicated methods is enough, lie for DSA_ , RSA_ ENGINE_ ...

**Comment by richsalz** [comment]
Maybe not.  OpenSSL already "takes over" too many API prefixes.  And nobody is really using the "raw" stack and LH stuff directly.  So I disagree.  But then, nobody else on the team has approved this yet, so it might not happen.

**Comment by t-j-h** [comment]
They should indeed be under the OPENSSL_ namespace - we are trying to clean up the usage in that area. @richsalz was also going to add in (off-by-default I think) backward compatibility macros and then seek team member view points on this one.

**Comment by richsalz** [comment]
Yes, there is one name now, lh_strhash() that has a compatibility flag.  Not sure what others, if any, are needed, but am happy to add them.

**Comment by richsalz** [comment]
Merged/squashed.  Only the one name needs preserving, so this is ready for review.

**Comment by richsalz** [comment]
@t-j-h ?

**Comment by mattcaswell** [comment]
Ping @t-j-h

**Comment by t-j-h** [comment]
I was expecting to see a full set of stack and lh compatibility macros in place - these are used in a fair amount of application code - you've set the target to just what you see the OpenSSL library itself using.

**Comment by richsalz** [comment]
Okay, I’ll look at adding more in a day or two

**Comment by richsalz** [comment]
Added a commit that maps all the old names.

**Comment by richsalz** [comment]
internal reviewed and done.

**Pull request closed without merging**
