### PR TITLE
test/x509: Test for issuer being overwritten when printing.

### PR DESCRIPTION
**Pull request by t8m**
The regression from commit 05458fdb73dcca30edace5ad727a15d6d919e215
was fixed, but there is no test for that regression. This adds it.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by DDvO — CHANGES_REQUESTED** [review]
Hmm, this compares the whole cert output, which is extremely brittle - it will break even on layout change!
I suggest specifically using `-issuer` and `sub file_contains` of `conversion.pl` to check the (only) line in the resulting output file .

**Comment by DDvO** [comment]
>  there are already two other existing tests that do the same. I do not think it is an issue as it can be easily fixed when the formatting changes. (And we should not do formatting changes randomly anyway.)

Ah right, I recall having to adapt those two reference cert output files after making changes to the cert output functions.

> Another option would be to just change the existing certificate that is compared verbatim to be one with different issuer and subject but still using the Cyrillic character

This option would at least would not increase the number of reference files to adapt.

Even better in my view would be to replace the current full cert output contents of `cyrillic.{msb,utf8}` by the output of `openssl x509 ... -subject -issuer`, producing and comparing just these two lines of output (rather then the whole certs).

**Comment by t8m** [comment]
> > Another option would be to just change the existing certificate that is compared verbatim to be one with different issuer and subject but still using the Cyrillic character
> 
> This option would at least would not increase the number of reference files to adapt.

I'll go for that as I do not think completely dropping full reference text output would be beneficial.

**Comment by DDvO** [comment]
Actually I doubt whether it's worth adding a (regression) test for this special issue.
If we take this path serious, a number of apps that would require hundreds of test cases each 
for a test coverage at this level of granularity.

**Comment by t8m** [comment]
I am not saying the test is comprehensive or anything like that but why not have it when it is basically for free.

**Review by DDvO — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
The idea of this test originally was to check that non-ASCII subject and issuer are printed correctly when the command line options are set correctly. What are you trying to do replacing the Cyrillic ones with something plain ASCII?

**Comment by beldmit** [comment]
The idea of this test originally was to check that non-ASCII subject and issuer are printed correctly when the command line options are set correctly. What are you trying to do replacing the Cyrillic ones with something plain ASCII?

**Comment by DDvO** [comment]
I also would have preferred if the issuer stayed in Cyrillic.

**Comment by DDvO** [comment]
Or even better, a different char set, say, Chinese!

**Comment by t8m** [comment]
OK, used Japanese now.

**Comment by beldmit** [comment]
I'm OK with your changes as we have the Unicode stuff where it was before. Maybe it's worth renaming the `cyrillic.pem` to `unicode.pem` just for clarity.

**Review by beldmit — APPROVED** [review]
LGTM

**Review by DDvO — APPROVED** [review]
Re-approving also from my perspective.
Nice trick to cover the additional test aspects with just some adapted test data.

**Comment by t8m** [comment]
> I'm OK with your changes as we have the Unicode stuff where it was before. Maybe it's worth renaming the `cyrillic.pem` to `unicode.pem` just for clarity.

I'll keep it as is as there is at least still some cyrillic there to avoid unnecessary churn.

**Comment by t8m** [comment]
Merged to master. Thank you for the reviews.

**Pull request closed without merging**
