### PR TITLE
Add support for BSD-riscv64 target

### PR DESCRIPTION
**Pull request by pkubaj**

### CODE REVIEW

**Review by kaduk — APPROVED** [review]

**Review by paulidale — APPROVED** [review]
Just noting that this would qualify for back port to 3.0 since it is only configuration additions.

**Comment by pkubaj** [comment]
I'm definitely for that (and same for 1.1.1).

**Comment by paulidale** [comment]
@openssl/otc any thoughts on back-porting this to 1.1.1 and 3.0?

**Comment by t8m** [comment]
I am OK with backport to 1.1.1 and 3.0

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.  This doesn't cherrypick cleaning to 3.0 (& I didn't try 1.1.1).  A new pull request for these is probably the way forward.

**Comment by mattcaswell** [comment]
A reminder of our platform policy:

"Support for a new platform should only be added if it is being adopted as a primary, secondary or community platform."

We shouldn't really have merged this without an equivalent update to the community platform list.

@pkubaj - can you raise a PR to add your self as community maintainer for this new platform?

**Comment by pkubaj** [comment]
Done.

**Pull request closed without merging**
