### PR TITLE
[1.1.1] Fix regression in no-deprecated build

### LINKED ISSUE #13896: Build failed on latest commit of branch `OpenSSL_1_1_1-stable`
```
$ ./config --prefix="/build_root/.openssl" --release no-deprecated no-shared no-dtls1-method no-tls1_1-method no-sm2 no-sm3 no-sm4 no-rc2 no-rc4 threads CFLAGS="$CFLAGS -fPIC" CXXFLAGS="$CXXFLAGS -fPIC" LDFLAGS='-fuse-ld=lld'
$ make -j "$(nproc)" CFLAGS="$CFLAGS -fPIE -Wl,-pie" CXXFLAGS="$CXXFLAGS -fPIE -Wl,-pie"

${LDCMD:-gcc} -pthread -m64 -Wa,--noexecstack -O2 -pipe -D_FORTIFY_SOURCE=2 -fexceptions -fstack-clash-protection -fstack-protector-strong -g -grecord-gcc-switches -Wl,-z,noexecstack,-z,relro,-z,now,-z,defs -Wl,--icf=all -fPIE -Wl,-pie -L. -fuse-ld=lld \ -o test/verify_extra_test test/verify_extra_test.o \ test/libtestutil.a -lcrypto -ldl -pthread
ld.lld: error: undefined symbol: X509_STORE_CTX_trusted_stack >>> referenced by verify_extra_test.c:203 (test/verify_extra_test.c:203) >>> test/verify_extra_test.o:(test_self_signed) >>> referenced by verify_extra_test.c:203 (test/verify_extra_test.c:203) >>> test/verify_extra_test.o:(test_self_signed)
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:9139: test/verify_extra_test] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build_root/openssl-1.1.1j-dev'
make: *** [Makefile:174: all] Error 2
```

You can replicate this built process with Dockerfile:
https://github.com/IceCodeNew/builder_image_x86_64-linux/blob/3679c1b123d815839b3a9eea0666fd8298bb4795/ubuntu_builder.Dockerfile#L84-L101

### PR DESCRIPTION
**Pull request by t8m**
Also add the no-deprecated to the minimal CI build to test it.

Fixes #13896
##### Checklist
- [x] tests are added or updated

### CODE REVIEW

**Review by DDvO — CHANGES_REQUESTED** [review]
For the master the `no-deprecated` was recently moved to a separate job in commit e3577adddf6bc4f0d9d202621a2c576d982d6f0a.
I think this would be good to do here, too, because many deprecation issues would not show in a minimal build.

**Comment by t8m** [comment]
> For the master the `no-deprecated` was recently moved to a separate job in commit [e3577ad](https://github.com/openssl/openssl/commit/e3577adddf6bc4f0d9d202621a2c576d982d6f0a).
> I think this would be good to do here, too, because many deprecation issues would not show in a minimal build.

I do not think it is that big issue in 1.1.1 as in 3.0 but it makes sense anyway. Done.

**Review by DDvO — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
Merged to 1.1.1 branch.

**Pull request closed without merging**
