### PR TITLE
Fix test/recipes/90-test_fipsload.t to use bldtop_file for the FIPS module

### PR DESCRIPTION
**Pull request by levitte**
It used bldtop_dir(), which is incorrect for files.

### CODE REVIEW

**Comment by levitte** [comment]
Related to #16523, which currently fails because of the error fixed here

**Comment by levitte** [comment]
Interestingly enough, this gives a weirdly looking command on VMS (`"[--.providers.fips.^.EXE]"` should really be `"[--.providers]fips.EXE"`), but the command doesn't fail...  I don't know why for the moment.

```
pipe MCR dsa10:[ia64.perl-5_20.][000000]perl.exe;1 [--.util]wrap.pl MCR [--.apps]openssl.exe fipsinstall -module "[--.providers]fips.EXE" -provider_name fips -section_name fips_sect -out [--.test]fipsmodule.cnf => 0
```

**Comment by levitte** [comment]
(yes, I know that some of you will want to tell me that there's more weirdness 😉)

**Comment by t8m** [comment]
The CI failure is relevant.

**Comment by levitte** [comment]
> The CI failure is relevant.

A, forgot to update the `use` line.  Hopefully, it will work better now

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
OK for master and 3.0.

**Review by paulidale — APPROVED** [review]
Good for 3.0 too.

**Comment by levitte** [comment]
Merged

master:
c6ee5d5b42e27b407dfc1fc8845e08c5a75e2221 Fix test/recipes/90-test_fipsload.t to use bldtop_file for the FIPS module

3.0:
03943ae71dfd1ac37cb9675197ea59cc2718f099 Fix test/recipes/90-test_fipsload.t to use bldtop_file for the FIPS module

**Pull request closed without merging**
