### PR TITLE
fix typo in README

### PR DESCRIPTION
**Pull request by shogo82148**
fix small typo in README

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
Thank you @shogo82148 for spotting and fixing this typo. Your fix qualifies as (legally) trivial and does not require a CLA, but you need to indicate your consent by adding a `CLA: trivial` line to the _body_ (separted by an empty line) of the commit message, like this.

```
Fix typo in README

CLA: trivial
```

Could you please amend your commit accordingly and force-push it? Thank you in advance!

**Review by kroeckx — APPROVED** [review]

**Review by mspncp — APPROVED** [review]
Forgot to approve 😉

**Comment by shogo82148** [comment]
I fixed the comment message and pushed it.

**Comment by mspncp** [comment]
Thank you! Your pull request has received the necessary number of approvals and will be merged after the 24 hour grace period has passed.

**Review by paulidale — APPROVED** [review]

**Comment by mspncp** [comment]
Merged to master in3ee3c4d2abeeeadc8d33498d1466a3a8381d286b, thank you!

**Pull request closed without merging**
