### PR TITLE
add support for SHA-3 based PRF to PBES2

### PR DESCRIPTION
**Pull request by tomato42**
As there are no limitations for HMACs used in PBKDF2 inside PBES2,
as more specifically the SHA-3 hashes are drop-in replacements for
SHA-2 hashes, we can easily add support for SHA-3 here.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
I'd like to see a revamp of the PBE infrastructure.  What's there is pretty horrible and a bit of a kludge.

Are there any test vectors for this?

**Comment by paulidale** [comment]
As safe as this is, I don't think it will make 3.0.

**Comment by tomato42** [comment]
> I'd like to see a revamp of the PBE infrastructure. What's there is pretty horrible and a bit of a kludge.
> 
> Are there any test vectors for this?

I'm not aware of any

**Comment by slontis** [comment]
> Are there any test vectors for this?

I cant find any test vectors either..
We could at least put in some ref data in test/recipes/30-test_evp_data/ evpkdf_pbkdf2.txt and evppbe_pbkdf2.txt

**Comment by slontis** [comment]
> I'd like to see a revamp of the PBE infrastructure. What's there is pretty horrible and a bit of a kludge.

Unravelling this is probably not as easy as it sounds. I think @jon-oracle may have tried to do this initially?

**Comment by jon-oracle** [comment]
> > I'd like to see a revamp of the PBE infrastructure. What's there is pretty horrible and a bit of a kludge.
> 
> Unravelling this is probably not as easy as it sounds. I think @jon-oracle may have tried to do this initially?

Yes I did try but abandoned the attempt as getting it to work alongside the existing API was painful.

It would be useful to deprecate the existing EVP_PBE_alg_add() API (which I'm not sure is even used/tested) so the new infrastructure can start from a clean slate. A big problem is the various *_keyivgen functions taking ASN1_TYPEs for the parameters. Rewriting them to use OSSL_PARAM and/or having some kind of utility to convert ASN.1 AlgorithmParameters to OSSL_PARAM and back might help.

**Comment by beldmit** [comment]
I'd like to have this change in 3.0.0 and some sort of PBE revamp after 3.0.0. @tomato42, did you test the interoperability for these algorithms between OpenSSL and any other implementations?

**Comment by t-j-h** [comment]
It is a new feature so not 3.0.0 relevant.

**Comment by beldmit** [comment]
Sad but true

**Comment by paulidale** [comment]
It is also possible to add these from an application via `EVP_PBE_alg_add()`.

**Comment by tomato42** [comment]
> I'd like to have this change in 3.0.0 and some sort of PBE revamp after 3.0.0. @tomato42, did you test the interoperability for these algorithms between OpenSSL and any other implementations?

No, GnuTLS doesn't support even SHA-512 as an PBKDF2 HMAC, I don't think NSS has SHA-3 implementation at all, and it can't import PKCS#12 files with SHA-3 MAC or KDF

**Review by beldmit — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by beldmit** [comment]
Merged, thanks!

**Pull request closed without merging**
