### PR TITLE
Add function and reason checking to evp_test

### PR DESCRIPTION
**Pull request by snhenson**
##### Checklist

- [x] tests are added or updated
- [x] CLA is signed

##### Description of change

Add options to check the function and reason code matches expected values.

### CODE REVIEW

**Comment by levitte** [comment]
I like at first sight. Have a look at the appveyor failures, though...

**Comment by snhenson** [comment]
There's something strange going on. The relevant errror message is:

> line 3699: unexpected keyword PeerKey
> evp_test.exe ..\..\test\evptests.txt => 1

But evptests.txt doesn't have "PeerKey" on line 3699.

**Comment by levitte** [comment]
Ah, that. 
The line count isn't quite right, and it's possible that this is a bio issue (see the pull request that avoids eating up '\n') 
Also, I have observed some issues with BIO_seek / BIO_tell on some platforms. Not sure that plays in here and currently not in a position to investigate further...

**Comment by snhenson** [comment]
Just tried a WIN64 no-asm build (which seems to be what appveyor is having problems with). Can't reproduce it here.

**Comment by snhenson** [comment]
The "error" originated with the previous evp_test enhancement but oddly is only triggered by the master branch and not 1.1.0.

**Comment by dot-asm** [comment]
> The "error" originated with the previous evp_test enhancement

And it seems to be gone now with another evptests.txt modification, unrelated to evp_test modification...

**Comment by dot-asm** [comment]
> And it seems to be gone now with another evptests.txt modification

I mean that same error was flagged in current master and now it's gone. In current master. And it probably should be noted that there is PeerKey at line 3699 in current master. It's as if appveyor used evptests.txt from master. And for some reason got angry with itself. As for line numbers being off, it wasn't a problem on Windows so far. And at least if you corrupt evptests.txt yourself, for example by replacing PeerKey with PeerKeyy, it tells the story right...

**Comment by snhenson** [comment]
Rebased against master, let's see what that does.

**Comment by snhenson** [comment]
It is OK now. Any further comments?

**Pull request closed without merging**
