### PR TITLE
EVP_Digest*: enable SHA3 pre-hashing for (EC)DSA

### PR DESCRIPTION
**Pull request by p-steuer**
Addresses  https://github.com/openssl/openssl/issues/8957 and ~~possibly the ecdsa part of~~ https://github.com/openssl/openssl/issues/7323

Couldnt find any test vectors for (ec)dsa signatures on sha3 hashes.

### CODE REVIEW

**Comment by mattcaswell** [comment]
I suggest this should be backported to 1.1.1

**Comment by mattcaswell** [comment]
FYI (for future reference), if you put "Fixes #8957" on a line on its own in the commit message then the issue will get automatically closed when you push it to the repo.

**Comment by p-steuer** [comment]
> if you put "Fixes #8957" on a line on its own in the commit message then the issue will get automatically closed

The issue was due to a failure in an external test suite. Ill add the fixes line to the commit message when its verified.

 > I suggest this should be backported to 1.1.1
Ill do it.

Let me merge this one (as an exercise).

**Comment by mattcaswell** [comment]
> Let me merge this one (as an exercise).

I felt certain you would want to :-)

**Comment by p-steuer** [comment]
Checked NIST and wycheproof testvectors and google but couldnt find any.

**Comment by p-steuer** [comment]
merged

master: e8d0678da4942dd027981175b16b6b3162731205 3f950d87650776d0e2874588081fecb7bdd4fbd0
1.1.1: bf3797fe3b71d58791b20cf6bc2304284e7aaa85 3e0b1a603b4dfb0ab5981634419a8db70ffc48b0

**Pull request closed without merging**
