### PR TITLE
Fix S390/PPC build for sha providers

### PR DESCRIPTION
**Pull request by slontis**
Added missing assembler for fips provider + fixed small compile issues.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
I forgot about this when I submitted #9168 earlier today...  which partially did the same thing as you did.

**Comment by levitte** [comment]
Did this get merged?

**Comment by slontis** [comment]
No @p-steuer did a smaller commit that just had the sha3 changes.. That is all that is needed right?

**Comment by slontis** [comment]
Which has been commited.

**Comment by levitte** [comment]
Yeah OK.
I saw the comment in #9236 after writing the comment above...

**Comment by slontis** [comment]
Yeah I should have added a comment here.. thanks.

**Comment by p-steuer** [comment]
I somehow missed this PR. You can always ping me for s390 stuff.

**Comment by levitte** [comment]
Heh, seems we are three-four looking at s390x stuff... Maybe we should talk with each other :wink:

**Comment by slontis** [comment]
@p-steuer will do.

**Pull request closed without merging**
