### PR TITLE
Add a workflow to test building from a read-only source tree [3.1 & 3.0]

### PR DESCRIPTION
**Pull request by levitte**
... and deal with the consequences.

*Note: this is a backport of #22908 for openssl-3.1 and openssl-3.0*

### CODE REVIEW

**Comment by levitte** [comment]
I have verified that this cherry-picks cleanly to openssl-3.0

**Comment by slontis** [comment]
Wheres the 'deal with the consequences part' :)

**Comment by levitte** [comment]
> Wheres the 'deal with the consequences part' :)

That's the second commit, which modifies `Configure`.
I was actually surprised that there was so little to do...

**Comment by slontis** [comment]
Is the test failure not related?

**Comment by levitte** [comment]
PING!  #22908 has been approved...  any chance this can as well?

**Comment by mattcaswell** [comment]
What about the comment from @slontis above?

**Comment by levitte** [comment]
Whoopsie, of course there should be no `enable-quic` in this PR...

**Review by t8m — APPROVED** [review]

**Comment by slontis** [comment]
Tests still failing.

**Review by nhorman — APPROVED** [review]

**Comment by slontis** [comment]
Why is this being approved with test failures?

**Comment by levitte** [comment]
I think that failure is irrelevant for this PR.  I can rebase it, though, and see if fares better

**Comment by levitte** [comment]
I have seen that failure in other PRs, FYI...

**Comment by levitte** [comment]
> I have seen that failure in other PRs, FYI... (#22948, #22929)

And that exact same error is in the current openssl-3.1 branch:

https://github.com/openssl/openssl/actions/runs/7117073364/job/19376972990

**Pull request closed without merging**
