### PR TITLE
Clean up SSL_OP_* a bit

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
Moved this from a different PR.

**Comment by richsalz** [comment]
I think that this should go in all branches for ease of cherry-pick, but if whoever does the other review disagrees, then let them merge as they desired.

**Comment by tmshort** [comment]
It's not s straight back-port, but it shouldn't be too hard.

**Comment by levitte** [comment]
it should be rather straight-forward to 1.1.0, no?  I'd say that a 1.0.2 backport probably requires a separate PR...

**Comment by tmshort** [comment]
Yes, 1.1.0 is straight-forward, 1.0.2 not so much.

**Comment by levitte** [comment]
(frankly, I'm not even sure 1.0.2 would be worth the while..)

**Comment by tmshort** [comment]
Fine by me :)

**Comment by richsalz** [comment]
merged.

**Pull request closed without merging**
