### PR TITLE
Fixed minor typo in the req.pod docs

### LINKED ISSUE #7927: Minor typo in docs
# Current:

> Additionally emailAddress is include

# Expected:

> Additionally emailAddress is included

# Location: 
https://www.openssl.org/docs/manmaster/man1/req.html

### PR DESCRIPTION
**Pull request by behrangsa**
Fixes #7927.

CLA: Trivial.

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by InfoHunter** [comment]
I think this should be cherry-picked back to 1.1.1

**Comment by behrangsa** [comment]
IIRC, I edited the file directly from my browser on an iPad and couldn’t find a way to add a second commit to the first PR.

**Comment by InfoHunter** [comment]
Ahh, that's no problem.

Ping @openssl/committers for a second review!

**Comment by InfoHunter** [comment]
Merged to master (005247af76aa8d623fadbf3a82aa7b8ef449989f) and cherry-picked to 1.1.1 (30e35ee1d54a7ad55ba724da795c513f07653252)

**Pull request closed without merging**
