### PR TITLE
Blake2b: Use OSSL_DIGEST_PARAM_SIZE as settable instead of XOFLEN

### LINKED ISSUE #22488: Change Blake2b to use OSSL_PARAM_DIGEST_SIZE as settable instead of OSSL_PARAM_DIGEST_XOFLEN
This needs to go in before 3.2.0 beta1.

### PR DESCRIPTION
**Pull request by t8m**
BLAKE2 is not really an extensible output function unlike SHAKE as the digest size must be set during the context initialization. Thus it makes no sense to use OSSL_DIGEST_PARAM_XOFLEN.

It is still necessary to use the EVP_DigestFinalXOF() function to get the output for non-default sizes as EVP_DigestFinal() cannot handle non-default sizes.

Fixes #22488

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t-j-h** [comment]
Having to use EVP_DigestFinalXOF goes against using XOFLEN being "wrong" in the sense that we have an XOF named API that has to used. I know it isn't XOF as discussed - but we should have a non-XOF named API for the final that works like this then.

**Comment by t8m** [comment]
> Having to use EVP_DigestFinalXOF goes against using XOFLEN being "wrong" in the sense that we have an XOF named API that has to used. I know it isn't XOF as discussed - but we should have a non-XOF named API for the final that works like this then.

Do we want such last minute API addition? I do not like this.

**Comment by t8m** [comment]
IMO we could just rename/alias the EVP_DigestFinalXOF as the name is misleading anyway.

**Comment by t-j-h** [comment]
The OTC discussion was about this not being an XOF as the reason to change the parameter name - but if we do that and then the user still has to call a function with XOF in its name that seems inconsistent to me. Renaming the function as that part of it isn't XOF would make sense - but you will need other views expressed on this. This itself is a last minute change and I don't think it does far enough to achieve the objective (of not packaging something up that isn't XOF in an XOF facade)

**Comment by t8m** [comment]
I still believe this is better than what we currently have in the code. We can add the alias to EVP_DigestSignXOF later.

Alternatively we live with what we have as is.

**Comment by t8m** [comment]
I've added the alias as that is relatively trivial.

**Comment by t8m** [comment]
Now we can start the bikeshedding about the alias name.

**Comment by t8m** [comment]
> I don't understand why `EVP_DigestFinal_ex()` can't be modified to allow output lengths that vary from the default. Sure, there's the `EVP_MD_get_size()` call, but it can be modified to retrieve the actual length, and retain the `EVP_MD_get_size()` as a fallback, can it not?

This would be rather non-trivial change - it would require us to make the OSSL_DIGEST_PARAM_SIZE as a ctx gettable and adding a helper function to get it. I can try to do it as an alternative.

**Comment by t-j-h** [comment]
I don't like any of the options facing us - 1) do nothing, 2) accept this PR, 3) change to not using the final-xof

3 seems like the right longer term solution but is too late for 3.2 beta and hence 3.2 itself and 2 is reasonable and 1 wasn't the OTC meeting view. 

I lean towards this PR as is.

**Comment by mattcaswell** [comment]
The alternative in #22491 is preferable to this PR IMO.

**Comment by levitte** [comment]
> The alternative in #22491 is preferable to this PR IMO.

Agreed

**Comment by t8m** [comment]
I am closing this in favor of https://github.com/openssl/openssl/pull/22491

**Pull request closed without merging**
