### PR TITLE
Apply fixup to feature/dtls-1.3 branch in order to rebase

### PR DESCRIPTION
**Pull request by mattcaswell**
There is a conflict when trying to rebase the feature/dtls-1.3 branch on top of the latest master. By applying this fixup commit to the feature branch first the conflict mostly goes away.

There is one other conflict that occurs at this point but it seems to be mostly a git ghost. I can't figure out why the remaining conflict occurs since as far as I can tell there should be no conflict. Merely accepting the incoming change resolves the issue.

Once this fixup is approved I plan to apply it to the feature/dtls-1.3 branch and then immediately rebase it against master (resolving the trivial conflict noted above).

### CODE REVIEW

**Comment by mattcaswell** [comment]
FYI @fwh-dc

**Review by nhorman — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
I'd propose we do not need to have 24h approval window for these feature branch rebase fixups.

**Comment by mattcaswell** [comment]
> I'd propose we do not need to have 24h approval window for these feature branch rebase fixups as they basically contain the changes that are already present on the master branch.

That's probably something to bring up at OTC. But for now there is no great hurry.

**Comment by mattcaswell** [comment]
Ok - pushed and the feature/dtlsv1.3 branch has been rebased.

@fwh-dc you will need to rebase any PRs to pick up the latest updates

**Pull request closed without merging**
