### PR TITLE
Remove engine lock hooks, restore mem alloc hooks

### PR DESCRIPTION
**Pull request by levitte**
Considering everything that's happening with threads and that engines get to handle that entirely on their own (they really don't even have to use the OpenSSL threads API, they can as well use pthreads or so directly for all that anyone cares), there's no point sending them locking hooks that may not even exist in not too long.

However, we do need to pass them our memory allocation hooks.

### CODE REVIEW

**Comment by t-j-h** [comment]
So we have a portability layer in place in the API for handling threading yet you've now cut engines out of being able to use it so they have to do something differently - that seems a little strange to me.

**Comment by mattcaswell** [comment]
@t-j-h we are moving to the new threading API...the old threading API will be going very very soon

**Comment by mattcaswell** [comment]
Looks good to me:

+1

**Comment by richsalz** [comment]
who's gonna remove the dynlock stuff?

**Comment by levitte** [comment]
@t-j-h, this has been in line for a long time.  if you knew how many have asked me if they *must* use OpenSSL threads routines or if they can roll their own...  guess what I answered, each time?

**Comment by levitte** [comment]
@richsalz, the new threads API is the new dynlocks ;-)

Seriously, it does what dynlocks were meant for, and much better

**Comment by levitte** [comment]
Merged.

**Comment by richsalz** [comment]
Right, to the dynlock APi’s should go away.

**Comment by levitte** [comment]
Agreed

**Comment by levitte** [comment]
... especially since engines was their only raison d'être

**Pull request closed without merging**
