### PR TITLE
TESTS: add test of decoding of invalid zero length ASN.1 INTEGER zero

### PR DESCRIPTION
**Pull request by levitte**
Confirms #7134

### CODE REVIEW

**Comment by levitte** [comment]
In the spirit of test driven development, this is *expected* to fail in CIs.
Fix in #7144

**Review by paulidale — APPROVED** [review]
On the assumption that this needs approval separately.

So long as (the fixed) #7144 goes in at the same time.

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Merged as part of #7145

**Comment by levitte** [comment]
Merged by #7144

**Pull request closed without merging**
