### PR TITLE
Allow small RSA exponents in the default provider

### LINKED ISSUE #16255: OpenSSL3 regression: RSA_generate_key_ex fails with e = 17
https://www.openssl.org/docs/manmaster/man3/RSA_generate_key_ex.html says

> The exponent is an odd number, typically 3, 17 or 65537.

But if you give it 17 it will fail because it will end up with `rsa_multiprime_keygen` calling `ossl_rsa_check_public_exponent` and BN_num_bits(17) is only 5 and will fail the 

`return (BN_is_odd(e) && bitlen > 16 && bitlen < 257);`

check

### PR DESCRIPTION
**Pull request by slontis**
Fixes #16255

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
There is a vote in progress related to this issue..

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
The hold is on the pending OTC vote.

**Comment by mattcaswell** [comment]
The vote has just closed:

accepted:  yes  (for: 4, against: 2, abstained: 3, not voted: 1)

**Comment by t8m** [comment]
Merged to master. Thank you.

**Pull request closed without merging**
