### PR TITLE
DOC: install documentation without execution permissions.

### LINKED ISSUE #12350: 3.0.0-alpha4: man pages and html docs installed with perms 755
In file Configurations/unix-Makefile.tmpl there are the following lines, that result in installing man pages and html docs with permissions 755 instead of (suggested) 644:

                chmod 755 $(DESTDIR)$(MANDIR)/man1/$${fn}$(MANSUFFIX); \
...
                chmod 755 $(DESTDIR)$(MANDIR)/man3/$${fn}$(MANSUFFIX); \
...
                chmod 755 $(DESTDIR)$(MANDIR)/man5/$${fn}$(MANSUFFIX); \
...
                chmod 755 $(DESTDIR)$(MANDIR)/man7/$${fn}$(MANSUFFIX); \
...
                chmod 755 $(DESTDIR)$(HTMLDIR)/man1/$$fn; \
...
                chmod 755 $(DESTDIR)$(HTMLDIR)/man3/$$fn; \
...
                chmod 755 $(DESTDIR)$(HTMLDIR)/man5/$$fn; \
...
                chmod 755 $(DESTDIR)$(HTMLDIR)/man7/$$fn; \

I suggest changing the 755 to 644.

Thanks and regards,

Rainer

### PR DESCRIPTION
**Pull request by levitte**
Fixes #12350

### CODE REVIEW

**Comment by rainerjung** [comment]
Note that there are another 4 lines that need fixing for the HTML docs (look for "chmod" and "HTMLDIR"). Thanks.

**Comment by levitte** [comment]
Oops, you're right, @rainerjung, I forgot those

**Comment by slontis** [comment]
111 also?

**Comment by levitte** [comment]
These are new mechanisms for master, so not for 1.1.1

**Comment by levitte** [comment]
Merged

d685fc7a59699aeb17120aebd17a9175ce5930cd DOC: install documentation without execution permissions.

**Pull request closed without merging**
