### PR TITLE
Silence gcc false positive warning on alpn_protos_len in test/handshake_helper.c in 1.1.1

### PR DESCRIPTION
**Pull request by DDvO**
As agreed with @bernd-edlinger in https://github.com/openssl/openssl/pull/12036#discussion_r435153089

### CODE REVIEW

**Comment by mattcaswell** [comment]
Is this only an issue in 1.1.1, i.e.  not master?

**Comment by bernd-edlinger** [comment]
It is only a question of time, when this happens in master.
There was no apparent reason why travis changed the gcc version in 1.1.1 only.
See #12033 
BTW: @DDvO please add "Fixes #12033" to the commit message, if not already done.

**Comment by mattcaswell** [comment]
>It is only a question of time, when this happens in master.

In which case we should make the same change in master. Adding branch labels for both.

**Comment by DDvO** [comment]
> BTW: @DDvO please add "Fixes #12033" to the commit message, if not already done.

Done now.

**Comment by kaduk** [comment]
Do we prefer playing whack-a-mole and sprinkling unneeded initializers periodically, or disabling `-Werror=maybe-uninitialized`?

**Comment by bernd-edlinger** [comment]
travis is still not happy:
```
*test/tls13encryptiontest.c: In function 'test_tls13_encryption':
test/testutil.h:357:34: error: 'refdatalen' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  357 | # define TEST_mem_eq(a, m, b, n) test_mem_eq(__FILE__, __LINE__, #a, #b, a, m, b, n)
      |                                  ^~~~~~~~~~~
test/tls13encryptiontest.c:291:12: note: 'refdatalen' was declared here
  291 |     size_t refdatalen;
      |            ^~~~~~~~~~
In file included from test/tls13encryptiontest.c:26:
test/testutil.h:357:34: error: 'refdatalen' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  357 | # define TEST_mem_eq(a, m, b, n) test_mem_eq(__FILE__, __LINE__, #a, #b, a, m, b, n)
      |                                  ^~~~~~~~~~~
test/tls13encryptiontest.c:291:12: note: 'refdatalen' was declared here
  291 |     size_t refdatalen;
```

**Comment by DDvO** [comment]
> travis is still not happy:

Thanks for pointing to that; fixed also in `test/tls13encryptiontest.c`.

**Comment by DDvO** [comment]
I kicked the CI twice yesterdays, but still the Travis run was not initiated.

**Comment by DDvO** [comment]
This time kicking had the desired effect on Travis.

**Comment by bernd-edlinger** [comment]
This time the build picked again a different gcc version.
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
This false positive warning only happens so far with s390
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
It is quite possible that only gcc-9.3 has this broken warning,
so this test is inconclusive, it could be that more changes are
needed we never saw this build pass with that gcc version.
Maybe we wait a bit what travis does next?

**Comment by DDvO** [comment]
> Maybe we wait a bit what travis does next?

After a couple of days have passed and no more GCC warning issues have popped up,
I've pushed this now - thanks!

**Pull request closed without merging**
