### PR TITLE
There is no -signreq option in CA.pl

### PR DESCRIPTION
**Pull request by mettacrawler**
CLA: trivial

##### Checklist

- [x] documentation is added or updated

### CODE REVIEW

**Comment by t8m** [comment]
Unfortunately for 1.1.1 there should be a separate PR because the -signreq is mentioned at one additional place there.

**Comment by t8m** [comment]
Merged to master, would you like to create a PR for the 1.1.1 branch?

**Comment by mettacrawler** [comment]
@t8m is it normal to close a branch with un-merged commits?

**Comment by t8m** [comment]
It is actually merged, the e1c6f76 is your commit, rebased and with the commit message adjusted so it contains the reviewed-by and link to the PR.

**Comment by mettacrawler** [comment]
@t8m PR for 1.1.1 https://github.com/openssl/openssl/pull/11897

**Comment by richsalz** [comment]
> is it normal to close a branch with un-merged commits?

yes, because the master source for openssl is not on github, but on an openssl server which the pushes to github as a read-only copy.

**Pull request closed without merging**
