### PR TITLE
Add ssl_ctx_test to test suite.

### PR DESCRIPTION
**Pull request by richsalz**
Did anyone try to build https://github.com/openssl/openssl/pull/6553? :)
And then run it? :(

This PR makes the test program compile.  But it fails.  What to do?
Ping the guilty parties: @paulidale, @levitte, @tiran.

### CODE REVIEW

**Comment by levitte** [comment]
Yup, I have run it, and think that's valuable to figure out what we do right or wrong. TDD (Test Driven Development) is a thing that we sometimes do too little of.

So basically, either the ssl code isn't quite right, or the test isn't. Fixing one or the other based on the results shown in this PR should spark another PR or two.

**Comment by richsalz** [comment]
TDD is for branches, not master, IMO. :)

**Comment by levitte** [comment]
Feature branches, yeah.  But that's what I'm saying, the presence of this failing test, *even though "just" in a PR*, may be reason for someone wanting to fix the problem.  Quite obviously, the fixing branch will have to be merged before this test is, to not disturb the nice green colour of master builds.

**Comment by richsalz** [comment]
The "quite obviously" part wasn't clear from your earlier comments.

But WTH, master's been broken for weeks anyway.

**Comment by kroeckx** [comment]
The error is most likely: https://github.com/openssl/openssl/pull/6553#pullrequestreview-132296477

**Comment by kroeckx** [comment]
That test made sense for #5127, which tried to change the behaviour, but as pointed out, is not what we wanted.

**Comment by levitte** [comment]
So that means we need to make some small adjustment to the test program. Would you be willing to, @kroeckx?

**Comment by kroeckx** [comment]
On Sun, Nov 03, 2019 at 02:55:47AM -0800, Richard Levitte wrote:
> So that means we need to make some small adjustment to the test program. Would you be willing to, @kroeckx? 

It's just changing a 0 into a 1 on that line.

**Comment by t8m** [comment]
Not just that. Also the expected max value needs to be changed.
The line should be:
`{TLS1_2_VERSION, TLS1_1_VERSION, 1, 1, TLS1_2_VERSION, TLS1_1_VERSION}`

**Comment by t8m** [comment]
@richsalz could you please fix the ssl_ctx_test.c accordingly?

**Comment by richsalz** [comment]
rebased and updated commit pushed.  locally-run test passes.

**Comment by richsalz** [comment]
not sure what you're asking; feel free to edit the commit message yourself.

**Comment by t8m** [comment]
Merged to master as 310553591c

**Pull request closed without merging**
