### PR TITLE
Remove getenv(OPENSSL_FIPS) in openssl command

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This is left over from the past.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
My concern about this code, is that it might be re-used for the 3.0 FIPS provider,
and then in consequence be set in environment variables, which will then
1.1.1 fail unexpectedly.

**Comment by paulidale** [comment]
I'm unsure about 1.1.1 for this.

**Comment by bernd-edlinger** [comment]
Why, this is no documented behavior, and it plays a prank on the user.

**Comment by levitte** [comment]
This environment variable was most relevant with the FIPS OpenSSL Module 2.0 (compatible with OpenSSL 1.0.2).  The reason we have the error is for users that have upgrade to the 1.1.x series must not be lead to believe that OPENSSL_FIPS still has the meaning they might think.

So I see nothing against removing this in 3.0, we have moved far enough from 1.0.2 to simply drop the check.  For 1.1.1, I'm just as dubious as @paulidale.

**Comment by bernd-edlinger** [comment]
Okay, then I'll add this to my 1.1.1 feature branch #11900

**Comment by bernd-edlinger** [comment]
Merged to master as 32df134

**Pull request closed without merging**
