### PR TITLE
Add support for new release commit review requirement bypass

### PR DESCRIPTION
**Pull request by hlandau**

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
I am labeling it as bug as this is a part of a fix for a bug in our release process.

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
I've learned a bash feature with this...

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you.

**Comment by levitte** [comment]
When your work with openssl/tools#115 is merged, this probably needs to be undone in favor of adding `--release` to all the `addrev` commands

**Pull request closed without merging**
