### PR TITLE
If BIO_snprintf failed, keep trying.

### LINKED ISSUE #2514: [rt.openssl.org #4649] [PATCH] BIO_debug_callback could write before the beginning of a buffer
Migrated from [rt.openssl.org#4649](https://rt.openssl.org/Ticket/Display.html?id=4649) (status was 'open')

Requestors:
* graeme.perrow@sap.com

Attachments:
* [BIO_debug_callback.patch](https://rt.openssl.org/Ticket/Attachment/71017/44700/BIO_debug_callback.patch)

From graeme.perrow@sap.com on 2016-08-16 18:23:05:
```
In the BIO_debug_callback function, we call BIO_snprintf which could return -1 in the case of an error. However, there is no check for this condition, and so the subsequent code would subtract one from buf and write data there, overwriting the byte immediately before the static buffer.

This patch fixes the problem by checking for a negative return code from the first BIO_sprintf.


```

From rsalz@openssl.org on 2016-08-16 18:54:39:
```
Probably better to do what we is done in master: "if (len<0)len=0;" and
proceed to try more output.
```

### PR DESCRIPTION
**Pull request by richsalz**
Fixes #2514

### CODE REVIEW

**Comment by dot-asm** [comment]
I would rather see it harmonized with master. I mean corresponding lines should look same in 1.1.x and 1.0.2. Or in other words copy from master or modify master...

**Comment by richsalz** [comment]
Good point!  Update commit pushed that looks exactly like master.

**Comment by levitte** [comment]
Errr...  I haven't looked at this before, and I have some doubts.  It only checks the first `BIO_snprintf` call, and somehow, the rest of them will be fine even though this first one failed?

Also, make sure that `buf` is properly initialised, or if *all* `BIO_snprintf()` calls fail, the `strlen(buf)` at the end may be troublesome...

**Comment by richsalz** [comment]
It was first done in commit a1673e1536729d49cb758b988ac7be368e9b1fdb.  Blame the reviewers :)  This PR just brings 1.0.2 into harmony with 1.1.0

**Comment by levitte** [comment]
*cough* I've obviously forgotten about that one.

However, the reasoning in that commit message clarifies things, so...

**Pull request closed without merging**
