### PR TITLE
Add many more OIDs

### PR DESCRIPTION
**Pull request by JonathanWilbur**
Signed-off-by: Jonathan M. Wilbur <jonathan.wilbur@wildboarsoftware.com>

### CODE REVIEW

**Comment by paulidale** [comment]
Why?

**Comment by JonathanWilbur** [comment]
> Why?

I added these OIDs from an extraction I produced from hundreds of ASN.1 modules. I recognize most of them do not really have significance for cryptography. I preferred to submit the complete list and get your feedback on what you'd like removed.

I would be happy to remove many / most of these if you do not want all of these, but I do think we should retain, at a minimum:

- The object identifiers pertaining to [Platform Certificates](https://trustedcomputinggroup.org/wp-content/uploads/IWG_Platform_Certificate_Profile_v1p1_r19_pub_fixed.pdf)
- The object identifiers pertaining to [CAdES](https://www.etsi.org/deliver/etsi_ts/101700_101799/101733/02.02.01_60/ts_101733v020201p.pdf)
- The object identifiers sourced from the ITU's [2019 edition](https://www.itu.int/rec/T-REC-X.520-201910-I/en) of the `SelectedAttributeTypes` module.

There are also object identifiers pertaining to algorithms in there, but maybe you do not want the object identifiers for algorithms not yet implemented in OpenSSL.

Bear in mind that there is an [outstanding PR](https://github.com/openssl/openssl/pull/15857) for implementing Attribute Certificates in OpenSSL, which would make a more comprehensive catalog of object identifiers more valuable.

**Comment by JonathanWilbur** [comment]
Regarding the CLA check, I emailed the legal team to add the email above to my CLA. I already agreed, just with a different email. I can resubmit with the email that I signed the CLA with if this turns out to be difficult.

**Comment by mattcaswell** [comment]
IMO, we should not seek to be a database of all known OIDs. This will just lead to a maintenance headache. Only OIDs with relevance to cryptography should be added.

**Comment by paulidale** [comment]
I think a better (future) approach would be having an ability to load OIDs from a file.  Either using a default file name or via configuration (or both).

Then we could look into removing the current OID database from the library.  Or at least most of it.

**Comment by beldmit** [comment]
This approach works only if we don't have to refer to a corresponding NID.

**Comment by JonathanWilbur** [comment]
> IMO, we should not seek to be a database of all known OIDs. This will just lead to a maintenance headache. Only OIDs with relevance to cryptography should be added.

I figured. I figured since I had them all, I'd make the pitch, since I don't think it's too much overhead to have them in there, but I'll remove the non-cryptography ones. Will that suffice? Major manufacturers want the Platform Certificate attributes, at least, because they expect to use them for hardware security. And CAdES has obvious pertinance to cryptography.

**Comment by mattcaswell** [comment]
> I'll remove the non-cryptography ones. Will that suffice?

From my point of view, yes. As long as there is a reasonable argument for why OpenSSL users would need those OIDs then I don't personally see a problem with adding them.

**Comment by paulidale** [comment]
> This approach works only if we don't have to refer to a corresponding NID.

We're moving towards using names not NIDs.

**Comment by levitte** [comment]
> I think a better (future) approach would be having an ability to load OIDs from a file. Either using a default file name or via configuration (or both).

Uhmmmm, we have that ability already.

https://github.com/openssl/openssl/blob/master/doc/man5/config.pod#asn1-object-identifier-configuration

**Pull request closed without merging**
