### PR TITLE
signature: Clamp PSS salt len to MD len (openssl-3.1)

### PR DESCRIPTION
**Pull request by neverpanic**
Cherry-pick of #19724 to openssl-3.1.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by neverpanic** [comment]
Test failures seem unrelated:

- https://github.com/openssl/openssl/actions/runs/3647741669/jobs/6160332931 is in code not changed by this PR
- https://github.com/openssl/openssl/actions/runs/3647741669/jobs/6160333910 is the same
- https://github.com/openssl/openssl/actions/runs/3647741671/jobs/6160336495 also fails in `90-test_sslapi.t` on the current state of the `openssl-3.1` branch.

**Review by t8m — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
> Is there something I should do to retrigger and/or fix those CI failures?

Nope, I'll just merge this.

**Comment by t8m** [comment]
Merged to 3.1 branch. Thank you for your contribution.

**Pull request closed without merging**
