### PR TITLE
Replace div-spoiler hack with simpler code

### PR DESCRIPTION
**Pull request by richsalz**
This comes from a comment in GH issue #1027. Andy wrote the code,
Rich made the PR.

Fixes #1027

### CODE REVIEW

**Comment by levitte** [comment]
Only for master, or does it apply to the release branches as well (how far back?)?

**Comment by richsalz** [comment]
It's a performance gain, so only master.  If you argue for 1.1.0 I'll be okay with that.

**Comment by levitte** [comment]
I'd argue for 1.1.0.  I see nothing wrong with performance enhancements in release branches as long as the ABI is maintained...  which seems to be the case here.

**Comment by richsalz** [comment]
okay, 1.1.0 as well.

**Comment by dot-asm** [comment]
> It's a performance gain

No, it's rather constant-time thing, i.e. security hardening of specific kind. Either way, as even commit message suggests, it's *replacement* for div_spoiler, so that some code, naturally one calculating div_spoiler, has to be even *removed*...

**Comment by richsalz** [comment]
div_spoiler is used in the calculation for rotate_offset which *is* used.  So I don't know what code can/should be removed.

**Comment by dot-asm** [comment]
> div_spoiler is used in the calculation for rotate_offset which is used.

No, that result is effectively discarded in `rotate_offset = 0`. Optimizing compiler would actually (or at least have all chances to) omit all the code referring div_spoiler as dead. But we don't want to take the chance and should explicitly do it, i.e. remove all calculations involving div_spoiler include declaration itself.

**Comment by richsalz** [comment]
SMH, I missed that zero assignment.  Updated commit pushed.

**Comment by dot-asm** [comment]
+1

**Comment by richsalz** [comment]
in 1.1.0 ```rotate_offset``` isn't zero'd so the cherry-pick doesn't apply cleanly.  not going to risk breaking.  someone ( @dot-asm? ) want to propose/provide a 1.1.0 variation of this?
will leave open with this comment hanging for now.
8f77fab on master.

**Comment by dot-asm** [comment]
#2277, it's exactly same modulo size_t vs. unsigned [int].

**Pull request closed without merging**
