### PR TITLE
configdata.pm.in: Make a HERE document stricter.

### LINKED ISSUE #12078: build fails if build path contains @
In 3.0.0-alpha3 and up to today's master HEAD (c4683009ad6e8d64e80112fd689921f6c169bd20), the configure phase of the build fails if the build path (i.e., the current directory) contains a `@` in the name. For example:

```
$ cd ~/tmp/foo@bar/openssl
$ ./config
Operating system: x86_64-apple-darwinDarwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64
WARNING! If you wish to build 32-bit libraries, then you have to
         invoke 'KERNEL_BITS=32 ./config '.
Configuring OpenSSL version 3.0.0-alpha4-dev for target darwin64-x86_64-cc
Using os-specific seed configuration
Creating configdata.pm
Running configdata.pm
Possible unintended interpolation of @bar in string at configdata.pm line 28952.
Possible unintended interpolation of @bar in string at configdata.pm line 28953.
Global symbol "@bar" requires explicit package name (did you forget to declare "my @bar"?) at configdata.pm line 28952.
Global symbol "@bar" requires explicit package name (did you forget to declare "my @bar"?) at configdata.pm line 28953.
Execution of configdata.pm aborted due to compilation errors.
```

This is relevant because in Homebrew, package names may include a `@` in the name to designate a version, and this will affect the build path.  The existing `openssl@1.1` package does not appear to be affected.

### LINKED ISSUE #12743: configure script fails if path contains "@" symbol
In Homebrew, the formula will be called "openssl@3" and get installed in `/usr/local/Cellar/openssl@3`. I noticed that the @ symbol in the path seems to break the configure script as below. This did not happen for `openssl@1.1`.

```sh
perl ./Configure --prefix=/usr/local/Cellar/openssl@3/3.0.0-alpha6 --openssldir=/usr/local/etc/openssl3 no-ssl3 no-ssl3-method no-zlib darwin64-x86_64-cc enable-ec_nistp_64_gcc_128
make
#Last 15 lines from /Users/jeroen/Library/Logs/Homebrew/openssl@3/02.make:
#2020-08-28 22:43:13 +0200
#
#make
#
#Makefile:2: *** missing separator.  Stop.
```

### LINKED ISSUE #13221: "perl Configure" fails due to folder names
For the latest version of openssl 1.1.1x as of today:

Perl has a weird quirk that needs to be mentioned in Notes.win for future users. Perl, specifically strawberry perl, will fail to properly execute "perl Configure" when the folder structure to your openssl folder is something like:

> C:/project-master@74gf8/openssl

The **@** symbol above causes perl to fail to generate the makefile for nmake properly, and gives meaningless errors (i.e. they don't point you to the folder structure). 

**Please consider adding a line to Notes.Win** specifying that folder names mustn't include the @ symbol for perl to work properly (and likely other symbols, I did not test this out with others).

### PR DESCRIPTION
**Pull request by levitte**
Fixes #13221
Fixes #12743
Fixes #12078

### CODE REVIEW

**Comment by levitte** [comment]
This is WIP until confirmed to fix the issues

**Review by paulidale — APPROVED** [review]
Assuming that this fixes the problems.

**Review by t-j-h — APPROVED** [review]

**Review by jeroen — APPROVED** [review]
Fixes my problem, thank you!

**Review by Croydon — APPROVED** [review]
Works for Conan

**Comment by levitte** [comment]
Merged

09803e9ce3a8a555e7014ebd11b4c80f9d300cf0 configdata.pm.in, util/dofile.pl: Make a HERE document stricter.

**Pull request closed without merging**
