### PR TITLE
Configuration: do not overwrite BASE_unix ex_libs in AIX

### PR DESCRIPTION
**Pull request by alltilla**
`BASE_unix` sets `ex_libs` to `-lz` based the on zlib linking.
AIX platforms overwrote this instead of adding to it.

Signed-off-by: Attila Szakacs <attila.szakacs@oneidentity.com>

### CODE REVIEW

**Comment by alltilla** [comment]
I think this change categorizes as trivial, based on "... one-line bugfixes might be accepted as trivial without requiring a CLA."
If you say CLA is required, I happily sign it.

Cheers!

**Comment by levitte** [comment]
I'd say that this is trivial.  To signal that, we ask you to add the following in the commit message, on a line of its own:

```
CLA: Trivial
```

**Comment by levitte** [comment]
Merged

b1f9db698011e5a178d53483eccfd0a44f132baf Configuration: do not overwrite BASE_unix ex_libs in AIX

**Comment by levitte** [comment]
This cherry-picks cleanly to 1.1.1.  Approval?

**Comment by slontis** [comment]
Approved. I see no reason not to put this back in 1.1.1 also.

**Comment by levitte** [comment]
Merged into 1.1.1 as well:

c437fc2d481ab62b76b11270293392649dd092d3 Configuration: do not overwrite BASE_unix ex_libs in AIX

**Pull request closed without merging**
