### PR TITLE
Clarify use of EGD for HPNS in rand/rand_egd.c comments.

### PR DESCRIPTION
**Pull request by rsbeckerca**
Signed-off-by: Randall S. Becker <randall.becker@nexbridge.ca>

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
Not certain if this change meets the stability policy for old releases.

**Comment by t8m** [comment]
> Not certain if this change meets the stability policy for old releases.

Yeah, this is borderline. @rsbeckerca would you be OK with dropping this and do it for master only?

**Comment by t8m** [comment]
Alternatively, it would be acceptable if you actually changed not just the comment but add a proper note in NOTES-NONSTOP.md.

But not with CLA: trivial.

**Comment by rsbeckerca** [comment]
> > Not certain if this change meets the stability policy for old releases.
> 
> Yeah, this is borderline. @rsbeckerca would you be OK with dropping this and do it for master only?

This is quite important to our user community at 3,0. The comment originally appeared to describe something only needed for a small edge-condition but is actually of broad relevance. The community cannot move to the 3.1/master branch at this stage for testing because it is not functional on the platform - other Issues are open to describe those, so we are stuck on 1.1.1 and 3.0 for now. We are seeing slow adoption of 3.0.x, partly because of what was considered misleading documentation in the block corrected by this change. The command does not change the functionality but it explains when do go down the code path and when not do.

Note: 1.1.1 is being handled in our own fork for obvious reasons. The change was motivated from there.

**Comment by rsbeckerca** [comment]
> Alternatively, it would be acceptable if you actually changed not just the comment but add a proper note in NOTES-NONSTOP.md.
> 
> But not with CLA: trivial.

I can remove the CLA: trivial. My thought was that the comment at the front of `NOTES-NONSTOP.md` already covered it:

```
 * The TNS/X platform supports hardware randomization.
   Specify the `--with-rand-seed=rdcpu` option to the `./Configure` script.
   This is recommended but not required. `egd` is supported at 3.0 but cannot
```

**Comment by t8m** [comment]
OK, given the comment is kind of developer documentation and misleading I think we can accept it as documentation change.

**Review by t8m — APPROVED** [review]

**Comment by rsbeckerca** [comment]
> OK, given the comment is kind of developer documentation and misleading I think we can accept it as documentation change.

Thanks. I know a bunch of people who will be happy about this.

**Comment by paulidale** [comment]
Merged.

**Pull request closed without merging**
