### PR TITLE
Do not eat trailing '\n' in BIO_gets for fd BIO.

### PR DESCRIPTION
**Pull request by t8m**
This is re-opening of the previous pull request #1925 due to rename of the branch.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
I'll repeat @t-j-h's words here (emphasis mine):

> It should go in master and *the behaviour change should be noted* - i.e. the doc should read as clearly as fgets does - *and it should note that prior versions of the FD bio did not have these semantics*.

I agree with him.  I suggest adding a `HISTORY` section in `BIO_read.pod` for it.

**Comment by richsalz** [comment]
Adding a comment in HISTORY and CHANGES "a long-standing bug..." is a great idea.

**Comment by kaduk** [comment]
Are we talking 1.1.1 or 1.2?

**Comment by levitte** [comment]
We're at least talking 1.1.1.  This is a bug, and a painfully so as it's been along for so long, but still a bug.  Me, I'd have it backported to 1.1.0 as well, but I think @openssl/team has varying opinions on that.

**Comment by t8m** [comment]
I've added the HISTORY section to the manpage.

**Comment by levitte** [comment]
Merged.  79b35228f1cc6fea47bab34611d79aab190f4f28 to 007d2725303936588df656042fd61aa8ec6f7254

**Pull request closed without merging**
