### PR TITLE
fips: remove drgb_no_trunc_dgst IG withdrawn

### PR DESCRIPTION
**Pull request by xnox**
- **fips: remove drgb_no_trunc_dgst IG withdrawn**
  IG D.G moved to W.2 and has withdrawn status. Meaning any approved
  hash, including truncated ones, are allowed.
  
  Remove all of drbg_no_trunc_dgst support, as it is now
  irrelevant. Leave history note in EVP_RAND manpages, as a hint as to
  why some hashes might not work with 3.1.1 - 3.4 fips providers.
  

- **Changes update**

### CODE REVIEW

**Review by paulidale — DISMISSED** [review]

**Comment by paulidale** [comment]
OTC: **Removing the command option is a breaking change.  Should it be allowed?**

**Comment by paulidale** [comment]
Kick CIs

**Comment by xnox** [comment]
I see cross-testing failures. I am not familiar with them.

Do I need to create 3.x-branch specific pull requests that limit EVP tests of truncated DRBGs to the v3.1.1 - v3.4  range only?

Or is it a false negative, because cross-test used master-tip test suite, rather than the PR-tip test suite?

```
Test Summary Report
-------------------
30-test_evp.t                         (Wstat: 256 Tests: 123 Failed: 1)
  Failed test:  63
  Non-zero exit status: 1
Files=327, Tests=4230, 142 wallclock secs (10.62 usr  1.12 sys + 372.99 cusr 83.07 csys = 467.80 CPU)
```

**Comment by paulidale** [comment]
> Do I need to create 3.x-branch specific pull requests that limit EVP tests of truncated DRBGs to the v3.1.1 - v3.4 range only?

This is the usual way.  Removing the tests is another possibility which is tempting here (but wait to see if that's a wider opinion).

**Comment by slontis** [comment]
Or we could just leave it as it is.. There is really not much reason to use these anyway.
It wasnt too long ago that this was added.

**Comment by t8m** [comment]
Yeah, we would at least need to keep the command line option as no-op.

**Comment by paulidale** [comment]
I very much doubt anyone uses the command line option.  It's fairly recent and rather pointless.

**Comment by xnox** [comment]
> **OTC: We want to keep the restriction unless there is compelling reason to allow the truncated hashes.**

Ack, then unapproved service indicator should be removed in favor of simple runtime check. As at this point it is a user choice (or compile time choice) which is approved either way.

**Pull request closed without merging**
