### PR TITLE
Remove EXPORT_VAR_AS_FUNC

### PR DESCRIPTION
**Pull request by richsalz**
We only export functions, not global, so remove the config option
and some of the #ifdef stuff.

Cannot do a complete removal of ```EXPORT_VAR_AS_FUNCTION``` until #9284 is merged.  Or should I merge that PR unto this one to clearly out all "var as function" stuff at once?

### CODE REVIEW

**Comment by richsalz** [comment]
Since #9284 has been approved, and will hopefully be merged soon, I will then update this to remove all traces of ```EXPORT_VAR_AS_FUNCTION``` stuff.

**Comment by richsalz** [comment]
updated commit pushed.

**Comment by paulidale** [comment]
Merged to master.  Thanks.

**Comment by levitte** [comment]
Thank you for taking care of this particular beast!

**Pull request closed without merging**
