### PR TITLE
Remove heartbeats

### PR DESCRIPTION
**Pull request by levitte**
Note: there are two commits.  One removes heartbeats enough without changing the public API and is suitable to merge into OpenSSL_1_1_0-stable and master.  The other one removes the heartbeats API entirely, and is more suitable for 1.2.0, whenever we get there.

### CODE REVIEW

**Comment by kroeckx** [comment]
So it has a merge conflict.

**Comment by levitte** [comment]
Not any more

**Comment by kaduk** [comment]
I'm curious why the previous state of affairs with DTLS-only heartbeats was deemed to be undesirable in preference of no heartbeat support at all.

**Comment by levitte** [comment]
@kaduk, I'm afraid I don't understand your question... Mind you, I haven't been part of the  heartbeats thing from the start, I'm just acting on an expressed desire to remove the heartbeats feature from OpenSSL.

**Comment by richsalz** [comment]
Concern that someone, somewhere was using it.

**Comment by vdukhovni** [comment]
I also don't see why this is on the agenda.  If we don't trust the buffer management in 1.1.0 and master, we need to fix that, removing heartbeats from DTLS is solving yesterday's problem. It seems to me that DTLS heartbeats are a plausibly useful feature, for which we should be able to provide a correct implementation.

**Comment by richsalz** [comment]
They are perhaps theoretically useful, but nobody is using it as far as we can tell.

**Comment by vdukhovni** [comment]
There is very little DTLS use period. But if we are supporting it, I think the right posture is to proudly say that heartbleed is not a problem because our code is a lot more solid and we stand behind the implementation, than to remove it.  We have cleaner buffer management, fuzzers, code review, ... it is I think time to stop paying attention to heartbleed and solve real problems.

**Comment by richsalz** [comment]
There’s an emotional aspect here as well.  KILL IT

**Comment by vdukhovni** [comment]
The emotional aspect is irrelevant.  If DTLS heartbeats remain in TLS 1.3, then we should continue to support the feature.  Only if TLS 1.3 is removing DTLS heartbeats, then I could be talked into this on account of upcoming obsolescence..

**Comment by ekasper** [comment]
We're not proudly supporting it - the test is thoroughly broken, nobody external has even noticed that, and nobody in the team has stepped up to fix it.

**Comment by kaduk** [comment]
Thanks for all the discussion.  The test being broken and no one having noticed that does seem to give support to the belief that it is unused.  Maybe some of that information could go in the commit message, though?

**Comment by tmshort** [comment]
My recollection is that even the ASA/AnyConnect that uses DTLS does not use Heartbeats; a data packet is used so that the VPN layer can "see" the keepalive/heartbeat.

**Comment by richsalz** [comment]
do the appropriate merge.  finally.

**Comment by richsalz** [comment]
closed by mistake.

**Comment by kroeckx** [comment]
@dwmw2: Do you have any comments about the usefulness of heartbeat for PMTUD in case of DTLS?

**Comment by dwmw2** [comment]
@tmshort is correct; AnyConnect does it all at the data layer, using a one-byte packet type as the first byte of the payload. We do extend the protocol somewhat in OpenConnect *(allowing standard DTLS, AEAD ciphersuites, proper negotiation,  etc.)* but we hadn't gone as far as using heartbeats to replace the Dead Peer Detection and keepalive, even though I suppose an argument could be made for doing so and regaining that byte.

So MTU detection is done with large DPD payload packets, and we have no current plan to change that. And Cisco themselves have it implemented in hardware and don't even seem to have plans to catch up to DTLSv1.0 let alone change anything else.

**Comment by richsalz** [comment]
ping @levitte you want me to do this?  My delete key is ready :+1:

**Review by t-j-h — APPROVED** [review]

**Comment by richsalz** [comment]
@levitte, the first commit is merged.  if you want to rebase or close or make a new one (or want me to do it) that holds only the second commit, which would be on-hold, let me know.

**Comment by levitte** [comment]
Whatever I have to do, I'll do tomorrow.

**Comment by kaduk** [comment]
Can I request that the commit message say something about why the code is being removed?

**Comment by kaduk** [comment]
> Can I request that the commit message say something about why the code is being removed?

Oops, apparently I can't, because the commit was pushed already even though the PR is not closed.

**Comment by richsalz** [comment]
Too late now.

And it should be immediately obvious to everyone about openssl and heartbeats.

**Comment by levitte** [comment]
It *is* possible to add a [note](https://git-scm.com/docs/git-notes)...

**Comment by richsalz** [comment]
Sure.  But we don’t justify any other commits.

**Comment by levitte** [comment]
It seems this PR was a bit too confusing.

Question: do we want the "almost entire" removal in the 1.1.0 branch as well?  That was my original intent.  If we do, I'll prepare a separate PR for that.

Meanwhile, this is now entirely merged into master.

**Comment by mattcaswell** [comment]
No...we should not remove this from a stable branch.

**Comment by levitte** [comment]
Ok then.  Thank you.

**Comment by richsalz** [comment]
Doesn’t that change the API?

--
Senior Architect, Akamai Technologies
Member, OpenSSL Dev Team
IM: richsalz@jabber.at Twitter: RichSalz

**Comment by levitte** [comment]
Errr...  ah, you mean we finally got to the point where we need to create the OpenSSL_1_1_x branch?

**Comment by levitte** [comment]
Actually, no...  or, well, we could add back the `"heartbeats"` item to `%disabled` in `Configure` to make that perfectly clear, and we could make `enable-heartbeats` a no-op, and leave it at that.  Would that be preferable?

**Comment by mattcaswell** [comment]
Well, technically, this would be an ABI/API break so isn't eligible for 1.1.1, it would have to be 1.2.0

**Comment by tmshort** [comment]
Keep the configuration interface the same. As a followup to my previous comment, The Cisco ASA was immune to Heartbleed because it didn't recognize the heartbeat record type. What happens now if a malicious client decides to send a heartbeat? Does the connection close, I presume?

**Comment by mattcaswell** [comment]
As of 1.1.0c (commit 436a2a01794) any unrecognised record type results in the connection closing.

**Comment by richsalz** [comment]
You have to revert that "completely remove" commit.  Source code that worked in 1.1.0 no longer works, configuration scripts no longer work (we talked about this with #1814 ), and binaries that used to work will probably now break.

+1 to revert that change, and then put this rest of this MR on hold.

**Comment by levitte** [comment]
I'll revert and make a new PR for pending 1.2.0 changes.  I'm pretty sure those will start piling up and we might be ready for a 1.1.x branch.

**Comment by FdaSilvaYY** [comment]
This PR has two commits : e72040c1dcd61d6669762a60924b8fa3a48c37fc, and 6c62f9e1639a7d1a879f363a99882920104dfedb
Only the second last was revert. Is it OK ?

**Comment by richsalz** [comment]
Yes, that is *exactly* the right thing.  HEARTBEAT functionality was removed, but the API and compatibility with 1.1.0 was not changed.

**Comment by levitte** [comment]
@FdaSilvaYY, I've kept the complete removal in a separate PR, #1928

**Pull request closed without merging**
