### PR TITLE
Make RSA key exchange code actually constant-time.

### PR DESCRIPTION
**Pull request by davidben**
Using RSA_PKCS1_PADDING with RSA_private_decrypt is inherently unsafe.
The API requires writing output on success and touching the error queue
on error. Thus, although the padding check itself is constant-time as of
294d1e36c2495ff00e697c9ff622856d3114f14f, and the logic after the
decryption in the SSL code is constant-time as of
adb46dbc6dd7347750df2468c93e8c34bcb93a4b, the API boundary in the middle
still leaks whether the padding check succeeded, giving us our
much-loved Bleichenbacher padding oracle.

Instead, PKCS#1 padding must be handled by the caller which uses
RSA_NO_PADDING, in timing-sensitive code integrated with the
Bleichenbacher mitigation. Removing PKCS#1 padding in constant time is
actually much simpler when the expected length is a constant (and if
it's not a constant, avoiding a padding oracle seems unlikely), so just
do it inline.

BoringSSL has been running with a variant of this code for some time now
without problems. See BoringSSL commits
0aa0767340baf925bda4804882aab0cb974b2d26 and
3f5b43df0752a877c744a9cac918e4f5e8d3aed6.

### CODE REVIEW

**Comment by kroeckx** [comment]
I'm wondering if after the RSA_private_decrypt() call we need to pad the front of rsa_decrypt with 0's at the front so that it's the correct length for the RSA key?  Or did we already change it to return a padded result?

I also had to look twice at why it didn't check that PS is at least 8 bytes.  I guess your comment about the 11 byte overhead could be improved.

**Comment by davidben** [comment]
> I'm wondering if after the RSA_private_decrypt() call we need to pad the front of rsa_decrypt with 0's at the front so that it's the correct length for the RSA key? Or did we already change it to return a padded result?

`RSA_private_decrypt` should already do this. See `RSA_padding_check_none`. (Though it internally takes the leading zeros off and puts them back on, which is also a separate problem. See https://boringssl.googlesource.com/boringssl/+/6887edb917ba9ecbed85f9d63ec36638b1d1dbb6 which makes it better, though still not ideal. `BIGNUM` needs to either be excised or reworked to really make this right. A bignum library for crypto should never strip leading zeros.)

> I also had to look twice at why it didn't check that PS is at least 8 bytes. I guess your comment about the 11 byte overhead could be improved.

Improved comments a bit. Also hopefully fixed signed/unsigned comparison that Travis was unhappy about.

**Comment by davidben** [comment]
> Or did we already change it to return a padded result?

Sorry, I should clarify, since I don't believe anything changed either. There may be some confusion with `RSA_private_decrypt`'s output and internal state. `RSA_PADDING_NONE` always returned something of the right size. However, internally, `RSA_private_decrypt` takes leading zeros off (and puts them back on for `RSA_PADDING_NONE`) and the padding check functions all require that the zeros are removed. This actually means the padding check functions and `RSA_PADDING_NONE` do not compose as one might imagine. It's a bit of a mess and you can see some of the consequences here:

https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=crypto/rsa/rsa_pmeth.c;h=767c4e7247da3262f210ca34c55a4b8a73ca4278;hb=HEAD#l308
(The zeros get taken off, put back on, and taken off again, before being passed to the padding check.)

The BoringSSL check I linked to, among other things, fixes this so the intermediate step is zero-padded and the padding check functions uniformly take a zero-padded input. This is an API break, but otherwise the code isn't constant-time. (See Manger's.)
https://boringssl.googlesource.com/boringssl/+/6887edb917ba9ecbed85f9d63ec36638b1d1dbb6%5E%21/

(Separately from that, getting a zero-padded input out of the RSA module is also a problem since `BIGNUM` may have chopped leading zeros off. We haven't fixed that one in BoringSSL yet since it'll take a bit of surgery and we haven't had the time yet. We just do the best we can for now with the internal representation we've got.)

Anyway, this is totally tangential to this CL. :-)

**Comment by kroeckx** [comment]
+1

**Comment by richsalz** [comment]
+1  backport?

**Comment by davidben** [comment]
> Should this be picked to 1.0.2?

A backport should be relatively straight-forward. Although it is a user-visible behavior change if anyone's using an `ENGINE`-backed RSA key. I don't know how much you all care about that.

**Comment by bryongloden** [comment]
🎉

**Pull request closed without merging**
