### PR TITLE
Removed references to 'OPENSSL_memcmp' since it wasn't used

### PR DESCRIPTION
**Pull request by gdrob**
'OPENSSL_memcmp' in crypto/o_str.c wasn't used anywhere.
'include/internal/o_str.h' contained only declaration for 'OPENSSL_memcmp' - so I removed the file and references to it.

### CODE REVIEW

**Comment by gdrob** [comment]
Not sure why the travis-ci fails. Is there any configuration change missing from this commit?

**Comment by mattcaswell** [comment]
You need to run "make update" and check in the changes to util/libcrypto.num

**Comment by dot-asm** [comment]
Formally speaking removing anything from export symbol list is inappropriate in non-major release.

**Comment by richsalz** [comment]
Right, the libcrypto.num entry should be changed to NOEXIST

**Comment by kroeckx** [comment]
We can't remove this in a 1.1 release, not even changing it to NOEXIST

**Comment by kroeckx** [comment]
Anyway, this still needs a CLA

**Comment by levitte** [comment]
> We can't remove this in a 1.1 release, not even changing it to NOEXIST

Actually, we can, as it's not part of our public API.

**Comment by gdrob** [comment]
Do I really have to get the CLA? Also build failures. Also build failures seem not related.

**Comment by mattcaswell** [comment]
> We can't remove this in a 1.1 release, not even changing it to NOEXIST

> Actually, we can, as it's not part of our public API.

I think that's a grey area since we promise "binary compatibility" and this is part of the ABI (just not part of the API).

**Comment by levitte** [comment]
Hmmm, so are you saying that we're promising that for private symbols that just happen to be exported in libcrypto because libssl needs them?  I didn't view things that way...

**Comment by mattcaswell** [comment]
> Hmmm, so are you saying that we're promising that for private symbols that just happen to be exported in libcrypto because libssl needs them? I didn't view things that way...

Technically I think we are saying that - or at least its a grey area. In any case this will be detected by ABI compliance checking tools and we would have to rejustify it every time we were challenged on it. Given the benefit of removal is limited, on balance I think I favour retaining this function.

**Comment by t-j-h** [comment]
Technically we should not be adding or removing any symbols that are exported. I think that is pretty much how it used to be handled - although a formal definition of what we mean by compatibility should be created. We also could do with defining what we mean by "public API" as we have varying views on that (from anything in the public header files to just what is in the pod-based docs).

**Comment by richsalz** [comment]
I need about nine symbols exported, ```RAND_DRBG_xxxx``` so that they can be used in test and by libssl.
I think our public API/ABI is what is declared in public header files.  Otherwise, why did we go through lots of discussion after the first F2F to set up internal directories?

**Comment by levitte** [comment]
> Technically we should not be **adding** or removing any symbols that are exported.

Really?

**Comment by levitte** [comment]
Other than that, I agree with @richsalz.  The message to the users is (or should be) "if you don't get it through our public headers, do *not* rely on it", or in other words, the contract we offer is declarative.

**Comment by mspncp** [comment]
@gdrob this pull request has been stalled with a single approval for a long time now, mainly because a [Contributor License Agreement](https://www.openssl.org/policies/cla.html) is still missing. If you are still interested in pursuing this pull request, please send us a signed CLA and rebase your pull request, since it has merge conflicts.

**Comment by gdrob** [comment]
Thanks for the information. I forgot about this one but I can send the CLA
over the weekend. It might motivate me to make some contributions.

Regards,
Grzegorz

śr., 10 kwi 2019 o 07:57 Matthias St. Pierre <notifications@github.com>
napisał(a):

**Comment by iamamoose** [comment]
This PR has been closed because it has been stalled for some time due to the lack of a CLA.  If you are able to supply a CLA please reopen this PR.  For CLA help see https://www.openssl.org/policies/cla.html

**Pull request closed without merging**
