### PR TITLE
82-test_ocsp_cert_chain.t: Terminate the server after 1 connection

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Comment by t8m** [comment]
@jamuir This should avoid the infinite waiting.

**Comment by jamuir** [comment]
I thought that the lines that were removed from the file `82-test_ocsp_cert_chain.t` were going to be restored (i.e. the lines removed from the last while loop).

Could they be restored?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by jamuir** [comment]
Restoring the lines makes it so that if there is no connection and the
server outputs an unexpected string, then the test will terminate (with a
failure).

Removing the lines has brought
back a problem that I dealt with during development.

I thought the issue with the AFL toolchain was supposed to be resolved by
setting AFL_MAP_SIZE.  Now, I cannot tell if it has because those lines
were removed.

**Comment by t8m** [comment]
@jamuir This is better fix. We just forcibly kill the server once the client terminates.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master and 3.3 branches. Thank you for the reviews.

**Pull request closed without merging**
