### PR TITLE
poly1305/asm/poly1305-x86_64.pl: add Knights Landing AVX512 result.

### PR DESCRIPTION
**Pull request by dot-asm**
Hardware used for benchmarking courtesy of Atos, experiments run by
Romain Dolbeau <romain.dolbeau@atos.net>. Kudos!

[skip ci]

pure commentary update, no code changes.

### CODE REVIEW

**Comment by dot-asm** [comment]
Hmmm, I had an impression [skip ci] applied even to appveyor... Did it, or do I remember it wrong?

**Comment by dot-asm** [comment]
Oh! It wasn't my intention to upload the additional commit, since it's not yet clear if it makes difference. It simply got synched, as I was synching master. But OK. I'm removing "ready" label and changing subject to WIP, and will ask for re-review if patch helps. And if it doesn't I intend to use approval for first commit. Sorry about noise...

**Comment by dot-asm** [comment]
And just in case it wasn't obvious, "WIP" in subject means that I don't seek approval till it's removed.

**Comment by dot-asm** [comment]
WIP removed, approval is pending. It's not pure commentary update anymore.

**Comment by dot-asm** [comment]
> IT was confusing to see '#' inside the code part.

Are you referring to commentaries or things like `%x#$T0`? If former, then question is if I should add couple of words, e.g. "will become ${S1}{%k2}{z}"? If latter, then it's kind of a "cast", it means %x-part of register $T0 which can be %ymm or %zmm. As you might know least significant half of %zmm is %ymm, and least significant half of %ymm is %xmm. The rationale behind "syntax" choice is regex simplicity...

**Comment by richsalz** [comment]
It was the former, and the "will become..." comment would help.

**Comment by dot-asm** [comment]
Updated commentary. Since it's pure commentary update I consider that approval stands unless claimed otherwise...

**Pull request closed without merging**
