### PR TITLE
Constify OSSL_FUNC_keymgmt_has()

### PR DESCRIPTION
**Pull request by romen**
The keydata argument of `OSSL_FUNC_keymgmt_has()` should be read-only.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
LGTM, but give @levitte time to comment

**Comment by romen** [comment]
@levitte I see you refactored this in #11006, was it intentional to make it non-`const` or just something that slipped through?

**Comment by romen** [comment]
I also wonder if I should apply the same to the next line: `keymgmt_validate`

**Comment by romen** [comment]
> I also wonder if I should apply the same to the next line: `keymgmt_validate`

See #13201: it's a separate PR because there the fallout of the constification has more serious consequences.

**Comment by romen** [comment]
> LGTM, but give @levitte time to comment

I'll start the clock, but will hold the merge until we get confirmation from @levitte

**Comment by levitte** [comment]
> @levitte I see you refactored this in #11006, was it intentional to make it non-`const` or just something that slipped through?

That specific function is actually completely new in #11006 :wink:

Having it non-const was an omission, so thanks for fixing it.

**Review by levitte — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.

**Pull request closed without merging**
