### PR TITLE
HPE NonStop TNS/X and TNS/E platform port changes for 1.1.1f

### LINKED ISSUE #5087: Assistance request: setting up for NonStop platform support
Greetings! I'm about to submit a PR for the NonStop NSX and NSE platform ports for OpenSSL and need assistance in setting up required pieces (Configurations/x-nonstop.conf) as well as documenting the port. The overall port has two basic aspects that deviate from standard code:

- Inclusion of platform FLOSS method redirects to emulate Linux behaviour, and
- Changes to root id - root on NonStop is 65535 rather than 0, and
- Compiles under c99 rather than gcc.

### PR DESCRIPTION
**Pull request by rsbeckerca**
This pull request is a roll-up of all changes that are being continuously tested as part of the HPE NonStop Port effort. Most changes are fairly trivial. Adds standard OSS unthreaded, PUT and SPT threaded. Add tests pass in OSS (POSIX) for TNS/X and TNS/E platforms at 1.1.1f.

Fixes #5087.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Please can you target master for this PR? These changes are too significant for porting to a stable branch - and you would need to make the equivalent changes in master in any case.

Please also submit a CLA:

https://www.openssl.org/policies/cla.html

**Comment by rsbeckerca** [comment]
We have not tested the changes with 3.0.0. These are 1.1.1-specific only. If we need to wait for 3.0.x, we can do that and I will reissue the PR in a few weeks.

**Comment by mattcaswell** [comment]
> We have not tested the changes with 3.0.0. These are 1.1.1-specific only. If we need to wait for 3.0.x, we can do that and I will reissue the PR in a few weeks. 

Feature freeze for 3.0 is imminent - alpha 6 is coming on Thursday. We expect beta1 towards the end of this month - as soon as beta1 is released we're in feature freeze so this would have to push back to 3.1 at that point.

> CLA agreement has been submitted to legal.

Perfect. Thanks.

**Comment by rsbeckerca** [comment]
For 3.0 to 3.1, are the changes going to be like 1.0 to 1.1, where the interfaces changed incompatibly, or will DLL resolution continue to work? This would drive our efforts.

**Comment by rsbeckerca** [comment]
To be replaced by PR on master.

**Comment by mattcaswell** [comment]
> For 3.0 to 3.1, are the changes going to be like 1.0 to 1.1, where the interfaces changed incompatibly, or will DLL resolution continue to work? This would drive our efforts.

See this blog post for a description of our new versioning scheme being implemented as of 3.0:

https://www.openssl.org/blog/blog/2018/11/28/version/

Basically if the major version number remains the same (i.e. 3 in this case), then we guarantee API and ABI compatibility between versions. So 3.1 would be API/ABI compatible with 3.0.

However I would note that it is only my assumption that the next release will be 3.1. There has been no such formal decision so, in theory, the OMC could decide to issue 4.0 next. I personally think it is unlikely, but I've been wrong before :-)

**Pull request closed without merging**
