### PR TITLE
mkerr: Fix string literal conversion

### PR DESCRIPTION
**Pull request by svenschwermer**
This fixes a compiler warning on clang-1205.0.22.9 when compiling the generated code as C++11:

    ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by levitte — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by svenschwermer** [comment]
I'm not sure what's wrong in the failing test. All tests pass when I run them locally. What to do?

**Comment by mattcaswell** [comment]
> I'm not sure what's wrong in the failing test. All tests pass when I run them locally. What to do?

It's difficult to see how this PR could cause that failure. It appears unconnected.

**Comment by t8m** [comment]
I agree this is trivial change as the first commit is really trivial and the second one is generated by openssl make itself so there is nothing copyrightable on that one either.

**Comment by t8m** [comment]
@levitte @paulidale do you agree with CLA: trivial?

**Comment by levitte** [comment]
I agree that it's trivial

**Review by paulidale — APPROVED** [review]
Yes, trivial.

**Comment by t8m** [comment]
Merged to master. Thank you for your contribution.

**Pull request closed without merging**
