### PR TITLE
gcm_get_funcs(): Add missing fallback for ghash on x86_64

### LINKED ISSUE #19673: Segfault in GCM for x86_64 without hardware acceleration
Context: https://github.com/openssl/openssl/blob/master/crypto/modes/gcm128.c#L414-L424

When `GHASH_ASM` is defined, `ctx->ghash` is set to NULL. However, when hardware acceleration is not available on x86_64 (e.g. without PCLMULQDQ), `ctx->ghash` stays NULL. This causes a segfault when trying to use GCM. This can be emulated by using the `OPENSSL_ia32cap` variables as follows:
```
$ openssl version
OpenSSL 3.2.0-dev  (Library: OpenSSL 3.2.0-dev )
$ OPENSSL_ia32cap=~0x1240000200000000:~0x00000600C0230000 openssl speed -evp aes-128-gcm
Doing AES-128-GCM for 3s on 16 size blocks: zsh: segmentation fault (core dumped)  OPENSSL_ia32cap=~0x1240000200000000:~0x00000600C0230000 openssl speed -evp 
```

This seems related to https://github.com/openssl/openssl/commit/186be8ed26f5561faf91d6da3ed14cd9cb6617dd where it was fixed for ARM and SPARC?

### PR DESCRIPTION
**Pull request by t8m**
Fixes #19673

### CODE REVIEW

**Comment by t8m** [comment]
Setting `tests: deferred` as for proper testing we should think about testing in CI with masking CPU capabilities in general.

**Review by hlandau — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master branch. Keeping open to merge to 3.1 after the gcm refactoring is merged there.

**Comment by thesamesam** [comment]
> Setting `tests: deferred` as for proper testing we should think about testing in CI with masking CPU capabilities in general.

It's the kind of thing that SDE can help with, but see https://github.com/openssl/openssl/pull/19597#issuecomment-1304942395. I agree some strategy needs to be found for testing various HW bits like this.

**Comment by hlandau** [comment]
@t8m Can this be merged to 3.1 now?

**Comment by t8m** [comment]
It was merged in [74bfc16](https://github.com/openssl/openssl/commit/74bfc163f10e01dda74aada66039ddec13d96d2f)

Closing.

**Pull request closed without merging**
