### PR TITLE
add option to allow for an iteration count

### PR DESCRIPTION
**Pull request by EasySec**
Add option to allow an iteration count to be used with the enc command
All changes comming from pkcs8 command

##### Checklist
- [x] documentation is added or updated
- [x] CLA is signed

### CODE REVIEW

**Comment by EasySec** [comment]
Next step could be to integrate also the -v2 option ?

**Comment by richsalz** [comment]
+1

**Comment by EasySec** [comment]
FYI, I am ready to go to add PBKDF2 as soon as this PR will be closed.

**Comment by mattcaswell** [comment]
I don't think this is the way to go. Under the hood this is using `EVP_BytesToKey()` which is no longer recommended. I know that by default `enc` is already using `EVP_BytesToKey()` with an iteration count of 1 - but it doesn't make any sense to me to add new ways of using a non-recommended approach. I'd suggest a separate `-pbkdf2` option to force PBKDF2. You could also have a `-iter` option but if you use it then it would force PBKDF2.

**Comment by EasySec** [comment]
For me this small PR was a preliminary stage before introducing PBKDF2. I mean -iter could be used for both legacy BytesToKey() and PBKDF2 options. But if I understand you correctly you would prefer another PR dedicated to PBKDF2 leaving BytesToKey() using only 1 iteration. Right ?

**Comment by mattcaswell** [comment]
> For me this small PR was a preliminary stage before introducing PBKDF2. I mean -iter could be used for both legacy BytesToKey() and PBKDF2 options. But if I understand you correctly you would prefer another PR dedicated to PBKDF2 leaving BytesToKey() using only 1 iteration. Right ?

Correct. I don't think we should provide additional capabilities on top of BytesToKey() - that will only encourage its use.

**Comment by EasySec** [comment]
With due respect, I find it hard to believe that such a tool can be use for real-life encryption ;-)
For me, <code>enc</code> is more about learning, experimenting, debuging or testing.
And there is probably still a lot of software around calling <code>EVP_BytesToKey()</code> internally with an iteration count != 1 and for which it might be helpfull adding it to the command (ethical-hacking ?).
Don't you think it's a bit like the discussion some monthes ago about keeping MD5 or DES in OpenSSL 1.1.0 ?
However, you are the best judge, so if you just close this PR, I will propose another to support PBKDF2 in compliance with your opinion.

**Comment by mattcaswell** [comment]
> With due respect, I find it hard to believe that such a tool can be use for real-life encryption ;-)
> For me, enc is more about learning, experimenting, debuging or testing.

People *do* use it.

> And there is probably still a lot of software around calling EVP_BytesToKey() internally with an iteration count != 1 and for which it might be helpfull adding it to the command (ethical-hacking ?).

I don't see any demand for that.

> Don't you think it's a bit like the discussion some monthes ago about keeping MD5 or DES in OpenSSL 1.1.0 ?

I'm not sure which specific discussion you are referring to.

> However, you are the best judge, so if you just close this PR, I will propose another to support PBKDF2 in compliance with your opinion.

I do not consider this PR to be mergeable in its current state. If you want to implement PBKDF2 in a separate PR then I will happily look at that.

**Pull request closed without merging**
