### PR TITLE
Fix link in openssl-ciphers.pod

### LINKED ISSUE #10226: Wrong link in online documentation
The online manual on ciphers for 1.1.1 has a dead link to `SSL_CTX_set_security_level`

See: https://www.openssl.org/docs/man1.1.1/man1/ciphers.html

The link href is set to:
https://www.openssl.org/docs/man1.1.1/man1/SSL_CTX_set_security_level.html

But this should be:
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html

### PR DESCRIPTION
**Pull request by levitte**
Fixes #10226

### CODE REVIEW

**Comment by mattcaswell** [comment]
@levitte - this seems to have been closed unmerged, and with no comment. Any particular reason?

**Comment by mattcaswell** [comment]
Ah! In which case could #10240 add a "Fixes" reference to #10226.

**Comment by richsalz** [comment]
You want me to add that to a commit there?

**Comment by mattcaswell** [comment]
> You want me to add that to a commit there?

Ideally, yes.

**Comment by richsalz** [comment]
Done.  Fairly tortured wording since it fixes a lot more, but done.

**Pull request closed without merging**
