### PR TITLE
Add branch coverage to coveralls statistics

### LINKED ISSUE #4444: Add branch coverage to coveralls statistics
Coveralls.io recently gained support for measuring not only line coverage but also branch coverage: https://github.com/lemurheavy/coveralls-public/issues/31#issuecomment-284484062

I'd like to see it reported openssl builds

### PR DESCRIPTION
**Pull request by levitte**
Fixes #4444

### CODE REVIEW

**Comment by levitte** [comment]
Coveralls has already been updated to produces stats for this, all we need is to start producing

**Comment by FdaSilvaYY** [comment]
Needs an`[extended tests]` tag into commit message to trigger a coverage test from a PR.

**Review by richsalz — APPROVED** [review]
once build passes.

**Comment by dot-asm** [comment]
This would be exactly right opportunity to add [extended tests] ;-)

**Comment by levitte** [comment]
Good idea.  Did so just now

**Comment by levitte** [comment]
Speaking of that...  I've noticed that the coveralls hook is quite randomly triggered, or at least doesn't report anything in quite a number of PRs.  Anyone know what's up with that?

**Comment by FdaSilvaYY** [comment]
AFAIK, there is at least 2 conditions :
 - [extended test] tag to trigger an complete Travis builds.
 - The build job who run coverage should complete his test pass.

**Comment by kroeckx** [comment]
My understanding is that travis submits the results to coveralls,
and only when coveralls received it will send something to github
that makes it show up.

**Comment by levitte** [comment]
That makes complete sense, of course...

**Comment by levitte** [comment]
So, according to [this](https://github.com/lemurheavy/coveralls-public/issues/31#issuecomment-284375195), there should be another line about branch coverage in the run status...  and yet, there isn't in the coverage details available now.  Anyone know why?

**Comment by kroeckx** [comment]
I think we're actually waiting for https://github.com/eddyxu/cpp-coveralls/issues/110 to get fixed

**Comment by dot-asm** [comment]
One can also wonder if one has to install some specific cpp-coveralls package. I mean when $COVERALLS build is processed we do `pip install --user cpp-coveralls` and question if version of *this* package matters, and if so if it's right.

**Comment by levitte** [comment]
So in essence, that means we'll get a nice surprise some time ahead...

**Comment by kroeckx** [comment]
So should we just merge this for now?

**Comment by richsalz** [comment]
I'm in favor :)

**Comment by levitte** [comment]
Merged.  21c215423954e72ee0a8d6bcb813c45e166d4776

**Pull request closed without merging**
