### PR TITLE
CORE: Add a generic callback function type

### PR DESCRIPTION
**Pull request by levitte**
This offers a very generic way to define a callback as well as calling
it.

### CODE REVIEW

**Comment by levitte** [comment]
This is an alternative to #10390

**Comment by levitte** [comment]
So, I've made an alternative for #10391 that works with this PR (#10414).  As for #10394 and #10289, I think I'll wait with the work on those until I have a yay or nay here (I sure hope I get a yay).

**Comment by levitte** [comment]
Ping.

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

10e7216e502916f8e7917ac4f21411fffd1fb882 CORE: Add a generic callback function type

**Pull request closed without merging**
