### PR TITLE
Add support for otherName:NAIRealm in output

### PR DESCRIPTION
**Pull request by Janfred**
The experimental [RFC 7585](https://tools.ietf.org/html/rfc7585#section-2.2) adds a new otherName. This commit adds support for displaying this information.

I'm not completely sure if this is a trivial change.

### CODE REVIEW

**Comment by richsalz** [comment]
It's possible to make a case that this is a trivial (for copyright purposes) because you added one line to objects.txt, and six lines to v3_alt.c.  And both of those are obvious, and the only way to do what you did.

**Comment by Janfred** [comment]
@beldmit Unfortunately I'm not quite familiar with openssl. Is there a way to verify the output of the GENERAL_NAME_print function?

**Comment by beldmit** [comment]
If you have a valid certificate containing otherName:NAIRealm, ```openssl x509 -text -in mycert.pem``` does the trick.

**Comment by Janfred** [comment]
@beldmit Currently I'm using `openssl req -noout -text -in ~/tmp/cert.csr`. It seems that `i2v_GENERAL_NAME` does the output there.
I'm currently struggling with creating an actual certificate with this attribute, I'm currently using only the CSR for testing.

**Comment by Janfred** [comment]
@beldemit @paulidale I have no problem with signing the CLA, so I'll just do this.

**Comment by paulidale** [comment]
@Janfred, thanks.

**Comment by levitte** [comment]
This is ready to be merged

**Comment by beldmit** [comment]
Will do today but a bit later.

**Comment by beldmit** [comment]
Squashed and merged. Many thanks!

**Pull request closed without merging**
