### PR TITLE
Initial KDF contribution

### PR DESCRIPTION
**Pull request by fliphil**
KDF source code contribution from Cisco Systems, with addition of
new files and respective changes to existing files.

### CODE REVIEW

**Comment by simo5** [comment]
@richsalz  What's needed to carry this PR forward ?

**Comment by mattcaswell** [comment]
This PR is against the OpenSSL-fips-2_0-stable branch which is no longer being updated. We are instead working on a new FIPS module - but that is still at the early stages. If the FIPS aspects of this are important to you, then you should wait until master has FIPS support again. Alternatively, you can strip out the FIPS stuff and create a new PR against master.

However, since this is a sizeable contribution perhaps some discussion about your aims and objectives for this work in an issue is wise first.

**Comment by simo5** [comment]
@mattcaswell I'm interested mainly in the SSH KDF, FIPS is a plus but can come later.
Would it be acceptable to propose a new PR with just an SSH KDF implementation ?

**Comment by mattcaswell** [comment]
Is the SSH KDF standardised somewhere (e.g. in an RFC...perhaps RFC4253)? We have a policy of only accepting standardised algorithms.

**Comment by simo5** [comment]
@mattcaswell, yes RFC 4253 Section 7.2

**Comment by simo5** [comment]
@mattcaswell it is also in SP 800-135

**Comment by mattcaswell** [comment]
Ok, in that case I'd say go ahead and create a PR for that against master.

**Comment by paulidale** [comment]
Is this worth fitting into #6674 ?

**Comment by mattcaswell** [comment]
Yes - good point. Any new KDF should probably be built on top of that PR.

**Comment by levitte** [comment]
Thanks for the reminder, @paulidale...  I meant to start looking more closely at that PR after the 1.1.1 release, and there's no day like today :smile: 

(I look forward to the SSH KDF as well, and would also encourage alignment with #6674 when that one gets finally approved)

**Comment by simo5** [comment]
Ok, mI have something working already, I'll go and rebase on top of #6674 then once I have decent tests will submit a PR

**Comment by Jesikaz520** [comment]
Can the composer of this thread please message me personally, thankyou.

**Comment by fliphil** [comment]
We (@bfussell) have a non-FIPS version of the code as well. Is that something that you are interested in?

**Comment by levitte** [comment]
Since @simo5 says he'll work on an adaptation for the new EVP_KDF API (now merged), I'm closing this

**Pull request closed without merging**
