### PR TITLE
Add Provider compatibility on PR CI job

### PR DESCRIPTION
**Pull request by t8m**
This job will run only if `extended tests` label is set on the PR.

### CODE REVIEW

**Comment by t8m** [comment]
Please note that the 2 failing provider compat CI jobs have to be fixed on the 3.0 and 3.1 branches.

**Comment by t8m** [comment]
Also please note I want to add this workflow to all the branches so subsequent PRs on these branches can use this CI job.

**Comment by paulidale** [comment]
> This job will run only if `extended tests` label is set on the PR.

Which tests would get this?
Unless this is run often, we will fail to catch breaking changes.  Such changes have appeared in all manner of different ways.

**Comment by t8m** [comment]
> Which tests would get this?
> Unless this is run often, we will fail to catch breaking changes. Such changes have appeared in all manner of different ways.

I do not plan to add the condition to `extended tests` to any existing tests that run on PRs (although it might make sense to add it for at least the self-hosted freebsd test which is flaky and we are unable to fix the flakiness). This is to be added for things like the Provider compat CI tests - which is being added by this PR.

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
ping @openssl/committers for second review

**Comment by t8m** [comment]
Merged to all the active branches. Finally we can easily test provider compatibility on PRs on all branches.

**Pull request closed without merging**
