### PR TITLE
Add riscv64 target for OpenSSL_1_1_1

### PR DESCRIPTION
**Pull request by luyahan**
Just add riscv64 config.

### CODE REVIEW

**Comment by luyahan** [comment]
@t8m  Hi Tomáš, can you review this pr?

**Comment by t8m** [comment]
Unfortunately this would require an exception from OTC/OMC as 1.1.1 is bug fix only.

**Comment by slontis** [comment]
The change has been merged to master via #14723

**Comment by slontis** [comment]
Does this need a hold?

**Comment by paulidale** [comment]
We've allow similar changes in the past but the OTC should confirm I think.

**Comment by luyahan** [comment]
> We've allow similar changes in the past but the OTC should confirm I think.

Hi paulidale
How to get OTC to confirm ?

**Comment by levitte** [comment]
> We've allow similar changes in the past but the OTC should confirm I think.

As a rule, we consider this type of change "new feature" and therefore not applicable on release branches.  We have *occasionally* made an exception to this rule, as per OMC decision / vote.

**Comment by h-vetinari** [comment]
> We have _occasionally_ made an exception to this rule, as per OMC decision / vote.

Recent example: https://github.com/openssl/openssl/pull/12369, see discussion there on how that was eventually resolved.
I think new architectures that need no adaptation of code (but can be implemented by just adding a config) should get a pass for maintenance branches (especially if the next release is still a while away).

**Comment by levitte** [comment]
I switch to the OMC decision label, to follow the example set by #12369, which @h-vetinari so kindly reminded us of.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
The vote has passed, this can be merged to 1.1.1.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Squashed the commits and merged to 1.1.1. Thank you for your contribution.

**Pull request closed without merging**
