### PR TITLE
WIP: Use valgrind instead of internal mdebug to check for memory leaks

### PR DESCRIPTION
**Pull request by levitte**
Related to #8322

### CODE REVIEW

**Comment by levitte** [comment]
Does anyone know of a similar tool for Windows that's available through appveyor?

**Comment by slontis** [comment]
How long will this take to run I wonder?

**Comment by levitte** [comment]
It turns out to be slow as a dog.  I think we're better off with #9294, if it can get sorted out cleanly enough.

**Comment by levitte** [comment]
Using valgrind has turned out to be slow as a sluggish snail.  Not a good idea, so I'm killing this.

**Pull request closed without merging**
