### PR TITLE
EVP_MD_CTX_[gs]ettable_params take wrong argument type.

### PR DESCRIPTION
**Pull request by paulidale**
They took an EVP_MD_CTX pointer and all the other equivalent functions for other
types accept an algorihtm pointer instead.

Digests also had EVP_MD_[gs]ettable_ctx_params function which worked the way the
EVP_MD_CTX_[gs]ettable_params should.

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Uhm, no, don't revert that change, it actually makes better sense

**Comment by levitte** [comment]
If you want to do something, align the other functions similarly

**Comment by paulidale** [comment]
Okay, I'll rework all the names to `EVP_XXX_[gs]ettable_ctx_params`.
I still want to delete the EVP_MD_CTX functions, I don't see a need for both.  Especially when they are implemented separately instead of in terms of one another.

**Comment by mattcaswell** [comment]
> I still want to delete the EVP_MD_CTX functions, I don't see a need for both. Especially when they are implemented separately instead of in terms of one another.

They are needed don't delete them! They are required by the EVP_DigestSign functionality

**Comment by mattcaswell** [comment]
There are scenarios where you have an active EVP_MD_CTX that can get and set parameters but there is no associated EVP_MD object available to the application. #10013.

**Comment by levitte** [comment]
Personally, I find that whole EVP_PKEY / EVP_MD API quite horrible, but revamping it with something completely new isn't a target for 3.0.  Maybe we could investigate that for 4.0?

**Comment by mattcaswell** [comment]
> Personally, I find that whole EVP_PKEY / EVP_MD API quite horrible, but revamping it with something completely new isn't a target for 3.0. Maybe we could investigate that for 4.0?

Yes, its a mess. EVP_DigestSign's misuse of EVP_MD_CTX is particularly horrible.

**Comment by paulidale** [comment]
Okay, I'll change the EVP_XXX_CTX_ versions to take a context and add the EVP_XXX_ versions that take the algorithm.

The continuance of the EVP_MD abuse was kind of disappointing.  I understand why.  Post 3.0 perhaps.

**Comment by paulidale** [comment]
I've slept on it and I'm unsure of the need for both flavours of the context gettables.

The original code is:

```C
const OSSL_PARAM *EVP_MD_gettable_ctx_params(const EVP_MD *md)
 {
    if (md != NULL && md->gettable_ctx_params != NULL)
         return md->gettable_ctx_params();
      return NULL;
}

const OSSL_PARAM *EVP_MD_CTX_gettable_params(EVP_MD_CTX *ctx)		
 {		
     if (ctx != NULL		
             && ctx->digest != NULL		
             && ctx->digest->gettable_ctx_params != NULL)		
         return ctx->digest->gettable_ctx_params();		
     return NULL;
}
```

The second function is, sans error checking, equivalent to:
```C
const OSSL_PARAM *EVP_MD_CTX_gettable_params(EVP_MD_CTX *ctx)		
{		
    return EVP_MD_gettable_ctx_params(ctx->digest);
}
```

Which is equivalent to a call of `EVP_MD_gettable_ctx_params(EVP_MD_CTX_md(ctx))`

It seems like only one of the flavours of the context gettable function is necessary (and that the name is incorrect for all other types).

Do we want both flavours still or just a naming fix up?

**Comment by levitte** [comment]
Arguably, `EVP_MD_CTX_gettable_params` is a convenience function, and there's really nothing wrong with having those per se.  I agree, though, that it should be rewritten in terms of `EVP_MD_gettable_params` (but do check that `ctx != NULL`!).

Either way, for asking the method (not its corresponding context), I would say that `EVP_MD_gettable_ctx_params` is less confusing than `EVP_MD_CTX_gettable_params`, because already established patterns...

**Comment by mattcaswell** [comment]
> I've slept on it and I'm unsure of the need for both flavours of the context gettables.

I disagree.

> Which is equivalent to a call of EVP_MD_gettable_ctx_params(EVP_MD_CTX_md(ctx))

Right now this is true. It won't be after #10013 is merged. As I said above there are scenarios where you will be able to get and set parameters on an active EVP_MD_CTX, but there is no available EVP_MD object (EVP_MD_CTX_md(ctx) will return NULL).

Please don't make any changes in this area until #10013 is in.

**Comment by levitte** [comment]
D'oh, forgot. Sorry

(might be a case of selective memory, that I *don't want* to remember the inner workings :wink:)

**Comment by paulidale** [comment]
@mattcaswell, okay the way forward would seem to be to align all the other types.

Is there a chance that this would be cleaned up at some point in the future?  If so, should we internalise the context based queries?

**Comment by paulidale** [comment]
Closing in favour of #10052 which renames all the other context gettable/settable function to match the naming here.

The `EVP_*_CTX_` functions also defined for MDs haven't been added yet.  Should they be public or not?

**Pull request closed without merging**
