### PR TITLE
RAND: ensure INT32_MAX is defined

### PR DESCRIPTION
**Pull request by levitte**
This value is used to set DRBG_MAX_LENGTH

### CODE REVIEW

**Comment by levitte** [comment]
Low hanging fruit!  ;-)

**Review by mspncp — APPROVED** [review]
> Low hanging fruit! ;-)

I'll bite! Hope, it's not poisoned...

**Comment by mspncp** [comment]
BTW: where was it missing? On VMS?

**Comment by levitte** [comment]
Yup, VMS...  and considering a recent report on openssl-users, I suspect older VC versions will have the same issue.

**Comment by levitte** [comment]
Most of all, stdint.h was introduced in C99, and considering we still support a minimum C89/C90, relying on those macros without our own hack is precarious.

**Comment by levitte** [comment]
Merged.

master:
f81b043ad856d8b9af5239a4978f8bd4b965dab9 RAND: ensure INT32_MAX is defined

1.1.1:
28361a0b821d36e3b19271b0a7909d5355b0990c RAND: ensure INT32_MAX is defined

**Pull request closed without merging**
