### PR TITLE
Add Windows VERSIONINFO resource to fips provider dll.

### LINKED ISSUE #18388: Windows FIPS provider lacks version information
In OpenSSL 3.0 and later, the fips.dll provider contains no version information.
Adding a few lines to `providers/build.info` creates the fips.rc, runs the resource compiler and attaches it to the DLL.
```
--- "openssl-master\\providers\\build.info"	2022-05-23 04:07:51.000000000 -0400
+++ "openssl-3.0.3\\providers\\build.info"	2022-05-23 17:51:57.079770500 -0400
@@ -118,6 +118,11 @@
   GENERATE[fipsmodule.cnf]=../util/mk-fipsmodule-cnf.pl \
           -module $(FIPSMODULE) -section_name fips_sect -key $(FIPSKEY)
   DEPEND[fipsmodule.cnf]=$FIPSGOAL
+
+  IF[{- $config{target} =~ /^(?:Cygwin|mingw|VC-|BC-)/ -}]
+    GENERATE[fips.rc]=../util/mkrc.pl fips
+    SOURCE[$FIPSGOAL]=fips.rc
+  ENDIF
 ENDIF
 
 #
```
A rebuild now has a fips.dll with the current version info it for versioning/installation.

### PR DESCRIPTION
**Pull request by slontis**
Fixes #18388

This just looks like an omission, as this is added to libcrypto and libssl

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
We also do not seem to generate the version info for legacy.so (if it is produced). That seems like an equivalent bug.

**Comment by levitte** [comment]
I can see why version info is relevant for shared libraries (that you link your program with on building), but for modules (that you load dynamicaly in runtime)? Not sure i get it...unless it's a packaging thing.

**Comment by beldmit** [comment]
If I remember correctly, it's at least good practice in Windows world.

**Comment by levitte** [comment]
Okie. But then, as @t8m says, this should be done with all modules we produce.... which also includes engines

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Pull request closed without merging**
