### PR TITLE
Revert "TEST: make and use a fipsinstall script"

### PR DESCRIPTION
**Pull request by levitte**
Unfortunately, this won't work on MacOS because of system integrity
measures on that platform, which clears DYLD_LIBRARY_PATH before
starting a sub-process executable.

Ref: https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html

This reverts commit ae6b654b669638882a6ddce012ff55adc7cf6a82.

### CODE REVIEW

**Comment by levitte** [comment]
Hmmm, shouldn't this be urgent?

**Comment by t8m** [comment]
It should.

**Comment by levitte** [comment]
I'll merge it later this afternoon

**Comment by paulidale** [comment]
Agreed, urgent.

**Comment by levitte** [comment]
Merged.

1e78a50f5a9d4874e910a3b42f10c176197aea88 Revert "TEST: make and use a fipsinstall script"

**Pull request closed without merging**
