### PR TITLE
Don't try the same decoder multiple times

### PR DESCRIPTION
**Pull request by mattcaswell**
The function collect_decoder decides whether a given decoder should be
tried or not. It loops through all the names for matching keymgmts to
see if any are a match or not. If there is a match then the decoder gets
added. However, each keymgmt may have multiple aliases and a decoder was
being added for each one. For example DHX has 4 alias names, and therefore
4 instances of the DHX decoder were added and being tried.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Empty squash commit pushed to fix a minor error in the commit message. No other changes.

**Review by t8m — APPROVED** [review]
Brilliant! That should definitely improve things a little on the decoder memory and CPU consumption.

**Review by levitte — APPROVED** [review]

**Comment by mattcaswell** [comment]
At @levitte's request I did some "before" and "after" comparisons to see how this impacts the decoder performance.

I applied this patch to the endecode_test to instrument the "decode" bits:

```` diff
From 39e54df5d503a384621dea28623c1772dc07391c Mon Sep 17 00:00:00 2001
From: Matt Caswell <matt@openssl.org>
Date: Fri, 21 May 2021 14:17:20 +0100
Subject: [PATCH] Instrument endecoder test

---
 test/endecode_test.c | 39 +++++++++++++++++++++++++++++++++++++++
 1 file changed, 39 insertions(+)

diff --git a/test/endecode_test.c b/test/endecode_test.c
index 9d0ebeb7e7..0bd18c19e6 100644
--- a/test/endecode_test.c
+++ b/test/endecode_test.c
@@ -8,6 +8,7 @@
  */
 
 #include <string.h>
+#include <time.h>
 #include <openssl/core_dispatch.h>
 #include <openssl/evp.h>
 #include <openssl/pem.h>
@@ -56,6 +57,30 @@ static OSSL_PARAM *ec_explicit_tri_params_explicit = NULL;
 # endif
 #endif
 
+struct timespec totalt;
+
+static void addtime(struct timespec *a, struct timespec b)
+{
+    a->tv_nsec += b.tv_nsec;
+    a->tv_sec += b.tv_sec;
+    if (a->tv_nsec >= 1000000000) {
+        a->tv_nsec -= 1000000000;
+        a->tv_sec++;
+    }
+}
+static struct timespec difftimespec(struct timespec a, struct timespec b)
+{
+    struct timespec temp;
+    if ((b.tv_nsec-a.tv_nsec)<0) {
+        temp.tv_sec = b.tv_sec-a.tv_sec-1;
+        temp.tv_nsec = 1000000000+b.tv_nsec-a.tv_nsec;
+    } else {
+        temp.tv_sec = b.tv_sec-a.tv_sec;
+        temp.tv_nsec = b.tv_nsec-a.tv_nsec;
+    }
+    return temp;
+}
+
 #ifndef OPENSSL_NO_KEYPARAMS
 static EVP_PKEY *make_template(const char *type, OSSL_PARAM *genparams)
 {
@@ -251,6 +276,9 @@ static int decode_EVP_PKEY_prov(const char *file, const int line,
     int ok = 0;
     int i;
     const char *badtype;
+    struct timespec start, end, difft;
+
+    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &start);
 
     if (strcmp(input_type, "DER") == 0)
         badtype = "PEM";
@@ -309,6 +337,13 @@ static int decode_EVP_PKEY_prov(const char *file, const int line,
     EVP_PKEY_free(testpkey);
     BIO_free(encoded_bio);
     OSSL_DECODER_CTX_free(dctx);
+
+    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &end);
+    difft = difftimespec(start, end);
+    addtime(&totalt, difft);
+
+    printf(" Sub-test time taken %ld s %09ld ns", difft.tv_sec, difft.tv_nsec);
+
     return ok;
 }
 
@@ -1326,11 +1361,15 @@ int setup_tests(void)
 # endif
     }
 
+    memset(&totalt, 0, sizeof(struct timespec));
     return 1;
 }
 
+
 void cleanup_tests(void)
 {
+    printf("Time taken %ld s %09ld ns", totalt.tv_sec, totalt.tv_nsec);
+
 #ifndef OPENSSL_NO_EC
     OSSL_PARAM_free(ec_explicit_prime_params_nc);
     OSSL_PARAM_free(ec_explicit_prime_params_explicit);
-- 
2.25.1
````
I then ran the test 5 times before the patch:

````
3 s 341650319 ns
3 s 055989335 ns
2 s 963098425 ns
3 s 177038477 ns
3 s 300566974 ns
Avg: 3.168s
````
And 5 times after the patch:
````
1 s 290877587
1 s 272791207
1 s 253170402
1 s 148444221
1 s 212075236
Avg: 1.235 s
````

So the performance improvement is about 2.5 times faster

**Comment by slontis** [comment]
> So the performance improvement is about 2.5 times faster

It makes debugging easier also :)

**Comment by mattcaswell** [comment]
Pushed. Thanks!

**Pull request closed without merging**
