### PR TITLE
* suggested patch for issue 13944

### LINKED ISSUE #13944: updatedb expires certificates with expiration date having 4-digit years before 2100.
In a private CA, I have some very long running certificates. In index.txt one of the expiration dates is 20730104163541Z meaning the certificate is valid until early 2073. If I run an updatedb command on this CA, this certificate is marked as "expired". I assume this is, because only the first two digits are interpreted as a year and this certificate therefore looks as if it would have been expired in 2020. I'm using openssl 1.1.1d.

### PR DESCRIPTION
**Pull request by arminfuerst**
CLA: trivial
Fixes #13944 
   - detect expiration dates after 2049-12-31
   - strip first two digits from expiration date if expiration date is after 2049-12-31
     to make compare with current date working again
This is my first PR for openssl - sorry for probably existing mistakes...

### CODE REVIEW

**Comment by arminfuerst** [comment]
CLA: trivial

**Comment by t8m** [comment]
This is unfortunately not within what is acceptable for CLA: trivial. Could you please submit an ICLA?

**Comment by arminfuerst** [comment]
> This is unfortunately not within what is acceptable for CLA: trivial. Could you please submit an ICLA?

The only way I found is to send a signed printout to <legal@opensslfoundation.org>.
(a) Is this correct?
(b) Is there a faster (pure digital?) way?

Thank you for your support!

**Comment by t8m** [comment]
IMO there is no pure digital way. @mattcaswell ?

**Comment by mattcaswell** [comment]
> IMO there is no pure digital way. @mattcaswell ?

We require a signed document. The signature can be a scan of your signature inserted into the document.

**Comment by t8m** [comment]
As for the patch - have you considered instead of trying to fix the bad y2k handling directly in the code, to actually use ASN1_TIME_set_string to parse the time from the DB and replace ASN1_UTCTIME with ASN1_TIME which should handle the y2k correctly by itself and then do the comparison of the ASN1_TIMEs. This should simplify the function much.

**Comment by arminfuerst** [comment]
> As for the patch - have you considered instead of trying to fix the bad y2k handling directly in the code, to actually use ASN1_TIME_set_string to parse the time from the DB and replace ASN1_UTCTIME with ASN1_TIME which should handle the y2k correctly by itself and then do the comparison of the ASN1_TIMEs. This should simplify the function much.

Thank you for your feedback. To be honest, I don't know all these data types by heart and I assumed, ASN1_TIME could cause issues with the timezone. I'll have a closer look at it when I find some spare time again.

I just sent the ICLA. Will this "automatically" fix the "cla-check" or do I have to set additional steps?

**Comment by t8m** [comment]
> I just sent the ICLA. Will this "automatically" fix the "cla-check" or do I have to set additional steps?

No additional steps needed for that on your side.

**Comment by mattcaswell** [comment]
Close/reopen to kick CLA bot

**Comment by arminfuerst** [comment]
I created an alternate suggestion using ASN1_TIME:
https://github.com/arminfuerst/openssl/commit/ec00b5ca7168cef55daba6ff2dbbcfecaf0ae779
Do you want to have a look at it first or shall I start a PR directly?

**Comment by t8m** [comment]
With the alternate proposal I meant using ASN1_TIME_set_string() for the time loaded from the database and  ASN1_TIME_compare() to compare it with the current time. I.e. dropping all the logic to handle y2k and compare the times from the apps code.

**Comment by arminfuerst** [comment]
Ok, thanks for the feedback :)

**Comment by arminfuerst** [comment]
I think that's what your idea was:
https://github.com/arminfuerst/openssl/commit/2790fe2d0355d7d47eb48c78f28d2b2b311ce12a

**Comment by t8m** [comment]
Closing in favour of #14026

**Pull request closed without merging**
