### PR TITLE
Code health: Remove unused aes_x86core.c

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
does @dot-asm need this for checking against his assembler stuff?

**Comment by dot-asm** [comment]
I'd prefer to keep it around. It's reference implementation used as template for some of assembly modules. Even though the module has x86 in its name, x86 in not the only platform that "stems" from this implementation...

**Comment by dot-asm** [comment]
On related note there is couple of similar files in poly1305, i.e. templates, also keepers...

**Comment by levitte** [comment]
Ok.  I did notice the comments about the similar poly1305 files being templates, would you mind adding a similar comment in aes_x86core.c, to make sure we're all clear on this?

Meanwhile, I'm closing this.

**Pull request closed without merging**
