### PR TITLE
Fix renegotiation with Client Auth (1.1.0)

### LINKED ISSUE #1920: OpenSSL 1.1.0 client can send Certificate message on renegotiation although not requested
As seen in https://bugzilla.redhat.com/show_bug.cgi?id=1393579 the openssl 1.1.0 client can send Certificate message although not requested with CertificateRequest on renegotiation. This is regression from 1.0.x.

In the handshake attached to the above Fedora bug you can see that the server requests a renegotiation where it sends CertificateRequest on which the client properly reacts with the Certificate message. Then the server immediately requests another renegotiation but this time without the CertificateRequest - the client in 1.1.0 incorrectly responds with Certificate message and the server (1.0.1) responds with fatal unexpected message alert.

### PR DESCRIPTION
**Pull request by mattcaswell**
##### Checklist

- [x] tests are added or updated
- [x] CLA is signed

##### Description of change

#1920 describes a problem where a non-client auth reneg handshake that occurs after a client-auth handshake will end up with the client sending a Certificate message when it is not supposed to.

There is another related bug where, in the same situation, the server expects a Certificate message even when it hasn't requested one!

These two bugs together mean that OpenSSL will happily talk to the same version of itself in this scenario, but nothing else.

In adding tests for this I found a third bug in the implementation of SSL_VERIFY_CLIENT_ONCE. The documentation for this flag says:
````
      B<Server mode:> only request a client certificate on the initial TLS/SSL
      handshake. Do not ask for a client certificate again in case of a
      renegotiation. This flag must be used together with SSL_VERIFY_PEER.
    
      B<Client mode:> ignored
````
But the implementation actually did nothing. After the server sends its
ServerKeyExchange message, the code was checking s->session->peer to see if
it is NULL. If it was set then it did not ask for another client
certificate. However s->session->peer will only be set in the event of a
resumption, but a ServerKeyExchange message is only sent in the event of a
full handshake (i.e. no resumption).
    
The documentation suggests that the original intention was for this to
have an effect on renegotiation, and resumption doesn't come into it.
    
The fix is to properly check for renegotiation, not whether there is already
a client certificate in the session.
    
As far as I can tell this has been broken for a *long* time. I actually wondered whether we would be better off just removing it. But as it turns out I need to use it for my tests to work so I fixed it anyway!!

I also fixed a bug in TLSProxy where zero length messages weren't being recorded properly.

This is the 1.1.0 version of #1982

Fixes #1920

### CODE REVIEW

**Comment by mattcaswell** [comment]
Updated this to have the same reneg test as #1982 for consistency reasons.

**Comment by levitte** [comment]
Is this still current?

**Comment by mattcaswell** [comment]
Yes - its still current.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
