### PR TITLE
crl: noout is not an output item

### LINKED ISSUE #15034: 3.0.0alpha15: "openssl crl -hash -noout" unexpected output format change
In 3.0.0alpha15 there is an unexpected output format change:

openssl crl -noout -hash -in /path/to/ca-bundle.crl
issuer name hash=fdd35eee

For 1.1.1k the format is:

openssl crl -noout -hash -in /path/to/crl/ca-bundle.crl
fdd35eee

I think that was supposed to get fixed by #14553, but that seems not to be enough.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #15034

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Rebased to fix trivial conflict in  test/recipes/25-test_crl.t

@mattcaswell @levitte Still OK?

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Yes

**Review by mattcaswell — APPROVED** [review]
Reconfirm

**Comment by t8m** [comment]
Merged to master now as I did not see a need to restart the 24hr waiting period.
Thank you for the reviews.

**Pull request closed without merging**
