### PR TITLE
Backport of PRs to 3.1 branch [batch 3]

### PR DESCRIPTION
**Pull request by t8m**
Third batch of backport commits to 3.1 branch.

Mostly clean cherry-picks only with minor conflict resolutions.

### CODE REVIEW

**Review by hlandau — APPROVED** [review]
Looks good.

This contains my libctx refactor and lhash stats deprecation.

**Review by levitte — APPROVED** [review]
Yup, looks good

**Comment by t8m** [comment]
Merging this now. Thank you for the reviews.

**Comment by t8m** [comment]
Merged to 3.1 branch.

**Pull request closed without merging**
