### PR TITLE
Downgrade also the download-artifact action

### PR DESCRIPTION
**Pull request by t8m**
It has to have the same version as upload-artifact.

### CODE REVIEW

**Comment by t8m** [comment]
This is a fix for https://github.com/openssl/openssl/actions/runs/8602356302

**Review by nhorman — APPROVED** [review]

**Comment by nhorman** [comment]
given our release timeline, should this be urgent?

**Comment by t8m** [comment]
> given our release timeline, should this be urgent?

Technically this is master branch only thing. So it does not really matter.

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master, 3.3 and 3.2 branches. Thank you for the reviews.

**Pull request closed without merging**
