### PR TITLE
Adapt workflows for security CI

### PR DESCRIPTION
**Pull request by quarckster**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by t8m — APPROVED** [review]
If this works, it is а really perfect solution!

**Comment by slontis** [comment]
Can you be a bit more transparent/verbose with your commit messages please.
i.e. What problem(s)  are you trying to solve by moving common platforms that work with Github actions to self hosted runners?

**Comment by quarckster** [comment]
> Can you be a bit more transparent/verbose with your commit messages please. i.e. What problem(s) are you trying to solve by moving common platforms that work with Github actions to self hosted runners?

OpenSSL has a mirror of this repository for security fixes staging and it's located on OpenSSL private instance of GitHub Enterprise Server. I want to replace Buildbot with GitHub Actions on that mirror. GHE cannot use github.com runners, so I submitted this PR to use appropriate runners depending on the URL of the GitHub server.

**Review by hlandau — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master, 3.2, 3.1, and 3.0 branches. Thank you.

**Pull request closed without merging**
