### PR TITLE
Improve doc of `x509 v3 set ctx()`

### PR DESCRIPTION
**Pull request by DDvO**
This has been carved out from #16998
such that these general doc improvements are made available earlier
and potential further merge conflicts are avoided for them.

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
This is not just a doc fix. The first commit should not be in this PR?

**Comment by DDvO** [comment]
Ah, this was because I had pushed that commit to the wrong `master` -
corrected this now, sorry for the confusion. Good you noticed this soon.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
> corrected this now, sorry for the confusion

It looks like the correction was somehow incorrect? :grin:

**Comment by DDvO** [comment]
Argh, somehow the reference head of this PR went wrong,
and so my yesterday's fix did not help.
What did help was to rebase on `upstream/master` and force-push.

**Comment by DDvO** [comment]
@t8m, how about restoring the **ready to merge**, now this is sorted out?

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
@DDvO restored

**Comment by DDvO** [comment]
Merged - thanks t8m for you patience with my branch handling mistake

**Comment by paulidale** [comment]
Close missed...

**Pull request closed without merging**
