### PR TITLE
1 0 1 stable standardize on dhe [rt.openssl.org #3203]

### PR DESCRIPTION
**Pull request by dkg**
Allow ECDHE and DHE as forward-compatible aliases for EECDH and EDH
    
    see RT #3203

Future versions of OpenSSL use the canonical terms "ECDHE" and "DHE"
as configuration strings and compilation constants.  This patch
introduces aliases so that the stable 1.0.1 branch can be
forward-compatible with code and configuration scripts that use the
normalized terms, while avoiding changing any library output for
stable users.

### CODE REVIEW

**Comment by kroeckx** [comment]
This isn't going to be merged in the stable branch.

**Comment by dkg** [comment]
On Fri 2015-05-22 19:06:01 -0400, Kurt Roeckx wrote:
 [ https://github.com/openssl/openssl/pull/168#issuecomment-104795754 ]
> This isn't going to be merged in the stable branch.

Can i ask why not?  Adding the DHE aliases to the stable branches would
mean that people can produce public documentation/recommendations using
the canonical forms of the names, and that documentation would work with
any maintained version of OpenSSL.

As it stands now, anyone producing documentation is likely to use the If
we want any OpenSSL-related documentation/recommendations to ever switch
over to using the canonical form of the names, supporting them in the
stable branches as inputs would be really useful.

(note that i'm not arguing for changing the outputs on the stable
branches)

       --dkg

**Comment by mattcaswell** [comment]
I am sceptical that that would be the case. In reality (IMO) it is likely to produce more confusion. What it introduces is differing functional behaviour between different letter versions of the *same* release. In addition, just because we introduce a particular patch into the latest version of a release it doesn't mean that all of the distros will follow suit and also incorporate that patch (and in fact as this would not be a security or bug fix patch I think it is quite likely that quite a few would not pick it up). Therefore in practice you still have to cater for all of the people that don't have that functionality (and worse you have to start qualifying it by saying "if you're on version 1.0.1n or above then you get x, otherwise with 1.0.1m or below you get y" - which I think is a lot more confusing message).

As a general principle I am opposed to introducing new functional behaviour within letter releases apart from in exceptional circumstances (such as to deal with a pressing security issue). The letter releases are intended to be for bug fixes only. This gives people certainty and stability. Even quite minor functional changes can have unexpected consequences and break things in unexpected ways. It is best, as much as possible, to avoid such issues altogether and not try to second guess what things will break stuff and what will not. We are under constant pressure to include new functional behaviour in existing releases (I was involved in a very similar conversation on another request earlier today). If we start to indulge that then we suddenly find ourselves doing active development on multiple branches...which is unsustainable.  Further we start making a  "rod for own back" by extending the attractiveness of out-dated releases, whereas actually we want to encourage people as much as possible to move to the latest versions.

In the 1.0.1 case this actually only has a limited lifespan anyway. General support for that will be finishing at the end of this year, with security fixes only for a further year after that. So the problem in this particular case should go away by itself within a foreseeable timespan.

**Comment by richsalz** [comment]
Two strong team opinions to close, and given the state of 1.0.1... closing.
And hey, @dkg , get a haircut dude :)

**Pull request closed without merging**
