### PR TITLE
Open ssl fips 2 0 stable

### PR DESCRIPTION
**Pull request by SteveMarquess**

### CODE REVIEW

**Comment by dot-asm** [comment]
Configure.orig appears to be patching artefact and shouldn't be here.

**Comment by dot-asm** [comment]
BTW, there is merge request[s] for OpenSSL-fips-2_0-dev in internal review system. It's broken in several logical commits. If we are to follow procedure we exercise normally in non-fips case, it would first have to go to dev and then cherry-picked to stable. But with this at hand, do we go other way around? I.e. cherry-pick to dev? Basically my question is do I simply omit merge request in internal system?

**Comment by SteveMarquess** [comment]
On 02/16/2017 09:59 AM, Andy Polyakov wrote:
> Configure.orig appears to be patching artefact and shouldn't be here.

Hmmm. Puzzled am I; all I did was apply your patch (3420.diff) to a
virgin clone. But indeed that patch has only 15 files and the pull
request has 17 (the other file being fips/fipsalgtest.pl from the
November commit).

I'll do it again and try and see where I went wrong...

-Steve M.

-- 
Steve Marquess
OpenSSL Validation Services, Inc.
1829 Mount Ephraim Road
Adamstown, MD  21710
USA
+1 301 874 2571
marquess@openssl.com
gpg/pgp key: http://openssl.com/docs/0x6D1892F5.asc

**Comment by SteveMarquess** [comment]
On 02/16/2017 10:08 AM, Andy Polyakov wrote:
> BTW, there is merge request[s] for OpenSSL-fips-2_0-dev in internal
> review system. It's broken in several logical commits. If we are to
> follow procedure we exercise normally in non-fips case, it would first
> have to go to dev and then cherry-picked to stable. But with this at
> hand, do we go other way around? I.e. cherry-pick to dev? Basically my
> question is do I simply omit merge request in internal system?
> 

Good question; I'll defer to DrH.

The FIPS module is bass-ackwards in the sense that the tarball (now
generated from mkfipstar.pl) has to match the hand-jammed patch that was
used for the formal testing (in this case, the 3420.diff file). Put
another way, whatever mistakes I make in that process we're stuck with
for that tagged release in -stable.

In order to include anything from -dev in an official tarball, I need to
have the foresight to include the corresponding patch in whatever is
used for the official testing.

For 2.0.15 I used just 3420.diff plus the old fipstest.pl change, so
we're stuck with that for whatever we tag as 2.0.15 (if we want it to
match the official tarball, which isn't a CMVP requirement but something
we want).

-Steve M.

-- 
Steve Marquess
OpenSSL Validation Services, Inc.
1829 Mount Ephraim Road
Adamstown, MD  21710
USA
+1 301 874 2571
marquess@openssl.com
gpg/pgp key: http://openssl.com/docs/0x6D1892F5.asc

**Comment by snhenson** [comment]
Yes we should have a PR for dev first in github. If it's in several logical commits so much the better. Then we cherry-pick the appropriate ones for the stable branch. Suggest we close this PR and start again.

**Comment by SteveMarquess** [comment]
On 02/16/2017 10:26 AM, Stephen Henson wrote:
> Yes we should have a PR for dev first in github. If it's in several
> logical commits so much the better. Then we cherry-pick the appropriate
> ones for the stable branch. Suggest we close this PR and start again.
> 

Side question: does the "reply+...@reply.github.com" go to both you and
Andy?

There are two logical commits here, the fipstest.pl patch (one file) and
Andy's c64 patch (16 files).

So what should I do? Commit both of those to -dev and do a pull request
for that in -dev?

Sounds like I should also close the original PR ... will try to figure
that out (as I'm sure you can tell I'm in over my head here; need to
learn it though).

-Steve M.


-- 
Steve Marquess
OpenSSL Validation Services, Inc.
1829 Mount Ephraim Road
Adamstown, MD  21710
USA
+1 301 874 2571
marquess@openssl.com
gpg/pgp key: http://openssl.com/docs/0x6D1892F5.asc

**Pull request closed without merging**
