### PR TITLE
fips: remove P-192

### PR DESCRIPTION
**Pull request by xnox**
In recent NIST standards P-192 now has legacy status for verification only, remove it from FIPS module.

Note, I don't believe it ever was popular. Thus I'm not sure it is needed to support "verification-only" mode of P-192 in the FIPS module.

Related: 24193

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
I don't think we can remove this outright.
It's pretty much guaranteed that someone will be using it :cry:

**Comment by xnox** [comment]
> I don't think we can remove this outright.
> It's pretty much guaranteed that someone will be using it :cry: 

It will still be available in regular builds, just not in FIPS provider.

The other approach is to patch security checks to allow it for just verification.

But that still is the same net result that somebody is using it and will be broken. Or add indicators.... But that's also questionable, as most software doesn't actually check for those.

I mean. Transition to 128bit requirements from 2030 will be fun.

**Comment by paulidale** [comment]
> The other approach is to patch security checks to allow it for just verification.

Yes to this.  But we also require a bypass mechanism that uses explicit indicators.
It's still being thrashed out.

**Comment by t8m** [comment]
**OTC: This cannot be a hard removal. It will need an indicator implemented as in the indicators requirements PR.**

Indicator requirements PR: https://github.com/openssl/openssl/pull/23609

**Comment by xnox** [comment]
> **OTC: This cannot be a hard removal. It will need an indicator implemented as in the indicators requirements PR.**
> 
> Indicator requirements PR: #23609

Ack. I'm not interested to implement an indicator though. Would a compile time option be acceptable with an implicit indicator? I.e. `./Configure no-p192` ?

**Comment by t8m** [comment]
> > **OTC: This cannot be a hard removal. It will need an indicator implemented as in the indicators requirements PR.**
> > Indicator requirements PR: #23609
> 
> Ack. I'm not interested to implement an indicator though. Would a compile time option be acceptable with an implicit indicator? I.e. `./Configure no-p192` ?

I think it would have to be something more general than just for this particular curve. Also it should have fips in the name as it would be really awkward to remove just this curve. Or... maybe what about `no-weak-ec-curves` ? Then it could be a removal of all weak (less than 255) bit curves from both fips and default providers.

**Comment by xnox** [comment]
> > > **OTC: This cannot be a hard removal. It will need an indicator implemented as in the indicators requirements PR.**
> > > Indicator requirements PR: #23609
> > 
> > 
> > Ack. I'm not interested to implement an indicator though. Would a compile time option be acceptable with an implicit indicator? I.e. `./Configure no-p192` ?
> 
> I think it would have to be something more general than just for this particular curve. Also it should have fips in the name as it would be really awkward to remove just this curve. Or... maybe what about `no-weak-ec-curves` ? Then it could be a removal of all weak (less than 255) bit curves from both fips and default providers.

ACK.

We will sort of have an impeding 128bit transition too. Which will sort of be either raising security level; or checking all the security bits. Because that would allow to drop SHA1 (haha) SHA2-224 (easy) SHA3-224 (trivial) P-192 and so on.

**Comment by slontis** [comment]
@xnox I am going thru the list of items related to FIPS indicators in https://github.com/openssl/openssl/issues/24849.
Do you want to add indicators to this PR, or are you happy for me to just start a new PR?

**Comment by slontis** [comment]
It looks like this will already work at the operation level since it calls ossl_fips_ind_ec_key_check() which will check for <112 bits already.

**Comment by slontis** [comment]
I will need to check the keygen also..

**Comment by xnox** [comment]
@slontis I have not looked at indicators yet.

Also for my needs I still want to have it compiled out, without any runtime indicators.

But haven't yet decided if only offer to compile it out of fips provider, or offer to move these from default/fips to legacy provider.

**Comment by slontis** [comment]
Unfortunately shifting it out is not very easy. The EC keymanager works just on 'EC' currently. i.e. you dont 'fetch' the curve.
Until that is figured out, putting one or 2 curves in a seperate provider is not feasible :(

**Comment by slontis** [comment]
so the best option is going to be a config option currently

**Comment by slontis** [comment]
All EC operations in the OpenSSL FIPS provider already use the security-check to limit curves to >= 112 bits (except keygen)
https://github.com/openssl/openssl/pull/25008 adds this to EC keygen also.

If you want to do something here it would need to be a configure option that removes weak EC curves.

**Pull request closed without merging**
