### PR TITLE
ASN.1: Refuse to encode to DER if non-optional items are missing [1.1.1]

### LINKED ISSUE #16026: ASN.1 encoders produce zero content for non-optional items
`i2d_RSAPrivateKey()` will happily encode an `RSA` structure where only *n* and *e* are present, i.e. a public key.  The following program demonstrates it:

``` C
#include <stdio.h>

#include <openssl/bn.h>
#include <openssl/rsa.h>
#include <openssl/x509.h>

static int TEST(const char *expr, int b)
{
  if (b)
    return 1;
  fprintf(stderr, "Failed '%s'\n", expr);
  return 0;
}

#define TEST_true(e) TEST(#e " != 0", (e) != 0)
#define TEST_ptr(p) TEST(#p " != NULL", (p) != NULL)
#define TEST_int_le(a,b) TEST(#a " <= " #b, (a) <= (b))

int main()
{
  RSA *rsa = NULL;
  BIGNUM *n = NULL;
  BIGNUM *e = NULL;
  int ok = 0;

  if (!TEST_ptr(rsa = RSA_new())
      || !TEST_ptr(n = BN_new())
      || !TEST_true(BN_set_word(n, 123456))
      || !TEST_ptr(e = BN_new())
      || !TEST_true(BN_set_word(e, 0x10001))
      || !TEST_true(RSA_set0_key(rsa, n, e, NULL)))
    goto end;

  n = e = NULL;                /* They are now "owned" by |rsa| */

  /*
   * This SHOULD fail, as we're trying to encode a public key as a private
   * key.  The private key bits MUST be present for a proper RSAPrivateKey.
   */
  if (TEST_int_le(i2d_RSAPrivateKey_fp(stdout, rsa), 0))
    ok = 1;

 end:
  RSA_free(rsa);
  BN_free(n);
  BN_free(e);
  return !ok;             /* exit code 0 for ok == 1 and vice versa */
}
```

``` console
$ cc -o asn1-RSAPrivateKey asn1-RSAPrivateKey.c -lcrypto
$ ./asn1-RSAPrivateKey > foo.der
Failed 'i2d_RSAPrivateKey_fp(stdout, rsa) <= 0'
$ echo $?
1
$ openssl asn1parse -i -inform d -in foo.der
    0:d=0  hl=2 l=  13 cons: SEQUENCE          
    2:d=1  hl=2 l=   1 prim:  INTEGER           :00
    5:d=1  hl=2 l=   3 prim:  INTEGER           :01E240
   10:d=1  hl=2 l=   3 prim:  INTEGER           :010001
```

The ASN.1 structure (https://datatracker.ietf.org/doc/html/rfc8017#appendix-A.1.2) is this:

```
         RSAPrivateKey ::= SEQUENCE {
             version           Version,
             modulus           INTEGER,  -- n
             publicExponent    INTEGER,  -- e
             privateExponent   INTEGER,  -- d
             prime1            INTEGER,  -- p
             prime2            INTEGER,  -- q
             exponent1         INTEGER,  -- d mod (p-1)
             exponent2         INTEGER,  -- d mod (q-1)
             coefficient       INTEGER,  -- (inverse of q) mod p
             otherPrimeInfos   OtherPrimeInfos OPTIONAL
         }
```

This isn't specifically about RSA, it's deep in the ASN.1 encoder, where the code for primitives is a bit lax with regards to zero content...  it doesn't check if the item is optional or not.

### PR DESCRIPTION
**Pull request by levitte**
Fixes #16026

### CODE REVIEW

**Comment by levitte** [comment]
So much test failure...  what box did I open now, Pandora?

**Comment by levitte** [comment]
Corrresponding for 3.0 in #16036

**Comment by levitte** [comment]
Failures resolved.  I did the length check in the wrong spot...

**Review by t8m — APPROVED** [review]

**Comment by levitte** [comment]
Merged

12e9b74c513a8ed3c1c260cf25221a465ae14b84 TEST: Check that i2d refuses to encode non-optional items with no content
006906cddda37e24a66443199444ef4476697477 ASN.1: Refuse to encode to DER if non-optional items are missing
5434acb6c4d56507d761b28f7e142ccab808a8fa Fix test/asn1_encode_test.c to not use ASN1_FBOOLEAN
f1d97905bbd8679b7647c992b97f526791069040 Fix test/asn1_encode_test.c to handle encoding/decoding failure
ea26844c4f624ef515d9228d3b623761a369b049 make update (adds a new function code)

**Comment by kgold2** [comment]
This breaks an application using an ISO 11889 HSM.
I suggest, to avoid the regression, to add a new, more restrictive i2d_x509_xxx API, but leave the existing function as it currently works.  In general, I think it's better to add new APIs than to change the behavior of existing ones.

**Pull request closed without merging**
