### PR TITLE
QUIC RADIX: Fix simple_conn test

### PR DESCRIPTION
**Pull request by hlandau**
Not sure how this got through, but this fixes the CI failure on feature/quic-server.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by nhorman — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
(removing the committer-review-pending label as @nhorman has approved on our behalf)

**Comment by t8m** [comment]
This could be merged urgently as this is a CI fix, if @nhorman and @hlandau agree.

**Comment by nhorman** [comment]
Its certainly not going to break anything more than it currently is.  Concur we can do this urgently

**Review by paulidale — APPROVED** [review]
agree urgent

**Comment by hlandau** [comment]
Agreed

**Comment by t8m** [comment]
Merged, thank you.

**Pull request closed without merging**
