### PR TITLE
Don't flush the ClientHello if we're going to send early data

### LINKED ISSUE #4783: TLS 1.3 0-RTT doesn't work with TCP Fast Open
I tried to turn on TCP Fast Open upon TLS 1.3 0-RTT in an attempt to reduce connection startup latency even more. (Regular socket IO with TCP_FASTOPEN_CONNECT on kernel 4.11+.)

OpenSSL will flush the socket after ClientHello regardless of presence of early data. Linux's implementation of TCP Fast Open will only send the first write as the SYN packet. A second write (early data in this case) has to wait for the TCP 1-RTT handshake. Thus OpenSSL's 0-RTT and Linux's TCP Fast Open defeats each other.

(Selected is the early data.)

The setup: Nginx running on TLS 1.3 draft 21 reverse proxying to an HTTP server at `localhost:10080`. The loopback interface is set to have 1500 MTU and 100 ms delay on TLS ports. The client is `./openssl s_client -sess_in /tmp/s -alpn h2,http/1.1 -early_data /tmp/http.txt -connect 127.0.0.43:10443`. The early data is `GET / HTTP/1.0\r\n\r\n`. Tested with e44480cc26c9bdf4227d963d84ae271a1efaccd9.

The TLS draft doesn't seem to be concerned about the transport layer or require ClientHello and early data be sent as separate packets. I don't really know. Or is there some other reason for the flush after ClientHello?

> 4.1.2. Client Hello
> [...] After sending the ClientHello message, the client waits for a ServerHello or HelloRetryRequest message. If early data is in use, the client may transmit early application data (Section 2.3) while waiting for the next handshake message.

I was able to start a connection with both `Client Hello, Application Data` in a single SYN packet by hacking the state machine a little bit to skip the flush.

### PR DESCRIPTION
**Pull request by mattcaswell**
We'd like the first bit of early_data and the ClientHello to go in the
same TCP packet if at all possible to enable things like TCP Fast Open.
Also, if you're only going to send one block of early data then you also
don't need to worry about TCP_NODELAY.

Fixes #4783

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by klzgrad** [comment]
Tests OK with this diff (Linux kernel 4.13)
```diff
diff --git a/apps/s_socket.c b/apps/s_socket.c
index 2f3e90bbf9..cf48fc9039 100644
--- a/apps/s_socket.c
+++ b/apps/s_socket.c
@@ -91,6 +91,23 @@ int init_client(int *sock, const char *host, const char *port,
             continue;
         }
 
+        if (type == SOCK_STREAM) {
+            ret = BIO_set_tcp_ndelay(*sock, 1);
+            if (ret < 0) {
+                BIO_closesocket(*sock);
+                ERR_print_errors(bio_err);
+                return 0;
+            }
+            int opt = 1;
+            ret = setsockopt(*sock, IPPROTO_TCP, /*TCP_FASTOPEN_CONNECT*/30, (char *)&opt, sizeof(opt));
+            if (ret < 0) {
+                BIO_closesocket(*sock);
+                ERR_print_errors(bio_err);
+                return 0;
+            }
+            ret = 0;
+        }
+
 #ifndef OPENSSL_NO_SCTP
         if (protocol == IPPROTO_SCTP) {
             /*
```

Tested cases:

- TCP_NODELAY on, small early data (fits in SYN)
- TCP_NODELAY off, small early data (fits in SYN)
- TCP_NODELAY on, large early data (doesn't fit in SYN)
- TCP_NODELAY off, large early data (doesn't fit in SYN)

All works correctly for the HTTP payload.

**Comment by kroeckx** [comment]
How does this interact with your draft 22 PR?

**Comment by mattcaswell** [comment]
> How does this interact with your draft 22 PR?

Not well. I was going to hold off on this one until the draft-22 changes are in.

**Comment by sumasrao** [comment]
Is this change going to be merged soon? Does the server expect the application data to be in the same packet as Client hello? I am currently having problem with the latest openssl master where, the application data is sent out immediately after client hello but the when I call SSL_read_early_data, the server always reports error.
image

**Comment by kaduk** [comment]
I think Matt would need to do the non-trivial rebase now that the draft-22 PR has landed.

**Comment by mattcaswell** [comment]
I rebased this following the draft-22 code going in, updated the documentation and resolved the TODO in the code. This is now ready for review.

**Comment by mattcaswell** [comment]
Ping @openssl/committers

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
