### PR TITLE
apps/openssl: make index.txt errors more verbose

### PR DESCRIPTION
**Pull request by deejgregor**
This is a backport of #15360.

I do not have an executed CLA, but this was a clean cherry-pick from #15360, so I figure it isn't needed in this case because I am not actually contributing any new code.

### CODE REVIEW

**Comment by t8m** [comment]
Unfortunately this is a feature and so this is not acceptable for merging into the 1.1.1 branch.

**Comment by deejgregor** [comment]
@t8m I'd like to suggest that this is a bug fix not a feature. The lack of any diagnostic output in this failure mode can be fairly troublesome for users of OpenSSL's `ca` subcommand (and apparently also `ocsp` and `srp`). Here's some more detail from the first commit in the original issue, #15360:

```
If index.txt exists but has some problems (like for example a single \n character in it) openssl will just exit without any error message.

Bug at least expirienced twice: https://superuser.com/questions/1327848/openssl-ca-fails-after-password-without-error-message
```

For example, here's what we ran into trying to do signing operations (this is a simplified case... in the production case where we ran into this we're using hardware security keys, which made debugging this much more complex since we couldn't tell if the problem was in OpenSSL, OpenSC, or with the hardware security key we were using):

```
$ X509_KU=digitalSignature,keyEncipherment /usr/local/Cellar/openssl@1.1/1.1.1l_1/bin/openssl ca -batch -config openssl.cnf -out issued/development.api.pem -infiles issued/development.api.pem.csr
Using configuration from openssl.cnf
$
```

And to make matters worse, with no diagnostic output it's very difficult to find references to this specific problem online that would hint that index.txt could be the culprit. We ended up firing up a system call tracer (which is unfortunately non-trivial on macOS where we were using hardware security keys) to get us close enough to finding the cause of this problem. I'd love to prevent this problem from tripping up others using OpenSSL 1.1.x, as it's kind of a nasty one if you hit it (especially for someone like me who isn't a regular user of OpenSSL).

By comparison, with the changes in this PR, I get output telling me of what the problem is, broadly:
```
$ DYLD_LIBRARY_PATH=~/git/openssl _KU=digitalSignature,keyEncipherment ~/git/openssl/apps/openssl version
OpenSSL 1.1.1m-dev  xx XXX xxxx
$ DYLD_LIBRARY_PATH=~/git/openssl X509_KU=digitalSignature,keyEncipherment ~/git/openssl/apps/openssl ca -batch -config openssl.cnf -out issued/development.api.pem -infiles issued/development.api.pem.csr
Using configuration from openssl.cnf
Problem with index file: .//index.txt (could not load/parse file)
$
```

**Comment by paulidale** [comment]
Question for OTC: **feature or bug fix?**

**Comment by levitte** [comment]
I think this is a misplaced fix.  `load_index()` already has *some* error handling, and even prints the errors to `bio_err` at the end.  See for yourselves:

https://github.com/openssl/openssl/blob/c28bcc507be1b035237892181bbbb28383c3f2be/apps/apps.c#L1535-L1599

However, it does look quite incomplete and inconsistent.  The master branch is a bit more developed:
 
https://github.com/openssl/openssl/blob/f87b4c4ea67393c9269663ed40a7ea3463cc59d3/apps/lib/apps.c#L1610-L1672

So if it were me, I would update `load_index()` in 1.1.1.

I know that this doesn't answer the question @paulidale asks, and quite frankly, I'm undecided

**Comment by mattcaswell** [comment]
OTC: This is a feature not a bug fix and therefore not suitable for backport.

Closing.

**Pull request closed without merging**
