### PR TITLE
mkbuildinf.pl: improve reproducible builds

### PR DESCRIPTION
**Pull request by jurobystricky**
If the environment contains SOURCE_DATE_EPOCH, generate output such as:

 #define DATE "built on: reproducible build, date unspecified"

instead of the usual, such as:

 #define DATE "built on: Tue Oct 24 17:20:35 2017"

The message is consistent with other messages if SOURCE_DATE_EPOCH
is defined.

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
There's already an ifdef, OPENSSL_USE_BUILD_DATE, that is used in crypto/cversion.c, that does the same thing.

Thanks for the idea, tho.

**Comment by jurobystricky** [comment]
Yes, but quite the same. This script 'mkbuildinf.pl" generates the file crypto/buildinf.h. The date there ends up breaking reproducible build for openssl-dbg packages (or any package containing this file)

**Comment by richsalz** [comment]
Then it would be good if buildinf.h used the same ifdef style as crypto/cversion.c

**Comment by richsalz** [comment]
But is this really needed?  Reproducible builds tend to compare output, not sources, no?

If this is needed, you'll have to sign our CLA and get Intel to put you on their list.  Or put the text "CLA: trivial" in your commit text (not the title).

**Comment by jurobystricky** [comment]
open-embedded splits openssl into several packages, some of them are affected by the generated  buildinf.h file,
(I believe those are openssl-dbg and openssl-staticdev packages,  when I build them on different days, they differ. )
I will rework the patch along the lines you suggested.
Thanks

**Comment by kaduk** [comment]
@richsalz SOURCE_DATE_EPOCH is the de facto standard variable used by reproducible builds all over the place.  Need we really be a special snowflake in this regard?

**Comment by richsalz** [comment]
I did not know that.  It would be good to have this PR change openssl to use that.

My other question still stands:  is it necessary that buildinf.h NEVER CHANGE if the variable is set?

**Comment by kaduk** [comment]
The requirement is actually fairly weak: we need to be reproducible only when invoked with the same compiler and configuration flags on the same platform and the same source tree (i.e., git commit), on different hosts and at different times.  https://wiki.debian.org/ReproducibleBuilds/Howto does not even require that we are reproducible when built at a different path in the filesystem, though I don't know how universal that relaxation is.

**Comment by kaduk** [comment]
Rebased, and updated libcrypto.num to match the 1.1.0 target. (This is too late for 1.1.0g, of course.)

**Comment by levitte** [comment]
Doesn't this mean we can remove [the ifdef soup around the date in `cversion.c` too](https://github.com/openssl/openssl/blob/master/crypto/cversion.c#L24-L32)?

**Comment by richsalz** [comment]
See #4644

**Comment by lamby** [comment]
FYI there's no real reason to replace it with a string, ie:

```
use POSIX qw(strftime);
my $date = strftime("%Y-%m-%d", gmtime($ENV{SOURCE_DATE_EPOCH} || time));
```

:)

**Comment by richsalz** [comment]
That's nice, but I think the time is useful :)

**Comment by lamby** [comment]
> That's nice, but I think the time is useful :)

Oh sure, adjust the format to suit. I was only demonstrating that we don't need to replace the date with a string such as "reproducible build".

**Comment by richsalz** [comment]
Ah, I see.  I'm clearly a noob on this stuff, so I'll just be the typing-monkey and do whatever @kaduk @levitte @kroeckx tell me to type.
:)

**Comment by richsalz** [comment]
Fix merged to master, thanks!

**Comment by lamby** [comment]
Thanks all :)

**Pull request closed without merging**
