### PR TITLE
Remove ENGINE_load_dasync() (no OPENSSL_INIT_ENGINE_DASYNC already)

### PR DESCRIPTION
**Pull request by azat**
Fixes: 8d00e30f96fb86b20bc992f626b188c3548fc58c ("Don't try to init dasync internally")

### CODE REVIEW

**Comment by azat** [comment]
Cc: @levitte

**Comment by mattcaswell** [comment]
Technically this would be an API change if we backported this to 1.1.0...but as its broken in that branch and always has been, I'd be ok with its removal because no one can be using it anyway.

**Comment by mattcaswell** [comment]
I see no CLA for you on file, although I think this is a trivial change. @azat do you agree?

**Comment by azat** [comment]
@mattcaswell indeed, thanks!

**Comment by mattcaswell** [comment]
Ping. Still needs a second team review.

**Comment by mattcaswell** [comment]
@richsalz do you agree this is trivial?

**Comment by richsalz** [comment]
Yes.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
