### PR TITLE
make update

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master.

Do we need an issue raised to fix the `make update` checker?

**Comment by rsbeckerca** [comment]
I don't think this will have an impact on the NonStop builds, but I'm checking anyway.

**Comment by levitte** [comment]
> Do we need an issue raised to fix the `make update` checker?

Why? It already does its job properly, the only issue is when we have several merges going in at a quick pace, then we occasionally miss something. I don't see that as a biggie.

**Comment by paulidale** [comment]
@levitte thanks for the response.  I suspected as much but figured it was better to ask than not.

**Comment by levitte** [comment]
Thanks for merging it so quickly

**Pull request closed without merging**
