### PR TITLE
Rework partial packet handling once more

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Address the concern that commit c53c2fec raised differently.

The original direction of the traffic is encoded in bit 0
of the flight number.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Previously, I mean before I ruined the code, this loop looked like this:
```
     foreach my $record (@{$self->record_list}) {
-        #We only replay the records for the current flight
-        if ($record->flight != $self->flight) {
-            next;
-        }
         $packet .= $record->reconstruct_record();
     }
```

So this restores the original logic, just with the difference that if bi-directional
traffic crosses only unsent flights from the same direction are considered.
@dot-asm I hope you like it.

**Comment by dot-asm** [comment]
What I don't appreciate is that decision if packet is to be reconstructed is split. I mean this loop has if-then-skip and reconstruct_record has if-then-skip too. Would you consider passing $self->flight to reconstruct_record (instead of $server) and consolidating if-then-skip a sensible thing?

**Comment by bernd-edlinger** [comment]
easy, because $server is always ($flight & 1)

**Comment by bernd-edlinger** [comment]
Merged.  Thanks!

**Pull request closed without merging**
