### PR TITLE
CMP app: fix combination of -certout and -chainout with equal filename arg

### PR DESCRIPTION
**Pull request by DDvO**
When using the same filename argument with the `cmp` app options `-certout` and `-chainout`,
the file so far contains just the chain - the new cert is lost because it happens to get overwritten.
This is fixed here in a useful way without touching the API, namely by prepending the cert to its chain.
On this occasion also the documentation is improved.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by DDvO** [comment]
> Would it be hard to add a test?

I had already started thinking about that, 
and meanwhile have added a test each on successfully producing and using the combined output file.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
Ping @openssl/committers for 2nd review - 
it's not a big PR, just some 10-15 lines of new/changed code.

**Review by nhorman — APPROVED** [review]

**Comment by tmshort** [comment]
Merged into master, and cherry-picked into openssl-3.3. The cherry-pick to openssl-3.2 was non-trivial, so another PR will have to be opened @DDvO.

**Comment by DDvO** [comment]
> Merged into master, and cherry-picked into openssl-3.3. The cherry-pick to openssl-3.2 was non-trivial, so another PR will have to be opened @DDvO.

It turns out that this was a simple (whitespace-only) merge conflict, 
which could have been handled during `pick-to-branch`.

Anyway, here is the separate backporting PR: #24696.

**Pull request closed without merging**
