### PR TITLE
Remove inadvertently commited test binaries

### PR DESCRIPTION
**Pull request by kaduk**
Commit 201015ee4f38e5d216a7625282c6b8a395b680b7 added some binaries
from fuzz/* that were not part of the intended functionality; remove them.
(Only the 1.0.2 branch version of the commit was affected, probably due
to a smaller .gitignore on that branch.)

### CODE REVIEW

**Comment by tmshort** [comment]
Should bn_conf.h and dso_conf.h also be removed?

**Comment by kaduk** [comment]
> Should bn_conf.h and dso_conf.h also be removed?

good catch, yes, they should.

**Comment by FdaSilvaYY** [comment]
You may also complete the .gitignore.
When I switch my working copy from a compiled master to 1.0.2, a lot of untracked items appear.

**Comment by dot-asm** [comment]
I'll give it some time for .gitignore to appear, if not, I'll merge...

**Comment by tmshort** [comment]
> When I switch my working copy from a compiled master to 1.0.2, a lot of untracked items appear.

.gitignore is usually used for build artifacts, not for switching between branches. For instance apps/progs.h is a repository file in OpenSSL_1_1_0-stable, but a generated file in master.

**Comment by kaduk** [comment]
I'd rather do any .gitignore changes in a separate pull request.

**Comment by levitte** [comment]
When switching branches like that, it's *always* a good idea to do a `git clean -fd`

**Comment by dot-asm** [comment]
Merged. Thanks.

**Pull request closed without merging**
