### PR TITLE
Handle PBMAC1 with absent PBKDF2 PRF

### PR DESCRIPTION
**Pull request by ocheron**
In two locations I observed a NULL pointer deference when testing posible algorithm combinations with PBMAC1.
This simply replicates code present elsewhere that tests the condition.

Alternatively, SHA-1 could also be rejected (as advised in the RFC) but this is more general than the choice of PRF in PBKDF2 since it is currently accepted as HMAC too.

##### Checklist
- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
@ocheron where did you take the default value from? 

I'd better forbid the cases when pbkdf2_param->prf is NULL

**Comment by tomato42** [comment]
the default PRF is for PBKDF2 is specified in [RFC 8018](https://datatracker.ietf.org/doc/html/rfc8018#appendix-A.2):
```
   PBKDF2-params ::= SEQUENCE {
       salt CHOICE {
           specified OCTET STRING,
           otherSource AlgorithmIdentifier {{PBKDF2-SaltSources}}
       },
       iterationCount INTEGER (1..MAX),
       keyLength INTEGER (1..MAX) OPTIONAL,
       prf AlgorithmIdentifier {{PBKDF2-PRFs}} DEFAULT
       algid-hmacWithSHA1 }
```

The rfc9579 only prohibits omitted `keyLength` value, so, this change is fine.

**Review by tomato42 — APPROVED** [review]
LGTM

**Comment by tomato42** [comment]
(while it LGTM, we really should add a test case for it, and also it would be nice to have a test case to verify that MD5 is rejected)

**Comment by t8m** [comment]
I am afraid this is outside of what is acceptable with CLA: trivial. Would you be OK to sign a regular CLA? https://openssl-library.org/policies/cla/index.html

Also would you be willing to add a testcase?

**Comment by ocheron** [comment]
Added a test case for this.
@t8m I'll be sending the ICLA shortly.

**Comment by beldmit** [comment]
Disagree with trivial, will approve if CLA issue is resolved

**Review by tomato42 — APPROVED** [review]

**Comment by t8m** [comment]
We have a CLA now.

**Review by t8m — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM

**Review by shahsb — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master and 3.4 branches. Thank you for your contribution.

**Pull request closed without merging**
