### PR TITLE
Fix potential memory leaks with BN_to_ASN1_INTEGER

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This is a potential memory leak, does unfortunately not cherry-pick.

### CODE REVIEW

**Comment by mattcaswell** [comment]
Is this intended for the release?

**Comment by bernd-edlinger** [comment]
would be good, yes.

**Comment by mattcaswell** [comment]
Looks like this issue has been there a long while. I'd rather not pull in new PRs into the release without a good justification, so I'd prefer to wait until the repo is unfrozen for this one.

**Comment by bernd-edlinger** [comment]
okay, agreed.

**Comment by paulidale** [comment]
Agreed, not for the upcoming release.

**Comment by bernd-edlinger** [comment]
Merged to master as f28bc7d, and 1.1.1 as 515c728.  Thanks!

**Pull request closed without merging**
