### PR TITLE
Make OSSL_PARAM_BLD_push_BN{,_pad}() return an error on negative numbers

### LINKED ISSUE #17070: Negative bignum OSSL_PARAM_BLD incorrect after retrieval
Dear reader,

During some testing I ran into something that seems to me like an issue. Consider the following code:
```
BIGNUM* bn_in = BN_new();
BN_set_word(bn_in, 123);
BN_set_negative(bn_in, 1);
std::cout << "In: " << BN_bn2dec(bn_in) << "\n";

OSSL_PARAM_BLD* bld = OSSL_PARAM_BLD_new();
OSSL_PARAM_BLD_push_BN(bld, "test", bn_in);

OSSL_PARAM* params = OSSL_PARAM_BLD_to_param(bld);
OSSL_PARAM* param  = OSSL_PARAM_locate(params, "test");

BIGNUM* bn_out = NULL;
OSSL_PARAM_get_BN(param, &bn_out);
std::cout << "Out: " << BN_bn2dec(bn_out) << "\n";
```

This constructs a `OSSL_PARAM_BLD` with a negative bignum, creates the `OSSL_PARAM*` from that, retrieves the parameter and gets the bignum. I would expect both in and out to show "-123".

However, the output I get is:
```
In: -123
Out: 123
```
So the negative flag seems to be lost somewhere.

This was only during some testing; we don't actually need negative bignums in parameters at this moment. So this does not have a high priority.

Is this indeed an issue or unclear documentation, or am I missing something?

Thanks in advance!

Best regards,
SpoofedEx

### PR DESCRIPTION
**Pull request by levitte**
Adding documentation to that fact as well.

Fixes #17070

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
CI failure is relevant.

**Comment by levitte** [comment]
> CI failure is relevant.

Fixed

**Review by t8m — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by paulidale** [comment]
I think the non-negative restriction is far wider that just this.  BNs map to unsigned integers.  The signed integer type in theory supports long integers but there is zero supporting code for it.

By picking out the param builder as special in not supporting negative BNs, I worry that people will assume that the rest of OSSL_PARAM and friends do support it (since the fact that they don't is not consistently stated).

Can of wriggle strings opening.

**Comment by paulidale** [comment]
Putting a hold one this because we need to work out what we're doing.  Documenting just this individual problem isn't enough IMO.  Either we go the whole way and document all of the PARAMs calls to not support negative BNs or we start supporting them globally.

**Comment by levitte** [comment]
Something to note is that I wrote "currently" in the documentation.  I would very much like to support negative bignums in OSSL_PARAMs as well, but we made a conscious choice that nonnegative was good enough for our purposes for 3.0.

**Comment by levitte** [comment]
I added a note in `doc/man3//OSSL_PARAM_int.pod` as well

**Comment by paulidale** [comment]
It would be easy enough to support signed BNs.  The most difficult part would be writing meaningful test cases.

Well, once the integer/unsigned integer stuff is resolved.  A non-negative BN can be passed as either -- should automatic coercion happen?

There are more places in the documentation where notes need to be added.  OSSL_PARAM(3) and OSSL_PARAM_allocate_from_text(3) should note something.  There will be more...

**Comment by levitte** [comment]
> ... OSSL_PARAM(3) ... should note something.

There's actually no reason at that level.  This issue isn't about the OSSL_PARAM structure at all, it's about limitations in functions surrounding it.

**Comment by levitte** [comment]
> Well, once the integer/unsigned integer stuff is resolved. A non-negative BN can be passed as either -- should automatic coercion happen?

We already do that for small size integers (I assume you were thinking of what `general_set_int`, `general_get_int`, `general_set_uint` and `general_get_uint` do), I see no reason why the same thing shouldn't be done with BIGNUMs.

**Comment by mattcaswell** [comment]
Please can someone summarise the question that is being asked of OTC?

**Comment by levitte** [comment]
> OSSL_PARAM_allocate_from_text(3) should note something

Actually no...  it does try to support signed numbers of any size.
(... but, it has a bug in that support, as it doesn't check the resulting MSBit to see if that corresponds to the sign or not.  That's a *different* issue, though)

**Comment by levitte** [comment]
`OSSL_PARAM_allocate_from_text()` issue discovered through this discussion are tracked in #17103 (fix in #17104)

**Comment by paulidale** [comment]
OTC question: should we:
1. document negative BNs as not working in some places (this PR)
2. document negative BNs as not working everywhere
3. make negative BNs work sensibly (and as a feature can it be back ported to 3.0)

**Comment by mattcaswell** [comment]
OTC: Supporting negative bignums is a feature. This PR should not be held if there is disagreement on all locations where it should be documented.

**Comment by levitte** [comment]
Merged

master:
db65eabefe76e44818ff8bd19c68990e7dcc70d3 Make OSSL_PARAM_BLD_push_BN{,_pad}() return an error on negative numbers
b33fb68a3230b8fc87f6663212ac3ffae0b361c5 DOC: OSSL_PARAM_{set,get,construct}_BN() currently only supports nonnegative numbers

3.0:
b5a4f7f56fc8601c6aadd58a5e22ab1a1954ba5a Make OSSL_PARAM_BLD_push_BN{,_pad}() return an error on negative numbers
8100a59fed1c985a3307c97af12cc8794bd93069 DOC: OSSL_PARAM_{set,get,construct}_BN() currently only supports nonnegative numbers

**Pull request closed without merging**
