### PR TITLE
Refactor the code for 'openssl list'

### PR DESCRIPTION
**Pull request by levitte**
This is in preparation for further work with this command.  It currently displays nothing about provider implementations, but it should.  To make the list command more workable, I moved its code to apps/list.c, but then got into some trouble adapting things related to apps/progs.h, so some cleanup was needed.

I've changed things so `apps/progs.h` and `apps/progs.c` are generated with `make update` instead of during build.

### CODE REVIEW

**Comment by paulidale** [comment]
I was thinking about this yesterday.  I decided I should code something that converts an OSSL_ITEM array (as returned by the `_get_param_types` functions) and creates a OSSL_PARAM array to query them all.

**Comment by levitte** [comment]
CIs are happy now

**Comment by levitte** [comment]
We really should have all the `_set_param_types` and `_get_param_types` functions return an array of OSSL_PARAM as descriptors...

**Comment by paulidale** [comment]
> We really should have all the `_set_param_types` and `_get_param_types` functions return an array of OSSL_PARAM as descriptors...

If it is possible I agree completely.  The big issue with them as they stand now is the lack of sizes for the strings/BNs (I don't think this is insurmountable but it could be difficult).

There is a second issue which we're not seeing at present: who _owns_ the returned OSSL_PARAM array?  Consider the core querying a provider to see what values it can give.  The OSSL_PARAM array then needs to be passed back to the provider which returns the relevant values.  It then needs to be passed back again to be freed.  A _clone_ call might work to transfer ownership.  Likewise the array could be allocated by the core and passed into the query to be populated.  I've not thought this one through sufficiently yet.

**Comment by levitte** [comment]
We should really discuss the ins and outs of OSSL_PARAM as type descriptors elsewhere.  I'm about to put together a PR that gets into the details, see ya there?

**Comment by paulidale** [comment]
You'll see me there, just not this evening.  I'm too tired at the moment

I'd eventually like to see `param_type` queries on everything that supports OSSL_PARAMs to future proof against new families of algorithm (e.g. AEAD ciphers or XOF digests).

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

4b62b8ed4989bb6767a38ae813495ba62215c25b Refactor apps/progs.* to be generate with 'make update'
753149d97f8474ff8745a66175b8e4a19fe50743 Move the code for 'openssl list' to its own translation unit.
e3cbccc5bbe18930c1d98b64abb505aad221c18d Add a mechnism to save the name of fetched methods
c1798afbe37f9a98278050c3437b715c16ce0e2b Re-implement EVP_MD_name() and EVP_CIPHER_name() as functions
ed45c999114e412edbd0018c435ae91e06625358 Add EVP_MD_provider() and EVP_CIPHER_provider()
f4ae5ba4b7d07fc9df4acbb7741aea75a1c584b0 Add OSSL_PROVIDER_name()
7da6cc6ccb1035fdc14ab1fc54321ad30bca1e58 Add internal function ossl_algorithm_do_all()
148609c62734f2068303ffa90f4ff8004478337e Refactor ossl_method_construct() in terms of ossl_algorithm_do_all()
23e34aa213a2e8003092436ab6f5dae68283e698 Add internal function evp_generic_do_all()
9af71317f9e5708dada7c1a660d862741945c436 Add EVP_CIPHER_do_all_ex() and EVP_MD_do_all_ex()
b6c97eee78c9ab646137772497b65e99124970db Re-implement the cipher and digest listings for 'openssl list'

**Comment by levitte** [comment]
Oh damn, I mixed this up with #9356...

**Comment by levitte** [comment]
Mistake undone, #9356 back on track.

**Pull request closed without merging**
