### PR TITLE
travis: test linux-ppc64le for gcc-5/clang EXTENDED_TEST asan/ubsan

### PR DESCRIPTION
**Pull request by grooverdan**
CLA: trivial

### CODE REVIEW

**Comment by grooverdan** [comment]
I notice the extended tests are skipped on pull requests. Here are the tests passing:
gcc: https://travis-ci.org/grooverdan/openssl/jobs/374662464
clang: https://travis-ci.org/grooverdan/openssl/jobs/374662465

**Comment by dot-asm** [comment]
Oh! PPC image is ubuntu 16. Cool... For reference, you can add [extended tests] to commit message to engage them for individual pull request. So suggestion is to exercise asan+ubsan with two compilers. Note that in other cases sanitizer builds are done with no-asm. This is to maximize sanitizers's coverage since they instrument only C code. And there is no reason not to do so even on PPC. But it's still interesting to exercise asm build. In other words more tests? Well, maybe no-asm+asan+ubsan with gcc and strict-warnings with clang would be sufficient. And depending on how fast is the latter, maybe even omit EXTENDED_TEST="yes"...

**Comment by grooverdan** [comment]
extended tests on gcc no ~20min. bit bigger than the previous largest ~16mins however well under the Travis limit of 50mins.

clang Warray-bounds on `strcmp` is a bit odd. Might try a later clang version once https://github.com/travis-ci/travis-build/pull/1370 is pushed to travis production. Removing for now.

**Comment by dot-asm** [comment]
As already said I suggest even
```
        - os: linux-ppc64le
          sudo: false
          env: CONFIG_OPTS="--strict-warnings"
          compiler: clang
```
If it complains about strcmp, then add -Wno-array-bounds after --strict-warnings, for now. Even though there is value in checking sanitized builds with two different compilers, testing more different things has value too. I for one would value latter actually more...

**Comment by dot-asm** [comment]
It would also be appropriate to make the suggested extended test last in the list and insert non-extended test just before first extended test. It would be easier to navigate and one doesn't have to wait out non-running extended test to see that non-extended tests are all right.

**Comment by dot-asm** [comment]
It's not exactly what I meant by better navigation. Idea was rather to append new targets to non-extended and extended blocks as if they were less related. As opposite to adding both targets at the boundary between them. But all right, that would work too I suppose...

I'd rather suggest to omit -Wpedantic and declare last argument to poly1305_init as `void (*func[2])()`. But this could be matter for separate effort, to get rid of all -Wno-flags but -Wno-array-bounds. As for latter. One can wonder if it would be more appropriate to resolve in some other way. Because offending definition is external, it's in /usr/include/bits/string.h, and we would still appreciate warnings in *our* code. Judging from header file it should be possible to achieve this by adding -D__NO_STRING_INLINES. In other words could you replace -Wno-array-bounds with -D__NO_STRING_INLINES?

Note that you can always say "now you know there is linux-ppc64le, just fix it to your liking."

**Comment by grooverdan** [comment]
@dot-asm, I'm ok with providing a working example of linux-ppc64le travis jobs but as you implied I'd rather leave you to fix the warnings that I felt was obliged to highlight and then ignore for testing.

**Comment by dot-asm** [comment]
I've created #6192. I'm not going to address warnings there, as there is #6191, so it would be easier to remove additional -Wno-flags later on... Closing this, but feel free to chime in in the other request. Thanks for the suggestion!

**Pull request closed without merging**
