### PR TITLE
Use a function to generate do-not-edit comment

### PR DESCRIPTION
**Pull request by richsalz**
The final part of my refactoring command flags.
Getting the spacing right on the "do not edit" warning was a pain, so use a function to do it.
Also, because this is the end of the series :) I added a CHANGES entry.

### CODE REVIEW

**Comment by levitte** [comment]
I disagree with the addition of the do_not_edit function. It makes it unclear what's going when just looking in the .pod.in file.
Also, considering that the only difference between what the function outputs and what you had there explicitly is an empty line, I have a hard time understanding the note about spacing being difficult... 

The CHANGES entry should go in, though could that be an independent PR?

**Comment by richsalz** [comment]
Well, as the person who did all the pod.in editing, I got tripped up occasionally. :)
The point is that the pod.in is simple, and the output pod is correct.
I'll leave this up for a bit to see if anyone else has opinions.

**Comment by richsalz** [comment]
I decided I feel a bit more strongly that this is the *right* thing to do. :)  Right now, the .pod.in files look like this:
```
=pod

=begin comment
{- join("\n", @autowarntext) -}

=end comment

=head1 NAME
```

With this PR, they look like this:
```
=pod
{- &OpenSSL::safe::do_not_edit(); -}

=head1 NAME
```

I think it's pretty obvious that the second is better.  But I'm biased, and I *did* do all the templating stuff for the docs. :)

**Comment by richsalz** [comment]
Re-re-thinking, I don't feel so strongly. :)  I can see how the "do not edit" function name might be off-putting but don't think that is very important.

**Comment by paulidale** [comment]
How about renaming the function to _output_do_not_edit_header_ or similar?
I think that bringing repeated sequences together like this is a good thing.

**Comment by richsalz** [comment]
Rebased, pushed new version to change the name.

**Comment by levitte** [comment]
Abusive use of `&` detected.  Bad form, please don't.

**Comment by richsalz** [comment]
Abusive?  Maybe "legacy"  Whatever.  Revised commit pushed.

**Comment by levitte** [comment]
> Revised commit pushed.

Maybe do it for real? :wink:

**Comment by richsalz** [comment]
>Maybe do it for real?

Reality is over-rated :)  This time for real.

**Comment by richsalz** [comment]
Travis failure is a timeout, unrelated.

**Comment by richsalz** [comment]
This is ready for merge BTW.

**Comment by levitte** [comment]
Merged.

625c781dc76df145cfd30eeff7b6de7dfcc8afc7 Use a function to generate do-not-edit comment

**Comment by richsalz** [comment]
Thanks, at least now that typo-ridden branch name can go :)

**Pull request closed without merging**
