### PR TITLE
Fix Coverity CID:1453685 'unreachable code' in aes_xts code.

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Hmmm, does this mean we need to update at least one Travis job to detect this?  Although, I'm sure there are cases of dead code throughout our code, depending on configuration...

**Comment by slontis** [comment]
> Hmmm, does this mean we need to update at least one Travis job to detect this? Although, I'm sure there are cases of dead code throughout our code, depending on configuration...

Should be ok. The code in here is platform independant, so it will get there.

**Comment by kroeckx** [comment]
Why isn't any of the existing test picking this up?

**Comment by kroeckx** [comment]
I don't agree this is ready to merge. I would like to understand why the test suite didn't pick this up. Maybe it doesn't have any tests covering XTS? Then it would be a good time to add them.

**Comment by slontis** [comment]
> Maybe it doesn't have any tests covering XTS? Then it would be a good time to add them.

There are XTS tests in evp_test. (via evpciph.txt). The normal encrypt/decrypt update uses the cupdate method (which calls the cipher method).
The only way that the ccipher method can be called is through another mechanism via a call to EVP_Cipher()..
@mattcaswell is this actually a useful interface - if it is then it would need tests, because absolutely nothing hits this function currently.

**Comment by slontis** [comment]
I will update this PR to not also do the *outl = inl inside aes_ctx_stream_update since it is already done in aes_xts_cipher

**Comment by kroeckx** [comment]
I guess that makes sense, it would at least explain why the test suite passed. I assume that with the 2nd commit only the test suite failed?

**Comment by slontis** [comment]
Thanks for reviewing. Merged to master.

**Pull request closed without merging**
