### PR TITLE
New wishlist item

### PR DESCRIPTION
**Pull request by SteveMarquess**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t-j-h** [comment]
I think these items should just be github issues with a FIPS140 tag on them - we shouldn't be putting issue lists into the source tree ... then you can just have one URL which shows all the issues with the FIPS140 tag on them ... wouldn't that be a better solution to this context?

**Comment by mattcaswell** [comment]
I dislike having issues hanging around long term which we can't actually close. We should be aiming to reduce our issues lists, but these FIPS ones can't be closed. I think we need a list somewhere of all the known FIPS issues which we don't plan to fix which is not the github issues list. I don't mind too much whether it is held in the source tree or somewhere else.

**Comment by richsalz** [comment]
I raised the issue with Steve and Steve and they were going to review the issues and close the various FIPS ones, putting a link into the wishlist file.

**Comment by richsalz** [comment]
The new FIPS project will take a different approach.  Closing this.

**Pull request closed without merging**
