### PR TITLE
fix memory leak in dsa parameter check

### PR DESCRIPTION
**Pull request by jakkdu**
Missing BN_CTX_end & BN_CTX_free

### CODE REVIEW

**Comment by mattcaswell** [comment]
As far as I can tell this purely internal function is never called.

**Comment by richsalz** [comment]
So should we remove the function?

**Comment by jakkdu** [comment]
Yes. If you want to leave it then I think you need to fix this.
Otherwise, removing the function seems fine.

**Comment by richsalz** [comment]
i'll close this request, and maybe open a new one that removes the file?

**Comment by jakkdu** [comment]
Good. Thanka

**Comment by richsalz** [comment]
function was removed in 895ffe4.

**Pull request closed without merging**
