### PR TITLE
Configure: disable the 'makedepend' option by default

### PR DESCRIPTION
**Pull request by mspncp**
Creating dependency information is useful for developers to minimize
rebuilds while working on the code. Regular users however build and
install the OpenSSL binaries in one go from scratch using configure,
make, and make install. So they don't benefit from the dependency
information, creating it only slows down the build process.

_Related to https://github.com/openssl/openssl/issues/14994#issuecomment-826142427 and #14055._

### CODE REVIEW

**Comment by mspncp** [comment]
Commit 0b6358013938e41a4b50951567abdbcb3111acd7 was just cherry-picked from #13684 to avoid merge conflicts. It will be dropped before merging this pull request.

**Review by levitte — DISMISSED** [review]

**Comment by mspncp** [comment]
> @mspncp I'm having some doubts in hindsight.

@paulidale if your concerns were about disabling 'makedepend', please note that I gave a heads-up warning on the openssl-users mailing list: https://mta.openssl.org/pipermail/openssl-users/2021-April/013729.html

cc @richsalz @rsbeckerca

**Comment by richsalz** [comment]
Moving comment from wrong place: I think a concern is that someone edits a header file and then the right things don't recompile. I think it's better to spend a few moments and make sure future builds are right.

**Comment by levitte** [comment]
The discussion that followed my approval shows that we don't all quite agree, so I've dismissed my approval for now to allow discussion to continue without any sudden "surprise"

**Comment by paulidale** [comment]
@mspncp, I know you pre-warned us about this.  I needed to think things through with a clear head.

I'm concerned that it will cause problems as @richsalz notes.

I think that **any** debug build (regardless of the option(s) that trigger it) **must** do the make depend.  This includes: --debug, -ggdb, enable-.*san and likely others.  I don't think we can realistically catch all of them, so it is best to err towards always building the dependencies.

The big question is: _has anyone quantified how long make depend takes?_

We need to consider what is being saved versus what is being lost.  How much extra time is lost for the folks who only configure and build?  How much time is this costing the distros?  I _know_ that this will cause developers some degree of pain.

**Comment by mspncp** [comment]
Ok, does this mean that your concerns raised in https://github.com/openssl/openssl/pull/13684#issuecomment-828236906 are only about `no-makedepend` and that #13684 can be merged now?

**Comment by levitte** [comment]
> The big question is: _has anyone quantified how long make depend takes?_

This is platform dependent, of course.  On a Unix family platform with gcc or clang, a build makes very little difference.  Windows is different, since the compiler output forces us to make two runs per translation unit (one for the object file and one for `/showIncludes`), so having makedepend enabled there is likely to make a pretty big impact.

**Comment by mspncp** [comment]
> Windows is different, since the compiler output forces us to make two runs per translation unit (one for the object file and one for `/showIncludes`),

Maybe there is a more efficient way to collect the dependency information which doesn't require two compiler runs? (`/showIncludes` was never intended for this purpase, see my https://github.com/openssl/openssl/issues/14994#issuecomment-826388059.) After all, Visual Studio does support minimal rebuilds, even Edit&Continue.

**Comment by levitte** [comment]
> After all, Visual Studio does support minimal rebuilds, even Edit&Continue.

Yeah, I know...  but that's not available through the `cl` command line, is it?  I believe that using that requires using a VS project file and `msbuild`...  it can probably be done (it would require writing a VS project file template, that's a *major* undertaking), although I have no idea how we'd get proper perlasm builds in there...

**Comment by levitte** [comment]
I've been pondering adding `/showIncludes` in the command line that produces the object files, save stderr to file, and parsing that file for include file notes.  That would be doable if we know for sure that we can parse those lines out without fail.  It's possible that the regexp `/^[^:)]*: [^:)]*: (.*)$/` is sufficient, I haven't tested that (yet?)...  This would be VS only, so far (since Embarcadero only supports that in their C preprocessor, we have to make that a separate command).

**Comment by paulidale** [comment]
> Ok, does this mean that your concerns raised in [#13684 (comment)](https://github.com/openssl/openssl/pull/13684#issuecomment-828236906) are only about `no-makedepend` and that #13684 can be merged now?

I'm okay with no-fips as the default.  Most people won't want a FIPS build.  So yes, merge the no-fips build.

**Comment by t8m** [comment]
IMO the solution for long makedepend could be to just more prominently advertise the no-makedepend in the windows build instructions for users who do not rebuild. Of course with mentioning the consequences if you try to do change & rebuild.

**Comment by mspncp** [comment]
Since there are too many concerns about changing the default for the `makedepend` option, I decided to drop my pull request.

**Pull request closed without merging**
