### PR TITLE
Don't use EC curve type specific functions

### PR DESCRIPTION
**Pull request by mattcaswell**
Some EC functions exist in `*_GFp` and `*_GF2m` forms, in spite of the implementations between the two curve types being identical. This PR provides equivalent generic functions with the `*_GFp` and `*_GF2m` forms just calling the generic functions.

This also updates all internal use of these functions to use the generic forms, and marks the old functions as deprecated in 1.2.0.

This is an alternative fix for #6646 (previous alternative fix in #6753).

### CODE REVIEW

**Comment by romen** [comment]
I definitely believe this solution is "practically perfect[-er] in every way"!

**Comment by mattcaswell** [comment]
Does that make me Mary Poppins?

**Comment by mattcaswell** [comment]
Not that perfect though. The CIs don't like it. Fixup commit pushed.

**Comment by mattcaswell** [comment]
Travis red cross is not relevant.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by bbbrumley** [comment]
@mattcaswell Nice PR here! I like the progress.

Any thoughts on deprecating `ec_GFp_simple_set_Jprojective_coordinates_GFp` in 1.2.0? Along with the corresponding pointers in `EC_METHOD`. IMO the entire concept of a `Z` coordinate should be hidden -- what each `EC_METHOD` does internally is really it's own business.

**Comment by mattcaswell** [comment]
> Any thoughts on deprecating `EC_POINT_set_Jprojective_coordinates_GFp` in 1.2.0?

I'm generally supportive of this (although of course we don't know when 1.2.0 will eventually come along). It's probably not a priority right at this moment. This PR only happened because it resolved a 1.1.1 issue in the SM2 code. Once 1.1.1 is out of the door I'd be happy to look at PRs that did this.

**Pull request closed without merging**
