### PR TITLE
Miss BN_CTX_end() after getting number

### PR DESCRIPTION
**Pull request by PeiweiHu**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — COMMENTED** [review]
I don't think these are actual problems.  In each case the BN_CTX is created and freed within a single function.  There is no need to BN_CTX_end() when freeing it.

There is also no need to have the `use_ctx` flags, a NULL passed to BN_CTX_end() works fine.

Still, it would be good style to do so.

**Comment by PeiweiHu** [comment]
Thanks for your review. Agree that it's a style issue more than a bug. Both remove `BN_CTX_start()` and add `BN_CTX_end()` are reasonable. But it seems a little bit weird if there is a `BN_CTX_start()` but no `BN_CTX_end()`. 

IMO, `use_ctx` is useful except in `ossl_sm2_decrypt()`. In the rare case (theoretically), `BN_CTX_end()` will accept a non-NULL ctx, which is not passed to `BN_CTX_start()` before, for example, when `kG == NULL` in `sm2_sig_gen()`. Errors may occur because of the `BN_STACK_pop()` within `BN_CTX_end()`.

**Comment by kroeckx** [comment]
Move the BN_CTX_start() to just after the BN_CTX_new_ex()?

**Comment by PeiweiHu** [comment]
> Move the BN_CTX_start() to just after the BN_CTX_new_ex()?

BN_CTX_start() dereferenced ctx directly without checking null or not.

**Pull request closed without merging**
