### PR TITLE
Teach EVP_PKAY_HMAC keys how to EVP_PKEY_cmp()

### PR DESCRIPTION
**Pull request by npmccallum**
Fixes openssl/openssl#1236

### CODE REVIEW

**Comment by richsalz** [comment]
+1

**Comment by FdaSilvaYY** [comment]
s/EVP_PKAY_HMAC/EVP_PKEY_HMAC

**Comment by npmccallum** [comment]
@FdaSilvaYY Thanks, fixed.

**Comment by kroeckx** [comment]
+1

**Comment by richsalz** [comment]
commit 3b92e51  thanks!

**Pull request closed without merging**
