### PR TITLE
Revert non-trivial commits from wipedout@yandex.ru

### PR DESCRIPTION
**Pull request by paulidale**
Reverting commits that could be considered non-trivial.

The changes to pbe_crypt.c are security altering.

### CODE REVIEW

**Comment by richsalz** [comment]
In email, @snhenson suggested the following if test to check size limits in pbe_crypt.c  Can you add it, as a separate commit?
```
I think you get the same effect by just doing:

if (maxmem > SIZE_MAX)
	maxmem = SIZE_MAX;

Steve.
```

**Comment by richsalz** [comment]
Approved assuming you add that commit (and don't squash when merging)

**Comment by paulidale** [comment]
I wasn't planning on squashing, best to keep these nice and isolated.

**Comment by paulidale** [comment]
Test failure is unrelated.  Merged.

**Comment by dot-asm** [comment]
That's what I call missed opportunity. I mean if you don't do real git revert (not actually suggesting it), then why not have a closer look to improve readability? Among other things readability is defined by how many questions code rises. I mean less is better. Consider following

```
    if (strlen(ent->dir) == (size_t)len &&
        strncmp(ent->dir, ss, (unsigned int)len) == 0)
```
Why (size_t) cast in one case and (unsigned int) in another? Makes no sense, hence it's *less* readable. Another question is if cast is safe. I mean recall that signed to unsigned cast is formally implementation-defined so question is if there are provisions that ensure len's positivity? Yes, one can argue that it's totally unlikely to happen, but we are talking about readability and *formal* compliance. In other words it doesn't matter how unlike it is...

Even mentioned `if (maxmem > SIZE_MAX) maxmem = SIZE_MAX;` can be made more readable. With for example `if (sizeof(maxmem) > sizeof(size_t) && maxmem > SIZE_MAX)` so that instead of struggling with question *why* does one have to perform the check, one even sees the reason upfront.

**Comment by paulidale** [comment]
I didn't notice the size_t and unsigned casts, that was a straight undo of the old commit.  A new PR to fix these is here #4372

I did think about the sizeof comparison but was concerned about pedantic failures with a condition that's always false/true.  I think a comment might be a better approach: #4373

**Pull request closed without merging**
