### PR TITLE
Use armv8 .quad instead of .dword

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes https://github.com/openssl/openssl/issues/18454.

### CODE REVIEW

**Comment by dg0yt** [comment]
Amends https://github.com/openssl/openssl/pull/17951.

**Comment by dg0yt** [comment]
FTR I couldn't run any tests. I hope it is covered by CI.

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by mattcaswell** [comment]
This has only been labelled for master branch. Shouldn't we be backporting this to 3.1?

**Comment by dg0yt** [comment]
> This has only been labelled for master branch. Shouldn't we be backporting this to 3.1?

Wrong label? *This* PR is for branch openssl-3.1. #21939 is for master.

**Comment by mattcaswell** [comment]
> Wrong label? This PR is for branch openssl-3.1. https://github.com/openssl/openssl/pull/21939 is for master.

Right. Actually that's how I noticed the incorrect label (the label says master but the PR targets 3.1).

Changing the label now. @paulidale, @t8m - please reconfirm

**Comment by paulidale** [comment]
+1

**Comment by t8m** [comment]
Yeah, OK for 3.1 of course.

**Comment by t8m** [comment]
Merged to 3.1 branch. Thank you for your contribution.

**Pull request closed without merging**
