### PR TITLE
Update s_client doc adding xmpp as value for -starttls

### PR DESCRIPTION
**Pull request by radiocane**
Trivial contribution.
- [x ] documentation is added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
@radiocane you have to add "CLA: trivial" to your commit text (git commit --amend) and re-push.  I agree this is trivial.  Thank you!

**Comment by radiocane** [comment]
Better? I'm sorry I didn't check before :(

**Comment by richsalz** [comment]
Not a problem; thanks!  Ping committers

**Comment by dot-asm** [comment]
This doesn't apply to master, which has even more protocols. Yes, they are documented.

**Comment by richsalz** [comment]
Merged, thank you for the fix!

**Pull request closed without merging**
