### PR TITLE
Add -lib option to util/mkerr.pl

### PR DESCRIPTION
**Pull request by levitte**
Sometimes, one might only want to rework a subset of all the internal
error codes.  -lib allows the caller to specify exactly which sub-libs
to rewrite.

-----

I found this to be useful for the STORE project, when I wanted to rebuild only the STORE header files.

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
The -lib doesn't seem like the right name, since we mainly think of crypto and ssl as the libraries.  Don't have a good alternative tho.  -only or -just ?  And it can be repeated which is cute.

**Comment by levitte** [comment]
I was pondering `-module`...  we do talk about libcrypto modules a little now and then.  Wadday say?

**Comment by richsalz** [comment]
-module works for me.

**Comment by levitte** [comment]
Cool.  Rename pushed

**Comment by richsalz** [comment]
+1

**Comment by levitte** [comment]
Merged.  964ff301d6b50dabdb9daeb533f337e015f0419f

**Pull request closed without merging**
