### PR TITLE
Keep the externally visible macro BIO_FLAGS_UPLINK in bio.h

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Move definition of BIO_FLAGS_UPLINK completely to cryptlib.h

### CODE REVIEW

**Comment by levitte** [comment]
No.  `bio.h` defines a public API while `cryptlib.h` does not, so you're effectively removing that macro from the public API, which we only do in new major releases.

I suggest a cleanup PR for master, where your change is much more applicable, for 1.2.0.

-1 (please close)

**Comment by bernd-edlinger** [comment]
Oh....

The problem here is hopefully not in master/110 but only on 102.
I became aware of it by the build failure on #7300,
which means that bio.h defines BIO_FLAGS_UPLINK differently
when cryptlib.h was previously included  or not.

**Comment by levitte** [comment]
The exact same problem potentially exists in master: https://github.com/openssl/openssl/blob/master/include/openssl/bio.h#L159-L165

That macro *should* be removed from public APIs, I totally agree with that.  However, we cannot do that before the next major release.

**Comment by bernd-edlinger** [comment]
Worse than I thought...
Maybe it would it be better to move the definition completely to bio.h,
so it is defined at least correctly?

**Comment by bernd-edlinger** [comment]
Updated to follow #7311

**Pull request closed without merging**
