### PR TITLE
Fix compile errors when building with --api=1.1.0 no-deprecated.

### LINKED ISSUE #15963: [3.0.0-beta1] build fails for darwin64-x86_64-cc with no-deprecated option
I have another one: Configuring with
```
$ uname -a
Darwin opensslmacbuild01 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
$ cc --version
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ ./Configure darwin64-x86_64-cc --api=1.1.0 no-deprecated
Configuring OpenSSL version 3.0.0-beta1 for target darwin64-x86_64-cc
Using os-specific seed configuration
Creating configdata.pm
Running configdata.pm
Creating Makefile.in
Creating Makefile
```
[...]
Resulting in a configuration: 
[Configure-dump.txt](https://github.com/openssl/openssl/files/6741194/Configure-dump.txt)
Leads to ...
```
$ make
/Library/Developer/CommandLineTools/usr/bin/make depend && /Library/Developer/CommandLineTools/usr/bin/make _build_sw
[...]
cc  -Iinclude -Iapps/include  -arch x86_64 -O3 -Wall -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF test/pem_read_depr_test-bin-pem_read_depr_test.d.tmp -MT test/pem_read_depr_test-bin-pem_read_depr_test.o -c -o test/pem_read_depr_test-bin-pem_read_depr_test.o test/pem_read_depr_test.c
test/pem_read_depr_test.c:55:5: error: implicit declaration of function 'DH_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    DH_free(dh);
    ^
test/pem_read_depr_test.c:55:5: note: did you mean 'BN_free'?
include/openssl/bn.h:299:6: note: 'BN_free' declared here
void BN_free(BIGNUM *a);
     ^
test/pem_read_depr_test.c:76:5: error: implicit declaration of function 'DH_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    DH_free(dh);
    ^
test/pem_read_depr_test.c:99:5: error: implicit declaration of function 'DSA_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    DSA_free(dsa);
    ^
test/pem_read_depr_test.c:120:5: error: implicit declaration of function 'DSA_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    DSA_free(dsa);
    ^
test/pem_read_depr_test.c:141:5: error: implicit declaration of function 'DSA_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    DSA_free(dsa);
    ^
test/pem_read_depr_test.c:163:5: error: implicit declaration of function 'RSA_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    RSA_free(rsa);
    ^
test/pem_read_depr_test.c:184:5: error: implicit declaration of function 'RSA_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    RSA_free(rsa);
    ^
7 errors generated.
make[1]: *** [test/pem_read_depr_test-bin-pem_read_depr_test.o] Error 1
make: *** [build_sw] Error 2
```
It compiles without `no-deprecated` option.

### PR DESCRIPTION
**Pull request by slontis**
Fixes #15963

INSTALL.md uses these exact options as an example so it should work.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Tested using
````
>./Configure -Werror --strict-warnings --api=1.1.0 no-deprecated
````

**Comment by slontis** [comment]
@paulidale should we have a Github Action for this? (Probably not really necessary once it works)

**Review by paulidale — APPROVED** [review]

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
I don't think a new run just for this is worthwhile.  If it could be fitted into an existing run then okay.

**Comment by paulidale** [comment]
Merged.

**Pull request closed without merging**
