### PR TITLE
Fix a possible crash in dsa_builtin_paramgen2

### PR DESCRIPTION
**Pull request by bernd-edlinger**
This is found by code review.

Another example where BN_CTX_get error handling is not quite correct.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
Unfortunately there is zero test coverage for X931 RSA key generation.

**Comment by glengillman** [comment]
Hi All,


I've been reading a lot of documentation and trying to step my way through building OpenSSL.


I've gone through the steps, installed Active Perl, installed NASM, then read a statement that it wasn't recommended to use that.  I am trying to build as x86.  So I opened Visual Studio 2012 command prompt - then I did the following:


NOTE:  I'm running this on a Windows 7 machine


ran this from the folder where the OpenSSL files were downloaded    (the prefix is an empty folder where I expected the target files to be created):


c:\perl\bin\perl.exe Configure VC-WIN32 --prefix=D:\Code_TFS\Shared\Libraries\FreeRDP\Main\RawFiles\OpenSSL_Solution


I observed that a new file was created named "makefile"

instructions say to run "do_ms" in the "ms" folder - but there are no executables in that folder, so I couldn't perform this step


nmake -f makefile

this ran for a bit.  There were several warnings and then errors.

Here are the first set of errors:     It seems that they are trying to utilize "Windows Kits\8.0" - and it is complaining about errors using that.   Is this the correct version of windows kits that should be used?   Is there any information about this ?   or how to install and/or configure it to use a different version ?


        cl  /I "." /I "include" -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPE
NSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_PART_WORD
S -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DS
HA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -D
WHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM "-DENG
INESDIR=\"D:\\Code_TFS\\Shared\\Libraries\\FreeRDP\\Main\\RawFiles\\OpenSSL_Solu
tion\\lib\\engines-1_1\"" "-DOPENSSLDIR=\"C:\\Program Files (x86)\\Common Files\
\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_ME
AN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /O2 /Zi /Fdapp
 -c /Foapps\apps.obj "apps\apps.c"
apps.c
C:\Program Files (x86)\Windows Kits\8.0\include\um\windows.h(32) : warning C4067
: unexpected tokens following preprocessor directive - expected a newline
apps\apps.c(2027) : error C2065: 'DWORD' : undeclared identifier
apps\apps.c(2027) : error C2146: syntax error : missing ';' before identifier 'e
rr'
apps\apps.c(2027) : error C2065: 'err' : undeclared identifier
apps\apps.c(2028) : error C2143: syntax error : missing ';' before 'type'
apps\apps.c(2041) : warning C4013: 'MultiByteToWideChar' undefined; assuming ext
ern returning int
apps\apps.c(2041) : error C2065: 'CP_ACP' : undeclared identifier
apps\apps.c(2041) : error C2065: 'WCHAR' : undeclared identifier
apps\apps.c(2041) : error C2059: syntax error : ')'
apps\apps.c(2043) : warning C4552: '<' : operator has no effect; expected operat
or with side-effect
apps\apps.c(2043) : error C2143: syntax error : missing ';' before ')'
apps\apps.c(2046) : error C2065: 'CP_ACP' : undeclared identifier
apps\apps.c(2046) : error C2065: 'WCHAR' : undeclared identifier
apps\apps.c(2046) : error C2059: syntax error : ')'


Any help is much appreciated.

Thank you

Glen

**Comment by glengillman** [comment]
Hi All,

I've been reading a lot of documentation and trying to step my way through building OpenSSL.

I've gone through the steps, installed Active Perl, installed NASM, then read a statement that it wasn't recommended to use that.  I am trying to build as x86.  So I opened Visual Studio 2012 command prompt - then I did the following:

NOTE:  I'm running this on a Windows 7 machine

ran this from the folder where the OpenSSL files were downloaded    (the prefix is an empty folder where I expected the target files to be created):

c:\perl\bin\perl.exe Configure VC-WIN32 --prefix=D:\Code_TFS\Shared\Libraries\FreeRDP\Main\RawFiles\OpenSSL_Solution

I observed that a new file was created named "makefile"
instructions say to run "do_ms" in the "ms" folder - but there are no executables in that folder, so I couldn't perform this step

nmake -f makefile

this ran for a bit.  There were several warnings and then errors.   
Here are the first set of errors:     It seems that they are trying to utilize "Windows Kits\8.0" - and it is complaining about errors using that.   Is this the correct version of windows kits that should be used?   Is there any information about this ?   or how to install and/or configure it to use a different version ?


        cl  /I "." /I "include" -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPE
NSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_PART_WORD
S -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DS
HA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -D
WHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM "-DENG
INESDIR=\"D:\\Code_TFS\\Shared\\Libraries\\FreeRDP\\Main\\RawFiles\\OpenSSL_Solu
tion\\lib\\engines-1_1\"" "-DOPENSSLDIR=\"C:\\Program Files (x86)\\Common Files\
\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_ME
AN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /O2 /Zi /Fdapp
 -c /Foapps\apps.obj "apps\apps.c"
apps.c
C:\Program Files (x86)\Windows Kits\8.0\include\um\windows.h(32) : warning C4067
: unexpected tokens following preprocessor directive - expected a newline
apps\apps.c(2027) : error C2065: 'DWORD' : undeclared identifier
apps\apps.c(2027) : error C2146: syntax error : missing ';' before identifier 'e
rr'
apps\apps.c(2027) : error C2065: 'err' : undeclared identifier
apps\apps.c(2028) : error C2143: syntax error : missing ';' before 'type'
apps\apps.c(2041) : warning C4013: 'MultiByteToWideChar' undefined; assuming ext
ern returning int
apps\apps.c(2041) : error C2065: 'CP_ACP' : undeclared identifier
apps\apps.c(2041) : error C2065: 'WCHAR' : undeclared identifier
apps\apps.c(2041) : error C2059: syntax error : ')'
apps\apps.c(2043) : warning C4552: '<' : operator has no effect; expected operat
or with side-effect
apps\apps.c(2043) : error C2143: syntax error : missing ';' before ')'
apps\apps.c(2046) : error C2065: 'CP_ACP' : undeclared identifier
apps\apps.c(2046) : error C2065: 'WCHAR' : undeclared identifier
apps\apps.c(2046) : error C2059: syntax error : ')'


Any help is much appreciated.

Thank you

Glen

**Comment by kaduk** [comment]
> Hi All,
> I've been reading a lot of documentation and trying to step my way through building OpenSSL.
> I've gone through the steps, installed Active Perl, installed NASM, then read a statement that it wasn't recommended to use that. I am trying to build as x86. So I opened Visual Studio 2012 command prompt - then I did the following:

@glengillman you are hijacking an existing thread.  You should send mail to openssl-users@openssl.org instead.  When you do so, please specify which version of OpenSSL you are using, and what documentation you are using (e.g., a URL to the website in question).  I'm also curious where you read that NASM is not recommended, since as far as I know, nasm *is* recommended.

**Comment by bernd-edlinger** [comment]
Yes, all three branches (except the hunk in crypto/rsa/rsa_ossl.c which is only 1.1.0 & master)

**Comment by richsalz** [comment]
merged (except for x391g code) to all three branches.

**Pull request closed without merging**
