### PR TITLE
Simplify AppVeyor configuration

### PR DESCRIPTION
**Pull request by t8m**
Adjust the stuff we are building and testing in various
configurations to trim the run time a little bit.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
AppVeyor build running here: https://ci.appveyor.com/project/t8m/openssl/builds/38934285

**Review by paulidale — APPROVED** [review]

**Comment by h-vetinari** [comment]
Has the project considered migrating to Azure Pipelines for the appveyor jobs? That would not come without some work but should remove the last CI bottleneck.

**Comment by paulidale** [comment]
We're looking into GitHub actions as a replacement for AppVeyor and more.  However, this is a slow process since the fellows have lots of 3.0 commitments.

If a PR came along moving the AppVeyor builds to Azure Pipelines, or even adding Azure Pipelines jobs independently of AppVeyor, I think it would be considered favourably.

**Comment by paulidale** [comment]
Merged to master.

**Comment by h-vetinari** [comment]
> If a PR came along moving the AppVeyor builds to Azure Pipelines, or even adding Azure Pipelines jobs independently of AppVeyor, I think it would be considered favourably.

I think the problem with this is that Azure Pipelines would need some setup on the org-side and cannot be purely introduced as a PR.

**Comment by richsalz** [comment]
I introduced a project member to a MSFT contact.  Look at https://github.com/marketplace/azure-pipelines (among others).  A PR could do all the mechanics and then give the project a recipe to follow :)

**Pull request closed without merging**
