### PR TITLE
(Temporarily) don't download clang package

### PR DESCRIPTION
**Pull request by richsalz**

### CODE REVIEW

**Comment by ekasper** [comment]
Nope, still doesn't work - try removing the llvm sources as well?

**Comment by richsalz** [comment]
Done.

**Comment by FdaSilvaYY** [comment]
Check this : https://github.com/travis-ci/travis-ci/issues/6120

**Comment by richsalz** [comment]
Seems neat, but too hard for me to understand ☹

**Comment by ekasper** [comment]
Urrr. clang: error: unknown argument: '-fno-sanitize-recover=all' - this option comes from our config, but is wrong for the old clang (which needs '-fno-sanitize-recover' instead I think...). Switch ubsan builds to gcc-5?

Otherwise, seems to be working - builds are failing with real errors now :/

**Comment by ekasper** [comment]
@FdaSilvaYY - thanks for the pointer! But swapping compilers is a simpler hotfix for now.

**Comment by richsalz** [comment]
Pushed update to use gcc not clang ☹

**Comment by ekasper** [comment]
@richsalz bad indent I think.

Otherwise +1 (just check that the travis run starts successfully before you push - it'll bail fast if the yml is bad)

**Comment by richsalz** [comment]
Fixed the indent.  Pushing to master now.

**Comment by richsalz** [comment]
I think that I will leave this open as a reminder that we need to revert the commit, a15cfae

**Pull request closed without merging**
