### PR TITLE
Update fuzz/corpora submodule to latest data

### PR DESCRIPTION
**Pull request by t8m**
This should fix the recent CIFuzz regression

Urgent as CI fails otherwise.

### CODE REVIEW

**Comment by t8m** [comment]
Hmm... for some reason this does not fix the CIFuzz build. I assume this is because it uses the master checkout for fetching the fuzz corpus or something.

This PR is correct anyway.

**Review by hlandau — APPROVED** [review]

**Comment by hlandau** [comment]
OK with urgent.

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Ok with urgent

**Comment by t8m** [comment]
Merged to master branch. Thank you for the swift reviews.

**Pull request closed without merging**
