### PR TITLE
Fix broken links in crypto manpage

### PR DESCRIPTION
**Pull request by Lipovlan**
CLA: trivial

### CODE REVIEW

**Comment by Lipovlan** [comment]
I thought I was fixing broken links due to them looking out of place, but the corresponding pages do not exists. Closing this issue.

**Comment by Lipovlan** [comment]
I found out that the link name should have been different. I fixed that as well and reopened the pull request.

**Review by paulidale — APPROVED** [review]
Okay with trivial.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM. Okay with `cla: trivial`

**Comment by paulidale** [comment]
Merged, thanks for the fixes.

**Pull request closed without merging**
