### PR TITLE
chacha/asm/chacha-armv4.pl: optimize scalar code path for Cortex-A5/A7.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by zx2c4** [comment]
Looks like there might be a problem with unaligned inputs on ARMv6? Every second 16 bytes of the output appears to be wrong. I'm investigating more now...

(Also Lrot8 appears unused and its usage commented out?)

**Comment by dot-asm** [comment]
Oh! Apparently I fell victim to own misconception. I assumed that no-additional-compiler flags produces pre-ARMv7 code on my computer and tested linux-armv4 without additional flags and with -march=armv7-a. It ought to stem from fact that it was originally case, but then default has changed, and I ended up testing same thing twice:-( Now I have to test without additional flags and with -march=armv4... Meanwhile the problem is fixed. Thanks!!!

> (Also Lrot8 appears unused and its usage commented out?)

It's remnant of attempt to replace vshr-by-24+vsli-by-8 by pair of vtbl. There is commentary about why it failed around vperm(). Thing about experiments, even failed ones, is that they are supposed to be reproducible. That's the reason why it's left around commented out.

**Comment by zx2c4** [comment]
For the record, the names I'm generally using in the kernel (Zinc library) for these are `chacha20_arm` for the scalar and `chacha20_neon` for the vector. If you want, you can get rid of the BLOCK*3 (192) check, and I'll handle this from C (as I'm already doing).

**Comment by dot-asm** [comment]
> The NEON part of it is generally separated via a #ifdef CONFIG_KERNEL_MODE_NEON

Right, I was going to ask about that. I'm unclear on following. In other modules that are used in kernel there is no this #ifdef. Does it mean that code from those modules is dead without NEON configured? But whatever. More relevant question is where does the definition come from? This is for my education :-) Is it -include options that forces a header file without no #include directives?

**Comment by zx2c4** [comment]
Elsewhere in the crypto subsystem, scalar implementations are separated from NEON implementations and then the .S files themselves are conditionally selected by the build system. This doesn't gel well with how you like to have one calling into the middle sections of others, and anyways I'm redoing the way some things work with my [new Zinc library](https://git.kernel.org/pub/scm/linux/kernel/git/zx2c4/linux.git/tree/lib/zinc?h=jd/wireguard), so I think this is the better way anyway.

Indeed all kconfig symbols are included via `-include` at the command line.

**Comment by dot-asm** [comment]
> new Zinc library

The way it looks I might as well leave name re-definitions to integrator.... On related note I'm compelled to say that even though it works to open with local label (I refer to .Loop_outer), processor couldn't care less, but humans could appreciate non-local values, in profiler output. I'm not in position to tell you what to do, but why not leave script output as is (modulo symbol redefinition) and omit first ` .global ChaCha20_ctr32` directive? Yes, some would be dead, but customization would be minimal. In fact it can as well be two separate files... Again, just a side-note suggestion :-)

But here is another thing I recalled. In sha512-armv4 we have VFP_ABI_PUSH/POP that are defined empty in kernel. I.e. in kernel one doesn't need to off-load {d8-d15} upon call. I bet because no caller would use NEON but leaf assembly subroutines. Either way would it be appropriate to arrange same here?

**Comment by dot-asm** [comment]
Added kernel support for more modules.

**Comment by dot-asm** [comment]
Well?

**Comment by levitte** [comment]
Side note: @dot-asm, speaking of "Well?", please get in touch.

**Comment by zx2c4** [comment]
The only things that are missing are the `CONFIG_KERNEL_MODE_NEON` stuff -- but I understand if you don't want to add that, since it's really quite project specific -- and the base 2^26->2^64 conversion stuff happening in the top of the scalar functions when is_base_2_26 is true. (It'd be nice to have this for x86 too, even if it's too cumbersome to try to integrate all the kernel changes from that into here at the moment.)

**Comment by zx2c4** [comment]
I've got this all nicely integrated now. Sorry for the delay, and thanks for working on this. In the process, I did find a few oversights that you'll want to fix up before merging this:

```diff
--- a/src/crypto/zinc/chacha20/chacha20-arm64.perlasm
+++ b/src/crypto/zinc/chacha20/chacha20-arm64.perlasm
@@ -386,6 +386,10 @@ my ($a,$b,$c,$d,$t)=@_;
 
 $code.=<<___;
 
+#ifdef __KERNEL__
+.globl  ChaCha20_neon
+.type   ChaCha20_neon,%function
+#endif
 .type  ChaCha20_neon,%function
 .align 5
 ChaCha20_neon:

--- a/src/crypto/zinc/poly1305/poly1305-arm64.perlasm
+++ b/src/crypto/zinc/poly1305/poly1305-arm64.perlasm
@@ -57,6 +57,10 @@ $code.=<<___;
 #ifndef        __KERNEL__
 # include "arm_arch.h"
 .extern        OPENSSL_armcap_P
+#else
+# define poly1305_init   poly1305_init_arm
+# define poly1305_blocks poly1305_blocks_arm
+# define poly1305_emit   poly1305_emit_arm
 #endif

@@ -933,19 +937,21 @@ poly1305_emit_neon:
 .align 5
 .Lzeros:
 .long  0,0,0,0,0,0,0,0
+#ifndef __KERNEL__
 .LOPENSSL_armcap_P:
 #ifdef __ILP32__
 .long  OPENSSL_armcap_P-.
 #else
 .quad  OPENSSL_armcap_P-.
 #endif
+#endif

diff --git a/src/crypto/zinc/poly1305/poly1305-mips64.perlasm b/src/crypto/zinc/poly1305/poly1305-mips64.perlasm
index 1faabbd..d30a03d 100644
--- a/src/crypto/zinc/poly1305/poly1305-mips64.perlasm
+++ b/src/crypto/zinc/poly1305/poly1305-mips64.perlasm
@@ -55,7 +55,7 @@
 #
 ######################################################################

-$flavour = shift || "o32"; # supported flavours are o32,n32,64,nubi32,nubi64
+$flavour = shift || "64"; # supported flavours are o32,n32,64,nubi32,nubi64

 die "MIPS64 only" unless ($flavour =~ /64|n32/i);

@@ -66,8 +66,8 @@ $SAVED_REGS_MASK = ($flavour =~ /nubi/i) ? "0x0003f000" : "0x00030000";
 ($in0,$in1,$tmp0,$tmp1,$tmp2,$tmp3,$tmp4) = ($a4,$a5,$a6,$a7,$at,$t0,$t1);

 $code.=<<___;
-#if (defined(_MIPS_ARCH_MIPS64R3) || defined(_MIPS_ARCH_MIPS64R5) || \
-     defined(_MIPS_ARCH_MIPS64R6)) \
+#if (defined(_MIPS_ARCH_MIPS64R3) || defined(_MIPS_ARCH_MIPS64R5) || \\
+     defined(_MIPS_ARCH_MIPS64R6)) \\
      && !defined(_MIPS_ARCH_MIPS64R2)
 # define _MIPS_ARCH_MIPS64R2
 #endif
```

**Comment by mattcaswell** [comment]
I'm wondering why this has been closed?

**Pull request closed without merging**
