### PR TITLE
fuzz/test-corpus: check if PATH_MAX is already defined

### PR DESCRIPTION
**Pull request by Biswa96**
##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by Biswa96** [comment]
How can I sign the CLA? I have no printer or software to fill the form. Anyone here?

**Comment by t8m** [comment]
Another option as this would be a change eligible for CLA: trivial would be to amend the commit message by adding `CLA: trivial` on a separate line.

**Comment by Biswa96** [comment]
Done.

**Review by t8m — APPROVED** [review]
LGTM. And I agree this is trivial.

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by beldmit** [comment]
Merged. Thanks!

**Pull request closed without merging**
