### PR TITLE
.travis.yml: make package pulls conditional.

### PR DESCRIPTION
**Pull request by dot-asm**
This is 1.1.0-specific partial pick from #2292.

### CODE REVIEW

**Comment by levitte** [comment]
Side note: The no-stdio made me think, do we have anything that tries out the applink stuff? Would it be worth looking into a test if not?

**Comment by levitte** [comment]
(noticed typo fixes, consider this a re-confirmation)

**Comment by dot-asm** [comment]
There was syntax error in .travis.yml, missing space[!] in line 102 (even though it said it's line 100 that broken!). So you guys have to reconfirm. But at least let's wait if travis finds more problems. I mean at least it's doing progress now, but would it manage to complete?

**Comment by dot-asm** [comment]
> The no-stdio made me think, do we have anything that tries out the applink stuff?

Applink stuff is designed in such way that it remains disengaged if everything is compiled with same compiler. In other words it's problematic to test. Well, as was discussed in #2404, VS2015 might use applink even if everything is compiled with same compiler, but test suite doesn't use calls that would require applink. Do you mean that one would write separate test for that?

**Comment by levitte** [comment]
> Do you mean that one would write separate test for that?

Something like that, yes

**Comment by dot-asm** [comment]
Red cross is unrelated. It's from appveyor and because I've cancelled the build myself.

**Pull request closed without merging**
