### PR TITLE
Fix faulty include

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
wonder why it builds on my system?

**Comment by levitte** [comment]
> wonder why it builds on my system?

Because there's a `-I` for the top source directory (to be able to include `e_os.h`).

**Comment by levitte** [comment]
Merged.  f2766f753ef72dd1b0cfae9bd3b54b18795a49e4

**Comment by tmshort** [comment]
This commit made things worse; builds fail miserably. There are three header files named rand.h. Which one do you really want?

```
~/git/openssl (master=)$ find . -name rand.h
./crypto/include/internal/rand.h
./include/openssl/rand.h
./include/internal/rand.h
~/git/openssl (master=)$ 
```

**Comment by tmshort** [comment]
I'm guessing the intent was:

`#include <internal/rand.h` ?

**Comment by tmshort** [comment]
Nope, that doesn't fix it.

**Comment by richsalz** [comment]
Does #3975 fix it?

**Pull request closed without merging**
