### PR TITLE
More zalloc: fix default initialisation of some allocated objects (1.0.2 backport)

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
Backport of GH #997 to 1.0.2 branch.

### CODE REVIEW

**Comment by richsalz** [comment]
+1

**Comment by mattcaswell** [comment]
Looks ok, but I can't find the referenced backport commit in the repo. Has it been committed already under a different hash value?

**Comment by mattcaswell** [comment]
Oh...I see...this is #997...then in that case the commit message will need to be updated when #997 goes in.

**Comment by FdaSilvaYY** [comment]
Yes, you are right. 
The commit-SHA1-id will changed, once you append your "Reviewed by ..." mentions.

**Comment by mattcaswell** [comment]
Ok, so I +1 this subject to #997 being approved first and the commit message being updated to reflect the real hash.

**Comment by FdaSilvaYY** [comment]
Commits reference was updated.
Travis is green, so this one is ready for merge.

**Comment by richsalz** [comment]
@mattcaswell reconfirm and I'll merge.
+1

**Comment by mattcaswell** [comment]
+1

**Comment by richsalz** [comment]
thanks, commit 4356cb28d39556c295b459c666e63a3e060967f5 pushed!

**Comment by FdaSilvaYY** [comment]
Commit ref is f792c663048f19347a1bb72125e535e4fb2ecf39
You're welcome.

**Pull request closed without merging**
