### PR TITLE
permitting no/empty digest in core_obj_add_sigid for openssl-3.0

### LINKED ISSUE #16761: OBJ_add_sigid disallows NID_undef for the digest id
The function `OBJ_add_sigid` explicitly disallows `NID_undef` for the digest id:

https://github.com/openssl/openssl/blob/64da15c40d15aac58e211fd25d00e9ae84d0379b/crypto/objects/obj_xref.c#L139-L145

However this makes no sense since we have multiple signature algorithms in the built-in list where it is valid for the digest id to be NID_undef (e.g. Ed25519 and Ed448):

https://github.com/openssl/openssl/blob/64da15c40d15aac58e211fd25d00e9ae84d0379b/crypto/objects/obj_xref.h#L22-L83

There are external provider that need to do this:
https://github.com/open-quantum-safe/oqs-provider/issues/2#issuecomment-936308396

### PR DESCRIPTION
**Pull request by baentsch**
Fixes #16761 for branch `openssl-3.0` (as per https://github.com/openssl/openssl/pull/16770#issuecomment-996504969)

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by baentsch** [comment]
The initial test was not thorough enough (no actual storage & retrieval test of [sig,dig=NID_undef,pkey] triplet). Please let me know if it would be prudent to also add the most recent test addition fixing that also to `master`.

**Comment by paulidale** [comment]
We should have the test in master too.

**Review by paulidale — APPROVED** [review]
Subject to a rebase to get rid of the merge commit.

**Comment by baentsch** [comment]
> We should have the test in master too.

See #17315.

> Subject to a rebase to get rid of the merge commit.

Unsure what to do with this comment: The conflict had been resolved by https://github.com/openssl/openssl/pull/17311/commits/7993df3d1fa17f6821f8f74d1356ed1405f2d49d, no?

**Comment by t8m** [comment]
We do not allow merge commits. Please drop it and instead do a git rebase and resolve the conflicts there.

**Comment by t8m** [comment]
Also please just drop the commit fixing the md nits. A commit fixing this is already in openssl-3.0 branch.

**Comment by baentsch** [comment]
> Also please just drop the commit fixing the md nits. A commit fixing this is already in openssl-3.0 branch.

`squashing` that commit out for some reason failed, sorry. Had to create #17327 as a "clean" PR. Closing this.

**Pull request closed without merging**
