### PR TITLE
Move Engine Library to new thread API

### PR DESCRIPTION
**Pull request by mattcaswell**
ping @ghedo, @richsalz

### CODE REVIEW

**Comment by levitte** [comment]
I'm eyeballing this, and it looks good.  I'll do a test build.

This makes me think that we should toss the lock hook fiddling in `bind_engine` (`include/openssl/engine.h`), are we ready for that?

**Comment by mattcaswell** [comment]
I'm thinking its too late to refactor stuff too extensively. I just want to move to the new thread API so we can lose the old one.

**Comment by levitte** [comment]
Well, yes, exactly.

**Comment by mattcaswell** [comment]
Ahhh...you mean this stuff:
````
    fns.lock_fns.lock_locking_cb = CRYPTO_get_locking_callback();
    fns.lock_fns.lock_add_lock_cb = CRYPTO_get_add_lock_callback();
    fns.lock_fns.dynlock_create_cb = CRYPTO_get_dynlock_create_callback();
    fns.lock_fns.dynlock_lock_cb = CRYPTO_get_dynlock_lock_callback();
    fns.lock_fns.dynlock_destroy_cb = CRYPTO_get_dynlock_destroy_callback();
````
Yes, I think that has to go...sigh...another MR...unless you fancy picking it up @levitte? You probably know that stuff better than anyone ;-)

**Comment by levitte** [comment]
On it already

**Comment by levitte** [comment]
#824

**Comment by levitte** [comment]
Test build went through smoothly and this looks safe enough to the naked eye, so +1

**Comment by mattcaswell** [comment]
Ping @levitte. I found some problems:
1) Some things call ENGINE APIs and end up initialising the locks even though an engine hasn't been loaded. This means we have to do ENGINE_cleanup no matter what.
2) I missed a lock in chil

A couple of commits have been added to address the issues. Can you reconfirm your +1?

**Comment by levitte** [comment]
I'm falling over with sleep.  Will look tomorrow

**Comment by mattcaswell** [comment]
@levitte...commit title updated (and the name of this GH pull request!)

**Comment by levitte** [comment]
Ooooh, ok, comments on commits do not show on this page.  I thought they did...

**Comment by levitte** [comment]
+1

**Comment by levitte** [comment]
This has been merged and can be closed

**Pull request closed without merging**
