### PR TITLE
Remove OSSLzu macros and use %zu (via BIO_printf).

### PR DESCRIPTION
**Pull request by paulidale**
Also convert the debug prints in dtls_mtu_test.c to use the output framework.

- [x] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
please look at #3727 -- should I use %z in my BIO_printf calls?

**Comment by paulidale** [comment]
@richsalz you are printing `uint64_t` variables.  `%zu` is for `size_t`.  So no, don't change to `%z` it would be wrong when size_t is not eight bytes.

**Comment by kroeckx** [comment]
We have that macro because %z is not part of the C90 standard.

**Comment by paulidale** [comment]
Does BIO_printf always support %zu ?
It's this function being used here.

**Comment by t-j-h** [comment]
Understood @kroeckx - but it is supported by BIO_printf which is what @paulidale is changing things over to use.

**Comment by kroeckx** [comment]
I guess the commit message is misleading

**Comment by paulidale** [comment]
I've changed the commit message and the PR title to indicate that BIO_printf is being used.

**Comment by dot-asm** [comment]
> Does BIO_printf always support %zu ?

In master, yes.

**Comment by richsalz** [comment]
Should we add %q or something similar to support printing 64bit values?  (Yes, a separate PR)

**Comment by richsalz** [comment]
merged.  next time do your own, kiddo :)  once you can, that is.

**Comment by paulidale** [comment]
I'm still fighting the local network restrictions :(

**Comment by paulidale** [comment]
Thanks though.

**Pull request closed without merging**
