### PR TITLE
fix deprecation inconsisteny w.r.t. CRYPTO_mem_debug_{push,pop}()

### LINKED ISSUE #9480: crypto/mem_dbg.c does not build without OPENSSL_NO_CRYPTO_MDEBUG
Since about two weeks, when building with `enable-crypto-mdebug` I get 

```
gcc  -I. -Icrypto/include -Iinclude -Iproviders/common/include -Iproviders/common/ciphers -Icrypto  -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -fPIC -pthread -m64 -Wa,--noexecstack -rdynamic -Wall -O0 -g --std=gnu90 -DDEBUG_UNUSED -DPEDANTIC -pedantic -Wno-long-long -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wswitch -Wsign-compare -Wshadow -Wformat -Wtype-limits -Wundef -Werror -Wmissing-prototypes -Wstrict-prototypes -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\""   -MMD -MF crypto/libcrypto-lib-mem_dbg.d.tmp -MT crypto/libcrypto-lib-mem_dbg.o -c -o crypto/libcrypto-lib-mem_dbg.o crypto/mem_dbg.c
crypto/mem_dbg.c:212:5: error: no previous prototype for 'CRYPTO_mem_debug_push' [-Werror=missing-prototypes]
 int CRYPTO_mem_debug_push(const char *info, const char *file, int line)
     ^
crypto/mem_dbg.c:217:5: error: no previous prototype for 'CRYPTO_mem_debug_pop' [-Werror=missing-prototypes]
 int CRYPTO_mem_debug_pop(void)
     ^
cc1: all warnings being treated as errors
Makefile:10240: recipe for target 'crypto/libcrypto-lib-mem_dbg.o' failed
make[1]: *** [crypto/libcrypto-lib-mem_dbg.o] Error 1
```

### PR DESCRIPTION
**Pull request by DDvO**
Fixes #9480

### CODE REVIEW

**Comment by mspncp** [comment]
I think you still need to add `DEPRECATEDIN_3` to the entry libcrypto.num. (Search there for an example.)

**Comment by DDvO** [comment]
Thanks for pointing out this dependency, sounds reasonable.
Yet the `DEPRECATEDIN_3` is already in since July 10 (commit e7aa7c11c71e84b2d6c06b1c81d130e8c1fba296);
I presume that `make ordinals` already did that according to `crypto.h`.

**Comment by levitte** [comment]
> I presume that `make ordinals` already did that according to `crypto.h`.

Yes

**Comment by mspncp** [comment]
> > I presume that `make ordinals` already did that according to `crypto.h`.
> 
> Yes

Sorry, my fault. I did not notice that I had another pull request instead of master checked out on my local branch.

**Comment by mspncp** [comment]
Merged to decdb980de, thanks.

**Pull request closed without merging**
