### PR TITLE
Adjust minimal build config in 1.1.1 branch

### PR DESCRIPTION
**Pull request by bernd-edlinger**
Backport of improvements from #9982 to 1.1.1 branch.
Adds some more exclusions which were previously missed.

[extended tests]

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mattcaswell** [comment]
Unsurprisingly travis is not happy

**Comment by bernd-edlinger** [comment]
incredible...

`test/sslapitest.c:6249:125: error: 'hostname_cb' undeclared (first use in this function)`

**Comment by bernd-edlinger** [comment]
See #11069

**Comment by mattcaswell** [comment]
#11069 was a dupe of #11014 which has now been merged. Close/reopen to kick travis CIs.

**Comment by bernd-edlinger** [comment]
now ok.

**Comment by bernd-edlinger** [comment]
Merged, OpenSSL_1_1_1-stable 52346fb.  Thanks

**Pull request closed without merging**
