### PR TITLE
[fuzzers] do not fail fuzzers with empty input

### PR DESCRIPTION
**Pull request by mikea**

### CODE REVIEW

**Comment by kroeckx** [comment]
I'm not sure what you're trying to fix and why you only change those 2 files in  that case,

**Comment by mikea** [comment]
@kroeckx these two fuzzers (and only these two) fail on empty input (len=0). As far as I can tell this happens because BIO_write doesn't like lenght=0.

**Comment by kroeckx** [comment]
You mean BIO_write() returns -1 on those and so the assert fails?

**Comment by mikea** [comment]
Yes

**Pull request closed without merging**
