### PR TITLE
Explicitly include e_os.h for close()

### PR DESCRIPTION
**Pull request by t8m**
This is an urgent CI fix for 3.1 and 3.0 branches but should be merged to all the active branches.

### CODE REVIEW

**Review by Sashan — APPROVED** [review]
agree with urgent.

**Review by andrewkdinh — APPROVED** [review]

**Review by t-j-h — APPROVED** [review]

**Comment by t-j-h** [comment]
Ok with urgent

**Review by mattcaswell — APPROVED** [review]
Ok with urgent

**Comment by t8m** [comment]
Merged to all the active branches. Thank you for the reviews.

**Comment by t8m** [comment]
Aarrgh.... we've change the e_os.h placement between 3.0 and 3.1.

**Pull request closed without merging**
