### PR TITLE
Fix NITs in comments and CHANGES for DEVRANDOM seeded check.

### PR DESCRIPTION
**Pull request by paulidale**
Post close nits from #9595.

### CODE REVIEW

**Comment by paulidale** [comment]
????

> nit: line break after ‚to‘

In CHANGES?  It's not wrapping past eighty columns.

**Comment by mspncp** [comment]
(It sticks out longer than the previous line)

**Comment by paulidale** [comment]
I've moved the new line and merged to 1.1.1 and master.

**Comment by rainerjung** [comment]
It seems the CHANGES entry in the 1.1.1 branch got duplicated.

**Comment by paulidale** [comment]
> It seems the CHANGES entry in the 1.1.1 branch got duplicated.

I think I'm ready to give up....

**Comment by paulidale** [comment]
Thanks, BTW :grin:

Removed in #9738.

**Pull request closed without merging**
