### PR TITLE
crypto/bn/build.info: Correct use of SSE2 definition

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
So travis is still failing?

**Comment by levitte** [comment]
It depends on #9884

**Comment by levitte** [comment]
Rebased, now that #9884 is in

**Comment by levitte** [comment]
CIs happy

**Comment by levitte** [comment]
Ping?  At this point, this is low hanging fruit

**Review by mattcaswell — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

d5d32e784dd2ac25b3c773893f94484bcda5a23d crypto/bn/build.info: Correct use of SSE2 definition

**Pull request closed without merging**
