### PR TITLE
Windows CI: Add make install step on the shared 64 bit build

### PR DESCRIPTION
**Pull request by t8m**
##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
CI seems relevant

**Review by paulidale — APPROVED** [review]
LGTM

**Comment by paulidale** [comment]
I've tagged this urgent since it's build fixing.  If someone else agrees, it can be merged.

**Review by slontis — APPROVED** [review]

**Comment by slontis** [comment]
If this breaks a build, then it is urgent

**Comment by t8m** [comment]
Merged to master. Thank you for the reviews!

**Pull request closed without merging**
