### PR TITLE
Document SSL_R_UNEXPECTED_EOF_WHILE_READING

### PR DESCRIPTION
**Pull request by mattcaswell**
Also document that it is ok to use this for control flow decisions.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Setting tests: deferred as it would be IMO nice to have a testcase for this reason code if it is officially documented as part of the API. But IMO this is a little bit more work than this simple doc PR so it should be properly planned.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by kroeckx** [comment]
Can you clarify why you mean with control flow decisions?

**Comment by mattcaswell** [comment]
> Can you clarify why you mean with control flow decisions?

The `ERR_GET_REASON` man page has this note on it:

> Applications should not make control flow decisions based on specific error
codes. Error codes are subject to change at any time (even in patch releases of
OpenSSL). A particular error code can only be considered meaningful for control
flow decisions if it is explicitly documented as such. New failure codes may
still appear at any time.

So, this makes `SSL_R_UNEXPECTED_EOF_WHILE_READING` explicitly documented as such according to the above note, i.e. it would be reasonable for an application to do something like this:

```` C
if (ERR_GET_REASON(errcode) == SSL_R_UNEXPECTED_EOF_WHILE_READING) {
    /* Do something */
} else {
    /* Do something else */
}
````

**Comment by kroeckx** [comment]
Maybe we should have a link to that other manpage.

**Comment by mattcaswell** [comment]
> Maybe we should have a link to that other manpage.

I have added that.

@t8m, @tom-cosgrove-arm - please reconfirm.

**Review by t8m — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]

**Comment by t8m** [comment]
Merged to the master and 3.2 branches. Needs a separate PR for 3.1 and 3.0.

**Comment by t8m** [comment]
@mattcaswell will you do that 3.1 PR?

**Comment by mattcaswell** [comment]
> @mattcaswell will you do that 3.1 PR?

#23327

**Pull request closed without merging**
