### PR TITLE
VMS: Copy DECC inclusion epi- and prologues to internals

### PR DESCRIPTION
**Pull request by levitte**
Because many of our test programs use internal headers, we need to make
sure they know how, exactly, to mangle the symbols.  So far, we've done
so by specifying it in the affected test programs, but as things change,
that will develop into a goose chase.  Better then to declare once and
for all how symbols belonging in our libraries are meant to be treated,
internally as well as publically.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by dot-asm — APPROVED** [review]

**Comment by levitte** [comment]
I was pondering for a bit if `__DECC_INCLUDE_*.H` should be copied to every directory under `crypto` and `ssl` we include from...  But that will be for another PR.

**Comment by levitte** [comment]
Merged.  f46f69f4092768ec4b911ced45c8cc73cc008739 and 27fc8ae22001a066ff99a8108f8dd70e547d6d64

**Comment by richsalz** [comment]
what about putting the includes in e_os.h?

**Comment by levitte** [comment]
I'm not sure I follow...

**Comment by richsalz** [comment]
Why have several copies of the DECC include files (you're "I was pondering" comment above)?  Why not have one copy, and have it referenced from e_os.h?  Then fix to make sure everyone includes e_os.h

**Comment by levitte** [comment]
It doesn't quite work that way...  basically, for any directory where those two files exist, DEC C translates this (using `include/openssl` as an example):

``` C
#include <openssl/foo.h>
```

to:

``` C
#include <openssl/__DECC_INCLUDE_PROLOGUE.H>
#include <openssl/foo.h>
#include <openssl/__DECC_INCLUDE_EPILOGUE.H>
```

Having them included in `e_os.h` doesn't fix the need for *before and after*.

**Comment by richsalz** [comment]
I see.  How about this, we put the VMS pragma's inline in each file, like we do with C++ support?

Adding ``__DECC_INLCUDE_``` files to every header diretory is kinda yucky IMO.

**Comment by levitte** [comment]
More yucky than adding the same pragmas to *every header file where it's relevant*, and remembering to *add them to any new header file*?  No thank you, I've done that goose chase for years with pre-1.1.0 OpenSSL, I do *not* want to go back there...  'cause of course it's gonna be me doing it!

**Comment by levitte** [comment]
However, the test programs that do need those pragmas internally are fairly few and far apart.  *That* I can deal with.

**Comment by richsalz** [comment]
yuck is a matter of taste?  shrug, okay.

**Comment by richsalz** [comment]
I was really just poking for alternatives.  If the header files in each directory is the simplest, then have a PR that puts them in every directory where there is a .h file.  I'll approve that PR.  Consistency is best.

**Comment by levitte** [comment]
Reopening: I seek approval to cherry-pick this back to 1.1.0.  The reason is that `fuzz/test-corpus.c` currently doesn't build on VMS, and this was the obvious solution for exactly that problem when introduced on master.

**Comment by levitte** [comment]
I'm sorry, I was inprecise.  I *only* needs to cherry-pick the commit that copies the DEC C specific files, i.e. commit f46f69f4092768ec4b911ced45c8cc73cc008739 (which is 1b77f953acf001f8b73c19668ca4f5cad2a6a990 with Reviewed-by lines added)

**Comment by richsalz** [comment]
approved for whatever subset you need to do.

**Comment by levitte** [comment]
Cherry-picked to 1.1.0:

6025c6619aa95a114a89ac3a60f8fac8abf0380a VMS: Copy DECC inclusion epi- and prologues to internals

Thank you!

**Pull request closed without merging**
