### PR TITLE
Add echo for end of each build phase

### PR DESCRIPTION
**Pull request by richsalz**
Ported GH #3842 to 1.1.0 branch

### CODE REVIEW

**Comment by dot-asm** [comment]
It's appropriate to back-port or cherry-pick #3759 to 1.1.0. Ping @mattcaswell or attempt cherry-pick direct here in this request?

**Comment by richsalz** [comment]
I would prefer @mattcaswell do the #3759; he knows more about it than I do.

**Comment by mattcaswell** [comment]
See #3854

**Comment by mattcaswell** [comment]
#3854 is in, so I suggest a rebase of this one.

**Comment by richsalz** [comment]
Rebased and pushed.

**Comment by richsalz** [comment]
merged thanks.

**Pull request closed without merging**
