### PR TITLE
add M1 macOS runner

### PR DESCRIPTION
**Pull request by quarckster**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
Not sure if this is possible to cherry pick to all release branches. If not, make a separate pr for those where it's not.

**Review by shahsb — APPROVED** [review]
LGTM

**Comment by slontis** [comment]
Could you point to where this is m1 based?

**Comment by quarckster** [comment]
> Could you point to where this is m1 based?

it's github.com runners, they recently announced the general availability https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by slontis** [comment]
Apart from the sspl_api_test (which is failing in other PR's) the other failures may be M1 specific. Not sure of the order of merging that should happen.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
The failures so far are not relevant (although interesting).

**Review by slontis — APPROVED** [review]

**Comment by t8m** [comment]
Merged to all the active branches. Thank you.

**Pull request closed without merging**
