### PR TITLE
Add text/x509aux to gitignore

### PR DESCRIPTION
**Pull request by tmshort**

### CODE REVIEW

**Comment by mattcaswell** [comment]
+1

**Comment by levitte** [comment]
+1

**Comment by richsalz** [comment]
+1

**Comment by mattcaswell** [comment]
Merged.

**Comment by mattcaswell** [comment]
That's got to be a record: 3 team review and pushed to master within 7 minutes ;-)

**Comment by levitte** [comment]
Heh :-)

**Comment by tmshort** [comment]
Whoo-hoo! This has been bothering me for a while.

**Comment by mattcaswell** [comment]
And me....and I guess Richard and Rich too!!

**Comment by levitte** [comment]
Actually, not me so much...  I build master out-of-source these days, so I don't get bothered by these details any more...  So I'm glad someone does notice!

**Pull request closed without merging**
