### PR TITLE
Fix PEM_write_bio_PrivateKey_traditional() to not output PKCS#8

### PR DESCRIPTION
**Pull request by levitte**
PEM_write_bio_PrivateKey_traditional() uses i2d_PrivateKey() to do the
actual encoding to DER.  However, i2d_PrivateKey() is a generic
function that will do what it can to produce output according to what
the associated EVP_PKEY_ASN1_METHOD offers.  If that method offers a
function 'old_priv_encode', which is expected to produce the
"traditional" encoded form, then i2d_PrivateKey() uses that.  If not,
i2d_PrivateKey() will go on and used more modern methods, which are
all expected to produce PKCS#8.

To ensure that PEM_write_bio_PrivateKey_traditional() never produces
more modern encoded forms, an extra check that 'old_priv_encode' is
non-NULL is added.  If it is NULL, an error is returned.

### CODE REVIEW

**Comment by levitte** [comment]
A backport to 1.1.1 will come in a separate PR

**Comment by levitte** [comment]
Backport to 1.1.1 in #12729

**Comment by levitte** [comment]
... and with this, we discover that not all of our `EVP_PKEY_ASN1_METHOD` instances support "traditional" PEM or DER output...  One example: DH

**Review by t8m — APPROVED** [review]
Approved if CI passes.

**Comment by levitte** [comment]
Merged

87d91d223b869855c11f51b54541ba8139d30d8e Fix PEM_write_bio_PrivateKey_traditional() to not output PKCS#8
bddfea0271d0596961a43283b36ff49923329a92 TEST: Adapt some tests for a stricter PEM_write_bio_PrivateKey_traditional()

**Pull request closed without merging**
