### PR TITLE
Rework DSO API conditions and configuration option

### PR DESCRIPTION
**Pull request by levitte**
'no-dso' is meaningless, as it doesn't get any macro defined.
Therefore, we remove all checks of OPENSSL_NO_DSO.  However, there may
be some odd platforms with no DSO scheme.  For those, we generate the
internal macro DSO_NONE and use it.

### CODE REVIEW

**Review by richsalz — COMMENTED** [review]
Wow, kind of surprising how much simpler things got!

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
A question: should this be back-ported to 1.1.1?  The `no-dso` option is similarly toothless there...

**Comment by levitte** [comment]
Meanwhile, I've merged into master.

31b6ed76dfd53529b74e79830c81372d0b756929 Rework DSO API conditions and configuration option

**Comment by paulidale** [comment]
I think 1.1.1 too but don't feel strongly about it.

**Comment by levitte** [comment]
Done in #8628

**Comment by Posolsvetla** [comment]
Hi, I guess, that with the removal of no-dso support, the no-dso build on Win is no longer supported?
The DSO_WIN32 is now defined, while before it wasn't (with no-dso used).
Is this intended or is it an oversight?
Thanks.

**Comment by levitte** [comment]
That's intended. That macro is really quite internal to the DSO sub-system, so it shouldn't make a difference outside of it.

**Pull request closed without merging**
