### PR TITLE
Fix a few github file references

### LINKED ISSUE #13396: The user support resource page is not valid now
Once you want to report new issues, system will remind you to refer the the support page: 

>     If you're asking about how to use OpenSSL, this isn't the right 
>     forum.  Please see our User Support resources:
>     https://github.com/openssl/openssl/blob/master/.github/SUPPORT.md

But, the link https://github.com/openssl/openssl/blob/master/.github/SUPPORT.md doesn't work now.

### PR DESCRIPTION
**Pull request by levitte**
https://github.com/openssl/openssl/blob/master/.github/SUPPORT.md ->
https://github.com/openssl/openssl/blob/master/SUPPORT.md

Fixes #13396

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
As a side note, I just re-read the SUPPORT.md file. I find the recommendation to disable asm in that file disturbing. This is not something we should be encouraging users to do without suitable caveats. The asm implementations often have security properties (constant time) that the C implementations may not have (not to mention of course the performance benefits). Building with no-asm might be a useful thing to do to rule in or out asm issues - but using it in production should be treated with caution.

**Comment by levitte** [comment]
> As a side note, I just re-read the SUPPORT.md file. I find the recommendation to disable asm in that file disturbing. This is not something we should be encouraging users to do without suitable caveats. The asm implementations often have security properties (constant time) that the C implementations may not have (not to mention of course the performance benefits). Building with no-asm might be a useful thing to do to rule in or out asm issues - but using it in production should be treated with caution.

Hmmm, I don't see anything suggesting that really suggests this for production.  What I do see, though, is that SUPPORT.md repeats the same thing twice, where the second one has section titles explaining the intent a bit better.

I'll take a dive at editing it to be, er, better.  Another PR.

**Comment by mattcaswell** [comment]
> Hmmm, I don't see anything suggesting that really suggests this for production. What I do see, though, is that SUPPORT.md repeats the same thing twice, where the second one has section titles explaining the intent a bit better.

"If you have problems with OpenSSL....configure with no-asm".

I think anyone reading that could reasonably interpret it as something you might consider for production. My point above was that there aren't sufficient caveats.

**Comment by levitte** [comment]
How about looking #13398 and see if that's a better read?

**Comment by levitte** [comment]
Merged

322d56cd645fa2372aaddc78ea5db9c71f58d28f Fix a few github file references

**Pull request closed without merging**
