### PR TITLE
rsa/rsa_ossl.c: implement variant of "Smooth CRT-RSA." [1.1.0]

### PR DESCRIPTION
**Pull request by dot-asm**
#6915 backport to 1.1.0.

### CODE REVIEW

**Comment by dot-asm** [comment]
Re-based and harmonized with master.

**Comment by dot-asm** [comment]
Which ping was it? Apparently there is magic one for this matter... P-i-i-i-i-i-i-n-g?

**Comment by dot-asm** [comment]
Too little i's? All right, copy-n-pasting for #6915: "P-i-i-i-i-i-i-i-i-i-i-n-g then?"

**Comment by mattcaswell** [comment]
@paulidale care to review this one too?

**Pull request closed without merging**
