### PR TITLE
Disable test/timing_load_creds.c on VMS

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
Urgent because the usual VMS whack-a-mole

**Review by beldmit — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Agree with urgent.

**Comment by beldmit** [comment]
I agree with urgent.

**Comment by levitte** [comment]
Merged

81929ac49aa583b2347348953d8399ad775c6fd1 Disable test/timing_load_creds.c on VMS

**Pull request closed without merging**
