### PR TITLE
Remove trailing whitespace from some files.

### PR DESCRIPTION
**Pull request by davidben**
The prevailing style seems to not have trailing whitespace, but a few
lines do. This is mostly in the perlasm files, but a few C files got
them after the reformat. This is the result of:

```
  find . -name '*.pl' | xargs sed -E -i '' -e 's/( |'$'\t'')*$//'
  find . -name '*.c' | xargs sed -E -i '' -e 's/( |'$'\t'')*$//'
  find . -name '*.h' | xargs sed -E -i '' -e 's/( |'$'\t'')*$//'
```

Note mkerr.pl has some changes in a heredoc for some help output, but
other lines there lack trailing whitespace too.

### CODE REVIEW

**Comment by mattcaswell** [comment]
+1

**Comment by FdaSilvaYY** [comment]
All good except that file :
[bn_prime.h](https://github.com/openssl/openssl/blob/master/crypto/bn/bn_prime.h)
```
  /*
   * WARNING: do not edit!
  * Generated by crypto/bn/bn_prime.pl
```

**Comment by davidben** [comment]
Oops! bn_prime.h changes dropped.

**Comment by kroeckx** [comment]
Maybe you should update the script so that it updates the file too?

**Comment by davidben** [comment]
Done. Pushed a new commit which fixes up the formatting.

**Comment by mattcaswell** [comment]
Merged.

**Pull request closed without merging**
