### PR TITLE
RT4347: Fix GCC unused-value warnings with HOST_c2l()

### PR DESCRIPTION
**Pull request by dwmw2**
The HOST_c2l() macro assigns the value to the specified variable, but also
evaluates to the same value. Which we ignore, triggering a warning.

To fix this, just cast it to void — like we did in commit 08e553644
("Fix some clang warnings.") for a bunch of other instances.

Although in fact, it looks like *all* users of `HOST_c2l()` are now casting its result away, so maybe we should just fix it not to do that at all?

### CODE REVIEW

**Comment by richsalz** [comment]
there's mutliple versions of HOST_c2l and some of them are code blocks.  So yeah, I think remove the ",l" to get a value back makes more sense.  Not sure your void cast will compile with, say the version at line 209 of md32_common.h

**Comment by kroeckx** [comment]
I would actually be in favour of not returning that l.  Not all implementations seem to be doing it in the first place.  I suggest you then also remove all those casts.

The same should probably also be done for HOST_l2c().

@dot-asm: Do you have any opinion on this?

**Comment by dwmw2** [comment]
The void cast has been there for at least three years in other places; see commit 08e553644.
It certainly works even with the code blocks...
```
#define HOST_c2l(c, l) ({unsigned int r;			\
			asm("movbe %1,%0"			\
			    :"=r"(r)				\
			    :"m"(((const unsigned int *)(c))));	\
			(c)+4; (l)=r;})

int foo(int *p)
{
	int bar;
	(void)HOST_c2l(p, bar);
	return bar;
}
```

Of course, using __builtin_bswap32() and friends would give the compiler much more of a clue what's going on, and give it much better scope for optimisation. But that's a different story... :)

**Comment by richsalz** [comment]
Okay, so it does work.  The point that changing the macro to not return anything is a smaller change than all those casts. :)

**Comment by dwmw2** [comment]
Maybe... maybe not. My patch above adds 39 casts. If we fix HOST_c2l() not to return a value, then arguably there's 48 casts already in the code base that would ideally want to be *removed* :)

I genuinely don't care. I'll submit a patch to do it the other way round if you want, or the above can stand. I was just pointing out that there was a subjective decision to be made.

**Comment by richsalz** [comment]
Let’s see what @dot-asm says ☺

**Comment by dot-asm** [comment]
Why me? I have no special opinion on this. But if we look at earlier precedents, then we'll see that (void) was used. The reason for why most recent (void)-ification was limited to MD4 and RIPEMD must depend on the fact that those are C on daily platform for most developers (who are fond of chasing warnings), so that C code mentioned here tends to so to say fall to blind spot because of assembly. So I suppose following earlier path and adhering to (void) as suggested is fine. At the very least just removing `,l` would not be really appropriate. Because it would mean that those macros would return *different* values in different situations. And that would be a bad style, unacceptable really. I mean *all* macro variants should be harmonized, i.e. expressions should always evaluate to *same* value or voided at definition.

**Comment by dot-asm** [comment]
Ah! I recalled similar issue was discussed on dev-list. And I was involved. That's probably why I was called even here. Note that by that time it was also about removal of `,l`, but note that return value of the then modified macro did not change. Indeed, expression `(... l|=something, l)` is equivalent to `(...l|=something)` and it's l.

**Comment by dot-asm** [comment]
To clarify. I disagree with @kroeckx's analysis that not all of those macros evaluate to value of `l`, they all do. [Assignment as last thing in gnu-ish }) makes it evaluate to assigned value.] One can argue that they don't have to and it's ugly that they do, but if we choose to change that, then it would be appropriate to maintain uniformity, in sense that they all should behave exactly same. I.e. while I don't have special opinion on which way it goes, I have opinion about not taking a 3rd way, way of just omitting few `, l` in those remaining cases. As something we can't disagree on we can choose to switch to `do { } while(0)` so that macros come out as statements, not as expressions, thus addressing problem at its root. But if you twist my arm and make me leave a vote, I'd vote for current @dwmw2's suggestion as it stands... Yes, it's arguably ugly (no offense, David, I naturally don't mean that you're responsible, it's just the way this way is), but I don't see it as a "medical condition"...

**Comment by dwmw2** [comment]
No offence taken. If you look back at my original submission, what I was saying was basically _"here's a fix which is consistent with what you did before... but it's ugly, so you might want to think again..."_

Change it or not, as you see fit. But it would have been wrong of me to *not* raise the question.

**Comment by richsalz** [comment]
+1
So @dot-asm will you plus-one?  I'll merge.

**Comment by dot-asm** [comment]
If I may twist your arm at some later occasion :-)

**Comment by richsalz** [comment]
Every ASM post of yours I approve twists my arm ☺

Thanks.

**Comment by richsalz** [comment]
commit 09977dd  tahnks!

**Pull request closed without merging**
