### PR TITLE
FIx mismatched curly brace

### PR DESCRIPTION
**Pull request by Dmitry-Me**
This resolves https://github.com/openssl/openssl/issues/691

### CODE REVIEW

**Comment by levitte** [comment]
+1

**Comment by mattcaswell** [comment]
+1...will you merge?

**Comment by levitte** [comment]
Sure

**Comment by levitte** [comment]
Merged

**Comment by Dmitry-Me** [comment]
Commit https://github.com/openssl/openssl/commit/9eaa5f9a329c4ef169697bba4dcfb7c7d5729e76

**Pull request closed without merging**
