### PR TITLE
Follow up for recent options changes

### PR DESCRIPTION
**Pull request by kaduk**
a48eaf711871b689b2287cf3c6c4038a5af636e9..a50ad1daaa68c109ea1a14225a7aba8660526101 left a '??' entry in INSTALL, and brought in some OPENSSL_NO_SHA after removing all of them.  Tidy up after these.

### CODE REVIEW

**Comment by levitte** [comment]
If you remove `"sct",` from the `@disablables` in `Configure`, this change will be complete.

**Comment by kaduk** [comment]
Ah, thanks for catching that @levitte -- fixed now

**Comment by mattcaswell** [comment]
+1

**Comment by levitte** [comment]
+1

**Comment by richsalz** [comment]
I took the liberty of merging; closed.  Thanks!

**Pull request closed without merging**
