### PR TITLE
Pin actions to a full length commit SHA

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

>Pin actions to a full length commit SHA

>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Also, dependabot supports upgrading based on SHA.

Signed-off-by: naveensinivasan <172697+naveensrinivasan@users.noreply.github.com>

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
These are our CI loops to verify pull requests.  Pinning them to a particular SHA value completely ruins their usefulness.

**Comment by romen** [comment]
@paulidale I think you might have been too quick in dismissing this. At least the parts I have been checking only pin the github actions we use in our CI to a commit version rather than a tag version.
This seems a desirable form of hardening of our CI against supply chain attacks and the sort.

**Comment by romen** [comment]
@paulidale I think you might have been too quick in dismissing this. At least the parts I have been checking only pin the github actions we use in our CI to a commit version rather than a tag version.
This seems a desirable form of hardening of our CI against supply chain attacks and the sort.

**Comment by paulidale** [comment]
I've reopened this.  I still have **signficant** concerns about pegging the CIs to commit: 629c2de402a417ea7690ca6ce3f33229e27606a5

**Comment by t8m** [comment]
IMO this is outside of what we allow with CLA: trivial although it is probably not copyrightable.

Could you please submit a CLA? https://www.openssl.org/policies/cla.html

**Comment by t-j-h** [comment]
I don't see the point frankly.

If there is an issue with uncontrolled updates to tags then we have a much larger problem that what this is "defending" against.

There is also this explicit note in the recommendations:

> First determine if your project is producing a library or application. If it is a library, you generally don't want to pin dependencies of library users, and should not follow any remediation steps.

**Comment by naveensrinivasan** [comment]
> IMO this is outside of what we allow with CLA: trivial although it is probably not copyrightable.
> 
> Could you please submit a CLA? https://www.openssl.org/policies/cla.html

image

I have submitted the CLA.

**Comment by naveensrinivasan** [comment]
> > IMO this is outside of what we allow with CLA: trivial although it is probably not copyrightable.
> > Could you please submit a CLA? https://www.openssl.org/policies/cla.html
> 
> image
> 
> I have submitted the CLA.

image

I don't want to use my actual email. I use the GitHub email that forwards the email. This keeps my privacy.

**Comment by t8m** [comment]
Then please submit CLA also with the GitHub e-mail.

**Comment by naveensrinivasan** [comment]
> Ping?

Sorry, Can you please share the email I need to send the CLA to? It keeps bouncing back. Thanks!

**Comment by naveensrinivasan** [comment]
> It should not bounce anymore, please try again.

image

**Pull request closed without merging**
