### PR TITLE
If an engine comes up explicitely, it must also come down explicitely (1.0.2)

### PR DESCRIPTION
**Pull request by levitte**
In apps/apps.c, one can set up an engine with setup_engine().
However, we freed the structural reference immediately, which means
that for engines that don't already have a structural reference
somewhere else (because it has registered at least one cipher or digest
algorithm method, and therefore gets a functional reference through the
ENGINE_set_default() call), we end up returning an invalid reference.

Instead, the function release_engine() is added, and called at the end
of the routines that call setup_engine().

Originally, the ENGINE API wasn't designed for this to happen, an
engine had to register at least one algorithm method, and was
especially expected to register the algorithms corresponding to the
key types that could be stored and hidden in hardware.  However, it
turns out that some engines will not register those algorithms with
the ENGINE_set_{algo}, ENGINE_set_cipher or ENGINE_set_digest
functions, as they only want the methods to be used for keys, not as
general crypto accelerator methods.  That may cause ENGINE_set_default()
to do nothing, and no functional reference is therefore made, leading
to a premature deallocation of the engine and it thereby becoming
unavailable when trying to fetch a key.

### CODE REVIEW

**Comment by levitte** [comment]
Description updated.  @dwmw2, since you're involved, do you agree with it from your end?

**Comment by dwmw2** [comment]
> Description updated. @dwmw2, since you're involved, do you agree with it from your end?

Apologies for missing that request. This works (modulo the `NULL` checking), and is fairly similar to what I'd submitted myself. However, I'm still fairly unhappy with commit  53a71b7429a4315f7761bea1be20a6d0b9c9a502 in the 1.0.2 stable branch. It's *correct*, but you're introducing a new torture test for engines' refcounting in the stable branch. It would be safer in 1.0.2 to take a *functional* reference at the start, and hold onto it until the end, instead of calling `ENGINE_init()` and `ENGINE_finish()` for each call into the engine.

**Comment by levitte** [comment]
Re the NULL stuff, I reworked `setup_engine()` and `release_engine() so they're always available, and could thereby remove quite a bit of `#ifndef` clutter.  Please have a look, I hope you'll be pleased with that.

**Comment by richsalz** [comment]
+1 looks good.

**Comment by levitte** [comment]
Merged.

**Pull request closed without merging**
