### PR TITLE
APPS `http_server.c`: allow clients to connect with IPv6

### PR DESCRIPTION
**Pull request by DDvO**
So far, the test server used for OCSP and CMP only supports IPv4 connections.
This adds support for IPv6, inspired by https://github.com/openssl/openssl/issues/15992#issuecomment-1559342037.

Extend doc and tests accordingly.
On this occasion, fix minor glitches in `openssl-ocsp.pod.in`.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by DDvO** [comment]
One of the CI job runs had failed for unrelated reasons:
```
unable to access 'https://github.com/openssl/openssl/': The requested URL returned error: 429
```
Just found that GitHub offers the nice feature to selectively re-run failed jobs,
so no need to kick the whole PR in such cases.

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
@openssl/committers this PR has been waiting for quite some time for the 2nd review, which should be rather straightforward.

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by DDvO** [comment]
Merged - thanks @t8m and @beldmit for your approvals.

**Pull request closed without merging**
