### PR TITLE
Find more undoc

### PR DESCRIPTION
**Pull request by richsalz**
Final, correct, checking in find-doc-nits for when a manpage documents a "private" function.
Private is determined by not being in util/lib*.num, or the special util/private.num which is
where we list other symbols (defines and typedefs) that aren't in the function list of the first
two .num files.

### CODE REVIEW

**Comment by paulidale** [comment]
`BIO_set` still appears in `util/libcrypto.num`.  Is this for legacy reasons or will it too go away?

`EVP_PKEY_CTX_set_rsa_rsa_keygen_bits` also appears in `doc/man7/RSA-PSS.pod`.  I assume it should disappear from there too.

Is it necessary to keep the 
> BIO_set() was removed in OpenSSL 1.1.0 as BIO type is now opaque.
comment in `doc/man3/BIO_new.pod`

**Comment by FdaSilvaYY** [comment]
It appears yes:
`BIO_set                                 2765	1_1_0	NOEXIST::FUNCTION:`
with the `NOEXIST `mention to avoid reusing his ordinal.

**Comment by paulidale** [comment]
Thanks for the clarification.

**Comment by levitte** [comment]
`NOEXIST` entries are functionally important at the end of the `.num` files, so that entry will not be reused.  Otherwise it doesn't reeeeally matter, since we next number selected will always be the current last plus one.

**Comment by levitte** [comment]
> Is it necessary to keep the 
> > BIO_set() was removed in OpenSSL 1.1.0 as BIO type is now opaque.
comment in `doc/man3/BIO_new.pod`

I think it is.  People who use it will wonder.

**Comment by mattcaswell** [comment]
As an aside, it would be useful if find-doc-nits could tell us about undocumented macros

**Comment by richsalz** [comment]
Merged.
As an aside, please see https://github.com/openssl/openssl/pull/3641 :)

**Pull request closed without merging**
