### PR TITLE
Add perl modeline to Configure scripts

### PR DESCRIPTION
**Pull request by jtbandes**
Encourages GitHub to perform proper syntax highlighting.

### CODE REVIEW

**Comment by levitte** [comment]
Not only github, but emacs as well.  I'm all for this.

**Comment by richsalz** [comment]
+1 so you can merge it.

**Comment by levitte** [comment]
Merged.  Thanks.

**Comment by ghedo** [comment]
The change to `Configure` causes build failures on all test environments and makes it impossible to actually build OpenSSL, please revert it (what's the point of having Travis if its errors are ignored...).

**Comment by levitte** [comment]
Yes, noticed...  darnit.

Question is, do we restore it as it was or do we add the usual hashbang line up top instead?  Move backward or forward?  Is the age old : exec magic really still needed?

**Comment by levitte** [comment]
shebang.  I just remembered it's called a shebang (#!).  Sorry for the confusion.

**Comment by ghedo** [comment]
I'd say go forward and drop the exec magic. But I don't really know what the point of that was in the first place so I may be wrong.

**Comment by levitte** [comment]
I agree with you, and even perlrun(1) does.

That syntax was a oooooold trick in case the script was run through a shell.

**Comment by levitte** [comment]
Either way, fix coming up

**Comment by levitte** [comment]
Fix pushed

**Pull request closed without merging**
