### PR TITLE
Fix typo in SSLeay License

### PR DESCRIPTION
**Pull request by JHH20**
Fixed a small typo in the original SSLeay License

### CODE REVIEW

**Review by paulidale — APPROVED** [review]
FWIW

**Comment by paulidale** [comment]
If you consider this to be trivial (I do), could you please add "CLA: trivial" on a line by itself in the commit message?

**Comment by JHH20** [comment]
@paulidale Yes, I have amended the commit message earlier to include the "CLA: trivial" text.

**Comment by t-j-h** [comment]
The license text is fixed and cannot be changed.

**Comment by mspncp** [comment]
FWIW: it's a duplicate of #6877

**Pull request closed without merging**
