### PR TITLE
STORE: split off the description of the 'file' scheme loader

### PR DESCRIPTION
**Pull request by levitte**
This includes a quick recommendation on how to name loader docmentation.

### CODE REVIEW

**Comment by levitte** [comment]
Ping?

**Comment by dot-asm** [comment]
Just in case for reference. I'm in general reluctant to approve things like documentation, because of lack of linguistic skills. I try to look for and point out factual wrongs or things that are not clear to me, but I try to abstain from approvals. In other words me not saying something in situation like this request rather means that I didn't spot something wrong :-)

**Comment by levitte** [comment]
Cool. So with that, does anyone else want to approve?

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
Thank you!

**Comment by levitte** [comment]
Merged.

166f0082e7ce53ed608d8519526b99893ca7925e STORE: split off the description of the 'file' scheme loader

**Pull request closed without merging**
