### PR TITLE
Fix manual generation on Unix

### PR DESCRIPTION
**Pull request by levitte**
Manual generation on Unix hasn't caught up with the directoory layout change.  Also, we have a well working script that does the work on other platforms, there's no point in making Unix a special case (i.e. double the maintainance burden).

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
Great!  For master and 1.1.0?  The cherry-pick will need some editing for the directory structure I assume.

**Comment by levitte** [comment]
I was actually thinking master only...  but can certainly make an effort for 1.1.0 as well if that's desired.

**Comment by richsalz** [comment]
I guess since 1.1.0 works now, it's not worth the effort.  Your call.

**Comment by levitte** [comment]
I think it requires a separate PR.  `util/process_docs.pl` is sufficiently different, methinks.

**Comment by levitte** [comment]
Merged.  579a6745337fe8dc4ce34fac6367fa197a7cc219 and cadb015b021065640c7ae02c5eefa0e04cdbd45e

**Comment by kroeckx** [comment]
So after this commit we have a lot of cases of things like: "X509_get_version.pod: cannot resolve L<d2i_X509(3)> in paragraph 19". Is that a new error message, or is this "better"?

**Comment by richsalz** [comment]
It's a new error message.

**Comment by levitte** [comment]
Errr, I haven't been able to reproduce it, can you give me circumstances?  Configuration command and exactly what you made?

**Comment by levitte** [comment]
Perhaps it would be best to raise an issue...

**Comment by levitte** [comment]
Ah, it seems this might be a bug in Pod::Html:

https://bugs.llvm.org//show_bug.cgi?id=1005

**Comment by kroeckx** [comment]
That's a bug from 2006?

Anyway, I was just looking at the output from travis, the first job.

**Comment by levitte** [comment]
Yeah, I saw it after asking...  Tried on my machine, saw no such errors, so cannot reproduce.

**Comment by levitte** [comment]
From the same Travis log:

```
PERLVERSION   =5.14.2 for x86_64-linux-gnu-thread-multi
```

... and I find [confirmation](http://stackoverflow.com/questions/8465807/what-is-the-correct-syntax-for-producing-http-links-with-custom-text-with-pod2ht) that this Perl version has issues that give that error message as well.

**Pull request closed without merging**
