### PR TITLE
fix pyca/cryptography test suite failure

### LINKED ISSUE #6527: pyca external tests are failing
Looks like the head of master is failing in the pyca external tests (which in turn means travis is failing). From the log it appears to be a new  mem leak, but I'm not familiar enough with the pyca code.

### PR DESCRIPTION
**Pull request by reaperhulk**
This fixes #6527. pyca/cryptography now uses `OPENSSL_cleanup` in its memleak tests.

### CODE REVIEW

**Comment by richsalz** [comment]
could we just sub-import the latest module?

Thank you for your timely help with this!

**Comment by levitte** [comment]
> could we just sub-import the latest module?

Isn't that what this PR does?

**Comment by reaperhulk** [comment]
@richsalz this PR should just update the commit hash for the submodule. I think GitHub makes it fancy and shows what that diff is though.

**Comment by richsalz** [comment]
thanks for the explanation.  looks good to me.

**Comment by bernd-edlinger** [comment]
Should I merge this?

**Comment by levitte** [comment]
Sure 👍

**Comment by bernd-edlinger** [comment]
Merged to master as a6efd86.
Thanks!

**Pull request closed without merging**
