### PR TITLE
Address session ownership

### PR DESCRIPTION
**Pull request by wbl**
This commit resolves an issue with corruption of session cache lists. There is an undocumented invariant maintained by SSL_SESSION_list_add and SSL_SESSION_list_remove that either a session has an owner and is in the linked list of that owning session, or is not. However duplication did not clear the owner.

Timeout management added in https://github.com/openssl/openssl/pull/8687 uses the owner pointer to update the list order, however if the session is a copy of the one in the cache, this logic is incorrect and leads to corruption of the list structures. The solution is to ensure duplicates have owner unset.

I also took the liberty of updating the documentation while I was at it.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
We will need CLA to be signed to be able to merge this PR. Could you please look at https://www.openssl.org/policies/cla.html

**Comment by wbl** [comment]
I sent a snail mail in a while ago let me try electronic this time

**Review by tmshort — APPROVED** [review]
LGTM

**Comment by wbl** [comment]
I've sent Tam an email with someone who should be the right current contact, so that should get sorted out soon.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
