### PR TITLE
DES keys are not 7 days long.

### PR DESCRIPTION
**Pull request by daztucker**
##### Description of change
Fixes misspellings of "week keys"

### CODE REVIEW

**Comment by daztucker** [comment]
The CLA policy says "all non-trivial contributors" however this is trivial.

**Comment by richsalz** [comment]
yes it is.  Can you add "CLA: trivial" to the commit and repush?

**Comment by daztucker** [comment]
done

**Comment by levitte** [comment]
For formality, I agree this is trivial

**Comment by daztucker** [comment]
Given that this pull request contains only changes to comments and docs I am not convinced that test coverage actually dropped by 0.004%.

**Comment by mattcaswell** [comment]
Agreed trivial.

**Comment by levitte** [comment]
Merged

master: 4fd7b54dc224930a0ce6dd67b35c598c5072857c
1.1.0: ca423a693a619b38fb96d94b0385f8ce91a8e759
1.0.2: 07109409daa674e4e766523a1dc51edb06299e03

**Comment by richsalz** [comment]
the coveralls measurements aren't as accurate as they claim to be :)

**Pull request closed without merging**
