### PR TITLE
WIP: Find out where is the echo

### PR DESCRIPTION
**Pull request by bernd-edlinger**
[extended tests]

out of curiosity...

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
```
[00:10:19] 	where echo
[00:10:19] C:\Program Files\Git\usr\bin\echo.exe
```

**Comment by levitte** [comment]
Oh my... I wonder what else there is in that directory...

**Comment by bernd-edlinger** [comment]
Yes. maybe even rem.exe ?

**Comment by bernd-edlinger** [comment]
by the way, why do we mkdir the install directory ? isn't nmake install supposed to create it ?

**Pull request closed without merging**
