### PR TITLE
fix: VC static debug library now compiled with /MTd runtime, instead of /MT

### PR DESCRIPTION
**Pull request by myrgy**

### CODE REVIEW

**Comment by levitte** [comment]
If you think this is a trivial fix, please att the following to the commit message on a line of its own:

```
CLA: trivial
```

If you don't think it's trivial, you will have to file a CLA.

**Comment by myrgy** [comment]
done

**Comment by dot-asm** [comment]
The lack for check for debug vs. release here is not a coincidence. As long as you complement /MT option with /Zl it doesn't matter if it was /MT or /MTd. Yes, /MTd also pre-defines _DEBUG, but we don't rely on it, nor does Windows API. So that debug static library would be same after the suggested modification. More specifically bearing no references to any particular CRT library. This decision is moved to executable link time, so that you are free to use /MTd when linking your application with debug (or release) static library.

**Comment by richsalz** [comment]
So close this?  Maybe we should have a FAQ entry?

**Comment by myrgy** [comment]
@dot-asm , could you please point to one more thing - what if I would like to build application with /MD(d), is it possible to use the same version, generated with /Zl  ?

**Comment by dot-asm** [comment]
> if I would like to build application with /MD(d), is it possible to use the same version, generated with /Zl ?

Yes. It should be possible to use static Windows library with *any* /M option. "Should be possible" means that if there is problem it will be treated as bug. I do check that it works once in a while, but not all the time...

**Comment by myrgy** [comment]
@dot-asm , I did a check - seems that it works fine.
@richsalz , I think we can close that PR.
Thanks

**Pull request closed without merging**
