### PR TITLE
Fix CI breakage due to ABIDIFF failure

### PR DESCRIPTION
**Pull request by t8m**
Also sync libcrypto.num and libssl.num with 3.2 branch and fix the EVP_DigestSqueeze symbol version.

This is urgent as CI is broken on pull requests.

### CODE REVIEW

**Review by nhorman — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Agree urgent

**Review by hlandau — APPROVED** [review]
OK with urgent

**Review by beldmit — APPROVED** [review]
LGTM, agree urgent

**Comment by t8m** [comment]
Merged to the master branch. Thank you for the reviews.

**Pull request closed without merging**
