### PR TITLE
Add support for wrap mode with openssl enc

### PR DESCRIPTION
**Pull request by dongbeiouba**
Add support for wrap mode with openssl enc

### CODE REVIEW

**Comment by t8m** [comment]
This is not a bug fix so it is not going to be merged to 1.1.1.

There is also a problem that the wrap mode has certain restrictions which do not make it that good for the enc command, so I am not even sure it is good idea to merge to master after the 3.0 release.

**Comment by dongbeiouba** [comment]
openssl enc in 3.0 beta version supports wrap mode, but openssl 1.1.1 doesn't.

Maybe some people still want to use openssl 1.1.1 instead of 3.0 in the near feature. 

This PR can resolve #10605.

**Comment by mattcaswell** [comment]
> Maybe some people still want to use openssl 1.1.1 instead of 3.0 in the near feature.

It is against policy to add features to 1.1.1. We allow bug and security fixes ones. So, unfortunately, as @t8m says, this won't be merged to 1.1.1.

**Comment by dongbeiouba** [comment]
Got it. Thanks.

**Pull request closed without merging**
