### PR TITLE
Get pointer type right in BIO_ssl_shutdown()

### LINKED ISSUE #2199: Crash in BIO_ssl_shutdown() in OpenSSL 1.1.0c
I've encountered a crash in BIO_ssl_shutdown() in OpenSSL 1.1.0c. It looks like the BIO_get_data() return value is being interpreted as an "SSL *" instead of as a "BIO_SSL *". For my case, this is resulting in a NULL pointer dereference.

This program (invoke with ./a.out <ssl server>) exhibits the crash:
[bio_ssl_shutdown.c](https://github.com/openssl/openssl/files/693920/bio_ssl_shutdown.c.txt)

I think this patch resolves the issue:
[bio_ssl.diff](https://github.com/openssl/openssl/files/693931/bio_ssl.diff.txt)

### PR DESCRIPTION
**Pull request by richsalz**
Thanks to Joseph Bester for finding this and suggesting a fix.
Fixed #2199

### CODE REVIEW

**Comment by t-j-h** [comment]
And if BIO_get_data returns NULL we get a NULL deref - which we should not be having. This is a user function that any valid BIO can be passed into ... and a BIO doesn't have to return non-NULL for BIO_get_data.

And when did BIO_ssl_shutdown get redefined to not actually go through all the BIOs in the stack and perform shutdown on them all - this was a while loop. That is a significant behaviour change. Looks to me like a 1.1 regression.

**Comment by richsalz** [comment]
Updated commit pushed that addresses @t-j-h's issues, and restores the old behavior.

**Comment by bernd-edlinger** [comment]
Just as a side note: BIO_get_data is used everywhere without null-pointer check.
Apparently it is guranteed to be non-zero in ssl_new?

**Comment by richsalz** [comment]
ping @t-j-h to reconfirm.

**Comment by richsalz** [comment]
9015d34 in master and 5180091 in 1.1.0  Thanks!

**Pull request closed without merging**
