### PR TITLE
Configurations/10-main.conf: remove redundant -pthread in ex_libs.

### PR DESCRIPTION
**Pull request by dot-asm**
Presumed rationale behind adding -pthread to ex_libs is that it's
listed as linker flag in gcc online docs. But it's a multi-stage flag,
i.e. one that applies to multiple stages, not link alone. Since we *do*
use cflags at *all* stages, it's only appropriate to list multi-stage
flags there, as opposite to trying to limit them to corresponding
stages.

For reference, HP-UX targets are handled in #5742. And yes, this is triggered by exchange in #5742. Just in case, as it stands now (i.e. without suggested modification) binaries are linked with double -pthread flags, at least on Linux, so that one -pthread flag *is* in fact redundant. [And it's argued that one in ex_libs is.]

### CODE REVIEW

**Comment by levitte** [comment]
I want to go through the general discussion about these on openssl-project first.

**Comment by dot-asm** [comment]
Note that I argue that what is discussed on the list and this request are kind of separate issues. Not without some overlap, but different. Namely that even *if* we go for further fragmentation of make variables, it would still be appropriate to collect mult-stage flags in one variable. As long as it actually works of course. And it does as it stands here. Also note that assertion is that without suggested modification linking is performed with two -pthread flags and one *is* in fact redundant. One can also put it this way. Since it's hardly appropriate to make bigger changes like further fragmentation of make variables in 1.1.1, removal of redundant -pthread can be considered desirable. Or on other words one can view redundant -pthread as kind of a bug in 1.1.1 :-)

**Comment by petrovr** [comment]
Andy Polyakov wrote:
> Presumed rationale behind adding -pthread to ex_libs is that it's
> listed as linker flag in gcc online docs. But it's a multi-stage flag,
> i.e. one that applies to multiple stages, not link alone. Since we *do*
> use cflags at *all* stages, it's only appropriate to list multi-stage
> flags there, as opposite to trying to limit them to corresponding
> stages.
 From openssl point of view there is no problem to put in cflags.
The problem is that -pthread flag from ex_libs goes in package config 
file (*.pc).
So removing from ex_libs you reintroduce already fixed issue.

-1 for proposed patch as is.

P.S.:
For protocol (follow-up  issue #5742 ) you could check gcc specs file, 
where option -pthread:
a) defines -D_REENTRANT unconditionally
b) adds library -lpthread conditionally

**Comment by kroeckx** [comment]
So I think there are at least 4 stages where a flag could
potentionally be used:
- compiling our libraries
- creating the library
- compiling apps or other projects
- linking apps or other projects

And for that last step there are 2 different cases: shared or static

For instance, when linking with the static library they should also
add -ldl. I'm not sure if they should use -lpthread or -pthread,
I'm not sure there is a difference, and -pthread will probably do
the right thing. When linking with the shared library they don't
need to do this.

**Comment by dot-asm** [comment]
> The problem is that -pthread flag from ex_libs goes in package config

Oh! Good catch! Hmm... I'd say it's unfortunate that there is redundant flag, but it's apparently kind of intentional... Or more specifically byproduct of something else... Fair enough! I don't quite follow why -lpthread didn't work or viewed more appropriate. Well, -pthread does add -lpthread in specific place, just before -lc, so it might be meaningful. Is this it? For reference, #5134.

**Comment by dot-asm** [comment]
Closing in favour of #5749.

Just in case, even though there is some overlap with discussion on the list, the problem [of excessive variable fragmentation] is not limited to this issue.

**Comment by levitte** [comment]
Thanks for the reminder, @petrovr.  @dot-asm, for reference: #5134

**Comment by levitte** [comment]
Gah, comments appearing after I submit my comment!  Sorry for the repeat

**Pull request closed without merging**
