### PR TITLE
Update aes_ige.c

### PR DESCRIPTION
**Pull request by VolVox99**
Changed N_WORDS (Derogatory Term) to NUM_WORDS which is not problematic and also makes the code more readable

### CODE REVIEW

**Comment by t8m** [comment]
This would be acceptable with CLA: trivial. If you are OK with that, please add CLA: trivial in a separate line to the commit message.

**Comment by kaduk** [comment]
The preferred thing to do is to add to the past commit's message, yes.
(Also, I note that a merge commit has been added since t8m's last comment -- we don't use merge commits for the official repo, so a rebase or other fixup will be needed at some point.)

I don't think github exposes a direct UI that lets you change the commit message of an existing commit from the web (or rather, to make a new commit that has the content of the existing commit but a different commit message, since the contents of the commit message are included in the hash that identifies the commit).  Typically on a system with a git CLI installed that would be something like `git checkout patch-1` to move onto the topic branch in question, then `git reset --hard HEAD~` to remove the merge commit, and `git commit --amend` to open an editor that will let you add the "CLA: trivial" line to the body of the commit message.  Then you would `git push <name-of-github-remote> +patch-1` to force-push (that's the `+` part) the branch with the modified commit.  But if you are unfamiliar or uncomfortable with git CLI usage like that, it's probably simplest to just "start over" and redo the commit on a different branch, which I think would then entail closing this PR and opening a new one with the fixed commit.

**Comment by VolVox99** [comment]
Done. Appreciate the detailed instructions!

**Comment by paulidale** [comment]
The CLA: trivial part needs to be on a line by itself.  Amending the commit again and adding some newlines ought to achieve this.

**Comment by VolVox99** [comment]
Stringent. Got it.

**Comment by paulidale** [comment]
OTC question: [b]should we make changes to IGE mode?[/b]
Refer to @slontis's comment.

**Comment by paulidale** [comment]
OTC: this change won't be included.

**Pull request closed without merging**
