### PR TITLE
Add DH key validation to default provider

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Dependent on PR #10910 (which depends on #10860 + #10897) and #10780

**Comment by slontis** [comment]
tests can only be added after keygeneration is implemented in the provider.

**Comment by levitte** [comment]
Darnit.  This was visually fine, but the failing CIs made me back off.  Rebase and we'll try again?

**Comment by slontis** [comment]
Rebase seemed to clear up the travis issues

**Comment by slontis** [comment]
rebased to fix test..

**Comment by slontis** [comment]
Merged to master.

**Pull request closed without merging**
