### PR TITLE
test_external_oqsprovider: Use working checkout of liboqs

### LINKED ISSUE #18898: oqsprovider external test failing on master
The last two github CI master builds have failed in the oqsprovider external test:

https://github.com/openssl/openssl/runs/7551684870?check_suite_focus=true
https://github.com/openssl/openssl/runs/7554971041?check_suite_focus=true

But the one before that was fine:

https://github.com/openssl/openssl/runs/7541090009?check_suite_focus=true

The PR that got pushed where the state seemed to change (#18878) is a documentation only change so it doesn't seem like it could be the culprit. So I'm not sure what's changed to cause this.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #18898

Urgent because the CI is broken.

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by t8m** [comment]
Reverted the part that updated the oqs provider as that was causing a build failure too. @mattcaswell please re-approve. Also OK with urgent?

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Reapproved. Yes - I'm ok with urgent.

**Comment by t8m** [comment]
ping for second review

**Review by beldmit — APPROVED** [review]
LGTM taking urgency into account

**Comment by t8m** [comment]
Merged to master branch. Thank you for the reviews.

**Comment by baentsch** [comment]
@t8m @mattcaswell Apologies for the mistake not merging interrelated changes in `liboqs` and `oqs-provider` in lockstep. We'll do our best to avoid this going forward. The change in this PR can be reverted any time now that the two libs are in sync again. OK for me to do a corresponding PR?

**Comment by t8m** [comment]
@baentsch Feel free to do it. Please note though that when I updated the oqs-provider in the submodule I've got a different CI failure.

**Comment by t8m** [comment]
Also please note that with this checkout we will not break CI on any future breaking changes in liboqs. So if you create a PR, please keep the concrete known-working checkout of liboqs in the test script.

**Comment by baentsch** [comment]
> please keep a concrete known-working checkout of liboqs in the test script.

ACK. We're planning on doing a release soon, so will do a PR then with known-good/"LTS" liboqs/oqs-provider combination (and then regular update PRs here to bring in new versions as both projects progress: OK?) -- that way such issues shouldn't cause issues at OpenSSL again.

**Comment by mattcaswell** [comment]
There's also oqs external test related changes in #18132 which might be impacted by this

**Comment by baentsch** [comment]
> There's also oqs external test related changes in https://github.com/openssl/openssl/pull/18132 which might be impacted by this

I just reviewed the oqs-provider related changes in #18132 and they look good to me, i.e., no impact after the change done in https://github.com/open-quantum-safe/oqs-provider/pull/56

**Pull request closed without merging**
