### PR TITLE
update documentation EVP_PKEY_gettable_params.pod

### PR DESCRIPTION
**Pull request by PeiweiHu**
CLA: trivial

fix unconsistency between source code and documentation caused by commit 4e92d5c79d501d09a978fd896c715da07902d8b7

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by PeiweiHu** [comment]
I signed cla already.

**Review by paulidale — APPROVED** [review]
Agreed, trivial

**Comment by paulidale** [comment]
You will need to amend the git commit to include the CLA: trivial line: git commit --amend; git push -f

**Comment by PeiweiHu** [comment]
> You will need to amend the git commit to include the CLA: trivial line: git commit --amend; git push -f

Thanks for your reminder. Done.

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
Merged to master and 3.0 branches after rewording the commit message to make it more descriptive. Thank you for your contribution.

**Pull request closed without merging**
