### PR TITLE
Const EC_KEY_dup

### PR DESCRIPTION
**Pull request by richmoore**

### CODE REVIEW

**Comment by richsalz** [comment]
+1.  Needs another reviewer.  This closes https://rt.openssl.org/Ticket/Display.html?id=4638

**Comment by levitte** [comment]
A look at the travis builds will also give you some details

**Comment by richmoore** [comment]
Thanks, --strict-warnings was a good tip!

**Comment by levitte** [comment]
+1

**Comment by levitte** [comment]
Noted @richsalz' +1, I'll merge

**Comment by richsalz** [comment]
also a +1 for you to merge in "make update" since the CMS change didn't include that; my goof. :(
#1355

**Comment by levitte** [comment]
Merged

**Comment by levitte** [comment]
make update added

**Pull request closed without merging**
