### PR TITLE
Coverity: hkdf ENV_MD_size() is an int that can be negative

### PR DESCRIPTION
**Pull request by slontis**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by kroeckx** [comment]
EVP_MD_size() only return -1 when you call it with md == NULL. I suggest that you check the argument first, in which case there is no point in checking it's return value.

**Comment by slontis** [comment]
I am not sure looking at the internals of the function to figure out what to test is a great idea. It also calls md->size() inside EVP_MD_size() which may or may not return -1 in some case in the future.

**Comment by t-j-h** [comment]
@kroeckx  EVP_MD_size can return -1 and pre-checking arguments to test for that is the wrong approach IMHO.
It's return value should be checked like @slontis is doing here.

We do not document that EVP_MD_size only returns -1 if the MD is NULL and that would be a prerequisite for taking that sort of approach IMHO.

**Comment by kroeckx** [comment]
I guess I didn't express myself properly. I think we should not
rely on the NULL check inside EVP_MD_size(), but check for NULL
ourself before calling it.

**Comment by slontis** [comment]
@mattcaswell Do you have an opinion on this?

**Comment by paulidale** [comment]
I'm happy with both checks.

**Comment by t-j-h** [comment]
@kroeckx that still does not alter this code for this PR - as the return can be -1 and hence it must be handled. Checking for NULL or not before is an entirely separate item and won't make a difference. When we know the code checks for NULL adding additional checks outside does not make sense IMHO.

But as your feedback isn't about removing the check-for-negative-results then this PR should go in as-is IMHO.

**Comment by mattcaswell** [comment]
Note that with providers, EVP_MD_size will call the md implementation inside the provider to find the result. Since we can't know what the provider implementations might do they could return a negative result for reasons other than a NULL input. So its good practice IMO to check the return value from this function.

**Comment by levitte** [comment]
I agree with @kroeckx that a NULL check is *also* good practive.  NULL isn't documented as valid input for `EVP_MD_size`, so while we can look at the code and see that it currently does treat it as valid input, that is undefined behaviour from a documentation perspective ...

(to avoid confusion, I use the term "valid input" as something that won't trigger an assertion, and I consider not checking for NULL input as a hard assertion.  That the input may trigger a run-time error doesn't matter)

**Comment by slontis** [comment]
I cant see any paths that are not checking for md being NULL. Most functions are static in this file, so there is only a few entry points which are doing the NULL check.

**Comment by kroeckx** [comment]
Feel free to merge it

**Comment by paulidale** [comment]
Merged, thanks everyone.

**Pull request closed without merging**
