### PR TITLE
Drop BIO_R_NULL_PARAMETER error code

### PR DESCRIPTION
**Pull request by zsugabubus**
It is only used at two places and those two places are also go against
common sense.

CLA: trivial

##### Checklist
- [x] documentation is added or updated

### CODE REVIEW

**Comment by t8m** [comment]
We cannot drop an existing error code as that would break the API compatibility with 1.1.1.

You could drop the places that are returning it however I do not see much sense in doing that.

We recently added more such NULL checks to other API calls so it would go against that direction to drop it here.

**Comment by zsugabubus** [comment]
Hmm. I came across this issue because I did `BIO_write(x, NULL, 0)` and it strangely failed. Then maybe checking for `inl == 0` could be moved upwards a bit instead?

> We recently added more such NULL checks to other API calls
   
Maybe dangling pointers should be checked too to avoid painful segfaults.

> so it would go against that direction to drop it here.

Maybe it is only me but reading/writing nothing to/from any address seems totally valid. Method does nothing yet fails? What if it should do something. On the other hand, if I say `BIO_write(x, (void *)0xdeadbeef, 0)` it succeeds but between the two the latter seems much less valid. (In my opinion.)

**Comment by t8m** [comment]
What would be the expected outcome of the `BIO_write(x, NULL, 0)` call? If nothing, then why do you call it?

But yeah, moving the in == NULL check after the inl  == 0 check would probably be acceptable.

**Comment by zsugabubus** [comment]
> What would be the expected outcome of the BIO_write(x, NULL, 0) call? 

Should be the same result as `BIO_write(x, (void *)(rand() + 1), 0)`, i.e. x stays the same and success. Guess that’s how most other `*write*()` works.

> If nothing, then why do you call it?

I use it on a code path that may append some data or may not. When I append nothing, buffer may be NULL (since malloc(0) can be NULL). I would like to keep things compact and nice by relying on this behavior.

**Comment by t8m** [comment]
I do not think this is relevant anymore. Closing.

**Pull request closed without merging**
