### PR TITLE
Cleanup error reporting providers

### PR DESCRIPTION
**Pull request by levitte**
Error reporting in `providers/` is changed to make better use of the newer ERR building blocks, and to drop the old function codes everywhere.

### CODE REVIEW

**Comment by slontis** [comment]
Not quite sure I understand the separation..
Aren't quite a few of the files in crypto (e.g crypto/rsa) include into the provider (and these contain RSAErr?)

**Review by paulidale — APPROVED** [review]
A thought, should all of the `*_F_*` macros be deprecated?
It should just be wrapping that part of the header file with the appropriate ifdef.

**Comment by levitte** [comment]
> A thought, should all of the `*_F_*` macros be deprecated?

Not in this PR.  `util/mkerr.pl` adds them automatically, and I believe that we're already treating that problem elsewhere

**Review by paulidale — APPROVED** [review]

**Comment by levitte** [comment]
Merged

6debc6ab7499745baf7123e69936a9997dbbe6cb Convert all {NAME}err() in providers/ to their corresponding ERR_raise() call

**Pull request closed without merging**
