### PR TITLE
Fix GOST OID

### PR DESCRIPTION
**Pull request by Voev**
CLA: trivial

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
Could you please leave this PR for me to merge?

**Comment by Voev** [comment]
@beldmit, I do not mind. What actions are required of me?

**Comment by beldmit** [comment]
Successfully pushed into master.
Thank you very much for your contribution!

**Comment by Voev** [comment]
I saw that the changes are merged into the master, but this error is stretching from version 1.1.1. @beldmit , could you merge the changes into 1.1.1 version too?

**Comment by beldmit** [comment]
Do we need to reconfirm this PR for 1.1.1?

**Comment by mspncp** [comment]
> Do we need to reconfirm this PR for 1.1.1?

The rule of thumb is: if it can be cherry-picked without conflicts, then you can push it as it is without creating a separate pull request for it. One prerequisite for that is that you indicate before approval to which branches you intend to push. You can do this by setting the branch labels (here: [master] and [1.1.1]), so that the reviewers know it in advance. 

In your case I would just set the labels in hindsight (which I'll do in a moment) and ask @levitte to reconfirm.

**Comment by beldmit** [comment]
@levitte could you please reconfirm this PR for 1.1.1?

**Comment by mattcaswell** [comment]
Github is doing something wierd and won't allow me to reopen or approve this PR. Anyway, I approve the backport to 1.1.1.

**Comment by mspncp** [comment]
If you hover with the mouse on the [Reopen and comment] button, you'll see the following message:

> The repository that has submitted this pull request has been deleted

Also, at the top it shows 

> 	Voev wants to merge 1 commit into openssl:master from unknown repository

**Comment by mspncp** [comment]
Nevertheless: @beldmit this should not stop you from cherry-picking :-)

**Comment by beldmit** [comment]
Hopefully done.

**Pull request closed without merging**
