### PR TITLE
Fix the info callback

### LINKED ISSUE #5721: TLSv1.3 unexpected InfoCallback after handshake completed
Our Delphi SSL library uses info_callback to check handshake status, in particlar to detect renegotiaton for older TLS protocols.  

With TLSv1.3, once the initial handshake is complete,  there is a second ICB SSL_handshake_start event, which logging shows precedes a New Session Ticket packet.  This ICB breaks our code, because we closed the connection to stop renegotiaton.   Fixed by ignoring it for TLSv1.3, but should it be called atall? 

11:36:25:844 04326370 Start Ssl ReadBIO
11:36:25:856 04326370 ICB> SSL_handshake_start: where=00000010, state=before SSL initialization
11:36:25:864 04326370 ICB> SSL_CB_HANDSHAKE_START
lots cut
11:36:26:256 04326370 ICB> SSL_handshake_done: where=00000020, state=SSL negotiation finished successfully
11:36:26:264 04326370 ICB> SSL_CB_HANDSHAKE_DONE, Error ok
11:36:26:274 04326370 SslHandshakeDone(0) Error=916. Secure connection with TLSv1.3, cipher TLS_AES_256_GCM_SHA384, 256 secret bits (256 total), session reused=False
more cut
11:36:26:345 ProtoMsg: TLS 1.3, State: SSL negotiation finished successfully, Recv, DataLen: 1, Data= 16
!!! unexpected ICB follows
11:36:26:356 04326370 ICB> SSL_handshake_start: where=00000010, state=SSL negotiation finished successfully
11:36:26:362 ProtoMsg: TLS 1.3 Handshake: New Session Ticket, State: SSLv3/TLS read server session ticket, Recv, DataLen: 274, Data=xx 
11:36:26:372 ProtoMsg: None, State: SSL negotiation finished successfully, Recv, DataLen: 5, Data= 17030319EA
11:36:26:396 ProtoMsg: TLS 1.3, State: SSL negotiation finished successfully, Recv, DataLen: 1, Data= 17

Angus

### PR DESCRIPTION
**Pull request by mattcaswell**
The info callback was not receiving all the handshake start and done events that it should in TLSv1.3. This fixes it and adds a test. I also updated the documentation to explain the meaning of the various events in a TLSv1.3 context.

Fixes #5721.

##### Checklist

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
?????

Uhmmmmm...  the appveyor failure looks weird...  why does the compilation of `test\versinos.obj` have no `/I` parameters at all?

As for the Travis one, impossible to analyse because of the ... wisdom of making make silent.  Would you mind hacking the default jobs to set `BUILDONLY=yes` in .travis.yml, specially for this PR, so we have a closer look at what's happening?  Meanwhile, I'll have a closer look at the Windows stuff.

**Comment by levitte** [comment]
BTW, you might want to not include `test/versions` in this PR ;-)
(we need to add it in `.gitignore`)

**Comment by levitte** [comment]
Ahhhh, it's actually the `test/versions` that's in this PR that throws the build system off...  Configure detects it and gets the info in `%unified_info` screwed up as soon as you build out-of-source...  all the cases that succeed build in-source...

That was unforeseen, I'll have a look at Configure to make it more robust against this kind of, err, "attack"

**Comment by levitte** [comment]
But, suffice to say, removing `test/versions` from this PR will fix the odd build failures

**Comment by mattcaswell** [comment]
Gah!! Thanks. Update force pushed.

I'm off to update .gitignore...

**Comment by mattcaswell** [comment]
There was a merge conflict with master. Rebased.

@richsalz - can you reconfirm?

**Comment by richsalz** [comment]
Reconfirm.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
