### PR TITLE
Configure: try to make sure every config target name is unique

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
I knew you'd be doing this :)  But why "try" ?

**Comment by levitte** [comment]
> But why "try" ?

If one file has something like this:

```
(
    "foo" => {
        ...
    },
    "bar" => {
        ...
    },
    "foo" => {
        ...
    },
);
```

.... there's no way for `Configure` to detect the double "foo" entry, perl will already have tossed one of them.

(well, actually, there *is* a way to read it as an array instead of a hash table, read through that array pairwise and check that the first pair half is unique across the array, then convert the array to a hash before insertion into `%table`...  because there is no viable support for pairwise operations as far back as perl 5.10, we have to implement it ourselves, and by now, this description has shown already what level of convolution we're talking about, and for very little gain.  So, err, "try")

**Comment by levitte** [comment]
> I knew you'd be doing this :)

Of course you did, it's such an obvious pattern of mine ;-)

**Comment by levitte** [comment]
Merged. 

master: 225f980d22dfe66aa3945c21609042c32284e61c
1.1.0: bda1af6d5f6f275c78d3145a03a208d8bc056553

**Pull request closed without merging**
