### PR TITLE
Ensure EVP_PKEY_set1_DH detects X9.42 keys

### LINKED ISSUE #10592: EVP_PKEY_set1_DH() fails to correctly assign X9.42 DH keys
OpenSSL supports both PKCS#3 and X9.42 DH keys. However the function `EVP_PKEY_set1_DH` assumes that the provided DH object is a PKCS#3 key and assigns it to the EVP_PKEY object with the `EVP_PKEY_DH` type. It should check what type of DH object it is and then either assign it as `EVP_PKEY_DH` or `EVP_PKEY_DHX` as appropriate.

### PR DESCRIPTION
**Pull request by mattcaswell**
OpenSSL supports both PKCS#3 and X9.42 DH keys. By default we use PKCS#3
keys. The function `EVP_PKEY_set1_DH` was assuming that the supplied DH
key was a PKCS#3 key. It should detect what type of key it is and assign
the correct type as appropriate.

Fixes #10592

### CODE REVIEW

**Comment by mattcaswell** [comment]
Fixup for the travis failure pushed. Please take another look.

**Comment by mattcaswell** [comment]
Travis is now green. Ping?

**Comment by mattcaswell** [comment]
Pushed to master and 1.1.1. I fixed a trivial conflict during the cherry-pick to 1.1.1.

**Comment by bernd-edlinger** [comment]
looks like this broke something on 1.1.1 branch:
```
 if $make2; then echo -e '+\057\057\057\057 MAKE OK'; else echo -e '+\057\057\057\057 MAKE FAILED'; travis_terminate 1; fi;

ar: creating apps/libapps.a

ar: creating libcrypto.a

ar: creating libssl.a

ar: creating test/libtestutil.a

test/evp_extra_test.c: In function 'test_EVP_PKEY_set1_DH':

test/evp_extra_test.c:1145:5: error: implicit declaration of function 'DH_get_2048_256' [-Werror=implicit-function-declaration]

     x942dh = DH_get_2048_256();

     ^

test/evp_extra_test.c:1145:12: error: assignment makes pointer from integer without a cast [-Werror]

     x942dh = DH_get_2048_256();

            ^

test/evp_extra_test.c:1146:5: error: implicit declaration of function 'DH_new_by_nid' [-Werror=implicit-function-declaration]

     pkcs3dh = DH_new_by_nid(NID_ffdhe2048);

     ^

test/evp_extra_test.c:1146:13: error: assignment makes pointer from integer without a cast [-Werror]

     pkcs3dh = DH_new_by_nid(NID_ffdhe2048);

             ^

test/evp_extra_test.c:1155:5: error: implicit declaration of function 'EVP_PKEY_set1_DH' [-Werror=implicit-function-declaration]

     if(!TEST_true(EVP_PKEY_set1_DH(pkey1, x942dh))

     ^

test/evp_extra_test.c:1168:5: error: implicit declaration of function 'DH_free' [-Werror=implicit-function-declaration]

     DH_free(x942dh);

     ^

cc1: all warnings being treated as errors

make[1]: *** [test/evp_extra_test.o] Error 1

```

I never finished adding the minimal build config on master, because that was to unstable
at that time.

**Comment by mattcaswell** [comment]
> looks like this broke something on 1.1.1 branch:

Hmmm. I can't recreate this build failure. How did you configure?

**Comment by mattcaswell** [comment]
Ah...`no-dh` seems to cause it.

**Comment by bernd-edlinger** [comment]
I think we should continue on enabling the minimal build config on master.
see #9982 and #9980 if we had those installed, you would know earlier when something breaks.

**Comment by mattcaswell** [comment]
Fix for this in #10644.

**Pull request closed without merging**
