### PR TITLE
`X509V3_get_d2i.pod`: Fix glitch on X509V3_get_ext_d2i vs. X509V3_get_d2i

### PR DESCRIPTION
**Pull request by DDvO**
Also align the order of the functions in the various sections.

Should this be backported?

- [x] documentation is added or updated

### CODE REVIEW

**Comment by t8m** [comment]
> Should this be backported?

I think why not.

**Comment by DDvO** [comment]
> Approved.

Thanks for the quick approvals.

> You could consider, if you're already touching the file, using `I<>` for arguments and removing `B` around NULL. (in a separate commit)

Good point, done.

**Review by t8m — APPROVED** [review]

**Review by mattcaswell — APPROVED** [review]

**Comment by DDvO** [comment]
Merged and backported to 3.0 - thanks @t8m and @mattcaswell.

**Comment by DDvO** [comment]
I just found that backporting to 1.1.1 would require some conflict resolution, thus likely an extra PR - 
I am uncertain if it is worth doing so.

**Comment by t8m** [comment]
> I am uncertain if it is worth doing so.

I do not think it is.

**Comment by mattcaswell** [comment]
Closing this since it has been merged.

**Pull request closed without merging**
