### PR TITLE
(1.1) Add SSL_(CTX_)?get0_(verify|chain)_cert_store functions

### LINKED ISSUE #18035: Function to retrieve value set by SSL_CTX_set1_verify_cert_store()
Currently we do not have a way to retrieve the `X509_STORE *` set in `SSL_CTX_set1_verify_cert_store`. We should consider adding a `SSL_CTX_get_verify_cert_store` function.

### PR DESCRIPTION
**Pull request by hlandau**
Backport of #18038 to 1.1.

Fixes #18035.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by petrovr** [comment]
Hugo Landau wrote:
> Backport of #18038 to 1.1.
>
> []
>    * (1.1) Add SSL_(CTX_)?get0_(verify|chain)_cert_store functions
>
Adding new exported function in LTS release does not make sense.

It is expected an application to keep binary compatibility, i.e. it should work with all 1.1 releases.
With other words application cannot use them if is build with 1.1, i.e. back-port is needless.

Regards,
Roumen Petrov

**Comment by t8m** [comment]
> It is expected an application to keep binary compatibility, i.e. it should work with all 1.1 releases. With other words application cannot use them if is build with 1.1, i.e. back-port is needless.

Nope! You always need to build with oldest patch release from the release series that you want to support. I.e. with 1.1.1e if you want to support anything >= 1.1.1e.

You should never build with 1.1.1n and expect it to work correctly with 1.1.1m.

Adding accessors in stable releases is allowed by policy.

**Comment by petrovr** [comment]
Tomáš Mráz wrote:
>> It is expected an application to keep binary compatibility, i.e. it should work with all 1.1 releases. With other words application cannot use them if is build with 1.1, i.e. back-port is needless.
> 
> Nope! You always need to build with oldest patch release from the release series that you want to support. I.e. with 1.1.1e if you want to support anything >= 1.1.1e.


Which build system allows this. Build is always with system libraries and many vendors do upgrades.


> 
> You should never build with 1.1.1n and expect it to work correctly with 1.1.1m.

Thanks for useless suggestion. This part is of scope.


> 
> Adding accessors in stable releases is allowed by policy.

Quite interesting interpretation of a policy.



Regards,
Roumen Petrov

**Comment by t8m** [comment]
> > Adding accessors in stable releases is allowed by policy.
> Quite interesting interpretation of a policy.

See the last item on https://www.openssl.org/policies/releasestrat.html

- When structures are made opaque, any newly required accessor macros or functions are added in a feature release of the extant LTS release and all supported intermediate successor releases.

**Comment by t8m** [comment]
Ping for second review.

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by paulidale** [comment]
Merged.

**Pull request closed without merging**
