### PR TITLE
Validate ClientHello session_id field length and send alert on failure

### PR DESCRIPTION
**Pull request by ghedo**
RT#4080

So, the check was already present, but it wasn't considered a fatal failure. Not sure what to think of this...

### CODE REVIEW

**Comment by ghedo** [comment]
Ping? The bug isn't exactly high priority but still worth fixing IMO. I can probably simplify the patch, but that would mean doing the check later after the whole ClientHello has already been parsed, not sure if a problem or not.

/cc @tomato42

**Comment by richsalz** [comment]
ping @mattcaswell

**Comment by mattcaswell** [comment]
Looks reasonable but is there a 1.0.2/1.0.1 version? The RT ticket says they are affected too.

**Comment by ghedo** [comment]
@mattcaswell patch for 1.0.2 and 1.0.1 is at:
https://github.com/ghedo/openssl/commit/72d6bbc66eee552a0b9c07485d3b8717261b641d

Should I open a new PR?

**Comment by mattcaswell** [comment]
Yes please

**Comment by ghedo** [comment]
See #545 and #546 (the patch is the same, just applied to different branches).

**Comment by ghedo** [comment]
@mattcaswell ping?

Note that I rebased the patch on master and fixed a small style issue.

**Comment by mattcaswell** [comment]
+1

**Comment by richsalz** [comment]
+1 if whoever submits fixes matt’s nit ☺

**Comment by ghedo** [comment]
@richsalz this PR doesn't need nit fixing AFAICT, and the other PRs are already fixed, so go ahead and merge, maybe? :)

**Comment by mattcaswell** [comment]
I will merge shortly

**Comment by mattcaswell** [comment]
Patch applied. Thanks.

**Pull request closed without merging**
