### PR TITLE
Add support for fuzzing with AFL

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by levitte** [comment]
May I suggest adding a Travis case for this, for demonstration purposes?

**Comment by kroeckx** [comment]
You think something like afl-clang will be installable on travis?

**Comment by ghedo** [comment]
Also, I don't think we want to run this on Travis since it will just run forever (like, literally).

Anyway, there's a typo in the commit message :)

**Comment by kroeckx** [comment]
I think it was only building it, not running the fuzzing.

**Pull request closed without merging**
