### PR TITLE
Ensure we initialized the locale before evp_pkey_name2type

### LINKED ISSUE #18158: A regression is introduced by #18103
```
#include <openssl/ec.h>
#include <openssl/evp.h>
#include <openssl/err.h>

int main(int argc, char *argv[])
{
        EVP_PKEY_CTX *pctx = NULL;
        int ret = 1;

        if ((pctx = EVP_PKEY_CTX_new_from_name(NULL, "RSA", NULL)) == NULL) {
                ERR_print_errors_fp (stderr);
                goto done;
        }

        ret = 0;
done:
        EVP_PKEY_CTX_free(pctx);

        return ret;
}
```
crashes with a segfault
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff79732f8 in __strcasecmp_l_avx () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff79732f8 in __strcasecmp_l_avx () from /lib64/libc.so.6
#1  0x00007ffff7c618aa in OPENSSL_strcasecmp (s1=0x402010 "SM2", s2=0x7ffff7de74ca "RSA") at crypto/ctype.c:350
#2  0x00007ffff7c45e93 in evp_pkey_name2type (name=0x402010 "SM2") at crypto/evp/p_lib.c:1019
#3  0x00007ffff7c4b811 in int_ctx_new (libctx=0x0, pkey=0x0, e=0x0, keytype=0x402010 "SM2", propquery=0x0, id=-1) at crypto/evp/pmeth_lib.c:202
#4  0x00007ffff7c4bd43 in EVP_PKEY_CTX_new_from_name (libctx=0x0, name=0x402010 "SM2", propquery=0x0) at crypto/evp/pmeth_lib.c:368
#5  0x0000000000401178 in main ()
```
Because we didn't init either default context or called OPENSSL_init_crypto before calling `evp_pkey_name2type`

### PR DESCRIPTION
**Pull request by neverpanic**
Fixes #18158
This is #18159 with the review feedback incorporated, since @beldmit is currently not at a machine where he can do the changes himself.

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
This is applicable to 3.0 only as in master the ossl_init_casecmp is a RUN_ONCE.

**Review by beldmit — APPROVED** [review]
Approved if CI passed

**Comment by beldmit** [comment]
I agree it's urgent

**Comment by t8m** [comment]
@beldmit as you're the co-author, this requires one more approval.

**Comment by beldmit** [comment]
@t8m sure

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
I agree this is urgent

**Comment by mattcaswell** [comment]
> This is applicable to 3.0 only as in master the ossl_init_casecmp is a RUN_ONCE.

So is an alternative fix required in master?

**Comment by mattcaswell** [comment]
Pushed to 3.0...I'm not clear if we need an equivalent fix for master

**Comment by beldmit** [comment]
I'm afraid we need. Could you please run the test added in this PR in master?

**Comment by t8m** [comment]
Yes, we need an alternative fix in master.

**Comment by t8m** [comment]
We can use https://github.com/openssl/openssl/pull/18159 for the fix on master.

**Comment by beldmit** [comment]
@t8m could you please open the issue to not forget about it?

**Comment by t8m** [comment]
There is no hurry to fix this there.

**Pull request closed without merging**
