### PR TITLE
Make enc -ciphers output consistent across multiple invocations

### PR DESCRIPTION
**Pull request by pauli-oracle**
Make the output of enc -ciphers identical even if run several times in a session.

The old output looked like this the first time:
```
OpenSSL> enc -ciphers
Supported ciphers:
-aes-128-cbc               -aes-128-cbc-hmac-sha1     -aes-128-cbc-hmac-sha256  
...
-seed-ofb                  
```

and this the second:
```
OpenSSL> enc -ciphers
Supported ciphers:
-aes-128-cbc               -aes-128-cbc-hmac-sha1    
...
-seed-ecb                  -seed-ofb    
```

This amounts to moving the column counter so it isn't a function local static variable and reinitialising it each time.

### CODE REVIEW

**Comment by pauli-oracle** [comment]
1.0.2 doesn't look like a terrible port, just not automatic.  I doubt there is a pressing need, so considering it a feature sounds fine :)

**Comment by levitte** [comment]
If it's a new feature, this should really be taken to master only...

**Comment by richsalz** [comment]
it's a bug-fix.  Do this:
```
openssl
enc ciphers -v
enc cphers -v
```

**Comment by levitte** [comment]
If it's a bug fix, I think a patch for 1.0.2 is warranted.

**Comment by richsalz** [comment]
OpenSSL_1_0_2-stable 2566388 Make the output of enc -ciphers identical
OpenSSL_1_1_0-stable 57e73ef Make the output of enc -ciphers identical
master               2b305ab Make the output of enc -ciphers identical even if run several times in a session.

closed.  (@levitte, I took your "it's a bugfix" as approval to cherry-pick to 1.0.2)

**Comment by levitte** [comment]
(good call, @richsalz)

**Pull request closed without merging**
