### PR TITLE
`cmp_client_test.c`: add tests for `OSSL_CMP_CTX_get_status`

### PR DESCRIPTION
**Pull request by DDvO**
This is a follow-up of #19205, adding test cases as requested.

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Comment by DDvO** [comment]
Rebased to fix new merge conflict in `test/cmp_client_test.c`

**Review by t8m — APPROVED** [review]
@paulidale please re-approve.

**Comment by t8m** [comment]
Please do not forget to remove `tests: deferred` from #19205 when this is merged.

**Comment by DDvO** [comment]
> Please do not forget to remove `tests: deferred` from #19205 when this is merged.

Will do, though then the PR won't have any label regarding tests any more.
Yet then adding `tests:present` also seems not appropriate.

**Comment by t8m** [comment]
> Will do, though then the PR won't have any label regarding tests any more.
> Yet then adding `tests:present` also seems not appropriate.

This is correct. PRs without label, merged after the date this policy change went in, are supposed to have tests present in another merged PR.

**Comment by DDvO** [comment]
@paulidale could you please re-approve.

**Review by paulidale — APPROVED** [review]

**Comment by vanessalcataldo** [comment]
Why do I keep constantly getting 


Vanessa Cataldo 

On Monday, November 28, 2022, 8:35 PM, Pauli ***@***.***> wrote:




@paulidale approved this pull request.

**Comment by DDvO** [comment]
Merged to master, 3.0, and 3.1
Thanks @t8m and @paulidale

**Comment by DDvO** [comment]
> Please do not forget to remove `tests: deferred` from #19205 when this is merged.

Done

**Comment by DDvO** [comment]
> Please do not forget to remove `tests: deferred` from #19205 when this is merged.

Done

**Pull request closed without merging**
