### PR TITLE
Additional name for all commands

### PR DESCRIPTION
**Pull request by richsalz**
Add openssl-foo as a name for the openssl "foo" command.
Addresses an issue found by a usability study to be published.

Fixed: #4548

### CODE REVIEW

**Comment by t-j-h** [comment]
It might make sense to have openssl-command work for the openssl app itself too.

**Comment by t-j-h** [comment]
i.e. openssl openssl-version -a etc

**Comment by levitte** [comment]
> i.e. openssl openssl-version -a etc

I disagree with that.  It over complicates things unecessarely.  The synopsis of the manpages make it clear that the command is `openssl version` etc

**Comment by levitte** [comment]
@richsalz, it would be good if you added this line in the commit message:

```
Fixes #4548
```

**Comment by t-j-h** [comment]
For other contexts if you have x-y as a man page section 1 name then running x-y works. See git examples - all of git-x are available as commands as well as "git x". And for the super app we would need to have openssl-command recognised? I think it adds to confusion to have man pages for commands that don't exist.

**Comment by levitte** [comment]
Aha, that's different.  So what you're suggesting is that we could have this work:

```
$ openssl-version -a
```

That I could accept.

Regarding git, that's not quite right.  It is correct when the command `git x` is really just a redirect to the script `git-x`, but not otherwise.  For example, `git-commit` doesn't work, because the `commit` sub-command is internal to the `git` binary.

**Comment by mspncp** [comment]
I saw you added the 1.1.0 label. Would it be a great deal to add this usability improvement to 1.0.2., too?

**Comment by richsalz** [comment]
I did a separate PR #4557

**Comment by levitte** [comment]
I saw that you merged this into master...  did you forget about 1.1.0 or am I just looking too fast?

**Comment by richsalz** [comment]
I just hadn't pushed.  Yup.  Done now.  Thanks.

**Comment by levitte** [comment]
Thanks

**Pull request closed without merging**
