### PR TITLE
Update rand_win.c

### PR DESCRIPTION
**Pull request by wgracz**
To support systems prior to Windows Vista and yet use Next Generation Cryptography on modern ones, I suggest to use BCryptGenRandom dynamically instead of static linking.

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by mspncp** [comment]
Thank you @wgracz for your contribution. Did you note that there is a similar pull request in #8916?

**Comment by paulidale** [comment]
I'm putting the same hold for the same reason as #8916

**Comment by romen** [comment]
> This PR is in a state where it requires action by @openssl/otc but the last update was 92 days ago

This PR actually requires action by the contributor, @wgracz, to solve both the CLA status and to reconcile the duplicate efforts with #8916.

**Comment by mattcaswell** [comment]
OTC: The current compile time switching is considered sufficient. Closing this PR.

**Pull request closed without merging**
