### PR TITLE
Fix the null pointer dereference

### LINKED ISSUE #17296: null pointer dereference possible in BN_hex2bn
The use case:
1 bn == NULL
2 if (i == 0 || i > INT_MAX / 4) matched 

int BN_hex2bn(BIGNUM **bn, const char *a)
{

    if (i == 0 || i > INT_MAX / 4)
        goto err;              // 1 if bn == NULL

    num = i + neg;
    if (bn == NULL)
        return num;
err:
    if (*bn == NULL)   // 2 null pointer dereference 
        BN_free(ret);
    return 0;
}

### PR DESCRIPTION
**Pull request by KanPlus**
Fixes #17296

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
The issue is on 1.1.1 as well but the PR won't apply cleanly there.

**Comment by KanPlus** [comment]
> The issue is on 1.1.1 as well but the PR won't apply cleanly there.

bn_print.c should be update on 1.1.1, should this raise in this PR?

**Comment by KanPlus** [comment]
> > The issue is on 1.1.1 as well but the PR won't apply cleanly there.
> 
> bn_print.c should be update on 1.1.1, should this raise in this PR?

#17302 raised

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to 3.0 and master, thanks for the fix.

**Pull request closed without merging**
