### PR TITLE
Make err_clear_constant_time really constant time

### PR DESCRIPTION
**Pull request by bernd-edlinger**
So finally trying to fix err_clear_constant_time

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
The old code was only constant time when it is used once.
BUT if a padding error is there we push two error codes, one in `RSA_padding_check_PKCS1_type_2`
and a second one in `rsa_ossl_private_decrypt`.
Now IF there is no error, the same stack location is accessed twice, but if there is
a padding error, a different stack location is accessed.  That makes the whole thing not constant time.
This patch makes sure that ERR_clear_error and ERR_pop_to_mark operate in constant time.
Only ERR_get_error reveals via it's timing the presence of a padding error,
but after private key operation ERR_clear_error should be called in any case since the
error code would prevail and create a padding oracle when accessed later.
I will try to come up with a comment describing that in more detail.

**Comment by bernd-edlinger** [comment]
Additionally the old code had a problem when the error state was not allocated on ERR_put_error
due to malloc failing but err_clear_last_constant_time could allocate a completely uninitialized
error, and screw it up, by the unchecked ` es->top = (top + ERR_NUM_ERRORS - clear) %
ERR_NUM_ERRORS;`

**Comment by paulidale** [comment]
That's a good description.

How's this two line summary:

"Flag error as cleared but remove it elsewhere to avoid two errors accessing the same error stack location, revealing timing information."

**Comment by bernd-edlinger** [comment]
yeah, soonds good.  Thanks.

**Comment by bernd-edlinger** [comment]
Merged to master as 94dc53a, 1.1.1 as 3372618 and 1.1.0 as 2a483a8.
Thanks!

**Pull request closed without merging**
