### PR TITLE
Building: Add modules with DEPENDs to GENERATEd files

### PR DESCRIPTION
**Pull request by levitte**
For files GENERATEd from templates (.in files), any perl module (.pm
file) that the file depends on will automatically be used.

This means that these two lines:

    GENERATE[foo]=foo.in
    DEPEND[foo]=whatever.pm

will emit this command in a Makefile (or corresponding):

    foo: foo.in whatever.pm configdata.pm
    $(PERL) -I. -Ipathto -Mwhatever -Mconfigdata $(SRCDIR)/util/dofile.pl \\
        foo.in > foo

Note that configdata.pm is automatically added, since util/dofile.pl
itself depends on it.

### CODE REVIEW

**Comment by levitte** [comment]
@richsalz, this should interest you in particular.

**Comment by richsalz** [comment]
#10159 needs this :)

I can't understand all the perl, but I hope this gets merged soon.

Are there any internal doc changes needed?

**Comment by levitte** [comment]
> Are there any internal doc changes needed?

Ah, yes, I totally forgot to adjust the build.info doc.

**Review by t8m — DISMISSED** [review]
Makes sense.

**Comment by levitte** [comment]
I still haven't adjusted the docs...

**Comment by levitte** [comment]
Documentation added

**Review by t8m — APPROVED** [review]
Re-approved.

**Comment by levitte** [comment]
Merged.

70d9675342efbc9fe518e082c44f3ad80a1e4671 Building: Add modules with DEPENDs to GENERATEd files

**Pull request closed without merging**
