### PR TITLE
Output RSA keys in PKCS #8 format

### PR DESCRIPTION
**Pull request by kroeckx**
Fixes: #6855

### CODE REVIEW

**Comment by kroeckx** [comment]
I'm not sure if we also want to do this in 1.1.1

**Comment by petrovr** [comment]
Kurt Roeckx wrote:
> [SNIP]
>
>    * Make genrsa use PKCS #8 encrypted private key format
Patch like this will not force my to use new commands.
As user I prefer genrsa and other 'old' commands to print on standard 
error deprecation message in OpenSSL 3.0 and to be removed in 4.0.

Regards,
Roumen Petrov

P.S.
I don't like to see changes in output format in 'release' branch. Once 
was enough ( 
https://gitlab.com/secsh/pkixssh/blob/master/tests/CA/config#L113 ) .

**Comment by kroeckx** [comment]
I think I agree that we don't want to change this in a stable branch.

But I'm not sure what else you're trying to say. And I guess the commit message is also confusing, I should fix that. It now always outputs it in the PKCS #8 format.

The format for an unencrypted file changes from `BEGIN RSA PRIVATE KEY` to `BEGIN PRIVATE KEY`, and for an encrypted from `BEGIN RSA PRIVATE KEY` with Proc-Type and DEK-Info to `BEGIN ENCRYPTED PRIVATE KEY`.

Tools like `openssl rsa` support both format as input.

**Comment by kroeckx** [comment]
I wonder if I should use `PEM_write_bio_PKCS8PrivateKey` instead of `PEM_write_bio_PrivateKey`, and I'm not sure what the difference is from looking at the manual.

**Comment by kroeckx** [comment]
It seems to be doing:
```
int PEM_write_bio_PrivateKey(BIO *bp, EVP_PKEY *x, const EVP_CIPHER *enc,
                             unsigned char *kstr, int klen,
                             pem_password_cb *cb, void *u)
{
    if (x->ameth == NULL || x->ameth->priv_encode != NULL)
        return PEM_write_bio_PKCS8PrivateKey(bp, x, enc,
                                             (char *)kstr, klen, cb, u);
    return PEM_write_bio_PrivateKey_traditional(bp, x, enc, kstr, klen, cb, u);
}
```

**Comment by kroeckx** [comment]
Pushed a new commit message, squashed the patches.

**Comment by levitte** [comment]
Genrsa should be deprecated. If you read openssl(1), you can see that this command is documented as superceded by genpkey. With that in mind, I don't think we should fix these old commands, but rather have them warn loudly that they are deprecated. I think that's what @petrovr tries to say.

**Comment by kroeckx** [comment]
I disagree that genrsa should get deprecated. Genpkey might be
more general, but is not usable without looking at the examples
of the manpage, while everywhere you look people say to use
genrsa.

Maybe you want to turn it into a wrapper for genpkey, but genrsa
should stay.

**Comment by t-j-h** [comment]
This sort of change will break things that are expecting non-PKCS#8 format output. We can convert between the two. Adding an option to control what sort of format comes out (PEM-encryption or PKCS#8) would be useful but I would not change the default output format.

I also wouldn't remove the genrsa application - it is widely used and referenced. 

So if this patch had the PKCS#8 output as a **new** option flag I would +1 it ...

**Comment by kroeckx** [comment]
The pkcs8 tool has a -traditional flag. I suggest to add
-traditional to both rsa and genrsa too, but to change the
default, because it's more secure.

(I just noticed that the rsa manpage at least says that it uses
the traditional format by default, clearly the manpages need
to be updated, and it needs a CHANGES entry)

**Comment by mattcaswell** [comment]
I think it is justified to make this change (in 3.0) since it is for security reasons. I would expect to see associated documentation and CHANGES updates.

**Comment by kroeckx** [comment]
It seems most of this got merged as part of #11225, but without actually documenting it or having an option to return the old format. So I tried to add the -traditional options in genrsa but it segfaults because pkey->ameth isn't set, and I can't figure out how to actually set it.

**Comment by kroeckx** [comment]
ping @openssl/committers

**Comment by levitte** [comment]
A note: _traditional is legacy at this point...  it's not supported in provider side encoders.  With those, PKCS#8 (both encrypted and unencrypted) is used for private keys, and SubjectPublicKeyInfo for public keys.

**Comment by kroeckx** [comment]
Traditional is what 1.1.1 generates. Are you saying we can't read
keys generated by 1.1.1 anymore?

**Comment by levitte** [comment]
> Are you saying we can't read keys generated by 1.1.1 anymore?

Nope, I only talked about *en*coders.  The decoders can still read the old format.

**Comment by kroeckx** [comment]
Note that other tools like pkcs8 also support the -traditional
option. Does that mean that's now broken?

**Comment by levitte** [comment]
I will have to look at that...

**Comment by levitte** [comment]
Ok,  I just realised that `PEM_write_bio_PrivateKey_traditional()` is broken already.  The mechanism depends on that the associated `EVP_PKEY_ASN1_METHOD` (if there is one, these days) has a function `old_priv_encode`.  If not,  it will promptly  use `priv_encode` instead and output a PKCS#8 structure anyway.  This flaw has been around for a long time.

I'll also point out what the manual says and has said for a long time (italics mine):

> **PEM_write_bio_PrivateKey_traditional**() writes out a private key in the "traditional" format with a simple private key marker and *should only be used for compatibility with legacy programs*.

What we can do is to insert some code in `PEM_write_bio_PrivateKey_traditional` that 1) tries to "downgrade" `pkey` to legacy form, and 2) check that `pkey->ameth->old_priv_encode` is non-NULL, or generate an error if it's NULL.  The latter could actually be backported to 1.1.1

**Comment by levitte** [comment]
Travis points out that you need to add documentation for `-traditional` in `doc/man1/openssl-genrsa.pod.in`

**Comment by kroeckx** [comment]
> Travis points out that you need to add documentation for `-traditional` in `doc/man1/openssl-genrsa.pod.in`

I never claimed this PR was complete, I got stuck on implementing
the -traditional flag.

**Comment by levitte** [comment]
> I never claimed this PR was complete, I got stuck on implementing the -traditional flag.

Okie.  Please add a bit of doc.  Other than that, this PR is fine.  I'm dealing with `PEM_write_bio_PrivateKey_traditional()` in #12728 and #12729, and am currently looking into dealing with provider-native keys in as sane a way as possible.

**Comment by kroeckx** [comment]
It seems that rsa and pkcs8 can use -traditional, but for genrsa it fails.

**Comment by levitte** [comment]
> It seems that rsa and pkcs8 can use -traditional, but for genrsa it fails.

Interesting that it should *fail'...  I expected it to give some kind of PEM output, but with PKCS#8 contents.  I'll have a look

**Comment by levitte** [comment]
Ah, of course, `x->ameth` is NULL...

**Comment by levitte** [comment]
I've a bigger ongoing effort to make it handle EVP_PKEYs with provider-native internal keys, I'm afraid this will have to wait until I'm done with that...

**Comment by kroeckx** [comment]
This is now ready for review.

**Review by levitte — APPROVED** [review]
Looks ok

**Comment by kroeckx** [comment]
This is now ready for review.

**Pull request closed without merging**
