### PR TITLE
VMS: More header inclusion compensation for VMS C compiler

### PR DESCRIPTION
**Pull request by levitte**
This was meant to end up with the rest of the fixes in #21951, but
that didn't quite happen...

### CODE REVIEW

**Comment by levitte** [comment]
Marked urgent for the same reason as for #21951

**Review by beldmit — APPROVED** [review]
LGTM if test passed

**Comment by t-j-h** [comment]
It should not be marked as urgent (nor should have the previous one).
That is the not the correct usage of urgent IMHO. 
There is no rush to have to fix this *immediately*.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM, assuming CI passes

**Review by t8m — APPROVED** [review]
I think this is urgent. Especially because it fixes a non-building VMS in CI and we have explicitly mentioned that CI failing fixes are urgent and it also does not touch anything outside VMS builds.

**Review by paulidale — APPROVED** [review]
okay with urgent

**Comment by levitte** [comment]
Merged

e0f4976ac634e8c74231e45f865457edab834324 VMS: More header inclusion compensation for VMS C compiler

**Pull request closed without merging**
