### PR TITLE
When we're just reading EX_CALLBACK data just get a read lock

### LINKED ISSUE #20286: 3.0 performance degraded due to locking
Using some internal QUIC tests, we see this timing in 1.1:
```
$ USE_GQUIC_VERSIONS=1 perf record -F 999 -g ./quic_lib_tests  --gtest_repeat=100  --gtest_filter=*ZeroRttDisabled*
$ perf report

+   31.73%    31.55%  quic_lib_tests  quic_lib_tests       [.] bn_sqr8x_internal
+    9.28%     9.28%  quic_lib_tests  quic_lib_tests       [.] mul4x_internal
+    4.91%     4.91%  quic_lib_tests  quic_lib_tests       [.] sha256_block_data_order_avx
```

In 3.0 we see this:
```

$ USE_GQUIC_VERSIONS=1 perf record -F 999 -g ./quic_lib_tests  --gtest_repeat=100  --gtest_filter=*ZeroRttDisabled*
$ perf report

+   11.02%    10.99%  quic_lib_tests  quic_lib_tests       [.] bn_sqr8x_internal
+    8.38%     8.08%  quic_lib_tests  libpthread-2.31.so   [.] __pthread_rwlock_rdlock
+    7.65%     7.51%  quic_lib_tests  libpthread-2.31.so   [.] __pthread_rwlock_unlock
+    4.98%     4.78%  quic_lib_tests  quic_lib_tests       [.] getrn
+    4.14%     4.11%  quic_lib_tests  quic_lib_tests       [.] mul4x_internal
+    3.37%     2.57%  quic_lib_tests  quic_lib_tests       [.] ossl_tolower
     3.30%     3.30%  quic_lib_tests  quic_lib_tests       [.] ossl_lh_strcasehash
+    2.72%     2.13%  quic_lib_tests  quic_lib_tests       [.] OPENSSL_strcasecmp
+    2.29%     2.05%  quic_lib_tests  quic_lib_tests       [.] ossl_lib_ctx_get_data
+    1.93%     1.93%  quic_lib_tests  quic_lib_tests       [.] sha256_block_data_order_avx
```

This seems to be part of `OSSL_DECODER_CTX_new_for_pkey`  16% of the time is spent in locking, on a *single threaded binary.* And 10% is in a string hashtable lookup.

If anyone on the project is going to look at this, I will try to get a small reproducer. But our the time for our QUIC tests is doubling.

### PR DESCRIPTION
**Pull request by mattcaswell**
The crypto_ex_data code was always obtaining a write lock in all functions regardless of whether we were only reading EX_CALLBACK data or actually changing it. Changes to the EX_CALLBACK data are rare, with many reads so we should change to a read lock where we can.

We hit this every time we create or free any object that can have ex_data associated with it (e.g. BIOs, SSL, etc)

Partially fixes #20286

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Review by hlandau — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
I have some performance test results based on the performance testing application in openssl/tools#148

The test calls `SSL_new()` and `BIO_new()` (twice - once for the read BIO and once for the write BIO), associates the BIOs with the SSL, and then frees them all. It does this repeatedly inside a loop across a specified number of threads. I tested 1, 10, 100, 500 and 1000 threads against 1.1.1, 3.0, 3.1, master and master with this patch.

The numbers given are the average time in us to complete a batch of 100 such sets of calls. Smaller numbers are better.

|  | 1 | 10 | 100 | 500 | 1000 |
| -- | -- | -- | -- | -- | -- |
| 1.1.1 | 203.49 | 125.866 | 348.1522 | 175.5177 | 230.12453 |
| 3.0 | 191.46 | 133.901 | 226.8244 | 206.45852 | 266.52152 |
| 3.1 | 200.83 | 142.235 | 281.4543 | 225.49338 | 279.68857 |
| master | 292.91 | 182.632 | 256.4876 | 237.5036 | 367.52966 |
| master + #20943 | 347.66 | 73.572 | 76.9842 | 96.13856 | 89.43387 |

We can see a clear benefit of this patch.

**Comment by mattcaswell** [comment]
More performance results for this patch in conjunction with #20950 are [here](https://github.com/openssl/openssl/pull/20950#issuecomment-1561329514)

**Comment by t8m** [comment]
@mattcaswell the performance degradation for the single thread case is slightly worrying. Any idea why that happens?

**Comment by t8m** [comment]
**OTC: This is not invasive and it's low risk so it can go in 3.1 and master.**

**Pull request closed without merging**
