### PR TITLE
params: add a warning about the PTR types.

### PR DESCRIPTION
**Pull request by paulidale**
The warning is to deter the unsure -- if in doubt the PTR type is almost certainly
**not** what you should be using.

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
The man page text seems to be OK. The header comment text seems to me to be patronizing too much. I'd use something like `If you are not completely sure you most likely want to use the ...other type`.

**Comment by paulidale** [comment]
I've changed the text.

I'm not sure that this can be blatant enough -- I think that **_everyone_** (except perhaps @levitte) has tried to use PTR types incorrectly.

If you think you should use them, you shouldn't :)

**Comment by t8m** [comment]
Then why do we even provide such thing? :smile:

**Comment by t8m** [comment]
Should the types be named OSSL_PARAM_UTF8_FOR_LEVITTE_ONLY ? :smile:

**Comment by paulidale** [comment]
> Should the types be named OSSL_PARAM_UTF8_FOR_LEVITTE_ONLY ? 😄

Yes.

**Comment by levitte** [comment]
I'd like to hear the background story, i.e how did someone shoot themselves in the foot this time?

**Comment by paulidale** [comment]
It's more an accumulation of feet shot than a single incident.

I've been meaning to add a note like this for a while.

**Comment by levitte** [comment]
> OSSL_PARAM_UTF8_FOR_LEVITTE_ONLY

while I'm kinda flattered (... ... ... I think :pensive:), my self inflation isn't grand enough.  So no...

**Comment by paulidale** [comment]
Merged to master.  Thanks for the comments.

**Pull request closed without merging**
