### PR TITLE
Add accessor function for the ex_nscert data in X509 object.

### PR DESCRIPTION
**Pull request by t8m**
##### Checklist
- [ x ] documentation is added or updated
- [ ] tests are added or updated
- [ x ] CLA is signed

##### Description of change

Subject says it all.

Signed-off-by: Tomas Mraz <tmraz@fedoraproject.org>

### CODE REVIEW

**Comment by mattcaswell** [comment]
Do you actually *have* any cert that needs this? I thought this was all ancient obsolete stuff.

**Comment by t8m** [comment]
I don't I just did not want to regress functionally when porting OpenVPN to the new API.

**Comment by mattcaswell** [comment]
Perhaps @snhenson knows the likelihood of coming across one of these. It *might* be an opportunity for you to retire some dead code from OpenVPN, rather than introduce dead code into OpenSSL ;-)

**Comment by t8m** [comment]
Note I am just patching OpenVPN downstream in Fedora and given the improbability of using such certs with Fedora I will just disable this part of code for us for now.

**Comment by FdaSilvaYY** [comment]
@t8m: `make update`  is required to amend libcrypto.num file with your new methods

**Comment by richsalz** [comment]
I'd prefer to completely kill NS Cert Type.  But if folks need it, then this is a good patch.

**Comment by t8m** [comment]
What would be the right forum to find out whether the NS cert type is still used somewhere or not? I'll ask our NSS folks but they might not know either.

**Comment by richsalz** [comment]
post on the mailing lists (openssl and tlswg?)  there is no definitive way to know, we'll just have to make our best guess.

**Comment by richsalz** [comment]
I will close this PR.  Re-open if you need it.  Thanks!

**Pull request closed without merging**
