### PR TITLE
Patch leak in EVP_PKEY2PKCS8() error path

### PR DESCRIPTION
**Pull request by jwalch**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]
LGTM

**Comment by mattcaswell** [comment]
Side note: I wonder whether the key downgrade in this function can be avoided now that we have @levitte's encoder infrastructure.

**Review by beldmit — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]

**Comment by t8m** [comment]
> Side note: I wonder whether the key downgrade in this function can be avoided now that we have @levitte's encoder infrastructure.

I suppose we would have to convert the key to DER through encoder and then parse that DER data into PKCS8_PRIV_KEY_INFO? Is that worth it when the legacy path has to stay for legacy keys?

**Comment by mattcaswell** [comment]
> I suppose we would have to convert the key to DER through encoder and then parse that DER data into PKCS8_PRIV_KEY_INFO? Is that worth it when the legacy path has to stay for legacy keys?

What about provider only algorithms that have no legacy implementation?

**Comment by t8m** [comment]
Hmm, right, it is unfortunate that we have to go through the full encoding/decoding but I do not see other way.

**Comment by richsalz** [comment]
> What about provider only algorithms that have no legacy implementation?

Wait until someone asks for it?

**Comment by mattcaswell** [comment]
> Wait until someone asks for it?

The other downside to the current implementation is downgrading a key is really quite undesirable and heavyweight IMO. Ideally there should be no such instances at all - except where we need to in order to support deprecated functionality. We seem to have virtually eliminated them - a quick search turned up just 3 instances left (ignoring code that has to be there for deprecated stuff).

**Comment by beldmit** [comment]
Merged. Thanks!

**Pull request closed without merging**
