### PR TITLE
Eai lamps

### PR DESCRIPTION
**Pull request by beldmit**
##### Checklist
- [ ] documentation is added or updated
- [ ] tests are added or updated

##### Description of change
The initial implementation of the https://tools.ietf.org/html/draft-ietf-lamps-eai-addresses-06

### CODE REVIEW

**Comment by FdaSilvaYY** [comment]
-No merge remote-tracking please.
- Tab Indentation is not compliant with project coding-style.
Is this PR related to this : https://tools.ietf.org/html/draft-ietf-lamps-eai-addresses-06

**Comment by beldmit** [comment]
Indentation fixed, thanks!

**Comment by richsalz** [comment]
The EIA stuff is going through another round of edits.  Closing this for now :)

**Comment by vdukhovni** [comment]
The design is converging on:

1. Only rfc822Name constraints, whose domain-valued (host or suffix) elements restrict *both* rfc822Name and SMTPUTF8Name subjectAltNames.
2. To compare an rfc822Name constraint with an SMTPUTF8Name SAN, the constraint domain's A-labels are decoded to UTF-8.

For OpenSSL:
* We MUST NOT add a dependency on libicu. (However, the good news is that decoding from A-labels to UTF-8 does not require libicu, we just need a small stand-alone PunyCode decoder, which we can get from the RFC).
* We'll expect any domains in the name constraints and SMTPUtf8 SANs to have already undergone the UTS#46 mapping. Name constraints inclusions and exclusions on UTF-8 elements will be byte-for-byte comparisons, no normalization or mappings.
* The job of normalizing the reference identifier (via libicu) will be documented to be the responsibility of the application.
* OpenSSL will compare any email address reference identifier against any SMTPUtf8 SANs via a byte-for-byte comparison.
* Applications can of course not delegate that job to the OpenSSL library, and do the email address name checks for themselves, we'll just make sure that the name constraints are satisfied.

If the authors of this PR are inspired to take a second attempt at this, feel free to either re-open this, or open a new PR that references this one.

**Pull request closed without merging**
