### PR TITLE
ASYNC: Fixes for nested job creation

### PR DESCRIPTION
**Pull request by uudiin**
In such a scenario, calling ASYNC_start_job() in a job again to create
a new job will cause the program to crash. This scenario is common in
coroutines, such as a web server, a coroutine listener, and a new client,
a new coroutine service, after accept () is created.

The current design of ASYNC does not support this scenario. Each coroutine
eventually falls back to the dispatcher. There are multiple coroutines,
and there is only one context for saving the coroutine exit, which is the
dispatcher. At this time, the context will be Being covered, this also
determines that only one coroutine can be running at the same time. And it
is dispatched by the dispatcher, which limits the application scenario
of ASYNC to a certain extent. In the traditional sense of coroutines,
dispatching is done by the users themselves, and there is no need for a
so-called dispatching center, dispatcher.

This patch solves this problem. For each coroutine, a context called back
is used for exit or pause (), so the dispatcher is not needed. This patch
does not change the ASYNC API.

There is also a simple example in the test code, which fully illustrates the
problems I described.

Signed-off-by: Tianjia Zhang <tianjia.zhang@linux.alibaba.com>

##### Checklist

- [ ] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by uudiin** [comment]
@InfoHunter @mattcaswell Could you give me some feedback on this patch?

**Comment by InfoHunter** [comment]
I still don't quite understand why the nested jobs are needed...

**Comment by uudiin** [comment]
> I still don't quite understand why the nested jobs are needed...

As I described above, it will be used in the ssl server scenario:
Open a job for `listen`, after `accept` a client and then open a job to communicate with the client

**Comment by InfoHunter** [comment]
Why don't you just start a new job after `accept` without opening a job for `listen`?

**Comment by uudiin** [comment]
> Why don't you just start a new job after `accept` without opening a job for `listen`?

`accept` is also a blocking operation, to achieve asynchronous, you need yield coroutine, which is `ASYNC_pause_job()`, so it is necessary to let the combination of `listen + accept` run in a async job.

**Comment by uudiin** [comment]
@mattcaswell @iamamoose ping

**Comment by mattcaswell** [comment]
IMO, nested async jobs are not a good idea. The concept was deliberately excluded from the original design. It adds too much complexity (high risk of something going wrong) - with little benefit.

I don't think this PR should be accepted.

**Comment by t8m** [comment]
> IMO, nested async jobs are not a good idea. The concept was deliberately excluded from the original design. It adds too much complexity (high risk of something going wrong) - with little benefit.
> 
> I don't think this PR should be accepted.

I agree. Would you put OTC hold on it and call a vote?

**Comment by mattcaswell** [comment]
> Would you put OTC hold on it and call a vote?

I put the hold on it. Do we actually need to call a vote to reject a PR? I'd say a vote is only required if there is disagreement within the committers.

**Comment by paulidale** [comment]
I don't think a vote is required unless a committer (or alternatively a committee member) wants this to go in.  In that case, they could call the vote.

**Comment by t8m** [comment]
I do not think a vote to reject a PR is always needed. For example if some PR is some total nonsense or the contributor does not respond to requests for changes it is clearly unneeded.

But in this concrete case where the PR is seemingly valid but we do not want to support the feature for technical reasons it would make sense to me.
The vote can be more general than just about closing this PR.  For example it could be a vote that we are not going to support nested ASYNC jobs.

**Comment by mattcaswell** [comment]
> But in this concrete case where the PR is seemingly valid but we do not want to support the feature for technical reasons it would make sense to me.

Seems like we need to discuss policy. Lets see if we have time at the next OTC meeting.

**Comment by InfoHunter** [comment]
> I don't think a vote is required unless a committer (or alternatively a committee member) wants this to go in

Personally, I think this PR needs more actions other than just rejecting it:

1. Do we really need this feature, if not:
2. Do we need to forbid this nested usage explicitly other than let the application crashes.

BTW, the author of this PR and me are in the affiliated companies (Alibaba & Ant Group), so perhaps my comment should only be consider as a note instead of a series opinion ;-)

**Comment by mattcaswell** [comment]
> Do we really need this feature, if not:

I've not yet heard a compelling argument for it, so I don't think so.

> Do we need to forbid this nested usage explicitly other than let the application crashes.

No, it shouldn't crash. I think a PR that failed gracefully in that scenario would be acceptable.

**Comment by mattcaswell** [comment]
OTC: Moving this to the Post 3.0 milestone

**Comment by uudiin** [comment]
@mattcaswell @t8m @paulidale This PR has already rebased on master and combine the PR https://github.com/openssl/openssl/pull/16703

**Comment by InfoHunter** [comment]
Ping @openssl/committers @openssl/otc , this is stale for a very long time, any ideas on this guys?

**Comment by t8m** [comment]
IMO there was a relevant reply by Matt here: https://github.com/openssl/openssl/pull/11421#issuecomment-733574384

**Comment by mattcaswell** [comment]
As I've previously noted in https://github.com/openssl/openssl/pull/11421#issuecomment-725984292 I don't think this PR should be accepted.

**Pull request closed without merging**
