### PR TITLE
Fix regression on x509 keyform argument

### PR DESCRIPTION
**Pull request by jussike**
In OpenSSL pre 1.1.0, 'openssl x509 -keyform engine' was possible
and supported.  In 1.1.0, type of keyform argument is OPT_FMT_PEMDER
which doesn't support engine. This changes type of keyform argument
to OPT_FMT_PDE which means PEM, DER or engine and updates the manpage
including keyform and CAkeyform.

This restores the pre 1.1.0 behavior.

This issue is very similar than https://github.com/openssl/openssl/issues/4366

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by richsalz** [comment]
Does the manpage need to be updated?

**Comment by mattcaswell** [comment]
> Does the manpage need to be updated?

Yes

**Comment by jussike** [comment]
Do I need the cla or is that trivial enough?

**Comment by beldmit** [comment]
I think it's trivial enough.

**Comment by t8m** [comment]
I also agree it is trivial. Please amend the commit message to contain CLA: trivial on separate line.

**Comment by mattcaswell** [comment]
Travis failure is not relevant.

**Comment by levitte** [comment]
`CLA: trivial` added to the commit message, since everyone agrees.
Merged.

master:
0ab6fc79a9a63370be1a615729dc2a6ed0d6c89b Fix regression on x509 keyform argument

1.1.1:
bf4006a6f9be691ba6eef0e8629e63369a033ccf Fix regression on x509 keyform argument

**Pull request closed without merging**
