### PR TITLE
OSSL_PARAM_allocate_from_text(): Allow detection of unsupported param keys

### PR DESCRIPTION
**Pull request by paulidale**
Alternative to  #11046

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Comment by paulidale** [comment]
Rebased to remove conflicts.

**Comment by paulidale** [comment]
Ping for review

**Comment by paulidale** [comment]
Ping @openssl/committers

**Comment by levitte** [comment]
@paulidale is away for a few days, so I'll merge this

**Comment by levitte** [comment]
Merged

2ee0dfa684d5fbda5758136807e2732bd4f85139 Params: add argument to the _from_text calls to indicate if the param exists.
292c8bdc083d1b739ae241775bfac36f1f998294 pmeth_lib: detect unsupported OSSL_PARAM.
e1dcac22607f6ecbb5ad4f15fc1a54f54f40c1ba apps: distinguish between a parameter error and an unknown parameter.

**Pull request closed without merging**
