### PR TITLE
CAPI: Allow to lookup certificate by hash

### PR DESCRIPTION
**Pull request by avoidik**
Allow to lookup certificates by hash, few memory leaks optimizations

```
openssl engine -t -post csp_idx:1 -post list_options:35 -post "lookup_cert:hash:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" capi
openssl dgst -keyform ENGINE -engine capi -sign "hash:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -out openssl.pdb.sig -sha1 openssl.pdb
```

### CODE REVIEW

**Comment by t8m** [comment]
Closing as this is a feature addition on an engine. The engine api is deprecated and there will be no more enhancements of existing engines on master branch.

**Comment by diegosiao** [comment]
What do we have in place @t8m?

**Comment by avoidik** [comment]
If I remember correctly, my case wasn't related to a specifically collision, I just wanted to optimize the way how OpenSSL CAPI is searching for certificates for PKCS11. In some cases Subject may include diacritical symbols which almost impossible to find using `CERT_FIND_SUBJECT_STR_A`.

I see a bunch of changes have been made into said engine right after my closed PR, not quite sure what was behind @t8m decision to close this PR. Mind to reconsider your decision @t8m?

**Comment by t8m** [comment]
It is not _my_ decision. It is a collective decision of the OMC/OTC that engines are deprecated. That means only bug fixes are accepted for engines, not enhancements.

**Pull request closed without merging**
