### PR TITLE
Add OID for RPKI id-ct-ASPA

### PR DESCRIPTION
**Pull request by job**
References: draft-ietf-sidrops-aspa-profile
"A Profile for Autonomous System Provider Authorization" (ASPA)

OID permanently assigned under 'SMI Security for S/MIME CMS Content Type (1.2.840.113549.1.9.16.1)'
https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#security-smime-1

CLA: trivial

### CODE REVIEW

**Comment by t8m** [comment]
Although this is most probably trivial from the copyright perspective we usually allow only very small changes under CLA: trivial. Could you please submit a regular CLA? https://www.openssl.org/policies/cla.html

**Comment by job** [comment]
@t8m hi, thanks for taking a look. Previously adding OIDs was deemed 'trivial'. Examples: https://github.com/openssl/openssl/pull/15207, https://github.com/openssl/openssl/pull/14050, and https://github.com/openssl/openssl/pull/13948

I'd like to avoid additional paperwork, as I do believe adding an OID is trivial :-)

**Comment by mattcaswell** [comment]
This looks trivial to me, so personally I'd be ok to accept it as such. Most of the changes are auto-generated anyway by the looks of things.

**Comment by job** [comment]
@mattcaswell indeed, the only 'original' work was the addition of the line in `obj_mac.num` and the one line in `objects.txt`.

The other changes were the result of executing `$ make generate_crypto_objects`

**Comment by t8m** [comment]
OK then

**Review by t8m — APPROVED** [review]

**Comment by mattcaswell** [comment]
> the only 'original' work was the addition of the line in obj_mac.num and the one line in objects.txt

Even the line in obj_mac.num should be auto-generated by `make generate_crypto_objects`. The *only* line you should have needed to add was the one in objects.txt

**Review by mattcaswell — APPROVED** [review]
Agree trivial

**Comment by job** [comment]
@mattcaswell ah cool! Thank you for teaching me :)

**Review by paulidale — APPROVED** [review]
Yes, trivial.

**Comment by t8m** [comment]
Squashed and merged to master branch. Thank you for your contribution.

**Pull request closed without merging**
