### PR TITLE
Return SSL_AD_UNEXPECTED_MESSAGE alert when receiving any other change_cipher_spec value(RFC 8446)

### PR DESCRIPTION
**Pull request by ldlb9527**
Fixes: #25086 
CLA: trivial

### CODE REVIEW

**Review by Sashan — APPROVED** [review]
looks good to me.

looks as CLA trivial

**Review by tom-cosgrove-arm — CHANGES_REQUESTED** [review]
Sorry, but can we have a title on the commit message? Then there should be a blank line before the `CLA: trivial` line.

Currently the commit header is just

```
commit 3714b1465e5084bccf9215de135216d8ca3b523f (HEAD -> fix-msg)
Author: cx <1249843194@qq.com>
Date:   Thu Aug 22 02:13:01 2024 +0800

    CLA: trivial
```

A more usual commit message would be something like

```
commit 02b8b7b83698d1c7ddfef274f16c039c8cca7988
Author: Bhaskar Metiya <bhaskarmetiya@gmail.com>
Date:   Wed Aug 14 11:34:01 2024 +0530

    Return SSL_AD_DECRYPT_ERROR alert on PSK binder validation failure (RFC 8446)
    
    CLA: trivial
```

**Comment by ldlb9527** [comment]
> Sorry, but can we have a title on the commit message? Then there should be a blank line before the `CLA: trivial` line.
> 
> Currently the commit header is just
> 
> ```
> commit 3714b1465e5084bccf9215de135216d8ca3b523f (HEAD -> fix-msg)
> Author: cx <1249843194@qq.com>
> Date:   Thu Aug 22 02:13:01 2024 +0800
> 
>     CLA: trivial
> ```
> 
> A more usual commit message would be something like
> 
> ```
> commit 02b8b7b83698d1c7ddfef274f16c039c8cca7988
> Author: Bhaskar Metiya <bhaskarmetiya@gmail.com>
> Date:   Wed Aug 14 11:34:01 2024 +0530
> 
>     Return SSL_AD_DECRYPT_ERROR alert on PSK binder validation failure (RFC 8446)
>     
>     CLA: trivial
> ```

Thank you for the feedback,I've updated the commit message

**Comment by mattcaswell** [comment]
Not sure why the coding style checker is complaining about files not included in this PR. Adding the "style: waived" label.

**Review by mattcaswell — APPROVED** [review]
LGTM

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

@mattcaswell please confirm you're OK with CLA: trivial.

**Comment by mattcaswell** [comment]
Agree - CLA trivial

**Review by shahsb — APPROVED** [review]
LGTM.

OK with CLA:trivial

Please note - the commit message should also include `Fixes: #<issueno>` string on new line

**Comment by FdaSilvaYY** [comment]
Typo in commit message ? : cipher_**stec**

**Comment by ldlb9527** [comment]
Thanks for catching those issues and suggesting improvements! I’ve made the necessary changes

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
