### PR TITLE
ARM assembly pack: translate bit-sliced AES implementation to AArch64

### PR DESCRIPTION
**Pull request by bavison**
This addresses a performance issue on the Raspberry Pi 4, when running in AArch64 mode. This device feature a Cortex-A72 CPU, without the cryptography extensions. OpenSSL includes a bit-sliced AES implementation for Arm cores which is used by the Raspberry Pi 4 in AArch32 mode, but this has not been usable in AArch64 mode until now. In fact, it runs a little faster on AArch64 than AArch32 because there are more registers available (so less spilling of variables to the stack is required) and I have been able to schedule the instructions to better suit modern CPUs that are superscalar for SIMD instructions.

The AArch32 version featured a build variant which was used at one point in the past when the same source file was built into the Linux kernel. Linux has since replaced this with a dedicated implementation, so this build variant is not carried across to the AArch64 version.

Here are some benchmarks for a 1.5 GHz Raspberry Pi 4, using `openssl speed -evp <type>` first with and then without `-decrypt`:

Before

type            | 16 bytes    | 64 bytes    |256 bytes   |1024 bytes   |8192 bytes  |16384 bytes
----------------|-------------|-------------|------------|-------------|------------|------------
aes-256-cbc     | 20985.17k   | 40250.30k   | 41440.43k  |  41834.15k  |  41945.77k |   41899.35k
aes-256-cbc     | 27709.77k   | 29490.15k   | 30024.11k  |  30124.03k  |  30203.90k |   30206.63k
aes-256-ctr     | 25902.21k   | 28224.73k   | 29000.96k  |  29195.26k  |  29253.63k |   29261.82k
aes-256-ctr     | 26052.76k   | 28445.89k   | 29051.39k  |  29178.88k  |  29253.63k |   29256.36k
aes-256-xts     | 12040.37k   | 18575.40k   | 21351.51k  |  22141.61k  |  22421.50k |   22435.16k
aes-256-xts     | 13714.33k   | 23058.97k   | 27679.66k  |  29090.82k  |  29521.24k |   29545.81k

After

type            | 16 bytes    | 64 bytes    |256 bytes   |1024 bytes   |8192 bytes  |16384 bytes
----------------|-------------|-------------|------------|-------------|------------|------------
aes-256-cbc     | 46384.37k   | 54493.12k   | 64383.74k  |  69976.41k  |  71789.23k |   71931.22k
aes-256-cbc     | 26784.13k   | 29198.31k   | 29956.35k  |  30095.29k  |  30198.44k |   30190.25k
aes-256-ctr     | 44068.21k   | 53480.06k   | 74281.22k  |  82495.83k  |  85330.60k |   85475.33k
aes-256-ctr     | 43571.85k   | 53088.87k   | 74143.91k  |  82298.88k  |  85502.63k |   85535.40k
aes-256-xts     | 15152.73k   | 25001.58k   | 58084.27k  |  66503.34k  |  70372.01k |   70533.12k
aes-256-xts     | 16100.20k   | 29117.95k   | 68045.31k  |  78810.11k  |  82823.85k |   83077.80k

This demonstrates a significant speed-up in all cases except CBC encryption (which by its nature is impossible to parallellise across multiple crypto blocks in the manner performed by bit-slicing).

The `make test` suite passes.

A separate PR #14592 has been raised to apply the equivalent change to master.

One thing that I noticed during debugging is that the `make test` suite occasionally calls the functions with identical input and output pointers. The C prototypes are defined by the types `cbc128_f` and `ctr128_f` in `modes.h` and struct `EVP_AES_XTS_CTX` member `stream` in `e_aes.c`. In all these cases, the `in` and `out` arguments to the function pointers do not feature a `restrict` qualifier, so this is a valid way to call them as far as a C compiler is concerned.

However, I'm aware that the AArch32 implementations (and doubtless many others) do not honour calls with pointers that alias in any other manner than strict equality - in other words, if the input and output buffers only partially overlap. At least for now, this is also the case with my AArch64 implementation. Since the input and output data are of identical size, this could be handled by `memmove`ing the source to the destination, then performing in-place de/encryption at the destination address. Since this would be a fix required in many places, I wonder whether it would be better implemented as a generic wrapper in some way?

The other course of action, of course, is to leave things as they are. But in that case, may I suggest that it's documented somewhere that identical `in` and `out` pointers are permitted, but that is the only form of pointer aliasing that is?

### CODE REVIEW

**Comment by paulidale** [comment]
We will need a version of this that goes into master, we put changes into master and then other branches.

OTC: should this be merged to 1.1.1?

I've added the _help wanted_ tag in the hope that somebody who understands ARM64 assembler can help review this.

**Comment by t8m** [comment]
Not sure this can be treated as pure bug fix (for the 1.1.1 merge).

**Comment by paulidale** [comment]
It would seem to be like some of the other performance enhancements we back ported: isolated to a specific architecture that's not well supported.  It's not quite the same, I'll put an OTC decision on this.

Regardless, we need this on master first.

**Comment by paulidale** [comment]
The OTC has made the decision that this should not be included in 1.1.1

**Pull request closed without merging**
