### PR TITLE
todo: remove TODO(3.0) from the sources.

### LINKED ISSUE #15325: Fix remaining TODO(3.0) items
```
crypto/evp/dh_ctrl.c: * TODO(3.0) Should this be deprecated in favor of passing a name or an
crypto/evp/dh_ctrl.c: * TODO(3.0) Should this be deprecated in favor of passing a name?
crypto/evp/dh_ctrl.c: * TODO(3.0) Should this be deprecated in favor of getting a name?
crypto/evp/dh_ctrl.c: * TODO(3.0) Should this be deprecated in favor of passing a name?
crypto/evp/dh_ctrl.c: * TODO(3.0) Should this be deprecated in favor of getting a name?
crypto/evp/dsa_ctrl.c:/* TODO(3.0): deprecate as this is needed only for legacy? */
crypto/evp/ec_ctrl.c: * TODO(3.0) Should this be deprecated in favor of passing a name?
crypto/evp/ec_ctrl.c: * TODO(3.0) Should this be deprecated in favor of getting a name?
crypto/evp/ec_ctrl.c: * TODO(3.0) Should this be deprecated in favor of setting a name or an
crypto/evp/evp_lib.c:/* TODO(3.0): EVP_DigestSign* not yet supported in FIPS module */
crypto/evp/pmeth_lib.c:/* TODO(3.0): Deprecate in favour of get_signature_md_name */
crypto/evp/pmeth_lib.c: * TODO(3.0): Deprecate functions calling this in favour of
crypto/rsa/rsa_lib.c: * TODO(3.0) Should this be deprecated?
crypto/rsa/rsa_lib.c: * TODO(3.0) Should this be deprecated?
crypto/rsa/rsa_lib.c: * TODO(3.0) Should this be deprecated in favor of passing a name?
crypto/rsa/rsa_lib.c: * TODO(3.0) Should this be deprecated in favor of passing a name?
crypto/rsa/rsa_lib.c: * TODO(3.0) Should this be deprecated in favor of getting a name?
crypto/rsa/rsa_lib.c: * TODO(3.0) Should this be deprecated in favor of passing a name?
crypto/rsa/rsa_lib.c: * TODO(3.0) Should this be deprecated in favor of passing a name?
crypto/rsa/rsa_lib.c: * TODO(3.0) Should this be deprecated in favor of getting a name?
```
~/work/openssl/openssl$ git grep 'TODO(3.0)' | wc -l 
20

### PR DESCRIPTION
**Pull request by paulidale**
Almost all were notes about wanting to deprecate CTRLs/utility functions.

Fixes #15325

### CODE REVIEW

**Comment by paulidale** [comment]
I don't think any of these remaining ones need addressing specifically.

**Review by t8m — APPROVED** [review]
LGTM. We will need to consider those calls when dropping the legacy support as most of them really do not make sense with providers - for example passing the EVP_MD when only the name is used anyway. But that does not require keeping the TODOs.

**Review by slontis — APPROVED** [review]

**Comment by paulidale** [comment]
We'll definitely need to consider dropping these when legacy support disappears.  We'll have to look through everything at that point, these TODOs aren't saving any effort.

**Comment by mattcaswell** [comment]
Pushed.

**Pull request closed without merging**
