### PR TITLE
Run the punycode-test over the fuzz corpora during test.

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by tmshort** [comment]
And not sure why this is considered a FIPS change?

**Comment by paulidale** [comment]
Yeah, the fips changed flag is weird.  It's caused by checksum changes in files that haven't been altered by this PR:

```diff
diff -u ../source/providers/fips.module.sources providers/fips.module.sources.new
diff -u ../source/providers/fips-sources.checksums providers/fips-sources.checksums.new
--- ../source/providers/fips-sources.checksums	2023-02-20 15:39:21.527278373 +0000
+++ providers/fips-sources.checksums.new	2023-02-20 15:40:39.084174581 +0000
@@ -97,12 +97,12 @@
 c56ad3073108a0de21c5820a48beae2bccdbf5aa8075ec21738878222eb9adc3  crypto/bn/bn_prime.h
 3dd5ce6ddea13d04a9470625af35328319d1a5f3a963183095edf3add314b7e0  crypto/bn/bn_rand.c
 6a6bb2ca178e1d5415c9b0e7933930009127e6ec5ffb6d8992cbc0a68880865b  crypto/bn/bn_recp.c
-669a157968afe07588507a2e9e35c1c4df9c2b0a95cd9c21404b0bfa21be0d37  crypto/bn/bn_rsa_fips186_4.c
+c31039a9e2d3d0e8adbff3ed234f2c5fd50ecab0332a2adf5e5c833f6aeedd86  crypto/bn/bn_rsa_fips186_4.c
 704b0b4723e5c9e9bae5f3e35f9ae8ae8dca3383929e954de9e5169845abfdb2  crypto/bn/bn_shift.c
 622e90766b29e0d25f46474429aebda8eba2246835b9e85dc26da7cdbd49334f  crypto/bn/bn_sqr.c
make: *** [Makefile:5246: diff-fips-checksums] Error 1
 42c8ce944c889abcfcf089d0ad2744b7587696d8d7785efa91b3f7ec53dc062a  crypto/bn/bn_sqrt.c
 24e62baa56e02f2db6454e10168b7c7fa7638db9221b9acda1803d43f38f36e0  crypto/bn/bn_word.c
-1223afacbc6923af1580340bbe6f7b9da453da3e29f0a251ac49b1e0bf109cf5  crypto/bn/rsa_sup_mul.c
+2e69544977adab07422acab5cbb32f4efb7ab68bc160dde711e3f7a8e755b43d  crypto/bn/rsa_sup_mul.c
 be27115efd36f0077a3ec26b1ff1f586b0b8969ba05d8ffa34b2ff4badf227bf  crypto/bn/rsaz_exp.c
 c4d64da1cdc732ea918fccd6a7bb2746b03365dd26f7ba1e74e08c307ca4c58e  crypto/bn/rsaz_exp.h
 55266c387202fd4f90bebfe7bb93c550b23b78dc3a90edcc668e5dbf480f916c  crypto/bn/rsaz_exp_x2.c
@@ -580,7 +580,7 @@
 7eec8b91910489a5afb2ac0fe2edd6a840ab8b367c3e96fb19ca4d30545d1e43  providers/implementations/include/prov/names.h
 b9f8781167f274ccd8b643b3bb6c4e1108fb27b2aae588518261af9415228dae  providers/implementations/include/prov/seeding.h
 83b226a73c5d41f3a9b86ec3b61ea846e17e59f5ddc6975f0a1011651b878efe  providers/implementations/kdfs/hkdf.c
-11a1a8dda44ea73151ac33e3cd6aaede68647bd340a301618f73fa9a35481f52  providers/implementations/kdfs/kbkdf.c
+060fb3b5650ec80e266fb1e9e4f525ce6a68f706049f5fb8f242369e3a47bf98  providers/implementations/kdfs/kbkdf.c
 6df121b03b7acd16103e9087a334dddd2277dd89531e3931953f7254c2cf1d8d  providers/implementations/kdfs/pbkdf2.c
 c0778565abff112c0c5257329a7750ec4605e62f26cc36851fa1fbee6e03c70c  providers/implementations/kdfs/pbkdf2.h
 abe2b0f3711eaa34846e155cffc9242e4051c45de896f747afd5ac9d87f637dc  providers/implementations/kdfs/pbkdf2_fips.c
FIPS CHANGED
```

**Comment by t8m** [comment]
Merged to master branch. Thank you.

**Pull request closed without merging**
