### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by DennisYurichev**
CLA: trivial

### CODE REVIEW

**Comment by t8m** [comment]
The CLA: trivial must be in the commit message body not just in the PR. (You can adjust the commit message with `git commit --amend` and pushing with --force.)

**Comment by DennisYurichev** [comment]
Oh common!
Nevermind, just ignore it.

**Comment by DennisYurichev** [comment]
If you want this fix, just edit your file without any PR or commit...

**Comment by t8m** [comment]
> If you want this fix, just edit your file without any PR or commit...

Unfortunately we need a PR for every change to be committed to the repository. So could you please do the trivial thing that I asked? Otherwise I'd have to create a branch, fix it there by myself, push and create a new PR.

**Pull request closed without merging**
