### PR TITLE
Fix memory leaks on error cases during drbg initializations

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
How do we fix the CIFuzz issue?

**Comment by t8m** [comment]
> How do we fix the CIFuzz issue?

Maybe @Leo-Neat the original author of this workflow could have some idea? But it might be possible that we would have to use a larger runner (which isn't for free).

**Comment by hlandau** [comment]
Could we split up CIFuzz into multiple runs, each with a different subset of the fuzz corpus?

**Comment by t8m** [comment]
Merged to the master, 3.2, 3.1 and 3.0 branches. Thank you for the reviews.

**Pull request closed without merging**
