### PR TITLE
Add DSA digests, and round out _fp API

### PR DESCRIPTION
**Pull request by pprindeville**
Block of related commits adding new convenience functions:

* i2d_DSAPublicKey_fp() and d2i_DSAPublicKey_fp() adding *_fp() methods to complement the existing homologues;
* DSA_public_digest() and DSA_private_digest(), to hash public or private keys;

Tests are provided for all of these except the first which is trivial.

Note that the DSA_public_digest() has a workaround for issue #6445.

### CODE REVIEW

**Comment by pprindeville** [comment]
CLA has been signed, scanned, and email today... awaiting processing.

**Comment by richsalz** [comment]
close/open to kick the cla bot.

**Comment by richsalz** [comment]
We are well into feature-freeze for 1.1.1 now. Do these new functions make up for things that used to be possible, but were broken because we made structures opaque?  If so, can you point to code/apps that used them?  If not, then these new API's would have to wait for the next release after 1.1.1

**Comment by pprindeville** [comment]
No, they are new functionality. How should I version them?

And how to deal with DSAPublicKey arguably being the wrong format?

**Comment by richsalz** [comment]
Don't worry about versioning, it will be fixed up when this is merged (after 1.1.1)  As for the format read/written by DSAPublicKey we can't change it or else we break interop.  Do the i2d/d2i publickey functions do the right thing?

**Comment by mattcaswell** [comment]
> And how to deal with DSAPublicKey arguably being the wrong format?

It isn't. It just predates the RFC format. It's unfortunate that the RFC then ended up using the same name we already had for something else. But we *do* support the SPKI format for DSA - just use DSA_PUBKEY instead.

**Comment by kroeckx** [comment]
Is it possible to do those things with the EVP layer? If not, would it make sense to add them to the EVP layer?

**Comment by pprindeville** [comment]
> But we do support the SPKI format for DSA - just use DSA_PUBKEY instead.

But that's not the format I need either.  I just need the ASN.1 `INTEGER` representation of `.DSA.pub_key`.  Does it make sense to add another `typedef` that handles this with the associated marshaling and bio/fp adornment, etc?

**Comment by pprindeville** [comment]
> Do the i2d/d2i publickey functions do the right thing?

Well, that's a partisan question, or at least a nuanced one.

I guess it depends on what you believe the _right thing_ to be for the format of the public key... there's the public key itself (which is what I need), there's the `SubjectPublicKeyInfo` (per RFC-5912), and there's the `DSAPublicKey` format which duplicates the `DSAParams` and doesn't seem to be defined in any RFC at all (or ITU document, that I can tell, but without a subscription to the service I have limited search capabilities).

**Comment by pprindeville** [comment]
Moving the RSA digest to a separate PR since there seems to be more consensus on what canonical key format is for RSA.

**Comment by mattcaswell** [comment]
> Does it make sense to add another typedef that handles this with the associated marshaling and bio/fp adornment, etc?

Since we're just talking about a plain ASN1 Integer here it doesn't seem worthwhile since we already have i2d_ASN1_INTEGER(). I don't see much point in improving the DSA API since we shouldn't be encouraging its use anyway and there should be few new applications using it.

**Comment by davidben** [comment]
What's the use case here? If you're hashing just the INTEGER representation of the public key, you aren't including any of the parameters, which are an important part of what key you've got. So if you're using this as some kind of key fingerprint, you aren't capturing all the context. (And, of course, you also aren't capturing the type of key in either of these.)

If whatever you're doing with these includes separately considering these hashes in the context of DSA + specific DSA parameters, then this is plausible. But if you have somewhere pre-configured that a hash of a DSA public key, via this scheme, and are trying to authenticate someone by it, unless your application has already separately authenticated or hardcoded the fact that the key is DSA and a particular set of DSA parameters, this isn't secure.

This sort of thing is why HPKP hashes the entire SubjectPublicKeyInfo and not just the subjectPublicKey value inside it.

**Comment by t8m** [comment]
This is adding API calls to deprecated DSA API so it is not really relevant for 3.0 and on.
Closing.

**Pull request closed without merging**
