### PR TITLE
Quick simplification of Mkerr .pl

### PR DESCRIPTION
**Pull request by FdaSilvaYY**
as suggested in PR #5275 
Ping @levitte  and @richsalz

### CODE REVIEW

**Comment by richsalz** [comment]
want me to merge or you?

**Comment by levitte** [comment]
Feel free to go ahead

**Comment by FdaSilvaYY** [comment]
@richsalz : this is ready,no ?

**Comment by richsalz** [comment]
It was merged with a699b8e4ca106a1aade0cc741eca63a61d44b90f I just didn't get around to push and closing this. :)

**Pull request closed without merging**
