### PR TITLE
Fix --strict-warnings with C90

### PR DESCRIPTION
**Pull request by tmshort**
Found with gcc 4.8.4

### CODE REVIEW

**Comment by tmshort** [comment]
```
$ ./config --strict-warnings
...
$ make
crypto/ec/ecp_nistz256.c: In function 'ecp_nistz256_inv_mod_ord':
crypto/ec/ecp_nistz256.c:1610:5: error: ISO C90 forbids mixed declarations and code [-Werror=pedantic]
     enum {
     ^
cc1: all warnings being treated as errors
make[1]: *** [crypto/ec/ecp_nistz256.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

**Comment by dot-asm** [comment]
Hmm... I regularly use elderly compilers, how did it slipped through? Oh well... Trouble here is that enum in question appears in unconditional #if-#else clause. I mean it's trouble for *readability*, not for compiler. In other words one can wonder if it would be appropriate to add a line of commentary mentioning that? I mean something like "used in alternative variable-window addition chain"?

**Comment by dot-asm** [comment]
Oh! It's already committed...

**Comment by tmshort** [comment]
It was also the #else of a #if 0

**Comment by dot-asm** [comment]
> It was also the #else of a #if 0

Yes, that's what I meant...

**Comment by tmshort** [comment]
@levitte this needs to be closed?

**Comment by kaduk** [comment]
Yup, closing --thanks!

**Comment by levitte** [comment]
Ah, I forgot this step.  It indeed got merged yesterday...  8e403a79b0e679c8df41a9686006c5fe052d79bd

**Pull request closed without merging**
