### PR TITLE
code health chacha_internal_test

### PR DESCRIPTION
**Pull request by pauli-oracle**
- [x] tests are added or updated

Update the internal chacha test to use the framework

### CODE REVIEW

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Comment by dot-asm** [comment]
-1 with following rationale. Basically there are two reasons, kind of personal and kind of general. On personal side I value the possibility to take as small amount of files as possible for a spin on exotic system. I would be likely to have to make it a project in specific IDE, there definitely is no perl, it's more than likely cross-compiled environment... And suggested modification makes it harder [than necessary]. As for general. Coding has multiple goals, one of which is that code is supposed to be as readable as possible to a human. So question is if suggested modification actually improves readability specifically for general public. Simple test. Can you print out the file, give it to a programmer and have him figure out what it does without having to make additional printouts? Or alternatively encourage him/her to ask questions, and then question would be how many questions will have to be answered...

**Comment by mattcaswell** [comment]
Too late. I already pushed :-(

**Comment by mattcaswell** [comment]
> -1 with following rationale. Basically there are two reasons, kind of personal and kind of general. On personal side I value the possibility to take as small amount of files as possible for a spin on exotic system. I would be likely to have to make it a project in specific IDE, there definitely is no perl, it's more than likely cross-compiled environment... And suggested modification makes it harder [than necessary].

This objection seems like an objection to the fundamental principle of having a test harness that everything uses. It seems quite late in the day to raise that objection now!

> As for general. Coding has multiple goals, one of which is that code is supposed to be as readable as possible tofor a human. So question is if suggested modification actually improves readability specifically for general public. Simple test. Can you print out the file, give it to a programmer and have him figure out what it does without having to make additional printouts? Or alternatively encourage him/her to ask questions, and then question would be how many questions will have to be answered...

I don't get it. The modification (in my eyes) makes very little difference to the readability. Yes, it helps if you have a familiarity with the test harness, but even without that it hardly makes it less readable.

**Comment by dot-asm** [comment]
>>  And suggested modification makes it harder [than necessary].

> This objection seems like an objection to the fundamental principle of having a test harness that everything uses.

No. But I fail to see why does *everything* have to use it *unconditionally*. Does it have to be self-purpose?

> It seems quite late in the day to raise that objection now!

I don't understand. Are there "you-may-speak" and "shut-up" hours?

>> Can you print out the file, give it to a programmer and have him figure out what it does without having to make additional printouts?

> I don't get it. The modification (in my eyes) makes very little difference to the readability.

I explicitly said that it's not about *our* eyes. We are not the only ones reading code. Nor *should* we be only ones. That's actually also a goal, making as many people read it as possible that is, and question even is how do we get closer to it? Does suggested modification get us closer?

> Yes, it helps if you have a familiarity with the test harness, but even without that it hardly makes it less readable.

Once again. How many questions would Joe C. Programmer [Jr.] ask when looking at single file? Before just *one*, namely "what does ChaCha20_ctr32 do". Now, he would have to ask for additional printouts...

**Comment by mattcaswell** [comment]
> No. But I fail to see why does everything have to use it unconditionally. Does it have to be self-purpose?

Yes. Up until now each test does things differently. For example: some check for mem leaks others do not. By standardising on a single approach then we know everything is going to check for mem leaks. If we want to make changes in the future that affect all tests then we can make changes in the harness as appropriate knowing that it will be picked up by everything.
 
> I don't understand. Are there "you-may-speak" and "shut-up" hours?

No - of course not. My point was that we've just spent a whole code-health Tuesday on converting as many tests as possible. Raising objections on the principle at the end of the day after we've done all the work is sub-optimal to say the least!

> Once again. How many questions would Joe C. Programmer [Jr.] ask when looking at single file? Before just one, namely "what does ChaCha20_ctr32 do". Now, he would have to ask for additional printouts...

Right. But you can also run the readability angle the other way around. Mostly programmers will not restrict themselves to a single file but will be reading multiple. This is likely to raise lots of questions and confusion about why one file does things in a particular way, but another file does things completely differently. By standardising on one approach you only need to understand how the test harness works to understand how all testing is done. Pick up any test file and you get a good idea about how it works.

**Pull request closed without merging**
