### PR TITLE
Add assembly config targets for UEFI build [1.1.1]

### PR DESCRIPTION
**Pull request by cjzurch**
Implementation of https://github.com/openssl/openssl/pull/11054 for 1.1.1.

### CODE REVIEW

**Comment by cjzurch** [comment]
Failed build says "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

I'm not sure how to re-start the build.

**Comment by kaduk** [comment]
> Failed build says "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

To be honest, that looks like a full or slow disk on the worker machine during the `make install` test, and I wouldn't worry about it affecting the mergability of the PR.

> I'm not sure how to re-start the build.

That said, if you do want to force a re-run of the CI, closing and reopening the PR should do so.

**Comment by cjzurch** [comment]
Thanks for the update! I don't really have a need to re-run it; I wasn't sure if it was required to pass before a PR could be approved.

**Comment by cjzurch** [comment]
@paulidale Would you mind taking a look at this?

**Comment by levitte** [comment]
What's our policy on adding new config targets on stable release branches again?

**Comment by mattcaswell** [comment]
> What's our policy on adding new config targets on stable release branches again?

This is usually considered a new feature and therefore not allowed.

**Comment by levitte** [comment]
So that would disqualify this PR, would it not?

**Comment by mattcaswell** [comment]
> So that would disqualify this PR, would it not?

Looks like it.

**Comment by zurcher** [comment]
... So I have to wait for 3.0 release?

**Comment by cjzurch** [comment]
So I have to wait for 3.0 release?

**Comment by levitte** [comment]
For those config targets to be part of the OpenSSL source?  Yes.  To use them no, you can have them in files of your own that you either tell Configure about with `--config=PATH/TO/FILE`, or place in a directory that you then give with the environment variable `OPENSSL_LOCAL_CONFIG_DIR`, for example:

```
perl Configure --config=c:/opt/openssl-configs/uefi-extra.conf UEFI-x86_64 ...
```

```
set OPENSSL_LOCAL_CONFIG_DIR=c:/opt/openssl-configs
perl Configure UEFI-x86_64 ...
```

**Comment by cjzurch** [comment]
Well that's even better than what I was trying to do. I'll go ahead and close this PR.

**Pull request closed without merging**
