### PR TITLE
Clarify return values for EVP_DigestVerifyFinal.

### PR DESCRIPTION
**Pull request by aeijdenberg**
Previous language was unclear.  New language isn't pretty but I believe
it is more accurate.

### CODE REVIEW

**Comment by benlaurie** [comment]
+1

**Comment by richsalz** [comment]
How about this instead?
```
EVP_DigestVerifyFinal() returns 1 for success; any other value indicates failure.  A return value of zero indicates that the signature did not verify successfully (that is, tbs did not match the original data or the signature had an invalid form), while other values to indicate a more serious error (and sometimes also indicate an invalid signature form).
```

**Comment by aeijdenberg** [comment]
Changed as suggested by Rich (with one minor change, removed extraneous "to").

**Comment by levitte** [comment]
+1

**Comment by richsalz** [comment]
done in master and 1.0.2; thanks.

**Comment by levitte** [comment]
Any reason why not 1.0.1?

**Comment by richsalz** [comment]
oops.  and 1.0.1

**Comment by levitte** [comment]
Thanks :-)

**Pull request closed without merging**
