### PR TITLE
fix: a error about bits of sm2 public key in the sm2 cert.

### PR DESCRIPTION
**Pull request by ymj-uos**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by ymj-uos** [comment]
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            fd:3e:26:d8:5a:c1:ae:b6:5b:2c:11:ac:60:31:87:d3
        Signature Algorithm: SM2-with-SM3
        Issuer: C=CN, O=沃通电子认证服务有限公司, CN=国密SM2根证书
        Validity
            Not Before: Oct 25 06:28:18 2019 GMT
            Not After : Oct 25 06:28:18 2034 GMT
        Subject: C=CN, O=沃通电子认证服务有限公司, CN=国密SM2服务器根证书V1
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:d8:b9:b8:db:4f:ec:dd:3d:fc:1c:f2:f3:5b:e4:
                    3b:2e:19:80:98:88:f5:61:df:cb:a9:ad:be:6c:cd:
                    dc:f3:92:44:49:20:90:e9:0f:c5:b4:3b:07:7d:51:
                    61:e9:59:9c:93:d6:af:3c:7c:2a:05:3b:29:eb:96:
                    85:33:a2:e7:f4
                ASN1 OID: SM2
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                31:B8:15:87:4C:CC:37:97:3A:ED:EF:4D:91:4A:2B:AD:0B:35:76:20
            X509v3 Subject Key Identifier: 
                96:87:FA:EC:C1:52:A6:31:DA:90:C1:16:5D:B2:78:A0:D6:29:FA:15
            X509v3 CRL Distribution Points: 
                Full Name:
                  URI:http://crl.wotrus.com/wotrus-sm2.crl
            Authority Information Access: 
                OCSP - URI:http://ocsp.wotrus.com
                CA Issuers - URI:http://aia.wotrus.com/wotrus-sm2.cer
            X509v3 Certificate Policies: 
                Policy: 1.2.156.150570.3.1
                  CPS: http://www.wotrus.com/policy/
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
    Signature Algorithm: SM2-with-SM3
    Signature Value:
        30:45:02:20:4d:33:70:26:4e:69:e5:df:c5:56:a7:25:8d:ef:
        cb:38:59:50:57:b4:ab:f1:3d:a5:a9:90:e3:0f:81:05:f4:7f:
        02:21:00:d0:52:e3:8a:fa:f1:af:29:6c:30:2b:1b:db:21:91:
        b6:f5:2a:e1:09:d5:de:86:db:5a:f0:ad:05:f4:13:c7:0a

**Comment by ymj-uos** [comment]
`Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            fd:3e:26:d8:5a:c1:ae:b6:5b:2c:11:ac:60:31:87:d3
        Signature Algorithm: SM2-with-SM3
        Issuer: C=CN, O=沃通电子认证服务有限公司, CN=国密SM2根证书
        Validity
            Not Before: Oct 25 06:28:18 2019 GMT
            Not After : Oct 25 06:28:18 2034 GMT
        Subject: C=CN, O=沃通电子认证服务有限公司, CN=国密SM2服务器根证书V1
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:d8:b9:b8:db:4f:ec:dd:3d:fc:1c:f2:f3:5b:e4:
                    3b:2e:19:80:98:88:f5:61:df:cb:a9:ad:be:6c:cd:
                    dc:f3:92:44:49:20:90:e9:0f:c5:b4:3b:07:7d:51:
                    61:e9:59:9c:93:d6:af:3c:7c:2a:05:3b:29:eb:96:
                    85:33:a2:e7:f4
                ASN1 OID: SM2
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                31:B8:15:87:4C:CC:37:97:3A:ED:EF:4D:91:4A:2B:AD:0B:35:76:20
            X509v3 Subject Key Identifier: 
                96:87:FA:EC:C1:52:A6:31:DA:90:C1:16:5D:B2:78:A0:D6:29:FA:15
            X509v3 CRL Distribution Points: 
                Full Name:
                  URI:http://crl.wotrus.com/wotrus-sm2.crl
            Authority Information Access: 
                OCSP - URI:http://ocsp.wotrus.com
                CA Issuers - URI:http://aia.wotrus.com/wotrus-sm2.cer
            X509v3 Certificate Policies: 
                Policy: 1.2.156.150570.3.1
                  CPS: http://www.wotrus.com/policy/
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
    Signature Algorithm: SM2-with-SM3
    Signature Value:
        30:45:02:20:4d:33:70:26:4e:69:e5:df:c5:56:a7:25:8d:ef:
        cb:38:59:50:57:b4:ab:f1:3d:a5:a9:90:e3:0f:81:05:f4:7f:
        02:21:00:d0:52:e3:8a:fa:f1:af:29:6c:30:2b:1b:db:21:91:
        b6:f5:2a:e1:09:d5:de:86:db:5a:f0:ad:05:f4:13:c7:0a
`

**Comment by ymj-uos** [comment]
Public-Key: (256 bit)
                pub:
                    04:d8:b9:b8:db:4f:ec:dd:3d:fc:1c:f2:f3:5b:e4:
                    3b:2e:19:80:98:88:f5:61:df:cb:a9:ad:be:6c:cd:
                    dc:f3:92:44:49:20:90:e9:0f:c5:b4:3b:07:7d:51:
                    61:e9:59:9c:93:d6:af:3c:7c:2a:05:3b:29:eb:96:
                    85:33:a2:e7:f4
                ASN1 OID: SM2

**Comment by ymj-uos** [comment]
[wotrus_uos_sm2_ca.zip](https://github.com/openssl/openssl/files/7658850/wotrus_uos_sm2_ca.zip)

**Comment by ymj-uos** [comment]
$ openssl x509 -text -noout -in ~/wotrus_uos_sm2_ca.crt

use the openssl x509 command to show a sm2 cert, the bits of public key is 512, but the result is 256 bits.

**Comment by ymj-uos** [comment]
image

this should be the correct result in the image.

**Comment by ymj-uos** [comment]
@t8m Hi, I am very thanks to your replying and patience, but I have some doubts to ask. I search lots of materials and standards to prove what you told me. I do not get any proof to say this "Public-Key" is equal to the number of bits of the (ECC/SM2) curves, but some my friends ask me why "Public-Key" is equal to 256bit (in fact it does have 512 bits, I agree it has two parts as well). If possible, would you give me more information?

**Comment by t8m** [comment]
Try:
```
openssl x509 -text -noout -in test/certs/ca-cert-ec-named.pem 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = Root CA
        Validity
            Not Before: Dec 12 20:18:27 2020 GMT
            Not After : Dec 13 20:18:27 2120 GMT
        Subject: CN = CA
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:fb:7e:31:70:a2:f7:ec:33:b4:4b:e6:74:6d:84:
                    55:29:3b:6c:08:89:31:72:57:5b:fb:b4:35:b7:06:
                    0a:ba:db:84:ed:4d:25:21:c7:57:72:e4:b3:cf:3c:
                    b2:a7:92:3e:1f:db:89:ff:c0:48:9d:07:5f:e5:5a:
                    ac:c5:28:14:82
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: 
                Certificate Sign, CRL Sign
            X509v3 Subject Key Identifier: 
                63:8A:05:39:44:4C:FC:2F:07:F5:88:3E:A6:00:B5:61:B0:72:1A:9E
            X509v3 Authority Key Identifier: 
                keyid:8E:F5:25:AF:1E:9B:6B:84:3D:7C:80:9A:C9:53:9C:4D:72:F7:A3:52
```

As you can see here the curve is the prime256v1 which is 256 bit curve. It would be very confusing to call the public key 512 bit one (although the encoding being uncompressed means that it really has 512 bits + the encoding marker byte) when the private key is 256 bit one. Also there is no separate call EVP_PKEY_get_public_key_bits() or whatever... And the EVP_PKEY_get_bits() is defined to be specific to the crypto system. It does not mean it is the length of the encoded public key in bits.

**Comment by t8m** [comment]
Just one more case - in case of RSA, the public key has also two parts - `n` and `e` - the public exponent bits are not counted in the RSA public key bits either.

**Pull request closed without merging**
