### PR TITLE
Better way to recognise mingw64 in config script

### PR DESCRIPTION
**Pull request by levitte**
This is an amendment of #2914

### CODE REVIEW

**Comment by levitte** [comment]
@dot-asm, I'd appreciate it if you had a look.

**Review by dot-asm — APPROVED** [review]
Looks proper

**Comment by dot-asm** [comment]
Red cross from travis is unrelated, ready to go [no surprise here].

**Comment by levitte** [comment]
Grand, thanks!  (and thanks for your patience)

master: 41bee3e8fb749504f21f78dbf3eca85e5b84820b
1.1.0: 641de7f7874439eb423eb7ace8fec58160cd6e37
1.0.2: d843779ddf77aec75bcbc4666bc1fdeb9b120fe4

**Pull request closed without merging**
