### PR TITLE
provider-keymgmt.pod: fix typo

### PR DESCRIPTION
**Pull request by rilysh**
In openssl/doc/man7/provider-keymgmt.pod, from asymmmetric to asymmetric (the previous one adds one extra "m").

### CODE REVIEW

**Comment by rilysh** [comment]
I'm a bit confused with CLA. This is a _very_ minor spelling change (almost unnoticeable) and I'm not sure what CLA tag it requires (either trivial or something else). Rules in CONTRIBUTION.md is vague to me.

Can anyone kindly help me out?

**Comment by InfoHunter** [comment]
This fix is trivial, so you can just add 'CLA: trivial' in the commit message separated by an empty line from the rest of the message. As per: https://www.openssl.org/policies/cla.html

**Comment by rilysh** [comment]
@InfoHunter Thanks for your reply, I've added the CLA: trivial section.

**Review by InfoHunter — APPROVED** [review]

**Review by t8m — APPROVED** [review]
OK with CLA: trivial

**Comment by t8m** [comment]
Merged to the master, 3.2, 3.1 and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
