### PR TITLE
Merge two internal/rand.h files into one

### PR DESCRIPTION
**Pull request by richsalz**
Fix issue found by #3974

### CODE REVIEW

**Comment by tmshort** [comment]
This fixes the build problems introduced with #3974, although I think that PR there should really have been:

`#include <internal/rand.h>`

Since there's no crypto/rand/include/rand.h file.

**Comment by richsalz** [comment]
You’re probably right.  But having two files was my initial mistake ☺

**Comment by richsalz** [comment]
ping @levitte ...

**Comment by levitte** [comment]
No. This doesn't conform to the intent and purpose of having two different internal directories.

The idea is that header files in `crypto/include/internal/` are strictly internal to libcrypto, i.e. not (intentionally) exported in libcrypto.so.  Header files in `include/internal/` are libcrypto symbols that libssl needs, i.e. are exported in libcrypto.so.

If you look again, you will notice that some header files in `crypto/include/internal` have `_int` added to them.  The purpose is to disambiguate them while still providing the separation between strictly libcrypto only symbols and internal symbols that aren't.  So my suggestion is to do the same thing with `crypto/include/internal/rand.h`, i.e. rename it to crypto/include/internal/rand_int.h` and fix the inclusions where appropriate.

Side note: is the DRBG API internal on purpose?  If not, the proper change would be to move the contents of `include/internal/rand.h` to `include/openssl/rand.h`

**Comment by levitte** [comment]
@tmshort, the difference between

``` C
#include "internal/whatever.h"
```

and

``` C
#include <internal/whatever.h>
```

is exactly zero.

**Comment by richsalz** [comment]
Okay, I will close this and open a new PR that moves crypto/include/internal/rand.h to rand_int.h

And to answer your side note, yes: SSL will need the RAND_DRBG API.

**Comment by richsalz** [comment]
See #3979; closing this.

**Comment by tmshort** [comment]
@levitte, no.
The quote format `#include "file.h"` is used to reference local include files relative to the current directory, and if that file is not found, the compiler's include path is searched.
The angle-bracket format `#include <file.h>` is used to reference header files that are located in the compiler's include path.
While the results may end up referencing the same file, they have different semantics.

**Comment by levitte** [comment]
@tmshort, I meant in practice in this case, i.e. it ends up reading the exact same file regardless of syntax.

**Comment by tmshort** [comment]
@levitte, yes, in this case the result is no-difference (and I indicated that possibility in my response). But the original statement was not qualified, and if directed at a contributor with a lesser ego, it might discourage them from contributing. :)

**Comment by levitte** [comment]
Yeah ok, good point.  I didn't think of the social aspect.

**Pull request closed without merging**
