### PR TITLE
Add ARIA as an alias for all ARIA based modes.

### PR DESCRIPTION
**Pull request by paulidale**
Include ARIA as an alias for ARIA based TLS modes.
`ciphers ARIA` works after this.

- [x] documentation is added or updated

### CODE REVIEW

**Comment by dot-asm** [comment]
But throw in some man1/ciphers.pod update too, as discussed in #4287 :-)

[Just in case, I'm signing off for today soon...]

**Comment by paulidale** [comment]
Done the ciphers.pod update

**Comment by paulidale** [comment]
Merged, thanks.

**Comment by tuchik** [comment]
paypal.me/tuchikdevill

**Pull request closed without merging**
