### PR TITLE
Remove some utilities from the core to provider interface

### PR DESCRIPTION
**Pull request by mattcaswell**
The core providers a number of essential functions as "upcalls" to
providers. Some of those were just utility functions that wrap other
upcalls - which don't seem essential and bloat the interface. We should
remove them in order to simplify the interface.

### CODE REVIEW

**Comment by richsalz** [comment]
If this works, you should also think of re-merging ```mem_str.c``` back into ```o_str.c```

**Comment by levitte** [comment]
> If this works, you should also think of re-merging ```mem_str.c``` back into ```o_str.c```

I agree with @richsalz on this

**Comment by mattcaswell** [comment]
> If this works, you should also think of re-merging mem_str.c back into o_str.c

Sure. I hadn't realised it had been split out in the first place. Done in a fixup commit.

**Comment by mattcaswell** [comment]
Travis is doing something weird. Above it says the travis builds are "pending" - but if I click into the details it shows all builds as green. Anyway I interpret that as all the CIs agreeing as per @levitte's comment above.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
