### PR TITLE
Correct printing of some otherName variants

### LINKED ISSUE #9950: Add support for reading SRVName in Subject Alternative Name
## Steps to reproduce

Take the following x509 certificate (`localhost.crt`) as an example:

```
-----BEGIN CERTIFICATE-----
MIIENzCCAx+gAwIBAgIUUKcPZOo+pk0x6K+BtkURLsQ+A48wDQYJKoZIhvcNAQEL
BQAwgY0xCzAJBgNVBAYTAkdCMRUwEwYDVQQHDAxUaGUgSW50ZXJuZXQxGjAYBgNV
BAoMEVlvdXIgT3JnYW5pc2F0aW9uMRgwFgYDVQQLDA9YTVBQIERlcGFydG1lbnQx
EjAQBgNVBAMMCWxvY2FsaG9zdDEdMBsGCSqGSIb3DQEJARYOeG1wcEBsb2NhbGhv
c3QwHhcNMTkwOTE5MjA0NzQ4WhcNMjAwOTE4MjA0NzQ4WjCBjTELMAkGA1UEBhMC
R0IxFTATBgNVBAcMDFRoZSBJbnRlcm5ldDEaMBgGA1UECgwRWW91ciBPcmdhbmlz
YXRpb24xGDAWBgNVBAsMD1hNUFAgRGVwYXJ0bWVudDESMBAGA1UEAwwJbG9jYWxo
b3N0MR0wGwYJKoZIhvcNAQkBFg54bXBwQGxvY2FsaG9zdDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBANZs3HwyTADtngwkrx0IlyG9LlaHMF4SyHsQwZLB
JG4f8o7f2XlwQ3Xk7CV8m58oIONH143xtVzmkSPMxe/gZ8XpJdko1vz7+FOGxGeo
rqmbJs+3X2vyXf4r/PqQmqAjhe4fAfhB4X0YEP43epv/Kf5Ryl4W0Ecj0eR1us4o
HMfX8dzUqPtU4lrBllLfOZUKTxTjURX/vsboKJTRKlHOyr9iQZameus1Rnm2ant2
NqVlJWvgxvu64XO0qXo598QGZU5LHK/3B0tTaSbIk62LsfkHFLkWh0BgVTutgdyH
gcEJRdlQYSju6nndIN56AXfOaMEhA2M+yQXSDrDXMRJ0WA0CAwEAAaOBjDCBiTAM
BgNVHRMEBTADAQH/MHkGA1UdEQRyMHCCCWxvY2FsaG9zdKAkBggrBgEFBQcIB6AY
FhZfeG1wcC1jbGllbnQubG9jYWxob3N0oCQGCCsGAQUFBwgHoBgWFl94bXBwLXNl
cnZlci5sb2NhbGhvc3SgFwYIKwYBBQUHCAWgCwwJbG9jYWxob3N0MA0GCSqGSIb3
DQEBCwUAA4IBAQCMByZU+InGgYIW8A032//tULFtf6O1rByTNQv0B+fQ6oWEZyIk
490A6lZhtltRvge1QYUXz2/guowLzo6zUBebV/Ezvg3JNGUY33NHPVdIJ76c3z5y
1BdunXTaLCF8ML1UuUvG/UaotA7UWSK7rRf79KBm4y6xwxyzUcsnjyLK67MoNT+t
kE3ZnkqtygFSqps8YkXZ33QB5I50XxhJDUtfyK9m1DNUzSDDBJnJVBXxU2yrqDto
81U1g/m8FU47GUtnQGb5sBmCs5Zp6Y7sBirf1k49tK+vKH33/YAxXTvpTPTGtaZb
VMaxqZWNM79oHlzCAW8LUI4Ex7WUcEvOepQU
-----END CERTIFICATE-----
```

`openssl x509 -in localhost.crt -text`

## What happens

`SRVName` entries appear as `othername:<unsupported>`

## Expected behaviour

`SRVName` entries appear as `SRVName: somedomain`

(`SRVName: _xmpp-client.localhost, _xmpp-server.localhost` I think for this specific certificate)

The OID for this entry is `1.3.6.1.5.5.7.8.7` (http://oid-info.com/cgi-bin/display?oid=1.3.6.1.5.5.7.8.7&action=display)

### LINKED ISSUE #9951: Add support for reading xmppAddr in Subject Alternative Name
## Steps to reproduce

Take the following x509 certificate (`localhost.crt`) as an example:

```
-----BEGIN CERTIFICATE-----
MIIENzCCAx+gAwIBAgIUUKcPZOo+pk0x6K+BtkURLsQ+A48wDQYJKoZIhvcNAQEL
BQAwgY0xCzAJBgNVBAYTAkdCMRUwEwYDVQQHDAxUaGUgSW50ZXJuZXQxGjAYBgNV
BAoMEVlvdXIgT3JnYW5pc2F0aW9uMRgwFgYDVQQLDA9YTVBQIERlcGFydG1lbnQx
EjAQBgNVBAMMCWxvY2FsaG9zdDEdMBsGCSqGSIb3DQEJARYOeG1wcEBsb2NhbGhv
c3QwHhcNMTkwOTE5MjA0NzQ4WhcNMjAwOTE4MjA0NzQ4WjCBjTELMAkGA1UEBhMC
R0IxFTATBgNVBAcMDFRoZSBJbnRlcm5ldDEaMBgGA1UECgwRWW91ciBPcmdhbmlz
YXRpb24xGDAWBgNVBAsMD1hNUFAgRGVwYXJ0bWVudDESMBAGA1UEAwwJbG9jYWxo
b3N0MR0wGwYJKoZIhvcNAQkBFg54bXBwQGxvY2FsaG9zdDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBANZs3HwyTADtngwkrx0IlyG9LlaHMF4SyHsQwZLB
JG4f8o7f2XlwQ3Xk7CV8m58oIONH143xtVzmkSPMxe/gZ8XpJdko1vz7+FOGxGeo
rqmbJs+3X2vyXf4r/PqQmqAjhe4fAfhB4X0YEP43epv/Kf5Ryl4W0Ecj0eR1us4o
HMfX8dzUqPtU4lrBllLfOZUKTxTjURX/vsboKJTRKlHOyr9iQZameus1Rnm2ant2
NqVlJWvgxvu64XO0qXo598QGZU5LHK/3B0tTaSbIk62LsfkHFLkWh0BgVTutgdyH
gcEJRdlQYSju6nndIN56AXfOaMEhA2M+yQXSDrDXMRJ0WA0CAwEAAaOBjDCBiTAM
BgNVHRMEBTADAQH/MHkGA1UdEQRyMHCCCWxvY2FsaG9zdKAkBggrBgEFBQcIB6AY
FhZfeG1wcC1jbGllbnQubG9jYWxob3N0oCQGCCsGAQUFBwgHoBgWFl94bXBwLXNl
cnZlci5sb2NhbGhvc3SgFwYIKwYBBQUHCAWgCwwJbG9jYWxob3N0MA0GCSqGSIb3
DQEBCwUAA4IBAQCMByZU+InGgYIW8A032//tULFtf6O1rByTNQv0B+fQ6oWEZyIk
490A6lZhtltRvge1QYUXz2/guowLzo6zUBebV/Ezvg3JNGUY33NHPVdIJ76c3z5y
1BdunXTaLCF8ML1UuUvG/UaotA7UWSK7rRf79KBm4y6xwxyzUcsnjyLK67MoNT+t
kE3ZnkqtygFSqps8YkXZ33QB5I50XxhJDUtfyK9m1DNUzSDDBJnJVBXxU2yrqDto
81U1g/m8FU47GUtnQGb5sBmCs5Zp6Y7sBirf1k49tK+vKH33/YAxXTvpTPTGtaZb
VMaxqZWNM79oHlzCAW8LUI4Ex7WUcEvOepQU
-----END CERTIFICATE-----
```

`openssl x509 -in localhost.crt -text`

## What happens

`xmppAddr` entries appear as `othername:<unsupported>`

## Expected behaviour

`xmppAddr` entries appear as `xmppAddr: someaddr`

(`xmppAddr: localhost` I think for this specific certificate)

The OID for this entry is 1.3.6.1.5.5.7.8.5 (http://oid-info.com/cgi-bin/display?oid=1.3.6.1.5.5.7.8.5&action=display)

### PR DESCRIPTION
**Pull request by beldmit**
Fixes #9950 
Fixes #9951 

Implementing printing out of some otherName variants:
xmppAddr
srvName
SmtpUTF8Mailbox (partially interferes with #9654).

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by dcooper16** [comment]
May I suggest adding the [Microsoft Universal Principal Name](https://support.microsoft.com/en-us/help/281245/guidelines-for-enabling-smart-card-logon-with-third-party-certificatio) to the list of otherName types that can be printed? The OID is already recognized by OpenSSL (SN_ms_upn, LN_ms_upn, NID_ms_upn, OBJ_ms_upn, etc. are already defined). The UPN is encoded as a UTF8String.

**Comment by beldmit** [comment]
Not a problem, but not just now.

**Comment by beldmit** [comment]
Done

**Comment by beldmit** [comment]
Would it be better to squash all the commits in one or leave as is?

**Comment by paulidale** [comment]
Squashing is generally better.

For the record: I approve a squashed version unseen.

**Comment by beldmit** [comment]
Merged. Thanks!

**Comment by Neustradamus** [comment]
Merged commit here:
- https://github.com/openssl/openssl/commit/4baee2d72e0c82bfd6de085df23a1bdc6af887ba

**Pull request closed without merging**
