### PR TITLE
Pass a required strength argument to RNG calls

### LINKED ISSUE #15512: Add strength argument to random number generation calls
There are a number of new calls introduced relating to library contexts and random number generation:

- `BN_rand_ex()`
- `BN_priv_rand_ex()`
- `BN_rand_range_ex()`
- `BN_priv_rand_range_ex()`
- `RAND_bytes_ex()`
- `RAND_priv_bytes_ex()`

It would make sense to also introduce an extra argument to these calls `unsigned int strength` to includes the security strength required of the generation.

The underlying EVP_RAND_CTX generate calls support this, so it's a matter of plumbing the argument through.  This part is straightforward and would need to be done before beta.

All calls to these functions from within libcrypto and libssl would need to be updated, however it wouldn't be necessary for a value other than zero to be passed for the moment.  That is, the full enforcement of security strengths could be postponed.

### PR DESCRIPTION
**Pull request by paulidale**
For the newly introduced RNG calls, it makes sense to include a required strength argument now rather than having to introduce another suite of calls later.  The plumbing and strength checks are already in place in providers, so this is just passing through the argument.

Fixes #15512

- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by slontis — COMMENTED** [review]
Documenting this as working may be a bad idea at the moment since it is just a dummy placeholder. What does the value of 0 mean?

**Comment by FdaSilvaYY** [comment]
Typo in 1st commit message

**Comment by t8m** [comment]
> Documenting this as working may be a bad idea at the moment since it is just a dummy placeholder. What does the value of 0 mean?

But it is already working? If you pass the strength you will get random bytes with at least the strength or an error. And 0 is simply strength of 0 - at least.

**Review by t8m — APPROVED** [review]

**Comment by paulidale** [comment]
@t8m is correct, an argument of zero is asking for a security strength of not less than zero bits.  I.e. it will always return bytes.

**Comment by paulidale** [comment]
Merged, thanks for the reviews.

**Comment by t-j-h** [comment]
This really points out a. Issue that the *user* has no way to change that strength value in the majority of the places you've touched and that means the API change isn't particularly useful. 

This was part of what we discussed in the OTC meeting - that we didn't have a way to set that information in all that places that we would need in order for RNG strength to make sense in terms of something a user could control more selectively.

This is something that shouldn't have gone in a this stage without an OTC discussion.

**Comment by paulidale** [comment]
I disagree.  This isn't about enforcement of the minimum strength throughout the library.  That will be a decision for the OTC to make at some point in the future and it is complicated as you note.

Rather, this is about getting the API right now while it can still be changed.  Is a minimum strength parameter useful?  I think so.  If it isn't included now, we would need to introduce _ex2 functions to accomodate it in the future.

An open question would be about prediction resistance: should that be added before API freeze?  It doesn't seem anything like as useful.

**Comment by t-j-h** [comment]
Completely disagree. We discussed that the API plumbing didn't allow us to pass stuff around in the right way for the user to meaningfully provide that information so it was something we would have to sort out later - where later means post-3.0 and effectively 4.0 given API changes.

What you have here is passing around a pile of 0 values which the user has no way to influence at all which makes it not actually useful for the user. Having something we do automatically for the user that does nothing more than what we had previously and does not allow any user interaction isn't meaningfully solving that problem. And that was the problem we agreed to defer because it would have a pile of API impacts.

**At this stage of 3.0 we should not be having a change like this drop suddenly without broader discussion.** 
I would have placed an OTC hold of this immediately if I wasn't away from access ... the other planned changes which impact APIs have been discussed with plenty of time for a consensus view. This one was not - and that is in my view rather poor form.

Something the user could set against a LIBCTX (and also set in CONF) would make sense - but that isn't what is done here.

**Pull request closed without merging**
