### PR TITLE
doc: Fix keymgmt functions parameters

### PR DESCRIPTION
**Pull request by Lipovlan**
CLA: trivial

Make OSSL_FUNC_keymgmt_import and OSSL_FUNC_keymgmt_export documentation correspond to core_dispatch.h signatures

### CODE REVIEW

**Review by t8m — APPROVED** [review]
Approved with CLA: trivial

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
I agree this is trivial

**Comment by mattcaswell** [comment]
The CI failures are odd but don't seem relevant to the changes in this PR

**Comment by t8m** [comment]
Merged to master and 3.0 branches. Thank you for your contribution.

**Pull request closed without merging**
