### PR TITLE
DECODER: Handle abstract object data type

### PR DESCRIPTION
**Pull request by levitte**
The PEM->DER decoder passes the data type of its contents, something
that decoder_process() ignored.

On the other hand, the PEM->DER decoder passed nonsense.

Both issues are fixed here.

### CODE REVIEW

**Comment by levitte** [comment]
This partially fixes the problems found in #13050.

**Review by mattcaswell — APPROVED** [review]
LGTM. From a testing perspective the test in #13050 should be sufficient to cover this.

**Comment by levitte** [comment]
> From a testing perspective the test in #13050 should be sufficient to cover this.

Yes

**Comment by levitte** [comment]
Merged

ecadfdadde491572b0bdf3c5a95e7a6a004585c6 DECODER: Handle abstract object data type

**Pull request closed without merging**
