### PR TITLE
Join the x509 and x509v3 directories

### LINKED ISSUE #8919: x509 and x509v3 directories are intermixed and should perhaps be combined

### PR DESCRIPTION
**Pull request by levitte**
This has been long overdue.

Note that this does not join the X509 and X509V3 error modules, that
will be too many macro changes at this stage.

Fixes #8919

### CODE REVIEW

**Comment by levitte** [comment]
Oh, I should probably add a note in CHANGES

**Comment by levitte** [comment]
Done

**Comment by slontis** [comment]
Needs a rebase..

**Comment by slontis** [comment]
After collapsing the v3 folder, does not merging the error modules cause any issues if a new error code is added?

**Comment by levitte** [comment]
> After collapsing the v3 folder, does not merging the error modules cause any issues if a new error code is added?

Nope.  It turns out that several error modules can coexist in the same directory, as they all depend on the start of the `_F_` and `_R_` macro names.

**Comment by levitte** [comment]
Rebase done

**Review by slontis — CHANGES_REQUESTED** [review]
Needs a rebase - I approve otherwise

**Comment by levitte** [comment]
> Needs a rebase - I approve otherwise

So err, I did the rebase, I'll take that as approval.

**Comment by slontis** [comment]
The CI loop hasnt finished yet :)

**Comment by levitte** [comment]
One thing I haven't quite dived into is joining `include/openssl/x509.h` and `include/openssl/x509v3.h`...  should that be part of this PR, or should I make a new PR for it?

**Review by slontis — APPROVED** [review]

**Comment by slontis** [comment]
new PR maybe

**Comment by levitte** [comment]
Merged.

878dc8dd9572a719d3b481e7f68af8bf17f4c68e Join the x509 and x509v3 directories

**Comment by richsalz** [comment]
You'll have to make sure a stub x509v3 file exists to not break applications of course.

**Comment by mspncp** [comment]
> You'll have to make sure a stub x509v3 file exists to not break applications of course.

I guess you are talking about the `x509v3.h` include file? No public include files were modified by this commit: 

```
git show --stat 878dc8dd9572 -- include
```

**Pull request closed without merging**
