### PR TITLE
Allow more than 32 KeyUpdates per connection

### LINKED ISSUE #8068: Only 32 KeyUpdates allowed per-connection
The use of [`key_update_count`](https://github.com/openssl/openssl/blob/master/ssl/statem/statem_lib.c#L617) strictly limits the number of TLS 1.3 KeyUpdate messages to 32 on a connection, irrespective of how long-lived the connection is or how much data is passing over it. While limiting a flood of KeyUpdate messages without any application data flow makes sense, a limit this strict seems like it'll trip up applications that try to rotate keys every <i>x</i> MBs of data, or <i>y</i> hours of time, etc.

(Note, in BoringSSL we have the same variable but it limits the number of _consecutive_ KeyUpdate messages. So application data resets the count. The limit there is just designed to avoid being an unbounded sink of network data without the upper levels of the stack ever seeing an event.)

### PR DESCRIPTION
**Pull request by mattcaswell**
We reset the max updates count as soon as we receive some non empty app
data. This means as long as we've received some app data more than 32
KeyUpdates can be handled in a connection.

Fixes #8068

### CODE REVIEW

**Comment by kroeckx** [comment]
I still see one potential case where me might be running into a problem. In case a peer is sending a lot of data, and at regular intervals does a key update and also requests one from the other side, that other side could either not send the key update yet until it has some application data to send, or it might directly reply and we might end up with more than 32 key updates with app data.

**Comment by mattcaswell** [comment]
Yes, I suppose that might be possible. I'm not sure how much we should be worried about that. We *could* additionally reset the count if we write app data. Not sure its worth it or not??

**Comment by kroeckx** [comment]
Or we could reset the counter in case we send a key update

**Comment by kroeckx** [comment]
But that only makes sense if we wait with replying until we have app data to send.

**Comment by davidben** [comment]
This sort of thing came up during standardization and is why KeyUpdate has separate `update_requested` vs `update_not_requested` modes and some text about coalescing.

From https://tools.ietf.org/html/rfc8446#section-4.6.3 (emphasis mine):
>   If the request_update field is set to "update_requested", then the
>   receiver MUST send a KeyUpdate of its own with request_update set to
>   "update_not_requested" **prior to sending its next Application Data**
>   **record**.  This mechanism allows either side to force an update to the
>   entire connection, but *causes an implementation which receives**
>   **multiple KeyUpdates while it is silent to respond with a single**
>   **update**.  Note that implementations may receive an arbitrary number of
>   messages between sending a KeyUpdate with request_update set to
>   "update_requested" and receiving the peer's KeyUpdate, because those
>   messages may already be in flight.  However, because send and receive
>   keys are derived from independent traffic secrets, retaining the
>   receive traffic secret does not threaten the forward secrecy of data
>   sent before the sender changed keys.

Here is the discussion thread for background: https://mailarchive.ietf.org/arch/msg/tls/cfw4paCGxI7Fj8QNmj6k1I66VII

The intent of this text was to allow a very simple implementation. Maintain a simple boolean flag on the connection. If you see an KeyUpdate on `SSL_read`, set the flag. If the flag is set when encrypting an application record in `SSL_write`, stick a KeyUpdate in front and clear the flag. This avoids tying together read and write channels and ensures bounded write overhead, both of which are important to prevent DoS.

**Comment by davidben** [comment]
The flags-based strategy also avoids introducing a variation of #7967. Otherwise an HTTP/1.1 server may read a bunch of KeyUpdates in the middle of a large POST body but, because the client is not yet reading from the socket, the KeyUpdates get stuck in a transport buffer. Then, since OpenSSL models KeyUpdates as an I/O-halting handshake (cf. #8069 ;-) ), the connection deadlocks.

(In general, read-triggered writes and write-triggered reads rarely work well and it's best to avoid them. Fundamentally, TLS is layered over a flow-controlled transport but does not control how fast each half flows. You want to avoid deviating from a dumb filter as much as possible. When you are forced to, all aspects of the application protocol need to be aware of what's happening for it to work.)

**Comment by kroeckx** [comment]
@mattcaswell: Can you confirm that we currently use a flag or not? Based on some of the things I read, I think we don't and so might cause the other side to say we've send too many key updates. If that's the case, I think we should fix this. I think it would also be good that we test that.

**Comment by mattcaswell** [comment]
No, we don't use the flag based approach. See this code in `ossl_statem_server13_write_transition()`:

````
    case TLS_ST_SR_KEY_UPDATE:
        if (s->key_update != SSL_KEY_UPDATE_NONE) {
            st->hand_state = TLS_ST_SW_KEY_UPDATE;
            return WRITE_TRAN_CONTINUE;
        }
        /* Fall through */

    case TLS_ST_SW_KEY_UPDATE:
        st->hand_state = TLS_ST_OK;
        return WRITE_TRAN_CONTINUE;
````

So basically if we just read a key update message then we check the status of `s->key_update`. If we just received an "update requested" key update message then `s->key_update` will not be SSL_KEY_UPDATE_NONE, and we immediately proceed to writing out our own key update. Otherwise we stop processing post handshake messages.

I don't particularly feel any need to change that but wouldn't object if someone else wanted to take it on.

**Comment by kroeckx** [comment]
My understanding is that with this PR, we're still unable to talk
to ourself when the sender requests many updates, because it's
sending a lot of data, and we don't write any data back. I don't
think that's behaviour we want. And the flag based solution seems
like the best way to avoid this.

**Comment by mattcaswell** [comment]
> My understanding is that with this PR, we're still unable to talk to ourself when the sender requests many updates, because it's sending a lot of data, and we don't write any data back. I don't think that's behaviour we want. And the flag based solution seems like the best way to avoid this.

I'm not keen on the flags based approach because it feels like overkill to me (requiring changes to the state machine) for what is a comparatively simple problem.

I've updated this PR to additionally reset the count in the event that we write application data. This I think addresses the problem you are describing.

**Comment by davidben** [comment]
I don't believe that addresses the unbounded writes DoS, but that can also be fixed orthogonally as it's more about the sending side than the receiving side.

(I found the flags-based implementation pretty straightforward, but we did also redo the write path quite a bit, to properly support 0-RTT's need to concurrently write early data and react to ServerHello and other edge cases. I don't remember what bits of it were on-path to KeyUpdate or not.)

**Comment by kroeckx** [comment]
I think you're still not understanding what I'm saying. If you apply the following patch it fails:
```
--- a/test/sslapitest.c
+++ b/test/sslapitest.c
@@ -4463,7 +4463,7 @@ static int test_key_update(int tst)
         goto end;

     for (i = 0; i < MAX_KEY_UPDATE_MESSAGES; i++) {
-        if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_NOT_REQUESTED))
+        if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_REQUESTED))
                 || !TEST_true(SSL_do_handshake(clientssl))
                 || !TEST_int_le(SSL_read(serverssl, buf, sizeof(buf)), 0))
             goto end;
@@ -4476,7 +4476,7 @@ static int test_key_update(int tst)
             goto end;
     }

-    if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_NOT_REQUESTED))
+    if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_REQUESTED))
             || !TEST_true(SSL_do_handshake(clientssl)))
         goto end;

@@ -4487,6 +4487,13 @@ static int test_key_update(int tst)
     if (!TEST_int_eq(ret, tst == 0 ? SSL_ERROR_SSL : SSL_ERROR_WANT_READ))
         goto end;

+    ret = SSL_read(clientssl, buf, sizeof(buf));
+    if (!TEST_int_le(ret, 0))
+        goto end;
+    ret = SSL_get_error(clientssl, ret);
+    if (!TEST_int_eq(ret, tst == 0 ? SSL_ERROR_SSL : SSL_ERROR_WANT_READ))
+        goto end;
+
     testresult = 1;

  end:
```

The tests passes when SSL_KEY_UPDATE_NOT_REQUESTED is used, but fails when SSL_KEY_UPDATE_REQUESTED is used.

**Comment by mattcaswell** [comment]
I don't think your patch is actually a fair test. Effectively the client is ignoring all messages it receives on its "read" BIO. If I make the following additional patch then it passes:

````
diff --git a/test/sslapitest.c b/test/sslapitest.c
index ab9657d49c..5034018b10 100644
--- a/test/sslapitest.c
+++ b/test/sslapitest.c
@@ -4465,7 +4465,8 @@ static int test_key_update(int tst)
     for (i = 0; i < MAX_KEY_UPDATE_MESSAGES; i++) {
         if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_REQUESTED))
                 || !TEST_true(SSL_do_handshake(clientssl))
-                || !TEST_int_le(SSL_read(serverssl, buf, sizeof(buf)), 0))
+                || !TEST_int_le(SSL_read(serverssl, buf, sizeof(buf)), 0)
+                || !TEST_int_le(SSL_read(clientssl, buf, sizeof(buf)), 0))
             goto end;
     }
 ````

**Comment by kroeckx** [comment]
I don't understand why that patch should even make a difference. Sure, it's not processing things in it's read BIO at that time, but it does at the end, and actually says there were too many key updates. I don't see why 1 call or 33 calls to SSL_read() should make a difference.

**Comment by mattcaswell** [comment]
While the first loop is running the client (in your version of the test) sends 32 key updates (update requested) but does not attempt to send any application data or attempt to process any records arriving in its read bio (this I claim is an unfair test because it does not seem like a realistic scenario). Therefore at the end of the first loop it has 32 key updates sat in its read bio waiting to be processed.

Next the client sends some app data and the server reads some. This has the affect of zeroing the key update count on both sides of the communication. However (for the client) this update count is already 0 because it hasn't yet processed the 32 waiting key updates sat in its read bio. Next the client sends another key update (update requested) and so now has 33 key updates waiting in its read bio. When the subsequent SSL_read(clientssl, ...) occurs it processes all 33 key updates at once and blows the max key update count limit.

With my additional patch applied the client calls SSL_read() during the first loop and so processes the key updates from the server straight away. Therefore by the end of the first loop all the key updates have been processed and the client's key update count is at 32. Next the client calls SSL_write() which has the effect of setting the key update count back to 0. Finally another key update (update requested) is performed. This time though when the client processes it the key update count starts off at 0 and therefore the maximum is never exceeded.

**Comment by kroeckx** [comment]
So here is an other patch:
```
--- a/test/sslapitest.c
+++ b/test/sslapitest.c
@@ -4462,24 +4462,28 @@ static int test_key_update(int tst)
                                                 SSL_ERROR_NONE)))
         goto end;
 
-    for (i = 0; i < MAX_KEY_UPDATE_MESSAGES; i++) {
+    if (tst == 0) {
+        for (i = 0; i < MAX_KEY_UPDATE_MESSAGES; i++) {
+            if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_NOT_REQUESTED))
+                    || !TEST_true(SSL_do_handshake(clientssl))
+                    || !TEST_int_le(SSL_read(clientssl, buf, sizeof(buf)), 0)
+                    || !TEST_int_le(SSL_read(serverssl, buf, sizeof(buf)), 0))
+                goto end;
+        }
         if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_NOT_REQUESTED))
                 || !TEST_true(SSL_do_handshake(clientssl))
-                || !TEST_int_le(SSL_read(serverssl, buf, sizeof(buf)), 0))
-            goto end;
-    }
-
-    if (tst == 1) {
-        if (!TEST_int_eq(SSL_write(clientssl, mess, strlen(mess)), strlen(mess))
-                || !TEST_int_eq(SSL_read(serverssl, buf, sizeof(buf)),
-                                         strlen(mess)))
+                || !TEST_int_le(SSL_read(clientssl, buf, sizeof(buf)), 0))
             goto end;
+    } else {
+        for (i = 0; i < MAX_KEY_UPDATE_MESSAGES+1; i++) {
+            if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_REQUESTED))
+                    || !TEST_true(SSL_do_handshake(clientssl))
+                    || !TEST_int_eq(SSL_write(clientssl, mess, strlen(mess)), strlen(mess))
+                    || !TEST_int_eq(SSL_read(serverssl, buf, sizeof(buf)), strlen(mess)))
+                goto end;
+        }
     }
 
-    if (!TEST_true(SSL_key_update(clientssl, SSL_KEY_UPDATE_NOT_REQUESTED))
-            || !TEST_true(SSL_do_handshake(clientssl)))
-        goto end;
-
     ret = SSL_read(serverssl, buf, sizeof(buf));
     if (!TEST_int_le(ret, 0))
         goto end;
@@ -4487,6 +4491,13 @@ static int test_key_update(int tst)
     if (!TEST_int_eq(ret, tst == 0 ? SSL_ERROR_SSL : SSL_ERROR_WANT_READ))
         goto end;
 
+    ret = SSL_read(clientssl, buf, sizeof(buf));
+    if (!TEST_int_le(ret, 0))
+        goto end;
+    ret = SSL_get_error(clientssl, ret);
+    if (!TEST_int_eq(ret, tst == 0 ? SSL_ERROR_SSL : SSL_ERROR_WANT_READ))
+        goto end;
+
     testresult = 1;
 
  end:
```

I've made the tst==1 case something that's more realistic, and it still fails. But adding the SSL_read(clientssl) call makes the error go away.

**Comment by mattcaswell** [comment]
So the change you've made there basically has a client repeatedly sending key updates and requesting a response, but not being prepared to read those responses. Again this seems quite unlikely to me. I'm not sure why we should feel we need to support that.

**Comment by kroeckx** [comment]
I just don't agree that that this is unlikely. The API clearly
allows it. But I also think this is the wrong API.

**Comment by mattcaswell** [comment]
Well the API allows you to send more than 32 key updates - without sending or receiving anything. I'm not sure that's wise though - and we could simply choose to document that. An alternative way to fix this issue is just to remove the maximum limit altogether. It's hardly an efficient DoS mechanism.

**Comment by kroeckx** [comment]
Without limit is fine for me.

**Comment by mattcaswell** [comment]
> Without limit is fine for me.

I've implemented that approach in #8299.

**Comment by mattcaswell** [comment]
Closed in favour of #8299

**Comment by mspncp** [comment]
:-)

**Pull request closed without merging**
