### PR TITLE
[DRAFT] Embedding HMAC into FIPS module itself

### PR DESCRIPTION
**Pull request by beldmit**
This patch is a part of Red Hat FIPS-related patches

the code is available here
https://gitlab.com/redhat/centos-stream/rpms/openssl/-/blob/c9s/0033-FIPS-embed-hmac.patch?ref_type=heads

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by beldmit** [comment]
The embedding code itself is
```
OPENSSL_CONF=/dev/null LD_LIBRARY_PATH=. apps/openssl dgst -binary -sha256 -mac HMAC -macopt hexkey:smth < providers/fips.so > providers/fips.so.hmac
objcopy --update-section .rodata1=providers/fips.so.hmac providers/fips.so providers/fips.so.mac
mv providers/fips.so.mac providers/fips.so
```

**Comment by beldmit** [comment]
The embedding code itself is
```
OPENSSL_CONF=/dev/null LD_LIBRARY_PATH=. apps/openssl dgst -binary -sha256 -mac HMAC -macopt hexkey:smth < providers/fips.so > providers/fips.so.hmac
objcopy --update-section .rodata1=providers/fips.so.hmac providers/fips.so providers/fips.so.mac
mv providers/fips.so.mac providers/fips.so
```

**Comment by beldmit** [comment]
The solution looks heavy GNU-ish and I have no idea if it will work on all non-Linux platforms. I strongly suspect the Windows approach should be different.

**Comment by beldmit** [comment]
**OTC: Is there any interest in this feature?**

**Comment by t8m** [comment]
IMO we do not want this unless we have a truly multiplatform solution at least for the major platforms. It is also complicated by stuff like windows binary signatures.

**Comment by mattcaswell** [comment]
This sounds very much like the "incore" value from the 2.0 module which we explicitly decided not to do again when we were designing the 3.0 module.

**Comment by beldmit** [comment]
@mattcaswell Is there any written rationale for this, just for clarity? I understand the downsides of this proposal so I'm totally OK to close it.

**Comment by slontis** [comment]
We agreed fairly early on in the design process to keep it simple.
The complexity required for every different platform for the old FOM is just not worth it.

**Comment by t-j-h** [comment]
There is no requirement to have an embedded marker in the binary and to have in-memory checking - there never has been any FIPS140 requirement that dictates this sort of approach. You have always been permitted in the context of software modules to maintain a check in a separate file. That separate file also can (and does) contain configuration information.

@beldmit is there any particular reason behind this approach in terms of feedback from your lab or is this driven by something other than a FIPS140 requirement?

**Comment by beldmit** [comment]
@t-j-h it is not a FIPS requirement, but it was mentioned at our F2F meeting and we agreed that I should raise the PR to discuss if this is an option for upstream. As there is an agreement that it is not worth efforts, let me close it.

**Pull request closed without merging**
