### PR TITLE
Fix the OCSP responder mode

### LINKED ISSUE #5681: ocsp argument verification regression in multi-process OCSP responder
pkix-ssh ocsp regression test start to fail after implementation of multi-process OCSP responder.

The error message is "Responder mode requires certificate, key, and CA."
It is result of extra code modifications non-related to multi-process responder: " !POINTER " vs " POINTER != NULL " (!?).

### PR DESCRIPTION
**Pull request by mattcaswell**
Broken by commit 3e3c7c36.

Fixes #5681

### CODE REVIEW

**Comment by mspncp** [comment]
ping @mattcaswell: shouldn't this bugfix go into the beta release?

**Comment by mattcaswell** [comment]
No - I figured it wasn't urgent enough for that.

**Comment by mspncp** [comment]
Ok. Just added the 1.1.1. milestone, because it's a bugfix for the next beta.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
