### PR TITLE
make ssl3_ciphers static

### PR DESCRIPTION
**Pull request by vszakats**
Fixes https://github.com/openssl/openssl/issues/673

### CODE REVIEW

**Comment by levitte** [comment]
Yes, I totally agree with that change.

**Comment by richsalz** [comment]
+1, let me know if you want me to do it.

**Comment by levitte** [comment]
Go ahead :-)

**Comment by richsalz** [comment]
done with 475f441, thanks.

**Comment by vszakats** [comment]
Thank you folks! (please `git push`)

**Comment by richsalz** [comment]
pushed

**Pull request closed without merging**
