### PR TITLE
Make X25519 and X448 FIPS unapproved

### PR DESCRIPTION
**Pull request by t8m**
Partially fixes: #22105

##### Checklist

- [x] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by paulidale — APPROVED** [review]

**Review by xnox — CHANGES_REQUESTED** [review]
In `providers/common/capabilities.c` do we also need to exclude X25519 from param_group_list? Is that list being used for key-exchange / TLS?

```diff
 diff --git a/providers/common/capabilities.c b/providers/common/capabilities.c
index f7234615e4..2cb2ee58de 100644
--- a/providers/common/capabilities.c
+++ b/providers/common/capabilities.c
@@ -126,85 +126,83 @@ static const TLS_GROUP_CONSTANTS group_list[] = {
 static const OSSL_PARAM param_group_list[][10] = {
 # ifndef OPENSSL_NO_EC
 #  ifndef OPENSSL_NO_EC2M
     TLS_GROUP_ENTRY("sect163k1", "sect163k1", "EC", 0),
     TLS_GROUP_ENTRY("K-163", "sect163k1", "EC", 0), /* Alias of above */
 #  endif
 #  ifndef FIPS_MODULE
     TLS_GROUP_ENTRY("sect163r1", "sect163r1", "EC", 1),
 #  endif
 #  ifndef OPENSSL_NO_EC2M
     TLS_GROUP_ENTRY("sect163r2", "sect163r2", "EC", 2),
     TLS_GROUP_ENTRY("B-163", "sect163r2", "EC", 2), /* Alias of above */
 #  endif
 #  ifndef FIPS_MODULE
     TLS_GROUP_ENTRY("sect193r1", "sect193r1", "EC", 3),
     TLS_GROUP_ENTRY("sect193r2", "sect193r2", "EC", 4),
 #  endif
 #  ifndef OPENSSL_NO_EC2M
     TLS_GROUP_ENTRY("sect233k1", "sect233k1", "EC", 5),
     TLS_GROUP_ENTRY("K-233", "sect233k1", "EC", 5), /* Alias of above */
     TLS_GROUP_ENTRY("sect233r1", "sect233r1", "EC", 6),
     TLS_GROUP_ENTRY("B-233", "sect233r1", "EC", 6), /* Alias of above */
 #  endif
 #  ifndef FIPS_MODULE
     TLS_GROUP_ENTRY("sect239k1", "sect239k1", "EC", 7),
 #  endif
 #  ifndef OPENSSL_NO_EC2M
     TLS_GROUP_ENTRY("sect283k1", "sect283k1", "EC", 8),
     TLS_GROUP_ENTRY("K-283", "sect283k1", "EC", 8), /* Alias of above */
     TLS_GROUP_ENTRY("sect283r1", "sect283r1", "EC", 9),
     TLS_GROUP_ENTRY("B-283", "sect283r1", "EC", 9), /* Alias of above */
     TLS_GROUP_ENTRY("sect409k1", "sect409k1", "EC", 10),
     TLS_GROUP_ENTRY("K-409", "sect409k1", "EC", 10), /* Alias of above */
     TLS_GROUP_ENTRY("sect409r1", "sect409r1", "EC", 11),
     TLS_GROUP_ENTRY("B-409", "sect409r1", "EC", 11), /* Alias of above */
     TLS_GROUP_ENTRY("sect571k1", "sect571k1", "EC", 12),
     TLS_GROUP_ENTRY("K-571", "sect571k1", "EC", 12), /* Alias of above */
     TLS_GROUP_ENTRY("sect571r1", "sect571r1", "EC", 13),
     TLS_GROUP_ENTRY("B-571", "sect571r1", "EC", 13), /* Alias of above */
 #  endif
 #  ifndef FIPS_MODULE
     TLS_GROUP_ENTRY("secp160k1", "secp160k1", "EC", 14),
     TLS_GROUP_ENTRY("secp160r1", "secp160r1", "EC", 15),
     TLS_GROUP_ENTRY("secp160r2", "secp160r2", "EC", 16),
     TLS_GROUP_ENTRY("secp192k1", "secp192k1", "EC", 17),
 #  endif
     TLS_GROUP_ENTRY("secp192r1", "prime192v1", "EC", 18),
     TLS_GROUP_ENTRY("P-192", "prime192v1", "EC", 18), /* Alias of above */
 #  ifndef FIPS_MODULE
     TLS_GROUP_ENTRY("secp224k1", "secp224k1", "EC", 19),
 #  endif
     TLS_GROUP_ENTRY("secp224r1", "secp224r1", "EC", 20),
     TLS_GROUP_ENTRY("P-224", "secp224r1", "EC", 20), /* Alias of above */
 #  ifndef FIPS_MODULE
     TLS_GROUP_ENTRY("secp256k1", "secp256k1", "EC", 21),
 #  endif
     TLS_GROUP_ENTRY("secp256r1", "prime256v1", "EC", 22),
     TLS_GROUP_ENTRY("P-256", "prime256v1", "EC", 22), /* Alias of above */
     TLS_GROUP_ENTRY("secp384r1", "secp384r1", "EC", 23),
     TLS_GROUP_ENTRY("P-384", "secp384r1", "EC", 23), /* Alias of above */
     TLS_GROUP_ENTRY("secp521r1", "secp521r1", "EC", 24),
     TLS_GROUP_ENTRY("P-521", "secp521r1", "EC", 24), /* Alias of above */
 #  ifndef FIPS_MODULE
     TLS_GROUP_ENTRY("brainpoolP256r1", "brainpoolP256r1", "EC", 25),
     TLS_GROUP_ENTRY("brainpoolP384r1", "brainpoolP384r1", "EC", 26),
     TLS_GROUP_ENTRY("brainpoolP512r1", "brainpoolP512r1", "EC", 27),
-#  endif
     TLS_GROUP_ENTRY("x25519", "X25519", "X25519", 28),
     TLS_GROUP_ENTRY("x448", "X448", "X448", 29),
-#  ifndef FIPS_MODULE
     TLS_GROUP_ENTRY("brainpoolP256r1tls13", "brainpoolP256r1", "EC", 30),
     TLS_GROUP_ENTRY("brainpoolP384r1tls13", "brainpoolP384r1", "EC", 31),
     TLS_GROUP_ENTRY("brainpoolP512r1tls13", "brainpoolP512r1", "EC", 32),
 #  endif
 # endif /* OPENSSL_NO_EC */
 # ifndef OPENSSL_NO_DH
     /* Security bit values for FFDHE groups are as per RFC 7919 */
     TLS_GROUP_ENTRY("ffdhe2048", "ffdhe2048", "DH", 33),
     TLS_GROUP_ENTRY("ffdhe3072", "ffdhe3072", "DH", 34),
     TLS_GROUP_ENTRY("ffdhe4096", "ffdhe4096", "DH", 35),
     TLS_GROUP_ENTRY("ffdhe6144", "ffdhe6144", "DH", 36),
     TLS_GROUP_ENTRY("ffdhe8192", "ffdhe8192", "DH", 37),
 # endif
 };
 #endif /* !defined(OPENSSL_NO_EC) || !defined(OPENSSL_NO_DH) */
```

**Comment by t8m** [comment]
> In `providers/common/capabilities.c` do we also need to exclude X25519 from param_group_list? Is that list being used for key-exchange / TLS?

Yeah, this is a good point. It should be excluded. I'll adjust the PR.

**Comment by t8m** [comment]
Hmm... this will require some testcase adjustments...

**Review by nhorman — APPROVED** [review]

**Review by paulidale — APPROVED** [review]

**Review by xnox — APPROVED** [review]

**Comment by paulidale** [comment]
Please close these after merging.....

**Comment by t8m** [comment]
> Please close these after merging.....

I close PRs after merging but sometimes it happens that I forget.

**Pull request closed without merging**
