### PR TITLE
Re-enable CMP test for AIX, but remove tests which are not consistent across all platforms

### PR DESCRIPTION
**Pull request by jon-oracle**
I've removed some tests which simulate a write to a directory by using a path ending in '/' as this is not compatible with fopen() on all platforms. On AIX the trailing '/' is removed and the path opened as a file.

- [X] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Well that failed pretty well :)

**Comment by slontis** [comment]
@paulidale - any ideas what this means?

**Comment by jon-oracle** [comment]
> @paulidale - any ideas what this means?

Looks like a bad merge of libcrypto.num, with duplicate numbering

**Comment by slontis** [comment]
@DDvO are you ok with this..

**Comment by slontis** [comment]
FYI @t-j-h

**Review by DDvO — APPROVED** [review]
I'm absolutely fine with this.
Good to remove those test cases in favor of platform independence; they are not essential at all.

**Review by slontis — APPROVED** [review]

**Comment by DDvO** [comment]
Merged - thanks @jon-oracle for the contribution..

**Pull request closed without merging**
