### PR TITLE
Check return of PEM_write_* functions and report possible errors

### PR DESCRIPTION
**Pull request by levitte**
In response to issue #905.

### CODE REVIEW

**Comment by mattcaswell** [comment]
+1

**Comment by levitte** [comment]
Merged

**Comment by richsalz** [comment]
Did the OP say this fixed their problem?

**Comment by levitte** [comment]
I meant to cherry-pick this to 1.0.2 as well.  @mattcaswell ?

**Comment by mattcaswell** [comment]
Yes, +1 for 1.0.2 too.

**Comment by levitte** [comment]
Done

**Pull request closed without merging**
