### PR TITLE
include/openssl/macros.h: better OPENSSL_FUNC fallback

### PR DESCRIPTION
**Pull request by levitte**
Make sure OPENSSL_FUNC gets defined to something, no matter what.

### CODE REVIEW

**Review by slontis — APPROVED** [review]
I do wonder what path it was hitting before..

**Review by paulidale — APPROVED** [review]
Looks good.

**Comment by paulidale** [comment]
I'm guessing that `__STDC_VERSION__` was defined but it was not late enough and it wasn't a GCC build.

**Comment by levitte** [comment]
Yeah, that was my conclusion too

**Comment by slontis** [comment]
It looks like certain compiler flags also turn it off..

**Comment by levitte** [comment]
Merged.

15dbf3a5a1ec27315753ef5a9148f6ad69277909 include/openssl/macros.h: better OPENSSL_FUNC fallback

**Pull request closed without merging**
