### PR TITLE
Make it possible for external code to flag a certificate as a proxy one.

### PR DESCRIPTION
**Pull request by levitte**

### CODE REVIEW

**Comment by levitte** [comment]
Together with #1294, grid folks should be pretty much covered by this.

**Comment by richsalz** [comment]
doc?  +1 assuming you fix that.

**Comment by levitte** [comment]
Fix what?  You lost me there...

**Comment by levitte** [comment]
Speaking of docs, someone should document `X509_check_purpose`...  I'm not sure I'm catching all the details to do it properly...

**Comment by levitte** [comment]
Documented, and fixed a related bug (proxy path length not properly initialised)

**Comment by richsalz** [comment]
Fix by documenting your new functions, I meant.
+1

**Comment by levitte** [comment]
Merged, thanks.

**Pull request closed without merging**
