### PR TITLE
CMP CLI-based tests: small extensions and improvements

### PR DESCRIPTION
**Pull request by DDvO**
This extends and tweaks some of the test cases in `80-test_cmp_http_data/*.csv`:

* `test_commands.csv`: improve test for `-reqin`, adding `-reqin_new_tid`
* `test_verification.csv`: add missing test case for `-untrusted` with non-matching cert
* `test_enrollment.csv`: clean up test cases regarding (non-existing) directories,
   which improves #15575.

- [x] tests are added or updated

### CODE REVIEW

**Comment by DDvO** [comment]
BTW, I am missing a label called, e.g., **triaged: test**.

**Review by paulidale — APPROVED** [review]

**Comment by t8m** [comment]
Adding a new test is a feature. :grin:

**Review by t8m — APPROVED** [review]

**Comment by DDvO** [comment]
> Adding a new test or improvement (not a bug fix) of existing one are features. :grin:

This makes some sense, but the same could have been said for **triaged: documentation**.
Addressing a test directly would be more precise,
and then the template given when opening a PR would become obsolete:
```
- [x] documentation is added or updated
- [ ] tests are added or updated
```

**Comment by t8m** [comment]
> the template given when opening a PR would become obsolete:

it would not as external contributors cannot set labels

**Comment by DDvO** [comment]
> > the template given when opening a PR would become obsolete:
> 
> it would not as external contributors cannot set labels

True.

Still **triaged: test** may make sense, and even **issue: test**,
for differentiation from productive actual (library/app) features.

**Comment by DDvO** [comment]
Merged - thanks @paulidale and @t8m

**Pull request closed without merging**
