### PR TITLE
Fix undefined behavior in crypto/cms/cms_lib.c

### PR DESCRIPTION
**Pull request by pbmedved**
Add check for null pointer to prevent segmentation fault.

### CODE REVIEW

**Comment by bernd-edlinger** [comment]
IMHO this looks like the error is elsewhere.

**Comment by kroeckx** [comment]
If the intention is to just return an error, which seems to be the effect of the change, I would prefer something like: if (cms == NULL) return NULL;

**Comment by mspncp** [comment]
@pbmedved is it possible for you to provide a call stack of the original crash? I slightly lean towards @bernd-edlinger‘s opinion that the problem might need to be addressed further down the stack.

**Comment by pbmedved** [comment]
@mspncp, I can transfer the check to:
CMS_CertificateChoices * CMS_add0_CertificateChoices (CMS_ContentInfo * cms)
CMS_CertificateChoices * CMS_add0_CertificateChoices (CMS_ContentInfo * cms)
STACK_OF (X509) * CMS_get1_certs (CMS_ContentInfo * cms)

```
Program received signal SIGSEGV, Segmentation fault.
0xb6a90b84 in CMS_get1_certs (cms=0x0) at crypto/cms/cms_lib.c:485
485         pcerts = cms_get0_certificate_choices(cms);
(gdb) bt
#0  0xb6a90b84 in CMS_get1_certs (cms=0x0) at crypto/cms/cms_lib.c:485
#1 my external lib
```

**Comment by t8m** [comment]
We do not have such checks spread throughout the library. Some of the calls explicitly check for the NULL parameters, some expect the caller to not invoke them with NULL parameter. IMO we do not want to add such checks randomly, especially not in 1.1.1.

**Comment by pbmedved** [comment]
OK, got it.
If i add tests and based on their results fix it in right places. Then can
we merge this?
вторник, 28 декабря 2021 г. пользователь Tomáš Mráz <
***@***.***> написал:

**Comment by bernd-edlinger** [comment]
@pbmedved did you consider creating a bug report against the external lib calling the
`CMS_get1_certs()` function with the invalid parameters?

**Comment by pbmedved** [comment]
@bernd-edlinger yes, I'm also gonna fix it in external lib.

**Pull request closed without merging**
