### PR TITLE
Use libctx when generating DH parameters

### PR DESCRIPTION
**Pull request by t8m**
We did not use libctx when generating the safe prime DH parameters.

It needs to be passed via BN_CTX.

### CODE REVIEW

**Review by beldmit — APPROVED** [review]
LGTM

**Review by mattcaswell — APPROVED** [review]

**Comment by mattcaswell** [comment]
Should there be a test for this?

**Comment by t8m** [comment]
> Should there be a test for this?

Not sure how to test this easily. Also the safe prime generator is very slow so we do not currently test it at all AFAIK.

**Comment by mattcaswell** [comment]
> Not sure how to test this easily.

Surely this is just load the null provider into the default libctx, and try and generate some DH params using a non-default libctx.

> Also the safe prime generator is very slow so we do not currently test it at all AFAIK.

Slowness could be a big issue. Maybe we should have a "make extended-tests" or something for such slow things we don't want to be running all the time. They could be run on a scheduled basis by CI.

**Comment by t8m** [comment]
Hmm... with 512 bits the safe prime generation is quick enough to not be a problem so I've added a testcase that tests this fix.

**Comment by t8m** [comment]
@mattcaswell @beldmit please re-approve.

**Review by mattcaswell — APPROVED** [review]

**Comment by beldmit** [comment]
Hmmm... does the test run in FIPS mode?

**Comment by t8m** [comment]
> Hmmm... does the test run in FIPS mode?

The evp_extra_test2 is not being executed with only the FIPS provider loaded.

**Comment by beldmit** [comment]
Thanks, my approval remains

**Review by slontis — COMMENTED** [review]
Why this one in particular.?
Without looking too far I can find  another one..
e.g: DH_check() does a prime test (which will create rands),

**Comment by t8m** [comment]
> Why this one in particular.? Without looking too far I can find another one.. e.g: DH_check() does a prime test (which will create rands),

Because I've noticed it. I did not do exhaustive search. And yeah, all these should be fixed but that can be in a separate PR.

**Comment by t8m** [comment]
Merged to master, 3.1, and 3.0 branches. Thank you for the reviews.

**Comment by t8m** [comment]
Followup in #19656

**Pull request closed without merging**
