### PR TITLE
Rename OPT_PROV_xxx to OPT_P_xxx

### PR DESCRIPTION
**Pull request by richsalz**
Consistency is important :)

### CODE REVIEW

**Comment by slontis** [comment]
Final Alpha has been released.. I think the time for this type of change has passed.

**Comment by h-vetinari** [comment]
> Final Alpha has been released

"final alpha" is a completely self-imposed and IMO contradictory concept - the stability promise begins with the beta1 (otherwise the "final alpha" effectively becomes beta1, no?).

Changes that would sufficiently improve 3.0.0 before it is frozen for years and years should still get a fair hearing IMO (not making a claim about this PR specifically re:"sufficiently", though I agree that consistency is indeed important).

**Comment by richsalz** [comment]
This changes *no* public API.

**Comment by mattcaswell** [comment]
> "final alpha" is a completely self-imposed and IMO contradictory concept - the stability promise begins with the beta1 (otherwise the "final alpha" effectively becomes beta1, no?).
>
> It's understandable to draw a line and say "no features beyond this point", and winding down the permissible impact before beta. I'm just saying that the actual freeze begins with beta, and any change before that should still be evaluated on its impact-vs-merits (not making a claim about this PR specifically, though I agree that consistency is indeed important).

Entirely correct. "beta1" is the actual freeze point. I would not be expecting significant new features at this point. We should be aiming for some stability. But we *can* still make API changes.

**Comment by mattcaswell** [comment]
Although of course this not an API or behavioural change. Its a refactor - which is also ok.

**Review by t8m — APPROVED** [review]

**Comment by richsalz** [comment]
Rebased to fix conflicts in three commands (spkac crl ca)

**Comment by paulidale** [comment]
I'd prefer the other names to be changed.  OPT_R_ isn't as meaningful as OPT_RAND_.

Yes, I have forgotten what OPT_R_ stood for and had to go look it up.

**Comment by t8m** [comment]
At this point this is IMO Post 3.0

**Comment by richsalz** [comment]
I don't see why it is post-3.0 it is purely internal.  It would be like changing a build file or a `xxx_local.h` header.
I think the project does not appreciate how important consistency is to the casual/downstream user.

**Pull request closed without merging**
