### PR TITLE
1_1_1-stable: Detect arm64-*-*bsd and enable assembly optimizations

### PR DESCRIPTION
**Pull request by allanjude**
CLA: trivial

### CODE REVIEW

**Comment by t8m** [comment]
I am not sure this is acceptable with CLA: trivial. Would you please consider signing a regular CLA? https://www.openssl.org/policies/cla.html

I suppose this is acceptable into 1.1.1 as this is just a new platform configuration.

**Review by beldmit — APPROVED** [review]
LGTM

**Review by paulidale — COMMENTED** [review]
Definitely not trivial.

**Review by paulidale — COMMENTED** [review]
As only additions, this would be acceptable for back port.

We will require the platform to be on the community supported list however.

**Comment by allanjude** [comment]
CLA was signed back in November.

**Review by paulidale — APPROVED** [review]

**Review by beldmit — APPROVED** [review]
LGTM

**Comment by t8m** [comment]
This needs to be rebased to resolve conflicts.

**Comment by allanjude** [comment]
> This needs to be rebased to resolve conflicts.

Rebased around the bsd-riscv conflict

**Comment by beldmit** [comment]
Still approved

**Review by paulidale — APPROVED** [review]
Still good.

**Review by t8m — APPROVED** [review]

**Pull request closed without merging**
