### PR TITLE
Windows CI: Enable fuzz test in plain build and fix hang in asn1parse fuzzer

### LINKED ISSUE #15682: Windows builds hang in test_fuzz_asn1parse after BIO_write_ex() return value change
As demonstrated in the Windows CI minimal build failures in #15672 there is a regression from the return value change in BIO_write_ex() 5d43bfa7d58c6af5e40d6615edc83c709df2852b. The test_fuzz_asn1parse hangs. It is unclear why this change affects only Windows.

### PR DESCRIPTION
**Pull request by t8m**
Fixes #15682

### CODE REVIEW

**Comment by t8m** [comment]
@DDvO:

So I had to partially revert the 5d43bfa to make the test_fuzz_asn1parse pass, otherwise it got stuck (on Windows only). This should be investigated by someone who has a Windows build environment.

**Comment by DDvO** [comment]
> So I had to partially revert the [5d43bfa](https://github.com/openssl/openssl/commit/5d43bfa7d58c6af5e40d6615edc83c709df2852b) to make the test_fuzz_asn1parse pass, otherwise it got stuck (on Windows only).

Hmm, to me it looks like your new version is equivalent, and I would be fine with keeping it
(though requiring some more lines) since it also solves the objective of #15608.

> This should be investigated by someone who has a Windows build environment.

I don't have one handy.

**Comment by t8m** [comment]
Unfortunately no, the last commit adds the `#if 0 #endif` and basically reverts all the BIO_write_ex changes. Without it the test_fuzz_asn1parse still hangs.

**Comment by slontis** [comment]
Doesn't this kind of defeat the purpose of a minimal build? This would be better of in another longer running windows build?

**Comment by t8m** [comment]
> Doesn't this kind of defeat the purpose of a minimal build? This would be better of in another longer running windows build?

Makes sense, I can add it to the plain build instead. The shared builds take too long time already.

**Comment by t8m** [comment]
@mspncp I know you're doing development on Windows, would you be willing to investigate the hang in test_fuzz_asn1parse?

**Comment by DDvO** [comment]
> > Doesn't this kind of defeat the purpose of a minimal build? This would be better of in another longer running windows build?
> 
> Makes sense, I can add it to the plain build instead. The shared builds take too long time already.

I don't think that it is an aim for a minimal build  to to run for only a short time, 
but to make sure that disabling as many features as possible does not lead to inconsistencies.
Nevertheless I suppose that a fuzz test should run with as many features as enabled as possible, 
which calls for running it on non-minimal build.

**Comment by t8m** [comment]
This is now ready for review.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Assuming the wording nit is done.

**Comment by t8m** [comment]
Fixup pushed. @paulidale Do you agree with severity: urgent? The failure is AppVeyor only currently though.

**Comment by paulidale** [comment]
I'm okay with urgent.

**Comment by t8m** [comment]
Merged to master. Thank you for the review!

**Comment by DDvO** [comment]
Glad that the issue with `fuzz/asn1parse.c` is solved.
I wonder why the changes to `BIO_write_ex()` were still needed then?
It seems that now `b == NULL` is forbidden.

**Comment by t8m** [comment]
> It seems that now `b == NULL` is forbidden.

Yes, and that is intentional. The problem is that writing to NULL returning 0 bytes in *written is incorrect and can lead to infinite loops in applications. So we do not want this change in semantics.

**Comment by DDvO** [comment]
> > It seems that now `b == NULL` is forbidden.
> 
> Yes, and that is intentional. The problem is that writing to NULL returning 0 bytes in *written is incorrect and can lead to infinite loops in applications. So we do not want this change in semantics.

Thanks for the explanation.
I see the risk in loops, though I would not say this is incorrect 
because it is a matter of definition what `*written` means in case `b == NULL`.
An infinite loop could still be avoided by checking `b == NULL`, 
and I would say if so far there was any call with `b == NULL` this was a bug in the call.
Nevertheless, since also @levitte did not like allowing `b == NULL` and its use is not important I'm fine with not having it.

**Comment by DDvO** [comment]
And why did the infinite loop only occur with Windows?
If it is because `BIO_new_file("/dev/null", "w");` fails on Windows,
I'd say this call should not have been done on Windows at all.

**Comment by t8m** [comment]
> And why did the infinite loop only occur with Windows?
> If it is because `BIO_new_file("/dev/null", "w");` fails on Windows,
> I'd say this call should not have been done on Windows at all.

Yes, but given this is just a test, I do not think it is worth the hassle adding some ifdefs.

**Comment by DDvO** [comment]
Well, cleanly coding this would have prevented the hard-to-analyze hang of the Windows CI fuzz tests.

**Comment by DDvO** [comment]
Allowing NULL BIO input or not is not a bug, bug a design decision.
Yet there were - and even after this PR still are - even two bugs in `fuzz/asn1parse.c`:
* `bio_out = BIO_new_file("/dev/null", "w");` does not make sense on non-UNIX-like systems
* Failure is not checked, not even for the new fallback: `bio_out = BIO_new(BIO_s_mem());` 

The real fix for issue #15682 is now in #15722.

**Comment by DDvO** [comment]
Closer code inspection reveals more bugs.
* `BIO_dump_indent_cb()` goes wrong if its `cb` returns an error - now also fixed by #15722.
* Here is the worst one in my view: 
   For Windows, before this PR `bio_out` happened to be NULL,
  which lead to `ASN1_parse_dump()` fail prematurely and silently, 
  **which defeated the purpose of `fuzz/asn1parse.c`** on Windows.

**Comment by t8m** [comment]
> Allowing NULL BIO input is a design decision

It is a design decision that was taken long ago when the API was added. We should not change it now.

**Comment by DDvO** [comment]
Where in `ASN1_parse_dump()` or its callees is the issue with `BIO_write_ex()` and NULL BIO input?
I only found calls to `BIO_write()`, which cannot have caused this issue.
BTW, much of the BIO code appears is a bit unclean.

**Comment by t8m** [comment]
It's where the BIO_f_prefix() is pushed onto the NULL bio. The prefix filter then uses BIO_write_ex() on the NULL next bio.

**Pull request closed without merging**
