### PR TITLE
Convert dhparam so that it no longer needs low level APIs

### PR DESCRIPTION
**Pull request by mattcaswell**
This converts the dhparam app so that it no longer needs to use any low level APIs, as well as adding a test to check that the behaviour is consistent with historic behaviour.

It does not address the issue that stdin does not currently work with the app (as described in issue #13185).

It is marked as pending because it requires the commits from #13228. Those commits are not included in this PR to ease review, but this means that the new test will fail.

I've also added an OMC hold on this because, in accordance with the recent OTC decision the "-C" option has been removed. However that decision needs OMC ratification.

Note that I developed and tested the new test in the 1.1.1 branch first. However I had to change it to get it to work in master because of subtle differences in the way the "-text" output works between the two versions (as per issue #13220).

### CODE REVIEW

**Comment by mattcaswell** [comment]
Now that #13228 has gone in I have taken this out of WIP and rebased it to resolve conflicts with master.

I have also removed the commits that dealt with removing the "-C" option since that was already handled by #13384. The OMC hold that was on this PR was related to that part of the change so I've also removed the hold.

This is now ready for review. Please take a look.

**Comment by mattcaswell** [comment]
Ping?

**Comment by mattcaswell** [comment]
Hmm. Travis failure - fixup pushed. I definitely already did that same fixup yesterday - but somehow I lost it.

**Review by paulidale — APPROVED** [review]

**Comment by mattcaswell** [comment]
Fixup pushed to address a travis failure. @paulidale - please can you reconfirm?

**Review by paulidale — APPROVED** [review]
Still good.

**Comment by mattcaswell** [comment]
Pushed. Thanks.

**Pull request closed without merging**
