### PR TITLE
Fix EC_POINT_bn2point() for BN_zero()

### LINKED ISSUE #10258: `EC_POINT_hex2point` incorrectly decodes the point at infinity
`EC_POINT_hex2point` incorrectly decodes the point at infinity, which is encoded as the hexstring `00`. This is because `hex2point` calls `oct2point` after converting `00` into a `BIGNUM` and calling `BN_bn2bin` on this bignum, which outputs 0 bytes whereas the decoder is expecting exactly `1` `0` byte in this case.

### PR DESCRIPTION
**Pull request by romen**
# Fix `EC_POINT_bn2point()` for `BN_zero()`

`EC_POINT_bn2point()` rejected `BIGNUM`s with a zero value.

This behavior indirectly caused failures when converting a point
at infinity through `EC_POINT_point2hex()` and then back to a point with
`EC_POINT_hex2point()`.

With this change such `BIGNUM`s are treated like any other and exported to
an octet buffer filled with zero.
It is then `EC_POINT_oct2point()` (either the default implementation or
the custom one in `group->meth->oct2point`) to determine if such encoding
maps to a valid point (generally the point at infinity is encoded as
`0x00`).

Fixes #10258

# Add self-test for `EC_POINT_hex2point()`

Adds tests for each curve to ensure that encodings obtained through
`EC_POINT_hex2point()` can be fed to `EC_POINT_point2hex()` yielding a point
identical to the one from which the encoding is generated.

##### Checklist
- [x] documentation added
- [x] tests are added or updated

### CODE REVIEW

**Comment by slontis** [comment]
Does this need a CHANGES entry? (I dont know the answer)

**Comment by romen** [comment]
> Does this need a CHANGES entry? (I dont know the answer)

I am not sure either, but gravitating toward a "probably not" answer.

Maybe the OMC reviewer can give feedback on it. (ping @mattcaswell )

I am currently looking into #10366 which is somehow related, but I am still undecided if that should have an impact on this PR or not.

**Comment by mattcaswell** [comment]
> Does this need a CHANGES entry? (I dont know the answer)

I'd say probably not. However perhaps the man page should be updated with something about what happens with points at infinity?

Other than that this PR looks good.

**Comment by romen** [comment]
> > Does this need a CHANGES entry? (I dont know the answer)
> 
> I'd say probably not. However perhaps the man page should be updated with something about what happens with points at infinity?
> 
> Other than that this PR looks good.

Ultimately it's each `EC_METHOD` responsibility to decide what is an acceptable representation of any point, including point at infinity, through the `point2oct` and `oct2point` pointers.
I believe all of the currently included implementations translate `Pinf -> \0\0 -> Pinf`, but can we really document something specific?

**Comment by mattcaswell** [comment]
> Ultimately it's each EC_METHOD responsibility to decide what is an acceptable representation of any point, including point at infinity, through the point2oct and oct2point pointers.

Surely, if an application calls `EC_POINT_bn2point()` then it is going to expect to always get the same result for a given point, regardless of which EC_METHOD happened to have been chosen? Similarly it should not matter which GFp curve you use they should all behave consistently with each other. And all GF2m curves should also be consistent with each other.

**Comment by romen** [comment]
@mattcaswell do you think the added lines clarify things enough?

**Comment by romen** [comment]
Merged to `master` with:
- d47c108756 Fix EC_POINT_bn2point() for BN_zero()
- 35ed029b5a Add self-test for EC_POINT_hex2point
- 3cc26f2eba Extend docs for EC_POINT conversion functions

Merged to `1.1.1` with:
- 6f6adf1d7b Fix EC_POINT_bn2point() for BN_zero()
- f59967cb72 Add self-test for EC_POINT_hex2point _(trivial changes on cherry-picking)_
- 3c25ac2d2e Extend docs for EC_POINT conversion functions

Thanks!

**Pull request closed without merging**
