### PR TITLE
On NonStop platform the EXIT_FAILURE is -1 truncated to 255

### LINKED ISSUE #15633: 15-test_rsapss.t fails on NonStop ia64 and x86
As of commit 97cf9b05fa, rsapss continues to fail on NonStop ia64. This was not the case at the base alpha17 but appeared after commit 036f8e71e3.
```
15-test_rsapss.t ................... 1/?
Error signing data
00000000:error:0200006E:rsa routines:RSA_padding_add_PKCS1_PSS_mgf1:data too large for key size:/home/git/openssl-3.0/crypto/rsa/rsa_pss.c:193:
00000000:error:1C880004:Provider routines:rsa_sign:RSA lib:/home/git/openssl-3.0/providers/implementations/signature/rsa_sig.c:608:
../../util/wrap.pl ../../apps/openssl dgst -sign ../../test/testrsa.pem -sha512 -sigopt 'rsa_padding_mode:pss' -sigopt 'rsa_pss_saltlen:max' -sigopt 'rsa_mgf1_md:sha512' ../../test/testrsa.pem => 255
not ok 3 - openssl dgst -sign, expect to fail gracefully
# ------------------------------------------------------------------------------
#   Failed test 'openssl dgst -sign, expect to fail gracefully'
#   at test/recipes/15-test_rsapss.t line 37.
Error signing data
00000000:error:0200006E:rsa routines:RSA_padding_add_PKCS1_PSS_mgf1:data too large for key size:/home/git/openssl-3.0/crypto/rsa/rsa_pss.c:193:
00000000:error:1C880004:Provider routines:rsa_sign:RSA lib:/home/git/openssl-3.0/providers/implementations/signature/rsa_sig.c:608:
../../util/wrap.pl ../../apps/openssl dgst -sign ../../test/testrsa.pem -sha512 -sigopt 'rsa_padding_mode:pss' -sigopt 'rsa_pss_saltlen:2147483647' -sigopt 'rsa_mgf1_md:sha1' ../../test/testrsa.pem => 255
not ok 4 - openssl dgst -sign, expect to fail gracefully
15-test_rsapss.t ................... 4/? ---------------------------------------
#   Failed test 'openssl dgst -sign, expect to fail gracefully'
#   at test/recipes/15-test_rsapss.t line 41.
Error opening signature file testrsapss.sig
00000000:error:80000FA2:system library:BIO_new_file:No such file or directory:/home/git/openssl-3.0/crypto/bio/bss_file.c:67:calling fopen(testrsapss.sig, rb)
00000000:error:10000080:BIO routines:BIO_new_file:no such file:/home/git/openssl-3.0/crypto/bio/bss_file.c:75:
../../util/wrap.pl ../../apps/openssl dgst -prverify ../../test/testrsa.pem -sha512 -sigopt 'rsa_padding_mode:pss' -sigopt 'rsa_pss_saltlen:max' -sigopt 'rsa_mgf1_md:sha512' -signature testrsapss.sig ../../test/testrsa.pem => 255
not ok 5 - openssl dgst -prverify, expect to fail gracefully
15-test_rsapss.t ................... 6/? ---------------------------------------
15-test_rsapss.t ................... Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/7 subtests
```

### PR DESCRIPTION
**Pull request by t8m**
Fixes #15633

##### Checklist

- [x] tests are added or updated

### CODE REVIEW

**Comment by levitte** [comment]
Another method that's much more platform independent is to drop the exit_checker thing and do this for graceful failure:

``` perl
ok(!run(...), title);
```

This works because the default exit_checker checks for EXIT_SUCCESS (always zero on all platforms I know).

**Comment by t8m** [comment]
> Another method that's much more platform independent is to drop the exit_checker thing and do this for graceful failure:

This would not check for a crash. But yeah, we do not do that in other tests for failures either. I'll do a fixup.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Seems like the exit_checker just shouldn't be used.

**Review by levitte — APPROVED** [review]

**Comment by levitte** [comment]
> Seems like the exit_checker just shouldn't be used.

It *is* quite special, and should be used with caution.

**Comment by t8m** [comment]
Could we have a standard run_fail() function that would return success if the exit value is 1-127 or 255 (to cover the NonStop)? And use that instead of !run()? Unfortunately this is outside of my perl fu to add that.

**Comment by levitte** [comment]
You can't assume that all platforms format their non-zero exit code the same way as on Unix.  The use of 2^7 as the this-is-a-signal-not-an-exit-code is Unix specific.  The only code the all platforms seem to agree on is that zero means success.

**Comment by t8m** [comment]
> You can't assume that all platforms format their non-zero exit code the same way as on Unix. The use of 2^7 as the this-is-a-signal-not-an-exit-code is Unix specific. The only code the all platforms seem to agree on is that zero means success.

We could make that platform-specific and start with just Unix platforms (including NonStop?) having the 1-127 or 255. For the rest we would use the != 0 check. It would not really matter whether the run_fail() detects the crashes perfectly everywhere but !run() cannot detect them anywhere.

**Comment by levitte** [comment]
What would `run_fail` return?  Most specifically, what would it return for a "crash" (i.e. exit codes with 2^7 set)?  Doesn't that make for very specialised use?

It sounds like it would be better to think of crashes as an out of band exception, i.e. detect them and use perl's `die` or some similar mechanism.  Whatever we choose to do, be prepared for fairly ugly hackery, as Test::More isn't designed with this in mind, as far as I know (I may have missed something).

**Comment by levitte** [comment]
Anyway, the handling of crashes is outside of the scope of this PR, I'd say

**Comment by t8m** [comment]
> Anyway, the handling of crashes is outside of the scope of this PR, I'd say

I agree with that.

**Comment by rsbeckerca** [comment]
> 
> 
> You can't assume that all platforms format their non-zero exit code the same way as on Unix. The use of 2^7 as the this-is-a-signal-not-an-exit-code is Unix specific. The only code the all platforms seem to agree on is that zero means success.

NonStop does have the this-is-a-signal-not-an-exit-code convention. It's just that `EXIT_FAILURE` is `-1` (wrongly, but it's been that way since the mid-1990s so changing it is really unlikely).

**Comment by rsbeckerca** [comment]
I am running a build/test cycle on NonStop for this PR as of commit fd2a7b089a

**Comment by rsbeckerca** [comment]
> 
> 
> I am running a build/test cycle on NonStop for this PR as of commit [fd2a7b0](https://github.com/openssl/openssl/commit/fd2a7b089a533537ad16ff96f6f5c5963b6a150d)

Works for me on NonStop ia64 and x86.

**Comment by paulidale** [comment]
Merged.

I'm a little surprised that Perl doesn't provide wrappers for the exit state.  `man 2 wait` lists statuses.  We could write a tiny C program that takes the exit code, runs it through the macros and returns a string or some such.

**Pull request closed without merging**
