### PR TITLE
set exec file attribute for scripts

### PR DESCRIPTION
**Pull request by vszakats**
(and adjust a really minor nit in tools/c_hash)

### CODE REVIEW

**Comment by richsalz** [comment]
+1
@levitte thoughts?

**Comment by levitte** [comment]
I'm not sure I understand the nit with `tools/c_hash`, and setting the exec bits on a `.pm` file (`util/with_fallback.pm`) is categorically wrong.

Also, I'm curious why this was deemed necessary...  would you care to elaborate, @vszakats ?

**Comment by vszakats** [comment]
The nit was just to sync the comment header with similar files next to it. Equal to whitespace change.
`.pm` file fixed, no more found with the same problem.

**Comment by levitte** [comment]
Also, I'm curious why this was deemed necessary... would you care to elaborate, @vszakats ?

**Comment by vszakats** [comment]
The whitespace thing? It's cosmetics, I'm removing it if that causes a problem.

**Comment by vszakats** [comment]
To elaborate, these files are supposed to be the belong to each other:
```
c_hash
c_info
c_issuer
c_name
```
All of those has the same comment at the top:
```
#!/bin/sh
#
# (text)
#
```

Except one:
```
#!/bin/sh
# print out the hash values
#
```

Note the missing first empty comment line.
So I added it to fit to the rest of the files.

Bad habit, I guess :(

**Comment by levitte** [comment]
Ah, no, that wasn't my question.  You've set the exec bit on a very large number of files.  Why did you think that was necessary?

**Comment by vszakats** [comment]
In my understanding those script files that feature a shebang are meant to be executed as scripts, and to make that work smoothly on systems that support an exec flag, it's best practice to set it. I could not derive the practice of OpenSSL in particular, because current state appears to be inconsistent in many places, suggesting that the exec flag settings are currently rather accidental than by design. But, I may be wrong in that of course.

**Comment by levitte** [comment]
> In my understanding those script files that feature a shebang are meant to be executed as scripts, and to make that work smoothly on systems that support an exec flag

Quite true in general.

> I could not derive the practice of OpenSSL in particular, because current state appears to be inconsistent in many places, suggesting that the exec flag settings are currently rather accidental than by design.

Welllll...  when building and testing, we almost exclusively use perl scripts, and call perl explicitely.  There are a few scripts in `util` that do have the exec bit for it.  Apart from that, the exec bit is sorted out explicitelly upon installation.

But ok, thanks for indulging.

**Comment by vszakats** [comment]
No worries! Everything considered, I think there a still quite a few scripts that are meant to be run standalone, where this patch could be useful, but then again, "meant to be run standalone" is quite an ambiguous distinction, so why not set the exec flag uniformly for all? I think it'd be nice.

**Pull request closed without merging**
