### PR TITLE
der: _ossl prefix DER functions

### PR DESCRIPTION
**Pull request by paulidale**
Functions renamed are:
```
der_aid_sha224Identifier, der_aid_sha256Identifier, der_aid_sha384Identifier, der_aid_sha512Identifier,
der_aid_sha512_224Identifier, der_aid_sha512_256Identifier, der_oid_c2onb191v4, der_oid_c2onb191v5, der_oid_c2onb239v4,
der_oid_c2onb239v5, der_oid_c2pnb163v1, der_oid_c2pnb163v2, der_oid_c2pnb163v3, der_oid_c2pnb176w1, der_oid_c2pnb208w1,
der_oid_c2pnb272w1, der_oid_c2pnb304w1, der_oid_c2pnb368w1, der_oid_c2tnb191v1, der_oid_c2tnb191v2, der_oid_c2tnb191v3,
der_oid_c2tnb239v1, der_oid_c2tnb239v2, der_oid_c2tnb239v3, der_oid_c2tnb359v1, der_oid_c2tnb431r1, der_oid_hashAlgs,
der_oid_id_Ed25519, der_oid_id_Ed448, der_oid_id_KMACWithSHAKE128, der_oid_id_KMACWithSHAKE256, der_oid_id_RSAES_OAEP,
der_oid_id_RSASSA_PSS, der_oid_id_X25519, der_oid_id_X448, der_oid_id_aes128_wrap, der_oid_id_aes192_wrap, der_oid_id_aes256_wrap,
der_oid_id_alg_CMS3DESwrap, der_oid_id_dsa, der_oid_id_dsa_with_sha1, der_oid_id_dsa_with_sha224, der_oid_id_dsa_with_sha256,
der_oid_id_dsa_with_sha384, der_oid_id_dsa_with_sha3_224, der_oid_id_dsa_with_sha3_256, der_oid_id_dsa_with_sha3_384,
der_oid_id_dsa_with_sha3_512, der_oid_id_dsa_with_sha512, der_oid_id_ecPublicKey, der_oid_id_ecdsa_with_sha3_224,
der_oid_id_ecdsa_with_sha3_256, der_oid_id_ecdsa_with_sha3_384, der_oid_id_ecdsa_with_sha3_512, der_oid_id_md2, der_oid_id_md5,
der_oid_id_mgf1, der_oid_id_pSpecified, der_oid_id_rsassa_pkcs1_v1_5_with_sha3_224, der_oid_id_rsassa_pkcs1_v1_5_with_sha3_256,
der_oid_id_rsassa_pkcs1_v1_5_with_sha3_384, der_oid_id_rsassa_pkcs1_v1_5_with_sha3_512, der_oid_id_sha1, der_oid_id_sha224,
der_oid_id_sha256, der_oid_id_sha384, der_oid_id_sha3_224, der_oid_id_sha3_256, der_oid_id_sha3_384, der_oid_id_sha3_512,
der_oid_id_sha512, der_oid_id_sha512_224, der_oid_id_sha512_256, der_oid_id_shake128, der_oid_id_shake128_len,
der_oid_id_shake256, der_oid_id_shake256_len, der_oid_md2WithRSAEncryption, der_oid_md4WithRSAEncryption,
der_oid_md5WithRSAEncryption, der_oid_prime192v1, der_oid_prime192v2, der_oid_prime192v3, der_oid_prime239v1,
der_oid_prime239v2, der_oid_prime239v3, der_oid_prime256v1, der_oid_ripemd160WithRSAEncryption, der_oid_rsaEncryption,
der_oid_sha1WithRSAEncryption, der_oid_sha224WithRSAEncryption, der_oid_sha256WithRSAEncryption, der_oid_sha384WithRSAEncryption,
der_oid_sha512WithRSAEncryption, der_oid_sha512_224WithRSAEncryption, der_oid_sha512_256WithRSAEncryption, der_oid_sigAlgs,
der_to_obj_algorithm, decode_der_dsa_sig, decode_der_integer, decode_der_length, DER_w_RSASSA_PSS_params,
DER_w_algorithmIdentifier_DSA, DER_w_algorithmIdentifier_DSA_with_MD, DER_w_algorithmIdentifier_EC,
DER_w_algorithmIdentifier_ECDSA_with_MD, DER_w_algorithmIdentifier_ED25519, DER_w_algorithmIdentifier_ED448,
DER_w_algorithmIdentifier_MDWithRSAEncryption, DER_w_algorithmIdentifier_RSA, DER_w_algorithmIdentifier_X25519,
DER_w_algorithmIdentifier_X448, DER_w_begin_sequence, DER_w_bn, DER_w_boolean, DER_w_end_sequence, DER_w_null, DER_w_octet_string,
DER_w_octet_string_uint32, DER_w_precompiled and DER_w_ulong.

```
- [x] documentation is added or updated
- [x] tests are added or updated

### CODE REVIEW

**Review by levitte — COMMENTED** [review]
I believe that you have to touch these lines too:

https://github.com/openssl/openssl/blob/master/providers/common/der/oids_to_c.pm#L43

https://github.com/openssl/openssl/blob/master/providers/common/der/oids_to_c.pm#L61

**Comment by paulidale** [comment]
The `der_oid_` functions caused problems so I figured later.
The master list in #12964 still includes them.

**Comment by levitte** [comment]
Okie

**Comment by paulidale** [comment]
Turned out to be easy enough once the Perl was fixed.  Just some macro fixes on top.  Commit is in :)

Thanks for the script pointer - I was trying to find the macro that did the magic.

**Comment by levitte** [comment]
> Thanks for the script pointer

you're welcome

**Review by levitte — APPROVED** [review]

**Comment by paulidale** [comment]
Merged to master (a little early), thanks for the assistance with this one.

**Pull request closed without merging**
